const char* chap1 = "In the beginning God created heaven and earth.\n"
	"And the earth was void and vacant, and darkness was upon the face of the depth: and the Spirit of God moved over the waters.\n"
	"And God said: Be light made. And light was made.\n"
	"And God saw the light that it was good: and he divided the light from the darkness.\n"
	"And he called the light, Day, and the darkness, Night: and there was evening & morning, that made one day.\n"
	"God also said: Be a firmament made amidst the waters: and let it divide between waters and waters.\n"
	"And God made a firmament, and divided the waters that were under the firmament, from those that were above the firmament. And it was so done.\n"
	"And God called the firmament, Heaven: and there was evening & morning^ that made the second day.\n"
	"God also said: let the waters that are under heaven be gathered together into one place: and let the dry land appear. And it was so done.\n"
	"And God called the dry land, Earth, and the gathering of waters together, he called Seas. And God saw that it was good.\n"
	"And said: Let the earth shoot forth green herbs, and such as may seed, & fruit-trees yielding fruit after his kind, such as may have seed in itself upon the earth. And it was so done.\n"
	"And the earth brought forth green herb, such as seedeth according to his kind, and tree that beareth fruit, having seed each one according to his kind. And God saw that it was good.\n"
	"And there was evening and morning^ that made the third day.\n"
	"Again God said: Be there lights made in the firmament of heaven, to divide the day and the night, and let them be for signs & seasons, and days and years;\n"
	"to shine in the firmament of heaven, and to give light upon the earth. And it was so done.\n"
	"And God made two great lights; a greater light to govern the day, and a lesser light to govern the night; and stars.\n"
	"And he set them in the firmament of heaven, to shine upon the earth,\n"
	"and to govern the day & the night, and to divide the light and the darkness. And God saw that it was good.\n"
	"And there was evening and morning^ that made the fourth day.\n"
	"God also said: Let the waters bring forth creeping creature having life, and flying fowl, over the earth under the firmament of heaven.\n"
	"And God created huge whales, and all living and moving creature, that the waters brought forth according to each sort, and all fowl according to their kind. And God saw that it was good.\n"
	"And he blessed them saying: Increase and multiply, and replenish the waters of the sea: and let the birds be multiplied upon the earth.\n"
	"And there was evening and morning^ that made the fifth day.\n"
	"God said moreover: Let the earth bring forth living creature in his kind, cattle, and such as creep, and beasts of the earth according to their kinds: and it was so done.\n"
	"And God made the beasts of the earth according to their kinds, and cattle, and all that creepeth on the earth in his kind. And God saw that it was good,\n"
	"and he said Let us make Man to our image & likeness: and let him have dominion over the fishes of the sea, and the fowls of the air, and the beasts, and the whole earth, and all creeping creature that moveth upon the earth.\n"
	"And God created man to his own image: to the image of God he created him, male and female he created them.\n"
	"And God blessed them, and saith: Increase and multiply, and replenish the earth, and subdue it, and rule over the fishes and the sea, and fowls of the air & all living creatures that move upon the earth.\n"
	"And God said: Behold I have given you all manner of herb that seedeth upon the earth, and all trees that have in themselves seed of their own kind, to be your meat:\n"
	"and to all beasts of the earth, and to every fowl of the air, and to all that move upon the earth, and wherein there is life, that they may have to feed upon. And it was so done.\n"
	"And God saw all things that he had made, and they were very good. And there was evening and morning^ that made the sixth day.";