const char* chap100 = "And Nadab and Abiu the sons of Aaron catching censers, did put in fire, and incense thereupon, offering before our Lord strange fire, which was not commanded them.\n"
	"And fire coming forth from our Lord, devoured them, & they died before our Lord.\n"
	"And Moyses said to Aaron: This is it which our Lord hath spoken: I will be sanctified in them, that approach to me, and in the sight of all the people I will be glorified. Which Aaron hearing held his peace.\n"
	"And Moyses calling Misael and Elisaphan, the sons of Oziel, the uncle of Aaron, said to them: Go and take away your brethren from the sight of the Sanctuary, and carry them without the camp.\n"
	"And going forthwith they took them as they lay, revested with linen tunics, and did cast them forth, as it had been commanded them.\n"
	"And Moyses spake to Aaron, & to Eleazar, and Ithamar his sons: Uncover not your heads, and rent not your vestments, lest perhaps you die, & indignation come upon all the assembly. Let your brethren, & all the house of Israel, lament the burning that our Lord hath raised,\n"
	"and yourselves shall not go out of the door of the tabernacle, otherwise you shall perish: for the oil of holy unction is upon you. Who did all things according to the precept of Moyses.\n"
	"Our Lord also said to Aaron:\n"
	"Wine, and any thing that may make drunk, you shall not drink, thou and thy sons, when you enter into the tabernacle of testimony, lest you die: because it is an everlasting precept through your generations.\n"
	"And that you may have knowledge to discern between the holy and profane, between the polluted and clean:\n"
	"and may teach the children of Israel all my ordinances, which the Lord hath spoken to them by the hand of Moyses.\n"
	"And Moyses spake to Aaron and to Eleazar, and Ithamar his sons, that were left: Take the sacrifice, that is remaining of the oblation of our Lord, and eat it without leaven beside the altar, because it is Holy of holies.\n"
	"And you shall eat it in a holy place: which is given to thee and thy sons of the oblations of our Lord, as it hath been commanded me.\n"
	"The breast also that is offered, and the shoulder that is separated, you shall eat in a most clean place, thou and thy sons, and thy daughters with thee. For they are laid apart for thee and thy children, of the healthful hosts of the children of Israel:\n"
	"because the shoulder and the breast, and the fat that is burnt on the altar, they have elevated before our Lord, and they pertain to thee, and to thy sons by a perpetual law, as our Lord hath commanded.\n"
	"Among these things, when Moyses sought for the buck goat, that had been offered for sin, he found it burnt: and being angry against Eleazar, and Ithamar the sons of Aaron that remained, he said:\n"
	"Why did you not eat the host for sin, in a holy place, which is most Holy, and given to you, that you may bear the iniquity of the multitude, and may pray for it in the sight of our Lord,\n"
	"especially whereas of the blood thereof, there hath not been carried within the holy places, and you ought to have eaten it in the Sanctuary, as it was commanded me?\n"
	"Aaron answered: This day hath been offered the victim for sin, and the holocaust before our Lord: and to me that is chanced which thou seest, how could I eat it, or please our Lord in ceremonies having a sorrowful heart?\n"
	"Which when Moyses had heard, he was satisfied with his answer.";