const char* chap1000 = "These things hath our Lord God shewed to me: and lo the former of the locust in the beginning of things that spring of the later rain, and behold the later rain after the king's mowing.\n"
	"And it came to pass: after it had finished to eat the grass of the land, I said: O Lord God be propitious I beseech thee: who shall raise up Jacob, because he is a little one?\n"
	"Our Lord hath had pity upon this: It shall not be, saith our Lord.\n"
	"These things hath our Lord God called judgement unto fire, and it devoured the great depth and it did eat a part together.\n"
	"And I said: Lord God be quiet I beseech thee: who shall raise up Jacob, because he is a little one?\n"
	"Our Lord had pity upon this: Yea this also shall not be, saith our Lord God.\n"
	"These things hath our Lord shewed to me: and lo our Lord standing upon a wall plastered, and in his hand a mason's trowel.\n"
	"And our Lord said to me: What seest thou Amos? And I said: A mason's trowel. And our Lord said: Behold I will lay down the trowel in the midst of my people Israel: I will add no more to plaster it over.\n"
	"And the excelses of the idol shall be thrown down, and the sanctifications of Israel shall be made desolate: and I will rise upon the house of Jeroboam with the sword.\n"
	"And Amasias the Priest of Bethel sent to Jeroboam the king of Israel, saying: Amos hath rebelled against thee in the midst of the house of Israel: the land will not be able to sustain all his words.\n"
	"For thus saith Amos: Jeroboam shall die by the sword, and Israel shall depart captive out of their land.\n"
	"And Amasias said to Amos: Thou that seest, go, fly into the land of Juda: and eat bread there, and thou shalt prophesy there.\n"
	"And in Bethel thou shalt add no more to prophesy: because it is the sanctification of the king, and it is the house of the kingdom.\n"
	"And Amos answered, and said to Amasias: I am not a Prophet and I am not the son of a Prophet: but an herdsman am I plucking sycamores.\n"
	"And our Lord took me when I followed the flock, and our Lord said to me: Go, Prophesy to my people Israel.\n"
	"And now hear the word of our Lord: Thou sayest: Thou shalt not prophesy upon Israel, and thou shalt not distill upon the house of the idol.\n"
	"Therefore thus saith our Lord: Thy wife shall fornicate in the city, and thy sons, and thy daughters shall fall by the sword, and thy ground shall be measured with a cord, and thou shalt die in a polluted land, and Israel shall depart captive out of their land.";