const char* chap1001 = "These things hath our Lord shewed to me: and behold an apple hook.\n"
	"And he said: What seest thou Amos? And I said: An apple hook. And our Lord said to me: The end cometh upon my people Israel: I will add no more to pass them.\n"
	"And the hinges of the temple shall creak in that day, saith our Lord God: many shall die: in every place shall silence be cast.\n"
	"Hear this you that tread down the poor, & make the needy of the land to fail,\n"
	"saying: When will the month pass, and we shall sell wares: and the Sabbath, and we open the corn: that we may diminish the measure, and increase the sicle, and convey in deceitful balances,\n"
	"that we may for silver possess the needy, and the poor for shoes, and may sell the refuse of the corn?\n"
	"Our Lord hath sworn against the pride of Jacob: If I shall forget even to the end all their works.\n"
	"Why, shall not the land be moved upon this, and every inhabitant thereof mourn: and rise up as a river altogether, and be cast out, & run down to the river of Aegypt?\n"
	"And it shall be in that day, saith our Lord God: The sun shall go down at midday, and I will make the earth to be dark in the day of light.\n"
	"And I will turn your festivities into mourning, and all your songs into lamentation: and I will bring in upon every back of yours sackcloth, and upon every head baldness: and I will lay it as the mourning of an only begotten son, & the later end thereof as a bitter day.\n"
	"Behold the days come, saith our Lord, and I will send forth famine into the land: not the famine of bread, nor thirst of water, but of hearing the word of the Lord.\n"
	"And they shall be moved from the sea even to sea, and from the North even to the East: they shall go about seeking the word of our Lord, and shall not find.\n"
	"In that day the fair virgins shall fail, and the young men in thirst.\n"
	"They that swear by the sin of Samaria, and say: Thy God o Dan liveth: and the way of Bersabee liveth: and they shall fall, and shall rise no more.";