const char* chap1003 = "The vision of Abdias. Thus saith our Lord God to Edom: We have heard a bruit from our Lord, and he hath sent a legate to the Gentiles: Rise ye, and let us arise against him into battle.\n"
	"Behold I have given thee a little one in the Gentiles: thou art contemptible exceedingly.\n"
	"The pride of thy heart hath extolled thee, dwelling in the clefts of rocks, exalting thy throne: which sayst in thy heart: Who shall pluck me down to the earth?\n"
	"If thou shalt be exalted as an eagle, and if thou shalt set thy nest among the stars: thence will I pluck thee down, saith our Lord.\n"
	"If thieves had gone in to thee, if robbers by night, how hadst thou held thy peace? Would not they have stolen things sufficient for themselves? If the grape gatherers had entered in to thee, would they not have left thee at the least a cluster?\n"
	"How have they searched Esau, have they sought out his hidden things?\n"
	"Even to the border have they cast thee out: all the men of thy league have mocked thee: the men of thy peace have prevailed against thee: they that eat with thee, shall lay ambushments under thee: there is no wisdom in him.\n"
	"Why, shall not I in that day, saith our Lord, destroy the wise out of Idumea, and prudence from the mount of Esau.\n"
	"And thy valiants of the South shall fear, that man may perish from the mount of Esau.\n"
	"For the slaughter, and for the iniquity against thy brother Jacob, confusion shall cover thee, and thou shalt perish for ever.\n"
	"In the day when thou stoodest against him, when strangers took his army, and foreigners entered his gates, and upon Jerusalem cast lot: thou also wast as one of them.\n"
	"And thou shalt not despise in the day of thy brother, in the day of his peregrination: and thou shalt not rejoice over the children of Juda, in the day of their perdition: & thou shalt not magnify thy mouth in the day of distress.\n"
	"Neither shalt thou enter the gate of my people in the day of their ruin: neither shalt thou also despise in his evils in the day of his destruction: and thou shalt not be sent out against his army in the day of his destruction.\n"
	"Neither shalt thou stand in the out-goings to kill them that fly: & thou shalt not shut up his remnant in the day of tribulation.\n"
	"Because the day of our Lord is at hand upon all nations: as thou hast done, so shall it be done to thee: thy retribution he will return upon thine own head.\n"
	"For as you have drunk upon my holy mount, shall all Gentiles drink continually: & they shall drink, and swallow up, and they shall be as though they were not.\n"
	"And in mount Sion shall be salvation, and it shall be holy: and the house of Jacob shall possess those that had possessed them.\n"
	"And the house of Jacob shall be a fire, and the house of Joseph a flame, and the house of Esau stubble: and they shall be kindled in them, and shall devour them: and there shall be no remains of the house of Esau, because our Lord hath spoken.\n"
	"And they that are toward the South, shall inherit the mount of Esau, and they in the champion countries, Philisthiims: and they shall possess the region of Ephraim, and the region of Samaria: and Benjamin shall possess Galaad.\n"
	"And the transmigration of this host of the children of Israel, all places of the Chananeites even to Sarepta: and the transmigration of Jerusalem, that is in Bosphorus, shall possess the cities of the South.\n"
	"And saviours shall ascend into mount Sion to judge the mount of Esau: and the kingdom shall be to our Lord.";