const char* chap1007 = "And Jonas was afflicted with great affliction, and was angry:\n"
	"and he prayed to our Lord, & said: I beseech thee o Lord, Why, is not this my word, when I was yet in my country? For this did I prevent to fly into Tharsis. For I know that thou art a clement, and merciful God, patient, and of much compassion, and forgiving upon the evil.\n"
	"And now Lord take I beseech thee my soul from me: because better is death to me than life.\n"
	"And our Lord said: Art thou angry well thinkest thou?\n"
	"And Jonas went out of the city, and sat against the East part of the city: and he made himself a bower there, and he sat under it in the shadow, till he might see what would befall to the city.\n"
	"And our Lord God prepared an ivy tree, and it came up over the head of Jonas, to be a shadow over his head, and to cover him: for he had laboured: and Jonas rejoiced upon the ivy with great joy.\n"
	"And God prepared a worm in the rising of the morning against the morrow: & it struck the ivy: & it withered.\n"
	"And when the sun was risen, our Lord commanded an hot and burning wind: and the sun beat upon the head of Jonas, and he broiled for heat: and he desired for his soul to die, and said: It is better for me to die than to live.\n"
	"And our Lord said to Jonas: Art thou angry well, thinkest thou, for the ivy? And he said: I am angry well even unto death.\n"
	"And our Lord said: Thou art sorry for the ivy, wherein thou hast not laboured, nor made it to grow, which in one night came forth, and in one night is perished.\n"
	"And shall not I spare Ninive the great city, wherein are more than a hundred twenty thousand men, that know not what is between their right hand and their left, and many beasts?";