const char* chap1008 = "The word of our Lord that was made to Micheas the Morasthite, in the days of Joathan, Achaz, and Ezechias kings of Juda: which he saw upon Samaria and Jerusalem.\n"
	"Hear all ye peoples: & let the earth attend, & the fullness thereof: and let our Lord God be unto you for a witness, our Lord out of his holy temple.\n"
	"Because lo our Lord will go forth out of his place: and he will descend, and will tread upon the highest of the earth.\n"
	"And the mountains shall be consumed under him: and the valleys shall be cloven, as wax at the presence of fire, and as waters that run down headlong.\n"
	"For the wickedness of Jacob all this, and for the sins of the house of Israel. What is the wickedness of Jacob? Is it not Samaria? And what the excelses of Juda? Is it not Jerusalem?\n"
	"And I will lay Samaria as a heap of stones in the field when a vineyard is planted: & I will pluck down her stones into the valley, & will discover her foundations.\n"
	"And all her sculptiles shall be cut in sunder, & all her wages shall be burnt with fire, & I will lay all her idols into perdition: because they are gathered together of the wages of an harlot, & unto the hire of an harlot they shall return.\n"
	"Upon this will I lament, and howl: I will go spoiled, and naked: I will make lamentation as of dragons, & mourning as it were of striches.\n"
	"Because her plague is desperate, because it is come even to Juda, it hath touched the gate of my people even to Jerusalem.\n"
	"In Geth declare it not, weep not with tears: in the house of dust sprinkle yourself with dust.\n"
	"And pass ye to yourselves o fair habitation, confounded with ignominy: she went not out that dwelleth in the going out: the house adjoining shall receive lamentation for you, which stood to herself.\n"
	"Because she is weakened to good which dwelleth in bitterness: because evil is descended from our Lord into the gate of Jerusalem.\n"
	"Tumult of the chariot of astonishment to the inhabitant of Lachis: it is the beginning of sin to the daughter of Sion, because in thee are found the wickednesses of Israel.\n"
	"Therefore shall he give spoilers upon the inheritance of Geth: the houses of lying into deception to the kings of Israel.\n"
	"As yet will I bring an heir to thee which dwellest in Maresa: even to Odolla shall the glory of Israel come.\n"
	"Be bald, and be polled for the children of thy delicacies: enlarge thy baldness as an eagle: because they are led captives out of thee.";