const char* chap1022 = "COME together, be ye gathered together o nation not to be beloved:\n"
	"before that the commandment bring forth the day as dust passing away, before the wrath of the fury of our Lord come upon you, before the day of the indignation of our Lord come upon you.\n"
	"Seek our Lord all ye meek of the earth, which have wrought his judgement: seek the just, seek the meek: if by any means you may be hid in the day of the fury of our Lord.\n"
	"Because Gaza is destroyed, and Ascalon as a desert, Azotus at noon they shall cast out, and Accaron shall be rooted out.\n"
	"Woe to you that inhabit the cord of the sea, o nation of castaways: the word of our Lord upon you o Chanaan land of the Philisthiims, and I will destroy thee, so that there shall not be an inhabiter.\n"
	"And the cord of the sea shall be the rest of pastors, and folds of cattle.\n"
	"And it shall be the cord of him, that shall remain of the house of Juda, there they shall feed: in the houses of Ascalon at even they shall rest: because our Lord their God will visit them, and turn away their captivity.\n"
	"I have heard the reproach of Moab, and the blasphemies of the children of Ammon, with which they have upbraided my people, and were magnified upon their borders.\n"
	"Therefore live I, saith the Lord of hosts the God of Israel, that Moab shall be as Sodom, and the children of Ammon as Gomorrha, dryness of thorns, and heaps of salt, and a desert even for ever: the remnant of my people shall spoil them, and the residue of my nation shall possess them.\n"
	"This shall befall them for their pride: because they have blasphemed, and have been magnified upon the people of the Lord of hosts.\n"
	"Our Lord shall be dreadful upon them, and shall attenuate all the gods of the earth: and they shall adore him every man out of his own place, all the islands of the Gentiles.\n"
	"Yea and you Aethiopians shall be slain with my sword.\n"
	"And he will stretch forth his hand upon the North, and will destroy Assur: and he will lay the Beautiful as a wilderness, and as a place not passable, and as a desert.\n"
	"And flocks shall lie in the midst thereof, all the beasts of the Gentiles: and onocratulus, and the Irchin shall abide in the thresholds thereof: the voice of one singing in the window, the raven on the upper post, because I will attenuate her strength.\n"
	"This is the glorious city dwelling in confidence: that said in her heart: I am, and beside me there is none other else: how is she become as a desert the couch for beasts? every one that passeth by her, shall hiss, and wag his hand.";