const char* chap1027 = "And I lifted up mine eyes, and saw: and lo a man, and in his hand a cord of measurers.\n"
	"And I said: Whither goest thou? And he said to me: To measure Jerusalem, and to see how great the breadth thereof is, and how great the length thereof.\n"
	"And behold the Angel that spake in me, came forth, and another Angel went out to meet him.\n"
	"And he said to him: Run, speak to this young man saying: Without wall shall Jerusalem be inhabited for the multitude of men, and of beasts in the midst thereof.\n"
	"And I will be to it, saith our Lord, a wall of fire round about: and I will be in glory in the midst thereof.\n"
	"O fly ye out of the land of the North, saith our Lord, because into the four winds of heaven have I dispersed you, saith our Lord.\n"
	"O Sion, fly thou that dwellest with the daughter of Babylon:\n"
	"because thus saith the Lord of hosts: After glory he sent me to the nations, that have spoiled you: for he that shall touch you, toucheth the apple of mine eye:\n"
	"because lo I lift up my hand upon them, and they shall be a prey to those that served them: and you shall know that the Lord of hosts sent me.\n"
	"Praise, and rejoice o daughter of Sion: because lo I come, & will dwell in the midst of thee, saith our Lord.\n"
	"And many nations shall be joined to our Lord in that day, and they shall be my people, and I will dwell in the midst of thee: and thou shalt know that the Lord of hosts hath sent me to thee.\n"
	"And our Lord will possess Juda his portion in the sanctified land: and he will yet choose Jerusalem.\n"
	"Let all flesh be silent at the presence of our Lord: because he is risen up out of his holy habitation.";