const char* chap1028 = "And our Lord shewed me Jesus the grand Priest standing before the Angel of our Lord: and Satan stood on his right hand, to be his adversary.\n"
	"And our Lord said to Satan: The Lord give rebuke on thee Satan: and the Lord that chose Jerusalem give rebuke on thee: Why, is not this a fire-brand taken out of the fire?\n"
	"And Jesus was clothed with filthy garments: and he stood before the face of the Angel.\n"
	"Who answered, and said to them that stood before him, saying: Take away the filthy garments from him. And he said to him: Behold I have taken away thine iniquity, and have clothed thee with change of garments.\n"
	"And he said: Put a clean mitre upon his head: and they put a clean mitre upon his head, and clothed him with garments: and the Angel of our Lord stood.\n"
	"And the Angel of our Lord contested Jesus, saying:\n"
	"Thus saith the Lord of hosts: If you will walk in my ways, and keep my watch, thou also shalt judge my house, and shalt keep my courts, and I will give thee walkers of them that now assist here.\n"
	"Hear o Jesus thou grand Priest, thou and thy friends that dwell before thee, because they are portending men: for behold I WILL BRING MY SERVANT THE ORIENT.\n"
	"Because lo the stone that I laid before Jesus: upon one stone there be seven eyes, behold I will grave the graving thereof, saith the Lord of hosts: and I will take away the iniquity of that land in one day.\n"
	"In that day, saith the Lord of hosts, every man shall call his friend under the vine and under the fig-tree.";