const char* chap1030 = "And I turned and lifted up mine eyes, and I saw, and behold a volume flying\n"
	"And he said to me: What seest thou? And I said: I see a volume flying: the length thereof of twenty cubits, and the breadth thereof of ten cubits.\n"
	"And he said to me: This is the malediction, that goeth forth upon the face of the earth: because every thief, as is there written, shall be judged: and every swearer, by it in like manner shall be judged.\n"
	"I will bring it forth, saith the Lord of hosts: and it shall come to the house of the thief, & to the house of him that sweareth by my name falsely: and it shall abide in the midst of his house, and shall consume it, & the timber thereof, and the stones thereof.\n"
	"And the Angel went out that spake in me: and he said to me: Lift up thine eyes, and see what is this, that goeth forth.\n"
	"And I said: What is it? And he said: This is an amphore going forth. And he said: This is their eye in all the earth.\n"
	"And behold a talent of lead was carried, and lo one woman sitting in the midst of the amphore.\n"
	"And he said: This is impiety. And he threw her in the midst of the amphore, and cast a lump of lead upon the mouth thereof.\n"
	"And I lifted up mine eyes, and saw: and behold two women coming forth, and spirit in the wings of them, and they had wings as the wings of a kite: and they lifted up the amphore between the earth and the heaven.\n"
	"And I said to the Angel that spake in me: Whither do these carry the amphore?\n"
	"And he said to me: That a house may be built for it in the land of Sennaar, and it may be established, and set there upon the foundation thereof.";