const char* chap1031 = "And I turned, and lifted up mine eyes, and saw: and behold four chariots coming forth from the midst of two mountains, and the mountains, mountains of brass.\n"
	"In the first chariot red horses, and in the second chariot black horses,\n"
	"and in the third chariot white horses, and in the fourth chariot speckled horses, and strong.\n"
	"And I answered, and said to the Angel, that spake in me: What are these things, my Lord?\n"
	"And the Angel answered, and said to me: These are the four winds of heaven, which go forth to stand before the Dominatour of all the earth.\n"
	"That, in which were the black horses went forth into the land of the North, and the white went forth after them: and the speckled went forth to the land of the South.\n"
	"But they that were strongest, went out, and sought to go, and to run about through-out all the earth. And he said: Go walk through-out the earth, and they walked through-out the earth.\n"
	"And he called me, & spake to me, saying: Behold, they that go forth into the land of the North, have made my spirit to rest in the land of the North.\n"
	"And the word of our Lord was made to me, saying:\n"
	"Take of the transmigration of Holdai, and of Tobias, and of Idaias: and thou shalt come in that day, and shalt enter into the house of Josias, the son of Sophonias, who came out of Babylon.\n"
	"And thou shalt take gold and silver: and shalt make crowns, & thou shalt set on the head of Jesus the son of Josedec the grand Priest,\n"
	"and thou shalt speak to him, saying: Thus saith the Lord of hosts, saying: BEHOLD A MAN, ORIENT IS HIS NAME: and under him shall spring up, & shall build a temple to our Lord.\n"
	"And he shall build a temple to our Lord: and shall bear glory, and shall sit, and rule upon his throne: and he shall be a Priest upon his throne, and the counsel of peace shall be between them two.\n"
	"And the crowns shall be to Helem, and Tobias, and Idaias, and Hem, the son of Sophonias, a memorial in the temple of our Lord.\n"
	"And they that are far, shall come, and shall build in the temple of our Lord: and you shall know that the Lord of hosts sent me to you. But this shall be, if hearing you will hear the voice of our Lord your God.";