const char* chap1035 = "Ask of our Lord rain in the lateward time, and our Lord will make snows, and will give them rain of showers, to every one grass in the field.\n"
	"Because the idols spake that which was unprofitable, and the diviners saw a lie, & the dreamers spake in vain: they comforted vainly: therefore are they led away as a flock: they shall be afflicted, because they have no Pastor.\n"
	"Upon the Pastors my fury is wrath, and upon the buckgoats I will visit: because the Lord of hosts hath visited his flock, the house of Juda, and hath made them as the horse of his glory in the battle.\n"
	"Of him the corner, of him the pin, of him the bow of battle, of him shall come forth every exactor together.\n"
	"And they shall be as valiants, treading the mire of the ways in battle: and they shall fight, because our Lord is with them: and the riders of horses shall be confounded.\n"
	"And I will strengthen the house of Juda, and the house of Joseph I will save: and I will convert them, because I will have mercy on them: and they shall be as they were when I had not cast them off, for I am the Lord their God, and will hear them.\n"
	"And they shall be as the valiants of Ephraim, & their heart shall rejoice as it were of wine: and their children shall see, and shall rejoice, & their heart shall be joyful in our Lord.\n"
	"I will hiss to them, and will gather them together, because I have redeemed them: and I will multiply them as they were multiplied before.\n"
	"And I will sow them among peoples, & from a far they shall remember me: & they shall live with their children, and shall return.\n"
	"And I will bring them back out of the Land of Aegypt, and out of the Assyrians I will gather them: and to the Land of Galaad & Libanus I will bring them, and there shall not be found place for them.\n"
	"And he shall pass over in the strait of the sea, and shall strike the waves in the sea, & all the depths of the river shall be confounded, & the pride of Assur shall be humbled, and the sceptre of Aegypt shall depart.\n"
	"I will strengthen them in the Lord, and in his name they shall walk, saith our Lord.";