const char* chap1046 = "And Judas, that was called Machabeus his son arose in his stead:\n"
	"and all his brethren helped him, & all that had joined themselves to his father, and they fought the battle of Israel with joy.\n"
	"And he dilated glory to his people, & put on him a brigantine as a giant, and girded about him his warly armour in battles, and protected the camp with his sword.\n"
	"He became like a lion in his acts, and as a lion's whelp roaring in hunting.\n"
	"And he persecuted the wicked inquiring them out, & such as troubled his people, them he burnt with fire:\n"
	"and his enemies were repelled for fear of him, all the workers of iniquity were troubled: and salvation was directed in his hand.\n"
	"And he exasperated many kings, & rejoiced Jacob in his works, & for ever his memory is in benediction.\n"
	"And he walked through the cities of Juda, & destroyed the impious out of them, & turned away wrath from Israel.\n"
	"And he was renowned even to the uttermost part of the earth, and he gathered them that perished.\n"
	"And Apollonius gathered together the Gentiles, and from Samaria a power much and great, to make battle against Israel.\n"
	"And Judas understood it, and went forth to meet him: and he struck, and killed him: and there fell many wounded, & the rest fled away.\n"
	"And he took the spoils of them, and the sword of Apollonius^ Judas took away, and he fought with it all his days.\n"
	"And Seron captain of the army of Syria heard that Judas gathered a congregation of the faithful, and an assembly with him,\n"
	"and he said: I will make me a name, and will be glorified in kingdom, and will overthrow Judas, and those that are with him that despised the word of the king.\n"
	"And he prepared himself: and there went up with him a camp of the impious strong helpers, to do vengeance upon the children of Israel.\n"
	"And they approached even as far as Bethoron: & Judas went forth to meet him with few.\n"
	"But as they saw the army coming to meet them, they said to Judas: How shall we a few be able to fight against so great a multitude & so strong, and we are wearied with fasting today?\n"
	"And Judas said: It is an easy matter for many to be inclosed in the hand of few, & there is no difference in the sight of the God of heaven to deliver in many, & in few.\n"
	"Because not in the multitude of the army is the victory of battle, but from heaven is the strength.\n"
	"They come to us in an obstinate multitude, & in pride, to destroy us, & our wives, & our children, and to spoil us.\n"
	"But we will fight for our lives, & our laws:\n"
	"& our Lord himself will destroy them before our face, but you^ fear them not.\n"
	"And as he ceased to speak, he flew upon them suddenly: & Seron was destroyed, & his host in his sight:\n"
	"& he pursued him in the descent of Bethoron even to the plain, & there fell of them eight hundred men, & the rest fled into the land of the Philisthiims.\n"
	"And the fear of Judas & of his brethren, & the dread fell upon all the nations round about them.\n"
	"And his name came to the king, & all nations told of the battles of Judas.\n"
	"And as king Antiochus heard these words he was wrath in his mind: & he sent, & gathered the army of all his kingdom, a camp exceeding strong:\n"
	"and he opened his treasury, and gave wages to the army for a year: and he commanded them, that they should be ready at all assays.\n"
	"And he saw that money failed out of his treasures, & the tributes of the region small, because of the dissension, and the plague, that he had made in the land, to take away the ordinances, that were from the first days:\n"
	"and he feared lest he should not have as once and twice, for costs & gifts, which he had given before with a large hand: & he had abounded above the kings, that had been before him.\n"
	"And he was exceedingly astonished in mind, and purposed to go into Persis, and to take the tributes of the regions, and to gather much silver.\n"
	"And he left Lysias a noble man of the blood royal, over the king's affairs, from the river Euphrates even to the river of Aegypt:\n"
	"and that he should bring up Antiochus his son, till he returned.\n"
	"And he delivered to him half the army, and Elephants: and he gave him commandment concerning all things that he would, and concerning the inhabitants of Jurie, and Jerusalem:\n"
	"and that he should send an army to them, to destroy and root out the power of Israel, and the remnant of Jerusalem, and to take away the memory of them out of the place,\n"
	"and that he should appoint inhabitants in all their coasts, children strangers, & should by lot distribute their land.\n"
	"And the king took the part of the army that remained, & went forth from Antioch the city of his kingdom in the year an hundreth and seven and forty: and he passed over the river Euphrates, & walked through the higher countries.\n"
	"And Lysias chose Ptolomee the son of Doryminus, and Nicanor, and Gorgias, mighty men of the king's friends.\n"
	"And he sent with them forty thousand men, and seven thousand horsemen: that they should come into the land of Juda, and should destroy it according to the word of the king.\n"
	"And they went forth with all their power, and came, and joined near to Emmaum in the champion country.\n"
	"And the merchants of the countries heard the name of them: and they took silver and gold exceeding much, and servants: and they came into the camp, to take the children of Israel for slaves, & there were added to them the army of Syria, & of the land of the strangers.\n"
	"And Judas saw, & his brethren, that the evils were multiplied, and the armies approached to their borders: and they knew the king's words, which he commanded to do to the people unto destruction and consummation:\n"
	"and they said every one to his neighbour: Let us set up the abasing of our people, & let us fight for our people, and our holies.\n"
	"And an assembly was gathered, that they should be ready unto battle: & that they should pray and desire mercy & miserations.\n"
	"And Jerusalem was not inhabited, but was a desert: there was none that came in and went out of her children: and the holy place was conculcated: and the children of strangers were in the castle, there was the inhabitation of the Gentiles, and pleasure was taken away from Jacob, & there failed their pipe and harp.\n"
	"And they gathered together, and came into Maspha against Jerusalem: because the place of prayer in Israel was in Maspha before.\n"
	"And they fasted that day, and clothed themselves with haircloths, and put ashes on their head: and they rent their garments:\n"
	"and they laid open the books of the law, out of which the Gentiles searched the similitude of their idols:\n"
	"and they brought the ornaments of Priests, and first-fruits, & tithes, & raised up Nazareites, that had fulfilled their days:\n"
	"and they cried with a loud voice to heaven, saying: What shall we do with these, & whither shall we carry them?\n"
	"And thy holies are conculcated, and they are contaminated, and thy Priests are brought into mourning, & into humiliation.\n"
	"And behold the Nations are come together against us to destroy us: thou knowest what things they intend against us.\n"
	"How shall we be able to stand before their face, unless thou o God do help us?\n"
	"And with trumpets they cried out with a loud voice.\n"
	"And after these things Judas appointed captains of the people, tribunes, and centurions, and sergeants, and decurions.\n"
	"And he said to them, that built houses, and despoused wives, and planted vineyards, and to the fearful, that every one should return into his house, according to the law.\n"
	"And they removed the camp, and pitched at the South of Emmaum.\n"
	"And Judas said: Gird up yourselves, and be mighty sons, and be ready against the morning, that you may fight against these nations, which are assembled against us to destroy us, and our holies,\n"
	"because it is better for us to die in battle, than to see the evils of our nation, and of the holies:\n"
	"but as it shall be the will in heaven, so be it done.";