const char* chap1052 = "In the mean time as Demetrius heard that Nicanor was fallen and his army in the battle, he added to send Bacchides and Alcimus again into Jurie, and the right wing with them.\n"
	"And they went the way, that leadeth into Galgal, and camped in Masaloth, which is in Arbellis: and they won it, and slew of men many souls.\n"
	"In the first month of the year an hundreth and fifty two they brought the army near to Jerusalem:\n"
	"and they arose, and went into Beraea twenty thousand men, and two thousand horsemen.\n"
	"And Judas had camped in Laisa, and three thousand chosen men with him:\n"
	"and they saw the multitude of the army that they were many, and they feared exceedingly: and many withdrew themselves out of the camp, and there remained of them but eight hundred men.\n"
	"And Judas saw that his army shrunk away, and the battle pressed upon him, and his heart was broken: because he had not time to gather them together, and he was discouraged.\n"
	"And he said to them that were remaining: Let us rise, and go to our adversaries, if we may be able to fight against them.\n"
	"And they dissuaded him saying: We are not able, but let us save our lives now, and return to our brethren, and then we will fight against them: and we are few.\n"
	"And Judas said: God forbid we should do this thing, to fly from them: & if our time be near, let us die manfully for our brethren, and let us not stain our glory.\n"
	"And the army moved out of the camp, and they stood to meet them: and the horsemen were divided into two parts, and the slingers, and the archers went before the army, & of the forward all mighty.\n"
	"And Bacchides was in the right wing, and the legion approached on two sides, & they sounded with trumpets:\n"
	"and they also cried out that were on Judas' side, even they also, & the earth was moved at the voice of the armies: and the battle was fought from morning even until the evening.\n"
	"And Judas saw that the stronger part of the army was on the right hand, and all the stout of heart came together with him:\n"
	"and the right side was discomfited of them, & he pursued them even to the mount of Azotus.\n"
	"And they that were in the left wing, saw that the ring wing was discomfited, and they followed after Judas, and them that were with him at the back:\n"
	"and the battle grew sore, and there fell many wounded of these and of them.\n"
	"And Judas was slain, and the rest fled.\n"
	"And Jonathas and Simon took Judas their brother, and buried him in the sepulchre of their fathers in the city Modin.\n"
	"And all the people of Israel lamented him with great lamentation, and they mourned many days,\n"
	"and said: How is the mighty fallen, that saved the people of Israel!\n"
	"And the rest of the words of Judas' battles, and of the valiant acts that he did, and of his greatness are not described: for they were exceeding many.\n"
	"And it came to pass: after the death of Judas, there came forth the wicked men in all the coasts of Israel, & there arose all that wrought iniquity.\n"
	"In those days was made an exceeding great famine, and all their country with themselves yielded to Bacchides.\n"
	"And Bacchides chose the impious men, & appointed them lords of the country:\n"
	"and they sought out, & searched for the friends of Judas, & brought them to Bacchides, and he took revenge on them, and scorned them.\n"
	"And there was made great tribulation in Israel, such as was not since the day, that there was no Prophet seen in Israel.\n"
	"And all the friends of Judas gathered, & said to Jonathas:\n"
	"Since thy brother Judas died, there is not a man like unto him, to go forth against the enemies, Bacchides, & them that are the enemies of our nation.\n"
	"Now therefore thee have we chosen this day to be for him our prince, and captain to wage our battle.\n"
	"And Jonathas took upon him at that time the princedom, & arose in the place of Judas his brother.\n"
	"And Bacchides understood it, and sought to kill him.\n"
	"And Jonathas understood it, and Simon his brother, and all that were with them: and they fled into the desert of Thecua, and they pitched by the water of the lake Asphar.\n"
	"And Bacchides understood it, and in the day of the Sabbaths came himself, and all his army over Jordan.\n"
	"And Jonathas sent his brother captain of the people, to desire the Nabutheians his friends, that they would lend him their provision, which was copious.\n"
	"And the children of Jambri issued forth of Madaba, and took John, & all things that he had, and went away having them.\n"
	"After these words, it was told Jonathas and Simon his brother, that the children of Jambri make a great marriage, & bring the bride out of Madaba, the daughter of one of the great princes of Chanaan with great pomp.\n"
	"And they remembered the blood of John their brother: and they went up, and hid themselves under the covert of the mountain.\n"
	"And they lifted up their eyes, and saw: and lo a tumult, a great preparation: and the bridegroom came forth, and his friends, and his brethren to meet them with timbrels, and musical instruments, and many weapons.\n"
	"And they rose upon them out of the embushment, and slew them, and there fell many wounded, & the rest fled into the mountains, and they took all the spoils of them:\n"
	"and the marriage was turned into mourning, and the voice of their musical instruments into lamentation.\n"
	"And they took revenge of the blood of their brother: and they returned to the bank of Jordan.\n"
	"And Bacchides heard it, and he came on the day of the Sabbaths even to the brink of Jordan with a great power:\n"
	"And Jonathas said to his company: Let us arise, and fight against our enemies: for it is not today as yesterday, and the day before.\n"
	"For lo battle directly against us, and the water of Jordan on this side and on that side, and banks, and marishes, & forests: and there is no place to turn aside.\n"
	"Now therefore cry ye unto heaven, that you may be delivered out of the hand of your enemies. And battle was joined.\n"
	"And Jonathas stretched forth his hand to strike Bacchides, & he turned aside from him backwards.\n"
	"And Jonathas lept aside, and they that were with him into Jordan, & they swam over Jordan to them:\n"
	"and there fell of Bacchides' part that day a thousand men: and they returned into Jerusalem,\n"
	"and built fenced cities in Jurie, the fortress that was in Jericho, and in Ammaum, and in Bethoron, and in Bethel, and Thamnata, and Phara, and Thopo with high walls, and gates, & locks.\n"
	"And he placed a garrison in them, that they might exercise enmities against Israel:\n"
	"and he fenced the city Bethsura, and Gazara, and the castle, and set garrisons in them, & provision of victuals:\n"
	"& he took the sons of the princes of the country for hostages, and put them in the castle in Jerusalem into ward.\n"
	"And in the year an hundred fifty three, the second month, Alcimus commanded the walls of the inner holy house to be destroyed, and the works of the Prophets to be destroyed: & he began to destroy.\n"
	"In that time was Alcimus strucken: and his works were stayed, and his mouth was stopped, and he was dissolved with the palsy, neither could he speak a word any more, and give commandment touching his house.\n"
	"And Alcimus died at that time with great torment.\n"
	"And Bacchides saw that Alcimus was dead: and he returned to the king, & the land was quiet for two years.\n"
	"And all the wicked thought saying: Behold Jonathas, and they that are with him, dwell in silence securely: now therefore let us bring Bacchides, and he shall take them all in one night.\n"
	"And they went, and gave him counsel.\n"
	"And he arose to come with a great army: and he sent secretly epistles to his fellows that were in Jurie, to take Jonathas, and them that were with him: but they could not, because their counsel was known to them.\n"
	"And he apprehended of the men of the country, that were the principal of the mischief, fifty men, and he slew them.\n"
	"And Jonathas retired aside, and Simon, and they that were with him into Bethbessen, which is in the desert: and he built up the ruins thereof, and they fortified it.\n"
	"And Bacchides understood it, and gathered together all his multitude, and sent word to them that were of Jurie.\n"
	"And he came, and camped above Bethbessen, and assaulted it many days, and made engines.\n"
	"And Jonathas left Simon his brother in the city, and went forth into the country, & came with a number,\n"
	"and struck Odares, and his brethren, and the children of Phaseron in their tabernacles, and he began to slay, and to grow in forces.\n"
	"But Simon and they that were with him, went out of the city, and burnt the engines,\n"
	"and they fought against Bacchides, & he was discomfited by them: and they afflicted him exceedingly, because his counsel, and his conflict was in vain.\n"
	"And being angry against the wicked men, that had given him counsel to come into their country, he slew many of them: but himself thought with the rest to depart into their country.\n"
	"And Jonathas understood it, and he sent unto him legates to make peace with him, and to render unto him the captives.\n"
	"And he took it gladly, and did according to his words, and sware that he would do him no harm all the days of his life.\n"
	"And he rendered unto him the captives, which he before had taken for a prey, out of the land of Juda: & returning he departed into his own country, and he added no more to come into their coasts.\n"
	"And the sword ceased out of Israel: and Jonathas dwelt in Machmas, and Jonathas began there to judge the people, and he destroyed the impious out of Israel.";