const char* chap1057 = "In the year an hundreth seventy two, king Demetrius gathered his army, and went into Media to get him aids to expugn Tryphon.\n"
	"And Arsaces the king of Persia, and Media heard, that Demetrius was entered his confines, and he sent one of his princes to take him alive.\n"
	"And he went, and struck the camp of Demetrius: and took him, and brought him to Arsaces, and he put him into ward.\n"
	"And all the land of Juda was at rest all the days of Simon, and he sought good to his nation: & his power, and his glory pleased them all days.\n"
	"And with all his glory he took Joppe for an haven, and made it an entrance unto the isles of the sea.\n"
	"And he enlarged the borders of his nation, and obtained the country:\n"
	"And gathered a great captivity, and had dominion of Gazara, and of Bethsura, and of the castle: and took away the uncleanness out of it, and there was none that resisted him.\n"
	"And every man tilled his land with peace: and the land of Juda yielded her fruits, and the trees of the fields their fruit.\n"
	"The ancients sat all in the streets, and treated of the good things of the land, and the youngmen did on them glory, and the stoles of war.\n"
	"And he gave victuals to the cities, and he appointed them that they should be vessels of munition, till the name of his glory was renowned even to the end of the earth.\n"
	"He made peace upon the land, and Israel rejoiced with great joy.\n"
	"And every man sat under his vine, and under his figtree: and there was none to make them afraid.\n"
	"There was none left that impugned them upon the earth: kings were discomfited in those days.\n"
	"And he confirmed all the humble of his people, and sought the law, & took away every wicked and evil man:\n"
	"he glorified the holies, and multiplied the vessels of the holy places.\n"
	"And it was heard at Rome that Jonathas was dead, & even unto the Spartiates: and they were very sorry.\n"
	"But as they heard that Simon his brother was made the High-Priest in his place, and he obtained all the country, and the cities therein;\n"
	"they wrote to him in brazen tables, to renew the amities and society, which they had made with Judas, & with Jonathas his brethren.\n"
	"And they were read in the sight of the Church in Jerusalem. And this is a copy of the epistles, that the Spartiates sent.\n"
	"THE PRINCES and the cities of the Spartians to Simon the grand Priest, & to the ancients, and the Priests, and the rest of the people of the Jews their brethren, greeting.\n"
	"The legates, that were sent to our people, have told us of your glory, and honour, and joy: and we rejoiced at their entrance.\n"
	"And we wrote that, which was said of them in the counsels of the people, thus: Numenius the son of Antiochus, and Antipater the son of Jason, legates of the Jews, came to us, renewing with us old amity.\n"
	"And it pleased the people to receive the men gloriously, and to put a copy of their words in the severed book of the people, to be for a memory to the people of the Spartiates. And a copy of these we have written to Simon the grand Priest.\n"
	"And after these things Simon sent Numenius to Rome, having a great buckler of gold, of the weight of thousand pounds, to establish amity with them. But when the people of Rome had heard\n"
	"these words, they said: What thanks-giving shall we render to Simon & his children?\n"
	"For he hath restored his brethren, and hath expugned the enemies of Israel from them: and they decreed him liberty, & registered it in tables of brass, & put it in titles in mount Sion.\n"
	"And this is a copy of the writing. THE EIGHTEENTH day of the month Elul, in the year an hundreth seventy two, the third year under Simon the grand-Priest in Asaramel,\n"
	"in a great assembly of the Priests, and of the people & the Princes of the nation, and the ancients of the country, these things were notified: that there have often been battles made in our country.\n"
	"But Simon the son of Mathathias of the children of Jarib, & his brethren put themselves in danger, and resisted the adversaries of their nation, that their holies and law might stand: and with great glory have they glorified their nation.\n"
	"And Jonathas gathered together his nation, & was made their grand Priest, & he was laid to his people.\n"
	"And their enemies would conculcate, and destroy their country, and extend their hands against the holies.\n"
	"Then Simon, resisted and fought for his nation, and bestowed much money, and armed the valiant men of his nation, and gave them wages:\n"
	"and he fortified the cities of Jurie, and Bethsura, that was in the borders of Jurie, where the armour of the enemies was before: and he placed there Jews for a garrison.\n"
	"And he fortified Joppe, which was by the sea: and Gazara, which is in the borders of Azotus, wherein the enemies dwelt before, and he placed Jews there: and whatsoever was fit for their correption, he put in them.\n"
	"And the people saw the fact of Simon, and the glory that he meant to do to his nation, and they made him their duke, and grand Priest, for that he had done all these things, and for the justice, and faith, which he kept to his nation, and for that he sought by all means to advance his people.\n"
	"And in his days it prospered in his hands, so that the heathen were taken away out of their country, and they that were in the city of David in Jerusalem in the castle, out of which they came forth, and contaminated all things that were round about the holies, and they brought great plague upon chastity:\n"
	"and he placed in it men of Jurie to the defence of the country, and of the city, and he raised the walls of Jerusalem.\n"
	"And king Demetrius appointed him the high priesthood.\n"
	"According to these things he made him his friend, and glorified him with great glory.\n"
	"For he heard that the Jews were called of the Romans, friends, & fellows, & brethren, & that they received Simon's legates gloriously:\n"
	"and that the Jews, and their Priests consented that he should be their duke, & high-Priest for ever, till there rise the faithful Prophet:\n"
	"and that he be duke over them, and that he should have the care of the holies, and that he should appoint rulers over their works, and over the country, and over the armour, and over the holds.\n"
	"And that he have care of the holies: and that he be heard of all, and that all writings in the country be written in his name: and that he be clothed with purple and gold:\n"
	"and that it be not lawful for any of the people, and of the Priests to disannul any of these, and to gainsay those things, that are said of him, or to call together an assembly in the country without him: & to be clothed with purple, & to wear a chain of gold.\n"
	"But he that shall do beside these things, or shall make frustrate any of these, he shall be guilty.\n"
	"And it pleased all the people to appoint Simon, and to do according to these words.\n"
	"And Simon took it upon him, and it pleased him to execute high Priest-hood, and to be duke & prince of the nation of the Jews, and of the Priests, and to be chief over all.\n"
	"And this writing they bade them put in tables of brass, and to set them in the circuit of the holies, in a famous place:\n"
	"and to put a copy thereof in the treasury, that Simon may have it, and his children.";