const char* chap1068 = "At that time Antiochus returned out of Persis dishonourably.\n"
	"For he had entered into the city which is called Persepolis, and he attempted to spoil the temple, and to oppress the city: but the multitude running together to arms, they were put to flight: and so it chanced that Antiochus after his flight returned with dishonour.\n"
	"And when he was come about Ecbatana, he understood the things that were done to Nicanor and Timothee.\n"
	"And swelling in anger, he thought that he might wreak the injury of them, that had put him to flight, upon the Jews. And therefore he commanded his chariot to be driven, journeying without intermission, the heavenly judgement urging him forward, because he spoke so proudly, that he would come to Jerusalem, & make it an heap of the sepulchre of the Jews.\n"
	"But he that seeth all things our Lord the God of Israel, struck him with an uncurable and invisible plague. For as he ended this very speech, a cruel plague of the bowels took him, and bitter torments of the inner parts:\n"
	"and indeed very justly, as who had tormented the bowels of others with many & new torments, albeit he by no means ceased from his malice.\n"
	"And beside this replenished with pride, breathing fire in his mind against the Jews, & commanding the matter to be hastened, it chanced him going with violence to fall from the chariot, & his limbs to be vexed with a grievous bruising of the body.\n"
	"And he that seemed to himself to rule even over the waves of the sea, replenished with pride above the measure of man, & to weigh the heights of mountains in a balance, now being humbled to the ground was carried in a portative seat, testifying the manifest power of God in himself:\n"
	"so that out of the body of the impious man, worms crawled abundantly, and his live flesh fell off for pains, with his smell also & stink the army was annoyed.\n"
	"And he that a little before thought to touch the stars of heaven, him no man could carry for the intolerable stink.\n"
	"Hereby therefore he began, being brought from his great pride, to come to the knowledge of himself, admonished by the plague of God, his pains increasing every moment.\n"
	"And when neither himself now could abide his own stink, thus he said: It is reason to be subject to God, and a mortal man not to think of himself equally with God.\n"
	"And this wicked man prayed to our Lord, of whom he was not to obtain mercy.\n"
	"And the city to the which he came in haste to have brought it to the ground, and to have made it a sepulchre of bodies heaped together, now wisheth to make it free:\n"
	"And the Jews whom he said he would not vouchsafe worthy, no not of burial, but would give them to birds and wild beasts to be spoiled, and destroy them with the little ones, now he promiseth to make them equal with the Athenians.\n"
	"The holy temple also, which before he had spoiled, he would adorn with goodly donaries, & would multiply the holy vessels, and of his revenues would allow the charges pertaining to the sacrifices.\n"
	"Besides these things, that he would be a Jew also, and would walk through every place of the earth, & would declare the power of God.\n"
	"But the pains ceasing not (for the just judgement of God was come upon him) despairing he wrote to the Jews by the manner of a supplication an epistle containing these words:\n"
	"TO HIS VERY GOOD SUBJECTS the Jews the king and prince Antiochus, much health, and welfare, and to be happy.\n"
	"If you and your children farewell, and if things be with you to your mind, we give very great thanks.\n"
	"And I being in infirmity, & mindful of you benignly, being returned out of the places of Persis, & taken with a grievous infirmity, have thought it necessary to have a care for the common profit:\n"
	"not despairing of myself, but having great hope to escape the sickness.\n"
	"But considering that my father also, at what times he led his army in the higher places, he shewed who should take the princedom after him:\n"
	"that if any mishap should chance, or hard tidings be told, they that were in the countries, knowing to whom the whole government was committed, might not be troubled.\n"
	"Besides this, considering that all the potestates, and bordering neighbours wait for times, and expect the event, I have appointed my son Antiochus king, whom, I having recourse oftentimes to the higher kingdoms did commend to many of you: and I have written to him that which is set down here beneath.\n"
	"I pray you therefore, and desire you mindful of the benefits both public and private, that every one keep his fidelity to me, and to my son.\n"
	"For I trust that he will deal modestly and gently, and following my purpose, and that he will be common unto you.\n"
	"Therefore the murderer and blasphemer being very sore strucken, & as himself had handled others, in a strange country among the mountains, with a miserable death departed this life.\n"
	"But Philip his foster brother removed his body: who fearing the son of Antiochus, went to Ptolomee Philometor into Aegypt.";