const char* chap107 = "And our Lord spake to Moyses, saying:\n"
	"Speak to Aaron and his sons, and to all the children of Israel, saying to them: This is the word which our Lord hath commanded, saying:\n"
	"Any man whosoever of the house of Israel, if he kill an ox or a sheep, or a goat in the camp or without the camp,\n"
	"and offer it not at the door of the tabernacle and oblation to the Lord, shall be guilty of blood: as if he had shed blood, so shall he perish out of the midst of his people.\n"
	"Therefore shall the children of Israel bring to the Priest their hosts, which they kill in the field, that they may be sanctified to our Lord before the door of the tabernacle of testimony, & they may immolate them pacific hosts to our Lord.\n"
	"And the Priest shall pour the blood upon the altar of our Lord, at the door of the tabernacle of testimony, and shall burn the fat for a sweet odour to our Lord:\n"
	"and they shall no more immolate their hosts to devils, with whom they have committed fornication. It shall be an ordinance for ever to them and to their posterity.\n"
	"And to them thou shalt say: The man of the house of Israel, and the strangers, which sojourn with you, that offereth an holocaust or victim,\n"
	"and bringeth it not to the door of the tabernacle of testimony, that it may be offered to our Lord, shall perish out of his people.\n"
	"Any man whosoever of the house of Israel, and of the strangers, that sojourn among them, if he eat blood, I will set my face against his life, and will destroy it out of his people,\n"
	"because the life of the flesh is in the blood: and I have given it to you, that upon the altar you may make expiation with it for your souls, and the blood may be for an expiation of the soul.\n"
	"Therefore have I said to the children of Israel: No soul of you shall eat blood, nor of the strangers, that sojourn with you.\n"
	"Any man whosoever of the children of Israel, and of the strangers that sojourn with you, if by hunting or fowling he take wild beast or fowl, which it is lawful to eat, let him pour out the blood thereof, and cover it with earth.\n"
	"For the life of all flesh is in the blood: whereupon I said to the children of Israel: The blood of no flesh shall you eat, because the life of the flesh is in the blood: and whosoever eateth it shall die.\n"
	"The soul that eateth carrion, or that which is taken of a beast, as well of them of the same country as of strangers, shall wash his cloths, and himself with water, and shall be contaminated until even: and in this order he shall be made clean.\n"
	"And if he do not wash his cloths, and his body, he shall bear his iniquity.";