const char* chap1072 = "In the year an hundred forty nine Judas understood, that Antiochus Eupator came with a multitude against Jurie.\n"
	"and with him Lysias the procurator, and chief over the affairs having with him of footmen an hundred ten thousand, and of horsemen five thousand, and elephants twenty two, chariots with hooks three hundred.\n"
	"And Menelaus also joined himself with them: & with much deceit besought Antiochus, not for the weal of his country, but hoping that he should be appointed to the principality.\n"
	"But the King of kings stirred up Antiochus' mind against the sinner, and Lysias suggesting that he was the cause of all the evils, he commanded (as the custom is with them) that being apprehended he should be killed in the same place.\n"
	"And there was in the same place a tower of fifty cubits, having an heap of ashes on every side: this had a prospect steep down.\n"
	"From thence he commanded the sacrilegious person to be thrown down into the ashes, all thrusting him forward to death.\n"
	"And by such law it chanced the transgressor of the law to die: and Menelaus not to be put into the earth.\n"
	"And indeed very justly, because he committed many offences toward the altar of God, the fire and ashes whereof was holy: himself was condemned into the death of ashes.\n"
	"But the king furious in mind, came to shew himself worse to the Jews than his father.\n"
	"Which things when Judas understood, he commanded the people that day and night they should invocate our Lord, that as always now also he would help them:\n"
	"as who were afraid to be deprived of the law, and their country, and the holy temple: and that he would not suffer the people that had of late taken breath a little while, to be again subdued to the blasphemous nations.\n"
	"All therefore doing it together, and craving mercy of our Lord with weeping and fastings, being prostrate for three days continually, Judas exhorted them to prepare themselves.\n"
	"But he with the ancients consulted, before the king should bring his army to Jury, and win the city, to go out, and to commit the event of the thing to the judgement of our Lord.\n"
	"Committing therefore the power and charge of all to God, the creator of the world, and having exhorted his company to fight manfully, and to stand even to death for the laws, the temple, the city, their country, and citizens: he placed his army about Modin.\n"
	"And having given a sign to his company of the victory of God, with most valiant young men picked out, by night setting upon the king's court, in the camp he slew four thousand men, and the greatest of the elephants, with them that had been placed thereupon,\n"
	"& he filled the camp of the enemies with exceeding fear & perturbation, & the things being prosperously achieved, they departed.\n"
	"And this was done when the day appeared, the protection of our Lord helping him.\n"
	"But the king having taken a taste of the hardiness of the Jews, attempted the difficulty of the places by policy:\n"
	"& he moved his camp to Bethsura, which was a strong hold of the Jews: but he was put to flight, he fell, he was diminished.\n"
	"And to them that were within Judas sent necessaries.\n"
	"But one Rhodocus of the Jews' army uttered the secrets to the enemies, who being sought for was apprehended, and shut up.\n"
	"Again the king had talk with them that were in Bethsura: he gave the right hand: he took it: he went away.\n"
	"He joined battle with Judas, he was overcome. And as he understood that Philippe rebelled at Antioch, who was left over the affairs, dismayed in mind entreating the Jews, and yielding unto them, he sweareth concerning all things that seemed reason, and being reconciled he offered sacrifice, honoured the temple, and gave hosts.\n"
	"He embraced Machabeus, and made him governor and prince from Ptolemais even to the Gerrenians.\n"
	"But after, as he came to Ptolemais the Ptolemaians took grievously the covenant of amity, being offended lest perhaps they would break their league.\n"
	"Then Lysias went up to the judgement seat, and declared the reason, and appeased the people, and returned to Antioch: and in this manner the king's journey and return proceeded.";