const char* chap108 = "And our Lord spake to Moyses, saying:\n"
	"Speak to the children of Israel, and thou shalt say to them: I^ the Lord your God,\n"
	"according to the custom of the Land of Aegypt, wherein you have dwelt, you shall not do: and according to the manner of the Country of Chanaan, into the which I will bring you, you shall not do, nor walk in their ordinances.\n"
	"You shall do my judgments, and shall observe my precepts, and shall walk in them. I^ the Lord your God.\n"
	"Keep my laws and judgments, which a man doing, shall live in them. I^ the Lord.\n"
	"No man shall approach to her that is next of his blood, to reveal her turpitude. I^ the Lord.\n"
	"The turpitude of thy father, and the turpitude of thy mother thou shalt not discover: she is thy mother, thou shalt not reveal her turpitude.\n"
	"The turpitude of thy father's wife thou shalt not discover: for it is the turpitude of thy father:\n"
	"The turpitude of thy sister by father, or by mother, which was born at home or abroad, thou shalt not reveal.\n"
	"The turpitude of thy son's daughter or of thy niece by the daughter, thou shalt not reveal: because it is thy turpitude.\n"
	"The turpitude of thy father's wife's daughter, which she bare to thy father, and is thy sister, thou shalt not reveal.\n"
	"The turpitude of thy father's sister thou shalt not discover: because she is the flesh of thy father.\n"
	"The turpitude of thy mother's sister thou shalt not reveal, because she is of the flesh of thy mother.\n"
	"The turpitude of thy father's brother thou shalt not reveal, neither shall thou approach to his wife, who is joined to thee by affinity.\n"
	"The turpitude of thy daughter in law thou shalt not reveal, because she is thy son's wife, neither shalt thou discover her ignominy.\n"
	"The turpitude of thy brother's wife thou shalt not reveal: because it is the turpitude of thy brother.\n"
	"The turpitude of thy wife, and her daughter thou shalt not reveal. Her son's daughter, and her daughter's daughter, thou shalt not take, to reveal her ignominy: because they are her flesh, and such copulation is incest.\n"
	"Thou shalt not take thy wife's sister for an harlot, to vex her withal, neither shalt thou reveal her turpitude, while she is yet living.\n"
	"To a woman, having her flowers, thou shalt not approach, neither shalt thou reveal her turpitude.\n"
	"With thy neighbour's wife thou shalt not company, nor be polluted with commixtion of seed.\n"
	"Of thy seed thou shalt not give to be consecrated to the idol Moloch, nor pollute the name of thy God: I^ the Lord.\n"
	"Company not with mankind, as with womankind, because it is abomination.\n"
	"With no beast shalt thou company, neither shalt thou be polluted with it. A woman shall not lie down to a beast, nor company with it: because it is an heinous fact.\n"
	"Neither be ye polluted in any of the things wherewith all the nations have been contaminated, which I will cast out before your sight,\n"
	"and wherewith the land is polluted: whose abominations I will visit, that it vomit out the inhabitants thereof.\n"
	"Keep my ordinances and judgments, and do not any of these abominations, as well the same countryman as the stranger that sojourneth with you.\n"
	"For all these execrable things did the inhabitants of the land, that have been before you, and have polluted it.\n"
	"Beware therefore lest in like manner it vomit out you also, when you shall do the like things, as it vomited out the nation that was before you.\n"
	"Every soul, that shall do any of these abominations, shall perish from the midst of his people,\n"
	"Keep my commandments. Do not the things which they have done, that have been before you, and be not polluted in them: I^ the Lord your God.";