const char* chap1089 = "THEN came to him from Jerusalem Scribes and Pharisees, saying:\n"
	"Why do thy Disciples transgress the tradition of the Ancients? For they wash not their hands when they eat bread.\n"
	"But he answering said to them: Why do you also transgress the commandment of God for your tradition? For God said:\n"
	"Honour father and mother. And: He that shall curse father or mother, dying let him die.\n"
	"But you say: whosoever shall say to father or mother, the gift whatsoever proceedeth from me, shall profit thee:\n"
	"And shall not honour his father or his mother: & you have made frustrate the commandment of God for your own tradition.\n"
	"Hypocrites, well hath Esay Prophesied of you, saying:\n"
	"This People honoureth me with their lips: but their heart is far from me.\n"
	"And in vain do they worship me, teaching doctrines and commandments of men.\n"
	"And having called together the multitudes unto him, he said to them: Hear ye and understand.\n"
	"Not that which entereth into the mouth, defileth a man: but that which proceedeth out of the mouth, that defileth a man.\n"
	"Then came his Disciples, and said to him: Dost thou know that the Pharisees, when they heard this word, were scandalized?\n"
	"But he answering said: All planting which my Heavenly Father hath not planted, shall be rooted up.\n"
	"Let them alone: blind they are, guides of the blind. And if the blind be guide to the blind, both fall into the ditch.\n"
	"And Peter answering said to him: Expound us this parable.\n"
	"But he said: Are you also as yet without understanding?\n"
	"Do you not understand, that all that entereth into the mouth, goeth into the belly, and is cast forth into the privy?\n"
	"But the things that proceed out of the mouth, come forth from the heart, and those things defile a man.\n"
	"For from the heart come forth evil cogitations, murders, adulteries, fornications, thefts, false testimonies, blasphemies.\n"
	"These are the things that defile a man. But to eat with unwashen hands, doth not defile a man.\n"
	"And JESUS went forth from thence and retired into the quarters of Tyre and Sidon.\n"
	"And behold a woman of Chanaan came forth out of those coasts, & crying out, said to him: Have mercy upon me, O Lord the Son of David: my daughter is sore vexed of a devil.\n"
	"Who answered her not a word. And his Disciples came and besought him saying: Dismiss her, because she cryeth out after us.\n"
	"And he answering said: I was not sent but to the sheep that are lost of the house of Israel.\n"
	"But she came and adored him, saying: Lord, help me.\n"
	"Who answering, said: It is not good to take the bread of the Children, and to cast it to the dogs.\n"
	"But she said: Yea Lord; for the whelps also eat of the crumbs that fall from the table of their masters.\n"
	"Then JESUS answering said to her: O woman, great is thy faith: be it done to thee as thou wilt: And her daughter was made whole from that hour.\n"
	"And when JESUS was passed from thence, he came beside the sea of Galilee: & ascending into the mountain, sat there.\n"
	"And there came to him great multitudes, having with them dumb persons, blind, lame, feeble, and many others: and they cast them down at his feet, and he cured them:\n"
	"So that the multitudes marveled seeing the dumb speak, the lame walk, the blind see: and they magnified the God of Israel.\n"
	"And JESUS called together his Disciples, and said: I pity the multitude because three days now they continue with me, & have not what to eat: and dismiss them fasting I will not, lest they faint in the way.\n"
	"And the Disciples say unto him: whence then may we get so many loaves in the desert as to fill so great a multitude?\n"
	"And JESUS said to them: How many loaves have you? But they said: Seven, & a few little fishes.\n"
	"And he commanded the multitude to sit down upon the ground.\n"
	"And taking the Seven loaves & the fishes, and giving thanks, he brake, & gave it to his Disciples, and the Disciples gave to the people.\n"
	"And they did all eat, and had their fill. And that which was left of the fragments they took up, seven baskets full.\n"
	"And there were that did eat, four thousand men, beside children & women.\n"
	"And having dismissed the multitude, he went up into a boat, and came into the coasts of Magedan.";