const char* chap110 = "And our Lord spake to Moyses, saying:\n"
	"These things thou shalt speak to the children of Israel: If any man of the children of Israel, & of the strangers, that dwell in Israel, give of his seed to the idol Moloch, dying let him die: the people of the land shall stone him.\n"
	"And I will set my face against him: and will cut him off from the midst of his people, because he hath given of his seed to Moloch, and hath contaminated my Sanctuary, and polluted my holy name.\n"
	"And if the people of the land neglecting, and as it were little esteeming my commandment, let alone the man that hath given of his seed to Moloch, and will not kill him:\n"
	"I will set my face upon that man, & his kindred, and will cut off both him, and all that consented with him, to commit fornication with Moloch, out of the midst of their people.\n"
	"The soul that shall decline to Magicians and soothsayers, and shall commit fornication with them, I will set my face against it, and destroy it out of the midst of his people.\n"
	"Sanctify yourselves, and be holy, because I am the Lord your God.\n"
	"Keep my precepts, & do them. I^ the Lord that sanctify you.\n"
	"He that curseth his father, or mother, dying let him die: he hath cursed father, and mother, his blood be upon him.\n"
	"If any man commit adultery with another man's wife, and commit adultery with his neighbour's wife, dying let them die, both the adulterer and the adultress.\n"
	"He that lieth with his stepmother, and revealeth the ignominy of his father, dying let both die: their blood be upon them.\n"
	"If any man lie with his daughter in law, let both die, because they have done an heinous fact: their blood be upon them.\n"
	"He that lieth with man as if he should company with woman, both have committed abomination, dying let them die: their blood be upon them.\n"
	"He that besides his wife the daughter, marrieth her mother, hath done wickedness: he shall burn alive with them, neither shall there so great abomination remain in the midst of you.\n"
	"He that shall company with beast & cattle, dying let him die: the beast also do ye kill.\n"
	"The woman that shall lie under any beast, shall be killed together with the same: their blood be upon them.\n"
	"He that taketh his sister the daughter of his father, or the daughter of his mother, & seeth her turpitude, & she beholdeth her brother's ignominy, they have committed a shameful thing: they shall be slain in the sight of their people, because they have revealed one another's turpitude, & they shall bear their iniquity.\n"
	"He that companieth with a woman in her menstrual flux, & revealeth her turpitude, & she openeth the fountain of her blood, both shall be destroyed out of the midst of their people.\n"
	"The turpitude of thy aunt by thy mother, and of thy aunt by thy father, thou shalt not discover: he that doth this, hath disclosed the ignominy of his flesh, both shall bear their iniquity.\n"
	"He that companieth with the wife of his uncle by the father, or of his uncle by the mother, & revealeth the ignominy of his kindred, both shall bear their sin: without children they shall die.\n"
	"He that marrieth his brother's wife, doth an unlawful thing, he hath revealed his brother's turpitude: they shall be without children.\n"
	"Keep my laws, and judgements, and do them: lest the land which you shall enter into and inhabit, vomit out you also.\n"
	"Walk not in the ordinances of the nations, which I will expel before you. For all these things have they done, and I have abhorred them.\n"
	"But to you I speak: Possess their land, which I will give you for an inheritance, a land flowing with milk and honey. I^ the Lord your God, that have separated you from other peoples.\n"
	"Therefore do you also separate the clean beast, from the unclean, and the clean fowl from the unclean: pollute not your souls in beasts, and birds, and all things that move on the earth, and which I have shewed unto you to be polluted.\n"
	"You shall be holy unto me, because I^ the Lord am holy, and I have separated you from other peoples, that you should be mine.\n"
	"Man, or woman, in whom is a pythonical or divining spirit, dying let them die: they shall stone them: their blood be upon them.";