const char* chap1105 = "AND he entered again into the Synagogue, and there was a man there that had a withered hand.\n"
	"And they watched him whether he would cure on the Sabboths; that they might accuse him.\n"
	"And he saith to the man that had the withered hand: rise up into the midst.\n"
	"And he saith to them: Is it lawful on the Sabboths to do well or ill? to save a soul, or to destroy? but they held their peace.\n"
	"And looking round about upon them with anger, being sorrowful for the blindness of their heart, he saith to the man: Stretch forth thy hand. And he stretched it forth; and his hand was restored unto him.\n"
	"And the Pharisees going forth, immediately made a consultation with the Herodians against him, how they might destroy him.\n"
	"But JESUS with his Disciples retired to the sea: and a great multitude from Galilee & Jewry followed him,\n"
	"and from Jerusalem, & from Idumaea, and beyond Jordan. And they about Tyre and Sidon, a great multitude, hearing the things which he did, came to him.\n"
	"And he spake to his Disciples that a boat might attend on him because of the multitude, lest they should throng him.\n"
	"For he healed many, so that there pressed in upon him for to touch him, as many had hurts.\n"
	"And the unclean spirits, when they saw him, fell down unto him: and they cried saying:\n"
	"Thou art the Son of God. And he vehemently charged them that they should not disclose him.\n"
	"And ascending into a mountain, he called unto him whom he would himself, and they came to him.\n"
	"And he made that twelve should be with him, and that he might send them to preach.\n"
	"And he gave them power to cure infirmities, and to cast out devils.\n"
	"And he gave to Simon the name Peter.\n"
	"And James of Zebedee, and John the brother of James; and he called their names, Boanerges, which is, the sons of thunder.\n"
	"And Andrew and Philippe, and Barthlemew and Matthew, and Thomas and James of Alphaeus, and Thaddaeus and Simon Cananaeus,\n"
	"and Judas Iscariote, who also betrayed him.\n"
	"And they come to a house; and the multitude resorteth together again, so that they could not so much as eat bread.\n"
	"And when his^ had heard of it, they went forth to lay hands on him. For they said that he was become mad.\n"
	"And the Scribes which were come down from Jerusalem, said: That he hath Beelzebub; and that in the prince of devils he casteth out devils.\n"
	"And after he had called them together, he said to them in parables: How can Satan cast out Satan?\n"
	"And if a Kingdom be divided against itself, that Kingdom cannot stand.\n"
	"And if a house be divided against itself, that house cannot stand.\n"
	"And if Satan be risen against himself, he is divided, and cannot stand, but hath an end.\n"
	"Nobody can rifle the vessels of the strong, being entered into his house, unless he first bind the strong, & then shall he rifle his house.\n"
	"Amen I say to you, that all sins shall be forgiven the sons of men, & the blasphemies wherewith they shall blaspheme:\n"
	"But he that shall blaspheme against the Holy Ghost, he hath not forgiveness for ever, but shall be guilty of an eternal sin. Because they said: He hath an unclean spirit.\n"
	"And there come his mother and brethren; and standing without they sent unto him calling him,\n"
	"And the multitude sat about him; and they say to him:\n"
	"Behold thy mother and thy brethren without seek thee.\n"
	"And answering them, he said: Who is my mother and my brethren?\n"
	"And looking upon them which sat round about him, he saith: Behold my mother and my brethren.\n"
	"For whosoever shall do the will of God, he is my brother and my sister and mother.";