const char* chap1125 = "AND when he had fully said all his words into the ears of the people, he entered into Capharnaum.\n"
	"And the servant of a certain Centurion being sick, was ready to die: who was dear unto him.\n"
	"And when he had heard of JESUS, he sent unto him the Ancients of the Jews, desiring him to come and heal his servant.\n"
	"But they being come to JESUS, besought him earnestly, saying to him, That he is worthy that thou shouldest do this for him.\n"
	"For he loveth our Nation; and he hath built a Synagogue for us.\n"
	"And JESUS went with them. And when he was now not far from the house, the Centurion sent his friends unto him, saying: Lord, trouble not thyself. For I am not worthy that thou shouldest enter under my roof.\n"
	"For the which cause neither did I think myself worthy to come to thee; but say the word, and my servant shall be made whole.\n"
	"For I also am a man subject to authority, having under me soldiers: and I say to this, go, and he goeth: and to another, come, and he cometh; and to my servant, do this, and he doeth it.\n"
	"Which JESUS hearing, marveled; and turning to the multitudes that followed him he said: Amen I say to you, neither in Israel have I found so great faith.\n"
	"And they that were sent, being returned home, found the servant that had been sick, whole.\n"
	"And it came to pass, afterward he went into a city that is called Naim; and there went with him his Disciples and a very great multitude.\n"
	"And when he came nigh to the gate of the city, behold a dead man was carried forth, the only son of his mother; and she was a widow: and a great multitude of the city with her.\n"
	"Whom when our Lord had seen, being moved with mercy upon her, he said to her: Weep not.\n"
	"And he came near and touched the coffin. And they that carried it stood still; and he said: Young man, I say to thee, arise.\n"
	"And he that was dead, sat up, and began to speak. And he gave him to his mother.\n"
	"And fear took them all; and they magnified God, saying, That a great Prophet is risen among us: and, that God hath visited his people.\n"
	"And this saying went forth into all Jewry of him, & into all the country about.\n"
	"And John's disciples shewed him of all these things.\n"
	"And John called two of his disciples, and sent them to JESUS, saying: Art thou he that art to come; or expect we another?\n"
	"And when the men were come unto him, they said: John the Baptist hath sent us to thee, saying: Art thou he that art to come; or expect we another?\n"
	"(And the self same hour, he cured many of maladies, and hurts, and evil spirits: and to many blind he gave sight.)\n"
	"And answering, he said to them: Go & report to John what you have heard and seen: That the blind see, the lame walk, the lepers are made clean, the deaf hear, the dead rise again,\n"
	"the poor are evangelized: and blessed is he whosoever shall not be scandalized in me.\n"
	"And when John's messengers were departed, he began to say of John to the multitudes: What went you out into the desert to see? A reed moved with the wind?\n"
	"But what went you forth to see? A man clothed in soft garments? Behold they that are in costly apparel and delicacies, are in the house of kings.\n"
	"But what went you out for to see? A Prophet? Certes I say to you, and more than a Prophet.\n"
	"This is he of whom it is written: Behold I send mine Angel before thy face, which shall prepare thy way before thee.\n"
	"For I say to you: A greater Prophet among the children of women than John the Baptist, there is no man. But he that is the lesser in the Kingdom of God, is greater than he.\n"
	"And all the people hearing and the Publicans, justified God, being baptized with John's baptism.\n"
	"But the Pharisees and the lawyers despised the counsel of God against themselves, being not baptized of him.\n"
	"And our Lord said: Where unto then shall I liken the men of this generation, and whereunto are they like?\n"
	"They are like to children sitting in the market-place, and speaking one to another, and saying: We have piped to you, and you have not danced; we have lamented, and you have not wept.\n"
	"For John the Baptist came neither eating bread nor drinking wine; and you say: He hath a devil.\n"
	"The Son of man came eating and drinking; and you say: Behold a man that is a gourmander and a drinker of wine, a friend of Publicans and sinners.\n"
	"And wisdom is justified of all her children.\n"
	"And one of the Pharisees desired him to eat with him. And being entered into the house of the Pharisee, he sat down to meat.\n"
	"And behold a woman that was in the city, a sinner, as she knew that he was set down in the Pharisee's house, she brought an alabaster box of ointment;\n"
	"and standing behind beside his feet, she began to water his feet with tears, & wiped them with the hairs of her head, and kissed his feet, & anointed them with the ointment.\n"
	"And the Pharisee that had bid him, seeing it, spake within himself, saying: This man if he were a Prophet, would know certes who and what manner of woman she is which toucheth him, that she is a sinner.\n"
	"And JESUS answering said to him: Simon, I have somewhat to say unto thee. But he said: Master, say.\n"
	"A certain creditor had two debters; one did owe five hundred pence, & the other fifty.\n"
	"They having not wherewith to pay, he forgave both. Whether therefore doth love him more?\n"
	"Simon answering said: I suppose that he to whom he forgave more. But he said to him: Thou hast judged rightly.\n"
	"And turning to the woman, he said unto Simon: Doest thou see this woman? I entered into thy house, water to my feet thou didst not give; but she with tears hath watered my feet, and with her hairs hath wiped them.\n"
	"Kiss thou gavest me not; but she since I came in, hath not ceased to kiss my feet.\n"
	"With oil thou didst not anoint my head; but she with ointment hath anointed my feet.\n"
	"For the which I say to thee: Many sins are forgiven her, because she hath loved much. But to whom less is forgiven, he loveth less.\n"
	"And he said to her: Thy sins are forgiven thee.\n"
	"And they that sat together at the table began to say within themselves. Who is this that also forgiveth sins?\n"
	"And he said to the woman: Thy faith hath made thee safe, go in peace.";