const char* chap113 = "And our Lord spake to Moyses saying:\n"
	"Speak to the children of Israel, and thou shalt say to them: These are the festivities of our Lord, which you shall call holy.\n"
	"Six days ye shall do work: the seventh day, because it is the rest of the sabbath, shall be called holy. No work shall you do in it: it is the Sabbath of the Lord in all your habitations.\n"
	"These therefore are the holy festivities of the Lord, which you must celebrate in their times.\n"
	"The first month, the fourteenth day of the month at even, is the Phase of the Lord:\n"
	"and the fifteenth day of this month is the solemnity of the Azymes of the Lord. Seven days shall you eat azymes.\n"
	"The first day shall be most solemn unto you, & holy: no servile work shall you do in it:\n"
	"but you shall offer sacrifice in fire to the Lord seven days, but the seventh day shall be more solemn, & more holy: and you shall do no servile work in it.\n"
	"And our Lord spake to Moyses, saying:\n"
	"Speak to the children of Israel, and thou shalt say to them. When you shall be entered into the land, which I will give you, and shall reap your corn, you shall bring sheaves of ears, the first fruits of your harvest to the Priest:\n"
	"who shall elevate the bundle before the Lord, the next day after the Sabbath, that it may be acceptable for you, and shall sanctify it.\n"
	"And in the self-same day that the sheaf is consecrated, shall be killed a lamb without spot of a year old for an holocaust of the Lord.\n"
	"And the libaments shall be offered with it, two tenths of flour tempered with oil, for a burnt sacrifice of the Lord, and a most sweet odour: libaments also of wine, the fourth part of an hin.\n"
	"Bread, and fried barley, & frumenty, you shall not eat of the corn, until the day that you offer thereof to your God. It is a precept for ever in your generations, and all your habitations.\n"
	"You shall number therefore from the morrow after the Sabbath, wherein you did offer the sheaf of the first fruits, seven full weeks,\n"
	"unto the morrow after the seventh week be expired, that is to say fifty days, and so you shall offer a new sacrifice to the Lord,\n"
	"out of all your habitations, two loaves of first fruits, of two tenths of flour leavened, the which you shall bake for the first fruits of the Lord.\n"
	"And you shall offer with the breads seven lambs without spot of a year old, and one calf from the herd, & two rams, and they shall be for an holocaust with their libaments, for a most sweet odour to the Lord.\n"
	"You shall make a buck goat also for sin, and two lambs of a year old for hosts of pacifics.\n"
	"And when the Priest hath elevated them with the breads of the first fruits before the Lord, they shall turn to his use.\n"
	"And you shall call this day most solemn, and most holy: no servile work shall you do in it. It shall be an everlasting ordinance in all your habitations, and generations.\n"
	"And after you reap the corn of your land, you shall not cut it to the very ground: neither shall you gather the ears that remain, but you shall let them alone for the poor & for strangers. I am the Lord your God.\n"
	"And our Lord spake to Moyses, saying:\n"
	"Speak to the children of Israel: The seventh month, on the first day of the month, shall be a Sabbath, a memorial, by sounding of trumpets, and shall be called holy:\n"
	"no servile work shall you do in it, and you shall offer holocaust to the Lord.\n"
	"And our Lord spake to Moyses, saying:\n"
	"upon the tenth day of this seventh month shall be the day of expiations most solemn, and it shall be called holy: and you shall afflict your souls in it, and shall offer holocaust to the Lord.\n"
	"No servile work shall you do the time of this day: because it is a day of propitiation, that the Lord your God may become propitious unto you.\n"
	"Every soul, that is not afflicted this day, shall perish out of his people:\n"
	"and which shall do any work, the same will I destroy out of his people.\n"
	"No work therefore shall you do in it: it shall be an everlasting ordinance unto you in all your generations, and habitations.\n"
	"It is a Sabbath of resting, and you shall afflict your souls the ninth day of the month: from even until even you shall celebrate your sabbaths.\n"
	"And our Lord spake to Moyses, saying:\n"
	"Speak to the children of Israel: From the fifteenth day of this seventh month, shall be the festivity of tabernacles seven days to the Lord.\n"
	"The first day shall be called most solemn and most holy: no servile work shall you do in it. And seven days you shall offer holocausts to the Lord.\n"
	"The eighth day also shall be most solemn and most holy, and you shall offer holocausts to the Lord: for it is of assembly and collection: no servile work shall you do in it.\n"
	"These are the festivities of the Lord, which you shall call most solemn and most holy, and shall offer in them oblations to the Lord, holocausts and libaments according to the rite of every day:\n"
	"beside the sabbaths of the Lord, and your gifts and those that you shall offer by vow, or which you shall give to the Lord voluntarily.\n"
	"Therefore from the fifteenth day of the seventh month, when you shall have gathered all the fruits of your land, you shall celebrate the festivity of the Lord seven days, on the first day and the eighth shall be a sabbath, that is rest.\n"
	"And you shall take to you the first day the fruits of a most fair tree, and the branches of palms, and boughs of the tree with thick leaves, and willows of the brook, and you shall rejoice before the Lord your God.\n"
	"And you shall celebrate the solemnity thereof seven days in the year. It shall be an everlasting ordinance in your generations. The seventh month shall you celebrate the festivity,\n"
	"and shall dwell in bowers seven days, every one that is of the stock of Israel shall abide in tabernacles:\n"
	"that your posterity may learn that I made the children of Israel to dwell in tabernacles, when I brought them out of the Land of Aegypt. I^ the Lord your God.\n"
	"And Moyses spake concerning the solemnities of our Lord to the children of Israel.";