const char* chap1137 = "AND entering in, he walked through Jericho.\n"
	"And behold a man named Zachaeus: and this was a Prince of the Publicans, and he rich.\n"
	"And he sought to see JESUS what he was, and he could not for the multitude, because he was little of stature.\n"
	"And running before, he went up into a sycamore tree that he might see him: because he was to pass by it.\n"
	"And when he was come to the place, JESUS looking up, saw him, and said to him: Zachaeus, come down in haste: because this day I must abide in thy house.\n"
	"And he in haste came down, and received him rejoicing.\n"
	"And when all saw it, they murmured saying, that he turned in, to a man that was a sinner.\n"
	"But Zachaeus standing, said to our Lord: Behold the half of my goods, Lord, I give to the poor: and if I have defrauded any man of any thing, I restore fourfold.\n"
	"JESUS said to him: That this day salvation is made to this house: because that he also is the son of Abraham.\n"
	"For the Son of man is come to seek and to save that which was lost.\n"
	"They hearing these things, he added and spake a parable, for that he was nigh to Jerusalem, and because they thought that forthwith the Kingdom of God should be manifested.\n"
	"He said therefore: A certain noble man went into a far country to take to himself a kingdom, and to return.\n"
	"And calling his ten servants, he gave them ten pounds, and said to them: Occupy till I come.\n"
	"And his citizens hated him: and they sent a legacy after him, saying: We will not have this man reign over us.\n"
	"And it came to pass after he returned, having received his kingdom: and he commanded his servants to be called, to whom he gave the money; that he might know how much every man had gained by occupying.\n"
	"And the first came, saying: Lord thy pound hath gotten ten pounds.\n"
	"And he said to him: Well fare thee good servant, because thou hast been faithful in a little, thou shalt have power over ten cities.\n"
	"And the second came saying: Lord, thy pound hath made five pounds.\n"
	"And he said to him: And be thou over five cities.\n"
	"And another came, saying: Lord, lo here thy pound, which I have had laid up in a napkin.\n"
	"For I feared thee, because thou art an austere man: thou takest up that^ thou didst not set down, and thou reapest that^ which thou didst not sow.\n"
	"He saith to him: By thine own mouth I judge thee, naughty servant. Thou didst know that I am an austere man, taking up that^ I set not down, and reaping that^ which I sowed not:\n"
	"and why didst thou not give my money to the bank, and I coming might certes with usury have exacted it?\n"
	"And he said to them that stood by: Take the pound away from him, and give it to him that hath ten pounds\n"
	"And they said to him: Lord, he hath ten pounds.\n"
	"But I say to you, that to every one that hath shall be given: and from him that hath not, that also which he hath shall be taken from him.\n"
	"But as for those mine enemies that would not have me reign over them, bring them hither; and kill them before me.\n"
	"And having said these things, he went before^ ascending to Jerusalem.\n"
	"And it came to pass when he was come nigh to Bethphage and Bethania unto the mount called Olivet, he sent two of his Disciples,\n"
	"saying: Go into the town which is over against, into the which as you enter, you shall find the colt of an ass tied, on which no man ever hath sitten: loose him, and bring him.\n"
	"And if any man ask you: Why loose you him? You shall say thus to him: Because our Lord needeth his service.\n"
	"And they that were sent, went their ways, and found as he said to them, the colt standing.\n"
	"And when they loosed the colt, the owners thereof said to them: Why loose you the colt?\n"
	"But they said: Because our Lord hath need of him.\n"
	"And they brought him to JESUS. And casting their garments upon the colt, they set JESUS thereupon.\n"
	"And as he went, they spread their garments underneath in the way.\n"
	"And when he approached now to the descent of mount-Olivet, all the multitudes of them that descended, began with joy to praise God with a loud voice, for all the miracles that they had seen,\n"
	"saying: Blessed is he that cometh King in the name of our Lord, peace in Heaven, and glory on high.\n"
	"And certain Pharisees of the multitudes said to him: Master, rebuke thy disciples.\n"
	"To whom he said: I say to you, that if these hold their peace, the stones shall cry.\n"
	"And as he drew near, seeing the city, he wept upon it, saying,\n"
	"Because if thou also hadst known, and that in this thy day, the things that pertain to thy peace: but now they are hid from thine eyes.\n"
	"For the days shall come upon thee: and thy enemies shall compass thee with a trench, and inclose thee about, and straiten thee on every side,\n"
	"and beat thee flat to the ground, and thy children that are in thee: and they shall not leave in thee a stone upon a stone, because thou hast not known the time of thy visitation.\n"
	"And entering into the Temple, he began to cast out the sellers therein and the buyers,\n"
	"saying to them: It is written, That my house is the house of prayer. But you have made it a den of thieves.\n"
	"And he was teaching daily in the Temple. And the chief Priests and the Scribes and the Princes of the people sought to destroy him:\n"
	"and they found not what to do to him. For all the people was suspense, hearing him.";