const char* chap1142 = "AND in the first of the Sabboth very early they came to the monument, carrying the spices which they had prepared.\n"
	"And they found the stone rolled back from the monument.\n"
	"And going in, they found not the body of our Lord JESUS.\n"
	"And it came to pass, as they were astonished in their mind at this, behold two men stood beside them in glistering apparel.\n"
	"And when they feared and cast down their countenance toward the ground, they said unto them: Why seek you the living with the dead?\n"
	"he is not here, but is risen. Remember how he spake to you, when he yet was in Galilee,\n"
	"saying: That the Son of man must be delivered into the hands of sinners and be crucified, and the third day rise again.\n"
	"And they remembered his words.\n"
	"And going back from the monument, they told all these things to those eleven, and to all the rest.\n"
	"And it was Mary Magdalene, and Joane, and Mary of James, and the rest that were with them, which said these things to the Apostles.\n"
	"And these words seemed before them as dotage, and they did not believe them.\n"
	"But Peter rising up ran to the monument; and stooping down he saw the linen cloths lying alone, and went away marveling with himself at that which was done.\n"
	"And behold, two of them went the same day into a town which was the space of sixty furlongs from Jerusalem, named Emmaus.\n"
	"And they talked betwixt themselves of all those things that had chanced.\n"
	"And it came to pass, while they talked and reasoned with themselves, JESUS also himself approaching went with them.\n"
	"But their eyes were held that they might not know him.\n"
	"And he said to them: What are these communications that you confer one with another walking, and are sad?\n"
	"And one whose name was Cleophas, answering, said to him: Art thou only a stranger in Jerusalem, and hast not known the things that have been done in it, these days?\n"
	"To whom he said: What things? And they said, concerning JESUS of Nazareth, who was a man a Prophet, mighty in work and word before God and all the people.\n"
	"And how our chief Priests and Princes delivered him into condemnation of death, and crucified him.\n"
	"But we hoped that it was he that should redeem Israel: and now besides all this, today is the third day since these things were done.\n"
	"But certain women also of ours, made us afraid: who before it was light, were at the monument,\n"
	"and not finding his body, came, saying that they saw a vision also of Angels, who say that he is alive.\n"
	"And certain men of ours went to the monument: and they found it so as the women said, but him they found not.\n"
	"And he said to them: O foolish, and slow of heart to believe in all things which the Prophets have spoken.\n"
	"Ought not Christ to have suffered these things, and so to enter into his glory?\n"
	"And beginning from Moyses and all the Prophets, he did interpret to them in all the scriptures the things that were concerning him.\n"
	"And they drew nigh to the town whither they went: and he made semblance to go further.\n"
	"And they forced him, saying: Tarry with us, because it is toward night, and the day is now far spent. And he went in with them.\n"
	"And it came to pass, whiles he sat at the table with them, he took bread, and blessed and brake, and did reach to them.\n"
	"And their eyes were opened, and they knew him: and he vanished out of their sight.\n"
	"And they said one to the other: Was not our heart burning in us, whiles he spake in the way, and opened unto us the scriptures?\n"
	"And rising up the same hour they went back into Jerusalem: and they found the eleven gathered together, and those that were with them,\n"
	"saying: That our Lord is risen indeed, and hath appeared to Simon.\n"
	"And they told the things that were done in the way: and how they knew him in the breaking of bread.\n"
	"And whiles they speak these things, JESUS stood in the midst of them, and he saith to them: Peace be to you; it is I, fear not.\n"
	"But they being troubled and frighted, imagined that they saw a Spirit.\n"
	"And he said to them: Why are you troubled, and cogitations arise into your hearts?\n"
	"See my hands, and feet, that it is I myself: handle, and see: for a Spirit hath not flesh and bones, as you see me to have.\n"
	"And when he had said this, he shewed them his hands and feet.\n"
	"But they yet not believing and marveling for joy, he said: Have you here any thing to be eaten?\n"
	"But they offered him a piece of fish broiled, and a honey comb.\n"
	"And when he had eaten before them, taking the remains he gave to them.\n"
	"And he said to them: These are the words which I spake to you, when I was yet with you, that all things must needs be fulfilled, which are written in the law of Moyses, and the Prophets, and the Psalms, of me.\n"
	"Then he opened their understanding, that they might understand the Scriptures.\n"
	"And he said to them: That so it is written, and so it behoved Christ to suffer, and to rise again from the dead the third day:\n"
	"and penance to be preached in his name and remission of sins unto all nations, beginning from Jerusalem.\n"
	"And you are witnesses of these things.\n"
	"And I send the promise of my Father upon you: but you, tarry in the city, till you be endued with power from high.\n"
	"And he brought them forth abroad into Bethania: and lifting up his hands he blessed them.\n"
	"And it came to pass whiles he blessed them, he departed from them, and was carried into Heaven.\n"
	"And they adoring went back into Jerusalem with great joy:\n"
	"and they were always in the temple praising and blessing God. Amen.";