const char* chap1144 = "AND the third day there was a marriage made in Cana of Galilee: and the mother of JESUS was there.\n"
	"And JESUS also was called, and his Disciples to the marriage.\n"
	"And the wine failing, the mother of JESUS saith to him: They have no wine.\n"
	"And JESUS saith to her: What is to me and thee woman? My hour cometh not yet.\n"
	"His mother saith to the ministers: Whatsoever he shall say to you, do ye.\n"
	"And there were set there six water-pots of stone, according to the purification of the Jews, holding every one two or three measures.\n"
	"JESUS saith to them: Fill the water-pots with water. And they filled them up to the top.\n"
	"And JESUS saith to them: Draw now, and carry to the chief steward. And they carried it.\n"
	"And after the chief steward tasted the water made wine, and knew not whence it was, but the ministers knew that had drawn the water; the chief steward calleth the bridegroom,\n"
	"and saith to him: Every man first setteth the good wine, and when they have well drunk, then that which is worse. But thou hast kept the good wine until now.\n"
	"This beginning of miracles did JESUS in Cana of Galilee: and he manifested his glory, and his Disciples believed in him.\n"
	"After this he went down to Capharnaum himself and his mother, and his brethren, and his Disciples; and there they remained not many days.\n"
	"And the Pasch of the Jews was at hand, and JESUS went up to Jerusalem:\n"
	"and he found in the Temple them that sold oxen and sheep and doves, and the bankers sitting.\n"
	"And when he had made as it were a whip of little cords, he cast them all out of the temple, the sheep also and the oxen, and the money of the bankers he poured out, and the tables he overthrew.\n"
	"And to them that sold doves, he said: Take away these things hence, and make not the house of my Father, a house of merchandise.\n"
	"And his Disciples remembered that it is written: The zeal of thy house hath eaten me.\n"
	"The Jews therefore answered and said to him: What sign doest thou shew us, that thou doest these things?\n"
	"JESUS answered and said to them: Dissolve this temple, and in three days I will raise it.\n"
	"The Jews therefore said: In forty and six years was this temple built, & wilt thou raise it in three days?\n"
	"But he spake of the temple of his body.\n"
	"Therefore when he was risen again from the dead, his Disciples remembered, that he said this, and they believed the scripture and the word that JESUS did say.\n"
	"And when he was at Jerusalem in the Pasch, upon the festival day, many believed in his name, seeing his signs which he did.\n"
	"But JESUS did not commit himself unto them, for that he knew all,\n"
	"and because it was not needful for him that any should give testimony of man; for he knew what was in man.";