const char* chap1148 = "AFTER these things JESUS went beyond the sea of Galilee, which is of Tiberias.\n"
	"and a great multitude followed him, because they saw the signs which he did upon those that were sick.\n"
	"JESUS therefore went up into the mountain, and there he sat with his Disciples.\n"
	"And the Pasch was at hand, the festival day of the Jews.\n"
	"When JESUS therefore had lifted up his eyes, and saw that a very great multitude cometh to him, he saith to Philippe: Whence shall we buy bread, that these may eat?\n"
	"And this he said, tempting him. For himself knew what he would do?\n"
	"Philippe answered him: Two hundred penny worth of bread is not sufficient for them, that every man may take a little piece.\n"
	"One of his Disciples, Andrew the brother of Simon Peter, saith to him:\n"
	"There is a boy here that hath five barley loaves, & two fishes; but what are these among so many?\n"
	"JESUS therefore saith: Make the men to sit down. And there was much grass in the place. The men therefore sat down, in number about five thousand.\n"
	"JESUS therefore took the loaves; and when he had given thanks, he distributed to them that sat. In like manner also of the fishes as much as they would.\n"
	"And after they were filled, he said to his Disciples: Gather the fragments that are remaining, lest they be lost.\n"
	"They gathered therefore, and filled twelve baskets with fragments of the five barley loaves, which remained to them that had eaten.\n"
	"Those men therefore when they had seen what a sign JESUS had done, said, That this is the Prophet indeed that is to come into the world.\n"
	"JESUS therefore when he knew that they would come to take him, and make him king, he fled again into the mountain himself alone.\n"
	"And when even was come, his Disciples went down to the sea.\n"
	"And when they were gone up into the ship, they came beyond the sea into Capharnaum: And now it was dark and JESUS was not come unto them.\n"
	"And the sea arose, by reason of a great wind that blew.\n"
	"When they had rowed therefore about five and twenty or thirty furlongs, they see JESUS walking upon the sea, and to draw nigh to the ship, and they feared.\n"
	"But he said to them: It is I, fear not.\n"
	"They would therefore have taken him into the ship: and forthwith the ship was at the land to which they went.\n"
	"The next day, the multitude that stood beyond the sea, saw that there was no other boat there but one, and that JESUS had not entered into the boat with his Disciples, but that his Disciples only were departed.\n"
	"But other boats came in from Tiberias beside the place where they had eaten the bread, our Lord giving thanks.\n"
	"When therefore the multitude saw that JESUS was not there, nor his Disciples, they went up into the boats, & came to Capharnaum seeking JESUS.\n"
	"And when they had found him beyond the sea, they said to him: Rabbi, when camest thou hither?\n"
	"JESUS answered them, and said: Amen, amen I say to you, you seek me not because you have seen signs, but because you did eat of the loaves, and were filled.\n"
	"Work not the meat that perisheth, but that endureth unto life everlasting, which the Son of man will give you. For him the Father, God, hath signed.\n"
	"They said therefore unto him: What shall we do that we may work the works of God?\n"
	"JESUS answered, and said to them: This is the work of God, that you believe in him whom he hath sent.\n"
	"They said therefore to him: What sign therefore doest thou, that we may see, and may believe thee? what workest thou?\n"
	"Our Fathers did eat Manna in the desert as it is written, Bread from Heaven he gave them to eat.\n"
	"JESUS therefore said to them: Amen, amen I say to you, Moyses gave you not the bread from Heaven, but my Father giveth you the true bread from Heaven.\n"
	"For the bread of God it is that descended from Heaven, and giveth life to the world.\n"
	"They said therefore unto him: Lord, give us always this bread.\n"
	"And JESUS said to them: I am the bread of life, he that cometh to me, shall not hunger; and he that believeth in me, shall never thirst.\n"
	"But I said to you that both you have seen me and you believe not.\n"
	"All that the Father giveth me, shall come to me; and him that cometh to me I will not cast forth.\n"
	"Because I descended from Heaven, not to do mine own will, but the will of him that sent me.\n"
	"For this is the will of him that sent me, the Father: that all that he hath given me I leese not thereof, but raise it in the last day.\n"
	"And this is the will of my Father that sent me; that every one that seeth the Son, and believeth in him, have life everlasting, & I will raise him in the last day.\n"
	"The Jews therefore murmured at him, because he had said, I am the bread which descended from Heaven;\n"
	"and they said: Is not this JESUS the son of Joseph, whose father and mother we know? How then saith he, That I descended from Heaven?\n"
	"JESUS therefore answered and said to them: Murmur not one to another:\n"
	"no man can come to me, unless the Father that sent me, draw him, and I will raise him up in the last day.\n"
	"It is written in the Prophets: And all shall be docible of God. Every one that hath heard of the Father, & hath learned, cometh to me.\n"
	"Not that any man hath seen the Father, but he which is of God; this hath seen the Father.\n"
	"Amen, amen I say to you: He that believeth in me, hath life everlasting.\n"
	"I am the bread of life.\n"
	"Your fathers did eat Manna in the desert; and they died.\n"
	"This is the bread that descended from Heaven: that if any man eat of it, he die not.\n"
	"I am the living bread, that came down from Heaven.\n"
	"If any man eat of this bread, he shall live for ever: and the bread which I will give, is my flesh for the life of the world.\n"
	"The Jews therefore strove among themselves, saying: How can this man give us his flesh to eat?\n"
	"JESUS therefore said to them: Amen, amen I say to you, unless you eat the flesh of the Son of man, and drink his blood, you shall not have life in you.\n"
	"He that eateth my flesh, and drinketh my blood, hath life everlasting; and I will raise him up in the last day.\n"
	"For my flesh, is meat indeed: and my blood is drink indeed.\n"
	"He that eateth my flesh, and drinketh my blood, abideth in me, and I in him.\n"
	"As the living Father hath sent me, and I live by the Father: and he that eateth me, the same also shall live by me.\n"
	"This is the bread that came down from Heaven. Not as your fathers did eat Manna, and died. He that eateth this bread, shall live for ever.\n"
	"These things he said teaching in the Synagogue, in Capharnaum.\n"
	"Many therefore of his Disciples hearing it, said: This saying is hard, and who can hear it?\n"
	"But JESUS knowing with himself that his Disciples murmured at this, he said to them: Doth this scandalize you?\n"
	"If then you shall see the Son of man ascend where he was before?\n"
	"It is the spirit that quickeneth, the flesh profiteth nothing. The words that I have spoken to you, be spirit and life.\n"
	"But there be certain of you that believe not. For JESUS knew from the beginning who they were that did not believe, and who he was that would betray him.\n"
	"And he said: Therefore did I say to you, that no man can come to me, unless it be given him of my Father.\n"
	"After this^ many of his Disciples went back: and now they walked not with him.\n"
	"JESUS therefore said to the Twelve: What, will you also depart?\n"
	"Simon Peter therefore answered him: Lord, to whom shall we go? thou hast the words of eternal life.\n"
	"And we believe and have known that thou art Christ the Son of God.\n"
	"JESUS answered them: Have not I chosen you the Twelve; and of you one is a devil?\n"
	"And he meant Judas Iscariot, Simon's son: for this same was to betray him, whereas he was one of the Twelve.";