const char* chap1149 = "AFTER these things JESUS walked into Galilee, for he would not walk into Jewry: because the Jews sought to kill him.\n"
	"And the festival day of the Jews, Scenopegia, was at hand.\n"
	"And his brethren said to him: Pass from hence, and go into Jewry; that thy Disciples also may see thy works which thou doest.\n"
	"For no man doeth any thing in secret, and seeketh himself to be in public. If thou do these things, manifest thyself to the world.\n"
	"For neither did his brethren believe in him.\n"
	"JESUS therefore saith to them: My time is not yet come; but your time is always ready.\n"
	"The world cannot hate you, but me it hateth: because I give testimony of it, that the works thereof are evil.\n"
	"Go you up to this festival day: I go not up to this festival day; because my time is not yet accomplished.\n"
	"When he had said these things, himself tarried in Galilee.\n"
	"But after his brethren were gone up, then he also went up to the festival day, not openly, but as it were in secret.\n"
	"The Jews therefore sought him in the festival day, and said: Where is he?\n"
	"And there was much murmuring in the multitude of him. For certain said: That he is good. And others said: No, but he seduceth the multitudes.\n"
	"Yet no man spake openly of him for fear of the Jews.\n"
	"And when the festivity was now half done, JESUS went up into the temple, and taught.\n"
	"And the Jews marveled, saying: How doth this man know letters, whereas he hath not learned?\n"
	"JESUS answered them, and said: My doctrine is not mine, but his that sent me.\n"
	"If any man will do the will of him, he shall understand of the doctrine whether it be of God, or I speak of myself.\n"
	"He that speaketh of himself, seeketh his own glory. But he that seeketh the glory of him that sent him, he is true, and injustice in him there is not.\n"
	"Did not Moyses give you the law, and none of you doeth the law?\n"
	"Why seek you to kill me? The multitude answered, and said, Thou hast a devil, who seeketh to kill thee?\n"
	"JESUS answered and said to them: One work I have done; and you do all marvel.\n"
	"Therefore Moyses gave you circumcision: not that it is of Moyses, but of the fathers, and in the Sabboth you circumcise a man.\n"
	"If a man receive circumcision in the Sabboth, that the law of Moyses be not broken; are you angry at me because I have healed a man wholly in the Sabboth?\n"
	"Judge not according to the face, but judge just judgement.\n"
	"Certain therefore of Jerusalem said: Is not this he whom they seek to kill?\n"
	"And behold, he speaketh openly, and they say nothing to him. Have the Princes known indeed that this is CHRIST?\n"
	"But this man we know whence he is. But when CHRIST cometh, no man knoweth whence he is.\n"
	"JESUS therefore cried in the temple teaching and saying: Both me you do know, and whence I am you know. And of myself I am not come, but he is true that sent me, whom you know not.\n"
	"I know him, because I am of him, and he sent me.\n"
	"They sought therefore to apprehend him: and no man laid hands upon him, because his hour was not yet come.\n"
	"But of the multitude many believed in him, and said: CHRIST, when he cometh shall he do more signs than these which this man doeth?\n"
	"The Pharisees heard the multitude murmuring these things touching him: and the Princes and Pharisees sent Ministers to apprehend him.\n"
	"JESUS therefore said to them: Yet a little time I am with you: and I go to him that sent me.\n"
	"You seek me, and shall not find: and where I am, you cannot come.\n"
	"The Jews therefore said among themselves, whither will this man go, that we shall not find him? will he go into the dispersion of the Gentiles, and teach the Gentiles?\n"
	"What is this saying that he hath said: You shall seek me, and shall not find; and where I am, you cannot come.\n"
	"And in the last, the great day of the festivity JESUS stood and cried, saying: If any man thirst, let him come to me, and drink.\n"
	"He that believeth in me, as the scripture saith, Out of his belly shall flow rivers of living water.\n"
	"(And this he said of the Spirit that they should receive which believed in him. For as yet the Spirit was not given: because JESUS was not yet glorified.)\n"
	"Of that multitude therefore, when they had heard these words of his, some said: This is the Prophet indeed.\n"
	"Others said: This is CHRIST. But certain said: Why, doth CHRIST come from Galilee?\n"
	"Doth not the scripture say: That of the seed of David, and from Bethlehem the town where David was, CHRIST doth come?\n"
	"Therefore there arose dissension in the multitude for him.\n"
	"And certain of them would have apprehended him: but no man laid hands upon him.\n"
	"The ministers therefore came to the chief Priests and the Pharisees. And they said to them: Why have you not brought him?\n"
	"The Ministers answered: Never did there man so speak, as this man.\n"
	"The Pharisees therefore answered them: Why, are you also seduced?\n"
	"Hath any of the Princes believed in him, or of the Pharisees?\n"
	"but this multitude that knoweth not the law, are accursed.\n"
	"Nicodemus said to them, he that came to him by night, who was one of them:\n"
	"Doth our law judge a man, unless it first hear him, and know what he doeth?\n"
	"They answered & said to him: Why, art thou also a Galilaean? Search, & see that from Galilee a Prophet riseth not.\n"
	"And every man returned to his house.";