const char* chap1151 = "AND JESUS passing by, saw a man blind: from his nativity;\n"
	"and his Disciples asked him: Rabbi, who hath sinned, this man, or his parents, that he should be born blind? JESUS answered:\n"
	"Neither hath this man sinned, nor his parents; but that the works of God may be manifested in him.\n"
	"I must work the works of him that sent me, whiles it is day. The night cometh, when no man can work.\n"
	"As long as I am in the world, I am the light of the world.\n"
	"When he had said these things, he spit on the ground, and made clay of the spittle, and spread the clay upon his eyes,\n"
	"and said to him: Go, wash in the pool of Siloe, which is interpreted, Sent. He went therefore, and washed; and he came seeing.\n"
	"Therefore the neighbours, and they which had seen him before, that he was a beggar, said: Is not this he that sat, and begged? Others said: That this is he.\n"
	"But others: No, not so, but he is like him. But he said: That I am he.\n"
	"They said therefore to him: How were thine eyes opened?\n"
	"He answered: That man that is called JESUS, made clay, and anointed mine eyes, and said to me: Go to the pool of Siloe, and wash. And I went, and washed, and saw.\n"
	"And they said to him: Where is he? He saith: I know not.\n"
	"They bring him that had been blind, to the Pharisees.\n"
	"And it was the Sabboth when JESUS made the clay, and opened his eyes.\n"
	"Again therefore the Pharisees asked him, how he saw. But he said to them: He put clay upon mine eyes, & I washed; and I see.\n"
	"Certain therefore of the Pharisees said: This man is not of God, that keepeth not the Sabboth. But others said: How can a man that is a sinner do these signs? And there was a schism among them.\n"
	"They say therefore to the blind again: Thou, what sayest thou of him that opened thine eyes? And he said: That he is a Prophet.\n"
	"The Jews therefore did not believe of him, that he had been blind and saw, until they called the parents of him that saw,\n"
	"and asked them, saying: Is this your son, whom you say that he was born blind? how then doth he now see?\n"
	"His parents answered them, and said: We know that this is our son, and that he was born blind;\n"
	"but how he now seeth, we know not, or who hath opened his eyes, we know not, ask himself; he is of age, let himself speak of himself.\n"
	"These things his parents said, because they feared the Jews. For the Jews had now conspired, that if any man should confess him to be CHRIST, he should be put out of the Synagogue.\n"
	"Therefore did his parents say: That he is of age, ask himself.\n"
	"They therefore again called the man that had been blind, and said to him: Give glory to God. We know that this man is a sinner.\n"
	"He therefore said to them: Whether he be a sinner, I know not: one thing I know, that whereas I was blind, now I see.\n"
	"They said therefore to him: What did he to thee? how did he open thine eyes?\n"
	"He answered them: I have now told you, and you have heard; why will you hear it again? will you also become his Disciples?\n"
	"They reviled him therefore, & said: Be thou his Disciple: but we are the Disciples of Moyses.\n"
	"We know that to Moyses God did speak; but this man we know not whence he is.\n"
	"The man answered and said to them: For in this it is marvelous that you know not whence he is, and he hath opened mine eyes.\n"
	"And we know that sinners God doth not hear. But if a man be a server of God, and do the will of him, him he heareth.\n"
	"From the beginning of the world it hath not been heard that any man hath opened the eyes of one born blind.\n"
	"unless this man were of God, he could not do any thing.\n"
	"They answered and said to him: Thou wast wholly born in sins, and doest thou teach us? And they did cast him forth.\n"
	"JESUS heard that they cast him forth; & when he had found him, he said to him: Doest thou believe in the Son of God?\n"
	"He answered, and said: Who is he Lord, that I may believe in him?\n"
	"And JESUS said to him: Both thou hast seen him; and he that talketh with thee, he it is.\n"
	"But he said, I believe Lord. And falling down he adored him.\n"
	"And JESUS said to him: For judgement came I into this world; that they that see not, may see: and they that see, may become blind.\n"
	"And certain of the Pharisees that were with him, heard; and they said to him: Why, are we also blind?\n"
	"JESUS said to them: If you were blind, you should not have sin, but now you say, That we see. Your sin remaineth.";