const char* chap1152 = "AMEN, amen I say to you, he that entereth not by the door into the fold of the sheep, but climbeth up another way; he is a thief and a robber.\n"
	"But he that entereth by the door, is the Pastor of the sheep.\n"
	"To this man the porter openeth; and the sheep hear his voice: and he calleth his own sheep by name, and leadeth them forth.\n"
	"And when he hath let forth his own sheep, he goeth before them: and the sheep follow him, because they know his voice.\n"
	"But a stranger they follow not, but fly from him because they know not the voice of strangers.\n"
	"This proverb JESUS said to them. But they knew not what he spake to them.\n"
	"JESUS therefore said to them again: Amen, amen I say to you, that I am the door of the sheep.\n"
	"And how many soever have come, are thieves and robbers: but the sheep heard them not.\n"
	"I am the door. By me if any enter, he shall be saved: & he shall go in and shall go out, & shall find pastures.\n"
	"The thief cometh not but to steal and kill & destroy. I came that they may have life, & may have more aboundantly.\n"
	"I am the good Pastor.\n"
	"The good Pastor giveth his life for his sheep. But the hireling & he that is not the Pastor, whose own the sheep are not, seeth the wolf coming, and leaveth the sheep, and flyeth: and the wolf raveneth, and disperseth the sheep.\n"
	"And the hireling flyeth because he is a hireling; and he hath no care of the sheep.\n"
	"I am the good Pastor; and I know mine, and mine know me.\n"
	"As the Father knoweth me, and I know the Father: and I yield my life for my sheep.\n"
	"And other sheep I have that are not of this fold: them also I must bring, and they shall hear my voice, and there shall be made one fold and one Pastor.\n"
	"Therefore the Father loveth me: because I yield my life, that I may take it again.\n"
	"No man taketh it away from me: but I yield it of myself. And I have power to yield it: and I have power to take it again. This commandment I received of my Father.\n"
	"A dissension rose again among the Jews for these words.\n"
	"And many of them said: He hath a devil and is mad; why hear you him?\n"
	"Others said: These are not the words of one that hath a devil. Can a devil open the eyes of blind men?\n"
	"And the Dedication was in Jerusalem: and it was winter.\n"
	"And JESUS walked in the temple, in Salomon's porch.\n"
	"The Jews therefore compassed him round about, and said to him: How long doest thou hold our soul in suspense? if thou be CHRIST, tell us openly.\n"
	"JESUS answered them: I speak to you; and you believe not; the works that I do in the name of my Father, they give testimony of me.\n"
	"But you do not believe, because you are not of my sheep.\n"
	"My sheep hear my voice; and I know them, and they follow me.\n"
	"And I give them life everlasting; and they shall not perish for ever, and no man shall pluck them out of my hand.\n"
	"My Father, that which he hath given me, is greater than all: and no man can pluck them out of the hand of my Father.\n"
	"I and the Father are one.\n"
	"The Jews took up stones, to stone him.\n"
	"JESUS answered them: Many good works I have shewed you from my Father, for which of those works do you stone me?\n"
	"The Jews answered him: For a good work we stone thee not, but for blasphemy, and because thou being a man, makest thyself God.\n"
	"JESUS answered them: Is it not written in your law, that I said, you are gods?\n"
	"If he called them gods, to whom the word of God was made, and the scripture cannot be broken;\n"
	"whom the Father hath sanctified and sent into the world, say you, That thou blasphemest, because I said I am the Son of God?\n"
	"If I do not the works of my Father, believe me not.\n"
	"But if I do, and if you will not believe me, believe the works: that you may know and believe that the Father is in me, and I in the Father.\n"
	"They sought therefore to apprehend him; and he went forth out of their hands.\n"
	"And he went again beyond Jordan into that place where John was baptizing first; and he tarried there.\n"
	"and many came to him, and they said: That John indeed did no sign. But all things whatsoever John said of this man, were true.\n"
	"And many believed in him.";