const char* chap1164 = "THE first treatise I made of all things, O Theophilus, which JESUS began to do and to teach,\n"
	"until the day wherein giving commandment by the Holy Ghost to the Apostles whom he chose, he was assumpted.\n"
	"to whom he shewed also himself alive after his passion in many arguments, for forty days appearing to them, and speaking of the Kingdom of God.\n"
	"And eating with them, he commanded them, that they should not depart from Jerusalem, but should expect the promise of the Father, which you have heard (saith he) by my mouth:\n"
	"for John indeed baptized with water, but you shall be baptized with the Holy Ghost after these few days.\n"
	"They therefore that were assembled, asked him, saying: Lord, whether at this time wilt thou restore the Kingdom to Israel?\n"
	"but he said to them: It is not for you to know times or moments, which the Father hath put in his own power:\n"
	"but you shall receive the virtue of the Holy Ghost coming upon you, and you shall be witnesses unto me in Jerusalem, and in all Jewry, and Samaria, and even to the utmost of the earth.\n"
	"And when he had said these things, in their sight he was elevated: & a cloud received him out of their sight.\n"
	"And when they beheld him going into Heaven, behold two men stood beside them in white garments,\n"
	"who also said: Ye men of Galilee, why stand you looking into Heaven? This JESUS which is assumpted from you into Heaven, shall so come as you have seen him going into Heaven.\n"
	"Then they returned to Jerusalem from the mount that is called Olivet, which is by Jerusalem, distant a Sabboth's journey.\n"
	"And when they were entered in, they went up into an upper chamber, where abode Peter & John, James and Andrew, Philippe and Thomas, Bartholomew and Matthew, James of Alphaeus and Simon Zelotes, and Jude of James.\n"
	"All these were persevering with one mind in prayer with the women and MARY the mother of JESUS, and his brethren.\n"
	"In those days Peter rising up in the midst of the Brethren, said: (and the multitude of persons together, was almost an hundred and twenty.)\n"
	"You men, brethren, the scripture must be fulfilled which the Holy Ghost spake before by the mouth of David concerning Judas, who was the captain of them that apprehended JESUS:\n"
	"who was numbered among us and obtained the lot of this ministry.\n"
	"And he indeed hath possessed a field of the reward of iniquity, and being hanged he burst in the midst, and all his bowels gushed out.\n"
	"And it was made notorious to all the inhabitants of Jerusalem: so that the same field was called in their tongue, Hacel-dema, that is to say, the field of blood.\n"
	"For it is written in the book of Psalms: Be their habitation made desert, & be there none to dwell in it. And his Bishopric let another take.\n"
	"Therefore, of these men that have assembled with us, all the time that our Lord JESUS went in and went out among us,\n"
	"beginning from the Baptism of John until the day wherein he was assumpted from us, there must one of these be made a witness with us of his resurrection.\n"
	"And they appointed two, Joseph, who was called Barsabas, who was surnamed Justus: and Matthias.\n"
	"And praying they said: Thou Lord that knowest the hearts of all men, shew of these two, one, whom thou hast chosen,\n"
	"to take the place of this ministry & Apostleship, from the which Judas hath prevaricated that he might go to his own place.\n"
	"And they gave them lots, and the lot fell upon Matthias, and he was numbered with the eleven Apostles.";