const char* chap1198 = "ARE you ignorant, brethren, (for I speak to them that know the Law) that the Law hath dominion over a man as long time as he liveth?\n"
	"For the woman that is under a husband; her husband living is bound to the law. But if her husband be dead, she is loosed from the law of her husband.\n"
	"Therefore her husband living, she shall be called an adulteress if she be with another man: but if her husband be dead^ she is delivered from the law of her husband: so that she is not and adulteress if she be with another man.\n"
	"Therefore my brethren you also are made dead to the Law by the body of Christ; that you may be another man's who is risen again from the dead, that we may fructify to God.\n"
	"For when we were in the flesh, the passions of sins that were by the Law, did work in our members, to fructify unto death.\n"
	"But now we are loosed from the law of death wherein we were detained: in so much we serve in newness of spirit, and not in the oldness of the letter.\n"
	"What shall we say then? Is the Law sin? God forbid. But sin I did not know, but by the Law: for concupiscence I knew not, unless the Law did say: Thou shalt not covet.\n"
	"But occasion being taken, sin by the commandment wrought in me all concupiscence. For without the Law sin was dead.\n"
	"And I lived without the Law sometime. But when the commandment was come, sin revived.\n"
	"And I was dead. And the commandment, that was unto life, the same to me was found to be unto death.\n"
	"For sin taking occasion by the commandment, seduced me, and by it killed me.\n"
	"Therefore the Law indeed is holy, and the commandment holy, and just, and good.\n"
	"That then which is good, to me was it made death? God forbid. But sin, that it may appear sin, by the good thing wrought me death: that sin might become sinning above measure by the commandment.\n"
	"For we know that the Law is spiritual, but I am carnal, sold under sin.\n"
	"For that which I work, I understand not. For not that which I will, the same do I, but which I hate, that I do.\n"
	"And if that which I will not, the same I do; I consent to the Law, that it is good.\n"
	"But now, not I work it any more, but the sin that dwelleth in me.\n"
	"For I know that there dwelleth not in me, that is to say, in my flesh, good. For to will, is present with me, but to accomplish that which is good, I find not.\n"
	"For not the good which I will, that do I; but the evil which I will not, that I do.\n"
	"And if that which I will not, the same I do: now not I work it, but the sin that dwelleth in me.\n"
	"I find therefore, the Law, to me having a will to do good, that evil is present with me.\n"
	"For I am delighted with the Law of God according to the inward man:\n"
	"but I see another law in my members, repugning to the law of my mind, and captiving me in the law of sin that is in my members.\n"
	"Unhappy man that I am, who shall deliver me from the body of this death?\n"
	"The grace of God by JESUS Christ our Lord. Therefore I myself with the mind serve the law of God, but with the flesh, the law of sin.";