const char* chap1200 = "I SPEAK the verity in Christ, I lie not, my conscience bearing me witness in the Holy Ghost,\n"
	"that I have great sadness & continual sorrow in my heart.\n"
	"For I wished myself to be an anathema from Christ for my brethren, who are my kinsmen according to the flesh,\n"
	"who are Israelites, whose is the adoption of sons, and the glory, and the testament, and the law-giving, & the service, and the promises:\n"
	"whose are the fathers, & of whom Christ is according to the flesh, who is above all things God blessed for ever. Amen.\n"
	"But not that the word of God is frustrate. For, not all that are of Israel, they be Israelites:\n"
	"nor they that are the seed of Abraham, all be children: but in Isaac shall the seed be called unto thee:\n"
	"that is to say, not they that are the children of the flesh, they are the children of God: but they that are the children of the promise, are esteemed for the seed.\n"
	"For the word of the promise is this: According to this time will I come; & Sara shall have a son.\n"
	"And not only she, But Rebecca also conceiving of one copulation, of Isaac our father.\n"
	"For when they were not yet born, nor had done any good or evil (that the purpose of God according to election might stand)\n"
	"not of works, but of the caller it was said to her: That the elder shall serve the younger,\n"
	"as it is written: Jacob I loved, but Esau I hated.\n"
	"What shall we say then? Is there iniquity with God? God forbid.\n"
	"For to Moyses he saith: I will have mercy on whom I have mercy; and I will shew mercy to whom I will shew mercy.\n"
	"Therefore it is not of the willer, nor the runner, but of God that sheweth mercy.\n"
	"For the Scripture saith to Pharao: That to this purpose have I raised thee, that in thee I may shew my power; and that my name may be renowned in the whole earth.\n"
	"Therefore on whom he will, he hath mercy; and whom he will, he doth indurate.\n"
	"Thou sayst therefore unto me: Why doth he yet complain? for who resisteth his will?\n"
	"O man, who art thou that doest answer God? Doth the work say to him that wrought it: Why hast thou made me thus?\n"
	"Or hath not the potter of clay, power, of the same mass to make one vessel unto honour, and another unto contumely?\n"
	"And if God willing to shew wrath, & to make his might known, sustained in much patience the vessels of wrath apt to destruction,\n"
	"that he might shew the riches of his glory upon the vessels of mercy which he prepared unto glory.\n"
	"Whom also he hath called, us, not only of the Jews, but also of the Gentiles,\n"
	"as in Osee he saith: I will call that which is not my people, my people; & her that was not beloved, beloved: & her that hath not obtained mercy, having obtained mercy.\n"
	"And it shall be, in the place where it was said to them, you are not my people: there they shall be called the sons of the living God.\n"
	"And Esaie cryeth for Israel: If the number of the children of Israel be as the sand of the sea, the remains shall be saved.\n"
	"For consummating a word, and abridging it in equity: because a word abridged shall our Lord make upon the earth.\n"
	"And as Esay foretold: unless the Lord of Sabaoth had left us seed, we had been made like Sodom, and we had been like as Gomorrha.\n"
	"What shall we say then? That the Gentiles which pursued not after justice, have apprehended justice, but the justice that is of faith.\n"
	"But Israel in pursuing the law of justice, is not come unto the law of justice.\n"
	"Why so? Because not of faith, but as it were of works. For they have stumbled at the stone of stumbling,\n"
	"as it is written: Behold I put in Sion a stone of stumbling, and a rock of scandal: and whosoever believeth in him, shall not be confounded.";