const char* chap1204 = "Let every soul be subject to higher powers, for there is no power but of God. And those that are, of God are ordained.\n"
	"Therefore he that resisteth the power, resisteth the ordinance of God. And they that resist, purchase to themselves damnation.\n"
	"For princes are no fear to the good work, but to the evil. But wilt thou not fear the power? Do good: and thou shalt have praise of the same.\n"
	"For he is God's minister unto thee for good. But if thou do evil, fear; for he beareth not the sword without cause. For he is God's minister: a revenger unto wrath, to him that doeth evil.\n"
	"Therefore be subject of necessity, not only for wrath, but also for conscience sake.\n"
	"For therefore you give tributes also. For they are the ministers of God, serving unto this purpose.\n"
	"Render therefore to all men their dew: to whom tribute, tribute: to whom custom, custom: to whom fear, fear; to whom honour, honour.\n"
	"Owe no man any thing: but that you love one another. For he that loveth his neighbour, hath fulfilled the law.\n"
	"For, Thou shalt not commit adultery, Thou shalt not kill, Thou shalt not steal. Thou shalt not bear false witness, Thou shalt not covet, and if there be any other commandment, it is comprised in this word, Thou shalt love thy neighbour as thyself.\n"
	"The love of thy neighbour, worketh no evil. Love therefore is the fullness of the Law.\n"
	"And that knowing the season, that it is now the hour for us to rise from sleep. For now our salvation is nearer than when we believed.\n"
	"The night is passed, and the day is at hand. Let us therefore cast off the works of darkness, & do on the armour of light.\n"
	"As in the day let us walk honestly: not in banquetings and drunkenness, not in chamberings and impudicities, not in contention and emulation:\n"
	"but do ye on our Lord JESUS Christ, and make not provision for the flesh in concupiscences.";