const char* chap1206 = "AND we that are the stronger, must sustain the infirmities of the weak, & not please ourselves.\n"
	"Let every one of you please his neighbour unto good, to edification.\n"
	"For, Christ did not please himself, but as it is written: The reproaches of them that reproached thee, fell upon me.\n"
	"For what things soever have been written, to our learning they are written: that by the patience and consolation of the Scriptures, we may have hope.\n"
	"And the God of patience and of comfort give you to be of one mind one toward another according to JESUS Christ:\n"
	"that of one mind, with one mouth you may glorify God & the Father of our Lord JESUS Christ.\n"
	"For the which cause receive one another; as Christ also hath received you unto the honour of God.\n"
	"For I say Christ JESUS to have been minister of the circumcision for the verity of God to confirm the promises of the fathers.\n"
	"But the Gentiles to honour God for his mercy, as it is written: Therefore will I confess to thee in the Gentiles o Lord, and will sing to thy name.\n"
	"And again he saith: Rejoice ye Gentiles with his people.\n"
	"And again: Praise^ all ye Gentiles^ our Lord; and magnify him all ye peoples.\n"
	"And again Esaie saith: There shall be the root of Jesse; and he that shall rise up to rule the Gentiles, in him the Gentiles shall hope.\n"
	"And the God of hope replenish you with all joy and peace in believing; that you may abound in hope, and in the virtue of the Holy Ghost.\n"
	"And I myself also, my brethren, am assured of you, that you also are full of love, replenished with all knowledge, so that you are able to admonish one another.\n"
	"But I have written to you (brethren) more boldly in part, as it were putting you in remembrance; for the grace which is given me of God,\n"
	"to be the minister of Christ JESUS in the Gentiles: sanctifying the Gospel of God, that the oblation of the Gentiles may be made acceptable and sanctified in the Holy Ghost.\n"
	"I have therefore glory in Christ JESUS toward God.\n"
	"For I dare not speak any of those things which Christ worketh not by me for the obedience of the Gentiles, by word and deeds,\n"
	"in the virtue of signs and wonders, in the virtue of the Holy Ghost: so that from Jerusalem round about unto Illyricum I have replenished the Gospel of Christ.\n"
	"And I have so preached this Gospel, not where Christ was named, lest I should build upon another man's foundation;\n"
	"but as it is written: They to whom it hath not been preached of him, shall see, and they that have not heard, shall understand.\n"
	"For the which cause also I was hindered very much from coming unto you.\n"
	"But now having no longer place in these countries, and having a desire to come unto you these many years now passed:\n"
	"when I shall begin to take my journey into Spain, I hope that as I pass, I shall see you, and be brought thither of you, if first in part I shall have enjoyed you.\n"
	"Now therefore I will go unto Jerusalem to minister to the saints.\n"
	"For Macedonia and Achaia have liked well to make some contribution upon the poor saints that are in Jerusalem.\n"
	"For it hath pleased them: and they are their debters. For if the Gentiles be made partakers of their spiritual things; they ought also in carnal things to minister unto them.\n"
	"This therefore when I shall have accomplished, and signed them this fruit, I will go by you into Spain.\n"
	"And I know that coming to you, I shall come in aboundance of the blessing of Christ.\n"
	"I beseech you therefore brethren by our Lord JESUS CHRIST, and by the charity of the Holy Ghost, that you help me in your prayers for me to God,\n"
	"that I may be delivered from the infidels that are in Jewry, and the oblation of my service may become acceptable in Jerusalem to the saints,\n"
	"that I may come to you in joy by the will of God, that I may be refreshed with you.\n"
	"And the God of peace be with you all. Amen.";