const char* chap1210 = "AND I, brethren, could not speak to you as to spiritual, but as to carnal. As it were to little ones in Christ,\n"
	"I gave you milk to drink, not meat: for you could not as yet. But neither can you now verily, for yet you are carnal.\n"
	"For whereas there is among you emulation and contention, are you not carnal, and walk according to man?\n"
	"For when one saith, I certes am Paul's, & another, I^ Apollo's; are you not men? What is Apollo then? and what is Paul?\n"
	"The Ministers of him whom you have believed, and to every one as our Lord hath given.\n"
	"I planted, Apollo watered; but God gave the increase.\n"
	"Therefore neither he that planteth is any thing, nor he that watereth; but he that giveth the increase, God.\n"
	"And he that planteth and he that watereth are one. And every one shall receive his own reward according to his own labour.\n"
	"For we are God's coadjutors; you are God's husbandry, you are God's building.\n"
	"According to the grace that is given me, as a wise workmaster have I laid the foundation: and another buildeth thereupon. But let every one look how he buildeth thereon.\n"
	"For other foundation no man can lay, beside that which is laid; which is CHRIST JESUS.\n"
	"And if any man build upon this foundation, gold, silver, precious stones, wood, hay, stubble,\n"
	"the work of every one shall be manifest: for the day of our Lord will declare, because it shall be revealed in fire: and the work of every one of what kind it is, the fire shall try.\n"
	"If any man's work abide, which he built thereupon; he shall receive reward.\n"
	"If any man's work burn, he shall suffer detriment: but himself shall be saved: yet so as by fire.\n"
	"Know you not that you are the temple of God; and the Spirit of God dwelleth in you?\n"
	"But if any violate the temple of God, God will destroy him. For the temple of God is holy: which you are.\n"
	"Let no man seduce himself: if any man seem to be wise among you in this world, let him become a fool that he may be wise.\n"
	"For the wisdom of this world is foolishness with God. For it is written: I will compass the wise in their subtlety.\n"
	"And again, Our Lord knoweth the cogitations of the wise that they be vain.\n"
	"Let no man therefore glory in men. For all things are yours:\n"
	"whether it be Paul, or Apollo, or Cephas, or the world, or life, or death, or things present, or things to come; for all are yours:\n"
	"and you are Christ's, and Christ is God's.";