const char* chap1211 = "SO let a man esteem us as the ministers of Christ, and the dispensers of the mysteries of God.\n"
	"Here now is required among the dispensers that a man be found faithful.\n"
	"But to me it is a thing of least account, to be judged of you, or of man's day: But I judge not my-self neither.\n"
	"For I am not guilty in conscience of any thing; but I am not justified herein: but he that judgeth me, is our Lord.\n"
	"Therefore judge not before the time; until our Lord do come, who also will lighten the hidden things of darkness, & will manifest the counsels of the hearts: & then the praise shall be to every man of God.\n"
	"But these things, brethren, I have transfigured into myself and Apollo, for you; that in us you may learn, one not to be puffed up against another, above that is written.\n"
	"For who discerneth thee? Or what hast thou that thou hast not received? And if thou hast received, what doest thou glory as though thou hast not received?\n"
	"Now you are filled, now are you become rich: without us you reign; & I would to God you did reign, that we also might reign with you.\n"
	"For I think that God hath shewed us Apostles the last, as it were deputed to death: because we are made a spectacle to the world, and to Angels and men.\n"
	"We are fools for Christ; but you wise in Christ. We weak; but you strong. You noble, but we base.\n"
	"Until this hour we do both hunger, and thirst, and are naked, and are beaten with buffets, and are wanderers,\n"
	"and labour working with our own hands. We are cursed; and do bless. We are persecuted; and sustain it.\n"
	"We are blasphemed; and we beseech. We are made the refuse of this world, the dross of all even until now.\n"
	"Not to confound you, do I write these things; but as my dearest children I admonish you.\n"
	"For if you have ten thousand Paedagogues in Christ; yet not many fathers. For in Christ JESUS by the Gospel I begat you.\n"
	"I beseech you therefore be followers of me.\n"
	"Therefore have I sent to you Timothee, who is my dearest son and faithful in our Lord; who will put you in mind of my ways that are in Christ JESUS, as everywhere in every Church I teach.\n"
	"As though I would not come to you, so certain are puffed up.\n"
	"But I will come to you quickly, if our Lord will: and will know not the words of them that be puffed up, but the power.\n"
	"For the Kingdom of God is not in words, but in power.\n"
	"What will you? in rod that I come to you; or in charity, and the spirit of mildness?";