const char* chap1217 = "FOR I will not have you ignorant, brethren, that our fathers were all under the cloud, & all passed through the sea,\n"
	"and all in Moyses were baptized in the cloud and in the sea:\n"
	"and all did eat the same spiritual food,\n"
	"and all drunk the same spiritual drink (and they drunk of the spiritual rock that followed them, and the rock was Christ.)\n"
	"But in the more part of them God was not well pleased. For they were overthrown in the desert.\n"
	"And these things were done in a figure of us, that we be not coveting evil things, as they also coveted.\n"
	"Neither become ye idolaters, as certain of them: as is written: The people sat down to eat and drink, and rose up to play.\n"
	"Neither let us fornicate, as certain of them did fornicate, and there fell in one day three and twenty thousand.\n"
	"Neither let us tempt Christ, as certain of them tempted, and perished by the serpents.\n"
	"Neither do you murmur, as certain of them murmured, and perished by the destroyer.\n"
	"And all these things chanced to them in figure: but they are written to our correption, upon whom the ends of the world are come.\n"
	"Therefore he that thinketh himself to stand, let him take heed lest he fall.\n"
	"Let not tentation apprehend you, but human. And God is faithful, who will not suffer you to be tempted above that which you are able: but will make also with tentation issue, that you may be able to sustain.\n"
	"For the which cause, my dearest, fly from the serving of idols.\n"
	"I speak as to wise men: yourselves judge what I say.\n"
	"The chalice of benediction which we do bless, is it not the communication of the blood of Christ? and the bread which we break, is it not the participation of the body of our Lord?\n"
	"For being many, we are one bread, one body, all that participate of one bread.\n"
	"Behold Israel according to the flesh: they that eat the hosts, are they not partakers of the altar?\n"
	"What then? do I say that that which is immolated to idols, is any thing? or that the idol is any thing?\n"
	"But the things that the heathen do immolate, to devils they do immolate, and not to God. And I will not have you become fellows of devils.\n"
	"You cannot drink the chalice of our Lord, and the chalice of devils: you cannot be partakers of the table of our Lord, and of the table of devils.\n"
	"Or do we emulate our Lord? Why, are we stronger than he? All things are lawful for me, but all things are not expedient.\n"
	"All things are lawful for me, but all things do not edify.\n"
	"Let no man seek his own, but another man's.\n"
	"All that is sold in the shambles, eat: asking no question for conscience.\n"
	"The earth is our Lord's, and the fullness thereof.\n"
	"If any invite you of the infidels, and you will go; eat of all that is set before you, asking no question for conscience.\n"
	"But if any man say, This is immolated to idols; do not eat for his sake that shewed it, and for conscience:\n"
	"conscience I say not thine but the other's. For why is my liberty judged of another man's conscience?\n"
	"If I participate with thanks; why am I blasphemed for that which I give thanks for?\n"
	"Therefore whether you eat, or drink, or do any other thing; do all things unto the glory of God.\n"
	"Be without offence to the Jews & to the Gentiles, & to the Church of God:\n"
	"as I also in all things do please all men, not seeking that which is profitable to myself, but which is to many; that they may be saved.";