const char* chap1218 = "BE ye followers of me, as I also of Christ.\n"
	"And I praise you brethren, that in all things you be mindful of me: and as I have delivered unto you, you keep my precepts.\n"
	"And I will have you know, that the head of every man, is Christ: and the head of the woman, is the man: and the head of Christ, is God.\n"
	"Every man praying or prophesying with his head covered, dishonoureth his head.\n"
	"But every woman praying or prophesying with her head not covered, dishonoureth her head: for it is all one as if she were made bald.\n"
	"For if a woman be not covered, let her be polled. But if it be a foul thing for a woman to be polled or made bald, let her cover her head.\n"
	"The man truly ought not to cover his head, because he is the image and glory of God; but the woman is the glory of the man.\n"
	"For the man is not of the woman, but the woman of the man.\n"
	"For the man was not created for the woman, but the woman for the man.\n"
	"(Therefore ought the woman to have power upon her head for the Angels.)\n"
	"But yet neither the man without the woman; nor the woman without the man, in our Lord.\n"
	"For as the woman is of the man, so also the man by the woman: but all things of God.\n"
	"Yourselves judge: doth it become a woman not covered to pray unto God?\n"
	"Neither doth nature itself teach you, that a man indeed if he nourish his hair, it is an ignominy for him:\n"
	"but if a woman nourish her hair, it is a glory for her, because hair is given her for a veil?\n"
	"But if any man seem to be contentious, we have no such custom, nor the CHURCH of God.\n"
	"And this I command: not praising it, that you come together not to better, but to worse.\n"
	"First indeed when you come together into the Church, I hear that there are schisms among you, and in part I believe it.\n"
	"For there must be heresies also: that they also which are approved, may be made manifest among you.\n"
	"When you come therefore together in one, it is not now to eat our Lord's supper.\n"
	"For every one taketh his own supper before to eat. And one certes is an hungered, and another is drunk.\n"
	"Why, have you not houses to eat and drink in? or contemn ye the Church of God: and confound them that have not? What shall I say to you? praise I you in this? I do not praise you.\n"
	"For I received of our Lord that which also I have delivered unto you, that our Lord JESUS in the night that he was betrayed, took bread:\n"
	"and giving thanks brake, and said: Take ye & eat, THIS IS MY BODY WHICH SHALL BE DELIVERED FOR YOU. This do ye for the commemoration of me.\n"
	"In like manner also the chalice after he had supped, saying: THIS CHALICE IS THE NEW TESTAMENT IN MY BLOOD. This do ye, as often as you shall drink, for the commemoration of me.\n"
	"For as often as you shall eat this bread, and drink the chalice, you shall shew the death of our Lord, until he come.\n"
	"Therefore whosoever shall eat this bread, or drink the chalice of our Lord unworthily, he shall be guilty of the body and of the blood of our Lord.\n"
	"But let a man prove himself: and so, let him eat of that bread, and drink of the chalice.\n"
	"For he that eateth and drinketh unworthily, eateth and drinketh judgement to himself, not discerning the body of our Lord.\n"
	"Therefore are there among you many weak and feeble, and many sleep.\n"
	"But if we did judge ourselves, we should not be judged.\n"
	"But whiles we are judged, of our Lord we are chastised; that with this world we be not damned.\n"
	"Therefore, my brethren, when you come together to eat, expect one another.\n"
	"If any man be an hungered, let him eat at home; that you come not together unto judgement. And the rest I will dispose, when I come.";