const char* chap1219 = "AND concerning spiritual things, I will not have you ignorant, brethren.\n"
	"You know that when you were heathen, you went to dumb idols according as you were led.\n"
	"Therefore I do you to understand that no man speaking in the Spirit of God, saith anathema to JESUS. And no man can say, Our Lord JESUS, but in the Holy Ghost.\n"
	"And there are divisions of graces, but one Spirit.\n"
	"And there are divisions of ministrations; but one Lord.\n"
	"And there are divisions of operations, but one God, which worketh all in all.\n"
	"And the manifestation of the Spirit is given unto every one to profit.\n"
	"To one certes by the Spirit is given the word of wisdom: and to another, the word of knowledge according to the same Spirit:\n"
	"to another, faith in the same Spirit: to another, the grace of doing cures in one Spirit:\n"
	"to another, the working of miracles: to another, prophecy: to another, discerning of spirits: to another, kinds of tongues: to another, interpretation of languages.\n"
	"And all these things worketh one and the same Spirit, dividing to every one according as he will.\n"
	"For as the body is one, and hath many members, and all the members of the body whereas they be many, yet are one body; so also Christ.\n"
	"For in one Spirit were we all baptized into one, whether Jews, or Gentiles, or bondmen, or free: & in one Spirit we were all made to drink.\n"
	"For the body also is not one member, but many.\n"
	"If the foot should say, because I am not the hand, I am not of the body: is it therefore not of the body?\n"
	"And if the ear should say, because I am not the eye, I am not of the body: is he therefore not of the body?\n"
	"If the whole body were the eye: where is the hearing? If the whole were the hearing: where is the smelling?\n"
	"But now God hath set the members, every one of them in the body as he would.\n"
	"And if all were one member, where were the body?\n"
	"But now there are many members indeed, yet one body.\n"
	"And the eye cannot say to the hand: I need not thy help; or again the head to the feet: You are not necessary for me.\n"
	"But much more those that seem to be the more weak members of the body, are more necessary:\n"
	"and such as we think to be the baser members of the body, upon them we put more aboundant honour: and those that are our unhonest parts, have more aboundant honesty.\n"
	"And our honest parts need nothing: but God hath tempered the body, giving to it that wanted, the more aboundant honour,\n"
	"that there might be no schism in the body, but the members together might be careful one for another.\n"
	"And if one member suffer any thing, all the members suffer with it. Or if one member do glory, all the members rejoice with it.\n"
	"And you are the body of Christ, and members of member.\n"
	"And some verily God hath set in the Church first Apostles, secondly Prophets, thirdly Doctors, next miracles, then the graces of doing cures, helps, governments, kinds of tongues.\n"
	"Are all Apostles? are all Prophets? are all Doctors?\n"
	"are all miracles? have all the grace of doing cures? do all speak with tongues? do all interpret?\n"
	"But pursue the better gifts. And yet I shew you a more excellent way.";