const char* chap123 = "And our Lord spake unto Moyses, saying:\n"
	"Speak to the children of Israel, and thou shall say to them: Man, or woman, when they shall make a vow to be sanctified, and will consecrate themselves to the Lord:\n"
	"they shall abstain from wine, & every thing that can make one drunk, vinegar of wine, and of any other potion, and whatsoever is pressed out of the grape, they shall not drink: new grapes and dry they shall not eat\n"
	"all the days wherein they are by vow consecrated to the Lord: whatsoever may be of the vineyard, from the raisin to the kernel they shall not eat.\n"
	"All the time of his separation a razor shall not pass over his head, until the day be expired, that he is consecrated to the Lord. He shall be holy whiles the bush of hair on his head doth grow.\n"
	"All the time of his consecration he shall not enter in to the dead,\n"
	"neither shall he be contaminated, no not on his father's and mother's and brother's and sister's corpse, because the consecration of his God is upon his head.\n"
	"All the days of his separation he shall be holy to the Lord.\n"
	"But if any man die suddenly before him, the head of his consecration shall be polluted: which he shall shave forthwith in the same day of his purgation, and again the seventh day:\n"
	"and in the eighth day he shall bring two turtles, or two young pigeons to the Priest in the entry of the covenant of testimony.\n"
	"And the Priest shall offer one for sin, and the other for an holocaust, and shall pray for him, because he hath sinned by occasion of the dead: and he shall sanctify his head that day:\n"
	"and shall consecrate to the Lord the days of his separation, offering a lamb of a year old for sin: yet so that the former days be made frustrate, because his sanctification was polluted.\n"
	"This is the law of consecration. When the days, that by vow he had determined, shall be expired: he shall bring him to the door of the tabernacle of covenant,\n"
	"and shall offer his oblation to the Lord, a male lamb of a year old without spot for an holocaust, and an ewe lamb of a year old without spot for sin, and a ram without spot, for a pacific host,\n"
	"a basket also of unleavened breads that are tempered with oil, and wafers without leaven anointed with oil, and the libaments of every one:\n"
	"which the Priest shall offer before the Lord, and shall offer as well for sin, as for an holocaust.\n"
	"But the ram he shall immolate for a pacific host to the Lord, offering withal the basket of azymes, and the libaments that by custom are due.\n"
	"Then shall the Nazarite be shaven before the door of the tabernacle of covenant, from the bush of the hair of his consecration: and he shall take his hairs, and lay them upon the fire, that is put under the sacrifice of pacifics.\n"
	"And a shoulder of the ram boiled, and one cake without leaven out of the basket, and one wafer unleavened, and he shall deliver them into the hands of the Nazarite, after that his head be shaven.\n"
	"And receiving them again from him, he shall elevate them in the sight of the Lord: and being sanctified they shall be the Priest's, as the breast, which was commanded to be separated, and the shoulder. After these things the Nazarite may drink wine.\n"
	"This is the law of the Nazarite, when he shall vow his oblation to the Lord in the time of his consecration, besides those things which his hand shall find, according to that which he had vowed in his mind, so shall he do to the fulfilling of his sanctification.\n"
	"And our Lord spake to Moyses, saying:\n"
	"Speak to Aaron and his sons: Thus shall you bless the children of Israel, and you shall say to them:\n"
	"Our Lord bless thee, and keep thee.\n"
	"Our Lord shew his face to thee, and have mercy upon thee.\n"
	"Our Lord turn his countenance upon thee, and give thee peace.\n"
	"And they shall invocate my name upon the children of Israel, and I will bless them.";