const char* chap1236 = "LO this the third time I come unto you: In the mouth of two or three witnesses shall every word stand.\n"
	"I foretold and do foretell as present, and now absent, to them that sinned before, and all the rest, that if I come again, I will not spare.\n"
	"Seek you an experiment of him that speaketh in me, Christ; who in you is not weak, but is mighty in you?\n"
	"For although he was crucified of infirmity; yet he liveth by the power of God. For we also are weak in him: but we shall live with him by the power of God on you.\n"
	"Try your own selves if you be in the faith, prove ye yourselves. Know you not yourselves that Christ JESUS is in you, unless perhaps you be reprobates.\n"
	"But I hope you know that we are not reprobates.\n"
	"And we pray God, that you do no evil, not that we may appear approved, but that you may do that which is good, and we be as reprobates.\n"
	"For we cannot any thing against the truth; but for the truth.\n"
	"For we rejoice, for that we are weak, and you are mighty. This also we pray for, your consummation.\n"
	"Therefore these things I write absent: that being present I may not deal hardly according to the power which our Lord hath given me unto edification and not unto destruction.\n"
	"For the rest, brethren, rejoice, be perfect, take exhortation, be of one mind, have peace; and the God of peace & love shall be with you.\n"
	"Salute one another in a holy kiss. All the saints salute you.\n"
	"The grace of our Lord JESUS Christ, and the charity of God, and the communication of the Holy Ghost be with you all. Amen.";