const char* chap1237 = "PAUL an Apostle not of men, neither by man, but by JESUS Christ, and God the Father that raised him from the dead,\n"
	"and all the brethren that are with me; to the churches of Galatia.\n"
	"Grace to you and peace from God the Father and our Lord JESUS Christ,\n"
	"who gave himself for our sins, that he might deliver us from this present wicked world, according to the will of our God and Father:\n"
	"to whom is glory for ever and ever. Amen.\n"
	"I marvel that thus so soon you are transferred from him that called you into the grace of Christ, unto another Gospel:\n"
	"which is not another, unless there be some that trouble you, and will invert the Gospel of Christ.\n"
	"But although we, or an Angel from Heaven, evangelize to you beside that which we have evangelized to you, be he anathema.\n"
	"As we have said before, so now I say again: If any evangelize to you, beside that which you have received, be he anathema.\n"
	"For do I now use persuasion to men, or to God? Or do I seek to please men? If I yet did please men, I should not be the servant of Christ.\n"
	"For I do you to understand, brethren, the Gospel that was evangelized of me, that it is not according to man.\n"
	"For neither did I receive it of man, nor learn it; but by the revelation of JESUS Christ.\n"
	"For you have heard my conversation sometime in Judaism, that above measure I persecuted the Church of God, and expugned it,\n"
	"and profited in Judaism above many of mine equals in my nation, being more abundantly an emulator of the traditions of my fathers.\n"
	"But when it pleased him that separated me from my mother's womb, and called me by his grace, to reveal his Son in me,\n"
	"that I should evangelize him among the Gentiles, incontinent I condescended not to flesh and blood,\n"
	"neither came I to Jerusalem to the Apostles my antecessors: but I went into Arabia, and again I returned to Damascus.\n"
	"Then, after three years I came to Jerusalem to see Peter: and tarried with him fifteen days.\n"
	"But other of the Apostles saw I none; saving James the brother of our Lord.\n"
	"And the things that I write to you; behold before God, that I lie not.\n"
	"After that, I came into the parts of Syria and Cilicia.\n"
	"And I was unknown by sight to the churches of Jewry, that were in Christ:\n"
	"but they had heard only, That he which persecuted us sometime, doth now evangelize the faith which sometime he expugned:\n"
	"and in me they glorified God.";