const char* chap1238 = "THEN after fourteen years I went up again to Jerusalem with Barnabas, taking Titus also with me.\n"
	"And I went up according to revelation: and conferred with them the Gospel which I preach among the Gentiles, but apart with them that seemed to be something, lest perhaps in vain I should run or had run.\n"
	"But neither Titus which was with me, whereas he was a Gentile, was compelled to be circumcised:\n"
	"but because of the false brethren craftily brought in, which craftily came in to espy our liberty that we have in Christ JESUS, that they might bring us into servitude.\n"
	"To whom we yielded not subjection no not for an hour, that the truth of the Gospel may remain with you.\n"
	"But of them that seemed to be something, (what they were some-time, it is nothing to me. God accepteth not the person of man) for to me, they that seemed to be something, added nothing.\n"
	"But contrarywise when they had seen, that to me was committed the Gospel of the prepuce, as to Peter of the circumcision\n"
	"(for he that wrought in Peter to the Apostleship of the circumcision, wrought in me also among the Gentiles)\n"
	"and when they had known the grace that was given me, James and Cephas and John, which seemed to be pillars, gave to me and Barnabas the right hands of society: that we unto the Gentiles, & they unto the circumcision:\n"
	"only that we should be mindful of the poor: the which same thing also I was careful to do.\n"
	"And when Cephas was come to Antioch, I resisted him in face, because he was reprehensible.\n"
	"For before that certain came from James, he did eat with the Gentiles: but when they were come, he withdrew and separated himself, fearing them that were of the circumcision.\n"
	"And to his simulation consented the rest of the Jews, so that Barnabas also was led of them into that simulation.\n"
	"But when I saw that they walked not rightly to the verity of the Gospel, I said to Cephas before them all: If thou being a Jew, livest Gentile-like and not Judaically, how doest thou compel the Gentiles to Judaize?\n"
	"We are by nature Jews, and not of the Gentiles, sinners.\n"
	"But knowing that man is not justified by the works of the Law, but by the faith of JESUS Christ; we also believe in Christ JESUS, that we may be justified by the faith of Christ, and not by the works of the Law: for the which cause, by the works of the Law no flesh shall be justified.\n"
	"But if seeking to be justified in Christ, ourselves also be found sinners; is Christ then a minister of sin? God forbid.\n"
	"For if I build the same things again which I have destroyed, I make myself a prevaricator.\n"
	"For I by the Law, am dead to the Law, that I may live to God: with Christ I am nailed to the cross.\n"
	"And I live, now not I; but Christ liveth in me. And that that I live now in the flesh, I live in the faith of the Son of God, who loved me, and delivered himself for me.\n"
	"I cast not away the grace of God. For if justice be by the Law, then Christ died in vain.";