const char* chap1239 = "O senseless Galatians, who hath bewitched you, not to obey the truth, before whose eyes JESUS Christ was proscribed, being crucified among you?\n"
	"This only I would learn of you: By the works of the Law, did you receive the Spirit, or by the hearing of the faith?\n"
	"Are you so foolish, that whereas you began with the spirit, now you will be consummate with the flesh?\n"
	"Have you suffered so great things without cause? if yet without cause.\n"
	"He therefore that giveth you the Spirit, and worketh miracles among you; by the works of the Law, or by the hearing of the faith doeth he it?\n"
	"As, Abraham believed God, and it was reputed to him unto justice.\n"
	"Know ye therefore that they that are of faith, the same are the children of Abraham.\n"
	"And the Scripture foreseeing that God justifieth the Gentiles by faith, shewed unto Abraham before, That in thee shall all nations be blessed.\n"
	"Therefore they that are of faith, shall be blessed with the faithful Abraham.\n"
	"For whosoever are of the works of the Law, are under curse. For it is written: Cursed be every one that abideth not in all things that be written in the book of the Law, to do them.\n"
	"But that in the Law no man is justified with God, it is manifest, because the just liveth by faith.\n"
	"But the Law is not by faith: but, He that doeth those things, shall live in them.\n"
	"Christ hath redeemed us from the curse of the Law, being made a curse for us (because it is written: Cursed is every one that hangeth on a tree)\n"
	"that on the Gentiles the blessing of Abraham might be made in Christ JESUS: that we may receive the promise of the Spirit by faith.\n"
	"Brethren (I speak according to man) yet a man's testament being confirmed no man despiseth, or further disposeth.\n"
	"To Abraham were the promises said, and to his seed. He saith not, And to seeds, as in many: but as in one, And to thy seed, which is Christ.\n"
	"And this I say, the testament being confirmed of God, the Law which was made after four hundred and thirty years, maketh not void to frustrate the promise.\n"
	"For if the inheritance be of the Law, now not of promise. But God gave it to Abraham by promise.\n"
	"Why was the Law then? It was put for transgressions, until the seed came to whom he had promised: ordained by Angels in the hand of a mediator.\n"
	"And a mediator is not of one: but God is one.\n"
	"Was the Law then against the promises of God? God forbid. For if there had been a Law given that could justify, undoubtedly justice should be of the Law.\n"
	"But the Scripture hath concluded all things under sin: that the promise by the faith of JESUS Christ might be given to them that believe.\n"
	"But before the faith came, under the Law we were kept shut up, unto that faith which was to be revealed.\n"
	"Therefore the Law was our Pedagogue in Christ: that we may be justified by faith.\n"
	"But when the faith came, now we are not under a pedagogue.\n"
	"For you are all the children of God by faith in Christ JESUS.\n"
	"For as many of you as are baptized in Christ, have put on Christ.\n"
	"There is not Jew nor Greek, there is not bond nor free, there is not male nor female. For all you are one in Christ JESUS.\n"
	"And if you be Christ's, then are you the seed of Abraham, heirs according to promise.";