const char* chap1248 = "CHILDREN, obey your parents in our Lord. For this is just.\n"
	"Honour thy father & thy mother (which is the first commandment in the promise)\n"
	"that it may be well with thee, & thou mayest be long lived upon the earth.\n"
	"And you fathers, provoke not your children to anger: but bring them up in the discipline & correption of our Lord.\n"
	"Servants, be obedient to your lords according to the flesh, with fear and trembling, in the simplicity of your heart, as to Christ:\n"
	"not serving to the eye, as it were pleasing men, but as the servants of Christ, doing the will of God from the heart.\n"
	"with a good will serving, as to our Lord and not to men.\n"
	"Knowing that every one what good soever he shall do, that shall he receive of our Lord, whether he be bond, or free.\n"
	"And you masters, do the same things to them, remitting threatenings: knowing that both their Lord and yours, is in Heaven: and acception of persons is not with him.\n"
	"Hence-forth, brethren, be strengthened in our Lord, and in the might of his power.\n"
	"Put you on the armour of God, that you may stand against the deceits of the devil.\n"
	"For our wrestling is not against flesh and blood: but against Princes and Potestates, against the rectors of the world of this darkness, against the spirituals of wickedness in the celestials.\n"
	"Therefore take the armour of God, that you may resist in the evil day, and stand in all things perfect.\n"
	"Stand therefore having your loins girded in truth, and clothed with the breast-plate of justice,\n"
	"& having your feet shod to the preparation of the Gospel of peace:\n"
	"in all things taking the shield of faith, wherewith you may extinguish all the fiery darts of the most wicked one.\n"
	"And take unto you the helmet of salvation: and the sword of the spirit (which is the word of God)\n"
	"in all prayer and supplication praying at all time in spirit: and in the same watching in all instance and supplication for all the saints:\n"
	"and for me, that speech may be given me in the opening of my mouth with confidence, to make known the mystery of the Gospel,\n"
	"for the which I am a legate in this chain, so that in it I may be bold according as I ought, to speak.\n"
	"And that you also may know the things about me, what I do, Tychicus my dearest brother and faithful minister in our Lord, will make you understand all things:\n"
	"whom I have sent to you for this same purpose, that you may know the things about us, and he may comfort your hearts.\n"
	"Peace to the brethren and charity with faith from God the Father, and our Lord JESUS Christ.\n"
	"Grace with all that love our Lord JESUS Christ in incorruption. Amen.";