const char* chap1252 = "THEREFORE, my dearest brethren and most desired, my joy and my crown: so stand in our Lord, my dearest.\n"
	"Euchodia I desire and Syntyche I beseech to be of one mind in our Lord.\n"
	"Yea and I beseech thee my sincere companion, help those women that have laboured with me in the Gospel with Clement, and the rest my coadjutors, whose names are in the book of life.\n"
	"Rejoice in our Lord always; again I say rejoice.\n"
	"Let your modesty be known to all men. Our Lord is nigh.\n"
	"Be nothing careful: but in every thing by prayer & supplication with thanks-giving let your petitions be known with God.\n"
	"And the peace of God which passeth all understanding, keep your hearts and intelligences in Christ JESUS.\n"
	"For the rest, brethren, what things soever be true, whatsoever honest, whatsoever just, whatsoever holy, whatsoever amiable, whatsoever of good fame, if there be any virtue, if any praise of discipline, these things think upon.\n"
	"Which you have both learned, and received, and heard, & seen in me; these things do ye, and the God of peace shall be with you.\n"
	"And I rejoiced in our Lord exceedingly, that once at the length you have reflourished to care for me, as you did also care: but you were occupied.\n"
	"I speak not as it were for penury. For I have learned, to be content with the things that I have.\n"
	"I know both to be brought low, I know also to abound: (every-where, and in all things I am instructed) both to be full, & to be hungry, both to abound, and to suffer penury.\n"
	"I can all things in him that strengtheneth me.\n"
	"Nevertheless you have done well, communicating to my tribulation.\n"
	"And you also know, o Philippians, that in the beginning of the Gospel, when I departed from Macedonia, no Church communicated unto me in the account of gift and receit, but you only:\n"
	"For unto Thessalonica also, once and twice you sent to my use.\n"
	"Not that I seek the gift, but I seek the fruit abounding in your account.\n"
	"But I have all things, and abound: I was filled after I received of Epaphroditus the things that you sent, an odour of sweetness, an acceptable host, pleasing God.\n"
	"And my God supply all your lack according to his riches in glory, in Christ JESUS.\n"
	"And to God & our Father be glory world without end. Amen.\n"
	"Salute ye every saint in Christ JESUS.\n"
	"The brethren that are with me, salute you. All the saints salute you: but especially they that are of Caesar's house.\n"
	"The grace of our Lord JESUS Christ be with your spirit. Amen.";