const char* chap1254 = "FOR I will have you know, brethren, what manner of care I have for you and for them that are at Laodicia, and whosoever have not seen my face in the flesh:\n"
	"that their hearts may be comforted, instructed in charity, and unto all the riches of the fullness of understanding, unto the knowledge of the mystery of God the Father of Christ JESUS,\n"
	"in whom be all the treasures of wisdom and knowledge hid.\n"
	"But this I say that no man deceive you in loftiness of words.\n"
	"For although I be absent in body, yet in spirit I am with you; rejoicing, and seeing your order, and the constancy of that your faith which is in Christ.\n"
	"Therefore as you have received JESUS Christ our Lord, walk in him,\n"
	"rooted and built in him, and confirmed in the faith, as also you have learned, abounding in him in thanks-giving.\n"
	"Beware lest any man deceive you by philosophy, & vain fallacy; according to the tradition of men, according to the elements of the world, and not according to Christ.\n"
	"For in him dwelleth all the fullness of the Godhead corporally:\n"
	"and you are in him replenished, who is the Head in all principality and power:\n"
	"in whom all you are circumcised with circumcision not made by hand in spoiling of the body of the flesh, in the circumcision of Christ,\n"
	"buried with him in Baptism: in whom also you are risen again by the faith of the operation of God, who raised him up from the dead.\n"
	"And you when you were dead in the offences and the prepuce of your flesh, did he quicken together with him; pardoning you all offences,\n"
	"wiping out the hand-writing of decree that was against us, which was contrary to us. And the same he hath taken out of the way, fastening it to the cross:\n"
	"and spoiling the principalities & Potestates, hath led them confidently in open shew, triumphing them in himself.\n"
	"Let no man therefore judge you in meat or in drink, or in part of a festival day, or of the New-moon, or of Sabboths:\n"
	"which are a shadow of things to come, but the body Christ's.\n"
	"Let no man seduce you, willing in the humility and religion of Angels, walking in the things which he hath not seen, in vain puffed up by the sense of his flesh,\n"
	"and not holding the Head, whereof the whole body by joints and bands being served and compacted, groweth to the increase of God.\n"
	"If then you be dead with Christ, from the elements of this world; why do you yet decree as living in the world?\n"
	"Touch not, taste not, handle not:\n"
	"which things are all unto destruction by the very use, according to the precepts and doctrines of men.\n"
	"Which are indeed having a shew of wisdom in superstition and humility, and not to spare the body, not in any honour to the filling of the flesh.";