const char* chap1256 = "YOU Masters, that which is just and equal, do to your servants: knowing that you also have a Master in heaven.\n"
	"Be instant in prayer; watching in it in thanks-giving,\n"
	"praying withal for us also, that God may open unto us the door of speech to speak the mystery of Christ (for the which also I am bound)\n"
	"that I may manifest it, so as I ought to speak.\n"
	"Walk with wisdom toward them that be without; redeeming the time.\n"
	"Your talk always, in grace let it be seasoned with salt: that you may know how you ought to answer every man.\n"
	"The things that are about me, Tychicus, our dearest brother, and faithful minister, & fellow-servant in our Lord, will make you understand all,\n"
	"whom I have sent to you for this same purpose, that he may know the things that concern you, and may comfort your hearts,\n"
	"with Onesimus, the most dear and faithful brother who is of you. All things that are done here, shall they do you to understand.\n"
	"Aristarchus my fellow-prisoner saluteth you, & Mark the cousin-german of Barnabas (concerning whom you have received commandments, If he come to you, receive him)\n"
	"and Jesus that is called Justus: who are of the Circumcision. These only are my coadjutors in the Kingdom of God: which have been a comfort to me.\n"
	"Epaphras saluteth you who is of you, the servant of Christ JESUS, always careful for you in prayers, that you may stand perfect and full in all the will of God.\n"
	"For I give him testimony that he hath much labour for you, & for them that be at Laodicia, and that are at Hierapolis.\n"
	"Luke, the most dear physician, saluteth you; and Demas.\n"
	"Salute the brethren that are at Laodicia; and Nymphas, and the Church that is in his house.\n"
	"And when the epistle shall be read with you, make that it be read also in the Church of the Laodicians: and that you read that which is of the Laodicians.\n"
	"And say to Archippus: See the ministry which thou hast received of our Lord, that thou fulfill it.\n"
	"The salutation: with mine own hand, Paul's. Be mindful of my bands. Grace be with you. Amen.";