const char* chap1258 = "FOR yourselves know, brethren, our entrance unto you, that it was not vain:\n"
	"but having suffered before and been abused with contumelies (as you know) at Philippi, we had confidence in our God, to speak unto you the Gospel of God in much carefulness.\n"
	"For our exhortation was not of error, nor of uncleanness, nor in deceit:\n"
	"but as we were approved of God that the Gospel should be committed to us, so we speak: not as pleasing men, but God, who proveth our hearts.\n"
	"For neither have we been, at any time in the word of adulation, as you know; nor in occasion of avarice, God is witness:\n"
	"nor seeking glory of men, neither of you, nor of others.\n"
	"Whereas we might have been a burden to you, as the Apostles of Christ; but we became children in the midst of you, as if a nurse should cherish her children:\n"
	"so having a desire to you, we would gladly deliver unto you not only the Gospel of God, but also our own souls because you are become most dear unto us.\n"
	"For you are mindful, brethren, of our labour and toil. Day and night working, lest we should charge any of you, we preached among you the Gospel of God.\n"
	"You are witnesses and God, how holily, and justly & without blame, we have been to you that did believe.\n"
	"As you know in what manner we desiring and comforting you, have adjured every one of you (as a father his children)\n"
	"that you would walk worthy of God, who hath called you into his Kingdom and glory.\n"
	"Therefore we also give thanks to God without intermission: because that when you had received of us the word of the hearing of God, you received it not as the word of men, but (as it is indeed) the word of God, who worketh in you that have believed.\n"
	"For you, brethren, are become followers of the Churches of God that be in Jewry, in Christ JESUS: for you also have suffered the same things of your own lineage, as they also of the Jews,\n"
	"who both killed our Lord JESUS, and the Prophets, and have persecuted us, and please not God, and are adversaries to all men,\n"
	"prohibiting us to speak to the Gentiles that they may be saved, to make up their sins always. For the wrath of God is come upon them even to the end.\n"
	"But we, brethren, deprived of you for a short time, in sight, not in heart; have hastened the more aboundantly to see your face with much desire.\n"
	"For we would have come to you, I^ Paul certes, once and again: but Satan hath hindered us.\n"
	"For what is our hope, or joy, or crown of glory? Are not you, before our Lord JESUS Christ in his coming?\n"
	"For you are our glory and joy.";