const char* chap126 = "And our Lord spake to Moyses in the desert of Sinai, the second year, after they went out of the land of Aegypt, the first month, saying:\n"
	"Let the children of Israel make the Phase in his time,\n"
	"the fourteenth day of this month at even, according to all the ceremonies and justifications thereof.\n"
	"And Moyses commanded the children of Israel that they should make the Phase.\n"
	"Who made it in his time: the fourteenth day of the month at even in mount Sinai. According to all things that our Lord had commanded Moyses the children of Israel did.\n"
	"But behold certain unclean upon the soul of man, which could not make the Phase on that day, coming to Moyses and Aaron,\n"
	"said to them: We are unclean upon the soul of man: why are we defrauded that we cannot offer the oblation to our Lord in due time among the children of Israel?\n"
	"To whom Moyses answered: Stand that I may ask counsel what our Lord will command concerning you.\n"
	"And our Lord spake to Moyses, saying:\n"
	"Speak to the children of Israel: The man that shall be unclean upon a soul, or in his journey far off in your nation, let him make the Phase to the Lord\n"
	"in the second month, the fourteenth day of the month at even: with azymes and wild lettuce shall they eat it:\n"
	"they shall not leave any thing thereof until morning, and a bone thereof they shall not break, all the rite of the Phase they shall observe.\n"
	"But if any man both be clean, and was not in his journey, and yet did not make the Phase, that soul shall be destroyed out from among his peoples, because he offered not sacrifice to the Lord in his due time: he shall bear his sin.\n"
	"The sojourner also and stranger if they be with you, shall make the Phase to the Lord, according to the ceremonies and justifications thereof. The self-same precept shall be among you as well to the stranger, as to him that is born in the country.\n"
	"Therefore the day that the tabernacle was erected, a cloud covered it. And from evening over the tabernacle there was as it were the likeness of fire until morning.\n"
	"So was it done always: by day the cloud covered it, and by night as it were the likeness of fire.\n"
	"And when the cloud that protected the tabernacle had been taken away, then the children of Israel matched: and in the place where the cloud had stood, there they camped.\n"
	"At the commandment of our Lord they marched, and at his commandment they pitched the tabernacle. All the days that the cloud stood over the tabernacle, they remained in the same place:\n"
	"and if it chanced that it did continue over it a long time, the children of Israel were in the watches of our Lord, and marched not.\n"
	"for as many days soever as the cloud had been over the tabernacle. At the commandment of our Lord they pitched their tents, and at his commandment they took them down.\n"
	"If the cloud had been from even until morning, and immediately at day break had forsaken the tabernacle, they marched: & if it had departed after a day and a night, they took down their tents.\n"
	"But if for two days or one month or a longer time it had been over the tabernacle, the children of Israel remained in the same place, and marched not: but immediately as it had departed, they removed the camp.\n"
	"By the word of the Lord they pitched their tents, and by his word they marched: and were in the Watches of our Lord according to his commandment by the hand of Moyses.";