const char* chap1266 = "I desire therefore first of all things that obsecrations, prayers, postulations, thanks-givings be made for all men,\n"
	"for kings and all that are in preeminence: that we may lead a quiet and a peaceable life in all piety and chastity.\n"
	"For this is good and acceptable before our Saviour God,\n"
	"who will all men to be saved, and to come to the knowledge of the truth.\n"
	"For there is one God, one also mediator of God and men, man Christ JESUS:\n"
	"who gave himself a redemption for all, whose testimony in due times is confirmed.\n"
	"Wherein I am appointed a preacher and an Apostle (I say the truth, I lie not) doctor of the Gentiles in faith and truth.\n"
	"I will^ therefore that men pray in every place: lifting up pure hands, without anger and altercation.\n"
	"In like manner women also in comely attire: with demureness and sobriety adorning themselves, not in plaited hair, or gold, or precious stones, or gorgeous apparel,\n"
	"but that which becometh women professing piety by good works.\n"
	"Let a woman learn in silence, with all subjection.\n"
	"But to teach I permit not unto a woman, nor to have dominion over the man: but to be in silence.\n"
	"For Adam was formed first; then Eve.\n"
	"And Adam was not seduced: but the woman being seduced, was in prevarication.\n"
	"Yet she shall be saved by generation of children: if they continue in faith and love and sanctification with sobriety.";