const char* chap1270 = "WHOSOEVER are servants under yoke, let them count their masters worthy of all honour; lest the name of our Lord and his doctrine be blasphemed.\n"
	"But they that have faithful masters, let them not contemn them because they are brethren, but serve the rather, because they be faithful and beloved, which are partakers of the benefit. These things teach and exhort.\n"
	"If any man teach otherwise, and consent not to the sound words of our Lord JESUS Christ, and to that doctrine which is according to piety,\n"
	"he is proud, knowing nothing, but languishing about questions and strife of words: of which rise envies, contentions, blasphemies, evil suspicions,\n"
	"conflicts of men corrupted in their mind, and that are deprived of the truth, that esteem gain to be piety.\n"
	"But piety with sufficiency is great gain.\n"
	"For we brought nothing into this world, doubtless, neither can we take away any thing.\n"
	"But having food, and wherewith to be covered, with these we are content.\n"
	"For they that will be made rich, fall into tentation and the snare of the devil, and many desires unprofitable and hurtful, which drown men into destruction and perdition.\n"
	"For the root of all evils is covetousness; which certain desiring have erred from the faith, and have entangled themselves in many sorrows.\n"
	"But thou, o man of God, fly these things; and pursue justice, piety, faith, charity, patience, mildness.\n"
	"Fight the good fight of faith: apprehend eternal life, wherein thou art called and hast confessed a good confession before many witnesses.\n"
	"I command thee before God who quickeneth all things, and Christ JESUS who gave testimony under Pontius Pilate a good confession,\n"
	"that thou keep the commandment without spot, blameless unto the coming of our Lord JESUS Christ.\n"
	"Which in due times the Blessed and only Mighty will shew, the King of kings and Lord of lords,\n"
	"who only hath immortality, and inhabiteth light not accessible, whom no man hath seen, yea neither can see, to whom be honour and empire everlasting. Amen.\n"
	"Command the rich of this world not to be high minded, nor to trust in the uncertainty of riches, but in the living God (who giveth us all things aboundantly to enjoy)\n"
	"to do well, to become rich in good works, to give easily, to communicate,\n"
	"to heap unto themselves a good foundation for the time to come, that they may apprehend the true life.\n"
	"O Timothee, keep the depositum, avoiding the profane novelties of voices, and oppositions of falsely called knowledge.\n"
	"Which certain promising, have erred about the faith. Grace be with thee. Amen.";