const char* chap1273 = "AND this know thou, that in the last days shall approach perilous times.\n"
	"And men shall be lovers of themselves, covetous, haughty, proud, blasphemous, not obedient to their parents, unkind, wicked,\n"
	"without affection, without peace, accusers, incontinent, unmerciful, without benignity,\n"
	"traitors, stubborn, puffed up, and lovers of voluptuousness more than of God:\n"
	"having an appearance indeed of piety, but denying the virtue thereof. And these avoid.\n"
	"For of these be they that craftily enter into houses; & lead captive seely women laden with sins, which are led with diverse desires:\n"
	"always learning, and never attaining to the knowledge of the truth.\n"
	"But as Iannes and Mambres resisted Moyses, so these also resist the truth, men corrupted in mind, reprobate concerning the faith.\n"
	"But they shall prosper no further: for their folly shall be manifest to all, as theirs also was.\n"
	"But thou hast attained to my doctrine, institution, purpose, faith, longanimity, love, patience,\n"
	"persecutions, passions: what manner of things were done to me at Antioch, at Iconium, at Lystra: what manner of persecutions I sustained. And out of all^ our Lord delivered me.\n"
	"And all that will live godly in Christ JESUS, shall suffer persecution.\n"
	"But evil men & seducers shall prosper to the worse: erring, and driving into error.\n"
	"But thou, continue in those things which thou hast learned, & are committed to thee: knowing of whom thou hast learned;\n"
	"& because from thine infancy thou hast known the holy Scriptures, which can instruct thee to salvation, by the faith that is in Christ JESUS.\n"
	"All Scripture inspired of God, is profitable to teach, to argue, to correct, to instruct in justice:\n"
	"that the man of God may be perfect, instructed to every good work.";