const char* chap1284 = "WHEREFORE intermitting the word of the beginning of Christ, let us proceed to perfection, not again laying the foundation of penance from dead works, & of faith toward God,\n"
	"of the doctrine of baptisms, & of imposition of hands, & of the resurrection of the dead, & of eternal judgement.\n"
	"And this shall we do, if God will permit.\n"
	"For it is impossible for them that were once illuminated, have tasted also the heavenly gift, & were made partakers of the Holy Ghost,\n"
	"have more-over tasted the good word of God, & the powers of the world to come,\n"
	"and are fallen, to be renewed again to penance, crucifying again to themselves the Son of God, and making him a mockery.\n"
	"For the earth drinking the rain often coming upon it, & bringing forth grass commodious for them by whom it is tilled, receiveth blessing of God.\n"
	"But bringing forth thorns and briers, it is reprobate, and very near a curse, whose end is, to be burnt.\n"
	"But we confidently trust of you, my best beloved, better things and nearer to salvation; although we speak thus.\n"
	"For God is not unjust, that he should forget your work & love which you have shewed in his name, which have ministered to the saints and do minister.\n"
	"And our desire is that every one of you shew forth the same carefulness to the accomplishing of hope unto the end:\n"
	"that you become not slothful, but imitators of them which by faith and patience shall inherit the promises.\n"
	"For God promising to Abraham, because he had none greater by whom he might swear, he sware by himself,\n"
	"saying, Unless blessing I shall bless thee, and multiplying shall multiply thee.\n"
	"And so patiently enduring he obtained the promise.\n"
	"For men swear by a greater than themselves: and the end of all their controversy, for the confirmation, is an oath.\n"
	"Wherein God meaning more aboundantly to shew to the heirs of the promise the stability of his counsel, he interposed an oath:\n"
	"that by two things unmoveable, whereby it is impossible for God to lie, we may have a most strong comfort. Who have fled to hold fast the hope proposed,\n"
	"which we have as an anchor of the soul, sure and firm, and going in into the inner parts of the veil,\n"
	"where JESUS the precursor for us is entered, made a high Priest for ever according to the order of Melchisedech.";