const char* chap1305 = "THAT which was from the beginning, which we have heard, which we have seen with our eyes, which we have looked upon, and our hands have handled, of the word of life:\n"
	"(and the life was manifested: and we have seen, and do testify, and declare unto you the life eternal which was with the Father, and hath appeared to us)\n"
	"that^ which we have seen and have heard, we declare unto you, that you also may have society with us, and our society may be with the Father and with his Son JESUS Christ.\n"
	"And these things we write to you, that you may rejoice, and your joy may be full.\n"
	"And this is the annunciation which we have heard of him, and declare unto you, That God is light, and in him there is no darkness:\n"
	"If we shall say that we have society with him, and walk in darkness, we lie, and do not the truth.\n"
	"But if we walk in the light, as he also is in the light: we have society one toward another, and the blood of JESUS Christ his Son cleanseth us from all sin.\n"
	"If we shall say that we have no sin, we seduce ourselves, and the truth is not in us.\n"
	"If we confess our sins, he is faithful & just, for to forgive us our sins, and to cleanse us from all iniquity.\n"
	"If we shall say that we have not sinned, we make him a liar, and his word is not in us.";