const char* chap1323 = "AND there was given me a reed like unto a rod: and it was said to me: Arise, and measure the Temple of God, and the altar, and them that adore in it.\n"
	"But the court which is without the Temple, cast forth, & measure not that: because it is given to the Gentiles, and they shall tread under-foot the holy city two & forty months:\n"
	"and I will give to my two witnesses, and they shall prophesy a thousand two hundred sixty days, clothed with sack-cloths.\n"
	"These are the two olive trees & the two Candlesticks that stand in the sight of the Lord of the earth.\n"
	"And if any man will hurt them, fire shall come forth out of their mouths, and shall devour their enemies. And if any man will hurt them, so must he be slain.\n"
	"These have power to shut heaven, that it rain not in the days of their prophecy: and they have power over the waters to turn them into blood, and to strike the earth with all plague as often as they will.\n"
	"And when they shall have finished their testimony, the beast which ascended from the depth, shall make war against them, and shall overcome them, and kill them.\n"
	"And their bodies shall lie in the streets of the great city, which is called spiritually Sodom and Aegypt, where their Lord also was crucified.\n"
	"And there shall of tribes, and peoples, and tongues, and Gentiles, see their bodies for three days, and a half: and they shall not suffer their bodies to be laid in monuments.\n"
	"And the inhabitants of the earth shall be glad upon them, and make merry: and shall send gifts one to another, because these two Prophets tormented them that dwelt upon the earth.\n"
	"And after three days and a half, the spirit of life from God entered into them. And they stood upon their feet, and great fear fell upon them that saw them.\n"
	"And they heard a loud voice from heaven saying to them: Come up hither. And they went up into heaven in a cloud: and their enemies saw them.\n"
	"And in that hour there was made a great earth-quake: and the tenth part of the city fell: and there were slain in the earth-quake names of men seven thousand: and the rest were cast into a fear, and gave glory to the God of heaven.\n"
	"The second woe is gone: and behold the third woe will come quickly.\n"
	"And the seventh Angel sounded with a trumpet: and there were made loud voices in heaven saying, The kingdom of this world is made our Lord's & his Christ's, and he shall reign for ever and ever. Amen.\n"
	"And the four and twenty Seniors which sit on their seats in the sight of God, fell on their faces, and adored God,\n"
	"saying: We thank thee Lord God omnipotent, which art, and which wast, and which shalt come: because thou hast received thy great power, and hast reigned.\n"
	"And the Gentiles were angry, and thy wrath is come, and the time of the dead, to be judged, and to render reward to thy Servants the Prophets and Saints, and to them that fear thy name, little and great, and to destroy them that have corrupted the earth.\n"
	"And the temple of God was opened in heaven: and the ark of his testament was seen in his temple, and there were made lightnings, and voices, and an earth-quake and great hail.";