const char* chap1332 = "AND I saw an Angel descending from heaven, having the key of the bottomless depth, and a great chain in his hand.\n"
	"And he apprehended the dragon the old serpent, which is the devil and Satan, and bound him for a thousand years.\n"
	"And he threw him into the depth, and shut him up, and sealed over him, that he seduce no more the nations, till the thousand years be consummate. And after these things he must be loosed a little time.\n"
	"And I saw seats: and they sat upon them, and judgement was given them, and the souls of the beheaded for the testimony of JESUS, and for the word of God, and that adored not the beast, nor his image, nor received his character in their foreheads or in their hands, and have lived, & reigned with Christ a thousand years.\n"
	"The rest of the dead lived not, till the thousand years be consummate. This is the first resurrection.\n"
	"Blessed and holy is he that hath part in the first resurrection. In these the second death hath not power: but they shall be Priests of God and of Christ: and shall reign with him a thousand years.\n"
	"And when the thousand years shall be consummate, Satan shall be loosed out of his prison, and shall go forth and seduce the nations that are upon the four corners of the earth, Gog, and Magog, and shall gather them into battle, the number of whom is as the sand of the sea.\n"
	"And they ascended upon the breadth of the earth, and compassed the camp of the Saints, and the beloved city.\n"
	"And there came down fire from God out of heaven, and devoured them:\n"
	"and the devil which seduced them, was cast into the pool of fire and brimstone, where both the beast & the false-prophet shall be tormented day and night for ever and ever.\n"
	"And I saw a great white throne, and one sitting upon it, from whose sight earth and heaven fled, and there was no place found for them.\n"
	"And I saw the dead, great and little, standing in the sight of the throne, and books were opened: and another book was opened, which is of life: and the dead were judged of those things which were written in the books according to their works.\n"
	"And the sea gave the dead that were in it, and death and hell gave their dead that were in them, and it was judged of every one according to their works.\n"
	"And hell and death were cast into the pool of fire. This is the second death.\n"
	"And he that was not found written in the book of life, was cast into the pool of fire.";