const char* chap137 = "And the children of Israel, and all the multitude came into the desert Sin, the first month: and the people abode in Cades. And Mary died there, and was buried in the same place.\n"
	"And when the people lacked water, they came together against Moyses and Aaron:\n"
	"and being turned into sedition, said: Would God we had perished among our brethren before our Lord.\n"
	"Why have you brought forth the Church of our Lord into the wilderness, that both we and our cattle should die?\n"
	"Why did you make us ascend out of Aegypt, and have brought us into this exceeding naughty place, which cannot be sowed, which bringeth forth neither fig, nor vines, nor pomegranates, moreover also hath no water for to drink?\n"
	"And Moyses and Aaron, the multitude being dismissed, entering into the tabernacle of covenant, fell flat upon the ground, and cried to our Lord, and said: Lord God hear the cry of this people, and open unto them thy treasure the fountain of living water, that being satisfied, their murmuring may cease. And the glory of our Lord appeared over them.\n"
	"And our Lord spake to Moyses, saying:\n"
	"Take the rod, and assemble the people together, thou and Aaron thy brother, and speak to the rock before them, and it shall give waters. And when thou hast brought forth water out of the rock, all the multitude shall drink and their cattle.\n"
	"Moyses therefore took the rod, which was in the sight of our Lord, as he commanded him,\n"
	"the multitude being assembled before the rock, and he said to them: Hear ye rebellious & incredulous: Can we out of this rock bring you forth water?\n"
	"And when Moyses had lifted up his hand striking the rock twice with the rod, there came forth great plenty of water, so that the people drunk and their cattle.\n"
	"And our Lord said to Moyses and Aaron: Because you have not believed me, to sanctify me before the children of Israel, you shall not bring in these peoples into the land, which I will give them.\n"
	"This is the water of contradiction, where the children of Israel quarrelled against our Lord, and he was sanctified in them.\n"
	"In the mean time Moyses sent messengers from Cades to the King of Edom, which should say: Thus thy brother Israel biddeth us to say: Thou knowest all the labour, that hath taken us,\n"
	"in what manner our fathers went down into Aegypt, and there we dwelt a great time, and the Aegyptians afflicted us, and our fathers:\n"
	"and in what manner we cried to our Lord, and he heard us, and sent an Angel, that hath brought us out of Aegypt. Lo being presently in the city of Cades, which is in thy uttermost borders,\n"
	"we beseech thee that we may have licence to pass through thy country. We will not go through the fields, nor through the vineyards, we will not drink the waters of thy wells, but we will go the common high way, declining neither to the right hand, nor to the left, till we be past thy borders.\n"
	"To whom Edom answered: Thou shalt not pass by me, otherwise I will come armed against thee.\n"
	"And the children of Israel said: We will go by the beaten way: and if we and the cattle drink thy waters, we will give thee that which is just: there shall be no difficulty in the price, only let us pass speedily.\n"
	"But he answered: Thou shalt not pass: And immediately he came forth to meet them with an infinite multitude, and a strong hand,\n"
	"neither would he condescend to them desiring to grant them passage through his borders. For the which cause Israel turned another way from him.\n"
	"And when they had removed the camp from Cades, they came into the mountain Hor, which is in the borders of the land of Edom:\n"
	"Where our Lord spake to Moyses:\n"
	"Let Aaron, saith he, go to his people: for he shall not enter to the Land, which I have given the children of Israel, for that he was incredulous to my mouth, at the Waters of contradiction.\n"
	"Take Aaron and his son with him, and thou shalt bring them into the mountain Hor.\n"
	"And when thou hast unvested the father of his vesture, thou shalt revest therewith Eleazar his son: Aaron shall be gathered, and die there.\n"
	"Moyses did as our Lord had commanded: and they went up into the mountain Hor before all the multitude.\n"
	"And when he had spoiled Aaron of his vestments, he revested Eleazar his son with them.\n"
	"After that he was dead in the top of the mountain, he went down with Eleazar.\n"
	"And all the multitude seeing that Aaron was dead, mourned upon him thirty days throughout all their families.";