const char* chap150 = "These are the mansions of the children of Israel, that went out of Aegypt by their troops in the hand of Moyses and Aaron,\n"
	"which Moyses described according to the places of the camp, which by our Lord's commandment they changed.\n"
	"The children of Israel therefore departing from Ramesses the first month, the fifteenth day of the first month, the morrow after they made the Phase, in a mighty hand, all the Aegyptians seeing them,\n"
	"& burying their first born, which our Lord had strucken (yea and on their gods also he had exercised vengeance)\n"
	"they camped in Soccoth.\n"
	"And from Soccoth they came into Etham, which is in the uttermost borders of the wilderness.\n"
	"Departing thence they came over against Phihahiroth, which looketh toward Beelsephon, and camped before Magdal.\n"
	"And departing from Phihahiroth, they passed through the midst of the sea into the wilderness: and walking three days through the desert Etham, they camped in Mara.\n"
	"And departing from Mara, they came into Elim, where there were the twelve fountains of waters, and the seventy palm trees: and there they camped.\n"
	"But departing thence also, they pitched their tents upon the Red sea. And departing from the Red sea,\n"
	"they camped in the desert Sin.\n"
	"From whence departing, they came into Daphca.\n"
	"And departing from Daphca, they camped in Alus.\n"
	"And departing from Alus, they pitched their tents in Raphidim, where the people wanted water to drink.\n"
	"And departing from Raphidim, they camped in the desert of Sinai.\n"
	"But departing also from the desert Sinai, they came to the Sepulchres of concupiscence.\n"
	"And departing from the Sepulchres of concupiscence, they camped in Haseroth.\n"
	"And from Haseroth they came into Rethma.\n"
	"And departing from Rethma, they camped in Remmonphares.\n"
	"Whence departing they came into Lebna.\n"
	"From Lebna they camped in Ressa.\n"
	"And departing from Ressa, they came into Ceelatha.\n"
	"Whence departing, they camped in the mountain Sepher.\n"
	"Departing from the mountain Sepher, they came into Harada.\n"
	"Thence departing, they camped in Maceloth.\n"
	"And departing from Maceloth, they came into Thahath.\n"
	"From Thahath they camped in Thare.\n"
	"Whence departing, they pitched their tents in Methca.\n"
	"And from Methca they camped in Hesmona.\n"
	"And departing from Hesmona, they came into Moseroth.\n"
	"And from Moseroth they camped in Benejaacan.\n"
	"And departing from Benejaacan, they came into the mount Gadgad.\n"
	"Whence departing, they camped in Jetebatha.\n"
	"And from Jetebatha they came into Hebrona.\n"
	"And departing from Hebrona, they camped in Asiongaber.\n"
	"Thence departing, they came into the desert Sin, this is Cades.\n"
	"And departing from Cades, they camped in the mount Hor, in the uttermost borders of the Land of Edom.\n"
	"And Aaron the Priest went up into the mountain Hor at the commandment of our Lord: and there he died the fortieth year of the coming forth of the children of Israel out of Aegypt, the fifth month, the first day of the month,\n"
	"when he was an hundred three and twenty years old.\n"
	"And the Chananite king of Arad, who dwelt toward the south, heard that the children of Israel were come into the Land of Chanaan.\n"
	"And departing from the mountain Hor, they camped in Salmona.\n"
	"Whence departing, they came into Phunon.\n"
	"And departing from Phunon, they camped in Oboth.\n"
	"And from Oboth they came into Ijeabarim, which is in the borders of the Moabites.\n"
	"And departing from Ijeabarim they pitched their tents in Dibongad.\n"
	"Whence departing, they camped in Helmondeblathaim.\n"
	"And departing from Helmondeblathaim, they came to the mountains Abarim against Nabo.\n"
	"And departing from the mountains Abarim, they passed to the champion countries of Moab, upon Jordan, against Jericho.\n"
	"And there they camped from Bethsimoth unto Abelsatim in the plainer places of the Moabites,\n"
	"where our Lord spake to Moyses:\n"
	"Command the children of Israel, and say to them: When you shall have passed Jordan, entering the Land of Chanaan,\n"
	"destroy all the inhabitants of that Land: break their titles, and burst to fitters their statues, and waste all their excelses,\n"
	"cleansing the Land, and dwelling in it. For I have given it you in possession,\n"
	"which you shall divide among you by lot. To the more you shall give the larger, and to the fewer the straiter. To every one as the lot shall fall, so shall the inheritance be given. By the tribes and the families the possession shall be divided.\n"
	"But if you will not kill the inhabitants of the Land: they that remain, shall be unto you as it were nails in your eyes, and spears in your sides, and they shall be your adversaries in the Land of your habitation:\n"
	"and whatsoever I had thought to do to them, I will do to you.";