const char* chap157 = "And now Israel hear the precepts and judgments, which I teach thee: that doing them, thou mayest live, and entering in mayest possess the Land, which the Lord the God of your fathers will give you.\n"
	"You shall not add to the word, that I speak to you, neither shall you take away from it: keep the commandment of the Lord your God which I command you.\n"
	"Your eyes have seen all things that our Lord hath done against Beelphegor, how he hath destroyed all his worshippers out of the midst of you.\n"
	"But you that cleave to the Lord your God, live all until this present day.\n"
	"You know that I have taught you precepts, and justices, as the Lord my God hath commanded me: so shall you do them in the Land, which you shall possess:\n"
	"and you shall observe, and fulfill them in work. For this is your wisdom, and understanding before peoples, that hearing all these precepts, may say: Behold a people full of wisdom and understanding, a great nation.\n"
	"Neither is there other nation so great, that hath gods approaching unto them, as our God is present at all our petitions.\n"
	"For what other nation is there so renowned that hath the ceremonies, and just judgments, and the whole law, which I will set forth this day before your eyes.\n"
	"Keep thyself therefore, and thy soul carefully. Forget not the words, that thine eyes have seen, and let them not fall out of thy heart all the days of thy life. Thou shalt teach them thy sons and thy nephews,\n"
	"the day wherein thou didst stand before the Lord thy God in Horeb, when our Lord spake to me, saying; Assemble unto me the people, that they may hear my words, and may learn to fear me all the time that they live on the earth, and may teach their children.\n"
	"And you came to the foot of the mount, which burned even unto heaven: and there was in it darkness, and a cloud and mist.\n"
	"And our Lord spake to you from the midst of the fire. The voice of his words you heard, and form you saw not at all.\n"
	"And he shewed you his covenant, which he commanded you to do, and the ten words, that he wrote in two tables of stone.\n"
	"And he commanded me at that time that I should teach you the ceremonies and judgments, which you should do in the Land, that you shall possess.\n"
	"Keep therefore your souls carefully. You saw not any similitude in the day, that our Lord spake to you in Horeb from the midst of the fire:\n"
	"lest perhaps deceived you might make you a graven similitude, or image of male or female,\n"
	"the similitude of all cattle, that are upon the earth, or of birds, that fly under heaven,\n"
	"and of creeping beasts, that move on the earth, or of fishes, that under the earth abide in the waters:\n"
	"lest perhaps lifting up thine eyes to heaven, thou see the Sun and the Moon, and all the stars of heaven, and deceived by error thou adore and serve them, which the Lord thy God created to serve all nations, that are under heaven.\n"
	"But you our Lord hath taken, and brought out of the iron furnace of Aegypt, to have you his people by inheritance, as it is this present day.\n"
	"And our Lord was angry with me for your words, and he sware that I should not pass over Jordan, nor enter into the excellent Land, which he will give you.\n"
	"Behold I die in this ground, I shall not pass over Jordan: you shall pass, and possess the goodly Land.\n"
	"Beware lest at any time thou forget the covenant of the Lord thy God, which he hath made with thee: and make to thee a graven similitude of those things, which our Lord hath prohibited to be made:\n"
	"because the Lord thy God is a consuming fire, jealous God.\n"
	"If you shall beget sons & nephews and abide in the Land, & being deceived make to you some similitude, committing evil before the Lord your God, to provoke him to wrath:\n"
	"I call this day heaven and earth witnesses, that you shall quickly perish from out of the Land, which being passed over Jordan you shall possess. You shall not dwell therein long time, but our Lord will destroy you,\n"
	"and disperse you into all nations, and you shall remain a few among the nations, to the which our Lord will lead you.\n"
	"and there you shall serve gods, that were framed with men's hand, wood and stone, that see not, nor hear, nor eat, nor smell.\n"
	"And when thou shalt seek there the Lord thy God, thou shalt find him, yet so, if thou seek him with all thy heart, & all tribulation of thy soul.\n"
	"After that all the things aforesaid shall find thee, & in the latter time thou shalt return to the Lord thy God, and shalt hear his voice.\n"
	"Because the Lord thy God is a merciful God: he will not leave thee, nor altogether destroy thee; nor forget the covenant, wherein he sware to thy fathers.\n"
	"Ask of the days of old, that have been before thy time from the day that God created man upon the earth, from one end of heaven to the other end thereof, if ever there was done the like thing, or it hath been known at any time,\n"
	"that a people should hear the voice of God speaking out of the midst of fire, as thou hast heard, and lived:\n"
	"if God so did that he went in, and took unto him a Nation out of the midst of nations, by temptations, signs, and wonders, by fight and strong hand, and stretched out arm, and horrible visions according to all things, that the Lord your God did for you in Aegypt, thine eyes seeing it:\n"
	"that thou mightest know that our Lord, he is God, and there is none other beside him,\n"
	"from heaven he made thee to hear his voice, that he might teach thee. And in earth he shewed thee his fire, very great, and thou didst hear his words out of the midst of the fire,\n"
	"because he loved thy fathers, and chose their seed after them. And he brought thee out of Aegypt, going before thee in his great power,\n"
	"to destroy very great nations and stronger than thou^ at thy entering in, and to bring thee in, and give thee their land in possession, as thou seest this present day.\n"
	"know therefore this day, and think in thy heart that our Lord he is God in heaven above, and in the earth beneath, and there is none other.\n"
	"Keep his precepts and commandments, which I command thee: that it may be well with thee, and thy children after thee, and thou mayest remain a long time upon the Land, which the Lord thy God will give thee.\n"
	"Then Moyses separated three cities beyond Jordan at the east side,\n"
	"that he might flee to them which should kill his neighbour not voluntarily, neither was his enemy a day or two before, and he might scape to some of these cities:\n"
	"Bosor in the wilderness, which is situated in the champion country of the tribe of Ruben: and Ramoth in Galaad, which is in the tribe of Gad: and Golan in Basan, which is in the tribe of Manasses.\n"
	"This is the law that Moyses set before the children of Israel,\n"
	"and these are the testimonies and ceremonies and judgments, which he spake to the children of Israel, when they came out of Aegypt,\n"
	"beyond Jordan in the valley against the temple of Phogor in the land of Sehon king of the Ammorrheite, that dwelt in Hesebon, whom Moyses struck. The children of Israel also coming out of Aegypt\n"
	"possessed his land, and the land of Og the king of Basan, the two kings of the Amorrheites, which were beyond Jordan toward the rising of the sun:\n"
	"from Aroer, which is situated upon the bank of the torrent Arnon, unto the mountain Sion, which is also Hermon,\n"
	"all the plain beyond Jordan at the east side, unto the sea of the wilderness, and unto the foot of mount Phasga.";