const char* chap191 = "Who being passed over, our Lord said to Josue:\n"
	"Choose twelve men, one in every tribe:\n"
	"& command them that they take up out of the midst of the channel of Jordan, where the feet of the Priests stood, twelve most hard stones, which you shall put in the place of the camp, where you shall pitch tents this night.\n"
	"And Josue called twelve men, whom he had chosen out of the children of Israel, one of every tribe,\n"
	"and he said to them: Go before the ark of our Lord your God to the midst of Jordan, and carry from thence every man a stone on your shoulders, according to the number of the children of Israel,\n"
	"that it may be a sign among you: and when your children shall ask you tomorrow, saying: What mean these stones?\n"
	"You shall answer them: The waters of Jordan decayed before the ark of the covenant of our Lord, when it passed over the same: therefore were these stones set for a monument of the children of Israel for ever.\n"
	"The children of Israel therefore did as Josue commanded them, carrying out of the channel of Jordan twelve stones, as our Lord had commanded him, according to the number of the children of Israel, unto the place, wherein they camped, and there they set them.\n"
	"Other twelve stones also Josue put in the midst of the channel of Jordan, where the Priests stood, that carried the ark of the covenant: and they be there until this present day.\n"
	"But the Priests that carried the ark, stood in the midst of Jordan, till all things were accomplished which our Lord had commanded Josue to speak to the people, and Moyses had said to him. And the people made haste, and passed over.\n"
	"And when they had all passed over, the ark also of our Lord passed over, the Priests also went before the people.\n"
	"The children of Ruben also and Gad, & the half tribe of Manasses, went armed before the children of Israel, as Moyses had commanded them:\n"
	"and forty thousand fighting men by troops, and bands marched through the plain and champion country of the city of Jericho.\n"
	"In that day our Lord magnified Josue before all Israel, that they should fear him, as they had feared Moyses, whiles he yet lived.\n"
	"And he said to him:\n"
	"Command the Priests that carry the ark of the covenant, that they come up out of Jordan.\n"
	"Who commanded them, saying: Come ye up out of Jordan.\n"
	"And when they that carried the ark of the covenant of our Lord were come up, & began to tread on the dry ground, the waters returned into their channel, and ran as they were wont before.\n"
	"And the people came up out of Jordan the tenth day of the first month, and camped in Galgal against the East side of the city of Jericho.\n"
	"The twelve stones also, which they had taken out of the channel of Jordan, Josue set in Galgal,\n"
	"and said to the children of Israel: When your children shall ask their fathers tomorrow, and shall say to them: What mean these stones?\n"
	"You shall teach them, and say: By the dry channel did Israel pass over this Jordan,\n"
	"your Lord God drying the waters thereof in your sight, until you passed over:\n"
	"as he had done before in the red sea, which he dried till we passed through:\n"
	"that all the people of the earth may learn the most strong hand of our Lord, that you also may fear our Lord your God.";