const char* chap2 = "The heavens therefore & the earth were fully finished, and all the furniture of them.\n"
	"And the seventh day God ended his work which he had made; and rested the seventh day, from all work that he had done.\n"
	"And he blessed the seventh day & sanctified it: because in it he had ceased from all his work which God created to make.\n"
	"These are the generations of heaven & earth, when they were created in the day, when our Lord God made the heaven, and the earth,\n"
	"and every plant of the field, before it shot up in the earth, and every herb of the ground before it sprang. For our Lord God had not rained upon the earth; and man was not^ to till the earth:\n"
	"But a spring rose out of the earth, watering all the overmost part of the earth.\n"
	"Our Lord God therefore formed man of the slime of the earth: and breathed into his face the breath of life, & man became a living soul.\n"
	"And our Lord God had planted Paradise of pleasure from the beginning: wherein he placed man whom he had formed.\n"
	"And our Lord God brought forth of the ground all manner of trees, fair to behold, and pleasant to eat of: the tree of life also in the middle of Paradise: and the tree of knowledge of good and evil.\n"
	"And a river issued out of the place of pleasure to water Paradise, which from thence is divided into four heads.\n"
	"The name of one is Phison: that is it which compasseth all the land of Hevilath, where gold groweth.\n"
	"And the gold of that land is very good: there is found bdellium, and the stone onyx.\n"
	"And the name of the second river is Gehon: that is it which compasseth all the land of Ethiopia.\n"
	"And the name of the third river is Tigris: that same passeth along by the Assyrians. And the fourth river, the same is Euphrates.\n"
	"Our Lord God therefore took man, & put him in the Paradise of pleasure, to work, & keep it.\n"
	"And he commanded him saying: Of every tree of Paradise eat thou:\n"
	"But of the tree of knowledge of good & evil eat thou not. For in what day soever thou shalt eat of it, thou shalt die the death.\n"
	"Our Lord God also said: It is not good for man to be alone: let us make him a help like unto himself.\n"
	"Our Lord God therefore having formed of clay all beasts of the earth, and fowls of the air; brought them to Adam, that he might see what to call them: for all that Adam called any living creature, the same is his name.\n"
	"And Adam called all beasts by their names, and all fowls of the air, and all cattle of the field: but unto Adam there was not found an helper like himself.\n"
	"Our Lord God therefore cast a deep sleep upon Adam: and when he was fast asleep, he took one of his ribs, & filled up flesh for it.\n"
	"And our Lord God built the rib which he took of Adam into a woman, & brought her to Adam.\n"
	"And Adam said: This now is bone of my bones, and flesh of my flesh: she shall be called woman, because she was taken out of man.\n"
	"Wherefore man shall leave his father & mother, & shall cleave to his wife, & they shall be two in one flesh.\n"
	"And they were both naked, to wit Adam and his wife; and were not ashamed.";