const char* chap211 = "And Josue gathered together all the tribes of Israel into Sichem, and called the ancients, and Princes, and judges, and masters: and they stood in the sight of our Lord:\n"
	"and to the people he spake in this manner: Thus saith our Lord the God of Israel: Beyond the river did your fathers dwell from the beginning, Thare the father of Abraham, and of Nachor: and they served strange gods.\n"
	"I took therefore your father Abraham from the coasts of Mesopotamia, and brought him into the Land of Chanaan, and multiplied his seed,\n"
	"and gave him Isaac: & again to him I gave Jacob and Esau. Of whom, to Esau I gave mount Seir to possess: but Jacob & his children went down into Aegypt.\n"
	"And I sent Moyses & Aaron, & struck Aegypt with many signs and wonders.\n"
	"And I brought you and your fathers out of Aegypt, and you came to the sea: and the Aegyptians pursued your fathers with chariots and horsemen, as far as the Red sea.\n"
	"And the children of Israel cried to the Lord: who did put darkness between you and the Aegyptians, and brought the sea upon them, & overwhelmed them. Your eyes saw all things I did in Aegypt, and you dwelt in the wilderness a great time:\n"
	"& I brought you into the Land of the Amorrhite, which dwelt beyond Jordan. And when they fought against you, I delivered them into your hands, and you possessed their Land, and slew them.\n"
	"And there rose Balac the son of Sephor king of Moab, and fought against Israel. And he sent and called Balaam the son of Beor, that he might curse you:\n"
	"& I would not hear him, but contrarywise by him I blessed you, and delivered you out of his hand.\n"
	"And you passed Jordan, and came to Jericho. And the men of that city fought against you, the Amorrhite, and Pherezite, and Chananite, & the Hetheite, and Gergesite, and the Heveite, and Jebusite: & I delivered them into your hands.\n"
	"And I sent before you hornets: and I cast them forth out of their places, the two kings of the Amorrheites, not in thy sword and bow.\n"
	"And I gave you the Land, wherein you laboured not, and the cities which you built not, to dwell in them: vineyards and olive trees, which you planted not.\n"
	"Now therefore fear our lord and serve him with a perfect and very true heart: and take away the gods, which your fathers served in Mesopotamia and in Aegypt, and serve our Lord.\n"
	"But if it like you not to serve our Lord, choice is given you: choose this day that which pleaseth you, whom you ought especially to serve, whether the gods, which your fathers served in Mesopotamia, or the gods of the Amorrheites, in whose Land you dwell: but I and my house will serve our Lord.\n"
	"And the people answered, and said: God forbid we should leave our Lord, and serve strange gods.\n"
	"Our Lord God he brought us and our fathers out of the Land of Aegypt, out of the house of servitude: and did in our sight great signs, & kept us in all the way by the which we walked, & among all the peoples, through which we passed.\n"
	"And he hath cast out all the nations, the Amorrhite inhabiter of the Land, which we have entered. We therefore will serve our Lord, because he is our God.\n"
	"And Josue said to the people: You cannot serve our Lord: for God is holy, and a mighty emulator, neither will he pardon your wickedness & sins.\n"
	"If you leave our Lord, and serve strange gods, he will turn himself; and will afflict you, & overthrow you after he hath given you good things.\n"
	"And the people said to Josue: No, it shall not be so as thou speakest, but we will serve our Lord.\n"
	"And Josue said to the people: You are witnesses, that yourselves have chosen to you our Lord for to serve him. And they answered: Witnesses.\n"
	"Now therefore, quoth he, take away strange gods out of the midst of you, and incline your hearts to our Lord the God of Israel.\n"
	"And the people said to Josue: We will serve our Lord God, and will be obedient to his precepts.\n"
	"Josue therefore in that day made a covenant, and proposed to the people precepts and judgments in Sichem.\n"
	"He wrote also all these words in the volume of the law of our Lord: and he took a very great stone, and put it under the oak, that was in the Sanctuary of our Lord:\n"
	"and said to all the people: Behold this stone shall be a testimony for you, that it hath heard all the words of our Lord, which he hath spoken to you: lest perhaps hereafter you will deny, and lie to our Lord your God.\n"
	"And he dismist the people, every one into their possession.\n"
	"And after these things^ Josue the Son of Nun the servant of our Lord died, being an hundred and ten years old:\n"
	"and they buried him in the coasts of his possession in Thamnathsare, which is situated in the mountain of Ephraim, on the North part of mount Gaas.\n"
	"And Israel served our Lord all the days of Josue, and of the ancients, that lived a long time after Josue, & that had known all the works of our Lord which he had done in Israel.\n"
	"The bones also of Joseph which the children of Israel had taken out of Aegypt, they buried in Sichem, in part of the field, which Jacob had bought of the sons of Hemor the father of Sichem, for a hundred young ewes, and it was in the possession of the sons of Joseph.\n"
	"Eleazar also the son of Aaron died: and they buried him in Gabaath of Phinees his son, which was given him in mount Ephraim.";