const char* chap216 = "And Debbora and Barac the son of Abinoem sang in that day, saying:\n"
	"You that of Israel have voluntarily offered your lives to peril, bless our Lord.\n"
	"Hear you kings, and give ear ye Princes: I am, I am she, that will sing to our Lord, I will chant to our Lord the God of Israel.\n"
	"Lord when thou wentest out of Seir, and didst pass by the countries of Edom, the earth was moved, and the heavens and clouds distilled waters.\n"
	"The mountains melted before the face of our Lord, and Sinai before the face of our Lord God of Israel.\n"
	"In the days of Samgar the son of Anath, in the days of Jahel the paths rested: and they that went by them, walked by by-ways.\n"
	"The valiants in Israel ceased, and rested: until Debbora arose, a mother rose in Israel.\n"
	"Our Lord chose new wars, and the gates of the enemies himself subverted: shield and spear if there appeared among forty thousand of Israel.\n"
	"My heart loveth the Princes of Israel: you that of your own good will^ offered yourselves to danger, bless our Lord.\n"
	"You that ride upon your fair asses, and sit in judgment, and walk in the way, speak.\n"
	"Where the chariots were crushed together, and the army of the enemies was suffocated, there let the justices of our Lord be told, and his clemency toward the valiants of Israel: then did the people of Our Lord go down to the gates, and obtained the principality.\n"
	"Arise, arise Debbora, arise, arise, and speak a canticle: Arise Barac, and apprehend thy captives thou son of Abinoem.\n"
	"The remnant of the people is saved, our Lord hath fought in the valiants.\n"
	"Out from Ephraim he destroyed them into Amalec, and after him out from Benjamin into thy peoples O Amalec: Out from Machir there descended Princes, and out from Zabulon they that led the army to fight.\n"
	"The Captains of Issachar were with Debbora, and followed the steps of Barac, who as it were into a headlong and bottomless pit gave himself to danger: Ruben being divided against it-self, there was found contention of courageous persons.\n"
	"Why dwellest thou between the two bounds, that thou mayest hear the whistlings of the flocks? Ruben being divided against itself, there was found contention of courageous men.\n"
	"Galaad rested beyond Jordan, and Dan gave himself to ships: Aser dwelt in the sea shore, and abode in havens.\n"
	"But Zabulon and Nephthali offered their lives to death in their country of Merome.\n"
	"The kings came & fought, the kings of Chanaan fought in Thanac besides the waters of Mageddo, and yet going a preying they took nothing.\n"
	"From heaven they fought against them: the stars remaining in their order and course, fought against Sisara.\n"
	"The torrent of Cison drew their carcasses, the torrent of Cadumim, the torrent of Cison: my soul tread down the strong ones.\n"
	"The hoof of the horses fell off, the strongest of the enemies flying violently, and falling down headlong.\n"
	"Curse ye the land of Meroz, said the Angel of our Lord: Curse the inhabitants thereof, because they came not to help our Lord, to aid his most mighty ones.\n"
	"Blessed among women be Jahel the wife of Haber the Cineite, and blessed be she in her tabernacle.\n"
	"To him that asked water she gave milk, and in the phial of Princes she offered butter.\n"
	"Her left hand she put to the nail, and her right hand to the smiths' hammer, and struck Sisara, seeking in his head a place for the wound, and piercing valiantly through his temple.\n"
	"Between her feet he fell: he failed, and died: he was rolled before her feet, and he lay without life and miserable.\n"
	"Looking through a window, his mother howled: and she spake out of a higher chamber: Why lingereth his chariot to come back? Wherefore are the feet of his waggons slow?\n"
	"One wiser than the rest of his wives answered these words to her mother in law:\n"
	"Peradventure now he divideth the spoils, and the fairest of the women is chosen for him: garments of sundry colours are delivered to Sisara for a prey, and diverse furniture is laid together to adorn the necks.\n"
	"So perish all thine enemies, O Lord: but they that love thee, as the Sun shineth in his rising, so let them glitter.\n"
	"And the Land rested for forty years.";