const char* chap222 = "There was at that time Jephte the Galaadite, a most valiant man & a warrior, the son of a woman that was an harlot, who was born of Galaad.\n"
	"And Galaad had a wife of whom he had sons: who after they were grown, cast out Jephte, saying: Thou canst not be heir in the house of our father, because thou art born of another mother.\n"
	"Whom he flying & avoiding, dwelt in the Land of Tob: and there were gathered to him needy men, & thievish, & followed him as their Prince.\n"
	"In those days the children of Ammon fought against Israel:\n"
	"who pressing sore upon them, the ancients of Galaad went to take Jephte out of the Land of Tob to help them:\n"
	"& they said to him: Come & be our Prince, & fight against the children of Ammon.\n"
	"To whom he answered: Are not you they that hated me, & cast me out of my father's house, and now are come to me forced by necessity.\n"
	"And the Princes of Galaad said to Jephte: For this cause be we now come to thee, that thou go forth with us, & fight against the children of Ammon, and be the Captain of all that dwell in Galaad.\n"
	"Jephte also said to them: If you be come to me sincerely, that I should fight for you against the children of Ammon, and if our Lord deliver them into my hands, shall I be your Prince?\n"
	"Who answered him: Our Lord which heareth these things, himself is mediator and witness that we will do as we have promised.\n"
	"Jephte therefore went with the Princes of Galaad, and all the people made him their Prince. And Jephte spake all his words before our Lord in Maspha.\n"
	"And he sent messengers to the king of the children of Ammon, which should say in his person: What is between me and thee, that thou art come against me, to waste my Land?\n"
	"To whom he answered: Because Israel took my land when he ascended out of Aegypt, from the coasts of Arnon unto Iaboc and Jordan: now therefore with peace restore the same to me.\n"
	"By whom Jephte again sent word, and commanded them that they should say to the king of Ammon:\n"
	"Thus saith Jephte: Israel did not take the Land of Moab, nor the Land of the children of Ammon:\n"
	"but when they ascended out of Aegypt, he walked through the desert unto the Red sea, and came into Cades.\n"
	"And he sent messengers to the king of Edom, saying: Suffer me that I may pass through the land. Who would not condescend to his requests. He sent also to the king of Moab, who also himself contemned to give passage. He abode therefore in Cades,\n"
	"and compassed the Land of Edom at the side, and the land of Moab: & came against the East quarter of the Land of Moab, & camped beyond Arnon: neither would he enter the bounds of Moab: for Arnon is the border of the Land of Moab.\n"
	"Israel therefore sent messengers to Sehon the king of the Amorrheites, who dwelt in Hesebon, & they said to him: Suffer me to pass through thy land unto the river.\n"
	"Who also himself despising the words of Israel, suffered him not to pass through his borders: but gathering an infinite multitude went forth against him into Jasa, & resisted strongly.\n"
	"And our Lord delivered him into the hands of Israel with all his army, & he struck him, & possessed all the Land of the Amorrhite the inhabiter of that country,\n"
	"and all the coasts thereof from Arnon unto Iaboc, and from the wilderness unto Jordan.\n"
	"Our Lord therefore the God of Israel subverted the Amorrhite, his people of Israel fighting against him, and wilt thou now possess his land?\n"
	"Are not those things which Chamos thy god possessed, due to thee by right? But the things that our Lord God hath obtained conqueror, shall come to our possession:\n"
	"unless perhaps thou be better than Balac the son of Sephor the king of Moab: or canst shew, that he wrangled against Israel, and fought against him,\n"
	"when he dwelt in Hesebon, & the little towns thereof, & in Aroer, & the towns thereof, or in all the cities near Jordan, for three hundred years. Wherefore have you so long attempted nothing for reclaim?\n"
	"Therefore I do not sin against thee, but thou doest evil against me, denouncing me unjust wars. Our Lord be judge the arbiter of this day between Israel, and between the children of Ammon.\n"
	"And the king of the children of Ammon would not harken to the words of Jephte, which he sent him by the messengers.\n"
	"Therefore the spirit of our Lord came upon Jephte, and circuiting Galaad, and Manasses, Maspha also of Galaad, and thence passing to the children of Ammon,\n"
	"he vowed a vow to our Lord, saying: If thou wilt deliver the children of Ammon into my hands,\n"
	"whosoever shalt first come forth out of the doors of my house, and shall meet me returning with peace from the children of Ammon, him will I offer an holocaust to our Lord.\n"
	"And Jephte passed to the children of Ammon, to fight against them: whom our Lord delivered into his hands.\n"
	"And he struck from Aroer till thou come to Mennith, twenty cities, and as far as Abel, which is set with vineyards, with a very great plague. And the children of Ammon were humbled by the children of Israel.\n"
	"But Jephte returning into Maspha to his house, his only begotten daughter met him with timbrels and dances. For he had not other children.\n"
	"Whom when he saw, he rent his garments, and said: Woe is me my daughter, thou hast deceived me, and thyself art deceived: for I have opened my mouth to our Lord, and I can do no other thing.\n"
	"To whom she answered: My father, if thou hast opened thy mouth to our Lord, do unto me whatsoever thou hast promised, the revenge & victory of thine enemies being granted to thee.\n"
	"And she said to her father: This only grant me which I desire: Suffer me that two months I may go about the mountains, & bewail my virginity with my fellows.\n"
	"To whom he answered: Go. And he dismissed her two months. And when she was gone with her fellows and companions, she mourned her virginity in the mountains.\n"
	"And the two months being expired, she returned to her father, and he did to her as he had vowed, who knew not man. Thence-forth a fashion in Israel, and a custom was kept:\n"
	"that after the compass of a year the daughters of Israel assemble together, and mourn the daughter of Jephte the Galaadite four days.";