const char* chap223 = "But behold in Ephraim there arose a sedition. For they passing against the North, said to Jephte: Going to fight against the children of Ammon, why wouldst thou not call us, that we might go with thee? Therefore we will burn thy house.\n"
	"To whom he answered: I and my people were at great strife against the children of Ammon: & I called you, that you should aid me, and you would not do it.\n"
	"Which I seeing put my life in mine own hands, and passed to the children of Ammon, and our Lord delivered them into my hands. What have I deserved, that you rise against me in battle.\n"
	"Therefore all the men of Galaad being called to him, he fought against Ephraim: and the men of Galaad struck Ephraim, because he had said: Galaad is a fugitive of Ephraim, & dwelleth in the midst of Ephraim & Manasses.\n"
	"And the Galaadites took the fords of Jordan, by the which Ephraim was to return. And when there had come to the same^ one of the number of Ephraim, flying, and had said: I beseech you let me pass: The Galaadites said to him: Art thou not an Ephraite? Who saying: I am not:\n"
	"they asked him: Say then Schibboleth, which is interpreted an ear of corn. Who answered, Sibboleth, not being able by the same letter to express, an ear of corn. And immediately being apprehended they killed him in the very passage of Jordan. And there fell at that time of Ephraim two and forty thousand.\n"
	"Therefore Jephte the Galaadite judged Israel six years: and he died, and was buried in his city of Galaad.\n"
	"After him Abesan of Bethlehem judged Israel:\n"
	"who had thirty sons, and as many daughters, which he sending abroad, gave to husbands, and took wives for his sons of the same number, bringing them into his house. Who judged Israel seven years:\n"
	"and died and was buried in Bethlehem.\n"
	"To whom succeeded Ahialon a Zabulonite: and he judged Israel ten years:\n"
	"and he died and was buried in Zabulon.\n"
	"After him^ Abdon judged Israel, the son of Illel a Pharathonite:\n"
	"who had forty sons, and of them thirty nephews, mounting upon seventy ass colts, and he judged Israel eight years:\n"
	"and he died, and was buried in Pharathon of the Land of Ephraim, in the mount of Amalec.";