const char* chap243 = "Therefore the men of Cariathiarim came, and brought back the ark of our Lord, and carried it into the house of Abinadab in Gabaa: and Eleazar his son they sanctified, that he might keep the ark of our Lord.\n"
	"And it came to pass, from the day that the ark of our Lord abode in Cariathiarim, the days were multiplied (for it was now the twentieth year) and all the house of Israel rested after our Lord.\n"
	"And Samuel spake to all the house of Israel, saying: If you turn to our Lord in all your heart, take away the strange gods out of the midst of you, Baalim and Astaroth: and prepare your hearts to our Lord, & serve him only, and he will deliver you from the hand of the Philisthiims.\n"
	"Therefore the children of Israel took away Baalim and Astaroth, and served our Lord only.\n"
	"And Samuel said: Gather together all Israel into Masphath, that I may pray our Lord for you.\n"
	"And they assembled into Masphath: and they drew water, and poured it out in the sight of our Lord, and they fasted that day, and said there: We have sinned to our Lord. And Samuel judged the children of Israel in Masphath.\n"
	"And the Philisthiims heard that the children of Israel were gathered together into Masphath, and the Princes of the Philisthiims went up to Israel. Which when the children of Israel had heard, they were afraid at the face of the Philisthiims.\n"
	"And they said to Samuel: cease not to cry to our Lord God for us, that he save us from the hand of the Philisthiims.\n"
	"And Samuel took one sucking lamb, and offered it a whole holocaust to our Lord: and Samuel cried to our Lord for Israel, & our Lord heard him.\n"
	"And it came to pass, when Samuel offered the holocaust, the Philisthiims began battle against Israel: but our Lord thundered with a great noise in that day upon the Philisthiims, & terrified them, & they were slain before the face of Israel.\n"
	"And the men of Israel issuing out of Masphath pursued the Philisthiims, & struck them unto the place, that was under Bethchar.\n"
	"And Samuel took one stone, and laid it between Masphath and Sen: and he called the name of that place, The stone of help. And he said: Thus far hath our Lord holpen us.\n"
	"And the Philisthiims were humbled, neither added they any more to come into the borders of Israel. Therefore the hand of our Lord was made upon the Philistiims, all the days of Samuel.\n"
	"And the cities, which the Philistiims had taken from Israel, were rendered to Israel, from Accaron unto Geth, and their borders: and he delivered Israel from the hand of the Philistiims, and there was peace between Israel and the Amorrheite.\n"
	"Samuel also judged Israel all the days of his life:\n"
	"and he went every year circuiting Bethel and Galgala and Masphath, and judged Israel in the foresaid places.\n"
	"And he returned into Ramatha: for there was his house, and there he judged Israel: he built also there an altar to our Lord.";