const char* chap244 = "And it came to pass when Samuel waxed old, he appointed his sons judges over Israel.\n"
	"And the name of his first begotten son was Joel: and the name of the second Abia, judges in Bersabee.\n"
	"And his sons walked not in his ways: but they declined after avarice, & took bribes, and perverted judgment.\n"
	"Therefore all the ancients of Israel being assembled, came to Samuel into Ramatha.\n"
	"And they said to him: Behold thou art old, and thy sons walk not in thy ways: appoint us a king, that he may judge us, as also all nations have.\n"
	"And the word was misliked in the eyes of Samuel, because they had said: Give us a king, that he may judge us. And Samuel prayed to our Lord.\n"
	"And our Lord said to Samuel: Hear the voice of the people in all things which they speak to thee. For they have not rejected thee, but me, that I should not reign over them.\n"
	"According to all their works, which they have done from the day that I brought them out of Aegypt until this day: as they have forsaken me, and served strange gods, so do they also unto thee.\n"
	"Now therefore hear their voice: but yet testify to them, and foretell them the right of the king, that shall reign over them.\n"
	"Samuel therefore spake all the words of our Lord to the people which had desired a king of him,\n"
	"and said: This shall be the right of the king, that shall reign over you: Your sons he will take, & put in his chariots, and will make them unto him the horsemen, and running footmen before his chariots,\n"
	"& will appoint them his tribunes, & centurions, & the ploughers of his fields, & mowers of his corn, & makers of his armour and of his chariots.\n"
	"Your daughters also will he take to make ointments, and to be cooks, and bakers.\n"
	"Your fields also, and vineyards, and the best olivets he will take away, and give to his servants.\n"
	"Yea and your corn also, and the revenues of your vineyards he will tithe, to give his eunuchs & servants.\n"
	"Your servants also and handmaids, and goodliest young men, and asses he will take away and put in his work.\n"
	"Your flocks also will he tithe, you shall be his servants.\n"
	"And you shall cry in that day from the face of the king, which you have chosen you: and our Lord will not hear you in that day, because you desired unto yourselves a king.\n"
	"But the people would not hear the voice of Samuel, but said: Not so: for there shall be a king over us,\n"
	"and we also will be as all nations: and our king shall judge us, and shall go forth before us, and shall fight our battles for us.\n"
	"And Samuel heard all the words of the people, and spake them in the ears of our Lord.\n"
	"And our Lord said to Samuel: Hear their voice, and appoint a king over them. And Samuel said to the men of Israel: Let every man go into his city.";