const char* chap26 = "And when a famine was risen in the land, after that sterility that had chanced in the days of Abraham, Isaac went to Abimelech king of the Palestines into Gerara.\n"
	"And our Lord appeared to him, and said: Go not down into Aegypt, but rest in the land which I shall tell thee.\n"
	"And sojourn in it, and I will be with thee, and will bless thee: for to thee and to thy seed I will give all these countries, accomplishing the oath which I sware to Abraham thy father.\n"
	"And I will multiply thy seed as the stars of heaven: and I will give to thy posterity all these countries: and in thy seed SHALL BE BLESSED ALL THE NATIONS OF THE EARTH,\n"
	"for because Abraham obeyed my voice, & kept my precepts and commandments, and observed my ceremonies and laws.\n"
	"Therefore Isaac abode in Gerara.\n"
	"Who when he was asked by the men of that place concerning his wife, answered: She is my sister; for he was afraid to confess that she was married to him, thinking lest peradventure they would kill him because of her beauty.\n"
	"And when very many days were passed, & he abode there, Abimelech the king of the Palestines looking forth through a window saw him sporting with Rebecca his wife.\n"
	"And calling for him, he said: it is evident that she is thy wife: why didst thou feign her to be thy sister? He answered: I feared lest I should die for her.\n"
	"And Abimelech said: Why hast thou deceived us? Some man of the people might have lien with thy wife, and thou hadst brought upon us a great sin. And he commanded all the people, saying:\n"
	"He that shall touch this man's wife, dying shall die.\n"
	"And Isaac sowed in that land, and he found that same year and hundred fold: and our Lord blessed him.\n"
	"And the man was made rich, and he went prospering and increasing, till he was made exceeding great:\n"
	"and he had also possessions of sheep and of herds, and a very great family. For this the Palestines envying him,\n"
	"stopped at that time all the wells, that the servants of his father Abraham had digged, filling them up with earth:\n"
	"in so much that Abimelech himself said to Isaac: Depart from us, because thou art become mightier than we a great deal.\n"
	"And departing, to come to the Torrent of Gerara, and to dwell there,\n"
	"again he digged other wells, which the servants of his father Abraham had digged, and which after his death the Philistines had stopped up of old: & he called them by the same names which his father before had called them.\n"
	"And they digged in the Torrent, and found living water:\n"
	"but there also the pastors of Gerara made a brawl against the pastors of Isaac, saying: it is our water. For which cause he called the name of the well, by occasion of that which had happened, Calumny.\n"
	"And they digged also another; and for that they brawled likewise, and he called the name of it, Enmity.\n"
	"Going forward from thence he digged another well, for which they contended not: therefore he called the name thereof, Latitude, saying: Now hath our Lord dilated us, and made us to increase upon the earth.\n"
	"And he went up from that place unto Bersabee,\n"
	"Where our Lord appeared to him that same night, saying: I am the God of Abraham thy father, do not fear, because I am with thee: I will bless thee, and multiply thy seed for my servant Abraham's sake.\n"
	"Therefore he builded there an altar: and having called upon the name of our Lord, he pitched his tent: & commanded his servants that they should dig a well.\n"
	"To the which place when there were come from Gerara Abimelech, and Ocozath his friend, & Phicol chief Captain of his soldiers,\n"
	"Isaac spake to them: Why are ye come to me a man whom you hated, and have thrust out from you?\n"
	"Who answered: We saw that the Lord is with thee, and therefore we said: Let there be an oath between us, and let us make a league,\n"
	"that thou do us no harm, as we also have touched nothing of thine, neither have we done that which might hurt thee: but with peace have we dismissed thee increased with the blessing of the Lord.\n"
	"Therefore he made them a feast, and after they had eaten and drunken,\n"
	"Arising in the morning, they sware one to another: and Isaac dismissed them peaceably into their place.\n"
	"And behold the same day came the servants of Isaac telling him of a well, which they had digged, and saying: We have found water.\n"
	"Whereupon he called it Abundance: and the name of the city was given Bersabee, even unto this present day.\n"
	"But Esau being forty years old married wives, Judith the daughter of Beeri the Hethite, and Basemath the daughter of Elon of the same place:\n"
	"Both which had offended the mind of Isaac and Rebecca.";