const char* chap260 = "David therefore went up from thence, and dwelt in the safest places of Engaddi.\n"
	"And when Saul was returned, after he pursued the Philistians, they told him, saying: Behold, David is in the desert Engaddi.\n"
	"Saul therefore taking unto him three thousand chosen men of all Israel, went forth to search out David & his men, yea over the steep broken rocks, which are accessible only to wild goats.\n"
	"And he came to the sheepcotes, which fell in his way as he went, and there was a cave, which Saul entered into, to do his easement: moreover David and his men lay hid in the inner part of the cave.\n"
	"And the servants of David said to him: Behold the day, whereof our Lord said to thee: I will deliver thee thine enemy, that thou mayest do to him as it shall seem good in thine eyes. David therefore arose, and cut off the hem of Saul's cloak softly.\n"
	"After this David's heart struck him, for that he had cut off the hem of Saul's cloak.\n"
	"And he said to his men: Our Lord be merciful unto me, that I do not this thing to my master the anointed of our Lord, that I should lay my hand upon him, because he is the anointed of our Lord.\n"
	"And David persuaded his men with words, and permitted them not to rise against Saul: moreover Saul rising out of the cave, went on his journey begun.\n"
	"And David rose up after him: and going out of the cave, cried behind Saul's back, saying: My lord king. And Saul looked back behind him: and David bowing himself flat toward the ground adored,\n"
	"and said to Saul: Why dost thou hear the words of men that say: David seeketh evil against thee?\n"
	"Lo this day thine eyes have seen, that our Lord delivered thee in my hand, in the cave, and I had a cogitation to kill thee, but mine eye hath spared thee. For I said: I will not extend mine hand upon my Lord, because he is the anointed of our Lord.\n"
	"But rather see and know, o my father, the hem of thy cloak in my hand, that when I did cut off the hem of thy cloak, I would not extend my hand upon thee. Mark, and see, that there is no evil in my hand, nor iniquity, neither have I sinned against thee: but thou liest in wait for my life, to take it away.\n"
	"Our Lord judge between me and thee, and our Lord revenge me of thee, but be not my hand upon thee.\n"
	"As also it is said in the old proverb: FROM THE IMPIOUS shall impiety proceed: be not therefore my hand upon thee: Whom dost thou persecute, o king of Israel?\n"
	"Whom dost thou persecute? Thou persecutest a dead dog, and a flea.\n"
	"Our Lord be judge, and judge between me and thee, and he see, and judge my cause, and deliver me out of thy hand.\n"
	"And when David had fully ended speaking such words to Saul, Saul said: Is this thy voice my son David? And Saul lifted up his voice, and wept:\n"
	"and said to David: Thou art juster than I: for thou hast done me good turns, and I have rendered thee evil.\n"
	"And thou hast shewed this day what good things thou hast done to me: how our Lord delivered me into thy hand, and thou hast not killed me.\n"
	"For who when he hath found his enemy, will let him go in a good way? But our Lord render thee this good turn, for that which thou hast wrought toward me this day.\n"
	"And now because I know that thou most certainly shalt reign, and have the Kingdom of Israel in thy hand:\n"
	"swear to me in our Lord, not to destroy my seed after me, nor to take away my name from the house of my father.\n"
	"And David sware to Saul. Saul therefore went into his house: and David and his men went up into safer places.";