const char* chap279 = "Our Lord therefore sent Nathan to David: Who when he was come to him, he said unto him: There were two men in one city, one rich, and the other poor.\n"
	"The rich man had sheep, and oxen exceeding many.\n"
	"But the poor man had nothing at all, beside one little ewe, which he had bought and nourished, and which had grown in his house together with his children, eating of his bread, and drinking of his cup, & sleeping in his bosom: & it was to him as a daughter.\n"
	"And when a certain stranger was come to the rich man, he sparing to take of his own sheep and oxen, to make a feast for that stranger, which was come to him, took the poor man's ewe, & made meats thereof for the man that was come to him.\n"
	"And David being exceedingly wrath with indignation against that man, said to Nathan: Our Lord liveth, the man that hath done this is the child of death.\n"
	"He shall render the ewe fourfold, because he hath done this thing, & hath not spared.\n"
	"And Nathan said to David: Thou art that man. Thus saith our Lord the God of Israel: I anointed thee to be king over Israel, & I delivered thee from the hand of Saul,\n"
	"and gave thee the house of thy lord, & the wives of thy lord in thy bosom, and have given thee the house of Israel and Juda: & if these things be little, I will add far greater things unto thee.\n"
	"Why therefore hast thou contemned the word of the Lord, that thou wouldest do evil in my sight? Urias the Hetheite thou hast smitten with the sword, and his wife thou hast taken to thy wife, and hast slain him with the sword of the children of Ammon.\n"
	"For which thing the sword shall not depart from thy house for ever, because thou hast despised me, and hast taken the wife of Urias the Hetheite, to be thy wife.\n"
	"Therefore thus saith our Lord: Behold, I will raise upon thee evil out of thine own house, and will take thy wives before thine eyes, and give them to thy neighbour, and he shall sleep with thy wives in the sight of this sun.\n"
	"For thou hast done it secretly: but I will do this word in the sight of all Israel, and in the sight of the sun.\n"
	"And David said to Nathan: I have sinned to our Lord. And Nathan said to David: Our Lord also hath taken away thy sin: thou shalt not die.\n"
	"Nevertheless, because thou hast made the enemies of our Lord to blaspheme, for this thing, the son that is born to thee dying shall die.\n"
	"And Nathan returned into his house. Our Lord also struck the child, which the wife of Urias had born to David, and he was past hope.\n"
	"And David besought our Lord for the child: and David fasted a fast, and going in aside, lay upon the ground.\n"
	"And the ancients of his house came, being earnest with him, that he would rise from the ground: who would not, neither did he eat meat with them.\n"
	"And it chanced the seventh day that the infant died: and the servants of David feared to tell him, that the child was dead. For they said: Behold when the child yet lived, we spake to him, and he heard not our voice: how much more if we shall say, The child is dead, will he afflict himself?\n"
	"When David therefore saw his servants muttering, he understood that the infant was dead: and he said to his servants: Is the child dead? Who answered him: He is dead.\n"
	"David therefore rose from the ground; and was washed and anointed: and when he had changed his garment, he entered into the house of our Lord: and adored, and came into his own house, and he called for bread, and he did eat.\n"
	"And his servants said unto him: What thing is this, that thou hast done? For the infant, when he yet lived, thou didst fast and weep: but the child being dead, thou didst rise up, and hast eaten bread.\n"
	"Who said: For the infant, whiles he yet lived, I fasted and wept; for I said: Who knoweth if perhaps our Lord will give him to me, and the infant may live?\n"
	"But now because he is dead, why do I fast? Shall I be able to call him again any more? I shall go to him rather: but he shall not return to me.\n"
	"And David comforted Bethsabee his wife, & going in unto her, slept with her: Who bare a son, & he called his name Salomon, & our Lord loved him.\n"
	"And he sent by the hand of Nathan the Prophet, & called his name, Amiable to our Lord, because our Lord loved him.\n"
	"Joab therefore fought against Rabbath of the children of Ammon, & won the king's city.\n"
	"And Joab sent messengers to David, saying: I have fought against Rabbath, & the City of waters is to be taken.\n"
	"Now therefore gather the rest of the people, & besiege the city, & take it: lest when the city shall be wasted of me, the victory be ascribed to my name.\n"
	"David therefore gathered all the people, and went forth against Rabbath, and when he had fought, he took it.\n"
	"And he took the crown of their king from his head, in weight a talent of gold, having most precious stones, and it was put upon David's head. Yea & the prey of the city he carried away exceeding much:\n"
	"bringing forth also the people thereof sawed them, and drew round about over them chariots shod with iron: and he divided them with knives, and drew them through in form of bricks: so did he to all the cities of the children of Ammon: and David returned, and all the army into Jerusalem.";