const char* chap281 = "And Joab the son of Sarvia, understanding that the king's heart was turned to Absalom,\n"
	"he sent to Thecua, and took thence a prudent woman: and he said to her: Feign that thou mournest, & put on a mourning garment, & be not anointed with oil, that thou mayest be as a woman now a long time mourning for one dead.\n"
	"And thou shalt go in unto the king, & shalt speak to him these manner of words. And Joab put the words in her mouth.\n"
	"Therefore when the woman of Thecua was gone in to the king, she fell before him upon the ground and adored, & said: Save me, o king.\n"
	"And the king said to her: What matter hast thou? Who answered: Alas, I am a widow woman: for my husband is dead.\n"
	"And thy handmaid had two sons: who fell at words against each other in the field, & there was none to stay them: & the one struck the other, & slew him.\n"
	"And behold the whole kindred rising against thy handmaid, saith: Deliver him that hath strucken his brother, that we may kill him for the life of his brother, whom he hath slain, & may clean destroy the heir: and they seek to extinguish my sparkle, which is left, that there may no name remain to my husband, nor relics upon the earth.\n"
	"And the king said to the woman: Go into thy house, and I will give commandment for thee.\n"
	"And the woman of Thecua said to the king: Upon me, my lord, be the iniquity, and upon the house of my father: but be the king & his throne innocent.\n"
	"And the king said: He that shall gainsay thee bring him to me, and he shall add no more to touch thee.\n"
	"Who said: Let the king remember our Lord his God, that the next of blood be not multiplied to revenge, and that they kill not my son. Who said: Our Lord liveth, there shall not fall of the hairs of thy son upon the earth.\n"
	"The woman therefore said: Let thy handmaid speak to my lord the king a word. And he said: Speak.\n"
	"And the woman said: Why hast thou thought such a thing against the people of God, and why hath the king spoken this word, that he would sin, and not bring again his banished one?\n"
	"We do all die, and as waters that return not, we fall down on the earth: neither will God have a soul to perish, but revoketh, meaning that he perish not altogether that is cast off.\n"
	"Now therefore I come, that I may speak to my lord the king this word, the people being present. And thy handmaid said: I will speak to the king, if by any means the king may do the word of his handmaid.\n"
	"And the king hath heard, to deliver his handmaid out of the hand of all, that would destroy me out of the inheritance of our Lord, and my son together.\n"
	"Let thy handmaid therefore say, that the word of my lord the king be made as a sacrifice. For even as an Angel of God, so is my lord the king, that he is moved neither with blessing nor cursing: Wherefore our Lord also thy God is with thee.\n"
	"And the king answering, said to the woman: Hide not from me the thing that I ask thee. And the woman said to him: Speak my lord king.\n"
	"And the king said: Is the hand of Joab with thee in all these things? The woman answered, & said: By the health of thy soul, my lord king, it is neither on the left hand, nor on the right of all these things, which my lord the king hath spoken: for thy servant Joab, he commanded me, and he put all these words into the mouth of thy handmaid.\n"
	"That I should change the form of this speech, thy servant Joab commanded this: and thou my lord king, art wise, as an Angel of God hath wisdom, that thou understandest all things upon the earth.\n"
	"And the king said to Joab: Behold I being pacified have done thy word: Go therefore, & call again the boy Absalom.\n"
	"And Joab falling upon his face unto the earth, adored, and blessed the king; and Joab said: This day thy servant hath understood, that I have found grace in thy sight my lord king for thou hast done the word of thy servant.\n"
	"Joab therefore arose and went into Gessur, and brought Absalom into Jerusalem.\n"
	"But the king said: Let him return into his house, and not see my face. Absalom therefore returned into his house, & the king's face he saw not.\n"
	"Moreover like as Absalom, there was not a man in all Israel so beautiful, & exceeding comely: from the sole of the foot to the crown there was no blemish in him.\n"
	"And when he polled his hair (once a year he was polled, because his bush did burden him) he weighed the hair of his head at two hundred sicles, of the common weight.\n"
	"And there were born to Absalom three sons: and one daughter, named Thamar, of a goodly beauty.\n"
	"And Absalom abode in Jerusalem two years, and saw not the king's face.\n"
	"He therefore sent to Joab, to send him to the king: who would not come to him. And when he had sent the second time, and he would not come to him,\n"
	"he said to his servants: You know the field of Joab beside my field, that hath barley harvest: go therefore and burn it with fire. The servants therefore of Absalom burnt the corn with fire. And Joab's servants coming, renting their garments, said: The servants of Absalom have burnt part of the field with fire.\n"
	"And Joab arose, & came to Absalom in his house, & said: Why have thy servants burnt my corn with fire?\n"
	"And Absalom answered Joab: I sent to thee beseeching thee that thou wouldst come unto me, & I might send thee to the king, & thou shouldst say to him: Wherefore came I out of Gessur? It was better for me to be there: I beseech thee therefore that I may see the face of the king: & if he be mindful of mine iniquity, let him kill me.\n"
	"Joab therefore entering in to the king, told him all things: and Absalom was called, and he entered in to the king: and adored upon the face of the earth before him: and the king kissed Absalom.";