const char* chap282 = "Therefore after these things Absalom made himself chariots, and horsemen, and fifty men, that should go before him.\n"
	"And Absalom rising early, stood beside the entrance of the gate, and every man that had business to the king's judgment, did Absalom call to him, and said: Of what city are thou? Who answering said: Of such a tribe of Israel am I^ thy servant.\n"
	"And Absalom answered him: Thy words seem unto me good and just. But there is none to hear thee appointed of the king. And Absalom said:\n"
	"Oh who would appoint me judge over the land, that all might come to me which have business, and I might judge justly!\n"
	"Yea and when a man came unto him to salute him, he put forth his hand, and taking him, kissed him.\n"
	"And this did he to all Israel coming for judgment, to be heard of the king, and he incited the hearts of the men of Israel.\n"
	"And after forty years, Absalom said to king David: Let me go, and pay my vows which I have vowed to our Lord in Hebron.\n"
	"For thy servant vowing did vow, when he was in Gessur of Syria, saying: If our Lord will bring me again into Jerusalem, I will sacrifice to our Lord.\n"
	"And king David said to him: Go in peace. And he arose, and went into Hebron.\n"
	"And Absalom sent spies into all the tribes of Israel, saying: forthwith as you shall hear the sound of the trumpet, say ye: Absalom reigneth in Hebron.\n"
	"Moreover with Absalom there went two hundred men out of Jerusalem being called, going with a simple heart, and utterly ignorant of the cause.\n"
	"Absalom also sent for Achitophel the Gilonite, David's counseller, from his city Gilo. And when he immolated victims, there was made a strong conspiracy, & the people running together increased with Absalom.\n"
	"A messenger therefore came to David, saying: All Israel with all their heart followeth Absalom.\n"
	"And David said to his servants, that were with him in Jerusalem: Arise let us fly: for there will be no escape for us from the face of Absalom: make haste to go out, lest coming perhaps he overtake us, and force ruin upon us, and strike the city in the edge of the sword.\n"
	"And the king's servants said to him: all things whatsoever our lord the king shall command, we thy servants will gladly execute.\n"
	"The king therefore went forth, and all his house on foot: & the king left ten women his concubines to keep the house.\n"
	"And the king going forth & all Israel on their feet, stood far from the house:\n"
	"and all his servants walked by him, and the legions Cerethi and Phelethi, and all the Getheites, valiant warriors, six hundred men which had followed him from Geth^ footmen, went before the king.\n"
	"And the king said to Ethai the Getheite: Why comest thou with us? Return and dwell with the king, because thou art a stranger, and art come forth out of thy place.\n"
	"Yesterday thou camest, and today shalt thou be forced to go forth with us? But I will go whither I shall go: return, and lead back thy brethren with thee, and our Lord will do with thee mercy and verity, because thou hast shewed grace and fidelity.\n"
	"And Ethai answered the king, saying: The Lord liveth, and my lord the king liveth: for that in what place soever thou shalt be, my lord king, either in death, or in life, there will thy servant be.\n"
	"And David said to Ethai: Come, and pass. And Ethai the Getheite passed, and all the men that were with him, and the rest of the multitude.\n"
	"And they all wept with a loud voice, and all the people passed: the king also went over the Torrent Cedron, and all the people marched against the way, that looketh to the desert.\n"
	"And Sadoc also the Priest came, and all the Levites with him carrying the ark of the covenant of God, and they set down the ark of God: & Abiathar ascended, till all the people was fully passed, which was come forth of the city.\n"
	"And the king said to Sadoc: Carry back the Ark of God into the city: if I shall find grace in the sight of my Lord, he will bring me again, and will shew me it, and his tabernacle.\n"
	"But if he shall say to me: Thou pleasest me not: I am ready, let him do that which is good before him.\n"
	"And the king said to Sadoc the Priest: O seer return into the city in peace: and Achimaas thy son, and Jonathas the son of Abiathar, your two sons let them be with you.\n"
	"Behold I will be hid in the champion of the desert, till there come word from you advertising me.\n"
	"Sadoc therefore and Abiathar carried back the Ark of God into Jerusalem: and they tarried there.\n"
	"Moreover David went up mount Olivet, climbing & weeping, going bare foot, & his head covered, yea & all the people which was with him, there head covered went up weeping.\n"
	"And it was told David that Achitophel also was in the conspiracy with Absalom, & David said: Infatuate, O Lord I beseech thee, the counsel of Achitophel.\n"
	"And when David went up to the top of the mount, wherein he would adore our Lord, behold there met him Chusai the Arachite, his garment rent & his head full of earth.\n"
	"And David said to him: If thou come with me, thou shalt be a burden to me:\n"
	"but if thou return into the city, and wilt say to Absalom: I am thy servant, o king: as I have been thy father's servant, so I will be thy servant: thou shalt defeat the counsel of Achitophel.\n"
	"And thou hast with thee Sadoc and Abiathar the Priests, and every word whatsoever thou shalt hear from out of the king's house, thou shalt tell Sadoc and Abiathar the Priests.\n"
	"And there are with them their two sons Achimaas the son of Sadoc, and Jonathas the son of Abiathar: and you shall send by them unto me every word whatsoever you shall hear.\n"
	"Chusai therefore the friend of David coming into the city, Absalom also entered into Jerusalem.";