const char* chap283 = "And when David had passed a little the top of the Mount, Siba the servant of Miphiboseth appeared coming to meet him, with two asses, which were loaden with two hundred loaves, and an hundred bunches of raisins, an hundred masses of figs, & a bottle of wine.\n"
	"And the king said to Siba: What mean these things? And Siba answered: The asses are for the king's household to sit on: and the loaves and the figs to eat for thy servants, and the wine to drink if any man shall faint in the desert.\n"
	"And the king said: Where is thy master's son? And Siba answered the king: He hath remained in Jerusalem, saying: This day will the house of Israel restore me the kingdom of my father:\n"
	"And the king said to Siba: Let all things be thine that were Miphiboseth's. And Siba said: I beseech thee let me find grace before thee, my lord king.\n"
	"King David therefore came as far as Bahurim: & behold there came forth thence a man of the kindred of the house of Saul named Semei, the son of Gera, & he proceeded going forth, & cursed.\n"
	"And he threw stones against David, & against all the servants of king David: & the whole people & all the warriors went on the right, & the left side of the king.\n"
	"And thus spake Semei when he cursed the king: Come forth, come forth thou man of blood, & man of Belial.\n"
	"Our Lord hath repayed thee all the blood of the house of Saul: because thou hast invaded the Kingdom for him, and our Lord hath given the Kingdom into the hand of Absalom thy son: and behold thine evils press thee, because thou art a man of blood.\n"
	"And Abisai the son of Sarvia said to the king: Why curseth this dead dog my lord thy king? I will go, and strike off his head.\n"
	"And the king said: What is it to me and you, ye sons of Sarvia? Let him alone that he may curse: for our Lord hath commanded him to curse David: and who is he that dare say, why hath he so done?\n"
	"And the king said to Abisai, and to all his servants: Behold my son, that came out of my womb, seeketh my life: how much more the son of Jemini? Let him alone that he may curse according to the precept of our Lord:\n"
	"if perhaps our Lord may respect mine affliction, and our Lord may render me good for this day's cursing.\n"
	"David therefore walked and his company in the way with him. And Semei by the bank on the hill's side, went over-against him, cursing, and casting stones against him, and sprinkling earth.\n"
	"The king therefore came, and all the people with him weary, and they were refreshed there.\n"
	"But Absalom and all his people entered into Jerusalem, yea and Achitophel with him.\n"
	"And when Chusai the Arachite David's friend was come to Absalom, he said to him: God save thee, o king, God save thee, o king.\n"
	"To whom Absalom, is this, quoth he, thy kindness toward thy friend? Why wentest thou not with thy friend?\n"
	"And Chusai answered Absalom: Not so: because I will be his, whom our Lord hath chosen, and all this people, and all Israel, and with him will tarry.\n"
	"Yea that I may add this also, whom shall I serve? Not the king's son? As I have served thy father, so will I serve thee also.\n"
	"And Absalom said to Achitophel: Consult what we ought to do.\n"
	"And Achitophel said to Absalom: Go into the concubines of thy father, which he hath left to keep the house: that when all Israel shall hear that thou hast defiled thy father, their hands may be strengthened with thee.\n"
	"They pitched therefore a tent for Absalom in the house top, and he went in to his father's concubines before all Israel.\n"
	"And the counsel of Achitophel, which he gave in those days, as if a man should consult God: so was all the counsel of Achitophel, both when he was with David, and when he was with Absalom.";