const char* chap284 = "Achitophel therefore said to Absalom: I will choose me twelve thousand men; & rising I will pursue David this night.\n"
	"And falling upon him (for as much as he is weary, & of weakened hands) I will strike him: and when all the people is fled, that is with him, I shall strike the king being desolate.\n"
	"And I shall reduce all the people, as one man is wont to return: for thou seekest one man: & all the people shall be in peace.\n"
	"And his saying pleased Absalom, & all the ancients of Israel.\n"
	"But Absalom said: Call Chusai the Arachite, & let us hear what he also saith.\n"
	"And when Chusai was come to Absalom, Absalom said to him: This manner of speech spake Achitophel; shall we do it or not? What counsel givest thou?\n"
	"And Chusai said to Absalom: It is not good counsel, that Achitophel hath given this time.\n"
	"And again Chusai inferred: Thou knowest thy father, and the men that are with him, to be very valiant, and of fell courage, as if a bear in the wood her whelps being taken away should rage: yea and thy father is a man of war, neither will he abide with the people.\n"
	"Perhaps he lieth now hid secretly in caves, or in some one place where he list: and when any one shall fall in the beginning, there shall one hear whosoever shall hear it, and say: There is made a slaughter in the people that followed Absalom.\n"
	"And every one of the most valiant whose heart is as it were a lion's, shall faint for fear: for all the people of Israel know thy father to be a valiant man, and that all be strong which are with him.\n"
	"But this seemeth unto me to be good counsel: Let all Israel be gathered to thee, from Dan to Bersabee, as the sand of the sea innumerable: and thou shalt be in the midst of them.\n"
	"And we shall set upon them in what place soever they shall be found: and we shall cover them, as dew is wont to fall upon the earth: and we shall not leave of the men, that are with him, not so much as one.\n"
	"And if he shall enter into any city, all Israel shall cast ropes upon that city round about, and we will draw it into the torrent, that there be not found thereof not so much as a little stone.\n"
	"And Absalom said, and all the children of Israel: The council of Chusai the Arachite is better than the counsel of Achitophel: and by the will of our Lord was the profitable counsel of Achitophel defeated, that our Lord might bring in evil upon Absalom.\n"
	"And Chusai said to Sadoc and Abiathar the Priests: In this and this manner gave Achitophel counsel to Absalom, and to the Ancients of Israel: and I gave such and such counsel.\n"
	"Now therefore send quickly, and tell David, saying: Tarry not this night in the champion of the desert, but without delay pass over: lest perhaps the king be swallowed up, and all the people that is with him.\n"
	"And Jonathas and Achimaas stood by the Fountain Rogel: there went a maid and told them: and they went forward, to report the message to king David: for they could not be seen, nor enter into the city.\n"
	"And a certain boy saw them, and told Absalom: but they making haste entered into the house of a certain man in Bahurim, who had a well in his court, and they went down into it.\n"
	"And a woman took and spread a covering over the mouth of the well, as it were drying sod barley: and so the thing was not known.\n"
	"And when Absalom's servants were come into the house, they said to the woman: Where is Achimaas, and Jonathas? And the woman answered them: They passed in haste, having tasted a little water. But they that sought, when they had not found, returned into Jerusalem.\n"
	"And when these were gone, they went up out of the well, and going on told king David, and said: Arise ye, and pass quickly the river: because this manner of counsel hath Achitophel given against you.\n"
	"David therefore arose, and all the people that was with him, and they passed over Jordan, until it waxed light, and not one at all was remaining, which did not pass the river.\n"
	"Moreover Achitophel seeing that his counsel was not executed, saddled his ass, and rose and went into his house, and into his city: and taking order with his house, hanged himself, and was buried in the sepulchre of his father.\n"
	"But David came into the Camp, and Absalom passed over Jordan, he and all the men of Israel with him.\n"
	"But Absalom appointed Amasa for Joab over the army: and Amasa was the son of a man, which was called Jethra of Jezrael, who went in to Abigail the daughter of Naas, the sister of Sarvia which was the mother of Joab.\n"
	"And Israel camped with Absalom in the Land of Galaad.\n"
	"And when David was come into the Camp, Sobi the son of Naas of Rabbath the sons of Ammon, and Machir the Son of Ammiel of Lodabar, and Berzellai the Galaadite of Rogelim,\n"
	"presented unto him, hangings, and tapestry, and earthen vessels, wheat, and barley, and meal, and polent, and beans, and rice, and fried peas,\n"
	"and honey, and butter, sheep, and fat calves, and they gave to David & the people that was with him, to eat: for they suspected that the people with hunger and thirst was faint in the desert.";