const char* chap299 = "Then were gathered together all the ancients of Israel with the princes of the tribes, and the heads of the families of the children of Israel to king Salomon into Jerusalem: that they might carry the Ark of the covenant of our Lord out of the city of David, that is, out of Sion.\n"
	"And all Israel assembled to king Salomon in the month of Ethanim, on a solemn day, that is the seventh month.\n"
	"And all the ancients of Israel came, and the Priests took the ark,\n"
	"and carried the ark of our Lord, and the tabernacle of covenant, and all the vessels of the Sanctuary, that were in the tabernacle: and the Priests and the Levites carried them.\n"
	"And King Salomon, and all the multitude of Israel which was assembled unto him, went with him before the ark, and they immolated sheep and oxen without estimation and number.\n"
	"And the priests brought in the ark of the covenant of our Lord into his place, into the oracle of the temple, into Sanctum Sanctorum under the wings of the Cherubs.\n"
	"For the Cherubs spread their wings over the place of the ark, and covered the ark, and the bars thereof above.\n"
	"And whereas the bars stood out, and the ends of them appeared without in the Sanctuary before the oracle, they appeared no farther outward, which also were there until this present day.\n"
	"And in the ark there was nothing else but two tables of stone, which Moyses put in it in Horeb, when our Lord made the covenant with the children of Israel, when they came out of the Land of Aegypt.\n"
	"And it came to pass, when the Priests were gone out of the Sanctuary, a cloud filled the house of our Lord,\n"
	"and the Priests could not stand and minister for the cloud: for the glory of our Lord had filled the house of our Lord.\n"
	"Then said Salomon: Our Lord said that he would dwell in a cloud.\n"
	"Building I have built a house for thy habitation, thy most firm throne for ever.\n"
	"And the king turned his face, and blessed all the Church of Israel: for all the Church of Israel stood.\n"
	"And Salomon said: Bless be our Lord the God of Israel, who spake by his mouth to David my father, & in his own hands hath perfected it, saying:\n"
	"Since the day that I brought my people Israel out of Aegypt, I chose no city of all the tribes of Israel, that a house might be built, and my name might be there: but I chose David to be over my people Israel.\n"
	"And David my father would have built a house to the name of our Lord the God of Israel:\n"
	"and our Lord said to David my father: In that thou hast thought in thy heart to build a house to my name, thou hast done well, casting this same thing in thy mind.\n"
	"Nevertheless thou shalt not build me a house, but thy son, that shall come forth of thy reins, he shall build a house to my name.\n"
	"Our Lord hath confirmed his word, which he spake: & I stand for David my father, & sit upon the throne of Israel, as our Lord hath spoken: and I have built a house to the name of our Lord the God of Israel.\n"
	"And I have appointed there a place for the ark, wherein the covenant of our Lord is, which he made with our fathers, when they came out of the Land of Aegypt.\n"
	"And Salomon stood before the altar of our Lord in the sight of the assembly of Israel, and extended his hands toward heaven,\n"
	"and said: Lord God of Israel, there is no God like to thee in heaven above, and upon the earth beneath: which keepest covenant and mercy with thy servants, that walk before thee in all their heart.\n"
	"Which hast kept to thy servant David my father, the things that thou hast spoken to him: by mouth thou didst speak, and with thy hands thou hast accomplished, as this day proveth.\n"
	"Now therefore Lord God of Israel, keep unto thy servant David my father the things which thou hast spoken to him, saying: There shall not be taken away of thee a man before me, which sitteth upon the throne of Israel: yet so if thy children shall keep their way, that they walk before me as thou hast walked in my sight.\n"
	"And now Lord God of Israel, let thy words be established, which thou hast spoken to thy servant David my father.\n"
	"Is it then to be thought that indeed God dwelleth upon the earth? For if heaven, and the heavens of heavens cannot contain thee, how much more this house, which I have built?\n"
	"But look toward the prayer of thy servant, & to his petitions, o Lord my God: hear the hymn and the prayer, which thy servant prayeth before thee this day:\n"
	"that thy eyes be opened upon this house night and day: upon the house, whereof thou saidst: My name shall be there: that thou hear the prayer, which thy servant prayeth in this place to thee.\n"
	"That thou hear the request of thy servant & of thy people Israel, whatsoever they shall pray for in this place, & thou shalt hear in the place of thy habitation in heaven: and when thou hast heard, thou shalt be merciful,\n"
	"If a man shall sin against his neighbour, & shall have any oath, wherewith he is held fast bound: & shall come because of the oath before thine altar into thy house,\n"
	"thou shalt hear in heaven: and shalt do, and judge thy servants, condemning the impious, and rendering his way upon his head, and justifying the just, and rewarding him according to his justice.\n"
	"If thy people Israel shall fly their enemies (because they will sin against thee) & doing penance and confessing to thy name, shall come, and pray, & beseech thee in this house;\n"
	"hear in heaven, & forgive the sin of thy people Israel, and thou shalt reduce them unto the land, which thou gavest to their fathers.\n"
	"If the heaven shall be shut, and it rain not, because of their sins, and praying in this place, they do penance to thy name, and shall be converted from their sins through their affliction:\n"
	"hear them in heaven, and forgive the sins of thy servants, and of thy people Israel: and shew them a good way wherein they may walk, and give rain upon thy land, which thou has given to thy people in possession.\n"
	"If famine arise in the land, or pestilence, or corrupt air, or blasting, or locust, or rust, and their enemy afflict them besieging the gates, all plague, all infirmity,\n"
	"all cursing, and banning, that shall chance to any man of thy people Israel: if any man shall know the wound of his heart, and shall spread forth his hands in this house,\n"
	"thou shalt hear in heaven, in the place of thy habitation, and shalt be merciful again, and shalt so do that thou give to every one according to his ways, as thou shalt see his heart (for thou only knowest the heart of all the children of men)\n"
	"that they fear thee all the days, which they live upon the face of the land, which thou hast given our fathers.\n"
	"Moreover also the stranger, which is not of thy people Israel, when he shall come from a far country for thy name (for thy great name shall be heard of, and thy strong hand,\n"
	"and thy stretched out arm every-where) when therefore he shall come, and shall pray in this place,\n"
	"thou shalt hear in heaven, in the firmament of thy habitation, & thou shalt do all things, for the which the stranger shall invocate thee: that all the peoples of the earth may learn to fear thy name, as thy people Israel, and may prove that thy name is invocated upon this house, which I have built.\n"
	"If thy people shall go forth to war against their enemies, by the way, whithersoever thou shalt send them, they shall pray to thee against the way of the city, which thou hast chosen, and against the house, which I have built to thy name,\n"
	"and thou shall hear in heaven their prayers, and their petitions, and shall do judgment for them.\n"
	"But if they shall sin to thee (for there is no man which sinneth not) and thou being wrath shalt deliver them to their enemies, and they shall be led captive into the land of their enemies far or near,\n"
	"and shall do penance in their heart in the place of captivity, and converted shall beseech thee in their captivity, saying: We have sinned, we have done wickedly, we have dealt impiously:\n"
	"and shall return to thee in all their heart, and all their soul, in the land of their enemies, to the which they shall be led captive: and shall pray to thee against the way of their land, which thou gavest to their fathers, & of the city which thou hast chosen, & of the temple which I have built to thy name:\n"
	"thou shalt hear in heaven, in the firmament of thy throne their prayers, and their petitions, and shall do their judgment for them:\n"
	"and shalt be merciful to thy people, which sinned to thee, and to all their iniquities wherewith they have transgressed against thee: & thou shalt give mercy before them that shall have them captives, that they may have compassion on them.\n"
	"For they are thy people, and thine inheritance, whom thou hast brought out of the Land of Aegypt, from the midst of the iron furnace.\n"
	"That thy eyes be open to the petition of thy servant, & of thy people Israel, and thou hear them in all things for which they shall invocate thee.\n"
	"For thou hast separated them to thee for an inheritance from all the peoples of the earth, as thou hast spoken by Moyses thy servant, when thou didst bring our fathers out of Aegypt, Lord God.\n"
	"And it came to pass, when Salomon had accomplished praying to our Lord all this prayer and petition, he rose from the sight of the altar of our Lord: for he had fastened both knees on the ground, and had spread his hands toward heaven.\n"
	"He stood therefore and blessed all the assembly of Israel with a loud voice, saying:\n"
	"Blessed be our Lord, which hath given rest to his people Israel, according to all things that he hath spoken: there hath not failed so much as one word of all the good things, that he spake by Moyses his servant.\n"
	"Be our Lord God with us, as he hath been with our fathers, not forsaking, nor rejecting us.\n"
	"But incline he our hearts to him, that we may walk in all his ways, and keep his commandments, and his ceremonies, and judgments whatsoever he commanded our fathers.\n"
	"And be these my words, wherewith I have prayed before our Lord, approaching to our Lord God day and night, that he may do judgment for his servant, and for his people Israel day by day:\n"
	"that all the people of the earth may know, that our Lord he is God, and there is none other besides him.\n"
	"Let our heart also be perfect with our Lord God, that we walk in his decrees, and keep his commandments, as also this day.\n"
	"Therefore the king, and all Israel with him, did immolate victims before our Lord.\n"
	"And Salomon killed pacific hosts, which he immolated to our Lord, of oxen two and twenty thousand, and of sheep an hundred twenty thousand: and they dedicated the temple of our Lord, the king, and the children of Israel.\n"
	"In that day the king sanctified the midst of the court, that was before the house of our Lord: for he made the holocaust there, and sacrifice, and fat of the pacifics: because the brazen altar, that was before our Lord, was too little, and could not take the holocaust, and sacrifice, and fat of the pacifics.\n"
	"Salomon therefore made in the time a solemn festivity, and all Israel with him, a great multitude from the entrance of Emath unto the River of Aegypt, before our Lord God, seven days and seven days, that is, fourteen days.\n"
	"And in the eighth day he dismissed the people: Who blessing the king, went into their tabernacles rejoicing, and with a joyful heart for all the good things, that our Lord had done to David his servant, and to Israel his people.";