const char* chap310 = "And Achab told Jezabel all things that Elias had done, and how he had killed all the prophets with the sword.\n"
	"And Jezabel sent a message to Elias, saying: These things do the gods to me, and these add they, if this hour tomorrow I make not thy soul as the soul of one of them.\n"
	"Elias therefore was afraid, and rising he went whither soever his will carried him: and he came into Bersabee of Juda, and left his servant there,\n"
	"and went forward into the desert, one day's journey. And when he was come, and sat under a juniper tree, he desired for his soul to die, and said: It sufficeth me Lord, take my soul: for I am not better than my fathers.\n"
	"And he cast himself down, & slept in the shadow of the juniper tree: & behold an Angel of our Lord touched him, and said to him: Arise, and eat.\n"
	"He looked, and behold at his head hearth-baked bread, and a vessel of water: he therefore did eat, & drink, & he slept again.\n"
	"And the Angel of our lord returned the second time, & touched him, & said to him: Arise, eat: for thou hast yet a great way to go.\n"
	"Who when he was risen, did eat & drink, and walked in the strength of that meat forty days, & forty nights, unto the mount of God, Horeb.\n"
	"And when he was come thither, he tarried in a cave, and behold the word of our Lord unto him, and he said to him: What doest thou here Elias?\n"
	"But he answered: With zeal have I been zealous for our Lord the God of hosts, because the children of Israel have forsaken thy covenant: thy altars have they destroyed, and thy Prophets they have slain with the sword, and I alone am left, and they seek my life to take it away.\n"
	"And he said to him: Come forth, and stand in the mount before our Lord: and behold our Lord passeth, and a great wind and strong, overthrowing mountains and breaking rocks before our Lord: not in the wind is our Lord, and after the wind an earth quake: not in the earth quake is our Lord,\n"
	"and after the earth quake fire: not in the fire is our Lord, & after the fire a whistling of a gentle wind.\n"
	"Which when Elias had heard, he covered his face with his mantle, and coming forth stood in the door of the cave, and behold a voice unto him, saying: What doest thou here Elias?\n"
	"And he answered: With zeal have I been zealous for our Lord the God of hosts: because the children of Israel have forsaken thy covenant: thine altars they have destroyed, and thy Prophets they have slain with the sword, and I alone am left, and they seek my life to take it away.\n"
	"And our Lord said to him: Go, and return into thy way by the desert of Damascus: and when thou art come thither thou shalt anoint Hazael king over Syria,\n"
	"and Jehu the son of Namsi thou shalt anoint king over Israel: and Eliseus the son of Saphat, which is of Abelmeula, thou shalt anoint prophet for thee.\n"
	"And it shall be, whosoever shall escape the sword of Hazael, him Jehu shall kill: and whosoever shall escape the sword of Jehu, him shall Eliseus kill.\n"
	"And I will leave me in Israel seven thousand men, whose knees have not been bowed before Baal, and every mouth, that hath not adored him kissing his hands.\n"
	"Elias therefore departing thence, found Eliseus the son of Saphat, ploughing with twelve yoke of oxen, and he was one of them that ploughed with twelve yoke of oxen: and when Elias came to him, he cast his mantle upon him.\n"
	"Who forthwith leaving the oxen ran after Elias, and said: Let me kiss, I pray thee, my father, and my mother, and so I will follow thee. And he said to him: Go, and return: for that which was my part, I have done to thee.\n"
	"And returning from him, he took a yoke of oxen, and killed them, and sod the flesh with the plough of the oxen, and gave to the people, and they did eat: and rising up he departed, and followed Elias, and ministered to him.";