const char* chap314 = "And Moab moved war against Israel, after that Achab was dead.\n"
	"And Ochozias fell through the stanchions of his upper chamber which he had in Samaria, and was sick: and he sent messengers, saying to them: Go, consult Beelzebub the god of Accaron, whether I may live of this my infirmity.\n"
	"And an Angel of our Lord spake to Elias the Thesbite, saying: Arise, and go up to meet the messengers of the king of Samaria, and thou shalt say to them: What^ is there not a God in Israel, that ye go to consult Beelzebub the god of Accaron?\n"
	"Wherefore thus saith our Lord: From the bed on which thou art ascended, thou shalt not go down, but dying thou shalt die. And Elias went away.\n"
	"And the messengers returned to Ochozias. Who said to them: Why are you returned?\n"
	"But they answered him: A man met us, and said to us: Go, and return to the king that sent you, and you shall say to him: Thus saith our Lord: Dost thou therefore send to consult Beelzebub the god of Accaron, because there was no God in Israel? Therefore from the bed, which thou art upon, thou shalt not go down, but dying thou shalt die.\n"
	"Who said to them: What shape and habit had that man, which met you, and spake these words?\n"
	"But they said: A hairy man, and girded about his reins with a girdle of leather: Who said: It is Elias the Thesbite.\n"
	"And he sent unto him a captain of fifty men, and the fifty that were under him. Who went up and said to him sitting in the top of the mount: Man of God; the king hath commanded that thou come down.\n"
	"And Elias answering, said to the captain of fifty men: If I be a man of God, let fire come down from heaven, and devour thee, and thy fifty. Fire therefore came down from heaven, and devoured him and the fifty men that were with him.\n"
	"And he sent again unto him another captain of fifty men, and his fifty with him. Who spake to him: Man of God, thus saith the king: Make haste, come down.\n"
	"Elias answering said: If I be a man of God, let fire come down from heaven, and devour thee, and thy fifty. Fire therefore came down from heaven, & devoured him, & his fifty.\n"
	"Again he sent a third captain of fifty men, and the fifty that were with him. Who when he was come, bowed his knees toward Elias, and prayed him and said: Man of God despise not my life and the lives of thy servants that are with me.\n"
	"Behold fire came down from heaven, and hath devoured the two first captains of fifty men, and the fifties, that were with them: but now I beseech thee that thou have mercy on my life.\n"
	"And an Angel of our Lord spake to Elias, saying: Go down with him, fear not. He therefore arose, and went down with him to the king,\n"
	"and spake to him: Thus saith our Lord: Because thou hast sent messengers to consult Beelzebub the god of Accaron, as though there were not a God in Israel, of whom thou mightest ask the word, therefore from the bed which thou art ascended upon, thou shalt not descend, but dying thou shalt die.\n"
	"He died therefore according to the word of our Lord which Elias spake, and Joram his brother reigned for him, in the second year of Joram the son of Josaphat the king of Juda: for he had no son.\n"
	"But the rest of the words of Ochozias, which he wrought, are not these written in the Book of the words of the days of the kings of Israel?";