const char* chap321 = "And Eliseus spake to the woman, whose son he restored to life, saying: Arise, go thou and thy house, and sojourn wheresoever thou shalt find: for our Lord hath called a famine, and it shall come upon the land seven years.\n"
	"Who arose, and did according to the word of the man of God: and going with her household, she sojourned in the land of the Philisthiims many days.\n"
	"And when the seven years were ended, the woman returned out of the Land of the Philisthiims: and she went forth to speak to the king for her house, and for her lands.\n"
	"And the king spake with Giezi the servant of the man of God, saying: Tell me all the marvelous things that Eliseus hath done.\n"
	"And when he had told the king how he had raised a dead man, the woman appeared, whose son he had revived, crying to the king for her house and her lands. And Giezi said: My lord king, this is the woman, and this is her son, whom Eliseus raised.\n"
	"And the king asked the woman: who told him. And the king gave her an eunuch, saying: Restore her all things that are hers, and all the revenues of the lands, from the day that she left the land until this present.\n"
	"Eliseus also came to Damascus, & Benadad the king of Syria was sick: & they told him, saying: The man of God cometh hither.\n"
	"And the king said to Hazael: Take with thee presents, & go to meet the man of God, & consult the Lord by him, saying: Can I escape of this mine infirmity?\n"
	"Hazael therefore went to meet him, having with him presents, & all good things of Damascus, the loads of forty camels. And when he stood before him, he said: Thy son Benadad the king of Syria hath sent me to thee, saying: Can I recover of this mine infirmity?\n"
	"And Eliseus said to him: Go, tell him: Thou shalt be healed: but our Lord hath shewed me that dying he shall die.\n"
	"And he stood with him, and was troubled so far that he blushed: and the man of God wept.\n"
	"To whom Hazael said: Why doeth my lord weep? But he said: Because I know what evils thou wilt do to the children of Israel. Their fenced cities thou wilt burn with fire, and their young men thou wilt kill with the sword, & their little ones thou wilt dash in pieces, and women with child thou wilt divide.\n"
	"And Hazael said: What am I thy servant a dog, that I should do this great thing? And Eliseus said: Our Lord hath shewed me that thou shalt be king of Syria.\n"
	"Who when he was departed from Eliseus, came to his master, who said to him: What said Eliseus to thee? But he answered: He told me: Thou shalt recover health.\n"
	"And when the next day was come, he took a coverlet, and poured water thereon, and spread it upon his face: who being dead, Hazael reigned for him.\n"
	"In the fifth year of Joram the son of Achab the king of Israel, and of Josaphat the king of Juda, reigned Joram the son of Josaphat the king of Juda.\n"
	"He was two and thirty years old when he began to reign, and he reigned eight years in Jerusalem.\n"
	"And he walked in the ways of the kings of Israel, as the house of Achab had walked: for the daughter of Achab was his wife: and he did that which is evil in the sight of our Lord.\n"
	"But our Lord would not destroy Juda, for David his servant, as he had promised him, to give him a lamp to him, & to his children always.\n"
	"In his days revolted Edom, from being under Juda, and made to it-self a king.\n"
	"And Joram came to Seira, and all the chariots with him: and he arose in the night, and struck the Idumeans, that had beset him, and the captains of the chariots, and the people fled into their tabernacles.\n"
	"Edom therefore revolted from being under Juda, until this day. Then Lobna also revolted at that time.\n"
	"But the rest of the words of Joram, and all that he did, are not these things written in the Book of the words of the kings of Juda?\n"
	"And Joram slept with his fathers, and was buried with them in the city of David, and Ochozias his son reigned for him.\n"
	"In the twelfth year of Joram the son of Achab the king of Israel, reigned Ochozias the son of Joram the king of Juda.\n"
	"Two and twenty years old was Ochozias when he began to reign, and he reigned one year in Jerusalem: the name of his mother was Athalia the daughter of Amri the king of Israel.\n"
	"And he walked in the ways of the house of Achab: & he did that which is evil before our Lord, as the house of Achab: for he was the son in law of the house of Achab.\n"
	"He went also with Joram the son of Achab, to fight against Hazael the king of Syria in Ramoth Galaad, and the Syrians wounded Joram.\n"
	"Who returned to be cured in Jezrahel: because the Syrians wounded him in Ramoth fighting against Hazael the king of Syria. Moreover Ochozias the son of Joram the king of Juda went down to visit Joram the son of Achab into Jezrael, because he was sick there.";