const char* chap329 = "In the seventeenth year of Phacee the son of Romelia reigned Achaz the son of Joatham king of Juda.\n"
	"Twenty years old was Achaz when he began to reign, and he reigned sixteen years in Jerusalem: he did not that which was pleasing in the sight of our Lord his God, as David his father.\n"
	"But he walked in the way of the kings of Israel: moreover also he consecrated his son, making him pass through fire according to the idols of the Gentiles: which our Lord destroyed before the children of Israel.\n"
	"He immolated also victims, and burnt incense in the excelses, and on the hills, and under every tree full of green leaves.\n"
	"Then went up Rasin the king of Syria, & Phacee the son of Romelia the king of Israel into Jerusalem to fight: and when they besieged Achaz, they were not able to overcome him.\n"
	"At that time Rasin the king of Syria restored Aila to Syria, and threw out the Jews out of Aila: and the Idumeians came into Aila, and dwelt there unto this day.\n"
	"And Achaz sent messengers to Theglathphalasar the king of the Assyrians, saying: I am thy servant, and thy son: come up, and save me out of the hand of the king of Syria, and from the hand of the king of Israel, which are risen together against me.\n"
	"And when he had gathered together the silver and gold, that could be found in the house of our Lord, & in the king's treasures, he sent gifts to the king of the Assyrians.\n"
	"Who also agreed to his will: for the king of the Assyrians went up into Damascus, and wasted it: and he transferred the inhabitants thereof to Cyrene, but Rasin he slew.\n"
	"And king Achaz went forth to meet Theglathphalasar the king of the Assyrians into Damascus, and when he had seen the altar of Damascus, king Achaz sent to Urias the Priest a pattern of it, and a similitude according to all the work thereof,\n"
	"And Urias the Priest built an altar, according to all things, which king Achaz had commanded, from Damascus, so did the Priest Urias, whilst king Achaz came from Damascus.\n"
	"And when the king was come from Damascus, he saw the altar and worshipped it: and went up and immolated holocausts, and his sacrifice,\n"
	"& offered libaments, & poured the blood of the pacifics, which he had offered upon the altar.\n"
	"Moreover the altar of brass that was before our Lord, he removed from the face of the temple, and from the place of the altar, and from the place of the temple of our Lord: and he set it at the side of the altar toward the North.\n"
	"King Achaz also commanded Urias the Priest, saying: Upon the greater altar offer the morning holocaust, and the evening sacrifice, and the king's holocaust, and his sacrifice, and the holocaust of the whole people of the land, and their sacrifices, and their libaments: and all the blood of the holocaust, and all the blood of the victim thou shalt pour out upon it: but the altar of brass shall be prepared ready at my pleasure.\n"
	"Urias therefore the Priest did according to all things, which king Achaz had commanded him.\n"
	"And king Achaz took the engraven feet, and the lavatory that was upon them: and he took down the sea from the oxen of brass, that held it up, and put it upon the pavement paved with stone.\n"
	"The Musach also of the Sabbath, which he had built in the temple: and the entry of the king outward he turned into the temple of our Lord, because of the king of the Assyrians.\n"
	"But the rest of the words of Achaz, which he did, are not these written in the Book of the words of the days of the kings of Juda?\n"
	"And Achaz slept with his fathers, and was buried with them in the city of David, and Ezechias his son reigned for him.";