const char* chap343 = "Also the sons of Ruben the first-begotten of Israel (for he was his first-begotten: but when he had violated his father's bed, his first-birth-right was given to the sons of Joseph the son of Israel, and he was not reputed for the first-begotten.\n"
	"Moreover Judas, which was the strongest among his brethren, of his stock sprang the Princes: but the first-birth-right was reputed to Joseph.)\n"
	"The sons then of Ruben the first-begotten of Israel: Enoch, and Phallu, Esron, and Charmi.\n"
	"The sons of Joel: Samia his son, Gog his son, Semei his son.\n"
	"Micha his son, Reia his son, Baal his son,\n"
	"Beera his son, whom Theglathphalnasar the king of the Assyrians led away captive, and he was Prince in the tribe of Ruben.\n"
	"And his brethren, and all his kindred, when they were numbered by their families, had these Princes Jehiel, and Zacharias.\n"
	"Moreover Bala the son of Azaz, the son of Samma, the son of Joel, he dwelt in Aroer as far as Nebo, and Beelmeon.\n"
	"Against the east quarter also he dwelt unto the entrance of the desert, and the river Euphrates. For they possessed a great number of cattle in the land of Galaad.\n"
	"And in the days of Saul they fought against the Agarenes, and slew them, and dwelt for them in their tabernacles, in all the quarter, that looketh to the East of Galaad.\n"
	"But the children of Gad dwelt over-against them in the land of Basan, as far as Selcha:\n"
	"Johel the head, and Sapham the second: and Janai, & Saphat in Basan.\n"
	"And their brethren according to the houses of their kindreds, Michael, and Mosollam, and Sebe, and Jorai, and Jacan, and Zie, & Heber, seven.\n"
	"These are the sons of Abihail, the son of Huri, the son of Jara, the son of Galaad, the son of Michael, the son of Jesesi, the son of Jeddo, the son of Buz.\n"
	"Also the brethren of the son of Abdiel, the son of Guni, prince of the house in their families.\n"
	"And they dwelt in Galaad, and in Basan, and in the towns thereof, and in all the suburbs of Saron, unto the borders.\n"
	"All these were numbered in the days of Joathan the king of Juda, and in the days of Jeroboam the king of Israel.\n"
	"The children of Ruben, and of Gad, and the half tribe of Manasses, men of war, carrying shields, and swords, and bending the bow, and taught to battles, four and forty thousand and seven hundred threescore going forth to fight.\n"
	"They fought against the Agarenes, but the Itureians, and Naphis, and Nodab\n"
	"gave them aid. And the Agarenes were delivered into their hands, and all that were with them, because they called upon God when they fought: and he heard them, because they believed in him.\n"
	"And they took all that they possessed, Camels fifty thousand, and sheep two hundred fifty thousand, and asses two thousand, and of men an hundred thousand souls.\n"
	"And many fell down wounded: for it was the battle of our Lord. And they dwelt for them until the transmigration.\n"
	"Also the children of the half tribe of Manasses possessed the land, from the coasts of Basan unto Baal, Hermon, and Sanir, & mount Hermon, for the number was great.\n"
	"And these were the Princes of the house of their kindred, Epher, & Jesi, and Eliel, & Esriel, and Jeremia, and Odoia, and Jediel, most valiant men and mighty, & renowned Princes in their families.\n"
	"But they forsook the God of their fathers, and fornicated after the gods of the peoples of the land, whom God took away before them.\n"
	"And the God of Israel raised up the spirit of Phul king of the Assyrians, and the spirit of Thelgathphalnasar king of Assur: and he transported Ruben, and Gad, and the half tribe of Manasses, and brought them into Lahela, and into Habor, and to Ara, and to the river of Gozan, until this day.";