const char* chap346 = "And Benjamin begat Bale his first begotten, Asbel the second, Ahara the third,\n"
	"Nohaa the fourth, and Rapha the fifth.\n"
	"And the sons of Bale were: Addar, and Gera, and Abiud,\n"
	"Abisue also, and Naaman, and Ahoe,\n"
	"and also Gera, and Sephuphan, and Huram.\n"
	"These are the sons of Ahod, Princes of their kindreds that dwelt in Gabaa, which were transported into Manahath.\n"
	"And Naaman, and Achia, and Gera he transported them, and begat Oza, and Ahiud.\n"
	"Moreover he begat Saharaim in the country of Moab, after he dismissed Husim and Bara his wives.\n"
	"And of Hodes his wife he begat Jobab, and Sebia, and Mosa, and Molchom,\n"
	"Jehus also, and Sechia, and Marma. These are his sons^ Princes in their families.\n"
	"And Mehusim begat Abitob, and Elphaal.\n"
	"Moreover the sons of Elphaal^ Heber, and Misaam, and Samad: this man built Ono, and Lod, and her daughters.\n"
	"And Baria, and Sama^ Princes of their kindreds that dwelt in Aialon: these drove away the inhabitants of Geth.\n"
	"And Ahio, & Sesac, and Jerimoth,\n"
	"and Sabadia, and Arod, and Heder,\n"
	"Michael also, and Jespha, & Joha the sons of Baria.\n"
	"And Zabadia, and Mosollam, and Hezeci, and Heber,\n"
	"and Jesamari, and Jezlia, and Jobab sons of Elphaal,\n"
	"and Jacim, and Zechri, and Zabdi\n"
	"and Elioenai, and Selethai, and Eliel,\n"
	"and Adaia, and Baraia, and Samarath the sons of Semei.\n"
	"And Jespham, and Heber, and Eliel.\n"
	"and Abdon, and Zechri, and Hanan,\n"
	"and Hanania, and Aelam, and Anathothia,\n"
	"and Jephdaia, and Phanuel the sons of Sesac.\n"
	"and Samsari, and Sohoria and Otholia.\n"
	"and Jersia, and Elia, and Zechri, the sons of Jeroham.\n"
	"these be the Patriarchs, and Princes of their kindreds, which dwelt in Jerusalem.\n"
	"And in Gabaon dwelt Abigabaon, and the name of his wife Maacha:\n"
	"And his first-begotten son Abdon, and Sur, and Cis, and Baal, and Nadab.\n"
	"Gedor also, and Ahio, and Zacher, and Macelloth:\n"
	"and Macelloth begat Samaa: and they dwelt over against their brethren in Jerusalem with their brethren.\n"
	"And Ner begat Cis, and Cis begat Saul. Moreover Saul begat Jonathas, and Melchisua, and Abinadab, and Esbaal.\n"
	"And the son of Jonathas, Meribbaal: and Meribbaal begat Micha.\n"
	"The sons of Micha, Phithon, and Melech, and Tharaa, and Ahaz.\n"
	"And Ahaz begat Joada and Joada begat Alamath, and Azmoth, and Zamri: moreover Zamri begat Mosa,\n"
	"and Mosa begat Banaa, whose son was Rapha, of whom was born Elasa, who begat Asel.\n"
	"Moreover Asel had six sons of these names, Ezricam, Bochru, Ismahel, Saria, Obdia, and Hanan. All these the sons of Asel.\n"
	"And the sons of Esec his brother, Ulam the first-begotten, and Jehus the second, and Eliphalet the third.\n"
	"And the sons of Ulam were most strong men, and archers of great force: and having many sons and nephews, unto an hundred fifty. All these the children of Benjamin.";