const char* chap397 = "Ezechias also sent to all Israel and Juda: and he wrote letters to Ephraim & Manasses, that they should come to the house of our Lord in Jerusalem, and should make a Phase to our Lord the God of Israel.\n"
	"Counsel therefore being taken of the king and the Princes, and of all the assembly of Jerusalem, they decreed to make the Phase the second month.\n"
	"For they could not make it in his time, because the Priests that might suffice, had not been sanctified, and the people had not as yet been gathered into Jerusalem.\n"
	"And the word pleased the king, and all the multitude.\n"
	"And they decreed to send messengers into all Israel from Bersabee unto Dan, that they should come, and make the Phase to our Lord the God of Israel in Jerusalem: for many had not made it as is prescribed by the law.\n"
	"And the posts went forth with letters of commandment from the king and his Princes, into all Israel and Juda, according to the which the king had commanded, proclaiming: Children of Israel return ye to our Lord the God of Abraham, and Isaac, and Israel: and he will return to the remnant, that hath escaped the hand of the king of the Assyrians.\n"
	"Become not as your fathers, and brethren, which have revolted from our Lord the God of their fathers, who hath delivered them into destruction, as yourselves see.\n"
	"Harden not your necks, as your fathers: give hands to our Lord, and come to his Sanctuary, which he hath sanctified for ever: serve our Lord the God of your fathers, & the wrath of his fury shall be turned away from you.\n"
	"For if you shall return to our Lord, your brethren, and children shall have mercy before their lords, that have led them captive, and they shall return into this land. For our Lord your God is merciful, and will not turn away his face from you, if you shall return to him.\n"
	"Therefore the posts went forward speedily from city to city, through the land of Ephraim, & of Manasses, as far as Zabulon, they mocking and scorning them.\n"
	"Nevertheless certain men of Aser, and Manasses, and Zabulon, condescending to the counsel, came to Jerusalem.\n"
	"But the hand of God was in Juda, to give them one heart to do the word of our Lord, according to the precept of the king and of the Princes\n"
	"And much people was gathered into Jerusalem to make the solemnity of Azymes in the second month:\n"
	"And rising they destroyed the altars that were in Jerusalem, and overthrowing all things wherein incense was burnt to idols, they threw it into the Torrent cedron.\n"
	"And they immolated the Phase the fourteenth day of the second month. The Priests also and the Levites at length being sanctified offered holocausts in the house of our Lord.\n"
	"And they stood in their order according to the disposition and Law of Moyses the man of God: but the Priests received the blood to be poured out of the hands of the Levites,\n"
	"because a great multitude was not sanctified: and therefore the Levites immolated the Phase for them that came not in time to be sanctified to our Lord.\n"
	"For a great part of the people of Ephraim, and Manasses, and Issachar, and Zabulon, that had not been sanctified, did eat the Phase, not according to that which is written: and Ezechias prayed for them, saying: Our good Lord will be merciful\n"
	"to all them that in all their heart seek our Lord the God of their fathers: & will not impute it to them that they are not sanctified.\n"
	"Whom our Lord heard, and was pacified to the people.\n"
	"And the children of Israel, that were found in Jerusalem, made the solemnity of Azymes seven days in great joy, praying our Lord every day. The Levites also and the Priests by instruments, that agreed to their office.\n"
	"And Ezechias spake to the heart of all the Levites, that had good understanding concerning our Lord: & they did eat during the seven days of the solemnity, immolating victims of pacifics, and praising our Lord the God of their fathers.\n"
	"And it pleased the whole multitude to celebrate it other seven days. Which also they did with great joy.\n"
	"For Ezechias the king of Juda had given the multitude a thousand oxen, and seven thousand sheep: but the Princes had given the people oxen a thousand, and sheep ten thousand: there was sanctified therefore a very great multitude of Priests.\n"
	"And all the multitude of Juda was full of mirth, as well of the Priests and Levites, as of all the assembly, that came out of Israel, of the proselytes also of the land of Israel, and them that dwelt in Juda.\n"
	"And there was made a great solemnity in Jerusalem, such as had not been in that city from the days of Salomon the son of David the king of Israel.\n"
	"And the Priests and the Levites rose up blessing the people: and their voice was heard: and their prayer came into the holy habitation of heaven.";