const char* chap41 = "After two years Pharao saw a dream. He thought he stood upon a river,\n"
	"out of the which came up seven kine, fair and fat exceedingly: and they fed in marish places.\n"
	"Other seven also came up out of the river, foul, and carrion lean: and they fed on the very bank of the river, in green places:\n"
	"and they devoured them that had the marvelous beauty and good state of bodies. Pharao after he waked,\n"
	"slept again, and saw another dream: Seven ears of corn grew forth upon one stalk full and fair:\n"
	"there sprang also other ears as many, thin and blasted with adustion,\n"
	"devouring all the beauty of the former. Pharao awaking up after his rest,\n"
	"and when morning was come being frighted with fear, he sent to all the interpreters of Aegypt, and to all the wise men: and they being called for, told them his dream, neither was there any that could interpret it.\n"
	"Then at length the master of the cup-bearers remembering himself, said: I confess my sin:\n"
	"The king being angry with his servants, commanded me and the chief of the bakers to be cast into the prison of the Captain of the soldiers:\n"
	"where in one night both of us saw a dream portending things to come.\n"
	"There was there a young man an Hebrew, servant to the same Captain of the soldiers, to whom telling our dreams,\n"
	"we heard whatsoever afterward the event of the thing proved to be so. For I was restored to my office, and he was hanged upon a gibbet.\n"
	"Forthwith at the king's commandment, Joseph being brought out of the prison they polled him: and changing his apparel, brought him unto him.\n"
	"To whom he said: I have seen dreams, and there is not any that can expound them; which I have heard, thou dost most wisely interpret.\n"
	"Joseph answered: Without me, God shall answer prosperous things to Pharao.\n"
	"Pharao therefore told that he had see: Me thought I stood upon the bank of the river,\n"
	"and seven kine came up out of the bank of the river, exceeding fair, and full of flesh: which grazed on green places in a marish pasture.\n"
	"And behold there followed these other seven kine, so passing ill favoured and lean, that I never saw the like in the land of Aegypt;\n"
	"which having devoured and consumed the former,\n"
	"gave no token of their fullness: but with the like leanness & deformity looked heavily. Awaking, and fallen again into a deep sleep,\n"
	"I saw a dream: Seven ears of corn grew forth upon one stalk, full and very fair.\n"
	"Other seven also thin and blasted with adustion, sprang of the stalk,\n"
	"which devoured the beauty of the former: I told the dream to the conjecturers, and there is no man that can declare it.\n"
	"Joseph answered: The king's dream is one: God hath shewed to Pharao the things that he will do.\n"
	"The seven fair kine, and the seven full ears, be seven years of plentifulness and both contain the self-same meaning of the dream.\n"
	"Also the seven lean and thin kine, that came up after them, and the seven thin ears, and blasted with the burning wind, are seven years of famine to come.\n"
	"Which shall be fulfilled in this order.\n"
	"Behold there shall come seven years of great fertility in the whole Land of Aegypt:\n"
	"after which shall follow other seven years of so great sterility, that all the abundance before shall be forgotten: for the famine shall consume all the land,\n"
	"and the greatness of the scarcity shall destroy the greatness of the plenty.\n"
	"And in that thou didst see the second time a dream pertaining to the same thing, it is a token of the certainty for that the word of God shall come to pass, and be fulfilled speedily.\n"
	"Now therefore let the king provide a wise man and industrious, & make him Ruler over the Land of Aegypt:\n"
	"that he may appoint overseers over all countries: and gather into barns the fifth part of the fruits, during the seven years of the fertility,\n"
	"that now presently shall ensue: and let all the corn be laid up under Pharao's hands, and let it be reserved in the cities.\n"
	"And let it be in a readiness against the famine of seven years to come, which shall oppress Aegypt, and the land shall not be consumed with scarcity.\n"
	"The counsel pleased Pharao, and all his servants:\n"
	"and he spake to them: Can we find such another man, that is full of the spirit of God?\n"
	"He said therefore to Joseph: Because God hath shewed thee all things that thou hast spoken, can I find a wiser and one like unto thee?\n"
	"Thou shalt be over my house, & at the commandment of thy mouth all the people shall obey: only in the throne of the Kingdom I will go before thee.\n"
	"And again Pharao said to Joseph: Behold, I have appointed thee over the whole land of Aegypt.\n"
	"And he took his ring from his own hand, and gave it into his hand: and he put upon him a silk robe, and put a chain of gold about his neck.\n"
	"And he made him go up into his second chariot, the crier proclaiming that all should bow their knee before him, and that they should know he was made Governor over the whole Land of Aegypt.\n"
	"And the king said to Joseph: I am Pharao: without thy commandment no man shall move hand or foot in all the land of Aegypt.\n"
	"And he turned his name, & called him in the Aegyptian tongue the Saviour of the world. And he gave him to wife Aseneth the daughter of Putiphar Priest of Heliopolis. Joseph therefore went forth to the land of Aegypt\n"
	"(and he was thirty years old when he stood in the sight of king Pharao) and did circuit all the countries of Aegypt.\n"
	"And the fertility of the seven years came: and the corn being bound up into sheaves was gathered into the barns of Aegypt.\n"
	"All the abundance also of grain was laid up in every city.\n"
	"And there was so great abundance of wheat, that it became equal to the sand of the sea, and the plenty exceeded measure.\n"
	"And there were born unto Joseph two sons before the famine came: whom Aseneth the daughter of Putiphar Priest of Heliopolis bare him.\n"
	"And he called the name of the first-begotten Manasses, saying: God made me to forget all my labours, and my father's house.\n"
	"The name also of the second he called Ephraim, saying: God hath made me to increase in the land of my poverty.\n"
	"Therefore when the seven years of the plentifulness, that had been in Aegypt were passed:\n"
	"the seven years of scarcity began to come, which Joseph foretold: and in the whole world the famine prevailed, but in all the land of Aegypt there was bread.\n"
	"The which being in hunger, the people cried to Pharao, desiring food. To whom he answered: Go ye to Joseph: & whatsoever he shall say to you, that do ye.\n"
	"And the famine daily increased in all the land: and Joseph opened all the barns, and sold to the Aegyptians: for them also the famine had oppressed.\n"
	"And all Provinces came into Aegypt, to buy victuals, and to moderate the misery of the scarcity.";