const char* chap417 = "And it came to pass, when Sanaballat had heard that we builded the wall, he was very angry: and being moved exceedingly he scorned the Jews,\n"
	"and said before his brethren, and the multitude of the Samaritans: What do the silly Jews? Will the gentiles let them alone? Shall they sacrifice and accomplish in one day? Why, are they able to build up the stones out of the heaps of dust, that are burnt?\n"
	"Yea Tobias also the Ammanite his neighbour said: Let them build: if a fox come up, he shall leap over their stone wall.\n"
	"Hear our God, because we are had in despise: turn the reproach upon their head, and give them into despise in a Land of captivity.\n"
	"Cover not their iniquity, and let not their sin be put out before thy face, because they have mocked thy builders.\n"
	"Therefore we built the wall, and joined together the whole unto the half part: and the heart of the people was provoked to work.\n"
	"And it came to pass when Sanaballat had heard, and Tobias, and the Arabians, and the Ammanites, and the Azotians, that the breach of the wall of Jerusalem was closed up, and the gates began to be stopped, they were wrath exceedingly.\n"
	"And they were all assembled together to come, and to fight against Jerusalem, and to prepare ambushments.\n"
	"And we prayed our God, and set watchmen upon the wall day and night against them.\n"
	"And Judas said: The strength of him that carrieth is weakened, and the mortar is very much, and we shall not be able to build the wall.\n"
	"And our enemies said: Let them not know, and let them be ignorant, till we come into the midst of them, and kill them, and make their work to cease.\n"
	"And it came to pass, the Jews that dwelt beside them, coming and telling us ten times, out of all places from whence they came to us,\n"
	"I set the people in a place behind the wall round about in order, with their swords, and spears, and bows.\n"
	"And I looked and rose up: and I said to the Princes and magistrates, and to the rest of the common people: Be not afraid at their face: Remember our Lord great and terrible, and fight for your brethren, your sons, and your daughters, and your wives, and your houses.\n"
	"And it came to pass, when our enemies had heard that it was told us, God defeated their counsel. And we returned all to the walls, every man to his work.\n"
	"And it came to pass from that day, the half part of their young men did the work, and half was ready to battle, and spears, and shields, and bows, and coats of mail, and the Princes behind them in all the house of Juda\n"
	"of them that built in the wall, and that carried burdens, and that laded them: with one of his hands he did the work, and with the other he held a sword:\n"
	"for every one of the builders was girded with a sword about his reins. And they builded, and sounded with the trumpet near me.\n"
	"And I said to the Princes, & to the magistrates, & to the rest of the common people: The work is great and broad, and we are separated in the wall one far from another:\n"
	"in what place soever you shall hear the sound of the trumpet, thither run together unto us: our God will fight for us.\n"
	"And let us ourselves do the work: and let the half part of us hold spears from the rising of the morning, till the stars appear.\n"
	"At that time also I said to the people: Let every man with his servant tarry in the midst of Jerusalem, and let there be courses among us by day and night to work.\n"
	"And I and my brethren, & my servants, and the watchmen that were behind me, did not put off our cloths: every man was made bare only to washing.";