const char* chap42 = "And Jacob hearing that victuals were sold in Aegypt, he said to his sons: Why neglect ye?\n"
	"I have heard that wheat is sold in Aegypt: Go ye down and buy us necessaries, that we may live and not be consumed with lack.\n"
	"Therefore the ten brethren of Joseph going down to buy corn in Aegypt,\n"
	"Benjamin being kept at home by Jacob, who said to his brethren: Lest perhaps he take any harm in the journey:\n"
	"entered into the land of Aegypt with others that went to buy. For the famine was in the land of Chanaan.\n"
	"And Joseph was Prince in the land of Aegypt, and at his pleasure corn was sold to the people. And when his brethren had adored him,\n"
	"and he knew them, he spake as it were to strangers somewhat roughly, asking them: From whence came you? Who answered: From the Land of Chanaan, that we may buy necessaries to live.\n"
	"And yet himself knowing his brethren, was not known of them.\n"
	"And remembering the dreams, which sometimes he had seen, he said to them: You are spies: to view the weaker parts of the land you are come.\n"
	"Who said: It is not so, my Lord, but thy servants are come to buy victuals.\n"
	"We are all the sons of one man: we are come as men of peace, neither do thy servants go about any evil.\n"
	"To whom he answered: It is otherwise: you came to consider the undefensed parts of this land.\n"
	"But they: We thy servants, say they, are twelve brethren, the sons of one man in the Land of Chanaan: the youngest is with our father, the other is not living.\n"
	"This is it, quoth he, that I said: You are spies.\n"
	"Now presently I will take a trial of you: by the health of Pharao you shall not depart hence, until your youngest brother do come,\n"
	"Send you one of you to bring him: and you shall be in prison till the things be proved which you have said, whether they be true or false: otherwise by the health of Pharao you are spies.\n"
	"Therefore he put them in prison three days.\n"
	"And the third day bringing them out of prison, he said: Do as I have said, and you shall live: for I fear God.\n"
	"If you be men of peace, let one of your brethren be bound in prison: and go ye your ways, and carry the corn that you have bought unto your houses,\n"
	"and bring your youngest brother to me, that I may prove your sayings to be true, and that you die not. They did as he had said,\n"
	"and they talked one to another: Worthily do we suffer these things, because we have sinned against our brother, seeing the distress of his soul whilst he besought us, and we heard not: therefore is this tribulation come upon us.\n"
	"Among whom Ruben one of them, said: Why, did not I say to you: Sin not against the boy; and you heard me not? Lo his blood is required.\n"
	"And they knew not that Joseph understood: because he spake to them by an interpreter.\n"
	"And he turned away himself a little while, and wept: and returning he spake to them.\n"
	"And taking Simeon, and binding him in their presence, he commanded his servants that they should fill up their sacks with wheat, and put every man's money again in their bags, giving them besides for to eat on the way: who did so.\n"
	"But they carrying their corn upon their asses, took their journey.\n"
	"And one of them opening his sack to give his beast provender in the Inn, beholding the money in the sack's mouth,\n"
	"he said to his brethren: My money is given me again, behold it is in the sack. And being astonished and troubled amongst themselves, they said: What is this, that God hath done unto us?\n"
	"And they came to Jacob their father into the land of Chanaan, & they told him all things that had chanced unto them, saying:\n"
	"The lord of the land spake to us roughly, & thought us to be spies of the province,\n"
	"to whom we answered: We are men of peace, neither do we attempt any treachery.\n"
	"We are twelve brethren born of one father: one is not living, the youngest is with our father in the Land of Chanaan.\n"
	"Who said to us: Thus shall I try that you be men of peace: Leave one of your brethren with me, and take ye provision necessary for your houses, and go your ways,\n"
	"and bring your youngest brother to me, that I may know you are not spies: and you may receive this fellow again, that is kept in prison: and afterwards may have license to buy what things you will.\n"
	"This being said when they poured out their corn, every man found his money tied in the mouth of the sacks: and all being astonished together,\n"
	"their father Jacob said: You have made me to be without children, Joseph is not living, Simeon is kept in bonds, and Benjamin you will take away: all these evils, are fallen upon me.\n"
	"To whom Ruben answered: Kill my two sons, if I bring him not again to thee: deliver him into my hand, and I will restore him unto thee.\n"
	"But he said: My son shall not go down with you: his brother is dead, and he alone is remaining: if any adversity shall chance to him in the land to the which you go, you shall bring down my hoar hairs with sorrow unto hell.";