const char* chap420 = "And after the wall was built, and I had put on the doors, and numbered the porters, and singing men, and Levites:\n"
	"I commanded Hanani my brother, and Hananias Prince of the house of Jerusalem (for he seemed as it were a true man, & one that feared God above the rest)\n"
	"and I said to them: Let not the gates of Jerusalem be opened until the heat of the sun. And when they yet stood by, the gates were shut, and barred: and I set watchmen of the inhabitants of Jerusalem, every one by their courses, and every man against his house.\n"
	"And the city was exceeding large and great, and the people few in the midst thereof, and there were no houses built.\n"
	"But God gave me in my heart, and I assembled the Princes and magistrates, and common people, that I might number them: and I found a Book of the number of them that came up first, and there was found written in it:\n"
	"These are the children of the province, which came up from the captivity of them that were transported, whom Nabuchodonosor the king of Babylon had transported, and returned into Jury, every one into his own city.\n"
	"They that came with Zorobabel, Josue, Nehemias, Azarias, Rahamias, Nahamani, Mardochaeus, Belsam, Mespharath, Begoai, Nahum, Baana. The number of the men of the people of Israel.\n"
	"The children of Pharos, two thousand an hundred seventy two.\n"
	"The children of Saphatia, three hundred seventy two.\n"
	"The children of Area, six hundred fifty two.\n"
	"The children of Phahathmoab of the children of Josue and Joab, two thousand eight hundred eighteen.\n"
	"The children of Aelam, a thousand two hundred fifty four.\n"
	"The children of Zethua, eight hundred forty five.\n"
	"The children of Zachai, seven hundred sixty.\n"
	"The children of Bannui, six hundred forty eight.\n"
	"The children of Bebai, six hundred twenty eight.\n"
	"The children of Azgad, two thousand three hundred twenty two.\n"
	"The children of Adonicam, six hundred sixty seven.\n"
	"The children of Beguai, two thousand sixty seven.\n"
	"The children of Adin, six hundred fifty five.\n"
	"The children of Ater, children of Hezecias, ninety eight.\n"
	"The children of Hasem, three hundred twenty eight.\n"
	"The children of Besai, three hundred twenty four.\n"
	"The children of Hareph, an hundred twelve.\n"
	"The children of Gabaon, ninety five.\n"
	"The children of Bethlehem, and Netupha, an hundred eighty eight.\n"
	"The men of Anathoth, an hundred twenty eight.\n"
	"The men of Bethazmoth, forty two.\n"
	"The men of Cariathiarim, Cephira, and Beroth, seven hundred forty three.\n"
	"The men of Rama and Geba, six hundred twenty one.\n"
	"The men of Machmas, an hundred twenty two.\n"
	"The men of Bethel and Hai, an hundred twenty three.\n"
	"The men of another Nebo, fifty two.\n"
	"The men of another Aelam, a thousand two hundred fifty four.\n"
	"The children of Harem, three hundred twenty.\n"
	"The children of Jericho, three hundred forty five.\n"
	"The children of Lod Hadid and Ono, seven hundred twenty one.\n"
	"The children of Senaa, three thousand nine hundred thirty.\n"
	"The Priests: The children of Idaia in the house of Josue, nine hundred seventy three.\n"
	"The children of Emmer, a thousand fifty two.\n"
	"The children of Phashur, a thousand two hundred forty seven.\n"
	"The children of Arem, a thousand seventeen. The Levites:\n"
	"The children of Josue and Cedmihel, the children\n"
	"of Oduia, seventy four: The singing men:\n"
	"the children of Asaph, an hundred forty eight.\n"
	"The porters: The children of Sellum, the children of Ater, the children of Telmon, the children of Accub, the children of Hatita, the children of Sobai: an hundred thirty eight.\n"
	"The Nathineites: The children of Soha, the children of Hasupha, the children of Tebbaath,\n"
	"the children of Ceros, the children of Siaa, the children of Phadon, the children of Lebana, the children of Hagaba, the children of Selmai,\n"
	"the children of Hanan, the children of Geddel, the children of Gaher,\n"
	"the children of Raaia, the children of Rasin, the children of Necoda,\n"
	"the children of Gesem, the children of Aza, the children of Phasea,\n"
	"the children of Besai, the children of Munim, the children of Nephussim,\n"
	"the children of Bacbuc, the children of Hacupha, the children of Harhur,\n"
	"the children of Besloth, the children of Mahida, the children of Harsa,\n"
	"the children of Bercos, the children of Sisara, the children of Thema,\n"
	"the children of Nasia, the children of Hatipha,\n"
	"the children of the servants of Salomon, the children of Sotai, the children of Sophereth, the children of Pharida,\n"
	"the children of Iahala, the children of Darcon, the children of Ieddel,\n"
	"the children of Saphatia, the children of Hatil, the children of Phochereth, who was born unto Sabaim, the son of Amon.\n"
	"All Nathineites, and the children of the servants of Salomon, three hundred ninety two.\n"
	"But these be they which came up from Thelmela, Thelharsa, Cherub, Addon, and Emmer: and could not shew the house of their fathers, and their seed, whether they were of Israel.\n"
	"The children of Dalaia, the children of Tobia, the children of Necoda, six hundred forty two.\n"
	"And of the Priests, the children of Habia, the children of Accos, the children of Berzellai, who took a wife of the daughters of Berzellai a Galaadite, and he was called by their name.\n"
	"These sought their writing in the register, & found it not: & they were cast out of the Priesthood.\n"
	"And Athersatha said to them, that they should not eat of the Holies of holies, until there stood up a Priest learned and cunning.\n"
	"All the multitude as it were one man^ forty two thousand three hundred sixty,\n"
	"beside their men-servants and women-servants, which were seven thousand three hundred thirty seven: and among them singing men, and singing women, two hundred forty five.\n"
	"Their horses, seven hundred thirty six, their mules two hundred forty five,\n"
	"their camels, four hundred thirty five, asses six thousand seven hundred twenty.\n"
	"And certain of the Princes of families gave unto the work. Athersatha gave into the treasure of gold a thousand drachmas, phials fifty, tunics for Priests five hundred thirty.\n"
	"And of the Princes of families there gave into the treasure of the work of gold, twenty thousand drachmas, and of silver two thousand two hundred pound.\n"
	"And that which the rest of the people gave, of gold twenty thousand drachmas, and of silver two thousand pound, and tunics for Priests sixty seven.\n"
	"And the Priests, and Levites, and porters, and singing men, and the rest of the common people, and the Nathineites, and all Israel dwelt in their cities. And the seventh month was come: and the children of Israel were in their cities.";