const char* chap43 = "In the mean time the famine did oppress all the land very sore.\n"
	"And the provision being spent, which they had brought out of Aegypt, Jacob said to his sons: Go again, and buy us a little victual.\n"
	"Judas answered: That Same man denounced unto us under attestation of an oath, saying: You shall not see my face, unless you bring your youngest brother with you.\n"
	"If therefore thou wilt send him with us, we will go forward together, and will buy necessaries for thee:\n"
	"but if thou wilt not, we will not go: for the man, as we have often said, denounced unto us saying: You shall not see my face without your youngest brother.\n"
	"Israel said to them: You have done this to my misery, in that you told him that you had another brother also.\n"
	"But they answered: The man asked us in order our progeny: if our father lived; if we had a brother: and we answered him consequently to that which he demanded: could we know that he would say: Bring hither your brother with you?\n"
	"Judas also said to his father: Send the boy with me, that we may set forward, and may live: lest we and our little ones die.\n"
	"I take upon me the boy: require him of my hand, unless I bring him again, and restore him to thee, I will be guilty of sin against thee for ever.\n"
	"If delay had not been made, we had been come now the second time.\n"
	"Therefore Israel their father said to them: If it must needs be so, do that you will: take of the best fruits of the land in your vessels, and carry to the man for presents, a courtesy of rosen, & of honey, & of incense, of myrrh, of terebinth, and of almonds.\n"
	"Double money also carry with you: and recarry that you found in your sacks, lest perhaps it was done by an error:\n"
	"but take also your brother, and go to the man.\n"
	"And my God almighty make him favourable unto you; and send back with you your brother, whom he keepeth, and this Benjamin: as for me I shall be desolate without children.\n"
	"The men therefore took the presents, & the double money, & Benjamin; & went down into Aegypt, & stood before Joseph.\n"
	"Whom when he had seen & Benjamin withal, he commanded the steward of his house, saying: Bring in the men into the house, and kill victims, and prepare a feast; because they shall eat with me at noon.\n"
	"He did that which was commanded him, and brought the men into the house.\n"
	"And there being sore afraid, they said one to another: because of the money which we carried back the first time in our sacks, we are brought in: that he may turn upon us a false accusation, and forcibly bring both us and our asses into bondage.\n"
	"Wherefore in the very door stepping to the steward of the house,\n"
	"They spake: Sir, we desire thee to hear us. Now once before we came down to buy provision:\n"
	"Which being bought, when we were come to the Inn, we opened our sacks, and found our money in the mouths of the sacks: which we have now brought again in the same weight.\n"
	"But we have brought other money besides, to buy the things that are necessary for us: our conscience is not privy, who put it in our bags.\n"
	"But he answered: Peace be with you, fear you not: your God, and the God of your father hath given you treasures in your sacks. For the money, which you gave me, I have for good. And he brought forth Simeon unto them.\n"
	"And being brought into the house, he fetched water, and they washed their feet, and he gave provender to their asses.\n"
	"But they made ready the presents, till Joseph should come in at noon: for they had heard that they should eat bread there.\n"
	"Therefore Joseph came in to his house, and they offered him presents holding them in their hands, and they adored prostrate to the ground.\n"
	"But he courteously resaluting them, asked them saying: Is the old man your father in health, of whom you told me? Is he yet living.\n"
	"Who answered: Thy servant our father is in health, he is yet living. And bowing themselves they adored him.\n"
	"And Joseph lifting up his eyes, saw Benjamin his brother of the same mother, and said: is this your young brother, of whom you told me? And again: God, saith he, be merciful unto thee my son.\n"
	"And he made haste because his heart was moved upon his brother, and tears brake forth: and entering into his chamber he wept.\n"
	"And when he had washed his face, coming forth again, he refrained himself, and said: Set bread on the table.\n"
	"Which being set down, to Joseph apart, and to his brethren apart, to the Aegyptians also that did eat with him apart (for it is unlawful for the Aegyptians to eat with the Hebrews, and they think such a feast profane)\n"
	"they sat before him, the first begotten according to his first-birth, and the youngest according to his age. And they marveled out of measure,\n"
	"Taking the portions that they received of him: and the greater portion came to Benjamin, so that it exceeded by five parts. And they drank and were inebriated with him.";