const char* chap432 = "And Tobias went forward, and a dog followed him, and he made his first abode by the river of Tigris.\n"
	"And he went out to wash his feet, and behold an huge fish came forth to devour him.\n"
	"Of whom Tobias being afraid, cried out with a loud voice, saying: Sir, he invadeth me.\n"
	"And the Angel said to him: Take him by the gill, and draw him to thee. Which when he had done, he drew him on the dry land, and he began to struggle before his feet.\n"
	"Then said the Angel to him: Take out the entrails of this fish, and his heart, and gall, and liver, keep to thee: for these are necessary & profitable for medicines.\n"
	"Which when he had done, he roasted the flesh thereof, and they took it with them in the way: the rest they salted which might suffice them, till they came to Rages the city of Medes.\n"
	"Then Tobias asked the Angel, & said to him: I beseech thee brother Azarias, tell me what remedies shall these things have, which thou hast bid me keep of the fish?\n"
	"And the Angel answering, said to him: If thou put a little piece of his heart upon coals, the smoke thereof driveth out all kind of devils, either from man or from woman, so that it cometh no more unto them.\n"
	"And the gall is available to anoint the eyes, in which there shall be white blemish and they shall be healed.\n"
	"And Tobias said to him: Where wilt thou that we tarry?\n"
	"And the Angel answering, said: Here is one named Raguel, a near kinsman of thy tribe, and he hath a daughter named Sara, and he hath neither man child, nor any woman child beside her.\n"
	"All his substance is due to thee, and thou mayst take her to wife.\n"
	"Ask her therefore of her father, and he will give her thee to wife.\n"
	"Then Tobias answered, and said: I hear that she hath been delivered to seven husbands, and they are dead: yea and I have heard, that a devil killed them.\n"
	"I am afraid therefore, lest these things may happen to me also: & whereas I am the only child of my parents, I may bring down their old age with sorrow unto hell.\n"
	"Then the Angel Raphael said to him: Hear me, and I will shew thee who they are, on whom the devil can prevail.\n"
	"For they that so receive matrimony, that they exclude God from themselves, & from their mind, & so give themselves to their lust, as horse and mule, which have not understanding, over them the devil hath power.\n"
	"But thou when thou shalt take her, entering into the chamber, for three days be continent from her, and thou shalt give thyself to nothing else but to prayers with her.\n"
	"And the same night, the liver of the fish set on the fire, the devil shall be driven away.\n"
	"But the second night thou shalt be admitted in the copulation of the holy Patriarchs.\n"
	"And the third night thou shalt obtain a blessing that sound children may be procreated of you.\n"
	"And when the third night is past, thou shalt take the virgin, with the fear of our Lord, moved rather for love of children than for lust, that in the seed of Abraham thou mayst obtain blessing in children.";