const char* chap453 = "And when it was waxen late, his servants made haste to their lodgings, and Vagao shut the chamber doors, and went his way.\n"
	"And they were all overladen with wine.\n"
	"And Judith was alone in the chamber.\n"
	"Moreover Holofernes lay in his bed, fast asleep with very much drunkenness.\n"
	"And Judith said to her maid that she should stand without^ before the chamber, & watch.\n"
	"And Judith stood before the bed, praying with tears, & with moving of her lips in silence,\n"
	"saying: Confirm me o Lord God of Israel and in this hour have respect to the works of my hands, that as thou hast promised, thou mayst advance Jerusalem thy city: and I may bring to pass that which I believing that it may be done by thee, have purposed.\n"
	"And when she had said these things, she went to the pillar, that was at his bed's head, and his sword that hung tied on it, she loosed.\n"
	"And when she had drawn it out, she took him by the hair of his head, and said: Confirm me, o Lord God, in this hour,\n"
	"and she struck twice upon his neck, and cut off his head, and took his canopy from the pillars, and rolled aside his body a trunk.\n"
	"And after a while she went out, and delivered the head of Holofernes to her maid, and bade her put it into her wallet.\n"
	"And they two went forth, according to their custom, as it were to prayer, and they passed the camp, and compassing the valley, they came to the gate of the city.\n"
	"And Judith a far off said to the keepers of the walls: Open the gates, because God is with us, which hath wrought power in Israel.\n"
	"And it came to pass, when the men had heard her voice, they called the ancients of the city.\n"
	"And they ran all to meet her, from the least to the greatest: because they hoped not that now she would come.\n"
	"And they lighting lights gathered round about her every one: and she going up into a higher place, commanded silence to be made. And when all had held their peace,\n"
	"Judith said: Praise ye the Lord our God, who hath not forsaken them that hope in him:\n"
	"and in me his handmaid he hath fulfilled his mercy, which he promised to the house of Israel: and he hath killed by my hand the enemy of his people this night.\n"
	"And bringing forth the head of Holofernes out of the wallet, she shewed it them, saying: Lo the head of Holofernes the General of the army of the Assyrians, & behold his canopy, wherein he lay in is drunkenness, where the Lord our God struck him by the hand of a woman.\n"
	"But the same our Lord liveth, that his Angel hath kept me, both going hence, and abiding there, and from thence returning hither: and our Lord hath not suffered me his handmaid to be defiled, but without pollution of sin he hath called me back to you, rejoicing in this victory, in my escape, and in your delivery.\n"
	"Confess ye all to him, because he is good, because his mercy is for ever.\n"
	"And they all adoring our Lord, said to her: Our Lord hath blessed thee in his power, because by thee he hath brought our enemies to nothing.\n"
	"Moreover Ozias the Prince of the people of Israel, said to her: Blessed art thou daughter of our Lord the high God, above all women upon the earth.\n"
	"Blessed be our Lord, which made heaven & earth, which hath directed thee unto the wounds of the head of the Prince of our enemies.\n"
	"Because this day he hath so magnified thy name, that thy praise shall not depart out of the mouth of men, which shall be mindful of the power of our Lord for ever, for that thou hast not spared thy life for the distresses and tribulation of thy kindred, but hast holpen the ruin before the presence of our God.\n"
	"And all the people said: So be it, so be it.\n"
	"Moreover Achior being called^ came, and Judith said to him: The God of Israel, to whom thou gavest testimony, that he revengeth himself of his enemies, he hath cut off the head of all the unfaithful this night by my hand.\n"
	"And that thou mayst prove that it is so, lo the head of Holofernes, who in the contempt of his pride contemned the God of Israel: and threatened thee death, saying: When the people of Israel shall be taken, I will command thy sides to be pierced with a sword.\n"
	"But Achior seeing the head of Holofernes, being in anguish for fear, fell on his face upon the earth, and his soul was sore troubled.\n"
	"But after taking spirit again he was refreshed, and fell down at her feet, and adored her, and said:\n"
	"Blessed art thou of thy God in every tabernacle of Jacob, because in every nation, which shall hear thy name, the God of Israel shall be magnified in thee.";