const char* chap465 = "Therefore in the thirteenth day of the twelfth month, which we have said now before to be called Adar, when slaughter was prepared for all the Jews, and their enemies gaped after their blood, the case being changed to the contrary, the Jews began to be superiors, and to revenge themselves of their adversaries.\n"
	"And they were gathered together in every city, and town, & place, to extend their hand against their enemies and their persecutors. And none durst resist, because the fear of their greatness did penetrate all peoples.\n"
	"For both the judges of the Provinces, and captains, and lieutenants, and every dignity that was chief over every place and work, extolled the Jews for fear of Mardocheus:\n"
	"Whom they knew to be Prince of the palace, and to be able to do very much: the fame also of his name increased daily, and flew abroad through all men's mouths.\n"
	"Therefore the Jews struck their enemies with a great slaughter, and slew them, repaying them that which they had prepared to do to them:\n"
	"in so much that in Susan also they killed five hundred men, besides the ten sons of Aman the Agagite the enemy of the Jews: whose names be these:\n"
	"Pharsandatha, and Delphon, and Esphatha,\n"
	"and Phoratha, and Adalia, & Aridatha,\n"
	"and Phermesta, and Arisai, and Aridai, and Iezatha.\n"
	"Whom when they had slain, they would not take preys of their goods.\n"
	"And by and by the number of them that were killed in Susan, was brought to the king.\n"
	"Who said to the queen: In the city of Susan the Jews have killed five hundred men, besides the ten sons of Aman: how great a slaughter thinkest thou do they make in all the Provinces? What askest thou more, and what wilt thou that I command to be done?\n"
	"To whom she answered: If it please the king, let there authority be given to the Jews, that as they have done today in Susan, so also they may do tomorrow, and that the ten sons of Aman be hanged on gibbets.\n"
	"And the king commanded that it should be so done. And forthwith the edict hung in Susan, and the ten sons of Aman were hanged.\n"
	"The fourteenth day of the month Adar, the Jews being gathered together, there were killed in Susan three hundred men: neither was their substance spoiled by them.\n"
	"Yea and through all Provinces, which were subject to the king's dominion, the Jews stood for their lives, their enemies and persecutors being slain: in so much that there was fully seventy five thousand of them that were killed, and no man took any of their goods.\n"
	"And the thirteenth day of the month Adar was the first day with them all^ of the slaughter, & the fourteenth day they ceased to kill. Which they ordained to be solemn, so that in it at all times afterward they gave themselves to good cheer, mirth and banquets.\n"
	"But they that made the slaughter in the city of Susan, were occupied in the slaughter the thirteenth and fourteenth day of the same month: and in the fifteenth day they ceased to kill. And therefore they ordained the same a solemn day of good cheer and joyfulness.\n"
	"But those Jews, that abode in towns not walled and villages, ordained the fourteenth day of the month Adar for banquets and joy, so that they rejoice in it, and send one another portions of banquets and meats.\n"
	"Mardocheus therefore wrote all these things, and being comprised in letters sent them to the Jews, that abode in all the king's Provinces, as well those that lay near, as far off,\n"
	"that they should take the fourteenth and fifteenth day of the month Adar for feasts, and the year always returning should celebrate them with solemn honour:\n"
	"because in the same days the Jews revenged themselves of their enemies, and mourning and sorrow were turned into mirth and joy, and that these should be days of good cheer and gladness, and they should send one to another portions of meats, and should give gifts to the poor.\n"
	"And the Jews received into a solemn rite all things, which they had begun to do at that time, and which Mardocheus by letters had commanded to be done.\n"
	"For Aman, the son of Amadathi of the stock of Agag, the enemy & adversary of the Jews, purposed evil against them, to kill them and destroy them: & he cast Phur, which in our language is turned, a lot.\n"
	"And afterward Esther went in to the king, beseeching that his endeavours might by the king's letters be made void: & the evil that he had intended against the Jews, might return upon his own head. Finally, they hung both him and his sons upon the gallows,\n"
	"and since that time these days are called Phurim, that is, of Lots: because Phur, that is, a lot, was cast into the pot. And all things that were done, are contained in the volume of this epistle, that is, of this Book:\n"
	"and the things that they sustained, and that were afterward changed, the Jews took upon themselves and their seed, & upon all that would be joined to their religion, that it should be lawful for none to pass without solemnity these days: which the writing testifieth, and certain times require; as years continually succeed one another.\n"
	"These are days, which no oblivion shall ever put out: and all Provinces in all the world shall celebrate throughout all generations: neither is there any city, wherein the days of Phurim, that is, of lots, must not be observed of the Jews, and of their progeny, which is bound to these ceremonies.\n"
	"And Esther the queen the daughter of Abihail, & Mardocheus the Jew wrote also the second epistle, that with all diligence this day should be established solemn for the time to come.\n"
	"and they sent to all the Jews, that were in the hundred and seven and twenty Provinces of king Assuerus, that they should have peace, and receive truth,\n"
	"observing the Days of lots, and in their time should celebrate them with joy: as Mardocheus and Esther had appointed, and they took upon them to be observed of themselves, and of their seed, fasts, and cries, and the days of lots,\n"
	"and all things, which are contained in the history of this Book, which is called Esther.";