const char* chap472 = "The great king Artaxerxes, from India to Aethiopia, to the dukes and Princes of an hundred twenty seven Provinces, which obey our commandment, sendeth greeting.\n"
	"Many have abused unto pride the goodness of Princes, and the honour, that hath been bestowed upon them:\n"
	"and they do not only endeavour to oppress the king's subjects, but not bearing the glory that is given them, they work treason against them that gave it.\n"
	"Neither are they content not to give thanks for the benefits, and to violate in themselves the laws of humanity, but they think they can escape the sentence of God also who seeth all things.\n"
	"And they have burst forth into so great madness, that such as observe diligently the offices committed unto them, and do all things so that they are worthy of all men's praise, them they endeavour to overthrow by subtile means of lies,\n"
	"whilst with crafty fraud they deceive the simple ears of Princes, and esteeming others by their own nature.\n"
	"Which thing is proved both out of old histories, and by these things, which are done daily, how the enterprises of kings are depraved by the evil suggestions of certain men.\n"
	"Wherefore we must provide for the peace of all Provinces.\n"
	"Neither must you think, if we command diverse things, that it cometh of the lightness of our mind, but that we give sentence according to the quality and necessity of times, as the profit of the common wealth requireth.\n"
	"And that you may more plainly understand, that which we say, Aman the son of Amadathi, both in mind & country a Macedonian, & an alien from the Persians' blood, and with his cruelty staining our piety, was received of us a stranger:\n"
	"and found our humanity so great towards him, that he was called our father, & was adored of all^ second after the king:\n"
	"who was puft up with so great swelling of arrogancy, that he went about to deprive us of Kingdom and life.\n"
	"For by certain new devices and not heard of before he hath sought to kill Mardocheus, by whose fidelity and benefits we live, and Esther the fellow of our Kingdom with all their nation:\n"
	"thinking this that they being slain, he might work treason to our solitariness, and might transfer the Kingdom of the Persians to the Macedonians.\n"
	"But we have found the Jews, which were by that most wicked of men appointed to be slain, in no fault at all, but contrary wise using just laws,\n"
	"and the children of the highest and the greatest, and always loving God, by whose benefit the Kingdom was given both to our fathers and to us, and is kept unto this day.\n"
	"Wherefore know ye those letters, which he directed in our name, to be of none effect.\n"
	"For the which heinous fact, before the gates of this city, that is of Susan, both himself that devised it, and all his kindred hang on gibbets: not we, but God repaying him that which he hath deserved.\n"
	"But this edict, which we now send, let it be set forth in all cities, that it be lawful for the Jews to use their own laws.\n"
	"Whom you must help, that those which had prepared themselves to their slaughter, they may kill, the thirteenth day of the twelfth month, which is called Adar.\n"
	"For God omnipotent hath turned this day of sadness and mourning into joy to them.\n"
	"Wherefore count you also this day among other festival days, and celebrate it with all joy, that hereafter also it may be known,\n"
	"that all, which faithfully obey the Persians, receive worthy reward for their fidelity: and they that lie in wait against their Kingdom, perish for their wicked fact.\n"
	"And every Province and city, that will not be partaker of this solemnity, let it perish by sword and fire, and let it so be destroyed, that not only men, but also beasts have no access thereto for ever, for an example of contempt, and disobedience.";