const char* chap474 = "And it came to pass when on a certain day the sons of God were come, and stood before our Lord, and Satan came among them, and stood in his sight,\n"
	"that our Lord said to Satan: From whence comest thou? Who answering said: I have gone round about the earth, and walked through it.\n"
	"And our Lord said to Satan: Hast thou considered my servant Job, that there is not the like to him in the earth, a man simple, and right, and fearing God, and departing from evil, and yet retaining innocency? But thou hast moved me against him, that I should afflict him in vain.\n"
	"To whom Satan answering, said: Skin for skin, and all things that a man hath, he will give for his life:\n"
	"otherwise put thy hand, and touch his bone and flesh, and then shalt thou see that he will bless thee in the face.\n"
	"Our Lord therefore said to Satan: Behold he is in thy hand, but yet save his life.\n"
	"Satan therefore going out from the face of our Lord, struck Job with a very sore boil, from the sole of the foot even to the top of his head:\n"
	"who with a shell scraped the corruption, sitting on a dunghill.\n"
	"And his wife said to him: Doest thou yet continue in thy simplicity? Bless God and die.\n"
	"Who said to her: Thou hast spoken like one of the foolish women: if we have received good things of the hand of God, evil things why should we not receive? In all these things Job sinned not with his lips.\n"
	"Therefore Job's three friends hearing all the evil, that had chanced to him, came every one out of their place, Eliphaz a Themanite, and Baldad a Suhite, and Sophar a Naamathite. For they had appointed, that coming together they would visit him, and comfort him.\n"
	"And when they had lifted up their eyes a far off, they knew him not, and crying out they wept, and renting their cloths sprinkled dust over their head toward heaven.\n"
	"And they sat with him on the ground seven days and seven nights, and no man spake to him a word: for they saw the pain to be vehement.";