const char* chap479 = "The life of man upon earth is a warfare, and his days, as the days of an hired man.\n"
	"As a servant desireth the shadow, and as the hired man tarrieth for the end of his work:\n"
	"so I also have had vain months, & have numbered to myself laborious nights.\n"
	"If I sleep, I shall say: When shall I arise? & again I shall expect the evening, & shall be replenished with sorrows even until darkness.\n"
	"My flesh is clothed with rottenness & filth of dust, my skin is withered, & drawn together.\n"
	"My days have passed more swiftly, than the web is cut of the weaver, and are consumed without any hope.\n"
	"Remember that my life is a wind, & mine eye shall not return to see good things.\n"
	"Neither shall the sight of man behold me: thine eyes upon me, and I shall not stand.\n"
	"As a cloud is consumed, and passeth away: so he that shall descend to hell shall not ascend.\n"
	"Neither shall he return any more into his house, neither shall his place know him any more.\n"
	"Wherefore I also will not spare my mouth, I will speak in the tribulation of my spirit: I will talk with the bitterness of my soul.\n"
	"Why, am I a sea, or a whale, that thou hast compassed me with a prison?\n"
	"If I say: My little bed shall comfort me, and I shall be relieved speaking with myself in my couch:\n"
	"Thou wilt terrify me by dreams, and by visions shake me with horror.\n"
	"For the which thing my soul hath chosen hanging, and my bones death.\n"
	"I have despaired. I shall now live no longer: Spare me, for my days are nothing.\n"
	"What is man that thou magnifiest him? Or why settest thou thy heart toward him?\n"
	"Thou doest visit him early, and suddenly thou provest him:\n"
	"How long doest thou not spare me, nor suffer me that I swallow my spittle?\n"
	"I have sinned, what shall I do to thee, o keeper of men? Why hast thou set me contrary to thee, and I am become burdenous to myself?\n"
	"Why doest thou not take away my sin, and why doest thou not take away mine iniquity? Behold now I shall sleep in the dust: and if thou seek me in the morning, I shall not be.";