const char* chap481 = "And Job answering, said:\n"
	"Indeed I know it is so, and that man is not justified compared with God.\n"
	"If he will content with him, he cannot answer him one for a thousand.\n"
	"He is wise of heart, and strong of force: who hath resisted him, and hath had peace?\n"
	"He that transported mountains, and they whom he subverted in his fury, knew not.\n"
	"He that removeth the earth out of her place, and the pillars thereof are shaken.\n"
	"He that commandeth the sun, and it riseth not: and shutteth up the stars as it were under a seal:\n"
	"He that alone spreadeth the heaven, & goeth upon the waves of the sea.\n"
	"He that maketh Arcturus, and Orion, and Hyades, and the inner parts of the south.\n"
	"He that doth great things and incomprehensible, and marvelous, of the which there is no number.\n"
	"If he come to me, I shall not see him: if he depart, I shall not understand.\n"
	"If suddenly he ask, who shall answer him? Or who can say: Why doest thou so?\n"
	"God whose wrath no man can resist, and under whom they stoop that carry the world.\n"
	"How great am I then, that I may answer him, and speak in my words with him?\n"
	"Who although I have any just thing, will not answer, but will beseech my judge.\n"
	"And when he shall hear me invocating, I do not believe that he hath heard my voice.\n"
	"For in a hurlwind shall he break me, and shall multiply my wounds yea without cause.\n"
	"He granteth not my spirit to rest, and he filleth me with bitterness.\n"
	"If strength be demanded, he is most strong: if equity of judgment, no man dare give testimony for me.\n"
	"If I will justify myself, mine own mouth shall condemn me: if I will shew myself innocent, he shall prove me wicked.\n"
	"Although I shall be simple, the self-same shall my soul be ignorant of, and I shall be weary of my life,\n"
	"One thing there is that I have spoken, both the innocent and the impious he consumeth.\n"
	"If he scourge, let him kill at once, and not laugh at the pains of innocents.\n"
	"The earth is given into the hands of the impious, he covereth the face of the judges thereof: and if it be not he, who is it then?\n"
	"My days have been swifter than a post: they have fled and have not seen good.\n"
	"They have passed by as ships carrying fruits, as an eagle flying to meat.\n"
	"When I shall say: I will not speak so, I change my face, & am tormented with sorrow.\n"
	"I feared all my works, knowing that thou didst not spare the offender.\n"
	"But if so also I am impious, why have I laboured in vain?\n"
	"If I be washed as it were with snow-waters, & my hands shall shine as most clean:\n"
	"Yet shall thou dip me in filth, and my garments shall abhor me.\n"
	"For neither I will answer a man that is like myself: nor that may be heard with me equally in judgment.\n"
	"There is none that may be able to reprove both, and to put his hand between both.\n"
	"Let him take his rod from me, and let not his dread terrify me.\n"
	"I will speak, and will not fear him: for I cannot answer fearing.";