const char* chap485 = "Behold mine eye hath seen all these things, and mine ear hath heard, and I have understood every thing.\n"
	"According to your knowledge I also do know: neither am I inferior to you.\n"
	"But yet I will speak to the Omnipotent, and I covet to dispute with God.\n"
	"First shewing you to be forgers of lying, and maintainers of perverse opinions.\n"
	"And would God ye would hold your peace, that you might be thought to be wise men.\n"
	"Hear ye therefore my correptions, and attend the judgment of my lips.\n"
	"Hath God need of your lie, that for him you speak guiles?\n"
	"Do you take his person, and do you endeavour to judge for God?\n"
	"Or shall it please him from whom nothing can be concealed, or shall he be deceived as a man, with your fraudulent dealings?\n"
	"He shall reprove you, because in secret you take his person.\n"
	"Forthwith as he shall move himself, he shall trouble you: and his terror shall come violently upon you.\n"
	"Your memory shall be compared to ashes, and your necks shall be brought into clay.\n"
	"Hold your peace a little while, that I may speak whatsoever my mind shall prompt me.\n"
	"Why do I tear my flesh with my teeth, and carry my soul in my hands?\n"
	"Although he shall kill me, I will trust in him: but yet I will reprove my ways in his sight.\n"
	"And he shall be my saviour: for no hypocrite shall come in his sight.\n"
	"Hear ye my word, and receive the obscure sayings with your ears.\n"
	"If I shall be judged, I know that I shall be found just.\n"
	"What is he that will be judged with me? Let him come: why am I consumed holding my peace?\n"
	"Two things only do not to me, and then shall I not be hid from thy face:\n"
	"Make thy hand far from me, and let not thy fear terrify me.\n"
	"Call me, and I will answer thee: or else I will speak, and do thou answer me.\n"
	"How great iniquities and sins I have, my wicked deeds and my offences shew thou me.\n"
	"Why hidest thou thy face, and thinkest me thine enemy?\n"
	"Against the leaf, that is violently taken with the wind, thou shewest thy might, and persecutest dry stubble.\n"
	"For thou writest bitterness against me, and wilt consume me with the sins of my youth.\n"
	"Thou hast put my feet in the stocks, and hast observed all my paths, and hast considered the steps of my feet.\n"
	"Who as rottenness am to be consumed, and as a garment, that is eaten of the moth.";