const char* chap492 = "But Sophar the Naamathite answering, said:\n"
	"Therefore my diverse cogitations succeed one another, and my mind is rapt into sundry things.\n"
	"The doctrine, wherewith thou reprovest me, I will hear, and the spirit of my understanding shall answer me.\n"
	"This I know from the beginning, since man was placed upon the earth,\n"
	"That the praise of the impious is short, and the joy of the hypocrite as it were for a moment:\n"
	"If his pride rise up even to the heaven, and his head touch the clouds:\n"
	"As a dunghill in the end he shall be destroyed, and they that had seen him, shall say: Where is he?\n"
	"As a dream that flyeth away he shall not be found, he shall pass as a vision by night:\n"
	"The eye that had seen him, shall not see him, neither shall his place behold him any more.\n"
	"His children shall come to naught with poverty, and his hands shall render him his sorrow.\n"
	"His bones shall be filled with the vices of his youth, & they shall sleep with him in the dust.\n"
	"For when evil shall be sweet in his mouth, he will hide it under his tongue.\n"
	"He will spare it, & not leave it, and will hide it in his throat.\n"
	"His bread in his belly shall be turned into the gall of asps within him.\n"
	"The riches which he hath devoured, he shall vomit out, & God shall draw them forth out of his belly.\n"
	"He shall suck the head of asps, and the viper's tongue shall kill him.\n"
	"(Let him not see the streams of the river, the torrents of honey, & of butter.)\n"
	"He shall be punished for all things that he did, & yet not be consumed: according to the multitude of his inventions so also shall he suffer.\n"
	"Because breaking in^ he hath made the poor naked: he hath violently taken a house, & built it not.\n"
	"Neither is his belly filled: and when he shall have the things he coveted, he cannot possess them.\n"
	"There remained not of his meat, & therefore nothing shall continue of his goods:\n"
	"When he shall be filled, he shall be straitened, he shall burn, and all sorrow shall fall upon him.\n"
	"Would God his belly were filled, that he may send forth the wrath of his fury upon him, and rain his battle upon him.\n"
	"He shall fly weapons of iron, and shall fall upon a bow of brass.\n"
	"The sword plucked out, and coming forth of his scabbard, and glistering in his bitterness: the horrible shall go and come upon him.\n"
	"All darkness is hid in his secrets: fire that is not kindled shall devour him, he shall be afflicted left in his tabernacle.\n"
	"The heavens shall reveal his iniquity, and the earth shall rise against him.\n"
	"The blossom of his house shall be opened, he shall be plucked down in the day of God's fury.\n"
	"This is the portion of an impious man from God, & the inheritance of his words from our Lord.";