const char* chap494 = "But Eliphaz the Themanite answering, said:\n"
	"Can man be compared with God, yea though he be of perfect knowledge?\n"
	"What doth it profit God if thou be just? Or what doest thou advantage him if thy way be unspotted?\n"
	"Shall he be afraid to reprove thee, and come with thee into judgment:\n"
	"And not for thy very great malice, and thine infinite iniquities?\n"
	"For thou hast taken away the pledge of thy brethren without cause, and the naked thou hast spoiled of cloths.\n"
	"Water to the weary thou hast not given, and from the hungry thou hast withdrawn bread.\n"
	"In the strength of thine arm thou didst possess the earth, and being the mightiest thou didst obtain it.\n"
	"Widows thou hast sent away empty, and the arms of pupils thou hast broken in pieces.\n"
	"Therefore art thou compassed with snares, and sudden fear troubleth thee.\n"
	"And thoughtest thou that thou shouldest not see darkness, and that thou shouldest not be oppressed with the violence of overflowing waters?\n"
	"Doest thou not think that God is higher than heaven, and is exalted above the top of the stars?\n"
	"And thou sayst: For what knoweth God? And he judgeth as it were by a mist.\n"
	"The clouds are his covert, neither doth he consider our things, and he walketh about the poles of heaven.\n"
	"Doest thou covet to keep the path of worlds, which wicked men have trodden?\n"
	"Who were taken away before their time, and a flood hath overthrown their foundation.\n"
	"Who said to God: Depart from us; and as though the Omnipotent could do nothing, they esteemed him:\n"
	"Whereas he had filled their houses with good things, whose sentence be far from me.\n"
	"The just shall see, & shall rejoice, & the innocent man shall scorn them.\n"
	"Is not their exaltation cut down, and hath not fire devoured the remnants of them?\n"
	"Agree thou therefore to him, and have peace: and by these things thou shalt have the best fruits.\n"
	"Receive the law of his mouth, and put his words in thy heart.\n"
	"If thou wilt return to the Omnipotent, thou shalt be builded up, and shalt make iniquity far from thy tabernacle.\n"
	"He shall give for earth flint, and for flint torrents of gold.\n"
	"And the Omnipotent shall be against thine enemies, and silver shall be heaped together unto thee.\n"
	"Then shalt thou abound in delights upon the Omnipotent, and shalt lift up thy face to God.\n"
	"Thou shalt ask him, and he will hear thee, and thou shalt pay thy vows.\n"
	"Thou shalt decree a thing, and it shall come to thee, and light shall shine in thy ways.\n"
	"For who will be humbled, shall be in glory: & he that will bow down his eyes, he shall be saved.\n"
	"The innocent shall be saved, but shall be saved in the cleanness of his hands.";