const char* chap503 = "I have made a covenant with mine eyes, that I would not so much as think of a virgin.\n"
	"For what part should God from above have in me, and inheritance the Omnipotent from on high?\n"
	"Is there not perdition to the wicked man, and alienation to them that work injustice?\n"
	"Doth not he consider my ways, and number all my steps?\n"
	"If I have walked in vanity, and my foot hath hastened in guile:\n"
	"Let him weigh me in a just balance, and let God know my simplicity.\n"
	"If my step have declined out of the way, and if my heart hath followed mine eyes, and if spot hath cleaved to my hands:\n"
	"Let me sow, and let another eat it: and let my progeny be plucked up by the roots.\n"
	"If my heart hath been deceived upon a woman, and if I have lien in wait at my friend's door:\n"
	"Let my wife be the harlot of another man, and let other men lie with her.\n"
	"For this is a heinous thing, and most great iniquity.\n"
	"It is a fire devouring even to perdition, and rooting up all things that spring.\n"
	"If I have contemned to abide judgment with my man-servant, & my maid-servant, when they had any controversy against me.\n"
	"For what shall I do when God shall rise to judge? And when he shall ask, what shall I answer him?\n"
	"Did not he make me in the womb that made him also: & did not one form me in the matrice?\n"
	"If I have denied to the poor, that which they would, & have made the eyes of the widow to expect:\n"
	"If I have eaten my morsel alone, and the pupil hath not eaten thereof with me.\n"
	"(Because from mine infancy mercy hath grown with me: and from my mother's womb it came forth with me.)\n"
	"If I have despised him that perisheth, for that he had not clothing, and the poor man without wherewithal to cover him:\n"
	"If his sides have not blessed me, and he was not warmed with the fleeces of my sheep:\n"
	"If I have lifted up my hand over the pupil, yea when I saw myself in the gate the superior:\n"
	"Let my shoulder fall from his juncture, and let my arm with his bones be broken.\n"
	"For I have always feared God as waves swelling upon me, & his weight I could not bear.\n"
	"If I have thought gold my strength, and have said to fine gold: My confidence.\n"
	"If I have rejoiced upon my great riches, and because my hand found many things.\n"
	"If I saw the sun when it shined, and the moon going clearly:\n"
	"And my heart in secret rejoiced, and I kissed my hand with my mouth.\n"
	"Which is most great iniquity, and a denial against God the most high?\n"
	"If I have been glad of his fall that hated me, and have rejoiced that evil had found him.\n"
	"For I have not given my throat to sin, that cursing I wished his soul.\n"
	"If the men of my tabernacle have not said: Who will give of his flesh that we may be filled?\n"
	"The stranger tarried not without, my door was open to the wayfaring man.\n"
	"If as man I have hid my sin, and have concealed my iniquity in my bosom.\n"
	"If I have been afraid at a very great multitude, and the contempt of kinsmen hath terrified me: and I have not rather held my peace, & not gone out of the door.\n"
	"Who will grant me an hearer, that the Omnipotent would hear my desire: and that himself that judgeth would write a book.\n"
	"That I may carry it on my shoulder, and put it about me as a crown?\n"
	"At every step of mine I will pronounce it, and as to the Prince I will offer it.\n"
	"If my land cry against me, & with it the furrows thereof lament:\n"
	"If I have eaten the fruits thereof without money, and have afflicted the soul of the tillers thereof.\n"
	"For wheat let the briar grow to me, and for barley the thorn.";