const char* chap506 = "Eliu therefore pronouncing spake these words also:\n"
	"Hear ye wise men my words: and ye learned harken to me:\n"
	"For the ear proveth words, and the throat discerneth meats by the taste.\n"
	"Let us choose us judgment, and among us let us see what is the better.\n"
	"Because Job said: I am just, and God hath subverted my judgment.\n"
	"For in judging me there is a lie: mine arrow is violent without any sin.\n"
	"What man is there as is Job, that drinketh scorning as it were water?\n"
	"What goeth with them that work iniquity, and walketh with impious men?\n"
	"For he hath said: Man shall not please God although he run with him.\n"
	"Therefore ye discreet men hear me, far from God be impiety, and iniquity from the Omnipotent.\n"
	"For he will render a man his work, & according to the ways of every one he will recompense them.\n"
	"For in very deed God will not condemn without cause, neither will the Omnipotent subvert judgment.\n"
	"What other hath he appointed over the earth? or whom hath he set over the world, which he made?\n"
	"If he direct his heart to him, he shall draw his spirit and breath unto him.\n"
	"All flesh shall fail together, and man shall return into ashes.\n"
	"If then thou have understanding, hear that is said, and harken to the voice of my speech.\n"
	"Can he that loveth not judgment, be healed? And how doest thou so far condemn him that is just?\n"
	"That saith to the king, Apostata: that calleth dukes impious:\n"
	"Who accepteth not the persons of Princes: nor hath known the tyrant, when he contended against the poor man: for all are the work of his hands.\n"
	"They shall suddenly die, and at mid-night peoples shall be troubled, & shall pass, & take away the violent without hand.\n"
	"For his eyes are upon the ways of men, and he considereth all their steps.\n"
	"There is not darkness, & there is not shadow of death, that they may be hid there which work iniquity.\n"
	"For it is no more in man's power to come to God into judgment.\n"
	"He shall destroy many, & innumerable, & shall make other to stand for them.\n"
	"For he knoweth their works: and therefore he shall bring night, and they shall be destroyed.\n"
	"As impious men he hath strucken them in the place of them that see.\n"
	"Who as it were of purpose have revolted from him, & would not understand all his ways:\n"
	"That they might cause the cry of the needy man to come to him, & he heard the voice of the poor.\n"
	"For he granting peace, who is there that can condemn? After he shall hide his countenance, who is there that may behold him, both upon nations, and upon all men?\n"
	"Who maketh a man that is an hypocrite reign for the sins of the people.\n"
	"Therefore because I have spoken to God, thee also I will not prohibit.\n"
	"If I have erred, teach thou me: If I have spoken iniquity, I will add no more.\n"
	"Doth God require it of thee, because it hath displeased thee? For thou beganst to speak, and not I: but if thou know any better thing, speak.\n"
	"Let men of understanding speak to me, and let a wiseman hear me.\n"
	"But Job hath spoken foolishly, and his words sound not discipline.\n"
	"O my father, let Job be proved even to the end: cease not from the man of iniquity.\n"
	"Who addeth blasphemy upon his sins, let him be restrained in the mean time among us: and then let him provoke God to judgment with his speeches.";