const char* chap507 = "Therefore Eliu again spake these words:\n"
	"Doth thy cogitation seem just to thee, that thou saidst: I am juster than God?\n"
	"For thou saidst: That which is right doth not please thee: or what will it profit thee if I sin?\n"
	"Therefore will I answer to thy words, and to thy friends with thee.\n"
	"Look up to heaven and see, and behold the sky, that it is higher than thou.\n"
	"If thou sin, what shalt thou hurt him? And if thine iniquities be multiplied, what shall thou do against him?\n"
	"Moreover if thou do justly, what shalt thou give him, or what shall he receive of thy hand?\n"
	"Man that is like to thee, thy impiety shall hurt: and thy justice shall help the son of man.\n"
	"Because of the multitude of calumniators they shall cry: and shall wail for the force of the arm of tyrants.\n"
	"And he hath not said: Where is God, that made me, that hath given songs in the night?\n"
	"Who teacheth us above the beasts of the earth, and instructeth us above the fowls of the air.\n"
	"There shall they cry, and he will not hear, because of the pride of the evil.\n"
	"God therefore will not hear without cause, and the Omnipotent will behold the causes of every one.\n"
	"Yea when thou shalt say: He considereth not: be judged before him, and expect him.\n"
	"For he doth not now infer his fury, neither doth he revenge wickedness exceedingly.\n"
	"Therefore Job in vain openeth his mouth, and without knowledge multiplieth words.";