const char* chap509 = "Upon this my heart is sore afraid, and is moved out of his place.\n"
	"Hear ye his speech in the terror of his voice, and the sound proceeding out of his mouth.\n"
	"Under all the heavens he considereth, and his light is upon the ends of the earth.\n"
	"After him shall sounding roar, he shall thunder with the voice of his greatness, and shall not be found out when his voice shall be heard.\n"
	"God shall thunder in his voice marvelously, he that doeth great & unsearchable things.\n"
	"He that commandeth the snow to descend upon the earth, and the winter rains, and the shower of his strength.\n"
	"He that signeth in the hand of all men, that every one may know his works.\n"
	"The beast shall enter into his covert, and shall abide in his den.\n"
	"From the inner parts shall a tempest come forth, & cold from Arcturus.\n"
	"When God bloweth^ frost congealeth, and again waters are poured most largely.\n"
	"Corn desireth clouds, & the clouds spread their light.\n"
	"Which go round about, whither-soever the will of the governer shall lead them, to all that he shall command them upon the face of the whole earth.\n"
	"Whether in one tribe, or in his land, or in what place soever of his mercy he shall command them to be found.\n"
	"Harken to these things Job: stand, and consider the marvels of God.\n"
	"Doest thou know when God commanded the rains, that they shew the light of his clouds?\n"
	"Knowest thou the great paths of the clouds, and the perfect knowledges?\n"
	"Are not thy garments hot, when the earth shall be blown with the South wind?\n"
	"Thou perhaps madest the heavens with him, which are most sound, cast as it were of brass.\n"
	"Shew us what we may say to him: for we are wrapped in darkness.\n"
	"Who shall tell him the things that I speak? Yea if man shall speak, he shall be devoured.\n"
	"But now they see not the light: suddenly the air shall be thickened into clouds, and the wind passing by shall drive them away.\n"
	"From the North gold cometh, & toward God fearful praising.\n"
	"We cannot find him worthily: great of strength, and judgment, and justice, and he cannot be uttered.\n"
	"Therefore shall men fear him, and all that seem to themselves to be wise, shall not dare to behold him.";