const char* chap55 = "After these things Moyses and Aaron went in, and said to Pharao: This saith the Lord God of Israel: dismiss my people that they may sacrifice to me in the desert.\n"
	"But he answered: Who is the Lord, that I should hear his voice, & dismiss Israel? I know not the Lord, and Israel I will not dismiss.\n"
	"And they said: The God of the Hebrews hath called us to go three days' journey into the wilderness, & to sacrifice to the Lord our God: lest perhaps there chance to us pestilence or sword.\n"
	"The king of Aegypt said to them: Why do you Moyses and Aaron solicit the people from their works? Go you to your burdens.\n"
	"And Pharao said: The people of the land is much: you see that the multitude is secretly increased: how much more if you give them rest from their works?\n"
	"Therefore he commanded in that day the overseers of the works and the exactors of the people, saying:\n"
	"You shall no more give straw to the people for to make bricks, as before; but let themselves go and gather straw.\n"
	"And the task of bricks, which they did before, you shall put upon them, neither shall you diminish any thing: for they are idle, and therefore they cry, saying: Let us go, and sacrifice to our God.\n"
	"Let them be oppressed with works, and let them accomplish them: that they hearken not to lying words.\n"
	"Therefore the overseers of the works and the exactors going forth said unto the people: Thus saith Pharao: I allow you no straw:\n"
	"go, and gather if you can find any-where: neither shall any thing of your work be diminished.\n"
	"And the people was dispersed through all the Land of Aegypt to gather straw.\n"
	"And the overseers of the works were instant, saying: Finish your work every day, as before you were wont to when straw was given unto you.\n"
	"And the overseers of the works of the children of Israel were scourged of Pharao's exactors, saying: Why do you not make up the task of bricks as before, neither yesterday, nor today?\n"
	"And the overseers of the children of Israel came, and cried out to Pharao, saying: Why dealest thou so against thy servants?\n"
	"Straw is not given us, and bricks are commanded us in like sort: behold we thy servants are beaten with whips, and thy people is unjustly dealt withal.\n"
	"Who said: You are idle, and therefore you say: Let us go and sacrifice to our Lord.\n"
	"Go therefore, and work: straw shall not be given you, and you shall give up the accustomed number of bricks.\n"
	"And the overseers of the children of Israel saw themselves in hard case, because it was said unto them: There shall not a whit be diminished of the bricks for every day.\n"
	"And they met Moyses and Aaron, who stood over-against them, coming forth from Pharao.\n"
	"and they said to them: Our Lord see and judge, because you have made our savour to stink before Pharao and his servants, and you have given him a sword for to kill us.\n"
	"And Moyses returned to our Lord, and said: Lord Why hast thou afflicted this people? Wherefore hast thou sent me?\n"
	"For since the time that I entered in to Pharao to speak in thy name, he hath afflicted thy people: and thou hast not delivered them.";