const char* chap557 = "Unto the end, for the sons of Core to understanding.\n"
	"O God we have heard with our ears: our fathers have declared to us. The work that thou hast wrought in their days: & in the days of old.\n"
	"Thy hand destroyed the nations, and thou didst plant them: thou didst afflict the peoples, and expel them.\n"
	"For not by their own sword did they possess the land, and their own arm did not save them: But thy right hand, and thine arm, and the illumination of thy countenance: because thou wast pleased in them.\n"
	"Thou art the same my King and my God: which commandest the salvations of Jacob.\n"
	"In thee we shall turn out our enemies with the horn, & in thy name we shall contemn them that rise up against us.\n"
	"For I will not hope in my bow: and my sword will not save me.\n"
	"For thou hast saved us from them that afflict us: and them that hate us thou hast confounded.\n"
	"In God we shall be praised all the day: and in thy name we will confess for ever.\n"
	"But now thou hast repelled and confounded us: and thou wilt not go forth, o God, in our hosts.\n"
	"Thou hast turned us back behind our enemies: and they that hated us spoiled for themselves.\n"
	"Thou hast given us as sheep that are to be eaten: and thou hast dispersed us among the nations.\n"
	"Thou hast sold thy people without price: and there was no multitude in the exchanges of them.\n"
	"Thou hast made us a reproach to our neighbours, a scorn and mocking stock to them that are round about us.\n"
	"Thou hast made us for a parable to the Gentiles: a wagging of the head among the peoples.\n"
	"All the day my shame is against me, and the confusion of my face hath covered me.\n"
	"At the voice of the upbraider, and the reproacher: at the face of the enemy and persecutor.\n"
	"All these things have come upon us, neither have we forgotten thee: and we have not done wickedly in thy testament.\n"
	"And our heart hath not revolted backward: & thou hast declined our paths from thy way.\n"
	"Because thou hast humbled us in the place of affliction, and the shadow of death hath covered us.\n"
	"If we have forgotten the name of our God, and if we have spread forth our hands to a strange god,\n"
	"Will not God inquire of these things? For he knoweth the secrets of the heart. Because for thee we are killed all the day: we are esteemed as sheep of slaughter.\n"
	"Arise, why sleepest thou, o Lord? Arise, and expel us not to the end.\n"
	"Why dost thou turn away thy face, forgettest our poverty and our tribulation?\n"
	"Because our soul is humbled in the dust: our belly is glued in the earth.\n"
	"Arise Lord, help us: and redeem us for thy name.";