const char* chap565 = "Unto the end, understanding to David,\n"
	"When Doeg the Idumeite came and told Saul: David is come into the house of Achimelech.\n"
	"Why doest thou glory in malice, which are mighty in iniquity?\n"
	"All the day hath thy tongue thought injustice: as a sharp razor thou hast done guile.\n"
	"Thou hast loved malice more than benignity: iniquity rather than to speak equity.\n"
	"Thou hast loved all words of precipitation, a deceitful tongue.\n"
	"Therefore will God destroy thee for ever, he will pluck thee out, & remove thee out of thy tabernacle: & thy root out of the land of the living.\n"
	"The just shall see, and fear, and shall laugh at him, and they shall say:\n"
	"Behold the man, that hath not put God for his helper. But hath hoped in the multitude of his riches, and hath prevailed in his vanity.\n"
	"But I as a fruitful olive tree in the house of God, have hoped in the mercy of God for ever: and for ever and ever.\n"
	"I will confess to thee for ever, because thou hast done it: and I will expect thy name, because it is good in the sight of thy Saints.";