const char* chap578 = "To the end, a Psalm of David, the Canticle of Jeremy, and Ezechiel, to the people of the transmigration, when they began to go forth.\n"
	"An hymn, o God, becometh thee in Sion: & a vow shall be rendered to thee in Jerusalem.\n"
	"Hear my prayer: all flesh shall come to thee.\n"
	"The words of the wicked have prevailed upon us: and thou wilt be propitious to our impieties.\n"
	"Blessed is he whom thou hast chosen and taken: he shall dwell in thy courts.\n"
	"We shall be replenished in the goods of thy house: holy is thy temple, marvelous in equity. Hear us, o God our saviour, the hope of all the ends of the earth, and in the sea far.\n"
	"Preparing mountains in thy strength, girded with might:\n"
	"which troublest the depths of the sea, the sound of the waves thereof.\n"
	"The Gentiles shall be troubled, and they that inhabit the borders shall be afraid of thy signs: the out-goings of the morning and evening thou shalt delight.\n"
	"Thou hast visited the earth, and hast inebriated it: thou hast multiplied to enrich it. The river of God is replenished with waters, thou hast prepared their meat: because so is the preparation thereof.\n"
	"Inebriate her rivers, multiply her fruits: in her drops she shall rejoice springing.\n"
	"Thou wilt bless the crown of the year of thy goodness: and thy fields shall be replenished with plenty.\n"
	"The beautiful places of the desert shall be fat: and the little hills shall be girded about with exultation.\n"
	"The rams of the sheep are clothed, and the valleys shall abound with corn: they will cry, yea they will say an hymn.";