const char* chap579 = "Unto the end, a Canticle of resurrection. Make ye jubilation to God all the earth,\n"
	"say a Psalm to his name: give glory to his praise.\n"
	"Say ye to God: How terrible are thy works, o Lord! In the multitude of thy strength thine enemies shall lie to thee.\n"
	"Let all the earth adore thee, and sing to thee: let it sing a Psalm to thy name.\n"
	"Come ye, and see the works of God: terrible in counsels over the children of men.\n"
	"Who turneth the sea into dry land, in the river they shall pass on foot, there we shall rejoice in him.\n"
	"Who ruleth in his strength for ever^ his eyes look upon the gentiles: they that exasperate him let them not be exalted in themselves.\n"
	"Ye Gentiles bless our God: and make the voice of his praise heard.\n"
	"Who hath put my soul in life: and hath not given my feet to be moved.\n"
	"Because thou hast proved us, o God: by fire thou hast tried us, as silver is tried.\n"
	"Thou hast brought us into a snare, thou hast laid tribulations on our back: thou hast set men upon our heads.\n"
	"We have passed through fire and water: and thou hast brought us out into refreshing.\n"
	"I will go into thy house with holocausts: I will render thee my vows:\n"
	"which my lips have distinguished. And my mouth hath spoken in my tribulation.\n"
	"Holocausts with marrow will I offer to thee, with incense of rams: I will offer to thee oxen with buck goats.\n"
	"Come ye, hear, and I will tell all ye that fear God, what great things he hath done for my soul.\n"
	"To him have I cried with my mouth, and have exulted under my tongue.\n"
	"If I have beheld iniquity in my heart, our Lord will not hear.\n"
	"Therefore hath God heard, and hath attended to the voice of my petition.\n"
	"Blessed be God who hath not removed my prayer, and his mercy from me.";