const char* chap581 = "Unto the end, a Psalm of Canticle, to David himself.\n"
	"Let God arise, and let his enemies be dispersed, and let them that hate him fly from his face.\n"
	"As smoke vanisheth, let them vanish away: as wax melteth at the presence of fire, so let sinners perish at the presence of God.\n"
	"And let the just make merry, and rejoice in the sight of God: and let them be delighted in mirth.\n"
	"Sing to God, say a Psalm to his name: make way to him, who mounteth upon the west, Lord is his name. Rejoice ye in his sight, they shall be troubled at the presence of him:\n"
	"the father of orphans, and judge of widows. God in his holy place:\n"
	"God that maketh men to inhabit of one manner in a house. That bringeth forth them that be bound, in strength, likewise them that exasperate, that dwell in sepulchres.\n"
	"O God when thou wentest forth in the sight of thy people, when thou didst pass through the desert.\n"
	"The earth was moved, and the heavens also distilled, at the presence of the God of Sina, at the face of the God of Israel.\n"
	"Voluntary rain shalt thou separate, o God, to thine inheritance: and it was weakened, but thou hath perfiteth it.\n"
	"Thy living creatures shall dwell in it: thou hast prepared in thy sweetness for the poor, o God.\n"
	"Our Lord shall give the word to them that evangelize, with great power.\n"
	"The King of hosts the beloved of the beloved: and to the beauty of the house, to divide the spoils.\n"
	"If ye sleep among the midst of the lots, the wings of a dove laid over with silver, and the hinder parts of her back in the paleness of gold.\n"
	"Whilst the heavenly discerneth kings over her, with snow they shall be made white in Selmon.\n"
	"The mountain of God a fat mountain. A mountain curded as cheese, a fat mountain:\n"
	"why suppose you curded mountains? A mountain, in which it hath well pleased God to dwell therein: for indeed our Lord will dwell even to the end.\n"
	"The chariot of God is ten thousand fold, thousands of them that rejoice, our Lord in them, in Sina in the holy place.\n"
	"Thou art ascended on high, thou hast taken captivity: thou hast received gifts in men: for even those that do not believe, our Lord God to inhabit.\n"
	"Blessed be our Lord day by day: the God of our salvations will make us a prosperous journey.\n"
	"Our God is the God of saving: and the issues of death are of our Lord, our Lord.\n"
	"But yet God still break the heads of his enemies: the hairy crown of them, that walk in their sins.\n"
	"Our Lord said: Out of Basan I will convert, I will convert into the depth of the sea.\n"
	"That thy foot may be dipped in blood: the tongue of thy dogs (made red) with the same (blood) of the enemies.\n"
	"They have seen thy enterings in, o God, the enterings of my God: of my King who is in the holy place.\n"
	"Princes came before joined with them that sang, in the midst of young women playing on timbrels.\n"
	"In Churches bless ye God our Lord, of the fountains of Israel.\n"
	"There Benjamin a young man, in excess of mind. The Princes of Juda their leaders: the Princes of Zabulon, the Princes of Nephthali.\n"
	"Command thy strength, o God: confirm this, o God, which thou hast wrought in us.\n"
	"From thy temple in Jerusalem, kings shall offer gifts to thee.\n"
	"Rebuke the wild beasts of the reed, the congregation of bulls in the kine of thy peoples: that they may exclude them, which are tried with silver. Dissipate the nations that will wars:\n"
	"Legates shall come out of Aegypt: Aethiopia shall prevent his hands to God.\n"
	"Ye Kingdoms of the earth sing to God: sing to our Lord:\n"
	"Sing ye to God, that mounteth upon the heaven of heaven, to the East. Behold he will give to his voice the voice of strength:\n"
	"give you glory to God upon Israel, his magnificence, and his power in the clouds.\n"
	"God is marvelous in his Saints, the God of Israel he will give power and strength to his people, God be blessed.";