const char* chap586 = "A Psalm to Asaph. How good is God to Israel, to them that are of a right heart!\n"
	"But my feet were almost moved, my steps almost slipped.\n"
	"Because I have had zeal upon the wicked, seeing the peace of sinners.\n"
	"Because there is no respect to their death: and stability in their plague.\n"
	"In the labours of men they are not, and with men they shall not be scourged.\n"
	"Therefore hath pride held them, they are covered with their iniquity and impiety.\n"
	"Their iniquity hath proceeded as it were of fat: they have passed into the affection of the heart.\n"
	"They have thought and have spoken wickedness: they have spoken iniquity on high.\n"
	"They have set their mouth unto heaven: and their tongue hath passed in the earth.\n"
	"Therefore will my people return here: and full days shall be found in them.\n"
	"And they have said: How doth God know, and is there knowledge in the highest?\n"
	"Lo the sinners themselves, and they that abound in the world, have obtained riches.\n"
	"And I said: Then have I justified my heart without cause, and have washed my hands amongst innocents:\n"
	"And have been scourged all the day, and my chastising in the mornings.\n"
	"If I said: I will speak this: behold I reproved the nation of thy children.\n"
	"I thought to know this thing, it is labour before me:\n"
	"Until I may enter into the sanctuary of God: and may understand concerning their latter ends.\n"
	"But yet for guiles thou hast put it to them: thou hast cast them down whilst they were elevated.\n"
	"How are they brought into desolation, they have failed suddenly: they have perished for their iniquity.\n"
	"As the dream of them that rise, o Lord, in thy city thou shalt bring their image to nothing.\n"
	"Because my heart is inflamed, and my reins are changed:\n"
	"And I am brought to nothing, and knew not.\n"
	"As a beast am I become with thee: and I always with thee.\n"
	"Thou hast held my right hand: and in thy will thou hast conducted me, and with glory thou hast received me.\n"
	"For what is to me in heaven? And besides thee what would I upon the earth?\n"
	"My flesh hath fainted, and my heart: God of my heart, and God my portion for ever.\n"
	"For behold, they that make themselves far from thee, shall perish: thou hast destroyed all that fornicate from thee.\n"
	"But it is good for me to cleave to God: to put my hope in our Lord God. That I may shew forth all thy praises, in the gates of the daughter of Sion.";