const char* chap601 = "A Canticle of a Psalm, to the children of Core, unto the end, for Maheleth to answer, of understanding to Eman the Ezrahite.\n"
	"O Lord the God of my salvation: in the day have I cried, and in the night before thee.\n"
	"Let my prayer enter in thy sight: incline thine ear to my petition.\n"
	"Because my soul is replenished with evils: & my life hath approached to hell.\n"
	"I am accounted with them that descend into the lake. I am become as a man without help,\n"
	"free among the dead, as the wounded sleeping in the sepulchres, of whom thou art mindful no more: and they are cast off from thy hand.\n"
	"They have put me in the lower lake: in the dark places, and in the shadow of death.\n"
	"Thy fury is confirmed upon me: and all thy waves thou hast brought in upon me.\n"
	"Thou hast made my familiars far from me: they have put me abomination to themselves. I was delivered and came not forth:\n"
	"mine eyes languished for poverty. I cried to thee o Lord all the day: I stretched out my hands to thee.\n"
	"Wilt thou do marvels to the dead: or shall physicians raise to life, and they confess to thee?\n"
	"Shall any in the sepulchre declare thy mercy, and thy truth in perdition?\n"
	"Shall thy marvelous works be known in darkness: and thy justice in the land of oblivion.\n"
	"And I o Lord have cried to thee: and in the morning shall my prayer prevent thee.\n"
	"Why doest thou, o Lord, reject my prayer: turnest away thy face from me?\n"
	"I am poor, and in labours from my youth: and being exalted, humbled, and troubled.\n"
	"Thy wraths have passed upon me: and thy terrors have troubled me.\n"
	"They have compassed me as water all the day: they compassed me together.\n"
	"Thou hast made friend, and neighbour far from me and my familiars because of misery.";