const char* chap602 = "Of understanding to Ethan the Ezrahite.\n"
	"The mercies of our Lord I will sing for ever. In generation and generation I will shew forth thy truth in my mouth.\n"
	"Because thou saidst: Mercy shall be built up for ever in the heavens: thy truth shall be prepared in them.\n"
	"I have ordained a testament with mine elect, I have sworn to David my servant:\n"
	"for ever will I prepare thy seed. And I will build thy seat unto generation and generation.\n"
	"The heavens shall confess thy marvelous works o Lord: yea and thy truth in the Church of Saints.\n"
	"For who in the clouds shall be equal to our Lord: shall be like to God among the sons of God?\n"
	"God who is glorified in the counsel of Saints, great and terrible over all that are round about him.\n"
	"O Lord God of hosts, who is like to thee? Thou art mighty, o Lord, and thy truth round about thee.\n"
	"Thou rulest over the power of the sea: and the moving of the waves thereof thou doest mitigate.\n"
	"Thou humbledst the proud one, as one wounded: in the arm of thy strength thou hast dispersed thine enemies.\n"
	"The heavens are thine, and the earth is thine, the round earth, and the fullness thereof thou hast founded:\n"
	"the north and the sea thou hast created. Thabor and Hermon shall rejoice in thy name:\n"
	"thy arm is with might. Let thy hand be confirmed, and thy right hand exalted:\n"
	"justice and judgment is the preparation of thy seat. Mercy and truth shall go before thy face:\n"
	"blessed is the people that knoweth jubilation. Lord they shall walk in the light of thy countenance,\n"
	"and in thy name they shall rejoice all the day: and in thy justice they shall be exalted.\n"
	"Because thou art the glory of their strength: and in thy good pleasure shall our horn be exalted.\n"
	"Because our protection is of our Lord: and of the holy one of Israel our King.\n"
	"Then didst thou speak in vision to thy Saints, and saidst: I have put help on the mighty one: & have exalted an elect one of my people.\n"
	"I have found David my servant: with mine holy oil have I anointed him.\n"
	"For mine hand shall help him: and mine arm shall strengthen him.\n"
	"The enemy shall nothing prevail in him: and the son of iniquity shall not add to hurt him.\n"
	"And I will cut down his enemies before his face: and them that hate him I will put to flight.\n"
	"And my truth, and my mercy with him: and in my name shall his horn be exalted.\n"
	"And I will put his hand in the sea: and his right hand in the rivers.\n"
	"He shall invocate me: Thou art my Father: my God, and the protector of my Salvation.\n"
	"And I will put him the first-begotten, high above the kings of the earth.\n"
	"I will keep my mercy unto him for ever: and my testament faithful to him.\n"
	"I will put his seed for ever and ever: and his throne as the days of heaven.\n"
	"But if his children shall forsake my law: and will not walk in my judgments.\n"
	"If they shall profane my justices: and not keep my commandments\n"
	"I will visit their iniquities with a rod: and their sins with stripes.\n"
	"But my mercy I will not take away from him: neither will I hurt in my truth.\n"
	"Neither will I profane my testament: and the words that proceed from my mouth I will not make frustrate.\n"
	"Once I have sworn in my holy, if I lie to David:\n"
	"his seed shall continue for ever.\n"
	"And his throne as the Sun in my sight, and as the Moon perfect for ever: and a faithful witness in heaven.\n"
	"But thou hast repelled and despised: thou hast deferred thy Christ.\n"
	"Thou hast overthrown the testament of thy servant: thou hast profaned his sanctuary on the earth.\n"
	"Thou hast destroyed all the hedges thereof: thou hast made the firmament thereof fear.\n"
	"All that pass by the way have spoiled him: he is become a reproach to his neighbours.\n"
	"Thou hast exalted the right hand of them that oppress him: thou hast made all his enemies joyful.\n"
	"Thou hast turned away the help of his sword: and hast not holpen him in battle.\n"
	"Thou hast destroyed him from emundation: and his seat thou hast broken down to the ground.\n"
	"Thou hast lessened the days of his time: thou hast overwhelmed him with confusion.\n"
	"How long, o Lord, doest thou turn away for ever: shall thy wrath burn as a fire?\n"
	"Remember what my substance is: for hast thou made all the children of men in vain?\n"
	"Who is the man that shall live, and shall not see death: shall deliver his soul from the hand of hell?\n"
	"Where are thine old mercies, o Lord, as thou swarest to David in thy truth?\n"
	"Be mindful, o Lord, of the reproach of thy servants (which I have held in my bosom) of many nations.\n"
	"Which thine enemies have reproached, o Lord, which they have reproached the commutation of thy Christ.\n"
	"Blessed be our Lord for ever: Be it, be it.";