const char* chap607 = "To David himself, in the fourth of the sabbath. Our Lord God of revenges: the God of revenges hath done freely.\n"
	"Be exalted thou that judgest the earth: render retribution to the proud.\n"
	"How long shall sinners, o Lord: how long shall sinners glory?\n"
	"Shall they utter, and speak iniquity? Shall all they speak that work injustice?\n"
	"Thy people, o Lord, they have humbled: and thine inheritance they have vexed.\n"
	"The widow, and the stranger they have slain: and the pupils they have killed.\n"
	"And they have said: The Lord shall not see, neither shall the God of Jacob understand.\n"
	"Understand ye foolish in the people: and ye fools be wise at sometime.\n"
	"He that planted the ear, shall he not hear? Or he that made the eye doth he not consider?\n"
	"He that chastiseth nations, shall he not rebuke: he that teacheth man knowledge?\n"
	"Our Lord knoweth the cogitations of men: that they be vain.\n"
	"Blessed is the man whom thou shalt instruct, o Lord, and shalt teach out of thy law.\n"
	"That thou mayst give him quietness from the evil days: till a pit be digged for the sinner.\n"
	"Because our Lord will not reject his people: and his inheritance he will not forsake.\n"
	"Until justice be turned into judgment: and they who are near it, are all that are right of heart.\n"
	"Who shall rise for me against the malignant? Or who shall stand with me against them that work iniquity?\n"
	"But that our Lord hath holpen me: within very little my soul had dwelt in hell.\n"
	"If I said: My foot is moved: thy mercy, o Lord, did help me.\n"
	"According to the multitude of my sorrows in my heart: thy consolations have made my soul joyful.\n"
	"Doth the seat of iniquity cleave to thee: which makest labour in precept?\n"
	"They will hunt after the soul of the just: and will condemn innocent blood.\n"
	"And our Lord became my refuge: and my God the help of my hope.\n"
	"And he will repay them their iniquity: and in their malice he will destroy them: the Lord our God will destroy them.";