const char* chap610 = "To this David, when his land was restored again to him. Our Lord hath reigned, let the earth rejoice: let many Islands be glad.\n"
	"Cloud and mist round about him: justice and judgment the correction of his seat.\n"
	"Fire shall go before him, and shall inflame his enemies round about.\n"
	"His lightnings shined to the round world, the earth saw: and was moved.\n"
	"The mountains melted as wax, before the face of our Lord: before the face of our Lord all the earth.\n"
	"The heavens have shewed forth his justice: and all peoples have seen his glory.\n"
	"Let them all be confounded, that adore sculptiles: and that glory in their idols. Adore him all ye his Angels:\n"
	"Sion heard, and was glad. And the daughters of Juda rejoiced, because of thy judgments, o Lord.\n"
	"Because thou Lord most high over all the earth: thou art exalted exceedingly above all gods.\n"
	"You that love our Lord, hate ye evil, our Lord keepeth the souls of his saints, out of the hand of the sinner he will deliver them.\n"
	"Light is risen to the just, and joy to the right of heart.\n"
	"Be glad ye just in our Lord: and confess ye to the memory of his sanctification.";