const char* chap616 = "To David himself. My soul bless thou our Lord: and all things, that are within me, his holy name.\n"
	"My soul bless thou our Lord: and forget not all his retributions.\n"
	"Who is propitious to all thine iniquities: who healeth all thine infirmities.\n"
	"Who redeemeth thy life from deadly falling: who crowneth thee in mercy and commiserations.\n"
	"Who replenisheth thy desire in good things: thy youth shall be renewed as the eagle's.\n"
	"Our Lord doth mercies: and judgment to all that suffer wrong.\n"
	"He made his ways known to Moyses, his wills to the children of Israel.\n"
	"Our Lord is pitiful, and merciful: long suffering, and very merciful.\n"
	"He will not be angry always: neither will he threaten for ever.\n"
	"He hath not done to us according to our sins: neither according to our iniquities hath he rewarded us.\n"
	"For according to the height of heaven from the earth: hath he strengthened his mercy upon them that fear him.\n"
	"As far as the East is distant from the West: hath he made our iniquities far from us.\n"
	"As a father hath compassion of his children, so hath our Lord compassion on them that fear him:\n"
	"because he hath known our making. He remembered that we are dust:\n"
	"man, his days are as grass, as the flower of the field, so shall he flourish.\n"
	"Because the spirit shall pass in him, and he shall not stand: and he shall know his place no more.\n"
	"But the mercy of our Lord from everlasting, and unto everlasting upon them that fear him. And his justice is upon the children's children, to them that keep his testament.\n"
	"And are mindful of his commandments to do them.\n"
	"Our Lord hath prepared his seat in heaven: and his Kingdom shall have dominion over all.\n"
	"Bless our Lord all ye his Angels: mighty in power, doing his word, that fear the voice of his words.\n"
	"Bless our Lord all ye his hosts: you his ministers, that do his will.\n"
	"Bless ye our Lord all his works: in every place of his dominion, my soul bless thou our Lord.";