const char* chap617 = "To David himself. My soul bless thou our Lord: o Lord my God thou art magnified exceedingly.\n"
	"Thou hast put on confession and beauty: being clothed with light as with a garment. Stretching out the heaven as a skin:\n"
	"which coverest the higher parts thereof with waters. Which makest the cloud for thee to ascend on: which walkest upon the wings of winds.\n"
	"Which makest spirits thine Angels: and thy ministers a burning fire.\n"
	"Which hast founded the earth upon the stability thereof: it shall not be inclined for ever and ever.\n"
	"The depth, as a garment, is his clothing: upon the mountains shall waters stand.\n"
	"At thy reprehension they shall fly: at the voice of thy thunder they shall fear.\n"
	"The mountains ascend: and the plain fields descend into the place, which thou hast founded for them.\n"
	"Thou hast set a bound, which they shall not pass over: neither shall they return to cover the earth.\n"
	"Which sendest forth fountains in the valleys: between the midst of mountains shall waters pass.\n"
	"All the beasts of the field shall drink: the wild asses shall expect in their thirst.\n"
	"Over them shall the fowls of the air inhabit: out of the midst of rocks they shall give forth voices.\n"
	"Watering the mountains from higher places: of the fruit of thy work shall the earth be filled.\n"
	"Bringing forth grass for beasts, and herb for the service of men. That thou mayst bring forth bread out of the earth:\n"
	"& wine may make the heart of man joyful. That he may make the face cheerful with oil: and bread may confirm the heart of man.\n"
	"The trees of the field shall be filled, and the cedars of Libanus, which he hath planted:\n"
	"there^ sparrows shall make their nest. The house of the heron is the leader of them:\n"
	"the high mountains for harts: the rock a refuge for the Irchins.\n"
	"He made the moon for seasons: the sun knoweth his going down.\n"
	"Thou didst appoint darkness, and night was made: in it shall all the beasts of the wood pass.\n"
	"The whelps of lions roaring, to raven, and to seek of God meat for themselves.\n"
	"The sun is risen, & they are gathered together: and in their couches they shall be placed.\n"
	"Man shall go forth to his work: and to his working until evening.\n"
	"How magnified are thy works, o Lord! Thou hast made all things in wisdom: the earth is filled with thy possession.\n"
	"This great sea, and very large, there are creeping beasts, whereof there is no number. Little beasts with great:\n"
	"there ships shall pass. This dragon, whom thou madest to delude:\n"
	"all expect of thee that thou give them meat in season.\n"
	"Thou giving unto them, they shall gather it: thou opening thy hand, all shall be filled with bounty.\n"
	"But thou turning away the face, they shall be troubled: thou shalt take away their spirit, and they shall fail, and shall return into their dust.\n"
	"Thou shalt send forth thy spirit, and they shall be created: and thou shalt renew the face of the earth.\n"
	"Be the glory of our Lord for ever: our Lord will rejoice in his works.\n"
	"Who looketh upon the earth, & maketh it to tremble: who toucheth the mountains, and they smoke.\n"
	"I will chant to our Lord in my life: I will sing to my God as long as I am.\n"
	"Let my speech be acceptable to him: but I will take delight in our Lord.\n"
	"Let sinners fail from the earth, and the unjust, so that they be not: my soul bless thou our Lord.";