const char* chap620 = "Alleluia. Confess ye to our Lord, because he is good: because his mercy is for ever.\n"
	"Let them say that are redeemed of our Lord, whom he redeemed out of the hand of the enemy: and out of the countries he gathered them:\n"
	"From the rising of the sun, and the going down: from the north, and the sea.\n"
	"They wandered in the wilderness, in a place without water: the way of city for habitation they found not.\n"
	"Hungry and thirsty: their soul fainted in them.\n"
	"And they cried to our Lord when they were in tribulation: and he delivered them out of their necessities.\n"
	"And he conducted them into the right way: to go into a city of habitation.\n"
	"Let the mercies of our Lord confess to him: and his marvelous works to the children of men.\n"
	"Because he hath filled the empty soul: and the hungry soul he hath filled with good things.\n"
	"Them that sat in darkness, and in the shadow of death: bound in neediness, and iron.\n"
	"Because they exasperated the words of God: and they provoked the counsel of the Highest.\n"
	"And their heart was humbled in labours: they were weakened, neither was there any to help.\n"
	"And they cried to our Lord when they were in tribulation: and he delivered them out of their necessities.\n"
	"And he brought them out of darkness, and the shadow of death: and brake their bonds asunder.\n"
	"Let the mercies of our Lord confess to him: & his marvelous works to the children of men.\n"
	"Because he hath destroyed the gates of brass; and the bars of iron he hath broken.\n"
	"He hath received them out of the way of their iniquity: for they were humbled for their injustices.\n"
	"Their soul did abhor all meat: & they approached even to the gates of death.\n"
	"And they cried to our Lord when they were in tribulation: and he delivered them out of their necessities.\n"
	"He sent his word, and healed them: and delivered them out of their destructions.\n"
	"Let the mercies of our Lord confess to him: & his marvelous works to the children of men.\n"
	"And let them sacrifice the sacrifice of praise: & shew forth his works in exultation.\n"
	"They that go down into the sea in ships, making traffic in the great waters.\n"
	"They have seen the works of our Lord, and his marvelous things in the depth.\n"
	"He said, and the blast of the storm stood: and the waves thereof were exalted.\n"
	"They ascend even to the heavens, and they descend even to the depths: their soul pined away in evils.\n"
	"They were troubled, and were moved as a drunken man: and all their wisdom was devoured.\n"
	"And they cried to our Lord when they were in tribulation, and he brought them out of their necessities.\n"
	"And he turned his storm into calm: & the waves thereof were quiet.\n"
	"And they rejoiced because they were quiet: and he conducted them into the haven of their will.\n"
	"Let the mercies of our Lord confess to him: and his marvelous works to the children of men.\n"
	"And let them exalt him in the Church of the people: and the chair of the ancients let them praise him.\n"
	"He turned the rivers into a desert: and the issues of waters into dryness.\n"
	"The fruitful land into a salt ground, for the malice of them that inhabit it.\n"
	"He turned the desert into pools of waters: and the land without water into issues of waters.\n"
	"And he placed the hungry there, and they built a city of habitation.\n"
	"And they sowed fields and planted vineyards: and they made fruit of nativity.\n"
	"And he blessed them, and they were multiplied exceedingly: and their beasts he lessened not.\n"
	"And they were made few: and were vexed by the tribulation of evils, and with sorrow.\n"
	"Contempt was poured out upon Princes: and he made them wander where was no way, and not in the way.\n"
	"And he did help the poor out of poverty: and made families as sheep.\n"
	"The just shall see, and shall rejoice: & all iniquity shall stop her mouth.\n"
	"Who is wise and will keep these things? And will understand the mercies of our Lord?";