const char* chap632 = "Alleluia. Aleph. Doctrine. Blessed are the immaculate in the way: which walk in the law of our Lord.\n"
	"Blessed are they that search his testimonies: that seek after him with all their heart.\n"
	"For they that work iniquity, have not walked in his ways.\n"
	"Thou hast very much commanded thy commandments to be kept.\n"
	"Would God my ways might be directed, to keep thy justifications.\n"
	"Then shall I not be confounded, when I shall look throughly in all thy commandments.\n"
	"I will confess to thee in direction of heart: in that I have learned the judgments of thy justice.\n"
	"I will keep thy justifications: forsake me not wholly.\n"
	"Beth. House. Wherein doth a young man correct his way? In keeping thy words.\n"
	"With my whole heart I have sought after thee: repel me not from thy commandments.\n"
	"In my heart I have hid thy words: that I may not sin to thee.\n"
	"Blessed art thou, o Lord: teach me thy justifications.\n"
	"In my lips I have pronounced all the judgments of thy mouth.\n"
	"I am delighted in the way of thy testimonies, as in all riches.\n"
	"I will be exercised in thy commandments: and I will consider thy ways.\n"
	"I will meditate in thy justifications: I will not forget thy words.\n"
	"Gimel. Fullness. Render to thy servant, quicken me: and I shall keep thy words.\n"
	"Reveal mine eyes: and I shall consider the marvelous things of thy law.\n"
	"I am a sojourner in the land, hide not thy commandments from me.\n"
	"My soul hath coveted to desire thy justifications, at all time.\n"
	"Thou hast rebuked the proud: cursed are they that decline from thy commandments.\n"
	"Take from me reproach, and contempt: because I have sought after thy testimonies.\n"
	"For Princes sat, and they spake against me: but thy servant was exercised in thy justifications.\n"
	"For both thy testimonies are my meditation: and thy justifications my counsel.\n"
	"Daleth. Of Tables. My soul hath cleaved to the pavement: quicken me according to thy word.\n"
	"I have uttered my ways, and thou hast heard me: teach me thy justifications.\n"
	"Instruct me the way of thy justifications: and I shall be exercised in thy marvelous works.\n"
	"My soul hath slumbered for tediousness: confirm me in thy words.\n"
	"Remove from me the way of iniquity: and according to thy law, have mercy on me.\n"
	"I have chosen the way of truth: I have not forgotten thy judgments.\n"
	"I have cleaved to thy testimonies, o Lord: do not confound me.\n"
	"I ran the way of thy commandments: when thou didst dilate my heart.\n"
	"He. This thing. Set me a law, o Lord, the way of thy justifications: and I will seek after it always.\n"
	"Give me understanding, and I will search thy law: and I will keep it with my whole heart.\n"
	"Conduct me into the path of thy commandments: because I would it.\n"
	"Incline my heart into thy testimonies: and not into avarice.\n"
	"Turn away mine eyes that they see not vanity: in thy way quicken me.\n"
	"Establish thy word to thy servant, in thy fear.\n"
	"Take away my reproach, which I have feared: because thy judgments are pleasant.\n"
	"Behold I have coveted thy commandments: in thine equity quicken me.\n"
	"Vau. And. And let thy mercy come upon me, o Lord: thy salvation according to thy word.\n"
	"And I shall answer a word to them that upbraid me: because I have hoped in thy words.\n"
	"And take not away out of my mouth the word of truth utterly: because I have much hoped in thy judgments.\n"
	"And I will keep thy law always: for ever, and for ever and ever.\n"
	"And I walked in largeness: because I have sought after thy commandments.\n"
	"And I spake of thy testimonies in the sight of kings: and was not confounded.\n"
	"And I meditated in thy commandments, which I loved.\n"
	"And I have lifted up my hands to thy commandments, which I loved: and I was exercised in thy justifications.\n"
	"Zain. This. Be mindful of thy word to thy servant, wherein thou hast given me hope.\n"
	"This hath comforted me in my humiliation: because thy word hath quickened me.\n"
	"The proud did unjustly exceedingly: but I declined not from thy law.\n"
	"I have been mindful of thy judgments from everlasting, o Lord: and was comforted.\n"
	"Fainting possessed me, because of sinners forsaking thy Law.\n"
	"Thy justifications were song by me, in the place of my peregrination.\n"
	"I have been mindful in the night of thy name, o Lord: and have kept thy law.\n"
	"This was done to me: because I sought after thy justifications.\n"
	"Heth. Life. My portion, o Lord, I said to keep thy law.\n"
	"I besought thy face, with all my heart: have mercy on me according to thy word.\n"
	"I thought upon my ways: and converted my feet unto thy testimonies.\n"
	"I am prepared, and am not troubled: to keep thy commandments.\n"
	"The cords of sinners have wrapped me round about: and I have not forgotten thy law.\n"
	"At mid-night I rose to confess to thee, for the judgments of thy justification.\n"
	"I am partaker of all that fear thee: and that keep thy commandments.\n"
	"The earth, o Lord, is full of thy mercy: teach me thy justifications.\n"
	"Teth. Good. Thou hast done bounty with thy servant, o Lord: according to thy word.\n"
	"Teach me goodness, and discipline, and knowledge: because I have believed thy commandments.\n"
	"Before I was humbled I offended: therefore have I kept thy word.\n"
	"Thou art good: and in thy goodness teach me thy justifications.\n"
	"The iniquity of the proud is multiplied upon me: but I in all my heart will search thy commandments.\n"
	"Their heart is curded together as milk: but I have meditated thy law.\n"
	"It is good for me that thou hast humbled me: that I may learn thy justifications.\n"
	"The law of thy mouth is good unto me, above thousands of gold and silver.\n"
	"Iod. Beginning. Thy hands have made me, and formed me: give me understanding, and I will learn thy commandments.\n"
	"They that fear thee shall see me, & shall rejoice: because I have much hoped in thy words.\n"
	"I know, o Lord, that thy judgments are equity: and in thy truth thou hast humbled me.\n"
	"Let thy mercy be done to comfort me, according to thy word unto thy servant.\n"
	"Let thy commiserations come to me, and I shall live: because thy law is my meditation.\n"
	"Let the proud be confounded, because they have done unjustly toward me: but I will be exercised in thy commandments.\n"
	"Let them be converted to me that fear thee: and that know thy testimonies.\n"
	"Let my heart be made immaculate in thy justifications, that I be not confounded.\n"
	"Caph. Hand, or Palm of the hand. My soul hath fainted for thy salvation: and I have much hoped in thy word.\n"
	"Mine eyes have failed for thy word, saying: When wilt thou comfort me?\n"
	"Because I am made as a bottle in the hoar frost: I have not forgotten thy justifications.\n"
	"How many are the days of thy servant: when wilt thou do judgment on them that persecute me?\n"
	"The unjust have told me fables: but not as thy law.\n"
	"All thy commandments are truth: they have unjustly persecuted me, help me.\n"
	"They have well near made end of me in the earth: but I have not forsaken thy commandments.\n"
	"According to thy mercy quicken me: and I shall keep the testimonies of thy mouth.\n"
	"Lamed. Discipline. For ever Lord thy word is permanent in heaven.\n"
	"Thy truth in generation and generation: thou hast founded the earth, and it is permanent.\n"
	"By thy ordinance the day continueth: because all things serve thee.\n"
	"But that thy law is my meditation: I had then perhaps perished in my humiliation.\n"
	"I will not forget thy justifications for ever: because in them thou hast quickened me.\n"
	"I am thine, save me: because I have sought out thy justifications.\n"
	"Sinners have expected me to destroy me: I understood thy testimonies.\n"
	"Of all consummation I have seen the end: thy commandment is exceeding large.\n"
	"Mem. Of them. How have I loved thy law, o Lord! All the day it is my meditation.\n"
	"Above mine enemies thou hast made me wise by thy commandment: because it is to me for ever.\n"
	"Above all that taught me have I understood: because thy testimonies are my meditation.\n"
	"Above ancients have I understood: because I have sought thy commandments.\n"
	"I have stayed my feet from all evil way: that I may keep thy words.\n"
	"I have not declined from thy judgments: because thou hast set me a law.\n"
	"How sweet are thy words to my jaws. More than honey to my mouth!\n"
	"By thy commandments I have understood: therefore have I hated all the way of iniquity.\n"
	"Nun. Everlasting. Thy word is a lamp to my feet, and a light to my paths.\n"
	"I sware, and have determined to keep the judgments of thy justice.\n"
	"I am humbled exceedingly, o Lord: quicken me according to thy word.\n"
	"The voluntaries of my mouth make acceptable, o Lord: and teach me thy judgments.\n"
	"My soul is in my hands always: and I have not forgotten thy law.\n"
	"Sinners laid a snare for me: and I have not erred from thy commandments.\n"
	"For inheritance I have purchased thy testimonies for ever: because they are the joy of my heart.\n"
	"I have inclined my heart to do thy justifications for ever, for reward.\n"
	"Samech. Help. I have hated the unjust: and I have loved thy law.\n"
	"Thou art my helper, and protector: and upon thy word I have much hoped.\n"
	"Depart from me ye malignant: and I will search the commandments of my God.\n"
	"Receive me according to thy word, and I shall live: and confound me not of mine expectation.\n"
	"Help me, and I shall be saved: and I will meditate in thy justifications always.\n"
	"Thou hast despised all that revolt from thy judgments: because their cogitation is unjust.\n"
	"All the sinners of the earth I have reputed prevaricators: therefore have I loved thy testimonies.\n"
	"Pierce my flesh with thy fear: for I am afraid of thy judgments.\n"
	"Ain. A fountain, or an eye. I have done judgment and justice: deliver me not to them that calumniate me.\n"
	"Receive thy servant unto good: let not the proud calumniate me.\n"
	"Mine eyes have failed after thy salvation: and for the word of thy justice.\n"
	"Do with thy servant according to thy mercy: and teach me thy justifications.\n"
	"I am thy servant: give me understanding, that I may know thy testimonies.\n"
	"It is time to do, o Lord: they have dissipated thy law.\n"
	"Therefore have I loved thy commandments, above gold and topazius.\n"
	"Therefore was I directed to all thy commandments: all wicked way I have hated.\n"
	"Phe. Mouth. Thy testimonies are marvelous: therefore hath my soul searched them.\n"
	"The declaration of thy words doth illuminate: and giveth understanding to little ones.\n"
	"I opened my mouth, and drew breath: because I desired thy commandments.\n"
	"Look upon me, and have mercy on me, according to the judgment of them that love thy name.\n"
	"Direct my steps according to thy word: and let not any injustice have domination over me.\n"
	"Redeem me from the calumnies of men: that I may keep thy commandments.\n"
	"Illuminate thy face upon thy servant: and teach me thy justifications.\n"
	"Mine eyes have gushed forth issues of waters: because they have not kept thy law.\n"
	"Sade. Justice. Thou art just, o Lord: and thy judgment is right.\n"
	"Thou hast commanded justice thy testimonies: and thy verity exceedingly.\n"
	"My zeal hath made me to pine away: because mine enemies have forgotten thy words.\n"
	"Thy word is fired exceedingly: and thy servant hath loved it.\n"
	"I am a youngman, and contemned: I have not forgotten thy justifications.\n"
	"Thy justice is justice for ever: and thy law is verity.\n"
	"Tribulation and distress have found me: thy commandments are my meditation.\n"
	"Thy testimonies are equity for ever^ give me understanding, and I shall live.\n"
	"Coph. Vocation. I have cried in my whole heart, hear me, o Lord: I will seek after thy justifications.\n"
	"I have cried to thee, save me: that I may keep thy commandments.\n"
	"I have prevented in maturity, and have cried: because I hoped much in thy words.\n"
	"Mine eyes have prevented early unto thee: that I might meditate thy words.\n"
	"Hear my voice according to thy mercy, o Lord: and according to thy judgment quicken me.\n"
	"They that persecute me have approached to iniquity: but from thy law they are made far off.\n"
	"Thou art nigh, o Lord: and all thy ways are truth.\n"
	"From the beginning I knew of thy testimonies: that thou hast founded them for ever.\n"
	"Res. Head. See my humiliation, and deliver me: because I have not forgotten thy law.\n"
	"Judge my judgment, & redeem me: for thy word quicken thou me.\n"
	"Salvation is far from sinners: because they have not sought after thy justifications.\n"
	"Thy mercies are many, o Lord: according to thy judgment quicken me.\n"
	"There are many that persecute me, and afflict me: I have not declined from thy testimonies.\n"
	"I saw the prevaricators, and I pined away: because they kept not thy words.\n"
	"See that I have loved thy commandments, o Lord: in thy mercy quicken me.\n"
	"The beginning of thy words is truth: all the judgments of thy justice are for ever.\n"
	"Sin. Tooth. Princes have persecuted me without cause: and my heart hath been afraid of thy words.\n"
	"I will rejoice at thy words: as he that findeth many spoils.\n"
	"I have heard iniquity, and abhorred it: but thy law I have loved.\n"
	"Seven times in the day I have said praise to thee, for the judgments of thy justice.\n"
	"There is much peace to them that love thy law: & there is no scandal to them.\n"
	"I expected thy salvation, o Lord: and have loved thy commandments.\n"
	"My soul hath kept thy testimonies: & hath loved them exceedingly.\n"
	"I have kept thy commandments, and thy testimonies: because all my ways are in thy sight.\n"
	"Tau. Sign. Let my petition approach in thy sight, o Lord: according to thy word give me understanding.\n"
	"Let my request enter in thy sight: according to thy word deliver me.\n"
	"My lips shall utter an hymn, when thou shalt teach me thy justifications.\n"
	"My tongue shall pronounce thy word: because all thy commandments are equity.\n"
	"Let thy hand be to save me: because I have chosen thy commandments.\n"
	"I have coveted thy salvation, o Lord: and thy law is my meditation.\n"
	"My soul shall live, and shall praise thee: and thy judgments shall help me.\n"
	"I have strayed as a sheep that is lost: seek thy servant, because I have not forgotten thy commandments.";