const char* chap645 = "A gradual Canticle. Remember David, o Lord, and all his meekness:\n"
	"As he sware to our Lord, vowed a vow to the God of Jacob.\n"
	"If I shall enter into the tabernacle of my house, if I shall ascend into the bed of my couch.\n"
	"If I shall give sleep to mine eyes, and slumbering to mine eye lids:\n"
	"And rest to my temples: until I find a place for our Lord, a tabernacle for the God of Jacob.\n"
	"Behold we have heard of it in Ephrata: we have found it in the fields of the wood.\n"
	"We will enter into his tabernacle: we will adore in the place where his feet stood.\n"
	"Arise Lord into thy rest, thou, and the ark of thy sanctification.\n"
	"Let thy Priests be clothed with justice: & let thy saints rejoice.\n"
	"For David thy servant's sake, turn not away the face of thy Christ.\n"
	"Our Lord hath sworn truth to David, and he will not disappoint it: Of the fruit of thy womb I will set upon thy seat.\n"
	"If thy children shall keep my testament, and these my testimonies which I will teach them: Their children also even for ever, shall sit upon thy seat.\n"
	"Because our Lord hath chosen Sion: he hath chosen it for an habitation to himself.\n"
	"This is my rest for ever and ever: here will I dwell because I have chosen it.\n"
	"Blessing I will bless her widow: her poor I will fill with breads.\n"
	"Her Priests I will clothe with salvation: and her saints shall rejoice with joyfulness.\n"
	"Thither will I bring forth a horn to David, I have prepared a lamp to my Christ.\n"
	"His enemies I will clothe with confusion: but upon him shall my sanctification flourish.";