const char* chap652 = "Unto the end, a Psalm of David. Lord thou hast proved me, and hast known me:\n"
	"thou hast known my sitting down, and my rising up.\n"
	"Thou hast understood my cogitations far off: my path, and my cord thou hast searched out.\n"
	"And thou hast foreseen all my ways: because there is not a word in my tongue.\n"
	"Behold, o Lord, thou hast known all the last things, & them of old: thou hast formed me, and hast put thy hand upon me.\n"
	"Thy knowledge is become marvelous of me: it is made great, and I cannot reach to it.\n"
	"Whither shall I go from thy spirit? And whither shall I fly from thy face?\n"
	"If I shall ascend into heaven, thou art there: if I descend into hell, thou art present.\n"
	"If I shall take my wings early, and dwell in the extreme parts of the sea.\n"
	"Certes thither also shall thy hand conduct me: and thy right hand shall hold me.\n"
	"And I said: Perhaps darkness shall tread over me: and the night is mine illumination in my delights.\n"
	"For darkness shall not be darkened from thee, and the night shall be lightened as the day: as the darkness thereof, so also the light thereof.\n"
	"Because thou hast possessed my reins: thou hast received me from my mother's womb.\n"
	"I will confess to thee, because thou art terribly magnified: thy works are marvelous, & my soul knoweth exceedingly.\n"
	"My bone is not hid from thee, which thou madest in secret: and my substance in the lower parts of the earth.\n"
	"Mine imperfection thine eyes have seen, & in thy book all shall be written: days shall be formed, & no man in them.\n"
	"But to me thy friends, o God, are become honourable exceedingly: their principality is exceedingly strengthened.\n"
	"I will number them, and they shall be multiplied above the sand: I rose up and I am yet with thee.\n"
	"If thou shalt kill sinners, o God: ye men of blood depart from me.\n"
	"Because you say in thought: they shall receive thy cities in vain.\n"
	"Did not I hate them that hate thee, o Lord: and pined away because of thine enemies?\n"
	"with perfect hatred did I hate them: they are become enemies to me.\n"
	"Prove me, o God, and know my heart: examine me, and know my paths.\n"
	"And see, if the way of iniquity be in me: and conduct me in the everlasting way.";