const char* chap656 = "A Psalm of David, when Absalom his son persecuted him. Lord hear my prayer: with thine ears receive my petition in thy truth: hear me in thy justice.\n"
	"And enter not into judgment with thy servant: because no man living shall be justified in thy sight.\n"
	"Because the enemy hath persecuted my soul: he hath humbled my life in the earth. He hath set me in obscure places as the dead of the world:\n"
	"and my spirit is in anguish upon me, within me my heart is troubled.\n"
	"I was mindful of old days, I have meditated in all thy works: in the facts of thy hands did I meditate.\n"
	"I have stretched forth my hands to thee: my soul is as earth without water unto thee.\n"
	"Hear me quickly, o Lord: my spirit hath fainted. Turn not away thy face from me: and I shall be like to them that descend into the lake.\n"
	"Make me hear thy mercy in the morning: because I have hoped in thee. Make the way known to me, wherein I may walk: because I have lifted up my soul to thee.\n"
	"Deliver me from mine enemies, o Lord, to thee I have fled:\n"
	"teach me to do thy will, because thou art my God. Thy good spirit will conduct me into the right way:\n"
	"for thy name sake, o Lord, thou wilt quicken me in thine equity. Thou wilt bring forth my soul out of tribulation:\n"
	"and in thy mercy thou wilt destroy mine enemies. And thou wilt destroy all that afflict my soul: because I am thy servant.";