const char* chap658 = "Praising, to David himself. I will exalt thee my God the King: and I will bless thy name for ever and for ever.\n"
	"Every day will I bless thee: and will praise thy name for ever, and for ever and ever.\n"
	"Great is our Lord and exceeding laudable, and of his greatness there is no end.\n"
	"Generation and generation shall praise thy works: and they shall pronounce thy power.\n"
	"They shall speak the magnificence of the glory of thy holiness: and shall tell thy marvelous works.\n"
	"And they shall tell the force of thy terrible things: and shall declare thy greatness:\n"
	"They shall utter the memory of the aboundance of thy sweetness: and in thy justice they shall rejoice.\n"
	"Our Lord is pitiful and merciful: patient and very merciful.\n"
	"Our Lord is sweet to all: and his commiserations are over all his works.\n"
	"Let all thy works, o Lord, confess to thee: and let thy Saints bless thee.\n"
	"They shall tell the glory of thy kingdom: and shall speak thy might.\n"
	"That they may make thy might known to the children of men: and the glory of the magnificence of thy kingdom.\n"
	"Thy kingdom is a kingdom of all worlds: and thy dominion in all generation and generation. Our Lord is faithful in all his words, and holy in all his works.\n"
	"Our Lord lifteth up all that fall: and setteth up all that are bruised.\n"
	"The eyes of all hope in thee, o Lord: and thou givest their meat in time convenient.\n"
	"Thou openest thy hand: and fillest every living creature with blessing.\n"
	"Our Lord is just in all his ways: and holy in all his works.\n"
	"Our Lord is near to all that invocate him: to all that invocate him in truth.\n"
	"He will do the will of them that fear him, and will hear their prayer, and save them.\n"
	"Our Lord keepeth all that love him: and he will destroy all sinners.\n"
	"My mouth shall speak the praise of our Lord: and let all flesh bless his holy name for ever, and for ever and ever.";