const char* chap665 = "The Parables of Salomon, the son of David, king of Israel.\n"
	"To know wisdom, and discipline:\n"
	"to understand the words of prudence: and to receive instruction of doctrine, justice, and judgment, and equity:\n"
	"that subtility may be given to little ones, knowledge and understanding to the youngman.\n"
	"the wise man hearing shall be wise: and he that understandeth shall possess governments.\n"
	"He shall understand a parable, and interpretation, the words of the wise, and their dark sayings.\n"
	"The fear of our Lord is the beginning of wisdom. Fools despise wisdom and doctrine.\n"
	"My son, hear the discipline of thy father, and leave not the law of thy mother:\n"
	"that grace may be added to thy head, and a chain of gold to thy neck.\n"
	"My son, if sinners shall entice thee, condescend not to them.\n"
	"If they shall say: Come with us, let us lie in wait for blood, let us hide snares against the innocent without cause:\n"
	"let us swallow him alive as hell, and whole as one descending into the lake.\n"
	"We shall find all precious substance, we shall fill our house with spoils.\n"
	"Cast in thy lot with us, let there be one purse of us all.\n"
	"My son, walk not with them, stay thy foot from their paths.\n"
	"For their feet run to evil, and make haste to shed blood.\n"
	"But a net is cast in vain before the eyes of them that have wings.\n"
	"Themselves also lie in wait against their own blood, & practise deceits against their own souls.\n"
	"So the paths of every covetous man, take violently the souls of the possessors.\n"
	"Wisdom preacheth abroad, she giveth her voice in the streets.\n"
	"In the head of multitudes she cryeth, in the doors of the gates of the city she uttereth her words, saying:\n"
	"O children how long do you love infancy, and fools covet those things, which are hurtful to themselves, and the unwise hate knowledge?\n"
	"Turn ye at my correption: behold I will utter my spirit to you, and will shew you my words.\n"
	"Because I called, and you refused: I stretched out my hand, and there was none that regarded.\n"
	"You have despised all my counsel, and have neglected my reprehensions.\n"
	"I also will laugh in your destruction, and will scorn, when that shall come to you, which you feared.\n"
	"When sudden calamity shall fall on you, and destruction as a tempest shall be at hand: when tribulation and distress shall come upon you:\n"
	"Then shall they invocate me, and I will not hear: in the morning shall they arise, and shall not find me:\n"
	"for that they have hated discipline, and not received the fear of our Lord,\n"
	"nor consented to my counsel, & detracted from all my correption.\n"
	"They shall eat therefore the fruits of their way, and shall be filled with their own counsels.\n"
	"The aversion of little ones shall kill them, and the prosperity of fools shall destroy them.\n"
	"But he that shall hear me, shall rest without terror, and shall enjoy aboundance, fear of evils being taken away.";