const char* chap666 = "My son, if thou wilt receive my words, and wilt hide my commandments with thee,\n"
	"that thine ear may hear wisdom: incline thine heart to know prudence.\n"
	"For if thou shalt call for wisdom, and incline thine heart to prudence:\n"
	"If thou shalt seek her as money, and as treasures shalt dig her up:\n"
	"then shalt thou understand the fear of our Lord, and shalt find the knowledge of God.\n"
	"Because our Lord giveth wisdom: and out of his mouth prudence and knowledge.\n"
	"He will keep the salvation of the righteous, & protect them that walk simply.\n"
	"Keeping the paths of justice, & guarding the ways of Saints.\n"
	"Then shalt thou understand justice, and judgment, and equity, and every good path.\n"
	"If wisdom shall enter into thy heart, and knowledge please thy soul:\n"
	"counsel shall keep thee, and prudence shall preserve thee,\n"
	"that thou mayst be delivered from the evil way, and from the man that speaketh perverse things:\n"
	"who leave the right way, and walk by dark ways:\n"
	"who are glad when they have done evil, and rejoice in most wicked things:\n"
	"whose ways are perverse, and their steps infamous.\n"
	"That thou mayst be delivered from the strange woman, and from the foreigner, which mollifieth her words,\n"
	"forsaketh the guide of her youth,\n"
	"and hath forgotten the covenant of her God. For her house is bowed down to death, and her paths to hell.\n"
	"All that go in unto her, shall not return^ neither shall they apprehend the paths of life.\n"
	"That thou mayst walk in a good way: and mayst keep the paths of the just.\n"
	"For they that are right, shall dwell in the earth, and the simple shall continue in it.\n"
	"But the impious shall be destroyed from the earth: and they that do unjustly shall be taken away from it.";