const char* chap674 = "A wise son maketh the father glad: but a foolish son is the sorrow of his mother.\n"
	"The treasures of impiety shall profit nothing: but justice shall deliver from death.\n"
	"Our Lord will not afflict with famine the soul of the just, and the deceitful practices of the impious he will overthrow.\n"
	"The slothful hand hath wrought poverty: the hand of the strong getteth riches. Who so trusteth to lies feedeth the winds: and the self-same man followeth the flying birds.\n"
	"He that gathereth in the harvest, is a wise son: but he that snorteth in summer, is the son of confusion.\n"
	"The blessing of our Lord is upon the head of the just: but iniquity covereth the mouth of the impious.\n"
	"The memory of the just is with praises: and the name of the impious shall rot.\n"
	"The wise of heart shall receive precepts: a fool is beaten with lips.\n"
	"He that walketh plainly, walketh confidently: but he that depraveth his ways, shall be manifest.\n"
	"He that winketh with the eye, shall give sorrow: and the fool in lips shall be beaten.\n"
	"A vein of life, the mouth of the just: and the mouth of the impious covereth iniquity.\n"
	"Hatred raiseth brawls: and charity covereth all sins.\n"
	"In the lips of the wise wisdom is found: and a rod on his back that lacketh wit.\n"
	"Wise men hide knowledge: but the mouth of the fool is next to confusion.\n"
	"The substance of a rich man, is a city of his strength: the fear of the poor their poverty.\n"
	"The work of the just unto life: but the fruit of the impious unto sin.\n"
	"The way of life, to him that keepeth discipline: but he that forsaketh reprehensions, erreth.\n"
	"Lying lips hide hatred: he that uttereth contumely is unwise.\n"
	"In much talk there shall not want sin: but he that moderateth his lips is most wise.\n"
	"The tongue of the just, is chosen silver: but the heart of the impious is nothing worth.\n"
	"The lips of the just teach very many: but they that are untaught, shall die in the penury of wit.\n"
	"The blessing of our Lord maketh men rich: neither shall affliction be joined to them.\n"
	"A fool worketh mischief as it were by laughter: but wisdom is prudence to a man.\n"
	"That which the impious feareth, shall come upon him: to the just their desire shall be given.\n"
	"As a tempest passing^ the impious shall not be: but the just as an everlasting foundation.\n"
	"As vinegar to the teeth, and smoke to the eyes, so a sluggard to them that sent him.\n"
	"The fear of our Lord shall add days: and the years of the impious shall be shortened.\n"
	"The expectation of the just is joy: but the hope of the impious shall perish.\n"
	"The strength of the simple^ the way of our Lord: and fear is to them that work evil.\n"
	"The just for ever shall not be moved: but the impious shall not dwell on the earth.\n"
	"The mouth of the just shall bring forth wisdom: the tongue of the froward shall perish.\n"
	"The lips of the just consider grateful things: and the mouth of the impious perverse things.";