const char* chap686 = "Better is a good name, than much riches: above silver and gold, good grace.\n"
	"The rich and poor have met one another: our Lord is the maker of both.\n"
	"The subtle saw evil, and hid himself: the innocent passed by, and was afflicted with damage.\n"
	"The end of modesty the fear of our Lord, riches and glory and life.\n"
	"Armour and swords in the way of the perverse: but the keeper of his own soul departeth far from them.\n"
	"It is a proverb: A youngman according to his way, when he is old will not depart from it.\n"
	"The richman ruleth over the poor: and he that borroweth is the servant of him that lendeth.\n"
	"He that soweth iniquity, shall reap evils, and with the rod of his wrath, he shall be consumed.\n"
	"He that is prone to mercy shall be blessed: for of his breads he hath given to the poor. He that giveth gifts shall purchase victory and honour: but he that receiveth taketh away the soul of the giver.\n"
	"Cast out the scorner, and brawling shall go forth with him, and cause shall cease and contumelies.\n"
	"He that loveth cleanness of heart, for the grace of his lips, shall have the king his friend.\n"
	"The eyes of our Lord keep knowledge: and the words of the just are supplanted.\n"
	"The slothful saith: A lion is without, in the midst of the streets I am to be slain.\n"
	"A deep pit the mouth of a strange woman: he with whom our Lord is angry, shall fall into it.\n"
	"Folly is tied together in the heart of a child, and the rod of discipline shall drive it away.\n"
	"He that doth calumniate the poor to increase his riches, himself shall give to a richer, and shall be in need.\n"
	"Incline thine ear, and hear the words of wisemen: and set thy heart to my doctrine:\n"
	"which shall be beautiful for thee, when thou shalt keep it in thy belly, and it shall flow in thy lips.\n"
	"That thy confidence may be in our Lord, wherefore I have shewed also it to thee this day.\n"
	"Behold I have described it to thee three manner of ways: in cogitations and knowledge:\n"
	"that I might shew thee the stability, and the words of truth, out of these to answer them that sent thee.\n"
	"Do not violence to the poor, because he is poor: neither oppress the needy in the gate:\n"
	"because our Lord will judge his cause, and will pierce them, that have pierced his soul.\n"
	"Be not friend to an angry man, nor walk with a furious man:\n"
	"lest perhaps thou learn his paths, and take scandal to thy soul.\n"
	"Be not with them that stick down their hands, and that offer themselves sureties for debts:\n"
	"for if thou have not wherewith to restore, what cause is there that he should take the covering from thy bed?\n"
	"Transgress not the ancient bounds, which thy fathers have put.\n"
	"Hast thou seen a man quick in his work? He shall stand before kings, neither shall he be before the unnoble.";