const char* chap691 = "Boast not for tomorrow, being ignorant what the day to come may bring forth.\n"
	"Let another praise thee, and not thine own mouth: a stranger and not thine own lips.\n"
	"A stone is heavy, and sand weighty: but the anger of a fool is heavier than both.\n"
	"Anger hath no mercy, nor fury breaking forth: and the violence of a moved spirit who can sustain?\n"
	"Better is manifest correption, than love hidden.\n"
	"Better are the wounds of him that loveth, than the fraudulent kisses of him that hateth.\n"
	"A soul that is full shall tread upon the honeycomb: and a soul that is hungry shall take bitter also for sweet.\n"
	"As a bird fleeting from her nest, so a man that forsaketh his place.\n"
	"The heart is delighted with ointment and diverse odours: and with the good counsels of a friend the soul is sweetened.\n"
	"Thy friend, and thy father's friend do not leave: and go not into thy brother's house in the day of thine affliction. Better is a neighbour near than a brother far off.\n"
	"Study wisdom my son, & make my heart joyful, that thou mayst make answer to the upbraider.\n"
	"The subtle man seeing evil, hideth himself: little ones passing through have sustained evil detriments.\n"
	"Take his garment that hath been surety for a stranger: and for aliens take from him a pledge.\n"
	"He that blesseth his neighbour with a loud voice, rising in the night, he shall be like him that curseth.\n"
	"Roofs dropping through in the day of cold, and a brawling woman are compared together:\n"
	"He that retaineth her, as he that should hold the wind, and shall call it the oil of his right hand.\n"
	"Iron is sharpened with iron, and a man sharpeneth the face of his friend.\n"
	"He that keepeth the figtree, shall eat the fruits thereof: and he that is the keeper of his master, shall be glorified.\n"
	"As in waters the countenance of them that look therein shineth, so the hearts of men are manifest to the prudent.\n"
	"Hell and perdition are never filled: in like manner also the eyes of men are unsatiable.\n"
	"As silver is tried in the forge, and gold in the furnace: so a man is proved by the mouth of him that praiseth. The heart of the wicked seeketh after evils, but the righteous heart seeketh after knowledge.\n"
	"If thou shall bray a fool in a mortar, as when a pestle striketh upon ptisane, his folly shall not be taken from him.\n"
	"Know diligently the countenance of thy cattle, and consider thy flocks:\n"
	"For thou shalt not have power always: but a crown shall be given into generation and generation.\n"
	"The meadows are open, and the green herbs have appeared, and the grass is gathered out of the mountains.\n"
	"Lambs for thy garment: and kids the price of the field.\n"
	"Let the milk of the goats suffice thee for thy meats, and for the necessities of thy house: and for victual to thy hand-maids.";