const char* chap695 = "The words of Lamuel the king. The vision wherewith his mother instructed him.\n"
	"What o my beloved, what o the beloved of my womb, what o beloved of my vows?\n"
	"Give not thy substance to women, & thy riches to destroy kings.\n"
	"Give not to kings, o Lamuel, give not wine to kings: because there is no secret where drunkenness reigneth,\n"
	"& lest perhaps they drink, & forget judgments, & change the cause of the children of the poor.\n"
	"Give strong drink to them that be sad, and wine unto them that are of a pensive mind:\n"
	"let them drink, and forget their poverty, and not remember their sorrow any more.\n"
	"Open thy mouth to the dumb, & to the causes of all the children that pass:\n"
	"open thy mouth, decree that which is just, & judge the needy & poor.\n"
	"A valiant woman who shall find? Far, and from the utmost borders is the price of her.\n"
	"The heart of her husband trusteth in her, and he shall not need spoils.\n"
	"She shall render good, and not evil, all the days of her life.\n"
	"She hath sought wool and flax, and hath wrought by the counsel of her hands.\n"
	"She is become as a merchant's ship, bringing her bread from far.\n"
	"And she hath risen in the night, and given prey to her household, and meats to her handmaids.\n"
	"She hath viewed a field, and bought it, of the fruit of her hands she hath planted a vineyard.\n"
	"She hath girded her loins with strength, and hath strengthened her arm.\n"
	"She hath tasted, and seen that her traffic is good: her lamp shall not be extinguished in the night.\n"
	"She hath put her hand to strong things, and her fingers have taken hold of the spindle.\n"
	"She hath opened her hand to the needy, and stretched out her palms to the poor.\n"
	"She shall not fear for her house in the colds of snow: for all her household are clothed with double.\n"
	"Tapestry clothing she hath made to herself: silk and purple is her garment.\n"
	"Her husband is noble in the gates, when he shall sit with the senators of the land.\n"
	"She made sindon, and sold it, and delivered a girdle to the Chananeite.\n"
	"Strength and beauty is her garment, and she shall laugh in the later day.\n"
	"She hath opened her mouth to wisdom, and the law of clemency is in her tongue.\n"
	"She hath considered the paths of her house, and hath not eaten her bread idle.\n"
	"Her children arose, and commended her to be most blessed: her husband, and he praised her.\n"
	"Many daughters have gathered together riches: thou hast passed them all.\n"
	"Grace is deceitful, and beauty is vain: the woman that feareth our Lord shall be praised.\n"
	"Give ye to her of the fruit of her hands, and let her works praise her in the gates.";