const char* chap707 = "Remember thy creator in the days of thy youth, before the time of affliction come, & the years approach, of which thou mayst say: They please me not:\n"
	"before the sun, and light, and moon, and stars be dark, and the clouds return after the rain:\n"
	"when the keepers of the house shall be moved, and the strongest men shall stagger, and the grinders shall be idle in a small number: and they shall wax dark that look through the holes:\n"
	"and they shall shut the doors in the street, at the baseness of the grinder's voice, and they shall rise up at the voice of the bird, and all the daughters of song shall be deaf.\n"
	"The high things also shall fear, and they shall be afraid in the way, the almond tree shall flourish, the locust shall be fatted, and the caper tree shall be destroyed: because man shall go into the house of his eternity, and the mourners shall go round about in the street.\n"
	"Before the silver cord be broken, and the golden head-band recur, and the water-pot be broken upon the fountain, and the wheel be broken upon the cistern,\n"
	"and the dust return into his earth, from whence it was, and the spirit return to God, who gave it.\n"
	"Vanity of vanities, said Ecclesiastes, and all things vanity.\n"
	"And whereas Ecclesiastes was most wise, he taught the people, and declared the things that he had done: and searching forth made many parables.\n"
	"He sought profitable words, and wrote words most right, and full of truth.\n"
	"The words of wisemen are as pricks, and as nails deeply strucken in, which by the counsel of masters are given of one pastor.\n"
	"More than these my son require not. Of making many books there is no end: and often meditation is affliction of the flesh.\n"
	"Let us all hear together the end of speaking. Fear God, and observe his commandments: for this is every man:\n"
	"and all things that are done, God will bring into judgement for every error, whether it be good or evil.";