const char* chap715 = "Who shall give to me thee my brother, sucking the breasts of my mother, that I may find thee without, and kiss thee, and now no man despise me?\n"
	"I will take hold of thee, and will bring thee into my mother's house: there thou shalt teach me, and I will give thee a cup of spiced wine, and new wine of my pomegranates.\n"
	"His left hand under my head, and his right hand shall embrace me.\n"
	"I adjure you o daughters of Jerusalem, that you raise not up, nor make the beloved to awake till herself will.\n"
	"Who is this, that cometh up from the desert, flowing with delights, leaning upon her beloved? Under the apple-tree I raised thee up: there thy mother was corrupted, there she was deflowered that bare thee.\n"
	"Put me as a seal upon thy heart, as a seal upon thine arm: because love is strong as death: jealousy is hard as hell, the lamps thereof lamps of fire and flames.\n"
	"Many waters cannot quench charity, neither shall floods overwhelm it: if a man shall give all the substance of his house for love, as nothing he shall despise it.\n"
	"Our sister is little, and hath no breasts. What shall we do to our sister in the day when she is to be spoken unto?\n"
	"If she be a wall, let us build upon it bulwarks of silver: if she be a door, let us join it together with boards of cedar.\n"
	"I am a wall: and my breasts are as a tower, since I was made before him as one finding peace.\n"
	"The peace-maker had a vineyard, in that which hath peoples: he delivered the same to keepers, a man bringeth for the fruit thereof a thousand pieces of silver.\n"
	"My vineyard is before me. A thousand are thy peace-makers, and two hundred for them, that keep the fruits thereof.\n"
	"Thou dwellest in the gardens, the friends do harken: make me hear thy voice.\n"
	"Fly, o my beloved, and be like to the roe, and to the fawn of harts upon the mountains of aromatical spices.";