const char* chap721 = "Wisdom is better than strength: and a wise man than a strong.\n"
	"Hear therefore ye kings, & understand, learn ye judges of the ends of the earth.\n"
	"Give ear ye that rule multitudes, and that please yourselves in multitudes of nations:\n"
	"because the power is given you of our Lord, and strength by the Highest, who will examine your works, and search your cogitations:\n"
	"because when you were the ministers of his Kingdom, you judged not rightly, nor kept the law of justice, nor have walked according to the will of God.\n"
	"Horribly and quickly will he appear to you: because most severe judgement shall be done on them, that bear rule.\n"
	"For to the little one mercy is granted: but the mighty shall mightily suffer torments.\n"
	"For God will not except any man's person, neither will fear the greatness of any man: because he made the little and the great, & he hath equally care of all.\n"
	"But to the stronger more strong torment is imminent.\n"
	"To you therefore o kings are these my words, that you may learn wisdom, and not fall.\n"
	"For they that have kept just things justly, shall be justified: and they that have learned these things, shall find what they may answer.\n"
	"Covet ye therefore my words, and love them, and you shall have discipline.\n"
	"Wisdom is clear, and such as never fadeth, and is easily seen of them that love her, and is found of them that seek her.\n"
	"She preventeth them that covet her, that she first may shew herself unto them.\n"
	"He that awaketh early to her, shall not labour: for he shall find her sitting at her doors.\n"
	"To think therefore of her, is perfect understanding: and he that watcheth for her, shall quickly be secure.\n"
	"Because she goeth about seeking them that be worthy of her, and in the ways she will shew herself to them cheerfully, and in all providence she will meet them.\n"
	"For the beginning of her is the most true desire of discipline.\n"
	"The care therefore of discipline, is love: and love is keeping of her laws: and the keeping of the laws, is the consummation of incorruption:\n"
	"and incorruption maketh to be next to God.\n"
	"Therefore the desire of wisdom leadeth to the everlasting Kingdom.\n"
	"If therefore you be delighted with thrones, and with sceptres, o ye kings of the people, love wisdom, that you may reign for ever.\n"
	"Love the light of wisdom all ye that bear rule over peoples.\n"
	"But what wisdom is, and how she was made, I will declare: and I will not hide from you the mysteries of God, but from the beginning of her nativity I will search out, and set the knowledge of her into light, and will not let pass the truth:\n"
	"neither will I go with pining envy: because such a man shall not be partaker of wisdom.\n"
	"But the multitude of the wise is the health of the round world: and a wise king is the stability of the people.\n"
	"Therefore take ye discipline by my words, and it shall profit you.";