const char* chap725 = "She kept him, that was first made of God father of the world, when he was created alone,\n"
	"and she brought him out of his sin, and gave him power to contain all things.\n"
	"After the unjust departed in his anger from her, by the fury of brother's manslaughter he perished.\n"
	"For whose cause, when water destroyed the earth, wisdom healed it again, governing the just by contemptible wood.\n"
	"She even in the consent of wickedness, when the nations had confederated themselves, knew the just, and preserved him without blame to God, and in his son's mercy kept the strong.\n"
	"She delivered the just, flying from the impious that perished, when the fire came down upon Pentapolis:\n"
	"to whom for a witness of their wickedness the desert land standeth smoking, and trees having fruits at uncertain season; and the memory of an incredulous soul a standing pillar of salt.\n"
	"For pretermitting wisdom they did not only slip in this, that they were ignorant of good things, but they left also unto men a memory of their foolishness, that in those things, in which they sinned in, they could not be hid neither.\n"
	"But wisdom hath delivered them that observe her from sorrows.\n"
	"And the just flying his brother's wrath, she conducted by the right ways, and shewed him the kingdom of God, and gave him the knowledge of the holy, did honest him in labours, and accomplished his labours.\n"
	"In the fraud of the circumventers of him she was present with him, and made him honourable.\n"
	"She kept him from the enemies, and from seducers she defended him, and gave him a strong fight, that he might overcome, and know that wisdom is mightier than all.\n"
	"She forsook not the just being sold, but delivered him from sinners: and she went down with him into the pit,\n"
	"and in bands left him not, till she brought him the sceptre of a Kingdom, and might against them that oppressed him: and shewed them to be liars, that spotted him, and gave him eternal glory.\n"
	"The just people, and seed without blame she delivered from the nations, that oppressed them.\n"
	"She entered into the soul of the servant of God, and stood against dreadful kings in wonders and signs.\n"
	"And she rendered to the just the hope of their labours, and conducted them in a marvelous way: and she was unto them for a cover in the day, and for the light of stars by night:\n"
	"and she transported them through the Red sea, and carried them over through a great water.\n"
	"But their enemies she drowned in the sea, and from the depth of hell she brought them out. Therefore the just took the spoils of the impious,\n"
	"and they sang thy holy name o Lord, and thy victorious hand they praised together:\n"
	"because wisdom hath opened the mouth of the dumb, and the tongues of infants she hath made eloquent.";