const char* chap733 = "But to thy saints there was very great light, and their voice indeed they heard, but figure they saw not. And because themselves also did not suffer by the same things, they magnified thee:\n"
	"and they that before had been hurt, because they were not hurt, gave thanks: and that there might be a difference, they asked a gift.\n"
	"For the which cause they had a burning pillar of fire for a guide of the unknown way, and thou gavest them the sun without hurt of a good harbour.\n"
	"They indeed worthy to lack light, and to suffer the prison of darkness, which kept thy children shut up, by whom the uncorrupt light of the law began to be given to the world.\n"
	"When they decreed to kill the infants of the just: and one child being laid forth, and delivered, thou to the reproving of them, didst take away a multitude of children, and destroyedst them together in the mighty water.\n"
	"For that night was known before of our fathers, that they knowing indeed what oaths they had credited, might be of better comfort.\n"
	"And by thy people indeed the health of the just was received, but destruction by the unjust.\n"
	"For as thou didst hurt the adversaries: so us also thou didst magnify, provoking us.\n"
	"For the just children of the good sacrificed secretly, and disposed the law of justice in concord: that the just should receive both good & evil alike, singing now the praises of the fathers.\n"
	"But there sounded a disagreeing voice of the enemies, and a lamentable mourning was heard for the bewailed infants.\n"
	"And the servant with the master was afflicted with like punishment, and a man of the vulgar sort suffered the like things to the king.\n"
	"All therefore alike by one name of death had dead ones innumerable. For neither did the living suffice to bury them: because in one moment, that which was the nobler nation of them, was destroyed.\n"
	"For concerning all things being incredulous because of the enchantments, but then first when there was destruction of the first-begotten, they promised to be the people of God.\n"
	"For when quiet silence contained all things, and the night was in the mid-way of her course,\n"
	"thy omnipotent word sallying out of heaven from the royal seats, lighted as a severe conqueror upon the midst of the land of destruction,\n"
	"a sharp sword carrying thy unfeigned commandment, and standing filled all with death, and reached even to heaven standing on the earth.\n"
	"Then incontinent the visions of naughty dreams troubled them, and fears unlooked for came upon them.\n"
	"And one here^ another there cast forth half alive, shewed for what cause of death he died.\n"
	"For the visions that troubled them, forewarned these things, that they might not perish as ignorant why they suffered evils.\n"
	"But then there touched the just also a tentation of death, and a disturbance of the multitude was made in the wilderness: but thy wrath did not long continue.\n"
	"For a man without blame hastening to pray for the people, bringing forth the shield of his ministry, prayer, and by incense alleging supplication, resisted the wrath, and made an end of the necessity, shewing that he is thy servant.\n"
	"And he overcame the multitudes, not in strength of body, nor with might of armour, but with a word subdued he him that vexed him, rehearsing the oaths of the parents, and the testament.\n"
	"For when they were now fallen dead by heaps one upon another, he stood between, and cut off the violence, and separated that way which leadeth to the living.\n"
	"For in the vesture down to the foot, which he had, was all the world: and the glorious things of the fathers were graven in the four jewels of stones, & thy magnificence was written in the diadem of his head.\n"
	"And to these he that destroyed gave peace, & these did he fear: for the proof only of wrath was sufficient.";