const char* chap755 = "Son hast thou sinned? Do so no more: but for the old also pray that they may be forgiven thee.\n"
	"As from the face of a serpent fly from sins: and if thou approach to them they will receive thee.\n"
	"The teeth of a lion the teeth thereof, killing the souls of men.\n"
	"All iniquity is as a two-edged sword, there is no remedy for the wound thereof.\n"
	"Brawling and injuries shall bring the substance to nothing: and the house that is very rich, shall be made nothing by pride: so the substance of the proud shall be rooted out.\n"
	"The prayer of the poor out of the mouth shall come to his ears, and judgement shall come for him speedily.\n"
	"He that hateth chastisement, is the trace of a sinner: and he that feareth God, will turn to his own heart.\n"
	"The mighty in a bold tongue is known a far off, and a wiseman knoweth himself to fall by him.\n"
	"He that buildeth his house at other men's charges, is as he that gathereth his stones in the winter.\n"
	"The synagogue of sinners is as tow gathered together, and their consummation a flame of fire.\n"
	"The way of sinners is paved with stones, & in their end, hell, & darkness, and pains.\n"
	"He that keepeth justice, shall contain the understanding thereof.\n"
	"The consummation of the fear of God wisdom and understanding.\n"
	"He shall not be taught, that is not wise in good.\n"
	"But there is wisdom that aboundeth in evil: and there is no understanding where bitterness is.\n"
	"The knowledge of the wise shall abound as an inundation, and his counsel is permanent as a fountain of life.\n"
	"The heart of a fool is as a broken vessel, and all wisdom it shall not hold.\n"
	"A man of knowledge will praise what soever wise word he shall hear, and will apply it to himself: the riotous man hath heard it, and it shall displease him, and he will cast it behind his back.\n"
	"The narration of a fool is as a burden in the way: for in the lips of the wise shall grace be found.\n"
	"The mouth of the prudent is sought in the Church, and they will think upon his words in their hearts.\n"
	"As a house destroyed, so is wisdom to a fool: & the knowledge of the unwise inexplicable words.\n"
	"Fetters on the feet, doctrine to a fool, and as manacles upon the right hand.\n"
	"A fool in laughter exalteth his voice, but a wise man will scarce laugh secretly.\n"
	"Doctrine to the prudent is a golden ornament, and as it were a bracelet on the right arm.\n"
	"The foot of a fool goeth easily into his neighbour's house: & a cunning man will be abashed at the person of the mighty.\n"
	"A fool will look from the window into the house: but he nurtured will stand without.\n"
	"It is the folly of a man to harken by the door: and a wiseman will be grieved with the contumely.\n"
	"The lips of the unwise shall tell foolish things: but the words of the wise shall be pondered in balance.\n"
	"The heart of fools is in their mouth: and the mouth of wisemen is in their heart.\n"
	"Whilst the impious curseth the devil, he curseth his own soul.\n"
	"The whisperer shall defile his soul, and shall be hated in all: and he that shall abide with him, shall be odious: the still man and wise shall be honoured.";