const char* chap768 = "Vain hope & lying is to a foolish man: & dreams extol the unwise.\n"
	"As he that apprehendeth a shadow, and pursueth the wind: so is he also that attendeth to lying visions.\n"
	"According to this is the vision of dreams: as a man's similitude before the face of a man.\n"
	"Of the unclean what shall be made clean? And of a liar what truth shall be said?\n"
	"Divination of error, and lying soothsayings, and the dreams of them that do evil, are vanity.\n"
	"And as a woman that travaileth, thy heart suffereth phantasies: unless it be a vision sent forth from the Highest, set not thy heart upon them.\n"
	"For dreams have made many to err, and they that hoped in them have failed.\n"
	"The word of the law shall be fulfilled without lying, and wisdom in the mouth of the faithful shall be made plain.\n"
	"He that hath not been proved, what knoweth he? A man expert in many things, shall think many things: and he that hath learned many things, shall declare understanding.\n"
	"He that is not tried, knoweth few things: and he that hath been in many things, multiplieth wickedness.\n"
	"He that hath not been proved, what manner of things knoweth he? He that is deceived, shall abound with wickedness.\n"
	"I have seen many things in wandering to and fro, and very many fashions of words.\n"
	"Sometimes I have been in danger unto death for these things, and I was delivered by the grace of God.\n"
	"The spirit of them that fear God is sought, & at his sight shall be blessed.\n"
	"For their hope is on him that saveth them, and the eyes of God upon them that love him.\n"
	"He that feareth our Lord shall tremble at nothing, and shall not dread: because he is his hope.\n"
	"His soul is blessed that feareth our Lord.\n"
	"To whom doth he look, and who is his strength?\n"
	"The eyes of our Lord are upon them that fear him, a protector of might, a stay of strength, a cover from the heat, and shadow for the noon time,\n"
	"a saving from offence, and help from falling, exalting the soul, and illuminating the eyes, giving health, and life, and blessing.\n"
	"The oblation of him that immolateth of an unjust thing is spotted, and the scornings of the unjust are not acceptable.\n"
	"Our Lord is only theirs that expect him in the way of truth and justice.\n"
	"The Highest alloweth not the gifts of the wicked: neither hath he regard to the oblations of the unjust, neither will he be made propitious for sins by the multitude of their sacrifices.\n"
	"He that offereth sacrifice of poor men's substance, is as he that sacrificeth the son in the presence of his father.\n"
	"The bread of the needy, is the life of the poor: he that defraudeth it, is a man of blood.\n"
	"He that taketh away bread in sweat, is as he that killeth his neighbour.\n"
	"He that sheddeth blood, and that defraudeth the hired man, are brethren.\n"
	"One building, and another destroying: what profit have they but the labour?\n"
	"One praying, and another cursing: whether's voice will God hear?\n"
	"He that is washed from the dead, and toucheth him again, what doth his washing profit?\n"
	"so a man that fasteth in his sins: and doing the same again, what doth he profit in humbling himself? Who will hear his prayer?";