const char* chap769 = "He that keepeth the law, multiplieth oblation.\n"
	"It is an wholesome sacrifice to attend to the commandments, and to depart from all iniquity.\n"
	"And to offer propitiation by sacrifice for injustices, and to retire from injustice is prayer for sins.\n"
	"He who offereth the flour of wheat, shall give thanks: and he that is merciful offereth sacrifice.\n"
	"To depart from iniquity is a thing that pleaseth our Lord well, and to depart from injustice is an entreating for sins.\n"
	"Thou shalt not appear before the sight of our Lord empty.\n"
	"For all these things are done because of the commandment of God.\n"
	"The oblation of the just maketh a fat altar, and is an odour of sweetness in the sight of the Highest.\n"
	"The sacrifice of the just is acceptable, and our Lord will not forget the memory thereof.\n"
	"Render glory to God with a good mind: and diminish not the first fruits of thine hands.\n"
	"In every gift make thy countenance cheerful, and in joyfulness sanctify thy tithes.\n"
	"Give to the Highest according to his gift, and with a good eye do according to the ability of thine hands:\n"
	"because our Lord is a rewarder, and will repay thee seven times so much.\n"
	"Offer not wicked gifts, for he will not receive them.\n"
	"And look not upon an unjust sacrifice, because our Lord is judge, and there is not with him the glory of person.\n"
	"Our Lord will not accept person against the poor, and he will hear the prayer of him that is hurt.\n"
	"He will not despise the prayers of the pupil: nor the widow, if she pour out speech of mourning.\n"
	"Do not the widow's tears run down the cheek, & her exclamation upon him that causeth them to run?\n"
	"For from the cheek they go up even to heaven, and our Lord the hearer will not be delighted in them.\n"
	"He that adoreth God in delectation, shall be received, & his petition shall approach even to the clouds.\n"
	"The prayer of him that humbleth himself, shall penetrate the clouds: and till it approach he will not be comforted: and he will not depart till the Highest behold.\n"
	"And our Lord will not be long, but will judge the just, and will do judgement: and the strongest will not have patience in them, that he may crush their back:\n"
	"and he will repay vengeance to the Gentiles, till he take away the multitude of the proud: & break the sceptres of the unjust,\n"
	"till he reward men according to their doings: and according to the works of Adam, and according to his presumption.\n"
	"till he judge the judgement of his people, and shall delight the just with his mercy:\n"
	"The mercy of God is beautiful in the time of tribulation, as a cloud of rain in the time of drought.";