const char* chap77 = "Thou shalt make also an Altar of the wood setim, which shall have five cubits in length, an as many in breadth, that is, four-square, and three cubits in height.\n"
	"And there shall be at the four corners horns of the same: and thou shalt cover it with brass.\n"
	"And thou shalt make for the uses thereof pans for to take the ashes, and tongues, and flesh-hooks, and fire pans, all the vessels thou shalt make of brass.\n"
	"And a grate in manner of a net of brass: at the four corners whereof shall be four rings of brass,\n"
	"which thou shalt put under the hearth of the Altar: and the grates shall be unto the midst of the Altar.\n"
	"Thou shalt make also two bars for the Altar of the wood setim, which thou shalt cover with plates of brass:\n"
	"and thou shalt draw them through rings, & they shall be on both sides of the Altar to carry it.\n"
	"Not massy, but empty & hollow in the inside shalt thou make it, as it was shewed thee in the Mount.\n"
	"Thou shalt make also the court of the tabernacle, in the south part whereof against the south there shall be hangings of twisted silk: one side shall hold in length an hundred cubits.\n"
	"And twenty pillars with as many feet of brass, which shall have heads with their engravings of silver.\n"
	"In like manner also on the north side there shall be in length hangings of an hundred cubits, twenty pillars, and feet of brass as many, and their heads with their engravings of silver.\n"
	"But in the breadth of the court, that looketh to the west, there shall be hangings of fifty cubits, and ten pillars, and as many feet.\n"
	"In that breadth also of the court, which looketh to the east, there shall be fifty cubits.\n"
	"In the which there shall be deputed to one side hangings of fifteen cubits, and three pillars and as many feet:\n"
	"and in the other side there shall be hangings containing fifteen cubits, three pillars, and as many feet.\n"
	"And in the entering of the court there shall be made an hanging of twenty cubits of hyacinth and purple, and scarlet twice dyed, and twisted silk, with embroidered work: it shall have four pillars, with as many feet.\n"
	"All the pillars of the court round about shall be garnished with plates of silver, silver heads, and feet of brass.\n"
	"In length the court shall occupy and hundred cubits, in breadth fifty, the height, shall be of five cubits, and it shall be made of twisted silk, and shall have feet of brass.\n"
	"All the vessels of the tabernacle for all uses and ceremonies, the pins as well of it as of the court, thou shalt make of brass.\n"
	"Command the children of Israel that they bring thee oil of the olive-trees the purest, and beaten with a pestle: that a lamp may burn always.\n"
	"in the tabernacle of the testimony, without the veil that is drawn before the testimony. And Aaron and his sons, shall place it, that it may give light before the Lord until the morning. Is shall be a perpetual observance throughout their successions before the children of Israel.";