const char* chap781 = "After these things arose Nathan the Prophet in the days of David.\n"
	"And as the fat separated from the flesh, so was David from the children of Israel.\n"
	"He played with lions as it were with lambs: and with bears he did in like manner as with lambs of sheep in his youth.\n"
	"Did not he kill the giant, & took away reproach from his nation?\n"
	"In lifting up his hand, with a stone of the sling he overthrew the boasting of Goliath:\n"
	"for he invocated our Lord the omnipotent, and he gave in his right hand, to take away the man strong in battle, and to exalt the horn of his nation.\n"
	"So in ten thousand did he glorify him, and praised him in the blessings of our Lord, in offering to him a crown of glory:\n"
	"for he destroyed the enemies on every side, and rooted out the Philisthiims the adversaries even until this present day: he brake their horn for ever.\n"
	"In every work he gave confession to the Holy one, and to the Highest, in the word of glory.\n"
	"From all his heart he praised our Lord, & loved God, that made him, and gave him might against his enemies:\n"
	"and he made singers to stand before the altar, and by their sound he made sweet tunes.\n"
	"And in the solemnities he gave honour, and adorned the times even to the end of his life, that they should praise the holy name of our Lord, and magnify the holiness of God in the morning.\n"
	"Our Lord purged his sins, and exalted his horn for ever: and he gave him a testament of the kingdom, and the seat of glory in Israel.\n"
	"After him arose a wise son, and for him did he overthrow all the might of the enemies.\n"
	"Salomon reigned in days of peace, to whom God subdued all his enemies, that he might build an house in his name, & prepare holiness for ever: as thou art instructed in thy youth.\n"
	"And thou art replenished as a river with wisdom, and thy soul discovered the earth.\n"
	"And thou didst multiply dark sayings in comparisons: thy name was bruited to the islands far off, and thou wast beloved in thy peace.\n"
	"The lands marveled at the songs and proverbs, and comparisons, and interpretations,\n"
	"and at the name of our Lord God, whose name is, God of Israel.\n"
	"Thou didst gather gold as copper, and filledst silver as lead,\n"
	"and bowedst thy thighs to women: thou hast had power on thy body.\n"
	"Thou hast made a blot in thy glory, & profaned thy seed to bring wrath to thy children, & thy folly to be kindled,\n"
	"to make the Kingdom divided, and a stubborn kingdom to reign of Ephraim.\n"
	"But God will not leave his mercy, and he will not corrupt, nor abolish his own works, neither will he destroy from the stock the nephews of his elect: and he will not corrupt the seed of him, that loveth our Lord.\n"
	"But he gave a remnant to Jacob, and to David of the same stock.\n"
	"And Salomon had an end with his fathers.\n"
	"And he left after him of his seed, the folly of the nation,\n"
	"and Roboam having little wisdom, who turned away the nation by his counsel,\n"
	"and Jeroboam the son of Nabat, who made Israel to sin, and made a way of sinning to Ephraim, and their sins did abound very many.\n"
	"They removed them away from their land very far.\n"
	"And he sought all iniquities, till there came defense unto them, and he rid them from all sins.";