const char* chap783 = "The memory of Josias is according to the confection of perfume made by the work of an apothecary.\n"
	"His remembrance shall be sweet as honey in every mouth, & as music in a banquet of wine.\n"
	"He was directed by God into the repentance of the nation, and he took away the abominations of impiety.\n"
	"And he governed his heart toward our Lord, and in the days of sinners he strengthened piety.\n"
	"Except David, and Ezechias, and Josias, all committed sin.\n"
	"For the kings of Juda forsook the law of the Highest, and contemned the fear of God.\n"
	"For they gave their kingdom to others and their glory to a strange nation.\n"
	"They burnt the chosen city of holiness, & made the ways thereof desolate in the hand of Jeremie.\n"
	"For they evil entreated him, who was consecrated a prophet from his mother's womb, to overthrow, & pluck up, and destroy, and to build again, and renew.\n"
	"Ezechiel who saw the sight of glory, which he shewed him in the chariot of Cherubs.\n"
	"For he made mention of the enemies in rain, to do good unto them, that have shewed right ways.\n"
	"And the bones of the twelve prophets well may they spring out of their place: for they have strengthened Jacob, and have redeemed themselves in the fidelity of power.\n"
	"How may we magnify Zorobabel? For he also was as a signet on the right hand,\n"
	"and so Jesus the son of Josedec: who in their days built the house, and erected the holy temple to our Lord, prepared to everlasting glory.\n"
	"And Nehemias in the memory of much time, who erected us our walls overthrown, and set up the gates and locks, who built our houses.\n"
	"No man hath been born in the earth like to Henoch: for he also was taken up from the earth.\n"
	"Neither as Joseph, who was a man born Prince of his brethren, the stay of the nation, the ruler of his brethren, the stay of the people:\n"
	"and his bones were visited, and after death they prophesied.\n"
	"Seth, and Sem obtained glory with men: and above every soul, in the beginning Adam.";