const char* chap787 = "The word that Isaie the son of Amos saw upon Juda and Jerusalem.\n"
	"And in the later days the mountain of the house of our Lord shall be prepared, in the top of mountains, and it shall be elevated above the little hills: and all nations shall flow unto it.\n"
	"And many peoples shall go, & shall say, come and let us go up to the mount of our Lord, and to the house of the God of Jacob, and he will teach us his ways, and we shall walk in his paths: because the law shall come forth from Sion, and the word of our Lord from Jerusalem.\n"
	"And he shall judge the Gentiles, and rebuke many peoples: and they shall turn their swords into coulters, and their spears into sithes: nation shall not lift up sword against nation, neither shall they be exercised any more to battle.\n"
	"House of Jacob come ye and let us walk in the light of our Lord.\n"
	"For thou hast rejected thy people, the house of Jacob: because they are filled as in times past, and have had soothsayers as the Philisthiims, and have struck fast to strange children.\n"
	"The land is replenished with silver and gold: and there is no end to their treasures.\n"
	"And their land is replenished with horses: and their chariots are innumerable. And their land is full of idols: they have adored the work of their hands, which their fingers made.\n"
	"And man bowed himself, and man was humbled: therefore forgive them not.\n"
	"Enter thou into the rock, and be hid in a pit, in the ground from the face of the fear of our Lord, & from the glory of his majesty.\n"
	"The lofty eyes of man are humbled, and the height of men shall be made to stoop: & our Lord only shall be exalted in that day.\n"
	"Because the day of the Lord of hosts shall be upon all the proud and lofty, and upon every one that is arrogant, and he shall be humbled.\n"
	"And upon all the cedars of Libanus high & elevated, & upon all the oaks of Basan.\n"
	"And upon all the high mountains, and upon all little hills elevated.\n"
	"And upon every high tower, and every fenced wall.\n"
	"And upon all the ships of Tharsis, and upon all that is fair to behold.\n"
	"And the loftiness of men shall be bowed, and the height of men shall be humbled, and our Lord only shall be exalted in that day.\n"
	"And idols shall utterly be destroyed.\n"
	"And they shall enter into the caves of rocks, and into the pits of the earth from the face of the fear of our Lord, and from the glory of his majesty, when he shall rise up to strike the earth.\n"
	"In that day shall a man cast away the idols of his silver, and the idols of his gold, which he had made him to adore, moles and bats.\n"
	"And he shall go into the clefts of rocks, and into the caves of stones from the face of the fear of our Lord, and from the glory of his majesty, when he shall rise up to strike the earth.\n"
	"Cease therefore from the man, whose spirit is in his nostrils, because he is reputed high.";