const char* chap802 = "The burden of Damascus. Behold Damascus shall cease to be a city, and shall be as an heap of stones in ruin.\n"
	"The forsaken cities of Aroer shall be for flocks, and they shall rest there, and there shall be none to terrify them.\n"
	"And aid shall cease from Ephraim, and the kingdom from Damascus: and the remnant of Syria shall be as the glory of the children of Israel: saith the Lord of hosts.\n"
	"And it shall be in that day: the glory of Jacob shall be diminished, and the fatness of his flesh shall become lean.\n"
	"And it shall be as one gathering in harvest that which remaineth, and his arm shall gather the ears of corn: and it shall be as he that seeketh ears in the vale of Raphaim.\n"
	"And the fruit thereof shall be left, as it were a cluster of grapes in it, and as the shaking of the olive tree, of two or three olives in the top of a bough, or four or five in the tops thereof, saith our Lord the God of Israel.\n"
	"In that day man shall incline himself to his maker, and his eyes shall look to the holy one of Israel.\n"
	"And he shall not incline to the altars, which his hands made: and the things that his fingers wrought he shall not regard, as groves and temples.\n"
	"In that day the cities of his strength shall be left, as the ploughs and the corn that were left before the face of the children of Israel, and thou shalt be desolate.\n"
	"Because thou hast forgotten God thy saviour, and hast not remembered thy strong helper: therefore shalt thou plant a faithful plant, & shalt sow a strange seed.\n"
	"In the day of thy planting shall be the wild grape, & in the morning thy seed shall flourish: the harvest is taken away in the day of inheritance, and he shall be vehemently sorry.\n"
	"Woe to the multitude of many peoples, being as the multitude of the sounding sea: & the tumult of multitudes, as the sound of many waters.\n"
	"Peoples shall sound as the sound of waters overflowing, and he shall rebuke him, and shall fly far off: and he shall be violently taken away as the dust of the mountains at the face of the wind, and as a whirlwind before a tempest.\n"
	"In the eventide, and behold trouble: in the morning, and he shall not be. This is the portion of them, that have wasted us, & the lot of them that spoiled us.";