const char* chap808 = "The burden of Tyre. Howl ye ships of the sea, because the house is destroyed, from whence they were wont to come: from the land of Cethim it is revealed to them.\n"
	"Hold your peace ye that dwell in the isle: the traffickers of Sidon passing over the sea, have replenished thee.\n"
	"The seed of Nilus in many waters, the harvest of the river was her fruits: & she was made the traffic of the nations.\n"
	"Be ashamed Sidon, for the sea saith, the strength of the sea, saying: I have not travailed, and I have not brought forth, and I have not nourished young men, nor brought virgins to their growth.\n"
	"When it shall be heard in Aegypt, they will be sorry when they shall hear of Tyre:\n"
	"Pass over the seas, howl ye that dwell in the isle.\n"
	"Is not this your city, which gloried from ancient days in her antiquity? Her feet shall lead her afar to sojourn.\n"
	"Who hath thought this against Tyre, that was some time crowned, whose merchants were princes, her chapmen the nobles of the earth?\n"
	"The Lord of hosts hath thought it, that he might pluck down the pride of all glory, and bring all the glorious of the earth to ignominy.\n"
	"Pass thy land as a river, o daughter of the sea, thou hast a girdle no more.\n"
	"He hath stretched forth his hand upon the sea, he hath troubled kingdoms: Our Lord hath given commandment against Chanaan, to destroy the strong thereof,\n"
	"and he said: Thou shalt add no more to glory, o Virgin daughter of Sidon sustaining calumny: rising up sail over to Cethim, there also thou shalt have no rest.\n"
	"Behold the land of the Chaldees was not such a people, Assur founded it: they led away the strong thereof into captivity, they undermined the houses thereof, they brought it to ruin.\n"
	"Howl ye ships of the sea, because your strength is destroyed.\n"
	"And it shall be in that day: thou shalt be in oblivion o Tyre, seventy years, as the days of one king: but after seventy years, there shall be to Tyre as it were the song of an harlot.\n"
	"Take an harp, go about the city thou harlot forgotten: sing well, multiply song, that there may be remembrance of thee.\n"
	"And it shall be after seventy years: our Lord will visit Tyre, and will bring her back again to her merchandise: and she shall fornicate again with all the kingdoms of the earth, upon the face of the earth.\n"
	"And the marts, and rewards shall be sanctified to our Lord: they shall not be kept in store, nor laid up: because her merchandise shall be for them, that shall dwell before our Lord, that they may eat unto satiety, and be clothed unto continuance.";