const char* chap809 = "Behold our Lord shall dissipate the earth, and make it naked, and afflict the face thereof, and disperse the inhabitants thereof.\n"
	"And as the people, so shall the priest be: & as the servant, so his master: as the handmaid, so her mistress: as the buyer, so he that selleth: as the lender, so he that borroweth: as he that asketh his due, so he that oweth.\n"
	"With dissipation shall the earth be dissipated, & with spoil it shall be spoiled: for our Lord hath spoken this word.\n"
	"The earth hath mourned, & fallen away, and is weakened: the world is fallen away, the height of the people of the earth is weakened.\n"
	"And the earth is infected by the inhabitants thereof: because they have transgressed the laws, changed right, dissipated the everlasting covenant.\n"
	"For this cause shall malediction devour the earth, & the inhabitants thereof shall sin: and therefore the dwellers therein shall be mad, & few men shall be left.\n"
	"The vintage hath mourned, the wine is weakened, all have sighed that rejoiced in heart.\n"
	"The joy of timbrels hath ceased, the sound of them that rejoice is left off, the sweetness of the harp is silent.\n"
	"They shall not drink wine with song: the drink shall be bitter to them that drink it.\n"
	"The city of vanity is broken down, every house is shut, no man goeth in.\n"
	"There shall be crying for the wine in the streets: all mirth is left: the joy of the earth is carried away.\n"
	"Desolation is left in the city, & calamity shall oppress the gates.\n"
	"Because these things shall be in the midst of the earth, in the midst of peoples, in like manner as if a few olives, which are remaining, should be shaken out of the olive tree; and grapes, when the vintage is ended.\n"
	"These shall lift up their voice, and praise: when our Lord shall be glorified, they shall make a joyful noise from the sea.\n"
	"For this cause in doctrines glorify our Lord: in the isles of the sea the name of our Lord the God of Israel.\n"
	"From the ends of the earth we have heard praises, the glory of the just one. And I said: My secret to me, my secret to me, woe is me: the prevaricators have prevaricated, and by the prevarication of transgressors they have prevaricated.\n"
	"Fear, and pit, and snare upon thee, that art inhabiter of the earth.\n"
	"And it shall be: He that shall fly from the voice of fear, shall fall into the pit: and he that shall rid himself out of the pit, shall be held in the snare: because the floodgates from on high are opened, and the foundations of the earth shall be shaken.\n"
	"With breaking shall the earth be broken, with bruising shall the earth be bruised, with moving shall the earth be moved,\n"
	"with shaking shall the earth be shaken as a drunken man, and shall be taken away as the tabernacle of one night: and the iniquity thereof shall be heavy upon it, and it shall fall, and not add to rise again.\n"
	"And it shall be: In that day our Lord will visit upon the host of heaven on high, and upon the kings of the earth, that are upon the earth.\n"
	"And they shall be gathered together as the gathering of a bundle into the lake, and shall be shut there in prison: and after many days they shall be visited.\n"
	"And the moon shall be confounded, when the Lord of hosts shall reign in mount Sion, and in Jerusalem, & shall be glorified in the sight of his ancients.";