const char* chap81 = "And our Lord spake to Moyses, saying:\n"
	"Behold, I have called by name Beseleel the son of Uri the son of Hur of the tribe of Juda,\n"
	"and I have replenished him with the spirit of God, with wisdom, & understanding, and knowledge in all work,\n"
	"to devise whatsoever may be artificially made of gold, and silver, and brass,\n"
	"of marble, and precious stones, and diversity of wood.\n"
	"And I have given him for his fellow, Ooliab the son of Achisamech of the tribe of Dan. And in the heart of every skillful man have I put wisdom: that they may make all things which I have commanded thee,\n"
	"the tabernacle of covenant, and the ark of testimony, and the propitiatory, that is over it, and all the vessels of the tabernacle,\n"
	"and the table and the vessels thereof, the candlestick most pure with the vessels thereof, and the Altars of incense,\n"
	"and of holocaust, and all their vessels, the laver with his foot,\n"
	"the holy vestments in the ministry for Aaron the Priest, and for his sons, that they may execute their office, about the sacred things:\n"
	"the oil of unction, and the incense of spices in the Sanctuary, all things which I have commanded thee, shall they make.\n"
	"And our Lord spake to Moyses, saying:\n"
	"Speak to the children of Israel, and thou shalt say to them: See that you keep my sabbath: because it is a sign between me and you in your generations: that you may know that I am the Lord, which sanctify you.\n"
	"Keep you my sabbath: for it is holy unto you: he that shall pollute it, dying shall die: he that shall do work in it, his soul shall perish out of the midst of his people.\n"
	"Six days shall you do work: in the seventh day is the sabbath, the holy rest to the Lord. Every one that shall do any work in this day, shall die.\n"
	"Let the children of Israel keep the Sabbath, and celebrate it in their generations. It is an everlasting covenant\n"
	"between me and the children of Israel, and a sign perpetual. For in six days the Lord made heaven and earth, and in the seventh he ceased from work.\n"
	"And our Lord, when he had ended such speeches in mount Sinai, gave unto Moyses two stone tables of testimony, written with the finger of God.";