const char* chap814 = "Woe to Ariel, Ariel the city, which David overcame: year is added to year: the solemnities are at an end.\n"
	"And I will make a trench about Ariel, and it shall be sorrowful and mourning, and it shall be to me as Ariel.\n"
	"And I will compass as a sphere round about thee, and will cast a rampier against thee, and place munitions to besiege thee.\n"
	"Thou shalt be humbled, thou shalt speak out of the earth, and out of the ground thy speech shall be heard: and thy voice shall be out of the earth as the Python's, and out of the ground thy speech shall mutter.\n"
	"And the multitude of them that fan thee shall be as small dust: and as isles passing away, the multitude of them, that have prevailed against thee.\n"
	"And it shall be suddenly forthwith. It shall be visited of the Lord of hosts in thunder, and earth quake, and with great voice of whirlwind and tempest, and with flame of devouring fire.\n"
	"And the multitude of all nations, that have fought against Ariel, shall be as the dream of a vision in the night, and all that have warred, and besieged, and prevailed against it.\n"
	"And as he that is hungry dreameth, and eateth, but when he is awake, his soul is empty: and as he that is thirsty dreameth, & drinketh, and after he is awake, faint as yet thirsteth, & his soul is empty: so shall the multitude be of all the Gentiles, that have fought against mount Sion.\n"
	"Be astonied, and marvel, waver, & stagger: be ye drunk, & not of wine: be moved, & not of drunkenness.\n"
	"Because our Lord hath mingled unto you the spirit of drowsiness, he will shut your eyes, he will cover your prophets & princes, that see visions.\n"
	"And the vision of all shall be unto you as the words of a book sealed: which when they shall give to him that knoweth letters, they shall say: Read this; and he shall answer: I cannot, for it is sealed.\n"
	"And the book shall be given to one that knoweth not letters, and it shall be said to him: Read; and he shall answer: I know not letters.\n"
	"And our Lord said: Because this people approacheth with their mouth, and with their lips glorifieth me, but their heart is far from me, and they have feared me by the commandment and doctrines of men:\n"
	"therefore behold I will add to make admiration to this people, by a great and wonderful miracle: for wisdom shall perish from their wise men, and the understanding of their prudent shall be hid.\n"
	"Woe unto you that are deep of heart, to hide your counsel from our Lord: whose works are in darkness, and they say: Who seeth us, and who knoweth us?\n"
	"This your cogitation is perverse: as if the clay should think against the potter, and the work should say to the maker thereof: Thou madest me not: or the thing formed should say to the fashioner thereof: Thou understandest not.\n"
	"Shall not yet within a little while, and in a short time, Libanus be turned into Charmel: and Charmel reputed for a forest?\n"
	"And in that day the deaf shall hear the words of the book, and out of the darkness and mist the eyes of the blind shall see.\n"
	"And the meek shall add joyfulness in our Lord, and the poor men shall rejoice in the holy one of Israel.\n"
	"Because he hath failed that did prevail, the scorner is consumed, and they are all cut down that watched upon iniquity:\n"
	"that made men sin in word, and supplanted him that reproved them in the gate, and declined in vain from the just.\n"
	"For this cause, thus saith our Lord to the house of Jacob, he that redeemed Abraham: Jacob shall not now be confounded, neither shall now his countenance be ashamed:\n"
	"but when he shall see his children, the works of mine hands, in the midst of him sanctifying my name, and they shall sanctify the holy one of Jacob, and shall preach the God of Israel,\n"
	"and they that err in spirit, shall know understanding, and the mutterers shall learn the law.";