const char* chap827 = "Behold my servant, I will receive him: mine elect, my soul hath pleased it-self in him: I have given my spirit upon him, he shall bring forth judgement to the Gentiles.\n"
	"He shall not cry, nor accept person, neither shall his voice be heard abroad.\n"
	"The bruised reed he shall not break, and smoking flax he shall not quench: he shall bring forth judgement in truth.\n"
	"He shall not be sad, nor turbulent, till he set judgement in the earth: and the islands shall expect his law.\n"
	"Thus saith the Lord God that created the heavens, and stretched them out: that established the earth, and the things that spring thereof: that giveth breath to the people, that is upon it, and spirit to them that tread thereupon.\n"
	"I^ the Lord have called thee in justice, and taken thy hand, & preserved thee. And I have given thee for a covenant of the people, for a light of the Gentiles.\n"
	"That thou mightest open the eyes of the blind, and bring forth the prisoner out of prison, and them that sit in darkness out of the prison house.\n"
	"I^ the Lord, this is my name: I will not give my glory to another, and my praise to graven things.\n"
	"The things that were first, lo they are come: new things also I do shew: before they come forth, I will make you hear them.\n"
	"Sing ye to the Lord a new song, his praise is from the ends of the earth: ye that go down to the sea, and you the fullness thereof: ye islands, and inhabitants of the same.\n"
	"Let the desert be exalted and the cities thereof: Cedar shall dwell in houses: ye inhabitants of the Rock, give praise, they shall cry from the top of the mountains.\n"
	"They shall give glory to the Lord, and shall declare his praise in the islands.\n"
	"The Lord shall go forth as a strong man, as a man of war shall he raise up zeal: he shall shout and cry: over his enemies he shall be strengthened.\n"
	"I have always held my peace, I have kept silence, I have been patient, I will speak as a travailing woman: I will dissipate, and swallow up together.\n"
	"I will make mountains and little hills desolate, and will make all their grass to wither: and I will turn rivers into islands, and will dry up the standing pools.\n"
	"And I will lead the blind into the way, which they know not: and in the paths, which they have been ignorant of I will make them walk: I will make darkness before them to be light, and crooked things straight: these words have I done to them, and have not forsaken them.\n"
	"They are turned backward: let them be confounded with confusion, that trust in graven thing, that say to the framed thing, ye are our gods.\n"
	"Hear ye deaf, and ye blind behold to see.\n"
	"Who is blind, but my servant? And deaf, but he to whom I have sent my messengers? Who is blind, but he that is sold? And who is blind, but the servant of the Lord?\n"
	"Thou that seest many things, wilt thou not keep them? Thou that hast ears open, wilt thou not hear?\n"
	"And the Lord hath been willing to sanctify him, and to magnify the law, and extol it.\n"
	"But the same people is spoiled, & wasted: all are the snare of youngmen, and they are hid in the houses of prisons: they are made a prey, neither is there to deliver them: a spoil, neither is there that saith: Restore.\n"
	"Who is there among you that will hear this, attend and harken for things to come?\n"
	"Who hath given Jacob into spoil, and Israel to the wasters? Hath not our Lord himself, to whom we have sinned? And they would not walk in his ways, and they have not heard his law.\n"
	"And he hath poured out upon them, the indignation of his fury, & a strong battle, and hath burnt him round about, and he knew not: and set him on fire, and he understood not.";