const char* chap828 = "And now thus saith our Lord that created thee, o Jacob, & formed thee, o Israel: Fear not, because I have redeemed thee, and called thee by the name: thou art mine.\n"
	"When thou shalt pass through the waters, I will be with thee, and the floods shall not cover thee: when thou shalt walk in fire, thou shalt not be burnt, and the flame shall not burn in thee:\n"
	"Because I am the Lord thy God the holy one of Israel thy saviour, I have given Aegypt thy propitiation, Aethiopia and Saba for thee.\n"
	"Since thou becamest honourable in mine eyes, and glorious: I have loved thee, & I will give men for thee, and peoples for thy soul.\n"
	"Fear not, because I am with thee: from the East will I bring thy seed, and from the West I will gather thee.\n"
	"I will say to the North: Give: and to the South: Hinder not: bring my sons from a far, and my daughters from the ends of the earth.\n"
	"And every one that invocateth my name, for my glory have I created him, formed him, and made him.\n"
	"Bring forth the blind people, and having eyes: the deaf, and he that hath ears.\n"
	"All the nations are assembled together, and the tribes are gathered: which of you can shew this & shall make us hear the former things? Let them give their witnesses, and be justified, and hear, and say: In very deed.\n"
	"You are my witnesses, saith our Lord, and my servants whom I have chosen: that you may know, and believe me, and understand that I myself am. Before me there hath no God been formed, & after me there shall not be.\n"
	"I am, I am the Lord, and there is no saviour beside me.\n"
	"I have shewed, and have saved: I have made it heard, and there hath been no strange one among you. You are my witnesses, saith our Lord, and I^ God.\n"
	"And from the beginning I myself, and there is not that can deliver out of my hand: I will work, and who shall turn it away?\n"
	"Thus saith the Lord your redeemer, the holy one of Israel: For your sake have I sent forth into Babylon, and have plucked down all the bars, & Chaldees glorying in their ships.\n"
	"I^ the Lord your holy one, that created Israel your king.\n"
	"Thus saith our Lord, that gave a way in the sea, and a path in the vehement waters.\n"
	"Which brought forth the chariot & the horse, the arm and the strong: they slept together, neither shall they rise again: they are broken as flax, and are extinct.\n"
	"Remember not former things, and look not on things of old.\n"
	"Behold I make new things, and now they shall spring forth, verily you shall know them: I will make a way in the desert, and rivers in the place not haunted.\n"
	"The beast of the field shall glorify me, the dragons and the ostriches: because I have given waters in the desert: rivers in the place not haunted, that I might give drink to my people, to mine elect.\n"
	"This people have I formed for myself, they shall tell my praise.\n"
	"Thou hast not invocated me, o Jacob, neither hast thou laboured in me, o Israel.\n"
	"Thou hast not offered me the ram of thine holocaust, and with thy victims thou hast not glorified me: I have not made thee to serve in oblation, nor put thee to pain in frankincense.\n"
	"Thou hast not bought me sweet cane for silver, and with the fat of thy victims thou hast not inebriated me. But thou hast made me to serve with thy sins, thou hast put me to pain with thine iniquities.\n"
	"I am, I am he that take clean away thine iniquities for mine own sake, and I will not remember thy sins.\n"
	"Bring me into remembrance, & let us be judged together: tell if thou have any thing, that thou mayst be justified.\n"
	"Thy first father sinned, and thy interpreters have transgressed against me.\n"
	"And I have profaned the holy princes, I have given Jacob to destruction, & Israel to reproach.";