const char* chap831 = "Bel is broken, Nabo is destroyed: their idols are made to beasts & cattle, your burdens of heavy weight even unto weariness.\n"
	"They have melted away, and are broken together: they could not save him that carried them, & their soul shall go into captivity.\n"
	"Hear me, o house of Jacob, all the remnant of the house of Israel, which are carried of my womb, are borne up of my matrice.\n"
	"Even unto old age I am the same, and unto hoar hairs I will carry: I have made, & I will bear: I will carry, and will save.\n"
	"Whereto have you resembled me, and made me equal, and compared me, and made me like?\n"
	"You that contribute gold out of the bag, and weigh silver with balance: hiring a goldsmith to make a god: and they fall down and adore.\n"
	"They bear him on their shoulders carrying, and setting him in his place, and he shall stand, and shall not move out of his place. Yea when they shall cry also unto him, he shall not hear: from tribulation he shall not save them.\n"
	"Remember this, and be confounded: return ye transgressors to the heart.\n"
	"Remember the former world, because I am God, and there is no God beside, neither is there the like to me.\n"
	"Which shew the last thing from the beginning, and from the beginning the things that as yet were not done, saying: My counsel shall stand, & all my will shall be done:\n"
	"Which call a bird from the east, and from a far country, the man of mine own will, and I have spoken, and will bring it: I have created, and will do it.\n"
	"Hear me ye hard hearted, which are far from justice.\n"
	"I have made my justice near, it shall not be far off, and my salvation shall not tarry. I will give salvation in Sion, and my glory to Israel.";