const char* chap841 = "Thus saith our Lord: keep ye judgement, and do justice: because my salvation is near to come, and my justice to be revealed.\n"
	"Blessed is the man that doth this thing, and the son of man that shall apprehend this, keeping the Sabbath that he pollute it not, keeping his hands that he do no evil.\n"
	"And let not the son of the stranger, that cleaveth to our Lord, say: By separation the Lord will divide me from his people.\n"
	"And let not the eunuch say: Behold I am a dry tree. Because thus saith our Lord to the eunuchs: They that shall keep my Sabbaths, and shall choose the things that I would, and shall hold my covenant.\n"
	"I will give unto them in my house, and within my walls a place, and a name better than sons and daughters, an everlasting name will I give them, which shall not perish.\n"
	"And the children of the stranger that cleave to the Lord, to worship him, & to love his name, to be his servants: every one that keepeth the Sabbath^ not to pollute it, and that holdeth my covenant.\n"
	"I will bring them into my holy mount, & will make them joyful in the house of my prayer: their holocausts, and their victims shall please me upon mine altar: because my house shall be called the house of prayer to all peoples.\n"
	"Saith our Lord God that gathereth the dispersed of Israel: As yet will I gather unto it, the gathered together thereof.\n"
	"All ye beasts of the field come to devour, all ye beasts of the forest.\n"
	"His watchmen all blind have been ignorant: dumb dogs not able to bark, seeing vain things, sleeping and loving dreams.\n"
	"And most impudent dogs, they have known no satiety: the pastors themselves have been ignorant of understanding: all have declined into their own way, every one to his own avarice, from the highest even to the last.\n"
	"Come, let us take wine, and be filled with drunkenness, and it shall be as today, so also tomorrow, and much more.";