const char* chap845 = "Arise, be illuminated Jerusalem: because thy light is come, & the glory of our Lord is risen upon thee:\n"
	"Because lo darkness shall cover the earth, & a mist the peoples: but upon thee shall our Lord arise, and his glory shall be seen upon thee.\n"
	"And the Gentiles shall walk in thy light, and kings in the brightness of thy rising.\n"
	"Lift up thine eyes round about & see, all these are gathered together, they are come to thee: thy sons shall come from a far, & thy daughters shall rise from the side.\n"
	"Then shalt thou see, & abound, & thy heart shall marvel and be enlarged, when the multitude of the sea shall be converted to thee, the strength of Gentiles shall come to thee.\n"
	"The inundation of camels shall cover thee, the dromedaries of Madian and Epha: all of Saba shall come, bringing gold and frankincense: and shewing forth praise to our Lord.\n"
	"All the cattle of Cedar shall be gathered together unto thee, the rams of Nabaioth shall minister to thee: they shall be offered upon my placable altar, and I will glorify the house of my majesty.\n"
	"Who are these, that fly as clouds, and as doves to their windows?\n"
	"For the islands expect me, and the ships of the sea in the beginning, that I may bring thy sons from a far: their silver, & their gold with them, to the name of the Lord thy God, and to the holy one of Israel, because he hath glorified thee.\n"
	"And the children of strangers shall build thy walls, and their kings shall minister to thee: for in mine indignation have I strucken thee, and in my reconciliation have I had mercy upon thee.\n"
	"And thy gates shall be open continually: day and night they shall not be shut, that the strength of the Gentiles may be brought to thee, and their kings may be brought.\n"
	"For the nation & the kingdom that shall not serve thee, shall perish: & the Gentiles shall be wasted with desolation.\n"
	"The glory of Libanus shall come to thee, the fir-tree, & box-tree, and pine-tree together, to adorn the place of my sanctification, and the place of my feet I will glorify.\n"
	"And the children of them that humbled thee, shall come crouching to thee, and all that detracted from thee shall adore the steps of thy feet, and shall call thee the city of the Lord, Sion of the holy one of Israel.\n"
	"For that thou wast forsaken, and hated, and there was none that passed by thee, I will make thee to be the pride of worlds, a joy unto generation & generation:\n"
	"& thou shalt suck the milk of the Gentiles, & thou shalt be nursed with the teat of kings: & thou shalt know that I am the Lord that save thee, and thy Redeemer the strong one of Jacob.\n"
	"For brass I will bring gold, and for iron I will bring silver: and for wood brass, and for stones iron: and I will make thy visitation peace, and thine overseers justice.\n"
	"Iniquity shall no more be heard in thy land, waste and destruction in thy borders, and salvation shall occupy thy walls, & praise thy gates.\n"
	"Thou shalt have the sun no more to shine by day, neither shall the brightness of the moon lighten thee: but the Lord shall be unto thee for an everlasting light, and thy God for thy glory.\n"
	"Thy sun shall go down no more, and thy moon shall not be diminished: because the Lord shall be unto thee for an everlasting light, & the days of thy mourning shall be ended.\n"
	"And thy people all just, for ever shall inherit the land, the bud of my planting, the work of mine hand to glorify.\n"
	"The least shall be into a thousand, and the little one into a most strong nation: I^ the Lord in the time thereof will suddenly do it.";