const char* chap849 = "Would God thou wouldest break the heavens asunder, and wouldst descend: at thy presence the mountains should melt away.\n"
	"As the burning of fire would they melt, the waters would burn with fire, that thy name might be made known to thine enemies: at thy presence the nations should be troubled.\n"
	"When thou shalt do marvelous things, we shall not sustain: thou art descended, and at thy presence the mountains are melted.\n"
	"From the beginning of the world they have not heard, nor received with the ears: the eye hath not seen, o God, beside thee, what things thou hast prepared for them that expect thee.\n"
	"Thou hast met him that rejoiceth, and doth justice: in thy ways they shall remember thee: behold thou art angry, and we have sinned: we have been always in them, and we shall be saved.\n"
	"And all we are become as one unclean, and all our justices as the cloth of a menstrued woman: and we have all fallen as a leaf, and our iniquities as the wind have taken us away.\n"
	"There is none that invocateth thy name: that riseth up, and holdeth thee, thou hast hid thy face from us, and hast dashed us in the hand of our iniquity.\n"
	"And now Lord thou art our father, & we clay: and thou art our maker, and all we the works of thy hands.\n"
	"Be not angry, o Lord, enough, and remember no more our iniquity: lo regard, all we are thy people.\n"
	"The city of thy holy one is made desert, Sion is made desert, Jerusalem is become desolate.\n"
	"The house of our sanctification, and of our glory, where our fathers praised thee, is turned into the burning of fire, and all our things worthy to be desired are turned into ruins.\n"
	"Wilt thou upon these things contain thyself, o Lord, wilt thou hold thy peace, and afflict us vehemently?";