const char* chap850 = "They have sought me that before asked not, they have found that sought me not, I said: Behold me, behold me, to a Gentility that did not invocate my name.\n"
	"I have spread forth mine hands all the day to an incredulous people, which goeth in a way not good after their own cogitations.\n"
	"A people that provoke me to anger before my face always: that immolate in gardens, and sacrifice upon bricks.\n"
	"That dwell in sepulchres, and sleep in temples of idols: that eat swine's flesh, and profane potage in their vessels.\n"
	"That say: Depart from me, approach not to me, because thou art unclean: these shall be smoke in my fury, a fire burning all the day.\n"
	"Behold it is written before me: I will not hold my peace, but I will render and repay into their bosom\n"
	"your iniquities, and the iniquities of your fathers together, saith our Lord, that have sacrificed upon the mountains, and upon the little hills have reproached me, & I will remeasure their first work in their bosom.\n"
	"Thus saith our Lord: As if a berry be found in a cluster, and it be said: Destroy it not, because it is a blessing: so will I do for my servants' sake, that I destroy not the whole.\n"
	"And I will bring forth seed out of Jacob, & out of Juda a possessor of my mountains: & mine elect shall inherit it, and my servants shall inhabit there.\n"
	"And the champion countries shall be into folds of flocks, and the valley of Achor for the couch of herds, unto my people that have sought after me.\n"
	"And you, that have forsaken the Lord, that have forgotten my holy mount, that set a table to Fortune, and offer libaments upon it.\n"
	"I will number you in the sword, and you shall all fall by slaughter: because I called, and you have not answered: I spake, and you have not heard, and you did evil in mine eyes: and you have chosen the things, that I would not.\n"
	"For this cause thus saith our Lord God: Behold my servants shall eat, and you shall be hungry: behold my servants shall drink, and you shall be thirsty.\n"
	"Behold my servants shall rejoice, and you shall be confounded: behold my servants shall praise for joyfulness of heart: and you shall cry for sorrow of heart, and for contrition of spirit you shall howl.\n"
	"And you shall leave your name for an oath to mine elect: and the Lord God shall kill thee, and will call his servants by another name.\n"
	"In which he that is blessed upon the earth, shall be blessed in God, Amen: & he that sweareth in the earth, shall swear by God Amen: because the former distresses are forgotten, & because they are hid from mine eyes.\n"
	"For behold I create new heavens, & a new earth: & the former things shall not be in memory, & they shall not ascend upon the heart.\n"
	"But you shall be glad & rejoice for ever in these things, which I create: because lo I create Jerusalem exultation, and the people thereof joy.\n"
	"And I will rejoice in Jerusalem, and be glad in my people, and there shall no more be heard in it the voice of weeping, and the voice of crying.\n"
	"There shall no more be a child of days, & an old man that shall not fill up his days, because the child of an hundred years shall die, and the sinner of an hundred years shall be accurst.\n"
	"And they shall build cities, and inhabit: and they shall plant vineyards, and eat the fruits thereof.\n"
	"They shall not build, and another shall dwell: they shall not plant, & another shall eat: for according to the days of the tree, shall be the days of my people, and they shall make old the works of their hands.\n"
	"Mine elect shall not labour in vain, nor engender in conturbation: because it is the seed of the blessed of the Lord, and their posterity with them.\n"
	"And it shall be, before they call, I will hear: as they are yet speaking, I will hear.\n"
	"The wolf and the lamb shall feed together, the lion and the oxe shall eat straw: & to the serpent dust shall be his bread: they shall not hurt, nor kill in all my holy mountain, saith our Lord.";