const char* chap852 = "The words of Jeremy the son of Helcias, of the Priests that were in Anathoth, in the land of Benjamin.\n"
	"The word of our Lord which was made to him in the days of Josias the son of Amon king of Juda, in the thirteenth year of his kingdom.\n"
	"And the word was made in the days of Joakim the son of Josias king of Juda, unto the end of the eleventh year of Sedecias the son of Josias king of Juda, even unto the transmigration of Jerusalem, in the fifth month.\n"
	"And the word of our Lord was made to me, saying:\n"
	"Before I formed thee in the womb, I knew thee: and before thou camest forth of the matrice, I sanctified thee, and a Prophet in the Gentiles I gave thee.\n"
	"And I said: A a a, o Lord God: Behold I cannot speak, because I am a child.\n"
	"And our Lord said unto me: Say not: I am a child: for to all things, to which I shall send thee, thou shalt go: and all things whatsoever I shall command thee, thou shalt speak.\n"
	"Be not afraid of their face: because I am with thee, to deliver thee, saith our Lord.\n"
	"And our Lord put forth his hand, and touched my mouth: & our Lord said to me: Behold I have given my words in thy mouth:\n"
	"Behold I have appointed thee this day over the Gentiles, and over kingdoms, that thou mayst pluck up, and destroy, and waste, and dissipate, and build, and plant.\n"
	"And the word of our Lord was made to me, saying: What seest thou Jeremy? And I said: I see a rod watching.\n"
	"And our Lord said to me? Well hast thou seen; because I will watch upon my word to do it.\n"
	"And the word of our Lord was made to me the second time, saying: What seest thou? And I said: I see a pot boiling hot, and the face thereof from the face of the North.\n"
	"And our Lord said unto me: From the North shall evil be opened upon all the inhabitants of the land.\n"
	"Because lo I will call together all the kindreds of the kingdoms of the North, saith our Lord: and they shall come, and shall set every one his throne in the entering of the gates of Jerusalem, and upon all the walls thereof round about, and upon all the cities of Juda.\n"
	"And I will speak my judgements with them, touching all the wickedness of them that have forsaken me, and have offered to strange gods, and have adored the work of their own hands.\n"
	"Thou therefore gird thy loins, & rise, and speak to them all things that I command thee. Be not afraid of their face: for I will make thee not to fear their countenance.\n"
	"For I have given thee this day to be as a fenced city, and as an iron pillar, and as a brazen wall over all the land of the kings of Juda, to the Princes thereof, & to the Priests, and to the people of the land.\n"
	"And they shall fight against thee, and shall not prevail: because I am with thee, saith our Lord, to deliver thee.";