const char* chap856 = "Go round about the ways of Jerusalem, and look, and consider, & seek in the streets thereof, whether you can find a man that doth judgements, and seeketh fidelity: and I will be propitious unto him.\n"
	"Yea if they say: Our Lord liveth this also they will swear falsely.\n"
	"O Lord thine eyes regard fidelity: thou hast strucken them, and they were not sorry: thou hast broken them, and they have refused to receive discipline: they have hardened their faces more than the rock, and they would not return.\n"
	"But I said: Perhaps they are poor and foolish, not knowing the way of the Lord, the judgement of their God.\n"
	"I will go therefore to the great men, and will speak to them: for they have known the way of their Lord: and behold these altogether have more broken the yoke, have burst the bonds.\n"
	"Therefore hath the lion out of the wood strucken them, the wolf in the evening hath wasted them, the leopard watching upon their cities: every one of them that shall come forth, shall be taken, because their prevarications, are multiplied, their revoltings are strengthened.\n"
	"Whereupon can I be propitious to thee? Thy children have forsaken me, and swear by them, that are not gods: I filled them, and they committed adultery, and did riotously in the harlot's house.\n"
	"They are become as amorous horses, and stallions: every one neighed at his neighbour's wife:\n"
	"Why, shall I not visit upon these things, saith our Lord? And on such a nation shall not my soul take revenge?\n"
	"Scale the walls thereof, and dissipate them, but make not a consummation: take away the branches thereof, because they are not the Lord's.\n"
	"For by prevarication hath the house of Israel prevaricated against me, and the house of Juda, saith our Lord.\n"
	"They have denied our Lord, and said: It is not he: neither shall the evil come upon us: we shall not see sword and famine.\n"
	"The Prophets have spoken into the wind, and there was no answer in them: these things therefore shall happen to them.\n"
	"Thus saith our Lord the God of hosts: Because you have spoken this word: behold, I give my words in thy mouth as fire, & this people as sticks, & it shall devour them.\n"
	"Behold I will bring upon you a nation from a far, o house of Israel, saith our Lord: a strong nation, an ancient nation, a nation whose tongue thou shalt not know, nor understand what it speaketh.\n"
	"The quiver thereof is as an open sepulchre, they are all strong.\n"
	"And it shall eat thy corn, and thy bread: it shall devour thy sons, and thy daughters: it shall eat thy flock, and thy herds: it shall eat thy vineyard, and thy fig: and it shall destroy thy fenced cities, wherein thou hast confidence, with the sword.\n"
	"But yet in those days, saith our Lord, I will not bring you into consummation.\n"
	"And if you shall say: Why hath the Lord our God done all these things to us? Thou shalt say to them: As you have forsaken me, and served a strange god in your own land, so shall you serve strange ones in a land not your own.\n"
	"Declare ye this to the house of Jacob, and make it heard in Juda, saying:\n"
	"Hear thou foolish people, that hast no heart, which having eyes, seest not: and ears, and hearest not.\n"
	"Me then will you not fear, saith our Lord: and at my presence will ye not be sorry? Who have set the sand a limit for the sea, an everlasting precept, that shall not pass, and they shall be moved, and shall not prevail: and the waves thereof shall swell, and shall not pass over it.\n"
	"But to this people their heart is become incredulous and exasperating, they are revolted and departed.\n"
	"And they have not said in their heart: Let us fear the Lord our God, who giveth us the timely and lateward rain in due season: who preserveth the fullness of the yearly harvest unto us.\n"
	"Your iniquities have turned away these things, and your sins have stayed good from you.\n"
	"Because there are found impious men in my people, that lie in wait as fowlers setting snares & traps to take men.\n"
	"As a net full of birds, so their houses are full of guile: therefore are they magnified, and enriched.\n"
	"They are made gross and fat: and have transgressed my words most wickedly. The cause of the widow they have not judged, the cause of the pupil they have not directed, and the judgement of the poor they have not judged.\n"
	"Shall I not visit upon these things, Saith our Lord? Or upon such a nation shall not my soul take revenge?\n"
	"Astonishment and marvelous things are done in the land.\n"
	"The Prophets prophesied a lie, and the Priests clapped with their hands: and my people hath loved such things: what shall be done therefore in the later end thereof?";