const char* chap863 = "Thou indeed o Lord art just, if I dispute with thee, but yet I will speak just things to thee: Why doth the way of the impious prosper: why is it well with all that transgress, and do wickedly?\n"
	"Thou hast planted them, and they have taken root: they prosper and bring forth fruit: thou art nigh to their mouth, and far from their reins.\n"
	"And thou Lord hast known me, thou hast seen me, and proved my heart with thee: gather them together as a flock to the victim, and sanctify them in the day of slaughter.\n"
	"How long shall the land mourn, and the herb of every field be withered for malice of the inhabitants therein? Beast is consumed, and fowl: because they have said: He shall not see our later ends.\n"
	"If running with foot-men thou hast laboured: how canst thou contend with horses? And whereas in a land of peace thou hast been secure, what wilt thou do in the pride of Jordan?\n"
	"For even thy brethren, and the house of thy father, they also have fought against thee, and have cried after thee with full voice: believe them not when they shall speak good things unto thee.\n"
	"I have forsaken my house, I have left mine inheritance: I have given my beloved soul into the hand of her enemies.\n"
	"Mine inheritance is become unto me as a lion in the wood: it hath uttered a voice against me, therefore have I hated it.\n"
	"Why, is mine inheritance unto me as a bird of diverse colours? Is it as a bird dyed throughout? Come, assemble yourselves all ye beasts of the land, make haste to devour.\n"
	"Many pastors have destroyed my vineyard, they have trodden down my portion: they have made my portion that was worthy to be desired, into a desert of desolation.\n"
	"They have laid it into dissipation, and it hath mourned upon me. With desolation is all the land made desolate: because there is none that considereth in the heart.\n"
	"Upon all the ways of the desert the wasters are come, because the sword of our Lord shall devour from one end of the land to the other end thereof: there is no peace to all flesh.\n"
	"They have sown wheat, and reaped thorns: they have taken an inheritance, & it shall not profit them: you shall be ashamed of your fruits, for the wrath of the fury of our Lord.\n"
	"Thus saith the Lord against all my most wicked neighbours: which touch the inheritance that I have distributed to my people of Israel: Behold I will pluck them out of their land, and the house of Juda I will pluck out of the midst of them.\n"
	"And when I shall have plucked them out, I will return, and have mercy on them: and will bring them back, every man to his inheritance, and every man into his land.\n"
	"And it shall be: if being taught they will learn the ways of my people, that they swear in my name: Our Lord liveth, as they have taught my people to swear by Baal: they shall be built in the midst of my people.\n"
	"But if they will not hear, I will pluck out that nation with plucking up and with destruction, saith our Lord.";