const char* chap865 = "The word of our Lord that was made to Jeremy concerning the words of the drought.\n"
	"Jury hath mourned, and the gates thereof are fallen down, and are obscured on the earth, and the cry of Jerusalem is come up.\n"
	"The greater men have sent their inferiors to the water: they came to draw, they found no water, they carried back their vessels empty: they were confounded and afflicted, and covered their heads.\n"
	"For the waste of the land, because there came no rain upon the earth, the husbandmen were confounded, they covered their heads.\n"
	"For the hind also brought forth in the field, and left it: because there was no grass.\n"
	"And the wild asses stood upon the rocks, they drew wind as dragons, their eyes failed, because there was no grass.\n"
	"If our iniquities have answered us: Lord do for thy name's sake, because our revoltings are many, to thee we have sinned.\n"
	"O expectation of Israel, the saviour thereof in the time of tribulation: why wilt thou be as a sojourner in the land, and as a wayfaring man turning in to lodge?\n"
	"Why wilt thou be as a wandering man, as the strong that cannot save? But thou o Lord art in us, and thy name is invocated upon us, forsake us not.\n"
	"Thus saith our Lord to his people, which hath loved to move their feet, and have not rested, and hath not pleased our Lord: Now will he remember their iniquities, and visit their sins.\n"
	"And our Lord said to me: Pray not for this people to good.\n"
	"When they shall fast I will not hear their prayers: and if they shall offer holocausts and victims, I will not receive them: because with sword, and famine, and pestilence I will consume them.\n"
	"And I said: A a a, O Lord God^ the Prophets say to them: You shall not see the sword, and there shall be no famine among you, but he will give you true peace in this place.\n"
	"And our Lord said to me: The Prophets prophesy falsely in my name: I sent them not, and I commanded them not, neither have I spoken unto them: lying vision, and deceitful divination, guilefulness, and the seduction of their own heart they prophesy unto you.\n"
	"Therefore thus saith our Lord of the Prophets, that prophesy in my name, whom I sent not, that say: There shall not be sword, and famine in this land: In sword and famine shall those Prophets be consumed.\n"
	"And the peoples to whom they prophesy, shall be cast forth in the ways of Jerusalem through famine and sword, and there shall be none to bury them; they & their wives, their sons & their daughters, and I will pour out their evil upon them.\n"
	"And thou shalt say this word unto them: Let mine eyes shed tears night & day, & not cease, because the virgin daughter of my people is afflicted with great affliction, with a very sore plague exceedingly.\n"
	"If I shall go out to the fields, lo the slain with the sword: and If I enter into the city, lo the pined away with famine. For the Prophet & the Priest are gone into a land which they knew not.\n"
	"Why, casting off hast thou cast away Juda, or hath thy soul abhorred Sion? Why then hast thou striken us, so that there is not health? We have expected peace, & there is no good: and a time of curing, and behold trouble.\n"
	"We have known o Lord our impieties, the iniquities of our fathers, because we have sinned to thee.\n"
	"Give us not into reproach for thy name's sake, neither make us to have the contumely of the throne of thy glory: remember, make not thy covenant with us void.\n"
	"Why, are there among the sculptiles of the Gentiles that can rain? Or can the heavens give showers? Art not thou the Lord our God, whom we have expected? For thou hast made all these things.";