const char* chap871 = "And Phassur the son of Emmer Priest, who was appointed Prince in the house of our Lord, heard Jeremy prophesying these words.\n"
	"And Phassur struck Jeremy the Prophet, and put him into the stocks, that was in the upper gate of Benjamin, in the house of our Lord.\n"
	"And when it was light on the morrow, Phassur brought forth Jeremy out of the stocks. And Jeremy said to him: Our Lord hath called thy name not Phassur, but fear on every side.\n"
	"Because thus saith our Lord: Behold I will give thee into fear, thee and all thy friends: and they shall fall by the sword of their enemies, and thine eyes shall see, and I will give all Juda into the hand of the king of Babylon: and he shall transport them into Babylon, and shall strike them with the sword.\n"
	"And I will give all the substance of this city, & all the labour thereof, and all the price, and all the treasures of the kings of Juda will I give into the hand of their enemies: and they shall spoil them, and take them away, and carry them into Babylon.\n"
	"But thou Phassur, and all the inhabiters of thy house shall go into captivity, and thou shalt come into Babylon, and there thou shalt die, and there shalt be buried, thou and all thy friends, to whom thou hast prophesied a lie.\n"
	"Thou hast seduced me, o Lord, and I am seduced: thou wast stronger than I, and hast prevailed: I am made a derision all the day, all do scorn me.\n"
	"Because now long ago I speak, crying out iniquity, and I often proclaim wasting: and the word of our Lord is made a reproach to me, and a derision all the day.\n"
	"And I said: I will not remember him, nor speak any more in his name: and there was made in my heart as a fire boiling, and shut up in my bones: and I fainted, not sustaining to bear it.\n"
	"For I heard the contumelies of many, and terror on every side: persecute ye, and let us persecute him: of all the men, that were my peaceables, and guarding my side: if by any means he may be deceived, and we prevail against him, and be revenged on him.\n"
	"But our Lord is with me as a strong warrior: therefore they that persecute me shall fall, and shall be weak: they shall be confounded exceedingly, because they have not understood the everlasting reproach, which never shall be clean put away.\n"
	"And thou Lord of hosts, prover of the just, which seest the reins and the heart: let me see I beseech thee thy revenge of them: for to thee I have revealed my cause.\n"
	"Sing ye to our Lord, praise our Lord: because he hath delivered the soul of the poor out of the hand of the wicked.\n"
	"Cursed be the day, wherein I was born: the day in which my mother bare me, be it not blessed.\n"
	"Cursed be the man that told my father, saying: There is a man child born to thee: and as it were with joy he rejoiced him.\n"
	"Let that man be as the cities are, which our Lord hath subverted, and it hath not repented him: let him hear crying in the morning, and howling at noon time.\n"
	"Who slew me not from the womb, that my mother might be made my grave, and her womb an everlasting conception.\n"
	"Why came I out of the womb, that I should see labour and sorrow, and my days should be spent in confusion?";