const char* chap872 = "The word that was made to Jeremy from our Lord when king Sedecias sent Phassur the son of Melchias unto him, and Sophonias the son of Maasias Priest, saying:\n"
	"Ask our Lord for us, because Nabuchodonosor the king of Babylon maketh battle against us: if perhaps our Lord shall do with us according to all his marvelous works, and he may retire back from us.\n"
	"And Jeremy said to them: Thus shall you say to Sedecias:\n"
	"Thus saith our Lord the God of Israel: Behold I will convert the weapons of war which are in your hands, and wherewith you fight against the king of Babylon, & the Chaldees, that besiege you round about the walls: & I will gather them together in the midst of this city.\n"
	"And I will vanquish you in stretched out hand, and in a strong arm, and in fury, and in indignation, and in great wrath.\n"
	"And will strike the inhabitants of this city, men and beasts shall die with a great pestilence.\n"
	"And after this saith our Lord: I will give Sedecias the king of Juda, and his servants, & his people, & they that are left in his city from the pestilence, and the sword, and famine, into the hand of Nabuchodonosor the king of Babylon, and into the hand of their enemies, and into the hand of them that seek their life, and he will strike them in the edge of the sword, and he will not be moved, nor spare, nor have mercy.\n"
	"And to this people thou shalt say: Thus saith our Lord: Behold I give before you the way of life, and the way of death.\n"
	"He that shall dwell within this city, shall die with the sword, and with famine, and pestilence: but he that shall go forth, and fly to the Chaldees that besiege you, shall live, and his life shall be to him as a spoil.\n"
	"For I have set my face upon this city to evil, & not to good, saith our Lord: it shall be given into the hand of the king of Babylon, & he shall burn it with fire.\n"
	"And to the house of the king of Juda: Hear ye the word of our Lord,\n"
	"o house of David, thus saith our Lord: Judge ye judgement in the morning, & deliver the oppressed by violence out of the hand of the oppressor: lest perhaps mine indignation go forth as fire, & be kindled, & there be none to quench it, because of the malice of your studies.\n"
	"Behold, I to thee inhabitress of the firm & champion valley saith our Lord: which say. Who shall strike us: & who shall enter into our houses?\n"
	"And I will visit upon you according to the fruit of your studies, saith our Lord: and I will kindle a fire in the forest thereof: and it shall devour all things round about it.";