const char* chap879 = "And it came to pass in that year, in the beginning of the kingdom of Sedecias king of Juda, in the fourth year, in the fifth month, Hananias the son of Azur the Prophet of Gabaon spake to me, in the house of our Lord before the Priests, and all the people, saying:\n"
	"Thus saith the Lord of hosts the God of Israel, I have broken the yoke of the king of Babylon.\n"
	"As yet two years of days, and I will make all the vessels of the house of our Lord to be brought back into this place, which Nabuchodonosor the king of Babylon took out of this place, and transported them into Babylon.\n"
	"And Jechonias the son of Joakim the king of Juda, and all the transmigration of Juda, that are entered into Babylon, I will make to return to this place, saith our Lord: for I will break the yoke of the king of Babylon.\n"
	"And Jeremy the Prophet said to Hananias the Prophet in the presence of the Priests, and in the presence of all the people, that stood in the house of our Lord:\n"
	"And Jeremy the Prophet said: Amen, Our Lord so do: our Lord raise up thy words, which thou hast prophesied: that the vessels may be brought again into the house of our Lord, and all the transmigration out of Babylon to this place.\n"
	"But yet hear this word, that I speak in thine ears, and in the ears of all the people:\n"
	"The Prophets, that have been before me, and before thee from the beginning, and have prophesied concerning many countries, and concerning great kingdoms of war, and of affliction, and of famine.\n"
	"The Prophet, that hath prophesied peace: when his word shall come to pass, the Prophet shall be known, whom our Lord hath sent in truth.\n"
	"And Hananias the Prophet took the chain from the neck of Jeremy the Prophet and brake it.\n"
	"And Hananias spake in the sight of all the people, saying: Thus saith our Lord: So will I break the yoke of Nabuchodonosor the king of Babylon after two years of days, from the neck of all nations.\n"
	"And Jeremy the Prophet went his way. And the word of our Lord was made to Jeremy, after that Hananias the Prophet brake the chain from the neck of Jeremy the Prophet, saying:\n"
	"Go, and thou shalt tell Hananias: Thus saith our Lord: Thou hast broken chains of wood, and thou shalt make for them chains of iron.\n"
	"Because thus saith the Lord of hosts the God of Israel: An iron yoke have I put upon the neck of all these Nations, to serve Nabuchodonosor the king of Babylon, and they shall serve him: moreover also the beasts of the earth I have given him.\n"
	"And Jeremy the Prophet said to Hananias the Prophet: Hear Hananias: Our Lord sent thee not, and thou hast made this people to trust in a lie.\n"
	"Therefore thus saith our Lord: Behold I will send thee from off the face of the earth: this year shalt thou die: for thou hast spoken against our Lord.\n"
	"And Hananias the Prophet died in that year, the seventh month.";