const char* chap883 = "The word that was made to Jeremy from our Lord in the tenth year of Sedecias the king of Juda: the same is the eighteenth year of Nabuchodonosor.\n"
	"Then the army of the king of Babylon besieged Jerusalem: and Jeremy the Prophet was shut up in the court of the prison, that was in the house of the king of Juda.\n"
	"For Sedecias the king of Juda had shut him up, saying: Why doest thou prophesy, saying: Thus saith our Lord: Behold I will give this city into the hand of the king of Babylon, and he shall take it?\n"
	"And Sedecias the king of Juda shall not escape out of the hand of the Chaldees: but he shall be delivered into the hands of the king of Babylon: and he shall speak with him mouth to mouth, and his eyes shall see his eyes.\n"
	"And he shall lead Sedecias into Babylon: & he shall be there till I visit him, saith our Lord. But if you will fight against the Chaldees you shall have nothing prosperous.\n"
	"And Jeremy said: The word of our Lord was made to me, saying:\n"
	"Behold, Hanameel the son of Sellum thy cousin shall come to thee, saying: Buy unto thee my field, which is in Anathoth: for it appertaineth to thee by kindred to buy it.\n"
	"And Hanameel mine uncle's son came unto me according to the word of our Lord to the entry of the prison, and said to me: Possess my field, which is in Anathoth in the land of Benjamin: because the inheritance pertaineth to thee, and thou art near of kin to possess it. And I understood that it was the word of our Lord.\n"
	"And I bought the field of Hanameel mine uncle's son, which is in Anathoth: and I weighed him the silver, seven staters, and ten pieces of silver.\n"
	"And I wrote it in a book, and signed it, and took witnesses: and I weighed the silver in balance.\n"
	"And I took the book of the possession signed, and the stipulations, and the things ratified, and the signs on the out side.\n"
	"And I gave the book of the possession to Baruch the son of Neri the son of Maasias in the sight of Hanameel my cousin, and in the sight of the witnesses, that were written in the book of the purchase, and in the sight of all the Jews, that sat in the court of the prison.\n"
	"And I commanded Baruch before them saying:\n"
	"Thus saith the Lord of hosts the God of Israel: Take these books, this book of the purchase signed, and this book, that is open: and put them in an earthen vessel, that they may continue many days.\n"
	"For thus saith the Lord of hosts, the God of Israel: Yet shall houses, and fields, and vineyards be possessed in this land.\n"
	"And I prayed to our Lord, after that I delivered the book of the possession to Baruch the son of Neri, saying:\n"
	"Alas, alas, alas, o Lord God: behold thou hast made heaven and earth in thy great strength, & in thy stretched out arm: no word shall be hard to thee:\n"
	"Which doest mercy on thousands, and renderest the iniquity of the fathers into the bosom of their children after them. O Most strong, great, & mighty, the Lord of hosts is thy name.\n"
	"Great in counsel, and incomprehensible in cogitation: whose eyes are open upon all the ways of the children of Adam, to render unto every one according to his ways, and according to the fruit of his inventions.\n"
	"Which hast put signs & wonders in the land of Aegypt even until this day, & in Israel, & in men, and hast made thee a name as is this day.\n"
	"And thou didst bring forth thy people Israel out of the Land of Aegypt, in signs, & in wonders, & in a strong hand, and in a stretched out arm, and in great terror.\n"
	"And thou gavest them this land, which thou swarest to their fathers, that thou wouldst give them a land flowing with milk and honey.\n"
	"And they entered in, & possessed it: & they obeyed not thy voice, & in thy law they walked not: all that thou didst command them to do, they did not: and all these evils are befallen them.\n"
	"Behold munitions are built against the city, that it may be taken: & the city is given into the hands of the Chaldees, which fight against it, at the presence of the sword, and of famine, and of pestilence: & what things soever thou hast spoken, are come to pass, as thyself seest.\n"
	"And sayst thou to me o Lord God: Buy the field for silver, & take witnesses, whereas the city is given into the hands of the Chaldees?\n"
	"And the word of our Lord was made to Jeremy, saying:\n"
	"Behold I am the Lord the God of all flesh: shall any word be hard for me?\n"
	"Therefore thus saith our Lord: Behold I will deliver this city into the hands of the Chaldees, and into the hands of the king of Babylon, and they shall take it.\n"
	"And the Chaldees shall come fighting against this city, and shall set it on fire, and burn it, and the houses, in whose tops they did sacrifice to Baal, and offered libaments to strange gods, to provoke me unto wrath.\n"
	"For the children of Israel, and the children of Juda were continually doing evil in mine eyes from their youth: the children of Israel which even until this present exasperate me in the work of their hands, saith our Lord.\n"
	"Because in fury and in mine indignation this city is made to me, from the day that they builded it, until this day, wherein it shall be taken out of my sight.\n"
	"For the malice of the children of Israel, and of the children of Juda, which they have done provoking me to wrath, they & their kings, their Princes, & their Priests, and their Prophets, the men of Juda, and the inhabitants of Jerusalem.\n"
	"And they have turned the backs to me, and not the faces: when I taught them early, & instructed them, & they would not hear that they might take discipline.\n"
	"And they have set their idols in the house, wherein my name is invocated, that they might pollute it.\n"
	"And they have built the excelses of Baal, which are in the valley of the son of Ennom, that they might consecrate their sons and their daughters to Moloch: which I commanded them not, neither hath it ascended into my heart, that they should do this abomination, & bring Juda into sin.\n"
	"And now for these things, thus saith our Lord the God of Israel to this city, whereof you say that it is delivered into the hands of the king of Babylon in sword, and in famine, and in pestilence.\n"
	"Behold I will gather them together out of all lands, to which I have cast them out in my fury, and in my wrath, and in my great indignation: and I will bring them again into this place, and will make them dwell confidently.\n"
	"And they shall be my people, and I will be their God.\n"
	"And I will give them one heart, and one way, that they may fear me all days: and it may be well with them, and with their children after them.\n"
	"And I will make an everlasting covenant with them: and will not cease to do them good: and I will give my fear in their heart, that they revolt not from me.\n"
	"And I will rejoice upon them, when I shall do them good: and I will plant them in this land in truth in my whole heart and in all my soul\n"
	"Because thus saith our Lord: As I have brought upon this people all this great evil: so will I bring upon them all the good, that I speak to them.\n"
	"And the fields shall be possessed in this land: whereof you say that it is desolate, because there is remaining no man nor beast, and it is given into the hands of the Chaldees.\n"
	"The fields shall be bought for money, and shall be written in a book, and the sign shall be stamped on, and a witness shall be taken, in the land of Benjamin, and round about Jerusalem, in the cities of Juda, and in the cities on the mountains, and in the champion cities, and in the cities that are toward the South: because I will convert their captivity, saith our Lord.";