const char* chap903 = "A child of one and twenty years was Sedecias when he began to reign: and eleven years he reigned in Jerusalem: and the name of his mother was Amital, the daughter of Jeremie of Lobna.\n"
	"And he did evil in the eyes of our Lord, according to all things that Joakim had done.\n"
	"Because the fury of our Lord was against Jerusalem, & against Juda, till he cast them away from his face: and Sedecias revolted from the king of Babylon.\n"
	"And it came to pass in the ninth year of his reign, in the tenth month, the tenth of the month, came Nabuchodonosor the king of Babylon, himself and all his army against Jerusalem, and they besieged it, and built against it munitions round about.\n"
	"And the city was besieged until the eleventh year of king Sedecias.\n"
	"And in the fourth month, the ninth of the month, a famine possessed the city: and there were no victuals for the people of the land.\n"
	"And a breach was made into the city, and all the men of war fled, and went out of the city in the night by the way of the gate that is between the two walls, and leadeth to the king's garden (the Chaldees besieging the city round about) & they departed by the way, that leadeth into the wilderness.\n"
	"But the army of the Chaldees pursued the king: and they apprehended Sedecias in the desert, which is beside Jericho: and all his train fled scattering from him.\n"
	"And when they had taken the king, they brought him to the king of Babylon into Reblatha, which is in the land of Emath; and he spake to him judgements.\n"
	"And the king of Babylon killed the sons of Sedecias before his eyes: yea & all the Princes of Juda he slew in Reblatha.\n"
	"And he plucked out the eyes of Sedecias, & bound him with fetters, & the king of Babylon brought him into Babylon: and he put him in the prison house even to the day of his death.\n"
	"And in the fifth month, the tenth of the month, the same is the nineteenth year of Nabuchodonosor the king of Babylon: came Nabuzardan the Prince of the warfare, who stood before the king of Babylon in Jerusalem.\n"
	"And he burnt the house of our Lord. And the king's house, and all the houses of Jerusalem, and every great house he burnt with fire.\n"
	"And all the host of the Chaldees that was with the Prince of the warfare, destroyed all the wall of Jerusalem round about.\n"
	"But of the poor of the people, and of the rest of the vulgar sort, which remained in the city, and of the fugitives, that were fled to the king of Babylon, and the rest of the multitude, Nabuzardan the Prince of the warfare transported.\n"
	"But of the poor of the land Nabuzardan the prince of the warfare left some to be dressers of vineyards, and husbandmen.\n"
	"The brazen pillars also, that were in the house of our Lord, and the feet, and the sea of brass, that was in the house of our Lord, the Chaldees brake: and they took all the brass of them into Babylon.\n"
	"And the kettles, and the fleshhooks, and the psalteries, and the phials, and the little mortars, and all the brazen vessels, that had been in the ministry, they took:\n"
	"and the water pots, and the censers, and the pitchers, and the basins, and the candlesticks, & the mortars, & the goblets: as many as of gold, of gold, & as many as of silver, of silver, did the Prince of the warfare take:\n"
	"and two pillars, & one sea, & twelve oxen of brass, that were under the feet, which king Salomon had made in the house of our Lord: there was no weight of the brass of all these vessels.\n"
	"And concerning the pillars, there were eighteen cubits of height in one pillar: & a cord of twelve cubits did compass it about: moreover the thickness thereof, of four fingers, and within it was hollow.\n"
	"And the little heads of brass upon both: the height of one little head, of five cubits: and the little nets, and the pomegranates upon the crown round about, all of brass. Likewise of the second pillar, & the pomegranates.\n"
	"And there were ninety six pomegranates hanging down: and all the pomegranates an hundred, were compassed with little nets.\n"
	"And the master of the warfare took Saraias the chief Priest, and Sophonias the second Priest: and the three keepers of the entry.\n"
	"And of the city he took one eunuch, that was chief over the men of war: and seven men of them, that saw the king's face, that were found in the city: and a scribe the captain of the soldiers, who tried the young soldiers: and three score of the people of the land, that were found in the midst of the city.\n"
	"And Nabuzardan the Prince of the warfare took them, and he brought them to the king of Babylon into Reblatha.\n"
	"And the king of Babylon struck them: and he killed them in Reblatha in the land of Emath: and Juda was transported from his land.\n"
	"This is the people, which Nabuchodonosor transported: In the seventh year, Jews three thousand and twenty three.\n"
	"In the eighteenth year of Nabuchodonosor from Jerusalem souls eight hundred thirty two.\n"
	"In the three and twentieth year of Nabuchodonosor, Nabuzardan the Prince of the warfare transported of the Jews seven hundred forty five souls. All the souls therefore were four thousand six hundred.\n"
	"And it came to pass in the seven and thirtieth year of the transmigration of Joachin the king of Juda, the twelfth month, the five and twentieth of the month, Evilmerodach the king of Babylon lifted up in the very year of his reign, the head of Joachin the king of Juda, and he brought him out of the prison house.\n"
	"And he spake with him good things, & he set his throne above the thrones of the kings, that were after himself in Babylon.\n"
	"And he changed his prison garments, and he did eat bread before him always all the days of his life.\n"
	"And his allowance of meat, a continual provision of meat was given him by the king of Babylon, every day a certain, even unto the day of his death, all the days of his life.";