const char* chap910 = "FOR the which thing the Lord our God hath established his word, that he spake to us, and to our judges, that have judged Israel, and to our kings, and to our princes, and to all Israel and Juda:\n"
	"that our Lord might bring upon us great evils, which were not done under the heaven, as have been done in Jerusalem, according to the things that are written in the law of Moyses:\n"
	"that a man should eat the flesh of his son, and the flesh of his daughter.\n"
	"And he hath given them under the hand of all the kings, that are round about us into reproach, and into desolation among all peoples, into which our Lord hath dispersed us.\n"
	"And we are made underneath, and not above: because we have sinned to the Lord our God, in not obeying his voice.\n"
	"To the Lord our God justice: but to us, and to our fathers confusion of face, as is this day.\n"
	"Because our Lord hath spoken upon us all these evils, that are come upon us:\n"
	"and we have not besought the face of the Lord our God, to return every one of us from our most wicked ways.\n"
	"And our Lord hath watched in evils, and hath brought them upon us: because our Lord is just in all his works, which he hath commanded us:\n"
	"and we have not heard his voice to walk in the precepts of our Lord, which he hath given before our face.\n"
	"And now o Lord God of Israel, which brought out thy people out of the Land of Aegypt in a strong hand, and in signs, and in wonders, and in thy great strength, and in a mighty arm, and madest thee a name as is this day:\n"
	"we have sinned, we have done impiously, we have dealt unjustly o Lord our God, in all thy justices.\n"
	"Let thy wrath be turned away from us: because we are left a few among the nations, where thou hast dispersed us.\n"
	"Hear o Lord our prayers, and our petitions, and bring us out for thine own sake: and grant us to find grace before their face, that have led us away:\n"
	"that all the earth may know that thou art the Lord our God, and that thy name is invocated upon Israel, and upon his stock.\n"
	"Look o Lord from thy holy house upon us, and incline thine ear, and hear us.\n"
	"Open thine eyes, & see: because the dead that are in hell, whose spirit is taken from their bowels, shall not give honour and justification to our Lord:\n"
	"but the soul, that is sorrowful for the greatness of evil, and goeth crooked, and weak, and the eyes failing, and the hungry soul giveth glory and justice to thee their Lord.\n"
	"For not according to the justices of our fathers do we pour out prayers, and ask mercy before thy sight o Lord our God:\n"
	"but because thou hast sent thy wrath, and thy fury upon us, as thou hast spoken by the hand of thy servants the prophets, saying:\n"
	"Thus saith our Lord: Bow down your shoulder, & your neck, and do works for the king of Babylon: and you shall sit in the land, which I have given to your fathers.\n"
	"But if you will not hear the voice of the Lord your God, to work for the king of Babylon: I will make you to fail out of the cities of Juda, and from without Jerusalem,\n"
	"and I will take from you the voice of mirth, and the voice of joy, and the voice of the bridegroom, and the voice of the bride, and all the land shall be without foot step that inhabit it.\n"
	"And they heard not thy voice, to work for the king of Babylon: and thou hast established thy words, which thou spakest by the hands of thy servants the prophets, that the bones of our kings, and of our fathers should be transported out of their place:\n"
	"and behold they are cast forth in the heat of the sun, and in the frost of the night: and they are dead in very sore pains, in famine, and by sword, and by casting forth.\n"
	"And hast made the temple, in which thy name was there invocated, as it is this day, for the iniquity of the house of Israel, and of the house of Juda.\n"
	"And thou hast done in us o Lord our God according to all thy goodness, and according to all that thy great compassion:\n"
	"as thou spakest by the hand of thy servant Moyses, in the day, that thou didst command him to write thy law before the children of Israel,\n"
	"saying: If you will not hear my voice, this great multitude shall be turned into a very little one among the Gentiles, whither I will disperse them:\n"
	"because I know that the people will not hear me. for it is a people of a stiff neck: and they shall be converted to their heart in the land of their captivity:\n"
	"and they shall know that I am the Lord their God: and I will give them a heart, and they shall understand: and ears, and they shall hear.\n"
	"And they shall praise me in the land of their captivity, and shall be mindful of my name.\n"
	"And they shall turn away themselves from their hard back, and from their malignant works: because they shall remember the way of their fathers, that sinned against me.\n"
	"And I will recall them back into the land, which I sware to their fathers, Abraham, Isaac, and Jacob, and they shall have dominion thereof: and I will multiply them, and they shall not be lessened.\n"
	"And I will establish unto them another testament everlasting, that I be their God, and they shall be my people: and I will no more move my people, the children of Israel from the land, that I have given them.";