const char* chap915 = "And it came to pass in the thirtieth year, in the fourth, in the fifth of the month, when I was in the midst of the captives beside the river Chobar, the heavens were opened, and I saw the visions of God.\n"
	"In the fifth of the month, the same is the fifth year of the transmigration of king Joachin,\n"
	"the word of our Lord was made to Ezechiel the son of Buzi Priest in the land of the Chaldees, by the river Chobar: and there the hand of our Lord was made upon him.\n"
	"And I saw, and behold a whirlwind came from the North: & a great cloud, and a fire involving, & brightness round about it: and out of the midst thereof as it were the form of amber, that is, out of the midst of the fire.\n"
	"and out of the midst thereof the similitude of four living creatures: and this was their look: the similitude of a man in them.\n"
	"There were four faces to one, and four wings to one.\n"
	"Their feet straight feet, and the sole of their foot as the sole of a calf's foot, and sparks as the form of glowing brass.\n"
	"And the hands of a man under their wings in four parts: and they had faces, and wings by the four parts.\n"
	"And the wings of them were joined one to another. They returned not when they went: but every one went before his face.\n"
	"And the similitude of their countenance: the face of a man, and the face of a lion on the right hand of them four: and the face of an oxe, on the left hand of them four: and the face of an eagle over them four.\n"
	"And their faces, and their wings were stretched out above: two wings of every one were joined, and two covered their bodies:\n"
	"and every one of them walked before his face: where the force of the spirit was, thither they went: neither did they return when they went: neither did they return when they walked.\n"
	"And the similitude of the living creatures, their look as it were of coals of burning fire, and as it were the resemblance of lamps. This was the vision running in the midst of the living creatures, brightness of fire, and from the fire lightning going forth.\n"
	"And the living creatures went, and returned after the similitude of glistering lightning.\n"
	"And when I beheld the living creatures, there appeared one wheel upon the earth by the living creatures, having four faces.\n"
	"And the shape of the wheels, and the work of them, as it were appearance of the sea: and one similitude of them four: and their appearance and work, as if it were a wheel in the midst of a wheel.\n"
	"By their four parts going they went: and they returned not when they walked.\n"
	"There was a stature also to the wheels, and height, and a fearful form: and the whole body was full of eyes round about them four.\n"
	"And when the living creatures walked, the wheels also walked together by them: and when the living creatures were lifted up from the earth, the wheels also were lifted up together.\n"
	"Whithersoever the spirit went, thither the spirit going, the wheels also were lifted up withal, following it: for the spirit of life was in the wheels.\n"
	"With them going they went, and with them standing they stood, and with them lifted up from the earth, the wheels also were lifted up together, following them: because the spirit of life was in the wheels.\n"
	"And a similitude over the heads of the living creatures of the firmament, as it were the sight of crystal dreadful, and stretched out over their heads above.\n"
	"And under the firmament the wings of them straight one toward another, every one with two wings covered his body, and the other was covered in like manner.\n"
	"And I heard the sound of the wings, as it were the sound of many waters, as it were the sound of the high God, when they walked, it was as the voice of a multitude, as the sound of a camp, and when they stood, their wings were let down.\n"
	"For when a voice was made above the firmament, that was over their head, they stood, and let down their wings.\n"
	"And above the firmament, that hung over their head, as it were the form of the sapphire stone the similitude of a throne, and upon the similitude of the throne, a similitude as it were the shape of a man above.\n"
	"And I saw as it were the form of amber, as the resemblance of fire within it round about: from his loins & upward, and from his loins downward, I saw as it were the resemblance of fire glistering round about.\n"
	"As the form of the bow when it is in a cloud on a day of rain, this was the form of the brightness round about.";