const char* chap926 = "And the word of our Lord was made to me, saying:\n"
	"Son of man, thou dwellest in the midst of an exasperating house: which have eyes to see, and see not: and ears to hear, and hear not: because it is an exasperating house.\n"
	"Thou therefore, o son of man, make thee vessels of transmigration, and thou shalt flit by day before them: and thou shalt flit out of thy place to another place in their sight; if perhaps they will behold: because it is an exasperating house.\n"
	"And thou shalt carry forth thy vessels as the vessels of one flitting by day in the sight of them: and thou shalt go forth at even before them, as one goeth forth that flitteth.\n"
	"Before their eyes dig to thee through the wall: and thou shalt go forth through it.\n"
	"In their sight on shoulders thou shalt be carried, in the dark thou shalt be carried out: thou shalt cover thy face, and shalt not see the earth: because I have given thee a portending sign to the house of Israel.\n"
	"I did therefore as he had commanded me: I carried my vessels as the vessels of one flitting by day: and at even I digged to me through the wall with my hand: and I went forth in the dark, and was carried on shoulders in their sight.\n"
	"And the word of our Lord was made to me in the morning, saying:\n"
	"Son of man, hath not the house of Israel the exasperating house said to thee: What doest thou?\n"
	"Say to them: Thus saith our Lord God: This burden upon the Prince, that is in Jerusalem, and upon all the house of Israel, which is in the midst of them.\n"
	"Say: I am your portending sign, as I have done, so shall it be done to them, into transmigration, and into captivity shall they go.\n"
	"And the Prince, that is in the midst of them, shall be carried on shoulders, he shall go forth in the dark: they shall dig through the wall to bring him out: his face shall be covered, that he may not see the earth with his eye.\n"
	"And I will stretch forth my net upon him, and he shall be taken in my net: and I will bring him into Babylon into the land of the Chaldees, and he shall not see it, and there he shall die.\n"
	"And all that are about him, his guard, and his troops I will disperse into every wind: and I will draw the sword after them.\n"
	"And they shall know that I am the Lord, when I shall have dispersed them in the Gentiles, and scattered them in the lands.\n"
	"And I will leave of them a few men from the sword, and the famine, and the pestilence: that they may declare all their wicked deeds in the Gentiles, to which they shall enter: and they shall know that I am the Lord.\n"
	"And the word of our Lord was made unto me, saying:\n"
	"Son of man, eat thy bread in trouble: yea & drink thy water in haste and sorrowfulness.\n"
	"And thou shalt say to the people of the land: Thus saith our Lord God to them that dwell in Jerusalem in the land of Israel: Their bread they shall eat in carefulness, and their water in desolation they shall drink: that the land may be made desolate from the multitude thereof, for the iniquity of all that dwell therein.\n"
	"And the cities, that are now inhabited, shall be desolate, and the land desert: and you shall know that I am the Lord.\n"
	"And the word of our Lord was made to me, saying:\n"
	"Son of man, what is this proverb with you in the land of Israel saying: The days shall be deferred to a long time, and all vision shall perish.\n"
	"Therefore say to them: Thus saith our Lord God: I will make this proverb cease, neither shall it any more be commonly said in Israel: and speak to them that the days are at hand, and the word of every vision.\n"
	"for all vision shall no more be in vain, nor divination ambiguous in the midst of the children of Israel.\n"
	"Because I^ the Lord will speak: and what word soever I shall speak, shall also be done, it shall not be prolonged any more: but in your days ye exasperating house, will I speak the word, and will do it, saith our Lord God.\n"
	"And the word of our Lord was made to me, saying:\n"
	"Son of man, behold the house of Israel, they that say: The vision, that this man seeth, is for many days: and this man Prophesieth long times.\n"
	"Therefore say to them: Thus saith our Lord God: Every word of mine shall be prolonged no further: the word that I shall speak, shall be accomplished, saith our Lord God.";