const char* chap928 = "And men of the ancients of Israel came to me, and sat before me.\n"
	"And the word of our Lord was made to me, saying:\n"
	"Son of man, These men have put their uncleanness in their hearts, and the scandal of their iniquity they have set against their face: what, being asked shall I answer them?\n"
	"For this cause speak to them, and thou shalt say to them: Thus saith our Lord God: Man, man of the house of Israel, that shall put his uncleanness in his heart, and set the scandal of his iniquity against his face, and shall come to the Prophet asking me by him: I^ the Lord will answer him in the multitude of his uncleanness:\n"
	"that the house of Israel may be taken in their heart, wherewith they have revolted from me in all their idols.\n"
	"Therefore say to the house of Israel: Thus saith our Lord God: Convert, and depart from your idols, and from all your contaminations turn away your faces.\n"
	"Because man man of the house of Israel and of the proselytes, whosoever shall be a stranger in Israel, if he be alienated from me, and put his idols in his heart, and set the scandal of iniquity against his face, and come to the Prophet to ask me by him: I^ the Lord will answer him by myself.\n"
	"And I will set my face upon that man, and will make him for an example, & for a proverb, & will destroy him out of the midst of my people: & you shall know that I am the Lord.\n"
	"And the Prophet when he shall err, & shall speak a word: I^ the Lord have deceived that Prophet: and I will stretch forth my hand upon him, and will rase him out of the midst of my people Israel.\n"
	"And they shall carry their iniquity: according to the iniquity of him that asketh, so shall the iniquity of the Prophet be.\n"
	"That the house of Israel may no more err from me, nor be polluted in all their prevarications: but may be my people, & I may be their God, saith the Lord of hosts.\n"
	"And the word of our Lord was made to me, saying:\n"
	"Son of man, the land when it shall sin to me, that transgressing it transgresseth, I will stretch forth my hand upon it, and will break the rod of the bread thereof: and I will send famine into it, and will kill out of it man and beast.\n"
	"And if these three men shall be in the midst thereof, Noe, Daniel, & Job: they by their justice shall deliver their own souls, saith the Lord of hosts.\n"
	"And if I shall bring most evil beasts also upon the land, to waste it; and it be without passage, for that there is none can pass because of the beasts:\n"
	"These three men if they shall be therein, I live, I, saith our Lord, that they shall deliver neither sons nor daughters: but themselves alone shall be delivered, and the land shall be made desolate.\n"
	"Or if I shall bring the sword in upon that land, and shall say to the sword: Pass through the land: and shall kill out of it man & beast:\n"
	"And these three men shall be in the midst thereof: I live, I, saith our Lord God, they shall not deliver sons nor daughters, but themselves alone shall be delivered.\n"
	"And if I shall send the pestilence also in upon that land, and shall pour out mine indignation upon it in blood, to take away out of it man and beast:\n"
	"And Noe, & Daniel, & Job shall be in the midst thereof: live I, saith our Lord God, that son and daughter they shall not deliver: but themselves by their justice shall deliver their own souls.\n"
	"Because thus saith our Lord: That and if I shall send in upon Jerusalem my four very sore judgements, the sword, and famine, and evil beasts, & the pestilence: to kill out of it man, and beast:\n"
	"Yet shall there be left in it salvation of some bringing out sons, and daughters: behold they shall go forth to you, & you shall see their way, and their inventions: and you shall be comforted upon the evil, that I have brought upon Jerusalem in all things, that I have brought in upon it.\n"
	"And they shall comfort you, when you shall see their way, & their inventions: and you shall know that I have not in vain done all things, which I have done in it, saith our Lord God.";