const char* chap932 = "And the word of our Lord was made to me, saying:\n"
	"What is that among you, you turn a parable into this proverb in the land of Israel, saying: The fathers did eat a sour grape, & the teeth of the children are set on edge?\n"
	"Live I, saith our Lord God, if this parable shall be unto you any more for a proverb in Israel.\n"
	"Behold all souls are mine: as the soul of the father, so also the soul of the son is mine: the soul that shall sin, the same shall die.\n"
	"And a man if he shall be just, and hath done judgement and justice,\n"
	"hath not eaten on the mountains, and not lifted up his eyes to the idols of the house of Israel: and hath not violated his neighbour's wife, & approached not to a menstruous woman:\n"
	"and made no man sorrowful: hath restored the pledge to the debter, taken nothing away by violence: hath given his bread to the hungry, and covered the naked with a garment:\n"
	"hath not lent to usury, and not taken more: hath turned away his hand from iniquity, and done true judgement between man & man:\n"
	"hath walked in my precepts, and kept my judgements, to do truth: this man is just, living he shall live, saith our Lord God.\n"
	"And if he hath begotten a son that is a robber shedding blood, and he do one of these things:\n"
	"and that doth not indeed all these things, but eateth on the mountains, and defileth his neighbour's wife:\n"
	"that maketh the needy and poor sorrowful, violently committeth robberies, restoreth not the pledge, & lifteth his eyes to idols, doth abomination:\n"
	"that giveth to usury, & taketh more: what, shall he live? He shall not live. Whereas he hath done all these detestable things, dying he shall die, his blood shall be upon him.\n"
	"But and if he hath begotten a son, that seeing all his father's sins, which he hath done, is afraid, and shall not do the like to them:\n"
	"hath not eaten upon the mountains, & not lifted up his eyes to the idols of the house of Israel, & hath not violated his neighbour's wife:\n"
	"and hath made no man sorrowful, hath not withheld the pledge, and hath not violently committed robbery, hath given his bread to the hungry, and covered the naked with clothing:\n"
	"hath turned away his hand from injury of the poor, hath not taken usury and overplus, hath done my judgements, hath walked in my precepts: this man shall not die in the iniquity of his father, but living he shall live.\n"
	"His father because he did calumniate, and did violence to his brother, and wrought evil in the midst of his people, behold he is dead in his own iniquity.\n"
	"And you say: Why hath not the son borne the iniquity of his father? Verily because the son hath wrought judgement and justice, he hath kept all my precepts, and done them, living he shall live.\n"
	"The soul that shall sin, the same shall die: the son shall not bear the iniquity of the father, and the father shall not bear the iniquity of the son: the justice of the just shall be upon him, and the impiety of the impious shall be upon him.\n"
	"But if the impious shall do penance from all his sins, which he hath wrought, and shall keep all my precepts, and do judgement, and justice: living he shall live, and shall not die.\n"
	"All his iniquities, which he hath wrought, I will not remember them: in his justice which he hath wrought, he shall live.\n"
	"Why, is the death of a sinner my will, saith our Lord God, and not that he convert from his ways, and live?\n"
	"But if the just man shall turn away himself from his justice, and do iniquity according to all the abominations, which the impious useth to work, shall he live? All his justices, which he had done, shall not be remembered: in the prevarication, which he hath prevaricated, and in his sin, which he hath sinned, in them he shall die.\n"
	"And you have said: The way of our Lord is not right. Hear ye therefore, o house of Israel: What, is not my way right, and are not rather your ways perverse?\n"
	"For when the just shall turn away himself from his justice, and doth iniquity, he shall die in them: in the injustice, that he hath wrought he shall die.\n"
	"And when the impious shall turn away himself from his impiety, which he hath wrought, and shall do judgement and justice he shall vivificate his soul.\n"
	"For considering, and turning away himself from all his iniquities, which he hath wrought, living he shall live, and not die.\n"
	"And the children of Israel say: The way of our Lord is not right. What, are not my ways right, o house of Israel, and not rather your ways perverse?\n"
	"Therefore will I judge every man according to his ways, o house of Israel, saith our Lord God. Convert, and do penance from all your iniquities: & iniquity shall not be a ruin to you.\n"
	"Cast away from you all your prevarications, wherein you have prevaricated, and make to yourselves a new heart, and a new spirit: and why will you die, o house of Israel?\n"
	"Because I will not the death of him that dieth, saith our Lord God, return ye, and live.";