const char* chap941 = "And the word of our Lord was made to me, saying:\n"
	"Thou therefore o son of man, take up a lamentation upon Tyre:\n"
	"And thou shalt say to Tyre, which dwelleth in the entrance of the sea, being the traffic of peoples to many islands: Thus saith our Lord God: o Tyre, thou hast said: I am of perfect beauty,\n"
	"& situated in the heart of the sea. Thy borderers, which builded thee have accomplished thy beauty:\n"
	"with the fir trees of Sanir they builded thee, with all the boards of the sea: they took the cedar from Libanus, to make thee a mast.\n"
	"Oaks of Basan they have hewed for thine oars: & thy banks they have made thee of the ivory of India, and little cabins of the islands of Italy.\n"
	"Various silk of Aegypt was woven for thy sail, to be put on the mast: hyacinth, and purple out of the islands of Elisa, were made thy covering.\n"
	"The inhabitants of Sidon, and the Aradians were thy rowers: thy wise men, o Tyre, were made thy governors.\n"
	"The ancients of Gebal, & wisemen thereof had mariners to the service of thy diverse stuff: all the ships of the sea, and their mariners have been in the people of thy traffic.\n"
	"The Persians, and Lydians, and the Libyans were in thine army thy men of war: the buckler, and helmet they did hang in thee for thine ornament.\n"
	"The children of Arad were with thine army upon thy walls round about: yea and the Pygmeians, that were in thy towers, hung up their quivers on thy walls round about: they accomplished thy beauty.\n"
	"They of Carthage thy merchants, for the multitude of all riches, with silver, iron, tin, and lead did they replenish thy marts.\n"
	"Greece, Thubal, and Mosoch, they were thy merchants: slaves, and vessels of brass they brought to thy people.\n"
	"From the house of Thogorma they brought horses, and horsemen, and mules to thy market.\n"
	"The children of Dedan were thy merchants: many islands the traffic of thy hand, teeth of ivory, and of Heben they exchanged for thy price.\n"
	"The Syrian was thy merchant for the multitude of thy works, the precious stone, and purple, and branched works, and fine linen, and silk, and chodchod they did set forth in thy market.\n"
	"Juda and the land of Israel they were thy merchants in the principal corn: balm, and honey, and oil, and resin they did set forth in thy marts.\n"
	"The Damacene was thy merchant in the multitude of thy works, in the multitude of diverse riches, in fat wine, in wools of the best colour.\n"
	"Dan, and Greece, and Mosel in thy marts have set forth wrought iron: stacte, and calamus were in thy merchandise.\n"
	"Dedan thy merchants in tapestry for seats.\n"
	"Arabia, and all the Princes of Cedar, they were the merchants of thy hand: with lambs, and rams, and kids thy merchants came to thee.\n"
	"The sellers of Saba, and Reema, they were thy merchants: with principal spices, and precious stone, and gold, which they did set forth in thy market.\n"
	"Haran, and Chene, and Eden, thy merchants: Saba, Assur, and Chelmad thy sellers.\n"
	"They were thy merchants in diverse manner, with folded pieces of hyacinth, and of embroidered cloths, and of precious riches, which were wrapped up, and bound with cords: cedars also they had in thy merchandise.\n"
	"The ships of the sea, thy chief in thy merchandise: and thou was replenished, and glorified exceedingly in the heart of the sea.\n"
	"In many waters have thy rowers brought thee: the southwind hath broken thee in the heart of the sea.\n"
	"Thy riches, and thy treasures, and thy manifold furniture, thy mariners, and thy governers, which hold thy stuff, and were chief over thy people: thy men of war also, that were in thee with all thy multitude, that is in the midst of thee: shall fall in the heart of the sea in the day of thy ruin.\n"
	"At the sound of the cry of thy governors shall the navies be troubled.\n"
	"And all they that held oar shall go down out of their ships: the mariners, and all the governors of the sea shall stand on the land:\n"
	"and they shall bewail upon thee with a loud voice, and shall cry bitterly: and they shall cast dust upon their heads, and shall be sprinkled with ashes.\n"
	"And they shall shave baldness upon thee, and shall be girded with haircloths: and they shall weep for thee in bitterness of soul with most bitter weeping.\n"
	"And they shall take up a mournful song upon thee, and shall lament thee: What city is as Tyre, which is become silent in the midst of the sea?\n"
	"Which in the going forth of thy merchandise from the sea didst fill many peoples: in the multitude of thy riches, and of thy peoples hast enriched the kings of the earth.\n"
	"Now thou art destroyed by the sea, thy riches are in the bottom of the waters, and all the multitude, that was in the midst of thee, are fallen.\n"
	"All the inhabitants of the islands are astonished upon thee: & all the kings of the same being striken with tempest have changed their looks.\n"
	"The merchants of peoples have hissed upon thee: thou art brought to nothing, and thou shalt not be even for ever.";