const char* chap944 = "And the word of our Lord was made to me, saying:\n"
	"Son of man prophesy, and say: Thus saith our Lord God: Howl ye, woe, woe to the day:\n"
	"because the day is near, and the day of our Lord approacheth: the day of a cloud, the time of the Gentiles shall be.\n"
	"And the sword shall come into Aegypt: & there shall be fear in Aethiopia, when the wounded shall fall in Aegypt, & the multitude thereof shall be taken away, and the foundations thereof be destroyed.\n"
	"Aethiopia, and Libya, and the Lydians, and all the rest of the common people, and Chub, and the children of the land of covenant, shall fall with them by the sword.\n"
	"Thus saith our Lord God: And they shall fall that underprop Aegypt, and the pride of the empire thereof shall be destroyed: from the tower of Siena shall they fall in it by the sword, saith our Lord the God of hosts.\n"
	"And they shall be dissipated in the midst of desolate lands, and the cities thereof shall be in the midst of desert cities.\n"
	"And they shall know that I am the Lord: when I shall have given fire in Aegypt, and all the aiders thereof shall be broken.\n"
	"In that day shall messengers go forth from my face in galleys to terrify the confidence of Aethiopia, and there shall be fear among them in the day of Aegypt: because it shall come without doubt.\n"
	"Thus saith our Lord God: I will make the multitude of Aegypt to cease in the hand of Nabuchodonosor the king of Babylon.\n"
	"He and his people with him the strongest of the Gentiles shall be brought to destroy the land: and they shall draw their swords upon Aegypt: and shall fill the land with the slain.\n"
	"And I will make the channels of the rivers dry, and will deliver the land into the hands of the most wicked: and will dissipate the land and the fullness thereof in the hands of aliens, I^ the Lord have spoken.\n"
	"Thus saith our Lord God: And I will destroy the idols, and I will make the idols to cease out of Memphis: and duke of the land of Aegypt there shall be no more: and I will give terror in the land of Aegypt.\n"
	"And I will destroy the land of Phathures, and will give fire in Taphnis, and will do judgements in Alexandria.\n"
	"And I will pour out mine indignation upon Pelusium the strength of Aegypt, and will kill the multitude of Alexandria,\n"
	"And will give fire in Aegypt: as a woman in travail shall Pelusium sorrow, and Alexandria shall be dissipated, and in Memphis daily distresses.\n"
	"The young men of Heliopolis, and of Bubasti shall fall by the sword, and themselves shall be led captive.\n"
	"And in Taphnis the day shall wax black, when I shall have broken there the sceptres of Aegypt, and the pride of the might thereof shall fail in it: the cloud shall cover her, & her daughters shall be led into captivity.\n"
	"And I will do judgements in Aegypt: & they shall know that I am the Lord.\n"
	"And it came to pass in the eleventh year, in the first month, in the seventh of the month, the word of our Lord was made to me, saying:\n"
	"Son of man, I have broken the arm of Pharao king of Aegypt: and behold it is not wound up, that health might be restored to it, that it might be bound with cloths, & swaddled with linen clouts, that recovering strength it might hold the sword.\n"
	"Therefore thus saith our Lord God: Behold I to Pharao king of Aegypt, and I will break into pieces his strong arm, already broken: and I will cast down the sword out of his hand:\n"
	"and will disperse Aegypt among the Gentiles, & will scatter them in the lands.\n"
	"And I will strengthen the arms of the king of Babylon, and will give my sword in his hand: and I will break the arms of Pharao, and the slain before his face shall groan with groanings.\n"
	"And I will strengthen the arms of the king of Babylon, and the arms of Pharao shall fall, and they shall know that I am the Lord, when I shall give my sword into the hand of the king of Babylon, and he shall have stretched it forth upon the Land of Aegypt:\n"
	"And I will disperse Aegypt into nations, and will scatter them into lands, and they shall know that I am the Lord.";