const char* chap946 = "And it came to pass the twelfth year, in the twelfth month, in the first of the month, the word of our Lord was made to me, saying:\n"
	"Son of man, take up a lamentation upon Pharao the king of Aegypt, & thou shalt say to him: Thou art likened to the Lion of the Gentiles, and the dragon, that is in the sea: and thou didst strike with the horn in thy rivers, and didst trouble the waters with thy feet, and didst conculcate their streams.\n"
	"Therefore thus saith our Lord God: I will spread my net upon thee in the multitude of many peoples, and I will draw thee out in my net.\n"
	"And I will throw thee forth on the ground, upon the face of the field will I cast thee away: and I will make all the fowls of heaven to dwell upon thee, and I will fill of thee the beasts of all the earth.\n"
	"And I will give thy flesh upon the mountains, and will fill the little hills with thy corruption.\n"
	"And I will water the earth with the stench of thy blood upon the mountains, and the valleys shall be filled of thee.\n"
	"And I will cover the heavens, when thou shalt be extinguished, and I will make the stars thereof to wax black: the sun I will cover with a cloud, & the moon shall not give her light.\n"
	"I will make all the lights of heaven to mourn upon thee: & I will give darkness upon thy land, saith our Lord God, when thy wounded shall fall in the midst of the land, saith our Lord God.\n"
	"And I shall provoke to anger the heart of many peoples, when I shall have brought in thy destruction in the Gentiles upon the lands, which thou knowest not.\n"
	"And I will make many peoples to be astonished upon thee, and their kings with exceeding horror shall be afraid upon thee, when my sword shall begin to fly upon their faces: and they shall be astonished suddenly, every one for his life, in the day of thy ruin.\n"
	"Because thus saith our Lord God:\n"
	"The sword of the king of Babylon shall come to thee, in the swords of the valiants will I overthrow thy multitude: invincible are all these Gentiles: and they shall waste the pride of Aegypt, and the multitude thereof shall be dissipated.\n"
	"And I will destroy all the beasts thereof, that were upon very many waters: and the foot of man shall trouble them no more, neither shall the hoof of beasts trouble them.\n"
	"Then will I make their waters most pure, and their rivers I will bring as oil, saith our Lord God.\n"
	"When I shall have made the Land of Aegypt desolate: & the land shall be made desert of her fullness, when I shall have strucken all the inhabitants thereof: & they shall know that I am the Lord.\n"
	"It is lamentation, and they shall lament it, the daughters of the Gentiles shall lament it, upon Aegypt, and upon the multitude thereof they shall lament it, saith our Lord God.\n"
	"And it came to pass in the twelfth year, in the fifteenth of the month, the word of our Lord was made to me, saying:\n"
	"Son of man, sing a mourning song upon the multitude of Aegypt: and pluck her down, herself, and the daughters of the strong nations, to the lowest earth, with them that go down into the lake.\n"
	"Fairer than whom art thou? Descend, & sleep with the uncircumcised.\n"
	"In the midst of the slain by the sword they shall fall. The sword is given, they have drawn her, and all her peoples.\n"
	"The most mighty of the strong shall speak to him from the midst of hell, which went down with his helpers, and slept uncircumcised, slain by the sword.\n"
	"There Assur, and all his multitude: round about him their graves, all the slain, and they that fell by the sword.\n"
	"Whose graves were made in the lowest lakes: and his multitude was made round about his grave: all the slain, and they that fell by the sword, which sometime had given fear in the land of the living.\n"
	"There Aelam, and all the multitude thereof round about her grave. All these slain, and falling by the sword: that went down uncircumcised to the lowest earth: which did put their terror in the land of the living, and they have borne their ignominy with them, that go down into the lake.\n"
	"In the midst of their slain they have set her couch among all her peoples: round about him their grave, and these uncircumcised, and slain by the sword, for they gave their terror in the land of the living, and have borne their ignominy with them, that descend into the lake: they are laid in the midst of the slain.\n"
	"There Mosoch, & Thubal, & all their multitude: round about him their graves: all these uncircumcised, and slain, and falling by the sword: because they gave their fear in the land of the living:\n"
	"And they shall not sleep with the valiants, and them that fell, and the uncircumcised, that went down to hell with their weapons, and put their swords under their heads, and their iniquities were in their bones: because they were made the terror of the valiants in the land of the living.\n"
	"And thou therefore shalt be destroyed in the midst of the uncircumcised, and shalt sleep with the slain by the sword.\n"
	"There Idumea, and her kings, and all her Princes, which were given with their host with the slain by the sword: and which slept with the uncircumcised, & with them that go down into the lake.\n"
	"There all the Princes of the North, and all the hunters: which were brought down with the slain, fearing, and in their strength confounded: which slept uncircumcised with the slain by the sword, & have borne their ignominy with them, that go down into the lake.\n"
	"Pharao saw them, and he was comforted upon all his multitude, which was slain by the sword, Pharao, & all his host, saith our Lord God:\n"
	"because I gave his terror in the land of the living, and he slept in the midst of the uncircumcised with the slain by the sword: Pharao and all his multitude, saith our Lord God.";