const char* chap962 = "And these are the names of the tribes from the borders of the North, by the way of Hethalon, as they go to Emath, the court of Enan the border of Damascus toward the North, by the way of Emath. And the East quarter thereof to the sea shall be for Dan one.\n"
	"And to the border of Dan, from the East quarter even to the quarter of the Sea, for Aser one:\n"
	"and upon the border of Aser, from the East quarter even to the quarter of the Sea, for Nephthali one.\n"
	"And upon the border of Nephthali, from the East quarter even to the quarter of the Sea, for Manasses one.\n"
	"And upon the border of Manasses, from the East quarter even to the quarter of the Sea, for Ephraim one.\n"
	"And upon the border of Ephraim, from the East quarter even to the quarter of the Sea, for Ruben one.\n"
	"And upon the border of Ruben, from the East quarter even to the quarter of the Sea, for Juda one.\n"
	"And upon the border of Juda, from the East quarter even to the quarter of the Sea, shall be the first fruits, which you shall separate, five and twenty thousand of breadth & of length, as every portion from the East quarter to the quarter of the Sea: and the sanctuary shall be in the midst thereof.\n"
	"The first fruits, which you shall separate to our Lord: the length of five and twenty thousand, and the breadth of ten thousand.\n"
	"And these shall be the first fruits of the sanctuary of the Priests: toward the North of length five and twenty thousand, and toward the Sea of breadth ten thousand. Yea and toward the East of breadth ten thousand, and toward the South of length five and twenty thousand: and the sanctuary of our Lord shall be in the midst thereof.\n"
	"The sanctuary shall be for the Priests of the sons of Sadoc, which kept my ceremonies, & erred not when the children of Israel erred, as the Levites also erred.\n"
	"And for them shall be the first fruits of the first fruits of the land holy of holies, by the border of the Levites.\n"
	"Yea & to the Levites in like manner by the borders of the Priests five & twenty thousand of length, & of breadth ten thousand. All the length of five and twenty thousand, and the breadth of ten thousand.\n"
	"And they shall not sell thereof, nor change, neither shall the first fruits of the land be transported, because they are sanctified to our Lord.\n"
	"But the five thousand, that remain in the breadth against the five & twenty thousand, shall be the profane parts of the city for habitation, and for the suburbs: and the city shall be in the midst thereof.\n"
	"And these are the measures thereof: to the North quarter five hundred and four thousand: and to the South quarter five hundred and four thousand: and to the East quarter five hundred & four thousand: & to the West quarter five hundred & four thousand:\n"
	"And the suburbs of the city shall be, to the North two hundred fifty, & to the South two hundred fifty, and to the East two hundred fifty, and to the Sea two hundred fifty.\n"
	"And that which shall be residue in length according to the first fruits of the sanctuary, ten thousand toward the East, and ten thousand toward the west, shall be as the first fruits of the sanctuary: and the fruits thereof shall be for bread to them, that serve the city.\n"
	"And they that serve the city, shall work of all the tribes of Israel.\n"
	"All the first fruits, of five and twenty thousand, answering to five and twenty thousand four square, shall be separated according to the first fruits of the sanctuary, and to the possession of the city.\n"
	"And that which shall be left, shall be the prince's of every part of the first fruits of the sanctuary, and of the possession of the city over against the five and twenty thousand of the first fruits unto the east border: Yea & to the sea over against the five & twenty thousand, unto the border of the Sea, likewise it shall be in the portions of the Prince: and the first fruits of the sanctuary, and the sanctuary of the temple shall be in the midst thereof.\n"
	"And of the possession of the Levites, & of the possession of the city in the midst of the prince's portions: shall be to the border of Juda, and to the border of Benjamin, shall also pertain to the prince.\n"
	"And to the rest of the tribes: from the East quarter to the West quarter, for Benjamin one.\n"
	"And against the border of Benjamin, from the East quarter to the West quarter, for Simeon one.\n"
	"And upon the border of Simeon from the East quarter to the West quarter, for Issachar one.\n"
	"And upon the border of Issachar, from the East quarter to the West quarter, for Zabulon one.\n"
	"And upon the border of Zabulon, from the East quarter to the quarter of the Sea, for Gad one.\n"
	"And upon the border of Gad, to the south quarter toward the South: and the border shall be from Thamar, even to the waters of contradiction of Cades, the inheritance against the great sea.\n"
	"This is the land, which you shall divide by lot to the tribes of Israel: and these are the portions of them, saith our Lord God.\n"
	"And these are the goings out of the city: from the North quarter thou shalt measure five hundred and four thousand.\n"
	"And the gates of the city according to the names of the tribes of Israel, three gates on the North side, the gate of Ruben one, the gate of Juda one, the gate of Levi one.\n"
	"And to the East quarter, five hundred and four thousand: and three gates, the gate of Joseph one, the gate of Benjamin one, the gate of Dan one.\n"
	"And to the South quarter, thou shalt measure five hundred and four thousand: and three gates, the gate of Simeon one, the gate of Issachar one, the gate of Zabulon one.\n"
	"And to the West quarter, five hundred and four thousand, and their gates three, the gate of Gad one, the gate of Aser one, the gate of Nephthali one.\n"
	"Round about eighteen thousand: and the name of the city from that day, Our Lord there.";