const char* chap964 = "IN the second year of the kingdom of Nabuchodonosor, Nabuchodonosor saw a dream, and his spirit was terrified, and his dream was fled from him.\n"
	"But the king commanded, that the soothsayers should be called together, and the magicians, and the sorcerers, and the Chaldees: to declare unto the king his dreams: who when they were come, stood before the king.\n"
	"And the king said to them: I saw a dream: & being confounded in mind I know not what I saw.\n"
	"And the Chaldees answered the king in Syriach: King for ever live: tell the dream to thy servants, and we will declare the interpretation thereof.\n"
	"And the king answering said to the Chaldees. The word is departed from me: unless you tell me the dream, and the conjecture thereof, you shall perish, and your houses shall be confiscate.\n"
	"But if you tell the dream, & the conjecture thereof, you shall receive of me rewards, & gifts, and much honour: the dream therefore, and the interpretation thereof tell you me.\n"
	"They answered the second time, & said: Let the king tell his servants the dream, & we will declare the interpretation thereof.\n"
	"The king answered, & said: Surely I know that you redeem time, knowing that the word is departed from me.\n"
	"If therefore you shew me not the dream, there is one sentence of you, that you have also framed a guileful interpretation, and full of deceit, to speak unto me till the time pass away. Tell me therefore the dream, that I may know that you speak a true interpretation also thereof.\n"
	"The Chaldees therefore answering before the king, said: There is no man upon the earth, that can accomplish thy word, o king, yea neither any king great and mighty, demandeth such a word of any soothsayer, & magician, and Chaldee.\n"
	"For the word that thou askest, o king, is weighty: neither shall there be found any, that can shew it in sight of the king, except the gods, whose conversation is not with men.\n"
	"Which thing being heard, the king in fury, and in great wrath commanded that all the wisemen of Babylon should perish.\n"
	"And the sentence being gone forth, wisemen were slain: & Daniel and his fellows were sought for, to perish.\n"
	"Then Daniel inquired concerning the law, and the sentence, of Arioch the prince of the king's warfare, who was gone forth to kill the wisemen of Babylon.\n"
	"And he asked him, that had received the power of the king, for what cause so cruel a sentence was gone forth from the face of the king. When Arioch therefore had shewed the matter to Daniel,\n"
	"Daniel going in desired the king, that he would give him a time to tell the solution to the king.\n"
	"And he went into his house, and he told the matter unto Ananias, & Misael, & Azarias his fellows:\n"
	"that they should ask mercy at the face of the God of heaven upon this sacrament, & Daniel and his fellows might not perish, with the rest of the wisemen of Babylon.\n"
	"Then was the mystery revealed to Daniel by a vision in the night: and Daniel blessed the God of heaven,\n"
	"and speaking said: The name of our Lord be blessed from everlasting & for ever more: because wisdom and strength are his.\n"
	"And he changeth times, and ages: transporteth kingdoms & establisheth them: giveth wisdom to the wise, and knowledge to them that understand discipline:\n"
	"he revealeth profound & hidden things, and knoweth the things that are done in darkness: and light is with him.\n"
	"To thee o God of our fathers I confess, and I praise thee: Because thou hast given me wisdom, & strength: and now thou hast shewed me the things that we desired of thee, because the king's word thou hast opened to us.\n"
	"After these things Daniel being entered in to Arioch, whom the king had appointed to destroy the wisemen of Babylon, spake thus unto him: Destroy not the wisemen of Babylon: bring me in before the presence of the king, & I will tell the solution to the king.\n"
	"Then Arioch in haste brought in Daniel to the king, and said to him: I have found a man of the children of the transmigration of Juda, that can tell the solution to the king.\n"
	"The king answered, and said to Daniel, whose name was Baltassar: Thinkest thou in very deed thou canst tell me the dream, that I saw, and the interpretation thereof?\n"
	"And Daniel answering before the king, said: The mystery, that the king demandeth, the wisemen, the Magicians, and the soothsayers, and the enchanters cannot declare unto the king.\n"
	"But there is a God in heaven that revealeth mysteries, who hath shewed unto thee, king Nabuchodonosor, what things are to come in the later times. Thy dream, and the visions of thy head in thy bed, are these.\n"
	"Thou o king beganst to think in thy bed, what should be hereafter: and he that revealeth mysteries, shewed thee what things are to come.\n"
	"To me also not in the wisdom, that is in me more than in all men alive, is this sacrament revealed: but that the interpretation might be made manifest to the king, and thou mightest know the cogitations of thy mind.\n"
	"Thou o king didst see, and behold as it were one great statua: that statua, great and high of stature stood over against thee, and the sight thereof was terrible.\n"
	"The head of this statua was of the best gold, but the breast and the arms of silver, moreover the belly, and the thighs of brass:\n"
	"and the legs of iron, of the feet a certain part was of iron, and a certain of earth.\n"
	"Thou sawest so, till a stone was cut out of a mountain without hands: and it struck the statua on the iron, & earthen feet thereof, & brake them in pieces.\n"
	"Then were the iron, the clay, the brass, the silver, and gold broken together, and brought as it were into the dust of a summer's floor, that are taken violently with the wind: and there was no place found for them: but the stone that struck the statua, was made a great mountain, and it filled all the earth.\n"
	"This is the dream: the interpretation also thereof we will tell before thee, o king.\n"
	"Thou art the king of kings: and the God of heaven hath given thee kingdom, and strength, and empire, and glory:\n"
	"and all things, wherein the children of men, and the beasts of the field do inhabit, the fowls also of the heaven he hath given in thy hand, and under thy dominion he hath appointed all things: thou therefore art the golden head.\n"
	"And after thee shall rise up another kingdom less than thou of silver: and another third kingdom of brass, which shall rule over all the world.\n"
	"And the fourth kingdom shall be as it were iron. As iron breaketh into pieces, & tameth all things, so shall that break, and destroy all these.\n"
	"Moreover because thou sawest part of the feet, and of the toes of the potter's clay, and part of iron: the kingdom shall be divided, which notwithstanding shall rise of the ground of iron, according as thou sawest the iron mingled with the earth of clay.\n"
	"And the toes in part of iron, and in part of earth: in part the kingdom shall be whole, and in part broken.\n"
	"And that thou sawest the iron mingled with the earth of clay, they shall be mingled indeed together with man's seed, but they shall not stick fast one to another, as iron cannot be mingled with earth.\n"
	"But in the days of those kingdoms the God of Heaven will raise up a kingdom, that shall not be dissipated for ever, and his kingdom shall not be delivered to another people: and it shall break in pieces, and shall consume all these kingdoms: and itself shall stand for ever.\n"
	"According as thou sawest, that the stone was cut out of the mountain without hands, and brake the earth in pieces, and the iron, and the brass, and the silver, and the gold, the great God hath shewed the king what things are to come hereafter. & the dream is true, & the interpretation thereof faithful.\n"
	"Then king Nabuchodonosor fell on his face, & adored Daniel, & commanded to sacrifice to him hosts & incense.\n"
	"The king therefore speaking said to Daniel: In very deed your God is the God of gods, and Lord of kings, and he that revealeth mysteries: because thou couldst open this sacrament.\n"
	"Then the king advanced Daniel on high, & he gave him many gifts, and great: and he made him prince over all the provinces of Babylon: and chief of the magistrates, over all the wisemen of Babylon.\n"
	"And Daniel requested of the king, and he appointed over the works of the province of Babylon, Sidrach, Misach, and Abdenago: but Daniel himself was in the doors of the king.";