const char* chap969 = "IN the first year of Baltassar the king of Babylon, Daniel saw a dream: & the vision of his head in his bed: and writing the dream, he comprehended it in a short speech: and in sum comprising it, he said:\n"
	"I saw in my vision by night, and behold the four winds of heaven fought in the great sea.\n"
	"And four great beasts came up, out of the sea diverse one from another.\n"
	"The first as it were a lioness, & she had the wings of an eagle: I beheld till her wings were plucked off, and she was lifted up from the earth, & she stood upon the feet as a man, & the heart of a man was given to her.\n"
	"And behold another beast like a bear stood aside: and there were three rews in the mouth thereof, and in the teeth thereof, & thus they said to it: Arise, eat very much flesh.\n"
	"After this I beheld, and lo another as it were a leopard, and it had wings as of a bird, four upon it, & there were four heads in the beast, and power was given to it.\n"
	"After this I beheld in the vision of the night, and lo a fourth beast terrible and marvelous, and strong exceedingly, it had great iron teeth, eating and breaking, and treading the rest with her feet: and it was unlike to the other beasts, which I had seen before it, and it had ten horns.\n"
	"I considered the horns, and behold another little horn sprang out of the midst of them: and three of the first horns were plucked off at the presence thereof, and lo eyes as it were the eyes of a man were in this horn, & a mouth speaking great words.\n"
	"I beheld till thrones were set, and the ancient of days sat: his vesture white as snow, and the hairs of his head as clean wool: his throne flames of fire: his wheels fire kindled.\n"
	"A fire & swift stream came forth from his face: thousands of thousands ministered to him, & ten thousand hundred thousands assisted him: judgement sat, and the books were opened.\n"
	"I beheld because of the voice of the great words, which that horn spake: and I saw that the beast was slain, and the body thereof was perished, and was committed to the fire to be burnt.\n"
	"The power of the other beasts also was taken away: and times of life were appointed them until time, and time.\n"
	"I beheld therefore in the vision of the night, and lo with the clouds of heaven there came in, as it were the son of man, and he came even to the ancient of days: and in his sight they offered him.\n"
	"And he gave him power, and honour, and kingdom: and all peoples, tribes, & tongues shall serve him: his power, an eternal power, that shall not be taken away: and his kingdom, that shall not be corrupted.\n"
	"My spirit trembled, I^ Daniel was made sore afraid at these things, and the visions of my head troubled me.\n"
	"I came to one of the assistants, and I asked the truth of him concerning all these things, who told me the interpretation of the words, and taught me:\n"
	"These four great beasts, are four kingdoms, which shall rise up out of the earth.\n"
	"And they shall take the kingdom of the holy God most high: & they shall obtain the kingdom even to world, & world of worlds.\n"
	"After this I would diligently learn of the fourth beast, which was very unlike from all, and exceeding terrible: his teeth and claws of iron: he did eat, and break in pieces, & the rest he stamped with his feet:\n"
	"and of the ten horns that he had on his head: and of the other, that had grown up, before which the three horns fell: and of that horn, that had eyes, and the mouth speaking great words, and was greater than the rest.\n"
	"I beheld, and lo that horn made war against the saints, and prevailed over them,\n"
	"till the ancient of days came, & gave judgement to the saints on High, and the time came, and the saints obtained the kingdom.\n"
	"And thus he said: The fourth beast shall be the fourth kingdom in the earth, which shall be greater than all the kingdoms, and shall devour the whole earth, and shall conculcate, and break it in pieces.\n"
	"Moreover the ten horns of that same kingdom, shall be ten kings: and another shall rise up after them, and he shall be mightier than the former, and he shall bring down three kings.\n"
	"And he shall speak words against the High one, and shall destroy the saints of the Highest: and he shall think that he can change times, & laws, and they shall be delivered into his hand even to a time, & times, & half a time.\n"
	"And judgement shall sit, that might^ may be taken away, and be broken, and perish even to the end.\n"
	"And kingdom, and power, and the greatness of the kingdom, that is under all the heaven, be given to the people of the saints of the Highest: whose kingdom is an everlasting kingdom, and all kings shall serve him, and shall obey him.\n"
	"Hitherto the end of the word, I^ Daniel was much troubled with my cogitations, and my face was changed in me: but the word I kept in my heart.";