const char* chap972 = "IN the third year of Cyrus king of the Persians, a word was revealed to Daniel surnamed Baltassar, and a true word, and great strength: & he understood the word: for there is need of understanding in vision.\n"
	"In those days^ I^ Daniel mourned the days of three weeks,\n"
	"desiderable bread I did not eat, and flesh and wine entered not into my mouth, yea neither with ointment was I anointed: till the days of three weeks were accomplished.\n"
	"And in the four & twentieth day of the first month I was by the great river, which is Tigris.\n"
	"And I lifted up mine eyes, & I saw: and behold a man clothed with linen cloths, & his reins girded with the finest gold:\n"
	"and his body as it were the chrysolithus, and his face as the form of lightning, and his eyes as a burning lamp: and his arms, & the parts that are downward even to the feet, as it were the form of glistering brass: and the voice of his word as the voice of a multitude.\n"
	"And I^ Daniel alone saw the vision: moreover the men that were with me, saw it not, but exceeding terror fell upon them, and they fled away, and hid themselves.\n"
	"And I being left alone saw this great vision: and there remained no strength in me, yea and my shape of countenance was changed in me, and I withered, neither had any strength.\n"
	"And I heard the voice of his words: and hearing I lay astonished upon my face, and my visage cleaved to the ground.\n"
	"And behold a hand touched me, and lifted me up upon my knees, and upon the joints of my hands.\n"
	"And he said to me: Daniel thou man of desires, understand the words, that I speak to thee, and stand in thy place: for now am I sent to thee. And when he had said this word to me, I stood trembling.\n"
	"And he said to me: Fear not Daniel: because since the first day that thou didst set thy heart to understand to afflict thyself in the sight of thy God, thy words have been heard: and I am come for thy words.\n"
	"But the prince of the kingdom of the Persians resisted me one and twenty days: and behold Michael one of the chief princes came to aid me, and I tarried there by the king of the Persians.\n"
	"But I am come to teach thee what things shall come to thy people in the later days, because as yet the vision unto days.\n"
	"And when he spake to me in these manner of words, I cast down my countenance to the ground, and held my peace.\n"
	"And behold as it were the similitude of the son of man touched my lips, and opening my mouth I spake, and said to him, that stood before me: My Lord, in thy vision my joints are dissolved, and no strength hath remained in me.\n"
	"And how can the servant of my Lord speak with my Lord? for no strength is remaining in me, yea & my breath is stopped.\n"
	"Again therefore there touched me as it were the vision of a man, and strengthened me,\n"
	"and he said: Fear not o man of desires, Peace be to thee: take courage & be strong. And when he spake with me, I received strength, and said: Speak my Lord, because thou hast strengthened me.\n"
	"And he said: Doest thou know wherefore I am come to thee? and now I will return, that I may fight against the prince of the Persians. When I therefore went forth, there appeared the prince of the Greeks coming.\n"
	"But yet I will tell thee that which is expressed in the scripture of truth: and none is my helper in all these, but Michael your prince.";