const char* chap984 = "In thy throat let there be a trumpet as an eagle upon the house of the Lord: for that they have transgressed my covenant, and have prevaricated my law.\n"
	"Me they shall invocate: My God, we Israel have known thee.\n"
	"Israel hath cast away the good thing, the enemy shall persecute him.\n"
	"They have reigned, & not of me: they have been Princes, & I knew not: their silver & their gold they made idols to themselves, that they might perish.\n"
	"Thy calf is cast off o Samaria, my fury is wrath against them. How long can they not be cleansed?\n"
	"Because it-self also is of Israel: the workman made it, and it is not God: because the calf of Samaria shall be as spiders' webs.\n"
	"Because they shall sow wind, & reap a whirlwind: there is no standing stalk in it, the bud shall not yield meal: & if it do yield, strangers shall eat it.\n"
	"Israel is devoured: Now is he become in nations as an unclean vessel.\n"
	"Because they went up to Assur, a wild ass solitary to himself: Ephraim have given gifts to lovers.\n"
	"Yea and when they shall hire the nations with reward, now will I gather them together: & they shall rest a while from the burden of the king and the princes.\n"
	"Because Ephraim hath multiplied altars to sin: altars are made to him unto sin.\n"
	"I will write to him my manifold laws, which have been accounted as strange.\n"
	"They shall offer hosts, they shall immolate flesh, and shall eat, and the Lord will not receive them: now will he remember their iniquity, and will visit their sins: they shall return into Aegypt.\n"
	"And Israel hath forgotten his maker, and hath built temples: and Judas hath multiplied fenced cities: & I will cast fire on his cities, and it shall devour the houses thereof.";