const char* chap995 = "Thus saith our Lord: Upon three wickednesses of Moab, and upon four I will not convert him: because he hath burnt the bones of Idumea even to ashes.\n"
	"And I will send fire into Moab, and it shall devour the houses of Carioth: and Moab shall die in the sound, in the noise of the trumpet:\n"
	"and I will destroy the judge out of the midst of him, and all his princes I will kill with him, saith our Lord.\n"
	"Thus saith our Lord: Upon three wickednesses of Juda, and upon four I will not convert him: because he hath cast away the law of our Lord, and not kept his commandments: for their idols have deceived them, after which their fathers went.\n"
	"And I will send fire into Juda, and it shall devour the houses of Jerusalem.\n"
	"Thus saith our Lord: Upon three wickednesses of Israel, and upon four I will not convert him: because he hath sold the just for silver, and the poor for shoes.\n"
	"Which bruise the heads of the poor upon the dust of the earth, and decline the way of the humble: and the son and his father have gone to a young woman, that they might violate my holy name.\n"
	"And upon garments laid to pledge they did lie beside every altar: & the wine of the condemned they drank in the house of their God.\n"
	"But I did cast out the Amorrheite before their face: whose height the height of Cedars, & he strong as an oak: & I destroyed his fruit from above, and his roots beneath.\n"
	"It is I that made you come up out of the Land of Aegypt, and I led you in the desert forty years, that you might possess the Land of the Amorrheite.\n"
	"And I raised up of your sons to be Prophets and of your young men Nazareites, is it not so o children of Israel, saith our Lord?\n"
	"And you drank wine to the Nazareites: and the Prophets you commanded, saying: prophesy not.\n"
	"Behold I will screak under you, as a wain screaketh laden with hay.\n"
	"And flight shall perish from the swift, and the valiant shall not obtain his strength, and the strong shall not save his life.\n"
	"And he that holdeth the bow shall not stand, and the swift of his feet shall not be saved, and the rider of the horse shall not save his life.\n"
	"and the stout of heart among the valiants shall fly naked in that day, saith our Lord.";