const char* chap10 = "These are the generations of the sons of Noe, Sem, Cham, and Japheth: and children were born to them after the flood.\n"
	"The children of Japheth: Gomer, & Magog, & Madai, & Javan, & Tubal, and Mosoch, and Thiras.\n"
	"Moreover the children of Gomer: Ascenez, and Riphath, and Thogorma.\n"
	"And the sons of Javan: Elisa, and Tharsis, the Cetims and the Dodanims.\n"
	"Of these were divided the Isles of Nations in their countries, each one according to his tongue, & their families in their nations.\n"
	"And the sons of Cham: Chus, & Mesraim, & Phut, and Chanaan.\n"
	"And the sons of Chus: Saba, Hevila, and Sabatha, & Regma, & Sabathaca. The sons of Regma: Saba, and Dadan.\n"
	"Moreover Chus begat Nemrod: he began to be mighty in the earth.\n"
	"and he was a valiant hunter before our Lord. Thereof rose a proverb: As it were Nemrod the valiant hunter before our Lord.\n"
	"And the beginning of his kingdom was Babylon, and Arach, and Achad, and Chalanne in the land of Sennaar.\n"
	"Out of that land came forth Assur, & builded Ninive, & the streets of the city, and Chale.\n"
	"Resen also between Ninive, & Chale: this is the great city.\n"
	"But Mesraim also begat the Ludims, & the Anamims, & the Laabims, the Nephthuims,\n"
	"and the Phetrusims, & the Casluims: of whom came forth the Philistims & the Caphtorims.\n"
	"And Chanaan begat Sidon his first-begotten, Hethaeus,\n"
	"and Iebusaeus, and Amorrhaeus, and Gergesaeus.\n"
	"Hevaeus and Aracaeus, Sinaeus,\n"
	"and Aradius, Samaraeus, and Hamathaeus: and afterwards were spread the people of the Chananites.\n"
	"And the limits of Chanaan were from Sidon as we come to Gerara even to Gaza, until thou enter to Sodoma and Gomorrha, and Adama, and Seboim, even to Lesa.\n"
	"These are the children of Cham in their kindreds, and tongues, and generations, and lands, and nations.\n"
	"Of Sem also father of all the children of Heber, the elder brother of Japheth, were born:\n"
	"The children of Sem: Aelam and Assur, and Arphaxad, and Lud, and Aram.\n"
	"The children of Aram: Us, and Hul, and Gether, and Mes.\n"
	"And Arphaxad also begat Sale, of whom was born Heber.\n"
	"And to Heber were born two sons: the name of the one was Phaleg, because that in his days was the earth divided: and his brother's name was Jectan.\n"
	"The which Jectan begat Elmodad, and Saleph, and Asarmoth, Jare;\n"
	"and Aduram, and Uzal, and Decla,\n"
	"and Ebal, and Abimael, Saba,\n"
	"and Ophir, and Hevila, and Jobab. All these were the children of Jectan.\n"
	"And their dwelling was from Messa as we go on as far as Sephar a mountain in the east.\n"
	"These are the children of Sem according to their kindred, and tongues, and countries in their nations.\n"
	"These are the families of Noe, according to their peoples and nations. Of these were the nations divided on the earth after the flood.";