const char* chap1012 = "Now shalt thou be spoiled daughter of the spoiler: they have laid siege upon us, with a rod shall they strike the cheek of the judge of Israel.\n"
	"AND THOU BETHLEHEM, Ephrata, art a little one in the thousands of Juda: out of thee shall come forth unto me he that shall be the dominatour in Israel: & his coming forth from the beginning, from the days of eternity.\n"
	"Therefore shall he give them even till the time, wherein she that travaileth shall bring forth: & the remnant of his brethren shall be converted to the children of Israel.\n"
	"And he shall stand, & feed in the strength of our Lord, in the height of the name of our Lord his God: & they shall be converted, because now shall he be magnified even to the ends of the earth.\n"
	"And this man shall be peace: when the Assyrian shall come into our land, and when he shall tread in our houses: & we will raise upon him seven Pastors, & eight principal men.\n"
	"And they shall feed the land of Assur in the sword, and the land of Nemrod in the spears thereof: & he shall deliver from Assur, when he shall come into our Land, & when he shall tread in our coasts.\n"
	"And the remnant of Jacob shall be in the midst of many peoples as dew from our Lord, & as drops upon the grass, which expecteth not man, & tarrieth not for the children of men.\n"
	"And the remnant of Jacob shall be in the Gentiles in the midst of many peoples, as a lion among the beasts of the forests, and as a lion's whelp among the flocks of cattle: who when he hath passed, & trodden down, & taken, there is none to deliver.\n"
	"Thy hand shall be exalted over thine enemies, & all thine enemies shall perish.\n"
	"And it shall be in that day, saith our Lord: I will take away thy horses out of the midst of thee, & will destroy thy chariots.\n"
	"And I will destroy the cities of thy land, & will destroy all thy munitions, & I will take away sorceries out of thy hand, & there shall be no divinations in thee.\n"
	"And I will make thy sculptiles to perish, and thy statues out of the midst of thee: and thou shalt no more adore the works of thy hands.\n"
	"And I will pluck up thy groves out of the midst of thee: & will destroy thy cities.\n"
	"And I will do vengeance in fury and in indignation among all the nations, that have not heard.";