const char* chap1014 = "Woe is me, because I am become as he that gathereth in autumn the clusters of vintage: there is no cluster to eat, timely ripe figs my soul hath desired.\n"
	"The holy is perished out of the earth, & there is none righteous among men: all lie in wait for blood, every one hunteth his brother to death.\n"
	"The evil of their hands they call good: the prince requireth, & the judge is in rendering: & the great man hath spoken the desire of his soul, & they have troubled it.\n"
	"He that is left among them, is as a brier, and he that is righteous, as the thorn of the hedge. The day of thy speculation, thy visitation cometh: now shall be the destruction of them.\n"
	"Believe not a friend, and trust not in prince: from her that sleepeth in thy bosom keep the closures of thy mouth.\n"
	"Because the son doth contumely to the father, and the daughter riseth against her mother, the daughter in law against her mother in law: and a man's enemies they of his own household.\n"
	"But I will look towards our Lord, I will expect God my saviour: my God will hear me.\n"
	"Rejoice not thou mine enemy over me, because I am fallen: I shall arise, when I have sit in darkness, our Lord is my light.\n"
	"I will bear the wrath of our Lord, because I have sinned to him: until he judge my judgement: he will bring me forth into the light, I shall see his justice.\n"
	"And mine enemy shall behold, and she shall be covered with confusion, which saith to me, where is the Lord thy God? Mine eyes shall look on her: now shall she be into conculcation as the mire of the streets.\n"
	"The day that thy walls may be builded upon: in that day shall the law be made far off.\n"
	"In that day and Assur shall come even to thee, and even to the fenced cities, and from the fenced cities even to the river, and to sea from sea, and to mountain from mountain.\n"
	"And the land shall be into desolation for the inhabitants thereof, and for the fruit of their cogitations.\n"
	"Feed thy people with thy rod, the flock of thine inheritance, them that dwell alone in the forest, in the midst of Carmel: they shall feed upon Basan and Galaad according to the days of old.\n"
	"According to the days of thy coming forth out of the Land of Aegypt I will shew him marvels.\n"
	"The nations shall see, and shall be confounded upon all their strength: they shall put the hand upon the mouth, their ears shall be deaf.\n"
	"They shall lick dust as serpents, as the creeping beasts of the earth, they shall be troubled in their houses: the Lord our God they shall dread, and shall fear thee.\n"
	"What God is like to thee, which takest away iniquity, and passest over the sin of the remnant of thine inheritance? He will send his fury in no more, because he is willing mercy.\n"
	"He will return, and will have mercy on us: he will lay away our iniquities: and he will cast all our sins into the bottom of the sea.\n"
	"Thou wilt give truth to Jacob, mercy to Abraham: which thou hast sworn to our fathers from the days of old.";