const char* chap1016 = "He is come up that shall scatter before thee, that shall keep the siege: behold the way, fortify the loins, strengthen force exceedingly.\n"
	"Because our Lord hath rendered the pride of Jacob, as the pride of Israel: because the waters have dissipated them, & have marred their branches.\n"
	"The buckler of his valiants fiery, the men of the army in scarlets, the reins of the chariot fiery in the day of his preparation, & the drivers are brought asleep.\n"
	"In the ways they are troubled, the chariots struck one against another in the streets: their appearance are as it were lamps, as it were lightning running to & fro.\n"
	"He will remember his valiants, they shall fall in their ways: they shall quickly scale the walls thereof, and a bower shall be prepared.\n"
	"The gates of the rivers are opened, and the temple thrown down to the ground.\n"
	"And the soldier is led away captive: and her handmaids were led away mourning as doves, murmuring in their hearts.\n"
	"And Ninive her waters as it were a fishpool of waters: but themselves are fled. Stand^ stand, and there is none that will return.\n"
	"Spoil the silver, spoil the gold: and there is no end of the riches of all vessels that are to be desired.\n"
	"She is dissipated, and rent, and torn: & pining heart, and dissolution of the knees, and defect in all reins: and the faces of them all as the blackness of a pot\n"
	"Where is the habitation of lions, and the pasture of lion's whelps, to which the lion went, to go in thither, the lion's whelp, and is there none to make them afraid?\n"
	"The lion hath caught sufficiently for his whelps, and hath killed for his lionesses: and he hath filled his dens with prey, and his couch with ravening.\n"
	"Behold I to thee, saith the Lord of hosts, and I will burn thy chariots even to smoke, and the sword shall eat thy little lions: and I will destroy thy prey out of the land, and the voice of thy messengers shall be heard no more.";