const char* chap1023 = "Woe to thee thou provoking, and redeemed city, the dove.\n"
	"She hath not heard the voice, and she hath not received discipline: she hath not trusted in our Lord, to her God she hath not approached.\n"
	"Her princes in the midst of her as lions roaring: her judges^ wolves in the evening, left nothing for the morning.\n"
	"Her prophets mad, men unfaithful: her priests have polluted the holy, they have done unjustly against the law.\n"
	"Our just Lord in the midst thereof will not do iniquity: in the morning, in the morning he will give his judgement into light, and it shall not be hid: but the wicked man hath not known the confusion.\n"
	"I have destroyed the Gentiles, & their corners are dissipated: I have made their ways desert, whiles there is none that passeth by: their cities are desolate, not a man remaining, nor any inhabiter.\n"
	"I said: Nevertheless thou shalt fear me, thou shalt receive discipline: and her habitation shall not perish for all things, wherein I have visited her: but yet rising early they corrupted all their cogitations.\n"
	"Wherefore expect me, saith our Lord, in the day of my resurrection till hereafter, because my judgement to assemble the Gentiles, and to gather kingdoms: & to pour upon them mine indignation, all the wrath of my fury: for in the fire of my jealousy shall all the earth be devoured.\n"
	"Because then will I restore to the peoples, a chosen lip, that all may invocate in the name of the Lord, & may serve him with one shoulder.\n"
	"Beyond the rivers of Aethiopia, thence shall my suppliants the children of my dispersed bring me a gift.\n"
	"In that day thou shalt not be confounded upon all thine inventions, wherein thou hast prevaricated against me: because then will I take away out of the midst of thee the lofty speakers of thy pride, & thou shalt add no more to be exalted in my holy mount.\n"
	"And I will leave in the midst of thee a people poor and needy: & they shall hope in the name of our Lord.\n"
	"The remnant of Israel shall not do iniquity, neither shall they speak leasing, and deceitful tongue shall not be found in their mouth: because they shall feed, and shall lie down, and there shall be none to make them afraid.\n"
	"Praise o daughter of Sion: make jubilation Israel: be glad & rejoice in all thy heart o daughter of Jerusalem.\n"
	"Our Lord hath taken away thy judgement, he hath turned away thine enemies: the king of Israel our Lord in the midst of thee, thou shalt fear evil no more.\n"
	"In that day it shall be said to Jerusalem: Fear not: to Sion, let not thy hands be dissolved.\n"
	"Our Lord thy God in the midst of thee strong, he will save: he will rejoice upon thee in gladness, he will be silent in his love, he will be joyful upon thee in praise.\n"
	"The triflers that were departed from thee, I will gather together, because they were of thee: that thou mayst no more have reproach for them.\n"
	"Behold I will kill all that have afflicted thee at that time: and I will save the halt, & her that was cast out I will gather: and I will make them into praise, and into name, in all the land of their confusion.\n"
	"In that time, when I will bring you: and in the time, that I will gather you: for I will give you into a name, and into praise to all the people of the earth, when I shall convert your captivity before your eyes, saith our Lord.";