const char* chap1029 = "And the Angel returned that spake in me: & he raised me up, as a man that is raised out of his sleep.\n"
	"And he said to me: What seest thou? And I said: I saw, & lo a candlestick all of gold, & the lamp thereof upon the head of it: and the seven lights thereof upon it: and seven funnels for the lights, that were upon the head thereof.\n"
	"And two olive-trees upon it: one on the right hand of the lamp, and one on the left hand thereof.\n"
	"And I answered, and I said to the Angel that spake in me, saying: What are these things, my Lord?\n"
	"And the Angel that spake in me answered, and said to me: Why, knowest thou not what these things are? And I said: No my Lord.\n"
	"And he answered, & said to me, saying: This is the word of our Lord to Zorobabel, saying: Not in an host, nor in strength: but in my spirit, saith the Lord of hosts.\n"
	"Who art thou o great mountain before Zorobabel? Into a plain: & he will bring forth the principal stone, and will make grace equal to the grace thereof.\n"
	"And the word of our Lord was made to me, saying:\n"
	"The hands of Zorobabel have founded this house, and his hands shall perfit it: and you shall know that the Lord of hosts hath sent me to you.\n"
	"For who hath despised little days? And they shall rejoice, & shall see the stone of tin in the hand of Zorobabel. These are the seven eyes of our Lord, that run through out the whole earth.\n"
	"And I answered, and said to him: What are these two olive-trees on the right hand of the candlestick, and on the left hand thereof?\n"
	"And I answered the second time, and said to him: What are the two branches of olive-trees, that are beside the two beaks of gold, in which are the funnels of gold?\n"
	"And he said to me, saying: Why, knowest thou not what these are? And I said: No, my Lord.\n"
	"And he said: These are two sons of oil which assist the dominatour of the whole earth.";