const char* chap1042 = "Behold I send mine Angel, and he shall prepare the way before my face. And forthwith shall come to his temple the Dominatour, whom you seek, and the Angel of the testament, whom you desire. Behold he cometh, saith the Lord of hosts:\n"
	"And who shall be able to think the day of his advent? And who shall stand to see him? For he as it were purging fire, and as the herb of fullers:\n"
	"and he shall sit purging, and cleansing the silver, and he shall purge the sons of Levi, and will strain them as gold, and as silver, and they shall be offering sacrifices to our Lord in justice.\n"
	"And the sacrifice of Juda and Jerusalem shall please our Lord, as the days of the world, and as the years of old.\n"
	"And I will come to you in judgement, and will be a swift witness to sorcerers, and adulterers, and to the perjured, and them that calumniate the hire of the hired man, the widows, and pupils, and oppress the stranger, nor have feared me, saith the Lord of hosts.\n"
	"For I^ the Lord, and I am not changed: and ye sons of Jacob are not consumed.\n"
	"For from the days of your fathers you have departed from mine ordinances, and have not kept them. Return to me, and I will return to you, saith the Lord of hosts. And you have said: Wherein shall we return?\n"
	"Shall man fasten God, because you do fasten me? And you have said: Wherein do we fasten thee? In tithes, and in first fruits.\n"
	"And in penury you are accursed, and you your whole nation fasten me.\n"
	"Bring in all the tithe into the barn: and let there be meat in my house, and prove me upon this, saith our Lord: if I open not unto you the flood-gates of heaven, and pour you out blessing even to aboundance,\n"
	"and I will rebuke for you the devourer, and he shall not corrupt the fruit of your land: neither shall the vine in the field be barren, saith the Lord of hosts.\n"
	"And all Nations shall call you blessed: for you shall be a land worthy to be desired, saith the Lord of hosts.\n"
	"Your words have been forcible upon me, saith the Lord.\n"
	"And you said: What have we spoken against thee? You have said: He is vain that serveth God, and what profit is it that we have kept his precepts, and that we have walked sorrowful before the Lord of hosts?\n"
	"Therefore now we call the arrogant blessed, for they that do impiety are builded, and they have tempted God and are made safe.\n"
	"Then spake they that feared our Lord, every one with his neighbour: and our Lord attended, and heard: and a book of monument was written before him for them that fear our Lord, and think on his name.\n"
	"And they shall be to me, saith the Lord of hosts, in the day that I do to my peculiar, and I will spare them, as a man spareth his son serving him.\n"
	"And you shall convert, and shall see what is between the just & the impious: and between him that serveth God, and serveth him not.";