const char* chap1048 = "And it came to pass, as the Gentiles round about heard that the altar was builded up, and the sanctuary as before, they were exceeding angry:\n"
	"and they thought to take away the stock of Jacob, that were among them, and they began to kill of the people, and to persecute.\n"
	"And Judas fought against the children of Esau in Idumea, & them that were in Acrabathane: because they beset the Israelites round about, and he struck them with a great plague.\n"
	"And he remembered the malice of the children of Bean, which were to the people a snare and a scandal, lying in wait for them in the way.\n"
	"And they were shut up by him in towers, and he came near to them, and anathematized them, and burnt their towers with fire, with all that were in them.\n"
	"And he passed to the children of Ammon, and found a strong band, and a copious people, and Timothee their captain:\n"
	"and he made many battles with them, and they were discomfited in their sight, & he struck them:\n"
	"and he took Gazer the city, and her daughters, and returned into Jewry.\n"
	"And the Gentiles that are in Galaad, gathered together against the Israelites, that were in their coasts to dispatch them: and they fled into the fortress of Datheman.\n"
	"And they sent letters to Judas, and his brethren, saying: The heathen round about are gathered together against us, to dispatch us:\n"
	"and they prepare to come, and to occupy the fortress into which we are fled: and Timothee is the captain of their host.\n"
	"Now therefore come, & deliver us, out of their hands, because a multitude of us is fallen.\n"
	"And all our brethren, that were in the places of Tubin, are slain: and they led away their wives captives, and the children, and the spoils, and they have slain there almost a thousand men.\n"
	"And the epistles were yet in reading, and lo other messengers came out of Galilee their coats rent, reporting according to these words:\n"
	"saying that there were assembled against them from Ptolemais, and Tyre, and Sidon, and all Galilee is replenished with aliens, to consume us.\n"
	"And as Judas and the people heard these words, a great assembly assembled together to consider what they should do for their brethren, that were in tribulation, and were expugned of them.\n"
	"And Judas said to Simon his brother: Choose thee men, and go, and deliver thy brethren in Galilee: and I, and my brother Jonathas will go into the country of Galaad.\n"
	"And he left Joseph the son of Zacharie, and Azarias, captains of the people with the residue of the army in Jurie to keep it:\n"
	"and he commanded them, saying: Be ye over this people: & make no battle against the heathen, till we return.\n"
	"And there were parted to Simon three thousand men, to go into Galilee: but to Judas eight thousand to go into the country of Galaad.\n"
	"And Simon went into Galilee, & made many battles with the heathen: and the heathen were discomfited before his face, and he pursued them even to the gate of Ptolemais.\n"
	"And there fell of the heathen almost three thousand men, & he took the spoils of them,\n"
	"and he took them that were in Galilee & in Arbatis with their wives, and children, & all things that they had, and he brought them into Jurie with great joy.\n"
	"And Judas Machabeus, and Jonathas his brother passed over Jordan, and went three days' journey through the desert.\n"
	"And the Nabutheians met them, & received them peaceably, & told them all things, that had happened to their brethren in the country of Galaad,\n"
	"and that many of them were comprehended in Barasa, and Bosor, and in Alimis, and in Casphor, & Mageth, & Carnaim, all these cities fenced, & great.\n"
	"Yea and in the rest of the cities of Galaad they are held captive, & on the morrow they appointed to remove the army near to these cities, and to take them, & to dispatch them in one day.\n"
	"And Judas turned & his army the way into Bosor suddenly, and took the city: and he slew every male in the edge of the sword, & took all their spoils, & burnt it with fire.\n"
	"And they arose thence by night, & went even to the fortress.\n"
	"And it came to pass early in the morning, when they had lifted up their eyes, & behold much people, whereof there was no number, carrying ladders, & engines to take the fortress, and they expugned them.\n"
	"And Judas saw that the battle began, and the cry of the battle ascended to heaven as a trumpet, and a great cry out of the city:\n"
	"& he said to his host: Fight ye today for your brethren.\n"
	"And he came with three ranks behind them & they cried out with trumpets, & cried in prayer.\n"
	"And the camp of Timothee understood that it was Machabeus, and they fled back from his presence: and they struck them with a great plague: and there fell of them in that day almost eight thousand men.\n"
	"And Judas turned aside into Maspha, and expugned, & took it, and he slew every male thereof, & he took the spoils thereof, & burnt it with fire.\n"
	"From thence he marched, and took Casbon, and Mageth, and Bosor, & the rest of the cities of Galaad.\n"
	"But after these words Timothee gathered another army, and camped against Raphon beyond the torrent.\n"
	"And Judas send to view the army: and they reported unto him, saying: That all nations, that are round about us, are assembled against us, an army exceeding great:\n"
	"and they have hired the Arabians to help them, & they have camped beyond the torrent, being ready to come unto thee into battle. And Judas went to meet them.\n"
	"And Timothee said to the princes of his army: When Judas shall approach, & his army to the torrent of water: if he pass over unto us first, we shall not be able to sustain him: because prevailing he will prevail against us.\n"
	"But if he be afraid to pass over, and camp without the river, let us pass over to them, and we shall prevail against them.\n"
	"But as Judas approached to the torrent of water, he set the scribes of the people by the torrent, & commanded them, saying: Leave not a man: but let all come into the battle.\n"
	"And he passed over to them first, & all the people after him, & all the heathen were discomfited at their presence, & they threw away their weapons, & fled to the temple, that was in Carnaim.\n"
	"And he took the city it-self, & the temple he burnt with fire, with all things that were therein: & Carnaim was subdued, & could not stand against the face of Judas.\n"
	"And Judas gathered together all the Israelites, that were in the country of Galaad, from the least even to the greatest, and their wives, and children, and an army exceeding great, to come into the land of Juda.\n"
	"And they came as far as Ephron: and this city was great, situate in the entrance, fenced exceedingly, and there was no means to decline from it on the right hand or on the left, but the way was through the midst.\n"
	"And they that were in the city, shut in themselves, and stopped the gates with stones: & Judas sent to them in peaceable words,\n"
	"saying: Let us pass through your land, and go into our country: and no man shall hurt you, only on foot we will pass. And they would not open unto them.\n"
	"And Judas commanded proclamation to be made in the camp, that they should approach every man in the place, wherein he was.\n"
	"and the men of strength approached, and he assaulted that city all the day, and all the night, and the city was delivered into his hand:\n"
	"& they slew every male in the edge of the sword, and he rooted it up, and took the spoils thereof, & passed through all the city upon the slain.\n"
	"And they passed over Jordan in the great plain, against the face of Bethsan.\n"
	"And Judas gathered together the hindmost, & he exhorted the people throughout all the way, till they came into the land of Juda:\n"
	"and they went up into mount Sion with joy and gladness, and offered holocausts because none of them was fallen till they returned in peace.\n"
	"And in the days that Judas & Jonathas were in the land of Galaad, & Simon his brother in Galilee against the face of Ptolomais,\n"
	"Joseph the son of Zacharie heard, & Azarias, the princes of the band, the things well achieved, and the battles that were made,\n"
	"and he said: Let us also make us a name, and let us go fight against the heathen, that are round about us.\n"
	"And he commanded them that were in his army, and they went to Jamnia.\n"
	"And Gorgias went forth out of the city, and his men to meet them into battle.\n"
	"And Joseph and Azarias were chased in flight even unto the borders of Jurie: and there fell that day of the people of Israel about two thousand men, and there was made a great tumult in the people:\n"
	"because they heard not Judas, & his brethren, thinking that they should do manfully.\n"
	"But they were not of the seed of those men by whom salvation was made in Israel.\n"
	"And the men of Juda were magnified exceedingly in the sight of all Israel, and of all nations where their name was heard.\n"
	"And they came together unto them, with acclamations for their good success.\n"
	"And Judas went out, and his brethren, and they expugned the children of Esau in the land, that is toward the South, and they struck Chebron, and her daughters: and the walls thereof and the towers he burnt with fire round about.\n"
	"And he removed the camp to go into the land of the aliens, and he walked through Samaria.\n"
	"In that day fell the Priests in battle, whilst they will do manfully, whilst they go forth without counsel into battle.\n"
	"And Judas declined to Azotus into the land of the aliens, and he threw down their altars, and the sculptiles of their gods he burnt with fire: and he took the spoils of the cities, and returned into the land of Juda.";