const char* chap105 = "And our Lord spake to Moyses and Aaron, saying:\n"
	"Speak to the children of Israel, and say to them: The man that hath a flux of seed, shall be unclean.\n"
	"And then he shall be judged subject to this fault, when the filthy humour at every moment cleaveth to his flesh, and is congealed.\n"
	"Every bed whereon he sleepeth shall be unclean, and wheresoever he sitteth.\n"
	"If any man touch his bed, he shall wash his cloths: and himself being washed with water, shall be unclean until even.\n"
	"If he sit where that man had sitten, he also shall wash his cloths: and being washed with water, shall be unclean until even.\n"
	"He that toucheth his flesh, shall wash his cloths: and himself being washed with water shall be unclean until even.\n"
	"If such a man cast his spittle upon him that is clean, he shall wash his cloths: and being washed with water he shall be unclean until even.\n"
	"The pad whereupon he sitteth shall be unclean:\n"
	"and whatsoever hath been under him, that hath the flux of seed, shall be polluted until even. He that carrieth any of these things, shall wash his cloths: and himself being washed with water, shall be unclean until even.\n"
	"Every one, whom he toucheth that is such an one, having not washed his hands before, shall wash his cloths, and being washed with water, shall be unclean until even.\n"
	"The earthen vessel that he toucheth shall be broken: but the wooden vessel shall be washed with water.\n"
	"If he be healed that hath such a disease, he shall number seven days after his cleansing, and having washed his cloths and all his body in living water, he shall be clean.\n"
	"And the eighth day he shall take two turtles, or two young pigeons, and he shall come into the sight of our Lord, to the door of the tabernacle of testimony, & shall give them to the Priest,\n"
	"who shall make one for sin, and the other for an holocaust, & he shall pray for him before our Lord, that he may be cleansed of the flux of his seed.\n"
	"The man from whom issueth the seed of copulation, shall wash with water all his body: and he shall be unclean until even.\n"
	"The garment & skin that he weareth, he shall wash with water, and it shall be unclean until even.\n"
	"The woman with whom he companieth shall be washed with water and shall be unclean until even.\n"
	"The woman that monthly hath the flux of blood, shall be separated seven days.\n"
	"Every one that toucheth her, shall be unclean until even:\n"
	"and that whereon she sleepeth or sitteth in the days of her separation shall be polluted.\n"
	"He that toucheth her bed shall wash his cloths: & himself being washed with water, shall be unclean until even.\n"
	"Whosoever shall touch any vessel whereupon she sitteth, he shall wash his cloths: and himself being washed with water shall be polluted until even.\n"
	"If a man company with her in the time of her menstrual blood, he shall be unclean seven days: and every bed whereon he sleepeth shall be polluted.\n"
	"The woman that hath a flux of blood many days not in her menstrual time, or that ceaseth not to have a flux after the menstrual blood, as long as she is subject to this disease, she shall be unclean, as if she were in her menstrual time.\n"
	"Every bed, whereupon she sleepeth, and vessel whereupon she sitteth, shall be polluted.\n"
	"Whosoever toucheth them shall wash his cloths: and himself being washed with water, shall be unclean until even.\n"
	"If the blood stay and cease to run, she shall count the seven days of her purification:\n"
	"and the eighth day she shall offer for herself to the Priest, two turtles, or two young pigeons, at the door of the tabernacle of testimony:\n"
	"who shall make one for sin, and the other for an holocaust, and he shall pray for her before our Lord, and for the flux of her uncleanness.\n"
	"You shall teach therefore the children of Israel, that they take heed of uncleanness, and die not in their filthiness, when they shall pollute my tabernacle that is among them.\n"
	"This is the law of him that hath the flux of seed and that is polluted by copulation,\n"
	"and the woman that is separated in her menstrual times, or that hath a continual flux of blood, and of the man that sleepeth with her.";