const char* chap1053 = "And in the year an hundreth threescore came up Alexander the son of Antiochus, that was surnamed Noble: and he took Ptolemais, and they received him, and he reigned there.\n"
	"And Demetrius the king heard it, and he gathered together an exceeding great army, and went forth to meet him into battle.\n"
	"And Demetrius sent an epistle to Jonathas in peaceable words, to magnify him.\n"
	"For he said: Let us prevent to make peace with him, before he make with Alexander against us:\n"
	"for he will remember all the evils, that we have done against him, and against his brother, and against his nation.\n"
	"And he gave him authority to gather an army, and to make weapons, and to be himself his fellow: and the hostages that were in the castle, he commanded to be delivered to him.\n"
	"And Jonathas came into Jerusalem, and read the epistles in the hearing of all the people, and of them that were in the castle.\n"
	"And they feared with great fear, because they heard that the king gave him authority to gather an army.\n"
	"And the hostages were delivered to Jonathas, and he rendered them to their parents.\n"
	"And Jonathas dwelt in Jerusalem, and began to build, & to renew the city.\n"
	"And he spake to them that made the works, that they should build the walls, and mount Sion round about with square stones for munition: and so they did.\n"
	"And the Aliens fled that were in the holds, which Bacchides had built:\n"
	"and every man left his place, & departed into his own country:\n"
	"only in Bethsura there remained some of them, that had forsaken the law, and the precepts of God: for this was for a refuge to them.\n"
	"And Alexander the king heard of the promises, that Demetrius had promised to Jonathas: and they told him the battles, & the worthy acts that he did, and his brethren, and the labours, that they endured:\n"
	"and he said: Why, shall we find any such man? And now we will make him a friend, and our fellow.\n"
	"And he wrote an epistle, and sent it to him according to these words, saying:\n"
	"KING Alexander to his brother Jonathas greeting.\n"
	"We have heard of thee, that thou art mighty of power, and art meet to be our friend:\n"
	"and now we make thee this day high Priest of thy nation, that thou be called the king's friend (& he sent him purple, and a crown of gold) & in our affairs thou be of one mind with us, and keep amity towards us.\n"
	"And Jonathas put on him the holy stole the seventh month, in the year an hundreth threescore in the solemn day of Scenopegia: and he gathered an army, and made very many weapons.\n"
	"And Demetrius heard these words, and was exceeding sorry, and said:\n"
	"What is this that we have done, that Alexander hath prevented us to take the friendship of the Jews for his strength?\n"
	"I also will write to them words of request, and dignities, and gifts: that they may be with me to aid me.\n"
	"And he wrote to them in these words: KING Demetrius to the nation of the Jews greeting.\n"
	"Because you have kept covenant towards us, and have continued in our amity, and have not joined to our enemies, we have heard of it, and are glad.\n"
	"And now persevere still to keep fidelity towards us, & we will reward you with good things, for that you have done with us.\n"
	"And we will remit you many charges, and will give you many gifts.\n"
	"And now I release you, and all the Jews from tributes, & I pardon you the prices of salt, & remit the crowns, & the thirds of the seed:\n"
	"and the half of the fruit of trees, which is my portion, I leave to you from this day forward, that it be not taken of the land of Juda, and of the three cities that are added thereto of Samaria, & Galilee from this day & for ever:\n"
	"& let Jerusalem be holy, and free with the coasts thereof: & the tithes, & tributes be they to it.\n"
	"I release also the authority of the castle, that is in Jerusalem, and I give it to the high priest, to place therein men whomsoever he shall choose, that may keep it.\n"
	"And every soul of the Jews, that is captive from the land of Juda in all my kingdom, I dismiss free for nothing, that all may be discharged also from tributes of their cattle.\n"
	"And all the solemn days, & the sabbaths, & the new moons, & the days appointed, and three days before the solemn day, and three days after the solemn day let them all be of immunity & remission, to all the Jews that are in my kingdom:\n"
	"& no man shall have power to do any thing, & to make businesses against any of them in any cause.\n"
	"And let there be enrolled of the Jews in the king's army to the number of thirty thousand men: & allowance shall be given them as behoveth to all the king's bands, & of them there shall be ordained certain, that shall be in the fortresses of the great king:\n"
	"and of these there shall be appointed over the affairs of the kingdom, that are done of trust, and let there be princes of them, and let them walk in their own laws, as the king hath commanded in the land of Juda.\n"
	"And the three cities that are added to Jury of the country of Samaria, let them be accounted with Jury: that they may be under one, and obey no other power, but the high priest's:\n"
	"Ptolomais, and the confines thereof, which I have given for a gift to the holies, that are in Jerusalem, to the necessary charges of the holy things.\n"
	"And I give every year fifteen thousand sicles of silver of the king's accounts, that belong to me:\n"
	"& all that is above which they had not rendered, that were over the affairs the years before, from this time they shall give it to the works of the house.\n"
	"And beside these five thousand sicles of silver, which they received of the account of the holies every year: & let these pertain to the priests, that execute the ministry.\n"
	"And whosoever fly into the temple that is in Jerusalem, and in all the coasts thereof, in the king's danger for matter, let them be dismissed, & all things, that they have in my kingdom, let them have it free.\n"
	"And to build or repair the works of the holy places, the charges shall be given of the king's account:\n"
	"and to build the walls in Jerusalem, and to fortify them round about, the charges shall be given of the king's account, and to build the walls in Jurie.\n"
	"But as Jonathas, & the people heard these words, they believed them not, nor received them: because they remembered the great mischief, that he had done in Israel, and had afflicted them exceedingly.\n"
	"And their liking was toward Alexander, because he had been the first mover of the words of peace unto them, & him they aided all days.\n"
	"And king Alexander gathered a great army, & moved the camp near to Demetrius.\n"
	"And the two kings joined battle, and the army of Demetrius fled, & Alexander pursued him, & urged them sore.\n"
	"And the battle grew very sore, till the sun went down: & Demetrius was slain in that day.\n"
	"And Alexander sent legates to Ptolomee king of Aegypt according to these words, saying:\n"
	"BECAUSE I am returned into my Kingdom, and am set in the seat of my fathers, & have obtained the princedom, & have destroyed Demetrius, & possessed our country,\n"
	"and have joined battle with him, and he is destroyed himself, & his camp by us, and we sit in the seat of his kingdom:\n"
	"and now let us make amity one with another: & give me thy daughter to wife, and I will be thy son in law, & I will give thee gifts, and to her dignity.\n"
	"And king Ptolomee answered, saying: HAPPY is the day wherein thou art returned to the land of thy fathers, and art set in the seat of their kingdom.\n"
	"And now I will do to thee that which thou hast written: but meet me at Ptolomais, that we may see one another, and I may despouse her to thee as thou hast said.\n"
	"And Ptolomee went out of Aegypt, he & Cleopatra his daughter, & he came to Ptolomais in the year an hundred threescore and two.\n"
	"And Alexander the king met him, & he gave him Cleopatra his daughter: and he made her marriage at Ptolomais, as kings in great glory.\n"
	"And king Alexander wrote to Jonathas, that he should come to meet him.\n"
	"And he went with glory to Ptolomais, & he met there the two kings, & he gave them much silver, & gold, & gifts: & he found grace in their sight.\n"
	"And there assembled against him pestilent men of Israel, wicked men soliciting against him: & the king attended not to them.\n"
	"And he commanded Jonathas to be changed of his garments, & that he should be clothed with purple: and so they did. And the king placed him to sit with himself.\n"
	"And he said to his princes: Go ye out with him into the midst of the city, & proclaim, that no man solicit against him for any matter, & that no man be troublesome unto him for any cause.\n"
	"And it came to pass, as they that solicited saw his glory that was published, & him covered with purple, they all fled:\n"
	"& the king magnified him, & wrote him amongst his chief friends, & made him Duke, & partaker of the princedom.\n"
	"And Jonathas returned into Jerusalem with peace & joy.\n"
	"In the year an hundreth sixty five came Demetrius the son of Demetrius from Crete into the land of his fathers.\n"
	"And Alexander the king heard it, & he was very sorry, & returned to Antioch.\n"
	"And Demetrius the king made Apollonius general, who was ruler of Coelesiria: & he gathered a great army, & came to Jamnia: & he sent Jonathas the high priest,\n"
	"saying: Thou only resistest us, & I am brought into derision, & into reproach, because thou doest exercise power against us in the mountains.\n"
	"Now therefore if thou trust in thy forces, come down to us in the plain, let us compare there one with another: because with me is the force of battles.\n"
	"Ask, & learn who I am, & the rest, that aid me, who also say that your foot cannot stand before our face, because twice have thy fathers been put to flight in their own land:\n"
	"and now how wilt thou be able to abide the horsemen, & so great an army in the plain, where is no stone, nor rock, nor place to fly?\n"
	"But as Jonathas heard the words of Apollonius, he was moved in mind: & he chose ten thousand men, & went forth from Jerusalem, & Simon his brother met him to aid him.\n"
	"And they moved the camp to Joppe, & it shut him out of the city: because the garrison of Apollonius was in Joppe, & he assaulted it.\n"
	"And they that were in the city being put in great fear, opened to him, & Jonathas obtained Joppe.\n"
	"And Apollonius heard it, & he took three thousand horsemen, & a great army.\n"
	"And he went to Azotus as making journey, and immediately he went forth into the plain: because he had a multitude of horsemen, and he trusted in them. And Jonathas pursued him unto Azotus, and they joined battle.\n"
	"And Apollonius left in the camp a thousand horsemen behind them secretly.\n"
	"And Jonathas understood that there was an embushment behind him, and they compassed his camp, and they threw darts upon the people from morning even unto evening.\n"
	"But the people stood, as Jonathas had commanded: and their horses laboured.\n"
	"And Simon put forth his army, and joined it against the legion: for the horsemen were wearied: and they were discomfited by him, and fled.\n"
	"And they that were scattered by the plain, fled into Azotus, and entered into Bethdagon their idol house, there to save themselves.\n"
	"And Jonathas burnt Azotus, and the cities that were round about it, and he took the spoils of them, and the temple of Dagon: and all that fled into it, he burnt with fire.\n"
	"And there were slain by the sword, with these that were burnt, almost eight thousand men.\n"
	"And Jonathas removed the camp from thence, and brought it to Ascalon: and they went out of the city to meet him in great glory.\n"
	"And Jonathas returned into Jerusalem with his company, having many spoils.\n"
	"And it came to pass: as Alexander the king heard these words, he added yet to glorify Jonathas.\n"
	"And he sent him a chain of gold, as the custom is to be given to the cousins of kings. And he gave him Accaron and all the borders thereof in possession.";