const char* chap1059 = "And John went up from Gazara, and told Simon his father what Cendebaeus did among their people.\n"
	"And Simon called his two elder sons, Judas and John, and he said to them: I and my brethren, and the house of my father, have expugned the enemies of Israel from our youth even to this day: and it hath prospered in our hands to deliver Israel oftentimes.\n"
	"And now I am old, but be you in place of me, and my brethren, and going forth fight for our nation: and the help from heaven be with you.\n"
	"And he chose out of the country twenty thousand fighting men and horsemen, and they went forth to Cendebaeus: and they slept in Modin.\n"
	"And they arose in the morning, and went into the plain field: and lo a mighty great army coming to meet them of foot men, and horsemen, & there was a running river between them.\n"
	"And he camped against the face of them, himself and his people, and he saw the people fearful to pass through the torrent, and he passed through first: and the men saw him, and they passed over after him.\n"
	"And he divided the people, and the horsemen in the midst of the footmen: and the horsemen of the adversaries were exceeding many.\n"
	"And they sounded with the holy trumpets: and Cendebaeus was put to flight, and his camp: and there fell many of them wounded, & the rest fled into the hold.\n"
	"Then was Judas^ John's brother wounded: But John pursued them, till he came to Cedron, which he built:\n"
	"and they fled even to the towers, that were in the fields of Azotus, and he burnt them with fire. And there fell of them two thousand men, and he returned into Jurie in peace.\n"
	"And Ptolomee the son of Abobus was appointed captain in the plain of Jericho, and he had much silver, & gold.\n"
	"For he was the son in law of the high-Priest.\n"
	"And his heart was exalted, and he would gain the country, and he purposed treachery against Simon and his sons to dispatch them.\n"
	"And Simon walking through the cities, that were in the country of Jurie, and being careful of them, went down into Jericho, he and Mathathias his son, and Judas, the year an hundreth seventy seven, the eleventh month: this is the month Sabath.\n"
	"And the son of Abobus received them with guile into a little fortress, that is called Doch, which he built, and he made them a great feast, and hid men there.\n"
	"And when Simon was inebriated & his sons, Ptolomee arose with his company, and they took their weapons, and entered into the feast, and slew him, and his two sons, and certain of his servants.\n"
	"And he did great deceit in Israel, and rendered evil for good.\n"
	"And Ptolomee wrote these things, and sent to the king that he should send him an army for aid, and he would deliver him the country, and their cities, and tributes.\n"
	"And he sent others into Gazara to dispatch John: and to the tribunes he sent epistles, that they should come to him, and he would give them silver, and gold, and gifts.\n"
	"And he sent others to take Jerusalem, and the mount of the temple.\n"
	"And one running before told John in Gazara, that his father was perished, and his brethren, and that he hath sent that thou also mayst be slain.\n"
	"But as he heard it, he was exceedingly afraid: and he apprehended the men, that came to destroy him, and he slew them: for he knew that they sought to destroy him.\n"
	"And the rest concerning the words of John, and his battles, and the valiant acts, which he did manfully, and the building of the walls, which he built, and the things that he did:\n"
	"lo these are written in the book of the days of his priesthood, from the time that he was made prince of the priests after his father.";