const char* chap1060 = "To the brethren, the Jews that are throughout Aegypt, the brethren, the Jews that are in Jerusalem, and that are in the country of Jurie, send health, & good peace.\n"
	"God do good to you, and remember his testament, that he spake to Abraham, and Isaac, and Jacob, his faithful servants:\n"
	"and give he unto you all an heart to worship him, and to do his will with a great heart, and a willing mind.\n"
	"Open he your heart in his law, and in his precepts, and make peace.\n"
	"Hear he your prayers, and be he reconciled unto you, neither forsake he you in the evil time.\n"
	"And now here we are praying for you.\n"
	"When Demetrius reigned, in the year one hundreth sixty nine, we Jews wrote unto you in the tribulation, and violence, that came upon us in these years, since Jason revolted from the holy land, and from the kingdom.\n"
	"They burnt the gate and shed innocent blood: and we prayed to our Lord, & were heard, & we offered sacrifice, and fine flour, and lighted the lamps, and set forth there breads.\n"
	"And now celebrate ye the days of Scenopegia of the month Casleu.\n"
	"In the year one hundreth eighty eight, the people that is at Jerusalem, and in Jurie, and the senate, and Judas, to Aristobolus the master of Ptolomee the king, who is of the stock of the anointed Priests, and to those Jews that are in Aegypt, health and welfare.\n"
	"Being delivered by God out of great dangers, we give him thanks magnifically, as who have fought against such a king.\n"
	"For he made them swarm out of Persis, that have fought against us, & the holy city.\n"
	"For when he was captain in Persis, & with him a very great army, he fell in the temple of Nania, being deceived by the counsel of Naneae's priests.\n"
	"For Antiochus, and his friends came to the place as to dwell with her, & that he might receive much money under the title of a dowry.\n"
	"And when Naneae's priests had laid it forth, and he with a few was entered within the compass of the temple, they shut the temple,\n"
	"when Antiochus was entered in: & a secret entrance of the temple being opened, casting stones they struck the duke, and them that were with him, and divided them in pieces, and cutting off their heads they threw them forth.\n"
	"Blessed be the God in all things, who hath delivered up the impious.\n"
	"We therefore meaning to keep the purification of the temple the five and twentieth day of the month Casleu, thought it necessary to signify unto you: that you also may keep the day of Scenopegia, and the day of the fire that was given, when Nehemias, after the temple was built & the altar, offered sacrifice.\n"
	"For when our fathers were carried into Persis, the Priests that then were the worshippers of God, taking the fire from the altar, hid it secretly in a valley where there was a pit deep, & dry, & therein they saved it, so that the place was unknown to all men.\n"
	"But when many years had passed, and it pleased God that Nehemias should be sent of the king of Persis: he sent the nephews of those Priests, that had hid it, to seek out the fire: and as they told us, they found not fire, but thick water.\n"
	"And he bade them draw, and bring unto him: and the sacrifices, that were laid on, the Priest Nehemias commanded to be sprinkled with the same water, and the wood, and the things that were laid thereupon.\n"
	"And as this was done, and the time was come that the sun shone forth, which before was in a cloud, there was kindled a great fire, so that all marveled.\n"
	"And all the Priests made prayer, whilst the sacrifice was consuming, Jonathas beginning, and the rest answering.\n"
	"And the prayer of Nehemias was in this manner: O LORD God creator of all, dreadful, & strong, just, & merciful, which only art the good King,\n"
	"only giver, only just, and omnipotent, and eternal: which deliverest Israel from all evil, which madest the fathers elect, and didst sanctify them.\n"
	"Receive the sacrifice for all thy people Israel, & keep thy part, and sanctify it.\n"
	"Gather together our dispersion, deliver them, that serve the Gentiles, and regard the contemned & abhorred: that the Gentiles may know that thou art our God.\n"
	"Afflict them that oppress us, and that do contumely in pride.\n"
	"Place thy people in thy holy place, as Moyses said.\n"
	"And the Priests sang hymns, till the sacrifice was consumed.\n"
	"And when the sacrifice was consumed, of the rest of the water Nehemias commanded the greater stones to be throughly washed.\n"
	"Which thing as it was done, out of them was kindled a flame: but by light also, that shined from the altar, it was consumed.\n"
	"And as the thing was made manifest, it was told the king of the Persians, that in the place, wherein those Priests that were transported, had hid fire, there appeared water, with the which Nehemias, and they that were with him, purified the sacrifices.\n"
	"And the king considering, and diligently examining the matter, made a temple for it, that he might approve that which was done.\n"
	"And when he had approved it, he gave to the Priests many good things, and diverse gifts, and taking them with his own hand, he gave to them.\n"
	"And Nehemias called this place Nephthar, which is interpreted purification. But it is called with many Nephi.";