const char* chap1061 = "And it is found in the descriptions of Jeremie the Prophet, that he commanded them that went in transmigration, to take the fire, as it was signified, and as he commanded them that were carried away in transmigration.\n"
	"And he gave them a law that they should not forget the precepts of our Lord, and that they should not err in their minds, seeing the idols of gold, & silver, & the ornaments of them.\n"
	"And saying other like things, he exhorted them that they would not remove the law from their heart.\n"
	"And it was in the same writing, how the Prophet commanded by the divine answer made to him, that the tabernacle, and the ark should follow in company with him, till he came forth into the mount in which Moyses ascended, and saw the inheritance of God.\n"
	"And Jeremie coming thither found a place of a cave: and he brought the tabernacle, and the ark, & the altar of incense in thither and stopped the door.\n"
	"And there came certain withal, that followed, to mark the place for themselves: and they could not find it.\n"
	"And as Jeremy understood it, blaming them he said: that the place shall be unknown, till God gather together the congregation of the people, and become propitious:\n"
	"and then our Lord will shew these things, and the majesty of our Lord shall appear, and there shall be a cloud as it was also made manifest to Moyses, and as when Salomon prayed that the place might be sanctified to the great God, he did manifest these things.\n"
	"For he handled wisdom magnifically: as having wisdom, did he offer the sacrifice of the dedication, and of the consummation of the temple.\n"
	"As Moyses also prayed to our Lord, and as Salomon prayed, and fire came down from heaven, and consumed the holocaust.\n"
	"And Moyses said: Because that which was for sin, was not eaten, it was consumed.\n"
	"In like manner Salomon also eight days celebrated the dedication.\n"
	"And these self same things were put in the descriptions and commentaries of Nehemias: & after what sort he making a library gathered together Books of the Prophets, and of David, and the epistles of the kings, and concerning the donaries.\n"
	"And in like manner Judas also such things as were fallen away by the war that happened to us, gathered them all together, and they are with us.\n"
	"If therefore you desire these things, send some that may fetch them unto you.\n"
	"We therefore meaning to keep the purification have written unto you: You shall do well then, if you keep these days.\n"
	"And God that hath delivered his people, and rendered the inheritance to all, the kingdom, and the priesthood, and the sanctification,\n"
	"as he promised in the law, we hope that he will quickly have mercy upon us, and will gather us together from under heaven into the holy place.\n"
	"For he hath delivered us out of great perils, and hath purged the place.\n"
	"Concerning Judas Machabeus, and his brethren, and of the purification of the great temple, and of the dedication of the altar,\n"
	"Yea and of the battles that pertain to Antiochus the Noble, and his son Eupator:\n"
	"and of the apparitions, that were made from heaven to them, that did manfully for the Jews, so that being few they revenged the whole country, and put to flight the barbarous multitude:\n"
	"and repaired the most famous temple in all the world, and delivered the city, and the laws that were abolished, were restored, our Lord with all clemency being made propitious unto them.\n"
	"Also the things which by Jason the Cyrenean are comprised in five Books, we have attempted to abridge in one volume.\n"
	"For considering the multitude of Books, & the difficulty to them, that will attempt the narrations of histories, because of the multitude of matters:\n"
	"We have been careful for them that are willing to read, that there might be delectation of the mind: and for the studious, that they may more easily commit it to memory: and that profit might ensue to all that read it.\n"
	"And to our own selves indeed, which have taken upon us this work, to make an abridgment, we have taken in hand no easy labour, yea rather a business full of watching and sweat.\n"
	"As they that prepare a feast, & seek to condescend to other men's will: for many men's sakes we do willingly sustain the labour.\n"
	"The verity certes concerning every particular^ leaving to the authors, & ourselves according to the form that is given, studying to be brief.\n"
	"For as the builder of a new house must have care of the whole building: but he that hath the care to paint must seek out the things that are apt for garnishing: so must it be esteemed also in us.\n"
	"For to gather together the understanding, to order the speech, and curiously to discuss every particular part, agreeth to the author of an history:\n"
	"but to pursue the brevity of speech, and to avoid the exact declarations of things, is to be granted to him that abridgeth.\n"
	"From hence then will we begin the narration: of the preface let it be sufficient to have said thus much: for it is a foolish thing before the history to flow over, and in the history to be short.";