const char* chap1065 = "But not long after the king sent a certain ancient man of Antioch, that should compel the Jews to remove themselves from the laws of their fathers and of God:\n"
	"to contaminate also the temple that was in Jerusalem, & to call it by the name of Jupiter Olympius: and in Garizim, according as they were that inhabited the place, of Jupiter Hospitalis.\n"
	"And the invasion of the evils was sore & grievous to all:\n"
	"for the temple was full of the lechery & gluttony of the Gentiles: & of them that played the harlots with whores. And women thrusting themselves of their own accord into the sacred houses, bringing in those things which were not lawful.\n"
	"The altar also was full of unlawful things which were forbidden by the laws.\n"
	"And neither were the Sabbaths kept, nor the solemn days of the fathers observed, neither plainly did any man confess himself to be a Jew.\n"
	"But they were led with bitter necessity in the king's birth day to sacrifices: & when the feast of Bacchus was kept, they were compelled to go about crowned with Ivy unto Bacchus.\n"
	"And there went forth a decree into the next cities of the Gentiles, the Ptolomeans giving the advise, that they also in like manner should do against the Jews, that they might sacrifice:\n"
	"and them that would not pass to the ordinances of the heathen, they should kill. A man then might see the misery.\n"
	"For two women were accused to have circumcided their children: whom, the infants hanging at their breasts, when they had openly led them about through the city, they threw down headlong by the walls.\n"
	"And others coming together to the next caves, and secretly keeping the day of the Sabbath, when they were discovered to Philip, were burnt with fire, because they feared for religion and observance, to help themselves with their hand.\n"
	"But I beseech them that shall read this book, that they abhor not for the adversities, but that they account those things, which have happened, not to be for the destruction, but for the chastening of our stock.\n"
	"For not to suffer sinners a long time to do as they will, but forthwith to punish, is a token of a great benefit.\n"
	"For, not as in other nations our Lord patiently expecteth, that when the day of judgement shall come, he may punish them in the fullness of sins:\n"
	"so also doth he determine in us, that our sins being come to the end, so at length he may punish us.\n"
	"For which cause he never certes removeth away his mercy from us: but chastening his people by adversity, he forsaketh them not.\n"
	"But let these things be said of us in few words for an admonition of the readers. And now we must come to the story.\n"
	"Therefore, Eleazarus one of the chief of the Scribes, a man striken in age, and comely of countenance, with open mouth gaping was compelled to eat swine's flesh.\n"
	"But he embracing rather a most glorious death than an hateful life, went before voluntarily to the punishment.\n"
	"And considering how he ought to come patiently sustaining, he determined not to commit unlawful things for love of life.\n"
	"But they that stood by, moved with unlawful pity, for the old friendship of the man, taking him in secret, desired that flesh might be brought, which it was lawful for him to eat, that he might feign to have eaten, as the king had commanded, of the flesh of the sacrifice:\n"
	"that by this fact he might be delivered from death: and for the old friendship of the man, they did him this courtesy.\n"
	"But he began to think upon the worthy preeminence of his age and ancientness, and the hoar hairs of natural nobility, and his doings from a child of very good conversation, and according to the ordinances, and the holy law made of God, he answered quickly, saying: that he would rather be sent unto hell.\n"
	"For it is not meet, quoth he, for our age to feign: that many young men thinking, that Eleazarus of four score year and ten is passed to the life of Aliens:\n"
	"they also through my dissimulation, and for a little time of corruptible life, may be deceived, and hereby I may purchase a stain, and a curse to mine old age.\n"
	"For although at this present time I be delivered from the punishments of men, yet neither alive nor dead shall I escape the hand of the Almighty.\n"
	"Wherefore in departing manfully out of this life, I shall appear worthy of mine old age:\n"
	"& to young men I shall leave a constant example, if with ready mind and stoutly I suffer an honest death, for the most grave and most holy laws. These things being spoken, forthwith he was drawn to execution.\n"
	"And they that led him, and had been a little before more mild, were turned into wrath for the words spoken of him, which they thought were uttered through arrogancy.\n"
	"But when he was now in killing with the strokes, he groaned, and said: O Lord, which hast the holy knowledge, thou knowest manifestly that whereas I might be delivered from death, I do sustain sore pains of the body: but according to the soul, for thy fear I do willingly suffer these things.\n"
	"And this man certes in this manner departed this life, leaving not only to young men, but also to the whole nation the memory of his death for an example of virtue and fortitude.";