const char* chap1066 = "And it came to pass, that seven brethren together with their mother being apprehended, to be compelled by the king to eat against the law^ swines' flesh, were tormented with whips and scourges.\n"
	"But one of them which was the first, said thus: What seekest thou, and what wilt thou learn of us? We are ready to die rather than to transgress the laws of God, coming from our fathers.\n"
	"The king therefore being wrath commanded frying pans, and brazen pots to be heated:\n"
	"the which forthwith being heated, he commanded his tongue, that had spoken first, to be cut out: and the skin of his head being drawn off, the ends also of his hands and feet to be chopped off, the rest of his brethren, and his mother looking on.\n"
	"And when he was now made in all parts unprofitable, he commanded fire to be put unto him, and that breathing as yet he should be fried in the frying pan: wherein when he was long tormented, the rest together with the mother exhorted one another to die manfully,\n"
	"saying: Our Lord God will behold the truth, and will take pleasure in us, as Moyses declared in the profession of the Canticle: And in his servants he will take pleasure.\n"
	"The first therefore being dead in this manner, they brought the next to make him a mocking stock: & the skin of his head with the hairs being drawn off, they asked if he would eat, before that he were punished throughout the whole body in every member.\n"
	"But he answering in his country speech, said: I will not do it. Wherefore this also in the next place, received the torments of the first:\n"
	"and being at the very last gasp, thus he said: Thou indeed, o most wicked man, in this present life destroyest us: but the King of the world will raise us up which die for his laws, in the resurrection of eternal life.\n"
	"After him the third is had in derision, and being demanded his tongue, he quickly put it forth, and constantly stretched out his hands:\n"
	"& with confidence he said: From heaven do I possess these, but for the laws of God now do I contemn these self same, because I hope that I shall receive them again of him.\n"
	"So that the king, and they that were with him marveled at the young man's courage, because he esteemed the torments as nothing.\n"
	"And this being thus dead, the fourth they vexed in like manner tormenting him.\n"
	"And when he was now even to die, thus he said: It is better for them that are put to death by men to expect hope of God, that they shall be raised up again by him. For to thee there shall not be resurrection unto life.\n"
	"And when they had brought the fifth, they tormented him. But he looking upon him,\n"
	"said: Thou having power among men, whereas thou art corruptible doest what thou wilt: but think not that our stock is forsaken of God.\n"
	"And do thou patiently abide, and thou shalt see his great power, in what sort he will torment thee, and thy seed.\n"
	"After him they brought the sixth, and he beginning to die, said thus: Be not deceived vainly: for we suffer this for our own sakes, sinning against our God, and things worthy of admiration are done in us:\n"
	"but do not think that thou shalt escape unpunished, for that thou hast attempted to fight against God.\n"
	"But the mother above measure marvelous, & worthy of good men's memory, which beholding her seven sons perishing in one day's space, bare it with a good heart, for the hope that she had in God:\n"
	"exhorted every one of them in their country language manfully, being replenished with wisdom: and joining a man's heart to a woman's cogitation,\n"
	"she said to them: I know not how you appeared in my womb: for neither did I give you spirit and soul and life, and the members of every one I myself framed not.\n"
	"But indeed the Creator of the world, that hath formed the nativity of man, and that invented the origin of all, and he will restore again with mercy unto you spirit and life, as now you despise yourselves for his laws.\n"
	"But Antiochus thinking himself contemned, and withal despising the voice of the upbraider, when the younger was yet alive, he did not only exhort with words, but also with oath he affirmed that he would make him rich and happy, & being turned from the laws of his fathers, he would account him a friend, & give him things necessary.\n"
	"But when the young man was not inclined to these things, the king called the mother, and counselled her to deal with the young man to save his life.\n"
	"And when he had exhorted her in many words, she promised that she would counsel her son.\n"
	"Therefore bending towards him, mocking the cruel tyrant, she said in her country language: My son have pity on me which have borne thee in my womb nine months, and gave thee milk for three years, and nourished thee, and brought thee unto this age.\n"
	"I beseech thee my son, that thou look to heaven and earth, and to all things that are in them: and understand that God of nothing made them & mankind:\n"
	"so shall it come to pass, that thou wilt not fear this tormenter, but being made a worthy partaker with thy brethren, take thou death, that in that mercy I may receive thee again with thy brethren.\n"
	"When she as yet was saying these things the young man said: For whom stay you? I obey not the commandment of the king, but the commandment of the law, which was given us by Moyses.\n"
	"But thou that art become the inventer of all malice against the Hebrews, shall not escape the hand of God.\n"
	"For we for our sins do suffer these things.\n"
	"And if the Lord our God hath been angry with us a little for rebuke & correction: yet he will be reconciled again to his servants.\n"
	"But thou o wicked, and of all men most flagitious, be not in vain extolled with vain hopes, inflamed against his servants.\n"
	"For thou hast not yet escaped the judgement of the almighty God, and him that beholdeth all things.\n"
	"For my brethren having now sustained short pain, are become under the testament of eternal life: but thou by the judgement of God shalt receive just punishment for thy pride.\n"
	"And I as also my brethren do yield my life and my body for the laws of our fathers: invocating God to be propitious to our nation quickly, and that thou with torments and stripes mayst confess that he only is God.\n"
	"But in me and in my brethren shall the wrath of the Almighty cease, which hath justly been brought upon all our stock.\n"
	"Then the king incensed with anger, raged against him more cruelly above all the rest, taking it grievously that he was mocked.\n"
	"And this same therefore died unspotted, wholly trusting in our Lord.\n"
	"And last of all after the sons the mother also was consumed.\n"
	"Therefore of the sacrifices, and of the exceeding cruelties there is enough said.";