const char* chap1073 = "But after the space of three years Judas understood, and they that were with him, that Demetrius the son of Seleucus with a strong multitude, & with ships was come up by the port of Tripolis to commodious places,\n"
	"and held the countries against Antiochus, and his governor Lysias.\n"
	"And one Alcimus that had been highpriest, but voluntarily was contaminated in the time of the confusion, considering that there was safety for him by no means, nor access to the altar,\n"
	"came to king Demetrius in the year an hundred fifty, offering him a crown of gold, & a palm, & besides these, Talloes, which seemed to be of the temple. And that same day indeed he held his peace.\n"
	"But having gotten a commodious time for his madness, being called of Demetrius to counsel, and asked on what thing and counsels the Jews rested, he answered:\n"
	"They of the Jews that are called Assidians, of whom Judas Machabeus is captain, nourish battles, and move seditions, neither do they suffer the realm to be quiet.\n"
	"For I also being defrauded of my ancestors' glory (I mean of the high priesthood) am come hither:\n"
	"principally indeed keeping fidelity to the king's commodities, but secondly also providing for my citizens, for by their naughtiness all our stock is not a little vexed.\n"
	"But all these things being known, o king, provide I pray thee, both for the country, and for our stock according to thy humanity published to all men.\n"
	"For as long as Judas is alive, it is unpossible that there be peace to the affairs.\n"
	"And such things being said of him, the other friends also behaving themselves as enemies against Judas, incensed Demetrius.\n"
	"Who forthwith sent Nicanor, chief over the elephants captain into Jurie:\n"
	"giving him commission, that he should take Judas himself: but them that were with him, he should disperse, & make Alcimus the high priest of the greatest temple.\n"
	"Then the nations, which had fled from Judas out of Jurie, joined themselves by troops with Nicanor, esteeming the miseries and calamities of the Jews the prosperities of their own affairs.\n"
	"The Jews therefore having heard of Nicanor's coming, and the assembly of the nations, being sprinkled with earth besought him, that ordained his people to keep them for ever, & that protecteth his portion by evident signs.\n"
	"And the captain commanding forthwith they removed from thence, and they came together to the castle of Dessau.\n"
	"And Simon the brother of Judas had joined battle with Nicanor: but he was made afraid with the sudden coming of the adversaries.\n"
	"Nevertheless Nicanor hearing the manliness of Judas' companions, & greatness of courage, that they had for the conflicts of their country, was afraid to make trial by blood.\n"
	"Wherefore he sent Posidonius, and Theodotius, and Matthias before to give and take the right hands.\n"
	"And when there was long consultation of these things, and the captain himself had moved it to the multitude, there was one sentence of them all to accord unto amity.\n"
	"Therefore they appointed a day, wherein they might secretly deal among themselves, and seats were brought forth & set for every one.\n"
	"But Judas commanded armed men to be in places convenient, lest perhaps some mischief might suddenly arise from the enemies: and they made agreeable communication.\n"
	"Nicanor abode at Jerusalem, and did nothing unjustly, and the flocks of the multitudes, that had been gathered together he diminished.\n"
	"And he esteemed Judas always dear from the heart, and he was inclined to the man.\n"
	"And he desired him to marry a wife, and to beget children. He made a marriage, he lived quietly, and they lived in common.\n"
	"But Alcimus seeing their charity one towards another, and the covenants, came to Demetrius, and said that Nicanor assented to foreign matters, and that he meant to make Judas being a traitor to the kingdom, his successor.\n"
	"Therefore the king being exasperated with this man's most wicked criminations, wrote to Nicanor, saying, that he indeed was greatly displeased for the covenant of their amity: nevertheless that he commanded him to send Machabeus quickly prisoner to Antioch.\n"
	"Which things being known Nicanor was amazed, and took it grievously, if he should undo those things which they had covenanted, being nothing hurt of the man.\n"
	"But because he could not resist the king, he observed opportunity whereby to accomplish the commandment.\n"
	"But Machabeus seeing that Nicanor dealt with him more austerely, and that he exhibited his accustomed meeting more sternly, understanding this austerity not to be of good, a few of his company gathered together, he hid himself from Nicanor.\n"
	"Which when he understood that he was stoutly prevented of the man, he came to the most great and most holy temple: and the Priests offering the accustomed hosts, he commanded the man to be delivered unto him.\n"
	"Who saying with an oath, that they knew not where he was, that was demanded, stretching out his hand to the temple,\n"
	"he sware, saying: Unless you will deliver Judas prisoner unto me, I will beat down this temple of God to the flat ground, and will dig down the altar, and this temple I will consecrate to Liber pater.\n"
	"And when he had said these things, he departed. But the Priests stretching forth their hands unto heaven, invocated him that was always the defender of their nation, saying thus:\n"
	"Thou o Lord of all, which lackest nothing, wouldest a temple of thy habitation to be made among us.\n"
	"And now o Lord holy of all holies, preserve for ever this house impolluted, which of late hath been cleansed.\n"
	"And Razias one of the ancients of Jerusalem, was accused to Nicanor, a man that was a lover of the city, and well reported of, who for his affection was called father of the Jews.\n"
	"This man long time kept the purpose of continency in Judaism, and content to give his body and life for perseverance.\n"
	"But Nicanor willing to manifest the hatred that he had against the Jews, sent five hundred soldiers to take him.\n"
	"For he thought if he had entrapped him, that he should do the Jews very great hurt.\n"
	"But the multitudes coveting to rush into his house, and to break open the gate, and to set fire thereto, when he was in taking, he struck himself with a sword:\n"
	"choosing to die nobly rather than to be made subject to sinners, and against his noble birth to suffer unworthy injuries.\n"
	"But whereas for haste he had not made the wound with a sure struck, and the multitudes brake in within the doors, running back boldly to the wall, he threw down himself manfully headlong unto the multitudes:\n"
	"who quickly giving place to his fall he fell upon his neck.\n"
	"And when he had breathed, incensed in mind he arose: and when his blood ran with a great stream, and he was wounded with most grievous wounds, running he passed through the multitude:\n"
	"and standing upon a certain steep rock, and now being become without blood, griping his bowels, with both hands he cast them upon multitudes, invocating the dominatour of life and spirit, that he would restore these to him again: and so he departed this life.";