const char* chap1075 = "THE book of the generation of JESUS Christ, the son of David, the son of Abraham.\n"
	"Abraham begat Isaac, And Isaac begat Jacob. And Jacob begat Judas and his brethren:\n"
	"And Judas begat Phares and Zaram of Thamar. And Phares begat Esron. And Esron begat Aram.\n"
	"And Aram begat Aminadab. And Aminadab begat Naasson. And Naasson begat Salmon.\n"
	"And Salmon begat Booz of Rahab. And Booz begat Obed of Ruth. And Obed begat Jesse.\n"
	"And Jesse begat David the king. And David the king begat Salomon of her that was the wife of Urias.\n"
	"And Salomon begat Roboam. And Roboam begat Abia. And Abia begat Asa.\n"
	"And Asa begat Josaphat. And Josaphat begat Joram. And Joram begat Ozias.\n"
	"And Ozias begat Joatham. And Joatham begat Achaz. And Achaz begat Ezechias.\n"
	"And Ezechias begat Manasses. And Manasses begat Amon. And Amon begat Josias.\n"
	"And Josias begat Jechonias and his brethren in the Transmigration of Babylon.\n"
	"And after the Transmigration of Babylon, Jechonias begat Salathiel. And Salathiel begat Zorobabel.\n"
	"And Zorobabel begat Abiud. And Abiud begat Eliacim. And Eliacim begat Azor.\n"
	"And Azor begat Sadoc. And Sadoc begat Achim. And Achim begat Eliud.\n"
	"And Eliud begat Eleazar. And Eleazar begat Mathan. And Mathan begat Jacob.\n"
	"And Jacob begat Joseph the husband of MARY: of whom was born JESUS, who is called CHRIST.\n"
	"Therefore all the generations from Abraham unto David, fourteen generations. And from David to the Transmigration of Babylon, fourteen generations. And from the Transmigration of Babylon unto CHRIST, fourteen generations.\n"
	"And the generation of CHRIST was in this wise. When his mother MARY was spoused to Joseph, before they came together, she was found to be with child, by the Holy Ghost.\n"
	"Whereupon Joseph her husband for that he was a just man, & would not put her to open shame: was minded secretly to dismiss her.\n"
	"But as he was thus thinking, behold the Angel of our Lord appeared to him in sleep saying: Joseph son of David, fear not to take MARY thy wife, for that which is born in her, is of the Holy Ghost.\n"
	"And she shall bring forth a Son: and thou shalt call his name JESUS. For he shall save his people from their sins.\n"
	"And all this was done that it might be fulfilled which our Lord spake by the Prophet saying.\n"
	"Behold a Virgin shall be with child, & bring forth a son, and they shall call his name Emmanuel, which being interpreted is, God with us.\n"
	"And Joseph rising up from sleep, did as the Angel of our Lord commanded him, & took his wife.\n"
	"And he knew her not till she brought forth her first born Son: & called his name JESUS.";