const char* chap1076 = "WHEN JESUS therefore was born in Bethlehem of Juda in the days of Herod the king, behold there came Sages from the East to Jerusalem,\n"
	"Saying, where is he that is born King of the Jews? For we have seen his star in the East, and are come to adore him.\n"
	"And Herod the king Hearing this, was troubled, & all Jerusalem with him.\n"
	"And assembling together all the high Priests and the Scribes of the people, he inquired of them where Christ should be born.\n"
	"But they said to him: In Bethlehem of Juda. For so it is written by the Prophet:\n"
	"And thou Bethlehem the land of Juda, art not the least among the Princes of Juda: for out of thee shall come forth the Captain that shall rule my people Israel.\n"
	"Then Herod secretly calling the Sages, learned diligently of them the time of the star which appeared to them;\n"
	"and sending them into Bethlehem, said: Go, & inquire diligently of the child; and when you shall find him, make report to me, that I also may come and adore him.\n"
	"Who having heard the king, went their way; and behold the star which they had seen in the East, went before them, until it came and stood over, where the child was.\n"
	"And seeing the star they rejoiced with exceeding great joy.\n"
	"And entering into the house, they found the child with MARY his mother, & falling down adored him; and opening their treasures, they offered to him gifts: gold, frankincense, and myrrh.\n"
	"And having received an answer in sleep that they should not return to Herod, they went back another way into their country.\n"
	"And after they were departed, Behold an Angel of our Lord appeared in sleep to Joseph, saying: Arise, & take the child and his mother, and fly into Aegypt; and be there until I shall tell thee. For it will come to pass that Herod will seek the child to destroy him.\n"
	"Who arose, & took the child and his mother by night, and retired into Aegypt: and he was there until the death of Herod:\n"
	"that it might be fulfilled which was spoken of our Lord by the Prophet, saying: Out of Aegypt have I called my Son.\n"
	"Then Herod perceiving that he was deluded by the Sages, was exceeding angry; and sending^ murdered all the men children that were in Bethlehem, & in all the borders thereof, from two year old and under, according to the time which he had diligently sought out of the Sages.\n"
	"Then was fulfilled that which was spoken by Jeremy the Prophet saying:\n"
	"A voice in Rama was heard, crying out & much wailing: Rachel bewailing her children, & would not be comforted, because they are not.\n"
	"But when Herod was dead, behold an Angel of our Lord appeared in sleep to Joseph in Aegypt.\n"
	"saying: Arise, and take the child & his mother, and go into the land of Israel. For they are dead that sought the life of the child.\n"
	"Who arose, & took the child and his mother, and came into the land of Israel.\n"
	"But hearing that Archelaus reigned in Jewry for Herod his father, he feared to go thither: and being warned in sleep retired into the quarters of Galilee.\n"
	"And coming he dwelt in a city called Nazareth: that it might be fulfilled which was said by the Prophets: That he shall be called a Nazarite.";