const char* chap1083 = "AND entering into a boat, he passed over the water, and came into his own city.\n"
	"And behold they brought to him one sick of the palsy lying in bed. And JESUS seeing their faith, said to the sick of the palsy: Have a good heart son, thy sins are forgiven thee.\n"
	"And behold certain of the Scribes said within themselves: He blasphemeth.\n"
	"And JESUS seeing their thoughts, said: Wherefore think you evil in your hearts?\n"
	"Whether is easier, to say, thy sins are forgiven thee: or to say, arise and walk.\n"
	"But that you may know that the Son of man hath power in earth to forgive sins, (then said he to the sick of the palsy,) Arise, take up thy bed, and go into thy house.\n"
	"And he arose, and went into his house.\n"
	"And the multitudes seeing it, were afraid, and glorified God that gave such power to men.\n"
	"And when JESUS passed forth from thence, he saw a man sitting in the custom-house, named Matthew; And he saith to him: Follow me. And he arose up, and followed him.\n"
	"And it came to pass as he was sitting at meat in the house, behold many Publicans and sinners came, and sat down with JESUS and his Disciples.\n"
	"And the Pharisees seeing it, said to his disciples: why doth your master eat with Publicans and sinners?\n"
	"But JESUS hearing it, said: They that are in health, need not a physician, but they that are ill at ease.\n"
	"But go your ways & learn what it is, I will mercy, & not sacrifice. For I am not come to call the just, but sinners.\n"
	"Then came to him the Disciples of John, saying: Why do we and the Pharisees fast often, but thy Disciples do not fast?\n"
	"And JESUS said to them: Can the children of the Bridegroom mourn, as long as the Bridegroom is with them? But the days will come when the Bridegroom shall be taken away from them, and then they shall fast.\n"
	"And no body putteth a piece of raw cloth to an old garment. For he taketh away the piecing thereof from the garment, and there is made a greater rent.\n"
	"Neither do they put new wine into old bottles. Otherwise the bottles break, and the wine runneth out, and the bottles perish. But new wine they put into new bottles: and both are preserved together.\n"
	"As he was speaking this unto them, behold a certain Governor approached, and adored him, saying: Lord, my daughter is even now dead; but come, lay thy hand upon her, and she shall live.\n"
	"And JESUS rising up followed him, and his Disciples.\n"
	"And behold a woman which was troubled with an issue of blood twelve years, came behind him, and touched the hem of his garment.\n"
	"For she said within herself: If I shall touch only his garment, I shall be safe.\n"
	"But JESUS turning and seeing her, said: Have a good heart daughter, thy faith hath made thee safe. And the woman became whole from that hour.\n"
	"And when JESUS was come into the house of the Governor, & saw minstrels and the multitude keeping a stir,\n"
	"he said: Depart, for the wench is not dead, but sleepeth. And they laughed him to scorn.\n"
	"And when the multitude was put forth, he entered in, and held her hand. And the maid arose.\n"
	"And this bruit went forth into all that country.\n"
	"And as JESUS passed forth from thence, there followed him two blind men crying and saying: Have mercy on us, O Son of David.\n"
	"And when he was come to the house, the blind came to him. And JESUS saith to them: Do you believe, that I can do this unto you? They say to him: Yea Lord.\n"
	"Then he touched their eyes, saying: According to your faith, be it done to you.\n"
	"And their eyes were opened, and JESUS threatened them, saying: See that no man know it.\n"
	"But they went forth, and bruited him in all that country.\n"
	"And when they were gone forth, behold they brought him a dumb man, possessed with a devil.\n"
	"And after the devil was cast out, the dumb man spake, and the multitudes marveled saying: Never was the like seen in Israel.\n"
	"But the Pharisees said: In the prince of devils he casteth out devils.\n"
	"And JESUS went about all the cities, and towns, teaching in their Synagogues, and preaching the Gospel of the Kingdom, and curing every disease, and every infirmity.\n"
	"And seeing the multitudes, he pitied them; because they were vexed, and lay like sheep that have not a shepherd.\n"
	"Then he saith to his Disciples: The harvest surely is great, but the workmen are few.\n"
	"Pray therefore the Lord of the harvest, that he send forth workmen into his harvest.";