const char* chap1086 = "AT that time JESUS went through the corn on the Sabboth: and his Disciples being hungry, began to pluck the ears, and to eat.\n"
	"And the Pharisees seeing them, said to him: Lo, thy Disciples do that which is not lawful for them to do on the Sabboth-days.\n"
	"But he said to them: Have you not read what David did when he was an hungered, and they that were with him:\n"
	"how he entered into the house of God, and did eat the loaves of proposition, which it was not lawful for him to eat, nor for them that were with him, but for Priests only?\n"
	"Or have ye not read in the Law, that on Sabboth-days the Priests in the temple do break the Sabboth, & are without blame?\n"
	"But I tell you that there is here a greater than the temple.\n"
	"And if you did know what it is, I will mercy, and not Sacrifice: you would never have condemned the innocents.\n"
	"For the Son of man is Lord of the Sabboth also.\n"
	"And when he had passed from thence, he came into their Synagogue.\n"
	"And behold there was a man which had a withered hand, and they asked him saying: Whether is it lawful to cure on the Sabboths? that they might accuse him.\n"
	"But he said to them: What man shall there be of you, that shall have one sheep: and if the same fall into a ditch on the Sabboths, will he not take hold and lift it up?\n"
	"How much better is a man more than a sheep? Therefore it is lawful on the Sabboths to do a good deed.\n"
	"Then he saith to the man: Stretch forth thy hand, and he stretched it forth, and it was restored to health even as the other.\n"
	"And the Pharisees going forth made a consultation against him, how they might destroy him.\n"
	"But JESUS knowing it, retired from thence: and many followed him, and he cured them all.\n"
	"and he charged them that they should not disclose him.\n"
	"That it might be fulfilled which was spoken by Esay the Prophet, saying:\n"
	"Behold my servant whom I have chosen, my beloved in whom my soul hath well liked. I will put my spirit upon him, and judgement to the Gentiles shall he shew.\n"
	"He shall not contend, nor cry out, neither shall any man hear in the streets his voice.\n"
	"The reed bruised he shall not break, & smoking flax he shall not extinguish: till he cast forth judgement unto victory.\n"
	"And in his name the Gentiles shall hope.\n"
	"Then was offered to him one possessed with a devil, blind and dumb: and he cured him, so that he spake and saw.\n"
	"And all the multitudes were amazed, and said: Whether this be the Son of David?\n"
	"But the Pharisees hearing it, said: This fellow casteth not out devils but in Beelzebub the prince of the devils.\n"
	"And JESUS knowing their cogitations, said to them: Every kingdom divided against itself shall be made desolate: and every city or house divided against itself, shall not stand.\n"
	"And if Satan cast out Satan, he is divided against himself: how then shall his kingdom stand?\n"
	"And if I in Beelzebub cast out devils, your children in whom do they cast out? Therefore they shall be your judges.\n"
	"But if I in the Spirit of God do cast out devils, then is the Kingdom of God come upon you.\n"
	"Or how can a man enter into the house of the strong, and rifle his vessels, unless he first bind the strong? and then he will rifle his house.\n"
	"He that is not with me, is against me: and he that gathereth not with me, scattereth.\n"
	"Therefore I say to you: Every sin and blasphemy shall be forgiven men, but the blasphemy of the Spirit shall not be forgiven.\n"
	"And whosoever shall speak a word against the Son of man, it shall be forgiven him: but he that shall speak against the Holy-Ghost, it shall not be forgiven him neither in this world, nor in the world to come.\n"
	"Either make the tree good, and his fruit good: or make the tree evil, and his fruit evil. For of the fruit the tree is known.\n"
	"You vipers' broods, how can you speak good things, whereas you are evil? For of the aboundance of the heart the mouth speaketh.\n"
	"A good man out of a good treasure bringeth forth good things: and an evil man out of an evil treasure bringeth forth evil things.\n"
	"But I say unto you, that every idle word that men shall speak, they shall render an account for it in the day of judgement.\n"
	"For of thy words thou shalt be justified, and of thy words thou shalt be condemned.\n"
	"Then answered him certain of the Scribes and Pharisees, saying: Master, we would see a sign from thee.\n"
	"Who answered, and said to them: The wicked and adulterous Generation seeketh a sign: and a sign shall not be given it, but the sign of Jonas the Prophet.\n"
	"For as Jonas was in the whale's belly three days and three nights; so shall the Son of man be in the heart of the earth three days and three nights.\n"
	"The men of Ninivee shall rise in the judgement with this Generation, and shall condemn it: because they did penance at the preaching of Jonas. And behold more than Jonas here.\n"
	"The queen of the South shall rise in the judgement with this Generation, and shall condemn it: because she came from the ends of the earth to hear the wisdom of Salomon, and behold more than Salomon here.\n"
	"And when an unclean spirit shall go out of a man, he walketh through dry places, seeking rest, and findeth not.\n"
	"Then he saith: I will return into my house whence I came out. And coming he findeth it vacant, swept with besoms, and trimmed.\n"
	"Then goeth he, and taketh with him seven other spirits more wicked than himself, and they enter in and dwell there: and the last of that man be made worse than the first. So shall it be also to this wicked Generation.\n"
	"As he was yet speaking to the multitudes, behold his mother and his brethren stood without, seeking to speak to him.\n"
	"And one said unto him: Behold thy mother and thy brethren stand without, seeking thee.\n"
	"But he answering him that told him, said: Who is my mother, and who are my brethren?\n"
	"And stretching forth his hand upon his Disciples, he said: Behold my mother and my brethren.\n"
	"For whosoever shall do the will of my Father, that is in Heaven: he is my brother, and sister, and mother.";