const char* chap1087 = "THE same day JESUS going out of the house, sat by the sea side.\n"
	"And great multitudes were gathered together unto him, in so much that he went up into a boat & sat: and all the multitude stood in the shore;\n"
	"and he spake to them many things in parables, saying: Behold the Sower went forth to sow.\n"
	"And whiles he soweth, some fell by the way side, and the fowls of the air did come and eat it.\n"
	"Other some also fell upon rocky places, where they had not much earth: and they shot up incontinent, because they had not deepness of earth,\n"
	"and after the sun was up, they parched: and because they had not root, they withered.\n"
	"And other fell among thorns: and the thorns grew and choked them.\n"
	"And other some fell upon good ground: and they yielded fruit, the one an hundredfold, the other threescore, and another thirty.\n"
	"He that hath ears to hear, let him hear.\n"
	"And his Disciples came and said to him: Why speakest thou to them in parables?\n"
	"Who answered and said unto them: Because to you it is given to know the mysteries of the Kingdom of Heaven: but to them it is not given.\n"
	"For he that hath, to him shall be given, and he shall abound: but he that hath not, from him shall be taken away that also which he hath.\n"
	"Therefore in parables I speak to them: because seeing they see not, and hearing they hear not, neither do they understand:\n"
	"and the Prophecy of Esay is fulfilled in them, which saith: With hearing shall you hear; and you shall not understand: and seeing shall you see, and you shall not see.\n"
	"For the heart of this people is waxed gross, and with their ears they have heavily heard, and their eyes they have shut: lest at any time they may see with their eyes, and hear with their ears, and understand with their heart and be converted, and I may heal them.\n"
	"But blessed are your eyes because they do see, and your ears because they do hear.\n"
	"For amen I say to you, that many Prophets and just men have desired to see the things that you see, and have not seen them: and to hear the things that you hear, and have not heard them.\n"
	"Hear you therefore the parable of the sower.\n"
	"Every one that heareth the word of the Kingdom and understandeth not, there cometh the wicked one, and catcheth away that which was sown in his heart: this is he that was sown by the way side.\n"
	"And he that was sown upon rocky places: this is he that heareth the word, and incontinent receiveth it with joy,\n"
	"yet hath he not root in himself, but is for a time: and when there falleth tribulation and persecution for the word, he is by and by scandalized.\n"
	"And he that was sown among thorns, this is he that heareth the word, and the carefulness of this world and the deceitfulness of riches choket up the word, and he becometh fruitless.\n"
	"But he that was sown upon good ground: this is he that heareth the word, and understandeth, and bringeth fruit, and yieldeth some an hundred-fold, and another threescore, and another thirty.\n"
	"Another parable he proposed to them, saying: The Kingdom of Heaven is resembled to a man that sowed good seed in his field.\n"
	"But when men were a sleep, his enemy came and oversowed cockle among the wheat, and went his way.\n"
	"And when the blade was shot up, and had brought forth fruit, then appeared also the cockle.\n"
	"And the servants of the goodman of the house coming said to him: Sir, didst thou not sow good seed in thy field? Whence then hath it cockle?\n"
	"And he said to them: The enemy-man hath done this. And the servants said to him: Wilt thou we go and gather it up?\n"
	"And he said: No lest perhaps gathering up the cockle, you may root up the wheat also together with it.\n"
	"Suffer both to grow until the harvest, and in the time of harvest I will say to the reapers: Gather up first the cockle, and bind it into bundles to burn, but the wheat gather ye into my barn.\n"
	"Another parable he proposed unto them, saying: The Kingdom of Heaven is like to a mustard-seed, which a man took and sowed in his field.\n"
	"Which is the least surely of all seeds: but when it is grown, it is greater than all herbs, and is made a tree, so that the fowls of the air come, and dwell in the branches thereof.\n"
	"Another parable he spake to them: The Kingdom of Heaven is like to leaven, which a woman took and hid in three measures of meal, until the whole was leavened.\n"
	"All these things JESUS spake in parables to the multitudes, and without parables he did not speak to them:\n"
	"that it might be fulfilled which was spoken by the Prophet saying: I will open my mouth in parables, I will utter things hidden from the foundation of the world.\n"
	"Then having dismissed the multitudes, he came into the house, and his Disciples came unto him, saying: Expound us the parable of the cockle of the field.\n"
	"Who made answer & said to them: He that soweth the good seed, is the Son of man.\n"
	"And the field, is the world. And the good seed: these are the children of the kingdom. And the cockle: are the children of the wicked one.\n"
	"And the enemy that sowed them, is the devil. But the harvest, is the end of the world. And the reapers, are the Angels.\n"
	"Even as cockle therefore is gathered up, and burnt with fire: so shall it be in the end of the world.\n"
	"The Son of man shall send his Angels, and they shall gather out of his Kingdom all scandals, and them that work iniquity:\n"
	"and shall cast them into the furnace of fire: There shall be weeping & gnashing of teeth.\n"
	"Then shall the just shine as the sun, in the Kingdom of their Father. He that hath ears to hear, let him hear.\n"
	"The Kingdom of Heaven is like a treasure hidden in a field. Which a man having found, did hide it, and for joy thereof goeth, and selleth all that he hath, and buyeth that field.\n"
	"Again the Kingdom of Heaven is like to a merchant man, seeking good pearls.\n"
	"And having found one precious pearl, he went his way, and sold all that he had, and bought it.\n"
	"Again the Kingdom of Heaven is like to a net cast into the sea, and gathering together of all kind of fishes.\n"
	"Which, when it was filled, drawing it forth, and sitting by the shore, they chose out the good^ into vessels, but the bad they did cast out.\n"
	"So shall it be in the consummation of the world. The Angels shall go forth, and shall separate the evil from among the just.\n"
	"And shall cast them into the furnace of fire; there shall be weeping and gnashing of teeth.\n"
	"Have ye understood all these things? They say to him, Yea.\n"
	"He said unto them: Therefore every Scribe instructed in the Kingdom of Heaven, is like to a man that is an householder, which bringeth forth out of his treasure new things and old.\n"
	"And it came to pass: when JESUS had ended these parables, he passed from thence.\n"
	"And coming into his own country, he taught them in their Synagogues, so that they marveled, and said: How came this fellow by this wisdom and virtues?\n"
	"Is not this the carpenter's son? Is not his mother called MARY, and his brethren James, and Joseph, and Simon, and Jude:\n"
	"and his sisters, are they not all with us? Whence therefore hath he all these things?\n"
	"And they were scandalized in him. But JESUS said to them: There is not a Prophet without honour but in his own country, and in his own house.\n"
	"And he wrought not many miracles there because of their incredulity.";