const char* chap1090 = "AND there came to him the Pharisees and Sadducees tempting: and they demanded him to shew them a sign from Heaven.\n"
	"But he answered & said to them: When it is evening, you say: It will be fair-weather, for the element is red.\n"
	"And in the morning: This day there will be a tempest, for the element doth glow and lower. The face therefore of the element you have skill to discern: & the signs of times can you not?\n"
	"The naughty and adulterous Generation seeketh for a sign: and there shall not a sign be given it, but the sign of Jonas the Prophet. And he left them and went away.\n"
	"And when his Disciples were come over the water, they forgot to take bread.\n"
	"Who said to them: Look well and beware of the leaven of the Pharisees & Sadducees.\n"
	"But they thought within themselves saying: Because we took not bread.\n"
	"And JESUS knowing it, said: Why do you think within yourselves, O ye of little faith, for that you have not bread?\n"
	"Do you not yet understand, neither do you remember the five loaves among five thousand men, and how many baskets you took up?\n"
	"neither the seven loaves, among four thousand men, and how many maunds you took up?\n"
	"Why do you not understand that I said not of bread to you: Beware of the leaven of the Pharisees, & Sadducees?\n"
	"Then they understood that he said not they should beware of the leaven of bread, but of the doctrine of the Pharisees and Sadducees.\n"
	"And JESUS came into the quarters of Caesarea Philippi: and he asked his Disciples, saying: whom say men that the Son of man is?\n"
	"But they said: Some John the Baptist, & othersome Elias, and others Jeremie, or one of the Prophets.\n"
	"JESUS saith to them: But whom do you say that I am?\n"
	"Simon Peter answered & said: Thou art Christ the Son of the living God.\n"
	"And JESUS answering, said to him: Blessed art thou Simon Bar-Jona: because flesh & blood hath not revealed it to thee, but my Father which is in Heaven.\n"
	"And I say to thee: That thou art Peter; and upon this Rock will I build my Church, and the gates of Hell shall not prevail against it.\n"
	"And I will give to thee the keys of the Kingdom of Heaven. And whatsoever thou shalt bind upon earth, it shall be bound also in the Heavens: and whatsoever thou shalt loose in earth, it shall be loosed also in the Heavens.\n"
	"Then he commanded his Disciples, that they should tell nobody that he was JESUS CHRIST.\n"
	"From that time JESUS began to shew his Disciples, that he must go to Jerusalem, & suffer many things of the Ancients & Scribes and Chief-Priests, and be killed, and the third day rise again.\n"
	"And Peter taking him unto him, began to rebuke him, saying: Lord, be it far from thee, this shall not be unto thee.\n"
	"Who turning said to Peter: Go after me Satan, thou art a scandal unto me: because thou savourest not the things that are of God, but the things that are of men.\n"
	"Then JESUS said to his Disciples: If any man will come after me, let him deny himself, and take up his cross, and follow me.\n"
	"For he that will save his life, shall lose it, and he that shall lose his life for me, shall find it.\n"
	"For what doth it profit a man, if he gain the whole world, and sustain the damage of his soul? Or what permutation shall a man give for his soul?\n"
	"For the Son of man shall come in the glory of his Father with his Angels: and then will he render to every man according to his works.\n"
	"Amen I say to you, there be some of them that stand here, that shall not taste death, till they see the Son of man coming in his Kingdom.";