const char* chap1091 = "AND after six days^ JESUS taketh unto him Peter, and James, & John his brother, & bringeth them into a high mountain apart:\n"
	"And he was transfigured before them. And his face did shine as the sun: & his garments became white as snow.\n"
	"And behold there appeared to them Moyses and Elias talking with him.\n"
	"And Peter answering, said to JESUS: Lord, it is good for us to be here: if thou wilt, let us make here three tabernacles, one for thee, and one for Moyses, and one for Elias.\n"
	"And as he was yet speaking, behold a bright cloud overshadowed them. And lo a voice out of the cloud, saying: This is my wellbeloved Son, in whom I am well pleased: hear ye him.\n"
	"And the Disciples hearing it, fell upon their face, and were sore afraid.\n"
	"And JESUS came and touched them: and he said to them: Arise, and fear not.\n"
	"And they lifting up their eyes, saw nobody, but only JESUS.\n"
	"And as they descended from the mount, JESUS commanded them, saying: Tell the vision to nobody, till the Son of man be risen from the dead.\n"
	"And his Disciples asked him, saying: what say the Scribes then, that Elias must come first?\n"
	"But he answering, said to them: Elias indeed shall come, and restore all things.\n"
	"And I say to you, that Elias is already come, and they did not know him, but wrought on him whatsoever they would. So also the Son of man shall suffer of them.\n"
	"Then the Disciples understood, that of John the Baptist he had spoken to them.\n"
	"And when he was come unto the multitude, there came to him a man falling down upon his knees before him, saying: Lord have mercy upon my Son, for he is lunatic, and sore vexed: for he falleth often into the fire, and often into the water.\n"
	"And I offered him to thy Disciples, and they could not cure him.\n"
	"JESUS answered and said: O faithless and perverse generation, how long shall I be with you? How long shall I suffer you? Bring him hither to me.\n"
	"And JESUS rebuked him, and the devil went out of him, and the lad was cured from that hour.\n"
	"Then came the Disciples to JESUS secretly, and said: Why could we not cast him out?\n"
	"JESUS said to them, because of your incredulity: For, Amen I say to you, if you have faith as a mustard seed, you shall say to this mountain, Remove from thence thither, and it shall remove; and nothing shall be impossible to you.\n"
	"But this kind is not cast out but by prayer and fasting.\n"
	"And when they conversed in Galilee, JESUS said to them: The Son of man is to be betrayed into the hands of men:\n"
	"and they shall kill him, and the third day he shall rise again. And they were stroken sad exceedingly.\n"
	"And when they were come to Capharnaum, there came they that received the didrachmes, unto Peter, and said to him: Your master doth he not pay the didrachmes?\n"
	"He saith, Yes. And when he was entered into the house, JESUS prevented him, saying: What is thy opinion Simon? The kings of the earth, of whom receive they tribute or cense? Of their children, or of strangers?\n"
	"And he said: Of strangers. JESUS said to him: Then the children are free.\n"
	"But that we may not scandalize them, go thy ways to the sea, and cast a hook: and that fish which shall first come up, take: and when thou hast opened his mouth, thou shalt find a stater: take that, and give it them for me and thee.";