const char* chap1092 = "AT that hour the Disciples came to JESUS, saying: Who, thinkest thou, is the greater in the Kingdom of Heaven?\n"
	"And JESUS calling unto him a little child, set him in the midst of them,\n"
	"and said: Amen I say to you, unless you be converted, and become as little children, you shall not enter into the Kingdom of Heaven.\n"
	"Whosoever therefore shall humble himself as this little child, he is the greater in the Kingdom of Heaven.\n"
	"And he that shall receive one such little child in my name, receiveth me.\n"
	"And he that shall scandalize one of these little ones that believe in me, it is expedient for him that a millstone be hanged about his neck, and that he be drowned in the depth of the sea.\n"
	"Woe be to the world for scandals. For it is necessary that scandals do come: but nevertheless woe to that man by whom the scandal cometh.\n"
	"And if thy hand, or thy foot scandalize thee, cut it off, and cast it from thee. It is good for thee to go into life maimed or lame, rather than having two hands or two feet, to be cast into everlasting fire.\n"
	"And if thine eye scandalize thee, pluck him out, and cast him from thee: It is good for thee having one eye to enter into life, rather than having two eyes to be cast into the Hell of fire.\n"
	"See that you despise not one of these little ones: for I say to you, that their Angels in Heaven always do see the face of my Father which is in Heaven.\n"
	"For the Son of man is come to save that which was perished.\n"
	"How think you? If a man have an hundred sheep, and one of them shall go astray; doth he not leave ninety nine in the mountains, and goeth to seek that which is strayed?\n"
	"And if it chance that he find it: Amen I say to you, that he rejoiceth more for that, than for the ninety nine that went not astray.\n"
	"Even so it is not the will of your Father, which is in Heaven, that one perish of these little ones.\n"
	"But if thy brother shall offend against thee, go, and rebuke him between thee and him alone. If he shall hear thee, thou shalt gain thy brother.\n"
	"And if he will not hear thee, join with thee besides, one or two: that in the mouth of two or three witnesses every word may stand.\n"
	"And if he will not hear them, tell the Church. And if he will not hear the Church, let him be to thee as the Heathen and the Publican.\n"
	"Amen I say to you, whatsoever you shall bind upon earth, shall be bound also in Heaven: and whatsoever you shall loose upon earth, shall be loosed also in Heaven.\n"
	"Again I say to you, that if two of you shall consent upon earth, concerning every thing whatsoever they shall ask, it shall be done to them of my Father which is in Heaven.\n"
	"For where there be two or three gathered in my name, there am I in the midst of them.\n"
	"Then came Peter unto him and said: Lord, how often shall my brother offend against me, & I forgive him? Until seven times?\n"
	"JESUS said to him: I say not to thee until seven times but until seventy times seven times.\n"
	"Therefore is the Kingdom of Heaven likened to a man being a king, that would make an account with his servants.\n"
	"And when he began to make the account, there was one presented unto him that owed him ten thousand talents.\n"
	"And having not whence to repay it, his Lord commanded that he should be sold, and his wife and children, and all that he had, and it to be repayed.\n"
	"But that servant falling down, besought him, saying: Have patience toward me, and I will repay thee all,\n"
	"And the Lord of that servant moved with pity, dismissed him, and the debt he forgave him.\n"
	"And when that servant was gone forth, he found one of his fellow-servants that did owe him an hundred pence: and laying hands upon him throttled him, saying: Repay that thou owest.\n"
	"And his fellow-servant falling down, besought him, saying: Have patience toward me, and I will repay thee all.\n"
	"And he would not: but went his way, and cast him into prison, till he repayed the debt.\n"
	"And his fellow-servants seeing what was done, were very sorry, and they came, and told their Lord all that was done.\n"
	"Then his Lord called him; and he said unto him: Thou ungracious servant, I forgave thee all the debt, because thou besoughtest me:\n"
	"oughtest not thou therefore also to have mercy upon thy fellow-servant, even as I had mercy upon thee?\n"
	"And his Lord being angry^ delivered him to the tormenters, until he repayed all the debt.\n"
	"So also shall my Heavenly Father do to you, if you forgive not every one his brother from your hearts.";