const char* chap1095 = "AND when they drew nigh to Jerusalem, and were come to Beth-phagee unto Mount-olivet, then JESUS sent two Disciples,\n"
	"saying to them: Go ye into the town that is against you, and immediately you shall find an ass tied and a colt with her: loose them & bring them to me:\n"
	"And if any man shall say ought unto you, say ye, that our Lord hath need of them: and forthwith he will let them go.\n"
	"And this was done that it might be fulfilled which was spoken by the Prophet, saying:\n"
	"Say ye to the daughter of Sion: Behold thy King cometh to thee, meek, & sitting upon an ass and a colt the foal of her that is used to the yoke.\n"
	"And the Disciples going, did as JESUS commanded them.\n"
	"And they brought the ass and the colt: and laid their garments upon them, and made him to sit thereon.\n"
	"And a very great multitude spread their garments in the way: and others did cut boughs from the trees, and strawed them in the way:\n"
	"and the multitudes that went before and that followed, cried, saying: Hosanna to the Son of David: Blessed is he that cometh in the name of our Lord. Hosanna in the highest.\n"
	"And when he was entered Jerusalem, the whole city was moved, saying: Who is this?\n"
	"And the People said: This is JESUS the Prophet, of Nazareth in Galilee.\n"
	"And JESUS entered into the temple of God, and cast out all that sold and bought in the temple, and the tables of the bankers, & the chairs of them that sold pigeons he overthrew:\n"
	"and he saith to them: It is written, My house shall be called the house of prayer: but you have made it a den of thieves.\n"
	"And there came to him the blind, and the lame in the temple; and he healed them.\n"
	"And the chief Priests & Scribes seeing the marvelous things that he did, and the children crying in the temple, & saying, Hosanna to the Son of David; they had indignation,\n"
	"and said to him: Hearest thou what these say? And JESUS said to them: Very well. Have you never read: That out of the mouth of infants and sucklings thou hast perfited praise?\n"
	"And leaving them, he went forth out of the city into Bethania, and remained there.\n"
	"And in the morning returning into the city, he was an hungered.\n"
	"And seeing a certain figtree by the way side, he came to it, and found nothing on it but leaves only, and he saith to it: Never grow there fruit of thee for ever. And incontinent the figtree was withered.\n"
	"And the Disciples seeing it, marveled saying: How is it withered incontinent?\n"
	"And JESUS answering said to them: Amen I say to you, if you shall have faith, and stagger not, not only that of the figtree shall you do, but and if you shall say to this mountain, Take up and throw thyself into the sea, it shall be done.\n"
	"And all things whatsoever you shall ask in prayer believing, you shall receive.\n"
	"And when he was come into the temple, there came to him as he was teaching, the chief Priests and ancients of the people, saying: In what power doest thou these things? and who hath given thee this power?\n"
	"JESUS answering said to them: I also will ask you one word, which if you shall tell me, I also will tell you in what power I do these things.\n"
	"The Baptism of John whence was it? from Heaven, or from men? But they thought within themselves, saying:\n"
	"If we shall say from Heaven, he will say to us, why then did you not believe him? But if we shall say from men, we fear the multitude, for all hold John as a Prophet.\n"
	"And answering to JESUS they said: We know not. He also said to them: Neither do I tell you in what power I do these things.\n"
	"But what is your opinion? A certain man had two sons, and coming to the first, he said: Son, go work today in my vineyard.\n"
	"And he answering, said: I will not. But afterward moved with repentance he went.\n"
	"And coming to the other, he said likewise. And he answering, said: I go Lord, and he went not:\n"
	"Which of the two did the father's will? They say to him: The first. JESUS saith to them: Amen I say to you, that the Publicans and whores go before you into the Kingdom of God.\n"
	"For John came to you in the way of justice, and you did not believe him. But the Publicans and whores did believe him: but you seeing it, neither have ye had repentance afterward, to believe him.\n"
	"Another parable hear ye: A man there was^ an householder who planted a vineyard, and made a hedge round about it, and digged in it a press, and builded a tower, and let it out to husbandmen: and went forth into a strange country.\n"
	"And when the time of fruits drew nigh, he sent his servants to the husbandmen, to receive the fruits thereof.\n"
	"And the husbandmen apprehending his servants, one they beat, another they killed, and another they stoned.\n"
	"Again he sent other servants more than the former: and they did to them likewise.\n"
	"And last of all he sent to them his son, saying: They will reverence my son.\n"
	"But the husbandmen seeing the son, said within themselves This is the heir, come, let us kill him, and we shall have his inheritance.\n"
	"And apprehending him they cast him forth out of the vineyard, & killed him.\n"
	"When therefore the Lord of the vineyard shall come, what will he do to those husbandmen?\n"
	"They say to him: The naughty men he will bring to naught: and his vineyard he will let out to other husbandmen, that shall render him the fruit in their seasons.\n"
	"JESUS saith to them: Have you never read in the Scriptures: The stone which the builders rejected, the same is made into the head of the corner? By our Lord was this done, and it is marvelous in our eyes.\n"
	"Therefore I say to you, that the Kingdom of God shall be taken away from you, and shall be given to a Nation yielding the fruits thereof.\n"
	"And he that falleth upon this stone, shall be broken: and on whom it falleth, it shall all to bruise him.\n"
	"And when the chief Priests and Pharisees had heard his parables, they knew that he spake of them.\n"
	"And seeking to lay hands upon him, they feared the multitudes: because they held him as a Prophet.";