const char* chap1096 = "AND JESUS answering, spake again in parables to them, saying:\n"
	"The Kingdom of Heaven is likened to a man being a king, which made a marriage to his son.\n"
	"And he sent his servants to call them that were invited to the marriage: and they would not come.\n"
	"Again he sent other servants, saying: Tell them that were invited, Behold I have prepared my dinner; my beeves & fatlings are killed, and all things are ready: come ye to the marriage.\n"
	"But they neglected and went their ways, one to his farm, and another to his merchandise:\n"
	"and the rest laid hands upon his servants, and spitefully entreating them, murdered them.\n"
	"But when the king had heard of it, he was wroth, and sending his hosts, destroyed those murderers, and burnt their city.\n"
	"Then he saith to his servants: The marriage indeed is ready: but they that were invited, were not worthy.\n"
	"Go ye therefore into the high ways; and whosoever you shall find, call to the marriage.\n"
	"And his servants going forth into the ways, gathered together all that they found, bad and good: and the marriage was filled with guests.\n"
	"And the king went in to see the guests: and he saw there^ a man not attired in a wedding garment.\n"
	"And he saith to him: Friend, how camest thou in hither not having a wedding garment? But he was dumb.\n"
	"Then the king said to the waiters: Bind his hands and feet, and cast him into the utter darkness: there shall be weeping & gnashing of teeth.\n"
	"For many be called, but few elect.\n"
	"Then the Pharisees departing, consulted among themselves for to entrap him in his talk.\n"
	"And they send to him their disciples with the Herodians, saying: Master, we know that thou art a true speaker, and teachest the way of God in truth, neither carest thou for any man. For thou dost not respect the person of men:\n"
	"Tell us therefore what is thy opinion, is it lawful to give tribute to Caesar, or not?\n"
	"But JESUS knowing their naughtiness, said: What do you tempt me Hypocrites?\n"
	"Shew me the tribute coin. And they offered him a penny.\n"
	"And JESUS saith to them: Whose is this image and superscription?\n"
	"They say to him, Caesar's. Then he saith to them: Render therefore the things that are Caesar's, to Caesar: and the things that are God's, to God.\n"
	"And hearing it they marveled, and leaving him went their ways.\n"
	"That day there came to him the Sadducees, that say there is no resurrection, and asked him,\n"
	"saying: Master, Moyses said, If a man die^ not having a child, that his brother marry his wife, and raise up seed to his brother.\n"
	"And there were with us seven brethren: and the first having married a wife, died; and not having issue, left his wife to his brother.\n"
	"In like manner the second and the third even to the seventh.\n"
	"And last of all^ the woman died also.\n"
	"In the Resurrection therefore whose wife of the seven shall she be? For they all had her.\n"
	"And JESUS answering, said to them: You do err, not knowing the Scriptures, nor the power of God.\n"
	"For in the resurrection neither shall they marry nor be married: but are as the Angels of God in Heaven.\n"
	"And concerning the resurrection of the dead, have you not read that which was spoken of God saying to you.\n"
	"I am the God of Abraham, and the God of Isaac, and the God of Jacob? He is not God of the dead, but of the living.\n"
	"And the multitudes hearing it, marveled at his doctrine.\n"
	"But the Pharisees hearing that he had put the Sadducees to silence, came together:\n"
	"and one of them a doctor of law asked of him, tempting him:\n"
	"Master, which is the great commandment in the law?\n"
	"JESUS said to him: Thou shalt love the Lord thy God from thy whole heart, and with thy whole soul, and with thy whole mind.\n"
	"This is the greatest & the first commandment.\n"
	"And the second is like to this: Thou shalt love thy neighbour as thyself.\n"
	"On these two commandments dependeth the whole Law and the Prophets.\n"
	"And the Pharisees being assembled, JESUS asked them\n"
	"saying: What is your opinion of Christ? whose son is he? They say to him, David's.\n"
	"He saith to them: How then doth David in spirit call him Lord, saying:\n"
	"The Lord said to my Lord, sit on my right hand, until I put thine enemies the foot-stool of thy feet?\n"
	"If David therefore call him Lord, how is he his son?\n"
	"And no man could answer him a word: neither durst any man from that day ask him any more.";