const char* chap1098 = "AND JESUS being gone out of the temple, went. And his Disciples came to shew him the buildings of the temple.\n"
	"And he answering said to them: Do you see all these things? Amen I say to you, there shall not be left here a stone upon a stone that shall not be destroyed.\n"
	"And when he was sitting upon Mount-olivet, the Disciples came to him secretly, saying: Tell us, when shall these things be? and what shall be the sign of thy coming, and of the consummation of the world?\n"
	"And JESUS answering, said to them: Beware that no man seduce you:\n"
	"for many shall come in my name saying, I am Christ; and they shall seduce many.\n"
	"For you shall hear of wars, & bruits of wars. See that ye be not troubled. For these things must be done, but the end is not yet.\n"
	"For Nation shall rise against Nation, and Kingdom against Kingdom; and there shall be pestilences, and famines, and earth-quakes in places;\n"
	"and all these things are the beginnings of sorrows.\n"
	"Then shall they deliver you into tribulation, and shall kill you: and you shall be odious to all Nations for my name's sake.\n"
	"And then many shall be scandalized: and they shall deliver up one another: and they shall hate one another.\n"
	"And many false-prophets shall rise, and shall seduce many.\n"
	"And because iniquity shall abound, the charity of many shall wax cold.\n"
	"But he that shall persevere to the end, he shall be saved.\n"
	"And this Gospel of the Kingdom shall be preached in the whole world, for a testimony to all nations, and then shall come the consummation.\n"
	"Therefore when you shall see the abomination of desolation, which was spoken of by Daniel the Prophet, standing in the holy place (he that readeth, let him understand)\n"
	"then they that are in Jewry, let them flee to the mountains:\n"
	"and he that is on the house-top let him not come down to take any thing out of his house:\n"
	"and he that is in the field, let him not go back to take his coat.\n"
	"And woe to them that are with child, and that give suck in those days.\n"
	"But pray that your flight be not in the winter, or on the Sabboth,\n"
	"For there shall be then great tribulation, such as hath not been from the beginning of the world until now, neither shall be.\n"
	"And unless those days had been shortened, no flesh should be saved: but for the Elect the days shall be shortened.\n"
	"Then if any man shall say unto you: Lo here is Christ, or there; do not believe him.\n"
	"For there shall rise false Christs and false-Prophets, and shall shew great signs and wonders, so that the Elect also (if it be possible) may be induced into error.\n"
	"Lo I have foretold you.\n"
	"If therefore they shall say unto you: Behold he is in the desert; go ye not out: Behold in the closets, believe it not.\n"
	"For as lightning cometh out of the east, and appeareth even into the west, so shall also the advent of the Son of man be.\n"
	"Wheresoever the body is, thither shall the Eagles also be gathered together.\n"
	"And immediately after the tribulation of those days the sun shall be darkened, and the moon shall not give her light, and the stars shall fall from Heaven, and the powers of Heaven shall be moved:\n"
	"and then shall appear the sign of the Son of man in Heaven: and then shall all tribes of the earth bewail: and they shall see the Son of man coming in the clouds of Heaven with much power and majesty.\n"
	"And he shall send his Angels with a trumpet, and a great voice: and they shall gather together his Elect from the four winds, from the furthest parts of Heaven even to the ends thereof.\n"
	"And of the figtree learn a parable: When now the bough thereof is tender, and the leaves come forth, you know that summer is nigh.\n"
	"So you also, when you shall see these things, know ye that it is nigh even at the doors.\n"
	"Amen I say to you, that this generation shall not pass, till all these things be done.\n"
	"Heaven and earth shall pass, but my words shall not pass.\n"
	"But of that day and hour nobody knoweth, neither the Angels of Heaven, but the Father alone.\n"
	"And as in the days of Noe, so shall also the coming of the Son of man be.\n"
	"For as they were in the days before the flood, eating and drinking, marrying and giving to marriage, even unto that day in which Noe entered into the ark,\n"
	"and knew not till the flood came, & took them all: so also shall the coming of the Son of man be.\n"
	"Then two shall be in the field: one shall be taken, & one shall be left.\n"
	"Two women grinding in the mill: one shall be taken, & one shall be left.\n"
	"Watch therefore because you know not what hour your Lord will come.\n"
	"But this know ye, that if the good-man of the house did know what hour the thief would come, he would surely watch, and would not suffer his house to be broken up.\n"
	"Therefore be you also ready, because at what hour you know not, the Son of man will come.\n"
	"Who, thinkest thou, is a faithful and wise servant, whom his Lord hath appointed over his family, to give them meat in season?\n"
	"Blessed is that servant, whom when his Lord cometh, he shall find so doing.\n"
	"Amen I say to you, that over all his goods shall he appoint him.\n"
	"But if that naughty servant shall say in his heart: My Lord is long a coming:\n"
	"and shall begin to strike his fellow-servants, and eateth, & drinketh with drunkards:\n"
	"the Lord of that servant shall come in a day that he hopeth not, & an hour that he knoweth not,\n"
	"and shall divide him, & appoint his portion with the hypocrites: there shall be weeping and gnashing of teeth.";