const char* chap1099 = "THEN shall the Kingdom of Heaven be like to ten virgins, which taking their lamps went forth to meet the bridegroom and the bride.\n"
	"And five of them were foolish, and five wise.\n"
	"But the five foolish, having taken their lamps, did not take oil with them:\n"
	"but the wise did take oil in their vessels with the lamps.\n"
	"And the bridegroom tarrying long^ they slumbered all and slept.\n"
	"And at midnight there was a clamour made: Behold the bridegroom cometh, go ye forth to meet him.\n"
	"Then arose all those virgins, and they trimmed their lamps.\n"
	"And the foolish said to the wise: Give us of your oil, because our lamps are going out.\n"
	"The wise answered, saying: Lest peradventure there suffice not for us and you, go rather to them that sell, and buy for yourselves.\n"
	"And whiles they went to buy, the bridegroom was come: and they that were ready, entered with him to the marriage, and the gate was shut.\n"
	"But last of all come also the other virgins saying: Lord, Lord, open to us.\n"
	"But he answering said: Amen I say to you, I know you not.\n"
	"Watch ye therefore, because you know not the day nor the hour.\n"
	"For even as a man going into a strange country, called his servants, and delivered them his goods.\n"
	"And to one he gave five talents, and to another two, and to another one, to every one According to his proper faculty: and immediately he took his journey.\n"
	"And he that had received the five talents, went his way, and occupied with the same, and gained other five.\n"
	"Likewise also he that had received the two, gained other two.\n"
	"But he that had received the one, going his way digged into the earth, and hid his lord's money.\n"
	"But after much time the lord of those servants cometh, & made account with them.\n"
	"And there came he that had received the five talents, & offered other five talents, saying: Lord^ five talents thou didst deliver me, behold I have gained other five besides.\n"
	"His lord said unto him: Well-fare thee good and faithful servant, because thou hast been faithful over a few things, I will place thee over many things: enter into the joy of thy lord.\n"
	"And there came also he that had received the two talents, & said: Lord^ two talents thou didst deliver me: behold I have gained other two.\n"
	"His lord said to him: Well-fare thee good & faithful servant: because thou hast been faithful over a few things, I will place thee over many things, enter into the joy of thy lord.\n"
	"And he also that had received the one talent, came forth, and said: Lord, I know that thou art a hard man; thou reapest where thou didst not sow, and gatherest where thou strawedst not:\n"
	"and being afraid I went, and hid thy talent in the earth: behold lo here thou hast that which thine is.\n"
	"And his lord answering, said to him: Naughty and slothful servant, thou didst know that I reap where I sow not, & gather where I strawed not:\n"
	"thou oughtest therefore to have committed my money to the bankers, and coming I might have received mine own with usury.\n"
	"Take ye away therefore the talent from him, and give it him that hath ten talents.\n"
	"For to every one that hath shall be given, and he shall abound: but from him that hath not, that also which he seemeth to have, shall be taken away from him.\n"
	"And the unprofitable servant^ cast ye out into the utter darkness. There shall be weeping and gnashing of teeth.\n"
	"And when the Son of man shall come in his majesty, and all the Angels with him, then shall he sit upon the seat of his majesty:\n"
	"and all nations shall be gathered together before him, and he shall separate them one from another, as the pastor separateth the sheep from the goats:\n"
	"and shall set the sheep at his right hand, but the goats at his left.\n"
	"Then shall the King say to them that shall be at his right hand: Come ye blessed of my Father, possess you the Kingdom prepared for you from the foundation of the world.\n"
	"For I was an hungered, and you gave me to eat: I was a thirst, and you gave me to drink.\n"
	"I was a stranger, and you took me in: naked, and you covered me: sick, and you visited me. I was in prison, and you came to me.\n"
	"Then shall the just answer him, saying: Lord, when did we see thee an hungered, and fed thee, a thirst, and gave thee drink?\n"
	"and when did we see thee a stranger, and took thee in? Or naked, and covered thee?\n"
	"Or when did we see thee sick or in prison, and came to thee?\n"
	"And the King answering, shall say to them: Amen I say to you, as long as you did it to one of these my least brethren, you did it to me.\n"
	"Then he shall say to them also that shall be at his left hand: Get ye away from me you cursed into fire everlasting, which was prepared for the devil and his angels.\n"
	"For I was an hungered, & you gave me not to eat, I was a thirst, & you gave me not to drink.\n"
	"I was a stranger, and you took me not in: naked, and you covered me not: sick, & in prison, and you did not visit me.\n"
	"Then they also shall answer him, saying: Lord, when did we see thee an hungered, or a thirst, or a stranger, or naked, or sick, or in prison, & did not minister to thee?\n"
	"Then he shall answer them, saying, Amen I say to you, as long as you did it not to one of these lesser, neither did you it to me.\n"
	"And these shall go into punishment everlasting: but the just, into life everlasting.";