const char* chap1102 = "AND in the evening of the Sabboth which dawneth on the first of the Sabboth, came Mary Magdalene, and the other Mary to see the sepulchre.\n"
	"And behold there was made a great earth-quake. For an Angel of our Lord descended from Heaven: and coming, rolled back the stone, and sat upon it:\n"
	"and his countenance was as lightning, and his garment as snow.\n"
	"And for fear of him, the watchmen were frighted, and became as dead.\n"
	"And the Angel answering said to the women: Fear not you. For I know that you seek JESUS that was crucified.\n"
	"He is not here, for he is risen, as he said. Come, and see the place where our Lord was laid.\n"
	"And going quickly, tell ye his Disciples that he is risen: and behold he goeth before you into Galilee: there you shall see him. Lo I have foretold you.\n"
	"And they went forth quickly out of the monument with fear and great joy, running to tell his Disciples.\n"
	"And behold JESUS met them, saying: All hail. But they came near and took hold of his feet, and adored him.\n"
	"Then JESUS said to them: Fear not. Go, tell my brethren that they go into Galilee, there they shall see me.\n"
	"Who when they were departed, behold certain of the watchmen came into the city, and told the chief Priests all things that had been done.\n"
	"And being assembled together with the Ancients, taking counsel, they gave a great sum of money to the soldiers,\n"
	"saying: Say you, that his Disciples came by night, and stole him away when we were asleep.\n"
	"And if the President shall hear of this, we will persuade him, and make you secure.\n"
	"But they taking the money, did as they were taught. And this word was bruited abroad among the Jews, even unto this day.\n"
	"And the eleven Disciples went into Galilee, unto the mount where JESUS had appointed them.\n"
	"And seeing him they adored, but some doubted.\n"
	"And JESUS coming near spake unto them, saying: All power is given to me in Heaven and in earth.\n"
	"going therefore teach ye all Nations: BAPTIZING THEM IN THE NAME OF THE FATHER, AND OF THE SON, AND OF THE HOLY GHOST,\n"
	"teaching them to observe all things whatsoever I have commanded you: and behold I am with you all days, even to the consummation of the world.";