const char* chap1109 = "AND there assemble together unto him the Pharisees and certain of the Scribes, coming from Jerusalem.\n"
	"And when they had seen certain of his Disciples eat bread with common hands, that is, not washed, they blamed them.\n"
	"For the Pharisees, and all the Jews, unless they often wash their hands, eat not, holding the tradition of the Ancients:\n"
	"And from the market, unless they be washed, they eat not: and many other things there be that were delivered unto them to observe, the washings of cups and cruses, and of brazen vessels & beds.\n"
	"And the Pharisees and Scribes asked him: Why do not thy Disciples walk according to the tradition of the Ancients, but they eat bread with common hands?\n"
	"But he answering, said to them: Well did Esay Prophesy of you Hypocrites, as it is written: This people honoureth me with their lips, but their heart is far from me.\n"
	"And in vain do they worship me, teaching doctrines precepts of men.\n"
	"For leaving the commandment of God, you hold the traditions of men, the washings of cruses and cups: & many other things you do like to these.\n"
	"And he said to them, well do you frustrate the precept of God, that you may observe your own tradition.\n"
	"For Moyses said: Honour thy father and thy mother; and, He that shall curse father or mother, dying let him die.\n"
	"But you say: If a man say to father or mother, Corban (which is a gift) whatsoever proceedeth from me, shall profit thee:\n"
	"And further you suffer him not to do ought for his father or mother,\n"
	"defeating the word of God for your own tradition which you have given forth. And many other things of this sort you do.\n"
	"And calling again the multitude unto him, he said to them: Hear me all you, and understand.\n"
	"Nothing is without a man^ entering into him, that can defile him. But the things that proceed from a man^ those are they that make a man common.\n"
	"If any man have ears to hear, let him hear.\n"
	"And when he was entered into the house from the multitude, his Disciples asked him the parable.\n"
	"And he saith to them: So are you also unskillful? Understand you not that every thing from without, entering into a man, cannot make him common:\n"
	"because it entereth not into his heart, but goeth into the belly, and is cast out into the privy, purging all the meats?\n"
	"But he said that the things which come forth from a man, they make a man common.\n"
	"For from within out of the heart of men proceed evil cogitations, adulteries, fornications, murders,\n"
	"thefts, avarices, wickedness, guile, impudicities, and evil eye, blasphemy, pride, foolishness.\n"
	"All these evils proceed from within, and make a man common.\n"
	"And rising from thence he went into the coasts of Tyre and Sidon: and entering into a house, he would that no man should know, and he could not be hid.\n"
	"For a woman immediately as she heard of him, whose daughter had an unclean spirit, entered in, and fell down at his feet.\n"
	"For the woman was a Gentile, a Syrophaenician born. And she besought him that he would cast forth the devil out of her daughter.\n"
	"Who said to her: Suffer first the children to be filled. For it is not good to take the children's bread, and cast it to the dogs.\n"
	"But she answered, and said to him: Yea Lord; for the whelps also eat under the table^ of the crumbs of the children.\n"
	"And he said to her: For this saying go thy way, the devil is gone out of thy daughter.\n"
	"And when she was departed into her house, she found the maid lying upon the bed, and the devil gone out.\n"
	"And again going out of the coasts of Tyre, he came by Sidon to the sea of Galilee through the midst of the coasts of Decapolis.\n"
	"And they bring to him one deaf and dumb; and they besought him that he would impose his hand upon him.\n"
	"And taking him from the multitude apart, he put his fingers into his ears, and spitting, touched his tongue;\n"
	"And looking up unto Heaven, he groaned, and said to him: Ephphetha, which is, Be thou opened.\n"
	"And immediately his ears were opened, and the string of his tongue was loosed, and he spake right.\n"
	"And he commanded them not to tell any body. But how much he commanded them, so much the more a great deal did they publish it.\n"
	"And so much the more did they wonder, saying: He hath done all things well; he hath made both the deaf to hear, and the dumb to speak.";