const char* chap1110 = "IN those days again when there was a great multitude, and had not what to eat: calling his Disciples together, he saith to them:\n"
	"I have compassion upon the multitude, because lo three days they now endure with me, neither have what to eat.\n"
	"And if I dismiss them fasting into their home, they will faint in the way; for some of them came far off.\n"
	"And his Disciples answered him: Whence may a man fill them here with bread in the wilderness?\n"
	"And he asked them: How many loaves have ye? Who said: Seven.\n"
	"And he commanded the multitude to sit down upon the ground. And taking the seven loaves, giving thanks he brake, and gave to his Disciples for to set before them, and they did set them before the multitude.\n"
	"And they had a few little fishes; and he blessed them, and commanded them to be set before them.\n"
	"And they did eat and were filled, and they took up that which was left of the fragments, seven maunds.\n"
	"And they that had eaten were about four thousand: and he dismissed them.\n"
	"And immediately going up into the boat with his Disciples, he came into the quarters of Dalmanutha.\n"
	"And the Pharisees went forth, and began to question with him, asking of him a sign from Heaven, tempting him.\n"
	"And groaning in spirit, he saith: Why doth this Generation ask a sign? Amen I say to you, If a sign shall be given to this generation.\n"
	"And leaving them, he went up again into the boat, and passed beyond the strait.\n"
	"And they forgot to take bread: and they had but one loaf with them in the boat.\n"
	"And he commanded them, saying: Look well and beware of the leaven of the Pharisees, and the leaven of Herod.\n"
	"And they reasoned among themselves saying: Because we have not bread.\n"
	"Which JESUS knowing, saith to them: Why do you reason, because you have not bread? do you not yet know nor understand? Yet have ye your heart blinded?\n"
	"having eyes see you not? and having ears hear you not? Neither do you remember?\n"
	"When I brake five loaves among five thousand; and how many baskets full of fragments took you up? They say to him, Twelve.\n"
	"When also seven loaves among four thousand, how many maunds of fragments took you up? And they say to him, Seven.\n"
	"And he said to them: How do you not yet understand?\n"
	"And they come to Bethsaida; and they bring to him one blind, and desired him that he would touch him.\n"
	"And taking the hand of the blind, he led him forth out of the town; and spitting into his eyes, imposing his hands, he asked him if he saw any thing.\n"
	"And looking up, he said: I see men as it were trees, walking.\n"
	"After that again he imposed his hands upon his eyes, and he began to see, and was restored, so that he saw all things clearly.\n"
	"And he sent him into his house, saying: Go into thy house; and if thou enter into the town, tell nobody.\n"
	"And JESUS went forth and his Disciples into the towns of Caesarea-Philippi; and in the way he asked his Disciples, saying to them: Whom do men say that I am?\n"
	"Who answered him, saying: John the Baptist, some Elias, & other some as it were one of the Prophets.\n"
	"Then he saith to them: But whom do you say that I am? Peter answering said to him: Thou art Christ.\n"
	"And he threatened them that they should not tell any man of him.\n"
	"And he began to teach them, that the Son of man must suffer many things, and be rejected of the Ancients and of the high Priests & the Scribes, and be killed: and after three days rise again.\n"
	"And he spake the word openly. And Peter taking him, began to rebuke him.\n"
	"Who turning, and seeing his Disciples, threatened Peter, saying: Go behind me Satan, because thou savourest not the things that are of God, but that are of men.\n"
	"And calling the multitude together with his Disciples, he said to them: If any man will follow me, let him deny himself, and take up his cross, and follow me.\n"
	"For he that will save his life, shall lose it; and he that shall lose his life for me and the Gospel, shall save it.\n"
	"For what shall it profit a man, if he gain the whole world, & suffer damage of his soul?\n"
	"Or what permutation shall a man give for his soul?\n"
	"For he that shall be ashamed of me, and of my words in this adulterous and sinful generation, the Son of man also will be ashamed of him, when he shall come in the glory of his Father with the holy Angels.\n"
	"AND he said to them: Amen I say to you, that there be some of them that stand here, which shall not taste of death, until they see the Kingdom of God coming in power.";