const char* chap1115 = "AND when he went out of the Temple, one of his Disciples saith to him: Master, behold what manner of stones, and what kind of buildings.\n"
	"And JESUS answering, said to him: Seest thou all these great buildings? There shall not be left a stone upon a stone, that shall not be destroyed.\n"
	"And when he sat in Mount-olivet against the temple, Peter and James and John and Andrew asked him apart:\n"
	"Tell us, when shall these things be? and what shall be the sign when all these things shall begin to be consummate?\n"
	"And JESUS answering began to say to them, See, that no man seduce you.\n"
	"For many shall come in my name saying that I am he; and they shall seduce many.\n"
	"And when you shall hear of wars and bruits of wars, fear not. For these things must be, but the end is not yet.\n"
	"For nation shall rise against nation and kingdom against kingdom, and there shall be earth-quakes in places, & famines. These things are the beginning of sorrows.\n"
	"But look to yourselves. For they shall deliver you up in Councils, and in Synagogues shall you be beaten, and you shall stand before Presidents and kings for my sake, for a testimony unto them.\n"
	"And into all nations first the Gospel must be preached.\n"
	"And when they shall lead you and deliver you, be not careful beforehand what you shall speak; but that which shall be given you in that hour, that speak ye. For it is not you that speak, but the Holy Ghost.\n"
	"And brother shall deliver brother unto death, and the father his Son; and the children shall arise against the parents, and shall work their death.\n"
	"And you shall be odious to all men for my name. But he that shall endure unto the end, he shall be saved.\n"
	"And when you shall see the abomination of desolation, standing where it ought not (he that readeth, let him understand) then they that are in Jewry, let them flee unto the mountains:\n"
	"and he that is on the house-top, let him not go down into the house, nor enter in^ to take any thing out of his house:\n"
	"and he that shall be in the field, let him not return back to take his garment.\n"
	"And woe to them that are with-child and that give suck in those days.\n"
	"But pray that the things chance not in the winter.\n"
	"For those days shall be such tribulations as were not from the beginning of the creation that God created until now, neither shall be.\n"
	"And unless the Lord had shortened the days, no flesh should be saved: but for the elect which he hath elected, he hath shortened the days.\n"
	"And then if any man shall say unto you, Lo, here is Christ, lo, there: do not believe.\n"
	"For there shall rise up false-Christs and false-Prophets, and they shall shew signs and wonders, to seduce (if it be possible) the elect also.\n"
	"You therefore take heed; behold I have foretold you all things.\n"
	"But in those days after that tribulation the sun shall be darkened, and the moon shall not give her light,\n"
	"and the stars of Heaven shall be falling down, and the powers that are in Heaven, shall be moved.\n"
	"And then they shall see the Son of man coming in the clouds, with much power and glory.\n"
	"And then shall he send his Angels, and shall gather together his elect from the four winds, from the uttermost part of the earth to the uttermost part of Heaven.\n"
	"And of the figtree learn ye a parable. When now the bough thereof is tender, and the leaves come forth, you know that summer is very nigh.\n"
	"So you also when you shall see these things come to pass, know ye that it is very nigh, at the doors.\n"
	"Amen I say to you, that this generation shall not pass, until all these things be done.\n"
	"Heaven & earth shall pass, but my words shall not pass.\n"
	"But of that day or hour no man knoweth, neither the Angels in Heaven, nor the Son, but the Father.\n"
	"Take heed, watch, and pray. For you know not when the time is.\n"
	"Even as a man who being gone into a strange country, left his house; and gave his servants authority over each work, and commanded the porter to watch.\n"
	"Watch ye therefore (for you know not when the Lord of the house cometh: at even, or at midnight, or at the cock crowing, or in the morning)\n"
	"lest coming upon a sudden, he find you sleeping.\n"
	"And that which I say to you, I say to all, Watch.";