const char* chap1119 = "BECAUSE many have gone about to compile a narration of the things that have been accomplished among us;\n"
	"according as they have delivered unto us, who from the beginning themselves saw and were ministers of the word;\n"
	"it seemed good also unto me having diligently attained to all things from the beginning, to write to thee in order, good Theophilus,\n"
	"that thou mayst know the verity of those words whereof thou hast been instructed.\n"
	"There was in the days of Herod the king of Jewry, a certain Priest named Zacharie, of the course of Abia; & his wife of the daughters of Aaron, and her name Elizabeth.\n"
	"And they were both just before God, walking in all the commandments and justifications of our Lord without blame,\n"
	"and they had no son: for that Elizabeth was barren, and both were well striken in their days.\n"
	"And it came to pass, when he executed the priestly function in the order of his course before God,\n"
	"according to the custom of the Priestly function, he went forth by lot to offer incense, entering into the temple of our Lord;\n"
	"and all the multitude of the people was praying without at the hour of the incense.\n"
	"And there appeared to him an Angel of our Lord, standing on the right hand of the Altar of incense.\n"
	"And Zacharie was troubled, seeing him; and fear fell upon him.\n"
	"But the Angel said to him: Fear not Zacharie, for thy prayer is heard; and thy wife Elizabeth shall bear thee a son and thou shalt call his name John:\n"
	"and thou shalt have joy and exultation, and many shall rejoice in his nativity.\n"
	"For he shall be great before our Lord; and wine and sicer he shall not drink; and he shall be replenished with the Holy Ghost even from his mother's womb.\n"
	"And he shall convert many of the children of Israel to the Lord their God.\n"
	"And he shall go before him in the spirit and virtue of Elias, that he may convert the hearts of the fathers unto the children, and the incredulous to the wisdom of the just, to prepare unto the Lord a perfect people.\n"
	"And Zacharie said to the Angel: Whereby shall I know this? For I am old; and my wife is well striken in her days.\n"
	"And the Angel answering said to him: I am Gabriel that assist before God; and am sent to speak to thee, and to evangelize these things to thee.\n"
	"And behold, thou shalt be dumb, and shalt not be able to speak until the day wherein these things shall be done; for-because thou hast not believed my words, which shall be fulfilled in their time.\n"
	"And the people was expecting Zacharie; and they marveled that he made tarriance in the temple.\n"
	"And coming forth he could not speak to them, and they knew that he had seen a vision in the temple. And he made signs to them, and remained dumb.\n"
	"And it came to pass, after the days of his office were expired, he departed into his house.\n"
	"And after these days^ Elizabeth his wife conceived; and hid herself five months, saying:\n"
	"For thus hath our Lord done to me in the days wherein he had respect to take away my reproach among men.\n"
	"And in the sixth month, the Angel Gabriel was sent of God into a city of Galilee, called Nazareth,\n"
	"to a virgin despoused to a man whose name was Joseph, of the house of David; and the virgin's name was MARY.\n"
	"And the Angel being entered in, said unto her: HAIL full of grace, our Lord is with thee: blessed art thou among women.\n"
	"Who having heard, was troubled at his saying, and thought what manner of salutation this should be.\n"
	"And the Angel said to her: Fear not MARY, for thou hast found grace with God.\n"
	"Behold thou shalt conceive in thy womb, and shalt bear a Son; and thou shalt call his name JESUS.\n"
	"He shall be great, and shall be called the Son of the most High, and our Lord God shall give him the seat of David his father:\n"
	"and he shall reign in the house of Jacob for ever, and of his Kingdom there shall be no end.\n"
	"And MARY said to the Angel: How shall this be done, because I know not man?\n"
	"And the Angel answering, said to her: The Holy Ghost shall come upon thee, and the power of the most High shall overshadow thee. And therefore also that which of thee shall be born Holy, shall be called the Son of God.\n"
	"And behold Elizabeth thy cousin, she also hath conceived a Son in her old age; and this month, is the sixth to her that is called barren;\n"
	"because there shall not be impossible with God any word.\n"
	"And MARY said, BEHOLD the handmaid of our Lord, be it done to me according to thy word. And the Angel departed from her.\n"
	"And MARY rising up in those days, went unto the hill country with speed into a city of Juda.\n"
	"And she entered into the house of Zacharie, and saluted Elizabeth.\n"
	"And it came to pass; as Elizabeth heard the salutation of MARY, the infant did leap in her womb. And Elizabeth was replenished with the Holy Ghost:\n"
	"and she cried out with a loud voice, and said, BLESSED art thou among women, and blessed is the fruit of thy womb.\n"
	"And whence is this to me, that the mother of my Lord doth come to me?\n"
	"For behold as the voice of thy salutation sounded in mine ears, the infant in my womb did leap for joy.\n"
	"And Blessed is she that believed because those things shall be accomplished that were spoken to her by our Lord.\n"
	"And MARY said: MY SOUL doth magnify our Lord:\n"
	"And my spirit hath rejoiced in God my Saviour.\n"
	"Because he hath regarded the humility of his handmaid; for behold from hence forth all generations shall call me blessed.\n"
	"Because he that is mighty hath done great things to me: and holy is his name.\n"
	"And his mercy from generation unto generations, to them that fear him.\n"
	"He hath shewed might in his arm: he hath dispersed the proud in the conceit of their heart.\n"
	"He hath deposed the mighty from their seat, & hath exalted the humble.\n"
	"The hungry he hath filled with good things: and the rich he hath sent away empty.\n"
	"He hath received Israel his child, being mindful of his mercy,\n"
	"As he spake to our fathers, to Abraham and his seed for ever.\n"
	"And MARY tarried with her about three months: and she returned into her house.\n"
	"And Elizabeth's full time was come to be delivered; and she bare a son.\n"
	"And her neighbours and kinsfolk heard that our Lord did magnify his mercy with her, and they did congratulate her.\n"
	"And it came to pass; on the eighth day they came to circumcise the child, and they called him by his father's name Zacharie.\n"
	"And his mother answering, said: Not so, but he shall be called John.\n"
	"And they said to her, That there is none in thy kindred that is called by this name.\n"
	"And they made signs to his father, what he would have him called.\n"
	"And demanding a writing table, he wrote, saying: John is his name. And they all marveled.\n"
	"And forthwith his mouth was opened, and his tongue, and he spake^ blessing God.\n"
	"And fear came upon all their neighbours; and all these things were bruited over all the hill-country of Jewry:\n"
	"and all that had heard, laid them up in their heart, saying: What an one, trow ye, shall this child be? For the hand of our Lord was with him.\n"
	"And Zacharie his father was replenished with the Holy Ghost; and he prophesied, saying:\n"
	"BLESSED BE OUR LORD God of Israel: because he hath visited and wrought the redemption of his people:\n"
	"And hath erected the horn of salvation to us, in the house of David his servant.\n"
	"As he spake by the mouth of his holy Prophets, that are from the beginning:\n"
	"Salvation from our enemies, and from the hand of all that hate us:\n"
	"To work mercy with our fathers; and to remember his holy testament,\n"
	"The oath which he sware to Abraham our father,\n"
	"that he would give to us. That without fear being delivered from the hand of our enemies, we may serve him,\n"
	"In holiness and justice before him, all our days.\n"
	"And thou child, shalt be called the Prophet of the Highest: for thou shalt go before the face of our Lord to prepare his ways.\n"
	"To give knowledge of salvation to his people, unto remission of their sins,\n"
	"Through the bowels of the mercy of our God, in which the Orient, from on high, hath visited us.\n"
	"To illuminate them that sit in darkness, and in the shadow of death: to direct our feet into the way of peace.\n"
	"And the child grew, and was strengthened in spirit, and was in the deserts until the day of his manifestation to Israel.";