const char* chap112 = "Our Lord also spake to Moyses, saying:\n"
	"speak to Aaron and to his sons, that they beware of those that are the consecrated things of the children of Israel, and contaminate not the name of the things sanctified to me, which they offer. I^ the Lord.\n"
	"Say to them, and to their posterity: Every man of your stock, that approacheth to those things that are consecrated, & which the children of Israel have offered to the Lord, in whom there is uncleanness, shall perish before the Lord. I am the Lord.\n"
	"The man of the seed of Aaron that is a leper, or hath a flux of seed shall not eat of those things that are sanctified to me until he be healed. He that toucheth a thing unclean by occasion of that is dead, and he from whom issueth seed as it were of copulation,\n"
	"and he that toucheth a creeping beast, and whatsoever unclean thing the touching whereof is filthy,\n"
	"shall be unclean until even, and shall not eat those things that are sanctified: but when he hath washed his flesh with water,\n"
	"and the sun is down, then being cleansed he shall eat of the sanctified things, because it is his meat.\n"
	"Carrion and that which was taken of a beast, they shall not eat, nor be polluted in them. I am the Lord.\n"
	"Let them keep my precepts, that they be not subject to sin, and die in the Sanctuary, when they shall have polluted it. I^ the Lord that sanctify them.\n"
	"No stranger shall eat of the sanctified things, the Priest's guest and hireling shall not eat of them.\n"
	"But whom the Priest hath bought, and he that is his servant born in his house, these shall eat of them.\n"
	"If the daughter of a Priest be married to any of the people: of those things that are sanctified, and of the first fruits she shall not eat.\n"
	"But if she be a widow, or put away, and without children return to her father's house: as she was wont being a maid, she shall be fed with her father's meats. No stranger hath power to eat of them.\n"
	"He that eateth of the sanctified things by ignorance, shall add the fifth part with that which he did eat, and shall give it to the Priest into the Sanctuary.\n"
	"Neither shall they contaminate the sanctified things of the children of Israel, which they offer to the Lord:\n"
	"lest perhaps they sustain the iniquity of their offence, when they shall have eaten the sanctified things. I^ the Lord that sanctify them.\n"
	"And our Lord spake to Moyses, saying:\n"
	"Speak to Aaron, and to his sons, and to all the children of Israel, and thou shalt say to them: The man of the house of Israel, and of the strangers which dwell with you, that offereth his oblation, either paying his vows, or offering of his own accord, whatsoever that be which he presenteth for an holocaust of the Lord,\n"
	"to be offered by you, it shall be a male without spot, of beefs, & muttons, & of goats.\n"
	"If it have a blemish, you shall not offer it, neither shall it be acceptable.\n"
	"The man that offereth a victim of pacifics to the Lord, either paying his vows, or offering of his own accord, as well of beefs as of muttons, shall offer it without blemish, that it may be acceptable: there shall be no blemish in it.\n"
	"If it be blind, if it be broken, if it have a scar, if blisters, or a scab, or a dry scurf: you shall not offer them to the Lord, nor burn of them upon the Lord's altar.\n"
	"An ox and a sheep, having the ear and the tail cut off, thou mayst offer voluntarily, but a vow cannot be payed of them.\n"
	"No beast that hath the stones bruised, or crushed, or cut and taken away, shall you offer to the Lord, & in your land make not this at all.\n"
	"Of the hand of a stranger you shall not offer breads to your God, and what other thing soever he would give: because they are all corrupted & blemished: you shall not receive them.\n"
	"And our Lord spake to Moyses, saying:\n"
	"An ox, a sheep, and a goat, when they are brought forth, shall be seven days under the udder of their dam: but the eighth day and so forward they may be offered to the Lord.\n"
	"Whether it be a beef, or a sheep, they shall not be immolated in one day with their young ones.\n"
	"If you immolate an host for thanks-giving to the Lord, that he may be placable,\n"
	"the same day you shall eat it, there shall not ought remain until the morning of the next day. I^ the Lord.\n"
	"Keep my commandments, & do them. I^ the Lord.\n"
	"Pollute not my holy name that I may be sanctified in the midst of the children of Israel. I^ the Lord that sanctify you,\n"
	"and brought you out of the Land of Aegypt, that I might be your God. I^ the Lord.";