const char* chap1120 = "AND it came to pass, in those days there came forth an Edict from Caesar Augustus, that the whole world should be enrolled.\n"
	"This first enrolling was made by the President of Syria^ Cyrinus.\n"
	"And all went to be enrolled, every one into his own city.\n"
	"And Joseph also went up from Galilee out of the city of Nazareth into Jewry, to the city of David that is called Beth-lehem: for because he was of the house and family of David,\n"
	"to be enrolled with MARY his despoused wife that was with child.\n"
	"And it came to pass, when they were there, her days were fully come that she should be delivered.\n"
	"And she brought forth her first begotten son, and swaddled him in cloths, and laid him down in a manger; because there was not place for them in the inn.\n"
	"And there were in the same country shepherds watching, and keeping the night watches over their flock.\n"
	"And behold, an Angel of our Lord stood beside them, and the brightness of God did shine round about them, and they feared with a great fear.\n"
	"And the Angel said to them: Fear not; for behold I evangelize to you great joy, that shall be to all the people:\n"
	"because this day is born to you a SAVIOUR which is Christ our Lord, in the city of David.\n"
	"And this shall be a sign to you; You shall find the infant swaddled in cloths, and laid in a manger.\n"
	"And suddenly there was with the Angel a multitude of the heavenly army, praising God, and saying,\n"
	"Glory in the highest to God: and in earth peace to men of good will.\n"
	"And it came to pass, after the Angels departed from them into Heaven, the shepherds spake one to another: Let us go over to Bethlehem, and let us see this word that is done, which our Lord hath shewed to us.\n"
	"And they came with speed; and they found MARY and Joseph, and the infant laid in the manger.\n"
	"And seeing it, they understood of the word that had been spoken to them concerning this child.\n"
	"And all that heard, did marvel; and concerning those things that were reported to them by the shepherds.\n"
	"But MARY kept all these words, conferring them in her heart.\n"
	"And the shepherds returned, glorifying and praising God in all things that they had heard, and seen, as it was said to them.\n"
	"And after eight days were expired, that the child should be circumcised; his name was called JESUS, which was called by the Angel, before that he was conceived in the womb.\n"
	"And after the days were fully ended of her purification according to the law of Moyses, they carried him into Jerusalem, to present him to our Lord\n"
	"(as it is written in the law of our Lord, That every male opening the matrice, shall be called holy to the Lord.)\n"
	"and to give a sacrifice according as it is written in the law of our Lord, a pair of turtles, or two young pigeons.\n"
	"And behold there was a man in Jerusalem named Simeon, and this man was just and religious, expecting the consolation of Israel: and the Holy Ghost was in him.\n"
	"And he had received an answer of the Holy Ghost, that he should not see death unless he saw first the CHRIST of our Lord.\n"
	"And he came in Spirit into the temple. And when his parents brought in the child JESUS, to do according to the custom of the Law for him,\n"
	"he also took him into his arms, and blessed God, and said:\n"
	"NOW THOU doest dismiss thy servant O Lord, according to thy word in peace.\n"
	"Because mine eyes have seen thy SALVATION,\n"
	"Which thou hast prepared before the face of all peoples:\n"
	"A light to the revelation of the Gentiles, & the glory of thy people Israel.\n"
	"And his father and mother were marveling upon those things which were spoken concerning him.\n"
	"And Simeon blessed them, and said to MARY his mother: Behold this is set unto the ruin, and unto the resurrection of many in Israel, & for a sign which shall be contradicted,\n"
	"and thine own soul shall a sword pierce, that out of many hearts cogitations may be revealed.\n"
	"And there was Anne a prophetess, the daughter of Phanuel, of the tribe of Aser: she was far striken in days, and had lived with her husband seven years from her virginity.\n"
	"And she was a widow until eighty and four years; who departed not from the temple, by fastings and prayers serving night and day.\n"
	"And she at the same hour suddenly coming in, confessed to our Lord; and spake of him to all that expected the redemption of Israel.\n"
	"And after they had wholly done all things according to the law of our Lord, they returned into Galilee, into their city Nazareth.\n"
	"And the child grew, and waxed strong: full of wisdom, and the grace of God was in him.\n"
	"And his parents went every year unto Jerusalem, at the solemn day of Pasch.\n"
	"And when he was twelve years old, they going up into Jerusalem according to the custom of the festival day;\n"
	"and having ended the days, when they returned, the child JESUS remained in Jerusalem: and his parents knew it not.\n"
	"And thinking that he was in the company, they came a day's journey, and sought him among their kinsfolk and acquaintance.\n"
	"And not finding him, they returned into Jerusalem, seeking him.\n"
	"And it came to pass, after three days they found him in the temple sitting in the midst of the Doctors, hearing them and asking them.\n"
	"And all were astonished that heard him, upon his wisdom & answers.\n"
	"And seeing him, they wondered. And his mother said to him: Son, why hast thou so done to us? Behold thy father and I sorrowing did seek thee.\n"
	"And he said to them: What is it that you sought me? Did you not know, that I must be about those things which are my Father's?\n"
	"And they understood not the word that he spake unto them.\n"
	"And he went down with them, and came to Nazareth; and was subject to them. And his mother kept all these words in her heart.\n"
	"And JESUS proceeded in wisdom and age, and grace with God and men.";