const char* chap1122 = "AND JESUS full of the Holy Ghost, returned from Jordan, & was driven in the spirit into the desert.\n"
	"forty days, and was tempted of the devil. And he did eat nothing in those days; and when they were ended, he was an hungered.\n"
	"And the devil said to him: If thou be the Son of God, say to this stone that it be made bread.\n"
	"And JESUS made answer unto him: It is written, That not in bread alone shall man live, but in every word of God.\n"
	"And the devil brought him into an high mountain, and shewed him all the kingdoms of the whole world in a moment of time;\n"
	"and he said to him: To thee will I give this whole power, and the glory of them; for to me they are delivered, and to whom I will, I do give them.\n"
	"Thou therefore if thou wilt adore before me, they shall all be thine.\n"
	"And JESUS answering said to him: It is written, Thou shalt adore the Lord thy God & him only shalt thou serve.\n"
	"And he brought him into Jerusalem, & set him upon the pinnacle of the Temple; and he said to him: If thou be the Son of God, cast thyself from hence downward.\n"
	"For it is written, that He hath given his Angels charge of thee, that they preserve thee:\n"
	"and that in their hands they shall bear thee up, lest perhaps thou knock thy foot against a stone.\n"
	"And JESUS answering said to him: It is said, Thou shalt not tempt the Lord thy God.\n"
	"And all the tentation being ended, the devil departed from him until a time.\n"
	"And JESUS returned in the force of the spirit into Galilee, and the same went forth through the whole country of him.\n"
	"And he taught in their Synagogues, and was magnified of all.\n"
	"And he came to Nazareth where he was brought up: and he entered according to his custom on the Sabboth day into the Synagogue; and he rose up to read.\n"
	"And the book of Esay the Prophet was delivered unto him. And as he unfolded the book, he found the place where it was written:\n"
	"The Spirit of the Lord upon me, for which he anointed me, to evangelize unto the poor he sent me, to heal the contrite of heart,\n"
	"to preach to the captives remission, and sight to the blind, to dismiss the bruised unto remission, to preach the acceptable year of the Lord, and the day of retribution.\n"
	"And when he had folded the book, he rendered it to the minister, and sat down. And the eyes of all in the Synagogue were bent upon him.\n"
	"And he began to say unto them: That this day is fulfilled this scripture in your ears.\n"
	"And all gave testimony to him; and they marveled in the words of grace that proceeded from his mouth, and they said: Is not this Joseph's son?\n"
	"And he said to them: Certes you will say to me this similitude, Physician, cure thyself: as great things as we have heard done in Capharnaum, do also here in thy country.\n"
	"And he said: Amen I say to you, that no Prophet is accepted in his own country.\n"
	"In truth I say to you, there were many widows in the days of Elias in Israel, when the Heaven was shut three years and six months, when there was a great famine made in the whole earth:\n"
	"And to none of them was Elias sent, but into Sarepta of Sidon, to a widow woman.\n"
	"And there were many lepers in Israel under Elisaeus the Prophet; and none of them was made clean but Naaman the Syrian.\n"
	"And all in the Synagogue were filled with anger, hearing these things.\n"
	"And they rose, and cast him out of the city: and they brought him to the edge of the hill, where upon their city was built, that they might throw him down headlong.\n"
	"But he passing through the midst of them, went his way.\n"
	"And he went down into Capharnaum a city of Galilee; and there he taught them on the Sabboths.\n"
	"And they were astonished at his doctrine; because his talk was in power.\n"
	"And in the Synagogue there was a man having an unclean devil, and he cried out with a loud voice.\n"
	"Saying: Let be, what to us and thee JESUS of Nazareth? Art thou come to destroy us? I know thee who thou art, the SAINT of God.\n"
	"And JESUS rebuked him, saying: Hold thy peace, & go out of him. And when the devil had thrown him into the midst, he went out of him, and hurted him nothing.\n"
	"And there came fear upon all, and they talked together one with another, saying: What word is this, that in power and virtue he commandeth the unclean spirits, and they go out?\n"
	"And the same of him was published into every place of the country.\n"
	"And JESUS rising up out of the Synagogue, entered into Simon's house. And Simon's wife's mother was holden with a great fever; and they besought him for her.\n"
	"And standing over her, he commanded the fever, and it left her. And incontinent rising, she ministered to them.\n"
	"And when the sun was down, all that had diseased of sundry maladies, brought them to him. But he imposing hands upon every one, cured them.\n"
	"And devils went out from many, crying and saying: That thou art the Son of God. And rebuking them he suffered them not to speak, that they knew he was Christ.\n"
	"And when it was day, going forth he went into a desert place; & the multitudes sought him, and came even unto him; and they held him that he should not depart from them.\n"
	"To whom he said: That to other cities also must I evangelize the Kingdom of God; because therefore I was sent.\n"
	"And he was preaching in the Synagogues of Galilee.";