const char* chap1124 = "AND it came to pass on the Sabboth second-first, when he passed through the corn, his Disciples did pluck the ears, & did eat rubbing them with their hands.\n"
	"And certain of the Pharisees said to them: Why do you that which is not lawful on the Sabboths?\n"
	"And JESUS answering them, said: Neither this have you read which David did, when himself was an hungered & they that were with him:\n"
	"how he entered into the house of God, and took the loaves of Proposition, and did eat, and gave to them that were with him, which it is not lawful to eat but only for Priests?\n"
	"And he said to them: That the Son of man is Lord of the Sabboth also.\n"
	"And it came to pass on another Sabboth also, that he entered into the Synagogue, and taught. And there was a man, and his right hand was withered.\n"
	"And the Scribes and Pharisees watched if he would cure on the Sabboth; that they might find how to accuse him.\n"
	"But he knew their cogitations; and he said to the man that had the withered hand: Arise, and stand forth into the midst. And rising he stood.\n"
	"And JESUS said to them: I ask you, if it be lawful on the Sabboths to do well or ill; to save a soul or to destroy?\n"
	"And looking about upon them all, he said to the man: Stretch forth thy hand. And he stretched it forth; & his hand was restored.\n"
	"And they were replenished with madness; & they communed one with another what they might do to JESUS.\n"
	"And it came to pass in those days, he went forth into the mountain to pray, and he passed the whole night in the prayer of God.\n"
	"And when day was come, he called his Disciples; and he chose twelve of them (whom also he named Apostles)\n"
	"Simon whom he surnamed Peter, and Andrew his brother, James and John, Philippe and Bartholomew,\n"
	"Matthew and Thomas, James of Alphaeus and Simon that is called Zelotes,\n"
	"and Jude of James, and Judas Iscariote which was the traitor.\n"
	"And descending with them he stood in a plain place, and the multitude of his Disciples, and a very great company of people from all Jewry and Jerusalem, and the sea coast both of Tyre & Sidon,\n"
	"Which were come to hear him, and to be healed of their maladies. And they that were vexed of unclean spirits, were cured.\n"
	"And all the multitude sought to touch him, because virtue went forth from him, and healed all.\n"
	"And he lifting up his eyes upon his Disciples, said: Blessed are ye poor: for yours is the Kingdom of God.\n"
	"Blessed are you that now are an hungered: because you shall be filled. Blessed are you that now do weep: because you shall laugh.\n"
	"Blessed shall you be when men shall hate you, and when they shall separate you, and upbraid you, and abandon your name as evil, for the Son of man's sake.\n"
	"Be glad in that day and rejoice: for behold, your reward is much in Heaven. For according to these things did their fathers to the Prophets.\n"
	"But woe to you that are rich: because you have your consolation.\n"
	"Woe to you that are filled: because you shall be hungry. Woe to you that now do laugh: because you shall mourn and weep.\n"
	"Woe, when all man shall bless you: For according to these things did their fathers to the false-Prophets.\n"
	"But to you I say that do hear: Love your enemies, do good to them that hate you.\n"
	"Bless them that curse you, and pray for them that calumniate you.\n"
	"And he that striketh thee on the cheek, offer also the other. And from him that taketh away from thee thy robe, prohibit not thy coat also.\n"
	"And to every one that asketh thee, give, and of him that taketh away the things that are thine, ask not again.\n"
	"And according as you will that men do to you, do you also to them in like manner.\n"
	"And if you love them that love you, what thank is to you? For sinners also love those that love them.\n"
	"And if ye do good to them that do you good: what thank is to you? For sinners also do this.\n"
	"And if ye lend to them of whom ye hope to receive; what thank is to you? For sinners also lend unto sinners, for to receive as much.\n"
	"But love ye your enemies; do good and lend, hoping for nothing thereby: and your reward shall be much, and you shall be the Sons of the Highest, because himself is beneficial upon the unkind and the evil.\n"
	"Be ye therefore merciful as also your Father is merciful.\n"
	"Judge not, & you shall not be judged. Condemn not, & you shall not be condemned. Forgive, and you shall be forgiven.\n"
	"Give, and there shall be given to you. Good measure & pressed down and shaken together and running over shall they give into your bosom. For with the same measure that you do mete, it shall be measured to you again.\n"
	"And he said to them a similitude also: Can the blind lead the blind? Do not both fall into the ditch?\n"
	"The Disciple is not above his Master: but every one shall be perfect, if he be as his Master.\n"
	"And why seest thou the mote in thy brother's eye: but the beam that is in thine own eye thou considerest not?\n"
	"Or how canst thou say to thy brother: Brother, let me cast out the mote out of thine eye: thyself not seeing the beam in thine own eye? Hypocrite, cast first the beam out of thine own eye; and then shalt thou see clearly to take forth the mote out of thy brother's eye.\n"
	"For there is no good tree that yieldeth evil fruits; nor evil tree, that yieldeth good fruit.\n"
	"For every tree is known by his fruit. For neither do they gather figs of thorns; neither of a bush do they gather the grape.\n"
	"The good man^ of the good treasure of his heart bringeth forth good; and the evil man of the ill treasure bringeth forth evil. For of the aboundance of the heart the mouth speaketh,\n"
	"And why call you me, Lord, Lord: and do not the things which I say?\n"
	"Every one that cometh to me, and heareth my words, and doeth them, I will shew you to whom he is like.\n"
	"He is like to a man building a house, that digged deep, and laid the foundation upon a rock. And when an inundation rose, the river beat against that house, and it could not move it; for it was founded upon a rock.\n"
	"But he that heareth, and doeth not; is like to a man building his house upon the earth without a foundation: against the which the river did beat; and incontinent it fell, and the ruin of that house was great.";