const char* chap1128 = "AND after this our Lord designed also other seventy two: and he sent them two and two before his face into every city and place whither himself would come.\n"
	"And he said to them: The harvest truly is much; but the workmen few. Desire therefore the Lord of the harvest, that he send workmen into his harvest.\n"
	"Go: Behold I send you as lambs among wolves.\n"
	"Carry not purse nor scrip, nor shoes; and salute no body by the way.\n"
	"Into whatsoever house you enter, first say: Peace to this house.\n"
	"And if the son of peace be there, your peace shall rest upon him: but if not, it shall return to you.\n"
	"And in the same house tarry you, eating and drinking such things as they have. For the workman is worthy of his hire. Remove not from house to house.\n"
	"And into what city soever you enter, and they receive you, eat such things as are set before you;\n"
	"and cure the sick that are in it, and say to them: The Kingdom of God is come nigh upon you.\n"
	"And into whatsoever city you enter, and they receive you not, going forth into the streets thereof, say:\n"
	"The dust also of your city that cleaveth to us, we do wipe off against you. Yet this know ye that the Kingdom of God is at hand.\n"
	"I say to you, it shall be more tolerable for Sodom in that day, than for that city.\n"
	"Woe to thee Corozaim, woe to thee Beth-saida: for if in Tyre and Sidon had been wrought the miracles that have been wrought in you, they had done penance sitting in sack cloth and ashes long ago.\n"
	"But it shall be more tolerable for Tyre and Sidon in the judgement, than for you.\n"
	"And thou Capharnaum that art exalted unto Heaven: thou shalt be thrust down even unto hell.\n"
	"He that heareth you, heareth me; and he that despiseth you, despiseth me. And he that despiseth me, despiseth him that sent me.\n"
	"And the Seventy-two returned with joy, saying: Lord, the devils also are subject to us in thy name.\n"
	"And he said to them: I saw Satan as a lightning fall from Heaven.\n"
	"Behold, I have given you power to tread upon serpents, and scorpions, and upon all the power of the enemy, and nothing shall hurt you.\n"
	"But yet rejoice not in this, that the spirits are subject unto you; but rejoice in this, that your names are written in Heaven.\n"
	"In that very hour he rejoiced in spirit, and said: I confess to thee O Father, Lord of Heaven and earth, because thou hast hid these things from the wise and prudent, and hast revealed them to little ones. Yea Father, for so hath it well pleased thee.\n"
	"All things are delivered to me of my Father. And no man knoweth who the Son is, but the Father; and who the Father is, but the Son, and to whom the Son will reveal.\n"
	"And turning to his Disciples, he said: Blessed are the eyes that see the things that you see.\n"
	"For I say to you, that many Prophets and kings desired to see the things that you see, and saw them not; and to hear the things that you hear, and heard them not.\n"
	"And behold a certain lawyer stood up, tempting him and saying: Master, by doing of what thing shall I possess life everlasting?\n"
	"But he said to him: In the law what is written? How readest thou?\n"
	"He answering said: Thou shalt love the Lord thy God with thy whole heart, and with thy whole soul, and with all thy strength, and with all thy mind: and thy neighbour as thyself.\n"
	"And he said to him: Thou hast answered right, this do and thou shalt live.\n"
	"But he desirous to justify himself, said to JESUS: And who is my neighbour?\n"
	"And JESUS taking it, said: A certain man went down from Jerusalem into Jericho, and fell among thieves, who also spoiled him, and giving him wounds went away leaving him half-dead.\n"
	"And it chanced that a certain Priest went down the same way; and seeing him, passed by.\n"
	"In like manner also a Levite, when he was near the place, and saw him, passed by.\n"
	"But a certain Samaritane going his journey, came near him; and seeing him, was moved with mercy.\n"
	"And going unto him, bound his wounds, pouring in oil and wine: and setting him upon his own beast, brought him into an inn, and took care of him.\n"
	"And the next day he took forth two pence, and gave to the host, and said: Have care of him; and whatsoever thou shalt supererogate, I at my return will repay thee.\n"
	"Which of these three in thy opinion was neighbour to him that fell among thieves?\n"
	"But he said: He that did mercy upon him. And JESUS said to him: Go, and do thou in like manner.\n"
	"And it came to pass as they went, and he entered into a certain town; and a certain woman named Martha, received him into her house,\n"
	"and she had a sister called Mary. Who sitting also at our Lord's feet, heard his word.\n"
	"But Martha was busy about much service. Who stood and said: Lord, hast thou no care that my sister hath left me alone to serve? Speak to her therefore, that she help me.\n"
	"And our Lord answering said to her: Martha, Martha, thou art careful, and art troubled about many things.\n"
	"But one thing is necessary, Mary hath chosen the best part which shall not be taken away from her.";