const char* chap1129 = "AND it came to pass, when he was in a certain place praying, as he ceased, one of his Disciples said to him: Lord teach us to pray, as John also taught his Disciples.\n"
	"And he said to them: When you pray, say, FATHER, sanctified be thy name. Thy Kingdom come,\n"
	"Our daily bread give us this day,\n"
	"and forgive us our sins, for because ourselves also do forgive every one that is in debt to us. And lead us not into temptation.\n"
	"And he said to them: Which of you shall have a friend, and shall go to him at midnight, and shall say to him, Friend, lend me three loaves,\n"
	"because a friend of mine is come out of his way to me, and I have not what to set before him:\n"
	"and he from within answering saith: Trouble me not, now the door is shut, and my children are with me in bed; I cannot rise and give thee.\n"
	"And if he shall persevere knocking, I say to you, although he will not rise and give him because he is his friend, yet for his importunity he will rise, and give him as many as he needeth.\n"
	"And I say to you, Ask, and it shall be given you: seek, and you shall find: knock, and it shall be opened to you.\n"
	"For every one that asketh, receiveth: and he that seeketh, findeth: and to him that knocketh, it shall be opened.\n"
	"And which of you if he ask his father bread, will he give him a stone? Or a fish, will he for a fish give him a serpent?\n"
	"Or if he ask an egg, will he reach him a scorpion?\n"
	"If you then being naught, know how to give good gifts to your children, how much more will your Father from Heaven give the good spirit to them that ask him?\n"
	"And he was casting out a devil, and that was dumb. And when he had cast out the devil, the dumb spake: and the multitudes marveled.\n"
	"And certain of them said: In Beel-zebub the prince of devils he casteth out devils.\n"
	"And other tempting, asked of him a sign from Heaven.\n"
	"But he seeing their cogitations, said to them: Every kingdom divided against itself, shall be made desolate, and house upon house, shall fall.\n"
	"And if Satan also be divided against himself, how shall his kingdom stand? Because you say that in Beel-zebub I do cast out devils.\n"
	"And if I in Beel-zebub cast out devils: your children, in whom do they cast out? Therefore they shall be your judges.\n"
	"But if I in the finger of God do cast out devils; surely the Kingdom of God is come upon you.\n"
	"When the strong armed keepeth his court, those things are in peace that he possesseth.\n"
	"But if a stronger than he come upon him and overcome him; he will take away his whole armour wherein he trusted, and will distribute his spoils.\n"
	"He that is not with me, is against me: and he that gathereth not with me, scattereth.\n"
	"When the unclean spirit shall depart out of a man, he wandereth through places without water, seeking rest. And not finding, he saith, I will return into my house whence I departed.\n"
	"And when he is come, he findeth it swept with a besom, and trimmed.\n"
	"Then he goeth and taketh seven other spirits worse than himself, and entering in they dwell there. And the last of that man be made worse than the first.\n"
	"And it came to pass, when he said these things, a certain woman lifting up her voice out of the multitude said to him: Blessed is the womb that bare thee, and the paps that thou didst suck.\n"
	"But he said: Yea rather, blessed are they that hear the word of God, and keep it.\n"
	"And the multitudes running together, he began to say: This generation, is a wicked generation: it asketh a sign, and a sign shall not be given it but the sign of Jonas the Prophet.\n"
	"For as Jonas was a sign to the Ninivites; so shall the Son of man also be to this generation.\n"
	"The queen of the South shall rise in the judgement with the men of this generation, and shall condemn them: because she came from the ends of the earth to hear the wisdom of Salomon. And behold, more than Salomon here.\n"
	"The men of Ninivee shall rise in the judgement with this generation, and shall condemn it, because they did penance at the preaching of Jonas. And behold, more than Jonas here.\n"
	"No man lighteth a candle, and putteth it in secret, neither under a bushel: but upon a candlestick, that they that go in may see the light.\n"
	"The candle of thy body is thine eye. If thine eye be simple, thy whole body shall be lightsome: but if it be naught, thy body also shall be darksome.\n"
	"See therefore that the light which is in thee, be not darkness.\n"
	"If then thy whole body be lightsome, having no part of darkness: it shall be lightsome wholly, and as a bright candle it shall lighten thee.\n"
	"And when he was speaking, a certain Pharisee desired him that he would dine with him. And he going in sat down to eat.\n"
	"And the Pharisee began to think within himself and to say: Why he was not washed before dinner.\n"
	"And our Lord said to him: Now you Pharisees do make clean^ that on the out side of the cup and of the platter; but that of yours which is within, is full of rapine and iniquity.\n"
	"Fools, did not he that made that on the out side, make that also that is on the inside?\n"
	"But yet that^ that remaineth, give alms, & behold all things are clean unto you.\n"
	"But woe to you Pharisees, because you tithe mint and rew and every herb: and pass over judgement and the charity of God. But these things you ought to have done, and not to omit those.\n"
	"Woe to you Pharisees, because you love the first chairs in the Synagogues, and salutations in the market place.\n"
	"Woe to you, because you are as monuments that appear not, and men walking over, are not ware.\n"
	"And one of the Lawyers answering saith to him: Master, in saying these things, thou speakest to our reproach also.\n"
	"But he said: Woe to you Lawyers also: because you load men with burdens which they cannot bear, and yourselves touch not the packs with one of your fingers.\n"
	"Woe to you that build the monuments of the Prophets: and your fathers did kill them.\n"
	"Surely you do testify that you consent to the works of your fathers: because they indeed did kill them, and you build their sepulchres.\n"
	"For this cause the wisdom also of God said, I will send to them Prophets and Apostles, and of them they will kill and persecute.\n"
	"That the blood of all the Prophets that was shed from the making of the world, may be required of this generation,\n"
	"from the blood of Abel unto the blood of Zacharie that was slain between the altar and the temple. Yea I say to you, it shall be required of this generation.\n"
	"Woe to you Lawyers, because you have taken away the key of knowledge: yourselves have not entered, & those that did enter you have prohibited.\n"
	"And when he said these things to them, the Pharisees & the Lawyers began vehemently to urge him, & to stop his mouth about many things,\n"
	"lying in wait for him, and seeking to catch something of his mouth, that they might accuse him.";