const char* chap1133 = "AND there approached Publicans and sinners unto him for to hear him.\n"
	"And the Pharisees and the Scribes murmured saying: That this man receiveth sinners, and eateth with them.\n"
	"And he spake to them this parable, saying:\n"
	"What man of you having an hundred sheep: and if he hath lost one of them, doth he not leave the ninety nine in the desert, and goeth after that which was lost until he find it?\n"
	"And when he hath found it, layeth it upon his shoulders rejoicing:\n"
	"and coming home calleth together his friends and neighbours, saying to them: Rejoice with me, because I have found my sheep that was lost?\n"
	"I say to you, that even so there shall be joy in Heaven upon one sinner that doth penance, than upon ninety nine just that need not penance.\n"
	"Or what woman having ten groats: if she leese one groat, doth she not light a candle, and sweep the house, and seek diligently, until she find?\n"
	"And when she hath found, calleth together her friends and neighbours, saying: Rejoice with me, because I have found the groat which I had lost?\n"
	"So I say to you, there shall be joy before the Angels of God upon one sinner that doth penance.\n"
	"And he said: A certain man had two sons;\n"
	"and the younger of them said to his father: Father, give me the portion of substance that belongeth to me. And he divided unto them the substance.\n"
	"And not many days after^ the younger son gathering all his things together went from home into a far country: and there he wasted his substance, living riotously.\n"
	"And after he had spent all, there fell a sore famine in that country, and he began to be in need.\n"
	"And he went, and cleaved to one of the citizens of that country. And he sent him into his farm to feed swine.\n"
	"And he would fain have filled his belly of the husks that the swine did eat; and no body gave unto him.\n"
	"And returning to himself he said: How many of my father's hirelings have aboundance of bread, and I here perish for famine?\n"
	"I will arise, and will go to my father, and say to him: Father, I have sinned against Heaven and before thee:\n"
	"I am not now worthy to be called thy son: make me as one of thy hirelings.\n"
	"And rising up he came to his father. And when he was yet far off, his father saw him, and was moved with mercy, and running to him fell upon his neck, and kissed him.\n"
	"And his son said to him: Father, I have sinned against Heaven & before thee, I am not now worthy to be called thy son.\n"
	"And the father said to his servants: Quickly bring forth the first stole, and do it on him, and put a ring upon his hand, and shoes upon his feet:\n"
	"and bring the fatted calf, and kill it, and let us eat, and make merry:\n"
	"because this my son was dead, and is revived: was lost, and is found. And they began to make merry.\n"
	"But his elder son was in the field, and when he came and drew nigh to the house, he heard music and dancing:\n"
	"and he called one of the servants, and asked what these things should be.\n"
	"And he said to him: Thy brother is come, and thy father hath killed the fatted calf, because he hath received him safe.\n"
	"But he had indignation, and would not go in. His father therefore going forth began to desire him.\n"
	"But he answering said to his father: Behold, so many years do I serve thee, and I never transgressed thy commandment, and thou didst never give me a kid to make merry with my friends:\n"
	"but after that this thy son, that hath devoured his substance with whores, is come, thou hast killed for him the fatted calf.\n"
	"But he said to him: Son, thou art always with me, and all my things are thine.\n"
	"But it behoved us to make merry and be glad because this thy brother was dead, and is revived, was lost, and is found.";