const char* chap1135 = "And he said to his Disciples: It is impossible that scandals should not come: but woe to him by whom they come.\n"
	"It is more profitable for him, if a mill-stone be put about his neck, and he be cast into the sea, than that he scandalize one of these little ones.\n"
	"Look well to yourselves. If thy brother sin against thee, rebuke him: and if he do penance, forgive him.\n"
	"And if he sin against thee seven times in a day, and seven times in a day be converted unto thee, saying, It repenteth me, forgive him.\n"
	"And the Apostles said to our Lord: Increase faith in us.\n"
	"And our Lord said: If you had faith like to a mustard-seed, you might say to this mulberry tree, be thou rooted up, and be transplanted into the sea: and it would obey you.\n"
	"And which of you having a servant plowing or keeping cattle, that will say to him returning out of the field: Pass quickly, sit down:\n"
	"and saith not to him: Make ready supper, and gird thyself, and serve me whiles I eat and drink, and afterward thou shalt eat and drink?\n"
	"Doth he give that servant thanks, for doing the things which he commanded him?\n"
	"I trow not: So you also, when you shall have done all things that are commanded you, say: We are unprofitable servants; we have done that which we ought to do.\n"
	"And it came to pass, as he went unto Jerusalem, he passed through the midst of Samaria and Galilee.\n"
	"And when he entered into a certain town, there met him ten men that were lepers, who stood a far off;\n"
	"and they lifted up their voice, saying: JESUS Master, have mercy on us.\n"
	"Whom as he saw, he said: Go, shew yourselves to the Priests. And it came to pass, as they went, they were made clean.\n"
	"And one of them as he saw that he was made clean, went back with a loud voice magnifying God,\n"
	"and he fell on his face before his feet, giving thanks: and this was a Samaritane.\n"
	"And JESUS answering said: Were not ten made clean? and where are the nine?\n"
	"There was not found that returned, and gave glory to God, but this stranger.\n"
	"And he said to him: Arise, go thy ways; because thy faith hath made thee safe.\n"
	"And being asked of the Pharisees: when cometh the Kingdom of God? he answered them and said: The Kingdom of God cometh not with observation:\n"
	"neither shall they say: Lo here, or lo there. For lo the Kingdom of God is within you.\n"
	"And he said to his Disciples: The days will come when you shall desire to see one day of the Son of man; and you shall not see.\n"
	"And they will say to you: Lo here and lo there. Go not, neither do ye follow after.\n"
	"For even as the lightning that lighteneth from under Heaven, unto those parts that are under Heaven, shineth: so shall the Son of man be in his day.\n"
	"But first he must suffer many things and be rejected of this generation.\n"
	"And as it came to pass in the days of Noe, so shall it be also in the days of the Son of man.\n"
	"They did eat and drink, they did marry wives and were given to marriage even until the day that Noe entered into the ark: and the flood came, and destroyed them all.\n"
	"Likewise as it came to pass in the days of Lot: They did eat and drink, bought and sold, planted, and builded:\n"
	"and in the day that Lot went out from Sodom, it rained fire & brimstone from Heaven, & destroyed them all:\n"
	"according to these things it shall be in the day that the Son of man shall be revealed.\n"
	"In that hour he that shall be in the house-top, and his vessel in the house, let him not go down to take them up: & he that is in the field, in like manner let him not return back.\n"
	"Be mindful of Lot's wife.\n"
	"Whosoever seeketh to save his life, shall lose it: and Whosoever doth lose the same, shall quicken it.\n"
	"I say to you, in that night there shall be two in one bed: the one shall be taken, and the other shall be left:\n"
	"two women shall be grinding together: the one shall be taken, and the other shall be left. two in the field: the one shall be taken, and the other shall be left.\n"
	"They answering say to him: Where Lord?\n"
	"Who said to them: Wheresoever the body shall be, thither will the eagles also be gathered together.";