const char* chap1139 = "AND beholding, he saw them that did cast their gifts into the treasury, rich persons.\n"
	"And he saw also a certain poor widow casting two brass mites.\n"
	"And he said: Verily I say to you, that this poor widow hath cast more than all.\n"
	"For all these of their aboundance have cast into the gifts of God: but she of her penury, hath cast in all her living that she had.\n"
	"And certain^ saying of the temple that it was adorned with goodly stones and donaries, he said:\n"
	"These things which you see, the days will come wherein there shall not be left a stone upon a stone that shall not be destroyed.\n"
	"And they asked him, saying: Master, when shall these things be: and what shall be the sign when they shall begin to come to pass?\n"
	"Who said: See you be not seduced. For many will come in my name, saying that I am he: and the time is at hand, go not therefore after them.\n"
	"And when you shall hear of wars and seditions, be not terrified: these things must first come to pass, but the end is not yet by and by.\n"
	"Then he said to them: Nation shall rise against nation, and kingdom against kingdom.\n"
	"And there shall be great earth-quakes in places, and pestilences and famines, and terrors from Heaven, and there shall be great signs.\n"
	"But before all these things they will lay their hands upon you: and persecute you delivering you into Synagogues and prisons, drawing you to kings and Presidents for my name.\n"
	"and it shall happen unto you for testimony.\n"
	"Lay up this therefore in your hearts, not to premeditate how you shall answer.\n"
	"For I will give you mouth and wisdom, which all your adversaries shall not be able to resist and gainsay.\n"
	"And you shall be delivered up of your parents and brethren, and kinsmen and friends: and they will put to death of you.\n"
	"And you shall be odious to all men for my name:\n"
	"and a hair of your head shall not perish.\n"
	"In your patience you shall possess your souls.\n"
	"And when you shall see Jerusalem compassed about with an army, then know that the desolation thereof is at hand.\n"
	"then they that are in Jewry, let them flee to the mountains: and they in the midst thereof, let them depart: and they in the countries, let them not enter into it.\n"
	"For these are the days of vengeance, that all things may be fulfilled that are written.\n"
	"But woe to them that are with child & that give suck in those days. For there shall be great affliction upon the land, and wrath on this people.\n"
	"And they shall fall by the edge of the sword; and shall be led captive into all nations: and Jerusalem shall be trodden of the Gentiles, till the times of nations be fulfilled.\n"
	"And there shall be signs in the sun and the moon and the stars: and upon earth distress of nations, for the confusion of the sound of sea and waves,\n"
	"men withering for fear and expectation, what shall come upon the whole world. For the powers of Heaven shall be moved:\n"
	"and then they shall see the Son of man coming in a cloud with great power and majesty.\n"
	"But when these things begin to come to pass, look up and lift up your heads: because your redemption is at hand.\n"
	"And he spake to them a similitude. See the figtree and all trees:\n"
	"when they now bud forth fruit out of themselves, you know that summer is nigh.\n"
	"So you also when you shall see these things come to pass, know that the Kingdom of God is nigh.\n"
	"Amen I say to you, that this generation shall not pass, till all be done.\n"
	"Heaven and earth shall pass; but my words shall not pass.\n"
	"And look well to yourselves, lest perhaps your hearts be overcharged with surfeiting and drunkenness and cares of this life: and that day come upon you suddenly.\n"
	"For as a snare shall it come upon all that sit upon the face of all the earth.\n"
	"Watch therefore, praying at all times, that you may be accounted worthy to escape all these things that are to come, and to stand before the Son of man.\n"
	"And the days he was teaching in the temple: but the nights^ going forth, he abode in the mount that is called Olivet.\n"
	"And all the people in the morning went unto him in the temple to hear him.";