const char* chap114 = "And our Lord spake to Moyses, saying:\n"
	"Command the children of Israel, that they bring unto thee oil of olives most pure, and clear, to furnish the lamps continually,\n"
	"without the veil of the testimony in the tabernacle of covenant. And Aaron shall set them from even until morning before the Lord, by a perpetual service and rite in your generations.\n"
	"Upon the candle stick most clean shall they be put always in the sight of the Lord.\n"
	"Thou shalt take also flour, & shalt bake thereof twelve breads, which shall have every one two tenths:\n"
	"which thou shalt set six one against another upon the most clean table before the Lord,\n"
	"and thou shalt put upon them the clearest frankincense, that the bread may be for a monument of the oblation of the Lord.\n"
	"Every sabbath they shall be changed before the Lord, received of the children of Israel by an everlasting covenant:\n"
	"and they shall be Aaron's and his sons', that they may eat them in a holy place: because it is most Holy of the sacrifices of the Lord by a perpetual right.\n"
	"And behold there went forth the son of a woman of Israel, whom she had born of an Aegyptian among the children of Israel, and fell at words in the camp with a man of Israel.\n"
	"And when he had blasphemed the name, and had cursed it, he was brought to Moyses: (And his mother was called Salumith, the daughter of Dabri of the tribe of Dan.)\n"
	"And they did cast him into prison, till they might know what our Lord would command.\n"
	"Who spake to Moyses,\n"
	"saying: Bring forth the blasphemer without the camp, and let all that heard him put their hands upon his head, and let all the people stone him.\n"
	"And to the children of Israel thou shalt speak: The man that curseth his God shall bear his sin:\n"
	"and he that blasphemeth the name of the Lord, dying let him die: all the multitude of the people shall stone him, whether he be a natural, or stranger. He that blasphemeth the name of the Lord, dying let him die.\n"
	"He that striketh, and killeth a man, dying let him die.\n"
	"He that striketh a beast, shall render one for it, that is to say, soul for soul.\n"
	"He that giveth any of his neighbours a blemish, as he did, so shall it be done to him:\n"
	"fracture for fracture, eye for eye, tooth for tooth he shall restore. What blemish he gave, the like shall he be compelled to sustain.\n"
	"He that striketh a beast, shall render another. He that striketh a man, shall be punished.\n"
	"Let there be equal judgment among you, whether a stranger, or a natural sin: because I am the Lord your God.\n"
	"And Moyses spake to the children of Israel: and they brought him forth that had blasphemed, without the camp, and they stoned him. And the children of Israel did as our Lord had commanded Moyses.";