const char* chap1140 = "AND the festival day of the Azymes approached, which is called Pasch:\n"
	"& the chief Priests & the Scribes sought how they might kill him: but they feared the people.\n"
	"And Satan entered into Judas that was surnamed Iscariote, one of the Twelve.\n"
	"And he went, and talked with the chief Priests and the Magistrates, how he might betray him to them.\n"
	"And they were glad, and bargained to give him money.\n"
	"And he promised. And he sought opportunity to betray him apart from the multitudes.\n"
	"And the day of the Azymes came, wherein it was necessary that the Pasch should be killed.\n"
	"And he sent Peter and John, saying: Go and prepare us the Pasch, that we may eat.\n"
	"But they said: Where wilt thou that we prepare it?\n"
	"And he said to them: Behold, as you enter into the city, there shall meet you a man carrying a pitcher of water: follow him into the house into which he entereth,\n"
	"and you shall say to the good-man of the house: The Master saith to thee, where is the inn where I may eat the Pasch with my Disciples?\n"
	"And he will shew you a great refectory adorned: and there prepare.\n"
	"And they going, found as he said to them, and prepared the Pasch.\n"
	"And when the hour was come, he sat down, and the twelve Apostles with him.\n"
	"And he said to them: With desire I have desired to eat this Pasch with you before I suffer.\n"
	"For I say to you, that from this time I will not eat it, till it be fulfilled in the Kingdom of God.\n"
	"And taking the chalice he gave thanks, and said: Take and divide among you.\n"
	"For I say to you, that I will not drink of the generation of the vine, till the Kingdom of God do come.\n"
	"And taking bread, he gave thanks, and brake; and gave to them, saying: THIS IS MY BODY WHICH IS GIVEN FOR YOU. Do this for a commemoration of me.\n"
	"In like manner the chalice also, after he had supped, saying: THIS IS THE CHALICE^ THE NEW TESTAMENT IN MY BLOOD, WHICH SHALL BE SHED FOR YOU.\n"
	"But yet behold, the hand of him that betrayeth me, is with me on the table.\n"
	"And the Son of man indeed goeth according to that which is determined: but yet woe to that man by whom he shall be betrayed.\n"
	"And they began to question among themselves, which of them it should be that should do this.\n"
	"And there fell also a contention between them, which of them seemed to be greater.\n"
	"And he said to them: The Kings of the Gentiles overrule them; and they that have power upon them, are called beneficial.\n"
	"But you not so: but he that is the greater among you, let him become as the younger: & he that is the leader, as the waiter.\n"
	"For which is greater, he that sitteth at the table, or he that ministereth? Is not he that sitteth? But I am in the midst of you, as he that ministereth:\n"
	"& you are they that have remained with me in my tentations.\n"
	"And I dispose to you, as my Father disposed to me, a Kingdom:\n"
	"that you may eat & drink upon my table in my Kingdom, & may sit upon thrones, judging the twelve tribes of Israel.\n"
	"And our Lord said: Simon, Simon, behold Satan hath required to have you for to sift as wheat:\n"
	"BUT I HAVE PRAYED FOR THEE, that thy faith fail not: and thou once converted, confirm thy brethren.\n"
	"Who said to him: Lord, with thee I am ready to go both into prison and unto death.\n"
	"And he said: I say to thee Peter, the cock shall not crow today, till thou deny thrice that thou knowest me.\n"
	"And he said to them: When I sent you without purse and scrip and shoes, did you lack any thing? But they said: Nothing.\n"
	"He said therefore unto them: But now he that hath a purse, let him take it, likewise also a scrip: and he that hath not, let him sell his coat, and buy a sword.\n"
	"For I say to you, that yet this that is written must be fulfilled in me: And with the wicked was he reputed. For those things that are concerning me, have an end.\n"
	"But they said: Lord, lo two swords here. But he said to them: It is enough.\n"
	"And going forth he went according to his custom into mount-Olivet. And his Disciples also followed him.\n"
	"And when he was come to the place, he said to them: Pray, lest ye enter into tentation.\n"
	"And he was pulled away from them a stone's cast: and kneeling he prayed,\n"
	"saying: Father, if thou wilt, transfer this chalice from me. But yet not my will, but thine be done.\n"
	"And there appeared to him an Angel from Heaven, strengthening him. And being in an agony, he prayed the longer.\n"
	"And his sweat became as drops of blood trickling down upon the earth.\n"
	"And when he was risen up from prayer, and was come to his Disciples, he found them sleeping for pensiveness.\n"
	"And he said to them: Why sleep you? Arise, pray, lest you enter into tentation.\n"
	"As he was yet speaking, behold a multitude: and he that was called Judas, one of the Twelve, went before them, and approached to JESUS, for to kiss him.\n"
	"And JESUS said to him: Judas with a kiss doest thou betray the Son of man?\n"
	"And they that were about him, seeing what would be, said to him: Lord, shall we strike with the sword?\n"
	"And one of them smote the servant of the high Priest: and cut off his right ear.\n"
	"But JESUS answering, said: Suffer ye thus far. And when he had touched his ear, he healed him.\n"
	"And JESUS said to them that were come unto him, the chief Priests, and magistrates of the temple, & ancients: As it were to a thief are you come forth with swords and clubs?\n"
	"When I was daily with you in the temple, you did not lay hands upon me, but this is your hour, and the power of darkness.\n"
	"And apprehending him, they led him to the high Priest's house: but Peter followed a far off.\n"
	"And a fire being kindled in the midst of the court, & they sitting about it, Peter was in the midst of them.\n"
	"Whom when a certain wench saw sitting at the light, and had beheld him, she said: This fellow also was with him.\n"
	"But he denied him, saying: Woman, I know him not.\n"
	"And after a while another man seeing him, said: And thou art of them. But Peter said: O man I am not.\n"
	"And after the space as it were of one hour, a certain other man affirmed, saying: Verily this fellow also was with him: for he is also a Galilaean.\n"
	"And Peter said: Man I know not what thou sayest. And incontinent as he was yet speaking, the cock crew.\n"
	"And our Lord turning looked on Peter. And Peter remembered the word of our Lord, as he had said: That before the cock crow, thou shalt thrice deny me.\n"
	"And Peter going forth a doors, wept bitterly.\n"
	"And the men that held him, mocked him, beating him.\n"
	"And they did blind-fold him, and smote his face. And they asked him saying: Prophesy, who is it that smote thee?\n"
	"And blaspheming many other things they said against him.\n"
	"And when it was day, there assembled the Ancients of the people and chief Priests and Scribes, and they brought him into their Council, saying:\n"
	"If thou be Christ tell us. And he said to them: If I tell you, you will not believe me:\n"
	"if also I ask, you will not answer me, nor dismiss me.\n"
	"But from henceforth the Son of man shall be sitting on the right hand of the power of God.\n"
	"And they all said: Art thou then the Son of God? Who said: You say that I am.\n"
	"But they said: What need we testimony any further? For ourselves have heard of his own mouth.";