const char* chap1143 = "In the beginning was the WORD, and the WORD was with God, and God was the WORD.\n"
	"This was in the beginning with God.\n"
	"All things were made by him: and without him was made nothing. That which was made,\n"
	"in him was life, and the life was the light of men:\n"
	"and the light shineth in darkness, and the darkness did not comprehend it.\n"
	"There was a man sent from God, whose name was John.\n"
	"This man came for testimony; to give testimony of the light, that all might believe through him.\n"
	"He was not the light, but to give testimony of the light.\n"
	"It was the true light, which lighteneth every man that cometh into this world.\n"
	"He was in the world, and the world was made by him, and the world knew him not.\n"
	"He came into his own, and his own received him not.\n"
	"But as many as received him, he gave them power to be made the sons of God, to those that believe in his name.\n"
	"Who, not of blood, nor of the will of flesh, nor of the will of man, but of God are born.\n"
	"AND THE WORD WAS MADE FLESH, and dwelt in us (and we saw the glory of him, glory as it were of the Only-begotten of the Father) full of grace and verity.\n"
	"John giveth testimony of him, and cryeth saying: This was he of whom I spake, He that shall come after me, is made before me: because he was before me.\n"
	"And of his fullness we all have received, and grace for grace.\n"
	"For the law was given by Moyses, grace and verity was made by JESUS Christ.\n"
	"God no man hath seen at any time: the only-begotten Son which is in the bosom of the Father, he hath declared.\n"
	"And this is John's testimony, when the Jews sent from Jerusalem Priests and Levites to him, that they should ask him, who art thou?\n"
	"And he confessed, and did not deny: and he confessed, That I am not CHRIST.\n"
	"And they asked him: What then? Art thou Elias? And he said: I am not. Art thou the Prophet? And he answered: No.\n"
	"They said therefore unto him: Who art thou, that we may give an answer to them that sent us? what sayest thou of thyself?\n"
	"He said: I am the voice of one crying in the desert, make straight the way of our Lord, as Esaie the Prophet said.\n"
	"And they that were sent were of the Pharisees.\n"
	"And they asked him, and said to him: Why then doest thou baptize, if thou be not Christ, nor Elias, nor the Prophet?\n"
	"John answered them, saying: I baptize in water; but there hath stood in the midst of you whom you know not.\n"
	"The same is he that shall come after me, that is made before me; whose latchet of his shoe I am not worthy to loose.\n"
	"These things were done in Bethania beyond Jordan, where John was baptizing.\n"
	"The next day John saw JESUS coming to him, and he saith: Behold the lamb of God, behold him that taketh away the sin, of the world.\n"
	"This is he of whom I said: After me there cometh a man, which is made before me: because he was before me.\n"
	"And I knew him not, but that he may be manifested in Israel, therefore came I baptizing in water.\n"
	"And John gave testimony, saying: That I saw the Spirit descending as a dove from Heaven, and he remained upon him.\n"
	"And I knew him not: but he that sent me to baptize in water, he said to me: He upon whom thou shalt see the Spirit descending and remaining upon him, he it is that baptizeth in the Holy Ghost.\n"
	"And I saw; and I gave testimony that this is the Son of God.\n"
	"The next day again John stood, and two of his Disciples.\n"
	"And beholding JESUS walking, he saith: Behold the Lamb of God.\n"
	"And the two Disciples heard him speaking, and they followed JESUS.\n"
	"And JESUS turning, and seeing them following him, saith to them, What seek you? Who said to him: Rabbi (which is called by interpretation, Master) where dwellest thou?\n"
	"He saith to them: Come and see. They came, and saw where he abode, and they tarried with him that day: and it was about the tenth hour.\n"
	"And Andrew the brother of Simon Peter was one of the two that had heard of John, and followed him.\n"
	"He findeth first his brother Simon, and saith to him: We have found MESSIAS, which is being interpreted, CHRIST.\n"
	"And he brought him to JESUS. And JESUS looking upon him, said: Thou art Simon the son of Jona: thou shalt be called Cephas, which is interpreted, Peter.\n"
	"On the morrow he would go forth into Galilee, and he findeth Philippe. And JESUS saith to him: Follow me.\n"
	"And Philippe was of Bethsaida, the city of Andrew and Peter.\n"
	"Philippe findeth Nathanael, and saith to him: Him whom Moyses in the law, and the Prophets wrote of, we have found, JESUS the son of Joseph, of Nazareth.\n"
	"And Nathanael said to him: From Nazareth can there be any good? Philippe saith to him: Come and see.\n"
	"JESUS saw Nathanael coming to him, and he saith of him: Behold an Israelite in very deed, in whom there is no guile.\n"
	"Nathanael saith to him: How knowest thou me? JESUS answered and said to him: Before that Philippe did call thee, when thou wast under the figtree, I saw thee.\n"
	"Nathanael answered him and saith: Rabbi, thou art the Son of God, thou art the King of Israel.\n"
	"JESUS answered, and said to him: Because I said unto thee, I saw thee under the figtree, thou believest; greater than these things shalt thou see.\n"
	"And he saith to him: Amen Amen I say to you, You shall see the Heaven opened, and the Angels of God ascending and descending, upon the Son of man.";