const char* chap1147 = "AFTER these things there was a festival day of the Jews, and JESUS went up to Jerusalem.\n"
	"And there is at Jerusalem upon Probatica a pond which in Hebrew is surnamed Bethsaida, having five porches.\n"
	"In these lay a great multitude of sick persons, of blind, lame, withered, expecting the stirring of the water.\n"
	"And an Angel of our Lord descended at a certain time into the pond; and the water was stirred. And he that had gone down first into the pond after the stirring of the water, was made whole of whatsoever infirmity he was holden.\n"
	"And there was a certain man there that had been eight and thirty years in his infirmity.\n"
	"Him when JESUS had seen lying, & knew that he had now a long time, he saith to him: Wilt thou be made whole?\n"
	"The sick man answered him: Lord, I have no man, when the water is troubled, to put me into the pond. For whiles I come, another goeth down before me.\n"
	"JESUS saith to him: Arise, take up thy bed, and walk.\n"
	"And forthwith he was made whole: and he took up his bed, and walked. And it was the Sabboth that day.\n"
	"The Jews therefore said to him that was healed: It is the Sabboth, thou mayst not take up thy bed.\n"
	"He answered them: He that made me whole, he said to me, take up thy bed, and walk.\n"
	"They asked him therefore, what is that man that said to thee, take up thy bed, and walk?\n"
	"But he that was made whole, knew not who it was. For JESUS shrunk aside from the multitude standing in the place.\n"
	"Afterward JESUS findeth him in the temple, & said to him: Behold thou art made whole; sin no more, lest some worse thing chance to thee.\n"
	"That man went his way, and told the Jews that it was JESUS that made him whole.\n"
	"Thereupon the Jews persecuted JESUS, because he did these things on the Sabboth.\n"
	"But JESUS answered them: My Father worketh until now; and I do work.\n"
	"Thereupon therefore the Jews sought the more to kill him: because he did not only break the Sabboth, but also he said God was his Father, making himself equal to God.\n"
	"JESUS therefore answered, and said to them: Amen, amen, I say to you, the Son cannot do any thing of himself, but that which he seeth the Father doing. For what things soever he doeth, these the Son also doeth in like manner.\n"
	"For the Father loveth the Son, and sheweth him all things that himself doeth, and greater works than these will he shew him, that you may marvel.\n"
	"For as the Father doth raise the dead and quickeneth: so the Son also quickeneth whom he will.\n"
	"For neither doth the Father judge any man: but all judgement he hath given to the Son,\n"
	"that all may honour the Son, as they do honour the Father. He that honoureth not the Son, doth not honour the Father, who sent him.\n"
	"Amen, amen I say to you, that he which heareth my word, and believeth him that sent me, hath life everlasting: and he cometh not into judgement, but shall pass from death into life.\n"
	"Amen, amen I say to you, that the hour cometh, and now it is when the dead shall hear the voice of the Son of God, and they that have heard, shall live.\n"
	"For as the Father hath life in himself; so he hath given to the Son also to have life in himself:\n"
	"and he hath given him power to do judgement also because he is the Son of man.\n"
	"Marvel not at this, because the hour cometh wherein all that are in the graves, shall hear his voice,\n"
	"and they that have done good things, shall come forth into the resurrection of life: but they that have done evil into the resurrection of judgement.\n"
	"I cannot of myself do any thing. As I hear, so I judge: and my judgement is just, because I seek not my will, but the will of him that sent me.\n"
	"If I give testimony of myself, my testimony is not true.\n"
	"There is another that giveth testimony of me: and I know that the testimony is true which he giveth of me.\n"
	"You sent to John; and he gave testimony to the truth,\n"
	"But I receive not testimony of man: but I say these things that you may be saved.\n"
	"He was the lamp burning and shining. And you would for a time rejoice in his light.\n"
	"But I have a greater testimony than John. For the works which the Father hath given me to perfit them: the very works themselves which I do, give testimony of me, that the Father hath sent me.\n"
	"And the Father that sent me, himself hath given testimony of me: neither have you heard his voice at any time, nor seen his shape,\n"
	"and his word you have not remaining in you: because whom he hath sent, him you believe not.\n"
	"Search the scriptures, for you think in them to have life everlasting: & the same are they that give testimony of me:\n"
	"and you will not come to me that you may have life.\n"
	"Glory of men I receive not.\n"
	"But I have known you, that the love of God you have not in you.\n"
	"I am come in the name of my Father, and you receive me not: if another shall come in his own name, him you will receive.\n"
	"How can you believe, that receive glory one of another: and the glory which is of God only, you seek not?\n"
	"Think not that I will accuse you to the Father. There is that accuseth you, Moyses, in whom you trust.\n"
	"For if you did believe Moyses: you would perhaps believe me also. For of me he hath written.\n"
	"And if you do not believe his writings: how will you believe my words.";