const char* chap115 = "And our Lord spake to Moyses in the mount Sinai, saying:\n"
	"Speak to the children of Israel, and thou shalt say to them: When you shall be entered to the land which I will give you, thou shalt sabbatize the sabbath to the Lord.\n"
	"Six years thou shalt sow thy field, and six years thou shalt cut thy vineyard, and shalt gather the fruits thereof:\n"
	"but in the seventh year a sabbath shall be to the earth, of the resting of the Lord: the field thou shalt not sow, and the vineyard thou shalt not cut.\n"
	"The things that the ground shall bring forth of it-self, thou shalt not reap: & the grapes of thy first fruits thou shalt not gather as a vintage: for it is a year of the resting of the earth:\n"
	"but they shall be unto you for meat, to thee & thy man-servant, to thy woman-servant and hireling, and to the stranger that sojourneth with thee:\n"
	"to thy beasts & cattle all things that grow shall give meat.\n"
	"Thou shalt number thee also seven weeks of years, that is to say, seven times seven, which together make forty-nine, years:\n"
	"& thou shalt sound with the trumpet the seventh month, the tenth day of the month, in the time of propitiation in all your land.\n"
	"Thou shalt sanctify the fiftieth year, and shalt proclaim remission to all the inhabitants of thy land: for it is the year of Jubilee. Every man shall return to his possession, & every one shall go back to his old family:\n"
	"because it is the Jubilee & the fiftieth year. You shall not sow nor reap the things that grow in the field of their own accord, & the first fruits of vintage you shall not gather,\n"
	"because of the sanctification of the Jubilee, but forthwith as they grow you shall eat them.\n"
	"In the year of Jubilee all shall return to their possessions.\n"
	"When thou shalt sell any thing to thy neighbour, or shalt buy of him, press not thy brother, but according to the number of the years of Jubilee thou shalt buy of him,\n"
	"and according to the supputation of the fruits he shall sell to thee.\n"
	"The more years remain after the Jubilee, so much more shall the price increase: and the less time that thou shalt account, so much the less shall the purchase be valued, for the time of the fruits he shall sell to thee.\n"
	"Do not afflict your countrymen, but let every one fear his God, because I^ the Lord your God.\n"
	"Do my precepts, and keep my judgments, and fulfill them: that you may dwell in the land without any fear,\n"
	"and the ground may yield you her fruits, which you may eat unto your fill, fearing no man's invasion.\n"
	"But if you say: What shall we eat the seventh year, if we sow not, nor gather our fruits?\n"
	"I will give you my benediction the sixth year, and it shall yield the fruits of three years:\n"
	"and the eighth year you shall sow, and shall eat of the old fruits, until the ninth year: till new be grown; you shall eat the old.\n"
	"The land also shall not be sold for ever: because it is mine, and you are my strangers & sojourners.\n"
	"For the which cause all the country of your possession shall be sold under the condition of redemption.\n"
	"If thy brother impoverished sell his little possession, & his kinsman will, he may redeem that which he had sold.\n"
	"But if he have no kinsman, and himself can find the price to redeem it:\n"
	"the fruits shall be accounted from that time when he sold it, and the residue he shall restore to the buyer, and so he shall receive his possession again.\n"
	"but if his hand find not to repay the price, the buyer shall have that he bought, until the year of Jubilee. For in it all sale shall return to the owner, & to the old possessor.\n"
	"He that selleth a house within the walls of a city, shall have licence to redeem it, until one year be expired.\n"
	"If he redeem it not, and the compass of the year be fully out, the buyer shall possess it, & his posterity for ever, & it cannot be redeemed, no not in the Jubilee.\n"
	"But if the house be in a village that hath not walls, it shall be sold according to the law of fields, if it be not redeemed before, in the Jubilee it shall return to the owner.\n"
	"The houses of Levites, which are in cities, may always be redeemed:\n"
	"if they be not redeemed, in the Jubilee they shall return to the owners, because the houses of the cities of the Levites are for possessions among the children of Israel.\n"
	"But let not their suburbs be sold, because it is a perpetual possession.\n"
	"If thy brother be impoverished, and weak of hand, & thou receive him as a stranger and sojourner and he live with thee,\n"
	"take not usuries of him, nor more than thou gavest: fear thy God, that thy brother may live with thee.\n"
	"Thou shalt not give him thy money to usury, and an overplus of the fruits thou shalt not exact of him.\n"
	"I^ the Lord your God, that brought you out of the Land of Aegypt, that I might give you the Land of Chanaan, & might be your God.\n"
	"If thy brother constrained by poverty sell himself to thee, thou shalt not oppress him with the servitude of servants,\n"
	"but he shall be as an hireling and a sojourner, until the year of Jubilee he shall work with thee,\n"
	"and afterward he shall go out with his children, & shall return to his kindred & to the possession of his fathers,\n"
	"for they are my servants, & I brought them out of the Land of Aegypt, let them not be sold by the condition of servants:\n"
	"afflict him not by might, but fear thy God.\n"
	"Let you manservant, & woman servant, be of the nations that are round about you.\n"
	"And of the strangers, that sojourn with you, or that were born of them in your land, these you shall have for servants:\n"
	"and by right of inheritance shall leave them to your posterity, & shall possess them for ever, but your brethren the children of Israel do ye not oppress by might.\n"
	"If the hand of a stranger or sojourner grow strong among you, and thy brother impoverished sell himself to him, or to any of his stock:\n"
	"after the sale he may be redeemed. He that will of his brethren shall redeem him,\n"
	"both the uncle by father, and the uncle's son, and the kinsman, and the allied. But and if himself be able also, he shall redeem himself,\n"
	"accounting only the years from the time of his selling unto the year of Jubilee: and accounting the money, that he was sold for, according to the number of the years and the reckoning of an hireling.\n"
	"If they be more years that remain until the Jubilee, according to these also shall he repay the price.\n"
	"If few, he shall make the reckoning with him according to the number of the years, and shall repay to the buyer for that which remaineth of the years,\n"
	"his wages being allowed for the which he served before: he shall not afflict him violently in thy sight.\n"
	"And if by these means he cannot be redeemed, in the year of Jubilee he shall go out with his children.\n"
	"For the children of Israel are my servants, whom I brought forth out of the Land of Aegypt.";