const char* chap1150 = "AND JESUS went into the Mount-olivet:\n"
	"and early in the morning again he came into the temple, and the people came to him, and sitting he taught them.\n"
	"And the Scribes and Pharisees bring a woman taken in adultery; and they did set her in the midst,\n"
	"And said to him: Master, this woman was even now taken in adultery.\n"
	"And in the law^ Moyses commanded us to stone such. What sayest thou therefore?\n"
	"And this they said tempting him, that they might accuse him. But JESUS bowing himself down, with his finger wrote in the earth.\n"
	"When they therefore continued asking him, he lifted up himself, and said to them: He that is without sin of you, let him first throw the stone at her.\n"
	"And again bowing himself, he wrote in the earth.\n"
	"And they hearing, went out one by one, beginning at the seniors: and JESUS alone remained, and the woman standing in the midst.\n"
	"And JESUS lifting up himself, said to her: Woman, where are they that accused thee? Hath no man condemned thee?\n"
	"Who said: No man, Lord. And JESUS said: Neither will I condemn thee. Go, and now sin no more.\n"
	"Again therefore JESUS spake to them, saying: I am the light of the world: he that followeth me, walketh not in darkness, but shall have the light of life.\n"
	"The Pharisees therefore said to him: Thou givest testimony of thyself; thy testimony is not true.\n"
	"JESUS answered, and said to them: Although I do give testimony of myself, my testimony is true: because I know whence I came, & whither I go: but you know not whence I come, or whither I go.\n"
	"You judge according to the flesh: I do not judge any man.\n"
	"And if I do judge, my judgement is true: because I am not alone, but I and he that sent me, the Father.\n"
	"And in your law it is written, that the testimony of two men is true.\n"
	"I am he that give testimony of myself: and he that sent me, the Father, giveth testimony of me.\n"
	"They said therefore to him: Where is thy Father? JESUS answered, Neither me do you know, nor my Father. If you did know me, perhaps you might know my Father also.\n"
	"These words JESUS spake in the Treasury, teaching in the temple, and no man apprehended him, because his hour was not yet come.\n"
	"Again therefore JESUS said to them: I go, and you shall seek me, and shall die in your sin. Whither I go, you cannot come.\n"
	"The Jews therefore said: Why, will he kill himself, because he saith: Whither I go, you cannot come?\n"
	"And he said to them: You are from beneath, I am from above. You are of this world, I am not of this world.\n"
	"Therefore I said to you that you shall die in your sins. For if you believe not that I am he, you shall die in your sin.\n"
	"They said therefore to him: Who art thou? JESUS said to them: The Beginning who also speak to you.\n"
	"Many things I have to speak and judge of you. But he that sent me, is true: and what I have heard of him, these things I speak in the world.\n"
	"And they knew not that he said to them that his Father was God.\n"
	"JESUS therefore said to them: When you shall have exalted the Son of man, then you shall know that I am he, and of myself I do nothing, but as the Father hath taught me, these things I speak:\n"
	"and he that sent me, is with me: and he hath not left me alone, because the things that please him I do always.\n"
	"When he spake these things, many believed in him.\n"
	"JESUS therefore said to them that believed him, the Jews: If you abide in my word, you shall be my Disciples indeed.\n"
	"And you shall know the truth, and the truth shall make you free.\n"
	"They answered him: We are the seed of Abraham, and we never served any man: how sayest thou, You shall be free?\n"
	"JESUS answered them: Amen, amen I say to you, that every one which committeth sin, is the servant of sin.\n"
	"And the servant abideth not in the house for ever: the son abideth for ever.\n"
	"If therefore the Son make you free, you shall be free indeed.\n"
	"I know that you are the children of Abraham: but you seek to kill me, because my word taketh not in you.\n"
	"I speak that which I have seen with my Father: and you do the things that you have seen with your father.\n"
	"They answered, and said to him: Our father is Abraham. JESUS saith to them: If you be the children of Abraham, do the works of Abraham.\n"
	"But now, you seek to kill me, a man that have spoken the truth to you, which I have heard of God. This did not Abraham.\n"
	"You do the works of your father. They said therefore to him: We were not born of fornication. We have one Father, God.\n"
	"JESUS therefore said to them: If God were your Father, verily you would love me. For from God I proceeded, and came: for I came not of myself, but he sent me:\n"
	"Why do you not know my speech? Because you cannot hear my word.\n"
	"You are of your father the devil, & the desires of your father you will do. He was a man-killer from the beginning, & he stood not in the verity; because verity is not in him. When he speaketh a lie, he speaketh of his own, because he is a liar, & the father thereof.\n"
	"But because I say the verity, you believe me not.\n"
	"Which of you shall argue me of sin? If I say the verity, why do you not believe me?\n"
	"He that is of God, heareth the words of God. Therefore you hear not, because you are not of God.\n"
	"The Jews therefore answered, and said to him: Do not we say well that thou art a Samaritane, and hast a devil?\n"
	"JESUS answered: I have no devil: but I do honour my Father, and you have dishonoured me.\n"
	"but I seek not mine own glory. There is that seeketh and judgeth.\n"
	"Amen, amen I say to you: If any man keep my word, he shall not see death for ever.\n"
	"The Jews therefore said: Now we have known that thou hast a devil. Abraham is dead, and the Prophets; and thou sayest: If any man keep my word, he shall not taste death for ever.\n"
	"Why, art thou greater than our father Abraham, who is dead? and the Prophets are dead. Whom doest thou make thyself?\n"
	"JESUS answered: If I do glorify myself, my glory is nothing. It is my Father that glorifieth me, whom you say that he is your God.\n"
	"And you have not known him, but I know him. And if I shall say that I know him not, I shall be like to you, a liar. But I do know him, and do keep his word.\n"
	"Abraham your father rejoiced that he might see my day: and he saw, and was glad.\n"
	"The Jews therefore said to him: Thou hast not yet fifty years and hast thou seen Abraham?\n"
	"JESUS said to them: Amen, amen I say to you, before that Abraham was made, I am.\n"
	"They took stones therefore to cast at him. But JESUS hid himself, and went out of the temple.";