const char* chap1156 = "LET not your heart be troubled. You believe in God, believe in me also.\n"
	"In my Father's house there be many mansions. If not, I would have told you, Because I go to prepare you a place.\n"
	"And if I go, and prepare you a place: I come again and will take you to myself, that where I am, you also may be.\n"
	"And whither I go you know, and the way you know.\n"
	"Thomas saith to him: Lord, we know not whither thou goest; and how can we know the way?\n"
	"JESUS saith to him: I am the way, and the verity, and the life. No man cometh to the Father; but by me.\n"
	"If you had known me, my Father also certes you had known: and from hence forth you shall know him, and you have seen him.\n"
	"Philippe saith to him: Lord shew us the Father, and it sufficeth us.\n"
	"JESUS saith to him: So long time I am with you; & have you not known me? Philippe, he that seeth me, seeth the Father also. How sayest thou, Shew us the Father?\n"
	"Doest thou not believe that I am in the Father, & the Father in me? The words that I speak to you, of myself I speak not. But my Father that abideth in me, he doeth the works.\n"
	"Believe you not, that I am in the Father and the Father in me? Otherwise for the works themselves believe.\n"
	"Amen, amen I say to you, he that believeth in me, the works that I do, he also shall do, and greater than these shall he do,\n"
	"because I go to the Father, & whatsoever you shall ask in my name, that will I do: that the Father may be glorified in the Son.\n"
	"If you ask me any thing in my name, that will I do.\n"
	"If you love me, keep my commandments.\n"
	"And I will ask the Father, and he will give you another Paraclete, that he may abide with you for ever,\n"
	"the Spirit of truth, whom the world cannot receive, because it seeth him not, neither knoweth him, but you know him: because he shall abide with you, and shall be in you.\n"
	"I will not leave you orphans: I will come to you.\n"
	"Yet a little while: and the world seeth me no more. But you see me: because I live, and you shall live.\n"
	"In that day you shall know that I am in my Father, and you in me; and I in you.\n"
	"He that hath my commandments, & keepeth them: he it is that loveth me. And he that loveth me, shall be loved of my Father: and I will love him, and will manifest myself to him.\n"
	"Judas saith to him, not that Iscariote: Lord, what is done, that thou wilt manifest thyself to us, and not to the world?\n"
	"JESUS answered, and said to him: If any love me, he will keep my word, and my Father will love him, and we will come to him, and will make abode with him.\n"
	"He that loveth me not, keepeth not my words. And the word which you have heard, is not mine; but his that sent me, the Father's.\n"
	"These things have I spoken to you abiding with you.\n"
	"But the Paraclete the Holy Ghost, whom the Father will send in my name, he shall teach you all things, & suggest unto you all things whatsoever I shall say to you.\n"
	"Peace I leave to you, my peace I give to you; not as the world giveth, do I give to you. Let not your heart be troubled, nor fear.\n"
	"You have heard that I said to you, I go, and I come to you. If you loved me, you would be glad verily, that I go to the Father: because the Father is greater than I.\n"
	"And now I have told you before it come to pass: that when it shall come to pass, you may believe.\n"
	"Now I will not speak many things with you. For the Prince of this world cometh, and in me he hath not any thing.\n"
	"But that the world may know that I love the Father: and as the Father hath given me commandment, so do I: Arise, let us go hence.";