const char* chap116 = "I^ The Lord your God: you shall not make to yourselves an idol and thing graven, neither shall you erect titles, nor set a notorious stone in your land, for to adore it, for I am the Lord your God.\n"
	"Keep my sabbaths, and dread my Sanctuary. I^ the Lord.\n"
	"If you walk in my precepts, and keep my commandments, and do them, I will give you rain in their seasons,\n"
	"and the earth shall bring forth her spring, and the trees shall be replenished with fruits.\n"
	"The threshing of your harvest shall reach unto vintage, and the vintage shall reach unto sowing time: and you shall eat your bread to your fill, and without fear shall you dwell in your land.\n"
	"I will give peace in your coasts: you shall sleep, and there shall be none to make you afraid. I will take away evil beasts: and the sword shall not pass through your quarters.\n"
	"You shall pursue your enemies, and they shall fall before you.\n"
	"Five of yours shall pursue and hundred strangers, and an hundred of you ten thousand: your enemies shall fall by the sword in your sight.\n"
	"I will respect you, and make you increase: you shall be multiplied, & I will establish my covenant with you.\n"
	"You shall eat the eldest of the old store, & new coming upon it you shall cast forth the old.\n"
	"I will set my tabernacle in the midst of you, and my soul shall not cast you off.\n"
	"I will walk among you, & will be your God, & you shall be my people.\n"
	"I^ the Lord your God, that have brought you out of the Land of the Aegyptians, that you should not serve them, and that have broken the chains of your necks, that you might go upright.\n"
	"But if you will not hear me, nor do all my commandments,\n"
	"if you despise my laws, and contemn my judgments that you do not those things which are appointed by me, and bring my covenant to nothing worth,\n"
	"I also will do these things to you: I shall quickly visit you with poverty, and burning heat, which shall waste your eyes, & consume your lives, you shall sow your seed in vain, which shall be devoured of the enemies.\n"
	"I will set my face against you, and you shall fall down before your enemies, and shall be made subject to them that hate you. You shall fly, when no man pursueth you.\n"
	"But if you will not obey me so neither, I will increase your chastisements seven-fold for your sins,\n"
	"and will break the pride of your stubbornness. And I will make to you the heaven from above as iron, and the earth as brass.\n"
	"Your labour shall be spent in vain, the earth shall not bring forth her spring, nor the trees yield their fruits.\n"
	"If you walk contrary to me, & will not hear me, I will increase your plagues until seven-fold for your sins:\n"
	"& I will send in upon you the beasts of the field, which may consume you, & your cattle, and may bring all things to a small number, and that your ways may be made desert.\n"
	"And if you will neither so receive discipline, but walk rather contrary to me:\n"
	"I also will go opposite against you, and will strike you seven times for your sins,\n"
	"and I will bring in upon you the sword a revenger of my covenant. And when you shall fly into the cities, I will send the pestilence in the midst of you, and you shall be delivered in the hands of the enemies,\n"
	"after I shall have broken the staff of your bread: so that ten women shall bake your breads in one oven, and shall render them by weight: and you shall eat, and shall not be filled.\n"
	"But if you will neither by these means hear me, but walk against me,\n"
	"I also will go against you in contrary fury, and will chastise you with seven plagues for your sins,\n"
	"so that you shall eat the flesh of your sons & of your daughters.\n"
	"I will destroy your excelses, & break your idols. You shall fall among the ruins of your idols, & my soul shall abhor you,\n"
	"in so much that I will bring your cities into a wilderness, and I will make your Sanctuaries desert, neither will I receive any more the most sweet odour.\n"
	"And I will destroy your land. And your enemies shall be astonished upon it, when they shall be inhabitants thereof.\n"
	"And you I will disperse into the Gentiles, and will draw out the sword after you, and your land shall be desert, and your cities destroyed.\n"
	"Then shall the land take pleasure in her sabbaths all the days of her desolation: when you shall be\n"
	"in the enemy's land, she shall sabbatize, and rest in the sabbaths of her desolation, because she did not rest in your sabbaths when you dwelt in it.\n"
	"And they that shall remain of you, I will put fear in their hearts in the countries of their enemies, the sound of a flying leaf shall terrify them, and they shall fly it as it were a sword: they shall fall when no man pursueth,\n"
	"and they shall every one fall upon their brethren, as flying from wars, none of you shall be so hardy as to resist your enemies.\n"
	"You shall perish among the Gentiles, and the enemy's land shall consume you.\n"
	"And if of them also some remain, they shall pine away in their iniquities in the land of their enemies, and for the sins of their fathers and their own they shall be afflicted:\n"
	"until they confess their own & their ancestors' iniquities, whereby they have prevaricated against me, and walked contrary unto me.\n"
	"I also therefore will walk against them, & bring them into their enemy's land, until their uncircumcised mind be ashamed: then shall they pray for their impieties.\n"
	"And I will remember my covenant, that I made with Jacob, and Isaac, and Abraham. Of the land also I will be mindful:\n"
	"which when it shall be left of them, shall take pleasure in her sabbaths, being desolate for them. But they shall pray for their sins, for that they rejected my judgments, and despised my laws.\n"
	"Howbeit even when they were in the land of their enemies I did not cast them off altogether, neither did I so despise them, that they should be consumed, and I should make my covenant with them frustrate. For I am the Lord their God,\n"
	"and I will remember mine old covenant, when I brought them out of the Land of Aegypt, in the sight of the Gentiles, for to be their God. I^ the Lord. These are the judgments, and precepts, and laws, which our Lord gave between himself and the children of Israel in Mount Sinai by the hand of Moyses.";