const char* chap1161 = "THEN therefore Pilate took JESUS, and scourged him.\n"
	"And the soldiers platting a crown of thorns, put it upon his head: and they put about him a purple garment.\n"
	"And they came to him, and said: Hail King of the Jews; and they gave him blows.\n"
	"Pilate went forth again, and saith to them: Behold I bring him forth unto you, that you may know that I find no cause in him.\n"
	"JESUS therefore went forth carrying the crown of thorns, and the purple vestiment. And he saith to them: Lo the man.\n"
	"When the chief Priests therefore and the ministers had seen him, they cried, saying: Crucify, crucify him. Pilate saith to them: Take him you, and crucify him. For I find no cause in him.\n"
	"The Jews answered him: We have a Law; and according to the Law he ought to die; because he hath made himself the Son of God.\n"
	"When Pilate therefore had heard this saying, he feared more.\n"
	"And he entered into the Palace again; and he saith to JESUS: Whence art thou? But JESUS gave him no answer.\n"
	"Pilate therefore saith to him: Speakest thou not to me? knowest thou not that I have power to crucify thee, and I have power to release thee?\n"
	"JESUS answered: Thou shouldest not have any power against me, unless it were given thee from above. Therefore he that hath betrayed me to thee, hath the greater sin.\n"
	"From thence forth Pilate sought to release him. But the Jews cried, saying: If thou release this man, thou art not Caesar's friend. Every one that maketh himself a king, speaketh against Caesar.\n"
	"But Pilate when he had heard these words, brought forth JESUS: and he sat in the judgement seat, in the place that is called Lithostrotos, and in Hebrew Gabbatha.\n"
	"And it was the Parasceve of Pasch, about the sixth hour, and he saith to the Jews: Lo your King.\n"
	"But they cried: Away, away with him, crucify him. Pilate saith to them: Shall I crucify your King? The chief Priests answered: We have no King, but Caesar.\n"
	"Then therefore he delivered him unto them for to be crucified. And they took JESUS, and led him forth.\n"
	"And bearing his own cross he went forth into that which is called the place of Calvary, in Hebrew Golgotha.\n"
	"Where they crucified him, and with him two others, on the one side & on the other, and in the midst JESUS.\n"
	"And Pilate wrote a title also: and he put it upon the cross. And it was written, JESUS OF NAZARETH THE KING OF THE JEWS.\n"
	"This title therefore many of the Jews did read: because the place where JESUS was crucified, was nigh to the city: and it was written in Hebrew, in Greek, and in Latin.\n"
	"The chief Priests therefore of the Jews said to Pilate: Write not, The King of the Jews; but that he said, I am King of the Jews.\n"
	"Pilate answered: That which I have written, I have written.\n"
	"The soldiers therefore when they had crucified him, took his garments (and they made four parts, to every soldier a part) & his coat. And his coat was without seam, wrought from the top throughout.\n"
	"They said therefore one to another: Let us not cut it, but let us cast lots for it whose it shall be. That the scripture might be fulfilled saying: They have parted my garments among them: and upon my vesture they have cast lots. And the soldiers did these things.\n"
	"And there stood beside the cross of JESUS, his mother, and his mother's sister, Mary of Cleophas, and Mary Magdalene.\n"
	"When JESUS therefore had seen his mother and the Disciple standing whom he loved, he saith to his mother: Woman, behold thy son.\n"
	"After that, he saith to the Disciple: Behold thy mother. And from that hour the Disciple took her to his own.\n"
	"Afterward JESUS knowing that all things were now consummate, that the scripture might be fulfilled, he saith, I thirst.\n"
	"A vessel therefore stood there full of vinegar. And they putting a sponge full of vinegar about hyssop, offered it to his mouth.\n"
	"JESUS therefore when he had taken the vinegar, said: It is consummate. And bowing his head, he gave up the ghost.\n"
	"The Jews therefore (because it was the Parasceve) that the bodies might not remain upon the cross on the Sabboth (for that was a great Sabboth day) they desired Pilate that their legs might be broken, and they might be taken away.\n"
	"The soldiers therefore came: and of the first indeed they brake the legs, and of the other that was crucified with him.\n"
	"But after they were come to JESUS, when they saw that he was dead, they did not break his legs,\n"
	"but one of the soldiers with a spear opened his side, & incontinent there came forth blood and water.\n"
	"And he that saw it, hath given testimony: and his testimony is true. And he knoweth that he saith true, that you also may believe.\n"
	"For these things were done that the scripture might be fulfilled: You shall not break a bone of him.\n"
	"And again another scripture saith: They shall look on him whom they pierced.\n"
	"And after these things Joseph of Arimathaea (because he was a Disciple of JESUS, but secret for fear of the Jews) desired Pilate that he might take away the body of JESUS. And Pilate permitted. He came therefore, & took away the body of JESUS.\n"
	"Nicodemus also came, he that at the first came to JESUS by night, bringing a mixture of myrrh and aloes, about an hundred pounds.\n"
	"They took therefore the body of JESUS, and bound it in linen cloths with the spices, as the manner is with the Jews to bury.\n"
	"And there was in the place where he was crucified, a garden: and in the garden a new monument, wherein no man yet had been laid.\n"
	"There therefore because of the Parasceve of the Jews, they laid JESUS, because the monument was hard by.";