const char* chap1165 = "AND when the days of Pentecost were accomplished, they were all together in one place:\n"
	"and suddenly there was made a sound from Heaven, as of a vehement wind coming, & it filled the whole house where they were sitting.\n"
	"And there appeared to them parted tongues as it were of fire, and it sat upon every one of them:\n"
	"and they were all replenished with the HOLY GHOST, and they began to speak with diverse tongues, according as the HOLY GHOST gave them to speak.\n"
	"And there were dwelling at Jerusalem Jews, devout men of every nation that is under Heaven.\n"
	"And when this voice was made, the multitude came together, and was astonished in mind, because every man heard them speak in his own tongue.\n"
	"And they were all amazed, and marveled saying: Are not, lo, all these that speak, Galilaeans,\n"
	"and how have we heard, each man our own tongue wherein we were born?\n"
	"Parthians, & Medians, & Elamites, & that inhabit Mesopotamia, Jewry, & Cappadocia, Pontus, and Asia,\n"
	"Phrygia, and Pamphilia, Aegypt & the parts of Libya that is about Cyrenee, & strangers of Rome,\n"
	"Jews also, and Proselytes, Cretensians, and Arabians: we have heard, them speak in our own tongues the great works of God.\n"
	"And they were all astonished, and marveled, saying one to another: What meaneth this?\n"
	"But others deriding said: That these are full of new wine.\n"
	"But Peter standing with the Eleven, lifted up his voice; and spake to them: Ye men, Jews, and all you that dwell in Jerusalem, be this known to you, and with your ears receive my words.\n"
	"For these are not drunk, as you suppose, whereas it is the third hour of the day:\n"
	"But this is it that was said by the Prophet Joel:\n"
	"And it shall be, in the last days (saith our Lord) of my Spirit I will pour out upon all flesh: and your sons and your daughters shall prophesy, and your young men shall see visions, and your Ancients shall dream dreams.\n"
	"and upon my servants truly, and upon my handmaids will I pour out in those days, of my Spirit, and they shall prophesy:\n"
	"and I will give wonders in the Heaven above, and signs in the earth beneath, blood and fire, and vapour of smoke.\n"
	"The sun shall be turned into darkness, and the moon into blood, before the great and manifest day of our Lord doth come.\n"
	"And it shall be, every one whosoever calleth upon the name of our Lord, shall be saved.\n"
	"Ye men of Israel hear these words: JESUS of Nazareth a man approved of God among you, by miracles & wonders and signs which God did by him in the midst of you, as you also know;\n"
	"this same, by the determinate counsel & prescience of God being delivered, you by the hands of wicked men have crucified and slain.\n"
	"Whom God hath raised up loosing the sorrows of hell, according as it was impossible that he should be holden of it.\n"
	"For David saith concerning him: I foresaw the Lord in my sight always: because he is at my right hand that I be not moved.\n"
	"For this, my heart hath been glad and my tongue hath rejoiced: moreover my flesh also shall rest in hope.\n"
	"Because thou wilt not leave my soul in hell, nor give thy Holy one to see corruption.\n"
	"Thou hast made known to me the ways of life: thou shalt make me full of joyfulness with thy face.\n"
	"Ye men, Brethren, let me boldly speak to you of the Patriarch David: that he died, and was buried; and his sepulchre is with us until this present day.\n"
	"Whereas therefore he was a Prophet, and knew that by an oath God hath sworn to him, that of the fruit of his loins there should sit upon his seat;\n"
	"foreseeing, he spake of the resurrection of Christ, for neither was he left in hell, neither did his flesh see corruption.\n"
	"This JESUS hath God raised again, whereof all we are witnesses.\n"
	"Being exalted therefore by the right hand of God, and having received of his Father the promise of the Holy Ghost, he hath poured out this whom you see and hear.\n"
	"For David ascended not into Heaven; but he saith: Our Lord hath said to my Lord, sit on my right hand.\n"
	"until I make thine enemies the foot-stool of thy feet.\n"
	"Therefore let all the house of Israel know most certainly that God hath made him both Lord, & CHRIST, this JESUS, whom you have crucified.\n"
	"And hearing these things, they were compunct in heart, and said to Peter and to the rest of the Apostles: What shall we do men, brethren.\n"
	"But Peter said to them, do penance, & be every one of you baptized in the name of JESUS CHRIST for remission of your sins; and you shall receive the gift of the Holy Ghost.\n"
	"For to you is the promise, and to your children, and to all that are far off, whomsoever the Lord our God shall call.\n"
	"With very many other words also did he testify and exhorted them, saying: Save yourselves from this perverse Generation.\n"
	"They therefore that received his word, were baptized: & there were added in that day about three thousand souls.\n"
	"And they were persevering in the doctrine of the Apostles, and in the communication of the breaking of bread, and prayers.\n"
	"And fear came upon every soul; many wonders also and signs were done by the Apostles in Jerusalem, and there was great fear in all.\n"
	"All they also that believed, were together, & had all things common.\n"
	"Their possessions and substance they sold, and divided them to all, according as every one had need.\n"
	"Daily also continuing with one accord in the temple, and breaking bread from house to house, they took their meat with joy and simplicity of heart:\n"
	"praising God, and having grace with all the people. And our Lord increased them that should be saved, daily together.";