const char* chap117 = "And our Lord spake to Moyses, saying:\n"
	"Speak to the children of Israel, and thou shalt say to them: The man that shall have made a vow, and bound his soul to God, by estimation he shall give the price.\n"
	"If it be a man from the twentieth year until three score, he shall give fifty sicles of silver, after the measure of the Sanctuary:\n"
	"if a woman, thirty.\n"
	"But from the fifth year until the twentieth, a man shall give twenty sicles: a woman ten.\n"
	"From one month until the fifth year, for a man shall be given five sicles: for a woman three.\n"
	"One that is three score & above, a man shall give fifteen sicles, a woman ten.\n"
	"If he be poor, and not able to pay the estimation, he shall stand before the Priest: and as much as he shall esteem, and see him able to pay, so much shall he give.\n"
	"But the beast, that may be immolated to the Lord, if a man do vow it, shall be holy,\n"
	"and cannot be changed, that is to say, neither a better for a bad, nor a worse for a good, and if he change it, both itself that was changed, and that for the which it was changed, shall be consecrated to the Lord.\n"
	"The unclean beast, which cannot be immolated to the Lord, if any man vow it shall be brought before the Priest.\n"
	"Who judging whether it be good or evil, shall set the price:\n"
	"which if he that offereth will give, he shall add above the estimation the fifth part.\n"
	"If a man vow his house, and sanctify it to the Lord, the Priest shall consider it, whether it be good or bad, and according to the price which he shall appoint, it shall be sold.\n"
	"but if he that had vowed will redeem it, he shall give the fifth part of the estimation besides, and shall have the house.\n"
	"And if he vow the field of his possession, and consecrate it to the Lord, the price shall be esteemed according to the measure of the seed. If the ground be sowed with thirty bushels of barley, let it be sold for fifty sicles of silver.\n"
	"If he vow his field immediately from the year of Jubilee, that is beginning, how much it can be worth, at so much it shall be esteemed:\n"
	"but if some time after, the Priest shall account the money according to the number of years that remain until the Jubilee, and there shall be diminished of the price.\n"
	"And if he that had vowed will redeem his field, he shall add the fifth part of the esteemed money, and shall possess it.\n"
	"And if he will not redeem it, but it be sold to any other man, he that had vowed it can redeem it no more:\n"
	"for when the day of Jubilee cometh, it shall be sanctified to the Lord, and the possession consecrated pertaineth to the right of the Priests.\n"
	"If the field be bought, and being not of his ancestor's possession be sanctified to the Lord,\n"
	"the Priest shall account the price according to the number of years, unto the jubilee: and he that had vowed shall give that to the Lord.\n"
	"But in the Jubilee, it shall return to the former owner that sold it and had it in the lot of his possession.\n"
	"All estimation shall be weighed by the sicle of the sanctuary. A sicle hath twenty oboles.\n"
	"The first born, which pertain to the Lord, no man may sanctify and vow: whether it be ox, or sheep, they are the Lord's.\n"
	"And if it be an unclean beast, he that offereth it shall redeem it, according to thy estimation, and shall add the fifth part of the price. If he will not redeem it, it shall be sold to another for how much soever it was esteemed by thee.\n"
	"Any thing that is consecrated to the Lord, whether it be man, or beast, or field, shall not be sold, neither can it be redeemed. Whatsoever is once consecrated, shall be holy of holies to the Lord.\n"
	"And any consecration, that is offered of a man, shall not be redeemed, but dying shall die.\n"
	"All tithes of the land, whether of corn, or of the fruits of trees, are the Lord's, and are sanctified to him.\n"
	"And if any man will redeem his tithes, he shall add the fifth part of them.\n"
	"Of all the tithes of oxen, and sheep, and goats, that pass under the sheep-herd's rod, every tenth that cometh shall be sanctified to the Lord.\n"
	"It shall not be chosen neither good nor bad, neither shall it be changed for another. If any man change it, both that which was changed, and that for the which it was changed, shall be sanctified to the Lord, and shall not be redeemed.\n"
	"These are the precepts, which our Lord commanded Moyses unto the children of Israel in the mount Sinai.";