const char* chap1170 = "AND the chief priest said: Are these things so?\n"
	"Who said: Ye men, brethren and fathers, hear. The God of glory appeared to our father Abraham when he was in Mesopotamia, before that he abode in Charan,\n"
	"& said to him: Go forth out of thy country, and out of thy kindred, & come into a land that I shall shew thee.\n"
	"Then went he forth out of the land of the Chaldees, and dwelt in Charan. And from thence, after his father was dead, he translated him into this land wherein you do now dwell.\n"
	"And he gave him no inheritance in it, no not the pace of a foot: and he promised to give it him in possession, and to his seed after him, when as he had no child.\n"
	"And God spake to him: That his seed shall be a sojourner in a strange country, and they shall subdue them to servitude, and shall evil entreat them four hundred years.\n"
	"and the nation which they shall serve, will I judge, said God. And after these things they shall go forth and shall serve me in this place.\n"
	"And he gave him the testament of circumcision, and so he begat Isaac, and circumcised him the eighth day: and Isaac, Jacob: and Jacob, the twelve Patriarchs.\n"
	"And the Patriarchs through emulation, sold Joseph into Aegypt. And God was with him:\n"
	"and delivered him out of all his tribulations. And he gave him grace and wisdom in the sight of Pharao the king of Aegypt, and he appointed him Governor over Aegypt and over all his house.\n"
	"And there came famine upon all Aegypt and Chanaan, and great tribulation: and our fathers found no victuals.\n"
	"But when Jacob had heard that there was corn in Aegypt; he sent our fathers first:\n"
	"and at the second time Joseph was known of his brethren, and his kindred was made known unto Pharao.\n"
	"And Joseph sending, called thither Jacob his father and all his kindred in seventy five souls.\n"
	"And Jacob descended into Aegypt: and he died, and our fathers.\n"
	"And they were translated into Sichem, and were laid in the sepulchre that Abraham bought for a price of silver of the sons of Hemor the son of Sichem.\n"
	"And when the time drew near of the promise which God had promised to Abraham, the people increased and was multiplied in Aegypt,\n"
	"until another king arose in Aegypt, that knew not Joseph.\n"
	"This same circumventing our stock, afflicted our fathers, that they should expose their children, to the end they might not be kept alive.\n"
	"The same time was Moyses born, and he was acceptable to God; who was nourished three months in his father's house.\n"
	"And when he was exposed, Pharao's daughter took him up, and nourished him for her own son.\n"
	"And Moyses was instructed in all the wisdom of the Aegyptians: and he was mighty in his words and works.\n"
	"And when he was fully of the age of forty years, it came to his mind to visit his brethren the children of Israel.\n"
	"And when he had seen one suffer wrong, he defended him: and striking the Aegyptian, he revenged his quarrel that sustained the wrong.\n"
	"And he thought that his brethren did understand that God by his hand would save them: but they understood it not.\n"
	"And the day following he appeared to them being at strife: and he reconciled them unto peace, saying: Men, ye are brethren, wherefore hurt you one another?\n"
	"But he that did the injury to his neighbour, repelled him, saying: Who hath appointed thee prince and judge over us:\n"
	"What, wilt thou kill me, as thou didst yesterday kill the Aegyptian?\n"
	"And Moyses fled upon this word: and he became a sojourner in the land of Madian, where he begat two sons.\n"
	"And after forty years were expired, there appeared to him in the desert of mount Sina an Angel in the fire of the flame of a bush.\n"
	"And Moyses seeing it, marveled at the vision. And as he went near to view it, the voice of our Lord was made to him:\n"
	"I am the God of thy fathers; the God of Abraham, the God of Isaac, and the God of Jacob. And Moyses being made to tremble, durst not view it.\n"
	"And our Lord said to him: Loose off the shoe of thy feet, for the place wherein thou standest, is holy ground.\n"
	"Seeing I have seen the affliction of my people which is in Aegypt, and I have heard their groaning and am descended to deliver them. And now come, and I will send thee into Aegypt.\n"
	"This Moyses, whom they denied, saying: Who hath appointed thee prince and Captain? him God sent prince & redeemer with the hand of the Angel that appeared to him in the bush.\n"
	"He brought them forth doing wonders and signs in the land of Aegypt, and in the red sea, and in the desert forty years.\n"
	"This is that Moyses which said to the children of Israel: A Prophet will God raise up to you of your own brethren as myself: him you shall hear.\n"
	"This is he that was in the assembly in the wilderness, with the Angel that spake to him in Mount Sina, and with our fathers: who received the words of life to give unto us.\n"
	"To whom our fathers would not be obedient: but they repelled him, and in their hearts turned away into Aegypt,\n"
	"saying to Aaron: Make us gods that may go before us. For this Moyses that brought us out of the land of Aegypt, we know not what is befallen to him.\n"
	"And they made a calf in those days, and offered sacrifice to the idol, and rejoiced in the works of their own hands.\n"
	"And God turned, and delivered them up to serve the host of Heaven, as it is written in the book of the Prophets: Did you offer victims and hosts unto me forty years in the desert, O house of Israel?\n"
	"And you took unto you the tabernacle of Moloch, and the star of your god Rempham, figures which you made, to adore them. And I will translate you beyond Babylon.\n"
	"The tabernacle of testimony was among our fathers in the desert, as God ordained speaking to Moyses, that he should make it according to the form which he had seen.\n"
	"Which our fathers with Jesus receiving, brought it in also into the possession of the Gentiles. Which God expelled from the face of our fathers, till in the days of David,\n"
	"who found grace before God, and desired that he might find a tabernacle for the God of Jacob.\n"
	"And Salomon built him a house.\n"
	"But the Highest dwelleth not in houses made by hand, as the Prophet saith:\n"
	"Heaven is my seat: and the earth the foot-stool of my feet. What house will you build me, saith our Lord, or what place is there of my resting?\n"
	"Hath not my hand made all these things?\n"
	"You stiff-necked and of uncircumcised hearts and ears, you always resist the Holy Ghost: as your fathers, yourselves also.\n"
	"Which of the Prophets did not your fathers persecute? And they slew them that foretold of the coming of the Just one, of whom now\n"
	"you have been betrayers and murderers: who received the Law by the disposition of Angels, and have not kept it.\n"
	"And hearing these things they were cut in their hearts, and they gnashed with their teeth at him.\n"
	"But he being full of the Holy Ghost, looking steadfastly unto Heaven, saw the glory of God, and JESUS standing on the right hand of God. And he said: Behold I see the Heavens opened, and the Son of man standing on the right hand of God.\n"
	"And they crying out with a loud voice, stopped their ears, and with one accord ran violently upon him.\n"
	"And casting him forth without the city they stoned him: and the witnesses laid off their garments beside the feet of a young man that was called Saul.\n"
	"And they stoned Steven invocating, and saying: Lord JESUS, receive my spirit.\n"
	"And falling on his knees, he cried with a loud voice, saying: Lord, lay not this sin unto them. And when he had said this, he fell asleep. And Saul was consenting to his death.";