const char* chap1171 = "AND the same day there was made a great persecution in the Church, which was at Jerusalem, and all were dispersed through the countries of Jewry and Samaria, saving the Apostles.\n"
	"And devout men took order for Steven's funeral, and made great mourning upon him.\n"
	"But Saul wasted the Church: entering in from house to house, and drawing men and women, delivered them into prison.\n"
	"They therefore that were dispersed, passed through, evangelizing the word.\n"
	"And Philippe descending into the city of Samaria, preached CHRIST unto them.\n"
	"and the multitudes were attent to those things which were said of Philippe, with one accord hearing, and seeing the signs that he did.\n"
	"For many of them that had unclean spirits, crying with a loud voice, went out. And many sick of the palsy and lame were cured.\n"
	"There was made therefore great joy in that city.\n"
	"And a certain man named Simon, who before had been in that city a Magician, seducing the nation of Samaria, saying himself to be some great one:\n"
	"unto whom all harkened from the least to the greatest, saying: This man is the power of God, that is called great.\n"
	"And they were attent upon him, because a long time he had bewitched them with his magical practises.\n"
	"But when they had believed Philippe evangelizing of the Kingdom of God, and of the name of JESUS CHRIST, they were baptized, men and women.\n"
	"Then Simon also himself believed: & being baptized, he cleaved to Philippe. Seeing also signs and very great miracles to be done, he was astonished with admiration.\n"
	"And when the Apostles who were in Jerusalem, had heard that Samaria had received the word of God: they sent unto them Peter and John.\n"
	"Who when they were come, prayed for them, that they might receive the Holy Ghost.\n"
	"For he was not yet come upon any of them, but they were only baptized in the name of our Lord JESUS.\n"
	"Then did they impose their hands upon them, & they received the Holy Ghost.\n"
	"And when Simon had seen that by the imposition of the hand of the Apostles, the Holy Ghost was given, he offered them money,\n"
	"saying: Give me also this power, that on whomsoever I impose my hands, he may receive the Holy Ghost.\n"
	"But Peter said to him: Thy money be with thee unto perdition: because thou hast thought that the gift of God is purchased with money.\n"
	"Thou hast no part, nor lot in this word. For thy heart is not right before God.\n"
	"Do penance therefore from this thy wickedness: and pray to God, if perhaps this cogitation of thy heart may be remitted thee.\n"
	"For I see thou art in the gall of bitterness and the obligation of iniquity.\n"
	"And Simon answering said: Pray you for me to our Lord, that nothing come upon me of these things which you have said.\n"
	"And they indeed having testified and spoken the word of our Lord, returned to Jerusalem, and evangelized to many countries of the Samaritans.\n"
	"And an Angel of our Lord spake to Philippe, saying: Arise, and go toward the South, to the way that goeth down from Jerusalem into Gaza: this is desert.\n"
	"And rising he went. And behold, a man of Aethiopia, an Eunuch, of great authority under Candace the queen of the Aethiopians, who was over all her treasures, was come to Jerusalem to adore:\n"
	"and he was returning and sitting upon his chariot, and reading Esay the Prophet.\n"
	"And the Spirit said to Philippe: Go near, and join thyself to this same chariot.\n"
	"And Philippe running thereunto, heard him reading Esay the Prophet, and he said: Trowest thou that thou understandest the things which thou readest?\n"
	"Who said: And how can I, unless some man shew me? & he desired Philippe that he would come up and sit with him.\n"
	"And the place of the scripture which he did read, was this: As a sheep to slaughter was he led: and as a lamb before his shearer, without voice, so did he not open his mouth.\n"
	"In humility his judgement was taken away. His generation who shall declare, for from the earth shall his life be taken?\n"
	"And the Eunuch answering Philip, said: I beseech thee, of whom doth the Prophet speak this? of himself, or of some other?\n"
	"And, Philip opening his mouth, and beginning from this scripture, evangelized unto him JESUS.\n"
	"And as they went by the way, they came to a certain water: and the Eunuch said: Lo water, who doth let me to be baptized?\n"
	"And Philip said: If thou believe with all thy heart, thou mayest. And he answering said: I believe that JESUS CHRIST is the Son of God.\n"
	"And he commanded the chariot to stay: and both went down into the water, Philip and the Eunuch, and he baptized him.\n"
	"And when they were come up out of the water, the Spirit of our Lord took away Philip, & the Eunuch saw him no more. And he went on his way rejoicing.\n"
	"But Philip was found in Azotus, and passing through, he evangelized to all the cities, till he came to Caesarea.";