const char* chap1175 = "AND at the same time Herod the king set his hands, to afflict certain of the Church.\n"
	"And he killed James the brother of John with the sword.\n"
	"And seeing that it pleased the Jews, he added to apprehend Peter also. And it was the days of the Azymes.\n"
	"Whom when he had apprehended, he cast into prison, delivering him to four quaternions of soldiers to be kept, meaning after the Pasch to bring him forth to the people.\n"
	"And Peter indeed was kept in prison. But prayer was made of the Church without intermission unto God for him.\n"
	"And when Herod would have brought him forth, the same night Peter was sleeping between two soldiers, bound with two chains: and the keepers before the door kept the prison.\n"
	"And behold an Angel of our Lord stood in presence: and light shined in the house: and striking Peter's side, he raised him, saying: Arise quickly. And the chains fell from his hands.\n"
	"And the Angel said to him: Gird thee, and put on thy shoes. And he did so. And he said to him: Put thy garment about thee, & follow me.\n"
	"And going forth he followed him, & he knew not that it was true which was done by the Angel: but he thought that he saw a vision.\n"
	"And passing through the first & the second watch, they came to the iron gate that leadeth to the city, which of itself opened to them. And going out, they went forward one street: and incontinent the Angel departed from him.\n"
	"And Peter returning to himself, said: Now I know in very deed that our Lord hath sent his Angel, and delivered me out of Herod's hand, & from all the expectation of the people of the Jews.\n"
	"And considering, he came to the house of Mary the mother of John, who was surnamed Mark, where many were gathered and praying.\n"
	"And when he knocked at the door of the gate, there came forth a wench to see, named Rhode.\n"
	"And as she knew Peter's voice, for joy she opened not the gate, but running in she told that Peter stood before the gate.\n"
	"But they said to her: Thou art mad. But she affirmed that it was so. But they said: It is his Angel.\n"
	"And Peter continued knocking. And when they had opened, they saw him, & were astonished.\n"
	"And beckoning with his hand to them, that they should hold their peace, he told how our Lord had brought him out of prison, & he said: Tell these things to James & to the brethren. And going forth he went into another place.\n"
	"And when day was come, there was no little ado between the soldiers, what was become of Peter.\n"
	"And Herod, when he had sought him, and had not found, making inquisition of the keepers, commanded them to be led away: & going down from Jewry into Caesarea, there he abode.\n"
	"And he was angry with the Tyrians and the Sidonians. But they with one accord came to him, and persuading Blastus that was chief of the king's chamber, they desired peace, for that their countries were nourished by him.\n"
	"And upon a day appointed, Herod being arrayed with kingly attire, sat in the judgement seat, and made an oration to them.\n"
	"And the people made acclamation, The voices of a God, & not of a man.\n"
	"And forthwith an Angel of our Lord strook him, because he had not given the honour to God: and being consumed of worms, he gave up the ghost.\n"
	"But the word of our Lord increased and multiplied.\n"
	"And Barnabas and Saul returned from Jerusalem, having accomplished their ministry, taking with them John that was surnamed Mark.";