const char* chap1183 = "AND after that the tumult was ceased, Paul calling the Disciples, and exhorting them, took his leave, and set forward to go into Macedonia.\n"
	"And when he had walked through those parts, & had exhorted them with much speech, he came to Greece:\n"
	"where when he had spent three months, the Jews laid wait for him as he was about to sail into Syria: and he had counsel to return through Macedonia.\n"
	"And there accompanied him Sosipater of Pyrrhus, of Beroea: and of Thessalonians, Aristarchus, and Secundus: and Caius of Derbe, and Timothee: and of Asia, Tychicus and Trophimus.\n"
	"These going before, stayed for us at Troas:\n"
	"But we sailed after the days of Azymes from Philippi, and came to them unto Troas in five days, where we abode seven days.\n"
	"And in the first of the Sabboth when we were assembled to break bread, Paul disputed with them, being to depart on the morrow: and he continued the sermon until mid-night.\n"
	"And there were a great number of lamps in the upper chamber where we were assembled.\n"
	"And a certain young man named Eutychus, sitting upon the window, whereas he was oppressed with heavy sleep: (Paul disputing long) driven by sleep, fell from the third loft down, and was taken up dead.\n"
	"To whom when Paul was gone down, he lay upon him: and embracing him he said: Be not troubled, for his soul is in him.\n"
	"And going up and breaking bread and tasting, and having talked sufficiently to them until day light, so he departed.\n"
	"And they brought the lad alive, & were not a little comforted.\n"
	"But we going up into the ship, sailed to Asson, from thence meaning to receive Paul; for so he had ordained, himself purposing to journey by land.\n"
	"And when he had found us in Asson, taking him with us we came to Mitylene.\n"
	"And sailing thence, the day following we came over against Chios: and the other day we arrived at Samos: and the day following we came to Miletum.\n"
	"For Paul had purposed to sail leaving Ephesus, lest any stay should be made him in Asia. For he hastened, if it were possible for him, to keep the day of Pentecost at Jerusalem.\n"
	"And sending from Miletum to Ephesus, he called the Ancients of the Church.\n"
	"Who being come to him, and assembled together, he said to them: You know from the first day that I entered into Asia, in what manner I have been with you all the time,\n"
	"serving our Lord with all humility and tears, and tentations that did chance to me by the conspiracies of the Jews:\n"
	"How I have withdrawn nothing that was profitable, but that I preached it to you, and taught you openly and from house to house,\n"
	"testifying to Jews and Gentiles penance toward God, and faith in our Lord JESUS CHRIST.\n"
	"And now behold, being bound by the spirit, I go to Jerusalem; not knowing what things shall befall me in it,\n"
	"but that the Holy Ghost throughout all cities doth protest to me, saying: that bands and tribulations abide me at Jerusalem.\n"
	"But I fear none of these things, neither do I make my life more precious than myself, so that I may consummate my course & ministry which I received of our Lord JESUS, to testify the Gospel of the grace of God.\n"
	"And now behold I do know, that you shall no more see my face all you, through whom I have passed preaching the Kingdom of God.\n"
	"Wherefore I take you to witness this present day that I am clear from the blood of all.\n"
	"For I have not spared to declare unto you all the counsel of God.\n"
	"Take heed to yourselves and to the whole flock wherein the Holy Ghost hath placed you bishops, to rule the Church of God which he hath purchased with his own blood.\n"
	"I know that after my departure there will ravening wolves enter in among you, not sparing the flock.\n"
	"And out of your own selves shall arise men speaking perverse things, to draw away Disciples after themselves.\n"
	"For the which cause be vigilant, keeping in memory that for three years^ night & day I ceased not with tears to admonish every one of you.\n"
	"And now I commend you to God and to the word of his grace, who is able to edify, and to give inheritance in all the sanctified.\n"
	"No man's silver and gold or garment have I coveted.\n"
	"Yourselves know that for such things as were needful for me and them that are with me, these hands have ministered.\n"
	"I have shewed you all things, that so labouring, you must receive the weak, and remember the word of our Lord JESUS, because he said: It is a more blessed thing to give rather than to take.\n"
	"And when he had said these things, falling on his knees he prayed with all them.\n"
	"And there was great weeping made of all; and falling upon the neck of Paul, they kissed him,\n"
	"being sorry most of all for the word which he had said, that they should see his face no more. And they brought him going unto the ship.";