const char* chap1184 = "AND when it came to pass that we sailed, being carried from them, with a straight course we came to Coos, and the day following to Rhodes, and from thence to Patara.\n"
	"And when we had found a ship that passed over to Phoenice, going up into it we sailed.\n"
	"And when we were in the sight of Cypres, leaving it on the left hand, we sailed into Syria, and came to Tyre: for there the ship was to discharge her load.\n"
	"And finding Disciples, we tarried there seven days: who said to Paul by the Spirit, that he should not go up to Jerusalem.\n"
	"And the days being expired, departing we went forward, all bringing us on the way, with their wives and children, till we were out of the city: and falling upon our knees on the shore, we prayed.\n"
	"And when we had bid one another farewell, we went up into the ship; and they returned unto their own.\n"
	"But we having ended the navigation, from Tyre came down to Ptolomais: and saluting the brethren, we tarried one day with them.\n"
	"And the next day departing, we came to Caesarea. And entering into the house of Philip the Evangelist, who was one of the seven, we tarried with him.\n"
	"And he had four daughters^ virgins, that did prophesy.\n"
	"And as we abode there for certain days, there came a certain Prophet from Jewry, named Agabus.\n"
	"He, when he was come to us, took Paul's girdle: and binding his own feet & hands, he said: Thus saith the Holy Ghost: The man whose girdle this is, so shall the Jews bind in Jerusalem, and shall deliver him into the hands of the Gentiles.\n"
	"Which when we had heard, we and they that were of the same place, desired him that he would not go up to Jerusalem.\n"
	"Then Paul answered, and said: What do you, weeping and afflicting my heart? for I am ready not only to be bound, but to die also in Jerusalem for the name of our Lord JESUS.\n"
	"And when we could not persuade him, we ceased, saying: The will of our Lord be done.\n"
	"And after these days, being prepared, we went up to Jerusalem.\n"
	"And there came also of the Disciples from Caesarea with us, bringing with them one Jason a Cyprian (with whom we should lodge) an old Disciple.\n"
	"And when we were come to Jerusalem, the brethren received us gladly.\n"
	"And the day following Paul went in with us to James, and all the Ancients were assembled.\n"
	"Whom when he had saluted, he told particularly what God had done among the Gentiles by his ministry.\n"
	"But they hearing it, magnified God, and said to him: Thou seest (brother) how many thousands there are among the Jews that have believed: and all are zelatours of the Law.\n"
	"But they have heard of thee that thou doest teach those Jews that are among the Gentiles, to depart from Moyses: saying that they ought not to circumcise their children, nor walk according to the custom.\n"
	"What is it then? needs must the multitude assemble: for they will hear that thou art come.\n"
	"Do this therefore which we tell thee. There are with us four men, that have a vow on them.\n"
	"Taking these unto thee, sanctify thyself with them; and bestow on them, that they may shave their heads: and all shall know that the things which they heard of thee, are false: but that thyself also walkest keeping the Law.\n"
	"But concerning them that believe of the Gentiles, we have written, decreeing that they should refrain themselves from the immolated to idols, and blood, and suffocated, and fornication.\n"
	"Then Paul taking the men unto him, the next day being purified with them entered into the temple, shewing the accomplishment of the days of the purification, until an oblation was offered for every one of them.\n"
	"But whiles the seven days were a finishing, those Jews that were of Asia, when they had seen him in the temple, stirred up all the people, and laid hands upon him,\n"
	"crying: Ye men of Israel, help: this is the man that against the people and the Law and this place teaching all men every-where, hath also moreover brought in Gentiles into the temple, and hath violated this holy place.\n"
	"(For they had seen Trophimus the Ephesian in the city with him, whom they supposed that Paul had brought into the temple.)\n"
	"And the whole city was in an uproar: and there was made a concourse of the people. And apprehending Paul, they drew him forth of the temple: and immediately the doors were shut.\n"
	"And as they sought to kill him, it was told the Tribune of the band, That all Jerusalem is in a confusion.\n"
	"Who forthwith taking unto him soldiers and Centurions, ran down to them. Who, when they had seen the Tribune and the soldiers, ceased to strike Paul.\n"
	"Then the Tribune coming near apprehended him, and commanded him to be bound with two chains: and he demanded who he was, and what he had done.\n"
	"And some cried one thing, some another, in the multitude. And whereas he could not know the certainty for the tumult, he commanded him to be led into the castle.\n"
	"And when he was come to the stairs, it chanced that he was carried of the soldiers because of the violence of the people.\n"
	"For the multitude of the people followed, crying: Away with him.\n"
	"And when Paul began to be brought into the castle, he saith to the Tribune: is it lawful for me to speak something to thee? Who said: Canst thou speak Greek?\n"
	"Art not thou the Aegyptian that before these days did raise a tumult, and didst lead forth into the desert four thousand men that were murderers?\n"
	"And Paul said to him: I am a man truly a Jew of Tarsus, a citizen not of an obscure city of Cilicia. And I desire thee, permit me to speak to the people.\n"
	"And when he had permitted him, Paul standing on the stairs, beckoned with his hand to the people. And great silence being made, he spake unto them in the Hebrew tongue, saying.";