const char* chap1187 = "AND after five days^ the high priest Ananias descended, with certain ancients and one Tertullus an orator, who went to the President against Paul.\n"
	"And Paul being cited, Tertullus began to accuse, saying: Whereas we live in much peace by thee, & many things are corrected by thy providence,\n"
	"we do always & in all places receive it, most excellent Felix, with all thanks-giving.\n"
	"But lest I hinder thee any longer, I desire thee of thy clemency briefly to hear us.\n"
	"We have found this man pestiferous, & raising seditions to all the Jews in the whole world, and author of the sedition of the sect of the Nazarenes.\n"
	"Who also hath attempted to violate the temple, whom also being apprehended we would have judged according to our law.\n"
	"But Lysias the Tribune coming in, with great force took him away out of our hands,\n"
	"commanding his accusers to come to thee, of whom thou mayest thyself judging, understand of all these things, whereof we accuse him.\n"
	"And the Jews also added, saying that these things were so.\n"
	"But Paul answered: (the President making a sign unto him for to speak) Knowing that of many years thou art judge over this nation, I will with good courage answer for myself.\n"
	"For thou mayest understand that it is not above twelve days to me, since I went up to adore in Jerusalem.\n"
	"And neither in the temple did they find me disputing with any man, or causing concourse of the multitude, neither in the synagogues, nor in the city:\n"
	"neither can they prove unto thee the things whereof they now accuse me.\n"
	"But this I confess to thee, that according to the sect, which they call heresy, I do so serve the Father my God, believing all things that are written in the Law & the Prophets:\n"
	"having hope in God, the which these also themselves expect, that there shall be a resurrection of just and unjust.\n"
	"In this myself also do study to have a conscience without offence toward God and toward men always.\n"
	"And after many years^ I came to bestow alms upon my nation, & oblations, and vows.\n"
	"In the which they found me purified in the temple: not with multitude nor with tumult.\n"
	"But certain Jews of Asia, who ought to be present before thee and to accuse, if they had any thing against me:\n"
	"or let these men themselves say, if they have found in me any iniquity, forasmuch as I stand in the Council,\n"
	"but of this one voice only that I cried standing among them, That of the resurrection of the dead am I judged this day of you.\n"
	"And Felix deferred them, knowing most certainly of this way, saying: When Lysias the Tribune is come down, I will hear you.\n"
	"And he commanded the Centurion to keep him, and that he should have rest, neither to prohibit any of his to minister unto him.\n"
	"And after some days, Felix coming with Drusilla his wife, which was a Jew, called Paul, and heard of him the faith that is in Christ JESUS.\n"
	"And he disputing of justice and chastity, and of the judgement to come, Felix being terrified, answered: For this time, go thy way: but in time convenient I will send for thee.\n"
	"hoping also withal, that money would be given him of Paul; for the which cause also oftentimes sending for him, he spake with him.\n"
	"But when two years were ended, Felix had a Successor Portius Festus. And Felix being willing to shew the Jews a pleasure, left Paul in prison.";