const char* chap1197 = "WHAT shall we say then? Shall we continue in sin that grace may abound?\n"
	"God forbid. For we that are dead to sin, how shall we yet live therein?\n"
	"Are you ignorant that all we which are baptized in Christ JESUS, in his death we are baptized?\n"
	"For we are buried together with him by Baptism into death: that as Christ is risen from the dead by the glory of the Father, so we also may walk in newness of life.\n"
	"For if we be become complanted to the similitude of his death, we shall be also of his resurrection.\n"
	"Knowing this, that our old man is crucified with him, that the body of sin may be destroyed, to the end that we may serve sin no longer.\n"
	"For he that is dead, is justified from sin.\n"
	"And if we be dead with Christ, we believe that we shall live also together with Christ.\n"
	"Knowing that Christ rising again from the dead, now dieth no more, death shall no more have dominion over him.\n"
	"For that he died, to sin he died once: but that he liveth, he liveth to God.\n"
	"So think you also, that you are dead to sin, but alive to God in Christ JESUS our Lord.\n"
	"Let not sin therefore reign in your mortal body, that you obey the concupiscences thereof.\n"
	"But neither do ye exhibit your members instruments of iniquity unto sin: but exhibit yourselves to God as of dead men, alive; and your members instruments of justice to God.\n"
	"For sin shall not have dominion over you. For you are not under the Law, but under grace.\n"
	"What then? shall we sin, because we are not under the Law, but under grace? God forbid.\n"
	"Know you not that to whom you exhibit yourselves servants to obey, you are the servants of him whom you obey, whether it be of sin, to death, or of obedience, to justice.\n"
	"But thanks be to God, that you were the servants of sin, but have obeyed from the heart, unto that form of doctrine, into the which you have been delivered.\n"
	"And being made free from sin, you were made servants to justice.\n"
	"I speak an human thing, because of the infirmity of your flesh. For as you have exhibited your members to serve uncleanness and iniquity, unto iniquity; so now exhibit your members to serve justice, unto sanctification.\n"
	"For when you were servants of sin, you were free to justice.\n"
	"What fruit therefore had you then in those things, for which now you are ashamed? For the end of them is death.\n"
	"But now being made free from sin, and become servants to God, you have your fruit unto sanctification, but the end, life everlasting.\n"
	"For the stipends of sin, death. But the grace of God, life everlasting in Christ JESUS our Lord.";