const char* chap1203 = "I BESEECH you therefore, brethren, by the mercy of God, that you exhibit your bodies a living host, holy, pleasing to God, your reasonable service.\n"
	"And be not conformed to this world; but be reformed in the newness of your mind, that you may prove what the good, & acceptable, & perfect will of God is.\n"
	"For I say by the grace that is given me, to all that are among you, not to be more wise than behoveth to be wise, but to be wise unto sobriety, to every one as God hath divided the measure of faith.\n"
	"For as in one body we have many members, but all the members have not one action;\n"
	"so we being many, are one body in Christ, & each one another's members.\n"
	"And having gifts, according to the grace that is given us, different, either prophecy according to the rule of faith,\n"
	"or ministry in ministering, or he that teacheth in doctrine,\n"
	"he that exhorteth in exhorting, he that giveth in simplicity, he that ruleth in carefulness, he that sheweth mercy in cheerfulness.\n"
	"Love without simulation. Hating evil, cleaving to good.\n"
	"Loving the charity of the brotherhood one toward another, with honour preventing one another.\n"
	"In carefulness not slothful. In spirit fervent. Serving our Lord.\n"
	"Rejoicing in hope. Patient in tribulation. Instant in prayer.\n"
	"Communicating to the necessities of the saints. Pursuing hospitality.\n"
	"Bless them that persecute you: bless, and curse not.\n"
	"To rejoice with them that rejoice, to weep with them that weep.\n"
	"Being of one mind one toward another. Not minding high things, but consenting to the humble. Be not wise in your own conceit.\n"
	"To no man rendering evil for evil. Providing good things not only before God, but also before all men.\n"
	"If it may be, as much as is in you, having peace with all men.\n"
	"Not revenging yourselves, my dearest, but give place unto wrath, for it is written: Revenge to me; I will reward, saith our Lord.\n"
	"but if thine enemy hunger, give him meat: if he thirst, give him drink. For, doing this, thou shalt heap coals of fire upon his head.\n"
	"Be not overcome of evil, but overcome in good the evil.";