const char* chap1208 = "PAUL called to be an Apostle of JESUS Christ, by the will of God, and Sosthenes a brother,\n"
	"to the Church of God that is at Corinth, to the sanctified in Christ JESUS, called to be saints, with all that invocate the name of our Lord JESUS Christ in every place of theirs and ours.\n"
	"Grace to you and peace from God our Father and our Lord JESUS Christ.\n"
	"I give thanks to my God always for you for the grace of God that is given you in Christ JESUS,\n"
	"that in all things you be made rich in him, in all utterance, and in all knowledge,\n"
	"(as the testimony of Christ is confirmed in you,)\n"
	"so that nothing is wanting to you in any grace, expecting the revelation of our Lord JESUS Christ,\n"
	"who also will confirm you unto the end without crime, in the day of the coming of our Lord JESUS Christ.\n"
	"God is faithful; by whom you are called into the society of his Son JESUS Christ our Lord.\n"
	"And I beseech you, brethren, by the name of our Lord JESUS Christ, that you all say one thing, and that there be no schisms among you: but that you be perfect in one sense, & in one knowledge.\n"
	"For it is signified unto me (my brethren) of you, by them that are of Chloe, that there be contentions among you.\n"
	"And I mean this, for that every one of you saith, I certes am Paul's, & I^ Apollo's, but I^ Cephas', and I^ Christ's.\n"
	"Is Christ divided? Why, was Paul crucified for you? or in the name of Paul were you baptized?\n"
	"I give God thanks, that I baptized none of you, but Crispus and Caius:\n"
	"lest any man say that in my name you were baptized.\n"
	"And I baptized also the house of Stephanas. But I know not if I have baptized any other.\n"
	"For Christ sent me not to baptize, but to evangelize: not in wisdom of speech, that the cross of Christ be not made void.\n"
	"For the word of the cross, to them indeed that perish, is foolishness; but to them that are saved, that is, to us, it is the power of God.\n"
	"For it is written: I will destroy the wisdom of the wise; and the prudence of the prudent I will reject.\n"
	"where is the wise? where is the Scribe? where is the disputer of this world? Hath not God made the wisdom of this world foolish?\n"
	"For because in the wisdom of God the world did not by wisdom know God; it pleased God by the foolishness of the preaching to save them that believe.\n"
	"For both the Jews ask signs, and the Greeks seek wisdom:\n"
	"but we preach Christ crucified, to the Jews certes a scandal, and to the Gentiles, foolishness:\n"
	"but to the called^ Jews & Greeks, Christ the power of God and the wisdom of God.\n"
	"For that which is the foolish of God, is wiser than men; and that which is the infirm of God, is stronger than men.\n"
	"For see your vocation brethren, that not many wise according to the flesh, not many mighty, not many noble:\n"
	"but the foolish things of the world hath God chosen, that he may confound the wise; and the weak things of the world hath God chosen, that he may confound the strong:\n"
	"and the base things of the world and the contemptible hath God chosen, and those things which are not, that he might destroy those things which are;\n"
	"that no flesh may glory in his sight.\n"
	"And of him you are in Christ JESUS, who is made unto us wisdom from God, & justice, & sanctification, and redemption:\n"
	"that as it is written: He that doth glory, may glory in our Lord.";