const char* chap121 = "And our Lord spake to Moyses and Aaron, saying:\n"
	"Take the sum of the sons of Caath out of the midst of the Levites, by their houses and families,\n"
	"from the thirtieth year and upward, unto the fiftieth year, of all that go in to stand and to minister in the tabernacle of covenant.\n"
	"This is the service of the sons of Caath:\n"
	"when the camps remove, Aaron and his sons shall enter into the tabernacle of covenant, and Sanctum Sanctorum, and shall take down the veil that hangeth before the door, and shall wrap in it the ark of testimony,\n"
	"and shall cover it again with a cover of Ianthine skins, and shall spread over it a cloth all of hyacinth, and shall draw in the bars.\n"
	"The table also of proposition they shall wrap in a cloth of hyacinth, and shall put with it the censers and little mortars, the goblets and cups to pour the libaments: the breads shall be always on it:\n"
	"and they shall spread over it a cloth of scarlet, which again they shall cover with a veil of ianthine skins, and shall put in the bars.\n"
	"They shall take also a cloth of hyacinth wherewith they shall cover the candlestick with the lamps and tongs thereof and snuffers and all the vessels of oil, which are necessary for the dressing of the lamps:\n"
	"and over all they shall put a cover of ianthine skins, and put in the bars.\n"
	"Moreover the golden altar also they shall wrap in a cloth of hyacinth, and shall spread over it a cover of ianthine skins, and put in the bars.\n"
	"All the vessels wherewith the ministration is done in the Sanctuary, they shall wrap in a cloth of hyacinth and shall spread over it a cover of ianthine skins, and put in bars.\n"
	"But the altar also they shall make clean from the ashes, & shall wrap it in a purple cloth,\n"
	"and shall put with it all the vessels, that they use in the ministry thereof, that is to say, fire pans, flesh hooks & forks, pot-hooks and shovels. All the vessels of the altar together they shall cover with a veil of ianthine skins, and shall put in the bars.\n"
	"And when Aaron and his sons have wrapped up the Sanctuary & the vessels thereof in the removing of the camp, then shall the sons of Caath enter in to carry the things wrapped up: and they shall not touch the vessels of the Sanctuary, lest they die. These are the burdens of the sons of Caath in the tabernacle of covenant:\n"
	"over whom shall be Eleazar the son of Aaron the Priest, to whose charge pertaineth the oil to dress the lamps, and the incense of composition, and the sacrifice, that is always offered, and the oil of unction, and whatsoever pertaineth to the service of the tabernacle, and of all the vessels, that are in the Sanctuary.\n"
	"And our Lord spake unto Moyses and Aaron, saying:\n"
	"Destroy not the people of Caath out of the midst of the Levites:\n"
	"but do this to them, that they may live, and not die, if they touch Sancta Sanctorum. Aaron and his sons shall enter, and they shall dispose the charges of every one, and shall divide what every one must carry.\n"
	"Let others by no curiosity see the things that are in the Sanctuary before they be wrapped up, otherwise they shall die.\n"
	"And our Lord spake to Moyses, saying:\n"
	"Take the sum of the sons of Gerson also by their houses and families & kindreds,\n"
	"from thirty years & upward, unto fifty years. Number them all that go in & minister in the tabernacle of covenant.\n"
	"This is the office of the family of the Gersonites,\n"
	"for to carry the curtains of the tabernacle, & the roof of the covenant the other cover, and over all the ianthine cover, and the hanging that hangeth in the entry of the tabernacle of covenant,\n"
	"the curtains of the court, and the veil in the entry that is before the tabernacle. All things that pertain to the altar, the cords, and vessels of the ministry,\n"
	"shall the sons of Gerson carry, by the commandment of Aaron and his sons: and every one shall know to what burden they must be assigned.\n"
	"This is the service of the family of the Gersonites in the tabernacle of covenant, and they shall be under the hand of Ithamar the son of Aaron the Priest.\n"
	"The sons of Merari also by the families and houses of their fathers thou shalt reckon,\n"
	"from thirty years and upward, until fifty years, all that enter in to the office of their ministry, & to the service of the covenant of testimony.\n"
	"These are their burdens: They shall carry the boards of the tabernacle and the bars thereof, the pillars and the feet of them,\n"
	"the pillars also of the court round about, with their feet and pins and cords. All the vessels and implements they shall receive by account, and so shall carry them.\n"
	"This is the office of the family of the Merarites, and their ministry in the tabernacle of covenant: and they shall be under the hand of Ithamar the son of Aaron the Priest.\n"
	"Moyses therefore and Aaron and the Princes of the synagogue reckoned the sons of Caath, by their kindreds and houses of their fathers,\n"
	"from thirty years and upward, unto the fiftieth year, all that enter in to the ministry of the tabernacle of covenant:\n"
	"and they were found two thousand seven hundred fifty.\n"
	"This is the number of the people of Caath that enter into the tabernacle of covenant: these did Moyses and Aaron number according to the word of our Lord by the hand of Moyses.\n"
	"The sons of Gerson also were numbered by the kindreds and houses of their fathers,\n"
	"from thirty years and upward, unto the fiftieth year, all that enter in to minister in the tabernacle of covenant:\n"
	"and they were found two thousand six hundred thirty.\n"
	"This is the people of the Gersonites, whom Moyses and Aaron numbered according to the word of our Lord.\n"
	"The sons of Merari also were numbered by the kindreds & houses of their fathers,\n"
	"from thirty years and upward, unto the fiftieth year, all that enter in to accomplish the rites of the tabernacle of covenant:\n"
	"and they were found three thousand two hundred.\n"
	"this is the number of the sons of Merari, whom Moyses and Aaron reckoned according to the commandment of our Lord by the hand of Moyses.\n"
	"All that were reckoned of the Levites, and whom Moyses and Aaron and the Princes of Israel took by name, by the kindreds and houses of their fathers,\n"
	"from thirty years and upward, unto the fiftieth year, entering in to the ministry of the tabernacle, and to carry the burden,\n"
	"were in all eight thousand five hundred eighty.\n"
	"According to the word of our Lord did Moyses reckon them, every one according to their office and burdens, as our Lord had commanded him.";