const char* chap1212 = "THERE is plainly heard fornication among you, and such fornication, as the like is not among the heathen, so that one hath his father's wife.\n"
	"And you are puffed up; and have not mourned rather, that he might be taken away from among you, that hath done this deed.\n"
	"I indeed absent in body, but present in spirit, have already judged, as present, him that hath so done,\n"
	"in the name of our Lord JESUS Christ, you being gathered together and my spirit, with the virtue of our Lord JESUS;\n"
	"to deliver such an one to Satan for the destruction of the flesh, that the spirit may be saved in the day of our Lord JESUS Christ.\n"
	"Your glorying is not good. Know you not that a little leaven corrupteth the whole paste?\n"
	"Purge the old leaven, that you may be a new paste, as you are azymes. For our Pasch, Christ, is immolated.\n"
	"Therefore let us feast, not in the old leaven, nor in the leaven of malice and wickedness, but in the azymes of sincerity and verity.\n"
	"I wrote to you in an epistle, not to keep company with fornicators.\n"
	"I mean not the fornicators of this world, or the covetous, or the extortioners, or servers of idols: otherwise you should have gone out of this world.\n"
	"But now I wrote to you, not to keep company, if he that is named a brother, be a fornicator, or a covetous person, or a server of idols, or a railer, or a drunkard, or an extortioner: with such an one not so much as to take meat.\n"
	"For what is it to me to judge of them that are without? Do not you judge of them that are within?\n"
	"for them that are without, God will judge. Take away the evil one from among yourselves.";