const char* chap1213 = "DARE any of you having a matter against another, to be judged before the unjust, & not before the saints?\n"
	"Or know you not that the saints shall judge of the world? And if the world shall be judged by you: are you unworthy to judge of the least things?\n"
	"Know you not that we shall judge Angels? how much more secular things?\n"
	"If therefore you have secular judgements; the contemptible that are in the Church, set them to judge.\n"
	"I speak to your shame. So is there not among you any wise man, that can judge between his brother?\n"
	"But brother with brother contendeth in judgement: & that before infidels?\n"
	"Now certes there is plainly a fault in you, that you have judgements among you. Why do you not rather take wrong? why do you not rather suffer fraud?\n"
	"But yourselves do wrong and defraud: and that to the brethren.\n"
	"Know you not that the unjust shall not possess the Kingdom of God? Do not err: Neither fornicators, nor servers of idols, nor adulterers, nor the effeminate, nor the liers with mankind,\n"
	"nor thieves, nor the covetous, nor drunkards, nor railers, nor extortioners shall possess the Kingdom of God.\n"
	"And these things certes you were, but you are washed, but you are sanctified, but you are justified in the name of our Lord JESUS Christ, and in the Spirit of our God.\n"
	"All things are lawful for me, but all things are not expedient. All things are lawful for me, but I will be brought under the power of none.\n"
	"The meat to the belly, & the belly to the meats: but God will destroy both it and them: and the body not to fornication, but to our Lord, & our Lord to the body.\n"
	"But God both hath raised up our Lord, and will raise up us also by his power.\n"
	"Know you not that your bodies are the members of Christ? Taking therefore the members of Christ, shall I make them the members of an harlot? God forbid.\n"
	"Or know you not, that he which cleaveth to an harlot, is made one body? For they shall be, saith he, two in one flesh.\n"
	"But he that cleaveth to our Lord, is one spirit.\n"
	"Fly fornication. Every sin whatsoever a man doeth is without the body: but he that doeth fornicate, sinneth against his own body.\n"
	"Or know you not that your members are the temple of the Holy Ghost which is in you, whom you have of God, and you are not your own?\n"
	"For you are bought with a great price. Glorify and bear God in your body.";