const char* chap122 = "And our Lord spake to Moyses, saying:\n"
	"Command the children of Israel, that they cast out of the camp every leper, and whosoever hath a flux of seed, & is polluted upon the dead:\n"
	"as well man as woman cast ye out of the camp, lest when they shall dwell with you, they contaminate it.\n"
	"And the children of Israel did so, and they did cast them forth without the camp, as our Lord had spoken to Moyses.\n"
	"And our Lord spake to Moyses, saying:\n"
	"Speak to the children of Israel: man, or woman, when they shall do any of all the sins, that are wont to chance to men, and by negligence have transgressed the commandment of the Lord, and have offended,\n"
	"they shall confess their sins, & restore the principal itself, & the fifth part over to him, against whom they sinned.\n"
	"But if there be none to receive it, they shall give it to the Lord, and it shall be the Priest's, the ram excepted, that is offered for expiation, to be a placable host.\n"
	"All the first fruits also, which the children of Israel do offer, pertain to the Priest:\n"
	"and whatsoever is offered into the Sanctuary of every one, and is delivered to the hands of the Priest, it shall be his.\n"
	"And our Lord spake to Moyses, saying:\n"
	"Speak to the children of Israel, and thou shalt say to them: The man, whose wife erreth, and contemning her husband,\n"
	"hath slept with another man, and her husband could not find it, but the adultery is secret, and cannot be proved by witnesses, because she was not found in the adulterous fact:\n"
	"if the spirit of jealousy stir up the husband against his wife, which either is polluted or is charged with false suspicion,\n"
	"he shall bring her to the Priest, and shall offer an oblation for her, the tenth part of a satum of barley meal: he shall not pour oil thereon, nor put frankincense upon it: because it is a sacrifice of jealousy, and an oblation searching out adultery.\n"
	"The Priest therefore shall offer it, & set it before the Lord.\n"
	"And he shall take holy water in an earthen vessel, and he shall cast a little gravel of the pavement of the tabernacle into it.\n"
	"And when the woman shall stand in the sight of the Lord, he shall uncover her head, and shall put upon her hands the sacrifice of recordation, and the oblation of jealousy: and himself shall hold the most bitter waters, whereon he heaped curses with execration,\n"
	"and he shall adjure her, and shall say: If another man hath not slept with thee, and if thou be not polluted by forsaking thy husband's bed, these most bitter waters shall not hurt thee, whereupon I have heaped curses.\n"
	"But if thou hast declined from thy husband, & art polluted, and hast lien with another man,\n"
	"thou shalt be subject to these maledictions: Our Lord give thee for a malediction, and an example of all among his people: make he thy thigh to rot, and belly swelling burst asunder.\n"
	"The cursed water enter into thy belly, and thy womb being swollen let thy thigh rot. And the woman shall answer, Amen, amen.\n"
	"And the Priest shall write these curses in a book, and shall wash them out with the most bitter waters, whereupon he heaped the curses,\n"
	"and he shall give them her to drink. Which when she hath drunk up,\n"
	"the Priest shall take of her hand the sacrifice of jealousy, and shall elevate it before the Lord, and shall put it upon the altar: yet so notwithstanding that first\n"
	"he take a handful of the sacrifice of that which is offered, & burn it upon the altar: and so give the most bitter waters to the woman to drink.\n"
	"Which when she hath drunk, if she be polluted, and by contempt of her husband guilty of adultery, the waters of malediction shall go through her, and her belly being puft up her thigh shall rot withal: and the woman shall be for a malediction, and an example to all the people.\n"
	"But if she be not polluted, she shall be blameless, and shall bear children.\n"
	"This is the law of jealousy. If the woman decline from her husband, and if she be polluted,\n"
	"and the husband stirred with the spirit of jealousy brought her in the sight of the Lord, and the Priest have done to her according to all things that are written:\n"
	"the husband shall be without fault, and she shall bear her iniquity.";