const char* chap1220 = "IF I speak with the tongues of men, and of Angels, and have not charity, I am become as sounding brass, or a tinkling cymbal.\n"
	"And if I should have prophecy, and knew all mysteries, and all knowledge, & if I should have all faith so that I could remove mountains, and have not charity, I am nothing.\n"
	"And if I should distribute all my goods to be meat for the poor, and if I should deliver my body so that I burn, and have not charity, it doth profit me nothing.\n"
	"Charity is patient, is benign: Charity envieth not, dealeth not perversely: is not puffed up,\n"
	"is not ambitious, seeketh not her own, is not provoked to anger, thinketh not evil,\n"
	"rejoiceth not upon iniquity, but rejoiceth with the truth:\n"
	"suffereth all things, believeth all things, hopeth all things, beareth all things.\n"
	"Charity never falleth away: whether prophecies shall be made void, or tongues shall cease, or knowledge shall be destroyed.\n"
	"For in part we know, & in part we prophesy.\n"
	"But when that shall come that is perfect, that shall be made void that is in part.\n"
	"When I was a little one, I spake as a little one, I understood as a little one, I thought as a little one. But when I was made a man, I did away the things that belonged to a little one.\n"
	"We see now by a glass in a dark sort: but then face to face. Now I know in part: but then I shall know as also I am known.\n"
	"And now there remain, faith, hope, charity, these three: but the greater of these is charity.";