const char* chap1221 = "FOLLOW Charity, earnestly pursue spiritual things: but rather that you may prophesy.\n"
	"For he that speaketh with tongues speaketh not to men, but to God: for no man heareth. But in spirit he speaketh mysteries.\n"
	"For he that prophesieth, speaketh to men unto edification, & exhortation, & consolation.\n"
	"He that speaketh with tongues, edifieth himself; but he that prophesieth, edifieth the Church.\n"
	"And I would have you all to speak with tongues, but rather to prophesy. For greater is he that prophesieth, than he that speaketh with tongues: unless perhaps he interpret, that the Church may take edification.\n"
	"But now, brethren; if I come to you speaking with tongues, what shall I profit you, unless I speak to you either in revelation, or in knowledge, or in prophecy, or in doctrine?\n"
	"Yet the things without life that give a sound, be it pipe or harp, unless they give a distinction of sounds, how shall that be known which is piped, or which is harped?\n"
	"For if the trumpet give an uncertain voice, who shall prepare himself to battle?\n"
	"So you also by a tongue unless you utter manifest speech, how shall that be known that is said? for you shall be speaking into the air.\n"
	"There are (for example) so many kinds of tongues in this world, & none is without voice.\n"
	"If then I know not the virtue of the voice, I shall be to him to whom I speak, barbarous; and he that speaketh barbarous to me.\n"
	"So you also, because you be emulators of spirits: seek to abound unto the edifying of the Church.\n"
	"And therefore he that speaketh with the tongue, let him pray that he may interpret.\n"
	"For if I pray with the tongue, my spirit prayeth, but my understanding is without fruit.\n"
	"What is it then? I will pray in the spirit, I will pray also in the understanding: I will sing in the spirit, I will sing also in the understanding.\n"
	"But if thou bless in the spirit, he that supplieth the place of the vulgar how shall he say, Amen, upon thy blessing? because he knoweth not what thou sayest.\n"
	"For thou indeed givest thanks well, but the other is not edified.\n"
	"I give my God thanks, that I speak with the tongue of you all.\n"
	"But in the Church I will speak five words with my understanding that I may instruct others also; rather than ten thousand words in a tongue.\n"
	"Brethren, be not made children in sense, but in malice be children, and in sense be perfect.\n"
	"In the Law it is written: That in other tongues and other lips I will speak to this people: and neither so will they hear me, saith our Lord.\n"
	"Therefore languages are for a sign not to the faithful, but to infidels: but prophecies, not to infidels, but to the faithful.\n"
	"If therefore the whole Church come together in one, and all speak with tongues, and there enter in vulgar persons or infidels, will they not say that you be mad?\n"
	"But if all prophesy, and there enter in any infidel or vulgar person, he is convinced of all, he is judged of all.\n"
	"the secrets of his heart are made manifest, and so falling on his face he will adore God, pronouncing that God is in you indeed.\n"
	"What is it then, brethren? when you come together, every one of you hath a psalm, hath a doctrine, hath a revelation, hath a tongue, hath an interpretation: let all things be done to edification.\n"
	"Whether a man speak with tongue, by two, or at the most by three, and in course, and let one interpret.\n"
	"But if there be not an interpreter, let him hold his peace in the Church, and speak to himself and to God.\n"
	"And let Prophets speak two or three, and let the rest judge.\n"
	"But if it be revealed to another sitting, let the first hold his peace.\n"
	"For you may all prophesy one by one: that all may learn, and all may be exhorted:\n"
	"and the spirits of prophets are subject to prophets.\n"
	"For God is not the God of dissension, but of peace: as also in all the Churches of the saints I teach.\n"
	"Let women hold their peace in the Churches: for it is not permitted them to speak, but to be subject, as also the Law saith.\n"
	"But if they list learn any thing, let them ask their own husbands at home. For it is a foul thing for a woman to speak in the Church.\n"
	"Or did the word of God proceed from you? came it unto you only?\n"
	"If any man seem to be a Prophet, or spiritual, let him know the things that I write to you, that they are the commandments of our Lord.\n"
	"But if any man know not, he shall not be known.\n"
	"Therefore, brethren, be earnest to prophesy: and to speak with tongues prohibit not.\n"
	"But let all things be done honestly and according to order among you.";