const char* chap1224 = "PAUL an Apostle of JESUS Christ by the will of God, and Timothee our brother: to the Church of God that is at Corinth, with all the saints that are in all Achaia.\n"
	"Grace unto you and peace from God our Father, & from our Lord JESUS Christ.\n"
	"Blessed be the God and Father of our Lord JESUS Christ, the Father of mercies and God of all comfort,\n"
	"who comforteth us in all our tribulation; that we also may be able to comfort them that are in all distress, by the exhortation wherewith we also are exhorted of God.\n"
	"For as the passions of Christ abound in us: so also by Christ doth our comfort abound.\n"
	"And whether we be in tribulation, for your exhortation & salvation: whether we be exhorted, for your exhortation & salvation, which worketh the toleration of the same passions which we also do suffer:\n"
	"and our hope is firm for you: knowing that as you are partakers of the passions, so shall you be of the consolation also.\n"
	"For we will not have you ignorant, brethren, concerning our tribulation, which happened in Asia, that we were pressed above measure above our power, so that it was tedious unto us even to live.\n"
	"But we in ourselves, had the answer of death, that we be not trusting in ourselves, but in God who raiseth up the dead,\n"
	"who hath delivered and doth deliver us out of so great dangers: in whom we hope that he will yet also deliver us,\n"
	"you helping withal in prayer for us, that by many men's persons, thanks for that gift which is in us, may be given by many in our behalf.\n"
	"For our glory is this, the testimony of our conscience, that in simplicity and sincerity of God, and not in carnal wisdom, but in the grace of God we have conversed in this world: and more aboundantly towards you.\n"
	"For we write no other things to you than that you have read and know. And I hope that you shall know unto the end:\n"
	"as also you have known us in part, that we are your glory, as you also ours in the day of our Lord JESUS Christ.\n"
	"And in this confidence I would first have come to you, that you might have a second grace:\n"
	"and by you pass into Macedonia, and again from Macedonia come to you, and of you be brought on my way into Jewry.\n"
	"Whereas then I was thus minded, did I use lightness? Or the things that I mind, do I mind according to the flesh, that there be with me, It is and It is not?\n"
	"But God is faithful, because our preaching which was to you, there is not in it, It is, and, It is not.\n"
	"For the Son of God JESUS Christ, who by us was preached among you, by me and Sylvanus and Timothee, was not, It is, and, It is not, but, It is, was in him.\n"
	"For all the promises of God that are, in him It is: therefore also by him, Amen to God, unto our glory.\n"
	"And he that confirmeth us with you in Christ, and that hath anointed us, God:\n"
	"who also hath sealed us, and given the pledge of the Spirit in our hearts.\n"
	"And I call God to witness upon my soul, that sparing you, I came not any more to Corinth, not because we over-rule your faith: but, we are helpers of your joy. For in the faith you stand.";