const char* chap1225 = "AND I have determined with my-self this same thing, not to come to you again in sorrow.\n"
	"For if I make you sorry; & who is it that can make me glad, but he that is made sorry by me?\n"
	"And this same I wrote to you; that I may not, when I come, have sorrow upon sorrow, of the which I ought to rejoice: trusting in you all, that my joy is the joy of you all.\n"
	"For of much tribulation and anguish of heart I wrote to you by many tears: not that you should be made sorry; but that you may know what charity I have more aboundantly toward you.\n"
	"And if any man hath made sorrowful, not me hath he made sorrowful, but in part, that I burden not all you.\n"
	"To him that is such a one, this rebuke sufficeth that is given of many:\n"
	"so that contrarywise you should rather pardon and comfort him, lest perhaps such an one be swallowed up with over great sorrow.\n"
	"For the which cause I beseech you that you confirm charity toward him.\n"
	"For therefore also have I written that I may know the experiment of you, whether in all things you be obedient.\n"
	"And whom you have pardoned any thing, I also. For, myself also that which I pardoned, if I pardoned any thing, for you in the person of Christ,\n"
	"that we be not circumvented of Satan. For we are not ignorant of his cogitations.\n"
	"And when I was come to Troas for the Gospel of Christ, and a door was opened unto me in our Lord,\n"
	"I had no rest in my spirit, for that I found not Titus my brother, but bidding them fare well, I went forth into Macedonia.\n"
	"And thanks be to God, who always triumpheth us in Christ JESUS, and manifesteth the odour of his knowledge by us in every place.\n"
	"For we are the good odour of Christ unto God in them that are saved, & in them that perish.\n"
	"To some indeed the odour of death unto death: but to others the odour of life unto life. And to these things who is so sufficient?\n"
	"For we are not as very many, adulterating the word of God, but of sincerity, and as of God, before God, in Christ we speak.";