const char* chap1226 = "BEGIN we again to commend our-selves? or do we need (as certain) epistles of commendation to you, of from you?\n"
	"Our epistle you are, written in our hearts, which is known & read of all men:\n"
	"being manifested that you are the epistle of Christ, ministered by us, & written not with ink, but with the Spirit of the living God: not in tables of stone, but in the tables carnal of the heart.\n"
	"And such confidence we have by Christ to God:\n"
	"not that we be sufficient to think any thing of our-selves, as of our-selves: but our sufficiency is of God.\n"
	"Who also hath made us meet ministers of the new testament: not in the letter, but in the Spirit. For the letter killeth: but the Spirit quickeneth.\n"
	"And if the ministration of death with letters figured in stones, was in glory, so that the children of Israel could not behold the face of Moyses for the glory of his countenance, that is made void;\n"
	"how shall not the ministration of the Spirit be more in glory?\n"
	"For if the ministration of damnation be in glory, much more the ministry of justice aboundeth in glory.\n"
	"For neither was it glorified, which in this part was glorious, by reason of the excelling glory.\n"
	"For if that which is made void, is by glory: much more that which abideth, is in glory.\n"
	"Having therefore such hope, we use much confidence:\n"
	"and not as Moyses put a veil upon his face, that the children of Israel might not behold his face, which is made void.\n"
	"but their senses were dulled. For until this present day, the self-same veil in the lecture of the old testament remaineth unrevealed (because in Christ it is made void)\n"
	"but until this present day, when Moyses is read, a veil is put upon their heart.\n"
	"But when he shall be converted to our Lord, the veil shall be taken away.\n"
	"And our Lord is a Spirit. And where the Spirit of our Lord is, there is liberty.\n"
	"But we all, beholding the glory of our Lord with face revealed, are transformed into the same image from glory unto glory, as of our Lord's Spirit.";