const char* chap1227 = "THEREFORE having this ministration; according as we have obtained mercy, we fail not,\n"
	"but we renounce the secret things of dishonesty, not walking in craftiness, nor adulterating the word of God, but in manifestation of the truth commending our-selves to every conscience of men before God.\n"
	"And if our Gospel be also hid, in them that perish it is hid,\n"
	"in whom the God of this world hath blinded the minds of the infidels, that the illumination of the Gospel of the glory of Christ, who is the image of God, might not shine to them.\n"
	"For we preach not our-selves, but JESUS Christ our Lord: and us, your servants by JESUS:\n"
	"because God that commanded light to shine of darkness, he hath shined in our hearts to the illumination of the knowledge of the glory of God, in the face of Christ JESUS.\n"
	"But we have this treasure in earthen vessels, that the excellency may be of the power of God, and not of us.\n"
	"In all things we suffer tribulation, but are not in distress: we want, but are not destitute:\n"
	"we suffer persecution, but are not forsaken: we are cast down, but we perish not:\n"
	"always bearing about in our body the mortification of JESUS, that the life also of JESUS may be manifested in our bodies.\n"
	"For we that live, are always delivered unto death for JESUS: that the life also of JESUS may be manifested in our mortal flesh.\n"
	"Death then worketh in us, but life in you.\n"
	"And having the same spirit of faith, as it is written: I believed, for the which cause I have spoken, we also believe, for the which cause we speak also:\n"
	"knowing that he which raised up JESUS, will raise up us also with JESUS and set us with you.\n"
	"For all things are for you: that the grace abounding by many in giving of thanks, may abound unto the glory of God.\n"
	"For which cause we fail not: but although that our man which is without, corrupt: yet that which is within, is renewed from day to day.\n"
	"For that our tribulation which presently is momentary & light, worketh above measure exceedingly an eternal weight of glory in us,\n"
	"we not considering the things that are seen, but that are not seen. For the things that be seen, are temporal: but those that be not seen, are eternal.";