const char* chap1232 = "FOR concerning the ministry that is done toward the saints, it is superfluous for me to write unto you.\n"
	"For I know your prompt mind: for the which I glory of you to the Macedonians: That Achaia also is ready from the year past, and your emulation hath provoked very many.\n"
	"But I have sent the brethren, that the thing which we glory of you, be not made void in this behalf, that (as I have said) you may be ready:\n"
	"lest when the Macedonians shall come with me, and find you unready, we (that we say not, ye) may be ashamed in this substance.\n"
	"Therefore I thought it necessary to desire the brethren that they would come to you, and prepare this blessing before promised, to be ready so, as a blessing, not as avarice.\n"
	"And this I say, he that soweth sparingly, sparingly also shall reap: and he that soweth in blessings, of blessings also shall reap.\n"
	"Every one as he hath determined in his heart, not of sadness or of necessity. For God loveth a cheerful giver.\n"
	"And God is able to make all grace abound in you: that in all things always having all sufficiency, you may abound unto all good works,\n"
	"as it is written: He distributed, he gave to the poor: his justice remaineth for ever.\n"
	"And he that ministereth seed to the sower, will give bread also for to eat: and will multiply your seed and will augment the increases of the fruits of your justice:\n"
	"that being enriched in all things, you may abound unto all simplicity, which worketh by us thanks-giving to God.\n"
	"Because the ministry of this office doth not only supply those things that the Saints want, but aboundeth also by many thanks-givings in our Lord,\n"
	"by the proof of this ministry, glorifying God in the obedience of your confession unto the Gospel of Christ, and in the simplicity of communicating unto them, and unto all,\n"
	"and in their praying for you, being desirous of you because of the excellent grace of God in you.\n"
	"Thanks be to God for his unspeakable gift.";