const char* chap1233 = "AND I^ Paul myself beseech you by the mildness and modesty of Christ, who in presence indeed am humble among you, but absent am bold on you.\n"
	"But I beseech you, that being present I need not be bold by that confidence wherewith I am thought to be bold against some: which think us as though we walk according to the flesh.\n"
	"For walking in the flesh, we war not according to the flesh.\n"
	"For the weapons of our warfare are not carnal: but mighty to God unto the destruction of munitions, destroying counsels,\n"
	"and all loftiness extolling itself against the knowledge of God, and bringing into captivity all understanding unto the obedience of Christ,\n"
	"and having in a readiness to revenge all disobedience, when your obedience shall be fulfilled.\n"
	"See the things that are according to appearance. If any man have affiance in himself, that he is Christ's: let him think this again with himself, that as he is Christ's, so we also.\n"
	"For and if I should glory some-what more of our power, which our Lord hath given us unto edification and not to your destruction; I shall not be ashamed.\n"
	"But that I may not be thought as it were to terrify you by epistles\n"
	"(for his epistles indeed, say they, are sore and vehement; but his bodily presence weak, & his speech contemptible)\n"
	"let him this think that is such a one, that such as we are in word by epistles, absent: such also we are in deed, present.\n"
	"For we dare not match or compare ourselves with certain, that commend themselves: but we measure ourselves in ourselves, & compare ourselves to ourselves.\n"
	"But we will not glory above our measure: but according to the measure of the rule; which God hath measured to us, a measure to reach even unto you.\n"
	"For not, as though we reached not unto you, do we extend ourselves beyond. For we are come as far as to you in the Gospel of Christ.\n"
	"not glorying above measure in other men's labours: but having hope of your faith increasing, to be magnified in you according to our rule aboundantly,\n"
	"yea unto those places that are beyond you, to evangelize, not in another man's rule, to glory in those things that are prepared before.\n"
	"But he that glorieth, let him glory in our Lord.\n"
	"For not he that commendeth himself, the same is approved; but whom God commendeth.";