const char* chap1234 = "Would God you could bear some little of my folly: but do ye also support me:\n"
	"for I emulate you with the emulation of God. For I have despoused you to one man, to present you a chaste virgin unto Christ.\n"
	"But I fear lest, as the serpent seduced Eve by his subtlety, so your senses may be corrupted, & fall from the simplicity that is in Christ.\n"
	"For if he that cometh, preach another Christ whom we have not preached, or you receive another spirit whom you have not received; or another Gospel which you have not received: you might well suffer it.\n"
	"For I suppose that I have done nothing less than the great Apostles.\n"
	"For although rude in speech, yet not in knowledge. But in all things we are made manifest to you.\n"
	"Or did I commit a sin, humbling myself, that you might be exalted? because I evangelized unto you the Gospel of God gratis?\n"
	"Other churches I spoiled, taking a stipend, for your ministry.\n"
	"And when I was with you, and had need, I was burdenous to none: for that which I wanted, the brethren supplied that came from Macedonia: and in all things I have kept myself without burden to you, and will keep.\n"
	"The truth of Christ is in me, that this glorying shall not be infringed toward me in the countries of Achaia.\n"
	"Wherefore? because I love you not? God doth know.\n"
	"But that which I do, I will also do, that I may cut away the occasion of them that desire occasion: that, in that which they glory, they may be found even like us.\n"
	"For such false apostles are crafty workers, transfiguring themselves into Apostles of Christ.\n"
	"And no marvel: for Satan himself transfigureth himself into an Angel of light.\n"
	"It is no great matter therefore if his ministers be transfigured as the ministers of justice: whose end shall be according to their works.\n"
	"Again I say, (let no man think me to be foolish: otherwise take me as foolish, that I also may glory a little,)\n"
	"that which I speak, I speak not according to God, but as it were in foolishness, in this substance of glorying.\n"
	"Because many glory according to the flesh, I also will glory.\n"
	"For you do gladly suffer the foolish: whereas yourselves are wise.\n"
	"For you suffer if a man bring you into servitude, if a man devour, if a man take, if a man be extolled, if a man strike you on the face.\n"
	"I speak according to dishonour, as though we had been weak in this part. Wherein any man dare (I speak foolishly) I dare also.\n"
	"They are Hebrews: and I. They are Israelites: and I. They are the seed of Abraham; and I.\n"
	"They are the ministers of Christ; and I. (I speak as one scarce wise) more I: in many more labours, in prisons more aboundantly, in stripes above measure, in deaths often.\n"
	"Of the Jews five times, did I receive forty, saving one.\n"
	"Thrice was I beaten with rods, once I was stoned, thrice I suffered shipwreck; night and day have I been in the depth of the sea,\n"
	"in journeying often, perils of waters, perils of thieves, perils of my Nation, perils of Gentiles, perils in the city, perils in the wilderness, perils in the sea, perils among false brethren,\n"
	"in labour and misery, in much watchings, in hunger and thirst, in fastings often, in cold and nakedness,\n"
	"beside those things which are outwardly: my daily instance, the carefulness of all churches.\n"
	"Who is weak, and I am not weak? Who is scandalized, and I am not burnt?\n"
	"If I must glory: I will glory of the things that concern my infirmity.\n"
	"The God and Father of our Lord JESUS Christ, who is blessed for ever, knoweth that I lie not.\n"
	"At Damascus the Governor of the nation under Aretas the king, kept the city of the Damascenes for to apprehend me:\n"
	"and through a window in a basket was I let down by the wall, and so escaped his hands.";