const char* chap1235 = "IF I must glory (it is not expedient indeed) but I will come to the visions & revelations of our Lord.\n"
	"I know a man in Christ above fourteen years ago (whether in the body, I know not, or out of the body, I know not: God doth know) such a one rapt even to the third Heaven.\n"
	"And I know such a man (whether in the body, or out of the body, I know not; God doth know)\n"
	"that he was rapt into Paradise; & heard secret words, which it is not lawful for a man to speak.\n"
	"For such an one I will glory: but for myself I will glory nothing, saving in my infirmities.\n"
	"For and if I will glory, I shall not be foolish: for I shall say truth. But I spare, lest any man should esteem me above that which he seeth in me, or heareth any thing of me.\n"
	"And lest the greatness of the revelations might extol me, there was given me a prick of my flesh, an angel of Satan, to buffet me.\n"
	"For the which thing thrice I besought our Lord, that it might depart from me.\n"
	"And he said to me: My grace sufficeth thee, for power is perfited in infirmity. Gladly therefore will I glory in mine infirmity, that the power of Christ may dwell in me.\n"
	"For the which cause I please myself in infirmities, in contumelies, in necessities, in persecutions, in distresses for Christ. For when I am weak, then am I mighty.\n"
	"I am become foolish: you have compelled me. For I ought to have been commended of you: for I have been nothing less than they that are above measure Apostles: although I am nothing.\n"
	"Yet the signs of my Apostleship have been done upon you in all patience, in signs & wonders & mighty deeds.\n"
	"For what is there that you have had less than the other churches; but that I myself have not burdened you? Pardon me this injury.\n"
	"Behold, now the third time I am ready to come to you; & I will not be burdenous unto you. For I seek not the things that are yours, but you. For neither ought the children lay up treasures for the parents, but the parents for the children.\n"
	"But I most gladly will bestow, & will myself moreover be bestowed for your souls: although loving you more, I am loved less.\n"
	"But be it so: I have not burdened you: but being crafty, I took you by guile.\n"
	"Have I circumvented you by any of them whom I sent to you?\n"
	"I requested Titus, and I sent with him a brother. Did Titus circumvent you? walked we not with one spirit? not in the self-same steps?\n"
	"Of old think you that we excuse ourselves to you? Before God, in Christ we speak: but all things (my dearest) for your edifying.\n"
	"For I fear lest perhaps when I come, I find you not such as I would: and I be found of you, such an one as you would not. Lest perhaps contentions, emulations, stomachings, dissensions, detractions, whisperings, swellings, seditions be among you.\n"
	"Lest again when I come, God humble me among you: & I mourn many of them that sinned before, & have not done penance for the uncleanness & fornication and incontinency that they have committed.";