const char* chap1240 = "AND I say, as long as the heir is a little one, he differeth nothing from a servant, although he be lord of all,\n"
	"But is under tutors and governors until the time limited of the father:\n"
	"so we also, when we were little ones, were serving under the elements of the world.\n"
	"But when the fullness of time came, God sent his Son made of a woman, made under the Law:\n"
	"that he might redeem them that were under the Law; that we might receive the adoption of sons.\n"
	"And because you are sons, God hath sent the Spirit of his son into your hearts crying: Abba, Father.\n"
	"Therefore now he is not a servant, but a son. And if a son, an heir also by God.\n"
	"But then indeed not knowing God, you served them that by nature are not Gods.\n"
	"But now when you have known God, or rather are known of God, how turn you again to the weak & poor elements, which you will serve again?\n"
	"You observe days, and months, and times, and years.\n"
	"I fear you, lest perhaps I have laboured in vain among you.\n"
	"Be ye as I, because I also am as you: Brethren, I beseech you, you have hurt me nothing.\n"
	"And you know that by infirmity of the flesh I evangelized to you heretofore:\n"
	"and your tentation in my flesh you despised not, neither rejected, but as and Angel of God you received me, as Christ JESUS.\n"
	"Where is then your blessedness? for I give you testimony that if it could be done, you would have plucked out your eyes and have given them to me.\n"
	"Am I then become your enemy, telling you the truth?\n"
	"They emulate you not well: but they would exclude you, that you might emulate them.\n"
	"But do you emulate the good in good always: and not only when I am present with you.\n"
	"My little children, whom I travail withal again, until Christ be formed in you.\n"
	"And I would be with you now and change my voice: because I am confounded in you.\n"
	"Tell me, you that will be under the law, have you not read the Law?\n"
	"For it is written that Abraham had two sons: one of the bond-woman, and one of the free-woman.\n"
	"But he that of the bond-woman, was born according to the flesh: and he that of the free-woman, by the promise.\n"
	"Which things are said by an allegory. For these are the two testaments. The one from mount Sina, gendering unto bondage; which is Agar,\n"
	"(for Sina is a mountain in Arabia, which hath affinity to that which now is Jerusalem) and serveth with her children.\n"
	"But that Jerusalem which is above, is free; which is our mother.\n"
	"For it is written: Rejoice thou barren, that bearest not: break forth and cry, that travailest not: because many are the children of the desolate, more than of her that hath a husband.\n"
	"But we brethren, according to Isaac, are the children of promise.\n"
	"But as then he that was born according to the flesh, persecuted him that was after the spirit; so now also.\n"
	"But what saith the Scripture? Cast out the bond-woman and her son. For the son of the bond-woman shall not be heir with the son of the free-woman.\n"
	"Therefore, brethren, we are not the children of the bond-woman, but of the free: by the freedom wherewith Christ hath made us free.";