const char* chap1241 = "STAND, and be not holden in again with the yoke of servitude.\n"
	"Behold I^ Paul tell you that if you be circumcised, Christ shall profit you nothing.\n"
	"And I testify again to every man circumciding himself, that he is a debter to do the whole Law.\n"
	"You are evacuated from Christ, that are justified in the Law: you are fallen from grace.\n"
	"For we in spirit, by faith, expect the hope of justice.\n"
	"For in Christ JESUS neither circumcision availeth ought, nor prepuce: but faith that worketh by charity.\n"
	"You ran well, who hath hindered you not to obey the truth?\n"
	"The persuasion is not of him that calleth you.\n"
	"A little leaven corrupted the whole paste.\n"
	"I have confidence in you in our Lord, that you will be of no other mind: but he that troubleth you, shall bear the judgement, whosoever he be.\n"
	"And as for me, brethren, if as yet I preach circumcision, why do I yet suffer persecution? Then is the scandal of the cross evacuated.\n"
	"I would they were also cut off that trouble you.\n"
	"For you, brethren, are called into liberty: only make not this liberty an occasion to the flesh, but by charity serve one another.\n"
	"For all the Law is fulfilled in one word: Thou shalt love thy neighbour as thyself.\n"
	"But if you bite and eat one another, take heed you be not consumed one of another.\n"
	"And I say, walk in the spirit, and the lusts of the flesh you shall not accomplish.\n"
	"For the flesh lusteth against the spirit, and the spirit against the flesh: for these are adversaries one to another: that not what things soever you will, these you do.\n"
	"But if you be led by the spirit, you are not under the Law.\n"
	"And the works of the flesh be manifest, which are fornication, uncleanness, impudicity, lechery,\n"
	"serving of idols, witch-crafts, enmities, contentions, emulations, angers, brawls, dissensions, sects,\n"
	"envies, murders, ebrieties, commessations, and such like. Which I foretell you, as I have foretold you, that they which do such things, shall not obtain the Kingdom of God.\n"
	"But the fruit of the Spirit is, Charity, joy, peace, patience, benignity, goodness, longanimity,\n"
	"mildness, faith, modesty, continency, chastity. Against such there is no law.\n"
	"And they that be Christ's, have crucified their flesh with the vices and concupiscences.\n"
	"If we live in the spirit, in the spirit also let us walk.\n"
	"Let us not be made desirous of vain glory, provoking one another, envying one another.";