const char* chap1243 = "PAUL an Apostle of JESUS Christ by the will of God: to all the saints that are at Ephesus; & to the faithful in Christ JESUS.\n"
	"Grace to you and peace from God our Father, and our Lord JESUS Christ.\n"
	"Blessed be God and the Father of our Lord JESUS Christ, which hath blessed us in all spiritual blessing, in celestials, in Christ:\n"
	"as he chose us in him before the constitution of the world, that we should be holy and immaculate in his sight in charity.\n"
	"Who hath predestinated us unto the adoption of sons, by JESUS Christ, unto himself; according to the purpose of his will:\n"
	"unto the praise of the glory of his grace, wherein he hath gratified us in his beloved Son.\n"
	"In whom we have redemption by his blood (the remission of sins) according to the riches of his grace.\n"
	"Which hath superabounded in us in all wisdom and prudence,\n"
	"that he might make known unto us the sacrament of his will, according to his good pleasure, which he purposed in himself,\n"
	"in the dispensation of the fullness of times, to perfit all things in Christ, that are in heaven and in earth, in him.\n"
	"In whom we also are called by lot: predestinate according to the purpose of him that worketh all things, according to the counsel of his will:\n"
	"that we may be unto the praise of his glory, which before have hoped in Christ:\n"
	"in whom you also, when you had heard the word of truth (the Gospel of your salvation) in which also believing you were signed with the holy Spirit of promise,\n"
	"which is the pledge of our inheritance, to the redemption of acquisition, unto the praise of his glory.\n"
	"Therefore I also hearing your faith that is in our Lord JESUS, and love toward all the saints,\n"
	"cease not to give thanks for you, making a memory of you in my prayers,\n"
	"that God of our Lord JESUS Christ, the Father of glory, give you the spirit of wisdom and of revelation, in the knowledge of him,\n"
	"the eyes of your heart illuminated, that you may know what the hope is of his vocation, and what are the riches of the glory of his inheritance in the saints,\n"
	"and what is the passing greatness of his power toward us that believe: according to the operation of the might of his power,\n"
	"which he wrought in Christ, raising him up from the dead, and setting him on his right hand in celestials\n"
	"above all Principality & Potestate & Power, and Domination, & every name that is named not only in this world, but also in that to come.\n"
	"And he hath subdued all things under his feet: and hath made him Head over all the CHURCH,\n"
	"which is his body, the fullness of him, which is filled all in all.";