const char* chap1247 = "Be ye therefore followers of God, as most dear children:\n"
	"and walk in love, as Christ also loved us, and delivered himself for us an oblation and host to God in an odour of sweetness.\n"
	"But fornication and all uncleanness, or avarice let it not so much as be named among you as it becometh Saints:\n"
	"or filthiness, or foolish talk, or scurrility, being to no purpose: but rather giving of thanks.\n"
	"For understanding^ know you this, that no fornicator, or unclean, or covetous person (which is the service of idols) hath inheritance in the Kingdom of Christ and of God.\n"
	"Let no man seduce you with vain words. For, for these things cometh the anger of God upon the children of diffidence.\n"
	"Become not therefore partakers with them.\n"
	"For you were sometime darkness, but now light in our Lord. Walk as children of the light,\n"
	"(for the fruit of the light is in all goodness, and justice, and verity)\n"
	"proving what is well pleasing to God:\n"
	"and communicate not with the unfruitful works of darkness, but rather reprove them.\n"
	"For the things that are done of them in secret, it is shame even to speak.\n"
	"But all things that are reproved, are manifested by the light. For all that is manifested, is light.\n"
	"For the which cause he saith: Rise thou that sleepest, and arise from the dead: and Christ will illuminate thee.\n"
	"See therefore, brethren, how you walk warily. Not as unwise, but as wise:\n"
	"redeeming the time, because the days are evil.\n"
	"Therefore become not unwise, but understanding what is the will of God.\n"
	"And be not drunk with wine wherein is riotousness, but be filled with the Spirit,\n"
	"speaking to yourselves in Psalms & hymns, and spiritual canticles, chanting and singing in your hearts to our Lord:\n"
	"giving thanks always for all things, in the name of our Lord JESUS Christ to God and the Father.\n"
	"Subject one to another in the fear of Christ.\n"
	"Let women be subject to their husbands, as to our Lord:\n"
	"because the man is the head of the woman: as Christ is the head of the CHURCH. Himself, the Saviour of his body.\n"
	"But as the CHURCH is subject to Christ, so also the women to their husbands in all things.\n"
	"Husbands, love your wives, as Christ also loved the CHURCH, and delivered himself for it:\n"
	"that he might sanctify it, cleansing it by the laver of water in the word,\n"
	"that he might present to himself a glorious CHURCH, not having spot, or wrinkle, or any such thing, but that it may be holy and unspotted.\n"
	"So also men ought to love their wives as their own bodies. He that loveth his wife, loveth himself.\n"
	"For no man ever hated his own flesh: but he nourisheth and cherisheth it, as also Christ the CHURCH:\n"
	"because we be the members of his body, of his flesh, and of his bones.\n"
	"For this cause shall man leave his father and mother: and shall cleave to his wife, and they shall be two in one flesh.\n"
	"This is a great Sacrament. But I speak in Christ & in the CHURCH.\n"
	"Nevertheless you also every one, let each love his wife as himself: and let the wife fear her husband.";