const char* chap1253 = "PAUL an Apostle of JESUS Christ by the will of God, and brother Timothee:\n"
	"to them that are at Colossa saints and faithful brethren in Christ JESUS.\n"
	"Grace to you and peace from God our Father and our Lord JESUS Christ. We give thanks to God and the Father of our Lord JESUS Christ always for you, praying:\n"
	"hearing your faith in Christ JESUS, and the love which you have toward all the saints,\n"
	"for the hope that is laid up for you in Heaven, which you have heard in the word of the truth of the Gospel,\n"
	"that is come to you, as also in the whole world it is, and fructifieth, and groweth, even as in you, since that day that you heard and knew the grace of God in truth,\n"
	"as you learned of Epaphras our dearest fellow-servant, who is a faithful minister of JESUS Christ for you,\n"
	"who also hath manifested to us your love in spirit.\n"
	"Therefore we also from the day that we heard it, cease not praying for you and desiring, that you may be filled with the knowledge of his will, in all wisdom, and spiritual understanding:\n"
	"that you may walk worthy of God, in all things pleasing: fructifying in all good work, & increasing in the knowledge of God:\n"
	"in all power strengthened according to the might of his glory, in all patience and longanimity with joy\n"
	"giving thanks to God and the Father, who hath made us worthy unto the part of the lot of the saints in the light:\n"
	"Who hath delivered us from the power of darkness, and hath translated us into the Kingdom of the Son of his love,\n"
	"in whom we have redemption, the remission of sins:\n"
	"who is the image of the invisible God, the first-born of all creature:\n"
	"because in him were created all things in Heaven, and in earth, visible, and invisible, whether Thrones, or Dominations, or Principalities, or Potestates: all by him, & in him were created:\n"
	"and he is before all, and all consist in him.\n"
	"And he is the Head of the body, the CHURCH, who is the beginning, first-born of the dead: that he may be in all things holding the primacy:\n"
	"because in him it hath well pleased, all fullness to inhabit:\n"
	"and by him to reconcile all things unto himself, pacifying by the blood of his cross, whether the things in earth, or the things that are in Heaven.\n"
	"And you, whereas you were sometime alienated and enemies in sense, in evil works:\n"
	"yet now he hath reconciled in the body of his flesh by death, to present you holy & immaculate, and blameless before him:\n"
	"if yet ye continue in the faith, grounded and stable, and unmovable from the hope of the Gospel which you have heard, which is preached among all creatures that are under Heaven, whereof I^ Paul am made a minister.\n"
	"Who now rejoice in suffering for you, and do accomplish those things that want of the passions of Christ, in my flesh for his body, which is the CHURCH:\n"
	"whereof I am made a minister according to the dispensation of God, which is given me toward you, that I may fulfill the word of God,\n"
	"the mystery that hath been hidden from worlds and generations, but now is manifested to his saints,\n"
	"to whom God would make known the riches of the glory of his sacrament in the Gentiles, which is Christ, in you the hope of glory,\n"
	"whom we preach, admonishing every man, and teaching every man in all wisdom, that we may present every man perfect in Christ JESUS.\n"
	"Wherein also I labour striving according to his operation which he worketh in me in power.";