const char* chap1259 = "FOR the which cause forbearing no longer, it pleased us to remain at Athens, alone.\n"
	"And we sent Timothee our brother, & the minister of God in the Gospel of Christ, to confirm you and exhort you for your faith,\n"
	"that no man be moved in these tribulations: for yourselves know, that we are appointed to this.\n"
	"For even when we were with you, we fore-told you that we should suffer tribulations, as also it is come to pass, and you know.\n"
	"Therefore I also forbearing no longer, sent to know your faith: lest perhaps he that tempteth, hath tempted you, and our labour be made vain.\n"
	"But now Timothee coming unto us from you, and reporting to us your faith and charity, and that you have a good remembrance of us always, desiring to see us, as we also^ you:\n"
	"therefore we are comforted, brethren, in you, in all our necessity, & tribulation, by your faith,\n"
	"because now we live, if you stand in our Lord.\n"
	"For what thanks-giving can we render to God for you, in all joy wherewith we rejoice for you before our God,\n"
	"night and day more aboundantly praying that we may see your face, and may accomplish those things that want of your faith?\n"
	"And God himself and our Father, & our Lord JESUS Christ direct our way to you.\n"
	"And our Lord multiply you, & make your charity abound one to another, and toward all men: as we also in you,\n"
	"to confirm your hearts without blame, in holiness, before God and our Father, in the coming of our Lord JESUS Christ with all his Saints. Amen.";