const char* chap1261 = "AND of the times and moments, brethren, you need not that we write to you.\n"
	"For yourselves know perfectly that the day of our Lord shall so come, as a thief in the night.\n"
	"For when they shall say, peace & security; then shall sudden destruction come upon them, as the pains to her that is with child, and they shall not escape.\n"
	"But you, brethren, are not in darkness; that the same day may as a thief over-take you.\n"
	"For all you are the children of light, and children of the day: we are not of the night nor of darkness.\n"
	"Therefore let us not sleep as also others: but let us watch & be sober.\n"
	"For they that sleep, sleep in the night; & they that be drunk, be drunk in the night.\n"
	"But we that are of the day, are sober, having on, the breast-plate of faith and charity, and a helmet, the hope of salvation.\n"
	"For God hath not appointed us unto wrath, but unto the purchasing of salvation by our Lord JESUS Christ,\n"
	"who died for us: that whether we watch, or sleep, we may live together with him.\n"
	"For the which cause comfort one another: and edify one another, as also you do.\n"
	"And we beseech you, brethren, that you will know them that labour among you, and that govern you in our Lord and admonish you:\n"
	"that you have them more aboundantly in charity for their work. Have peace with them.\n"
	"And we beseech you, brethren, admonish the unquiet, comfort the weak-minded, bear up the weak, be patient to all.\n"
	"See that none render evil for evil to any man: but always that which is good pursue towards each other, & towards all.\n"
	"Always rejoice.\n"
	"Pray without intermission.\n"
	"In all things give thanks. For this is the will of God in Christ JESUS in all you.\n"
	"The Spirit^ extinguish not.\n"
	"Prophecies^ despise not.\n"
	"But prove all things: hold that which is good.\n"
	"From all appearance of evil refrain yourselves.\n"
	"And the God of peace himself sanctify you in all things: that your whole spirit, and soul and body without blame may be preserved in the coming of our Lord JESUS Christ.\n"
	"He is faithful, that hath called you, who also will do it.\n"
	"Brethren pray for us.\n"
	"Salute all the brethren in a holy kiss.\n"
	"I adjure you by our Lord that this epistle be read to all the holy brethren.\n"
	"The grace of our Lord JESUS Christ be with you. Amen.";