const char* chap1268 = "AND the Spirit manifestly saith that in the last times certain shall depart from the faith attending to spirits of error, and doctrines of devils,\n"
	"speaking lies in hypocrisy, and having their conscience seared,\n"
	"forbidding to marry, to abstain from meats which God created to receive with thanks-giving for the faithful, and them that have known the truth.\n"
	"For every creature of God is good, and nothing to be rejected that is received with thanks-giving.\n"
	"For it is sanctified by the word of God and prayer.\n"
	"These things proposing to the brethren, thou shalt be a good minister of Christ JESUS, nourished in the words of the faith and the good doctrine which thou hast attained unto.\n"
	"But foolish and old wives' fables avoid: and exercise thyself to piety.\n"
	"For corporal exercise is profitable to little: but piety is profitable to all things: having promise of the life that now is, and of that to come.\n"
	"A faithful saying and worthy of all acceptation:\n"
	"For to this purpose we labour and are reviled, because we hope in the living God which is the Saviour of all men, especially of the faithful.\n"
	"Command these things and teach.\n"
	"Let no man contemn thy youth: but be an example of the faithful, in word, in conversation, in charity, in faith, in chastity.\n"
	"Till I come, attend unto reading, exhortation, doctrine.\n"
	"Neglect not the grace that is in thee: which is given thee by prophecy, with imposition of the hands of priesthood.\n"
	"These things do thou mediate, be in these things: that thy profiting may be manifest to all.\n"
	"Attend to thyself, and to doctrine: be earnest in them. For, this doing, thou shalt save both thyself and them that hear thee.";