const char* chap1269 = "A Senior rebuke not: but beseech as a father: young men, as brethren:\n"
	"old women, as mothers: young women, as sisters, in all chastity.\n"
	"Honour widows, which are widows indeed.\n"
	"But if any widow have children or nephews; let her learn first to rule her own house, & to render mutual duty to her parents. For this is acceptable before God.\n"
	"But she that is a widow indeed and desolate, let her hope in God, and continue in obsecrations & prayers night and day.\n"
	"For she that is in deliciousness, living is dead.\n"
	"And this command that they be blameless.\n"
	"But if any man have not care of his own, and especially of his domesticals, he hath denied the faith, and is worse than an infidel.\n"
	"Let a widow be chosen of no less than three-score years, which hath been the wife of one husband,\n"
	"having testimony in good works, if she have brought up her children, if she have received to harbour, if she have washed the saints' feet, if she have ministered to them that suffer tribulation, if she have followed every good work.\n"
	"But the younger widows avoid. For when they shall be wanton in Christ, they will marry:\n"
	"having damnation, because they have made void their first faith.\n"
	"And withal idle also they learn to go about from house to house: not only idle, but also full of words & curious, speaking things which they ought not.\n"
	"I will^ therefore the younger to marry, to bring forth children, to be housewives: to give no occasion to the adversary for to speak evil.\n"
	"For now certain are turned back after Satan.\n"
	"If any faithful man have widows, let him minister to them, and let not the Church be burdened: that there may be sufficient for them that are widows indeed.\n"
	"The priests that rule well, let them be esteemed worthy of double honour: especially they that labour in the word and doctrine.\n"
	"For the Scripture saith: Thou shalt not muzzle the mouth to the ox that treadeth out the corn; and, The work-man is worthy of his hire.\n"
	"Against a priest receive not accusation, but under two or three witnesses.\n"
	"Them that sin, reprove before all: that the rest also may have fear.\n"
	"I testify before God and Christ JESUS, and the elect Angels, that thou keep these things without prejudice, doing nothing by declining to the one part.\n"
	"Impose hands on no man lightly, neither do thou communicate with other men's sins. Keep thyself chaste.\n"
	"Drink not yet water; but use a little wine for thy stomach, and thy often infirmities.\n"
	"Certain men's sins be manifest, going before to judgement: and certain men they follow.\n"
	"In like manner also good deeds be manifest, and they that are otherwise, cannot be hid.";