const char* chap1274 = "I Testify before God and JESUS Christ who shall judge the living and the dead, and by his advent, and his Kingdom:\n"
	"Preach the word. Urge in season, out of season, reprove, beseech, rebuke, in all patience and doctrine.\n"
	"For there shall be a time when they will not bear sound doctrine: but according to their own desires they will heap to themselves masters, having itching ears,\n"
	"and from the truth certes they will avert their hearing, and to fables they will be converted.\n"
	"But be thou vigilant, labour in all things, do the work of an Evangelist, fulfill thy ministry. Be sober.\n"
	"For I am even now to be sacrificed: and the time of my resolution is at hand.\n"
	"I have fought a good fight, I have consummate my course, I have kept the faith.\n"
	"Concerning the rest, there is laid up for me a crown of justice, which our Lord will render to me in that day, a just judge: and not only to me, but to them also that love his coming.\n"
	"Make haste to come to me quickly.\n"
	"For Demas hath left me, loving this world, and is gone to Thessalonica: Crescens into Galatia, Titus into Dalmatia.\n"
	"Luke only is with me. Take Mark, and bring him with thee: for he is profitable to me for the ministry.\n"
	"But Tychicus I have sent to Ephesus.\n"
	"The cloak that I left at Troas with Carpus, coming bring with thee, and the books, especially the parchment.\n"
	"Alexander the Coppersmith hath shewed me much evil: our Lord will reward him according to his works:\n"
	"whom do thou also avoid, for he hath greatly resisted our words.\n"
	"In my first answer no man was with me, but all did forsake me: be it not imputed to them.\n"
	"But our Lord stood to me, and strengthened me, that by me the preaching may be accomplished, and all Gentiles may hear: and I was delivered from the mouth of the lion.\n"
	"Our Lord hath delivered me from all evil work: and will save me unto his heavenly Kingdom. To whom be glory for ever and ever. Amen.\n"
	"Salute Prisca and Aquila, and the house of Onesiphorus.\n"
	"Erastus remained at Corinth. And Trophimus I left sick at Miletum.\n"
	"Make haste to come before winter. Eubulus and Pudens and Linus and Claudia, and all the brethren, salute thee.\n"
	"Our Lord JESUS Christ be with thy spirit. Grace be with you. Amen.";