const char* chap1275 = "PAUL the servant of God, and an Apostle of JESUS Christ according to the faith of the elect of God and knowledge of the truth: which is according to piety,\n"
	"into the hope of life everlasting, which he promised that lieth not, God, before the secular times:\n"
	"but hath manifested in due times his word in preaching, which is committed to me according to the precept of our Saviour God:\n"
	"to Titus my beloved son according to the common faith, grace and peace from God the Father, and Christ JESUS our Saviour.\n"
	"For this cause left I thee in Crete, that thou shouldest reform the things that are wanting, and shouldest ordain priests by cities, as I also appointed thee:\n"
	"if any be without crime, the husband of one wife, having faithful children, not in the accusation of riot, or not obedient.\n"
	"For a Bishop must be without crime, as the steward of God: not proud, not angry, not given to wine, no striker, not covetous of filthy lucre:\n"
	"but given to hospitality, gentle, sober, just, holy, continent:\n"
	"embracing that faithful word which is according to doctrine, that he may be able to exhort in sound doctrine, and to reprove them that gainsay it.\n"
	"For there be many disobedient, vain-speakers, and seducers, especially they that are of the Circumcision.\n"
	"Who must be controlled. Who subvert whole houses, teaching the things they ought not, for filthy lucre.\n"
	"One of them said, their own proper prophet, The Cretensians always liars, naughty beasts, slothful bellies.\n"
	"This testimony is true. For the which cause rebuke them sharply, that they may be sound in the faith,\n"
	"not attending to Jewish fables, and commandments of men, averting themselves from the truth.\n"
	"All things are clean to the clean: but to the polluted and to infidels nothing is clean: but polluted are both their mind and conscience.\n"
	"They confess that they know God: but in their works they deny, whereas they be abominable and incredulous and to every good work reprobate.";