const char* chap1276 = "BUT do thou speak the things that become sound doctrine.\n"
	"Old men that they be sober, chaste, wise, sound in the faith, in love, in patience.\n"
	"Old women in like manner, in holy attire, not ill speakers, not given to much wine: teaching well,\n"
	"that they may teach the young women wisdom, to love their husbands, to love their children,\n"
	"wise, chaste, sober, having a care of the house, gentle, subject to their husbands, that the word of God be not blasphemed.\n"
	"Yong men in like manner exhort that they be sober.\n"
	"In all things shew thyself an example of good works, in doctrine, in integrity, in gravity,\n"
	"the word sound, irreprehensible: that he which is on the contrary part, may be afraid, having no evil to say of us.\n"
	"Servants to be subject to their masters, in all things pleasing, not gainsaying:\n"
	"not defrauding, but in all things shewing good faith, that they may adorn the doctrine of our Saviour God in all things.\n"
	"For the grace of God our Saviour hath appeared to all men:\n"
	"instructing us that denying impiety and worldly desires, we live soberly, and justly, and godly in this world,\n"
	"expecting the blessed hope and advent of the glory of the great God and our Saviour JESUS Christ,\n"
	"who gave himself for us, that he might redeem us from all iniquity, and might cleanse to himself a people acceptable, a pursuer of good works.\n"
	"These things speak, and exhort and rebuke with all authority. Let no man contemn thee.";