const char* chap1278 = "PAUL the prisoner of Christ JESUS, and brother Timothee: to Philemon the beloved and our coadjutor,\n"
	"and to Appia our dearest sister, and to Archippus our fellow-soldier and to the church which is in thy house.\n"
	"Grace to you and peace from God our Father, and our Lord JESUS Christ.\n"
	"I give thanks to my God, always making a memory of thee in my prayers,\n"
	"hearing thy charity & faith which thou hast in our Lord JESUS, and toward all the saints:\n"
	"that the communication of thy faith may be made evident in the agnition of all good that is in you in Christ JESUS.\n"
	"For I have had great joy and consolation in thy charity, because the bowels of the saints have rested by thee brother.\n"
	"For the which thing having great confidence in Christ JESUS to command thee that^ which pertaineth to the purpose:\n"
	"for charity rather I beseech, whereas thou art such an one, as Paul being old and now prisoner also of JESUS Christ.\n"
	"I beseech thee for my son whom I have begotten in bands, Onesimus,\n"
	"who hath been sometime unprofitable to thee, but now profitable both to me and thee,\n"
	"whom I have sent back to thee. And do thou receive him as mine own bowels.\n"
	"Whom I would have retained with me, that for thee he might minister to me in the bands of the Gospel:\n"
	"but without thy counsel I would do nothing: that thy good might be not as it were of necessity, but voluntary.\n"
	"For perhaps therefore he departed for a season from thee, that thou mightest take him again for ever.\n"
	"Now not as a servant, but for a servant, a most dear brother, especially to me, but how much more to thee both in the flesh and in our Lord?\n"
	"If therefore thou take me for thy fellow; receive him as myself.\n"
	"And if he hath hurt thee any thing or is in thy debt, that^ impute to me.\n"
	"I^ Paul have written with mine own hand: I will repay it: not to say to thee, that thou owest me thine own self also.\n"
	"Yea brother. God grant I may enjoy thee in our Lord. Refresh my bowels in our Lord.\n"
	"Trusting in thy obedience I have written to thee, knowing that thou wilt do above that also which I do say.\n"
	"And withal provide me also a lodging. For I hope by your prayers that I shall be given to you.\n"
	"There salute thee Epaphras my fellow-prisoner in Christ JESUS,\n"
	"Mark, Aristarchus, Demas and Luke my coadjutors.\n"
	"The grace of our Lord JESUS Christ be with your spirit. Amen.";