const char* chap1279 = "DIVERSELY and many ways in times past God speaking to the fathers in the prophets,\n"
	"last of all in these days hath spoken to us in his Son, whom he hath appointed heir of all, by whom he made also the worlds.\n"
	"Who being the brightness of his glory, and the figure of his substance, and carrying all things by the word of his power, making purgation of sins, sitteth on the right hand of the Majesty in the high places:\n"
	"being made so much better than Angels, as he hath inherited a more excellent name above them.\n"
	"For to which of the Angels hath he said at any time, Thou art my Son, today have I begotten thee? and again, I will be to him a Father, and he shall be to me a Son.\n"
	"And when again he bringeth in the first-begotten into the world, he saith, And let all the Angels of God adore him.\n"
	"And to the Angels truly he saith, He that maketh his Angels, spirits: and his ministers, a flame of fire.\n"
	"But to the Son: Thy throne o God for ever and ever: a rod of equity, the rod of thy kingdom.\n"
	"Thou hast loved justice, and hated iniquity: therefore thee, God, thy God hath anointed with the oil of exultation above thy fellows.\n"
	"And, Thou in the beginning o Lord didst found the earth: and the works of thy hands are the heavens.\n"
	"They shall perish, but thou shalt continue: and they shall all wax old as a garment.\n"
	"And as a vesture shalt thou change them, and they shall be changed: but thou art the self-same, and thy years shall not fail.\n"
	"But to which of the Angels said he at any time: Sit on my right hand, until I make thine enemies the foot-stool of thy feet?\n"
	"Are they not all, ministering spirits: sent to minister for them which shall receive the inheritance of salvation?";