const char* chap128 = "In the mean time there arose a murmuring of the people, as it were repining for labour, against our Lord. Which when our Lord had heard, he was angry. And the fire of our Lord being kindled against them, devoured the uttermost part of the camp.\n"
	"And when the people had cried to Moyses, Moyses prayed to our Lord, and the fire was quenched.\n"
	"And he called the name of the place, Kindling: for that the fire of our Lord had been kindled against them.\n"
	"For the common vulgar people that came up with them, burned with desire, sitting and weeping, the children of Israel being joined together with them, and said: Who shall give us flesh to eat?\n"
	"We remember the fishes that we did eat in Aegypt gratis: the cucumbers come unto our mind, and the melons, and leeks and onions and garlic.\n"
	"Our soul is dry, our eyes behold nothing else but Manna.\n"
	"And the Manna was as it were the seed of Coriander, of the colour of bdellion.\n"
	"And the people went about, & gathering it, ground it in a mill, or brayed it in a mortar, boiling it in a pot, and making cakes thereof of the taste as it were of oiled bread.\n"
	"And when the dew fell in the night upon the camp, the Manna also fell withal.\n"
	"Moyses therefore heard the people weeping by their families, every one at the doors of his tent. And the fury of our Lord was exceeding wrath: but to Moyses also it seemed an intolerable thing.\n"
	"And he said to our Lord: Why hast thou afflicted thy servant? wherefore do I not find grace before thee? and why hast thou laid the weight of all this people upon me?\n"
	"Have I conceived all this multitude, or begotten them, that thou shouldest say to me: Carry them in thy bosom as the nurse is wont to carry the little infant, and bear them into the land, for the which thou hast sworn to their fathers?\n"
	"Whence shall I have flesh to give to so great a multitude? They whine against me, saying: Give us flesh that we may eat.\n"
	"I alone cannot sustain all this people, because it is heavy for me.\n"
	"But if it seem unto thee otherwise, I beseech thee to kill me, and let me find grace in thine eyes, that I be not molested with so great evils.\n"
	"And our Lord said to Moyses: Gather me seventy men of the ancients of Israel, whom thou knowest to be the ancients of the people and masters: and thou shalt bring them to the door of the tabernacle of covenant, and shalt make them to stand there with thee,\n"
	"that I may descend & speak to thee: and I will take of thy spirit, and will deliver to them, that they may sustain with thee the burden of the people, and thou only be not burdened.\n"
	"To the people also thou shalt say: Be sanctified: tomorrow you shall eat flesh: for I have heard you say: Who shall give us meats of flesh? It was well with us in Aegypt. That the Lord may give you flesh, and you may eat:\n"
	"not one day, nor two, or five, or ten, no nor twenty,\n"
	"but even to a month of days, till it go out of your nostrils, & be turned to loathsomeness, because you have rejected the Lord, who is in the midst of you, and have whined before him, saying: Wherefore came we out of Aegypt?\n"
	"And Moyses said: There are six hundred thousand footmen of this people, and sayest thou: I will give them flesh to eat a whole month?\n"
	"Why, shall a multitude of sheep and oxen be killed, that it may suffice for meat? Or shall all the fishes of the sea be gathered together, for to fill them?\n"
	"To whom our Lord answered: Why, is the hand of the Lord unable? Now presently thou shalt see whether my word shall be accomplished in deed.\n"
	"Moyses therefore came, and told the people the words of our Lord, assembling seventy men of the ancients of Israel, whom he caused to stand about the tabernacle.\n"
	"And our Lord descended in a cloud, and spake to him, taking away of the spirit that was in Moyses, and giving to the seventy men. And when the spirit had rested on them, they prophesied, neither ceased they any more.\n"
	"And there had remained in the camp two men, of the which one was called Eldad, and the other Medad, upon whom the spirit rested. For they also had been enrolled, & were not gone forth to the tabernacle.\n"
	"And when they prophesied in the camp, there ran a boy, and told Moyses, saying: Eldad and Medad do prophesy in the camp.\n"
	"Forthwith Josue the Nun, the minister of Moyses, and chosen of many, said: My Lord Moyses forbid them.\n"
	"But he said: Why hast thou emulation for me? O that all the people might prophesy, and that our Lord would give them his spirit!\n"
	"And Moyses returned, and the ancients of Israel into the camp.\n"
	"And a wind coming forth from our Lord, taking quails over the sea brought them, and let them fall into the camp the space of one day's journey, on every side of the camp round about, and they did fly in the air two cubits high over the earth.\n"
	"The people therefore rising up all that day, and the night, and the next day, gathered together a multitude of quails, he that did least, ten cores: and they dried them round about the camp.\n"
	"As yet the flesh was in their teeth, neither had that kind of meat failed: & behold the fury of our Lord being provoked against the people, struck them with an exceeding great plague.\n"
	"And that place was called, The Sepulchres of concupiscence: for there they buried the people that had lusted. And departing from the Sepulchres of concupiscence, they came unto Haseroth, and tarried there.";