const char* chap1280 = "THEREFORE more aboundantly ought we to observe those things which we have heard: lest perhaps we run out.\n"
	"For if the word that was spoken by Angels, became sure, and all prevarication and disobedience hath received a just retribution of reward:\n"
	"how shall we escape if we neglect so great salvation? which when it was begun to be declared by our Lord, of them that heard^ was confirmed on us,\n"
	"God withal testifying by signs, and wonders, and diverse miracles, and distributions of the Holy Ghost according to his will.\n"
	"For not to Angels hath God made subject the world to come, whereof we speak.\n"
	"But one hath testified in a certain place, saying: What is man, that thou art mindful of him: or the son of man, that thou visitest him?\n"
	"Thou didst minish him little less than Angels: with glory and honour thou hast crowned him, and constituted him over the works of thy hands.\n"
	"All things hast thou made subject under his feet. For in that he subjected all things to him, he left nothing not subject to him. But now we see not as yet all things subjected to him.\n"
	"But him that was a little lessened under the Angels, we see JESUS, because of the passion of death, crowned with glory and honour: that through the grace of God he might taste death for all.\n"
	"For it became him for whom all things, and by whom all things, that had brought many children into glory, to consummate the author of their salvation, by his passion.\n"
	"For he that sanctifieth, and they that be sanctified; all of one. For the which cause he is not ashamed to call them brethren,\n"
	"saying, I will declare thy name to my brethren: in the midst of the Church will I praise thee.\n"
	"And again, I will have affiance in him. And again, Behold here am I & my children: whom God hath given me.\n"
	"Therefore because the children have communicated with flesh and blood, himself also in like manner hath been partaker of the same: that by death he might destroy him that had the empire of death, that is to say, the devil:\n"
	"and might deliver them that by the fear of death through all their life were subject to servitude.\n"
	"For no where doth he take Angels: but the seed of Abraham he taketh.\n"
	"Whereupon he ought in all things to be like unto his brethren: that he might become a merciful and faithful high Priest before God, that he might repropitiate the sins of the people.\n"
	"For in that wherein himself suffered and was tempted: he is able to help them also that are tempted.";