const char* chap1283 = "FOR every high Priest taken from among men, is appointed for men in those things that pertain to God: that he may offer gifts and sacrifices for sins:\n"
	"that can have compassion on them that be ignorant and do err: because himself also is compassed with infirmity:\n"
	"& therefore he ought, as for the people, so also for himself to offer for sins.\n"
	"Neither doth any man take the honour to himself, but he that is called of God, as Aaron.\n"
	"So Christ also did not glorify himself that he might be made a high priest; but he that spake to him, My Son art thou, I this day have begotten thee.\n"
	"As also in another place he saith, Thou art a priest for ever, according to the order of Melchisedech.\n"
	"Who in the days of his flesh, with a strong cry and tears, offering prayers and supplications to him that could save him from death, was heard for his reverence.\n"
	"And truly whereas he was the Son, he learned by those things which he suffered, obedience:\n"
	"and being consummate, was made to all that obey him, cause of eternal salvation,\n"
	"called of God a high priest according to the order of Melchisedech.\n"
	"Of whom we have great speech and inexplicable to utter: because you are become weak to hear.\n"
	"For whereas you ought to be masters for your time, you need to be taught again yourselves what be the elements of the beginning of the words of God: & you are become such as have need of milk, and not of strong meat.\n"
	"For every one that is partaker of milk, is unskillful of the word of justice: for he is a child.\n"
	"But strong meat is for the perfect, them that by custom have their senses exercised to the discerning of good and evil.";