const char* chap1287 = "THE former also indeed had justifications of service, and a secular sanctuary.\n"
	"For the tabernacle was made, the first, wherein were the candlesticks, and the table, and the proposition of loaves, which is called Holy.\n"
	"But after the second veil, the tabernacle, which is called Sancta Sanctorum:\n"
	"having a golden censer, and the ark of the testament covered about on every part with gold, in the which was a golden pot having Manna, and the rod of Aaron that had blossomed, and the tables of the testament,\n"
	"and over it were the Cherubins of glory over-shadowing the propitiatory, of which things it is not needful to speak now particularly.\n"
	"But these things being so ordered, in the first tabernacle indeed the Priests always entered, accomplishing offices of the sacrifices.\n"
	"But in the second, once a year the high priest only: not without blood which he offereth for his own and the people's ignorance:\n"
	"the Holy Ghost signifying this, that the way of the Holies was not yet manifested, the former tabernacle as yet standing.\n"
	"Which is a parable of the time present: according to which are offered gifts and hosts, which cannot concerning the conscience^ make perfect him that serveth,\n"
	"only in meats and in drinks, and diverse baptisms, and justices of the flesh laid on them until the time of correction.\n"
	"But Christ assisting an high Priest of the good things to come, by a more ample and more perfect tabernacle not made with hand, that is, not of this creation:\n"
	"neither by the blood of goats or of calves, but by his own blood entered in once into the Holies, eternal redemption being found.\n"
	"For if the blood of goats and of oxen and the ashes of an heifer being sprinkled, sanctifieth the polluted to the cleansing of the flesh,\n"
	"how much more hath the blood of Christ who by the Holy Ghost offered himself unspotted unto God, cleansed our conscience from dead works, to serve the living God?\n"
	"And therefore he is the Mediator of the new Testament: that death being a mean, unto the redemption of these prevarications which were under the former testament, they that are called may receive the promise of eternal inheritance.\n"
	"For where there is a testament: the death of the testator must of necessity come between.\n"
	"For a testament is confirmed in the dead: otherwise it is yet of no value, whiles the testator liveth.\n"
	"Whereupon neither was the first certes dedicated without blood.\n"
	"For all the commandment of the Law being read of Moyses to all the people: he taking the blood of calves and goats with water and scarlet wool and hyssop, sprinkled the very book also itself and all the people,\n"
	"saying, This is the blood of the Testament, which God hath commanded unto you.\n"
	"The tabernacle also & all the vessel of the ministry he in like manner sprinkled with blood.\n"
	"And all things almost according to the law are cleansed with blood: and without shedding of blood there is not remission.\n"
	"It is necessary therefore that the examplers of the celestials be cleansed with these: but the celestials themselves with better hosts than these.\n"
	"For JESUS is not entered into Holies made with hand, examplers of the true: but into Heaven it-self, that he may appear now to the countenance of God for us.\n"
	"Nor that he should offer himself often, as the high priest entereth into the Holies, every year in the blood of others:\n"
	"otherwise he ought to have suffered often from the beginning of the world: but now once in the consummation of the worlds, to the destruction of sin, he hath appeared by his own host.\n"
	"And as it is appointed to men to die once, and after this, the judgement:\n"
	"so also Christ was offered once to exhaust the sins of many. The second time he shall appear without sin to them that expect him, unto salvation.";