const char* chap1288 = "FOR the law having a shadow of good things to come, not the very image of the things: every year with the self-same hosts which they offer incessantly, can never make the comers thereto perfect:\n"
	"otherwise they should have ceased to be offered, because the worshippers once cleansed should have no conscience of sin any longer.\n"
	"But in them there is made a commemoration of sin every year.\n"
	"For it is impossible that with the blood of oxen and goats sins should be taken away.\n"
	"Therefore coming into the world he saith: Host and oblation thou wouldest not: but a body thou hast fitted to me:\n"
	"Holocausts and for sin did not please thee.\n"
	"Then said I, Behold I come: in the head of the book it is written of me: That I may do thy will, o God.\n"
	"Saying before, Because hosts and oblations & holocausts, & for sin thou wouldest not, neither did they please thee, which are offered according to the law,\n"
	"then said I, Behold I come that I may do thy will, o God: he taketh away the first, that he may establish that that followeth.\n"
	"In the which will, we are sanctified by the oblation of the body of JESUS Christ once.\n"
	"And every Priest indeed is ready daily ministering, and often offering the same hosts, which can never take away sins:\n"
	"but this man offering one host for sins, for ever sitteth on the right hand of God,\n"
	"hence-forth expecting, until his enemies be put the foot-stool of his feet.\n"
	"For by one oblation hath he consummated for ever them that are sanctified.\n"
	"And the Holy Ghost also doth testify to us. For after that^ he said:\n"
	"And this is the Testament which I will make to them after those days, saith our Lord, giving my laws in their hearts, and in their minds will I superscribe them:\n"
	"and their sins and iniquities I will now remember no more.\n"
	"But where there is remission of these, now there is not an oblation for sins.\n"
	"Having therefore, brethren, confidence in the entering of the Holies in the blood of Christ:\n"
	"which he hath dedicated to us a new & living way by the veil, that is, his flesh,\n"
	"and a high Priest over the house of God,\n"
	"let us approach with a true heart in fullness of faith, having our hearts sprinkled from evil conscience, and our body washed with clean water.\n"
	"Let us hold the confession of our hope undeclining (for he is faithful that hath promised)\n"
	"and let us consider one another unto the provocation of charity and of good works:\n"
	"not forsaking our assembly as some are accustomed, but comforting, and so much the more as you see the day approaching.\n"
	"For if we sin willingly after the knowledge of the truth received, now there is not left an host for sins,\n"
	"but a certain terrible expectation of judgement & rage of fire, which shall consume the adversaries.\n"
	"A man making the Law of Moyses frustrate, without any mercy dieth under two or three witnesses.\n"
	"How much more think you, doth he deserve worse punishments which hath trodden the Son of God under-foot, and esteemed the blood of the testament polluted, wherein he is sanctified, and hath done contumely to the spirit of grace?\n"
	"For we know him that said, Revenge to me, I will repay. And again, That our Lord will judge his people.\n"
	"It is horrible to fall into the hands of the living God.\n"
	"But call to mind the old days: wherein being illuminated, you sustained a great fight of passions.\n"
	"And on the one part certes by reproaches and tribulations made a spectacle; & on the other part made companions of them that conversed in such sort.\n"
	"For, you both had compassion on them that were in bonds: and the spoil of your own goods you took with joy, knowing that you have a better and a permanent substance.\n"
	"Do not therefore leese your confidence, which hath a great remuneration.\n"
	"For patience is necessary for you: that doing the will of God, you may receive the promise.\n"
	"For yet a little and a very little while, he that is to come, will come, and will not slack.\n"
	"And my just liveth of faith: but if he withdraw himself, he shall not please my soul.\n"
	"But we are not the children of withdrawing unto perdition: but of faith to the winning of the soul.";