const char* chap1289 = "AND faith is, the substance of things to be hoped for, the argument of things not appearing.\n"
	"For in this the old men obtained testimony.\n"
	"By faith, we understand that the worlds were framed by the word of God: that of invisible things visible things might be made.\n"
	"By faith, Abel offered a greater host to God than Cain: by which he obtained testimony that he was just, God giving testimony to his gifts, and by it, he being dead, yet speaketh.\n"
	"By faith Henoch was translated, that he should not see death, and he was not found: because God translated him. For before his translation he had testimony that he had pleased God.\n"
	"But without faith it is impossible to please God. For he that cometh to God, must believe that he is, and is a rewarder to them that seek him.\n"
	"By faith, Noe having received an answer concerning those things which as yet were not seen, fearing, framed the ark for the saving of his house, by the which he condemned the world: and was instituted heir of the justice which is by faith.\n"
	"By faith, he that is called, Abraham, obeyed to go forth into the place which he was to receive for inheritance: and he went forth, not knowing whither he went.\n"
	"By faith, he abode in the land of promise, as in a strange land, dwelling in cottages with Isaac & Jacob the coheirs of the same promise.\n"
	"For he expected the city that hath foundations: whose artificer and maker is God.\n"
	"By faith, Sara also herself being barren, received virtue in conceiving of seed, yea past the time of age: because she believed that he was faithful which had promised.\n"
	"For the which cause even of one (and him quite dead) there rose as the stars of heaven in multitude, and as the sand that is by the sea shore innumerable.\n"
	"According to faith died all these, not having received the promises, but beholding them a far off, and saluting them, and confessing that they are pilgrims & strangers upon the earth.\n"
	"For they that say these things, do signify that they seek a country.\n"
	"And indeed if they had been mindful of the same from whence they came forth, they had time verily to return.\n"
	"But now they desire a better, that is to say, a heavenly. Therefore God is not confounded to be called their God. For he hath prepared them a city.\n"
	"By faith, Abraham offered Isaac, when he was tempted: and his only-begotten did he offer who had received the promises:\n"
	"(to whom it was said, That in Isaac shall seed be called to thee.)\n"
	"accounting that God is able to raise up even from the dead. Whereupon he received him also for a parable.\n"
	"By faith, also of things to come, Isaac blessed Jacob and Esau.\n"
	"By faith, Jacob dying, blessed every one of the sons of Joseph: and adored the top of his rod.\n"
	"By faith, Joseph dying, made mention of the going forth of the children of Israel: and gave commandment concerning his bones.\n"
	"By faith, Moyses being born, was hid three months by his parents: because they saw him a proper infant, and they feared not the king's edict.\n"
	"By faith, Moyses being made great, denied himself to be the son of Pharao's daughter:\n"
	"rather choosing to be afflicted with the people of God, than to have the pleasure of temporal sin,\n"
	"esteeming the reproach of Christ, greater riches than the treasure of the Aegyptians. For he looked unto the remuneration.\n"
	"By faith, he left Aegypt: not fearing the fierceness of the king. For him that is invisible he sustained as if he had seen him.\n"
	"By faith, he celebrated the Pasch, & the shedding of the blood: that he which destroyed the first-born, might not touch them.\n"
	"By faith they passed the red sea as it were by the dry land: which the Aegyptians assaying, were devoured.\n"
	"By faith the walls of Jericho fell down, by the circuiting of seven days.\n"
	"By faith, Rahab the harlot perished not with the incredulous, receiving the spies with peace.\n"
	"And what shall I yet say? For the time will fail me telling of Gedeon, Barac, Sampson, Jephte, David, Samuel, & the prophets:\n"
	"who by faith overcame kingdoms, wrought justice, obtained promises, stopped the mouths of lions,\n"
	"extinguished the force of fire, repelled the edge of the sword, recovered of their infirmity, were made strong in battle, turned away the camp of foreigners:\n"
	"women received of resurrection their dead, and others were racked, not accepting redemption, that they might find a better resurrection.\n"
	"And others had trial of mockeries and stripes, moreover also of bands and prisons:\n"
	"they were stoned, they were hewed, they were tempted, they died in the slaughter of the sword, they went about in sheep-skins, in goats' skins, needy, in distress, afflicted:\n"
	"of whom the world was not worthy; wandering in deserts, in mountains & dens, and in caves of the earth.\n"
	"And all these being approved by the testimony of faith, received not the promise,\n"
	"God for us providing some better thing, that they without us should not be consummate.";