const char* chap129 = "And Mary and Aaron spake against Moyses, for his wife the Aethiopian,\n"
	"and they said: hath our Lord spoken by Moyses only? Hath he not spoken to us also in like manner? Which when our Lord had heard,\n"
	"(For Moyses was the mildest man above all men that dwelt upon the earth)\n"
	"immediately he spake to him, and to Aaron and Mary: Go forth you three only to the tabernacle of covenant. And when they were come forth,\n"
	"our Lord descended in the pillar of a cloud, and stood in the entry of the tabernacle calling Aaron & Mary. Who going unto him,\n"
	"he said to them: Hear my words: If there shall be among you a Prophet of the Lord, in vision will I appear to him, or in sleep I will speak to him.\n"
	"But my servant Moyses is not such an one, who in all my house is most faithful:\n"
	"for mouth to mouth I speak to him: and plainly, and not by riddles and figures doth he see the Lord. Why therefore did you not fear to detract from my servant Moyses?\n"
	"And being wrath against them, he went away:\n"
	"the cloud also departed that was over the tabernacle: and behold Mary appeared white with leprosy as it were snow. And when Aaron had looked on her, and saw her wholly covered with leprosy,\n"
	"he said to Moyses: I beseech thee my Lord, lay not upon us this sin which we have foolishly committed,\n"
	"let not this woman be as it were dead, and as an abortive that is cast forth of the mother's womb. Lo now the one half of her flesh is devoured with the leprosy.\n"
	"And Moyses cried to our Lord, saying: God, I beseech thee, heal her.\n"
	"To whom our Lord answered: If her father had spit upon her face, ought she not to have been ashamed seven days at the least? Let her be separated seven days without the camp, and afterwards she shall be called again.\n"
	"Mary therefore was shut forth without the camp seven days: and the people moved not from that place, until Mary was called again.";