const char* chap1290 = "AND therefore we also having so great a cloud of witnesses put upon us: laying away all weight and sin that compasseth us, by patience let us run to the fight proposed unto us,\n"
	"looking on the author of faith, and the consummator JESUS, who, joy being proposed unto him, sustained the Cross, contemning confusion, and sitteth on the right hand of the seat of God.\n"
	"For, think diligently upon him which sustained of sinners such contradiction against himself: that you be not wearied, fainting in your minds.\n"
	"For you have not yet resisted unto blood, repugning against sin:\n"
	"and you have forgotten the consolation, which speaketh to you, as it were to children, saying, My son, neglect not the discipline of our Lord: neither be thou wearied whiles thou art rebuked of him.\n"
	"For whom our Lord loveth, he chasteneth; & he scourgeth every child that he receiveth.\n"
	"Persevere ye in discipline. As unto children doth God offer himself to you. For what son is there, whom the father doth not correct?\n"
	"But if you be without discipline, whereof all be made partakers; then are you bastards, and not children.\n"
	"Moreover the fathers indeed of our flesh we had for instructors, and we did reverence them: shall we not much more obey the Father of spirits, and live?\n"
	"And they indeed for a time of few days, according to their will instructed us: but he, to that which is profitable in receiving of his sanctification.\n"
	"And all discipline for the present certes seemeth not to be of joy, but of sorrow: but afterward it will render to them that are exercised by it, most peaceable fruit of justice.\n"
	"For the which cause stretch up the slacked hands & the loose knees\n"
	"and make straight steps to your feet: that no man halting err, but rather be healed.\n"
	"Follow peace with all men, and holiness: without which no man shall see God:\n"
	"looking diligently lest any man be wanting to the grace of God: lest any root of bitterness springing up do hinder, and by it many be polluted.\n"
	"Lest there be any fornicator or profane person as Esau: who for one dish of meat sold his first-birth-rights.\n"
	"For know ye that afterward also desiring to inherit the benediction, he was reprobated: for he found not place of repentance, although with tears he had sought it.\n"
	"For you are not come to a palpable mount, and an accessible fire, and whirl-wind, and darkness, and storm,\n"
	"and the sound of trumpet, and voice of words, which they that heard, excused themselves, that the word might not be spoken to them,\n"
	"(for they did not bear that which was said: And if a beast shall touch the mount, it shall be stoned.\n"
	"And so terrible was it which was seen, Moyses said: I am frighted and tremble.)\n"
	"But you are come to mount Sion, and the city of the living God, heavenly Jerusalem, and the assembly of many thousand Angels,\n"
	"& the Church of the first-born, which are written in the Heavens, and the judge of all, God: and the spirits of the just made perfect,\n"
	"and the mediator of the new Testament JESUS, and the sprinkling of blood speaking better than Abel.\n"
	"See that you refuse him not^ speaking. For if they escaped not, refusing him that spake upon the earth, much more we, that turn away from him speaking to us from Heaven.\n"
	"Whose voice moved the earth then: but now he promiseth, saying, Yet once; and I will move not only the earth, but heaven also.\n"
	"And in that he sayeth, Yet once, he declareth the translation of moveable things as being made, that those things may remain which are unmovable.\n"
	"Therefore receiving an unmovable kingdom, we have grace: but the which let us serve pleasing God, with fear & reverence.\n"
	"For our God is a consuming fire.";