const char* chap1291 = "LET the charity of the fraternity abide in you.\n"
	"And hospitality do not forget, for by this, certain being not aware, have received Angels to harbour.\n"
	"Remember them in bands, as if you were bound with them; & them that labour, as yourselves also remaining in body.\n"
	"Marriage honourable in all, & the bed undefiled. For, fornicators and adulterers God will judge.\n"
	"Let your manners be without avarice: contented with things present. For he said, I will not leave thee, neither will I forsake thee.\n"
	"So that we do confidently say: Our Lord is my helper: I will not fear what man shall do to me.\n"
	"Remember your Prelates, which have spoken the word of God to you: the end of whose conversation beholding, imitate their faith.\n"
	"JESUS Christ yesterday, and today: the same also for ever.\n"
	"With various & strange doctrines be not led away. For it is best that the heart be established with grace, not with meats: which have not profited those that walk in them.\n"
	"We have an altar: whereof they have not power to eat which serve the tabernacle.\n"
	"For the bodies of those beasts, whose blood for sin is carried into the holies by the high Priest, are burned without the camp.\n"
	"For the which thing JESUS also, that he might sanctify the people by his own blood, suffered without the gate.\n"
	"Let us go forth therefore to him without the camp; carrying his reproach.\n"
	"For we have not here a permanent city: but we seek that which is to come.\n"
	"By him therefore let us offer the host of praise always to God, that is to say, the fruit of lips confessing to his name.\n"
	"And beneficence and communication do not forget, for with such hosts God is promerited.\n"
	"Obey your Prelates, and be subject to them. For they watch as being to render account for your souls: that they may do this with joy, and not mourning. For this is not expedient for you.\n"
	"Pray for us. For we have confidence that we have a good conscience, willing to converse well in all.\n"
	"And I beseech you the more to do this, that I may the more speedily be restored to you.\n"
	"And the God of peace which brought out from the dead the great Pastor of the sheep, in the blood of the eternal testament, our Lord JESUS Christ,\n"
	"fit you in all goodness, that you may do his will, doing in you that which may please before him by JESUS Christ: to whom is glory for ever and ever. Amen.\n"
	"And I desire you, brethren, that you suffer the word of consolation. For in very few words have I written to you.\n"
	"Know you our brother Timothee to be dismissed: with whom (if he come the sooner) I will see you.\n"
	"Salute all your prelates, and all the saints. The brethren of Italy salute you.\n"
	"Grace be with you all. Amen.";