const char* chap1292 = "JAMES the servant of God and of our Lord JESUS Christ, to the twelve tribes that are in dispersion, greeting.\n"
	"Esteem it, my brethren, all joy, when you shall fall into diverse tentations:\n"
	"knowing that the probation of your faith worketh patience.\n"
	"And let patience have a perfect work: that you may be perfect & entire, failing in nothing.\n"
	"But if any of you lack wisdom, let him ask of God who giveth to all men aboundantly, and upbraideth not: and it shall be given him.\n"
	"But let him ask in faith^ nothing doubting. For he that doubteth, is like to a wave of the sea, which is moved & carried about by the wind.\n"
	"Therefore let not that man think that he shall receive any thing of our Lord.\n"
	"A man double of mind is inconstant in all his ways.\n"
	"But let the humble brother glory, in his exaltation:\n"
	"and the rich, in his humility, because as the flower of grass shall he pass:\n"
	"for the sun rose with heat, & parched the grass, and the flower of it fell away, and the beauty of the shape thereof perished: so the rich man also shall wither in his ways.\n"
	"Blessed is the man that suffereth tentation: for when he hath been proved, he shall receive the crown of life, which God hath promised to them that love him.\n"
	"Let no man when he is tempted, say that he is tempted of God. For God is not a tempter of evils, and he tempteth no man.\n"
	"But every one is tempted of his own concupiscence abstracted and allured.\n"
	"Afterward concupiscence when it hath conceived, bringeth forth sin. But sin when it is consummate, engendereth death.\n"
	"Do not err therefore, my dearest brethren.\n"
	"Every best gift, and every perfect gift, is from above, descending from the Father of lights, with whom is no transmutation, nor shadowing of alteration.\n"
	"Voluntarily hath he begotten us by the word of truth, that we may be some beginning of his creature.\n"
	"You know, my dearest brethren. And let every man be swift to hear, but slow to speak, and slow to anger.\n"
	"For the anger of man worketh not the justice of God.\n"
	"For the which thing casting away all uncleanness and aboundance of malice, in meekness receive the engrafted word, which is able to save your souls.\n"
	"But be doers of the word, and not hearers only, deceiving yourselves.\n"
	"For if a man be a hearer of the word, and not a doer: he shall be compared to a man beholding the countenance of his nativity in a glass.\n"
	"For he considered himself, and went his way, and by and by forgat what an one he was.\n"
	"But he that hath looked in the law of perfect liberty, and hath remained in it, not made a forgetful hearer, but a doer of the work; this man shall be blessed in his deed.\n"
	"And if any man think himself to be religious, not bridling his tongue, but seducing his heart, this man's religion is vain.\n"
	"Religion clean and unspotted with God and the Father, is this, to visit pupils and widows in their tribulation: and to keep himself unspotted from this world.";