const char* chap1293 = "MY brethren, Have not the faith of our Lord JESUS Christ of glory in acception of persons.\n"
	"For if there shall enter into your assembly a man having a golden ring in goodly apparel, and there shall enter in a poor man in homely attire,\n"
	"and you have respect to him that is clothed with the goodly apparel, and shall say to him, Sit thou here well: but say to the poor man, Stand thou there, or sit under my foot-stool:\n"
	"do you not judge with yourselves, and are become judges of unjust cogitations?\n"
	"Hear, my dearest brethren: hath not God chosen the poor in this world, rich in faith, and heirs of the Kingdom which God hath promised to them that love him?\n"
	"But you have dishonoured the poor man. Do not the rich oppress you by might: and themselves draw you to judgements?\n"
	"Do not they blaspheme the good name that is invocated upon you?\n"
	"If not-withstanding you fulfill the royal law according to the Scriptures, Thou shalt love thy neighbour as thyself, you do well:\n"
	"but if you accept persons, you work sin, reproved of the Law as transgressors.\n"
	"And whosoever shall keep the whole Law, but offendeth in one, is made guilty of all.\n"
	"For he that said, Thou shalt not commit adultery, said also, Thou shalt not kill. And if thou do not commit adultery, but shall kill; thou art made a transgressor of the Law.\n"
	"So speak ye, and so do, as beginning to be judged by the law of liberty.\n"
	"For judgement without mercy to him that hath not done mercy. And mercy exalteth it-self above judgement.\n"
	"What shall it profit, my brethren, if a man say he hath faith, but hath not works? Shall faith be able to save him?\n"
	"And if a brother or sister be naked, and lack daily food,\n"
	"and one of you say to them, Go in peace, be warmed and filled; but you give them not the things that are necessary for the body; what shall it profit?\n"
	"So faith also, if it have not works, is dead in it-self.\n"
	"But some man saith, Thou hast faith, and I have works: shew me thy faith without works; and I will shew thee by works my faith.\n"
	"Thou believest that there is one God. Thou doest well: the devils also believe and tremble.\n"
	"But wilt thou know, o vain man, that faith without works is idle?\n"
	"Abraham our father was he not justified by works, offering Isaac his son upon the altar?\n"
	"Seest thou that faith did work with his works: and by the works the faith was consummate?\n"
	"And the Scripture was fulfilled, saying, Abraham believed God, and it was reputed him to justice, and he was called the friend of God.\n"
	"Do you see that by works a man is justified; & not by faith only?\n"
	"And in like manner also Rahab the harlot, was not she justified by works, receiving the messengers, and putting them forth another way?\n"
	"For even as the body without the spirit is dead: so also faith without works is dead.";