const char* chap1294 = "BE ye not many masters, my brethren, knowing that you receive the greater judgement.\n"
	"For in many things we offend all. If any man offend not in word; this is a perfect man. He is able also with bridle to turn about the whole body.\n"
	"And if we put bits into the mouths of horses that they may obey us, we turn about all their body also.\n"
	"And behold, the ships, whereas they be great, and are driven of strong winds: yet are they turned about with a little stern whither the violence of the director will.\n"
	"So the tongue also is certes a little member, and vaunteth great things. Behold how much fire what a great wood it kindleth?\n"
	"And the tongue, is fire, a whole world of iniquity. The tongue is set among our members, which defileth the whole body, and inflameth the wheel of our nativity, inflamed of hell.\n"
	"For all nature of beasts & fowls & serpents & of the rest is tamed & hath been tamed by the nature of man:\n"
	"But the tongue no man can tame, an unquiet evil, full of deadly poison.\n"
	"By it we bless God and the Father, & by it we curse men which are made after the similitude of God.\n"
	"Out of the self-same mouth proceedeth blessing & cursing. These things must not be so done, my brethren.\n"
	"Doth the fountain give forth out of one hole sweet and sour water?\n"
	"Can, my brethren, the fig-tree yield grapes, or the vine, figs? So neither can the salt water yield sweet.\n"
	"Who is wise and hath knowledge among you? Let him shew by good conversation his working in mildness of wisdom.\n"
	"But if you have bitter zeal, and there be contentions in your hearts; glory not and be not liars against the truth.\n"
	"For this is not wisdom descending from above: but earthly, sensual, devilish.\n"
	"For where zeal and contention is, there is inconstancy, and every perverse work.\n"
	"But the wisdom that is from above, first certes is chaste; then peaceable, modest, suasible, consenting to the good, full of mercy and good fruits, not judging, without simulation.\n"
	"And the fruit of justice, in peace is sowed, to them that make peace.";