const char* chap1296 = "GO to now ye rich men, weep, howling in your miseries which shall come to you.\n"
	"Your riches are corrupt; and your garments are eaten of moths.\n"
	"Your gold and silver is rusted; and their rust shall be for a testimony to you, and shall eat your flesh as fire. You have stored to yourselves wrath in the last days.\n"
	"Behold the hire of the work-men that have reaped your fields, which is defrauded of you, cryeth: and their cry hath entered into the ears of the Lord of Sabboth.\n"
	"You have made merry upon the earth: and in riotousness you have nourished your hearts in the day of slaughter.\n"
	"You have presented, and slain the just one: and he resisted you not.\n"
	"Be patient therefore, brethren, until the coming of our Lord. Behold, the husband-man expecteth the precious fruit of the earth: patiently bearing till he receive the timely and the lateward.\n"
	"Be you also patient, and confirm your hearts: because the coming of our Lord will approach.\n"
	"Grudge not, brethren, one against another: that you be not judged. Behold, the judge standeth before the gate.\n"
	"Take an example, brethren, of labour and patience, the Prophets, which spake in the name of our Lord.\n"
	"Behold we account them blessed that have suffered. The sufferance of Job you have heard, and the end of our Lord you have seen, because our Lord is merciful and pitiful.\n"
	"But before all things, my brethren, swear not, neither by heaven, nor by earth; nor other oath whatsoever. But let your talk be, yea, yea: no, no: that you fall not under judgement.\n"
	"Is any of you in heaviness? let him pray. Is he of a cheerful heart? let him sing.\n"
	"Is any man sick among you? let him bring in the priests of the Church, and let them pray over him, anoiling him with oil in the name of our Lord.\n"
	"And the prayer of faith shall save the sick: and our Lord shall lift him up: and if he be in sins, they shall be remitted him.\n"
	"Confess therefore your sins one to another: and pray one for another, that you may be saved. For the continual prayer of a just man availeth much.\n"
	"Elias was a man like unto us, passible: and with prayer he prayed that it might not rain upon the earth, and it rained not for three years and six months.\n"
	"And he prayed again: and the heaven gave rain, and the earth yielded her fruit.\n"
	"My brethren, if any of you shall err from the truth, and a man convert him:\n"
	"he must know that he which maketh a sinner to be converted from the error of his way, shall save his soul from death, and covereth a multitude of sins.";