const char* chap1298 = "LAYING away therefore all malice, and all guile, and simulations, and envies, and all detractions,\n"
	"as infants even now born, reasonable, milk without guile desire ye, that in it you may grow unto salvation.\n"
	"If yet you have tasted that our Lord is sweet.\n"
	"Unto whom approaching, a living stone, of men indeed reprobated, but of God elect and made honourable:\n"
	"be ye also yourselves super-edified as it were living stones, spiritual houses, a holy priesthood, to offer spiritual hosts, acceptable to God by JESUS Christ.\n"
	"For the which cause the Scripture containeth, Behold I put in Sion a principal corner-stone elect, precious. And he that shall believe in him, shall not be confounded.\n"
	"To you therefore that believe, honour: but to them that believe not, the stone which the builders rejected, the same is made into the head of the corner:\n"
	"and a stone of offence, & a rock of scandal, to them that stumble at the word, neither do believe wherein also they are put.\n"
	"But you are an elect generation, a kingly priesthood, a holy nation, a people of purchase: that you may declare his virtues, which from darkness hath called you into his marvelous light.\n"
	"Which sometime not a people: but now the people of God. Which not having obtained mercy: but now having obtained mercy.\n"
	"My dearest I beseech you as strangers & pilgrims, to refrain yourselves from carnal desires which war against the soul,\n"
	"having your conversation good among the Gentiles: that in that wherein they misreport of you as of malefactors, by the good works considering you, they may glorify God in the day of visitation.\n"
	"Be subject therefore to every human creature for God: whether it be to king, as excelling:\n"
	"or to rulers as sent by him to the revenge of malefactors, but to the praise of the good:\n"
	"for so is the will of God, that doing well you may make the ignorance of unwise men to be dumb.\n"
	"as free, and not as having the freedom for a cloak of malice, but as the servants of God.\n"
	"Honour all men. Love the fraternity. Fear God. Honour the king.\n"
	"Servants be subject in all fear to your masters, not only to the good & modest, but also to the wayward.\n"
	"For this is thank, if for conscience of God a man sustain sorrows, suffering unjustly.\n"
	"For what glory is it, if sinning, and buffeted you suffer? But if doing well you sustain patiently, this is thank before God.\n"
	"For unto this are you called: because Christ also suffered for us, leaving you an example that you may follow his steps.\n"
	"Who did no sin, neither was guile found in his mouth.\n"
	"Who when he was reviled, did not revile: when he suffered, he threatened not: but delivered himself to him that judged him unjustly.\n"
	"Who himself bare our sins in his body upon the tree: that dead to sins, we may live to justice. By whose stripes you are healed.\n"
	"For you were as sheep straying: but you be converted now to the Pastor & Bishop of your souls.";