const char* chap1299 = "IN like manner also let the women be subject to their husbands: that if any believe not the word, by the conversation of the women without the word they may be won,\n"
	"considering your chaste conversation in fear.\n"
	"Whose trimming let it not be outwardly the plaiting of hair, or laying on gold round about, or of putting on vestures:\n"
	"but the man of the heart that is hidden, in the incorruptibility of a quiet and a modest spirit, which is rich in the sight of God.\n"
	"For so sometime the holy women also that trusted in God, adorned themselves, subject to their own husbands.\n"
	"As Sara obeyed Abraham, calling him lord: whose daughters you are, doing well, and not fearing any perturbation.\n"
	"Husbands likewise, dwelling with them according to knowledge, as unto the weaker feminine vessel imparting honour, as it were to the coheirs also of the grace of life: that your prayers be not hindered.\n"
	"And in fine all of one mind, having compassion, lovers of the fraternity, merciful, modest, humble.\n"
	"not rendering evil for evil, nor curse for curse: but contrarywise, blessing: for unto this are you called, that you may by inheritance possess a benediction.\n"
	"For he that will love life, and see good days, let him refrain his tongue from evil, & his lips that they speak not guile.\n"
	"Let him decline from evil, and do good: let him inquire peace, & follow it:\n"
	"because the eyes of our Lord are upon the just, and his ears unto their prayers: but the countenance of our Lord upon them that do evil things.\n"
	"And who is he that can hurt you, if you be emulators of good?\n"
	"But & if you suffer ought for justice, blessed are ye. And the fear of them fear ye not, & be not troubled.\n"
	"But sanctify our Lord Christ in your hearts, ready always to satisfy every one that asketh you a reason of that hope which is in you:\n"
	"but with modesty and fear, having a good conscience: that in that which they speak ill of you, they may be confounded which calumniate your good conversation in Christ.\n"
	"For it is better to suffer as doing well (if the will of God will have it so) than doing ill.\n"
	"Because Christ also died once for our sins, the just for the unjust: that he might offer us to God, mortified certes in flesh, but quickened in spirit.\n"
	"In the which spirit coming he preached to them also that were in prison:\n"
	"which had been incredulous sometime, when they expected the patience of God in the days of Noe, when the ark was a building: in the which, few, that is, eight souls were saved by water.\n"
	"Whereunto Baptism being of the like form now saveth you also: not the laying away of the filth of the flesh, but the examination of a good conscience toward God by the resurrection of JESUS Christ.\n"
	"Who is on the right hand of God, swallowing death, that we might be made heirs of life everlasting: being gone into Heaven, Angels and Potentates and Powers subjected to him.";