const char* chap130 = "And the people marched from Haseroth pitching their tents in the desert of Pharan.\n"
	"And there our Lord spake to Moyses, saying:\n"
	"Send men that may view the Land of Chanaan, which I will give to the children of Israel, one of every tribe, of the Princes.\n"
	"Moyses did that which our Lord had commanded, from the desert of Pharan sending principal men, whose names be these.\n"
	"Of the tribe of Ruben, Sammua the son of Zechur.\n"
	"Of the tribe of Simeon, Saphat the son of Huri.\n"
	"Of the tribe of Juda, Caleb the son of Jephone.\n"
	"Of the tribe of Issachar, Igal the son of Joseph.\n"
	"Of the tribe of Ephraim, Osee the son of Nun.\n"
	"Of the tribe of Benjamin, Phalti the son of Raphu.\n"
	"Of the tribe of Zabulon, Geddiel the son of Sodi.\n"
	"Of the tribe of Joseph, of the sceptre of Manasses, Gaddi, the son of Susi.\n"
	"Of the tribe of Dan, Ammiel the son of Gemalli.\n"
	"Of the tribe of Aser, Sthur the son of Michael.\n"
	"Of the tribe of Nephthali, Nahabi the son of Vapsi.\n"
	"Of the tribe of Gad, Guel the son of Machi.\n"
	"These are the names of the men, whom Moyses sent to view the Land: and he called Osee the son of Nun, Josue.\n"
	"Moyses therefore sent them to view the Land of Chanaan, and said to them: Go up by the south side. And when you shall come to the mountains,\n"
	"view the Land, what it is: and the people that are the inhabitants thereof, whether they be strong or weak: few in number or many:\n"
	"the land it-self, whether it be good or bad: what manner of cities, walled or without walls:\n"
	"the ground, fat or barren, woody or without trees. Be of good courage, and bring us of the fruits of the Land. And it was the time when now the first ripe grapes are to be eaten.\n"
	"And when they were gone up, they viewed the Land from the desert of Sin, unto Rohob as you enter to Emath.\n"
	"And they went up at the south side, & came to Hebron, where were Achiman and Sisai & Tholmai the sons of Enac, for Hebron was built seven years before Tanis the city of Aegypt.\n"
	"And going forward as far as the Torrent of cluster, they cut off a branch with the grapes thereof, which two men carried upon a lever. They took of the pomegranates also & of the figs of that place:\n"
	"which was called Nehelescol, that is to say, the Torrent of cluster, for that thence the children of Israel had carried a cluster.\n"
	"And the discoverers of the Land returning after forty days, having circuited all the country,\n"
	"came to Moyses & Aaron and to all the assembly of the children of Israel into the desert of Pharan; which is in Cades. And speaking to them and to all the multitude they shewed the fruits of the Land:\n"
	"and reported, saying: We came into the Land to which thou didst send us, which in very deed floweth with milk and honey, as by these fruits may be known:\n"
	"but it hath very strong inhabitants, and cities great and walled. The stock of Enac we saw there.\n"
	"Amalec dwelleth in the south, the Hetheite and the Jebusite and the Amorrhite in the mountains: but the Chananite abideth beside the sea and about the streams of Jordan.\n"
	"Among these things Caleb appeasing the murmuring of the people that rose against Moyses, said: Let us go up and possess the Land because we may obtain it.\n"
	"But the others, that had been with him, said: No, we are not able to go up to this people, because it is stronger than we.\n"
	"And they detracted from the Land, which they had viewed, before the children of Israel, saying: The Land, which we have viewed, devoureth her inhabitants: the people, that we beheld, is of a tall stature.\n"
	"There we saw certain monsters of the sons of Enac, of the giant's kind: to whom being compared, we seemed as it were locusts.";