const char* chap1300 = "CHRIST therefore having suffered in the flesh, be you also armed with the same cogitation. Because he that hath suffered in the flesh, hath ceased from sins:\n"
	"that now not after the desires of men, but according to the will of God he live the rest of his time in the flesh.\n"
	"For the time past sufficeth (to accomplish the will of the Gentiles) them that have walked in riotousness, desires, excess of wine, banquetings, potations, and unlawful services of idols.\n"
	"Wherein they marvel blaspheming, you not concurring into the same confusion of riotousness.\n"
	"Who shall render account to him, which is ready to judge the living and the dead.\n"
	"For, for this cause also was it evangelized to the dead: that they may be judged indeed according to men, in the flesh: but may live according to God in the Spirit.\n"
	"And the end of all shall approach. Be wise therefore, and watch in prayers.\n"
	"But before all things, having mutual charity continual among yourselves: because charity covereth the multitude of sins.\n"
	"Using hospitality one toward another without murmuring.\n"
	"Every one as he hath received grace, ministering the same one toward another: as good dispensers of the manifold grace of God.\n"
	"If any man speak, as the words of God. If any man minister, as of the power, which God administereth. That in all things God may be honoured by JESUS Christ: to whom is glory & empire for ever and ever. Amen.\n"
	"My dearest, think it not strange in the fervour which is to you for a tentation, as though some new thing happened to you:\n"
	"But communicating with the passions of Christ, be glad, that in the revelation also of his glory you may be glad rejoicing.\n"
	"If you be reviled in the name of Christ, you shall be blessed: because that which is of the honour, glory, and virtue of God, and the Spirit which is his, shall rest upon you.\n"
	"But let none of you suffer as a murderer, or a thief, or a railer, or a coveter of other men's things.\n"
	"But if as a Christian, let him not be ashamed, but let him glorify God in this name.\n"
	"For the time is that judgement begin of the house of God. And if first of us, what shall be the end of them that believe not the Gospel of God?\n"
	"And if the just man shall scarce be saved, where shall the impious & sinner appear?\n"
	"Therefore they also that suffer according to the will of God, let them commend their souls to the faithful Creator, in good deeds.";