const char* chap1301 = "THE seniors therefore that are among you, I beseech, myself a fellow senior with them & a witness of the Passions of Christ, who am also partaker of the glory which is to be revealed in time to come:\n"
	"feed the flock of God which is among you^ providing not by constraint, but willingly according to God: neither for filthy lucre sake, but voluntarily:\n"
	"neither as over-ruling the Clergy, but made examples of the flock from the heart.\n"
	"And when the Prince of pastors shall appear, you shall receive the incorruptible crown of glory.\n"
	"In like manner ye young men be subject to the seniors. And do ye all insinuate humility one to another, because God resisteth the proud, and to the humble he giveth grace.\n"
	"Be ye humbled therefore under the mighty hand of God, that he may exalt you in the time of visitation:\n"
	"casting all your carefulness upon him, because he hath care of you.\n"
	"Be sober and watch: because your adversary the devil as a roaring lion goeth about, seeking whom he may devour.\n"
	"Whom resist ye, strong in faith: knowing that the self-same affliction is made to that your fraternity which is in the world.\n"
	"But the God of all grace, which hath called us unto his eternal glory in Christ JESUS, he will perfit you having suffered a little, and confirm, and stablish you.\n"
	"To him be glory and empire for ever and ever. Amen.\n"
	"By Sylvanus, a faithful brother to you, as I think, I have briefly written: beseeching & testifying that this is the true grace of God, wherein you stand.\n"
	"The Church saluteth you, that is in Babylon, co-elect: and Mark my son.\n"
	"Salute one another in a holy kiss. Grace be to all you which are in Christ JESUS. Amen.";