const char* chap1310 = "THE Senior to the Lady Elect and her children, whom I love in truth, and not I only, but also all that have known the truth,\n"
	"for the truth which abideth in us, and shall be with us for ever.\n"
	"Grace be with you, mercy, peace from God the Father, and from Christ JESUS the Son of the Father in truth, and charity.\n"
	"I was exceeding glad, because I have found of thy children walking in truth, as we have received commandment of the Father.\n"
	"And now I beseech thee Lady, not as writing a new commandment to thee, but that which we have had from the beginning, that we love one another.\n"
	"And this is charity, that we walk according to his commandments. For this is the commandment, that as you have heard from the beginning, you walk in the same:\n"
	"because many seducers are gone out into the world, which do not confess JESUS Christ to have come into flesh: this is a seducer and an Antichrist.\n"
	"Look to yourselves, that you lose not the things which you have wrought: but that you may receive a full reward.\n"
	"Every one that revolteth, and persisteth not in the doctrine of Christ, hath not God. He that persisteth in the doctrine, the same hath both the Father, and the Son.\n"
	"If any man come to you, and bring not this doctrine, receive him not into the house, nor say, God save you, unto him.\n"
	"For he that saith unto him, God save you, communicateth with his wicked works.\n"
	"Having more things to write unto you: I would not by paper and ink: for I hope that I shall be with you, and speak mouth to mouth: that your joy may be full.\n"
	"The children of thy sister Elect salute thee.";