const char* chap1315 = "AND to the Angel of the Church of Sardis, write: Thus saith he that hath the seven Spirits of God, and the seven stars: I know thy works, that thou hast the name that thou livest, and thou art dead.\n"
	"Be vigilant, and confirm the rest of the things which were to die. For I find not thy works full before my God.\n"
	"Have in mind therefore in what manner thou hast received and heard: and keep, and do penance. If therefore thou watch not, I will come to thee as a thief, and thou shalt not know what hour I will come to thee.\n"
	"But thou hast a few names in Sardis, which have not defiled their garments: and they shall walk with me in whites, because they are worthy.\n"
	"He that shall overcome, shall thus be vested in white garments, and I will not put his name out of the book of life, and I will confess his name before my Father, and before his Angels.\n"
	"He that hath an ear, let him hear what the Spirit saith to the Churches.\n"
	"And to the Angel of the Church of Philadelphia write: Thus saith the Holy one and the True one, he that hath the key of David; he that openeth, and no man shutteth, shutteth, and no man openeth:\n"
	"I know thy works. Behold I have given before thee a door opened which no man can shut: because thou hast a little power, and hast kept my word, and hast not denied my name.\n"
	"Behold I will give of the synagogue of Satan, which say they be Jews, and are not, but do lie. Behold I will make them come and adore before thy feet. And they shall know that I have loved thee.\n"
	"Because thou hast kept the word of my patience, and I will keep thee from the hour of tentation, which shall come upon the whole world to tempt the inhabitants on the earth.\n"
	"Behold I come quickly: hold that which thou hast, that no man take thy crown.\n"
	"He that shall overcome, I will make him a pillar in the temple of my God: and he shall go out no more: and I will write upon him the name of my God, and the name of the city of my God, new Jerusalem, which descendeth out of Heaven from my God, and my new name.\n"
	"He that hath an ear, let him hear what the Spirit saith to the Churches.\n"
	"And to the Angel of the Church of Laodicia write: Thus saith Amen, the faithful and true witness, which is the beginning of the creature of God:\n"
	"I know thy works, that thou art neither cold, nor hot. I would thou were cold, or hot.\n"
	"But because thou art lukewarm, and neither cold nor hot, I will begin to vomit thee out of my mouth.\n"
	"Because thou sayest, That I am rich, and enriched, and lack nothing; and knowest not that thou art a miser, and miserable, and poor, and blind, and naked.\n"
	"I counsel thee to buy of me gold fire-tried, that thou mayest be made rich: and mayest be clothed in white garments, that the confusion of thy nakedness appear not: and with eye-salve anoint thine eyes, that thou mayest see.\n"
	"I, whom I love, do rebuke and chastise. Be zealous therefore and do penance.\n"
	"Behold I stand at the door and knock. If any man shall hear my voice, and open to me the gate, I will enter in to him, and will sup with him, and he with me.\n"
	"He that shall overcome, I will give unto him to sit with me in my throne: as I also have overcome, and have sitten with my Father in his throne.\n"
	"He that hath an ear, let him hear what the Spirit saith to the Churches.";