const char* chap1320 = "AND when he had opened the seventh seal, there was made silence in heaven, as it were half an hour.\n"
	"And I saw seven Angels standing in the sight of God: and there were given to them seven trumpets.\n"
	"And another Angel came, and stood before the altar, having a golden censer: and there were given to him many incenses that he should give of the prayers of all saints upon the altar of gold, which is before the throne of God.\n"
	"And the smoke of the incenses of the prayers of the saints ascended from the hand of the Angel before God.\n"
	"And the Angel took the censer, & filled it of the fire of the altar, and cast it on the earth, and there were made thunders & voices and lightnings, and a great earth-quake.\n"
	"And the seven Angels which had the seven trumpets, prepared themselves to sound with the trumpet.\n"
	"And the first Angel sounded with the trumpet, and there was made hail and fire, mingled in blood, and it was cast on the earth, and the third part of the earth was burnt, & the third part of trees was burnt, and all green grass was burnt.\n"
	"And the second Angel sounded with the trumpet: and as it were a great mountain burning with fire, was cast into the sea, & the third part of the sea was made blood:\n"
	"and the third part of those creatures died, which had lives in the sea, and the third part of the ships perished.\n"
	"And the third Angel sounded with the trumpet, and a great star fell from heaven, burning as it were a torch, and it fell on the third part of the floods, and on the fountains of waters:\n"
	"and the name of the star is called worm-wood. And the third part of the waters was made into worm-wood: and many men died of the waters, because they were made bitter.\n"
	"And the fourth Angel sounded with the trumpet, and the third part of the sun was smitten, and the third part of the moon, and the third part of the stars, so that the third part of them was darkened, and of the day there shined not the third part, and of the night in like manner,\n"
	"And I looked, and heard the voice of one eagle flying through the midst of heaven, saying with a loud voice: Woe, woe, woe to the inhabiters on the earth: because of the rest of the voices of the three Angels which were to sound with the trumpet.";