const char* chap1325 = "AND I saw a beast coming up from the sea, having seven heads, and ten horns, & upon his horns ten diadems, and upon his heads names of blasphemy.\n"
	"And the beast which I saw, was like to a libard, and his feet as of a bear, and his mouth, as the mouth of a lion. And the dragon gave him his own force and great power.\n"
	"And I saw one of his heads as it were slain to death: and the wound of his death was cured. And all the earth was in admiration after the beast.\n"
	"And they adored the dragon which gave power to the beast: and they adored the beast, saying: Who is like to the beast? and who shall be able to fight with it?\n"
	"And there was given to it a mouth speaking great things and blasphemies: and power was given to it to work two and forty months.\n"
	"And he opened his mouth unto blasphemies toward God, to blaspheme his name, & his tabernacle, & those that dwell in heaven.\n"
	"And it was given unto him to make battail with the saints, & to overcome them. And power was given him upon every tribe and people, and tongue, and nation,\n"
	"and all that inhabit the earth, adored it, whose names be not written in the book of life of the Lamb, which was slain from the beginning of the world.\n"
	"If any man have an ear, let him hear.\n"
	"He that shall lead into captivity, goeth into captivity: he that shall kill in the sword, he must be killed with the sword. Here is the patience and the faith of saints.\n"
	"And I saw another beast coming up from the earth: and he had two horns, like to a lamb, & he spake as a dragon.\n"
	"And all the power of the former beast he did in his sight: and he made the earth and the inhabitants therein, to adore the first beast, whose wound of death was cured.\n"
	"And he did many signs, so that he made also fire to come down from heaven unto the earth in the sight of men.\n"
	"And he seduceth the inhabitants on the earth through the signs which were given him to do in the sight of the beast, saying to them that dwell on the earth, that they should make the image of the beast which hath the stroke of the sword, and lived.\n"
	"And it was given him to give spirit to the image of the beast, and that the image of the beast should speak: and should make, that whosoever shall not adore the image of the beast, be slain.\n"
	"And he shall make all, little & great, and rich, and poor, and free-men, and bond-men, to have a character in their right hand, or in their foreheads.\n"
	"And that no man may buy or sell, but he that hath the character, or the name of the beast, or the number of his name.\n"
	"Here is wisdom. He that hath understanding, let him count the number of the beast. For it is the number of a man; and the number of him is six hundred sixty six.";