const char* chap1326 = "AND I looked, & behold a Lamb stood upon mount Sion, & with him an hundred forty four thousand having his name, and the name of his Father written in their foreheads.\n"
	"And I heard a voice from heaven, as the voice of many waters, and as the voice of great thunder: and the voice which I heard, as of harpers harping on their harps.\n"
	"And they sang as it were a new song before the seat and before the four beasts, and the Seniors, & no man could say the song, but those hundred forty four thousand, that were bought from the earth.\n"
	"These are they which were not defiled with women. For they are virgins. These follow the Lamb whithersoever he shall go. These were bought from among men, the first fruits to God and the Lamb:\n"
	"and in their mouth there was found no lie. For they are without spot before the throne of God.\n"
	"And I saw another Angel flying through the midst of heaven, having the eternal Gospel, to evangelize unto them that sit upon the earth, and upon every nation, and tribe, and tongue, and people;\n"
	"saying with a loud voice: Fear our Lord, and give him honour, because the hour of his judgement is come: and adore ye him that made heaven and earth, the sea and all things that are in them, and the fountains of waters.\n"
	"And another Angel followed, saying: Fallen fallen is that great Babylon, which of the wine of the wrath of her fornication made all nations to drink.\n"
	"And the third Angel followed them, saying with a loud voice: If any man adore the beast and his image, and receive the character in his forehead, or in his hand;\n"
	"he also shall drink of the wine of the wrath of God, which is mingled with pure wine in the cup of his wrath, and shall be tormented with fire & brimstone in the sight of the holy Angels and before the sight of the Lamb.\n"
	"And the smoke of their torments shall ascend for ever and ever: neither have they rest day and night, which have adored the beast, and his image, and if any man take the character of his name.\n"
	"Here is the patience of saints, which keep the commandments of God and the faith of JESUS.\n"
	"And I heard a voice from heaven, saying to me: Write, Blessed are the dead which die in our Lord. From hence-forth now, saith the Spirit, that they rest from their labours. For their works follow them.\n"
	"And I saw, and behold a white cloud: and upon the cloud one sitting like to the Son of man, having on his head a crown of gold, and in his hand a sharp sickle.\n"
	"And another Angel came forth from the temple, crying with a loud voice to him that sat upon the cloud: Thrust in thy sickle, and reap, because the hour is come to reap, for the harvest of the earth is dry.\n"
	"And he that sat upon the cloud, thrust his sickle into the earth, and the earth was reaped.\n"
	"And another Angel came forth from the temple which is in heaven, himself also having a sharp sickle.\n"
	"And another Angel came forth from the altar, which had power over the fire: and he cried with a loud voice to him that had the sharp sickle, saying: Thrust in thy sharp sickle, and gather the clusters of the vineyard of the earth: because the grapes thereof be ripe.\n"
	"And the Angel thrust his sharp sickle into the earth, and gathered the vineyard of the earth, & cast it into the great press of the wrath of God:\n"
	"and the press was trodden without the city, and blood came forth out of the press, up to the horse bridles, for a thousand six hundred furlongs.";