const char* chap1329 = "AND there came one of the seven Angels which had the seven vials, & spake with me, saying: Come, I will shew thee the damnation of the great harlot, which sitteth upon many waters.\n"
	"with whom the kings of the earth have fornicated, & they which inhabit the earth have been drunk of the wine of her whoredom.\n"
	"And he took me away in spirit into the desert. And I saw a woman sitting upon a scarlet coloured beast, full of names of blasphemy, having seven heads, and ten horns.\n"
	"And the woman was clothed round about with purple and scarlet, and gilted with gold, and precious stone, and pearls, having a golden cup in her hand, full of the abomination & filthiness of her fornication.\n"
	"And in her forehead a name written, Mystery: Babylon the great, mother of the fornications and the abominations of the earth.\n"
	"And I saw the woman drunken of the blood of Saints, and of the blood of the Martyrs of JESUS. And I marveled when I had seen her, with great admiration.\n"
	"And the Angel said to me: Why doest thou marvel? I will tell thee the mystery of the woman, and of the beast that carrieth her, which hath the seven heads, and the ten horns.\n"
	"The beast which thou sawest, was, and is not, and shall come up out of the bottomless depth, and go into destruction: and the inhabitants on the earth (whose names are not written in the book of life from the making of the world) shall marvel, seeing the beast that was, and is not.\n"
	"And here is understanding, that hath wisdom. The seven heads, are seven hills, upon which the woman sitteth, and they are seven kings.\n"
	"Five are fallen, one is, and another is not yet come: and when he shall come, he must tarry a short time.\n"
	"And the beast which was, and is not: the same also is the eight, and is of the seven, & goeth into destruction.\n"
	"And the ten horns which thou sawest, are ten kings, which have not yet received kingdom, but shall receive power as kings one hour after the beast.\n"
	"These have one counsel and force: and their power they shall deliver to the beast.\n"
	"These shall fight with the Lamb, and the Lamb shall overcome them, because he is Lord of lords, and King of kings, and they that are with him, called, and elect, and faithful.\n"
	"And he said to me: The waters which thou sawest where the harlot sitteth, are peoples, and nations, and tongues.\n"
	"And the ten horns which thou sawest in the beast: these shall hate the harlot, and shall make her desolate and naked, and shall eat her flesh, and her they shall burn with fire.\n"
	"For God hath given into their hearts, to do that which pleaseth him: that they give their kingdom to the beast, till the words of God be consummate.\n"
	"And the woman which thou sawest: is the great city, which hath kingdom over the kings of the earth.";