const char* chap133 = "And behold Core the son of Isaar, the son of Caath, the son of Levi, and Dathan and Abiron the sons of Eliab, Hon also the son of Pheleth of the children of Ruben,\n"
	"rose against Moyses, & other of the children of Israel, two hundred fifty men, princes of the synagogue, and which in the time of assembly were called by name.\n"
	"And when they had stood up against Moyses and Aaron, they said: Let it suffice you, that all the multitude consisteth of holy ones, and our Lord is among them: Why lift you up yourselves above the people of our Lord?\n"
	"Which when Moyses had heard, he fell flat on his face:\n"
	"and speaking to Core and all the multitude, he said: In the morning our Lord will make it known who pertain to him, and the holy he will join to himself: and whom he shall choose, they shall approach to him.\n"
	"This do therefore: Take every man their censers, thou Core, and all thy councel:\n"
	"and taking fire in them tomorrow, put upon it incense before our Lord: and whom soever he shall choose, the same shall be holy: you do much exalt yourselves ye sons of Levi.\n"
	"And he said again to Core: Hear ye sons of Levi:\n"
	"Is it a small thing unto you, that the God of Israel hath separated you from all the people, and joined you to himself, that you should serve him in the service of the tabernacle, and should stand before the full assembly of the people, & should minister to him?\n"
	"did he therefore make thee and all thy brethren the sons of Levi to approach unto him, that you should challenge unto you the priesthood also,\n"
	"& all thy company should stand against our Lord? For what is Aaron that you murmur against him?\n"
	"Moyses therefore sent to call Dathan and Abiron the sons of Eliab. Who answered: We come not.\n"
	"Why, is it a small matter to thee that thou hast brought us out of a land, that flowed with milk and honey, to kill us in the desert, unless thou rule also like a Lord over us?\n"
	"Indeed^ hast thou brought us into a land, that floweth with rivers of milk and honey, and hast thou given us possessions of fields and vineyards? What, wilt thou pluck out our eyes also? We come not.\n"
	"Moyses therefore being very wrath, said to our Lord: Respect not their sacrifices: thou knowest that I have not taken of them so much as a little ass at any time, neither have afflicted any of them.\n"
	"And he said to Core: Thou, and all thy congregation stand ye apart before our Lord, and Aaron tomorrow apart.\n"
	"Take every one your censers, and put incense upon them, offering to our Lord two hundred fifty censers: Let Aaron also hold his censer.\n"
	"Which when they had done, Moyses and Aaron standing,\n"
	"& had heaped together all the multitude against them to the door of the tabernacle, the glory of our Lord appeared to them all.\n"
	"And our Lord speaking to Moyses and Aaron, said:\n"
	"Separate yourselves from the midst of this congregation, that I may suddenly destroy them.\n"
	"Who fell flat on their face, and said: Most mighty God of the spirits of all flesh, when one sinneth, shall thy wrath rage against all?\n"
	"And our Lord said to Moyses:\n"
	"Command the whole people that they separate themselves from the tabernacles of Core and Dathan and Abiron.\n"
	"And Moyses arose, and went to Dathan and Abiron: and the ancients of Israel following him,\n"
	"he said to the multitude: Depart from the tabernacles of the impious men, and touch not the things that pertain to them, lest you be wrapped in their sins.\n"
	"And when they were departed from their tents round about, Dathan and Abiron coming forth stood in the entry of their pavilions with their wives and children, and all the multitude.\n"
	"And Moyses said: In this you shall know that our Lord hath sent me to do all things that you see, and that I have not forged them of my own mind:\n"
	"If they die the accustomed death of men, and if the plague, wherewith others also are wont to be visited, do visit them, our Lord did not send me:\n"
	"but if our Lord do a new thing, that the earth opening her mouth swallow them down, and all things that pertain to them, and they descend quick into hell, you shall know that they have blasphemed our Lord.\n"
	"Immediately therefore as he ceased to speak, the earth brake a-sunder under their feet:\n"
	"and opening her mouth, devoured them with their tabernacles & all their substance.\n"
	"and they went down into hell quick covered with the ground, and perished out of the midst of the multitude.\n"
	"But all Israel, that stood round about, fled at the cry of them that perished, saying: Lest perhaps the earth swallow us also.\n"
	"But a fire also coming forth from our Lord, slew the two hundred fifty men, that offered the incense.\n"
	"And our Lord spake to Moyses, saying:\n"
	"Command Eleazar the son of Aaron the Priest that he take up the censers that lie in the burning fire, and that he sprinkle the fire hither and thither: because they be sanctified\n"
	"in the deaths of the sinners: and let him beat them into plates, and fasten them to the altar, because there hath been offered incense in them to the Lord, and they are sanctified, that the children of Israel may see them for a sign and a monument.\n"
	"Eleazar therefore the Priest took the brazen censers, wherein they had offered, whom the burning fire devoured, and beat them into plates, fastening them to the altar:\n"
	"that the children of Israel afterward might have, wherewith to be admonished, that no stranger approach, and he that is not of the seed of Aaron, to offer incense to our Lord, lest he suffer as Core hath suffered, & all his congregation, according as our Lord spake to Moyses.\n"
	"And all the multitude of the children of Israel murmured the day following against Moyses & Aaron, saying: You have killed the people of our Lord.\n"
	"And when there rose a sedition, and the tumult grew farther,\n"
	"Moyses and Aaron fled to the tabernacle of covenant. Which after they were entered the cloud covered it, and the glory of our Lord appeared.\n"
	"And our Lord said to Moyses:\n"
	"Depart from the midst of this multitude, even now will I destroy them. And as they lay upon the ground,\n"
	"Moyses said to Aaron: Take the censer, and drawing fire from the altar, put incense upon it, going quickly to the people to pray for them: for even now is the wrath come forth from our Lord, & the plague rageth.\n"
	"Which when Aaron had done, and had run to the midst of the multitude, which now the burning fire did waste, he offered the incense:\n"
	"and standing between the dead and the living, he prayed for the people, and the plague ceased.\n"
	"And there were, that were strucken, fourteen thousand and seven hundred men, beside them that had perished in the sedition of Core.\n"
	"And Aaron returned to Moyses unto the door of the tabernacle of covenant after that the destruction was ceased.";