const char* chap135 = "And our Lord said to Aaron: Thou, and thy sons, and the house of thy father with thee shall bear the iniquity of the Sanctuary: both thou & thy sons together shall bear the sins of your priesthood.\n"
	"But thy brethren also of the tribe of Levi, and the sceptre of thy father take with thee, and let them be ready at hand, and minister to thee: but thou and thy sons shall minister in the tabernacle of testimony.\n"
	"And the Levites shall watch upon thy precepts, and upon all the works of the tabernacle: so notwithstanding, that they approach not to the vessels of the Sanctuary and to the altar, lest both they die, and you perish withal.\n"
	"But let them be with thee, and watch in the custodies of the tabernacle, and in all the ceremonies thereof. A stranger shall not join with you.\n"
	"Watch in the custody of the Sanctuary, and in the ministry of the altar: lest indignation rise upon the children of Israel.\n"
	"I have given you your brethren the Levites out of the midst of the children of Israel, and have delivered them a gift to the Lord, to serve in the ministries of his tabernacle.\n"
	"And thou and thy sons look to your priesthood: and all things that pertain to the service of the altar, and that are within the veil, shall be executed by the Priests. If any stranger approach, he shall be slain.\n"
	"And our Lord spake to Aaron, behold I have given thee the custody of my first fruits. All things that are sanctified of the children of Israel, have I delivered to thee and to thy sons for the priestly office, as everlasting ordinances.\n"
	"These things therefore shalt thou take of those, that are sanctified, and are offered to the Lord. All oblation, and sacrifice, and whatsoever is rendered to me for sin and offence, & becometh Holy of holies, shall be thine, and thy sons.\n"
	"In the Sanctuary shalt thou eat it: males only shall eat thereof, because it is to thee a consecrated thing.\n"
	"But the first fruits, which the children of Israel shall vow and offer, I have given thee, and thy sons, and thy daughters for a perpetual right. He that is clean in thy house, shall eat them.\n"
	"All the best of oil, and wine, and corn, whatsoever first fruits they offer to the Lord, I have given them to thee.\n"
	"Of fruits all the first, that the ground bringeth forth, and are brought to the Lord, shall turn to thy uses: he that is clean in thy house, shall eat them.\n"
	"Every thing that the children of Israel render by vow, shall be thine.\n"
	"Whatsoever first breaketh forth from the matrice of all flesh, which they offer to the Lord, whether it be of men, or of beasts, shall be thy right: yet so, that for the first born of man thou take a price, and every beast that is unclean thou cause to be redeemed,\n"
	"whose redemption shall be after one month, for five sicles of silver, by the weight of the Sanctuary. A sicle hath twenty oboles.\n"
	"But the first-born of beef and sheep and goat thou shalt not cause to be redeemed, because they are sanctified to the Lord, only the blood of them thou shalt pour upon the altar, and the fat thou shalt burn for a most sweet odour to the Lord.\n"
	"But the flesh shall turn to thy use, as the consecrated breast, and the right shoulder, shall be thine.\n"
	"All the first fruits of the Sanctuary which the children of Israel offer to the Lord, have I given thee and thy sons, and daughters for a perpetual right. A covenant of salt is it for ever before the Lord, to thee and to thy sons.\n"
	"And our Lord said to Aaron: In their land you shall possess nothing, neither shall you have a portion among them: I am thy portion and inheritance in the midst of the children of Israel.\n"
	"And to the sons of Levi I have given all the tithes of Israel in possession for the ministry wherewith they serve me in the tabernacle of covenant:\n"
	"that the children of Israel approach not any more to the tabernacle, nor commit deadly sin,\n"
	"only the sons of Levi serving me in the tabernacle, and bearing the sins of the people. It shall be an everlasting ordinance in your generations. No other thing shall they possess,\n"
	"being content with the oblation of tithes, which I have separated for their uses and necessaries.\n"
	"And our Lord spake to Moyses, saying:\n"
	"Command the Levites, and denounce unto them: When you shall receive of the children of Israel the tithes, which I have given you, offer first fruits of them to the Lord, that is to say, the tenth part of the tenth:\n"
	"that it may be reputed to you for an oblation of first fruits, as well of the barn floors as of the presses,\n"
	"and of all things whereof you receive tithes, the first fruits offer to the Lord, and give them to Aaron the Priest.\n"
	"All things that you shall offer of the tithes, and shall separate for the gifts of the Lord, they shall be the best and chosen things.\n"
	"And thou shalt say to them: If you offer all the goodly and the better things of the tithes, it shall be reputed to you as if you had given first fruits of the barn floor and the press:\n"
	"and you shall eat them in all your places, as well you as your families: because it is the reward for the ministry, wherewith you serve in the tabernacle of testimony.\n"
	"And you shall not sin in this point, reserving the principal and fat things to yourselves, lest you pollute the oblations of the children of Israel, and die.";