const char* chap138 = "Which when the Chananite King of Arad, who dwelt toward the south, had heard, to wit, that Israel was come by the way of the spies, he fought against them, and being victor, he took the prey of them.\n"
	"But Israel binding himself by vow to our Lord, said: If thou wilt deliver this people into my hand, I will destroy their cities.\n"
	"And our Lord heard the prayers of Israel, and delivered the Chananite, whom they slew overthrowing their cities: and they called the name of that place Horma, that is to say, Anathema.\n"
	"And they marched also from the mountain Hor, by the way that leadeth to the Red sea, that they might compass the land of Edom. And the people began to be weary of the journey and labour:\n"
	"and speaking against God and Moyses, they said: Why didst thou bring us out of Aegypt, to die in the wilderness? There wanteth bread, waters there are none: our soul now loatheth at this most light meat.\n"
	"Wherefore our Lord sent upon the people fiery serpents, at whose plagues and the deaths of very many,\n"
	"they came to Moyses, and said: We have sinned, because we have spoken against our Lord and thee: Pray that he take from us the serpents. And Moyses prayed for the people\n"
	"and our Lord spake to him: Make a brazen serpent, and set it for a sign: he that being strucken looketh on it, shall live.\n"
	"Moyses therefore made A BRAZEN SERPENT, and set it for a sign: whom when they that were strucken looked on, they were healed.\n"
	"And the children of Israel marching camped in Oboth.\n"
	"Whence departing they pitched their tents in Jeabarim, in the wilderness, that looketh toward Moab against the east part.\n"
	"And removing from thence, they came to the Torrent Zared.\n"
	"Which they forsaking camped against Arnon, which is in the desert, & standeth out in the borders of the Amorrhite. For Arnon is the border of Moab, dividing the Moabites & the Amorrheites.\n"
	"Whereof it is said in the book of the wars of our Lord: As he did in the Red sea, so will he do in the streams of Arnon.\n"
	"The rocks of the torrents were bowed, that they might rest in Ar, and lie in the borders of the Moabites.\n"
	"From that place appeared the well, whereof our Lord spake to Moyses: Gather the people together, and I will give them water.\n"
	"Then Israel sang this verse: Arise the well. They sang thereto:\n"
	"The well, which the Princes digged, & the Captains of the multitude prepared in the lawgiver, and in their staves. And they marched from the wilderness to Mathana.\n"
	"From Mathana unto Nahaliel: from Nahaliel unto Bamoth\n"
	"From Bamoth is a valley in the country of Moab, in the top of Phasga, which looketh toward the desert.\n"
	"And Israel sent messengers to Sehon King of the Amorrheites, saying:\n"
	"I beseech thee that I may have licence to pass through thy land: we will not go aside into the fields and the vineyards, we will not drink waters of the wells, we will go the king's high way, till we be past thy borders.\n"
	"Who would not grant that Israel should pass by his borders; but rather gathering an army, went forth to meet them in the desert, and came unto Jasa, and fought against them.\n"
	"Of whom he was strucken in the edge of the sword, and his land was possessed from Arnon unto Jeboc, and to the children of Ammon: for the borders of the Ammonites were kept with a strong garrison.\n"
	"Israel therefore took all his cities, and dwelt in the cities of the Amorrhite, to wit, in Hesebon, and the villages thereof.\n"
	"The city Hesebon was Sehon's the king of the Amorrhite, who fought against the king of Moab: and took all the land, that had been of his dominion, as far as Arnon.\n"
	"Therefore it is said in the proverb: Come into Hesebon, let the city of Sehon be built and erected:\n"
	"A fire went forth from Hesebon, a flame from the town of Sehon, & devoured Ar of the Moabites, and the inhabitants of the high places of Arnon.\n"
	"Woe to thee Moab, thou art undone people of Chamos. He hath given his sons into flight, and his daughters into captivity to Sehon the King of the Amorrheites.\n"
	"There yoke is perished from Hesebon unto Dibon, they came weary into Nophe, and unto Medaba.\n"
	"Israel therefore dwelt in the Land of the Amorrhite.\n"
	"And Moyses sent some to take a view of Jazer: Whose villages they took, and possessed the inhabitants.\n"
	"And they turned themselves, and went up by the way of Basan, and Og the king of Basan came against them with all his people, to fight in Edrai.\n"
	"And our Lord said to Moyses: Fear him not, for into thy hand I have delivered him, and all his people, and land: and thou shalt do to him as thou didst to Sehon the king of the Amorrheites, the inhabiter of Hesebon.\n"
	"They therefore smote him also with his sons, and all his people unto utter destruction, and they possessed his land.";