const char* chap139 = "And marching forward they camped in the champion country of Moab, where Jericho is situated beyond Jordan.\n"
	"And Balac the son of Sephor seeing all things that Israel had done to the Amorrhite,\n"
	"and that the Moabites were in great fear of him, and could not sustain his assault,\n"
	"he said to the elders of Madian: So will this people destroy all that dwell in our coasts, as the oxe is wont to eat the grass unto the very roots. And he was at the same time king in Moab.\n"
	"He sent therefore messengers to Balaam the son of Beor a soothsayer, who dwelt upon the river of the land of the children of Ammon, to call him, and to say: Behold a people is come out of Aegypt, that hath covered the face of the earth, sitting against me.\n"
	"Come therefore, and curse this people, because it is mightier than I: if by any means I may strike them and cast them out of my land. For I know that he is blessed whom thou shalt bless, and cursed upon whom thou shalt heap curses.\n"
	"And the ancients of Moab went, and the elders of Madian, having the price of divination in their hands. And when they were come to Balaam, and had told him all the words of Balac:\n"
	"he answered: Tarry here this night, and I will answer whatsoever the Lord shall say to me. And whilst they stayed with Balaam, God came, and said to him:\n"
	"What would these men that are with thee?\n"
	"He answered: Balac the son of Sephor king of the Moabites hath sent to me,\n"
	"saying: Behold a people that is come out of Aegypt, hath covered the face of the land: come, and curse them, if by any means fighting I may drive them away.\n"
	"And God said to Balaam: Go not with them, neither do thou curse the people: because it is blessed.\n"
	"Who in the morning arising said to the Princes: Go into your country, because the Lord hath forbid me to come with you.\n"
	"The princes returning, said to Balac: Balaam would not come with us.\n"
	"Again he sent many more and more noble, than he had sent before.\n"
	"Who when they were come to Balaam, said: Thus saith Balac the son of Sephor: Slack not to come to me:\n"
	"for I am ready to honour thee, and whatsoever thou wilt I will give thee: Come, and curse this people.\n"
	"Balaam answered: If Balac would give me his house full of silver and gold, I cannot change the word of the Lord my God, to speak either more, or less.\n"
	"I beseech you that you will also tarry here this night, and I may know what the Lord will answer me once more.\n"
	"God therefore came to Balaam in the night, and said to him: If these men be come to call thee, arise and go with them: yet so, that thou do that which I shall command thee.\n"
	"Balaam arose in the morning, and saddling his ass went with them.\n"
	"And God was angry. And an Angel of our Lord stood in the way against Balaam, who sat upon the ass, and had two servants with him.\n"
	"The ass seeing the Angel standing in the way, with a drawn sword, turned herself out of the way, and went by the field. Whom when Balaam had beat, and had brought her again to the beaten way,\n"
	"the Angel stood in the straits of two walls, wherewith vineyards were inclosed.\n"
	"Whom the ass seeing, joined herself close to the wall, and bruised the foot of him that rid. But he beat her again:\n"
	"and nevertheless the Angel passing to a narrow place, where there could be no going aside neither to the right hand nor to the left, stood to meet him.\n"
	"And when the ass had seen the Angel standing, she fell under the feet of the rider. Who being angry, beat her sides with a staff more vehemently.\n"
	"And our Lord opened the mouth of the ass, and she spake: What have I done to thee? Why strikest thou me, lo now the third time?\n"
	"Balaam answered: Because thou hast deserved, and hast abused me: I would I had a sword, that I might kill thee.\n"
	"The ass said: Am not I thy beast, on which thou hast been always accustomed to ride until this present day? Tell me what like thing did I ever to thee. But he said: Never.\n"
	"Forthwith our Lord opened the eyes of Balaam, and he saw the Angel standing in the way with a drawn sword, and he adored him flat to the ground.\n"
	"To whom the Angel said: Why beatest thou thy ass the third time? I am come to withstand thee, because thy way is perverse, and contrary to me:\n"
	"and unless the ass had turned out of the way, giving place to me resisting thee, I had slain thee, and she should have lived.\n"
	"Balaam said: I have sinned, not knowing that thou didst stand against me: and now if it displease thee that I go, I will return.\n"
	"The Angel said: Go with these men, and see thou speak no other thing than I shall command thee. He went therefore with the Princes.\n"
	"Which when Balac heard, he came forth to meet him in a town of the Moabites, that is situated in the uttermost borders of Arnon.\n"
	"And he said to Balaam: I sent messengers to call thee, why didst thou not come immediately unto me? Was it because I cannot reward thy coming?\n"
	"To whom he answered: Lo here I am: Shall I be able to speak any other thing, but that which God shall put in my mouth?\n"
	"They therefore went on together, and came into a city, that was in the uttermost borders of his Kingdom.\n"
	"And when Balac had killed oxen, and sheep, he sent thereof to Balaam, and to the Princes that were with him, presents.\n"
	"And when morning was come, he brought him to the excelses of Baal, and he beheld the uttermost part of the people.";