const char* chap146 = "The first day also of the seventh month shall be venerable and holy unto you, no servile work shall you do therein, because it is the day of sounding and of trumpets.\n"
	"And you shall offer an holocaust for a most sweet odour to the Lord, one calf of the herd, one ram, and seven lambs of a year old without blemish:\n"
	"and in their sacrifices of flour tempered with oil three tenths to every calf, two tenths to a ram,\n"
	"one tenth to a lamb, which together are seven lambs:\n"
	"and a buck goat for sin, which is offered for the expiation of the people,\n"
	"besides the holocaust of the Calends with the sacrifices thereof, and the everlasting holocaust with the accustomed libaments. With the same ceremonies shall you offer burnt sacrifice for a most sweet odour to the Lord.\n"
	"The tenth day also of this seventh month shall be holy and venerable unto you, & you shall afflict your souls: no servile work shall you do therein.\n"
	"And you shall offer an holocaust to the Lord for a most sweet odour, one calf of the herd, one ram, seven Lambs of a year old without blemish:\n"
	"and in their sacrifices of flour tempered with oil three tenths to every calf, two tenths to the ram,\n"
	"the tenth part of a tenth to every lamb, which are in all seven lambs:\n"
	"and a buck goat for sin, besides these things that are wont to be offered for offence unto expiation, and for the everlasting holocaust with their sacrifice and libaments.\n"
	"But the fifteenth day of the seventh month, which shall be unto you holy and venerable, no servile work shall you do therein, but you shall celebrate the solemnity to the Lord seven days.\n"
	"and you shall offer an holocaust for a most sweet odour to the Lord, calves of the herd thirteen, rams two, lambs of a year old without blemish fourteen:\n"
	"& in their libaments of flour tempered with oil three tenths to every calf, which are together thirteen calves: & two tenths to every ram, that is, together to two rams,\n"
	"And the tenth part of a tenth to every lamb, which are together fourteen lambs:\n"
	"and a buck goat for sin, beside the everlasting holocaust, & the sacrifice & the libament thereof.\n"
	"The next day you shall offer calves of the herd twelve, two rams, lambs a year old without blemish fourteen:\n"
	"and the sacrifices and libaments of every one to the calves and the rams and the lambs you shall ritely celebrate:\n"
	"and a buck goat for sin, beside the everlasting holocaust, and the sacrifice and libament thereof.\n"
	"The third day you shall offer eleven calves, two rams, lambs of a year old without blemish fourteen:\n"
	"and the sacrifices and the libaments of every one to the calves & the rams and the lambs you shall ritely celebrate:\n"
	"and a buck-goat for sin, beside the everlasting holocaust, and the sacrifice, and libament thereof.\n"
	"The fourth day you shall offer ten calves, two rams, lambs a year old without blemish fourteen:\n"
	"and the sacrifices and the libaments of every one to the calves and the rams and the lambs you shall ritely celebrate:\n"
	"and a buck-goat for sin, beside the everlasting holocaust, and the sacrifice thereof and libament.\n"
	"The fifth day you shall offer nine calves, two rams, lambs of a year old without blemish fourteen:\n"
	"and the sacrifices and the libaments of every one to the calves and the rams and the lambs you shall ritely celebrate:\n"
	"and a buck-goat for sin, beside the everlasting holocaust, and the sacrifices thereof and libament.\n"
	"The sixth day you shall offer eight calves, two rams, lambs of a year old without blemish fourteen:\n"
	"& the sacrifices and the libaments of every one to the calves and the rams & the lambs you shall ritely celebrate:\n"
	"and a buck-goat for sin, beside the everlasting holocaust, and the sacrifice thereof and libament.\n"
	"The seventh day you shall offer seven calves, and two rams, lambs of a year old without blemish fourteen:\n"
	"and the sacrifices and the libaments of every one to the calves and the rams and the lambs you shall ritely celebrate:\n"
	"and a buck-goat for sin, beside the everlasting holocaust and the sacrifice thereof and libament.\n"
	"The eighth day, which is most solemn, no servile work you do therein,\n"
	"offering an holocaust for a most sweet odour to the Lord: one calf, one ram, lambs of a year old with out blemish seven.\n"
	"And the sacrifices and the libaments of every one to the calves and the rams and the lambs you shall ritely celebrate:\n"
	"and a buck-goat for sin, besides the everlasting holocaust, & the sacrifice thereof and libament.\n"
	"These things shall you offer to the Lord in your solemnities: besides your vows and voluntary oblations in holocaust, in sacrifice, in libament, and in pacific hosts.";