const char* chap147 = "And Moyses told the children of Israel all things that our Lord had commanded him:\n"
	"and he spake to the Princes of the tribes of the children of Israel: This is the word that our Lord hath commanded:\n"
	"If any man make a vow to our Lord, or bind himself by an oath: he shall not make his word frustrate, but all that he promised he shall fulfill.\n"
	"If a woman vow any thing, and bind herself with an oath, she that is in her father's house, & as yet in maiden's age: if her father know the vow that she promised, and the oath wherewith she bound her soul, and hold his peace, she shall be bound to the vow:\n"
	"Whatsoever she promised and sware, she shall fulfill in deed.\n"
	"But if immediately as he heareth it, her father do gainsay it, both her vows & her oaths shall be frustrate, neither shall she be bound to the promise, for that her father hath gainsaid it.\n"
	"If she have a husband, and vow any thing, and the word once going out of her mouth bind her soul by an oath,\n"
	"the day that her husband heareth it, and doth not gainsay it, she shall be bound to the vow, and shall render whatsoever she promised.\n"
	"But if as soon as he heareth he gainsay it, and make her promises frustrate, and the words wherewith she had bound her soul, our Lord will be propitious to her.\n"
	"The widow, and she that is divorced, whatsoever they vow they shall render.\n"
	"The wife in the house of her husband, when she hath bound herself by vow and by oath,\n"
	"if her husband hear, and hold his peace, neither do gainsay the promise, she shall render whatsoever she had promised.\n"
	"But if forthwith he gainsay it, she shall not be holden bound to the promise: because her husband gainsaid it, and our Lord will be propitious to her.\n"
	"If she vow and bind herself by oath, to afflict her soul by fasting, or abstinence from other things, it shall be in the arbitrement of her husband, whether she shall do it, or not do it.\n"
	"And if the husband hearing it hold his peace, and defer sentence till another day: whatsoever she had vowed and promised, she shall render: because immediately as he heard it, he held his peace,\n"
	"but if he gainsay it after that he knew it, himself shall bear her iniquity.\n"
	"These are the laws, which our Lord appointed to Moyses between the husband and the wife, between the father and the daughter, that is as yet in maiden's age, or that abideth in her father's house.";