const char* chap15 = "When these things therefore were done, the word of our Lord was made to Abram by a vision saying: fear not Abram, I am thy Protector, and thy reward exceeding great.\n"
	"And Abram said: Lord God, what wilt thou give me? I shall go without children: and the son of the steward of my house is this Damascus Eliezer.\n"
	"And Abram added: But to me thou hast not given seed: and Lo my servant born in my house shall be mine heir.\n"
	"And immediately the word of our Lord came to him saying: He shall not be thine heir: but he that shall come out of thy womb him shalt thou have thine heir.\n"
	"And he brought him forth abroad, and said to him: Look up to heaven, and number the stars, if thou canst. And he said to him: so shall thy seed be.\n"
	"Abram believed God, and it was reputed to him unto justice.\n"
	"And he said to him: I am the Lord that brought thee out from Ur of the Chaldees for to give thee this land, and that thou mightest possess it.\n"
	"But he said: Lord God, how may I know that I shall possess it?\n"
	"And our Lord answered, and said: Take me a cow of three years old, and a she goat of three years, and a ram of three years, a turtle also, and a pigeon.\n"
	"Who taking all these, divided them by the midst, and laid each two pieces arow one against the other: but the birds he divided not.\n"
	"And the fowls lighted upon the carcasses, and Abram drove them away.\n"
	"And when the sun was setting, a deep sleep fell upon Abram, and a great and darksome horror invaded him.\n"
	"And it was said unto him: Know and foreknow that a pilgrim shall thy seed be in a land not their own (and they shall bring them under bondage, and afflict them) four hundred years.\n"
	"But the Nation, whom they shall serve, I will judge: and after this they shall go forth with great substance.\n"
	"And thou shalt go to thy fathers in peace, buried in a good old age.\n"
	"But in the fourth generation they shall return hither: for as yet the iniquities of the Amorrheans are not at the full until this present time.\n"
	"Therefore when the sun was set, there arose a dark mist, and there appeared a furnace smoking, and a flake of fire passing between those divisions.\n"
	"That day God made a covenant with Abram, saying: To thy seed will I give this land from the river of Aegypt even to the great river Euphrates.\n"
	"the Cineans, and Cenezeites, the Cedmonites,\n"
	"and the Hethits, and the Pherezits, the Raphaims also,\n"
	"and the Amorreans and the Chananites, and Gargasites, and the Jebusites.";