const char* chap151 = "And our Lord spake to Moyses, saying:\n"
	"Command the children of Israel, and thou shalt say to them: When you are entered into the Land of Chanaan, and it shall be fallen unto you by lot in possession, it shall be limited by these borders:\n"
	"The southside shall begin from the wilderness Sin, which is beside Edom: and it shall have toward the East the most salt sea for the limits.\n"
	"The which shall compass the south side by the ascending of the Scorpion, so that they shall pass into Senna, and reach toward the South as far as Cadesbarne, from whence the frontiers shall go forth to the town named Adar, and shall reach as far as Asemona.\n"
	"And the border shall go round about from Asemona to the Torrent of Aegypt, and shall end in the shore of the great sea.\n"
	"And the west side shall begin from the great sea, and the same shall be the limit thereof.\n"
	"Moreover toward the North part the borders shall begin from the great sea, reaching unto the most high mountain,\n"
	"from the which they shall come unto Emath as far as the borders of Sedada:\n"
	"and the frontiers shall go as far as Sephorna, and the town Enan. These shall be the borders in the North part.\n"
	"From thence they shall mark out the bounds toward the East side from the Village Enan unto Sephama,\n"
	"and from Sephama the bounds shall go down unto Rebla against the fountain Daphnim: from thence they shall come eastward to the sea Cenereth,\n"
	"and shall reach as far as Jordan, and at the last shall be closed in by the most salt sea. This you shall have for your Land by the bounds thereof round about.\n"
	"And Moyses commanded the children of Israel, saying: This shall be the Land, which you shall possess by lot, and which our Lord hath commanded to be given to the nine tribes, and to the half tribe.\n"
	"For the tribe of the children of Ruben by their families, and the tribe of the children of Gad according to the number of their kindreds, the half also of the tribe of Manasses,\n"
	"that is, two tribes and an half, have taken their portion beyond Jordan against Jericho at the east side.\n"
	"And our Lord said to Moyses:\n"
	"These are the names of the men, that shall divide the Land unto you: Eleazar the Priest, and Josue the son of Nun,\n"
	"and one Prince of every tribe,\n"
	"whose names are these: Of the tribe of Juda, Caleb: son of Jephone.\n"
	"Of the tribe of Simeon, Samuel the son of Ammiud.\n"
	"Of the tribe of Benjamin Elidad the son of Chaselon.\n"
	"Of the tribe of the children of Dan, Bocci the son of Iogli.\n"
	"Of the children of Joseph of the tribe of Manasses, Hanniel the son of Ephod.\n"
	"Of the tribe of Ephraim, Camuel the son of Sephthan.\n"
	"Of the tribe of Zabulon, Elisaphan the son of Pharnach.\n"
	"Of the tribe of Issachar, Duke Phaltiel the son of Ozan.\n"
	"Of the tribe of Aser, Ahiud the son of Salomi.\n"
	"Of the tribe of Nephthali: Phedael the son of Ammiud.\n"
	"These are they whom our Lord commanded to divide the Land of Chanaan to the children of Israel.";