const char* chap152 = "These things also spake our Lord to Moyses in the champion countries of Moab upon Jordan, against Jericho:\n"
	"Command the children of Israel that they give unto the Levites of their possessions\n"
	"cities to dwell in, and their suburbs round about: that themselves may abide in the towns, and the suburbs may be for their cattle and beasts.\n"
	"Which from the walls of the cities outward, round about, shall reach the space of a thousand paces.\n"
	"Toward the East shall be two thousand cubits: and toward the South in like manner shall be two thousand: toward the sea also, which looketh to the West, shall be the same measure: and the North part shall be limited with equal bounds. And the cities shall be in the midst, and the suburbs without.\n"
	"And of the same towns, which you shall give to the Levites, six shall be separated for the aid of fugitives, that he may fly to them which hath shed blood: and beside these other forty two towns,\n"
	"that is, in all forty eight with their suburbs.\n"
	"And those cities, that shall be given of the possessions of the children of Israel, from them that have more, more shall be taken away: and that have less, fewer. Each shall give towns to the Levites according to the measure of their inheritance.\n"
	"Our Lord said to Moyses:\n"
	"Speak to the children of Israel, and thou shalt say to them: When you shall have passed over Jordan into the Land of Chanaan,\n"
	"determine what cities shall be for the succour of fugitives, that have not voluntarily shed blood:\n"
	"in which when the fugitive shall be, the kinsman of him that is killed cannot kill him, until he stand in the sight of the multitude, and his cause be judged.\n"
	"And of those cities, that are separated for refuge of the fugitives,\n"
	"three shall be beyond Jordan, and three in the Land of Chanaan,\n"
	"as well for the children of Israel as for strangers and sojourners, that he may fly to them, which hath not voluntarily shed blood.\n"
	"If any man strike with iron, and he die that was strucken, he shall be guilty of murder, and himself shall die.\n"
	"If he cast a stone, and he that is strucken die: he shall be punished in like manner.\n"
	"If he that is strucken with wood die, he shall be revenged by the striker's blood.\n"
	"The kinsman of him that is slain, shall kill the murderer, as soon as he apprehendeth him, he shall kill him.\n"
	"If through hatred one push a man, or cast any thing at him by stratagem,\n"
	"or being his enemy, strike him with his hand, and he die: the striker shall be guilty of murder. The kinsman of him that is slain as soon as he findeth him, shall kill him.\n"
	"But if by chance-medley, and without hatred,\n"
	"and enmity, he do any of these things,\n"
	"and this be proved in the hearing of the people, and the question debated between him that struck, and the next of blood:\n"
	"the innocent shall be delivered from the hand of the revenger, & by sentence shall be brought back into the city, to which he had fled, and he shall tarry there, until the High-priest, that is anointed with the holy oil, do die.\n"
	"If the murderer be found without the limits of the cities, that are deputed to the banished,\n"
	"and be strucken of him that is the revenger of blood: he shall be guiltless that killed him.\n"
	"For the fugitive ought to have stayed in the city until the death of the High-priest. And after he is dead, then shall the murderer return into his country.\n"
	"These things shall be perpetual, and for an ordinance in all your habitations.\n"
	"The murderer shall be punished by witnesses: none shall be condemned, at the testimony of one man.\n"
	"You shall not take a price of him, that is guilty of blood, he also shall die forthwith.\n"
	"The banished and fugitives before the death of the High-Priest may by no means return into their own cities.\n"
	"Pollute not the land of your habitation, which is polluted with the blood of innocents: neither can it otherwise be expiated, but by his blood, that sheddeth another man's blood.\n"
	"And so shall your possession be cleansed myself abiding with you. For I am the Lord that dwell among the children of Israel.";