const char* chap154 = "These are the words, which Moyses spake to all Israel beyond Jordan, in the champion wilderness, against the Red sea, between Pharan and Tophel and Laban and Haseroth, where there is very much gold:\n"
	"eleven days from Horeb by the way of mount Seir to Cadesbarne.\n"
	"The fortieth year, the eleventh month, the first day of the month Moyses spake to the children of Israel all things that our Lord had commanded him to say unto them:\n"
	"after that he had struck Sehon king of the Amorrheites, which dwelt in Hesebon: and Og the king of Basan which abode in Aseroth, and in Edrai,\n"
	"beyond Jordan in the Land of Moab. And Moyses began to expound the law, and to say:\n"
	"The Lord our God spake to us in Horeb, saying: It is sufficient for you that you have stayed in this mountain:\n"
	"return, and come to the mountain of the Amorrheites, and to the rest that are next to it champion and hilly and lower places against the South, and beside the shore of the sea, the Land of the Chananites, and of Libanus unto the great river Euphrates.\n"
	"Behold (quoth he) I have delivered it to you: enter in and possess it, upon the which our Lord sware to your fathers Abraham, Isaac, and Jacob, that he would give it to them, & to their seed after them.\n"
	"And I said to you at that time:\n"
	"I alone cannot sustain you, because the Lord your God hath multiplied you, and you are this day as the stars of heaven, very many.\n"
	"(The Lord God of your fathers add to this number many thousands, and bless you as he hath spoken.)\n"
	"I alone am not able to sustain your businesses, and the charge of you and your quarrels.\n"
	"Give from among you wise and skillful men, and such whose conversation is approved in your tribes, that I may appoint them your princes.\n"
	"Then you answered me: The thing is good which thou meanest to do.\n"
	"And I took of your tribes^ men wise and noble, and appointed them Princes, tribunes, and centurions, and quinquagenarians, and deans, that might teach you all things.\n"
	"And I commanded them, saying: Hear them, and judge that which is just: whether he be the same country man, or a stranger.\n"
	"There shall be no difference of persons, so shall you hear the little as the great: neither shall you accept any man's person, because it is the judgment of God. And if any thing seem hard to you, refer it to me, and I will hear it.\n"
	"And I commanded all things that you ought to do.\n"
	"And departing from Horeb, we passed through the terrible and huge wilderness, which you saw, by the way of the mountain of the Amorrhite, as the Lord our God had commanded us. And when we were come into Cadesbarne,\n"
	"I said to you: You are come to the mountain of the Amorrhite, which the Lord our God will give to us.\n"
	"See the Land which the Lord thy God giveth thee: go up and possess it, as the Lord our God hath spoken to thy fathers: fear not, neither dread you any thing.\n"
	"And you came all unto me, and said: Let us send men that may view the Land, and may bring us word what way we shall ascend, and to what cities to go.\n"
	"And because the saying pleased me, I sent of you twelve men, one of every tribe.\n"
	"Who when they had gone, and were ascended into the mountains, they came as far as the Valley of cluster: and the Land being viewed,\n"
	"taking of the fruits thereof, to shew the fruitfulness, they brought unto us, and said: The Land is good, which the Lord our God will give us.\n"
	"And you would not go up, but being incredulous at the word of the Lord our God,\n"
	"you murmured in your tabernacles, and said: our Lord hateth us, and therefore hath brought us out of the Land of Aegypt, that he might deliver us into the hand of the Amorrhite, and destroy us.\n"
	"Whither shall we go up? The messengers have feared our heart, saying: The multitude is very great, and taller of stature than we: the cities great, and fenced even unto heaven, the sons of the Enacims we have seen there.\n"
	"And I said to you: Fear not, neither be ye afraid of them:\n"
	"Our Lord God, which is your conductor, himself will fight for you, as he did in Aegypt in the sight of all.\n"
	"And in the wilderness (thyself hast seen) the Lord thy God hath carried thee, as a man is wont to bear his little son, all the way that you have walked, until you came to this place.\n"
	"And neither so did you believe the Lord your God,\n"
	"who went before you in the way, and marked out the place wherein you should pitch your tents, in the night shewing you the way by fire, and in the day by the pillar of a cloud.\n"
	"And when our Lord had heard the voice of your words, being wrath he sware and said:\n"
	"There shall not any of the men of this wicked generation see the good Land, which by oath I promised to your fathers:\n"
	"beside Caleb the son of Jephone, For he shall see it, and to him I will give the Land, that he hath trodden, and to his children, because he hath followed the Lord.\n"
	"Neither is his indignation against the people to be marveled at, whereas our Lord being angry with me also for you, said: Neither shalt thou enter in thither.\n"
	"But Josue the son of Nun thy minister, he shall enter for thee: exhort and strengthen him, and he shall by lot divide the Land of Israel.\n"
	"Your little ones, of whom you said that they should be led captives, and your sons that this day know not the difference of good and evil, they shall enter in: and to them I will give the Land, and they shall possess it.\n"
	"But return you and go into the wilderness by the way of the Red sea.\n"
	"And you answered me: We have sinned to our Lord: We will go up and fight, as the Lord our God hath commanded. And when you ready armed went unto the mountain,\n"
	"our Lord said to me: Say to them: Go not up, and fight not, for I am not with you: lest you fall before your enemies.\n"
	"I spake, and you heard not: But resisting the commandment of our Lord, and swelling with pride you went up into the mountain.\n"
	"Therefore the Amorrhite that dwelt in the mountains issuing forth, and coming to meet you, pursued you, as bees are wont to pursue: and smote you from Seir as far as Horma.\n"
	"And when returning you wept before our Lord, he heard you not, neither would he condescend to your voice.\n"
	"You abode therefore in Cadesbarne a great time.";