const char* chap158 = "And Moyses called all Israel, and said to them: Hear Israel the ceremonies and judgments, which I speak in your ears this day: learn them, and fulfill them in work.\n"
	"The Lord our God made a covenant with us in Horeb.\n"
	"Not with our fathers did he make the covenant, but with us at this present, and do live.\n"
	"Face to face did he speak to us in the mount out of the midst of the fire.\n"
	"I was arbiter and Mediator betwixt our Lord and you at that time, to shew you his words, for you feared the fire, and went not up into the mount, and he said:\n"
	"I^ the Lord thy God, that brought thee out of the Land of Aegypt out of the house of servitude.\n"
	"Thou shalt not have strange gods in my sight.\n"
	"Thou shalt not make to thee a thing graven, nor the similitude of any things, that are in heaven above, and that are in the earth beneath, and that abide in the waters under the earth.\n"
	"Thou shalt not adore them, and thou shalt not serve them. For I am the Lord thy God, a Jealous God, rendering the iniquity of the fathers upon the children unto the third and fourth generation to them that hate me,\n"
	"and doing mercy upon many thousands to them that love me, and keep my precepts.\n"
	"Thou shalt not usurp the name of the Lord thy God in vain: for he shall not be unpunished that taketh his name upon a vain thing.\n"
	"Observe the day of the Sabbath, to sanctify it, as the Lord thy God hath commanded thee.\n"
	"Six days shalt thou work, and shalt do all thy works.\n"
	"The seventh is the day of the Sabbath, that is, the rest of the Lord thy God. Thou shalt not do any work therein, thou, and thy son and daughter, man servant and woman servant, and oxe, and ass, and all thy cattle, and the stranger that is within thy gates: that thy man servant may rest, and thy woman servant, even as thyself.\n"
	"Remember that thou also didst serve in Aegypt, and the Lord thy God brought thee out from thence in a strong hand, and stretched out arm. Therefore hath he commanded thee that thou shouldst observe the Sabbath.\n"
	"Honour thy father and mother, as our Lord thy God hath commanded thee, that thou mayst live a long time, and it may be well with thee in the Land, which the Lord thy God will give thee.\n"
	"Thou shalt not murder.\n"
	"Neither shalt thou commit adultery.\n"
	"And thou shalt not steal.\n"
	"Neither shalt thou speak against thy neighbour false testimony.\n"
	"Thou shalt not covet thy neighbour's wife: Nor house, nor field, nor man servant, nor woman servant, nor oxe, nor ass, and all things that are his.\n"
	"These words spake our Lord to all your multitude in the mount, out of the midst of the fire and the cloud, and the darkness, with a loud voice, adding nothing more: and he wrote them in the two tables of stone, which he delivered unto me.\n"
	"And you after you heard the voice out of the midst of the darkness, and saw the mount burn, came to me all the Princes of the tribes and the elders, and you said:\n"
	"Behold the Lord our God hath shewed us his majesty and greatness for we have heard his voice out of the midst of the fire, & have proved this day that God speaking with man, man hath lived.\n"
	"Why shall we die therefore, and this exceeding great fire devour us? For if we hear the voice of the Lord our God any more, we shall die.\n"
	"What is all flesh, that it should hear the voice of the living God, who speaketh out of the midst of the fire as we have heard, and may live?\n"
	"Approach thou rather: and hear all things that the Lord our God shall say to thee: and thou shalt speak to us, and we hearing will do them.\n"
	"Which when our Lord had heard, he said to me: I have heard the voice of the words of this people, which they spake to thee: they have spoken all things well.\n"
	"Who shall give them to have such a mind, that they would fear me, and keep all my commandments at all time, that it may be well with them and with their children for ever?\n"
	"Go and say to them: Return into your tents.\n"
	"But thou stand here with me, and I will speak to thee all my commandments, and ceremonies, and judgments: which thou shalt teach them, that they may do them in the Land, which I will give them in possession.\n"
	"Keep therefore and do the things which our Lord God hath commanded you: you shall not decline neither to the right hand, nor to the left:\n"
	"but the way that the Lord your God hath commanded shall you walk, that you may live, and it may be well with you, and your days may be prolonged in the land of your possession.";