const char* chap159 = "These are the precepts, and ceremonies, and judgments, which the Lord your God commanded that I should teach you, and you should do them in the Land, whereunto you pass over to possess it:\n"
	"that thou mayst fear the Lord thy God, and keep his commandments and precepts, which I command thee, and thy sons, and nephews, all the days of thy life, that thy days may be prolonged.\n"
	"Hear Israel, and observe that thou do the things which our Lord hath commanded thee, and it may be well with thee, and thou mayst be greatly multiplied, as the Lord God of thy fathers hath promised thee a land flowing with milk & honey.\n"
	"Hear Israel, The Lord our God, is one Lord.\n"
	"Thou shalt love the Lord thy God with thy whole heart, and with thy whole soul, and with thy whole strength.\n"
	"And these words, which I command thee this day, shall be in thy heart:\n"
	"and thou shalt tell them to thy children, and thou shalt meditate sitting in thy house, and walking on thy journey, sleeping, and rising.\n"
	"And thou shalt bind them as a sign on thy hand, and they shall be and shall move between thine eyes,\n"
	"and thou shalt write them in the entry, and on the doors of thy house.\n"
	"And when the Lord thy God shall have brought thee into the Land, for the which he sware to thy fathers Abraham, Isaac, and Jacob: and shall have given thee great and goodly cities, which thou didst not build,\n"
	"houses full of all riches, which thou didst not erect, cisterns which thou didst not dig, vineyards and oliveyards, which thou didst not plant,\n"
	"and thou shalt have eaten and be full:\n"
	"take heed diligently lest thou forget our Lord, that brought thee out of the Land of Aegypt, out of the house of servitude. Thou shalt fear the Lord thy God, and him only shalt thou serve, and by his name shalt thou swear.\n"
	"You shall not go after the strange gods of all Nations, that are round about you:\n"
	"because the Lord thy God is a Jealous God in the midst of thee: lest sometime the fury of the Lord thy God be wrath against thee, & take thee away from the face of the earth.\n"
	"Thou shalt not tempt the Lord thy God, as thou didst tempt him in the place of tentation.\n"
	"Keep the precepts of the Lord thy God, and the testimonies & ceremonies, which he hath commanded thee:\n"
	"And do that which is pleasant and good in the sight of our Lord, that it may be well with thee: and entering in thou mayest possess the goodly Land, whereof our Lord sware to thy fathers,\n"
	"that he would destroy all thy enemies before thee, as he hath spoken.\n"
	"And when thy son shall ask thee tomorrow, saying: What mean these testimonies, and ceremonies, and judgments, which the Lord our God hath commanded us?\n"
	"thou shalt say to him: We were the bondmen of Pharao in Aegypt, and our Lord brought us out of Aegypt in a strong hand:\n"
	"and he did signs & wonders great and very sore in Aegypt against Pharao, and all his house, in our sight,\n"
	"and he brought us out from thence, that being brought in^ he might give us the Land, whereupon he sware to our fathers.\n"
	"And our Lord commanded that we should do all these ordinances, and should fear the Lord our God, that it might be well with us all the days of our life, as it is at this day.\n"
	"And he will be merciful to us, if we keep and do all his precepts before the Lord our God, as he commanded us.";