const char* chap163 = "At that time our Lord said to me: Hew thee two tables of stones, as the former were, & come up to me into the mount: & thou shalt make an ark of wood,\n"
	"& I will write in the tables the words that were in them, which before thou didst break, & thou shalt put them in the ark.\n"
	"I made therefore an ark of the wood Setim. And when I had hewed two tables of stone like to the former, I went up into the mount, having them in my hands.\n"
	"And he wrote in the tables, according as he had written before, the ten words, which our Lord spake to you in the mount from the midst of the fire, when the people was gathered: and he gave them to me.\n"
	"And returning from the mount, I came down, and put the tables into the ark, that I had made, which are there till this present, as our Lord commanded me.\n"
	"And the children of Israel removed their camp from Beroth of the children of Jacan into Mosera, where Aaron died and was buried, for whom Eleazar his son did the function of priesthood.\n"
	"Thence they came into Gadgad: from the which place departing, they camped in Jetebatha, in a Land of waters and torrents.\n"
	"At that time he separated the tribe of Levi, to carry the ark of the covenant of our Lord, and to stand before him in the ministry, and to bless in his name until this present day.\n"
	"For the which cause Levi had no part nor possession with his brethren: because, our Lord himself is his possession, as the Lord thy God promised him.\n"
	"And I stood in the mount, as before, forty days and nights: and our Lord heard me this time also, and would not destroy thee.\n"
	"And he said to me: Go, and march before the people, that they may enter, and possess the Land, which I sware to their fathers that I would deliver to them.\n"
	"And now Israel, what doth the Lord thy God require of thee, but that thou fear the Lord thy God, and walk in his ways, and love him, and serve the Lord thy God with all thy heart, and with all thy soul:\n"
	"and keep the commandments of our Lord, and his ceremonies, which I command thee this day, that it may be well with thee?\n"
	"Behold heaven is the Lord's thy God, and the heaven of heaven, the earth and all things that are in it.\n"
	"And yet to thy fathers was our Lord joined, and he loved them, and chose their seed after them, that is to say you, from all Nations, as this day it is proved.\n"
	"Circumcise therefore the prepuce of your heart, and your neck indurate no more:\n"
	"because the Lord your God he is the God of gods, and the Lord of lords, a great God and mighty, and terrible, that accepteth not person nor gifts.\n"
	"He doth judgment to the pupil and the widow, loveth the stranger, and giveth him victual and raiment.\n"
	"And do you therefore love strangers because you also were strangers in the Land of Aegypt.\n"
	"Thou shalt fear the Lord thy God, and serve him only: to him thou shalt cleave, and shalt swear in his name.\n"
	"He is thy praise, and thy God, that hath done for thee these great and terrible things, which thine eyes have seen.\n"
	"In seventy souls did thy fathers go down into Aegypt: and behold now the Lord thy God hath multiplied thee as the stars of heaven.";