const char* chap167 = "Be ye the children of the Lord your God: you shall not cut yourselves, nor make baldness for the dead.\n"
	"because thou art a holy people to the Lord thy God: and he chose thee to be his peculiar people of all nations that are upon the earth.\n"
	"Eat not the things that are unclean.\n"
	"This is the beast, that you ought to eat: The oxe, and the sheep, and the goat,\n"
	"the hart and the doe, the buffle, the chamois, the pygargue, the wild beef, the camelopard.\n"
	"Every beast, that divideth the hoof in two parts, and cheweth the cud, shall you eat.\n"
	"But of them that chew the cud, and divide not the hoof, these you shall not eat, as the camel, the hare, the cherogril: because they chew the cud, & divide not the hoof, they shall be unclean to you\n"
	"The swine also, because it divideth the hoof, and cheweth not the cud, shall be unclean. Their flesh you shall not eat, and their carcasses you shall not touch.\n"
	"These shall you eat of all that abide in the waters: Such as have fins and scales, eat:\n"
	"them that are without fins & scales, eat not, because they are unclean.\n"
	"All birds that are clean eat.\n"
	"The unclean eat not: to wit, the eagle, and the grype, & the osprey,\n"
	"the ringtail, and the vulture and kite according to their kind:\n"
	"and all of the raven's kind,\n"
	"and the ostrich, and the owl, and the stern, and the hawk according to his kind:\n"
	"the herodian and the swan, and the stork,\n"
	"and the diver, the porphirion, and nightcrow,\n"
	"the onocratal, and the charadrion, every one in their kind: the lapwing also and the bat.\n"
	"And all that creepeth and hath little wings, shall be unclean, and shall not be eaten.\n"
	"All that is clean, eat.\n"
	"But whatsoever is dead of it-self, eat not thereof. To the stranger, that is within thy gates, give it to eat, or sell it to him: because thou art the holy people of our Lord thy God. Thou shalt not boil a kid in the milk of his dam.\n"
	"The tenth part thou shalt separate of all thy fruits that spring in the earth every year,\n"
	"and thou shalt eat in the sight of our Lord thy God in the place, which he shall choose, that his name may be invocated therein, the tithe of thy corn, and wine, and oil, and the first born of thy herds and sheep: that thou mayest learn to fear the Lord thy God at all time.\n"
	"But when the way, and the place which our Lord thy God shall choose, are far, and he hath blessed thee, and thou canst not carry all these things thither,\n"
	"thou shalt sell, and bring all into a price, and shalt carry it in thy hand, and shalt go to the place, which our Lord thy God shall choose:\n"
	"and thou shalt buy with the same money whatsoever pleaseth thee, either of herds, or of sheep, wine also and sicer, and all that thy soul desireth: and thou shalt eat before our Lord thy God, and shall feast, thou and thy house:\n"
	"and the Levite that is within thy gates, beware thou forsake him not, because he hath no other part in thy possession.\n"
	"The third year thou shalt separate another tenth of all things, that grow to thee at that time: and shalt lay it up within thy gates.\n"
	"And the Levite shall come that hath no other part nor possession with thee, and the stranger and pupil and widow, that are within thy gates, and shall eat and be filled: that our Lord thy God may bless thee in all the works of thy hands that thou shalt do.";