const char* chap168 = "In the seventh year thou shalt make a remission.\n"
	"which shall be celebrated in this order. He to whom any thing is owing of his friend or neighbour and brother, cannot ask it again, because it is the year of remission of our Lord.\n"
	"Of the sojourner and stranger thou shalt exact: of thy country man & neighbour thou shalt not have power to require it.\n"
	"And needy person and beggar there shall be none among you that our Lord thy God may bless thee in the land, which he will give thee in possession.\n"
	"Yet so if thou hear the voice of our Lord thy God, & keep all things that he hath bid, and which I command thee this day, he will bless thee, as he hath promised.\n"
	"Thou shalt lend to many nations, & thyself shalt borrow of no man. Thou shalt have dominion over very many nations, and no man shall have dominion over thee.\n"
	"If one of thy brethren that abideth within the gates of thy city in the land, which our Lord thy God will give thee, come to poverty: thou shalt not harden thy heart, nor close thy hand,\n"
	"but shalt open it to the poor man, and shalt lend him, that which thou perceivest he hath need of.\n"
	"Beware lest perhaps an impious cogitation steal in upon thee, and thou say in thy heart: The seventh year of remission draweth nigh: & turn away thy eyes from thy poor brother denying to lend him that which he asketh: lest he cry against thee to our Lord, and it become a sin unto thee.\n"
	"But thou shalt give to him: neither shalt thou do any thing craftily in relieving his necessities: that our Lord thy God may bless thee at all times, and in all things whereunto thou shalt put thy hand.\n"
	"There shall not want poor in the land of thy habitation: therefore I command thee that thou open thy hand to thy needy and poor brother, that liveth in the Land.\n"
	"When thy brother an Hebrew man, or Hebrew woman is sold to thee, and hath served thee six years, in the seventh year thou shalt let him go free:\n"
	"and to whom thou givest freedom, thou shalt in no case suffer him to depart empty:\n"
	"but give him his wayfare of thy flocks, and of thy barn floor, and thy press, wherewith our Lord thy God shall bless thee.\n"
	"Remember that thyself also didst serve in the Land of Aegypt, and our Lord thy God made thee free, and therefore do I now command thee.\n"
	"But if he say: I will not depart; because he loveth thee, and thy house, and feeleth that he is well with thee:\n"
	"thou shalt take an awl, and bore through his ear in the door of thy house, & he shall serve thee for ever. To thy woman servant also thou shalt do in like manner.\n"
	"Turn not away thine eyes from them, when thou makest them free: because he hath served thee six years after the wages of an hireling: that our Lord thy God may bless thee in all the works that thou doest.\n"
	"Of the first born, that come forth in thy herds and sheep, whatsoever is of the male sex, thou shalt sanctify to our Lord thy God. Thou shalt not work with the first born of an oxe, and thou shalt not shear the first born of thy sheep.\n"
	"In the sight of our Lord thy God shalt thou eat them every year in the place, that our Lord shall choose, thou and thy house.\n"
	"But if it have blemish, and be either lame, or blind, or in any part disfigured or feeble, it shall not be immolated to our Lord thy God:\n"
	"but within the gates of thy city shalt thou eat it: as well the clean as the unclean in like manner shall eat them, as the doe, and the hart.\n"
	"This only shalt thou observe, that their blood thou eat not, but pour it out on the earth as water.";