const char* chap170 = "Thou shalt not immolate to our Lord thy God a sheep, and an oxe, wherein there is blemish, or any fault: because it is abomination to our Lord thy God.\n"
	"When there shall be found with thee within one of thy gates, which our Lord thy God shall give thee, man or woman that do evil in the sight of our Lord thy God, and transgress his covenant,\n"
	"that they go and serve strange gods, and adore them, the sun and the moon, and all the host of heaven, which things I commanded not,\n"
	"and this is told thee, and hearing it thou hast inquired diligently, and found it to be true, and the abomination is committed in Israel:\n"
	"thou shalt bring forth the man and the woman, that have committed that most heinous thing, to the gates of thy city, and they shall be stoned.\n"
	"At the mouth of two or three witnesses shall he perish that is to be slain. Let no man be killed, one only giving testimony against him.\n"
	"The hand of the witnesses shall be first to kill him, and the hand of the rest of the people shall be laid on last: that thou mayest take away the evil out of the midst of thee.\n"
	"If thou perceive that the judgment with thee be hard and doubtful between blood and blood, cause and cause, leprosy and leprosy: and thou see that the words of the judges within thy gates do vary: arise, and go up to the place, which our Lord thy God shall choose.\n"
	"And thou shalt come to the Priests of the Levitical stock, and to the judge, that shall be at that time: and thou shalt ask of them, who shall shew thee the truth of the judgment.\n"
	"And thou shalt do whatsoever they, that are presidents of the place which our Lord shall choose, shall say and teach thee,\n"
	"according to his law; and thou shalt follow their sentence: neither shalt thou decline to the right hand nor to the left hand.\n"
	"But he that shall be proud, refusing to obey the commandment of the Priest, which at that time ministereth to our Lord thy God, and the decree of the judge, that man shall die, and thou shalt take away the evil out of Israel:\n"
	"and the whole people hearing shall fear, that none afterward swell in pride.\n"
	"When thou art entered the Land, which our Lord thy God will give thee, and dost possess it, and dwellest in it, and sayest: I will set a king over me, as all nations have round about:\n"
	"him shalt thou set, whom our Lord thy God shall choose of the number of thy brethren. A man of another nation that is not thy brother, thou canst not make king.\n"
	"And when he is made, he shall not multiply to himself horses, nor lead back the people into Aegypt, taking high courage for the number of his horsemen, especially whereas our Lord hath commanded you that in no case you return any more the same way.\n"
	"He shall not have many wives, that may allure his mind, nor huge weights of silver & gold.\n"
	"And after he shall sit in the throne of his kingdom, he shall copy to himself the Deuteronomy of this Law in a volume, taking the copy of the priests of the Levitical tribe,\n"
	"& he shall have it with him, & shall read it all the days of his life, that he may learn to fear our Lord his God, and keep his words and ceremonies, that are commanded in the law.\n"
	"And that his heart be not lifted up into pride over his brethren, nor decline to the right side or the left side, that he may reign a long time, and his sons over Israel.";