const char* chap172 = "When our Lord thy God hath destroyed the nations, whose land he will deliver to thee, and thou dost possess it, and dwellest in the cities and houses thereof:\n"
	"three cities shalt thou separate to thee in the midst of the Land, which our Lord thy God will give thee in possession,\n"
	"preparing diligently the way: and thou shalt divide the whole province of thy Land equally into three parts: that he which for murder is a fugitive, may have near at hand, wither to escape.\n"
	"This shall be the law of the murderer that flyeth, whose life is to be saved: He that striketh his neighbour unwitting, & that is proved yesterday & the day before to have had no hatred against him,\n"
	"but to have gone with him simply unto the wood to cut wood, and in cutting of wood^ the axe slipped out of his hand, & the iron falling from the handle struck his friend, and killed him: he shall fly to one of the cities aforesaid, and live:\n"
	"lest perhaps the next kinsman of him, whose blood was shed, pricked with sorrow, pursue, and apprehend him if the way be too long, and strike his life that is not guilty of death, because he is proved to have had no hatred before, against him that was slain.\n"
	"Therefore I command thee, that thou separate three cities of equal distance one from another.\n"
	"And when our Lord thy God shall have dilated thy borders, as he sware to thy fathers, and shall give thee all the Land that he promised them\n"
	"(yet so, if thou keep his commandments, & do the things which I command thee this day, that thou love our Lord thy God, and walk in his ways at all time) thou shalt add to thee other three cities, and shalt double the number of the three cities aforesaid:\n"
	"that innocent blood be not shed in the midst of the Land, which our Lord thy God will give thee to possess, lest thou be guilty of blood.\n"
	"But if any man hating his neighbour, lie in wait for his life, and rise and strike him, and he die, and he fly to one of the cities aforesaid,\n"
	"the ancients of his city shall send, and take him out of the place of refuge, and shall deliver him into the hand of the kinsman of him, whose blood was shed, & he shall die.\n"
	"Thou shalt not pity him, & thou shalt take away the guilty blood out of Israel, that it may be well with thee.\n"
	"Thou shalt not take, and transfer thy neighbour's bounds, which thy predecessors did set in thy possession, which our Lord thy God will give thee in the Land, that thou shalt receive to possess.\n"
	"One witness shall not stand against any man, whatsoever sin, or wickedness it be: but in the mouth of two or three witnesses shall every word stand.\n"
	"If a lying witness stand against a man, accusing him of prevarication,\n"
	"both of them, whose the cause is, shall stand before our Lord in the sight of the Priests and the judges that shall be in those days.\n"
	"And when searching most diligently, they shall find that the false witness hath said a lie against his brother:\n"
	"they shall render to him as he meant to do to this brother, and thou shalt take away the evil out of the midst of thee:\n"
	"that others hearing may have fear, and may not be bold to do such things.\n"
	"Thou shalt not pity him, but life for life, eye for eye, tooth for tooth, hand for hand, foot for foot shall thou exact.";