const char* chap175 = "Thou shalt not see thy brother's oxe or sheep straying, and pass by: but shalt bring it back to thy brother,\n"
	"although thy brother be not nigh, and thou know him not: thou shalt bring them unto thy house, and they shall be with thee until thy brother seek them, and receive them.\n"
	"In like manner shalt thou do with his ass, and with his raiment, and with every thing of thy brother's, that shall be lost: if thou find it, neglect it not as pertaining to another.\n"
	"If thou see thy brother's ass or oxe to be fallen in the way, thou shalt not contemn it, but shalt lift it up with him.\n"
	"A woman shall not be clothed with man's apparel, neither shall a man use woman�s apparel: for he is abominable before God that doeth these things.\n"
	"If walking by the way thou find a bird�s nest in a tree or on the ground, and the dam sitting upon the young or the eggs: thou shalt not hold her with her young,\n"
	"but shalt let her go, taking the young and holding them: that it may be well with thee, and thou mayest live a long time.\n"
	"When thou buildest a new house, thou shalt make a battlement to the roof round about: lest blood be shed in thy house, and thou be guilty, another slipping, and falling headlong.\n"
	"Thou shalt not sow thy vineyard with diverse seed: lest both the seed which thou didst sow, and the things that grow of the vineyard be sanctified together.\n"
	"Thou shalt not plough with an oxe and ass together.\n"
	"Thou shalt not wear a garment that is woven of wool and linen.\n"
	"Thou shalt make little cords in the hem at the four corners of thy cloak, wherewith thou shalt be covered.\n"
	"If a man marry a wife, and afterward hate her,\n"
	"and seek occasions to put her away, objecting unto her a very ill name, and say: I took this wife, and companying with her: I found her not a virgin:\n"
	"her father and mother shall take her, and shall carry with them the signs of her virginity to the ancients of the city that are in the gate:\n"
	"and the father shall say: I gave my daughter unto this man to wife: whom because he hateth,\n"
	"he layeth unto her a very ill name, so that he saith: I found not thy daughter a virgin: and behold these are the signs of my daughters virginity. They shall spread the vesture before the ancients of the city:\n"
	"and the ancients of that city shall take the man, and beat him,\n"
	"condemning him besides^ in a hundred sicles of silver, which he shall give to the wench's father, because he hath infamously spread a very ill name upon a virgin of Israel: and he shall have her to wife, and cannot put her away all the days of his life.\n"
	"But if it be true which he objected, and virginity be not found in the wench,\n"
	"they shall cast her forth without the doors of her father's house, and the men of her city shall stone her to death, & she shall die: because she hath done wickedness in Israel, to fornicate in her father's house: and thou shalt take away the evil out of the midst of thee.\n"
	"If a man lie with another's man wife, both shall die, that is to say, the adulterer and the adulteress: and thou shalt take away the evil out of Israel.\n"
	"If a man have despoused a maid that is a virgin, and some man find her in the city, & lie with her,\n"
	"thou shalt bring forth both of them to the gate of that city, & they shall be stoned: the maid, because she cried not, being in the city: the man, because he hath humbled his neighbour's wife, and thou shalt take away the evil from the midst of thee.\n"
	"But if the man find the maid that is despoused in the field, and taking her lie with her, he alone shall die:\n"
	"the maid shall suffer nothing, neither is she guilty of death: for as a thief riseth against his brother, and taketh away his life, so also did the maid suffer.\n"
	"She was alone in the field: she cried, and there was no man to deliver her.\n"
	"If a man find a maid that is a virgin, which hath not a spouse, and taking her lie with her, and the matter come into judgment,\n"
	"he that lay with her, shall give to the father of the maid fifty sicles of silver, and shall have her to wife, because he hath humbled her: he cannot put her away all the days of his life.\n"
	"No man shall take his father's wife, nor reveal his covering.";