const char* chap177 = "If a man take a wife, and have her, and she find not grace before his eyes for some loathsomeness: he shall write a bill of divorce, and shall give it in her hand, and dismiss her out of his house.\n"
	"And being departed, when she shall have married another husband,\n"
	"and he also hateth her, and hath given her a bill of divorce, and hath dismissed her out of his house, or is dead:\n"
	"the former husband cannot take her again to wife: because she is polluted, and is made abominable before our Lord: lest thou make thy Land to sin, which our Lord thy God shall deliver thee to possess.\n"
	"When a man hath lately taken a wife, he shall not go forth to battle, neither shall any public necessity be enjoined him, but he shall attend to his own house without fault, that one year he may rejoice with his wife.\n"
	"Thou shalt not take for a pledge the nether or the upper millstone: because he hath pledged his life to thee.\n"
	"If any man be taken soliciting his brother of the children of Israel, & selling him take a price, he shall be slain, and thou shalt take away the evil from the midst of thee.\n"
	"Observe diligently that thou incur not the plague of leprosy, but thou shalt do whatsoever the Priests of the Levitical stock shall teach thee, according to that, which I have commanded them, and fulfill thou it carefully.\n"
	"Remember what our Lord your God did to Mary, in the way when you came out of Aegypt.\n"
	"When thou shalt require of thy neighbour any thing that he oweth thee, thou shalt not enter into his house to take away a pledge:\n"
	"but thou shalt stand without, and he shall bring forth to thee that which he hath.\n"
	"But if he be poor, the pledge shall not lodge with thee that night,\n"
	"but forthwith thou shalt restore it to him before the going down of the sun: that sleeping in his raiment, he may bless thee, and thou mayest have justice before our Lord thy God.\n"
	"Thou shalt not deny the hire of the needy, and poor man thy brother, or the stranger, that dwelleth with thee in the land, and is within thy gates:\n"
	"but the same day thou shalt pay him the price of his labour, before the going down of the sun because he is poor, and there-withal sustaineth his life: lest he cry against thee to our Lord, and it be reputed to thee for a sin.\n"
	"The fathers shall not be slain for the children, nor the children for the fathers, but every one shall die for his own sin,\n"
	"Thou shalt not pervert the judgment of the stranger and the pupil, neither shalt thou take away the widow's raiment for a pledge.\n"
	"Remember that thou didst serve in Aegypt, & our Lord thy God delivered thee from thence. Therefore I command thee that thou do this thing.\n"
	"When thou hast reaped the corn in the field, and forgetting hast left a sheaf, thou shalt not return to take it away: but thou shalt suffer the stranger, and the pupil, and the widow to take it away, that our Lord thy God may bless thee in all the work of thy hands.\n"
	"If thou have gathered the fruits of thy olive trees, whatsoever remaineth on the trees, thou shalt not return to gather it: but shalt leave it to the stranger, the pupil, and the widow.\n"
	"If thou make vintage of thy vineyard, thou shalt not gather the clusters that remain, but they shall go to the uses of the stranger, the pupil, & the widow.\n"
	"Remember that thou also didst serve in Aegypt, and therefore I command thee that thou do this thing.";