const char* chap179 = "And when thou art entered into the Land, which our Lord thy God will give thee to possess, and hast obtained it, and dwellest in it:\n"
	"thou shalt take first of all thy fruits, and put them in a maund, and shalt go to the place, which our Lord thy God shall choose, that his name may be invocated there:\n"
	"and thou shalt go to the Priest, that shall be in those days, and say to him: I profess this day before our Lord thy God, that I am entered into the Land, for the which he sware to our fathers, that he would give it us.\n"
	"And the Priest taking the maund at his hand, shall set it before the altar of our Lord thy God:\n"
	"and thou shalt speak in the sight of our Lord God: The Syrian persecuted my father, who descended into Aegypt, and sojourned there in a very small number, and grew into a nation great and strong and of an infinite multitude.\n"
	"And the Aegyptians afflicted us, and persecuted us, laying on most grievous burdens:\n"
	"and we cried to our Lord the God of our fathers: who heard us, and respected our affliction, and labour, and distress:\n"
	"and brought us out of Aegypt in a strong hand, a stretched out arm, in great terror, in signs and wonders:\n"
	"and brought us into this place, and delivered to us this Land flowing with milk and honey.\n"
	"And therefore now I offer first fruits of the Land, which our Lord hath given me. And thou shalt leave them in the sight of our Lord thy God, adoring our Lord thy God,\n"
	"And thou shalt feast in all the good things, which our Lord thy God hath given to thee, and thy house, thou and the Levite, and the stranger that is with thee.\n"
	"When thou hast finished the tithe of all thy fruits, in the third year of tithes thou shalt give to the Levite, & the stranger, & the pupil, & the widow, that they may eat within thy gates, and be filled:\n"
	"& thou shalt speak in the sight of our Lord thy God: I have brought that which is sanctified out of my house, & have given it to the Levite, and the stranger, and the pupil, and the widow, as thou hast commanded me: I have not transgressed thy commandments nor forgotten thy precepts.\n"
	"I have not eaten of them in my mourning, nor separated them in any uncleanness, nor spent of them any thing in funerals. I have obeyed the voice of our Lord my God, and have done all things as thou didst command me.\n"
	"Look from thy sanctuary, and thy high habitation of heaven, and bless thy people Israel, and the Land, which thou hast given us, as thou swarest to our fathers, a land flowing with milk & honey.\n"
	"This day our Lord thy God hath commanded thee to do these commandments and judgments: that thou keep and fulfill them with all thy heart, and with all thy soul.\n"
	"Thou hast chosen our Lord this day to be thy God, and to walk in his ways, and keep his ceremonies, and precepts, and judgements, & obey his commandment.\n"
	"And our Lord hath chosen thee this day, that thou shouldst be his peculiar people, as he hath spoken to thee, and thou shouldst keep all his commandments:\n"
	"and make thee higher than all nations which he created, to his praise, and name, and glory: that thou mayst be a holy people of our Lord thy God, as he hath spoken.";