const char* chap18 = "And God appeared to him in the vale of Mambre as he sat in the door of his tent, in the very heat of the day.\n"
	"And when he had lifted up his eyes, there appeared to him three men standing near unto him: whom after he had seen, he ran to meet them from the door of his tent, and adored to the ground.\n"
	"And He said^ Lord, if I have found grace in thy sight, go not past thy servant:\n"
	"but I will fetch a little water, and wash ye your feet, and rest ye under the tree.\n"
	"And I will set a morsel of bread, and strengthen your heart, afterward you shall pass: for therefore are you come aside to your servant. Who said: Do as thou hast spoken.\n"
	"Abraham made haste into the tent to Sara, and said to her: Make haste, temper together three measures of flour, and make hearth cakes.\n"
	"But himself ran to the herd, and took from thence a calf very tender and very good, and gave it to a young man: who made haste and boiled it.\n"
	"He took also butter and milk, and the calf which he had boiled, and set before them: but himself did stand beside them under the tree.\n"
	"And when they had eaten, they said to him: Where is Sara thy wife? He answered: Lo she is in the tent.\n"
	"To whom he said: Returning I will come to thee at this time, life accompanying, and Sara thy wife shall have a son. Which when Sara heard, she laughed behind the door of the tent.\n"
	"And they were both aged, and far entered in years, and it ceased to be with Sara after the manner of women.\n"
	"Who laughed secretly saying: After I am waxen old, and my Lord is an old one, shall I give myself to pleasure?\n"
	"And our Lord said to Abraham: Why did Sara laugh, saying: Shall I an old woman bear a child indeed?\n"
	"Is there any thing hard to God? According to appointment I will return to thee this very self-same time, life accompanying, & Sara shall have a son.\n"
	"Sara denied, saying: I laughed not; being much afraid. But our Lord: It is not so, saith he, but thou didst laugh.\n"
	"When the men therefore were risen up from thence, they turned their eyes against Sodome: and Abraham did go with them, bringing them on the way.\n"
	"And our Lord said: Can I conceal from Abraham the things which I will do,\n"
	"whereas he shall be into a Nation great, and very strong, and in him are TO BE BLESSED ALL THE NATIONS OF THE EARTH?\n"
	"For I know that he will command his children, and his house after him that they keep the way of the Lord, & do judgement and justice: that for Abraham's sake the Lord may bring to effect all the things that he hath spoken unto him. Therefore said our Lord:\n"
	"The cry of Sodome and Gomorre is multiplied, and their sin is aggravated exceedingly.\n"
	"I will descend, and see whether they have in act accomplished the cry that is come to me: or whether it be not so, that I may know.\n"
	"And they turned themselves from thence, and went their way to Sodome: but Abraham as yet stood before our Lord.\n"
	"And approaching he said: What! Wilt thou destroy the just with the wicked?\n"
	"If there shall be fifty just persons in the city, shall they perish withal? And wilt thou spare that place for fifty just, if they be therein?\n"
	"Be it far from thee, that thou do this thing, and that thou kill the just with the wicked, and that the just be in like case as the wicked, this is not beseeming thee, which judgest all the earth: no, thou wilt not do this judgement.\n"
	"And our Lord said to him: If I shall find in Sodome fifty just persons within the city, I will spare the whole place for their sake.\n"
	"And Abraham answered, and said: Because I have once begun, I will speak to my Lord, whereas I am dust and ashes.\n"
	"What if there shall be five less than fifty just persons? Wilt thou for forty five destroy the whole city? And he said: I will not destroy it, if I shall find five and forty.\n"
	"And again he said unto him: But if forty shall be found there, what wilt thou do? He said: I will not strike it for forty's sake.\n"
	"Lord, saith he, be not angry I beseech thee, if I speak: What if thirty shall be found there? He answered: I will not do it, if I shall find thirty there.\n"
	"Because, saith he, I have once begun, I will speak to my Lord: What if twenty shall be found there? He said: I will not destroy it for twenty's sake.\n"
	"I beseech thee, saith he, be not angry Lord, if I speak yet once more: What if ten shall be found there? And he said: I will not destroy it for ten's sake.\n"
	"And our Lord departed after that he ceased to speak unto Abraham: and Abraham returned into his place.";