const char* chap180 = "And Moyses and the ancients of Israel commanded the people, saying: Keep every commandment that I command you this day.\n"
	"And when you are passed over Jordan into the land, which our Lord thy God will give thee, thou shalt erect great stones, and shalt polish them with plaster.\n"
	"that thou mayst write on them all the words of this law, when thou hast passed over Jordan: that thou mayst enter into the Land, which our Lord thy God will give thee, a land flowing with milk and honey, as he sware to thy fathers.\n"
	"When therefore you are passed Jordan, erect the stones, which I command you this day, in mount Hebal, and thou shalt polish them with plaster:\n"
	"and thou shalt build there an altar to our Lord thy God^ of stones, which iron hath not touched,\n"
	"and of stones not fashioned nor polished: and thou shalt put upon it holocausts to our Lord thy God,\n"
	"and shalt immolate pacific hosts, and eat there, and feast before our Lord thy God.\n"
	"And thou shalt write upon the stones all the words of this law plainly and clearly.\n"
	"And Moyses and the Priests of the Levitical stock said to all Israel: Attend, and hear Israel: This day thou art made the people of our Lord thy God:\n"
	"thou shalt hear his voice, and do the commandments and justices, which I command thee.\n"
	"And Moyses commanded the people in that day, saying:\n"
	"These shall stand to bless the people, upon mount Garizim, when you are past Jordan: Simeon, Levi, Judas, Issachar, Joseph, & Benjamin.\n"
	"And over against them these shall stand to curse on mount Hebal: Ruben, Gad, and Aser, and Zabulon, Dan and Nephthali.\n"
	"And the Levites shall pronounce, and say to all the men of Israel with a high voice:\n"
	"Cursed be the man that maketh a graven and molten thing, the abomination of our Lord, the work of the hands of artificers, & shall put it in secret, and all the people shall answer, and say: Amen.\n"
	"Cursed be he that honoureth not his father and mother. And all the people shall say: Amen.\n"
	"Cursed be he that removeth his neighbour's bounds. And all the people shall say: Amen.\n"
	"Cursed be he that maketh the blind to go amiss in his journey. And all the people shall say: Amen.\n"
	"Cursed be he that perverteth the judgment of the stranger, of the pupil and the widow. And all the people shall say: Amen.\n"
	"Cursed be he that sleepeth with his father's wife, and revealeth the cover of his bed. And all the people shall say: Amen.\n"
	"Cursed be he that lieth with any beast. And all the people shall say: Amen.\n"
	"Cursed be he that sleepeth with his sister, the daughter of his father, or of his mother. And all the people shall say: Amen.\n"
	"Cursed be he that sleepeth with his mother in law. And all the people shall say: Amen.\n"
	"Cursed be he that secretly striketh his neighbour. And all the people shall say: Amen.\n"
	"Cursed be he that taketh gifts, to kill the soul of innocent blood. And all the people shall say: Amen.\n"
	"Cursed be he that abideth not in the words of this law, and fulfilleth them not in work, and all the people shall say: Amen.";