const char* chap181 = "But if thou wilt hear the voice of our Lord thy God, that thou do and keep all his commandments, which I command thee this day, our Lord thy God will make thee higher than all nations, that be on the earth.\n"
	"And all these blessings shall come upon thee, and overtake thee: yet so if thou hear his precepts.\n"
	"Blessed shalt thou be in the city, and blessed in the field.\n"
	"Blessed shall be the fruit of thy womb, and the fruit of thy ground, and the fruit of thy cattle, the troops of thy herds, & the folds of thy sheep.\n"
	"Blessed shall thy barns be, and blessed thy remains:\n"
	"Blessed shalt thou be coming in and going out.\n"
	"Our Lord will give thine enemies, that rise up against thee, to fall down in thy sight: one way they shall come against thee, and seven ways they shall fly from thy face.\n"
	"Our Lord will send forth blessing upon thy cellars, and upon all the works of thy hands: and will bless thee in the land, that thou shalt receive.\n"
	"Our Lord will raise thee up unto himself to be a holy people, as he sware to thee: If thou keep the commandments of our Lord thy God, and walk in his ways.\n"
	"And all the people of the earth shall see that the name of our Lord is invocated upon thee, and they shall fear thee.\n"
	"Our Lord will make thee abound with all goods, with the fruit of thy womb, & the fruit of thy cattle, with the fruit of thy land, which our Lord sware to thy fathers that he would give thee.\n"
	"Our Lord will open his most excellent treasure, the heaven, that it may give rain to thy land in due season: and will bless all the works of thy hands. And thou shalt lend to many nations, and thyself shalt take loan of no man.\n"
	"And our Lord shall make thee the head, and not the tail: and thou shalt be always above, and not under: yet so, if thou wilt hear the commandments of our Lord thy God which I command thee this day, and keep & do them,\n"
	"& decline not from them, neither to the right hand, nor to the left, nor follow strange gods, nor serve them.\n"
	"But if thou wilt not hear the voice of our Lord thy God, to keep & do all his commandments & ceremonies which I command thee this day, all these curses shall come upon thee, and overtake thee.\n"
	"Cursed shalt thou be in the city, cursed in the field.\n"
	"Cursed shall thy barn be, and cursed thy remains.\n"
	"Cursed shall be the fruit of thy womb, and the fruit of thy ground, the herds of thy oxen, and the flocks of thy sheep.\n"
	"Cursed shalt thou be coming in, and cursed going out.\n"
	"Our Lord shall send upon thee famine and hunger, & rebuke upon all the works which thou shalt do: until he consume and destroy thee quickly, for thy most wicked inventions, wherein thou hast forsaken me.\n"
	"Our Lord set the pestilence upon thee, until he consume thee out of the land, which thou shalt enter in to possess.\n"
	"Our Lord strike thee with poverty, with the fever and cold, with burning and heat, & with corrupt air and blasting, and pursue thee till thou perish.\n"
	"Be the heaven that is over thee, of brass, & the ground that thou treadest, of Iron.\n"
	"Our Lord give dust for rain upon thy land, and ashes descend from heaven upon thee, till thou be consumed.\n"
	"Our Lord deliver thee to fall down before thine enemies. One way go thou forth against them, & fly seven, and be thou dispersed throughout all the Kingdoms of the earth.\n"
	"And be thy carcass meat to all the fowls of the air, & beasts of the earth, and be there none to drive them away.\n"
	"Our Lord strike thee with the boyle of Aegypt, and the part of thy body, by the which dung is cast out, with scab also and itch, so that thou canst not be cured.\n"
	"Our Lord strike thee with madness and blindness and fury of mind,\n"
	"& grope thou at midday as the blind is wont to grope in the dark, and direct not thy ways. And at all times sustain thou wrong, and be thou oppressed with violence, neither have thou any to deliver thee.\n"
	"Take thou a wife, and another sleep with her. Build thou a house, and dwell not therein. Plant thou a vineyard, and take not the vintage thereof.\n"
	"Be thy oxe immolated before thee, and thou not eat thereof. Be thy ass taken away in thy sight, and not restored to thee. Be thy sheep given to thine enemies, and be there none to help thee.\n"
	"Be thy sons and thy daughters delivered to another people, thine eyes seeing, and dazzling at the sight of them all the day, and be there no strength in thy hand.\n"
	"The fruits of thy land, and all thy labours let a people eat, which thou knowest not: and be thou always sustaining calumny, and oppressed all days,\n"
	"and astonished at the terror of those things, which thine eyes shall see.\n"
	"Our Lord strike thee with a very sore botch in the knees and shanks, and be thou uncurable from the sole of the foot unto the top of thy head.\n"
	"Our Lord shall bring thee, and thy king whom thou shalt appoint over thee, unto a nation, which thou and thy fathers know not: & there thou shalt serve strange gods, wood and stone.\n"
	"And thou shalt be destroyed for a proverb and fable to all peoples, unto whom our Lord shall bring thee in.\n"
	"Thou shalt cast much seed into the ground, and gather little: because the locusts shall devour all things.\n"
	"Thou shalt plant a vineyard, and dig, and the wine thou shalt not drink, nor gather any thing thereof: because it shall be wasted with worms.\n"
	"Thou shalt have olives in all thy borders, and shalt not be anointed with the oil: because they shall drop away, and perish.\n"
	"Thou shalt beget sons and daughters, and shalt not enjoy them: because they shall be led into captivity.\n"
	"All thy trees and the fruits of thy ground the blasting shall consume.\n"
	"The stranger that liveth with thee in the Land, shall ascend over thee, and shall be higher: and thou shalt descend downward, and be inferior.\n"
	"He shall lend thee, and thou shalt not lend him. He shall be as the head, and thou shalt be the tail.\n"
	"And all these curses shall come upon thee, and pursuing shall overtake thee, till thou perish: because thou heard not the voice of our Lord thy God, nor kept his commandments and ceremonies which he commanded thee.\n"
	"And they shall be in thee as signs & wonders, and in thy seed for ever:\n"
	"because thou didst not serve our Lord thy God in joy and gladness of heart, for the abundance of all things.\n"
	"Thou shalt serve thine enemy, whom our Lord will send upon thee, in hunger, and thirst, and nakedness, and all penury, and he shall put an iron yoke upon thy neck, till he consume thee.\n"
	"Our Lord will bring upon thee a Nation from a far, and from the uttermost ends of the earth, in likeness of an eagle that flyeth with vehemency: whose tongue thou canst not understand:\n"
	"a very malapert Nation, that will attribute nothing to the ancient, nor have pity on the little one,\n"
	"and will devour the fruit of thy cattle, and the fruits of thy Land: until thou perish, and will not leave thee wheat, wine, and oil, herds of oxen, and flocks of sheep: until it destroy thee,\n"
	"and consume thee in all thy cities, and thy strong and high walls be destroyed, wherein thou hadst confidence in all thy Land. Thou shalt be besieged within thy gates in all thy Land, which our Lord thy God will give thee:\n"
	"and thou shalt eat the fruit of thy womb, and the flesh of thy sons & of thy daughters, which our Lord thy God shall give thee, in the distress and vastation wherewith thine enemy shall oppress thee.\n"
	"The man that is delicate in thee & very riotous, shall much envy his own brother, and his wife that lieth in his bosom,\n"
	"so that he shall not give them of the flesh of his children, which he will eat: because he hath nothing else in the siege and penury, wherewith thine enemies shall waste thee within all thy gates.\n"
	"The tender and delicate woman, that could not go upon the ground; nor set down her foot for over-much niceness and tenderness, will envy her husband, that lieth in her bosom, upon the flesh of her son, and daughter:\n"
	"and the filthiness of the after births, that come forth from the midst of her thighs, and upon the children that are born the same hour. For they shall eat them secretly, because of the penury of all things, in the siege and vastation, wherewith thine enemy shall oppress thee within thy gates.\n"
	"Unless thou keep and do all the words of this law, that be written in this volume, and fear his name glorious and terrible, that is, Our Lord thy God:\n"
	"our Lord shall increase thy plagues, and the plagues of thy seed, great plagues and continuing, sore infirmities and perpetual.\n"
	"And he shall turn upon thee all the afflictions of Aegypt, which thou didst fear, and they shall cleave to thee.\n"
	"Moreover also all the diseases, and plagues, that be not written in the volume of this law, our Lord will bring upon thee, till he consume thee:\n"
	"& you shall remain few in number, which before was as the stars of heaven for multitude, because thou heardest not the voice of our Lord thy God.\n"
	"And as before our Lord rejoiced upon you, doing good to you, & multiplying you: so he shall rejoice destroying and subverting you, so that you may be taken away from the Land, which thou shalt enter to possess.\n"
	"Our Lord shall disperse thee into all peoples, from the farthest parts of the earth to the ends thereof: and there thou shalt serve strange gods, which thou art ignorant of and thy fathers, wood and stone.\n"
	"In those nations also thou shalt not be quiet, neither shall there be resting for the step of thy foot. For our Lord will give thee a fearful heart, and dazzling eyes, & a soul consumed with pensiveness:\n"
	"and thy life shall be as it were hanging before thee. Thou shalt fear night and day, and thou shalt not trust in thy life.\n"
	"In the morning thou shalt say: Who will grant me evening? And at evening: Who will grant me morning? For the fearfulness of thy heart, wherewith thou shalt be terrified, and for those things which thou shalt see with thine eyes.\n"
	"Our Lord shall bring thee again with ships into Aegypt by the way, whereof he said to thee that thou shouldst see it no more. There shalt thou be sold to thine enemies for bondmen and bondwomen, and no man shall buy you.";