const char* chap182 = "These are the words of the covenant which our Lord commanded Moyses to make with the children of Israel in the Land of Moab: beside that covenant which he made with them in Horeb.\n"
	"And Moyses called all Israel, and said to them: you saw all things, that our Lord did before you in the Land of Aegypt to Pharao, and to all his servants, and to his whole land,\n"
	"the great tentations, which thine eyes have seen, those mighty signs, and wonders,\n"
	"and our Lord hath not given you a heart to understand, and eyes to see, and ears that can hear, unto this present day.\n"
	"He hath brought you forty years by the desert: your garments are not worn out, neither are the shoes of your feet consumed with age.\n"
	"Bread you have not eaten, wine and sicer you have not drunk: that you might know that I am the Lord your God.\n"
	"And you came to this place: and there came forth Sehon the king of Hesebon, and Og the king of Basan, meeting us to fight. And we struck them.\n"
	"and took their land, and delivered it in possession to Ruben and Gad, and the half tribe of Manasses.\n"
	"Keep therefore the words of this covenant, and fulfill them: that you may understand all things that you do.\n"
	"You stand this day all before our Lord your God, your Princes, and tribes, and ancients, and doctors, all the people of Israel,\n"
	"your children and your wives, and the strangers that abide with thee in the camp, besides the cutters of wood, and them, that carry water:\n"
	"that thou mayest pass in the covenant of our Lord thy God, and in the oath which in this day our Lord thy God maketh with thee:\n"
	"that he may raise thee up a people to himself, and he be thy God as he hath spoken to thee, and as he sware to thy fathers, Abraham, Isaac, and Jacob.\n"
	"Neither with you only do I make this covenant, and confirm these oaths,\n"
	"but with all that be present & absent.\n"
	"For you know how we dwelt in the Land of Aegypt, and how we have passed through the midst of nations, which passing through\n"
	"you have seen their abominations & filth, that is to say, their idols, wood and stone, silver and gold, which they worshipped.\n"
	"Lest perhaps there be among you man or woman, family or tribe, whose heart is turned away this day from our Lord God, to go and serve the gods of those Nations: and there be among you a root bringing forth gall & bitterness.\n"
	"And when he shall hear the words of this oath, he bless himself in his heart, saying: I shall have peace, and walk in the pravity of my heart: and the drunken take to her the thirsty,\n"
	"& our Lord forgive him not: but then his fury most specially fume, and his zeal against that man, and all the curses sit upon him, that be written in this volume: & our Lord abolish his name under heaven,\n"
	"and consume him unto perdition out of all the tribes of Israel, according to the curses that are contained in the Book of this law & covenant.\n"
	"And the generation following shall say, and the children that shall be born from thence-forth, and the strangers that shall come from a far, seeing the plagues of that Land, & the infirmities, wherewith our Lord hath afflicted it,\n"
	"burning it with brimstone, and heat of the salt, so that it can no more be sown, nor any green thing spring thereof, after the example of the subversion of Sodom and Gomorrha, Adama, and Seboim, which our Lord subverted in his wrath & fury.\n"
	"And all the Nations shall say: Why hath the Lord done thus to this Land? What is this exceeding wrath of his fury?\n"
	"And they shall answer: Because they forsook the covenant of the Lord, which he made with their fathers, when he brought them out of the Land of Aegypt:\n"
	"and they have served strange gods, and adored them, whom they knew not, and to whom they had not been designed:\n"
	"therefore the fury of the Lord was wrath against this Land, to bring upon it all the curses that are written in this volume:\n"
	"and he hath cast them out of their land, in wrath and fury, and in very great indignation, and hath thrown them into a strange land, as this day it is proved.\n"
	"Things hidden, to our Lord God, which are manifest, to us and to our children for ever, that we may do all the words of this Law.";