const char* chap186 = "This is the blessing, wherewith Moyses the man of God blessed the children of Israel before his death.\n"
	"And he said: Our Lord came from Sinai, and from Seir is he risen to us: he hath appeared from mount Pharan, and with him thousands of Saints. In his right hand a fiery law.\n"
	"He hath loved the peoples, all the Saints are in his hand: and they that approach to his feet shall receive of his doctrine.\n"
	"Moyses commanded us a law, the inheritance of the multitude of Jacob.\n"
	"He shall be king with the most right, the Princes of the people being assembled with the tribes of Israel.\n"
	"Live Ruben, and die he not, and be he little in number.\n"
	"This is the blessing of Judas: Hear Lord the voice of Judas, and bring him in unto his people: his hands shall fight for him, and he shall be his helper against his adversaries.\n"
	"To Levi also he said: Thy perfection, and thy doctrine be to thy holy man, whom thou hast proved in tentation, and judged at the Waters of contradiction.\n"
	"He that said to his father and to his mother: I know you not; and to his brethren: I know you not: and they knew not their children. These kept thy word, and observed thy covenant,\n"
	"thy judgments, o Jacob, and thy law, o Israel: they shall put incense in thy fury, and holocaust upon thine altar.\n"
	"Bless Lord his strength, and receive the works of his hands. Strike the backs of his enemies, and they that hate him, let them not rise up.\n"
	"And to Benjamin he said: The best beloved of our Lord shall dwell confidently in him: as in a bride-chamber all the day shall he abide, and between his shoulders shall he rest.\n"
	"To Joseph also he said: Of the blessing of our Lord be his land, of the fruits of heaven, and the dew, & the depth lying underneath.\n"
	"Of the pomes of the fruits of the sun and moon,\n"
	"of the tops of the old mountains, of the pomes of the eternal hills:\n"
	"and of the fruits of the earth, and of the fullness thereof. The blessing of him, that appeared in the bush, come upon the head of Joseph, and upon the crown of the Nazarite among his brethren.\n"
	"His beauty as of the first born of an oxe, his horns the horns of an unicorn: in them shall he winnow the Nations even to the ends of the earth. These are the multitudes of Ephraim, and these the thousands of Manasses.\n"
	"And to Zabulon he said: Rejoice Zabulon in thy going out, and Issachar in thy tabernacles.\n"
	"They shall call the peoples to the mountain: there shall they immolate the victims of justice. Who shall suck the inundation of the sea as milk, and the hidden treasures of the sands.\n"
	"And to Gad he said: Blessed be Gad in breadth: as a lion hath he rested, and taken the arm and the top of the head.\n"
	"And he saw his principality, that in his part the doctor was reposed: which was with the princes of the people, and did the justices of our Lord, and his judgment with Israel.\n"
	"To Dan also he said: Dan a lion's whelp, he shall flow largely from Basan.\n"
	"And to Nephthali he said: Nephthali shall enjoy abundance, and shall be full of the blessings of our Lord: the sea and the south he shall possess.\n"
	"To Aser also he said: Blessed be Aser in children, be he acceptable to his brethren, and dip he in oil his foot.\n"
	"His shoe iron and brass. As the days of thy youth, so also thy old age.\n"
	"There is no other God as the God of the rightest: the mounter of heaven is thy helper. By his magnificence the clouds run hither and thither,\n"
	"his habitation is above, and under the everlasting arms: he shall cast out the enemy from thy face, and shall say: Be destroyed.\n"
	"Israel shall dwell confidently, and alone. The eye of Jacob in the land of corn and wine, and the heavens shall be misty with dew.\n"
	"Blessed art thou Israel: who is like to thee, o people that art saved in our Lord, the shield of thy help, and the sword of thy glory? Thy enemies shall deny thee, and thou shalt tread their necks.";