const char* chap190 = "Josue therefore rising up in the night, removed the camp: and departing from Setim, they came to Jordan, he and all the children of Israel, & abode there for three days.\n"
	"Which being passed, the heralds went through the midst of the camp,\n"
	"and began to proclaim: When you shall see the ark of covenant of our Lord your God, and the Priests of the Levitical stock carrying it, rise you also, & follow them going before:\n"
	"& let there be between you & the ark the space of two thousand cubits: that you may see it a far off, & know which way you may go: because you have not walked by it before: & beware you approach not to the ark.\n"
	"And Josue said to the people: Be sanctified, for tomorrow our Lord will do among you marvelous things.\n"
	"And he said to the Priests: Take up the ark of the covenant, & go before the people. Who fulfilling his commandments, took it, and walked before them.\n"
	"And our Lord said to Josue: This day will I begin to exalt thee before all Israel: that they may know as I was with Moyses, so am I with thee also.\n"
	"And do thou command the Priests, that carry the ark of the testament, and say to them: When you shall be entered into part of the water of Jordan, stand in it.\n"
	"And Josue said to the children of Israel: Come hither, and hear the word of our Lord your God.\n"
	"And again he said: In this you shall know that our Lord the living God is in the midst of you, and shall destroy in your sight the Chananite and Hetheite, the Heveite and Pherezite, the Gergesite also and the Jebusite, and the Amorrhite.\n"
	"Behold the ark of the covenant of the Lord of all the earth shall go before you into Jordan.\n"
	"Prepare twelve men of the tribes of Israel, one of every tribe.\n"
	"And when the Priests that carry the ark of the Lord of the whole earth shall set the steps of their feet in the waters of Jordan, the waters that are beneath shall run down and decay: and those that come from above, shall stand together in one heap.\n"
	"Therefore the people went out of their tabernacles to pass over Jordan: and the Priests that carried the ark of the covenant, went on before them.\n"
	"And they being entered into Jordan, and their feet dipped in part of the water (and Jordan in the harvest time had filled the banks of his channel)\n"
	"the waters that came downward stood in one place, and like a mountain swelling up appeared far from the city, that is called Adom, to the place of Sarthan: but those that were beneath ran down into the Sea of the wilderness (which now is called the dead sea) until they wholly decayed.\n"
	"And the people went against Jericho: and the Priests that carried the ark of the covenant of our Lord, stood girded upon the dry ground in the midst of Jordan, and all the people passed over through the dry channel.";