const char* chap193 = "And Jericho was shut and fenced, for fear of the children of Israel, and no man durst go out or come in.\n"
	"And our Lord said to Josue: Behold I have given into thy hands Jericho, & the king thereof, & all the valiant men.\n"
	"Go round about the city all you that be men of war once a day: so shall you do six days.\n"
	"And the seventh day the Priests shall take up the seven trumpets, which are used in the Jubilee, and shall go before the ark of the covenant: and you shall go about the city seven times, and the Priests shall sound with trumpets.\n"
	"And when the voice of the trumpet shall sound in length and with a broken tune, and shall sound in your ears, all the people shall cry together with a very great shout, and the walls of the city shall fall to the ground, and they shall enter in every one at the place against which they shall stand.\n"
	"Josue therefore the son of Nun called the Priests, and said to them: Take up the ark of the covenant: and let seven other Priests take up the seven trumpets of the Jubilees, and march before the ark of our Lord.\n"
	"To the people also he said: Go and compass the city, the armed going before the ark of our Lord.\n"
	"And when Josue had ended his words, and the seven Priests sounded with seven trumpets before the ark of the covenant of our Lord,\n"
	"and all the armed host went before, the rest of the common people followed the ark, and all places sounded with the trumpets.\n"
	"But Josue had commanded the people, saying: You shall not cry, neither shall your voice be heard, nor any word go out of your mouth, until the day come wherein I shall say to you: Cry, and shout.\n"
	"Therefore the ark of our Lord went about the city once a day, & returning into the camp, abode there.\n"
	"Josue therefore rising in the night, the Priests took the ark of our Lord,\n"
	"and seven of them seven trumpets, which are used in the jubilee: and they went before the ark of our Lord walking and sounding: and the armed people went before them, and the rest of the common people followed the ark, and they sounded with trumpets.\n"
	"And they went round about the city the second day once, and returned into the camp. So did they six days.\n"
	"But the seventh day, rising up early they went about the city, as it was ordained, seven times.\n"
	"And when in the seventh going about^ the priests sounded with the trumpets, Josue said to all Israel: Make a shout, for our Lord hath delivered to you the city:\n"
	"and let this city be anathema: and all things that are in it, to our Lord. Only Rahab the harlot let her live, with all that be with her in the house: for she hid the messengers whom we sent.\n"
	"But you, beware you touch not ought of those things, that are commanded, and be guilty of prevarication, and all the camp of Israel be under sin, and be troubled.\n"
	"But whatsoever gold or silver there shall be, and of brazen vessels and iron, let it be consecrated to our Lord, laid up in his treasures.\n"
	"Therefore all the people making a shout, and the trumpets sounding, after that the voice and the sound thundered in the ears of the multitude, the walls forthwith fell: and every man went up by the place that was against him, and they took the city,\n"
	"and killed all things that were in it, from man to woman, from the infant to the old man. The oxen also and sheep, and the asses they struck in the edge of the sword.\n"
	"But to the two men that had been sent for spies, Josue said: Go into the house of the woman the harlot, and bring her forth, and all things that be hers, as you assured her by oath.\n"
	"And the young men going in, brought out Rahab, and her parents, her brethren also, and all her stuff and kindred, and made them to tarry without the camp.\n"
	"But the city, and all things that were found therein they burnt; except the gold and silver, and brazen vessels, and iron, which they consecrated unto the treasury of our Lord.\n"
	"But Rahab the harlot and the house of her father, and all that she had, Josue caused to live, and they dwelt in the midst of Israel until this present day: for that she hid the messengers, which he had sent to view Jericho. At that time Josue pronounced a curse, saying:\n"
	"Cursed be the man before our Lord, that shall raise up and build the city of Jericho. In his first born lay he the foundations thereof, and in the last of his children set he up the gates thereof.\n"
	"Our Lord therefore was with Josue, and his name was bruited in all the earth.";