const char* chap198 = "Which things when Jabin the king of Asor had heard, he sent to Jobab the king of Madon, and to the king of Semeron, and to the king of Achsaph:\n"
	"to the kings also of the North, that dwelt in the mountains and in the plain against the south side of Ceneroth, in the champion also and countries of Dor by the sea side:\n"
	"the Chananite also on the East and West, and the Amorrhite and Hetheite and Pherezite and Jebusite in the mountains: the Heveite also which dwelt at the foot of Hermon in the Land of Maspha.\n"
	"And they issued forth all with their troops, a people exceeding many as the sand that is in the shore of the sea, their horses also and chariots of passing great multitude.\n"
	"And all these kings assembled together in one at the Waters of Merom, to fight against Israel.\n"
	"And our Lord said to Josue: Fear them not: for tomorrow this self-same hour will I deliver all these to be wounded in the sight of Israel: their horses thou shalt houghsinew, and their chariots thou shalt burn with fire.\n"
	"And Josue came, & all the host with him against them to the Waters of Merom suddenly, & ran in upon them,\n"
	"and our Lord delivered them into the hands of Israel. Who struck them, and pursued them as far as great Sidon, and the Waters of Maserephoth, and the field of Masphe, which is on the East side thereof. Therefore he struck all, so that he left no relics of them:\n"
	"and he did as our Lord had commanded him, their horses he houghsinewed, and their chariots he burnt.\n"
	"And returning immediately he took Asor: and the king thereof he struck with the sword. For Asor in old time among all these Kingdoms held the principality.\n"
	"And he struck all the souls, that abode there: he left not in it any remains, but to utter destruction he wasted all things, and the city it-self he destroyed with fire.\n"
	"And all the cities round about, their kings also he took, struck & destroyed, as Moyses the servant of God had commanded him.\n"
	"Except the cities that were situated on hills and higher ground, the rest Israel burnt: one only^ Asor^ very well fenced he consumed with fire.\n"
	"And all the prey of these cities and the cattle^ the children of Israel divided among themselves, all the men being slain.\n"
	"As our Lord had commanded Moyses his servant, so did Moyses command Josue, and he accomplished all things: he omitted not of all the commandments, not so much as one word, which our Lord had commanded Moyses.\n"
	"Josue therefore took all the hilly country, & south, & the land of Gosen, and the plain, and the West quarter, and the mountain of Israel, and the champion country thereof:\n"
	"and the part of the mountain, that goeth up to Seir as far as Baalgad by the plain of Libanus under mount Hermon: all their kings he took, struck, & slew.\n"
	"A great time did Josue fight against these kings.\n"
	"There was not a city that did deliver it-self to the children of Israel, except the Heveite, which dwelt in Gabaon: for he took all by fight.\n"
	"For it was the sentence of our Lord, that their hearts should be indurate and they should fight against Israel, and fall, and should not deserve any clemency, and should perish, as our Lord had commanded Moyses.\n"
	"At that time Josue came and slew the Enacims of the mountains, of Hebron, and Dabir, and Anab, and from all the mountain of Juda and Israel, and destroyed their cities.\n"
	"He left not any of the stock of the Enacims, in the Land of the children of Israel: saving the cities of Gaza, and Geth, and Azotus, in the which only they were left.\n"
	"Josue therefore took all the Land, as our Lord spake to Moyses, and delivered it in possession to the children of Israel, according to their parts and tribes: and the Land rested from battles.";