const char* chap200 = "Josue was old, and striken in age, and our Lord said to him: Thou art old, and of a great age, and there is a very large country left, which is not yet divided by lot:\n"
	"to wit, all Galilee, Philisthiim, and all Gessuri.\n"
	"From the troubled river that watereth Aegypt, unto the borders of Accaron against the North: the Land of Chanaan, which is divided unto five lords of the Philisthiims, the Gazeites, the Azotians, the Ascalonites, the Getheites, and the Accaronites.\n"
	"But on the South side are the Heveites, all the Land of Chanaan, and Maara of the Sidonians as far as Apheca, and the borders of the Amorrhite,\n"
	"and his confines. The country also of Libanus against the East from Baalgad under mount Hermon, till thou enter into Emath.\n"
	"Of all that dwell in the mountain from Libanus, unto the Waters Maserephoth, and all the Sidonians. I am he that will destroy them from the face of the children of Israel. Let it come therefore into a portion of the inheritance of Israel, as I have commanded thee.\n"
	"And now divide the Land in possession to the nine tribes, and to the half tribe of Manasses,\n"
	"with the which Ruben & Gad have possessed the Land, which Moyses the servant of our Lord delivered to them beyond the streams of Jordan, on the east side.\n"
	"From Aroer, which is situate on the bank of the torrent Arnon, and in the midst of the valley, and all the champion of Medaba, as far as Dibon:\n"
	"and all the cities of Cehon, the king of the Amorrhite, which reigned in Hesebon, unto the borders of the children of Ammon.\n"
	"And Galaad, and the border of Gessuri and Machati, and all mount Hermon, and all Basan, as far as Salecha,\n"
	"all the Kingdom of Og in Basan, which reigned in Astaroth and Edrai, he was of the relics of the Raphaims: and Moyses struck, and destroyed them.\n"
	"And the children of Israel would not destroy Gessuri and Machati: and they have dwelt in the midst of Israel until this present day.\n"
	"But to the tribe of Levi he gave no possession: but the sacrifices and victims of our Lord the God of Israel, that is his inheritance, as he spake to him.\n"
	"Moyses therefore gave possession to the children of Ruben according to their kindreds.\n"
	"And their border was from Aroer, which is situate on the bank of the torrent Arnon, and in the midst of the valley of the same torrent: all the plain, that leadeth to Medaba,\n"
	"and Hesebon, and all their villages, which are in the champion. Dibon also, and Bamothbaal, and the town Baalmaon,\n"
	"and Jassa, and Cedimoth, and Mephaath,\n"
	"and Cariathaim, and Sabama, and Sarathasar in the mountain of the Valley.\n"
	"Bethphogor and Asedoth, Phasga and Bethiesimoth,\n"
	"and all the champion cities, and all the Kingdoms of Sehon the king of the Amorrhite, that reigned in Hesebon, whom Moyses struck with the Princes of Madian: the Heveite, and Recem, and Sur, and Hur, and Rebe^ Dukes of Sehon inhabitants of the Land.\n"
	"And Balaam the son of Beor the soothsayer, did the children of Israel kill by the sword, with the rest that were slain.\n"
	"And the river of Jordan was made the border of the children of Ruben. This is the possession of the Rubenites by their kindreds of cities and villages.\n"
	"And Moyses gave to the tribe of Gad & to his children possession by their kindreds, the division whereof is this:\n"
	"The border of Jaser, and all the cities of Galaad, and the half part of the Land of the children of Ammon: as far as Aroer, which is against Rabba:\n"
	"and from Hesebon unto Ramoth, Masphe and Betonim: and from Manaim unto the borders of Dabir.\n"
	"In the valley also Bethhara, and Bethnemra, and Socoth, and Saphon the other part of the Kingdom of Sehon the king of Hesebon: the end of this also is Jordan, unto the uttermost part of the sea Cenereth beyond Jordan on the east side.\n"
	"This is the possession of the children of Gad by their families, their cities, and villages.\n"
	"He gave also to the half tribe of Manasses and their children possession according to their kindreds,\n"
	"the beginning whereof is this: From Manaim all Basan, and all the Kingdoms of Og the king of Basan, and all the villages of Jair, which are in Basan, threescore towns.\n"
	"And the half part of Galaad, and Astaroth, and Edrai, cities of the Kingdom of Og in Basan: to the children of Machir, the son of Manasses, to the half part of the children of Machir according to their kindreds.\n"
	"This possession divided Moyses in the champion countries of Moab, beyond Jordan, against Jericho on the East side.\n"
	"But to the tribe of Levi he gave no possession: because our Lord the God of Israel himself is their possession, as he spake to them.";