const char* chap208 = "And the Princes of the families of Levi came to Eleazar the Priest, and Josue the son of Nun, and to the chief of the kindreds in every tribe of the children of Israel\n"
	"and they spake to them in Silo of the Land of Chanaan, and said: Our Lord commanded by the hand of Moyses, that cities should be given us to inhabit, and their suburbs to feed cattle.\n"
	"And the children of Israel gave of their possessions according to the commandment of our Lord, cities and their suburbs.\n"
	"And the lot came forth unto the family of Caath of the children of Aaron the Priest out of the tribe of Judas, and Simeon, and Benjamin, thirteen cities.\n"
	"And to the rest of the children of Caath, that is to the Levites, which remained, out of the tribes of Ephraim, and Dan, and the half tribe of Manasses, ten cities.\n"
	"Moreover to the children of Gerson came forth a lot, that they should take of the tribes of Issachar & Aser & Nephthali, & the half tribe of Manasses in Basan, cities in number thirteen.\n"
	"And to the sons of Merari by their kindreds, of the tribe of Ruben and Gad & Zabulon, twelve cities.\n"
	"and the children of Israel gave to the Levites cities and their suburbs, as our Lord commanded by the hand of Moyses, giving to every one by lot.\n"
	"Of the tribes of the children of Judas & Simeon^ Josue gave cities: whose names be these,\n"
	"to the children of Aaron by the families of Caath of the Levitical stock (for the first lot came forth to them)\n"
	"Cariatharbe the father of Enac, which is called Hebron, in the mountain of Judas, & the suburbs thereof round about.\n"
	"But the fields and the towns thereof he had given to Caleb the son of Jephone to possess.\n"
	"He gave therefore to the children of Aaron the Priest Hebron a city of refuge, & the suburbs thereof: and Lobna with the suburbs thereof:\n"
	"and Jether and Estemo,\n"
	"& Holon, & Dabir,\n"
	"and Ain, & Ieta, and Bethsames, with the suburbs thereof: nine cities of two tribes, as hath been said.\n"
	"And of the tribe of the children of Benjamin, Gabaon, & Gabae,\n"
	"and Anathoth and Almon, with their suburbs: four cities.\n"
	"All the cities together of the children of Aaron the Priest, thirteen, with their suburbs.\n"
	"But to the rest by the families of the children of Caath of the Levitical stock was given this possession.\n"
	"Of the tribe of Ephraim the cities of refuge, Sichem with the suburbs thereof in the mountain of Ephraim, and Gazer\n"
	"and Cibsaim, and Beth horon, with the suburbs thereof, four cities.\n"
	"Of the tribe of Dan also, Eltheco and Gabathon,\n"
	"& Aialon and Gethremmon, with the suburbs thereof, four cities.\n"
	"Moreover of the half tribe of Manasses, Thanac and Gethremmon, with their suburbs, two cities.\n"
	"All the cities ten, and their suburbs, were given to the children of Caath of the inferior degree.\n"
	"To the children of Gerson also of the Levitical stock he gave of the half tribe of Manasses the cities of refuge, Gaulon in Basan, and Bosram, with their suburbs, two cities.\n"
	"Moreover of the tribe of Issachar, Cesion, and Dabereth,\n"
	"and Iaramoth, & Engannim, with their suburbs, four cities.\n"
	"And of the tribe of Aser, Masal and Abdon,\n"
	"and Helcath, & Rohob, with their suburbs, four cities.\n"
	"Of the tribe also of Nephthali the cities of refuge, Cedes in Galilee: and Hammoth Dor, and Carthan, with their suburbs, three cities.\n"
	"All the cities of the families of Gerson, thirteen, with their suburbs.\n"
	"And to the children of Merari Levites of the inferior degree by their families was given of the tribe of Zabulon, Iecnam and Cartha\n"
	"and Damna and Naalol, four cities with their suburbs.\n"
	"Of the tribe of Ruben beyond Jordan against Jericho the cities of refuge, Bosor in the wilderness, Misor and Jaser and Iethson and Mephaath, four cities with their suburbs.\n"
	"Of the tribe of Gad the cities of refuge, Ramoth in Galaad, and Manaim & Hesebon & Jaser, four cities with their suburbs.\n"
	"All the cities of the children of Merari by their families and kindreds, twelve.\n"
	"Therefore all the cities of the Levites in the midst of the possession of the children of Israel were forty eight,\n"
	"with their suburbs, every one distributed by the families.\n"
	"And our Lord God gave to Israel all the Land, that he had sworn he would give to their fathers: and they possessed it, and dwelt in it.\n"
	"And peace was given by him on all nations round about: and none of their enemies durst resist them, but all were brought into their dominion.\n"
	"Not so much certes as one word, which he had promised, that he would perform unto them, was frustrate, but all things were accomplished in deeds.";