const char* chap213 = "And the Angel of our Lord went up from Galgal to the place of weepers, and said: I brought you out of Aegypt, and have brought you into the Land, for the which I sware to your fathers: and I promised that I would not make frustrate my covenant with you for ever:\n"
	"only so that you should not make a league with the inhabitants of this Land, but should overthrow their altars: and you would not hear my voice. Why have you done this?\n"
	"For the which cause I would not destroy them from before your face: that you may have enemies, and their gods may be a ruin unto you.\n"
	"And when the Angel of our Lord spake these words to all the children of Israel, they lifted up their voice, and wept.\n"
	"And the name of that place was called, the place of weepers, or of tears: and there they immolated hosts to our Lord.\n"
	"Josue therefore dismissed the people, and the children of Israel went every one into his possession, to obtain it:\n"
	"and they served our Lord all his days, and the days of the ancients, of them that lived a long time after him, and knew all the works of our Lord, which he had done with Israel.\n"
	"And Josue the son of Nun, the servant of our Lord, died, being an hundred and ten years old,\n"
	"and they buried him in the borders of his possession in Thamnathsare in the mount of Ephraim, on the North side of mount Gaas.\n"
	"And all that generation was gathered to their fathers: and there rose others, that knew not our Lord, and the works which he had done with Israel.\n"
	"And the children of Israel did evil in the sight of our Lord, and served Baalim.\n"
	"And they left our Lord the God of their fathers, that had brought them out of the Land of Aegypt: and followed strange gods, and the gods of the peoples, that dwelt round about them, and adored them: and they provoked our Lord to anger,\n"
	"leaving him, and serving Baal and Astaroth.\n"
	"And our Lord being wrath against Israel, delivered them into the hands of ransackers: who took them and sold them to the enemies, that dwelt round about: neither could they resist their adversaries:\n"
	"but whither soever they had meant to go, the hand of our Lord was upon them, as he spake, and sware to them: and they were vehemently afflicted.\n"
	"And our Lord raised up Judges, that should deliver them from the hands of the wasters: but neither would they hear them,\n"
	"fornicating with strange gods, and adoring them. They did quickly forsake the way, in the which their fathers had gone: and hearing the commandments of our Lord, they did all things contrary.\n"
	"And when our Lord raised up Judges, in their days he was moved with mercy, and heard the groanings of the afflicted, and delivered them from the slaughter of the wasters.\n"
	"But after the Judge was dead, they returned, and did much worse things than their fathers had done, following strange gods, serving them, and adoring them. They left not their inventions, and the very hard way, by which they were accustomed to walk.\n"
	"And the fury of our Lord was angry against Israel, & said: Because this nation hath made my covenant frustrate, which I had made with their fathers, and hath contemned my voice:\n"
	"I also will not destroy the nations which Josue did let alone, and died:\n"
	"that in them I may try Israel, whether they will keep the way of the Lord, and walk in it, as their fathers kept it, or not.\n"
	"Our Lord therefore left all these nations, and would not quickly overthrow them, neither delivered them into the hands of Josue.";