const char* chap214 = "These are the Nations, which our Lord left, that in them he might instruct Israel, and all that had not known the wars of the Chananites:\n"
	"that afterward their children might learn to fight with their enemies, and to be accustomed to war:\n"
	"the five Princes of the Philisthiims, and the Chananite, and Sidonian, and Heveite, that dwelt in mount Libanus, from mount Baal Hermon to the entering into Emath.\n"
	"And he left them, that in them he might try Israel, whether they would hear the commandments of our Lord, which he had commanded their fathers by the hand of Moyses, or not.\n"
	"Therefore the children of Israel dwelt in the midst of the Chananite, and Hetheite, and Amorrhite, and Pherezite, and Heveite, and Jebusite:\n"
	"and they took their daughters to wives, and themselves gave their own daughters to their sons, and served their gods.\n"
	"And they did evil in the sight of our Lord, and forgot their God, serving Baalim and Astaroth.\n"
	"And our Lord being wrath against Israel, delivered them into the hands of Chusan Rasathaim the king of Mesopotamia, and they served him eight years.\n"
	"And they cried to our Lord: who raised them up a saviour, & delivered them, to wit, Othoniel the son of Cenez, the younger brother of Caleb:\n"
	"and the Spirit of our Lord was in him, and he judged Israel. And he went forth to fight, and our Lord delivered into his hands Chusan Rasathaim the king of Syria, and oppressed him.\n"
	"And the land rested forty years, and Othoniel the son of Cenez died.\n"
	"And the children of Israel added to do evil in the sight of our Lord: who strengthened against them Eglon the king of Moab: because they did evil in his sight.\n"
	"And he joined to him the children of Ammon, and Amalec: and he went and struck Israel, and possessed the city of palms.\n"
	"And the children of Israel served Eglon the king of Moab eighteen years:\n"
	"and afterward they cried to our Lord: who raised up unto them a saviour called Aod, the son of Gera, the son of Jemini, who used both hands for the right. And the children of Israel sent by him presents to Eglon the king of Moab.\n"
	"Who made himself a two edged sword, having in the midst a haft in length the palm of a hand, and was girded therewith under his cassock on the right thigh.\n"
	"And he presented the gifts to Eglon the king of Moab. And Eglon was exceeding gross.\n"
	"And when he had presented the gifts unto him, he brought his fellows on the way that came with him.\n"
	"And returning from Galgal, where the idols were, he said to the king: I have a secret message to thee, o king. And he commanded silence: & all being gone forth that were about him,\n"
	"Aod went in to him: and he sat in a summer chamber alone, and he said: A word from God I have to thee. Who forthwith rose out of his throne.\n"
	"And Aod put forth his left hand, & took the dagger from his right thigh, and fastened it into his belly\n"
	"so mightily that the haft followed the blade in the wound, and was closed up fast with the most fat grease. Neither did he pluck out the dagger, but as he had strucken^ so left it in the body: and forthwith by the secret parts of nature the ordure of the belly came forth.\n"
	"But Aod shutting the doors of the chamber very diligently, & locking them sure,\n"
	"went out by a postern door. And the king's servants going in, saw the doors of the chamber shut, and they said: Peradventure he purgeth his belly in the summer chamber.\n"
	"And expecting long till they were ashamed, & seeing that no man did open, they took a key: and opening they found their Lord on the earth lying dead.\n"
	"But Aod, whiles they were troubled, escaped, and passed by the Place of idols, whence he had returned. And he came into Seirath:\n"
	"and forthwith the trumpet sounded in the mount of Ephraim: and the children of Israel went down with him, himself going in the front.\n"
	"Who said to them: Follow me: for our Lord hath delivered our enemies the Moabites into our hands. And they went down after him, and occupied the fords of Jordan, which bring over into Moab: & they suffered no man to pass:\n"
	"but they struck the Moabites at that time, about ten thousand, all stout and strong men, none of them could escape.\n"
	"And Moab was humbled that day under the hand of Israel: and the Land rested eighty years.\n"
	"After him was Samgar the son of Anath, who struck of the Philisthimes six hundred men with the coulter of a plough: and he also defended Israel.";