const char* chap220 = "And Abimelech the son of Jerobaal went into Sichem to his mother's brethren and spake to them, & to all the kindred of the house of his mother's father, saying:\n"
	"Speak to all the men of Sichem: whether is better for you, that seventy men have dominion over you, all the sons of Jerobaal, or that one man have dominion over you? & withal consider that I am your bone, and your flesh.\n"
	"And his mother's brethren spake to him to all the men of Sichem all these words, & inclined their hearts after Abimelech, saying: He is our brother.\n"
	"And they gave him seventy weight of silver out of the temple of Baalberit. Who hired therewith unto himself needy men and vagabonds, and they followed him.\n"
	"And he came into his father's house in Ephra, and murdered his brethren the sons of Jerobaal, seventy men, upon one stone: & there remained Joatham the youngest son of Jerobaal, & was hid.\n"
	"And all the men of Sichem assembled together all the families of the city of Mello: & they went and made Abimelech king, beside the oak that stood in Sichem.\n"
	"Which being told to Joatham, he went, & stood in the top of mount Garizim: & lifting up his voice, he cried, & said: Hear me ye men of Sichem, so as God may hear you.\n"
	"The trees went to anoint a king over them: & they said to the olive tree: Reign over us.\n"
	"Which answered: Can I forsake my fatness, which both gods do use, and men, and come to be promoted among the trees?\n"
	"And the trees said to the fig tree: Come, and take the Kingdom over us.\n"
	"Which answered them: Can I forsake my sweetness, and my most sweet fruits, & go to be promoted among the other trees?\n"
	"And the trees spake to the vine: Come, and reign over us.\n"
	"Which answered them: Can I forsake my wine, that cheereth God and men, & be promoted among the other trees?\n"
	"And the trees said to the rhamnus: Come, and reign over us.\n"
	"Who answered them: If indeed you make me your king, Come, and rest under my shadow: but if you mean it not, let there fire issue forth of the rhamnus, & devour the cedars of Libanus.\n"
	"Now therefore, if you have well, and without sin appointed Abimelech king over you, and have dealt well with Jerobaal, and with his house, & have requited him the like for his benefits, who fought for you,\n"
	"& put his life in dangers, that he might deliver you from the hand of Madian,\n"
	"who now are risen against my father's house, and have killed his sons seventy men upon one stone, & have made Abimelec the son of his handmaid king over the inhabitants of Sichem, because he is your brother:\n"
	"If therefore you have dealt well, and without fault with Jerobaal, and his house, rejoice this day in Abimelech, & rejoice he in you.\n"
	"But if unjustly, let there fire issue forth from him, and consume the inhabitants of Sichem, and town of Mello: and let there fire go forth from the men of Sichem, and from the town of Mello, & devour Abimelech.\n"
	"Which things when he had said, he fled, and went into Bera: and dwelt there for fear of Abimelech his brother.\n"
	"Abimelech therefore reigned over Israel three years.\n"
	"And our Lord sent a very evil spirit between Abimelech and the inhabitants of Sichem: Who began to detest him,\n"
	"& to lay the wickedness of the murdering of the seventy sons of Jerobaal, & the shedding of their blood upon Abimelech their brother, and upon the rest of the Princes of the Sichemites, that had holpen him.\n"
	"And they set an ambushment against him on the top of the mountains: & whiles they tarried for his coming, they committed robberies, taking preys of them that passed by: and it was told Abimelech.\n"
	"And Gaal the son of Obed came with his brethren, & passed into Sichem. At whose coming the inhabitants of Sichem taking courage,\n"
	"issued forth into the fields, wasting the vineyards, & treading the grapes: and gathering companies of musicians went into the temple of their god, and in their banquets and cups cursed Abimelech,\n"
	"Gaal the son of Obed crying: Who is Abimelech; and what is Sichem, that we should serve him? Is he not the son of Jerobaal, and hath made Zebul his servant prince over the men of Emor the father of Sichem? Why then shall we serve him?\n"
	"would God that some man would give this people under my hand, that I might take Abimelech out of the way. And some said to Abimelech: Gather together a multitude of an army, and come.\n"
	"For Zebul the Prince of the city, hearing the words of Gaal the son of Obed, was very wrath,\n"
	"& sent messengers secretly to Abimelech, saying: Behold, Gaal the son of Obed is come into Sichem with his brethren, & raiseth the city against thee.\n"
	"Arise therefore in the night with the people, that is with thee, and lie hid in the field:\n"
	"and betimes in the morning at sun rising, set upon the city. And when he issueth forth against thee with his people, do to him what thou shalt be able.\n"
	"Abimelech therefore arose with all his army in the night, and laid ambushments near to Sichem in four places.\n"
	"And Gaal the son of Obed went forth, & stood in the entrance of the gate of the city. And Abimelech rose, & all his army with him from the place of the ambushments.\n"
	"And when Gaal had seen the people, he said to Zebul: Behold a multitude cometh down from the mountains. To whom he answered: Thou seest the shadows of the mountains as it were heads of men, & with this error thou art deceived.\n"
	"Again Gaal said: Behold there cometh down people from the navel of the land, & one troop cometh by the way that looketh to the oak.\n"
	"To whom Zebul said: Where is now thy mouth, wherewith thou didst speak? Who is Abimelech that we should serve him? Is not this the people, which thou didst despise? Go forth, and fight against him.\n"
	"Gaal therefore went, the people of the Sichimites looking on, and fought against Abimelech,\n"
	"who pursued him flying, and drive him into the city: and there were slain of his part many, unto the gate of the city.\n"
	"And Abimelech sat in Ruma: but Zebul expelled Gaal and his companions out of the city, neither did he suffer them to abide in it.\n"
	"Therefore the day following the people went forth into the field. Which being told to Abimelech,\n"
	"he took his army, and divided it into three troops, setting ambushments in the fields. And seeing that the people came out of the city, he arose, and set upon them\n"
	"with his own troop, oppugning and besieging the city: and two troops scattered through the field pursue the adversaries.\n"
	"Moreover Abimelech all the day oppugned the city: which he took, & killed the inhabitants thereof, and destroyed it, so that he sowed salt in it.\n"
	"Which when they heard that dwelt in the tower of Sichem, they entered into the temple of their god Berith, where they had made a covenant with him, & thereof the place had taken his name, which was exceeding well fenced.\n"
	"Abimelech also hearing that the men of the tower of Sichem were gathered together,\n"
	"he went up into mount Selmon with all his people: and taking an axe, he cut off the bough of a tree, and laying it on his shoulder & carrying it, he said to his companions: That which you see me do, do ye out of hand.\n"
	"They therefore cutting off boughs from the trees, every man as fast as he could, followed their captain. Who compassing the fort burnt it: and so it came to pass, that with the smoke and the fire a thousand persons were slain, men and women together, of the inhabitants of the tower of Sichem.\n"
	"And Abimelech departing thence came to the town of Thebes, which compassing he besieged with his army.\n"
	"And there was in the midst of the city an high tower, to the which were fled both men and women together, and all the Princes of the city, the gate being shut very strongly, and they standing upon the battlements of the tower by the bulwarks.\n"
	"And Abimelech coming near the tower, fought manfully: & approaching to the door, endeavoured to put fire under it:\n"
	"and behold one woman casting from above a piece of a millstone, dashed it against the head of Abimelech, and brake his brain.\n"
	"Who called by and by his esquire, and said to him: Draw out thy sword, and strike me: lest perhaps it be said that I was slain of a woman. Who doing as he was commanded slew him.\n"
	"And when he was dead, all that were with him of Israel returned into their seats:\n"
	"and God repayed the evil, that Abimelech had done against his father, killing his seventy brethren.\n"
	"The Sichemites were also rewarded for that which they had wrought, and the curse of Joatham the son of Jerobaal came upon them.";