const char* chap221 = "After Abimelech there arose Ruler in Israel Thola the son of Phua the uncle of Abimelech, a man of Issachar, which dwelt in Samir of mount Ephraim:\n"
	"and judged Israel three and twenty years, and died and was buried in Samir.\n"
	"After him succeeded Jair the Galaadite, who judged Israel for two and twenty years,\n"
	"having thirty sons sitting upon thirty ass colts, & Princes of thirty cities, which of his name were called Havoth Jair, that is, the towns of Jair, until this present day, in the Land of Galaad.\n"
	"And Jair died, and was buried in the place, which is called Camon.\n"
	"But the children of Israel joining new sins to their old, did evil in the sight of our Lord, & served the idols, Baalim and Astaroth, & the gods of Syria and of Sidon and of Moab and the children of Ammon and of the Philisthiims: and they left our Lord, and did not serve him.\n"
	"Against whom our Lord being wrath, delivered them into the hands of the Philisthiims and of the children of Ammon.\n"
	"And they were afflicted and sore oppressed for eighteen years, all that dwelt beyond Jordan in the Land of the Amorrhite, which is in Galaad:\n"
	"in so much, that the children of Ammon passing over Jordan wasted Judas and Benjamin and Ephraim: and Israel was afflicted exceedingly.\n"
	"And crying to our Lord, they said: We have sinned to thee, because we have forsaken our Lord God & have served Baalim.\n"
	"To whom our Lord spake: Have not the Aegyptians and the Amorrheites, and the children of Ammon and the Philisthiims,\n"
	"the Sidonians also and Amalech and Chanaan oppressed you, & you cried to me, and I delivered you out of their hands?\n"
	"And yet you have forsaken me, and have worshipped strange gods: therefore I will not add to deliver you any more:\n"
	"go and invocate the gods which you have chosen: let them deliver you in the time of distress.\n"
	"And the children of Israel said to our Lord: We have sinned, render to us whatsoever pleaseth thee: only now deliver us.\n"
	"In saying which things, they threw away out of their coasts all the idols of strange gods, and served our Lord God: who sorrowed for their miseries.\n"
	"Therefore the children of Ammon crying together pitcht their tents in Galaad: against whom the children of Israel being assembled camped in Maspha.\n"
	"And the Princes of Galaad said every one to their neighbours: Who of us shall first begin to fight against the children of Ammon, shall be the Duke of the people of Galaad.";