const char* chap230 = "There was a certain man a Levite, dwelling on the side of mount Ephraim, who took a wife of Bethlehem Juda:\n"
	"which left him, and returned unto her father's house into Bethlehem, & abode with him four months.\n"
	"And her husband followed her, willing to be reconciled unto her, & to speak her fair, & to bring her back with him, having in his company a servant and two asses: who received him, & brought him into her father's house. Which when his father in law had heard, and had seen him, he met him joyful.\n"
	"and embraced the man. And the son in law tarried in the house of his father in law three days, eating with him and drinking familiarly.\n"
	"But the fourth day arising before day, he would depart. Whom his father in law held, and said to him: Taste first a little bread, & strengthen thy stomach, and so thou shalt depart.\n"
	"And they sat together, & did eat & drink. And the father of the young woman said to his son in law: I beseech thee that thou tarry here today, and let us make merry together.\n"
	"But he rising up, began as if he would depart. And nevertheless with much ado his father in law stayed him, and made him to tarry with him.\n"
	"But when morning was come, the Levite prepared to go his journey. To whom his father in law again: I beseech thee, quoth he, that thou take a little meat, and making thyself strong, till the day be farther spent, afterward thou mayest depart. They did eat therefore together.\n"
	"And the young man arose, that he might set forward with his wife and his servant. To whom his father in law spake again: Consider that the day is more declining to the west, and draweth nigh to evening: tarry with me today also, and spend the day in mirth, and tomorrow thou shalt depart that thou mayest go into thy house.\n"
	"His son in law would not condescend to his words: but forthwith went forward, and came over against Jebus, which by another name is called Jerusalem, leading with him two asses laden, and his concubine.\n"
	"And now they were come nigh to Jebus & the day changed into night: & the servant said to his master: Come, I beseech thee, let us turn into the city of the Jebusites, and tarry in it.\n"
	"To whom his master answered: I will not enter into the town of a strange nation, which is not of the children of Israel but I will pass as far as Gabaa:\n"
	"and when I shall come thither, we will lodge in it, or at the least in the city of Rama.\n"
	"They passed therefore by Jebus, and went on their journey begun, and the sun went down to them beside Gabaa, which is in the tribe of Benjamin:\n"
	"and they turned into it, that they might lodge there. Whither when they were entered, they sat in the street of the city, and no man would receive them to lodge.\n"
	"And behold there appeared an old man, returning out of the field and from his work in the evening, who himself also was of mount Ephraim, and dwelt as a stranger in Gabaa; but the men of that country were the children of Jemini.\n"
	"And lifting up his eyes, the old man saw the man sitting with his fardels in that street of the city, and said to him: Whence comest thou? And whither goest thou?\n"
	"Who answered him: We departed from Bethlehem Juda, and we go to our place, which is on the side of mount Ephraim, from whence we went into Bethlehem: and now we go to the house of God, and none will receive us under his roof,\n"
	"having straw and hay for provender of the asses, and bread and wine for the use of myself and of thy handmaid, and of the servant that is with me: we lack nothing but lodging.\n"
	"To whom the old man answered: Peace be with thee, I will give all things that are necessary: only, I beseech thee, tarry not in the street.\n"
	"And he brought him into his house, and gave provender to his asses: and after they had washed their feet, he received them to a banquet.\n"
	"They making merry, and after the labour of their journey refreshing their body with meat & drink, there came men of that city, the children of Belial (that is to say, without yoke) and besetting the old man's house, began to knock at the doors, crying to the master of the house, & saying: Bring forth the man, that entered into thy house, that we may abuse him.\n"
	"And the old man went out to them, and said: Do not so brethren, do not this evil: because this man is entered to my lodging, and cease from this folly:\n"
	"I have a daughter that is a virgin, & this man hath a concubine, I will brink them forth to you, that you may humble them, and fulfill your lust: only, I beseech you, work not this wickedness against nature on the man.\n"
	"They would not agree to his words. Which the man seeing, he brought forth his concubine to them, and he delivered her to them to be illuded: whom when they had abused all the night, they let her go in the morning.\n"
	"But the woman, when the darkness departed, came to the door of the house, where her lord lodged, & there fell down.\n"
	"Morning being come, the man arose, & opened the door, that he might finish his journey begun: & behold his concubine lay before the door, her hands spread on the threshold.\n"
	"To whom he, thinking that she took her rest, spake: Arise, and let us walk, Who answering nothing, perceiving that she was dead, he took her, & laid her upon his ass, & returned into his house.\n"
	"Which when he was entered unto, he took a sword, and cutting the carcass of his wife with her bones into twelve parts and pieces, he sent them into all the borders of Israel.\n"
	"Which when every one had seen, they cried together: There was never such a thing done in Israel from that day, when our fathers ascended out of Aegypt, until this present time: give sentence, and decree in common what is needful to be done.";