const char* chap235 = "But after that she was returned to her mother in law, she heard of her: My daughter, I will seek thee rest, and will provide that it may be well with thee.\n"
	"This Booz, to whose maids thou art joined in the field, is our night kinsman, and this night he winnoweth the barn floor of the barley.\n"
	"Wash therefore and anoint thyself, and put on thy better garments, and go down into the barn floor, let no man see thee, till he shall have ended eating & drinking.\n"
	"And when he shall go to sleep, mark the place wherein he sleepeth: and thou shalt come, and discover the mantle wherewith he is covered toward his feet, and shall cast thyself down and lie there: and he will tell thee what thou must do.\n"
	"Who answered: Whatsoever thou shalt command, that will I do.\n"
	"And she went down into the barn floor, and did all the things which her mother in law had commanded her.\n"
	"And when Booz had eaten, and drunken, and was made pleasant, and was gone to sleep by the heap of sheaves, she came closely, and discovering the mantle at his feet, laid herself down.\n"
	"And behold, when it was now midnight the man was afraid, and troubled: and he saw a woman lying at his feet,\n"
	"and said to her: Who art thou? And she answered: I am Ruth thy handmaid: spread thy mantle upon thy servant, because thou art nigh of kin.\n"
	"And he said: Blessed art thou of our Lord my daughter, and the former mercy thou hast passed with the latter: because thou hast not followed young men either poor or rich.\n"
	"Fear not therefore, but whatsoever thou shalt say to me, I will do to thee. For all the people that dwelleth within the gates of my city know, that thou art a woman of virtue.\n"
	"Neither do I deny myself nigh of kin, but there is another nearer than I.\n"
	"Rest this night: and when morning is come, if he will retain thee by the right of nigh of kindred, the thing is well done, but if he will not, I will take thee without all doubt, our Lord liveth, sleep until morning.\n"
	"She slept therefore at his feet till the night was gone. Therefore she arose before men could know one another, and Booz said: Beware lest any man know that thou camest hither.\n"
	"And again, Spread, quoth he, thy mantle, wherewith thou art covered, and hold it with both hands. Who spreading and holding it, he measured six measures of barley, and put it upon her. Who carrying it entered into the city,\n"
	"and came to her mother in law. Who said to her: What hast thou done daughter? And she told her all things, that the man had done to her.\n"
	"And she said: Behold six measures of barley hath he given me, and he said: I will not have thee return empty to thy mother in law.\n"
	"And Noemi said: Expect daughter till we see what end the thing will have. For the man will not cease until he have accomplished that which he hath spoken.";