const char* chap247 = "And it came to pass as it were a month after, Naas the Ammonite ascended, and began to fight against Jabes of Galaad. And all the men of Jabes said to Naas: Make a league with us, and we will serve thee.\n"
	"And Naas the Ammonite answered them: In this will I make a league with you, that I may pluck out the right eyes of you all, and may make you a reproach in all Israel.\n"
	"And the ancients of Jabes said to him: Grant unto us seven days, that we may send messengers unto all the coasts of Israel: & if there shall not be that may defend us, we will come forth to thee.\n"
	"The messengers therefore came into Gabaa of Saul: and they spake these words, in the hearing of the people: and all the people lifted up their voice, and wept.\n"
	"And behold Saul came, following oxen out of the field, and said: What aileth the people that they weep? And they told him the words of the men of Jabes.\n"
	"And the Spirit of our Lord seized on Saul, when he had heard these words, and his fury was exceeding wrath.\n"
	"And taking both the oxen, he cut them into pieces, & sent them into all the coasts of Israel by messengers, saying: Whosoever shall not go forth, and follow Saul and Samuel, so shall it be done to his oxen. Therefore the fear of our Lord invaded the people, and they went forth as it were one man.\n"
	"And he numbered them in Bezec: and there were of the children of Israel three hundred thousand: and of the men of Juda thirty thousand.\n"
	"And they said to the messengers that came: Thus shall you say to the men, that are in Jabes Galaad: Tomorrow, when the sun shall wax hot, you shall have relief. The messengers therefore came, & told the men of Jabes: Who were glad.\n"
	"And they said: In the morning we will come forth to you: & you shall do to us whatsoever shall please you.\n"
	"And it came to pass, when the morrow was come, Saul set the people into three parts: & entered into the midst of the camp in the morning watch, and struck Ammon until the day waxed hot, & the rest were dispersed, so that there were not left among them two together.\n"
	"And the people said to Samuel: Who is this that said: what, shall Saul reign over us? Give us the men and we will kill them.\n"
	"And Saul said: No man shall be killed this day, because our Lord this day hath relieved Israel:\n"
	"And Samuel said to the people: Come and let us go into Galgal, and let us renew there a Kingdom.\n"
	"And all the people went into Galgal, and there they made Saul king before our Lord in Galgal, and they immolated there pacific victims before our Lord. And Saul rejoiced there, and all the men of Israel exceedingly.";