const char* chap248 = "And Samuel said to all Israel: Behold I have heard your voice according to all things which you have spoken to me, and I have appointed a king over you.\n"
	"And now the king goeth before you: and I am waxen old and have gray hairs: moreover my sons are with you: therefore having conversed with you from my youth until this day, lo I am ready.\n"
	"Speak of me before our Lord, and before his Christ, whether I have taken any man's oxe, or ass: If I have calumniated any man, if I have oppressed any man, if I have taken gift of any man's hand: and I will contemn that same this day, and will restore it to you.\n"
	"And they said thou hast not calumniated us, nor oppressed us, nor taken ought of any man's hand.\n"
	"And he said to them: Witness is our Lord against you, and witness is his Christ in this day, that you have not found any thing in my hand. And they said: Witness.\n"
	"And Samuel said to the people: Our Lord who made Moyses & Aaron, & brought our fathers out of the Land of Aegypt is present.\n"
	"Now therefore stand, that I may contend in judgment against you before our Lord, concerning all the mercies of our Lord, which he hath done with you, and with your fathers:\n"
	"how Jacob entered into Aegypt, and your fathers cried to our Lord: and our Lord sent Moyses and Aaron, and brought your fathers out of Aegypt: and placed them in this place.\n"
	"Who forgat our Lord their God, and he delivered them in the hand of Sisara master of the host of Hasor, and in the hand of the Philisthiims, and in the hand of the king of Moab, and they fought against them.\n"
	"But afterward they cried to our Lord, & said: We have sinned, because we have forsaken our Lord, & have served Baalim & Astaroth: now therefore deliver us from the hand of our enemies, & we will serve thee.\n"
	"And our Lord sent Jerobaal, & Badan, & Jephte, & Samuel, and delivered you from the hand of your enemies round about, & you dwelt securely.\n"
	"But you seeing that Naas, king of the children of Ammon was come against you, you said to me: Not so, but a king shall reign over us: whereas our Lord your God did reign among you.\n"
	"Now therefore your king is ready, whom you have chosen and desired: behold our Lord hath given you a king.\n"
	"If you shall fear our Lord, and serve him, & hear his voice, and not exasperate the mouth of our Lord: both you, & the king which reigneth over you, shall be followers of our Lord your God:\n"
	"But if you will not hear the voice of our Lord, but shall exasperate his words, the hand of our Lord shall be upon you, & upon your fathers.\n"
	"But now also stand, & see this great thing which our Lord will do in your sight.\n"
	"Is it not wheat harvest today? I will call upon our Lord, & he will give noises & rain: and you shall know, & see that you have done great evil to yourselves in the sight of our Lord, desiring a king over you.\n"
	"And Samuel cried to our Lord, & our Lord gave noises & rain in that day.\n"
	"And all the people feared exceedingly our Lord and Samuel. And all the people said to Samuel: Pray for thy servants to our Lord thy God, that we die not. For we have added evil to all our sins, that we desired unto us a king.\n"
	"And Samuel said to the people: Fear not, you have done all this evil: but yet depart not from the back of our Lord, but serve our Lord in all your heart.\n"
	"And decline not after vain things, which shall not profit you, nor deliver you, because they are vain.\n"
	"And our Lord will not forsake his people for his great name: because our Lord hath sworn to make you a people to himself.\n"
	"And far from me be this sin in our Lord, that I should cease to pray for you, and I will teach you the good and right way.\n"
	"Therefore fear our Lord, and serve him in truth and from your whole heart. For you have seen the great works which he hath done among you.\n"
	"But if you shall persevere in malice, both you and your king shall perish together.";