const char* chap251 = "And Samuel said to Saul: Our Lord sent me to anoint thee king over his people Israel; now therefore hear the voice of our Lord:\n"
	"Thus saith the Lord of hosts: I have recounted whatsoever Amalec hath done to Israel: how he resisted them in the way when they came up out of Aegypt.\n"
	"Now therefore go, and strike Amalec, and destroy all that he hath: spare him not, and covet not ought of his things: but kill from man unto woman, both child & suckling, oxe and sheep, camel and ass.\n"
	"Saul therefore commanded the people, and numbered them as it were lambs: two hundred thousand footmen, & ten thousand of the men of Juda.\n"
	"And when Saul was come unto the city of Amalec, he laid ambushments in the torrent.\n"
	"And Saul said to the Cineite: Go ye, retire & depart from Amalec: lest perhaps I wrap thee in with him, for thou hast done mercy with all the children of Israel, when they descended out of Aegypt. And the Cineite departed out of the midst of Amalec.\n"
	"And Saul struck Amalec from Hevila, until thou come to Sur, which is over-against Aegypt.\n"
	"And he apprehended Agag the king of Amalec alive: but all the common people he slew in the edge of the sword.\n"
	"And Saul and the people spared Agag, & the best flocks of sheep & herds, & the garments & rams, & all things, that were fair, neither would they destroy them: but whatsoever was vile and refuse, that they destroyed.\n"
	"And the word of our Lord was made to Samuel, saying:\n"
	"It repenteth me that I have made Saul king: because he hath forsaken me, & hath not fulfilled my words in work. And Samuel was strucken sad, and cried to our Lord all the night.\n"
	"And when Samuel had risen in the night, to go to Saul in the morning, it was told Samuel, that Saul was come into Carmelus, and had erected to himself a triumphant arch, and returning was passed, & gone into Galgal. Samuel therefore came to Saul, and Saul offered an holocaust to our Lord of the first of the preys, which he had brought from Amalec.\n"
	"And when Samuel was come to Saul, Saul said to him: Blessed be thou to our Lord, I have fulfilled the word of our Lord.\n"
	"And Samuel said: And what is this voice of flocks, which soundeth in mine ears, and of herds, which I hear?\n"
	"And Saul said: They have brought them from Amalec: for the people hath spared the better sheep and herds that they might be immolated to our Lord thy God, but the rest we have slain.\n"
	"And Samuel said to Saul: Suffer me, and I will shew thee what our Lord hath spoken to me this night. And he said to him: Speak.\n"
	"And Samuel said: When thou wast a little one in thine own eyes, was thou not made chief in the tribes of Israel? And our Lord anointed thee to be king over Israel,\n"
	"and our Lord sent thee on the way, and said: Go, and kill the sinners of Amalec, and thou shalt fight against them until the utter destruction of them.\n"
	"Why therefore hast thou not heard the voice of our Lord: but art turned to the prey, & hast done evil in the eyes of our Lord?\n"
	"And Saul said to Samuel: Yea I have heard the voice of our Lord, & have walked in the way by which our Lord sent me, & have brought Agag the king of Amalec, & Amalec I have slain.\n"
	"But the people took of the prey^ sheep and oxen, the principal of those things which were slain, to immolate to our Lord their God in Galgal.\n"
	"And Samuel said: why? Will our Lord have holocausts and victims, and not rather that the voice of our Lord be obeyed? For BETTER IS OBEDIENCE THAN VICTIMS: and to harken rather than to offer the fat of rams.\n"
	"Because it is as it were the sin of enchantment, to resist, & as it were the wickedness of idolatry, to refuse to obey. For as much therefore as thou hast rejected the word of our Lord, our Lord hath rejected thee, that thou shalt not be king.\n"
	"And Saul said to Samuel: I have sinned, because I have transgressed the saying of our Lord, and thy words, fearing the people, and obeying their voice.\n"
	"But now bear I beseech thee my sin, and return with me, that I may adore our Lord.\n"
	"And Samuel said to Saul: I will not return with thee, because thou hast rejected the word of our Lord, and our Lord hath rejected thee that thou shalt not be king over Israel.\n"
	"And Samuel turned himself to depart: but he caught the hem of his cloak, which also did rend.\n"
	"And Samuel said to him: Our Lord hath rent the Kingdom of Israel from thee this day, and hath delivered it to thy neighbour better than thou.\n"
	"Moreover the Triumpher in Israel will not spare, and he will not be turned with repentance: for neither is he a man that he may repent.\n"
	"But he said: I have sinned: howbeit now honour me before the ancients of my people, and before Israel, & return with me, that I may adore our Lord thy God.\n"
	"Samuel therefore returning followed Saul: & Saul adored our Lord.\n"
	"And Samuel said: Bring unto me Agag the king of Amalec. And Agag was presented to him very fat, trembling. And Agag said: Doth bitter death thus separate?\n"
	"And Samuel said: As thy sword hath made women without children, so shall thy mother among women be without children. And Samuel hewed him into pieces before our Lord in Galgal.\n"
	"And Samuel departed into Ramatha: but Saul ascended unto his house into Gabaa.\n"
	"And Samuel saw Saul no more unto the day of his death: but yet Samuel lamented Saul because it repented our Lord that he had appointed him king over Israel.";