const char* chap254 = "And it came to pass, when he had finished to speak unto Saul, the soul of Jonathas was joined fast to the soul of David, and Jonathas loved him as his soul.\n"
	"And Saul took him in that day, and did not grant unto him to return into his father's house.\n"
	"And David and Jonathas entered a league, for he loved him as his soul.\n"
	"For Jonathas stripped himself of the coat wherewith he was clothed, and gave it to David, and the rest of his garments, unto his sword, and bow, and unto his belt.\n"
	"David also went forth to all things wheretosoever Saul sent him, & he behaved himself wisely: and Saul placed him over the men of war, & he was accepted in the eyes of all the people, & specially in the eyes of Saul's servants.\n"
	"Moreover when David returned, after he struck the Philistian, the women came forth from all the tribes of Israel, singing & dancing to Saul the king, in timbrels of joy, & in cornets.\n"
	"and the women sang, playing and saying: Saul struck a thousand, and David ten thousand.\n"
	"And Saul was exceeding angry, & this word was displeasant in his eyes, and he said: They have given David ten thousand, & to me they have given a thousand: what remaineth for him but only the Kingdom?\n"
	"Therefore Saul did not look upon David with right eyes from that day and afterward.\n"
	"And a day after, the evil spirit of God invaded Saul, and he prophesied in the midst of his house. And David played with his hand as every day. And Saul held a spear,\n"
	"and threw it, thinking that he could nail David to the wall, and David declined from his face the second time.\n"
	"And Saul feared David because our Lord was with him, and was departed from himself.\n"
	"Saul therefore removed him from him, and made him a tribune over a thousand men, and he went out and came in before all the people.\n"
	"Also in all his ways David dealt wisely, and our Lord was with him.\n"
	"Saul therefore saw that he was exceeding wise, and he began to beware of him.\n"
	"But all Israel and Juda loved David, for he came in and went out before them.\n"
	"And Saul said to David: Behold my elder daughter Merob, her will I give thee to wife, only be thou a valiant man, and fight the battles of our Lord. And Saul thought saying: Be not my hand upon him, but let the hands of the Philistians be upon him.\n"
	"And David said to Saul: What am I, or what is my life, or the kindred of my father in Israel, that I should be made the son in law of the king?\n"
	"And it came to pass, at what time Merob the daughter of Saul should have been given to David, she was given to Hadriel the Molathite to wife.\n"
	"But David loved Michol the other daughter of Saul. And it was told Saul, and it pleased him.\n"
	"And Saul said: I will give her to him, that she may be a scandal unto him, & that the hand of the Philistians may be upon him. And Saul said to David: In two things thou shalt be my son in law this day.\n"
	"And Saul commanded his servants: Speak to David secretly out of my presence, saying: Behold thou pleasest the king, and all his servants love thee. Now therefore be thou the king's son in law.\n"
	"And the servants of Saul spake all these words in the ears of David. And David said: Doth it seem unto you a small matter to be the son in law of a king? But I am a poor man, and of small ability.\n"
	"And the servants of Saul reported, saying: These manner of words hath David spoken.\n"
	"And Saul said: Speak thus to David: The king needeth no dowry, but only an hundred prepuces of the Philistians, that revenge may be made of the king's enemies. Moreover Saul thought to deliver David into the hands of the Philistians.\n"
	"And when his servants had reported to David the words that Saul had said, the word was liked in the eyes of David, to be made the king's son in law.\n"
	"And after few days David rising up, went with the men that were under him, and he struck of the Philisthiims two hundred men, and brought their prepuces, and numbered them to the king, that he might be his son in law, Saul therefore gave him Michol his daughter to wife.\n"
	"And Saul saw, and understood that our Lord was with David. And Michol the daughter of Saul loved him.\n"
	"And Saul began more to fear David: and Saul became enemy to David all days.\n"
	"And the Princes of the Philistians went forth: and from the beginning of their going forth, David behaved himself more wisely, than all the servants of Saul, and his name was made renowned exceedingly.";