const char* chap258 = "David therefore went from thence, and fled to the cave of Odollam. Which when his brethren had heard, and all his father's house, they went down to him thither.\n"
	"And there were gathered unto him all that were in distress, and oppressed with debt, and of a pensive heart, and he was made their Prince, and there were with him about four hundred men.\n"
	"And David departed from thence into Maspha which is Moab: and he said to the king of Moab: Let my father and my mother tarry with you, I beseech thee, till I know what God will do to me.\n"
	"And he left them before the face of the king of Moab, and they abode with him all the days that David was in garrison.\n"
	"And Gad the Prophet said to David. Tarry not in garrison, depart, and go into the Land of Juda. And David departed, and came into the forest of Haret.\n"
	"And Saul heard that David had appeared, and the men that were with him. And Saul when he abode in Gabaa, and was in the wood which is in Rama, holding a spear in his hand, and all his servants that stood about him,\n"
	"he said to his servants that stood about him: Hear me now ye children of Jemini: will the son of Isai give to all you fields, and vineyards, and make all you tribunes, and centurions:\n"
	"because you have all conspired against me, and there is none that telleth me, especially where my son also hath entered league with the son of Isai? There is none of you that pitieth my case, neither is there that telleth me: for that my son hath raised up my servant against me, lying in wait for me until this day.\n"
	"And Doeg the Idumeite which stood by, and was the chief among the servants of Saul, answering, I saw, quoth he, the son of Isai in Nobe with Achimelech the son of Achitob the Priest.\n"
	"Who consulted our Lord for him, and gave him victuals, yea and the sword of Goliath the Philistian he gave to him.\n"
	"The king therefore sent to call for Achimelech the Priest the son of Achitob & all his father's house, the Priests that were in Nobe, who came all to the king.\n"
	"And Saul said to Achimelech: Hear thou son of Achitob. Who answered: I am ready, my Lord.\n"
	"And Saul said to him: Why have you conspired against me, thou, and the son of Isai, and hast given him bread and a sword, & hast consulted our Lord for him, that he might rise up against me, continuing a traitor until this day?\n"
	"And Achimelech answering the king, said: And who amongst all thy servants faithful as David, and the king's son in law, and going forth at thy commandment, & glorious in thy house?\n"
	"Did I begin this day to consult our Lord for him? Far be this from me: let not the king suspect such a thing against his servant, in all the house of my father: for thy servant knew not any thing concerning this business, either little or great.\n"
	"And the king said: Dying thou shalt die Achimelech, thou, and all thy father's house.\n"
	"And the king said to the couriers, that stood about him. Turn yourselves, and kill the Priests of our Lord, for their hand is with David, knowing that he was fled, and they told me not. And the king's servants would not extend their hands upon the Priests of our Lord.\n"
	"And the king said to Doeg: Turn thou, and run upon the Priests. And Doeg the Idumeite being turned, ran upon the Priests, and murdered in that day eighty five men revested with an ephod of linen.\n"
	"And Nobe the city of the Priests he struck in the edge of the sword, men and women, and children, and sucklings, and oxe and ass and sheep in the edge of the sword.\n"
	"But one son of Achimelech the son of Achitob, escaping, whose name was Abiathar, fled to David,\n"
	"and told him that Saul had slain the Priests of our Lord.\n"
	"And David said to Abiathar: I knew in that day when Doeg the Idumeite was there, without doubt he would tell Saul, I am guilty of all the souls of thy father.\n"
	"Abide with me, fear not: if any man shall seek my life, he shall seek thy life also, and with me thou shall be preserved.";