const char* chap259 = "And they told David, saying: Behold the Philistiims oppugn Ceila, and spoil the barns.\n"
	"David therefore consulted our Lord, saying: Shall I go, and strike these Philistians? And our Lord said to David: Go, and thou shalt strike the Philistians, and shalt save Ceila.\n"
	"And the men that were with David, said to him: Behold we resting here in Jury are afraid, how much more if we shall go into Ceila against the bands of the Philistians?\n"
	"Again therefore David consulted our Lord. Who answering said to him: Arise, and go into Ceila: for I will deliver the Philistians in thy hand.\n"
	"David therefore and his men went into Ceila, and fought against the Philistians, and drove away their beasts, and struck them with a great slaughter, and David saved the inhabitants of Ceila.\n"
	"Moreover at that time, when Abiathar the son of Achimelech fled to David into Ceila, he went down having with him an ephod.\n"
	"And it was told Saul that David was come into Ceila: and Saul said: Our Lord hath delivered him into my hands, & he is shut up being entered the city, where in are gates and locks.\n"
	"And Saul commanded all the people, that they should go down into Ceila to fight, and besiege David and his men.\n"
	"Which when David understood, that Saul secretly prepared evil against him, he said to Abiathar the Priest: Apply the Ephod.\n"
	"And David said: Lord God of Israel, thy servant hath heard a bruit, that Saul determineth to come into Ceila, to destroy the city for me:\n"
	"Will the men of Ceila deliver me into his hands? And will Saul come down, as thy servant hath heard? Lord God of Israel tell thy servant. And our Lord said: He will come down.\n"
	"And David said: Will the men of Ceila deliver me, and the men that are with me, into the hands of Saul? And our Lord said: They will deliver thee.\n"
	"David therefore arose and his men, about six hundred, and going out of Ceila, wandered hither and thither uncertain: and it was told Saul that David was fled from Ceila, and was saved: for which cause he dissembled to go forth.\n"
	"But David abode in the desert in most strong places, & he tarried in the mount of the desert Ziph, in a shadowed hill. Saul notwithstanding sought him always: and our Lord delivered him not into his hands.\n"
	"And David saw that Saul was gone forth to seek his life. Moreover David was in the desert Ziph, in a wood.\n"
	"And Jonathas the son of Saul arose, and went to David into the wood, and strengthened his hands in God, and said to him:\n"
	"Fear not; for neither shall the hand of Saul my father find thee, and thou shalt reign over Israel, & I shall be second to thee, yea and my father knoweth this.\n"
	"Both therefore made a league before our Lord: and David abode in the wood: but Jonathas returned into his house.\n"
	"And the Zipheites went up unto Saul in Gabaa, saying: Lo, doth not David lie hid with us in the most safe places of the wood, in the hill Hachila, which is on the right hand of the desert?\n"
	"Now therefore, as thy soul hath desired, come down, & it shall be our charge to deliver him into the king's hands.\n"
	"And Saul said: Blessed be ye of our Lord, because you have pitied my case.\n"
	"Go therefore I pray you, and prepare diligently, and deal curiously, and consider the place, where his foot is, and who hath seen him there, for he thinketh of me, that I craftily lie in wait for him.\n"
	"Consider and see all his lurking holes, wherein he is hid, and return to me with the certainty of the thing, that I may go with you. Yea and if he shall stop up himself into the earth, I will search him out among all the thousands of Juda.\n"
	"But they rising went into Ziph before Saul: and David and his men were in the desert Maon, in the champion country at the right hand of Jesimon.\n"
	"Saul therefore and his company went to seek him: and it was told David, and forthwith he went down to the rock, and abode in the desert Maon, which when Saul had heard, he pursued David in the desert Maon.\n"
	"And Saul went at the side of the mountain on the one part: and David and his men were in the side of the mountain on the other part: moreover David despaired that he could escape from the face of Saul: Saul therefore & his men in manner of a ring compassed David & his men, to take them.\n"
	"And a messenger came to Saul, saying: Make haste, and come, because the Philistiims have poured in themselves upon the land.\n"
	"Saul therefore returned leaving off to pursue David, and he went to meet the Philistians. For this cause they called that place, The Rock dividing.";