const char* chap261 = "And Samuel died, and all Israel was gathered together, and they mourned for him, and buried him in his house in Ramatha. And David rising went down into the desert of Pharan.\n"
	"And there was a certain man in the wilderness of Maon, & his possession in Carmel, & that man was exceeding great: and he had three thousand sheep, & a thousand goats: and it chanced that his flock was shorn in Carmel.\n"
	"And the name of the man was Nabal: & the name of his wife Abigail. And that woman was very wise and beautiful: moreover her husband hard, and very ill, and malicious: and he was of the kindred of Caleb.\n"
	"When David therefore heard in the desert, that Nabal sheared his flock,\n"
	"he sent ten young men, and said to them: Go up into Carmel, & you shall come to Nabal, and shall salute him in my name peaceably.\n"
	"And you shall say: Peace be to my brethren, and to thee, and peace to thy house, and to all whatsoever thou hast^ be peace.\n"
	"I have heard, that thy shepherds which were with us in the desert did shear: we have never molested them, neither hath ought been wanting to them at any time of the flock, all the time that they were with us in Carmel.\n"
	"Ask thy servants, and they will tell thee. Now therefore let thy servants find grace in thine eyes: for we are come in a good day, whatsoever thy hand shall find, give thy servants, and thy son David.\n"
	"And when David's servants were come, they spake to Nabal all these words in David's name: and so held their peace.\n"
	"But Nabal answering the servants of David, said: Who is David? And what is the son of Isai? There are servants multiplied now a days which fly from their masters.\n"
	"Shall I then take my breads, and my waters, and the flesh of my cattle, which I have killed for my shearers, and give to men whom I know not whence they are?\n"
	"Therefore the servants of David returned by their way, and returning came & told him all the words that he had said.\n"
	"Then said David to his servants: Every man gird him with his sword. And they were every one girded with their swords. And David also was girded with his sword: and there followed David about four hundred men: moreover two hundred remained at the baggage.\n"
	"But to Abigail the wife of Nabal one of their servants told, saying: Behold David hath sent messengers from the desert, to bless our master, and he disdained them:\n"
	"these men were good enough to us, & not troublesome: neither did ever any thing perish all the time, that we have converst with them in the desert:\n"
	"they were in stead of a wall to us both in the day and in the night, all the days that we fed the flocks with them.\n"
	"Wherefore consider, and think what thou hast to do, for malice is accomplished against thy husband, & against thy house, and he is the son of Belial, so that no man can speak to him.\n"
	"Abigail therefore made haste, and took two hundred loaves, and two bottles of wine, and five muttons ready dresst, and five measures of polent, and an hundred branches of raisins, and two hundred masses of dry figs, and laid them upon asses,\n"
	"and said to her servants: Go before me; lo, I will follow you at your back: but she told not her husband Nabal.\n"
	"When she therefore had gotten upon an ass, and came down to the foot of the mountain, David and his men came down meeting her, whom she also met.\n"
	"And David said: In vain verity have I preserved all things that were this man's in the desert, and there perished nothing of all that pertained to him, & he hath rendered me evil for good.\n"
	"These things do God to the enemies of David, & these things add he, if I shall leave of all things that pertain to him until morning, any thing pissing against the wall.\n"
	"And when Abigail had seen David, she made haste, & light from her ass, & fell down before David upon her face, & adored upon the earth,\n"
	"and fell at his feet, & said: In me my Lord be this iniquity: let thy handmaid speak I beseech thee in thine ears: and hear the words of thy servant.\n"
	"Let not my lord the king I pray thee, set his heart upon this naughty man Nabal: because according to his name, he is a fool, and folly is with him: but I thy handmaid saw not thy servants my lord, whom thou didst send.\n"
	"Now therefore my lord, our Lord liveth, and thy soul liveth, who hath stayed thee that thou shouldst not come unto blood, and hath saved thy hand to thee: and now be thine enemies as Nabal, & they that seek evil to my lord.\n"
	"Wherefore receive this benediction, which thy handmaid hath brought to thee my lord: and give to thy servants that follow thee my lord.\n"
	"Take away the iniquity of thy handmaid: for our Lord making will make to my lord a faithful house, because thou my lord dost fight the battles of our Lord: let not malice therefore be found in thee all the days of thy life.\n"
	"For if a man shall rise, persecuting thee, & seeking thy life, the life of my lord shall be kept, as in the bundle of the living, with our Lord thy God: Moreover the life of thine enemies shall be whurled, as in the violence, and whurl of a sling.\n"
	"When our Lord therefore shall do to thee, my lord, all good things, which he hath spoken concerning thee, and shall constitute thee Prince over Israel,\n"
	"this shall not be an occasion of sobbing to thee, and a scruple of heart to my Lord, that thou hast shed innocent blood, or thyself hast revenged thyself: and when our Lord hath bestowed these benefits upon my lord, thou shalt remember thy handmaid.\n"
	"And David said to Abigail: Blessed be our Lord the God of Israel, who hath sent thee this day to meet me, and blessed be thy speech,\n"
	"and blessed be thou, which hast stayed me today, that I might not go to blood, and revenge me with mine own hand.\n"
	"Otherwise our Lord liveth, the God of Israel, who hath stayed me that I should not do thee any evil, unless thou hadst quickly come to meet me, there had not remained to Nabal until morning light, any pissing against a wall.\n"
	"And David took of her hand all things which she had brought him, and said to her: Go peaceably into thy house, behold I have heard thy voice, and have honoured thy face.\n"
	"And Abigail came to Nabal: and behold he had a feast in his house, as it were the feast of a king, and Nabal's heart was pleasant: for he was drunk exceedingly: and she told him not a word little or great until morning.\n"
	"But early when Nabal had digested his wine, his wife told him these words, & his heart was dead inwardly, & he became as a stone.\n"
	"And when ten days had passed, our Lord struck Nabal, & he died.\n"
	"Which when David had heard that Nabal was dead, he said: Blessed be our Lord, who hath judged the cause of my reproach at the hand of Nabal, and hath kept his servant from evil, and the malice of Nabal hath our Lord rendered upon his head. David therefore sent, and spake to Abigail, that he might take her to himself to wife.\n"
	"And David's servants came to Abigail into Carmel, and spake to her, saying: David hath sent us unto thee, to take thee to his wife.\n"
	"Who arising adored flat toward the earth, and said: Lo let thy servant be as an handmaid, to wash the feet of the servants of my lord.\n"
	"And Abigail arose, and made haste, and gat upon an ass, and five women went with her, waiting maids, and followed the messengers of David, and became his wife.\n"
	"Yea and Achinoam also did David take of Jezrahel: and both were his wives.\n"
	"But Saul gave Michol his daughter David's wife to Phalti, the son of Lais, who was of Gallim.";