const char* chap266 = "And when David & his men were come to Siceleg the third day, the Amalecites had made an invasion on the south side into Siceleg, & had strucken Siceleg, & burnt it with fire.\n"
	"And had led away women captive out of it, from the less unto the great: and had not killed any man, but had led them with them, & went on their journey.\n"
	"When David therefore and his men were come to the city, and had found it burnt with fire, and their wives and their sons, and their daughters to be led away captive,\n"
	"David and the people that was with him, lifted up their voices, and mourned till tears failed them.\n"
	"For the two wives also of David were led away captive, Achinoam the Iezraelite, and Abigail the wife of Nabal of Carmel.\n"
	"And David was strucken very sad: for the people would have stoned him, because the soul of every man was bitterly affected upon their sons, and daughters: but David was strengthened in our Lord his God.\n"
	"And he said to Abiathar the Priest the son of Achimelech: Apply unto me the Ephod. And Abiathar applied the Ephod to David,\n"
	"and David consulted our Lord, saying: Shall I pursue these thieves, and shall I take them or not? And our Lord said to him: Pursue them: for thou shalt take them without doubt, & take from them the prey.\n"
	"David therefore went himself, and the six hundred men that were with him, and they came unto the Torrent Besor: & some being weary stayed.\n"
	"But David himself, and four hundred men pursued: for two hundred stayed, who being weary could not pass the Torrent Besor.\n"
	"And they found an Aegyptian in the field, and brought him to David: and they gave him bread to eat, and water to drink,\n"
	"and also a piece of a mass of dry figs, and two bunches of resins. Who when he had eaten, his spirit returned, and he was refreshed: for he had not eaten bread, nor drunken water three days and three nights.\n"
	"David therefore said to him. Whose art thou? Or whence? And wither goest thou? Who said: I am a young man of Aegypt, the servant of an Amalecite: and my master hath left me, because I began to be sick three days agone.\n"
	"For we brake forth at the south side of Cerethi, and against Juda, and at the south of Caleb, and burnt Siceleg with fire.\n"
	"And David said to him: Canst thou bring me to this company? Who said: Swear to me by God, that thou wilt not kill me, nor deliver me into the hands of my lord, and I will bring thee to this company, And David sware to him.\n"
	"Who when he had brought them, behold they sat upon the face of all the earth, eating & drinking, and as it were keeping a festival day, for all the prey and spoils which they had taken out of the Land of the Philisthiims, and out of the Land of Juda.\n"
	"And David struck them from evening until the evening of the next day, and there escaped not any of them, but four hundred young men, which had gotten upon camels, and were fled.\n"
	"David therefore rescued all things that the Amalecites had taken, and he rescued his two wives.\n"
	"Neither was there any wanting from little to great, as well of their sons as of their daughters, and of the spoils, and what things soever they had taken, David brought all again.\n"
	"And he took all the flocks and herds, and drave them before his face: and they said: This is the prey of David.\n"
	"And David came to the two hundred men, which being weary had stayed, neither were able to follow David, and he had bidden them to rest in the Torrent Besor: who came forth to meet David, and the people that were with him. And David coming to the people, saluted them peaceably.\n"
	"And every naughty, and wicked fellow of the men, that had gone with David, answering, said: Because they came not with us, we will not give them any thing of the prey, which we have recovered: but let their wife and children suffice every man, whom when they had received, let them depart.\n"
	"But David said: You shall not do so my brethren, of these things, which our Lord hath delivered to us, and hath kept us, and hath given the thieves, that were broken out against us, into our hands:\n"
	"neither shall any man hear you upon this talk. For there shall be equal portion of him that went down into battle, and of him that abode at the baggage, and they shall divide alike.\n"
	"And this hath been done from that day, and ever after it was decreed, and ordained as a law in Israel.\n"
	"David therefore came into Siceleg, and sent gifts of the prey to the ancients of Juda his neighbours, saying: Take a benediction of the prey of our Lord's enemies.\n"
	"To them that were in Bethel, and that were in Ramoth toward the South, and them that were in Gether,\n"
	"and them in Aroer, and them in Sephamoth, and them in Esthamo,\n"
	"and them in Rachal, and them in the cities of Jerameel, and them in the cities of Semi,\n"
	"and them in Harama, and them in the lake of Asan, and them in Athach,\n"
	"and them in Hebron, and to the rest that were in those places, in the which David had tarried, and his men.";