const char* chap267 = "And the Philisthiims fought against Israel, and the men of Israel fled before the face of the Philisthiims, and fell being slain in mount Gelboe.\n"
	"And the Philisthiims fell upon Saul, and upon his sons, and they struck Jonathas, and Abinadab, and Melchisua the sons of Saul,\n"
	"and the whole weight of the battle was turned upon Saul: and the archers overtook him, and he was sore wounded of the archers.\n"
	"And Saul said to his esquire: Draw out thy sword, and strike me: lest perhaps these uncircumcised come, and kill me, mocking me. And his esquire would not: for he was frighted with exceeding fear. Saul therefore caught his sword, and fell upon it.\n"
	"Which when his esquire had seen, to wit, that Saul was dead, himself also fell upon his sword and died with him.\n"
	"Saul therefore died, and his three sons, and his esquire, and all his men in that day together.\n"
	"And the children of Israel, that were beyond the valley, and beyond Jordan, seeing that the men of Israel were fled, and that Saul was dead, and his sons, they left their cities, and fled: and the Philisthiims came, and dwelt there.\n"
	"And when the next day was come, the Philisthiims came to spoil them that were slain, and they found Saul and his three sons, lying in mount Gelboe.\n"
	"And they did cut off Saul's head, and spoiled him of his armour, and sent into the land of the Philistians round about, that it should be declared in the temple of their idols, and among their people.\n"
	"And they did put his armour in the temple of Astaroth, but his body they hung on the wall of Bethsam.\n"
	"Which when the inhabiters of Jabes Galaad had heard whatsoever the Philisthiims had done to Saul,\n"
	"all the most valiant men arose, and walked all the night, and took the body of Saul, and the bodies of his sons, from the wall of Bethsam: and they came to Jabes Galaad, and burnt them them there:\n"
	"and they took their bones, and buried them in the wood of Jabes, and fasted seven days.";