const char* chap268 = "And it came to pass, after that Saul was dead, that David returned from the slaughter of Amalec, and tarried in Siceleg two days.\n"
	"And in the third day there appeared a man coming out of Saul's camp, his garments torn, and sprinkled on the head with dust, and as he came to David, he fell upon his face, and adored.\n"
	"And David said unto him: Whence comest thou? Who said to him: I fled out of the camp of Israel.\n"
	"And David said unto him: What is the matter that is done? Tell me. Who said: The people is fled out of the battle, and many of the people are overthrown & dead: yea Saul also and Jonathas his son are dead.\n"
	"And David said to the young man that told him: How knowest thou that Saul is dead, and Jonathas his son?\n"
	"And the young man that told him, said: By chance I came into mount Gelboe, and Saul leaned upon his spear: moreover the chariots and horsemen approached unto him,\n"
	"and turning backward, and seeing me he called. To whom when I had answered, Here I am,\n"
	"he said to me: Who art thou? And I said to him: I am an Amalecite.\n"
	"And he said to me: Stand upon me and kill me, because anguishes hold me, and as yet all my life is in me.\n"
	"And standing upon him, I killed him: for I knew that he could not live after the fall: and I took the Diadem that was on his head, & the bracelet from his arm, & have brought to thee my lord hither.\n"
	"And David taking his garments rent them, and all the men that were with him,\n"
	"and they mourned, & wept, & fasted until evening upon Saul & upon Jonathas his son, and upon the people of our Lord, & upon the house of Israel, because they were fallen by the sword.\n"
	"And David said to the young man that had told him: Whence art thou? Who answered: I am the son of a man a stranger of Amalec.\n"
	"David said to him: Why didst thou not fear to put to thy hand to kill the anointed of our Lord?\n"
	"And David calling one of his servants, said: Go run upon him. Who struck him, & he died.\n"
	"And David said to him: Thy blood be upon thine own head: for thine own mouth hath spoken against thee, saying: I have slain the anointed of our Lord.\n"
	"And David mourned this kind of mourning upon Saul, and upon Jonathas his son.\n"
	"And he commanded that they should teach the children of Juda the bow, as it is written in the Book of the just.) And he said: Consider, O Israel, for them that be dead wounded upon thy high places.\n"
	"The Nobles, O Israel, are slain upon thy mountains: how are the valiant fallen?\n"
	"Tell it not in Geth, neither tell ye it in the high ways of Ascalon: lest perhaps the daughters of the Philisthiims be glad, lest the daughters of the uncircumcised rejoice.\n"
	"Mountains of Gelboe, let neither dew nor rain come upon you, neither be they fields of the first fruits: because there was the shield of the valiants cast away, the shield of Saul, as though he were not anointed with oil.\n"
	"From the blood of the slain, from the fat of the valiants, the arrow of Jonathas never returned backward, and the sword of Saul did not return empty.\n"
	"Saul and Jonathas amiable, and comely in their life, in death also were not divided: swifter than eagles, stronger than lions.\n"
	"Ye daughters of Israel weep upon Saul, who clothed you with scarlet in delicacies, who gave golden ornaments to your attire.\n"
	"How have the valiants fallen in battle? Jonathas been slain in thy high places?\n"
	"I am sorry for thee, my brother Jonathas, exceeding beautiful and amiable above the love of women. As the mother loveth her only son, so did I love thee.\n"
	"How have the strong fallen, and the weapons of war perished?";