const char* chap27 = "And Isaac was old, and his eyes were dim, and he could not see: and he called Esau his elder son, and said to him: My son? Who answered: Here I am.\n"
	"To whom his father: Thou seest, quoth he, that I am old, and know not the day of my death.\n"
	"Take thy instruments, thy quiver, and bow, and go abroad: and when thou hast taken any thing by hunting,\n"
	"make me broth thereof, as thou knowest I like, and bring that I may eat, and my soul may bless thee before I die.\n"
	"Which when Rebecca had heard, and he was gone into the field to fulfill his father's commandment,\n"
	"she said to her son Jacob: I heard thy father talking with Esau thy brother, and saying to him:\n"
	"Bring me of thy hunting, and make me meats that I may eat, and bless thee in the sight of our Lord before I die.\n"
	"Now therefore, my son, assent to my counsel:\n"
	"and go thy way to the flock, bring me two kids of the best, that I may make of them meat for thy father, such as he gladly eateth:\n"
	"Which when thou hast brought in, and he hath eaten, he may bless thee before he die.\n"
	"To whom he answered: Thou knowest that Esau my brother is an hairy man, and I am smooth:\n"
	"if my father shall feel me, and perceive it, I fear lest he will think I would have deluded him, and I shall bring upon me a curse for a blessing.\n"
	"To whom his mother said: This curse, my son, light upon me, only hear thou my voice, and go, fetch me the things which I have said.\n"
	"He went, and brought, and gave them to his mother. She dressed meats, even as she knew his father liked.\n"
	"And she did on him the garments of Esau very good, which she had at home with her:\n"
	"and the little skins of the kids she put about his hands, and covered the bare of his neck.\n"
	"And she gave him the broth, and delivered him bread that she had baked.\n"
	"Which when he had carried in, he said: My father? But he answered: I hear. Who art thou my son?\n"
	"And Jacob said: I am thy first begotten Esau: I have done as thou didst command me: arise, sit, and eat of my hunting, that thy soul may bless me.\n"
	"And again Isaac to his son: How couldest thou, said he, find it so quickly, my son? Who answered: It was the will of God that that which I would^ came quickly in my way.\n"
	"And Isaac said: Come hither, that I may feel thee my son, and may prove whether thou be my son Esau, or not.\n"
	"He came near to his father, and when he had felt him, Isaac said: The voice verily, is the voice of Jacob: but the hands are the hands of Esau.\n"
	"And he knew him not, because his hairy hands had made him like unto the elder. Blessing him therefore,\n"
	"he said: Art thou my son Esau? He answered: I am.\n"
	"But he said: Bring me the meats of thy hunting, my son, that my soul may bless thee. Which when they were brought and he had eaten, he offered him wine also, which after he had drunk,\n"
	"he said to him: Come near me, and give me a kiss, my son.\n"
	"He came near, and kissed him. And immediately as he felt the fragrant savour of his garments, blessing him, he said: Behold the savour of my son is as the savour of a plentiful field, which our Lord hath blessed.\n"
	"God give thee of the dew of heaven, & of the fatness of the earth abundance of corn and wine.\n"
	"And let peoples serve thee, and tribes adore thee: be thou lord of thy brethren, and thy mother's children bow they before thee. He that shall curse thee, be he cursed: and he that shall bless thee, be he replenished with blessings.\n"
	"Isaac had scarce ended his words, and Jacob now gone forth abroad, but Esau came,\n"
	"and brought in to his father meats made of his hunting, saying: Arise my father, and eat of thy son's hunting; that thy soul may bless me.\n"
	"And Isaac said to him: Why! Who art thou? Who answered: I am thy first begotten son Esau.\n"
	"Isaac was amazed and astonished exceedingly, and marveling more than a man can believe, said: Who is he then that even now brought me venison that he had taken, and I did eat of all things before thou camest, and I have blessed him, and he shall be blessed.\n"
	"Esau having heard his father's words, roared out with a great cry; and being dismayed, said: Bless me also, my father.\n"
	"Who said: Thy brother came deceitfully and took thy blessing.\n"
	"But he said again: Rightly is his name called Jacob; for he hath supplanted me lo the second time: my first-birth-right he took before, and now the second time he hath stolen my blessing. And again to his father he said: Hast thou not reserved me also a blessing?\n"
	"Isaac answered: I have appointed him thy lord, and all his brethren I have made subject to his service: with corn and wine I have established him, and for thee, my son, what shall I do more after this?\n"
	"To whom Esau said: Hast thou one only blessing, father? I beseech thee bless me also. And when he wept that he howled again,\n"
	"Isaac being moved, said to him: In the fat of the earth, and in the dew of heaven from above,\n"
	"shall thy blessing be. Thou shalt live by the sword, and shalt serve thy brother: and the time shall come, when thou shalt shake off and loose his yoke from thy neck.\n"
	"Esau therefore always hated Jacob for the blessing wherewith his father had blessed him; and he said in his heart: The days will come of the mourning of my father, and I will kill Jacob my brother.\n"
	"These things were told to Rebecca: who sending and calling Jacob her son, said to him: Behold Esau thy brother threateneth to kill thee.\n"
	"Now therefore, my son, hear my voice, and get thee up and fly to Laban my brother into Haran:\n"
	"and thou shalt dwell with him a few days, till the fury of thy brother be assuaged,\n"
	"and his indignation cease, and he forget those things which thou hast done to him: afterward I will send, and bring thee from thence hither. Why shall I be deprived of both sons in one day?\n"
	"And Rebecca said to Isaac: I am weary of my life for the daughters of Heth: if Jacob take a wife of the stock of this land, I list not live.";