const char* chap270 = "There was made therefore long strife between the house of Saul, & between the house of David: David prospering & always stronger than himself, but the house of Saul decreasing daily.\n"
	"And there were sons born to David in Hebron: & his first begotten was Amnon of Achinoam the Jezrahelite.\n"
	"And after him Cheleab of Abigail the wife of Nabal of Carmel: moreover the third Absalom, the son of Maacha the daughter of Tolmai king of Gessur.\n"
	"And the fourth Adonias, the son of Haggith: and the fifth Saphathia, the son of Abital.\n"
	"The sixth also Jethraam of Egla the wife of David. These were born to David in Hebron.\n"
	"Therefore when there was battle between the house of Saul & house of David, Abner the son of Ner ruled the house of Saul.\n"
	"And Saul had a concubine named Respha, the daughter of Aia. And Isboseth said to Abner:\n"
	"Why didest thou go in to my father's concubine? Who being wrath exceedingly for the words of Isboseth, said: What am I a dog's head against Juda this day, which have done mercy upon the house of Saul thy father, and upon his brethren and nearest friends, and have not delivered thee into the hands of David, and hast thou sought against me that thou mightest charge me for a woman today?\n"
	"These things do God to Abner, and these things add he to him, unless as our Lord hath sworn to David, so I do truth to him.\n"
	"That the Kingdom be transferred from the house of Saul, and the throne of David be exalted over Israel, and over Juda, from Dan to Bersabee.\n"
	"And he could not answer him any thing, because he feared him.\n"
	"Abner therefore sent messengers to David for himself saying: Whose is the land? And that they should say: Make amity with me, and my hand shall be with thee: and I will reduce unto thee all Israel.\n"
	"Who said: Very well; I will make amity with thee: but one thing I desire of thee, saying: Thou shalt not see my face before thou bring Michol the daughter of Saul: and so thou shalt come, and see me.\n"
	"And David sent messengers to Isboseth the son of Saul, saying: Restore my wife Michol, which I betrothed to me for an hundred prepuces of the Philisthiims.\n"
	"Isboseth therefore sent, and took her from her husband Phaltiel, the son of Lais.\n"
	"And her husband followed her weeping as far as Behurim: and Abner said to him: Go, and return. Who returned.\n"
	"Abner also spake to the ancients of Israel, saying: Both yesterday and the day before you sought David that he might reign over you.\n"
	"Now therefore do so: because our Lord hath spoken to David, saying: In the hand of my servant David I will save my people Israel from the hands of the Philisthiims, and of all their enemies.\n"
	"And Abner spake also to Benjamin. And he went to speak unto David in Hebron all things which pleased Israel, and all Benjamin.\n"
	"And he came to David into Hebron with twenty men: and David made a feast to Abner, and to his men that came with him.\n"
	"And Abner said to David: I will rise, that I may gather unto thee my lord king all Israel, and may enter a league with thee, & thou mayest reign over all, as thy soul desireth. When David therefore had brought Abner on the way, and he was gone in peace,\n"
	"forthwith David's servants and Joab came, having slain the robbers, with a prey exceeding great: and Abner was not with David in Hebron, because he had now dismissed him, and he was departed in peace.\n"
	"And Joab, and all the army which were with him, came afterward: it was therefore told Joab, that Abner the son of Ner came to the king, and he dismissed him, and he departed in peace.\n"
	"And Joab went in to the king, & said: What hast thou done? Behold Abner came to thee: why didst thou dismiss him & he is gone & departed?\n"
	"knowest thou not Abner the son of Ner, that to this end he came to thee, that he might deceive thee, & might know thy going out, & thy coming in, & understand all things that thou doest?\n"
	"Joab therefore being gone from David, sent messengers after Abner, and brought him back from the cistern Sira, David being ignorant thereof.\n"
	"And when Abner was returned into Hebron, Joab brought him aside to the midst of the gate, to speak unto him in guile: and struck him there in the privy parts, & he died, in revenge of the blood of Asael his brother.\n"
	"Which when David had heard, that the thing was now done, he said: I am innocent, and my Kingdom before God for ever from the blood of Abner the son of Ner,\n"
	"& come it upon the head of Joab, & upon all his father's house: neither let there fail of the house of Joab one having a flux of seed, & a leper, and holding the distaff, and falling by the sword, & lacking bread.\n"
	"Joab therefore & Abisai his brother slew Abner, because he had killed Asael their brother in Gabaon in the battle.\n"
	"And David said to Joab, and to all the people, that were with him: Rent your garments, and be girded with sack cloths, & mourn before the funeral of Abner. Moreover king David followed the bier.\n"
	"And when they had buried Abner in Hebron, king David lifted up his voice, and wept upon the grave of Abner: and all the people also wept.\n"
	"And the king mourning and lamenting Abner, said: Not as cowards are wont to die, hath Abner died.\n"
	"Thy hands were not bound, and thy feet were not laden with fetters: but as men are wont to fall before the children of iniquity, so art thou fallen. And all the people doubling it wept upon him.\n"
	"And when all the multitude was come to take meat with David, when it was yet clear day, David sware, saying: These things do God to me, and these add he, if before sun set I shall taste bread or any thing else.\n"
	"And all the people heard, and all things pleased them which the king did in the sight of all the people.\n"
	"And all the people knew, and all Israel in that day, that it was not the king's doing, that Abner the son of Ner was slain.\n"
	"The king also said to his servants: Are you ignorant that a Prince, and the greatest is slain this day in Israel?\n"
	"But I as yet delicate, & anointed king: moreover the sons of Sarvia are hard to me: our Lord reward him that doeth evil according to his malice.";