const char* chap272 = "And all the tribes of Israel came to David in Hebron, saying: Behold we are thy bone and thy flesh.\n"
	"Yea and yesterday also & the day before when Saul was king over us, thou wast he that didst lead us forth & bring back Israel: & our Lord said to thee: Thou shalt feed my people Israel, and thou shalt be Prince over Israel.\n"
	"The ancients also of Israel came to the king into Hebron, & king David made a league with them in Hebron before our Lord: and they anointed David to be king over Israel.\n"
	"Thirty years old was David when he began to reign, and he reigned forty years.\n"
	"In Hebron he reigned over Juda seven years and six months: and in Jerusalem he reigned three and thirty years over all Israel & Juda\n"
	"And the king went, & all the men that were with him, into Jerusalem, to the Jebuseite the inhabiter of the land, & they said to David: Thou shalt not come in hither, unless thou take away the blind & the lame, saying: David shall not come in hither.\n"
	"But David took the tower of Sion, this is the city of David.\n"
	"For David had proposed in that day a reward to whosoever should strike the Jebuseite, and touch the gutters of the house tops, and take away the blind and the lame that hated the soul of David: therefore it is said in the proverb: The blind and the lame shall not enter into the temple.\n"
	"And David dwelt in the tower, and called it, The city of David: & built round about from Mello and inwards.\n"
	"And he went prospering and growing up, and our Lord the God of hosts was with him.\n"
	"Hiram also the king of Tyre sent messengers to David, and cedar trees, and carpenters, and masons for walls: and they built a house for David.\n"
	"And David knew that our Lord had confirmed him king over Israel, and that he exalted his Kingdom over his people Israel.\n"
	"David therefore took yet concubines and wives of Jerusalem, after he was come from Hebron: and there were born to David other sons also and daughters:\n"
	"And these be the names of them, that were born to him in Jerusalem, Samua, and Sobab, and Nathan, and Salomon,\n"
	"and Jebahar and Elisua, and Nepheg,\n"
	"and Japhia, and Elisama, and Elioda, and Eliphaleth.\n"
	"The Philistiims therefore heard that they had anointed David to be king over Israel: and they went up all to seek David: which when David had heard, he went down into a hold.\n"
	"And the Philistiims coming were spread in the Vale Raphaim.\n"
	"And David consulted our Lord, saying: Shall I go up to the Philistiims? And wilt thou give them into my hand? And our Lord said to David: Go up, because delivering I will give the Philistiims in thy hand.\n"
	"David therefore came into Baal Pharasim: and struck them there, and said: Our Lord hath divided mine enemies before me, as waters are divided, therefore the name of the place was called Baal Pharasim.\n"
	"And they left there their graven gods: which David, and his men took.\n"
	"And the Philistians added yet to go up, and spread themselves in the Vale Raphaim.\n"
	"And David consulted our Lord: Shall I go up against the Philistiims, and wilt thou deliver them into my hands? Who answered: Go not up against them, but fetch a compass behind their back, & thou shalt come to them over against the pear trees.\n"
	"And when thou shalt hear the sound of one going in the top of the pear-trees, then shalt thou enter battle: because then will our Lord go forth before thy face, to strike the camp of the Philistiims.\n"
	"David therefore did as our Lord had commanded him, and he struck the Philistiims from Gabaa, until thou come to Gezer.";