const char* chap273 = "And David again gathered all the chosen of Israel, thirty thousand,\n"
	"And David arose, and went, and all the people that was with him of the men of Juda, to bring the ark of God, upon which was invocated the name of the Lord of hosts, which sitteth in the Cherubins upon it.\n"
	"And they laid the ark of God upon a new wain: and took it out of the house of Abinadab, who was in Gabaa: and Oza and Ahio the sons of Abinadab, did drive the new wain.\n"
	"And when they had taken it out of the house of Abinadab, who was in Gabaa, Ahio keeping the ark of God went before the ark.\n"
	"But David, and all Israel played before our Lord in all wrought wood, both on harps and lutes and timbrels & citterns and cymbals.\n"
	"And after they came to the Floor of Nachon, Oza put forth his hand to the ark of God, and held it: because the oxen spurned, and made it lean aside.\n"
	"And our Lord was wrath with indignation against Oza, and struck him for the rashness: who died there before the ark of God.\n"
	"And David was strucken sad, for that our Lord had strucken Oza, & the name of that place was called: The striking of Oza until this day.\n"
	"And David feared our Lord in that day, saying: How shall the ark of our Lord come unto me?\n"
	"And he would not have the ark of our Lord turn in to himself into the city of David: but he caused it to turn in unto the house of Obededom the Getheite.\n"
	"And the ark of our Lord dwelt in the house of Obededom the Getheite three months: & our Lord blessed Obededom, & all his house,\n"
	"And it was told king David, that our Lord had blessed Obededom, & all that he had for the ark of God. David therefore went, & brought away the ark of God out of the house of Obededom, into the city of David with joy.\n"
	"And when they had passed, that carried the ark of our Lord, six passes, he immolated an oxe and a ram.\n"
	"And David danced with all his might before our Lord, moreover David was girded with a linen ephod.\n"
	"And David, & all the house of Israel brought the ark of testament of our Lord in jubilation, & in sound of trumpet.\n"
	"And when the ark of our Lord was entered into the city of David, Michol the daughter of Saul looking forth through a window, saw king David leaping, & dancing before our Lord: and she despised him in her heart.\n"
	"And they brought in the ark of our Lord, & set it in his place in the midst of the tabernacle, which David had pitched for it: & David offered holocausts, & pacifics before our Lord.\n"
	"And when he had accomplished offering holocausts and pacifics, he blessed the people in the name of the Lord of hosts.\n"
	"And he distributed to all the multitude of Israel as well man as woman, to every one, one cake of bread, and one roasted piece of beef, and flour fried with oil: and all the people went, every man into his house.\n"
	"And David returned to bless his own house: and Michol the daughter of Saul coming forth to meet David, said: How glorious was the king of Israel today uncovering himself before the handmaids of his servants, and was naked, as if one of the ribalds should be naked.\n"
	"And David said unto Michol: Before our Lord, which hath chosen me rather than thy father, and than all his house, and commanded me that I should be duke over the people of our Lord in Israel,\n"
	"both will I play, & will become more vile than I have been: and I will be humble in mine eyes, and with the handmaids, of whom thou speakest, I will appear more glorious.\n"
	"Therefore unto Michol the daughter of Saul was there no child born unto the day of her death.";