const char* chap274 = "And it came to pass when the king sat in his house, and our Lord had given him rest on every side from all his enemies,\n"
	"he said to Nathan the Prophet: Dost thou see that I dwell in a house of cedar, & the ark of God is set in the midst of skins?\n"
	"And Nathan said to the king: All that is in thy heart, go do, because our Lord is with thee.\n"
	"And it came to pass in that night: and behold the word of our Lord to Nathan, saying:\n"
	"Go, and speak to my servant David: Thus saith our Lord: Shalt thou build me a house to dwell in?\n"
	"For neither have I dwelt in house from the day that I brought the children of Israel out of the Land of Aegypt, until this day: but I walked in tabernacle, and in tent.\n"
	"Throughout all the places, that I have passed with all the children of Israel, speaking did I speak to one of the tribes of Israel, which I commanded to feed my people Israel, saying: why did you not build me a house of cedar?\n"
	"And now these things shalt thou say to my servant David: Thus saith the Lord of hosts: I took thee out of the pastures following the flocks, that thou shouldest be Prince over my people Israel:\n"
	"and I have been with thee wheresoever thou hast walked, and have slain all thine enemies from thy face: and have made thee a great name, according to the name of the great ones, that are in the earth.\n"
	"And I will appoint a place for my people Israel, and will plant it, and they shall dwell under it, and shall be troubled no more: neither shall the children of iniquity add to afflict them as before.\n"
	"From the day that I appointed Judges over my people Israel: and I will give thee rest from all thine enemies. And our Lord foretelleth thee, that our Lord will make thee a house.\n"
	"And when thy days shall be accomplished, and thou shalt sleep with thy fathers, I will raise up thy seed after thee, which shall come forth of thy womb, and I will establish his Kingdom.\n"
	"He shall build a house to my name, and I will establish the throne of his Kingdom for ever.\n"
	"I will be to him for a father, and he shall be to me for a son: who if he shall do any thing unjustly, I will rebuke him in the rod of men, and in the plagues of the sons of men.\n"
	"But my mercy I will not take away from him, as I took from Saul, whom I removed from thy face.\n"
	"And thy house shall be faithful, and thy Kingdom for ever before thy face, and thy throne shall be firm continually.\n"
	"According to all these words, & according to all this vision, so did Nathan speak to David.\n"
	"And David went in, & sat before our Lord, & said: Who am I, o Lord God, & what is my house, that thou hast brought me thus far?\n"
	"But this also hath seemed little in thy sight, o Lord God, unless thou didst speak also of the house of thy servant for a long time: for this is the law of Adam, Lord God.\n"
	"What can David therefore add yet, to speak unto thee? For thou knowest thy servant, o Lord God.\n"
	"For thy word, and according to thy heart thou hast done all these great things, so that thou wouldest notify it to thy servant.\n"
	"Therefore art thou magnified, o Lord God, because there is none like to thee, neither is there a God besides thee, in all things that we have heard with our ears.\n"
	"And what nation is there in the earth as thy people Israel, for the which God hath gone, that he might redeem it to be his people, & might make himself a name, & do for them great wonders, and horrible things upon the earth, before the face of thy people, whom thou redeemedst to thyself out of Aegypt, from the nations & from their gods.\n"
	"For thou hast confirmed the people Israel to be an everlasting people: and thou Lord God art become their God.\n"
	"Now therefore, o Lord God, raise up for ever the word, that thou hast spoken upon thy servant & upon his house, & do as thou hast spoken,\n"
	"that thy name may be magnified for ever, and it may be said: The Lord of hosts is God over Israel. And the house of thy servant David shall be established before our Lord,\n"
	"because thou, o Lord of hosts God of Israel, hast revealed the ear of thy servant, saying: A house I build thee: therefore hath thy servant found his heart to pray thee with this prayer.\n"
	"Now therefore, o Lord God, thou art God, & thy words shall be true: for thou hast spoken to thy servant these good things.\n"
	"Begin therefore, & bless the house of thy servant, that it may be for ever before thee: because thou Lord God hast spoken, by thy blessing shall the house of thy servant be blessed for ever.";