const char* chap275 = "And it came to pass, after these things David struck the Philisthiims, and humbled them, & David took the bridle of tribute out of the hand of the Philisthiims.\n"
	"And he struck Moab, & measured them with a cord, making them even with the earth: & he measured two cords, one to kill, & one to save alive: & Moab became serving David under tribute.\n"
	"And David struck Adarezer the son of Rohob king of Soba, when he went forth to have dominion over the river Euphrates.\n"
	"And David having taken of his part a thousand seven hundred horsemen, & twenty thousand footmen, hoghsinewed all the chariot horses: & he left of them a hundred chariots.\n"
	"There came also Syria of Damascus to bring aid unto Adarezer the king of Soba: and David struck of Syria two & twenty thousand men.\n"
	"And David put a garrison in Syria of Damascus: & Syria became serving David under tribute: and our Lord preserved David in all things to whatsoever he went forth.\n"
	"And David took the golden armour, which the servants of Adarezer had, and brought them into Jerusalem.\n"
	"And out of Bete, and out of Beroth the cities of Adarezer king David took brass exceeding much.\n"
	"And Tou the king of Emath heard that David had strucken all the force of Adarezer,\n"
	"And Tou sent Joram his son to king David, to salute him congratulating, and to give thanks: for that he had overthrown Adarezer, and strucken him. For Tou was enemy to Adarezer, and in his hand were vessels of gold, & vessels of silver, & vessels of brass:\n"
	"which also king David sanctified to our Lord with the silver and gold, that he had sanctified of all the nations, which he had subdued\n"
	"of Syria, & Moab, and the children of Ammon, and the Philisthiims, and Amalec, & of the spoils of Adarezer the son of Rohob king of Soba.\n"
	"David also made himself a name when he returned having taken Syria in the Vale of Salt-pits, eighteen thousand being slain:\n"
	"& he put soldiers in Idumea, and placed a garrison: and all Idumea was made to serve David: & our Lord preserved David in all things to whatsoever he proceeded.\n"
	"And David reigned over all Israel: David also did judgment and justice to all his people.\n"
	"And Joab the son of Sarvia was over the army: moreover Josaphat the son of Ahilud was recorder:\n"
	"and Sadoc the son of Achitob, and Achimelech the son of Abiathar, were Priests: and Saraias, scribe:\n"
	"And Banaias the son of Joiada was over the Cerethi and Phelethi: and the sons of David Princes.";