const char* chap276 = "And David said: Is there any think you that is remaining of the house of Saul, that I may do mercy with him for Jonathas' sake?\n"
	"And there was of the house of Saul a servant named Siba, whom when the king had called unto him, he said to him: Art thou Siba? And he answered: I am so thy servant.\n"
	"And the king said: Is there any remaining of the house of Saul, that I may do with him the mercy of God? And Siba said to the king: There is yet living a son of Jonathas, lame of his feet.\n"
	"Where is he? Quoth he. And Siba said to the king: Behold he is in the house of Machir the son of Ammiel in Lodabar.\n"
	"King David therefore sent, and took him out of the house of Machir the son of Ammiel of Lodabar.\n"
	"And when Miphiboseth the son of Jonathas the son of Saul was come to David, he fell on his face, and adored. And David said: Miphiboseth? Who answered: Here I am thy servant.\n"
	"And David said to him: Fear not, because doing I will do mercy on thee for Jonathas thy father, and I will restore the lands of Saul thy father, and thou shalt eat bread upon my table always.\n"
	"Who adoring him, said: Who am I thy servant, that thou hast respect upon a dead dog like unto me?\n"
	"The king therefore called Siba the servant of Saul, and said to him: All things whatsoever were Saul's, and all his house, I have given to thy master's son.\n"
	"Till for him therefore the land, thou and thy sons, and thy servants: and thou shalt bring in meats for thy master's son, that he may be maintained: and Miphiboseth the son of thy Lord shall eat always bread upon my table. And Siba had fifteen sons, and twenty servants.\n"
	"And Siba said to the king: As thou my lord king hast commanded thy servant, so will thy servant do: and Miphiboseth shall eat upon my table, as one of the sons of the king.\n"
	"And Miphiboseth had a little son called Micha: and all the kindred of the house of Siba served Miphiboseth.\n"
	"Moreover Miphiboseth dwelt in Jerusalem: because he did eat always of the king's table: and he was lame on both feet.";