const char* chap28 = "Isaac therefore called Jacob, and blessed him, and commanded him saying: Take not a wife of the stock of Chanaan;\n"
	"but go and make a journey into Mesopotamia of Syria; to the house of Bathuel thy mother's father, and take thee a wife thence of the daughters of Laban thine uncle.\n"
	"And God Almighty bless thee, and make thee increase, and multiply thee: that thou mayest be into multitudes of peoples.\n"
	"And give he thee the blessings of Abraham, and to thy seed after thee: that thou mayest possess the land of thy peregrination, which he promised to thy grandfather.\n"
	"And when Isaac had dismissed him, taking his journey he came to Mesopotamia of Syria to Laban, the son of Bathuel the Syrian, brother to Rebecca his mother.\n"
	"And Esau seeing that his father had blessed Jacob, and had sent him into Mesopotamia of Syria, to marry a wife thence; and that after the blessing he had commanded him, saying: Thou shalt not take a wife of the daughters of Chanaan;\n"
	"and that Jacob obeying his parents was gone into Syria:\n"
	"having trial also that his father did not willingly see the daughters of Chanaan,\n"
	"he went to Ismael, and took to wife besides them which he had before, Maheleth the daughter of Ismael Abraham's son, sister to Nabajoth.\n"
	"Therefore Jacob being departed from Bersabee, went on to Haran.\n"
	"And when he was come to a certain place, and would rest in it after sun set, he took one of the stones that lay there, and putting it under his head, slept in the same place.\n"
	"And he saw in his sleep a ladder standing upon the earth, & the top thereof touching heaven: the Angels also of God ascending & descending by it,\n"
	"and our Lord leaning upon the ladder saying to him: I am the Lord God of Abraham thy father, & the God of Isaac: the Land wherein thou sleepest, I will give to thee and to thy seed.\n"
	"And thy seed shall be as the dust of the earth: thou shalt be dilated to the West, and to the East, and to the North, and to the South: and IN THEE AND THY SEED ALL THE TRIBES OF THE EARTH SHALL BE BLESSED.\n"
	"And I will be thy keeper whither soever thou goest, and will bring thee back into this land: neither will I leave thee, till I shall have accomplished all things which I have said.\n"
	"And when Jacob was awaked out of sleep, he said: Indeed our Lord is in this place, and I wist not.\n"
	"And trembling he said: How terrible is this place! This is none other but the house of God, and the gate of heaven.\n"
	"And Jacob arising in the morning took the stone, which he had laid under his head, and erected it for a title, pouring oil upon the top.\n"
	"And he called the name of the city Bethel, which before was called Luza.\n"
	"And he vowed a vow, saying: If God shall be with me, and shall keep me in the way, by the which I walk, and shall give me bread to eat, and raiment to put on,\n"
	"and I shall be returned prosperously to my father's house, the Lord shall be my God,\n"
	"and this stone, which I have erected for a title, shall be called the House of God: and of all things that thou shalt give to me, I will offer tithes to thee.";