const char* chap287 = "It chanced also that there was there a man of Belial, named Seba, the son of Bochri, a man of Jemini: and he sounded the trumpet, and said: We have no part in David, nor inheritance in the son of Isai: Return into thy tabernacles Israel.\n"
	"And all Israel was separated from David, and followed Seba the son of Bochri: but the men of Juda struck to their king from Jordan unto Jerusalem.\n"
	"And when the king was come into his house to Jerusalem, he took the ten women his concubines, which he had left to keep the house, and he delivered them into custody, allowing them victuals: and he went not in unto them, but they were shut up until the day of their death living in widowhood. And the king said to Amasa:\n"
	"Call me together all the men of Juda against the third day, and be thou present.\n"
	"Amasa therefore went to call together Juda, and tarried beyond the time appointed which the king had assigned him.\n"
	"And David said to Abisai: Now will Seba the son of Bochri more afflict us, than Absalom: take therefore the servants of thy lord, and pursue him, lest perhaps he find fenced cities, and escape us.\n"
	"There went forth therefore with him Joab's men, Cerethi also and Phelethi: and all the strong men issued forth of Jerusalem to pursue Seba the son of Bochri.\n"
	"And when they were beside the great stone, which is in Gabaon, Amasa coming met them. Moreover Joab was clothed with a strait coat according to the measure of his stature, and upon it girded with a sword hanging down to the flank, in a scabbard, which being made for the purpose could with light moving come forth and strike.\n"
	"Joab therefore said to Amasa: God save thee my brother. And he held, with his right hand the chin of Amasa, as it were kissing him.\n"
	"But Amasa marked not the sword, which Joab had, who struck him in the side, & poured out his bowels on the ground, neither added he the second wound, and he died. And Joab, and Abisai his brother pursued Seba the son of Bochri.\n"
	"In the mean time certain men, when they stood by the carcass of Amasa, of Joab's company, said: Lo he that would have been for Joab the companion of David.\n"
	"And Amasa imbrued with blood, lay in the midst of the way. A certain man saw this, that all the people, stayed to see him, and he removed Amasa out of the way into the field, and covered him with a garment, that they which passed might not stay because of him.\n"
	"He therefore being removed out of the way, every man passed following Joab to pursue Seba the son of Bochri.\n"
	"Moreover he had passed through all the tribes of Israel unto Abela, & Bethmaaca: and all the chosen men were gathered together unto him.\n"
	"They therefore came, and assaulted him in Abela, and in Bethmaaca, & they compassed the city with munitions, & the city was besieged: and all the multitude, that was with Joab, laboured to destroy the walls.\n"
	"And a wise woman cried out from the city: Hear ye, hear ye, tell Joab: Approach hither, and I will speak with thee.\n"
	"Who when he was come to her, she said to him: Art thou Joab? And he answered, I am. To whom she spake thus: Hear the words of thy handmaid. Who answered: I do hear.\n"
	"And she again said: A saying was used in the old proverbs: They that ask, let them ask in Abela: and so they prospered.\n"
	"Am not I she that answer truth in Israel, and thou seekest to subvert the city, and to overthrow a mother city in Israel? Why throwest thou down headlong the inheritance of our Lord?\n"
	"And Joab answering, said: God forbid, God forbid that I should, I do not throw down, nor destroy.\n"
	"The matter is not so, but a man of mount Ephraim, Seba the son of Bochri by name, hath lifted up his hand against king David: Deliver him only, and we will depart from the city. And the woman said to Joab: Behold his head shall be thrown to thee off the wall.\n"
	"She therefore went to all the people, and spake to them wisely: who threw the head of Seba the son of Bochri being cut off, to Joab. And he sounded the trumpet, and they departed from the city, every one into their tabernacles: and Joab returned to Jerusalem unto the king.\n"
	"Joab therefore was over all the army of Israel: and Banaias the son of Joiada over the Ceretheites and Pheletheites.\n"
	"But Aduram over the tributes: moreover Josaphat the son of Ahilud, was register.\n"
	"And Siva, a scribe: and Sadoc and Abiathar, priests.\n"
	"And Ira the Jairite was the priest of David.";