const char* chap289 = "And David spake to our Lord the words of this song, in the day that our Lord delivered him out of the hand of all his enemies, and out of the hand of Saul.\n"
	"And he said: Our Lord is my rock, and my strength, and my Saviour.\n"
	"God is my strong one, I will hope in him: my shield, and the horn of my salvation: my lifter up, and my refuge: my Saviour, from iniquity thou wilt deliver me.\n"
	"Our Lord praise-worthy will I invocate: and from mine enemies I shall be save.\n"
	"Because the pangs of death have compassed me: the streams of Belial have terrified me.\n"
	"The ropes of hell have compassed me: the snares of death have prevented me.\n"
	"In my tribulation I will invocate our Lord, & I will cry to my God: and he will hear my voice out of his holy temple, and my cry shall come to his ears.\n"
	"The earth quaked and trembled, the foundations of the mountains were strucken, and shaken, because he was angry with them.\n"
	"A smoke arose out of his nostrils, and a fire from his mouth shall devour: coals were kindled from him.\n"
	"And he bowed the heavens, and descended: and mist under his feet.\n"
	"And he ascended upon the Cherubins, and flew: and slid over the wings of the wind.\n"
	"He put darkness round about him a cover: stilling waters out of the clouds of heaven.\n"
	"By the shining in his presence: the coals of fire were kindled.\n"
	"Our Lord will thunder from heaven: and the high one will give his voice.\n"
	"He shot his arrows and dispersed them: lightning, and consumed them.\n"
	"And the overflowings of the sea appeared, and the foundations of the world were discovered at the rebuking of our Lord, at the breathing of the spirit of his fury.\n"
	"He sent from high heaven, and took me, and drew me out of many waters.\n"
	"He delivered me from my most mighty enemy, and from them that hated me: because they were stronger than I.\n"
	"He prevented me in the day of my affliction, and our Lord became my stay.\n"
	"And he brought me forth into latitude, he delivered me, because I well pleased him.\n"
	"Our Lord will reward me according to my justice: and according to the cleanness of my hands will he render to me.\n"
	"Because I have kept the ways of our Lord, and have not done impiously, from my God.\n"
	"For all his judgments are in my sight: and his precepts I have not removed from me.\n"
	"And I shall be perfect with him; and shall keep myself from mine iniquity.\n"
	"And our Lord will restore unto me according to my justice: and according to the cleanness of my hands in the sight of his eyes.\n"
	"With the holy one thou shalt be holy: and with the strong perfect.\n"
	"With the elect thou shalt be elect: and with the perverse thou shalt be perverted.\n"
	"And the poor people thou wilt save: and the haughty in thine eyes thou wilt humble.\n"
	"Because thou art my lamp, o Lord: and thou wilt illuminate my darkness.\n"
	"For in thee I will run girded: in my God I will leap over the wall.\n"
	"God, his way immaculate, the word of our Lord is examined by fire: he is the shield of all that trust in him.\n"
	"Who is God beside our Lord: and who is strong beside our God?\n"
	"God who hath girded me with strength: and made even my perfect way.\n"
	"Making my feet equal with the Harts, and setting me upon my high places.\n"
	"Teaching my hands unto battle: and framing mine arms as it were a brazen bow.\n"
	"Thou hast given me the shield of thy salvation: and thy mildness hath multiplied me.\n"
	"Thou shalt enlarge my steps under me: and mine ankles shall not fail.\n"
	"I will pursue mine enemies, and bruise them: and will not return till I consume them.\n"
	"I will consume and break them, that they rise not: they shall fall under my feet.\n"
	"Thou hast girded me with strength to battle: thou hast bowed under me them that resist me.\n"
	"Mine enemies thou hast made to turn to me the back: them that hated me, and I shall destroy them.\n"
	"They shall cry, and there shall not be to save, to our Lord, and he will not hear them.\n"
	"I will destroy them as the dust of the earth: as the mire of the streets will I bruise and break them.\n"
	"Thou wilt save me from the contradictions of my people: thou wilt keep me to be the head of the Gentiles: the people which I know not, will serve me.\n"
	"The children aliens will resist me, with the hearing of the ear they will obey me.\n"
	"The children aliens are fallen away, and shall be straitened in their distresses.\n"
	"Our Lord liveth, and my God is blessed: and the strong God of my salvation shall be exalted.\n"
	"God which givest me revenges, and throwest down peoples under me.\n"
	"Which bringest me out from mine enemies, and from them that resist me dost lift me up: from the wicked man thou shalt deliver me.\n"
	"Therefore will I confess unto thee, o Lord, among the Gentiles, and will sing to thy name.\n"
	"Magnifying the salvations of his king, and doing mercy to his Christ David, and to his seed for ever.";