const char* chap29 = "Jacob therefore going on his journey, came into the East country.\n"
	"And he saw a well in the field, and three flocks of sheep lying beside it: for of it the beasts were watered, and the mouth thereof was closed with a great stone.\n"
	"And the manner was when all the sheep were gathered together they did roll off the stone, and after the sheep were refreshed they put it on the mouth of the well again.\n"
	"And he said to the shepherds: Brethren, whence are you? Who answered: Of Haran.\n"
	"And he asked them, saying: Know you Laban the son of Nachor? They said: We do know him.\n"
	"Is he in health? Quoth he: He is in health, say they: And behold Rachel his daughter cometh with his flock.\n"
	"And Jacob said: There is yet much day remaining, neither is it time to bring the flocks into the folds again: first give the sheep drink, and so bring them back to feed.\n"
	"Who answered: we cannot, till all the cattle be gathered together: and we remove the stone from the well's mouth, that we may water the flocks.\n"
	"They were yet speaking, and behold Rachel came with her father's sheep: for she fed the flock.\n"
	"Whom when Jacob had seen, & knew her to be his cousin-german, & that they were the sheep of Laban his uncle, he removed the stone, wherewith the well was closed.\n"
	"And having watered the flock, he kissed her: and lifted up his voice wept,\n"
	"and he told her that he was her father's brother, and the son of Rebecca: but she in haste went & told her father.\n"
	"Who when he heard that Jacob his sister's son was come, he ran forth to meet him, & embracing him & heartily kissing him, brought him into his house. And when he had heard the causes of his journey,\n"
	"he answered: Thou art my bone and my flesh. And after the days of one month were expired,\n"
	"he said to him: because thou art my brother, shalt thou serve me gratis? Tell me, what wages wilt thou take?\n"
	"He had indeed two daughters, the name of the elder was Lia; & the younger was called Rachel.\n"
	"But Lia was blear-eyed, Rachel well favoured, & of a beautiful countenance.\n"
	"Whom Jacob loving, said: I will serve thee for Rachel thy younger daughter seven years.\n"
	"Laban answered: It is better that I give her to thee than to another man, tarry with me.\n"
	"Jacob therefore served for Rachel seven years: and they seemed a few days because of the greatness of his love.\n"
	"And he said to Laban: give me my wife: because now the time is complete, that I may company with her.\n"
	"Who having bid a great number of his friends to the feast, made the marriage.\n"
	"And at night he brought in Lia his daughter to him,\n"
	"giving his daughter a handmaid, named Zelpha. With whom when Jacob had companied after the manner, when morning was come he saw Lia:\n"
	"and he said to his father in law: What is it that thou didst mean to do? Did not I serve thee for Rachel? Why hast thou deceived me?\n"
	"Laban answered: It is not the custom in this place, that we bestow the younger in marriage first.\n"
	"Make up the week of days of this match: and I will give thee this same also, for the work that thou shalt serve me other seven years.\n"
	"He yielded to his pleasure; and after the week was past, he married Rachel to wife:\n"
	"to whom her father had delivered Bala for to be her servant.\n"
	"And having at length obtained the marriage that he wished, he preferred the love of the later before the former, serving with him other seven years.\n"
	"And our Lord seeing that he despised Lia opened her womb, her sister remaining barren.\n"
	"Who conceived and bare a son, and called his name Ruben, saying: Our Lord saw mine affliction: now my husband will love me.\n"
	"And again she conceived and bare a son, and said: For because our Lord heard that I was contemned, he hath given this also to me: and she called his name Simeon.\n"
	"And she conceived the third time, and bare another son: and said: Now also my husband will be joined to me, for because I have born him three sons: and therefore she called his name, Levi.\n"
	"The fourth time she conceived and bare a son, and said: Now will I confess to our Lord. And for this she called him Juda: And she left bearing.";