const char* chap292 = "And king David was old, and had many days of age: & when he was covered with cloths, he was not warmed.\n"
	"His servants therefore said to him: Let us seek for our lord the king a young woman a virgin, and let her stand before the king, and cherish him, and sleep in his bosom, and warm our lord the king.\n"
	"They sought therefore a beautiful young woman in all the coasts of Israel, and they found Abisag a Sunamite, & brought her to the king.\n"
	"And the damsel was exceeding beautiful, and she slept with the king, and served him, but the king did not know her.\n"
	"And Adonias the son of Haggith was elevated, saying: I will reign. And he made himself chariots & horsemen, & fifty men, that should run before him.\n"
	"Neither did his father control him at any time, saying: Why didst thou this? And he also was very beautiful, the second born after Absalom.\n"
	"And he had talk with Joab the son of Sarvia, and with Abiathar the priest, who furthered Adonias' side.\n"
	"But Sadoc the Priest, and Banaias the son of Joiada, and Nathan the Prophet, and Semei, and Rei, and the strength of David's army was not with Adonias.\n"
	"Adonias therefore having immolated rams and calves, and all fat beasts beside the Stone zoheleth, which was nigh to the Fountain Rogel, called all his brethren the sons of the king, and all the men of Juda the servants of the king:\n"
	"But Nathan the Prophet, and Banaias, and all the strong ones, and Salomon his brother he called not.\n"
	"Nathan therefore said to Bethsabee the mother of Salomon: Hast thou not heard that Adonias the son of Haggith hath reigned, & our lord David is ignorant thereof?\n"
	"Now therefore come, take counsel of me, & save thy life, & thy son Salomon's.\n"
	"Go, & enter in to king David, & say to him: Didst not thou my lord king swear to me thy handmaid, saying: Salomon thy son shall reign after me, and he shall sit in my throne? Why then reigneth Adonias?\n"
	"And whiles thou art yet speaking there with the king, I will come after thee, & make up thy words.\n"
	"Bethsabee therefore went in to the king in the chamber: and the king was exceeding old, and Abisag the Sunamite ministered to him.\n"
	"Bethsabee bowed herself, and adored the king. To whom the king said: What is thy will? Quoth he.\n"
	"Who answering said: My lord, thou didst swear to thy handmaid by our Lord thy God, that Salomon thy son shall reign after me, and he shall sit in my throne.\n"
	"And behold now Adonias reigneth, thou my lord the king not knowing thereof.\n"
	"He hath killed oxen, and all fat things, and many rams, and called all the king's sons. Abiathar also the Priest, and Joab the General of the warfare: but Salomon thy servant he called not.\n"
	"Notwithstanding my lord king, the eyes of all Israel look upon thee, that thou wouldest shew them, who shall sit in thy throne my lord king after thee.\n"
	"And it shall be when my lord king sleepeth with his fathers, I & my son Salomon shall be sinners.\n"
	"As she was yet speaking with the king, Nathan the Prophet came.\n"
	"And they told the king, saying: Nathan the Prophet is here. And when he was gone in to the king, and had adored bowing to the earth,\n"
	"Nathan said: My lord king, didst thou say: Let Adonias reign after me, and let him sit upon my throne?\n"
	"Because he is gone down today, and hath immolated oxen, and fatlings, and many rams, and called all the king's sons, and the captains of the army, Abiathar also the Priest: and they eating and drinking before him, and saying: God save the king Adonias:\n"
	"me thy servant, and Sadoc the Priest, and Banaias the son of Joiada, and Salomon thy servant he called not.\n"
	"Is this word proceeding from my lord the king, and hast thou not told me thy servant who should sit upon the throne of my lord the king after him?\n"
	"And king David answered, saying: Call unto me Bethsabee. Who when she was entered in to the king, and stood before him,\n"
	"the king sware, and said: Our Lord liveth, which hath delivered my soul from all distress,\n"
	"that as I sware to thee by our Lord the God of Israel, saying: Salomon thy son shall reign after me, and he shall sit upon my throne for me, so will I do this day.\n"
	"And Bethsabee bowing her countenance unto the earth adored the king, saying: God save my lord for ever.\n"
	"King David also said: Call me Sadoc the priest, and Nathan the prophet, & Banaias the son of Joiada. Who when they were entered in before the king,\n"
	"he said to them: Take with you the servants of your lord, and set Salomon my son upon my mule: and bring him into Gihon.\n"
	"And let Sadoc the priest anoint him there, and Nathan the prophet to be king over Israel: and you shall sound the trumpet, and shall say: God save king Salomon.\n"
	"And you shall go up after him, and he shall come, and shall sit upon my throne, and he shall reign for me: and I will ordain him that he be Prince over Israel, and over Juda.\n"
	"And Banaias the son of Joiada answered the king, saying: Amen: so speak our Lord the God of my lord the king.\n"
	"As our Lord hath been with my lord the king, so be he with Salomon, and make his throne higher than the throne of my lord king David.\n"
	"Sadoc therefore the Priest, and Nathan the Prophet went down, and Banaias the son of Joiada, and Cerethi, and Phelethi: and they set Salomon upon the mule of king David, and brought him into Gihon.\n"
	"And Sadoc the priest took a horn of oil out of the tabernacle, and anointed Salomon: and they sounded the trumpet, and all the people said: God save king Salomon.\n"
	"And all the multitude went up after him, and the people singing on shalms, and rejoicing with great gladness, and the earth sounded of their cry.\n"
	"And Adonias heard, and all that were invited of him, and the feast was ended: yea & Joab hearing the voice of the trumpet, said: What meaneth the cry of the city making a tumult?\n"
	"As he yet spake, came Jonathas the son of Abiathar the Priest: to whom Adonias said: Come in, because thou art a stout man, and bringest good news.\n"
	"And Jonathas answered Adonias: Not so: for our lord king David hath appointed Salomon king,\n"
	"and hath sent with him Sadoc the Priest, and Nathan the Prophet, and Banaias the son of Joiada, and Cerethi, and Phelethi, and they have set him upon the king's mule.\n"
	"And Sadoc the Priest, and Nathan the Prophet have anointed him king in Gihon: & they are gone up thence rejoicing, and the city sounded: this is the voice that you heard.\n"
	"Yea and Salomon sitteth upon the throne of the Kingdom.\n"
	"And the king's servants entering in, have blessed our lord king David, saying: God amplify the name of Salomon above thy name, and magnify his throne above thy throne. And the king adored in his bed:\n"
	"and he hath thus spoken: Blessed be our Lord the God of Israel, who hath given this day one sitting in my throne, mine eyes seeing it.\n"
	"They therefore were terrified, and they all arose, that had been invited of Adonias, and every man went his way.\n"
	"And Adonias fearing Salomon arose, & went, & held the horn of the altar.\n"
	"And they told Salomon, saying: Behold Adonias fearing king Salomon, hath taken hold of the horn of the altar, saying: Let king Salomon swear to me this day, that he will not kill his servant with the sword.\n"
	"And Salomon said: If he be a good man, there shall not so much as one hair of his^ fall upon the ground: but if evil shall be found in him, he shall die.\n"
	"King Salomon therefore sent, and brought him out from the altar: and going in he adored king Salomon: and Salomon said to him: Go to thy house.";