const char* chap293 = "And the days of David approached that he should die, and he commanded his son Salomon, saying:\n"
	"I enter into the way of all flesh: take courage, and play the man.\n"
	"And observe the watches of our Lord thy God, that thou walk in his ways, and keep his ceremonies, and his precepts & judgments, and testimonies as is written in the law of Moyses: that thou mayst understand all things which thou doest, and whithersoever thou shalt turn thyself:\n"
	"that our Lord may confirm his words, which he hath spoken of me, saying: If thy children shall keep their ways, and shall walk before me in truth, in all their heart, and in all their soul, there shall not altogether be taken from thee a man out of the throne of Israel.\n"
	"Thou knowest also what Joab the son of Sarvia hath done to me, what he did to the two Princes of the army of Israel, to Abner the son of Ner, & Amasa the son of Jether: whom he slew, & shed the blood of war in peace, and put the blood of battle in his belt, which was about his loins, and in his shoe, which was on his feet.\n"
	"Thou shalt do therefore according to thy wisdom, and shalt not bring his hoar head peaceably unto hell.\n"
	"But to the sons also of Berzellai the Galaadite thou shalt render kindness, and they shall eat on thy table: for they met me when I fled from the face of Absalom thy brother.\n"
	"Thou shalt also with thee Semei the son of Gera the son of Jemini of Bahurim, who cursed me with a wicked curse, when I went to the Camp; but because he came down to meet me when I passed Jordan, and I sware to him by our Lord, saying: I will not kill thee with the sword;\n"
	"do not thou suffer him to be guiltless. But thou art a wise man, so that thou knowest what thou shalt do to him, and thou shalt bring his hoar hair with blood unto hell.\n"
	"David therefore slept with his fathers, & was buried in the city of David.\n"
	"And the days that David reigned in Israel, are forty years: in Hebron he reigned seven years, in Jerusalem thirty three.\n"
	"And Salomon sat upon the throne of David his father, & his Kingdom was confirmed exceedingly.\n"
	"And Adonias the son of Haggith entered in to Bethsabee the mother of Salomon. Who said to him: Is thy coming peaceable? Who answered: Peaceable.\n"
	"And he added: I have a word to speak with thee. To whom she said: Speak. And he:\n"
	"Thou knowest, quoth he, that the kingdom was mine, & all Israel had purposed to make me over them to be their king: but the kingdom is transposed, & is made my brother's: for it was appointed him of our Lord.\n"
	"Now therefore I desire one petition of thee; Confound not my face. Who said to him: Speak.\n"
	"And he said: I pray^ speak to Salomon the king (for he cannot deny thee any thing) that he give me Abisag the Sunamite to wife.\n"
	"And Bethsabee said: Well, I will speak for thee to the king.\n"
	"Bethsabee therefore came to king Salomon, to spake unto him for Adonias: & the king arose to meet her, & adored her, & sat down upon his throne: & a throne was set for the king's mother, who sat on his right hand.\n"
	"And she said to him: One little petition I desire of thee, confound not my face. And the king said to her: My mother ask: for it behoveth not that I turn away thy face.\n"
	"Who said: Let Abisag the Sunamite be given to Adonias thy brother to wife.\n"
	"And king Salomon answered, and said to his mother: Why doest thou ask Abisag the Sunamite for Adonias? Ask for him also the Kingdom: for he is my brother elder than I, & hath Abiathar the priest, & Joab the son of Sarvia.\n"
	"Therefore king Salomon sware by our Lord, saying: These things do God to me, & these add he, because Adonias hath spoken this word against his life.\n"
	"And now, our Lord liveth which hath established me, & placed me upon the throne of David my father, and which hath made me a house, as he spake, this day shall Adonias be slain.\n"
	"And king Salomon sent by the hand of Banaias the son of Joiada, who slew him, & he died.\n"
	"To Abiathar also the priest the king said: Go into Anathoth to thy field, and thou indeed art a man of death: but today I will not kill thee, because thou didst carry the ark of our Lord God before David my father, & hast sustained labour in all things, wherein my father laboured.\n"
	"Salomon therefore cast out Abiathar, that he should not be the priest of our Lord, that the word of our Lord might be fulfilled, which he spake concerning the house of Heli in Silo.\n"
	"And then a messenger came to Joab, for that Joab had turned after Adonias, and after Salomon had not turned: Joab therefore fled into the tabernacle of our Lord, & caught the horn of the altar.\n"
	"And it was told king Salomon, that Joab was fled into the tabernacle of our Lord, and was beside the altar: and Salomon sent Banaias the son of Joiada, saying: Go, kill him\n"
	"And Banaias came to the tabernacle of our Lord, and said to him: Thus saith the king: Come forth. Who said: I will not come forth, but here will I die. Banaias reported his word to the king, saying: Thus spake Joab, and thus he answered me.\n"
	"And the king said to him: Do as he hath spoken: and kill him, and bury him, and thou shalt remove the innocent blood, which hath been shed of Joab, from me, and from the house of my father.\n"
	"And our Lord shall render his blood upon his head, because he murdered two just men, and better than himself: and slew them with his sword, my father David not knowing, Abner the son of Ner^ general of the warfare of Israel, and Amasa the son of Jether general of the army of Juda:\n"
	"and their blood shall return upon the head of Joab, and upon the head of his seed for ever. But to David & his seed & his house, & to his throne be peace for ever from our Lord.\n"
	"Banaias therefore the son of Joiada went up, and setting upon him slew him: and he was buried in his house in the desert.\n"
	"And the king appointed Banaias the son of Joiada for him over the army, and Sadoc the priest he placed for Abiathar.\n"
	"The king also sent, and called Semei, and said to him: Build thee a house in Jerusalem, and dwell there: and thou shalt not go out thence hither and thither.\n"
	"But what day soever thou shalt go out, and shalt pass the Torrent Cedron, know that thou art to be slain: thy blood shall be upon thy head.\n"
	"And Semei said to the king: The saying is good: as my lord the king hath spoken, so will thy servant do. Semei therefore dwelt in Jerusalem many days.\n"
	"And it came to pass after three years, that the servants of Semei fled to Achis the son of Maacha the king of Geth: and it was told Semei that his servants were gone into Geth.\n"
	"And Semei arose, and saddled his ass, & went to Achis into Geth to require his servants, & he brought them out of Geth.\n"
	"And it was told Salomon that Semei went into Geth out of Jerusalem, & was returned.\n"
	"And sending he called him, & said to him: Did I not testify to thee by our Lord, & told thee before: What day soever thou going out shalt pass hither and thither, know that thou shalt die? And thou didst answer me: The saying is good, which I have heard.\n"
	"Why then hast thou not kept the oath of our Lord, and the precept that I commanded thee?\n"
	"And the king said to Semei: Thou knowest all the evil, whereof thy heart is privy to thyself, which thou didst to David my father: our Lord hath rendered thy malice upon thy head.\n"
	"And king Salomon be blessed, and the throne of David shall be stable before our Lord for ever.\n"
	"The king therefore commanded Banaias the son of Joiada: who going out, struck him, and he died.";