const char* chap30 = "And Rachel seeing she was unfruitful, envied her sister, and said to her husband: Give me children, otherwise I shall die.\n"
	"With whom Jacob being angry answered: Am I as God, who hath deprived thee of the fruit of thy womb?\n"
	"But she said: I have here my servant Bala: Company with her, that she may bear upon my knees, and I may have children of her.\n"
	"And she gave him Bala unto marriage: who,\n"
	"When her husband had companied with her, conceived and bare a son.\n"
	"And Rachel said: Our Lord hath judged for me and hath heard my voice, giving me a son, and therefore she called his name, Dan.\n"
	"And again Bala conceiving bare another,\n"
	"for whom Rachel said: God hath compared me with my sister, and I have prevailed: and she called him Nephthali.\n"
	"Lia perceiving that she had left bearing, delivered Zelpha her handmaid to her husband.\n"
	"Who conceiving and bringing forth a son,\n"
	"she said: Happily. And therefore called his name Gad.\n"
	"Zelpha also bare another.\n"
	"And Lia said: This is for my blessedness: for women will call me blessed. Therefore she called him Aser.\n"
	"And Ruben, going forth in the time of wheat harvest into the field, found mandragoras: which he brought to his mother Lia. And Rachel said: Give me part of thy son's mandragoras.\n"
	"She answered: Dost thou think it a small matter that thou hast taken my husband from me, unless thou take also my son's mandragoras? Rachel said: For thy son's mandragoras let him sleep with thee this night.\n"
	"And when Jacob returned at even from the field, Lia went out to meet him, and said: Company with me, because with wages I have hired thee for my son's mandragoras. And he slept with her that night.\n"
	"And God heard her prayers: and she conceived and bare the fifth son,\n"
	"And said: God hath given me a reward, because I gave my handmaid to my husband. And she called his name Issachar.\n"
	"Again Lia conceiving, bare the sixth son,\n"
	"& said: God hath endowed me with a good dowry: this turn also my husband will be with me, for because I have born him six sons, and therefore she called his name, Zabulon.\n"
	"After whom she bare a daughter named Dina.\n"
	"Our Lord also remembering Rachel heard her, and opened her womb.\n"
	"Who conceived and bare a son, saying: God hath taken away my reproach.\n"
	"And she called his name, Joseph, saying: Our Lord add to me another son.\n"
	"And when Joseph was born, Jacob said to his father in law: Dismiss me that I may return into my country, and to my land.\n"
	"Give me my wives, and my children, for whom I have served thee, that I may depart: thou knowest the service that I have served thee.\n"
	"Laban said to him: Let me find grace in thy sight: I have learned by experience that God hath blessed me for thy sake:\n"
	"appoint thee wages which I shall give thee.\n"
	"But he answered: Thou knowest how I have served thee, and how great thy possession hath been in my hands.\n"
	"Thou hadest a small thing before I came to thee, and now thou art made rich: and our Lord hath blessed thee at my coming in. It is reason therefore that once I provide also for mine own house.\n"
	"And Laban said: What shall I give thee? But he said: I will nothing: but if thou wilt do that which I demand, I will feed and keep thy sheep again.\n"
	"Go round about all the flocks, and separate all the sheep of diverse colours, of speckled fleece: and what-soever shall be russet and spotted, and of diverse colours, as well in the sheep as in the goats, shall be my wages.\n"
	"And my justice shall answer for me tomorrow before thee, when the time of the bargain shall come: and all that shall not be of diverse colours, and spotted, and russet, as well in the sheep as in the goats, shall accuse me of theft.\n"
	"And Laban said: I like well that thou demandest.\n"
	"And he separated the same day the she goats, and the sheep, and the he goats, and the rams of diverse colours, and spotted: and all the flock of one colour, that is of white and black fleece, he delivered in the hand of his sons.\n"
	"And he put a space of three days' journey betwixt him and his son in law, who fed the rest of his flock.\n"
	"Jacob therefore taking green rods of the poplar, and of the almond, and of the plane-trees, in part pilled them: and when the barks were taken off, in the parts that were pilled there appeared whiteness: but the parts that were whole remained green: and by this means the colour was made diverse.\n"
	"And he put them in the troughs, where the water was poured out: that when the flocks should come to drink, thy might have the rods before their eyes, and in the sight of them conceive.\n"
	"And it came to pass that in the very heat of the ramming, the sheep beheld the rods, and brought forth spotted, and of diverse colours, and speckled.\n"
	"And Jacob divided the flock, and put the rods in the troughs before the eyes of the rams: and all the white and the black were Laban's, and the rest, Jacob's, when the flocks were separated one from the other.\n"
	"Therefore when the ewes went to ram, in the prime time Jacob put the rods in the troughs of water before the eyes of the rams, and of the ewes, that in looking upon them they might conceive:\n"
	"but when the later coming was, and the last conceiving, he did not put them. And those that were lateward became Laban's: and they of the prime time, Jacobs.\n"
	"And the man was enriched beyond measure, and he had many flock, women servants and men servants, camels and asses.";