const char* chap300 = "And it came to pass when Salomon had perfected the building of the house of our Lord, & the king's house, and all that he wished & would have done,\n"
	"our Lord appeared to him the second time, as he had appeared to him in Gabaon.\n"
	"And our Lord said to him: I have heard thy prayer & thy petition which thou hast prayed before me: I have sanctified this house, which thou hast built, that I might put my name there for ever, and mine eyes and my heart shall be there always.\n"
	"Thou also if thou wilt walk before me, as thy father walked, in simplicity of heart, and in equity, and wilt do all things, which I have commanded thee, and wilt keep my ordinances and my judgments:\n"
	"I will set the throne of thy Kingdom over Israel for ever, as I have spoken to David thy father, saying: There shall not be taken away a man of thy stock from the throne of Israel.\n"
	"But if by revolting you and your children shall turn away, not following me, nor keeping my commandments, and my ceremonies, which I have proposed to you, but shall go and worship strange gods, and adore them:\n"
	"I will take away Israel from the face of the land, which I have given them, and the temple which I have sanctified to my name, I will cast away from my sight, and Israel shall be for a proverb, and for a fable to all peoples.\n"
	"And this house shall be for an example: every one that shall pass by it, shall wonder, and hiss, and say: Why hath the Lord done thus to this land, and to this house?\n"
	"And they shall answer: Because they have forsaken the Lord their God, which brought their fathers out of the Land of Aegypt, and have followed strange gods, and adored them, and worshipped them: therefore hath the Lord brought upon them all this evil.\n"
	"And twenty years being complete, after that Salomon had built the two houses, that is, the house of our Lord, and the house of the king,\n"
	"(Hiram the king of Tyre ministering to Salomon cedar trees & fir trees, and gold according to all that he had need) then Salomon gave to Hiram twenty towns in the Land of Galilee.\n"
	"And Hiram went from Tyre, to see the towns which Salomon had given him, and they pleased him not,\n"
	"and he said: Are these the cities, which thou hast given me, brother? And he called them the land Chabul, until this day.\n"
	"Hiram also sent to king Salomon an hundred and twenty talents of gold.\n"
	"This is the sum of the expenses, which king Salomon offered to build the house of our Lord, and his own house, and Mello, and the wall of Jerusalem, and Heser, and Mageddo, and Gazer.\n"
	"Pharao the king of Aegypt came up and took Gazer, and burnt it with fire: And the Chananite, that dwelt in the city, he slew, and gave it for a dowry to his daughter the wife of Salomon.\n"
	"Salomon therefore built Gazer, and Bethhoron the lower,\n"
	"and Balaath, and Palmira in the Land of the wilderness.\n"
	"And all the villages, that pertained to him, and were without wall, he fenced, and the cities of the chariots, and the cities of the horsemen, and whatsoever pleased him to build in Jerusalem, and in Libanus, and in all the land of his dominion.\n"
	"All the people, that was remaining of the Amorrheites, and Hetheites, and Pherezites, and Heveites, and Jebusites, that are not of the children of Israel:\n"
	"their children, that were remaining in the land, to wit, those whom the children of Israel could not abolish: Salomon made tributaries, until this day.\n"
	"But of the children of Israel Salomon appointed not any man to serve, but they were men of war, and his servants, and Princes, and captains, and overseers of the chariots and horses.\n"
	"And there were Princes over all the works of Salomon, made overseers, five hundred fifty, which had the people subject, and commanded over their appointed works.\n"
	"And the daughter of Pharao went up out of the city of David into her house, which Salomon had built her: then did he build Mello.\n"
	"Salomon also offered three times every year holocausts, and pacific victims upon the altar, which he had built to our Lord, and he burnt incense before our Lord: and the temple was perfected.\n"
	"King Salomon also made a navy in Asiongaber, which is beside Ailath in the shore of the Redsea in the Land of Idumea.\n"
	"And Hiram sent in that navy his men, that were mariners & skillful of the sea, with the servants of Salomon.\n"
	"Who when they were come into Ophir, the gold taken thence of four hundred and twenty talents, they brought to king Salomon.";