const char* chap302 = "And king Salomon loved many women strangers, the daughter also of Pharao, and Moabites, & Ammonites, Idumeians, and Sidonians, & Hetheians:\n"
	"of the nations, whereof our Lord said to the children of Israel: You shall not go in unto them, neither shall any of them come in unto yours: for they will most certainly turn away your hearts to follow their gods. To these therefore was Salomon coupled in most fervent love.\n"
	"And he had wives as it were queens seven hundred, and concubines three hundred: and the women turned away his heart.\n"
	"And when he was now old, his heart was depraved by women, that he followed strange gods: neither was his heart perfect with our Lord his God, as the heart of David his father.\n"
	"But Salomon worshipped Astarthee the goddess of the Sidonians, and Moloch the idol of the Ammonites.\n"
	"And Salomon did that which was not liked before our Lord, and he accomplished not to follow our Lord, as David his father.\n"
	"Then built Salomon a temple to Chamos the idol of Moab, in the mount that is against Jerusalem, and to Moloch the idol of the children of Ammon.\n"
	"And in this manner did he to all his wives that were strangers, which burnt frankincense, & immolated to their gods.\n"
	"Therefore our Lord was wrath with Salomon, because his mind was turned away from our Lord the God of Israel, who had appeared unto him the second time,\n"
	"and had commanded him concerning this word, that he should not follow strange gods, & he kept not the things which our Lord commanded him.\n"
	"Our Lord therefore said to Salomon: Because thou hast done this, and hast not kept my covenant, and my precepts, which I have commanded thee, breaking I will rent asunder thy Kingdom, and will give it to thy servant.\n"
	"Nevertheless in thy days I will not do it because of David thy father: out of the hand of thy son I will rent it,\n"
	"neither will I take away the whole Kingdom, but one tribe I will give to thy son for David my servant, and Jerusalem, which I have chosen.\n"
	"And our Lord raised up an adversary to Salomon, Adad an Idumeite of the king's seed, who was in Edom.\n"
	"For when David was in Idumea, and Joab the general of the warfare was gone up to bury them that were slain, and had slain all male kind in Idumea,\n"
	"for Joab tarried there six months, and all Israel, till he slew all male kind in Idumea.\n"
	"Adad himself fled, & the men of Idumea of his father's servants with him, to go into Aegypt: and Adad was a little boy.\n"
	"And when they rose out of Madian, they came into Pharan, and they took with them men of Pharan, and entered into Aegypt to Pharao the king of Aegypt: who gave him a house, and appointed him meats, and assigned him land.\n"
	"And Adad found grace before Pharao exceedingly, in so much that he gave him to wife the german sister of his wife Taphnes the queen.\n"
	"And the sister of Taphnes bare him a son Genubath, and Taphnes brought him up in the house of Pharao: & Genubath was dwelling at Pharao’s house with his children.\n"
	"And when Adad in Aegypt had heard, that David slept with his fathers, and that Joab the general of the warfare was dead, he said to Pharao: Dismiss me, that I may go into my country.\n"
	"And Pharao said to him: For what lackest thou with me: that thou seekest to go into thine own country? But he answered: Nothing: yet I beseech thee that thou dismiss me.\n"
	"God also raised up to him an adversary, Razon the son of Eliada, who had fled Adarezer the king of Soba his Lord:\n"
	"and he gathered men against him, and he became the captain of thieves, when David killed them: and they went to Damascus, and dwelt there, and they made him king in Damascus,\n"
	"and he was an adversary to Israel all the days of Salomon: and this is the evil of Adad, and hatred against Israel, and he reigned in Syria.\n"
	"Jeroboam also the son of Nabath, an Ephratheite of Sareda, the servant of Salomon, whose mother was called Serva, a woman widow, lifted up his hand against the king.\n"
	"And this is the cause of his rebellion against him, because Salomon built Mello, and filled up the breach of the city of David his father.\n"
	"And Jeroboam was a strong man and mighty: and Salomon seeing the young man of a good wit and industrious, had made him chief over the tributes of all the house of Joseph.\n"
	"It came to pass therefore at that time, that Jeroboam went out of Jerusalem, and the Prophet Ahias the Silonite found him in the way, covered with a new cloak: and they two only were in the field.\n"
	"And Ahias taking his new cloak, wherewith he was covered, cut it into twelve parts.\n"
	"And he said to Jeroboam: Take unto thee ten pieces: for thus saith our Lord the God of Israel: Behold I will rent the Kingdom out of the hand of Salomon, and will give thee ten tribes.\n"
	"But one tribe shall remain to him for my servant David, and Jerusalem the city, which I have chosen of all the tribes of Israel:\n"
	"because he hath forsaken me, and hath adored Astarthee the goddess of the Sidonians, and Chamos the god of Moab, and Moloch the god of the children of Ammon: and hath not walked in my ways, to do justice before me, and my precepts, and judgments, as David his father.\n"
	"Neither will I take away all the Kingdom out of his hand, but I will make him Prince all the days of his life, for David my servant, whom I chose, who kept my commandments & my precepts.\n"
	"But I will take away the Kingdom out of his son's hand, and will give thee ten tribes:\n"
	"and to his son I will give one tribe, that there may remain a lamp to David my servant at all times before me in Jerusalem, the city which I have chosen, that my name might be there.\n"
	"And thee will I take, and thou shalt reign over all things, that thy soul desireth, and thou shalt be king over Israel.\n"
	"If therefore thou wilt hear all things, that I shall command thee, and wilt walk in my ways, and do that which is right before me, keeping my commandments and my precepts, as David my servant did: I will be with thee, and will build thee a faithful house, as I built a house to David, and I will deliver Israel to thee:\n"
	"and I will afflict the seed of David upon this, but yet not always.\n"
	"Salomon therefore would have killed Jeroboam: who arose, and fled into Aegypt to Sesac the king of Aegypt, and was in Aegypt until the death of Salomon.\n"
	"And the rest of the words of Salomon, and all that he did, and his wisdom: behold they are all written in the Book of the words of the days of Salomon.\n"
	"And the days that Salomon reigned in Jerusalem over all Israel, are forty years.\n"
	"And Salomon slept with his fathers, and was buried in the city of David his father, & Roboam his son reigned for him.";