const char* chap308 = "And Elias the Thesbite of the inhabiters of Galaad said to Achab: Our Lord liveth the God of Israel, in whose sight I stand, if there shall be these years dew and rain, but according to the words of my mouth.\n"
	"And the word of our Lord came to him, saying:\n"
	"Depart from hence, and go against the East, and be hid in the Torrent Carith, which is against Jordan,\n"
	"and there thou shalt drink of the torrent: and I have commanded the ravens that they feed thee there.\n"
	"He therefore went, and did according to the word of our Lord: and when he was gone, he sat in the Torrent Carith, which is against Jordan.\n"
	"The ravens also brought him bread and flesh in the morning, in like manner bread and flesh in the evening, and he drank of the torrent.\n"
	"But after certain days the torrent was dried: for it had not rained upon the earth.\n"
	"Therefore the word of our Lord came to him, saying:\n"
	"Arise, and go into Sareptha of the Sidonians, and thou shalt tarry there: for I have commanded a widow woman there to feed thee.\n"
	"He arose and went into Sareptha. And when he was come to the gate of the city, the widow woman appeared to him gathering sticks, and he called her, and said to her: Give me a little water in a vessel, that I may drink.\n"
	"And when she went to fetch it, he cried after her saying: Bring me also, I beseech thee, a morsel of bread in thy hand.\n"
	"who answered: Our Lord thy God liveth, I have no bread, but so much meal in a pot as a hand can hold, and a little oil in a vessel: behold I gather two sticks, that I may go in, and dress it for me & my son, that we may eat, and die.\n"
	"To whom Elias said: fear not, but go, and do as thou hast said: but first make for me of the same meal a little hearth cake, & bring it to me: & for thyself & thy son thou shalt make afterward.\n"
	"For thus saith our Lord the God of Israel: The pot of meal shall not fail, nor the vessel of oil be diminished until the day, wherein our Lord will give rain upon the face of the earth.\n"
	"Who went and did according to the word of Elias: and he did eat, and she, and her house: and from that day\n"
	"the pot of meal failed not, and the vessel of oil was not diminished, according to the word of our Lord, which he spake in the hand of Elias.\n"
	"And it came to pass after these things, the son of the woman, the good wife of the house, fell sick, & the sickness was very vehement, so that there remained no breath in him,\n"
	"She therefore said to Elias: what is to me and thee thou man of God? Comest thou unto me, that mine iniquities might be remembered, and thou mightest kill my son?\n"
	"And Elias said to her: Give me thy son. And he took him from her bosom, and carried him into the upper chamber where himself abode, and laid him upon his bed.\n"
	"And he cried to our Lord, and said: O Lord my God, what, the widow also with whom I am after a sort sustained, hast thou afflicted, that thou wouldest kill her son?\n"
	"And he stretched forth, and measured himself upon the child three times, and he cried to our Lord, and said: O Lord my God, let the soul of this child, I beseech thee, return into his body.\n"
	"And our Lord heard the voice of Elias: and the soul of the child returned into him, and he revived.\n"
	"And Elias took the child, and brought him down from the upper chamber into the lower house, and delivered him to his mother, and said to her: Behold thy son liveth.\n"
	"And the woman said to Elias: Now, in this I have known that thou art a man of God, and the word of our Lord in thy mouth is true.";