const char* chap319 = "And the children of the Prophets said to Eliseus: Behold the place, wherein we dwell before thee is strait for us.\n"
	"Let us go as far as Jordan, and take out of the wood every man some timber, that we may build there a place to dwell in. Who said: Go.\n"
	"And one of them said: Come therefore thou also with thy servants. He answered: I will come.\n"
	"And he went with them. And when they were come to Jordan they cut wood.\n"
	"And it chanced, that when one had cut down timber, the head of the axe fell into the water: and he cried out, and said: Alas alas alas my Lord, this same also I did borrow.\n"
	"And the man of God said: where fell it? And he shewed him the place: he therefore cut off a piece of wood, and cast it thither: and the iron did swim,\n"
	"and he said: Take it up. Who stretched forth his hand, & took it.\n"
	"And the king of Syria fought against Israel, & took counsel with his servants, saying: In that and that place let us lay embushments.\n"
	"Therefore the man of God sent to the king of Israel, saying: Beware thou pass not into such a place: because the Syrians are there in embushments.\n"
	"The king of Israel therefore sent to the place, which the man of God had told him, and prevented him, and looked well to himself there not once or twice.\n"
	"And the heart of the king of Syria was troubled for this thing. And calling together his servants, he said: Why do you not tell me who is the betrayer of me to the king of Israel?\n"
	"And one of his servants said: Not so my lord king, but Eliseus the prophet, which is in Israel, telleth the king of Israel all words, whatsoever thou shalt speak in thy privy chamber.\n"
	"And he said to them: Go, and see where he is: that I may send, and take him. And they told him, saying: Behold in Dothan.\n"
	"He therefore sent thither horses and chariots, and the force of his army: who when they were come in the night, they beset the city.\n"
	"And the servant of the man of God rising early, went out, and saw an army round about the city, and horses and chariots: & he told him, saying: Alas alas alas my lord, what shall we do.\n"
	"But he answered: Fear not: for there are more with us than with them.\n"
	"And when Eliseus had prayed, he said: Lord open the eyes of this man, that he may see. And our Lord opened the eyes of the servant, and he beheld: and lo the mountain full of horses, and of fiery chariots round about Eliseus.\n"
	"But the enemies went down to him: moreover Eliseus prayed to our Lord, saying: Strike, I beseech thee, this people with blindness. And our Lord smote them, that they saw not, according to the word of Eliseus.\n"
	"And Eliseus said to them: This is not the way, neither is this the city: follow me, and I will shew you the man, whom you seek. He therefore led them into Samaria:\n"
	"and when they were entered into Samaria, Eliseus said: Lord open the eyes of these men, that they may see. And our Lord opened their eyes, and they saw themselves to be in the midst of Samaria.\n"
	"And the king of Israel said to Eliseus, when he had seen them: Shall I strike them, my father?\n"
	"And he said: Thou shalt not strike them: for thou didst not take them with thy sword, and thy bow, that thou mayst strike them: but set bread & water before them, that they may eat & drink, and go to their master.\n"
	"And a great preparation of meats was set before them, and they did eat and drink, and he dismissed them, and they went away to their master, & the robbers of Syria came no more into the Land of Israel.\n"
	"And it came to pass after these things, Benadad the king of Syria gathered together all his army, & went up, and besieged Samaria.\n"
	"And there was a great famine in Samaria: and so long it was besieged, till the head of an ass was sold for four score silver pieces, & the fourth part of a cabe of pigeon's dung, for five silver pieces.\n"
	"And when the king of Israel passed by the wall, a certain woman cried out to him, saying: Save me my lord king.\n"
	"Who said: No, our Lord save thee: how can I save thee? Of the floor, or of the press? And the king said to her: What aileth thee? Who answered:\n"
	"This woman said to me: Give thy son, that we may eat him today, and my son we will eat tomorrow:\n"
	"We therefore boiled my son, and did eat him. And I said to her the next day: Give thy son, that we may eat him. Who hath hid her son.\n"
	"Which when the king had heard, he rent his garments, and passed by the wall. And all the people saw the hair-cloth, which he wore next upon his flesh.\n"
	"And the king said: These things do God to me, and these add he, if the head of Eliseus the son of Saphat shall stand upon him this day.\n"
	"But Eliseus sat in his house, & the ancients sat with him. He therefore sent a man before: & before that messenger came, he said to the ancients: Do you know that this murderer's son hath sent to cut off my head? See therefore, when the messenger shall come, shut the door, and suffer him not to enter in: for behold the sound of his master's feet is behind him.\n"
	"Whilst he was yet speaking to them, the messenger appeared, which came to him. And he said: Behold, this so great evil is of our Lord: what shall I look for more of our Lord?";