const char* chap32 = "Jacob also went on his journey that he had begun: and the Angels of God met him.\n"
	"Whom when he had seen, he said: These are the Camps of God, and he called the name of that place Mahanaim, that is, Camps.\n"
	"And he sent also messengers before him to Esau his brother into the land of Seir, into the country of Edom:\n"
	"and he commanded them, saying: Thus speak ye unto my lord Esau: This saith thy brother Jacob: I have sojourned, and have been with Laban until this present day.\n"
	"I have oxen, & asses, & sheep, & men servants: & women servants: & now I send a legacy to my lord, that I may find grace in thy sight.\n"
	"And the messengers returned to Jacob, saying: We came to Esau thy brother, & behold he cometh with speed to meet thee with four hundred men.\n"
	"Jacob feared exceedingly: and being sore afraid divided the people that was with him, the flocks also and the sheep, and the oxen, and the camels, into two troops,\n"
	"saying: If Esau come to one troop, and strike it, the other troop that remaineth shall be saved.\n"
	"And Jacob said: O God of my father Abraham, and God of my father Isaac; O Lord that didst say to me: Return into thy land, and into the place of thy nativity, and I will do thee good:\n"
	"I am inferior to all thy mercies, and thy truth that thou hast fulfilled to thy servant. With my staff I passed over this Jordan: and now with two troops I do return.\n"
	"Deliver me from the hand of my brother Esau, because I am sore afraid of him: lest perhaps he come, and strike the mother with the children.\n"
	"Thou didst say that thou wouldst do good to me, and dilate my seed as the sand of the sea, which for multitude cannot be numbered.\n"
	"And when he had slept there that night, he separated of those things which he had, gifts to his brother Esau,\n"
	"she goats two hundred, he goats twenty, ewes two hundred, and rams twenty,\n"
	"thirty milch camels with their colts, forty kine, and twenty bulls, twenty she asses, and their foals ten.\n"
	"And he sent by the hands of his servants every flock by it-self, and he said to his servants: Go before me, and let there be a space between flock and flock.\n"
	"And he commanded the former, saying: If thou meet my brother Esau, and he ask thee, whose art thou? Or whither goest thou? Or whose are these that thou doest follow?\n"
	"Thou shalt answer: Jacob's thy servant, he hath sent them for gifts to my lord Esau: himself also cometh after us.\n"
	"In like manner he gave commandments to the second, and the third, and to all that followed the flocks, saying: With the self-same words speak ye to Esau, when you shall find him.\n"
	"And ye shall add: Jacob also thy servant himself followeth on after us; for he said: I will pacify him with the gifts that go before, and afterward I will see him, perhaps he will be gracious unto me.\n"
	"The gifts therefore went before him, but himself lodged that night in the camp.\n"
	"And when he was risen early, he took his two wives, and his handmaids as many, with his eleven sons, and passed over the ford Iaboc.\n"
	"And when he had set over all things that appertained to him,\n"
	"he tarried alone: and behold a man wrestled with him till morning.\n"
	"Who when he saw that he could not overcome him, he touched the sinew of his thigh, and forthwith it shrank.\n"
	"And he said to him: Let me go for it is break of day. He answered: I will not let thee go, unless thou bless me.\n"
	"He therefore said: What is thy name? He answered: Jacob.\n"
	"But he, no, thy name, quoth he, shall not be called Jacob. But Israel: for if thou hast been strong against God, how much more shalt thou prevail against men?\n"
	"Jacob asked him: Tell me by what name art thou called? He answered: Why dost thou ask my name? and blessed him in the same place.\n"
	"And Jacob called the name of the place Phanuel, saying: I have seen God face to face, and my soul was made safe.\n"
	"And immediately the sun rose to him, after that he was past Phanuel; but he halted on his foot.\n"
	"For which cause the children of Israel eat not the sinew, that shrunk in Jacob's thigh, unto this present day: because he touched the sinew of his thigh, and it shrunk.";