const char* chap322 = "And Eliseus the Prophet called one of the children of the Prophets, and said to him: Gird thy loins, and take this little box of oil in thy hand, and go into Ramoth Galaad.\n"
	"And when thou shalt come thither, thou shalt see Jehu the son of Josaphat the son of Namsi: and going in thou shalt raise him out of the midst of his brethren, and shalt bring him into an inner chamber.\n"
	"And holding the little box of oil, thou shalt pour upon his head, and shalt say: Thus saith our Lord: I have anointed thee king over Israel. And thou shalt open the door, and fly, and shalt not stay there.\n"
	"The young man therefore the child of a Prophet went into Ramoth Galaad,\n"
	"and entered in thither: and behold the captains of the army sat, and he said: I have a word to thee o prince: And Jehu said: to whom of us all? But he said: To thee o prince.\n"
	"And he arose, and went into the chamber: but he poured oil upon his head, and said: Thus saith our Lord the God of Israel: I have anointed thee king over the people of the Lord of Israel,\n"
	"and thou shalt strike the house of Achab thy master, and I will revenge the blood of my servants the Prophets, and the blood of all the servants of the Lord of the hand of Jezabel.\n"
	"And I will destroy all the house of Achab, and kill of Achab him that pisseth against a wall, and the shut up, and the meanest in Israel.\n"
	"And I will make the house of Achab as the house of Jeroboam the son of Nabat, and as the house of Baasa the son of Ahias.\n"
	"Jezabel also the dogs shall eat in the field of Jezrahel, neither shall there be any to bury her. And he opened the door, & fled.\n"
	"And Jehu went forth to his master's servants. Who said to him: Are all things well? Why came this mad man to thee? Who said to them: You know the man, and what he spake.\n"
	"But they answered: It is false, but rather do thou tell us. Who said to them: Thus and thus he spake to me: and he said: Thus saith our Lord, I have anointed thee king over Israel.\n"
	"They therefore made haste, and every man taking his mantle laid it under his feet after the similitude of a judgment seat, and they sounded the trumpet, & said: Jehu hath the Kingdom.\n"
	"Jehu therefore the son of Josaphat the son of Namsi conspired against Joram: Moreover Joram had besieged Ramoth Galaad, he and all Israel against Hazael the king of Syria:\n"
	"and was returned to be cured in Jezrael of the wounds, for the Syrians had wounded him, fighting against Hazael the king of Syria. And Jehu said: If it please you, let no man go forth fugitive out of the city, lest he go, and tell in Jezrahel.\n"
	"And he mounted, and went into Jezrahel: for Joram was sick there, and Ochozias the king of Juda was come down to visit Joram.\n"
	"The watchman therefore, that stood upon the tower of Jezrahel, saw the troop of Jehu coming, & said: I see a troop. And Joram said: Take a Chariot, and send to meet them, and let him that goeth say: Are all things well?\n"
	"He went therefore, that was gotten up into the chariot, to meet him, and said: Thus saith the king: Are all things peaceable? And Jehu said: What hast thou to do with peace? Pass, and follow me. The watchman also told, saying: The messenger came to them, & returneth not.\n"
	"He sent also the second chariot of horses: and he came to them, & said: Thus saith the king: Is there peace? And Jehu said: What hast thou to do with peace? Pass, & follow me.\n"
	"And the watchman told, saying: He is come as far as they, & returneth not: and it is the pace as it were the pace of Jehu the son of Namsi, for he goeth amain.\n"
	"And Joram said: Make ready the chariot. And they made ready his chariot, and Joram the king of Israel went forth, and Ochozias the king of Juda, each in their chariots, and they went forth to meet Jehu, and found him in the field of Naboth the Jezrahelite.\n"
	"And when Joram had seen Jehu, he said: Is there peace Jehu? But he answered: What peace? The fornications of Jezabel thy mother, and her many sorceries are in their vigour.\n"
	"And Joram turned his hand, and flying said to Ochozias: Treason Ochozias.\n"
	"Moreover Jehu bent his bow with his hand, and struck Joram between the shoulders: and the arrow went out through his heart, & immediately he fell in his chariot.\n"
	"And Jehu said to captain Badacer: Take him, throw him forth in the field of Naboth the Jezrahelite: for I remember when I and thou sitting in a chariot did follow Achab this man's father, that our Lord lifted up this burden upon him, saying:\n"
	"If not for the blood of Naboth, and for the blood of his children, which I saw yesterday, saith our Lord, I requite thee not in this field saith our Lord. Now therefore take him, & throw him into the field according to the word of our Lord.\n"
	"But Ochozias the king of Juda seeing this, fled by the way of the house of the garden: & Jehu pursued him, and said: This man also strike ye in his chariot. And they struck him in the going up of Gaver, which is beside Jeblaam: who fled into Mageddo, and died there.\n"
	"And his servants laid him upon his chariot, and carried him into Jerusalem: and they buried him there in his sepulchre with his fathers in the City of David.\n"
	"In the eleventh year of Joram the son of Achab, reigned Ochozias over Juda,\n"
	"and Jehu came into Jezrahel. Moreover Jezabel hearing of his entrance, painted her face with stibic stone, and decked her head, & beheld through the window\n"
	"Jehu coming at the gate, and said: Can there be peace to Zambri, that killed his master?\n"
	"And Jehu lifted up his face to the window, and said: What is she? And two or three eunuchs bowed themselves to him.\n"
	"But he said to them: Cast her down headlong, and they threw her down and the wall was sprinkled with the blood, and the hoofs of the horses trod her.\n"
	"And when he was entered in to eat and to drink, he said: Go, and see that cursed woman, and bury her: because she is a king's daughter.\n"
	"And when they went to bury her, they found nothing but the skull, and the feet, and the extreme parts of the hands.\n"
	"And returning they told him. And Jehu said: It is the word of our Lord, which he spake by his servant Elias the Thesbite, saying: In the field of Jezrahel shall the dogs eat the flesh of Jezabel.\n"
	"and the flesh of Jezabel shall be as dung upon the face of the earth in the field of Jezrahel, so that they which pass by shall say: Is this that same Jezabel?";