const char* chap323 = "And Achab had seventy sons in Samaria: Jehu therefore wrote letters, and sent into Samaria to the chief of the city, and to the ancients, & to them that brought up Achab's children, saying:\n"
	"As soon as you shall receive these letters, ye that have your master's sons, & chariots, & horses, & fenced cities, & armour,\n"
	"choose the better, & him that shall please you of your master's sons, & set him upon his father's throne, & fight for the house of your lord.\n"
	"They were sore afraid, and said: Behold two kings could not stand before him, & how shall we be able to resist?\n"
	"The overseers therefore of the house, and the rulers of the city, & the ancients, & the tutors sent to Jehu, saying: We are thy servants, whatsoever thou shalt command we will do, neither will we make us a king: Do thou whatsoever pleaseth thee.\n"
	"And he wrote letters to them again the second time, saying: If you be mine, and obey me, take the heads of your master's sons, and come to me this very hour tomorrow into Jezrahel. Moreover the king's sons, seventy men were brought up with the chief of the city.\n"
	"And when the letters were come to them, they took the king's sons, and slew seventy men, and put their heads in baskets, and sent them to him into Jezrahel.\n"
	"And a messenger came, and told him, saying: They have brought the heads of the king's sons. Who answered: Lay them in two heaps by the entrance of the gate until morning.\n"
	"And when it was light he went forth, and standing said to all the people: You are just: If I have conspired against my master, and have slain him, who hath strucken all these?\n"
	"See therefore now there hath not fallen of the words of our Lord on the ground, which our Lord spake upon the house of Achab, and our Lord hath done that which he spake in the hand of his servant Elias.\n"
	"Jehu therefore smote all that were left of the house of Achab in Jezrahel, and all his nobles, and familiars, and Priests, till there remained no relics of him.\n"
	"And he arose, and came into Samaria: and when he was come to the cabin of the shepherds in the way,\n"
	"he found the brethren of Ochozias the king of Juda, and he said to them: What are you? Who answered: We are the brethren of Ochozias, and are come down to salute the king's sons, & the queen's sons.\n"
	"Who said: Take them alive. Whom when they had taken alive, they killed them in the cistern beside the cabin, two and forty men, & he left not any of them.\n"
	"And when he was gone thence, he found Jonadab the son of Rechab coming to meet him, and he blessed him. And he said to him: Is thy heart right as my heart with thy heart? And Jonadab said: It is. If it be so, quoth he, give me thy hand. Who gave him his hand. But he lifted him up to him into the chariot,\n"
	"and said to him: Come with me, and see my zeal for our Lord. And being set in his chariot,\n"
	"he brought him into Samaria. And he struck all that were left of Achab in Samaria, till there was not one, according to the word of our Lord, which he spake by Elias.\n"
	"Jehu therefore assembled all the people, & said to them: Achab worshipped Baal a little, but I will worship him more.\n"
	"Now therefore call to me all the Prophets of Baal, and all his servants, and all his Priests: let there be none but that he come, for I have a great sacrifice to Baal: He that shall be wanting shall not live. Moreover Jehu did this craftily, that he might destroy the worshippers of Baal.\n"
	"And he said: Sanctify a solemn day to Baal. And he called\n"
	"and sent into all the borders of Israel, and all the servants of Baal came: there was left not one that came not. And they entered into the temple of Baal: and the house of Baal was filled, from one end to the other.\n"
	"And he said to them that were over the garments: Bring forth garments for all the servants of Baal. And they brought them forth garments.\n"
	"And Jehu going in, and Jonadab the son of Rechab into the temple of Baal, said to the worshippers of Baal: Search, and see lest perhaps there be any with you of the servants of the Lord, but that there be the servants of Baal only.\n"
	"They therefore went in to make victims and holocausts: but Jehu had prepared him without fourscore men, and said to them: Whosoever shall escape of these men, whom I will bring into your hands, his life shall be for the life of him.\n"
	"And it came to pass, when the holocaust was ended, Jehu commanded his soldiers and captains: Go in and strike them, let none escape. And the soldiers and captains struck them in the edge of the sword, and cast them forth: and they went into the city of the temple of Baal,\n"
	"and brought forth the statue out of Baal's temple, and burnt it,\n"
	"and brake it in pieces. They destroyed also the temple of Baal, & made a jakes for it until this day.\n"
	"Jehu therefore destroyed Baal out of Israel:\n"
	"but yet from the sins of Jeroboam the son of Nabat, who made Israel to sin, he departed not, neither forsook he the golden calves, that were in Bethel, and Dan.\n"
	"And our Lord said to Jehu: Because thou hast diligently done that which was right, and that pleased in mine eyes, and hast done all things that were in my heart, against the house of Achab: thy children shall sit upon the throne of Israel to the fourth generation.\n"
	"Moreover Jehu observed not to walk in the law of our Lord the God of Israel in all his heart: for he departed not from the sins of Jeroboam, who had made Israel to sin.\n"
	"In those days our Lord began to be weary of Israel: and Hazael smote them in all the coasts of Israel,\n"
	"from Jordan against the East quarter, all the land of Galaad, & Gad, & Ruben, & Manasses, from Aroer, which is upon the Torrent Arnon, and Galaad, and Basan.\n"
	"But the rest of the words of Jehu, and all that he did, and his strength, are not these things written in the Book of the words of the days of the kings of Israel?\n"
	"And Jehu slept with his fathers, and they buried him in Samaria: and Joachaz his son reigned for him.\n"
	"And the days which Jehu reigned over Israel be eight and twenty years, in Samaria.";