const char* chap327 = "In the second year of Joas the son of Joachaz the king of Israel reigned Amasias the son of Joas the king of Juda.\n"
	"Five and twenty years old was he when he began to reign: and nine & twenty years he reigned in Jerusalem, the name of his mother was Ioadan of Jerusalem.\n"
	"And he did right before our Lord, but yet not as David his father. He did according to all things, which Joas his father did:\n"
	"but this only that he took not away the excelses: for yet the people immolated, and burnt incense in the excelses.\n"
	"And when he obtained the Kingdom, he smote his servants, which had slain the king his father:\n"
	"but their children that killed him, he did not put to death, according to that which is written in the book of the law of Moyses, as our Lord commanded, saying: The fathers shall not die for the children, neither shall the children die for the fathers: but every one shall die in his own sin.\n"
	"He smote Edom in the Vale of Salt pits ten thousand, and took the rock in battle, & called the name thereof, Jectehel, until this present day.\n"
	"Then Amasias sent messengers to Joas the son of Joachaz, the son of Jehu the king of Israel, saying: Come let us see one another.\n"
	"And Joas the king of Israel sent again to Amasias the king of Juda saying: A thistle of Libanus sent to a cedar tree, which is in Libanus, saying: Give thy daughter to my son to wife. And the beasts of the forest, that are in Libanus, passed & trod the thistle.\n"
	"Thou striking hast prevailed over Edom, and thy heart hath puffed thee up: be content with the glory, and sit in thy house: Why provokest thou evil, that thou mayst fall & Juda with thee?\n"
	"And Amasias agreed not. And Joas the king of Israel went up, and they saw each other, he & Amasias the king of Juda in Bethsames a town of Juda.\n"
	"And Juda was strucken before Israel, & every man fled into their tabernacles.\n"
	"But Joas the king of Israel did take Amasias the king of Juda the son of Joas, the son of Ochozias, in Bethsames, & brought him into Jerusalem: and he brake down the wall of Jerusalem, from the gate of Ephraim unto the gate of the corner, four hundred cubits.\n"
	"And he took all the gold, and silver, and all the vessels, that were found in the house of our Lord, and in the king's treasures, and hostages, and returned into Samaria.\n"
	"But the rest of the words of Joas which he did, and his strength, wherewith he fought against Amasias the king of Juda, are not these things written in the Book of the words of the days of the kings of Israel?\n"
	"And Joas slept with his fathers, and was buried in Samaria with the kings of Israel: and Jeroboam his son reigned for him.\n"
	"And Amasias the son of Joas the king of Juda lived, after that Joas the son of Joachaz the king of Israel was dead, fifteen years.\n"
	"But the rest of the words of Amasias, are not these things written in the Book of the words of the days of the kings of Juda?\n"
	"And there was a conspiracy made against him in Jerusalem: But he fled into Lachis. And they sent after him into Lachis, and killed him there.\n"
	"And they carried him away upon horses, and he was buried in Jerusalem with his fathers in the City of David.\n"
	"And all the people of Juda took Azarias sixteen years old, and made him king for his father Amasias.\n"
	"He built Aelath, and restored it to Juda, after that the king slept with his fathers.\n"
	"In the fifteenth year of Amasias the son of Joas the king of Juda, reigned Jeroboam the son of Joas the king of Israel in Samaria, one and forty years:\n"
	"and he did that which is evil before our Lord. He departed not from all the sins of Jeroboam the son of Nabat, who made Israel to sin.\n"
	"He restored the borders of Israel from the entrance of Emath, unto the Sea of the wilderness, according to the word of our Lord the God of Israel, which he spake by his servant Jonas the son of Amathi, the Prophet, who was of Geth, which is in Opher.\n"
	"For our Lord saw the affliction of Israel exceeding bitter, & that they were consumed unto the imprisoned & meanest persons, and that there was none to help Israel.\n"
	"Neither did our Lord determine that he would destroy the name of Israel from under heaven, but he saved them in the hand of Jeroboam the son of Joas.\n"
	"But the rest of the words of Jeroboam, and all that he did, and his strength, wherewith he fought, and how he restored Damascus, and Emath to Juda in Israel, are not these things written in the Book of the words of the days of the kings of Israel?\n"
	"And Jeroboam slept with his fathers the kings of Israel, and Zacharias his son reigned for him.";