const char* chap328 = "In the seven and twentieth year of Jeroboam the king of Israel reigned Azarias the son of Amasias the king of Juda.\n"
	"He was sixteen years old, when he began to reign, and two and fifty years he reigned in Jerusalem: the name of his mother was Jechelia of Jerusalem.\n"
	"And he did that which was liked before our Lord, according to all things that his father Amasias did\n"
	"But the excelses he destroyed not: as yet the people sacrificed, & burnt incense in the excelses.\n"
	"And our Lord struck the king, and he was a leper until the day of his death, & he dwelt in a free house a-part: but Joathan the king's son governed the palace, and judged the people of the land.\n"
	"But the rest of the words of Azarias, and all that he did, are not these things written in the Book of the words of the days of the kings of Juda?\n"
	"And Azarias slept with his fathers: and they buried him with his ancestors in the city of David, & Joathan his son reigned for him.\n"
	"In the eight and thirtieth year of Azarias the king of Juda, reigned Zacharias the son of Jeroboam over Israel in Samaria six months:\n"
	"and he did that which is evil before our Lord, as his fathers had done: he departed not from the sins of Jeroboam the son of Nabat, who made Israel to sin.\n"
	"And Sellum the son of Jabes conspired against him: and smote him openly, killed him, and reigned for him.\n"
	"but the rest of the words of Zacharias, are not these written in the Book of the words of the days of the kings of Israel?\n"
	"This is the word of our Lord, which he spake to Jehu, saying: Thy children shall sit unto the fourth generation upon the throne of Israel. And so it came to pass.\n"
	"Sellum the son of Jabes reigned the nine and thirtieth year of Azarias the King of Juda: and reigned one month in Samaria.\n"
	"And Manahem the son of Gadi went up from Thersa: and he came into Samaria, and smote Sellum the son of Jabes in Samaria, and slew him, and reigned for him.\n"
	"But the rest of the words of Sellum, and his conspiracy, wherewith he wrought treason, are not these things written in the Book of the words of the days of the kings of Israel?\n"
	"Then Manahem struck Thapsa and all that were in it and the borders thereof from Thersa, for they would not open unto him: and he slew all women thereof that were with child, and ripped them.\n"
	"In the nine and thirtieth year of Azarias the king of Juda, reigned Manahem the son of Gadi over Israel ten years in Samaria.\n"
	"And he did that which was evil before our Lord: he departed not from the sins of Jeroboam the son of Nabat, who made Israel to sin all his days.\n"
	"Phul also the king of the Assyrians came into the land, and Manahem gave to Phul a thousand talents of silver, that he should aid him, and establish his Kingdom.\n"
	"And Manahem put a tax of silver upon Israel, on them that were mighty and rich to give the king of the Assyrians, fifty sicles of silver every man: and the king of the Assyrians returned, and tarried not in the land.\n"
	"But the rest of the words of Manahem, and all that he did, are not these things written in the Book of the words of the days of the kings of Israel?\n"
	"And Manahem slept with his fathers: and Phaceia his son reigned for him.\n"
	"In the fiftieth year of Azarias the king of Juda reigned Phaceia the son of Manahem over Israel in Samaria two years:\n"
	"and he did that which was evil before our Lord: he departed not from the sins of Jeroboam the son of Nabat, who made Israel to sin.\n"
	"And Phacee the son of Romelia, his captain conspired against him, and struck him in Samaria, in the tower of the king's house beside Argob and beside Arie, and with him fifty men of the children of Galaadites, and he slew him, and reigned for him.\n"
	"But the rest of the words of Phaceia and all that he did, are not these things written in the Book of the words of the days of the kings of Israel.\n"
	"In the two and fiftieth year of Azarias the king of Juda reigned Phacee the son of Romelia over Israel in Samaria twenty years.\n"
	"And he did that which was evil before our Lord: he departed not from the sins of Jeroboam the son of Nabat, who made Israel to sin.\n"
	"In the days of Phacee the king of Israel came Theglathphalasar the king of Assur, and took Aion, and Abel, the house of Maachat & Janoe, and Cedes, and Asor, and Galaad, and Galilee, and all the land of Nephthali: and transported them unto the Assyrians.\n"
	"And Osee the son of Ela conspired, and lay in wait against Phacee the son of Romelia, and struck him, and slew him: and he reigned for him the twentieth year of Joatham the son of Ozias\n"
	"But the rest of the words of Phacee, and all that he did, are not these things written in the Book of the words of the days of the kings of Israel?\n"
	"In the second year of Phacee the son of Romelia the king of Israel, reigned Joatham the son of Ozias the king of Juda.\n"
	"Five and twenty years old was he when he began to reign, and sixteen years he reigned in Jerusalem: the name of his mother was Jerusa, the daughter of Sadoc.\n"
	"And he did that which was liked before our Lord: according to all things, which Ozias his father had done, did he work.\n"
	"Howbeit the excelses he took not away: as yet the people immolated, and burnt incense in the excelses: he built the highest gate of the house of our Lord.\n"
	"But the rest of the words of Joatham, and all that he did, are not these things written in the Book of the words of the days of the kings of Juda?\n"
	"In those days our Lord began to send into Juda^ Rasin the king of Syria, and Phacee the son of Romelia.\n"
	"And Joatham slept with his fathers, and was buried with them in the city of David his father, and Achaz his son reigned for him.";