const char* chap33 = "And Jacob lifting up his eyes, saw Esau coming, and with him four hundred men: and he divided the children of Lia, and of Rachel, and of the two handmaids:\n"
	"and he put both the handmaids and their children foremost: and Lia and her children in the second place: and Rachel and Joseph last.\n"
	"And himself going forward adored prostrate to the ground seven times, until his brother came near.\n"
	"Esau therefore running to meet his brother, embraced him: and clasping him fast about the neck, and kissing him wept.\n"
	"And casting up his eyes he saw the women and their little ones, and said: What mean these? And do they pertain to thee? He answered: They are the little ones which God hath given to me thy servant.\n"
	"And the handmaids and their children coming near bowed themselves.\n"
	"Lia also with her children came near: and when they had adored in like manner, last Joseph and Rachel adored.\n"
	"And Esau said: What are the troops that I did meet? He answered: That I might find grace before my lord.\n"
	"But he said: I have plenty, my brother, be thy things to thyself,\n"
	"And Jacob said: Do not so, I beseech thee, but if I have found grace in thine eyes, take a little present at my hands: for so have I seen thy face as if I should have seen the countenance of God: be gracious to me,\n"
	"and take the blessing which I have brought thee, and which God hath given me, who giveth all things. Scarce at his brother's great instance taking it,\n"
	"he said: let us march on together, and I will accompany thee in thy journey.\n"
	"And Jacob said: My lord thou knowest that I have with me little ones, and sheep, and kine with young: which if I cause to overlabour themselves in going, in one day all the flocks will die.\n"
	"It may please my lord to go before his servant: and I will follow softly after him, as I shall see my little ones to be able, until I come to my lord in Seir.\n"
	"Esau answered: I beseech thee, that of my people at the leastwise, which is with me, there may remain some to accompany thee in the way. It is not needful, said he, this only I have need of, that I may find grace (my lord) in thy sight.\n"
	"Esau therefore returned that day the same way that he came, into Seir.\n"
	"And Jacob cometh into Socoth: where having built a house, and pitched his tents, he called the name of that place Socoth, that is, Tabernacles.\n"
	"and he passed into Salem a city of the Sichimites, which is in the land of Chanaan, after he returned from Mesopotamia of Syria: and he dwelt beside the town.\n"
	"And he bought that part of the field, wherein he had pitched his tents, of the children of Hemor, the father of Sichem, for an hundred lambs.\n"
	"And erecting an altar there, on it he called upon the most Mighty God of Israel.";