const char* chap332 = "Which things when Ezechias the king had heard, he rent his garments, and was covered with sackcloth, and entered into the house of our Lord.\n"
	"And he sent Eliacim the governor of the house, and Sobna the scribe, & the ancients of the Priests covered with sackcloths, to Isaias the Prophet the son of Amos.\n"
	"Who said to him: Thus saith Ezechias: This day is a day of tribulation, and rebuke, and of blasphemy: the children are come to the birth, and the woman in travail hath not strength.\n"
	"If perhaps our Lord thy God will hear all the words of Rabsaces, whom the king of the Assyrians his master hath sent to upbraid the living God, and reprove with words, which our Lord thy God hath heard: and make thou prayer for the remnants that are found.\n"
	"The servants thereof of king Ezechias came to Isaie.\n"
	"And Isaie said to them: Thus shall you say to your master: Thus saith our Lord: Fear not for the words, which thou hast heard, with which the servants of the king of the Assyrians have blasphemed me.\n"
	"Behold I will send into him a spirit, and he shall hear a message, and shall return into his country, and I will overthrow him with the sword in his country.\n"
	"Rabsaces therefore returned, and found the king of Assyrians expugning Lobna: for he heard that he was departed from Lachis.\n"
	"And when he had heard of Tharaca the king of Aethiopia, saying: Behold, he is come forth to fight against thee: and went against him, he sent messengers to Ezechias, saying:\n"
	"Say this to Ezechias the king of Juda: Let not thy God seduce thee, in whom thou hast confidence: neither say thou: Jerusalem shall not be delivered into the hands of the king of the Assyrians.\n"
	"For thou thyself hast heard what the kings of the Assyrians have done to all the countries, how they have spoiled them, canst thou therefore only be delivered?\n"
	"Why, have the gods of the Nations delivered all those, whom my fathers have destroyed, to wit, Gozan and Haran, and Reseph, and the children of Eden, which were in Thelassar?\n"
	"Where is the king of Emath, and the king of Arphad, and the king of the city of Sepharvaim, of Ana and Ava?\n"
	"Therefore when Ezechias had received the letters of the hand of messengers, and had read them, he went up into the house of our Lord, and laid them open before our Lord,\n"
	"and prayed in his sight, saying: Lord God of Israel, which sittest upon the cherubins, thou art the only God of all the kings of the earth: thou madest heaven and earth:\n"
	"Incline thine ear, and hear: open Lord thine eyes, and see: and hear all the words of Sennacherib, who hath sent to upbraid unto us the living God.\n"
	"In very deed Lord, the kings of the Assyrians have destroyed Nations, and the countries of all.\n"
	"And they have cast their gods into fire: for they were not gods, but the works of men's hands of wood and stone, and they destroyed them.\n"
	"Now therefore, O Lord our God, save us from his hand, that all the Kingdoms of the earth may know, that thou art the Lord the only God.\n"
	"And Isaie the son of Amos sent to Ezechias, saying: Thus saith our Lord the God of Israel: That which thou hast besought me concerning Sennacherib the king of the Assyrians, I have heard.\n"
	"This is the word that our Lord hath spoken of him: The virgin daughter of Sion hath despised thee, & scorned thee: Behind thy back hath the daughter of Jerusalem wagged her head.\n"
	"Whom hast thou upbraided, & whom hast thou blasphemed? Against whom hast thou exalted thy voice, and lifted up thine eyes in high? Against the holy one of Israel.\n"
	"By the hand of thy servants thou hast upbraided our Lord, and hast said: In the multitude of my chariots have I climbed the height of mountains, in the top of Libanus, and have cut down high cedars thereof, and the chosen fir-trees of it. And I have entered into the borders thereof, & the forest of the carmel thereof\n"
	"have I cut down. And I have drunk strange waters, and have dried up with the steps of my feet all the waters inclosed.\n"
	"Why, hast thou not heard what I have done from the beginning? From ancient days I have made that thing, and now I have brought it to effect: and fenced cities shall be into ruin of little hills bickering together.\n"
	"And they that sit in them, weak of hand, they have trembled & are confounded, they became as the grass of the field, and the green herb of the roofs of houses, which withered before it came to ripeness.\n"
	"Thy habitation, and thy going out, and thy coming in, and thy way I have known before, and thy fury against me.\n"
	"Thou hast been mad against me, and thy pride hath ascended into mine ears: I therefore will put a ring in thy nostrils, and a bit in thy lips, and will bring thee back into the way, by the which thou camest.\n"
	"And to thee Ezechias this shall be a sign: Eat this year what thou shalt find: and in the second year, the things that grow of themselves: moreover in the third year sow ye and reap: plant ye vineyards, and eat the fruit of them.\n"
	"And whatsoever shall be left of the house of Juda, shall take root downward, and bear fruit upward.\n"
	"For out of Jerusalem there shall remnants go forth, and that which is to be saved from the mount of Sion: the zeal of the Lord of hosts shall do this.\n"
	"Wherefore thus saith our Lord^ of the king of the Assyrians: He shall not enter into this city, nor shoot arrow into it, neither shall shield occupy it, nor munition compass it.\n"
	"By the way, that he came, he shall return: and into this city he shall not enter, saith our Lord.\n"
	"And I will protect this city, and will save it for myself, and for David my servant.\n"
	"It came to pass therefore in that night, an Angel of our Lord came, and struck in the camp of the Assyrians an hundred eighty five thousand. And when he was risen early, he saw all the bodies of the dead,\n"
	"and Sennacherib the king of the Assyrians departing went away, and tarried in Ninive.\n"
	"And when he adored in the temple of Nesroch his god, Adramelech and Sarasar his sons struck him with the sword, and they fled into the land of the Armenians, and Asarhaddon his son reigned for him.";