const char* chap334 = "Twelve years old was Manasses, when he began to reign, & he reigned five and fifty years in Jerusalem: the name of his mother was Haphsiba.\n"
	"And he did evil in the sight of our Lord, according to the idols of the Nations, which our Lord destroyed from the face of the children of Israel:\n"
	"And he was turned, and built the excelses, which Ezechias his father had destroyed: and he set up altars to Baal, and made groves, as Achab the king of Israel had done: and he adored all the host of heaven, and worshipped it.\n"
	"And he built altars in the house of our Lord, of the which our Lord said: In Jerusalem I will put my name.\n"
	"And he built altars to all the host of heaven in the two courts of the temple of our Lord.\n"
	"And he made his son pass through fire: and he used soothsaying, and observed divinations, and made pythons, and multiplied enchanters, to do evil before our Lord, & to provoke him.\n"
	"He set also the idol of the grove, which he had made in the temple of our Lord: concerning the which our Lord spake to David, and to Salomon his son: In this temple, & in Jerusalem, which I have chosen out of all the tribes of Israel, I will put my name for ever.\n"
	"And I will no more make the foot of Israel to be moved out of the land, which I gave to their fathers: yet so if in work they shall keep all things that I have commanded them, & all the law which my servant Moyses commanded them.\n"
	"But they heard not: but were seduced by Manasses, to do evil above the Nations, which our Lord destroyed before the face of the children of Israel\n"
	"And our Lord spake in the hand of his servants the Prophets, saying:\n"
	"Because Manasses the king of Juda hath done these most wicked abominations, passing all things that the Amorrheites did before him, and hath made Juda also to sin in his filths:\n"
	"therefore thus saith our Lord the God of Israel: Behold I will bring in evils upon Jerusalem and Juda: that whosoever shall hear it, both his ears shall tingle.\n"
	"And I will stretch out upon Jerusalem the cord of Samaria, and the weight of the house of Achab: and I will wipe out Jerusalem, as tables are wont to be wiped out, and wiping out I will turn it, and draw often the pencil upon the face thereof.\n"
	"But I will leave remnants of mine inheritance, and will deliver them into the hands of their enemies: and they shall be unto waste, and unto spoil to all their adversaries:\n"
	"because they have done evil before me, and have continued provoking me, from the day that their fathers came out of Aegypt, until this day.\n"
	"Moreover Manasses shed also innocent blood exceeding much, till he filled Jerusalem even to the mouth: beside his sins, wherein he made Juda to sin, to do evil before our Lord.\n"
	"But the rest of the words of Manasses, and all that he did, and his sin, which he sinned, are not these things written in the Book of the words of the days of the kings of Juda?\n"
	"And Manasses slept with his fathers, and was buried in the garden of his house, in the garden of Oza: and Amon his son reigned for him.\n"
	"Two and twenty years old was Amon when he began to reign: two years also he reigned in Jerusalem: the name of his mother was Messalemeth the daughter of Jeteba.\n"
	"And he did evil in the sight of our Lord, as Manasses his father had done.\n"
	"And he walked in all the way, by the which his father had walked: and he served the filths, which his father had served, and he adored them,\n"
	"and forsook our Lord the God of his fathers, and walked not in the way of our Lord.\n"
	"And his servants lay in wait against him, and slew the king in his house.\n"
	"But the people of the land struck all them, that had conspired against king Amon: and made Josias his son their king for him.\n"
	"But the rest of the words of Amon which he did, are not these written in the Book of the words of the days of the kings of Juda?\n"
	"And they buried him in his sepulchre, in the garden of Oza: and Josias his son reigned for him.";