const char* chap335 = "Eight years old was Josias when he began to reign, he reigned one & thirty years in Jerusalem: the name of his mother was Idida, the daughter of Hadaia of Besecath.\n"
	"And he did that which was liked before our Lord, and walked in all the ways of David his father: he declined not to the right hand, or to the left.\n"
	"And in the eighteenth year of king Josias, the king sent Saphan the son of Aslia, the son of Messulam, the scribe of the temple of our Lord, saying to him:\n"
	"Go to Helcias the high Priest, that the money may be gathered into a sum, which hath been brought into the temple of our Lord, which the porters of the temple have gathered of the people,\n"
	"and let it be given to the workmen by the overseers of the house of our Lord, who also shall distribute it to them that work in the temple of our Lord, to make the reparations of the temple:\n"
	"that is, to the carpenters and masons, and to them that mend broken places: and that timber may be bought, and stones out of the quarries, to repair the temple of our Lord.\n"
	"Yet let not the money which they receive be accounted to them, but let them have it in their power, and upon their fidelity.\n"
	"And Helcias the high Priest said to Saphan the scribe: I have found the Book of the law in the house of our Lord: and Helcias gave the volume to Saphan, who also did read it.\n"
	"Saphan also the scribe came to the king, and reported unto him that which he had commanded, and said: Thy servants have gathered into a sum the money, which is found in the house of our Lord: and they have given it to be distributed to the workmen, by the overseers of the works of the temple of our Lord.\n"
	"Saphan also the scribe told the king, saying: Helcias the priest hath given me a Book. Which when Saphan had read before the king,\n"
	"and the king had heard the words of the law of our Lord, he rent his garments.\n"
	"And he willed Helcias the Priest, and Ahicam the son of Saphan, and Achobor the son of Micha, and Saphan the Scribe, and Asaia the king's servant, saying:\n"
	"Go and consult our Lord for me, and for the people, and for all Juda, concerning the words of this volume, which is found: for the great wrath of our Lord is kindled against us: because our fathers have not heard the words of this Book, to do all that is written for us.\n"
	"Helcias therefore the Priest, and Ahicam, and Achobor, and Saphan, and Asaia went to Holda a prophetess, the wife of Sellum, the son of Thecua, the son of Araas keeper of the garments, who dwelt in Jerusalem in the second: and they spake to her.\n"
	"And she answered them: Thus saith our Lord the God of Israel: Tell the man, that sent you to me:\n"
	"Thus saith our Lord: Behold, I will bring evils upon this place, and upon the inhabitants thereof, all the words of the law which the king of Juda hath read:\n"
	"because they have forsaken me, and have sacrificed to strange gods, provoking me in all the works of their hands: and my indignation shall be kindled in this place, and shall not be quenched.\n"
	"But to the king of Juda, that sent you to consult our Lord, thus you shall say: Thus saith our Lord the God of Israel: For that thou hast heard the words of the volume,\n"
	"and thy heart is strucken with fear, and thou art humbled before the Lord, hearing the words against this place, and the inhabitants thereof, to wit, that they should become a wonder and a curse: and hast rent thy garments, and wept before me, and I have heard it, saith our Lord:\n"
	"therefore I will gather thee to thy fathers, and thou shalt be gathered to thy sepulchre in peace, that thy eyes may not see all the evils, which I will bring in upon this place.";