const char* chap339 = "Adam, Seth, Enos,\n"
	"Cainan, Malaleel, Jared,\n"
	"Henoch, Mathusale, Lamech,\n"
	"Noe, Sem, Cham, and Japheth.\n"
	"The sons of Japheth: Gomer, and Magog, & Madai, and Javan, Thubal, Mosoch, Thiras.\n"
	"Moreover the sons of Gomer: Ascenez, and Riphath, and Thogorma.\n"
	"And the sons of Javan: Elisa and Tharsis, Cethim and Dodanim.\n"
	"The sons of Cham: Chus, and Mesraim, and Phut, and Chanaan.\n"
	"And the sons of Chus: Saba, and Hevila, Sabatha, and Regma, and Sabathaca. Moreover the sons of Regma: Saba, and Dadan.\n"
	"And Chus begat Nemrod: this began to be mighty in the earth.\n"
	"But Mesraim begat Ludim, and Anamim, and Laabim, and Nephtuim,\n"
	"Phetrusim also, and Casluim: from whom came Philisthiim, & Caphthorim.\n"
	"But Chanaan begat Sidon his firstborn, the Hetheite also,\n"
	"and the Jebuseite, and the Amorrhite, and the Gergesite,\n"
	"& the Heveite, & the Aracite, & the Sinite.\n"
	"The Aradium also, and the Samarite, & the Hamathite.\n"
	"The sons of Sem: Aelam, and Assur, and Arphaxad, and Lud, and Aram, & Hus, and Hul, and Gether, and Mosoch.\n"
	"And Arphaxad begat Sale, who also begat Heber.\n"
	"Moreover to Heber were born two sons, the name of one was Phaleg, because in his days the earth was divided; and the name of his brother Jectan.\n"
	"And Jectan begat Elmodad, & Saleph, and Asarmoth, and Jare,\n"
	"Adoram also, and Usal, and Decla,\n"
	"Hebal also, and Abimael, and Saba, moreover\n"
	"also Ophir, and Hevila, and Jobab. All these are the sons of Jectan:\n"
	"Sem, Arphaxad, Sale,\n"
	"Heber, Phaleg, Ragau,\n"
	"Serug, Nachor, Thare,\n"
	"Abram, this is Abraham.\n"
	"And the sons of Abraham, Isaac and Ismael.\n"
	"And these are the generations of them. The first-begotten of Ismael, Nabajoth, and Cedar, and Adbeel, and Mabsam,\n"
	"and Masma, and Duma, Massa, Hadad, and Thema,\n"
	"Jetur, Naphis, Cedma. These are the sons of Ismahel.\n"
	"And the sons of Cetura Abraham's concubine, which she bare: Zamran, Jecsan, Madan, Madian, Jesboc, and Sue. Moreover the sons of Jecsan: Saba, and Dadan. And the sons of Dadan: Assurim, and Latussim, and Laomim.\n"
	"And the sons of Madian: Epha, and Epher, and Henoch, and Abida, and Eldaa. All these the sons of Cetura.\n"
	"And Abraham begat Isaac: whose sons were Esau, and Israel.\n"
	"The sons of Esau: Eliphaz, Rahuel, Jehus, Ihelom, and Core.\n"
	"The sons of Eliphaz: Theman, Omar, Sephi, Gathan, Cenez, Thamna, Amalec.\n"
	"The sons of Rahuel: Nahath, Zaza, Samma, Meza.\n"
	"The sons of Seir: Lotan, Sobal, Sebeon, Ana, Dison, Eser, Disan.\n"
	"The sons of Lotan: Hori, Homam. And the sister of Lotan was Thamna.\n"
	"The sons of Sobal: Alian, and Manahath, and Ebal, Sephi, and Onam. The sons of Sebeon: Aia and Ana. The sons of Ana: Dison.\n"
	"The sons of Dison: Hamram, and Eseban, and Jethran, and Charan.\n"
	"The sons of Eser: Balaan, and Zavan, and Jacan. The sons of Disan: Hus and Aran.\n"
	"These be the kings, that reigned in the Land of Edom, before there was a king over the children of Israel: Bale the son of Beor: and the name of his city, Denaba.\n"
	"And Bale died, and Jobab the son of Zare of Bosra, reigned for him.\n"
	"And when Jobab also was dead, Husam of the Land of the Themanes reigned for him.\n"
	"And Husam also died, and Adad the son of Badad reigned for him, who struck Madian in the Land of Moab: and the name of his city was Avith.\n"
	"And when Adad also was dead, Semla of Masreca reigned for him.\n"
	"But Semla also died, and there reigned for him Saul of Rohoboth, which is situate besides the river.\n"
	"Saul also being dead, Balanan, the son of Achobor reigned for him.\n"
	"But this also died, and Adad reigned for him: whose city's name was Phau, and his wife was called Meetabel the daughter of Matred, the daughter of Mezaab.\n"
	"And Adad being dead, there began to be dukes in Edom for kings: duke Thamna, duke Alva, duke Jetheth,\n"
	"duke Oolibama, duke Ela, duke Phinon,\n"
	"duke Cenez, duke Theman, duke Mabsar,\n"
	"duke Magdiel, duke Hiram. These be the dukes of Edom.";