const char* chap347 = "All Israel therefore was numbered: and the sum of them was written in the Book of the kings of Israel & Juda and they were transported into Babylon for their sin.\n"
	"And they that dwelt first in their possessions and in their cities: Israel, and the Priests, and the Levites, and the Nathineans.\n"
	"There dwelt in Jerusalem of the children of Juda, and of the children of Benjamin, also of the children of Ephraim, and Manasses.\n"
	"Othei the son of Ammiud, the son of Amri, the son of Omrai, the son of Bonni, of the sons of Phares the son of Juda.\n"
	"And of Siloni Asaia the first-begotten, and his sons.\n"
	"And of the sons of Zara: Jehuel, and their brethren, six hundred ninety.\n"
	"Moreover of the sons of Benjamin: Salo the son of Mosollam, the son of Oduia the son of Asana:\n"
	"and Jobania the son of Jeroham: and Ela the son of Ozi the son of Mochori: and Mosollam the son of Saphatias, the son of Rahuel, the son of Jebania,\n"
	"and their brethren by their families, nine hundred fifty six. All these Princes of their kindreds by the houses of their fathers.\n"
	"And of the Priests: Jedaia, Joiarib, and Jachin:\n"
	"Azarias also the son of Helcias, the son of Mosollam, the son of Sadoc, the son of Maraioth, the son of Achitob, high Priest of the house of God.\n"
	"Moreover Adaias the son of Jeroham, the son of Phassur, the son of Melchias: and Maasai the son of Adiel, the son of Jezra, the son of Mosollam, the son of Mosollamith, the son of Emmer.\n"
	"their brethren also Princes by their families a thousand seven hundred three score, most able men of strength to the work of the ministry in the house of God.\n"
	"And of the Levites: Semeia the son of Hassub the son of Ezricam, the son of Hasebia of the sons of Merari.\n"
	"Bacbacar also a carpenter, and Galal, and Mathania the son of Micha, the son of Zechri the son of Asaph:\n"
	"and Obdia the son of Semei, the son of Galal, the son of Idithun: and Barachia the son of Asa, the son of Elcana, who dwelt in the courts of Netophati.\n"
	"And the porters: Sellum, and Accub, and Telmon, and Ahimam: and their brother Sellum the Prince,\n"
	"until that time, in the king's gate toward the east, waited by their courses of the children of Levi.\n"
	"But Sellum the son of Core the son of Abiasaph, the son of Core, with his brethren, and his father's house, these are the Corites over the works of the ministry, keepers of the entrances of the tabernacle: and their families in course keeping the entrance of the camp of our Lord.\n"
	"And Phinees the son of Eleasar, was their Prince before our Lord.\n"
	"Moreover Zacharias the son of Mosollamia, porter of the gate of the tabernacle of testimony.\n"
	"All these chosen men for porters, at every gate, two hundred twelve: and appointed out in their proper towns: Whom David and Samuel the seer appointed, upon their fidelity.\n"
	"as well them as their sons, in the doors of the house of our Lord, and in the tabernacle by their courses.\n"
	"By the four winds were the porters: that is to say, toward the East, and toward the West, & toward the North, & toward the South.\n"
	"And their brethren dwelt in villages, & came upon their Sabbaths from time to time.\n"
	"To these four Levites was committed all the number of porters, & they were over the chambers, and treasures of the house of our Lord.\n"
	"Also round about the temple of our Lord they abode in their watches: that when it was time, they in the morning might open the doors.\n"
	"Of these men's stock there were also over the vessels of the ministry: for by number the vessels were both brought in and carried out.\n"
	"Of them also they that had the implements of the sanctuary committed unto them, did oversee the flour, and wine, and oil, and frankincense, and spices.\n"
	"And the sons of Priests made ointments of the spices.\n"
	"And Mathathias a Levite the first-begotten of Sellum the Corite, was overseer of those things, which were fried in the frying pan.\n"
	"Moreover of the children of Caath their brethren, there were over the loaves of proposition, to prepare always new every Sabbath.\n"
	"These are the chief of the singing men by the families of the Levites, which abode in the chambers, that they might day and night continually serve in their ministry.\n"
	"The heads of the Levites, Princes in their families, tarried in Jerusalem.\n"
	"And in Gabaon abode Jehiel the father of Gabaon, and the name of his wife Maacha.\n"
	"His first-begotten son Abdon, and Sur, and Cis, and Baal, and Ner, and Nadab,\n"
	"Gedor also, and Ahio, and Zacharias, and Macelloth.\n"
	"Moreover Macelloth begat Samaan, these dwelt over against their brethren in Jerusalem, with their brethren.\n"
	"And Ner begat Cis: and Cis begat Saul: and Saul begat Jonathas, and Melchisua, and Abinadab, and Esbaal.\n"
	"And the son of Jonathas, Meribbaal: & Meribbaal begat Micha.\n"
	"Moreover the sons of Micha, Phithon, & Melech, & Tharaa, and Ahaz.\n"
	"And Ahaz begat Jara, & Jara begat Alamath, & Azmoth, & Zamri. And Zamri begat Mosa.\n"
	"And Mosa begat Banaa: whose son Raphaia begat Elasa: of whom was born Asel.\n"
	"Moreover Asel had six sons of these names, Ezricam, Bochru, Ismael, Saria, Obdia, Hanan, these are the sons of Asel.";