const char* chap35 = "In the mean time God spake to Jacob: Arise, and go up to Bethel, and dwell there, and make an altar to God that appeared to thee when thou didst fly from Esau thy brother.\n"
	"And Jacob having called together all his house, said: Cast away the strange gods that are among you, and be cleansed and change your garments.\n"
	"Arise, and let us go up into Bethel, that we may make there an altar unto God: who herd me in the day of my tribulation, and accompanied me in my journey.\n"
	"They gave to him therefore all the strange gods that they had, and the earlets which were in their ears: but he buried them under the terebinth that is behind the city of Sichem.\n"
	"And when they were departed, the terror of God invaded all the cities round about, and they durst not pursue them going away.\n"
	"And Jacob came to Luza, which is in the land of Chanaan, surnamed Bethel: he and all the people that was with him.\n"
	"And he builded there an altar, and called the name of that place, The house of God: for there God appeared to him when he fled from his brother.\n"
	"The same time died Debora the nurse of Rebecca, and was buried at the foot of Bethel under an oak: and the name of that place was called The oak of weeping.\n"
	"And God appeared again to Jacob after he returned from Mesopotamia of Syria, and he blessed him,\n"
	"saying: Thou shalt not be called any more Jacob, but Israel shall be thy name. And he called him Israel,\n"
	"and said to him: I am God Almighty, increase thou and multiply: Of thee shall be nations and peoples of nations, kings shall come forth of thy loins.\n"
	"And the land which I gave to Abraham and Isaac, I will give to thee, and to thy seed after thee.\n"
	"And he departed from him.\n"
	"But he erected a title of stone in the place where God had spoken unto him: offering upon it liquid offerings, and pouring oil on it,\n"
	"and calling the name of that place, Bethel.\n"
	"And being gone forth from thence, he came in the spring time to the land which leadeth to Ephrata: wherein when Rachel was in travail,\n"
	"because of difficulty in her travail, she began to be in danger, and the midwife said unto her: Fear not, for thou shalt have also this a son.\n"
	"And her soul departing for pain, and death now at hand, she called the name of her son Benoni, that is the son of my pain: but his father called him Benjamin, that is the son of the right hand.\n"
	"Rachel therefore died, and was buried in the high way that leadeth to Ephrata, this same is Bethleem.\n"
	"And Jacob erected a title over her sepulchre: This is the title of Rachel's monument, until this present day.\n"
	"Departing thence, he pitched his tent beyond the Flock tower.\n"
	"And when he dwelt in that country, Ruben went, and slept with Bala his father's concubine: which thing he was not ignorant of. And the sons of Jacob were twelve.\n"
	"The sons of Lia: Ruben the first begotten, and Simeon, and Levi, and Judas, and Issachar, and Zabulon.\n"
	"The sons of Rachel: Joseph and Benjamin.\n"
	"The sons of Bala Rachel's handmaid: Dan and Nephthali.\n"
	"The sons of Zelpha Lia's handmaid: Gad and Aser: these are the sons of Jacob, that were born to him in Mesopotamia of Syria.\n"
	"He came also to Isaac his father in Mambre, the city of Arbee, this is Hebron: wherein Abraham and Isaac sojourned.\n"
	"And the days of Isaac were complete an hundred eighty years.\n"
	"And spent with age he died, and was put to his people, being old and full of days, and Esau and Jacob his sons buried him.";