const char* chap350 = "These also came to David into Siceleg, when as yet he fled from Saul the son of Cis, the which were most valiant and excellent warriors,\n"
	"drawing the bow & hurling with both hands stones in slings, & shooting arrows directly: of the brethren of Saul of Benjamin.\n"
	"The Prince Ahiezer, and Joas the sons of Samaa a Gabaathite, and Jaziel, and Phallet the sons of Azmoth, and Beracha, and Jehu an Anothothite.\n"
	"Samaias also a Gabaonite the most valiant amongst the thirty and above the thirty. Jeremias, and Jeheziel, and Johanan, & Jezabad a Gaderothite.\n"
	"And Eluzai, and Jerimuth, and Baalia, & Samaria, and Saphatia an Haruphite.\n"
	"Elcana, and Jesia, and Azareel, and Joezer, and Jesbaam of Carehim:\n"
	"Joela also, and Zabadia the sons of Jeroham of Gedor.\n"
	"Yea and of Gaddi also there fled to David, when he lay hid in the desert most valiant men, & the best warriors, holding shield and spear: their faces as the faces of a lion, & swift as the roe-bucks on the mountains:\n"
	"Ezer the Prince, Obdias the second, Eliab the third,\n"
	"Masmana the fourth, Jeremias the fifth,\n"
	"Ethi the sixth, Eliel the seventh,\n"
	"Johanan the eight, Elzebad the ninth,\n"
	"Jeremias the tenth, Machbanai the eleventh,\n"
	"these of the children of Gad were the Princes of his army. The meanest was captain over an hundred soldiers, & the greatest, over a thousand.\n"
	"These are they which passed Jordan the first month, when it used to flow over his banks: & they chased away all that dwelt in the valleys toward the east quarter and the west.\n"
	"And there came also of Benjamin, & of Juda to the hold, wherein David abode.\n"
	"And David went out to meet them, & said: If you be come peaceably to me for to help me, my heart be joined to you, but if you lie in wait against me for my adversaries, whereas I have no iniquity in my hands, the God of our fathers see, and judge.\n"
	"But the spirit came on Amasai the Prince among thirty, & he said: We are thine, o David, & with thee, o son of Isai: peace, peace be to thee, and peace to thy helpers, for thy God helpeth thee. David therefore received them, and appointed them Princes of the band.\n"
	"Moreover of Manasses there fled to David, when he came with the Philisthiims against Saul to fight, and he fought not with them: because the Princes of the Philisthiims taking counsel sent him back, saying: with the peril of our head will he return to his Lord Saul.\n"
	"Therefore when he returned into Siceleg, there fled to him of Manasses, Ednas, and Jozabab, and Jedihel, and Michael, and Ednas, & Jozabad, and Eliu, and Salathi, the Princes of a thousand in Manasses.\n"
	"These did aid David against the rovers: for they were all most valiant men, & were made commanders in the army.\n"
	"Yea & there came every day to David to help him, till it became a great number, as it were the army of God.\n"
	"This also is the number of the commanders of the army, which came to David, when he was in Hebron, to transfer the kingdom of Saul to him, according to the word of our Lord.\n"
	"The children of Juda bearing shield and spear, six thousand eight hundred well appointed to battle.\n"
	"Of the children of Simeon valiant men to fight, seven thousand one hundred.\n"
	"Of the children of Levi, four thousand six hundred.\n"
	"Joiada also Prince of the stock of Aaron, and with him three thousand seven hundred.\n"
	"Sadoc also a young man of goodly towardness, and the house of his father, Princes twenty two.\n"
	"And of the children of Benjamin the brethren of Saul, three thousand: for a great part of them as yet followed the house of Saul.\n"
	"Moreover of the children of Ephraim twenty thousand eight hundred valiant of strength, men renowned in their kindreds.\n"
	"And of the half tribe of Manasses, eighteen thousand, every one by their names, came to make David king.\n"
	"Also of the children of Issachar men of understanding, that knew all times to command what Israel should do, Princes two hundred: and all the rest of the tribe did follow their counsel.\n"
	"Moreover of Zabulon such as went forth to battle, and stood in array well appointed with armour of war, there came fifty thousand to aid, not in a double heart.\n"
	"And of Nephthali, commanders a thousand & with them furnished with shield & spear, seven & thirty thousand.\n"
	"Of Dan also prepared to battle, twenty eight thousand six hundred.\n"
	"And of Aser going forth to fight, & provoking in battle, forty thousand.\n"
	"And beyond Jordan of the children of Ruben & of Gad, & the half part of the tribe of Manasses, furnished with armour of war, an hundred twenty thousand.\n"
	"All these men of war well appointed to fight, with perfect heart came into Hebron, to make David king over all Israel: yea & all the rest of Israel were of one heart, that David should be made king.\n"
	"And they were there with David three days eating and drinking: for their brethren had prepared for them.\n"
	"Yea and they that were near them as far as Issachar, and Zabulon, and Nephthali, brought loaves on Asses, and on camels, and on mules, and upon oxen, to eat: meal, figs, raisins, wine, oil, beeves, muttons, in all aboundance, for there was joy in Israel.";