const char* chap360 = "And David said: This is the house of God, and this is an altar for holocaust to Israel.\n"
	"And he commanded that the proselytes of the land of Israel should be gathered together, and he appointed of them masons to hew stones and polish them, that the house of God might be built.\n"
	"David prepared also very much iron for the nails of the gates, and for the joinings and jointures: & of brass an innumerable weight.\n"
	"The cedar-trees also could not be esteemed, which the Sidonians and Tyrians brought down to David.\n"
	"And David said: Salomon my son is yet a little child and delicate, and the house which I would have to be builded to our Lord, must be such as may be renowned in all countries: I therefore will prepare him necessaries. And for this cause before his death he prepared all the expenses.\n"
	"And he called Salomon his son: and commanded him that he should build a house to our Lord the God of Israel.\n"
	"And David said to Salomon: My son, it was my will to have built a house to the name of our Lord my God.\n"
	"But the word of our Lord was made to me, saying: Thou hast shed much blood, and fought very many battles, thou canst not build a house to my name, so much blood being shed before me:\n"
	"the son, which shall be born to thee, shall be a most quiet man: for I will make him rest from all his enemies round about: and for this cause, he shall be called Peaceable: and I will give peace and quietness in Israel all his days.\n"
	"He shall build a house to my name, and he shall be to me for a son, and I will be to him for a father: and I will establish the throne of his Kingdom over Israel for ever.\n"
	"Now therefore my son, Our Lord be with thee, and do thou prosper, and build the house of our Lord thy God, as he hath spoken of thee.\n"
	"Our Lord also give thee wisdom and understanding, that thou mayst be able to rule Israel, and to keep the law of our Lord thy God.\n"
	"For then thou shalt be able to prosper, if thou shalt keep the commandments, and judgments, which our Lord commanded Moyses to teach Israel: take courage and play the man, fear not, neither be dismayed.\n"
	"Behold I in my poverty have prepared the charges of the house of our Lord, of gold an hundred thousand talents, and of silver a thousand thousand talents, but of brass, & of iron there is no weight, for the number is surpassed with the greatness: timber & stones I have prepared to all the charges.\n"
	"Thou hast also very many artificers, hewers of stones, and masons, and carpenters, and of all occupations most skillful to make work\n"
	"in gold and silver and brass and iron, whereof there is no number. Rise therefore, and do it, and our Lord will be with thee.\n"
	"David also commanded all the Princes of Israel, that they should help Salomon his son.\n"
	"You see, quoth he, that our Lord your God is with you, and hath given you rest round about, and hath delivered all your enemies into your hands, and the land is subdued before our Lord, and before his people.\n"
	"Give therefore your heart and your souls, to seek our Lord your God: and arise, and build a sanctuary to our Lord God, that the Ark of the covenant of our Lord, and the vessels consecrated to our Lord, may be brought into the house, which is built to the name of our Lord.";