const char* chap362 = "Moreover to the sons of Aaron these were the partitions: The sons of Aaron: Nadab, and Abiu, and Eleazar, and Ithamar.\n"
	"But Nadab and Abiu died before their father without children: and Eleazar and Ithamar did the function of priesthood.\n"
	"And David divided them, that is, Sadoc of the sons of Eleazar, and Ahimelech of the sons of Ithamar, according to their courses and ministry.\n"
	"And there were found many more children of Eleazar among the principal men, than children of Ithamar. And he divided to them, that is, to the children of Eleazar, Princes by their families sixteen: and to the children of Ithamar by their families and houses eight.\n"
	"Moreover he divided both families between themselves by lots: for there were Princes of the Sanctuary, and Princes of God, as well of the children of Eleazar, as of the children of Ithamar.\n"
	"And Semeias wrote them, the son of Nathanael the Scribe a Levite, before the king and Princes, and Sadoc the Priest, and Ahimelech the son of Abiathar, the Princes also of the Priestly and Levitical families: one house, which was over the rest, Eleazar's, and another house, which had the rest under it, Ithamar's.\n"
	"And the first lot came forth to Joiarib, the second to Jedei,\n"
	"the third to Harim, the fourth to Seorim,\n"
	"the fifth to Melchia, the sixth to Maiman,\n"
	"the seventh to Accos, the eighth to Abia,\n"
	"the ninth to Jesua, the tenth to Sechenia,\n"
	"the eleventh to Eliasib, the twelfth to Jacim,\n"
	"the thirteenth to Hoppha, the fourteenth to Isbaab,\n"
	"the fifteenth to Belga, the sixteenth to Emmer,\n"
	"the seventeenth to Hezir, the eighteenth to Aphses,\n"
	"the nineteenth to Pheteia, the twentieth to Hezechiel,\n"
	"the one and twentieth to Jachin, the two and twentieth to Gamul,\n"
	"the three and twentieth to Dalaiau, the four and twentieth to Maaziau.\n"
	"These be their courses according to their ministries, to enter into the house of our Lord, and according to their rite under the hand of Aaron their father: as our Lord the God of Israel had commanded.\n"
	"Moreover of the children of Levi, which were remaining, there was Subael of the children of Amram: and of the children of Subael, Jehedeia.\n"
	"Also of the children of Rohobia the Prince of Jesias.\n"
	"And the son of Isaari Salemoth, & the son of Salemoth Jahath:\n"
	"and his son Jeriau the first, Amarias the second, Jahaziel the third, Jecmaan the fourth.\n"
	"The son of Oziel, Micha: the son of Micha, Samir.\n"
	"The brother of Micha, Jesia: and the son of Jesia, Zacharias.\n"
	"The sons of Merari: Moholi and Musi. The son of Oziau: Benno.\n"
	"The son also of Merari: Oziau, and Soam, and Zacchur, and Hebri.\n"
	"Moreover the son of Moholi: Eleazar, who had no children.\n"
	"And the son of Cis, Jeramael.\n"
	"The sons of Musi: Moholi, Eder, and Jerimoth. These be the sons of Levi according to the houses of their families.\n"
	"And they also did cast lots against their brethren the sons of Aaron before David the king, and Sadoc, and Ahimelech, and the Princes of the Priestly and Levitical families, as well the elder as the younger. Lot divided all equally.";