const char* chap364 = "And the divisions of the porters: of the Corites Meselemia, the son of Core, of the sons of Asaph.\n"
	"The sons of Meselemia: Zacharias the first-begotten, Jadihel the second, Zabadias the third, Jathanael the fourth,\n"
	"Aelam the fifth, Johanan the sixth, Elioenai the seventh.\n"
	"And the sons of Obededom Semeias the first-begotten, Jozabad the second, Joaha the third, Sachar the fourth, Nathanael the fifth,\n"
	"Ammiel the sixth, Issachar the seventh, Phollathi the eight: because our Lord blessed him.\n"
	"And to Semei his son were born sons, the chief of their families: for they were most valiant men.\n"
	"The sons then of Semeias: Othni, and Raphael, and Obed, Elizabad, and his brethren most valiant men: Eliu also, and Samachias.\n"
	"All these of the sons of Obededom: they, & their sons, & their brethren most able to minister, sixty two of Obededom.\n"
	"Moreover the sons of Meselemia, and their brethren most strong, eighteen.\n"
	"And of Hosa, that is, of the sons of Merari: Semri the Prince (for he had not a first-begotten, and therefore his father made him chief)\n"
	"Helcias the second, Tabelias the third, Zacharias, the fourth: all these the sons, and brethren of Hosa, thirteen.\n"
	"These were divided into porters, that the Princes also of the watches, even as their brethren, might minister in the house of our Lord.\n"
	"Lots therefore were cast equally, both to little, and great, by their families, for every one of the gates.\n"
	"The lot then of the East fell to Selemia. Moreover to Zacharias his son, a most wise man, and skillful, the North quarter chanced by lot.\n"
	"But to Obededom and his sons, toward the South: in which part of the house was the Council of the ancients.\n"
	"Sephim, and Hosa toward the West, by the gate which leadeth to the way of ascent: watch against watch.\n"
	"And toward the East six Levites: and toward the North four a day: and toward the South likewise in a day four: and where the Council was, two and two.\n"
	"In the cells also of the porters toward the West four in the way: and two at every cell.\n"
	"These be the divisions of the porters of the sons of Core, and of Merari\n"
	"Moreover Achias was over the treasures of the house of God, and the vessels of the holy places.\n"
	"The sons also of Ledan, the sons of Gersonni: of Ledan princes of the families, Ledan, and Gersonni, Jehieli.\n"
	"The sons of Jehieli: Zathan, and Joel, his brethren over the treasures of the house of our Lord,\n"
	"to the Amramites, and Isaarites, and Hebronites, and Ozielites.\n"
	"And Subael the son of Gersom, the son of Moyses, chief over the treasures.\n"
	"His brethren also Eliezer, whose son Rahabia, and his son Isaias, and his son Joram, his son also Zechri, and his son Selemith.\n"
	"Selemith himself, and his brethren over the treasures of the sanctified holy things, which David the king sanctified, and the Princes of families, and the centurions, and the captains of the host\n"
	"of the wars, and of the spoils of the battles, which they had consecrated to the maintenance and furniture of the temple of our Lord.\n"
	"And all these things did Samuel the Seer sanctify, and Saul the son of Cis, and Abner the son of Ner, and Joab the son of Sarvia: and all that had sanctified them by the hand of Selemith, and of his brethren.\n"
	"But the chief over the Isaarites was Chonenias, and his sons, to the works abroad over Israel, to teach and judge them.\n"
	"Moreover the Hebronites Hasabias, and his brethren most able men, a thousand seven hundred were chief over Israel beyond Jordan against the West, in all the works of our Lord, & for the ministry of the king.\n"
	"And the Prince of the Hebronites was Jeria according to their families and kindreds. In the fortieth year of king David they were numbered, and there were found most valiant men in Jazer Galaad,\n"
	"and his brethren of stronger age, two thousand seven hundred Princes of families. And David the king made them overseers over the Rubenites and the Gaddites, and the half tribe of Manasses, for all the ministry of God, and the king.";