const char* chap365 = "And the children of Israel according to their number, the Princes of families, tribunes, and centurions, and overseers, that ministered to the king according to their companies, coming in and going out every month in the year, every one was chief over four and twenty thousand.\n"
	"Over the first company the first month Jesboam was chief the son of Zabdiel, and under him four & twenty thousand.\n"
	"Of the sons of Phares, the Prince of all the Princes in the host the first month.\n"
	"The company of the second month had Dudia an Ahohite, & after him another named Macelloth, which governed part of four and twenty thousand.\n"
	"Captain also of the third company in the third month, was Banaias the son of Joiada the Priest: and in his division four and twenty thousand.\n"
	"The same is Banaias the most valiant among thirty, and above the thirty, and over his company Amizabad his son was chief.\n"
	"The fourth, in the fourth month, Asahel the brother of Joab, and Zabadias his son after him: and in his company four and twenty thousand.\n"
	"The fifth, in the fifth month, Prince Samaoth, a Jezerite: and his company four and twenty thousand.\n"
	"The sixth, in the sixth month, Hira the son of Acces a Thecuite: and in his company four and twenty thousand.\n"
	"The seventh, in the seventh month, Helles a Phallonite of the children of Ephraim: and in his company four and twenty thousand.\n"
	"The eight, in the eighth month, Sobochai an Husathite of the stock of Sarahi: and in his company four and twenty thousand.\n"
	"The ninth, in the ninth month, Abiezer an Anathothite of the children of Jemini: and in his company four and twenty thousand.\n"
	"The tenth, in the tenth month, Marai, & he a Netophathite of the stock of Zarahi: & in his company four and twenty thousand.\n"
	"The eleventh in the eleventh month, Banaias, a Pharathonite of the children of Ephraim: & in his company four & twenty thousand.\n"
	"The twelfth, in the twelfth month, Holdai a Netophathite, of the stock of Gothoniel: and in his company four and twenty thousand.\n"
	"Furthermore there were chief over the tribes of Israel, over the Rubenites, Duke Eliezer the son of Zechri: over the Simeonites, Duke Saphatias the son of Maacha:\n"
	"over the Levites, Hasabias the son of Camuel: over the Aaronites, Sadoc:\n"
	"over Juda, Eliu the brother of David: over Issachar, Amri the son of Michael:\n"
	"over the Zabulonites, Jesmaias the son of Abdias: over the Nephthalites, Jerimoth the son of Ozriel:\n"
	"over the children of Ephraim, Osee the son of Ozaziu: over the half tribe of Manasses, Joel the son of Phadaia:\n"
	"and over the half tribe of Manasses in Galaad, Jaddo the son of Zacharias: and over Benjamin, Jasiel the son of Abner.\n"
	"But over Dan, Ezrihel the son of Jeroham: these be the Princes of the children of Israel.\n"
	"And David would not number them from twenty years downward: because our Lord had said that he would multiply Israel as the stars of heaven.\n"
	"Joab the son of Sarvia began to number, and finished not: because upon this there fell wrath upon Israel: and therefore the number of them that were numbered, was not registered in the chronicles of king David.\n"
	"And over the king's treasures was Azmoth the son of Adiel, and over those treasures, which were in the cities, and in the towns, and in the towers, Jonathan the son of Ozias was president.\n"
	"And over husbandry, and the husbandmen, which tilled the ground, Ezri the son of Chelub was overseer:\n"
	"and over the dressers of vineyards, Semeias a Romathite: and over the wine cellars, Zabdias an Aphonite.\n"
	"For over the Olivets and the fig grooves, which were in the champion, was Balanam a Gederite: and over the oil cellars, Joas.\n"
	"Furthermore over the herds that fed in Saron, the overseer was Setrai a Saronite: and over the oxen in the valleys, Saphat the son of Adli:\n"
	"but over the camels, Ubil an Ismaelite: and over the asses, Jadias a Meronathite:\n"
	"over the sheep also Jaziz an Agarene all these, Princes of the substance of king David.\n"
	"And Jonathan David's uncle, a counsellor, a man wise and learned: He and Jahiel the son of Hachamoni were with the king's sons.\n"
	"Achitophel also the king's counsellor, and Chusai an Arachite the king's friend.\n"
	"After Achitophel was Joiada the son of Banaias, and Abiathar. And the Prince of the king's army was Joab.";