const char* chap368 = "Salomon therefore the son of David was strengthened in his Kingdom, and our Lord was with him, and magnified him on high.\n"
	"And Salomon commanded all Israel, the tribunes, and the centurions, & the dukes, and judges of all Israel, and the Princes of the families:\n"
	"and he went with all the multitude into the Excelse of Gabaon, where was the tabernacle of the covenant of our Lord, which Moyses the servant of God made, in the wilderness.\n"
	"For David had brought the Ark of God from Cariathiarim into the place, which he had prepared for it, & where he had pitcht a tabernacle for it, that is, in Jerusalem:\n"
	"The altar also of brass, which Beseleel the son of Uri the son of Hur had made, was there before the tabernacle of our Lord: which also Salomon sought, and all the assembly.\n"
	"And Salomon went up to the altar of brass, before the tabernacle of the covenant of our Lord, and offered on it a thousand hosts.\n"
	"And behold in that very night God appeared to him, saying: Ask what thou wilt that I may give it thee.\n"
	"And Salomon said to God: Thou hast done great mercy with my father David: and hast made me king for him.\n"
	"Now therefore Lord God be thy word fulfilled, which thou hast promised to David my father: for thou hast made me king over thy people great in number, which is so innumerable as the dust of the earth.\n"
	"Give me wisdom and intelligence, that I may come in and go out before thy people: for who can worthily judge this thy people, which is so great?\n"
	"And God said to Salomon: Because this rather hath pleased thy heart, and thou hast not asked riches, and substance, and glory, nor their lives that hate thee, no nor many days of life: but hast desired wisdom and knowledge, that thou mayst be able to judge my people, over which I have made thee king:\n"
	"Wisdom and knowledge are given thee: and riches, and substance, and glory I will give thee, so that none among the kings neither before thee, nor after thee shall be like thee.\n"
	"Salomon therefore came from the Excelse of Gabaon into Jerusalem before the tabernacle of covenant, and reigned over Israel.\n"
	"And he gathered to him chariots and horsemen, and there amounted to him a thousand four hundred chariots, and twelve thousand horsemen: and he caused them to be in the cities of the chariots, and with the king in Jerusalem.\n"
	"And the king gave silver and gold in Jerusalem as stones, and cedar-trees as sycamores, which grow in the champion in great multitude.\n"
	"And there were horses brought him from Aegypt, and from Coa by the king's merchants, which went, and bought by a price,\n"
	"a chariot of four horses for six hundred pieces of silver, & an horse for an hundred fifty: in like manner of all the kingdoms of the Hetheites, and of the kings of Syria market was made.";