const char* chap370 = "And Salomon began to build the house of our Lord in Jerusalem, in mount Moria, which had been shewed to David his father, in the place, which David had prepared in the floor of Ornan the Jebusite.\n"
	"And he began to build in the second month, in the fourth year of his Kingdom.\n"
	"And these be the foundations, which Salomon laid, to build the house of God, of length in the first measure sixty cubits, of breadth twenty cubits.\n"
	"But the porch before the front, which was extended in length according to the measure of the breadth of the house, of twenty cubits: moreover the height was of an hundred twenty cubits: and he did gild it on the inside with most pure gold.\n"
	"Also the greater house he covered with wooden boards of fir tree, & he fastened on plates of fine gold throughout: and he graved in it palm-trees, and as it were little chains embracing one another.\n"
	"He paved also the floor of the Temple with most precious marble, in much beauty.\n"
	"Moreover it was most tried gold, of the plates whereof he covered the house, and the beams thereof, and the posts, and the walls, and the doors: and he graved Cherubs in the walls.\n"
	"He made also the house of Sanctum Sanctorum: the length according to the breadth of the house, of twenty cubits: and the breadth likewise of it twenty cubits: and he covered it with plates of gold, as it were six hundred talents.\n"
	"Yea and he made nails of gold, so that every nail weighed fifty sicles a piece: the upper chambers also he covered with gold.\n"
	"He made also in the house of Sanctum Sanctorum two Cherubs of statuary work: and he covered them with gold.\n"
	"The wings of the Cherubs were extended twenty cubits, so that one wing had five cubits, and touched the wall of the house: and the other having five cubits, touched the wing of the other Cherub.\n"
	"In like manner the wing of the other Cherub, had five cubits, and touched the wall: and his other wing of five cubits, touched the wing of the other Cherub.\n"
	"Therefore the wings of both the Cherubs were spread forth, and were extended twenty cubits: and they stood upright on their feet, and their faces were turned to the utter house.\n"
	"He made also a veil of hyacinth, purple, scarlet, and silk: & wove in it Cherubs.\n"
	"Before the doors also of the temple two pillars, which had five and thirty cubits in height: moreover their heads, of five cubits.\n"
	"Moreover also as it were little chains in the oracle, and he put them to the heads of the pillars: pomegranates also an hundred, which he put between the little chains.\n"
	"The pillars also themselves he put in the entrance of the temple, one on the right hand, and the other on the left: that, which was on the right hand, he called Jachin: and that on the left hand, Boz.";