const char* chap371 = "He made also an altar of brass of twenty cubits in length, and of twenty cubits in breadth, and of ten cubits in height.\n"
	"A Sea also cast, ten cubits from brim to brim, round in compass: it had five cubits in height, and a cord of thirty cubits did compass it round about.\n"
	"There was also under it the similitude of oxen, and certain engravings of ten cubits on the outside compassed the belly of the Sea, as it were with two rews.\n"
	"and the oxen were cast: and the Sea it-self was set upon the twelve oxen, of the which three looked toward the North, and other three to the West: moreover other three to the South, and the three that remained, to the East, having the Sea put upon them: and the hinder parts of the oxen were inward under the sea.\n"
	"Moreover the thickness thereof had the measure of a palm, and the brim thereof was as it were the brim of a chalice, or of a crisped lily: and it held three thousand metretes.\n"
	"He made also ten lavatories: and set five on the right hand, and five on the left, that they might wash in them all things, that they would offer for holocaust: moreover in the Sea the Priests were washed.\n"
	"And he made also ten golden candlesticks, according to the fashion which they were commanded to be made by: and he set them in the temple, five on the right hand, and five on the left.\n"
	"Moreover also ten tables: and he set them in the temple, five on the right hand, and five on the left. Phials also of gold an hundred.\n"
	"He made also the court of the Priests, and a great hall: and doors in the hall, which he covered with brass.\n"
	"Moreover he set the Sea on the right side against the East toward the South.\n"
	"And Hiram made cauldrons, and flesh-hooks, and phials: and accomplished all the king's work in the house of God:\n"
	"that is to say, two pillars, and the chapiters and the heads, and as it were certain little nets, which should cover the heads over the chapiters.\n"
	"Pomegranates also four hundred, and two little nets, so that two rews of the pomegranates were joined to each little net, which covered the pommels, and the heads of the pillars.\n"
	"He made feet also, and lavatories, which he put upon the feet:\n"
	"one sea, also twelve oxen under the sea.\n"
	"And the cauldrons, and flesh-hooks, and phials. All the vessels did Hiram his father make for Salomon in the house of our Lord of most pure brass.\n"
	"In the country of Jordan did the king cast them, in a clay ground between Socot and Saredatha.\n"
	"And the multitude of vessels was innumerable, so that the weight of the brass was not known.\n"
	"And Salomon made all the vessels of the house of God, and the golden altar, and the tables, and upon them the loaves of proposition,\n"
	"the candlesticks also with their lamps to give light before the oracle, according to the rite, of most pure gold:\n"
	"and certain flourishing things, and lamps, and golden tongs all were made of most fine gold.\n"
	"The vessels also of perfume and censers, and phials, and little mortars, of most pure gold. And he graved the doors of the inner temple, that is, in Sancta Sanctorum: and the doors of the temple without^ of gold. And so all the work was finished which Salomon made in the house of our Lord.";