const char* chap373 = "Then Salomon said: Our Lord promised that he would dwell in darkness:\n"
	"and I have built a house to his name, that he might dwell there for ever.\n"
	"And the king turned his face, and blessed all the multitude of Israel (for all the multitude stood attent) and said:\n"
	"Blessed be our Lord the God of Israel, who in work hath accomplished that, which he spake to David my father, saying:\n"
	"From the day, that I brought my people out of the Land of Aegypt, I chose not a city of all the tribes of Israel, that a house might be built in it to my name: neither did I choose any other man, to be Duke in my people Israel.\n"
	"but I chose Jerusalem, that my name may be in it: and I chose David, that I might appoint him over my people Israel.\n"
	"And whereas David my father had meant to build a house to the name of our Lord the God of Israel,\n"
	"our Lord said to him: Because thy will was this, that thou wouldest build a house to my name, thou hast done well certes to have such a will:\n"
	"howbeit thou shalt not build the house, but thy son, which shall come out of thy loins, he shall build a house to my name.\n"
	"Our Lord therefore hath accomplished his word, which he spake: and I am risen for David my father, and sit upon the throne of Israel, as our Lord hath spoken: and have built a house to the name of our Lord the God of Israel.\n"
	"And I have put in it the Ark, wherein is the covenant of our Lord, which he made with the children of Israel:\n"
	"He therefore stood before the Altar of our Lord, over against all the multitude of Israel, and stretched forth his hands.\n"
	"For Salomon had made an eminent place of brass, and had put it in the midst of the temple, having five cubits of length, and breadth, & three of height: & he stood upon it: and afterward kneeling over against all the multitude of Israel, and his hands lifted up toward heaven,\n"
	"he said: Lord God of Israel, there is not the like God to thee in heaven and in earth: which keepest covenant and mercy with thy servants, that walk before thee in all their heart:\n"
	"which hast performed to thy servant David my father what things soever thou hadst spoken to him: and the things that by mouth thou hadst promised, in work thou hast accomplished, as also the present time proveth.\n"
	"Now therefore Lord God of Israel, fulfill to thy servant my father David, what soever thou didst speak to him, saying: There shall not fail of thee a man before me, to sit upon the throne of Israel: yet so if thy children keep their ways, and walk in my law, as thou also hast walked before me.\n"
	"And now Lord God of Israel, be thy word confirmed, which thou hast spoken to thy servant David.\n"
	"Is it credible then that God should dwell with men upon the earth? If heaven & the heavens of heavens do not take thee, how much more this house, which I have built?\n"
	"But to this end only it is made, that thou shouldest respect the prayer of thy servant, & his supplication Lord my God: and mayst hear the prayers, which thy servant poureth out before thee:\n"
	"that thou open thine eyes upon this house days and nights, upon the place, wherein thou hast promised that thy name should be invocated,\n"
	"and wouldest hear the prayer, which thy servant prayeth in it: and mayst hear the prayers of thy servant, and of thy people Israel. Whosoever shall pray in this place, hear out of thy habitation, that is^ from the heavens, & be propitious.\n"
	"If any man shall sin against his neighbour, and come ready to swear against him, and bind himself with a curse before the altar in this house:\n"
	"thou shalt hear from heaven, and shalt do the judgment of thy servant, so that thou render to the unjust his way upon his own head, and revenge the just, rewarding him according to his justice.\n"
	"If thy people Israel shall be overcome of their enemies (for they will sin to thee) & converted shall do penance, and beseech thy name, and pray in this place,\n"
	"thou shalt hear from heaven, and be thou propitious to the sin of thy people Israel, and reduce them into the land, which thou gavest them, and their fathers.\n"
	"If the heaven being shut, there fall no rain for the sins of the people, and they shall beseech thee in this place, and shall confess to thy name, & shall be converted from their sins, when thou shalt afflict them,\n"
	"hear from heaven o Lord, and forgive the sins of thy servants and of thy people Israel, and teach them the good way, by the which they may go: and give rain to thy land, which thou hast given thy people to possess.\n"
	"If famine shall arise in the land, and pestilence, rust, and blast, and locust, & bruch, and the enemies, wasting the countries, shall besiege the gates of the city, and all plague and infirmity shall press them:\n"
	"if any of thy people Israel shall pray, knowing their plague and infirmity, and shall spread forth their hands in this house,\n"
	"thou shalt hear from heaven, to wit, out of thy high habitation, & be thou propitious, & render to every one according to his ways which thou knowest him to have in his heart: (for thou only knowest the hearts of the children of men:)\n"
	"that they may fear thee, & walk in thy ways all the days, that they live upon the face of the land, which thou hast given to our fathers.\n"
	"The Foreigner also, which is not of thy people Israel, if he come from a far country, for thy strong hand, & thy stretched out arm, and adore in this place:\n"
	"thou shalt hear from heaven thy most firm habitation, and shalt do all things, for the which that pilgrim shall invocate thee: that all the peoples of the earth may know thy name, and may fear thee, as thy people Israel, and may know, that thy name is invocated upon this house, which I have built.\n"
	"If thy people shall go forth to war against their adversaries, by the way that thou shalt send them. Shall adore thee against the way wherein is this city, which thou hast chosen, & the house, which I have built to thy name:\n"
	"thou shalt from heaven hear their prayers, and petition, and do thou revenge.\n"
	"And if they shall sin to thee (for there is no man that sinneth not) & thou be angry with them, and deliver them to the enemies, and they lead them captive into a far country, or which is near at the least,\n"
	"and being converted in their heart in the land, to the which they were led captive, shall do penance, and shall beseech thee in the land of their captivity, saying: We have sinned, we have done wickedly, we have dealt unjustly:\n"
	"and shall return to thee in all their heart, and in all their soul, in the land of their captivity, to the which they were led, shall adore thee against the way of their land, which thou gavest their fathers, & of the city, which thou hast chosen, & of the house, which I have built to thy name:\n"
	"thou shall hear from heaven, that is, from thy firm habitation their prayers, and do thou judgment, and forgive thy people, although sinful:\n"
	"for thou art my God: let thine eyes, I beseech thee, be opened, and let thine ears be attent to the prayer, that is made in this place.\n"
	"Now therefore arise Lord God in thy rest, thou and the Ark of thy strength: Let thy Priests Lord God put on salvation, and thy Saints rejoice in good things.\n"
	"Lord God turn not away from the face of thy Christ: remember the mercies of David thy servant.";