const char* chap379 = "And when the kingdom of Roboam was strengthened and fortified, he forsook the law of our Lord, and all Israel with him.\n"
	"And in the fifth year of the kingdom of Roboam came up Sesac the king of Aegypt into Jerusalem (because they had sinned to our Lord)\n"
	"with a thousand two hundred chariots, and threescore thousand horsemen: neither was any number of the common people, that came with him out of Aegypt, to wit, Libyans, and Troglodytes, and Aethiopians.\n"
	"And he took the most fenced cities in Juda, and came over unto Jerusalem.\n"
	"And Semeias the Prophet went to Roboam, and to the Princes of Juda, that were gathered together in Jerusalem, flying from Sesac, and he said to them: Thus saith our Lord: You have left me, and I have left you in the hand of Sesac.\n"
	"And the Princes of Israel, and the king, being astonished, said: Our Lord is just.\n"
	"And when our Lord had seen that they were humbled, the word of our Lord came to Semeias, saying: Because they are humbled, I will not destroy them, and I will give them a little aid, & my fury shall not drop upon Jerusalem by the hand of Sesac.\n"
	"But yet they shall serve him, that they may know the distance of my service, and of the service of the Kingdom of the earth.\n"
	"Therefore Sesac the king of Aegypt retired from Jerusalem, taking away the treasures of the house of our Lord, and of the king's house, & he took all things with him, and the golden shields that Salomon had made,\n"
	"for the which the king made brazen ones, and delivered them to the Princes of the shield-bearers, which kept the entrance of the palace.\n"
	"And when the king entered into the house of our Lord, the shield-bearers came, and took them, and brought them back again to their armoury.\n"
	"But yet because they were humbled, the wrath of our Lord was turned away from them, neither were they utterly destroyed: for in Juda there were found good works.\n"
	"King Roboam therefore was strengthened in Jerusalem, and reigned: one & forty years old was he when he began to reign, and he reigned seventeen years in Jerusalem, the city which our Lord chose, to confirm his name there, out of all the tribes of Israel: and the name of his mother was Naama an Ammonite.\n"
	"And he did evil, and prepared not his heart to seek our Lord.\n"
	"But the works of Roboam the first and the last are written in the Books of Semeias the Prophet, and of Addo the Seer, and diligently expounded: and Roboam and Jeroboam fought one against the other all their days.\n"
	"And Roboam slept with his fathers, and was buried in the city of David. And Abias his son reigned for him.";