const char* chap38 = "The same time Judas going down from his brethren, turned in to a man an Odolamite, named Hiras.\n"
	"And he saw there the daughter of a man of Chanaan, called Sue: and taking her to wife, he did company with her.\n"
	"Who conceived, and bare a son, and called his name Her.\n"
	"And conceiving a child again, she called her son after he was born, Onan.\n"
	"She bare also the third, whom she called Sela: after whose birth, she ceased to bear any more.\n"
	"And Judas gave a wife to Her his first-begotten, named Thamar.\n"
	"Also Her the first-begotten of Judas, was wicked in the sight of our Lord, and was slain of him.\n"
	"Judas therefore said to Onan his son: Company with thy brother's wife, and be joined to her, that thou mayest raise seed to thy brother.\n"
	"He knowing that the children should not be born to himself, companying with his brother's wife, shed his seed upon the ground, lest children might be born in his brother's name.\n"
	"And therefore our Lord struck him, because he did a detestable thing.\n"
	"For the which cause Judas said to Thamar his daughter in law: Be a widow in thy father's house, till Sela my son grow up: for he feared lest he also might die, as his brethren. Who went her way and dwelt in her father's house.\n"
	"And after many days were come and gone, the daughter of Sue the wife of Judas died. Who after his mourning having received consolation, went up to the shearers of his sheep, himself and Hiras his shepherd of his flock, the Odolamite, into Thamnas.\n"
	"And it was told Thamar that her father in law came up into Thamnas to shear his sheep.\n"
	"Who putting off the garments of her widowhood, took a veil: and changing her habit, sat in the cross way that leadeth to Thamnas: because Sela was grown, and she had not taken him to her husband.\n"
	"Whom when Judas had seen, he supposed her to be an harlot: for she had covered her face, lest she should be known.\n"
	"And going unto her, he said: Suffer me to lie with thee: for he knew her not to be his daughter in law. Who answering: What wilt thou give me that thou mayest enjoy my company?\n"
	"He said: I will send thee a kid out of the flocks. And when she said again: I will suffer that thou wilt, if thou give me a pledge, till thou send that which thou dost promise;\n"
	"Judas said: What wilt thou to be given thee for a pledge? She answered: Thy ring, and bracelet, and staff which thou holdest in thy hand. The woman therefore by once companying conceived,\n"
	"and rising she went her way: and putting off the apparel which she had taken, put on the garments of her widowhood.\n"
	"And Judas sent a kid by his shepherd the Odolamite, that he might receive the pledge again, which he had given to the woman: who when he had not found her,\n"
	"he asked the men of that place: Where is the woman that sat in the cross way? All making answer: There was no harlot in this place,\n"
	"he returned to Judas, and said to him: I have not found her: yea the men also of that place said unto me, that there never sat harlot there.\n"
	"Judas said: Let her take it to her, surely she cannot charge us with a lie, I sent the kid which I promised: and thou didst not find her.\n"
	"And behold after three months they told Judas, saying: Thamar thy daughter in law hath played the harlot, and her belly seemeth to swell. And Judas said: Bring her forth that she may be burnt.\n"
	"Who when she was led to execution, she sent to her father in law, saying: By that man, whose these things are, have I conceived: look whose the ring is, and the bracelet, and the staff.\n"
	"Who acknowledging the gifts, said: She is juster than I: because I did not give her to Sela my son. But he knew her no more.\n"
	"And when she was ready to be brought to bed, there appeared twins in her belly: and in the very delivery of the infants, one put forth the hand, wherein the midwife tied a scarlet string, saying:\n"
	"This shall come forth the former.\n"
	"But he drawing back his hand, the other came forth: and the woman said: Why is the partition divided for thee? And for this cause called his name Phares.\n"
	"Afterward his brother came forth, in whose hand was the scarlet string: whom she called Zara.";