const char* chap380 = "In the eighteenth year of king Jeroboam, reigned Abias over Juda.\n"
	"Three years reigned he in Jerusalem, and his mother's name was Michaia, the daughter of Uriel of Gabaa: there was war between Abias & Jeroboam.\n"
	"And when Abias had begun battle, and had most warlike men, and of chosen ones four hundreth thousand: Jeroboam put his army in array on the contrary side, eight hundreth thousand men, who themselves also were chosen men, & most valiant to battles.\n"
	"Abias therefore stood upon mount Semeron, which was in Ephraim, and said: Hear Jeroboam, & all Israel:\n"
	"Are you ignorant that our Lord the God of Israel gave the kingdom to David over Israel for ever, to him & his children as a covenant of salt?\n"
	"And there rose up Jeroboam the son of Nabat, the servant of Salomon the son of David: and rebelled against his Lord.\n"
	"And there were gathered to him all the most vain men, and the children of Belial: and they prevailed against Roboam the son of Salomon: moreover Roboam was rude, and of a fearful heart, and could not resist them.\n"
	"Now therefore you say that you are able to resist the Kingdom of our Lord, which he possesseth by the children of David, and you have a great multitude of people, and golden calves, which Jeroboam hath made you for gods.\n"
	"And you have cast out the Priests of our Lord, the children of Aaron, & the Levites: and you have made you Priests, as all the peoples of the earth: who soever shall come and consecrate his hand in a bullock of oxen, and in seven rams, is made the Priest of them that are not gods.\n"
	"But our Lord is God, whom we forsake not, and the Priests do minister to our Lord of the children of Aaron, and the Levites are in their order.\n"
	"Holocausts also they do offer to our Lord, every day morning and evening, and incense made according to the precepts of the law, and the loaves are set forth on a most clean table, and there is with us the golden candlestick, and the lamps thereof, that they may be lighted always at evening: for we keep the precepts of the Lord our God, whom you have forsaken.\n"
	"Therefore in our host^ God is the Prince, & his Priests, which sound with trumpets, and resound against you: children of Israel fight not against our Lord the God of your fathers, because it is not expedient for you.\n"
	"He speaking these things, Jeroboam endeavoured to entrap him behind. And when he stood over against the enemies, he compassed Juda unwitting with his army.\n"
	"And Judas looking back, saw the battle at hand before and behind, and cried to our Lord: and the Priests began to sound with trumpets.\n"
	"And all the men of Juda made a shout: and behold they crying, God terrified Jeroboam, and all Israel that stood against Abias and Juda.\n"
	"And the children of Israel fled from Juda, and our Lord delivered them into their hand.\n"
	"Abias therefore and his people struck them with a great slaughter, and there fell wounded of Israel five hundreth thousand valiant men.\n"
	"And the children of Israel were humbled at that time, and the children of Juda exceedingly encouraged, because they had trusted in our Lord the God of their fathers.\n"
	"And Abias pursued Jeroboam flying, and he took his cities, Bethel and her daughters, & Jesana with her daughters, Ephron also and her daughters.\n"
	"Neither was Jeroboam able to resist any more, in the days of Abias: whom our Lord struck, and he died.\n"
	"Therefore Abias, his empire being strengthened, took fourteen wives: and he begat two and twenty sons, & sixteen daughters.\n"
	"But the rest of the words of Abias, and of his ways and words, are written diligently in the Book of Addo the Prophet.";