const char* chap381 = "And Abias slept with his fathers, and they buried him in the City of David: & Asa his son reigned for him, in whose days the land was quiet ten years.\n"
	"And Asa did that which was good and pleasing in the sight of his God, & he overthrew the altars of strange service, and the excelses,\n"
	"and brake the statues, and cut down the groves.\n"
	"And he commanded Juda that they should seek our Lord the God of their fathers, and should do the law, and all the commandments.\n"
	"And he took away out of all the cities of Juda the altars, & temples, and reigned in peace.\n"
	"He built also fenced cities in Juda, because he was quiet, and there had no battles risen in his time, our Lord giving peace.\n"
	"And he said to Juda: let us build these cities, and compass them with walls, and strengthen them with towers, and gates, & locks, whilst things are quiet from battles, because we have sought our Lord the God of our fathers, and he hath given us peace round about. They therefore did build, and there was no impediment in building.\n"
	"And Asa had in his army of them that carried shields and spears, of Juda three hundred thousand: and of Benjamin shield-bearers and archers, two hundred eighty thousand, all these were most valiant men.\n"
	"And Zara the Aethiopian with his army issued forth against them, ten hundred thousand, and with three hundred chariots: and he came as far as Maresa.\n"
	"Moreover Asa went on to meet him, and set his army in array to battle in the vale Sephata, which is near Maresa.\n"
	"And he invocated our Lord God, and said: Lord there is no difference with thee, whether thou help in few, or in many: help us o Lord our God: for having confidence in thee, & in thy name we are come against this multitude. Lord, thou art our God, let not man prevail against thee.\n"
	"Our Lord therefore terrified the Aethiopians before Asa and Juda: & the Aethiopians fled.\n"
	"And Asa pursued them, & the people that was with him, unto Gerara: & the Aethiopians fell to utter destruction because our Lord killing them, and his army fighting, they were destroyed. They took therefore many spoils,\n"
	"and they struck all the cities round about Gerara: for great terror had invaded all men: and they spoiled the cities, and carried away much prey.\n"
	"Yea and destroying the sheepcotes of sheep, they took an infinite multitude of cattle, and of camels: and returned into Jerusalem.";