const char* chap382 = "And Azarias the son of Oded, the Spirit of God coming upon him,\n"
	"went out to meet Asa, and said to him: Hear ye me Asa, and all Juda and Benjamin: Our Lord is with you, because you have been with him. If you will seek him, you shall find: but if you forsake him, he will forsake you.\n"
	"And many days shall pass in Israel without the true God, and without Priest a teacher, and without the Law.\n"
	"And when they shall return in their distress to our Lord the God of Israel, and shall seek him, they shall find him.\n"
	"At that time there shall not be peace to him that goeth out and cometh in, but terrors on every side in the inhabiters of the earth.\n"
	"For nation shall fight against nation, and city against city, because our Lord will trouble them with all distress.\n"
	"You therefore take courage, and let not your hands be dissolved: for there shall be reward to your work.\n"
	"Which when Asa had heard, to wit, the words, and the prophecy of Azarias the son of Oded the Prophet, he took courage, and took away the idols out of all the land of Juda, and out of Benjamin, and out of the cities, which he had taken, of mount Ephraim, and he dedicated the altar of our Lord, which was before the porch of our Lord.\n"
	"And he gathered together all Juda and Benjamin, & the strangers with them of Ephraim, and of Manasses, and of Simeon: for many were fled to him of Israel, seeing that our Lord his God was with him.\n"
	"And when they were come into Jerusalem the third month, in the fifteenth year of the reign of Asa,\n"
	"they immolated to our Lord in that day of the spoils and the prey that they had brought, oxen seven hundred, and rams seven thousand.\n"
	"And he went in after the manner to establish the covenant, that they should seek our Lord the God of their fathers in all their heart, and in all their soul.\n"
	"And if any man, quoth he, shall not seek our Lord the God of Israel, let him die, from the least to the greatest, from man unto woman.\n"
	"And they sware to our Lord with a loud voice in jubilation, and in noise of trumpet, and sound of shalms,\n"
	"all that were in Juda, with execration: for in all their heart did they swear, & with all their will did they seek him, & found him, & our Lord gave them rest round about.\n"
	"Yea & Maacha the mother of king Asa he deposed from the royal empire, because she had made in a grove the idol of Priapus: which he wholly destroyed, and breaking into pieces, burnt it in the Torrent cedron.\n"
	"But the Excelses were left in Israel: nevertheless the heart of Asa was perfect all his days.\n"
	"And those things which his father had vowed, and himself, he brought into the house of our Lord, gold and silver, and of vessels diverse furniture.\n"
	"And there was no war unto the five and thirtieth year of the reign of Asa.";