const char* chap385 = "Josaphat therefore was rich and very glorious, & was joined in affinity to Achab.\n"
	"And he went down to him after certain years into Samaria: at whose coming Achab killed muttons and oxen very many for him and the people that came with him: & he persuaded him to go up into Ramoth Galaad.\n"
	"And Achab the king of Israel said to Josaphat the king of Juda: Come with me into Ramoth Galaad. To whom he answered: As I am^ thou also: as thy people, so my people also: and we will be with thee in battle.\n"
	"Josaphat said to the king of Israel: Consult I beseech thee presently the word of our Lord.\n"
	"Therefore the king of Israel gathered together of the Prophets four hundred men, & said to them: Shall we go into Ramoth Galaad to fight, or sit still? But they said: Go up, say they, & God will deliver it into thy hand.\n"
	"And Josaphat said: Is there not here a Prophet of our Lord, that we may inquire also of him?\n"
	"And the king of Israel said to Josaphat: There is one man, of whom we may ask the will of our Lord: but I hate him, because he doth not prophesy me good, but evil at all times: and it is Micheas the son of Jemla. And Josaphat said: Speak not in this manner, o king.\n"
	"The king of Israel therefore called one of the Eunuchs, and said to him: Call quickly Micheas the son of Jemla.\n"
	"Moreover the king of Israel, and Josaphat the king of Juda, both sat in their thrones, clothed with kingly attire, and they sat in the court beside the gate of Samaria, and all the Prophets prophesied before them.\n"
	"But Sedecias the son of Chanaana made him horns of iron, and said: Thus saith our Lord: With these shalt thou strike Syria, till thou destroy it.\n"
	"And all the Prophets in like manner prophesied, and said: Go up into Ramoth Galaad, and thou shalt prosper, and our Lord will deliver them into the king's hand.\n"
	"And the messenger that went to call Micheas, said to him: Behold the words of all the Prophets with one mouth tell the king good things: I beseech thee therefore that thy word also dissent not from them, and that thou speak prosperous things.\n"
	"To whom Micheas answered: Our Lord liveth, whatsoever my God shall say to me, that will I speak.\n"
	"He therefore came to the king. To whom the king said: Micheas, shall we go into Ramoth Galaad to fight, or sit still? To whom he answered Go ye up: for all things shall fall out prosperous, and the enemies shall be delivered into your hands.\n"
	"And the king said: Again and again I adjure thee, that thou speak not to me, but that which is true in the name of our Lord.\n"
	"But he said: I saw all Israel disperst in the mountains, as sheep without a shepherd: & our Lord said: These have no masters: let every man return into his house in peace.\n"
	"And the king of Israel said to Josaphat: did I not tell thee that this man did not prophesy me any good, but those things that be evil?\n"
	"But he said: Hear ye therefore the word of our Lord: I saw our Lord sitting in his throne, and all the host of heaven assisting him on the right hand and on the left.\n"
	"And our Lord said: who shall deceive Achab the king of Israel, that he may go up and fall in Ramoth Galaad? And when one said in this manner, and another otherwise:\n"
	"there came forth a spirit, and stood before our Lord, & said: I will deceive him. To whom our Lord said: wherein wilt thou deceive him.\n"
	"But he answered: I will go forth, and will be a lying spirit in the mouth of all his Prophets. And our Lord said: Thou shalt deceive, and shalt prevail: go forth, and do so.\n"
	"Now therefore, behold our Lord hath given the spirit of lying in the mouth of all thy Prophets, and our Lord hath spoken of thee evil things.\n"
	"And Sedecias the son of Chanaana came, and struck the cheek of Micheas, and said: Which way passed the spirit of our Lord from me, that it should speak to thee.\n"
	"And Micheas said: Thou thyself shalt see in that day, when thou shalt enter into chamber out of chamber, to be hid.\n"
	"And the king of Israel commanded, saying: Take Micheas, and lead him to Amon the governor of the city, and to Joas the son of Amelech.\n"
	"And you shall say: Thus saith the king: Cast this fellow into prison, and give him a little bread, and a little water, till I return in peace.\n"
	"And Micheas said: If thou return in peace, our Lord hath not spoken in me, and he said: Hear all ye peoples.\n"
	"Therefore the king of Israel, & Josaphat the king of Juda, went up into Ramoth Galaad.\n"
	"And the king of Israel said to Josaphat: I will change my habit, and so I will go to the fight, but be thou clothed with thine own garments. And the king of Israel changing his habit came to the battle.\n"
	"And the king of Syria had commanded the captains of his horsemen saying: Fight not against the least, or against the greatest, but against the king of Israel only.\n"
	"Therefore when the Princes of the horsemen saw Josaphat, they said: This is the king of Israel. And they compassed him fighting: but he cried to our Lord, and he holp him, and turned them away from him.\n"
	"For when the captains of the horsemen saw, that it was not the king of Israel, they left him.\n"
	"And it chanced that one of the people shot an arrow at adventure, and struck the king of Israel between the neck & the shoulders, & he said to his coacher: Turn thy hand, & carry me out of the battle, because I am wounded.\n"
	"And the fight was ended in that day: moreover the king of Israel stood in his chariot against the Syrians until evening, and died at the sun set.";