const char* chap388 = "And Josaphat slept with his fathers, & was buried with them in the City of David: and Joram his son reigned for him.\n"
	"Who had brethren the sons of Josaphat, Azarias, and Jahiel, and Zacharias, & Azarias, & Michael, and Saphatias. All these were the sons of Josaphat the king of Juda.\n"
	"And their father gave them many gifts of silver, and of gold, and pensions, with the most fenced cities in Juda: But the Kingdom he delivered to Joram, because he was the first begotten.\n"
	"And Joram rose over the Kingdom of his father: and when he had established himself, he slew all his brethren with the sword, and certain of the Princes of Israel.\n"
	"Two and thirty years old was Joram when he began to reign: and he reigned eight years in Jerusalem.\n"
	"And he walked in the ways of the kings of Israel, as the house of Achab had done: for Achab's daughter was his wife, and he did evil in the sight of our Lord.\n"
	"But our Lord would not destroy the house of David for the covenant which he had made with him: and because he had promised that he would give him a lamp, and to his sons for ever.\n"
	"In those days Edom rebelled, from being subject to Juda, and made themselves a king\n"
	"And when Joram had passed with his Princes, and all the horsemen, that were with him, he rose in the night, and struck Edom, which had compassed him, and all the captains of his horsemen.\n"
	"But yet Edom rebelled, from being under the dominion of Juda until this day: at that time Lobna also revolted, from being under his hand. For he had forsaken our Lord the God of their fathers:\n"
	"moreover he built also excelses in the cities of Juda, and he made the inhabitants of Jerusalem to fornicate, and Juda to transgress.\n"
	"And there were letters brought him from Elias the Prophet, in which was Written: Thus saith our Lord the God of David thy father: Because thou hast not walked in the ways of Josaphat thy father, and in the ways of Asa the king of Juda,\n"
	"but hast gone by the ways of the kings of Israel, and hast made Juda to fornicate, and the inhabitants of Jerusalem, having imitated the fornication of the house of Achab, moreover also hast killed thy brethren, the house of thy father, better men than thou:\n"
	"behold our Lord will strike thee with a great plague with all thy people, and children, and thy wives, and all thy substance.\n"
	"And thou shalt be sick of a very sore disease of thy belly, till thy vital parts come forth by little and little every day.\n"
	"Our Lord therefore raised up against Joram the spirit of the Philisthians, and of the Arabians, which are borderers to the Aethiopians.\n"
	"and they went up into the Land of Juda, and wasted it, and they spoiled all the substance, that was found in the king's house, moreover also his sons, and wives: neither was there a son left him but Joachaz, who was the youngest.\n"
	"And beside all these things our Lord struck him with an incurable disease of the belly.\n"
	"And when day succeeded day, and the spaces of times passed about, the circuit of two years was complete: and so being wasted with a long consumption, so that he voided even his very bowels, he was rid of the disease, and of his life together. And he died in an exceeding vile infirmity, and the people made him not exequies according to the manner of burning, as they had done to his ancestors.\n"
	"He was two and thirty years old, when he began to reign, and he reigned eight years in Jerusalem. And he walked not rightly, and they buried him in the City of David: but yet not in the sepulchre of the kings.";