const char* chap39 = "Therefore Joseph was brought into Aegypt, and Putiphar an Eunuch of Pharao, Prince of his army, a man of Aegypt bought him, at the hand of the Ismaelites, by whom he was brought.\n"
	"And our Lord was with him, and he was a man that in all things did prosperously: and he dwelt in his master's house,\n"
	"who knew very well that our Lord was with him, and that all things which he did were directed by him in his hand.\n"
	"And Joseph found grace before his master, and ministered to him: by whom being made ruler over all his things, he governed the house committed to him, and all things that were delivered unto him:\n"
	"and our Lord blessed the house of the Aegyptian for Joseph's sake, and multiplied as well in houses, as in lands all his substance.\n"
	"Neither knew he any other thing, but the bread which he did eat. And Joseph was of beautiful countenance, and comely favoured to behold.\n"
	"After many days therefore his Mistress cast her eyes on Joseph, and said: Sleep with me.\n"
	"Who in nowise assenting to that wicked act, said to her: Behold, my master having delivered all things unto me, knoweth not what he hath in his own house:\n"
	"Neither is there any thing which is not in my power, or that he hath not delivered to me, beside thee, that art his wife: how therefore can I do this wicked thing, and sin against my God?\n"
	"With these kind of words day by day both the woman was importune upon the young man, and he refused the adultery.\n"
	"And it chanced on a certain day, that Joseph went into the house, and did some business without any man with him:\n"
	"and she catching the skirt of his garment, said: Sleep with me. Who leaving the cloak in her hand, fled, and went forth abroad.\n"
	"And when the woman saw the garment in her hands, and herself to be contemned,\n"
	"she called to her the men of her house, and said to them: See he hath brought in an Hebrew to delude us: he came upon me for to lie with me; and when I had cried out,\n"
	"and he heard my voice, he left the cloak that I held, and fled forth.\n"
	"For an argument therefore of her credit she reserved the cloak, & shewed it to her husband returning home,\n"
	"and said: There came unto me the Hebrew servant, whom thou didst bring hither, for to delude me:\n"
	"and when he heard me cry, he left the cloak which I held, and fled forth.\n"
	"His master hearing these things, and giving over light credit to his wife's words, was very wrath:\n"
	"and delivered Joseph into prison, where the king's prisoners were kept, and he was there shut up.\n"
	"And our Lord was with Joseph, and having mercy upon him gave him grace in the sight of the chief of the prison.\n"
	"Who delivered in his hand all the prisoners that were kept in custody: and whatsoever was done, was under him.\n"
	"Neither did himself know anything, having committed all things to him: for our Lord was with him, and directed all his works.";