const char* chap391 = "Seven years old was Joas when he began to reign: and he reigned forty years in Jerusalem, the name of his mother was Sebia of Bersabee.\n"
	"And he did that which is good before our Lord all the days of Joiada the Priest.\n"
	"And Joiada took for him two wives, of whom he begat sons & daughters.\n"
	"After which things it pleased Joas to repair the house of our Lord.\n"
	"And he assembled the priests, & the Levites & said to them: Go ye forth to the cities of Juda, & gather of all Israel money for the reparation of the temple of your God, year by year, and do this in haste: moreover the Levites did negligently.\n"
	"And the king called Joiada the Prince, and said to him: why hast thou had no care to constrain the Levites to bring in out of Juda and Jerusalem the money, that was appointed of Moyses the servant of our Lord, that all the multitude of Israel should bring it in into the tabernacle of testimony?\n"
	"For the most impious Athalia, & her children have destroyed the house of God, and of all things that had been sanctified in the temple of our Lord, they adorned the temple of Baalim.\n"
	"The king therefore commanded and they made a chest: and set it by the gate of our Lord on the out side.\n"
	"And it was proclaimed in Juda and Jerusalem, that every man should bring the price to our Lord, which Moyses the servant of God appointed over all Israel, in the desert.\n"
	"And all the Princes rejoiced, and all the people: and going in they contributed into the chest of our Lord, and cast in so that it was filled.\n"
	"And when it was time that they should bring the chest before the king by the hands of Levites (for they saw much money) the king's Scribe went in, and he whom the high Priest had appointed: & they poured out the money that was in the chest, and recarried it to his place: and so did they from day to day, and there was gathered infinite money.\n"
	"Which the king and Joiada gave to them, that oversaw the works of the house of our Lord: but they hired with it hewers of stones, and artificers of all works, to repair the house of our Lord: smiths also of iron and brass, that that which began to fall might be upholden.\n"
	"And they that wrought did industriously, and the breach of the walls was closed by their hands, and they raised the house of our Lord into the old state, and made it stand firmly.\n"
	"And when they had accomplished all the works, they brought the rest of the money before the king and Joiada: of the which were made vessels of the temple to the ministry, and for holocausts, phials also, and other vessels of gold and silver, and holocausts were offered in the house of our Lord continually all the days of Joiada.\n"
	"But Joiada became old being full of days, and died when he was an hundred and thirty years old.\n"
	"And they buried him in the city of David with the kings, because he had done good with Israel, and with his house.\n"
	"And after that Joiada was dead, the Princes of Juda went in, and adored the king, who being altered by their serviceableness, agreed to them.\n"
	"And they forsook the temple of our Lord the God of their fathers, and served groves, and sculptiles, & there came wrath against Juda, and Jerusalem for this sin.\n"
	"And he sent them Prophets, that they should return to our Lord, whom, protesting, they would not hear.\n"
	"The spirit of God therefore invested Zacharias the son of Joiada the Priest, and he stood in the sight of the people, and said to them: Thus saith our Lord God: Why transgress you the precept of our Lord, which thing shall not profit you, and have forsaken our Lord, that he should forsake you?\n"
	"Who being gathered against him, they threw stones according to the king's commandment, in the court of the house of our Lord.\n"
	"And Joas the king did not remember the mercy, that Joiada his father had done with him, but he killed his son. Who when he died, said: Our Lord see, and require it.\n"
	"And when a year was come about, the army of Syria came up against him: and it came into Juda and Jerusalem, & slew all the Princes of the people, and all the prey they sent to the king into Damascus.\n"
	"And whereas there was come a very small number of the Syrians, our Lord delivered into their hands an infinite multitude, for that they had forsaken our Lord the God of their fathers: on Joas also they exercised ignominious judgments.\n"
	"And departing they left him in great disease: and his servants rose against him, for revenge of the blood of the son of Joiada the Priest, and they slew him in his bed, & he died: and they buried him in the City of David, but not in the king's sepulchres.\n"
	"And there conspired against him Zabad the son of Semmaath an Ammonitess, and Jozabad the son of Semarith a Moabitess.\n"
	"Moreover his children, and the sum of money, which was gathered under him, and the repairing of the house of God are written more diligently in the Book of kings: and Amasias his son reigned for him.";