const char* chap4 = "And Adam knew Eve his wife, who conceived and brought forth Cain, saying: I have gotten a man through God.\n"
	"And again she brought forth his brother Abel. And Abel was a shepherd, & Cain a husbandman.\n"
	"And it befell after many days that Cain offered of the fruits of the earth gifts to our Lord.\n"
	"Abel also offered of the first-begotten of his flock, and of their fat: and our Lord had respect of Abel, & to his gifts.\n"
	"But to Cain, and to his gifts he had not respect: And Cain was exceeding angry, and his countenance abated.\n"
	"And our Lord said to him: Why art thou angry? and why is thy countenance fallen?\n"
	"If thou do well, shall thou not receive again: but if thou dost ill, shall not thy sin forthwith be present at the door? But the lust thereof shall be under thee, and thou shalt have dominion over it.\n"
	"And Cain said to Abel his brother: Let us go forth abroad. And when they were in the field, Cain rose up against his brother Abel, and slew him.\n"
	"And our Lord said to Cain: Where is Abel thy brother? Who answered: I know not, am I my brother's keeper?\n"
	"And he said to him: what hast thou done? The voice of thy brother's blood cryeth to me out of the earth.\n"
	"Now therefore cursed shalt thou be upon the earth, which hath opened her mouth, & received the blood of thy brother at thy hand.\n"
	"When thou shalt till it, it shall not yield to thee her fruit: a rogue and vagabond shalt thou be upon the earth.\n"
	"And Cain said to our Lord: Mine iniquity is greater than that I may deserve pardon.\n"
	"Lo thou dost cast me out this day from the face of the earth, and from thy face shall I be hid, and I shall be a vagabond and fugitive on the earth: every one therefore that findeth me shall kill me.\n"
	"And our Lord said to him: No, it shall not so be: but whosoever shall kill Cain, shall be punished seven-fold. And our Lord put a mark on Cain, that whosoever found him should not kill him.\n"
	"And Cain went forth from the face of our Lord, and dwelt as a fugitive on the earth at the east side of Eden.\n"
	"And Cain knew his wife, who conceived and brought forth Enoch: And he built a city, and called the name thereof by the name of his son, Enoch.\n"
	"Moreover Enoch begat Irad, and Irad begat Maviael, and Maviael begat Mathusael, and Mathusael begat Lamech.\n"
	"Who took two wives, the name of the one was Ada, and the name of the other Sella.\n"
	"And Ada brought forth Iabel, who was the father of them that dwell in tents, and of herdsmen.\n"
	"And his brother's name was Jubal: he was the father of them that sing on harp & organs.\n"
	"Sella also brought forth Tubalcain, who was a hammerer and worker in all work of brass and iron. And the sister of Tubalcain was Noema.\n"
	"And Lamech said to his wives Ada and Sella: Hear my voice ye wives of Lamech, harken to my talk: for I have slain a man to the wounding of myself, and a stripling to mine own dry blow bruising.\n"
	"Seven-fold vengeance shall be taken of Cain: but of Lamech seventy times seven-fold.\n"
	"Adam also knew his wife again: and she brought forth a son, & called his name Seth, saying: God hath given me other seed for Abel, whom Cain slew.\n"
	"But to Seth also was born a son, whom he called Enos, this man began to invocate the name of our Lord.";