const char* chap40 = "These things being so done, it chanced that two Eunuchs, the cup-bearer of the King of Aegypt, and his baker, offended against their lord.\n"
	"And Pharao being wrath against them (for the one was chief of the cup-bearers, the other chief baker)\n"
	"he sent them into the prison of the captain of the soldiers, in the which Joseph also was prisoner.\n"
	"But the keeper of the prison delivered them to Joseph, who also ministered to them: some little time was passed, and they were kept in custody.\n"
	"And they saw each of them both a dream in one night, according to an interpretation agreeing to themselves:\n"
	"to whom when Joseph was entered in the morning, and saw them sad,\n"
	"he asked them, saying: Why is your countenance sadder today than it was wont?\n"
	"Who answered: We have seen a dream, and there is no body to interpret it to us. And Joseph said to them: Why doth not interpretation belong to God? Tell me what you have seen.\n"
	"The chief of the cup-bearers first told his dream: I saw before me a vine,\n"
	"wherein were three branches, growing by little and little into buds, and after the blossoms, the grapes waxed ripe:\n"
	"and the cup of Pharao in my hand: and I took the grapes, and wrung them into the cup which I held, and I gave the cup to Pharao.\n"
	"Joseph answered: This is the interpretation of the dream: The three branches, are yet three days:\n"
	"after the which Pharao will remember thy service, & will restore thee to thy old degree: & thou shalt give him the cup according to thine office, as before thou hadst wont to do.\n"
	"Only remember me, when it shall be well with thee, and do me this mercy, to put Pharao in mind that he take me out of this prison:\n"
	"because I was taken away by stealth, out of the land of the Hebrews, and here an innocent was I cast into the lake.\n"
	"The master of the bakers seeing that he had wisely resolved the dream, he said: And I also saw a dream, that I had three baskets of meal upon my head:\n"
	"and that in one basket that was the higher, I carried all meats that are made by the art of baking, and that the birds did eat out of it.\n"
	"Joseph answered: This is the interpretation of the dream: The three baskets, are yet three days:\n"
	"after the which Pharao will take thy head from thee, and hang thee on the cross, and the fowls shall tear thy flesh.\n"
	"The third day after this was the birth-day of Pharao: who making a great feast to his servants, at the banquet he remembered the master of the cup-bearers, and the chief of the bakers.\n"
	"And he restored the one into his place, to reach him the cup,\n"
	"the other he hanged on a gibbet, that the truth of the interpreter might be approved.\n"
	"And yet notwithstanding the chief of the cup-bearers, prosperous things succeeding, forgat his interpreter.";