const char* chap402 = "And Josias made in Jerusalem a Phase to our Lord, which was immolated the fourteenth day of the first month.\n"
	"And he appointed the Priests in their offices, & exhorted them that they would minister in the house of our Lord.\n"
	"To the Levites also, at whose instruction all Israel was sanctified to our Lord, he spake: Put the Ark in the Sanctuary of the temple, which Salomon built^ the son of David the king of Israel, for you shall carry it no more: but now minister to our Lord your God, & to his people Israel.\n"
	"And prepare yourselves by your houses & kindreds in the divisions of every one, as David the king of Israel commanded, & Salomon his son described.\n"
	"And minister ye in the Sanctuary by families and Levitical companies,\n"
	"and being sanctified immolate the Phase, prepare also your brethren, that they may do according to the words, which our Lord spake in the hand of Moyses.\n"
	"Moreover Josias gave to all the people, that was found there in the solemnity of the Phase, lambs and kids of the flocks, and of the rest of the cattle thirty thousand, of oxen also three thousand, all these things of the king's substance.\n"
	"His dukes also voluntarily offered that which they vowed, as well to the people, as to the Priests and the Levites. Moreover Helcias, and Zacharias, and Jahiel, Princes of the house of our Lord, gave to the Priests to make the Phase, cattle, one with another two thousand six hundred, and oxen three hundred.\n"
	"And Chonenias, & Semeias, also Nathanael, his brethren, moreover Hasabias, & Jehiel, and Jozabad Princes of the Levites, gave to the rest of the Levites to celebrate the Phase five thousand sheep, and oxen five hundred.\n"
	"And the ministry was prepared, and the Priests stood in their office: the Levites also in companies, according to the king's commandment.\n"
	"And the Phase was immolated: and Priests sprinkled the blood with their hand, and the Levites drew of the skins of the holocausts:\n"
	"and they separated them to give them by the houses and families of every one, and to be offered to our Lord, as it is written in the Book of Moyses, of oxen also they did in like manner.\n"
	"And they roasted the Phase upon fire, according to that which is written in the law: but the pacific hosts they boiled in cauldrons, and kettles, and pots, & in haste they distributed it to all the people.\n"
	"And for themselves and for the Priests they prepared afterward: for in oblation of holocausts and of fat the Priests were occupied until night: wherefore the Levites prepared for themselves, and for the Priests the children of Aaron last.\n"
	"Moreover the singing men the children of Asaph stood in their order, according to the precept of David, and Asaph, and Heman, and Idithun the Prophets of the king: and the porters watched at every gate, so that they departed not a moment from the ministry. For the which cause also their brethren the Levites prepared meats for them.\n"
	"Therefore all the service of our Lord was ritely accomplished that day, so that they made the Phase, and offered holocausts upon the altar of our Lord, according to the precept of king Josias.\n"
	"And the children of Israel that were found there, made the Phase at that time, and the solemnity of Azymes seven days.\n"
	"There was not a Phase like to this in Israel, from the days of Samuel the Prophet: neither did any of all the kings of Israel make a Phase as Josias, to the Priests, and the Levites, and to all Juda, and Israel, that was found, and to the inhabitants of Jerusalem.\n"
	"In the eighteenth year of the Kingdom of Josias was this Phase celebrated.\n"
	"After that Josias had repaired the temple, came up Nechao the king of Aegypt to fight in Charcamis beside Euphrates: and Josias went forth to meet him.\n"
	"But he sending messengers unto him, said: What have I to do with thee king of Juda? I come not against thee this day, but I fight against another house, to the which God hath commanded me to go in haste. Leave to do against God, who is with me, lest he kill thee.\n"
	"Josias would not return, but prepared battle against him, neither did he agree to the words of Nechao from the mouth of God, but went forward to fight in the field of Mageddo.\n"
	"And there being wounded of the Archers, he said to his servants: Carry me out of the battle, because I am sore wounded.\n"
	"Who removed him from one chariot into another chariot that followed him after the manner of kings, and they carried him away into Jerusalem, & he died, & was buried in the monument of his fathers, and all Juda & Jerusalem mourned for him.\n"
	"Jeremy most of all: whose lamentations all the singing men and singing women repeat until this present day upon Josias, & it is grown as it were a law in Israel: Behold it is said to be written in the lamentations.\n"
	"But the rest of the words of Josias and of his mercies: which are commanded by the law of our Lord:\n"
	"his works also the first and the last, are written in the Book of the kings of Juda and Israel.";