const char* chap405 = "And these are the children of the province that went up from the captivity, which Nabuchodonosor the king of Babylon had transported into Babylon, and returned into Jerusalem and Juda, every man into his city.\n"
	"They that came with Zorobabel, Josue, Nehemia, Saraia, Rahelaia, Mardochai, Belsan, Mesphar, Beguai, Rehum, Baana: The number of the men of the people of Israel:\n"
	"The children of Pharos two thousand an hundred seventy two.\n"
	"The children of Sephatia, three hundred seventy two.\n"
	"The children of Area, seven hundred seventy five.\n"
	"The children of Phahath Moab, of the children of Josue: Joab, two thousand eight hundred twelve.\n"
	"The children of Aelam a thousand two hundred fifty four.\n"
	"The children of Zethua, nine hundred forty five.\n"
	"The children of Zachai, seven hundred sixty.\n"
	"The children of Bani^ six hundred forty two.\n"
	"The children of Bebai, six hundred twenty three.\n"
	"The children of Azgad, a thousand two hundred twenty two.\n"
	"The children of Adonicam, six hundred sixty six.\n"
	"The children of Beguai, two thousand fifty six.\n"
	"The children of Adin, four hundred fifty four.\n"
	"The children of Ather, which were of Ezechias, ninety eight.\n"
	"The children of Besai, three hundred and twenty three.\n"
	"The children of Iora, an hundred twelve.\n"
	"The children of Hasum, two hundred twenty three.\n"
	"The children of Gebbar, ninety five.\n"
	"The children of Bethlehem, an hundred twenty three.\n"
	"The men of Netupha, fifty six.\n"
	"The men of Anathoth an hundred twenty eight.\n"
	"The children of Azmaveth, forty two.\n"
	"The children of Cariathiarim, Cephira, & Beroth, seven hundred forty three.\n"
	"The children of Rama and Gabaa, six hundred twenty one.\n"
	"The men of Machmas, an hundred twenty two.\n"
	"The men of Bethel and Hai, two hundred twenty three.\n"
	"The children of Nebo, fifty two.\n"
	"The children of Megbis, an hundred fifty six.\n"
	"The children of another Aelam, a thousand two hundred fifty four.\n"
	"The children of Harim, three hundred twenty.\n"
	"The children of Lod Hadid and Ono, seven hundred twenty five.\n"
	"The children of Jericho, three hundred forty five.\n"
	"The children of Senaa, three thousand six hundred thirty.\n"
	"The Priests: The children of Iadaia in the house of Josue, nine hundred seventy three.\n"
	"The children of Emmer, a thousand fifty two.\n"
	"The children of Pheshur, a thousand two hundred forty seven.\n"
	"The children of Harim, a thousand and seventeen.\n"
	"The Levites: The children of Josue and Cedmiel, the children of Odovia, seventy four.\n"
	"The singing men: The children of Asaph, an hundred twenty eight.\n"
	"The children of the Porters: the children of Sellum, the children of Ater, the children of Telmon, the children of Accub, the children of Hatita, the children of Sobai: all an hundred thirty nine.\n"
	"The Natheneites: The children of Siha, the children of Hasupha, the children of Tabbaoth,\n"
	"The children of Ceros, the children of Siaa, the children of Phadon,\n"
	"The children of Lebana, the children of Hagaba, the children of Accub,\n"
	"The children of Hagab, the children of Semlai, the children of Hanan,\n"
	"The children of Gaddel, the children of Gaher, the children of Raaia,\n"
	"The children of Rasin, the children of Necoda, the children of Gazam,\n"
	"The children of Aza, the children of Phasea, the children of Besee,\n"
	"The children of Asena, the children of Munim, the children of Nephusim,\n"
	"The children of Bacbuc, the children of Hacupha, the children of Harhur,\n"
	"The children of Besluth, the children of Mahida, the children of Harsa,\n"
	"The children of Bercos, the children of Sisara, the children of Thema,\n"
	"The children of Nasia, the children of Hatipha,\n"
	"The children of the servants of Salomon, the children of Sotai, the children of Sophereth, the children of Pharuda,\n"
	"The children of Iala, the children of Dercon, the children of Geddel,\n"
	"The children of Saphatia, the children of Hatil, the children of Phochereth, which were of Asebaim, the children of Ami.\n"
	"All the Nathinites, & the children of the servants of Salomon, three hundred ninety two.\n"
	"And these are they that came up from Thelmela, Thelharsa, Cherub, and Adon, and Emer. And they could not shew the house of their fathers and their seed, whether they were of Israel.\n"
	"The children of Dalaia, the children of Tobia, the children of Necoda, six hundred fifty two.\n"
	"And of the children of the Priests: The children of Hobia, the children of Accos, the children of Berzellai, who took a wife of the daughters of Berzellai the Galaadite, and was called by their name:\n"
	"these sought the writing of their genealogy, and found it not, and they were cast out of the Priesthood.\n"
	"And Athersatha said to them, that they should not eat of the Holy of holies, till there rose a Priest learned and perfect.\n"
	"All the multitude as it were one man, forty two thousand three hundred sixty:\n"
	"beside their men servants, and women servants, which were seven thousand three hundred thirty seven: & among them singing men, & singing women two hundred.\n"
	"Their horses seven hundred thirty six, their mules two hundred forty five,\n"
	"their camels, four hundred thirty five, their asses six thousand seven hundred twenty.\n"
	"And of the Princes of the fathers, when they entered into the temple of our Lord, which is in Jerusalem, they offered voluntarily unto the house of our Lord to build it in his place.\n"
	"According to their abilities, they gave the expenses of the work, of gold sixty one thousand solids, of silver five thousand pounds, & garments for the Priests an hundred.\n"
	"The Priests therefore and the Levites, and they of the people, and the singing men, and the porters, and the Nathinites dwelt in their cities, and all Israel in their cities.";