const char* chap413 = "Esdras therefore thus praying, and beseeching, and weeping, and lying before the temple of God, there was gathered to him of Israel an exceeding great company of men and women and children, and the people wept with much lamentation.\n"
	"And Sechenias the son of Jehiel of the children of Aelam answered, and said to Esdras: We have transgressed against our God, and have taken to wives strange women of the peoples of the land: and now if there be penance in Israel upon this,\n"
	"let us make a covenant with the Lord our God, to put away all the wives, and them that are born of them, according to the will of our Lord, and of them that fear the precept of the Lord our God: be it done according to the law.\n"
	"Arise, it is thy part to discern, and we will be with thee: take courage, and do it.\n"
	"Esdras therefore rose up, and adjured the Princes of the Priests and of the Levites, & all Israel, that they should do according to this word, and they sware.\n"
	"And Esdras rose up before the house of God, & went to the chamber of Johanan the son of Eliasib, and entered into it: he did eat no bread, & drank no water: for he mourned for the transgression of them that were come out of the captivity.\n"
	"And there was a proclamation sent in Juda and Jerusalem to all the children of the transgression, that they should assemble together into Jerusalem.\n"
	"And every one that shall not come within three days, according to the counsel of the Princes & ancients, all his substance shall be taken away and himself shall be cast out of the company of the transmigration.\n"
	"There assembled therefore all the men of Juda, and Benjamin into Jerusalem within three days, that is the ninth month, the twentieth day of the month: and all the people sat in the street of the house of God, trembling for the sin, and the rain.\n"
	"And Esdras the Priest arose, and said to them: You have transgressed, and taken strange women to wife, to add upon the sin of Israel.\n"
	"And now give confession to our Lord the God of your fathers, and do his pleasure, and be separated from the peoples of the land, and from your wives the strangers.\n"
	"And all the multitude answered, and said with a loud voice: According to thy word unto us, so be it done.\n"
	"Nevertheless because there is much people, and a time of rain, and we cannot abide to stand without, and it is not a work of one day or two (for we have exceedingly sinned in this thing),\n"
	"let there be Princes appointed in all the multitude: & let all in our cities that have taken strangers to wife, come at set times, and with them the ancients by city and city, and the judges thereof, until the wrath of our God be turned away from us for this sin.\n"
	"Therefore Jonathan the son of Azahel, and Iaazia the son of Thecua were appointed over this, and Mosollam and Sebethai Levites did help them:\n"
	"and the children of the transmigration did so. And Esdras the Priest, and the men, Princes of the families, went into the houses of their fathers, & all by their names, and they sat in the first day of the tenth month to search out the matter.\n"
	"And all the men were fully counted that had taken strangers to wife, unto the first day of the first month.\n"
	"And there were found of the sons of the Priests that had taken strangers to wife. Of the children of Josue the son of Josedec, and his brethren, Maasia, and Eliezer, and Jarib, and Godolia.\n"
	"And they gave their hands to put away their wives, & to offer for their offence a ram of the flock.\n"
	"And of the children of Emmer, Hanani, and Zebedia.\n"
	"And of the children of Harim, Maasia, and Elia, and Semeia, and Jehiel, and Ozias.\n"
	"And of the children of Pheshur, Elionai, Maasia, Ismael, Nathanael, Jozabed, and Elasa.\n"
	"And of the children of the Levites, Jozabed, and Semei, and Celaia, the same is Calita, Phataia, Juda, & Eliezer.\n"
	"And of the singing men Eliasib: and of the porters, Sellum, and Thelem, and Uri.\n"
	"And of Israel, of the children of Pharos, Remeia, and Iezia, and Melchia, and Miamin, and Eliezer, and Melchia, and Banea.\n"
	"And of the children of Aelam, Mathania, Zacharias, and Jehiel, and Abdi, and Jerimoth, and Elia.\n"
	"And of the children of Zethua, Elioenai, Eliasib, Mathania, Jerimuth, and Zabad, and Aziza.\n"
	"And of the children of Bebai, Johanan, Hanania, Zabbai, Athalai.\n"
	"And of the children of Bani, Mosollam, and Melluch, and Adaia, Jasub, and Saal, and Ramoth.\n"
	"And of the children of Phahath Moab, Edna & Chalal, Bananias, and Maasias, Mathanias, Beseleel, Bennui, and Manasse.\n"
	"And of the children of Herem, Eliezer, Josue, Melchias, Semeias, Simeon,\n"
	"Benjamin, Maloch, Samarias.\n"
	"And of the children of Hasom, Mathanai, Mathatha, Zabad, Eliphelet, Iermai, Manasse, Semei.\n"
	"Of the children of Bani, Maaddi, Amram, and Vel,\n"
	"Baneas, and Badaias, Cheliau,\n"
	"Vania, Marimuth, and Eliasib,\n"
	"Mathanias, and Mathanai, and Iasi,\n"
	"and Bani, and Bennui, Semei,\n"
	"and Salmias, and Nathan, & Adaias,\n"
	"and Mechnedebai, Sisai, Sarai.\n"
	"Ezrel, and Selemiau, Semeria,\n"
	"Sellum, Amaria, Joseph.\n"
	"Of the children of Nebo, Jehiel, Mathathias, Zabad, Zabina, Ieddu, and Joel, and Banaia.\n"
	"All these had taken strangers to wife, and there were of them that had born children.";