const char* chap416 = "And Eliasib the high Priest arose, and his brethren the Priests: and they built the gate of the flock: they sanctified it, and set the doors thereof, and unto the tower of an hundred cubits they sanctified it, unto the tower of Hananeel.\n"
	"And besides him did the men of Jericho build, and besides him built Zachur the son of Amri.\n"
	"But the fish-gate the children of Asnaa did build: they covered it, and set up the doors thereof, and the locks, and bars. And besides them built Marimuth the son of Urias the son of Accas.\n"
	"And besides him built Mosollam the son of Bazachias, the son of Mesezebel, & besides them built Sadoc the son of Baana.\n"
	"And beside them builded the Thecuenes: but their great men did not put under their necks in the work of their Lord.\n"
	"And Joiada the son of Phasea, and Mosollam the son of Besodia built the old-gate, covered it, & set up the doors thereof, and the locks, and bars.\n"
	"And beside them built Meltias a Gabaonite, & Iadon a Meronathite, men of Gabaon, & Maspha, for the duke that was in the country beyond the River.\n"
	"And beside him built Eziel the son of Araia a goldsmith: and beside him built Ananias the son of a Pigmentary: and they left Jerusalem unto the wall of the broader street.\n"
	"And beside him built Raphaia the son of Hur, Prince of the street of Jerusalem.\n"
	"And beside them Jedaia the son of Haromaph against his house: and beside him built Hattus the son of Hasebomia.\n"
	"The half part of the street built Melchias the son of Herem, and Hasub the son of Phahath Moab, and the tower of the furnaces.\n"
	"And beside him built Sellum the son of Alohes Prince of the half part of the street of Jerusalem, he and his daughters.\n"
	"And the gate of the valley built Hanun, and the inhabitants of Zanoe: they built it, and set up the doors thereof, and the locks, and bars, and a thousand cubits in the wall unto the gate of the dunghill.\n"
	"And the gate of the dunghill built Melchias the son of Rechab, the Prince of the street of Bethacaram: he built it, & set up the doors thereof, and the locks, and bars.\n"
	"And the gate of the fountain Sellum builded the son of Colhoza, Prince of the village of Maspha: he built it, and covered it, and set up the doors thereof, and the locks, and bars, and the walls of the pool of Siloe unto the king's garden, and unto the steps that go down from the city of David.\n"
	"After him built Nehemias the son of Azboc Prince of the half part of the street of Bethsur, as far as over against the sepulchre of David, and unto the pool, that is built with great work, and unto the house of the valiants.\n"
	"After him the Levites builded, Rehum the son of Benni. After him built Hasebias Prince of the half part of the street of Ceila in his street.\n"
	"After him built their brethren, Bavai the son of Enadad, Prince of the half part of Ceila.\n"
	"And beside him built Azer the son of Josue, the Prince of Maspha the second measure, against the visiting of the most sure corner.\n"
	"After him in the mount built Baruch the son of Zachai the second measure, from the corner unto the gate of the house of Eliasib the high Priest.\n"
	"After him built Merimuth the son of Urias the son of Haccus, the second measure, from the gate of the house of Eliasib, as far as the house of Eliasib extended.\n"
	"And after him built the Priests, men of the champion of Jordan.\n"
	"After him built Benjamin and Hasub against their house: and after him built Azarias the son of Maasias the son of Ananias against his house.\n"
	"After him built Bennui the son of Hanadad the second measure, from the house of Azarias unto the bending, and unto the corner.\n"
	"Phalel the son of Ozi against the bending and the tower, which appeareth from out of the king's high house, that is, in the court of the prison: after him Phadaia the son of Pharos.\n"
	"And the Nathineites dwelt in Ophel, as far as over against the gate of waters toward the East, and the tower that stood out.\n"
	"After him the Thecuenes builded the second measure over against, from the great and eminent tower unto the wall of the temple.\n"
	"And upward to the gate of horses the Priests built, every man against his house.\n"
	"After them build Sadoc the son of Emmer against his house. And after him built Semaia the son of Sechenias, keeper of the East gate.\n"
	"After him built Hanania the son of Selemia, and Hanun the son of Seleph the sixth, the second measure: after him built Mosollam the son of Barachias, against his treasury. After him Melchias a gold-smith son unto the house of the Nathineites, and of them that sold old stuff against the judgment gate, and unto the upper chamber of the corner.\n"
	"And within the upper chamber of the corner in the gate of the flock, the goldsmiths and merchants builded.";