const char* chap427 = "Tobias of the tribe and city of Nephthali (which is in the upper parts of Galilee above Naasson, beyond the way that leadeth to the west, having on the right hand the city Sephet)\n"
	"when he was captive in the days of Salmanasar the king of the Assyrians, yet being in captivity, he forsook not the way of truth,\n"
	"so that he imparted all things that he could make daily to his brethren captives with him, which were of his kindred.\n"
	"And whereas he was younger than all the tribe of Nephthali, yet did he no childish thing in his work.\n"
	"Finally, when all went to the golden calves, which Jeroboam the king of Israel had made, he alone fled the companies of all,\n"
	"and went into Jerusalem to the temple of our Lord, and there adored our Lord God of Israel, offering faithfully all his first fruits, and his tithes,\n"
	"so that in the third year he ministered all the tithing to the proselytes and strangers.\n"
	"These things and the like to these did he observe being a child according to the law of God.\n"
	"But when he was a man, he took to wife Anna of his own tribe, and he begat a son of her, giving him his own name.\n"
	"Whom from his infancy he taught to fear God, and to abstain from all sin.\n"
	"Therefore when by the captivity he was come with his wife and son into the city of Ninive, with all his tribe,\n"
	"(When all did eat of the meats of the Gentiles) he kept his soul, and never was contaminated in their meats.\n"
	"And because he was mindful of our Lord in all his heart, God gave him grace in the sight of Salmanasar the king,\n"
	"and he gave him leave to go whithersoever he would, having liberty to do what things soever he would.\n"
	"He therefore went to all that were in the captivity, and gave them wholesome admonitions.\n"
	"And when he was come into Rages a city of the Medes, and had ten talents of silver of these wherewith he had been honoured of the king:\n"
	"and when in a great multitude of his kindred, he saw Gabelus stand in need, who was of his tribe, under a bill of his hand he gave him the said weight of silver.\n"
	"But after much time, Salmanasar the king being dead, when Sennacherib his son reigned for him, & esteemed the children of Israel odious in his sight:\n"
	"Tobias daily went through all his kindred, and comforted them, and divided to every one, as he was able, of his goods:\n"
	"the hungry he nourished, and to the naked he gave cloths, and the dead, and them that were slain, he buried carefully.\n"
	"Finally when king Sennacherib was returned flying from Jewry the slaughter, that God had made about him for his blasphemy, & being angry slew many of the children of Israel, Tobias buried their bodies.\n"
	"But when it was told the king, he commanded him to be slain, and took all his substance.\n"
	"But Tobias flying with his son and with his wife, nakedly lay hid, because many loved him.\n"
	"But after forty five days the king was slain of his own sons,\n"
	"and Tobias returned into his house, and all his substance was restored to him.";