const char* chap428 = "But after these things, when there was a festival day of our Lord, and a good dinner was made in Tobias' house,\n"
	"he said to his son: Go, and bring some of our tribe that fear God, to make merry with us.\n"
	"And when he had gone, returning he told him, that one of the children of Israel lay slain in the street. And he forthwith leaping up from his place at the table, leaving his dinner, came fasting to the body:\n"
	"and taking it up carried it to his house secretly, that when the sun should be down, he might warily bury him.\n"
	"And when he had hid the body, he eat bread with mourning & trembling.\n"
	"remembering that word which our Lord said by Amos the Prophet: Your festival days shall be turned into lamentation & mourning.\n"
	"But when the sun was down, he went and buried him.\n"
	"And all his neighbours rebuked him, saying: Even now thou wast commanded to be slain because of this matter, and thou didst scarce escape the commandment of death, and doest thou bury the dead again?\n"
	"But Tobias more fearing God than the king, in haste took the bodies of them that were slain, and hid them in his house, & at midnight buried them.\n"
	"And it happened that on a certain day, being wearied with burying, coming into his house he had cast himself down by the wall, and slept,\n"
	"and as he was sleeping, hot dung out of the swallows nest fell upon his eyes, and he was made blind.\n"
	"And this tentation therefore our Lord permitted to chance unto him, that an example might be given to posterity of his patience, as also of holy Job.\n"
	"For whereas he feared God always from his infancy, and kept his commandments, he grudged not against God for that the plague of blindness had chanced to him,\n"
	"but continued immovable in the fear of God, giving thanks to God all the days of his life.\n"
	"For as the kings insulted against blessed Job, so his parents and cousins derided his life, saying:\n"
	"Where is thy hope, for the which thou didest bestow alms & burials?\n"
	"But Tobias rebuked them, saying: Speak not so:\n"
	"because we are the children of holy ones, and look for that life, which God will give to them, that never change their faith from him.\n"
	"But Anna his wife went daily to weaving work, and she brought the gains of her handy labour, which she could get.\n"
	"Whereby it came to pass, that she receiving a kid of goats had brought it home:\n"
	"the voice whereof bleating^ when her husband had heard, he said: Take heed, lest perhaps it be stolen, restore ye it to his owners, because it is not lawful for us either to eat any thing of theft or to touch it.\n"
	"To these words his wife being angry answered: Thy hope is become vain manifestly, and thine alms now have appeared.\n"
	"And with these, and other such like words she upbraided him.";