const char* chap429 = "Then Tobias lamented, and began to pray with tears,\n"
	"saying: Thou art just o Lord, and all thy judgments are just, & all thy ways mercy, & truth & judgment.\n"
	"And now Lord be mindful of me, and take not revenge of my sins, neither remember the sins of me, or of my parents.\n"
	"Because we have not obeyed thy commandments, therefore we are delivered in spoil, and captivity, and death, and into a fable, and into reproach to all nations, in which thou hast dispersed us.\n"
	"And now Lord great are thy judgments, because we have not done according to thy precepts, & have not walked sincerely before thee:\n"
	"and now Lord according to thy will^ do with me, and command my spirit to be received in peace: for it is expedient for me to die, rather than to live.\n"
	"The very same day therefore it chanced that Sara the daughter of Raguel in Rages a city of the Medes, she also heard reproach of one of her father's hand-maids,\n"
	"because she had been delivered to seven husbands, and the devil named Asmodeus had killed them forthwith as they were entered in unto her.\n"
	"Therefore when she rebuked the wench for her fault, she answered her, saying: Let us no more see son of thee, or daughter upon the earth, thou murderer of thy husbands.\n"
	"What, wilt thou kill me also, as thou hast now killed seven husbands? At this voice she went into an higher chamber of her house: and three days and three nights did not eat, nor drink:\n"
	"but continuing in prayer with tears besought God, that he would deliver her from this reproach.\n"
	"And it came to pass the third day, whiles she accomplished her prayer, blessing our Lord,\n"
	"she said: Blessed is thy name o God of our fathers: who when thou hast been angry, wilt do mercy, and in the time of tribulation forgivest them their sins, that invocate thee.\n"
	"To thee o Lord I turn my face, to thee I direct mine eyes.\n"
	"I desire Lord that thou loose me from the bond of this reproach, or else take me away from the earth.\n"
	"Thou knowest Lord that I never coveted a husband, & have kept my soul clean from all concupiscence.\n"
	"Never have I companied myself with sporters: neither have I made myself partaker with them that walk in lightness.\n"
	"But a husband I consented to take, with thy fear, not with my lust.\n"
	"And either I was unworthy of them, or they perhaps were not worthy for me: because perhaps thou hast kept me for another man.\n"
	"For thy counsel is not in man's power.\n"
	"But this hath every one for certain, that worshippeth thee, that his life, if it be in probation, shall be crowned: and if it be in tribulation, it shall be delivered: and if it be in correction, it shall be lawful to come to thy mercy.\n"
	"For thou art not delighted in our perditions: because after a tempest thou makest a calm, and after tears and weeping thou pourest in joyfulness.\n"
	"Be thy name God of Israel blessed for ever.\n"
	"At that time the prayers of both were heard in the sight of the glory of the high God:\n"
	"and the holy Angel of our Lord Raphael was sent to cure them both, whose prayers at one time were recited in the sight of our Lord.";