const char* chap430 = "Therefore when Tobias thought his prayer to be heard that he might have died, he called to him Tobias his son,\n"
	"and said to him: Hear my son the words of my mouth, and lay them as a foundation in thy heart.\n"
	"When God shall take my soul, bury my body: & thou shalt do honour to thy mother all the days of her life:\n"
	"for thou must be mindful what perils, and how great she suffered for thee in her womb.\n"
	"And when she also shall have accomplished the time of her life, bury her beside me.\n"
	"And all the days of thy life have God in thy mind: and beware thou consent not to sin at any time, and pretermit the precepts of our Lord God.\n"
	"Of thy substance give alms, & turn not away thy face from any poor person: for so it shall come to pass that neither the face of our Lord shall be turned from thee.\n"
	"As thou shalt be able, so be merciful.\n"
	"If thou have much, give aboundantly: if thou have little, study to impart also a little willingly.\n"
	"For thou doest treasure up to thyself a good reward in the day of necessity.\n"
	"Because alms delivereth from all sin, and from death, and will not suffer the soul to go into darkness.\n"
	"Great confidence before God most high shall alms be to all them that do it.\n"
	"Take heed to thyself my son of all fornication, and beside thy wife never abide to know crime,\n"
	"Never permit pride to rule in thy word: for in it all perdition took his beginning.\n"
	"Whosoever hath wrought any thing for thee, pay him his hire immediately, and let not the hire of thy hired servant remain with thee at all.\n"
	"That which thou hatest to be done to thee by another, see thou do it not to another at any time.\n"
	"Eat thy bread with the hungry & needy, and of thy garments cover the naked.\n"
	"Set thy bread, and thy wine upon the burial of a just man, and do not eat and drink thereof with sinners.\n"
	"Seek counsel always of a wise man.\n"
	"At all time bless God: and desire of him, that he direct thy ways, and that all thy counsels remain in him.\n"
	"I tell thee also my son that I gave ten talents of silver, whiles thou wast yet a child, to Gabelus, in Rages a city of the Medes, & I have a bill of his hand with me:\n"
	"and therefore inquire how thou mayst come to him, and receive of him the foresaid weight of silver, and restore him the bill of his hand.\n"
	"Fear not my son: we lead indeed a poor life, but we shall have many good things if we fear God, and depart from all sin, and do well.";