const char* chap436 = "But when Tobias tarried long because of the marriage, Tobias his father was careful, saying: Why thinkest thou doth my son tarry, or why is he held there?\n"
	"Is Gabelus dead thinkest thou, and no man will restore him the money?\n"
	"And he began to be sorrowful exceedingly himself, and Anna his wife with him: & they began both to weep together: because their son did not return to them the day appointed.\n"
	"His mother therefore wept with discomfortable tears, & said: Woe, woe is me, my son, why sent we thee to go to a strange country, the light of our eyes, the staff of our old age, the comfort of our life, the hope of our posterity?\n"
	"We having all things together in thee only, ought not to have let thee go from us.\n"
	"To whom Tobias said: Hold thy peace, and be not troubled, our son is safe, that man with whom we sent him is faithful enough.\n"
	"Howbeit she could by no means be comforted, but daily running out looked about, and went about all ways by which there seemed hope he would return, that she might see him a far off, if it were possible, coming.\n"
	"But Raguel said to his son in law: Tarry here, and I will send a messenger to Tobias thy father, that thou art in health.\n"
	"To whom Tobias said: I know that my father and my mother do now count the days, and their spirit is tormented in them.\n"
	"And when Raguel desired Tobias in many words, and he by no means would hear him, he delivered Sara unto him, & the half part of all his substance in men servants, & women servants, in cattle, in camels, and in kine, and in much money and dismist him safe and joyful from him,\n"
	"saying: The holy Angel of our Lord be in your journey, and bring you through safe, and that you may find all things well about your parents, and mine eyes may see your children before I die.\n"
	"And the parents taking their daughter, kissed her, and let her go:\n"
	"admonishing her to honour her father and mother in law, to love her husband, to rule the household, to govern the house, and to shew herself irreprehensible.";