const char* chap437 = "And when they returned they came to Charan, which is in the mid-way against Ninive, the eleventh day.\n"
	"And the Angel said: Brother Tobias thou knowest how thou didst leave thy father.\n"
	"If it please thee therefore, let us go before, and let the families follow softly after us, together with thy wife, and with the beasts.\n"
	"And when this pleased him that they should go, Raphael said to Tobias: Take with thee of the gall of the fish: for it shall be necessary. Tobias therefore took of that gall and they departed.\n"
	"But Anna sat beside the way daily, in the top of a hill, from whence she might see a far off.\n"
	"And whilst she watched his coming out of that place, she saw a far off, and by and by perceived her son coming: and running she told her husband saying: Behold thy son cometh.\n"
	"And Raphael said to Tobias: But when thou art entered into thy house forthwith adore our Lord thy God: and giving thanks to him go to thy father, and kiss him.\n"
	"And immediately anoint upon his eyes of this gall of the fish, which thou carriest with thee. For know thou that forthwith his eyes shall be opened, and thy father shall see the light of heaven, and shall rejoice in the sight of thee.\n"
	"Then ran the dog before, which had been with them in the way, and coming as it were a messenger with the fawning of his tail rejoiced.\n"
	"And his father that was blind rising up began to run stumbling with his feet: and giving a servant his hand, went to meet his son.\n"
	"And receiving him kissed him, with his wife, and they began both to weep for joy.\n"
	"And when they had adored God, and given thanks, they sat down together.\n"
	"Then Tobias taking of the gall of the fish, anointed his father's eyes.\n"
	"And he stayed as it were almost half an hour: and the white blemish began to come out of his eyes, as it were the skin of an egg.\n"
	"Which Tobias taking drew from his eyes, and immediately he received sight.\n"
	"And they glorified God, to wit, himself and his wife, and all that knew him.\n"
	"And Tobias said: I bless thee Lord God of Israel, because thou hast chastised me, and thou hast saved me: and behold I see Tobias my son.\n"
	"After seven days also came in Sara his son's wife, & all the family safe, & cattle, & the camels, and much money of his wives: and that money also, which he had received of Gabelus:\n"
	"and he told his parents all the benefits of God, which he had done to him by the man that conducted him.\n"
	"And Achior and Nabath^ Tobias' sister's sons came, rejoicing at Tobias, and congratulating him for all good things that God had shewed towards him.\n"
	"And for seven days making good cheer, they rejoiced all with great joy.";