const char* chap438 = "Then Tobias called to him his son, and said to him: What may we give to this holy man, that is come with thee?\n"
	"Tobias answering, said to his father: Father what reward shall we give him? Or what can be worthy of his benefits?\n"
	"He hath led me & brought me again safe, he received the money of Gabelus, he caused me to have my wife, and the evil spirit he chased from her, he made joy unto her parents, myself he delivered from being devoured of the fish, thee also he hath made to see the light of heaven, and we are replenished with all good things by him. What can we give him worthy for these things?\n"
	"But I beseech thee my father, that thou desire him, if perhaps he will vouchsafe to take unto him the one half of all things which are brought.\n"
	"And they calling him, to wit the father and the son, took him aside: and began to desire him that he would vouchsafe to accept the half part of all things, that they had brought.\n"
	"Then he said to them secretly: Bless ye the God of heaven, and before all that live confess to him, because he hath done mercy with you.\n"
	"For to hide the secret of a king is good: but to reveal and confess the works of God is an honourable thing.\n"
	"Prayer is good with fasting and alms, rather than to lay up treasures of gold:\n"
	"because alms delivereth from death, and that is it which purgeth sins, and maketh to find mercy and life everlasting.\n"
	"But they that commit sin and iniquity, are enemies to their own soul.\n"
	"I open therefore unto you the truth, and I will not hide from you the secret word.\n"
	"When thou didst pray with tears, and didst bury the dead, and left thy dinner, and didest hide the dead by day in thy house, and by night didst bury them, I offered thy prayer to our Lord.\n"
	"And because thou wast acceptable to God, it was necessary that tentation should prove thee.\n"
	"And now our Lord sent me to cure thee, and to deliver Sara thy son's wife from the devil.\n"
	"For I am Raphael an Angel, one of the seven, which assist before our Lord.\n"
	"And when they had heard these things, they were troubled, and trembling fell upon the ground on their face.\n"
	"And the Angel said to them: Peace be to you, fear not.\n"
	"For when I was with you, by the will of God I was so: bless ye him, and sing to him.\n"
	"I seemed indeed to eat with you, and to drink: but I use an invisible meat and drink, which cannot be seen of men.\n"
	"It is time therefore that I return to him, that sent me: but bless ye God, and tell all his marvelous works.\n"
	"And when he had said these things, he was taken from their sight, and they could see him no more.\n"
	"Then prostrate for three hours upon their face, they blessed God: and rising up they told all his marvelous works.";