const char* chap44 = "And Joseph commanded the steward of his house, saying: Fill their sacks with corn, as much as they can hold: and put the money of every one in the top of his sack.\n"
	"And in the sack's mouth of the younger put my silver cup, and the price which he gave for the wheat. And it was so done.\n"
	"And when the morning rose, they were dismissed with their asses.\n"
	"And they were now departed out of the city, and had gone forward a little way: then Joseph sending for the steward of his house, said: Arise, quote he, and pursue the men: and overtaking them say to them: Why have you rendered evil for good?\n"
	"The cup which you have stolen is that wherein my Lord doth drink, and wherein he is wont to divine: you have done a very evil thing.\n"
	"He did as he had commanded. And having overtaken them, he spake to them in the same order.\n"
	"Who answered: Why doth our Lord speak so, as though thy servants had committed so heinous a fact?\n"
	"The money that we found in the top of our sacks, we recarried to thee from the land of Chanaan: & how followeth it, that we have stolen out of thy Lord's house gold or silver?\n"
	"With whom soever of thy servants that shall be found which thou seekest, let him die, and we will be the bondmen of our Lord.\n"
	"Who said to them: Be it done according to your sentence: with whom soever it shall be found, be he my bondmen, and you shall be guiltless.\n"
	"Therefore in haste taking down their sacks upon the ground, every man opened.\n"
	"Which when he had searched, beginning from the elder even to the youngest, he found the cup in Benjamin's sack.\n"
	"But they renting their garments, and loading their asses again, returned into the town.\n"
	"And Judas foremost with his brethren entered in to Joseph (for he was not yet gone out of the place) and they fell together before him on the ground.\n"
	"To whom he said: Why would you do so? Know you not that there is not the like to me in the science of divining.\n"
	"To whom Judas said: What shall we answer, my Lord? Or what shall we speak, or be able justly to pretend? God hath found the iniquity of thy servants: lo we are all bondmen to my Lord, both we, & he with whom the cup was found.\n"
	"Joseph answered: God forbid that I should so do: he that stole the cup, the same be my bondman: and go you free unto your father.\n"
	"And Judas approaching nearer said boldly: I beseech thee my Lord, let thy servant speak a word in thine ears, and be not angry with thy servant: for after Pharao thou art,\n"
	"my Lord. Thou didst ask thy servants the first time: Have you a father or a brother?\n"
	"and we answered thee my Lord: We have a father an old man, and a little boy, that was born in his old age; whose brother by the mother is dead: and his mother hath him only, and his father loveth him tenderly.\n"
	"And thou saidst to thy servants: Bring him hither to me, and I will set mine eyes on him.\n"
	"We suggested to my Lord: The boy cannot leave his father: for if he leave him, he will die.\n"
	"And thou saidst to thy servants: Unless your youngest brother come with you, you shall no more see my face.\n"
	"Therefore when we were gone up to thy servant our father, we told him all things that my Lord did speak.\n"
	"And our father said: Go again, and buy us a little wheat.\n"
	"To whom we said: We cannot go: if our youngest brother shall go down with us, we will set forward together: otherwise he being absent, we dare not see the man's face.\n"
	"Whereunto he answered: You know that my wife bare me two.\n"
	"One went forth, and you said: A beast did devour him: and hitherto he appeareth not.\n"
	"If you take this also, and ought befall him in the way, you shall bring down my hoar hairs with sorrow unto hell.\n"
	"Therefore if I shall enter to thy servant our father, and the boy be wanting (whereas his life dependeth upon the life of him)\n"
	"and he shall see that he is not with us, he will die, and thy servants shall bring down his hoar hairs with sorrow unto hell.\n"
	"Let me be thy proper servant that did take him into my protection and promised, saying: Unless I bring him again I will be guilty of sin against my father for ever.\n"
	"I therefore thy servant will tarry instead of the child in the service of my Lord, and let the child go up with his brethren.\n"
	"For I cannot return to my father, the child being absent; lest I stand by a witness of the calamity that shall oppress my father.";