const char* chap440 = "And the words of Tobias were ended. And after that Tobias was restored to his sight, he lived two and forty years, and saw the children of his nephews.\n"
	"Therefore an hundred and two years being accomplished, he was buried honourably in Ninive.\n"
	"For being six and fifty years old he lost the sight of his eyes, and being threescore he received it again.\n"
	"And the rest of his life was in joy, and with great increase of the fear of God he went forward in peace.\n"
	"And at the hour of his death he called unto him Tobias his son, and his seven young sons, his nephews, and said to them.\n"
	"The destruction of Ninive is near: for the word of our Lord faileth not: and our brethren, which are dispersed from the land of Israel, shall return to it.\n"
	"And all the desert land thereof shall be replenished, & the house of God which is burnt in it, shall again be re-edified: and thither shall all return that fear God,\n"
	"and the Gentiles shall forsake their idols, and shall come into Jerusalem; and shall inhabit in it,\n"
	"and all the kings of the earth shall rejoice in it, adoring the king of Israel.\n"
	"Hear ye therefore my children your father: serve our Lord in truth, and seek to do the things that please him:\n"
	"and command your children that they do justices and alms deeds, that they be mindful of God, and bless him at all time in truth, and in all their power.\n"
	"Now therefore children hear me, and do not tarry here: but what day soever you shall bury your mother by me in one sepulchre, from thenceforth direct your steps to depart hence:\n"
	"for I see that the iniquity thereof will give it an end.\n"
	"And it came to pass after the death of his mother, Tobias departed out of Ninive with his wife, and children, and children's children, and returned to his father and mother in law.\n"
	"And he found them in health in good old age: and he took care of them, and he closed their eyes: and all the inheritance of Raguel's house he received: and he saw the fifth generation, his children's children.\n"
	"And ninety nine years being accomplished in the fear of our Lord, with joy they buried him.\n"
	"And all his kindred, and all his generation continued in good life, and in holy conversation, so that they were acceptable both to God, and to men, and to all the inhabitants in the land.";