const char* chap441 = "Arphaxad therefore king of the Medes had subdued many nations to his empire, and he built a most mighty city, which he called Ecbatanis,\n"
	"of stones squared and hewed: he made walls thereof in height seventy cubits, and in breadth thirty cubits, and the towers thereof he made in height an hundred cubits.\n"
	"But each side of them was in four square twenty foot long, and he made the gates thereof according to the height of the towers:\n"
	"and he gloried as mighty in the force of his army, and in the glory of his chariots.\n"
	"In the twelfth year of his reign: Nabuchodonosor the king of the Assyrians, who reigned in Ninive the great city, fought against Arphaxad, and overcame him\n"
	"in the great field, which is called Ragau, about Euphrates, and Tigris, and Iadason in the field of Erioch the king of the Elicians.\n"
	"Then was the Kingdom of Nabuchodonosor exalted, and his heart was elevated: and he sent to all that dwelt in Cilicia and Damascus, and Libanus,\n"
	"and to the nations, that are in Carmelus, and Cedar, and the inhabitants of Galilee in the great field of Esdrelon,\n"
	"and to all that were in Samaria, and beyond the river Jordan even to Jerusalem, and all the land of Jesse till you come to the borders of Aethiopia.\n"
	"To all these Nabuchodonosor king of the Assyrians sent messengers:\n"
	"Who all with one mind said nay, and sent them back empty, and rejected them without honour.\n"
	"Then Nabuchodonosor the king taking indignation against all that land, swore by his throne and kingdom that he would revenge himself of all those countries.";