const char* chap443 = "Then the kings and Princes of all cities and Provinces, namely of Syria and Mesopotamia, and Syria Sobal, and Libya, and Cilicia sent their ambassadors, which coming to Holofernes, said:\n"
	"Let thy indignation toward us cease: For it is better that living we fear Nabuchodonosor the great king, and be subject to thee, than dying, we should with our destruction suffer the damages of our servitude.\n"
	"Every city of ours, and all our possession, all mountains, and hills, and fields, and herds of oxen, and flocks of sheep, and goats, and of horses, and camels, and all our goods, and families are in thy sight:\n"
	"Let all our things be under thy law.\n"
	"We also, and our children are thy servants.\n"
	"Come to us a peaceable Lord, and use our service, as it shall please thee.\n"
	"Then went he down from the mountains with horsemen in a great power, and took every city, and every inhabiter of the land.\n"
	"And of all the cities he took to help him valiant men, and chosen for battle.\n"
	"And so great fear lay upon all those Provinces, that the inhabitants of all cities, Princes, and honourable persons, together with the people went out to meet him coming,\n"
	"receiving him with garlands, and torches, dancing with timbrels, and shalms.\n"
	"Neither doing these things, could they for all that^ mitigate the fierceness of his stomach:\n"
	"for he did both destroy their cities, and cut down their groves.\n"
	"For Nabuchodonosor the king had commanded him, that he should destroy all the gods of the earth, that he only might be called god of those nations, which could be subdued with the might of Holofernes.\n"
	"And passing through all Syria Sobal, and all Apamea, and all Mesopotamia, he came to the Idumeians into the land of Gabaa,\n"
	"and took their cities, and sat there for thirty days, in which days he commanded all the army of his power to be united.";