const char* chap447 = "But Holofernes the next day commanded his armies, that they should go up against Bethulia.\n"
	"And there were of war foot-men an hundred twenty thousand, and horse-men two and twenty thousand, besides the preparations of those men, whom the captivity had taken, and had been led away out of the Provinces & cities, of all youth.\n"
	"All prepared themselves together to the fight against the children of Israel, and they came by the hill side unto the top, which looketh toward Dothaim, from the place which is called Belma unto Chelmon, which is against Esdrelon.\n"
	"But the children of Israel, as they saw the multitude of them, laid themselves prostrate upon the earth, casting ashes upon their heads, praying with one accord, that the God of Israel would shew his mercy upon his people.\n"
	"And taking their weapons of war, they sat at the places, which by a narrow path-way lead directly between the mountains, and they were keeping them all day and night.\n"
	"Moreover Holofernes, whilst he compasseth round about, found that the fountain which ran in, went directly to their conduit on the south side without the city: and he commanded their conduit to be cut asunder.\n"
	"Nevertheless there were fountains not far from the walls, out of which secretly they seemed to draw water to refresh themselves, rather than to drink.\n"
	"But the children of Ammon and Moab came to Holofernes, saying: The children of Israel trust not in spear, nor in arrow, but the mountains defend them, and the hills standing marvelous steep guard them.\n"
	"Therefore that thou mayst overcome them without joining battle, set keepers of the fountains, that they may not draw water of them, and without sword thou shalt kill them, or at the least being wearied they will yield their city, which they think being set in the mountains, cannot be overcome.\n"
	"And these words pleased Holofernes and his soldiers, and he placed round about an hundred men at every fountain.\n"
	"And when that watch had been fully kept for twenty days, the cisterns failed, and the collections of waters to all the inhabitants of Bethulia, so that there was not within the city whereof they might be satisfied, no not for one day, because water was daily given to the people by measure.\n"
	"Then all the men, and women, young men, and children, being gathered together to Ozias, all together with one voice,\n"
	"said: God judge between us and thee, because thou hast done evil against us, in that thou wouldest not speak peaceably with the Assyrians, and for this cause God hath sold us into their hands.\n"
	"And there is none to help, whereas we lie prostrate before their eyes in thirst, and great destruction.\n"
	"And now assemble ye all, that are in the city, that we may of our own accord yield us all to the people of Holofernes.\n"
	"For it is better, that captives we bless our Lord living, than we should die, and be a reproach to all flesh, when we shall see our wives and our infants die before our eyes.\n"
	"We call to witness this day heaven and earth, and the God of our fathers, which taketh vengeance of us according to our sins, that now you deliver the city into the hand of Holofernes' army, that our end may be short in the edge of the sword, which is made longer in the drought of thirst.\n"
	"And when they had said these things, there was made great weeping and howling of all in the assembly, and for many hours with one voice they cried to God, saying:\n"
	"We have sinned with our fathers, we have done unjustly, we have committed iniquity.\n"
	"Thou because thou art gracious, have mercy upon us, or in thy scourge revenge our iniquities, and deliver not them that trust in thee to a people, that knoweth not thee,\n"
	"that they say not among the Gentiles: Where is their God?\n"
	"And when they^ wearied with these cries, and tired with these weepings, had held their peace,\n"
	"Ozias rising up imbrued with tears, said: Be of good cheer brethren, and these five days let us expect mercy of our Lord.\n"
	"For peradventure he will cut off his indignation, and will give glory to his name.\n"
	"But if after five days be past there come no aid, we will do these words, which you have spoken.";