const char* chap45 = "Joseph could no longer refrain many standing by in presence: whereupon he commanded that all should go forth, and no stranger should be present at their acknowledging one of another.\n"
	"And he lifted up his voice with weeping, which the Aegyptians heard, and all the house of Pharao.\n"
	"And he said to his Brethren: I am Joseph: is my father yet living? His brethren could not answer him being terribly astonished out of measure.\n"
	"To whom gently he said: Come hither to me. And when they were come near him, I am, quoth he, Joseph your brother, whom you sold into Aegypt.\n"
	"Be not afraid, neither let it seem to you a hard case that you did sell me into these countries: for God sent me before you into Aegypt for your preservation.\n"
	"For it is two years since the famine began to be upon the earth, and yet five years remain, wherein there can be neither earing nor reaping.\n"
	"And God sent me before, that you may be preserved upon the earth, and may have victuals to live.\n"
	"Not by your counsel, but by the will of God was I sent hither: who hath made me as it were a father to Pharao, and Lord of his whole house, and Prince in all the land of Aegypt.\n"
	"Make haste and get ye up to my father, and you shall say to him: Thy son Joseph willeth thus: God hath made me Lord of the whole land of Aegypt: come down to me, tarry not.\n"
	"And thou shalt dwell in the land of Gessen: and thou shalt be near me thou and thy sons, and thy son's children, thy sheep, and thy herds, and all things that thou dost possess.\n"
	"And there I will feed thee (for yet there are five years of famine remaining) lest both thou perish and thy house, and all things that thou dost possess.\n"
	"Behold, your eyes, and the eyes of my brother Benjamin do see, that it is my mouth that speaketh unto you.\n"
	"Report to my father my whole glory & all things that you have seen in Aegypt: make haste, and bring him to me.\n"
	"And falling upon the neck of his brother Benjamin, embracing him he wept: he also in like manner weeping upon his neck.\n"
	"And Joseph kissed all his brethren, and wept upon every one: after which things they were bold to speak unto him.\n"
	"And it was heard of, and very famously reported abroad in the king's court: The brethren of Joseph are come: and Pharao was glad, and all his family.\n"
	"And he spake to Joseph that he should command his brethren, saying: Loading your beasts go into the Land of Chanaan,\n"
	"and take thence your father and kin, and come to me: and I will give you all the good things of Aegypt, that you may eat the marrow of the land.\n"
	"Give commandment also that they take wains out of the land of Aegypt, for the carriage of their little ones and wives: and say: Take up your father, and make haste to come with all speed.\n"
	"Neither do you leave any thing of your household stuff: for all the riches of Aegypt shall be yours.\n"
	"And the sons of Israel did as it was commanded them. To whom Joseph gave wains according to Pharao's commandment, and victuals for the way.\n"
	"He bade also to be brought up for every one two robes: but to Benjamin he gave three hundred pieces of silver with five robes of the best:\n"
	"sending to his father as much money & raiment, adding besides them he asses that should carry of all the riches of Aegypt, and as many she asses, carrying wheat for the journey and bread.\n"
	"Therefore he dismissed his brethren, and when they were departing he said to them: Be not angry in the way.\n"
	"Who going up out of Aegypt, came into the land of Chanaan to their father Jacob.\n"
	"And they told him saying: Joseph thy son is living: and he ruleth in all the Land of Aegypt. Which when Jacob heard, awaking as it were out of a heavy sleep, notwithstanding did not believe them.\n"
	"They on the contrary side reported the whole order of the thing. And when he saw the wains and all things that he had sent, his spirit revived,\n"
	"and he said: It sufficeth me if Joseph my son be living yet: I will go, and see him before I die.";