const char* chap450 = "And it came to pass, when she had ceased to cry to our Lord, she rose from the place, wherein she lay prostrate to our Lord.\n"
	"And she called her Abra, and going down into her house she took from her the hair-cloth, & put off the garments of her widowhood,\n"
	"and washed her body, and anointed herself with ointment, and plaited the hair of her head, and put a crown upon her head, and clothed herself with the garments of her joyfulness, and put pantofles on her feet, & took bracelets, and Lilies, and earlets, and rings, and with all her ornaments she adorned herself.\n"
	"To whom also our Lord gave beauty: because all this trimming did not depend of sensuality, but of virtue: and therefore our Lord amplified this beauty on her, that she might appear to all men's eyes of incomparable comeliness.\n"
	"She therefore laid upon her Abra a bottle of wine, and a vessel of oil, and polent, and dry figs, and bread, and cheese, and went forward.\n"
	"And when they were come to the gate of the city, they found Ozias expecting, and the ancients of the city.\n"
	"Who when they saw her, being astonished marveled at her beauty exceedingly.\n"
	"Yet asking her no question, they let her pass, saying: The God of our fathers give thee grace, and strengthen all the counsel of thy heart, with his power, that Jerusalem may glory upon thee, and thy name may be in the number of the holy and just.\n"
	"And they that were there said all with one voice: So be it, so be it.\n"
	"But Judith praying our Lord, passed through the gates^ she & her Abra.\n"
	"And it came to pass, when she went down the hill, about break of day the watchmen of the Assyrians met her, & held her, saying: whence comest thou? Or wither goest thou?\n"
	"Who answered, I am a daughter of the Hebrews, therefore am I fled from their face because I knew it should come to pass, that they should be given you unto spoil, because that contemning you, they would not of their own accord yield themselves, that they might find mercy in your sight.\n"
	"For this cause I thought with myself, saying: I will go to the presence of the Prince Holofernes, that I may tell him their secrets, and shew him by what entrance he may win them, so that there shall not fall one man of his army,\n"
	"And when those men had heard her words, they considered her face, and she was a wonder in their eyes, for they marveled at her beauty exceedingly.\n"
	"And they said to her: Thou hast saved thy life, in that thou hast found such counsel, that thou wouldest come down to our Lord.\n"
	"And this know thou, that when thou shalt stand in his sight, he will deal well with thee, and thou shalt be most gracious in his heart. And they brought her to the tabernacle of Holofernes, telling him of her.\n"
	"And when she was entered before his face, forthwith Holofernes was caught in his eyes.\n"
	"And his guard said to him: Who can contemn the people of the Hebrews, which have so beautiful women, that we should not worthily fight against them for these?\n"
	"Judith therefore seeing Holofernes sitting in a canopy, which was woven of purple, and gold, and emerald, and precious stones:\n"
	"and when she had looked in his face, she adored him, falling prostrate upon the ground. And the servants of Holofernes lifted her up, their lord commanding it.";