const char* chap454 = "And Judith said to all the people: Hear me brethren, hang ye this head upon our walls:\n"
	"and it shall be, when the sun shall rise, let every man take his armour, & issue ye forth with violence, not that you go down beneath, but as it were invading violently.\n"
	"Then the watchmen must of necessity run to raise up their Prince to battle.\n"
	"And when the captains of them shall run to the tabernacle of Holofernes, and shall find him headless rolled in blood, fear will fall upon them.\n"
	"And when you shall know that they fly, go after them securely, because our Lord will destroy them under your feet.\n"
	"Then Achior seeing the power, that God of Israel wrought, forsaking the rite of gentility, believed God, and circumcised the flesh of his prepuce, and was joined to the people of Israel, and all the succession of his kindred until this present day.\n"
	"And immediately as day brake, they hung the head of Holofernes upon the walls, & every man took his armour, & they went forth with great noise & shouting.\n"
	"Which the watchmen seeing, ran to the tabernacle of Holofernes.\n"
	"Moreover they that were in the tabernacle coming, and before the door of the tabernacle making a noise to raise him, they endeavoured by art to disquiet him, that Holofernes might awake not by them raising him, but by them making a noise.\n"
	"For no man durst by knocking, or entering, to open the chamber of the chief of the Assyrians.\n"
	"But when his Dukes and tribunes were come, and all the chief of the army of the king of the Assyrians, they said to the chamberlains:\n"
	"Go in, and awake him, because the mice issuing out of their holes, have presumed to provoke us to battle.\n"
	"Then Vagao entering into his chamber, stood before the curtain, & made a clapping with his hands: for he thought that he slept with Judith.\n"
	"But when with the sense of his ears he perceived no motion of person lying, he came near to the curtain, and lifting it up, and seeing the body without the head of Holofernes weltered in his blood lie upon the ground, cried out in a loud voice with weeping, and rent his garments.\n"
	"And going into the tabernacle of Judith, he found her not, and he lept forth to the people,\n"
	"and said: One Hebrew woman hath made confusion in the house of king Nabuchodonosor: for behold Holofernes lieth upon the ground and his head is not upon him.\n"
	"Which when the Princes of the power of the Assyrians had heard, they all rent their garments, & intolerable fear and dread fell upon them, and their minds were troubled exceedingly.\n"
	"And there was made an incomparable cry in the midst of their camp.";