const char* chap455 = "And when all the army heard that Holofernes was beheaded, courage and counsel fell from them, and being shaken with trembling only and fear, they help themselves by flight,\n"
	"so that none spake with his neighbour, but hanging the head, all things left behind, they made haste to escape the Hebrews, whom they heard to come armed upon them, flying by the ways of the fields, and the paths of the hills.\n"
	"The children of Israel therefore seeing them flying, followed them. And they went down sounding with trumpets, and shouting after them.\n"
	"And because the Assyrians were not united together, they went headlong into flight: but the children of Israel pursuing in one company, discomfited all that they could find.\n"
	"Ozias therefore sent messengers through all the cities and countries of Israel.\n"
	"Every country therefore, and every city sent chosen youth armed after them, and they pursued them in the edge of the sword, until they came to the extremity of their borders.\n"
	"And the rest that were in Bethulia, entered into the camp of the Assyrians, and took away the prey, which the Assyrians flying had left, and were loaden exceedingly.\n"
	"But they that were returned conquerors to Bethulia, took away with them all things that were theirs, so that there was no number in cattle, and beasts, and all their moveables, that from the least unto the greatest all were made rich of their preys.\n"
	"And Ioachim the high Priest came from Jerusalem into Bethulia with all his ancients to see Judith.\n"
	"Who when she was come out to him, they all blessed her with one voice, saying: Thou art the glory of Jerusalem, thou the joy of Israel, thou the honour of our people:\n"
	"because thou hast done manfully, and thy heart was strengthened, for that thou had loved chastity, and after thy husband not known any other: therefore also the hand of our Lord hath strengthened thee, and therefore shall thou be blessed for ever.\n"
	"And all the people said: So be it, so be it.\n"
	"And for thirty days, scarce were the spoils of the Assyrians gathered of the people of Israel.\n"
	"Moreover all things, that were proved to be the peculiar goods of Holofernes, they gave to Judith, in gold, and silver, and garments, and precious stones, and all stuff, and all the things were delivered her of the people.\n"
	"And all the people rejoiced with women, and virgins, and youngmen, on instruments and harps.";