const char* chap456 = "Then sang Judith this song to our Lord, saying:\n"
	"Begin ye to our Lord in timbrels, sing ye to our Lord in cymbals, tune to him a new Psalm, rejoice, and invocate his name.\n"
	"Our Lord confoundeth battles, Lord is his name.\n"
	"Who hath set his camp in the midst of his people, that he might deliver us from the hand of all our enemies.\n"
	"Assur came out of the mountains from the North in the multitude of his strength: whose multitude stopped up the torrents, and their horses covered the valleys.\n"
	"He said that he would set my borders on fire, and kill my young men with the sword, to give my infants into prey, and virgins into captivity.\n"
	"But our Lord omnipotent hath hurt him, and hath delivered him into the hands of a woman, and hath pierced him.\n"
	"For, not by young men is their mighty one fallen, neither have the sons of Titan strucken him, neither did the high giants set themselves upon him, but Judith the daughter of Merari in the beauty of her face dissolved him.\n"
	"For she put from her the garments of widowhood, and put on her the garments of joy, in the rejoicing of the children of Israel.\n"
	"She anointed her face with ointment, and tied together her locks with a crown, she took a new stole to deceive him.\n"
	"Her sandals ravished his eyes, her beauty made his soul captive, she with a sword cut off his head.\n"
	"The Persians did quake at her constancy, and the Medes at her boldness.\n"
	"Then did the camp of the Assyrians howl, when my humble ones appeared, withering in thirst.\n"
	"The sons of young women have pierced them, and they have killed them as boys flying away: they have perished in battle before the face of the Lord my God.\n"
	"Let us sing an hymn to our Lord, let us sing a new hymn to our God.\n"
	"Adonai o Lord, great art thou, and noble in thy power, and whom no man can overcome.\n"
	"Let every creature of thine serve thee: because thou saidst, and they were made: thou didst send thy spirit, and they were created, and there is none that can resist thy voice.\n"
	"The mountains with the waters shall be moved with the foundations: the rocks shall melt as wax before thy face.\n"
	"But they that fear thee, shall be great with thee in all things.\n"
	"Woe be to the nation, that riseth up upon my kindred: for our Lord omnipotent will be revenged on them, in the day of judgment he will visit them.\n"
	"For he will give fire, and worms into their flesh, that they may be burnt, and may feel for ever.\n"
	"And it came to pass after these things, all the people after the victory came into Jerusalem to adore our Lord: and forthwith as they were purified, they all offered holocausts, and vows, and their promises.\n"
	"Moreover Judith offered for an anathema of oblivion all the instruments of war of Holofernes, which the people gave her, and the canopy that herself had taken away out of his chamber.\n"
	"And the people was pleasant according to the face of saints, and for three months the joy of this victory was celebrated with Judith.\n"
	"And after those days every man returned into his house, and Judith was made great in Bethulia, and she was more glorious to all the land of Israel.\n"
	"There was also chastity joined to her virtue, so that she knew not man all the days of her life, after that Manasses her husband was dead.\n"
	"And on festival days she came forth with great glory.\n"
	"And she abode in her husband's house an hundred five years, and dismist her Abra free, & she died and was buried with her husband in Bethulia.\n"
	"And all the people mourned for her seven days.\n"
	"And in all the space of her life there was not that troubled Israel, and after her death many years.\n"
	"But the day of the festivity of this victory is received of the Hebrews in the number of holy days, and is worshipped of the Jews from that time until this present day.";