const char* chap46 = "And Israel taking his journey with all things that he had^ came to the well of the oath, and killing there victims to the God of his father Isaac,\n"
	"he heard him by a vision of the night calling him, and saying unto him: Jacob, Jacob. To whom he answered: Lo here I am.\n"
	"God said to him: I am the most mighty God of thy father: fear not, go down into Aegypt, for into a great nation will I make thee there.\n"
	"I will go down with thee thither, and thence will I bring thee returning: Joseph also shall put his hands upon thine eyes.\n"
	"And Jacob rose up from the well of the oath: and his sons took him up, with their little ones and wives in the wains, which Pharao had sent to carry the old man,\n"
	"and all that he had possessed in the Land of Chanaan: and he came into Aegypt with all his seed,\n"
	"His sons, and nephews, daughters, and all his progeny together.\n"
	"And these are the names of the children of Israel, that entered into Aegypt, himself with his children. His first-begotten Ruben.\n"
	"The sons of Ruben: Henoch and Phallu and Hesron and Charmi.\n"
	"The sons of Simeon: Iamuel and Jamin and Ahod, and Jachin and Sohar, and Saul the Son of Chananitess.\n"
	"The sons of Levi: Gerson and Caath and Merari.\n"
	"The sons of Juda: Her & Onan and Sela and Phares and Zara. And Her and Onan died in the land of Chanaan. And there were sons born to Phares: Hesron and Hamul.\n"
	"The sons of Issachar: Thola and Phua and Job and Semron.\n"
	"The sons of Zabulon: Sared and Elon and Iahelel.\n"
	"These are the sons of Lia, which she bare in Mesopotamia of Syria with Dina his daughter. All the souls of his sons and daughters are thirty three.\n"
	"The sons of Gad: Sephion and Haggi and Siuni & Esebon and Heri and Arodi and Areli.\n"
	"The sons of Aser: Jamne and Jesua and Jessui and Beria, Sara also their sister. The sons of Beria: Heber and Melchiel,\n"
	"these be the sons of Zelpha, whom Laban gave to Lia his daughter, and these she bare to Jacob sixteen souls.\n"
	"The sons of Rachel Jacob's wife: Joseph and Benjamin.\n"
	"And there were sons born to Joseph in the Land of Aegypt, which Aseneth the daughter of Putiphar Priest of Heliopolis bare to him: Manasses and Ephraim.\n"
	"The sons of Benjamin: Bela and Bechor and Asbel and Gera and Naaman and Echi and Ros and Mophim and Ophim and Ared.\n"
	"These be the sons of Rachel, which she bare to Jacob: all the souls, fourteen.\n"
	"The sons of Dan: Husim.\n"
	"The sons of Nephthali: Jaziel and Guni and Ieser and Sallem.\n"
	"These be the sons of Bala, whom Laban gave to Rachel his daughter: and these she bare to Jacob; all the souls, seven.\n"
	"All the souls, that entered with Jacob into Aegypt, and that came out of his thigh, besides his son's wives, sixty six.\n"
	"And the sons of Joseph, that were born to him in the land of Aegypt, two souls, All the souls of the house of Jacob, that entered into Aegypt, were seventy.\n"
	"And he sent Judas before him to Joseph, that he should tell him, and he should come into Gessen to meet him.\n"
	"Wither when he was come, Joseph addressing his chariot went up to meet his father, unto the same place: and seeing him fell upon his neck, and as they embraced he wept.\n"
	"And his father said to Joseph: Now will I die with joy, because I have seen thy face, and do leave thee alive.\n"
	"But he spake to his brethren, and to all his father's house: I will go up, & will tell Pharao, and will say to him: My brethren, and my father's house that were in the Land of Chanaan, are come to me:\n"
	"and the men are pastors of sheep, & their trade is to feed flocks: their cattle, & herds, and all that they could have, they have brought with them.\n"
	"And when he shall call you & shall say: What is your trade?\n"
	"You shall answer: We thy servants are pastors, from our infancy until this present, both we and our fathers. And this you shall say, that you may dwell in the Land of Gessen, because the Aegyptians detest all pastors of sheep.";