const char* chap462 = "That night the king passed without sleep, and he commanded the histories and chronicles of former times to be brought him. Which when they were read in his presence,\n"
	"they came to that place where it was written, how Mardocheus had uttered the treason of Bagathan and Thares the eunuchs, coveting to kill king Assuerus.\n"
	"Which when the king had heard, he said: What honour and reward hath Mardocheus received for this fidelity? His servants & ministers said to him: He hath received no reward at all.\n"
	"And the king by and by, Who is, quoth he, in the court? For Aman had entered the inner court of the king's house, that he might suggest to the king, and he might command Mardocheus to be hanged fast on the gibbet, which was prepared for him.\n"
	"The servants answered: Aman standeth in the court. And the king said: Let him come in.\n"
	"And when he was come in, he said to him: What ought to be done to the man, whom the king is desirous to honour? But Aman thinking in his heart, and supposing that the king would honour no other but himself,\n"
	"answered: The man, whom the king desireth to honour,\n"
	"ought to be clothed with the king's garments, and to be set upon the horse that is for the king's saddle, and to take the king's crown upon his head,\n"
	"and let the chief of the king's Princes and nobles hold his horse and going through the street of the city, cry and say: So shall he be honoured, whomsoever the king will honour.\n"
	"And the king said to him: Make haste, and taking a robe and a horse, do that thou hast spoken, to Mardocheus the Jew, which sitteth before the doors of the palace: Beware thou pretermit nothing of those things, which thou hast spoken.\n"
	"Aman therefore took a robe and a horse, and putting it on Mardocheus, & setting him on the horse, in the street of the city went before him, and cried: This honour is he worthy of, whomsoever the king is willing to honour.\n"
	"And Mardocheus returned to the palace gate: & Aman made haste to go into his house, mourning and his head covered:\n"
	"and he told Zares his wife and his friends all things that had chanced him. To whom the wise men whom he had in counsel, and his wife answered: If Mardocheus be of the Jews' seed, before whom thou hast begun to fall, thou canst not resist him, but thou shalt fall in his sight.\n"
	"As they were yet speaking, the king's eunuchs came, and compelled him to go quickly to the banquet which the queen had prepared.";