const char* chap467 = "In the fourth year when Ptolomee and Cleopatra reigned, Dositheus, which named himself a Priest, and of the Levitical kindred, and Ptolomee his son brought this epistle of Phurim, which they said Lysimachus the son of Ptolomee did interpret in Jerusalem.\n"
	"In the second year, when Artaxerxes the greatest reigned, in the first day of the month Nisan, Mardocheus the son of Jairi, the son of Semei, the son of Cis, of the tribe of Benjamin,\n"
	"a Jew which dwelt in the city of Susan, a great man and among the first of the king's court, saw a dream.\n"
	"And he was of that number of captives, whom Nabuchodonosor the king of Babylon had transported from Jerusalem with Jechonias the king of Juda:\n"
	"and this was his dream: There appeared voices, and tumults, and thunders, and earth-quakes, and perturbation upon the earth.\n"
	"and behold two great dragons, prepared one against another into battle.\n"
	"At whose cry all nations were raised up to fight against the nation of the just.\n"
	"And that was a day of darkness and danger, of tribulation and distress, and great fear upon the earth.\n"
	"And the nation of the just fearing their evils, was troubled, and prepared to death.\n"
	"And they cried to God: and they crying, a little fountain grew into a very great river, and abounded into very many waters.\n"
	"Light and the sun arose, & the humble were exalted, & they devoured the glorious.\n"
	"Which when Mardocheus had seen, and risen out of his bed, he mused what God would do: and he had it fixed in his mind, desirous to know what the dream should signify.";