const char* chap47 = "Joseph therefore going in told Pharao, saying: My father and brethren, their sheep and herds, and all things that they possess, are come out of the Land of Chanaan; and behold they stay in the Land of Gessen.\n"
	"The utmost also of his brethren five persons he presented before the King:\n"
	"whom he asked: What trade have you? They answered: We thy servants are pastors of sheep, both we, and our fathers.\n"
	"We are come to sojourn in the land, because there is no grass for thy servant's flocks, the famine being very sore in the land of Chanaan: and we desire thee to command that we thy servants may be in the Land of Gessen.\n"
	"And the King therefore said to Joseph: Thy father and thy brethren are come to thee.\n"
	"The Land of Aegypt is in thy sight: make them to dwell in the best place, & deliver them the Land of Gessen. And if so be thou know that there are industrious men among them, appoint them masters of my cattle.\n"
	"After this Joseph brought in his father to the king, and set him before him: who blessed him,\n"
	"and being asked of him: How many be the days of the years of thy life?\n"
	"He answered: The days of the pilgrimage of my life are an hundred thirty years, few and evil, and they are not come to the days of my fathers, in which they were pilgrims.\n"
	"And blessing the king, he went forth.\n"
	"But Joseph gave possession to his father and his brethren in Aegypt, in the best place of the land, in Rhamesses, as Pharao had commanded.\n"
	"And he nourished them, and all his father's house, allowing victuals to every one.\n"
	"For in the whole world there wanted bread. & famine oppressed the land, especially of Aegypt and Chanaan.\n"
	"Out of which he gathered together all the money for the selling of corn, & brought it in unto the king's treasure.\n"
	"And when the buyers wanted money, all Aegypt came to Joseph, saying Give us bread: why die we before thee, our money failing?\n"
	"To whom he answered: Bring your cattle, and for them I will give you victuals, if you have not to pay.\n"
	"Which when they had brought, he gave them sustenance for horses, and sheep, and oxen, and asses: and he sustained them that year for the exchange of the cattle.\n"
	"And they came the second year, and said to him: We will not conceal from our Lord, that our money failing, our cattle withal have failed: neither art thou ignorant, that we have nothing besides our bodies and land.\n"
	"Why therefore shall we die in thy sight? Both we and our land will be thine: buy us to be the king's bondmen, & give us seed, lest for default of tillers the land be turned into a wilderness.\n"
	"Joseph therefore bought all the Land of Aegypt, every man selling his possessions for the greatness of the famine. And he brought it under Pharao's hands,\n"
	"and all the people thereof from the farthest ends of Aegypt, even to the uttermost coasts thereof,\n"
	"saving the land of the Priests, which the king had delivered them: to whom also a certain allowance of victuals was given out of the common barns, and therefore they were not driven to sell their possessions.\n"
	"Joseph therefore said to the people: Behold as you see, Pharao possesseth both you and your land: take seed, and sow the fields,\n"
	"that you may have corn. The fifth part you shall give to the king: the other four I am content you shall have for seed, & for food to your families & your children.\n"
	"Who answered our life is in thy hand: only let our Lord have a respect unto us, and we will gladly serve the King.\n"
	"From that time until this present day in the whole land of Aegypt, the fifth part is payed to the kings, and it became as it were a law, saving the land of the Priests, which was free from this condition.\n"
	"Israel therefore dwelt in Aegypt that is, in the Land of Gessen, and possessed it: and was increased, & multiplied exceedingly.\n"
	"And he lived in it seventeen years: and all the days of his life came to an hundred forty seven years.\n"
	"And when he saw that the day of his death approached, he called his son Joseph, and said to him: If I have found grace in thy sight, put thy hand under my thigh: and thou shalt do me this mercy and truth. Not to bury me in Aegypt:\n"
	"but I will sleep with my fathers, and take me away out of this land, & bury me in the sepulchre of my ancestors. To whom Joseph answered: I will do that thou hast commanded.\n"
	"And he said: Swear then to me. Who swearing, Israel adored God, turning to the bed's head.";