const char* chap470 = "Esther also the queen fled to our Lord, fearing the peril that was at hand.\n"
	"And when she had laid off her royal garments, she took cloths meet for weeping and mourning, & for diverse ointments, filled her head with ashes & dung, & her body she humbled with fasts: and all the places, in which before she was accustomed to rejoice, she filled with tearing of her hairs.\n"
	"And she besought our Lord the God of Israel, saying: My Lord, which only art our King, help me solitary woman, and which have no other helper beside thee.\n"
	"My peril is in my hands.\n"
	"I have heard of my father that thou Lord didst take Israel out from all Gentiles, and our fathers out of all their predecessors before, that thou mightest possess an everlasting inheritance, and thou hast done to them as thou hast spoken.\n"
	"We have sinned in thy sight, and therefore thou hast delivered us into the hands of our enemies:\n"
	"for we have worshipped their gods. Thou art just o Lord.\n"
	"And now it sufficeth them not, that they oppress us with most hard servitude, but imputing the force of their hands to the might of their idols,\n"
	"they will change thy promises, and destroy thine inheritance, and shut the mouths of them that praise thee, and extinguish the glory of thy temple and altar,\n"
	"that they may open the mouths of Gentiles, and praise the strength of idols, and magnify a carnal king for ever.\n"
	"Deliver not o Lord thy sceptre to them that are not, lest they laugh at our ruin: but turn their counsel upon them, & destroy him, that hath begun to do cruelly against us.\n"
	"Remember o Lord: and shew thyself to us in the time of our tribulation, and give me confidence Lord King of gods, and of all power:\n"
	"give me speech well framed in my mouth, in the presence of the lion, and turn his heart into the hatred of our enemy, that both himself may perish, and the rest that consent unto him.\n"
	"But deliver us in thy hand, and help me, having no other help but thee o Lord, which hast the knowledge of all things,\n"
	"and knowest that I hate the glory of the wicked, and detest the bed of the uncircumcised, and of every stranger.\n"
	"Thou knowest my necessity, that I abhor the sign of my pride & glory, which is upon my head in the days of my ostentation, and detest it as the cloth of a woman in her monthly flowers, and wear it not in the days of my silence,\n"
	"and that I have not eaten at Aman's table, neither the king's banquet hath pleased me, and that I have not drunk the wine of libaments:\n"
	"& that thy handmaid did never rejoice, since I was transported hither unto this day, but in thee o Lord the God of Abraham.\n"
	"O God strong above all, hear the voice of them, that have no other hope, and deliver us from the hand of the wicked, and deliver me from my fear.";