const char* chap475 = "After these things Job opened his mouth, and cursed his day,\n"
	"and spake.\n"
	"Perish may the day wherein I was born, & the night wherein it was said: A man is conceived.\n"
	"Be that day turned into darkness, God require it not from above, and let it not be lightened with light.\n"
	"Let darkness, and the shadow of death obscure it, let a mist possess it, and be it wrapped in bitterness.\n"
	"A darksome hurl wind possess that night, be it not counted in the days of the year, nor numbered in the months.\n"
	"Be that night solitary, nor praise-worthy.\n"
	"Let them curse it which curse the day, which are ready to raise up Leviathan.\n"
	"Let the stars be darkened with the mist thereof: let it expect light and let it not see, neither the rising of the appearing morning.\n"
	"Because it shut not up the doors of the womb that bare me, nor took away evils from mine eyes.\n"
	"Why died I not in the matrice, perished not forthwith being come forth of the womb?\n"
	"Why received upon the knees: why nursed with the breasts?\n"
	"For now sleeping I should be quiet, and should rest in my sleep:\n"
	"With kings and consuls of the earth, which build themselves solitary places:\n"
	"Or with Princes, that posses gold, and replenish their houses with silver:\n"
	"Or as a thing untimely born that is hid I should not be, or as they that being conceived have not seen the light.\n"
	"There the impious have ceased from tumult, & there the wearied with strength have rested.\n"
	"And they sometime bound together without grief, have not heard the voice of the exactor.\n"
	"Little and great are there, and the servant free from his master.\n"
	"Why is there light given to a miserable man, and life to them, that are in bitterness of soul,\n"
	"that expect death, and it cometh not, as they that dig up treasure,\n"
	"and they rejoice exceedingly when they have found the grave?\n"
	"To a man whose life is hid, and God hath compassed him with darkness?\n"
	"Before I eat I sigh: and as it were overflowing waters, so my roaring:\n"
	"Because the fear which I feared, hath chanced to me: and that which I was afraid of, hath happened.\n"
	"Have I not dissembled? Have I not kept silence? Have I not been at ease? And indignation is come upon me.";