const char* chap476 = "But Eliphaz the Themanite answering, said:\n"
	"If we shall begin to speak to thee, perhaps thou wilt take it grievously, but the word conceived who can hold?\n"
	"Behold thou hast taught many, and weary hands thou hast strengthened.\n"
	"Them that wavered thy words have confirmed, and trembling knees thou hast strengthened:\n"
	"But now a plague is come upon thee, & thou hast fainted: hath touched thee, and thou art troubled.\n"
	"Where is thy fear, thy strength, thy patience, and the perfection of thy ways?\n"
	"Remember I beseech thee, who ever being innocent hath perished? Or when have the just been destroyed?\n"
	"Yea rather I have seen them that work iniquity, and sow sorrows, and reap them,\n"
	"to have perished by the blast of God, and with the spirit of his wrath to have been consumed.\n"
	"The roaring of the lion, and the voice of the lioness, and the teeth of the whelps of lions are bruised:\n"
	"The tiger hath perished, because he had no prey, and the lions' whelps are destroyed.\n"
	"Moreover to me there was spoken a secret word, and as it were by stealth hath mine ear received the veins of the whispering thereof.\n"
	"In the horror of a vision by night, when deep sleep is wont to hold men,\n"
	"fear held me, and trembling, and all my bones were made sore afraid:\n"
	"And when the spirit passed in my presence, the hairs of my flesh stood upright.\n"
	"There stood one, whose countenance I knew not, an image before mine eyes, and I heard the voice as it were of a gentle wind:\n"
	"What, shall man be justified in comparison of God, or shall a man be more pure than his maker?\n"
	"Behold they that serve him are not stable, and in his Angels he found wickedness:\n"
	"How much more they that inhabit houses of clay, which have an earthly foundation, shall be consumed as it were of the moth?\n"
	"From morning until evening they shall be cut down: and because none understandeth, they shall perish for ever.\n"
	"And they that shall be left, shall be taken away from them: they shall die, and not in wisdom.";