const char* chap478 = "But Job answering, said:\n"
	"would God my sins were weighed, whereby I have deserved wrath, and the calamity, which I suffer, in a balance.\n"
	"As the sand of the sea this would appear heavier, wherefore my words also are full of sorrow:\n"
	"Because the arrows of our Lord be in me, the indignation whereof drinketh up my spirit, & the terrors of our Lord war against me.\n"
	"Will the wild ass roar when he hath grass? Or the oxe loweth when he shall stand before the full manger?\n"
	"Or can an unsavoury thing be eaten, that is not seasoned with salt? Or can a man taste that which being tasted bringeth death?\n"
	"The things which before^ my soul would not touch, now for anguish are my meats.\n"
	"Who will grant that my petition may come: and that God would give me that which I expect?\n"
	"And he that hath begun, the same would loose his hand, and cut me off?\n"
	"And this might be my comfort, that afflicting me with sorrow, he spare not, nor I gainsay the words of the Holy one.\n"
	"For what is my strength, that I can sustain it? Or what is mine end, that I should do patiently?\n"
	"Neither is my strength the strength of stones, neither is my flesh of brass.\n"
	"Behold there is no help for me in myself, and my familiar friends also are departed from me.\n"
	"He that taketh away mercy from his friend, forsaketh the fear of our Lord.\n"
	"My brethren have passed by me, as the torrent that passeth swiftly in the valleys.\n"
	"They that fear the hoarfrost, snow shall fall upon them.\n"
	"At the time, when they shall be dissipated they shall perish: & after they wax hot they shall be dissolved out of their place.\n"
	"The paths of their steps are entangled: they shall walk in vain, & shall perish.\n"
	"Consider ye the paths of Thema, the ways of Saba, and expect a little while.\n"
	"They are confounded, because I have hoped: they are come also even unto me, and are covered with shame.\n"
	"Now you are come: and even now seeing my plague you are afraid.\n"
	"Have I said: Bring ye to me, and of your substance give to me?\n"
	"Or deliver me from the hand of the enemy, and out of the hand of the strong deliver me?\n"
	"Teach ye me, and I will hold my peace: and if I perhaps have been ignorant in any thing, instruct ye me.\n"
	"Why have you detracted from the words of truth, whereas there is none of you that can control me?\n"
	"To rebuke only you frame speeches, and you utter words in the wind.\n"
	"You rush in upon a pupil, and you endeavour to overthrow your friend.\n"
	"Notwithstanding accomplish that which you have begun: give ear, and see whether I lie.\n"
	"Answer I beseech you without contention: and speaking that which is just, judge ye.\n"
	"And you shall not find iniquity in my tongue, neither shall folly sound in my jaws.";