const char* chap48 = "These things being so done, it was told Joseph that his father was sick: who, taking his two sons Manasses and Ephraim, went forward.\n"
	"And it was told the old man: Behold thy son Joseph cometh to thee. Who being strengthened sat on his bed.\n"
	"And Joseph being entered in to him, he said: God Almighty appeared to me in Luza, which is in the Land of Chanaan: and he blessed me,\n"
	"and said: I will increase, and multiply thee, and make thee into multitudes of peoples: and I will give thee this land, and to thy seed after thee for an everlasting possession.\n"
	"Thy two sons therefore which were born to thee in the Land of Aegypt before I came hither to thee, shall be mine: Ephraim and Manasses, as Ruben and Simeon shall be reputed to me.\n"
	"But the rest begotten of thee after them, shall be thine, and shall be called by the name of their brethren in their possessions.\n"
	"For unto me, when I came out of Mesopotamia, Rachel died in the land of Chanaan in the very journey, and it was spring time: and I entered into Ephrata, and buried her by the way side to Ephrata, which by another name is called Bethleem.\n"
	"And seeing his sons he said to him: Who are these?\n"
	"He answered: They are my sons, whom God hath given me in this place. Bring them, quoth he, to me, that I may bless them.\n"
	"For Israel's eyes were dim by reason of very great age, and he could not see clearly. And when they were set beside him, kissing and embracing them,\n"
	"he said to his son: I am not defrauded of thy sight, moreover God hath shewed me thy seed.\n"
	"And when Joseph had taken them from his father's lap, he adored prostrate unto the ground.\n"
	"And he set Ephraim on his right hand, that is, on the left hand of Israel: but Manasses on his own left hand, to wit, on his father's right hand, and put them near to him.\n"
	"Who stretching forth his right hand, put it upon the head of Ephraim the younger brother: and the left upon the head of Manasses, that was the elder, changing hands.\n"
	"And Jacob blessed the sons of Joseph, and said: God, in whose sight my fathers Abraham & Isaac have walked, God that feedeth me from my youth until this present day:\n"
	"The Angel that delivereth me from all evils, bless these children: and be my name called upon them, the names also of my fathers Abraham, and Isaac, and grow they into a multitude upon the earth.\n"
	"And Joseph seeing that his father had put his right hand upon the head of Ephraim, took it heavily: and taking his father's hand he went about to lift it from Ephraim's head & to remove it upon the head of Manasses.\n"
	"And he said to his father: It is not convenient father so to be: because this is the first-begotten put thy right hand upon his head.\n"
	"Who refusing, said: I know my son, I know: and this same indeed shall be into peoples, and shall be multiplied: but his younger brother shall be greater than he: and his seed shall grow into nations.\n"
	"And he blessed them at that time, saying: In thee shall Israel be blessed, and it shall be said: God do unto thee as unto Ephraim, & as unto Manasses. And he set Ephraim before Manasses.\n"
	"And he said to Joseph his son: Behold I die, & God will be with you, and will bring you back into the land of your fathers.\n"
	"I do give thee one portion above thy brethren, which I took out of the hand of the Amorrhean with my sword and bow.";