const char* chap483 = "But Sophar the Naamathite answering, said:\n"
	"Why, shall he that speaketh many things, not hear also? Or shall a man full of words be justified?\n"
	"To thee only shall men hold their peace? & when thou hast mocked others, shalt thou be confuted of none?\n"
	"For thou hast said: My word is pure, and I am clean in thy sight.\n"
	"And I would wish that God would speak with thee, and would open his lips to thee.\n"
	"That he might shew thee the secrets of wisdom, and that his law is manifold, and thou mightest understand that thou art exacted much lesser things of him than thy iniquity deserveth.\n"
	"Peradventure thou wilt comprehend the steps of God, and wilt find out the Omnipotent perfectly?\n"
	"He is higher than heaven, and what wilt thou do? Deeper than hell, and how wilt thou know?\n"
	"The measure of him is longer than the earth, & broader than the sea.\n"
	"If he shall overthrow all things, or shall straiten them into one, who shall say against him?\n"
	"For he knoweth the vanity of men, & seeing iniquity doth he not consider?\n"
	"A vain man is extolled into pride, & thinketh himself born free as a wild ass's colt.\n"
	"But thou hast confirmed thy heart, & hast spread thy hands to him.\n"
	"If thou shalt take away from thee the iniquity that is in thy hand, & injustice remain not in thy tabernacle:\n"
	"Then mayst thou lift up thy face without spot, & thou shalt be stable, & shalt not fear.\n"
	"Thou shalt also forget misery, & shalt remember it as waters that are passed.\n"
	"And the brightness as it were of noon days, shall arise to thee at evening: and when thou shalt think thyself consumed, thou shalt rise as the day star.\n"
	"And thou shalt have confidence, hope being set before thee, & buried thou shalt sleep secure.\n"
	"Thou shalt rest, and there shall be none to terrify thee: and very many shall beseech thy face.\n"
	"But the eyes of the impious shall decay, and escape shall fail them, and their hope the abomination of the soul.";