const char* chap489 = "My spirit shall be extenuated, my days shall be shortened, and the grave only remaineth for me.\n"
	"I have not sinned, and mine eye abideth in bitterness.\n"
	"Deliver me, and set me beside thee, and let any man's hand fight against me.\n"
	"Thou hast made their heart far from discipline, and therefore they shall not be exalted.\n"
	"He promiseth a prey to his fellows, and the eyes of his children shall fail.\n"
	"He hath set me as it were for a proverb of the common people, and I am an example before them.\n"
	"Mine eye is dim for indignation, and my members are brought as it were to nothing.\n"
	"The just shall be astonished upon this, and the innocent shall be raised up against the hypocrite.\n"
	"And the just shall hold his way, & with clean hands shall add strength.\n"
	"Be all you therefore converted, and come, and I shall not find among you any wise man.\n"
	"My days have passed, my cogitations are dissipated, tormenting my heart:\n"
	"Night they have turned into day, and again after darkness I hope for light.\n"
	"If I shall expect, hell is my house, and in darkness I have made my bed.\n"
	"I have said to rottenness: Thou art my father, my mother, and my sister, to worms.\n"
	"Where is now then my expectation, and my patience who considereth.\n"
	"All my things shall descend into most deep hell: there at the least, shall I have rest thinkest thou?";