const char* chap491 = "But Job answering, said:\n"
	"How long do you afflict my soul, and wear me with words?\n"
	"Behold, ten times you confound me, and are not ashamed oppressing me.\n"
	"For although I have been ignorant, mine ignorance shall be with me.\n"
	"But you are set up against me, & reprove me with reproaches.\n"
	"At the least now understand ye, that God hath afflicted me not with equal judgment, and hath compassed me with his scourges.\n"
	"Behold I shall cry suffering violence, and no man will hear: I shall cry out, and there is none to judge.\n"
	"He hath hedged my path round about and I cannot pass, and in my way hath put darkness.\n"
	"He hath spoiled me of my glory, and hath taken the crown from my head.\n"
	"He hath destroyed me on every side, and I perish, and as it were from a tree plucked hath he taken away my hope.\n"
	"His fury is wrath against me, and he hath so accounted me as his enemy.\n"
	"His servants have come together, and have made themselves a way by me, and have besieged my tabernacle round about.\n"
	"He hath made my brethren far from me, and my acquaintance as strangers have departed from me.\n"
	"My kinsmen have forsaken me, and they that knew me have forgotten me.\n"
	"The guests of my house, and my maidservants have counted me an alien, and I have been as it were a stranger in their eyes.\n"
	"I called my servant, and he did not answer me, with mine own mouth I besought him.\n"
	"My wife hath abhorred my breath, and I prayed the children of my womb.\n"
	"Fools also despised me, and when I was departed from them, they backbited me.\n"
	"My counsellers sometime have abhorred me: & he whom I loved most hath turned against me.\n"
	"The flesh being consumed, my bone hath cleaved to my skin, and there are left only lips about my teeth.\n"
	"Have mercy upon me, have mercy upon me, at the least you my friends, because the hand of our Lord hath touched me.\n"
	"Why do you as God persecute me, and are filled with my flesh?\n"
	"Who will grant me that my words may be written? Who will give me that they may be drawn in a Book,\n"
	"with iron pen, & in plate of lead, or else with stile might be graven in flint-stone?\n"
	"For I know that my Redeemer liveth, & in the last day I shall rise out of the earth.\n"
	"And I shall be compassed again with my skin, and in my flesh I shall see God.\n"
	"Whom I myself shall see, & mine eyes shall behold, & none other: this my hope is laid up in my bosom.\n"
	"Why then do you say now: Let us persecute him, & let us find root of word against him?\n"
	"Fly therefore from the face of the sword, because the sword is the revenger of iniquities: and know ye that there is judgment.";