const char* chap5 = "This is the book of the generation of Adam. In the day, when God created man, to the likeness of God made he him.\n"
	"Male and female created he them; and blessed them: and called their name Adam, in the day when they were created.\n"
	"And Adam lived an hundred and thirty years; & begat to his own image and likeness, and called his name Seth.\n"
	"And the days of Adam, after he begat Seth, came to eight hundred years: and he begat sons and daughters.\n"
	"And all the time that Adam lived, came to nine hundred & thirty years, and he died.\n"
	"Set also lived an hundred five years, and begat Enos.\n"
	"And Seth lived after he begat Enos, eight hundred and seven years, and begat sons and daughters.\n"
	"And all the days of Seth came to nine hundred & twelve years, and he died.\n"
	"And Enos lived ninety years, and begat Cainan.\n"
	"After whose birth he lived eight hundred and fifteen years, and begat sons and daughters.\n"
	"And all the days of Enos came to nine hundred and five years, and he died.\n"
	"Cainan also lived seventy years, & begat Malaleel.\n"
	"And Cainan lived after he begat Malaleel, eight hundred & forty years, and begat sons and daughters.\n"
	"And all the days of Cainan came to nine hundred and ten years, and he died.\n"
	"And Malaleel lived sixty five years and begat Jared.\n"
	"And Malaleel lived after he begat Jared, eight hundred & thirty years, and begat sons and daughters.\n"
	"And all the days of Malaleel came to eight hundred ninety five years, and he died.\n"
	"And Jared lived an hundred sixty two years, and begat Enoch.\n"
	"And Jared lived after he begat Enoch eight hundred years, and begat sons and daughters.\n"
	"And all the days of Jared came to nine hundred sixty two years, and he died.\n"
	"Moreover Enoch lived sixty five years, and begat Mathusala.\n"
	"And Enoch walked with God: and lived after he begat Mathusala, three hundred years, and begat sons and daughters.\n"
	"And all the days of Enoch came to three hundred sixty five years.\n"
	"And he walked with God, and was seen no more: because God took him.\n"
	"Mathusala also lived an hundred eighty seven years, and begat Lamech.\n"
	"And Mathusala lived, after he begat Lamech, seven hundred eighty two years, and begat sons and daughters.\n"
	"And all the days of Mathusala came to nine hundred sixty nine years, and he died.\n"
	"And Lamech lived an hundred eighty two years, & begat a son:\n"
	"and he called his name Noe, saying: This son shall comfort us from the works & labours of our hands on the earth, which our Lord cursed.\n"
	"And Lamech lived, after he begat Noe, five hundred ninety five years, and begat sons and daughters.\n"
	"And all the days of Lamech came to seven hundred seventy seven years, and he died. And Noe when he was five hundred years old, begat Sem, Cham, and Japhet.";