const char* chap504 = "But these three men omitted to answer Job, for that he seemed just to himself.\n"
	"And Eliu the son of Barachel a Buzite, of the kindred of Ram, was angry and took indignation: and he was angry against Job, for that he said himself to be just before God.\n"
	"Moreover against his friends he had indignation, for that they had not found a reasonable answer, but only had condemned Job.\n"
	"Therefore Eliu expected Job speaking, because they were his elders that spake.\n"
	"But when he saw that the three were not able to answer, he was wrath exceedingly.\n"
	"And Eliu the son of Barachel a Buzite answering, said: I am younger in time, and you more ancient, therefore casting down my head, I was afraid to shew you my sentence.\n"
	"For I hoped that longer age would speak, and that a multitude of years would teach wisdom.\n"
	"But as I see, there is a Spirit in men, and the inspiration of the Omnipotent giveth understanding.\n"
	"They of many years are not the wise men, neither do the ancients understand judgment.\n"
	"Therefore will I speak: Hear ye me, I also will shew you my wisdom.\n"
	"For I have expected your words, I have heard your wisdom, as long as you contended in words.\n"
	"And as long as I thought you said somewhat, I considered: but as I see, here is none of you that can reprove Job, and answer to his words.\n"
	"Lest perhaps you may say: We have found wisdom, God hath rejected him, not man.\n"
	"He hath spoken nothing to me, and I will not answer him according to your words.\n"
	"They were afraid, and answered no more, and they have taken away talk from themselves.\n"
	"Therefore because I have expected, and they spake not: they stood, and answered no more:\n"
	"I also will answer my part, & will shew my knowledge.\n"
	"For I am full of words, and the spirit of my belly straiteneth me.\n"
	"Behold, my belly is as new wine without a vent, which breaketh new vessels.\n"
	"I will speak, and take breath a little: I will open my lips, and will answer.\n"
	"I will not accept the person of a man, & I will not make God equal to man.\n"
	"For I know not how long I shall continue, and whether after a while my maker will take me away.";