const char* chap505 = "Hear therefore Job my sayings, and harken to all my words.\n"
	"Behold I have opened my mouth, let my tongue speak within my jaws.\n"
	"My words are of my simple heart, and my lips shall speak a pure sentence.\n"
	"The Spirit of God made me, and the breadth of the Omnipotent gave me life.\n"
	"If thou canst, answer me, and stand against my face.\n"
	"Behold God hath made me also even as thee, and of the same clay I also was formed.\n"
	"But yet let not my miracle terrify thee, and let not my eloquence be burdenous to thee.\n"
	"Thou therefore hast said in my ears, and I have heard the voice of thy words:\n"
	"I am clean, and without sin: unspotted, and there is no iniquity in me.\n"
	"Because he hath found quarrels in me, therefore hath he thought me his enemy.\n"
	"He hath put my feet in the stocks, he hath observed all my ways.\n"
	"This therefore is it, wherein thou art not justified: I will answer thee, that God is greater than man.\n"
	"Doest thou contend against him because he hath not answered thee to all words?\n"
	"God, speaketh once, and repeateth not the self-same the second time.\n"
	"By a dream in a vision by night, when heavy sleep falleth upon men, and they sleep in their bed.\n"
	"Then doth he open the ears of men, and teaching instructeth them with discipline.\n"
	"That he may turn a man from these things, which he doth, and may deliver him from pride:\n"
	"Delivering his soul from corruption: and his life, that it pass not unto the sword.\n"
	"He rebuketh also by sorrow in the bed, and he maketh all his bones to wither.\n"
	"Bread is become abominable to him in his life, and to his soul the meat before desired.\n"
	"His flesh shall consume, and the bones that had been covered, shall be made naked.\n"
	"His soul hath approached to corruption, and his life to things causing death.\n"
	"If there shall be an Angel speaking for him, one of thousands, to declare man's equity.\n"
	"He shall have mercy on him, and shall say: deliver him, that he descend not into corruption: I have found wherein I may be propitious to him.\n"
	"His flesh is consumed with punishments, let it return to the days of his youth.\n"
	"He shall beseech God, and he will be pacified towards him: and he shall see his face in jubilation, and he will render to a man his justice.\n"
	"He shall behold men, and shall say: I have sinned, and indeed I have offended, and as I was worthy, I have not received.\n"
	"He hath delivered his soul that it should not go into death, but living should see the light.\n"
	"Behold all these things doth God work three times in every one.\n"
	"That he may reclaim their souls from corruption, and illuminate them with the light of the living.\n"
	"Attend Job, and hear me: and hold thy peace, whilst I speak.\n"
	"But if thou hast what to speak, answer me, speak, for I would thee to appear just.\n"
	"And if thou have not, hear me: hold thy peace, & I will teach thee wisdom.";