const char* chap508 = "Eliu also adding spake these words:\n"
	"Bear with me a little, and I will shew to thee: for as yet I have what to speak for God.\n"
	"I will repeat my knowledge from the beginning, and I will prove my maker just.\n"
	"For indeed my words are without lie, & perfect knowledge shall be proved to thee.\n"
	"God doth not cast away the mighty, whereas himself also is mighty.\n"
	"But he saveth not the impious, and he giveth judgment to the poor.\n"
	"He shall not take away his eyes from the just man, and he placeth kings in the throne for ever, and there they are extolled.\n"
	"And if they shall be in chains, & be bound with the ropes of poverty.\n"
	"He shall shew them their works, and their wicked deeds, because they have been violent.\n"
	"He also shall reveal their ear, to chastise them: & shall speak, that they may return from iniquity:\n"
	"If they shall hear and observe, they shall accomplish their days in good, and their years in glory.\n"
	"But if they hear not, they shall pass by the sword, and shall be consumed in folly.\n"
	"Dissemblers and crafty men provoke the wrath of God, neither shall they cry when they are bound.\n"
	"Their soul shall die in tempest, and their life, among the effeminate.\n"
	"He shall deliver the poor out of his distress, and shall reveal his ear in tribulation.\n"
	"Therefore he shall save thee most largely out of the narrow mouth, and not having foundation under it: and the quietness of thy table shall be full of fatness.\n"
	"Thy cause is judged as an impious man's, cause and judgment thou shalt receive.\n"
	"Let not therefore anger overcome thee, that thou oppress any man: neither let multitude of gifts incline thee.\n"
	"Lay down thy greatness without tribulation, & all the puissant of strength.\n"
	"Protract not the night, that peoples may come up for them.\n"
	"Beware thou decline not to iniquity: for thou hast begun to follow it after misery.\n"
	"Behold, God is high in his strength, and none is like to him among the law givers.\n"
	"Who can search his ways? Or who can say to him: Thou hast wrought iniquity?\n"
	"Remember that thou knowest not his work, whereof men have sung.\n"
	"All men see him, every one beholdeth far off.\n"
	"Behold, God is great surmounting our knowledge: the number of his years is inestimable.\n"
	"Who taketh away the drops of rain, & poureth out showers as it were gifts of water.\n"
	"Which flow out from the clouds, that cover all things from above.\n"
	"If he will stretch forth clouds as his tent,\n"
	"And lighten with his light from above, he shall cover also the ends of the sea.\n"
	"For by these he judgeth peoples, and giveth victuals to many mortal men.\n"
	"In his hands he hideth the light, & commandeth it that it come again.\n"
	"He sheweth his friend thereof, that it is his possession, and that he may ascend to it.";