const char* chap51 = "These be the names of the children of Israel, that entered into Aegypt with Jacob: they did enter in^ every one with their houses,\n"
	"Ruben, Simeon, Levi, Judas,\n"
	"Issachar, Zabulon, & Benjamin,\n"
	"Dan, and Nephthali, Gad, and Aser.\n"
	"Therefore all the souls that came out of Jacob's thigh were seventy: and Joseph was in Aegypt.\n"
	"Who being dead, and all his brethren, and all that generation,\n"
	"the children of Israel increased, and as it were springing up did multiply, and growing strong exceedingly, filled the land.\n"
	"In the mean time there arose a new king over Aegypt, that knew not Joseph:\n"
	"and he said to his people: Behold the people of the children of Israel is much, and stronger than we.\n"
	"Come, let us wisely oppress the same, lest perhaps it multiply: and if there shall be any war against us, it joined with our enemies, and we being overthrown, they depart out of the land.\n"
	"Therefore he set over them masters of the works, to afflict them with burdens: and they built unto Pharao cities of tabernacles, Phithom, and Ramesses.\n"
	"And the more they did oppress them, so much the more they multiplied and increased:\n"
	"and the Aegyptians hated the children of Israel, and deriding afflicted them:\n"
	"and they brought their life into bitterness with the hard works of clay and brick, & with all service, wherewith they were pressed in the works of the earth.\n"
	"And the king of Aegypt said to the midwives of the Hebrews, of whom one was called Sephora, the other Phua,\n"
	"commanding them: When you shall be midwives to the Hebrew women, and the time of delivery is come, if it be a man-child, kill it: if a woman, reserve her.\n"
	"But the midwives feared God, and did not according to the commandment of the king of Aegypt, but preserved the men-children.\n"
	"To whom being called unto him, the king said: What is this that you meant to do, that you would save the men-children?\n"
	"Who answered: The Hebrew women are not as the Aegyptian women: for they have the knowledge to play the midwife themselves, and before we come to them, they are delivered.\n"
	"God therefore did well to the midwives: and the people increased, and became strong exceedingly.\n"
	"And because the midwives feared God, he built them houses.\n"
	"Pharao therefore commanded all his people, saying: Whatsoever shall be born of the male-sex cast it into the river: whatsoever of the female, reserve it.";