const char* chap512 = "And our Lord answering Job out of the whirlwind, said:\n"
	"Gird thy loins as a man: I will ask thee, & do thou tell me.\n"
	"Shalt thou make my judgment of none effect: and condemn me, that thou mayst be justified?\n"
	"And hast thou an arm as God, and dost thou thunder with like voice?\n"
	"Put beauty about thee, and set up thyself aloft, and be glorious, and put on goodly garments.\n"
	"Disperse the proud in thy fury, and beholding every arrogant man, humble him.\n"
	"Behold all the proud, and confound them, and destroy the impious in their place.\n"
	"Hide them in the dust together, and plunge their faces in the pit.\n"
	"And I will confess, that thy right hand is able to save thee.\n"
	"Behold Behemoth whom I made with thee, shall eat hay as it were an oxe.\n"
	"His strength is in his loins, and his power in the navel of his belly.\n"
	"He gathereth together his tail as the cedar tree, the sinews of his stones are perplex.\n"
	"His bones are as pipes of brass, his gristle as it were plates of iron.\n"
	"He is the beginning of the ways of God, which made him, he shall apply his sword.\n"
	"To him the mountains bear grass: all the beasts of the field shall play there.\n"
	"He sleepeth under the shadow, in the secret of the reed, and in moist places.\n"
	"Shadows do protect his shadow, the willows of the torrent shall compass him.\n"
	"Lo, he shall sup up the river, & shall not marvel: and he hath confidence that Jordan may run into his mouth.\n"
	"In his eyes as with a hook he shall take him, and with stakes he shall bore through his nostrils.\n"
	"Canst thou draw out the Leviathan with a hook, and with a rope shalt thou tie his tongue?\n"
	"Shalt thou put a ring in his nostrils, or bore through his jaw with a buckle?\n"
	"Will he multiply prayers to thee, or speak to thee gentle words?\n"
	"Will he make a covenant with thee, and shalt thou take him to be a servant for ever?\n"
	"Shalt thou delude him as a bird, or tie him for thy handmaids?\n"
	"Shall friends cut him, merchants divide him?\n"
	"Shalt thou fill nests with his skin, and the cabin of fishes with his head?\n"
	"Lay thy hand upon him: remember battle, and add to speak no more.\n"
	"Behold his hope shall frustrate him, and in the sight of all he shall be cast down headlong.";