const char* chap521 = "The Psalm of David which he sung to our Lord, for the words of Chusi the son of Jemini.\n"
	"O Lord my God I have hoped in thee: save me from all that persecute me, and deliver me.\n"
	"Lest sometime he as a Lion violently take my soul, whilst there is none to redeem, nor to save.\n"
	"O Lord my God if I have done this, if there be iniquity in my hands:\n"
	"If I have rendered to them that repayed me evils, let me worthily fall empty from mine enemies.\n"
	"Let the enemy persecute my soul, and take it, and tread down my life in the earth, and bring down my glory into the dust.\n"
	"Arise Lord in thy wrath: and be exalted in the coasts of mine enemies.\n"
	"And arise, o Lord my God, in the precept which thou hast commanded: and a synagogue of peoples shall compass thee.\n"
	"And for it return on high: our Lord judgeth peoples. Judge me, o Lord, according to my justice, and according to my innocency upon me.\n"
	"The wickedness of sinners shall be consumed, and thou shalt direct the just, which searchest the heart and reins, o God.\n"
	"My just help is from our Lord, who saveth those that be right of heart.\n"
	"God is a just judge, strong, & patient: is he angry every day?\n"
	"Unless you will be converted, he shall shake his sword, he hath bent his bow, and prepared it.\n"
	"And in it he hath prepared the vessels of death: he hath made his arrows for them that burn.\n"
	"Behold he hath bred with injustice: he hath conceived sorrow, and brought forth iniquity.\n"
	"He hath opened a pit, and digged it up: and he is fallen into the ditch, which he made.\n"
	"His sorrow shall be turned upon his head: and his iniquity shall descend upon his crown.\n"
	"I will confess to our Lord according to his justice: and will sing to the name of our Lord most high.";