const char* chap529 = "The inscription of the title to David himself. Preserve me, o Lord, because I have hoped in thee.\n"
	"I have said to our Lord: Thou art my God, because thou needest not my goods.\n"
	"To the Saints that are in his land, he hath made all my wills marvelous in them.\n"
	"Their infirmities were multiplied: afterward they made haste. I will not assemble their conventicles of blood: neither will I be mindful of their names by my lips.\n"
	"Our Lord the portion of mine inheritance, and of my cup: thou art he, that will restore mine inheritance unto me.\n"
	"Cords are fallen to me in goodly places: for mine inheritance is goodly unto me.\n"
	"I will bless our Lord, who hath given me understanding: moreover also even till night my veins have rebuked me.\n"
	"I foresaw our Lord in my sight always: because he is at my right hand, that I be not moved.\n"
	"For this thing my heart hath been glad, and my tongue hath rejoiced: moreover also my flesh shall rest in hope.\n"
	"Because thou wilt not leave my soul in hell: neither wilt give thy holy one to see corruption. Thou hast made the ways of life known to me, thou shalt make me full of joy with thy countenance: delectations on thy right hand, even to the end.";