const char* chap53 = "And Moyses fed the sheep of Jethro his father in law the Priest of Madian: and having driven the flock to the inner parts of the desert, he came to the mountain of God, Horeb.\n"
	"And our Lord appeared to him in a flame of fire out of the midst of a bush: and he saw that the bush was on fire and was not burnt.\n"
	"Moyses therefore said: I will go, and see this great vision, why the bush is not burnt.\n"
	"And our Lord seeing that he went forward to see, he called him out of the midst of the bush, and said: Moyses, Moyses. Who answered: Here I am.\n"
	"But he said: Approach not hither, loose off thy show from thy feet: for the place wherein thou standest is holy ground.\n"
	"And he said: I am the God of thy father, the God of Abraham, the God of Isaac, and the God of Jacob. Moyses hid his face; for he durst not look against God.\n"
	"To whom our Lord said: I have seen the affliction of my people in Aegypt, and I have heard their cry because of their rigour that oversee the works:\n"
	"and knowing their sorrow, I am descended to deliver them out of the hands of the Aegyptians, and to bring them out of that land into a land good and large, into a land that floweth with milk and honey, to the place of the Chananeite, and Hetheite, and Amorrheite, and Pherezeite, and Heveite, & Jebuseite.\n"
	"Therefore the cry of the children of Israel is come unto me: and I have seen their affliction wherewith they are oppressed by the Aegyptians.\n"
	"But come, and I will send thee to Pharao, that thou mayest bring forth my people the children of Israel out of Aegypt.\n"
	"And Moyses said to God: Who am I that I shall go to Pharao, and bring forth the children of Israel out of Aegypt?\n"
	"Who said to him: I will be with thee; and this thou shalt have for a sign that I have sent thee: When thou shalt have brought my people out of Aegypt, thou shalt sacrifice to God upon this mountain.\n"
	"Moyses said to God: Lo I shall go to the children of Israel, and say to them: The God of your fathers hath sent me to you. If they shall say to me: What is his name: What shall I say to them?\n"
	"God said to Moyses: I AM WHICH AM. He said: Thus shalt thou say to the children of Israel: HE WHICH IS, hath sent me to you.\n"
	"And God said again to Moyses: These things shalt thou say to the children of Israel: The Lord God of your fathers, the God of Abraham, the God of Isaac, and the God of Jacob hath sent me to you this is my name for ever, and this is my memorial into generation & to generation.\n"
	"Go, and gather together the Ancients of Israel, and thou shalt say to them: The Lord God of your fathers hath appeared to me, the God of Abraham, the God of Isaac, and the God of Jacob, saying: Visiting I have visited you: and I have seen all things that have chanced to you in Aegypt:\n"
	"and I have said the word to bring you forth out of the affliction of Aegypt, into the land of the Chananeite, and Hetheite, and Amorrheite, and Pherezeite, and Heveite, and Jebuseite, to a Land that floweth with milk and honey.\n"
	"And they shall hear thy voice: and thou shalt enter in, thou and the ancients of Israel to the king of Aegypt, and thou shalt say to him: The Lord God of the Hebrews hath called us: We will go three days' journey into the wilderness to sacrifice unto the Lord our God.\n"
	"But I know that the king of Aegypt will not dismiss you to go but by mighty hand.\n"
	"For I will stretch forth my hand, and will strike Aegypt in all my marvels, which I will do in the midst of them: after these he will dismiss you.\n"
	"And I will give grace to this people in the sight of the Aegyptians: and when you shall go forth, you shall not depart empty:\n"
	"but each woman shall ask of her neighbour and of her that is in house with her^ vessels of silver and of gold, and raiment: and you shall lay it upon your sons and daughters, and shall spoil Aegypt.";