const char* chap530 = "The prayer of David. Hear, o Lord my justice: attend my petition. With thine ears hear my prayer, not in deceitful lips.\n"
	"From thy countenance let my judgment proceed: let thine eyes see equities.\n"
	"Thou hast proved my heart, and visited it by night: by fire thou hast examined me, and there is no iniquity found in me.\n"
	"That my mouth speak not the works of men: for the words of thy lips I have kept the hard ways.\n"
	"Perfit my passes in thy paths, that my steps be not moved.\n"
	"I have cried, because thou hast heard me, o God: incline thine ear to me, and hear my words.\n"
	"Make thy mercies marvelous, which savest them that hope in thee.\n"
	"From them that resist thy right hand keep me, as the apple of the eye. Under the shadow of thy wings protect me:\n"
	"from the face of the impious, that have afflicted me. Mine enemies have compassed my soul,\n"
	"they have shut up their fat: their mouth hath spoken pride.\n"
	"Casting me forth now have they compassed me: they have set their eyes to bend them unto the earth.\n"
	"They have taken me as a lion ready to the prey: and as a lion's whelp dwelling in hid places.\n"
	"Arise Lord, prevent him, and supplant him: deliver my soul from the impious, thy sword\n"
	"from the enemies of thy hand. Lord from a few out of the land divide them, in their life: their belly is filled of thy secrets. They are filled with children: and they have left their remnants to their little ones.\n"
	"But I in justice shall appear to thy sight: I shall be filled when thy glory shall appear?";