const char* chap532 = "Unto the end, the Psalm of David.\n"
	"The heavens shew forth the glory of God, and the firmament declareth the works of his hands.\n"
	"Day unto day uttereth word: and night unto night sheweth knowledge.\n"
	"There are no languages, nor speeches, whose voices are not heard.\n"
	"Their sound hath gone forth into all the earth; and unto the ends of the round world the words of them.\n"
	"He put his tabernacle in the sun: & himself as a bridegroom coming forth of his bride-chamber. He hath rejoiced as a giant to run the way,\n"
	"his coming forth from the top of heaven: And his recourse even to the top thereof: neither is there that can hide himself from his heat.\n"
	"The law of our Lord is immaculate converting souls: the testimony of our Lord is faithful, giving wisdom to little ones.\n"
	"The justices of our Lord be right, making hearts joyful: the precept of our Lord lightsome, illuminating the eyes.\n"
	"The fear of our Lord is holy, permanent for ever and ever: the judgments of our Lord be true, justified in themselves.\n"
	"To be desired above gold and much precious stone: and more sweet above honey and the honey-comb.\n"
	"For thy servant keepeth them, in keeping them is much reward.\n"
	"Sins who understandeth? From my secret sins cleanse me:\n"
	"and from other mens spare thy servant. If they shall not have dominion over me, then shall I be immaculate; and shall be cleansed from the greatest sin.\n"
	"And the words of my mouth shall be such as may please: and the meditation of my heart in thy sight always. O Lord my helper and my Redeemer.";