const char* chap533 = "Unto the end, the Psalm of David.\n"
	"Our Lord hear thee in the day of tribulation: the name of the God of Jacob protect thee.\n"
	"Send he aid to thee from the holy place: and from Sion defend he thee.\n"
	"Be he mindful of all thy sacrifice: and be thy holocaust made fat.\n"
	"Give he unto thee according to thy heart: and confirm he all thy counsel.\n"
	"We shall rejoice in thy salvation: and in the name of our God we shall be magnified.\n"
	"Our Lord accomplish all thy petitions: now have I known that our Lord hath saved his CHRIST. He shall hear him from his holy heaven: the salvation of his right hand is in powers.\n"
	"These in chariots, and these in horses: but we will invocate in the name of the Lord our God.\n"
	"They are bound, & have fallen: but we have risen & are set upright.\n"
	"Lord save the king, and hear us in the day, that we shall invocate thee";