const char* chap54 = "Moyses answering said: They will not believe me, nor hear my voice, but they will say: Our Lord hath not appeared to thee.\n"
	"Therefore he said to him: What is that thou holdest in thy hand? He answered: A rod.\n"
	"And our Lord said: Cast it upon the ground. He did cast it, and it was turned into a serpent, so that Moyses fled.\n"
	"And our Lord said: Stretch thy hand, & catch the tail thereof. He stretched it forth, & took hold of it, and it was turned into a rod.\n"
	"That they may believe, quoth he, that the Lord God of their fathers hath appeared to thee, the God of Abraham, the God of Isaac, & the God of Jacob.\n"
	"And our Lord said again: Put thy hand into thy bosom. Which when he had put into his bosom, he brought it forth full of leprosy like snow.\n"
	"Draw back, quoth he, thy hand into thy bosom. He drew it back, and brought it forth again, & it was like the other flesh.\n"
	"If they will not believe thee, quoth he, nor hear the word of the former sign, they will believe the word of the sign following.\n"
	"And if so be they will believe neither of these two signs, nor hear thy voice, take water of the river, & pour it out upon the dry land, and whatsoever thou drawest of the river shall be turned into blood.\n"
	"Moyses said: I beseech thee, Lord, I am not eloquent from yesterday and the day before: and since thou hast spoken to thy servant, I have more impediment & slowness of tongue.\n"
	"Our Lord said to him: Who made the mouth of man; or who framed the dumb and deaf, the seeing and the blind? Did not I?\n"
	"Go on therefore, and I will be in thy mouth; & will teach thee what thou shalt speak.\n"
	"But he said: I beseech thee, Lord, send whom thou wilt send.\n"
	"Our Lord being angry at Moyses, said: Aaron thy brother the Levite, I know that he is eloquent: behold he cometh forth to meet thee, & seeing thee shall be glad at the heart.\n"
	"Speak to him, and put my words in his mouth; & I will be in thy mouth, and in his mouth, and will shew you what ye must do.\n"
	"He shall speak in thy stead to the people, and shall be thy mouth: but thou shalt be to him in those things that pertain to God.\n"
	"This rod also take in thy hand, wherewith thou shalt do the signs.\n"
	"Moyses went his way, & returned to Jethro his father in law, and said to him: I will go and return to my brethren in Aegypt, that I may see if they be yet alive. To whom Jethro said: Go in peace:\n"
	"Therefore our Lord said to Moyses in Madian: Go, and return into Aegypt: for they are all dead that sought thy life.\n"
	"Moyses therefore took his wife, and his children, and set them upon an ass: and returned into Aegypt, carrying the rod of God in his hand.\n"
	"And our Lord said to him returning into Aegypt: See that thou do all the wonders which I have put in thy hand, before Pharao: I will indurate his heart, and he will not dismiss the people.\n"
	"And thou shalt say to him: This saith the Lord: My first-begotten son is Israel.\n"
	"I said to thee: dismiss my son that he may serve me, and thou wouldst not dismiss him: behold I will kill thy first-begotten son.\n"
	"And when he was in his journey, in the Inn, our Lord met him, and would have killed him.\n"
	"Sephora by and by took a very sharp stone, and circumcised the prepuce of her son, and touched his feet, and said: A bloody spouse thou art to me.\n"
	"And he let him go after she had said, A bloody spouse thou art to me, because of the circumcision.\n"
	"And our Lord said to Aaron: Go to Moyses into the desert. Who went forth to meet him unto the Mountain of God, and kissed him.\n"
	"And Moyses told Aaron all the words of our Lord, by which he had sent him, and the signs that he had commanded.\n"
	"And they came together, and gathered together all the ancients of the children of Israel.\n"
	"And Aaron spake all the words which our Lord had said to Moyses: and he wrought the signs before the people,\n"
	"and the people believed. And they heard that our Lord had visited the children of Israel, and that he had looked upon their affliction; and they adored prostrate.";