const char* chap540 = "The Psalm of David before he was anointed. Our Lord is my illumination, and my salvation, whom shall I fear? Our Lord is the protector of my life, of whom shall I be afraid?\n"
	"Whilst the harmful approach upon me, to eat my flesh. Mine enemies that trouble me, themselves are weakened and are fallen.\n"
	"If camps stand together against me, my heart shall not fear. If battle rise up against me, in this will I hope.\n"
	"One thing I have asked of our Lord, this will I seek for, that I may dwell in the house of our Lord all the days of my life. That I may see the pleasantness of our Lord, and visit his temple.\n"
	"Because he hath hid me in his tabernacle: in the day of evils he hath protected me, in the secret of his tabernacle.\n"
	"In a rock he hath exalted me: and now he hath exalted my head over mine enemies. I have gone round about, and have immolated in his tabernacle an host of jubilation: I will sing, and say a Psalm to our Lord.\n"
	"Hear, o Lord, my voice, wherewith I have cried to thee: have mercy on me, and hear me.\n"
	"My heart hath said to thee, my face hath sought thee out: thy face, o Lord, I will seek.\n"
	"Turn not away thy face from me: decline not in wrath from thy servant. Be thou my helper: forsake me not, neither despise me, o God my Saviour.\n"
	"because my father and my mother have forsaken me: but our Lord hath taken me.\n"
	"Give me a law, o Lord, in thy way: and direct me in the right path, because of mine enemies.\n"
	"Deliver me not into the souls of them that trouble me: because unjust witnesses have risen up against me: and iniquity hath lied to it-self.\n"
	"I believe to see the good things of our Lord, in the land of the living.\n"
	"Expect our Lord, do manfully: and let thy heart take courage, and expect thou our Lord.";