const char* chap546 = "The Psalm of David. Rejoice ye just in our Lord; praising becometh the righteous.\n"
	"Confess ye to our Lord on the harp: on a psalter of ten strings sing to him.\n"
	"Sing ye to him a new song: sing well to him in jubilation.\n"
	"Because the word of our Lord is right, and all his works are in faith.\n"
	"He loveth mercy and judgment: the earth is full of the mercy of our Lord.\n"
	"By the word of our Lord the heavens are established: and by the spirit of his mouth all the power of them,\n"
	"Gathering together the waters of the sea, as it were in a bottle: putting the depths in treasures.\n"
	"Let all the earth fear our Lord: and let all the inhabitants of the world be moved at him.\n"
	"Because he said, and they were made: he commanded and they were created,\n"
	"Our Lord dissipateth the counsels of nations: and he reproveth the cogitations of people, and he reproveth the counsels of princes.\n"
	"But the counsel of our Lord abideth for ever, the cogitations of his heart in generation and generation.\n"
	"Blessed is the nation, whose God is our Lord: the people whom he hath chosen for his inheritance.\n"
	"Our Lord hath looked from heaven: he hath seen all the children of men.\n"
	"From his prepared habitation he hath looked upon all that inhabit the earth\n"
	"Who made their hearts severally: who understandeth all their works.\n"
	"The king is not saved by much power: and the giant shall not be saved in the multitude of his strength.\n"
	"The horse faileth to safety, and in the aboundance of his force he shall not be saved.\n"
	"Behold the eyes of our Lord be upon them that fear him: and on them, that hope upon his mercy.\n"
	"That he may deliver their souls from death: and nourish them in famine.\n"
	"Our soul expecteth our Lord: because he is our helper and protector.\n"
	"Because in him our heart shall rejoice: and we have trusted in his holy name.\n"
	"Let thy mercy, o Lord, be made upon us, as we have hoped in thee.";