const char* chap547 = "To David, when he changed his countenance before Abimelech, and he dismist him, and he went away\n"
	"I will bless our Lord at all time: his praise always in my mouth.\n"
	"In our Lord my soul shall be praised: let the mild hear, and rejoice.\n"
	"Magnify ye our Lord with me: and let us exalt his name for ever.\n"
	"I have sought out our Lord, and he hath heard me: and from all my tribulations he hath delivered me.\n"
	"Come ye to him, and be illuminated: and your faces shall not be confounded.\n"
	"This poor man hath cried, and our Lord hath heard him: and from all his tribulations he hath saved him.\n"
	"The Angel of our Lord shall put in himself about them that fear him: and shall deliver them.\n"
	"Taste ye, and see that our Lord is sweet: blessed is the man, that hopeth in him.\n"
	"Fear ye our Lord all ye his Saints: because there is no lack to them that fear him.\n"
	"The rich have wanted, and have been hungry: but they that seek after our Lord shall not be diminished of any good.\n"
	"Come children, hear me: I will teach you the fear of our Lord.\n"
	"who is the man that will have life: loveth to see good days?\n"
	"Stay thy tongue from evil: and thy lips that they speak not guile.\n"
	"Turn away from evil, and do good: seek after peace and pursue it.\n"
	"The eyes of our Lord upon the just: and his ears unto their prayers.\n"
	"But the countenance of our Lord is upon them that do evil things: to destroy their memory out of the earth.\n"
	"The just have cried, and our Lord hath heard them: and out of all their tribulations he hath delivered them.\n"
	"Our Lord is nigh to them, that are of a contrite heart: and the humble of spirit he will save.\n"
	"Many are the tribulations of the just: and out of all these our Lord will deliver them.\n"
	"Our Lord keepeth all their bones: there shall not one of them be broken.\n"
	"The death of sinners is very ill: and they that hate the just shall offend.\n"
	"Our Lord will redeem the souls of his servants: and all that hope in him shall not offend.";