const char* chap548 = "To David himself. Judge o Lord them that hurt me: overthrow them that impugn me.\n"
	"Take armour and shield: and rise up to help me.\n"
	"Bring forth the sword, and shut up against them, that persecute me: say to my soul: I am thy salvation.\n"
	"Let them be confounded & ashamed, that seek my soul. Let them be turned backward, and be confounded that think evil against me.\n"
	"Be they made as dust before the face of wind; and the Angel of our Lord straitening them\n"
	"Let their way be made darkness and slipperness: and the Angel of our Lord pursuing them.\n"
	"Because they have hid the destruction of their snare for me without cause: in vain have they upbraided my soul.\n"
	"Let the snare which he knoweth not, come on him; and the net, which he hath hid, catch him: and let him fall into the very same snare.\n"
	"But my soul shall rejoice in our Lord: and shall be delighted upon his salvation.\n"
	"All my bones shall say: Lord, who is like to thee? Delivering the needy from the hand of them that are stronger than he: the needy and poor from them that spoil him.\n"
	"Unjust witnesses rising up, asked me things that I knew not.\n"
	"They repayed me evil thing for good, sterility to my soul.\n"
	"But I when they were troublesome to me, did put on cloth of hair. I humbled my soul in fasting: and my prayer shall be turned into my bosom.\n"
	"As a neighbour, as our brother, so did I please: as mourning and sorrowful so was I humbled.\n"
	"And they rejoiced against me, and came together: scourges were gathered together upon me, and I was ignorant.\n"
	"They were dissipated, and not compunct, they tempted me, they scorned me with scorning: they gnashed upon me with their teeth.\n"
	"Lord when wilt thou regard? Restore thou my soul from their malignity, mine only one from the lions.\n"
	"I will confess to thee in the great Church, in a grave people I will praise thee.\n"
	"Let them not rejoice over me that are my adversaries unjustly: that hate me without cause, and twinkle with the eyes.\n"
	"Because they spake indeed peaceably to me: and in the anger of the earth speaking they meant guiles.\n"
	"And they opened their mouth awide upon me: they said, Well, well, our eyes have seen.\n"
	"Thou hast seen, o Lord, keep not silence: Lord depart not from me.\n"
	"Arise and attend to my judgment: my God, and my Lord unto my cause.\n"
	"Judge me according to thy justice, o Lord my God, and let them not rejoice over me.\n"
	"Let them not say in their hearts: Well, well, to our soul: neither let them say, We have devoured him.\n"
	"Let them blush and be ashamed together, that rejoice at my evils. Let them be clothed with confusion and shame, that speak great things upon me.\n"
	"Let them rejoice and be glad, that will my justice: and let them say always: Our Lord be magnified, that will the peace of his servant.\n"
	"And my tongue shall meditate thy justice, thy praise all the day.";