const char* chap549 = "Unto the end, to the servant of our Lord David himself.\n"
	"The unjust hath said within himself, that he would sin: there is no fear of God before his eyes.\n"
	"Because he hath done deceitfully in his sight: that his iniquity may be found unto hatred.\n"
	"The words of his mouth are iniquity, and guile: he would not understand that he might do well.\n"
	"He hath meditated iniquity in his bed: he hath set himself on every way not good, and malice he hath not hated.\n"
	"Lord thy mercy is in heaven: and thy truth even to the clouds.\n"
	"Thy justice as the hills of God: thy judgments are great depth. Men & beasts thou wilt save, o Lord,\n"
	"as thou hast multiplied thy mercy, o God. But the children of men shall hope in the covert of thy wings.\n"
	"They shall be inebriated with the plenty of thy house: and with the torrent of thy pleasure thou shalt make them drink.\n"
	"Because with thee is the fountain of life: and in thy light we shall see light.\n"
	"Extend thy mercy to them that know thee, and thy justice to them, that are of a right heart.\n"
	"Let not the foot of pride come to me: and let not the hand of a sinner move me.\n"
	"There have they fallen that work iniquity: they were expelled, neither could they stand.";