const char* chap550 = "A Psalm to David himself. Have no emulation toward the malignant: neither envy them that do iniquity.\n"
	"Because they shall quickly wither as grass: and as the blossoms of herbs they shall soon fall.\n"
	"Hope in our Lord and do good: and inhabit the land, and thou shalt be fed in the riches thereof.\n"
	"Be delighted in our Lord: & he will give thee the petitions of thy heart.\n"
	"Reveal thy way to our Lord, and hope in him: and he will do it.\n"
	"And he will bring forth thy justice as light: and thy judgment as midday:\n"
	"Be subject to our Lord, and pray him. Have no emulation in him, that prospereth in his way: in a man that doth injustices.\n"
	"Cease from wrath, and leave fury: have not emulation that thou be malignant.\n"
	"Because they that are malignant, shall be cast out: but they that expect our Lord, the same shall inherit the land.\n"
	"And yet a little while, and the sinner shall not be: and thou shalt seek his place, and shall not find it.\n"
	"But the meek shall inherit the land, and shall be delighted in multitude of peace.\n"
	"The sinner shall observe the just: & shall gnash upon him with his teeth.\n"
	"But our Lord shall scorn him: because he foreseeth that his day shall come.\n"
	"Sinners have drawn out the sword: they have bent their bow; That they may deceive the poor and needy: that they may murder the right of heart.\n"
	"Let their own swords enter into their hearts: and let their bow be broken.\n"
	"Better is a little to the just, above much riches of sinners.\n"
	"Because the arms of sinners shall be broken in pieces: but our Lord confirmeth the just.\n"
	"Our Lord knoweth the days of the immaculate: and their inheritance shall be for ever.\n"
	"They shall not be confounded in the evil time, and in the days of famine they shall be filled:\n"
	"because the sinners shall perish. But the enemies of our Lord forthwith as they shall be honoured and exalted, vanishing shall vanish as smoke.\n"
	"The sinner shall borrow, and not pay: but the just is merciful and will give.\n"
	"Because they that bless him shall inherit the land: but they that curse him shall perish.\n"
	"With our Lord the step of man shall be directed: and he shall like well of his way.\n"
	"When he shall fall, he shall not be bruised: because our Lord putteth his hand under.\n"
	"I have been young, for I am old: and I have not seen the just forsaken, nor his seed seeking bread.\n"
	"All the day he is merciful and lendeth: & his seed shall be in blessing.\n"
	"Decline from evil, & do good: and inhabit for ever & ever.\n"
	"Because our Lord loveth judgment, and he will not forsake his saints: they shall be preserved for ever. The unjust shall be punished: and the seed of the impious shall perish.\n"
	"But the just shall inherit the land: and shall inhabit for ever and ever upon it.\n"
	"The mouth of the just shall meditate wisdom, and his tongue shall speak judgment.\n"
	"The law of his God in his heart: and his steps shall not be supplanted.\n"
	"The sinner considereth the just: and seeketh to murder him.\n"
	"But our Lord will not leave him in his hands: neither will he condemn him, when judgment shall be given of him.\n"
	"Expect our Lord, and keep his way: and he will exalt thee, that thou mayst inherit the land: when the sinners shall perish^ thou shalt see.\n"
	"I have seen the impious highly exalted, and advance as the cedars of Libanus.\n"
	"And I passed by, and behold he was not: and I sought him, and his place was not found.\n"
	"Keep innocency, and see equity: because there are remains for the peaceable man.\n"
	"But the unjust shall perish together: the remains of the impious shall perish.\n"
	"But the salvation of the just is of our Lord: and he is their protector in the time of tribulation.\n"
	"And our Lord will help them, and deliver them: and he will take them away from sinners, and save them, because they have hoped in him.";