const char* chap558 = "Unto the end, for them, that shall be changed, to the sons of Core for understanding, a Canticle for the beloved.\n"
	"My heart hath uttered a good word: I tell my works to the king. My tongue is the pen of a scribe, that writeth swiftly.\n"
	"Goodly of beauty above the sons of men, grace is poured abroad in thy lips: therefore hath God blessed thee for ever.\n"
	"Be girded with thy sword upon thy thigh, o most mighty.\n"
	"With thy beauty and fairness intend, proceed prosperously, and reign, Because of truth, and mildness, and justice: and thy right hand shall conduct thee marvelously.\n"
	"Thy sharp arrows, the peoples underneath thee shall fall into the hearts of the king's enemies.\n"
	"Thy seat o God for ever and ever: a rod of direction the rod of thy Kingdom.\n"
	"Thou hast loved justice, and hast hated iniquity: therefore God, thy God, hath anointed thee with the oil of gladness above thy fellows.\n"
	"Myrrh, and Aloes, and Cassia from thy garments, from houses of ivory, out of the which\n"
	"the daughters of kings have delighted thee in thy honour.\n"
	"The Queen stood on thy right hand in golden raiment: compassed with variety. Hear daughter, and see, and incline thine ear: and forget thy people, and the house of thy father.\n"
	"And the King will covet thy beauty: because he is the Lord thy God, and they shall adore him.\n"
	"And the daughters of Tyre with gifts, all the rich of the people shall beseech thy countenance.\n"
	"All the glory of that daughter of the King is within, in borders of gold,\n"
	"clothed round about with varieties. Virgins shall be brought to the King after her: her neighbours shall be brought to thee.\n"
	"They shall be brought in joy and exultation: they shall be brought into the temple of the King.\n"
	"For thy fathers there are born sons to thee: thou shalt make them Princes over all the earth.\n"
	"They shall be mindful of thy name in all generation and generation. Therefore shall peoples confess to thee for ever: and for ever and ever.";