const char* chap562 = "Unto the end, to the sons of Core a Psalm.\n"
	"Hear these things all ye Gentiles: receive with your ears all ye that inhabit the earth.\n"
	"All ye earthly persons, and children of men: together in one^ the rich and the poor.\n"
	"My mouth shall speak wisdom, and the meditation of my heart prudence.\n"
	"I will incline mine ear unto a parable: I will open my proposition on a Psalter.\n"
	"Why shall I fear in the evil day? The iniquity of my heel shall compass me.\n"
	"They that trust in their strength: and glory in the multitude of their riches.\n"
	"A brother doth not redeem, man shall redeem: he shall not give unto God his reconciliation.\n"
	"And the price of the redemption of his own soul: and he shall labour for ever,\n"
	"and shall live yet unto the end.\n"
	"He shall not see death, when he shall see the wise dying, the unwise, and the fool shall perish together. And they shall leave their riches to strangers:\n"
	"and their sepulchres their houses for ever. Their Tabernacles in generation and generation: they have renowned their names in their lands.\n"
	"And man when he was in honour did not understand: he was compared to beasts without understanding, and became like to them.\n"
	"This their way is a scandal to them: and afterward in their mouth they shall take pleasure.\n"
	"As sheep they are put in hell: death shall feed upon them. And the just shall rule over them in the morning: and their aid shall wax old in hell from their glory.\n"
	"Nevertheless God will redeem my soul out of the hand of hell, when he shall take me,\n"
	"Fear not when a man shall be made rich: and when the glory of his house shall be multiplied.\n"
	"Because when he shall die, he shall not take all things: neither shall his glory go down with him.\n"
	"Because his soul in his life shall be blessed: he will confess to thee when thou shalt do him good.\n"
	"He shall enter in, even to the progenies of his fathers: and he shall not see light for ever.\n"
	"Man, when he was in honour, did not understand: he was compared to beasts without understanding, and became like to them.";