const char* chap568 = "Unto the end in songs, understanding to David.\n"
	"Hear my prayer, o God, despise not my petition.\n"
	"Attend to me and hear me.\n"
	"I am made sorrowful in my exercise: and am troubled at the voice of the enemy: and at the tribulation of the sinner. Because they have wrested iniquities upon me: & in anger they were troublesome to me.\n"
	"My heart is troubled in me: & the fear of death is fallen upon me.\n"
	"Fear and trembling are come upon me: and darkness hath covered me.\n"
	"And I said: Who will give me wings as of a dove, and I will fly: and rest?\n"
	"Lo I have gone far flying away: and I abode in the wilderness.\n"
	"I expected him, that saved me from pusillanimity of spirit, and tempest.\n"
	"Precipitate, o Lord, and divide their tongues: because I have seen iniquity, and contradiction in the city.\n"
	"Day and night shall iniquity compass it upon the walls thereof, and labour in the midst thereof, and injustice.\n"
	"And there hath not ceased out of the streets thereof usury and guile.\n"
	"For if mine enemy had spoken evil to me, I would verily have born it. And if he that hated me had spoken great things upon me: I would perhaps have hid myself from him.\n"
	"But thou a man of the same mind: my guide, and my familiar.\n"
	"Which didest take sweet meats together with me: in the house of God we walked with consent.\n"
	"Let death come upon them: and let them go down quick into hell. Because there is wickedness in their habitations, in the midst of them.\n"
	"But I have cried to God, and our Lord will save me.\n"
	"In the evening, and morning, & at midday, I will speak, and declare, and he will hear my voice.\n"
	"He will redeem my soul in peace from them, that approach to me: because among many they were with me.\n"
	"God will hear, and he which is before the worlds will humble them.\n"
	"For there is no change with them, & they feared not God: he hath stretched forth his hand in repaying.\n"
	"They have contaminated his testament, they are divided by the wrath of his countenance; and his heart hath approached. His words are made softer than oil: and the same are darts.\n"
	"Cast thy care upon our Lord: and he will nourish thee: he will not give fluctuation to the just for ever.\n"
	"But thou, o God, wilt bring them down into the pit of destruction. Bloody and deceitful men shall not live half their days, but I will hope in thee, o Lord.";