const char* chap570 = "Unto the end, destroy not, to David in the inscription of the title, when he fled from the face of Saul into the cave.\n"
	"Have mercy on me, o God, have mercy on me: because my soul hath trusted in thee. And I will hope in the shadow of thy wings, until iniquity pass.\n"
	"I will cry to God the highest: God that hath done me good.\n"
	"He sent from heaven, and delivered me: he hath given into reproach them that trod upon me. God hath sent his mercy and his truth,\n"
	"and hath delivered my soul out of the midst of lions' whelps: I slept troubled. The sons of men, their teeth are weapons and arrows: and their tongue a sharp sword.\n"
	"Be exalted above the heavens, o God: and thy glory upon all the earth.\n"
	"They prepared a snare for my feet: and bowed down my soul. They digged a pit before my face: and they are fallen into it.\n"
	"My heart is ready, o God, my heart is ready: I will sing, and say a Psalm.\n"
	"Arise my glory, arise psalter and harp: I will arise early.\n"
	"I will confess to thee among peoples, o Lord: and I will say a Psalm to thee among the Gentiles.\n"
	"Because thy mercy is magnified even to the heavens, and thy truth even to the clouds.\n"
	"Be exalted above the heavens o God: and thy glory upon all the earth.";