const char* chap572 = "Unto the end, destroy not, to David in the inscription of the title, when Saul sent, and watched his house to kill him.\n"
	"Deliver me from mine enemies, o my God: and from them that rise up against me defend me.\n"
	"Deliver me from them that work iniquity: and from bloody men save me.\n"
	"Because lo they have taken my soul: the strong have fallen violently upon me.\n"
	"Neither is it mine iniquity, nor my sin, o Lord: without iniquity have I run, and gone directly.\n"
	"Rise up to meet me, and see: and thou, o Lord, the God of powers, God of Israel, attend to visit all nations: have no mercy on all that work iniquity.\n"
	"They will return at evening: and they shall suffer famine as dogs, and shall compass the city.\n"
	"Behold they will speak in their mouth, and a sword in their lips: because who hath heard?\n"
	"And thou, o Lord wilt scorn them: thou wilt bring to nought all the nations.\n"
	"I will keep my strength to thee: because thou art my receiver:\n"
	"my God, thy mercy shall prevent me.\n"
	"God will shew unto me concerning mine enemies, kill them not lest sometime my peoples forget. Disperse them in thy strength: and depose them^ my protector, o Lord.\n"
	"The sin of their mouth, the word of their lips: and let them be taken in their pride. And for cursing and lying they shall be talked of\n"
	"in consummation: in wrath of consummation and they shall not be. And they shall know that God will rule over Jacob: and over the ends of the earth.\n"
	"They shall be turned at evening, and shall suffer famine as dogs: & shall compass the city.\n"
	"They shall be dispersed to eat: and if they be not filled, they will murmur also.\n"
	"But I will sing thy strength: and will exalt thy mercy in the morning. Because thou art become my receiver, and my refuge in the day of my tribulation.\n"
	"My helper, I will sing to thee, because thou art God my receiver: my God, my mercy.";