const char* chap582 = "Unto the end, for them that shall be changed, to David.\n"
	"Save me, o God: because waters are entered into my soul.\n"
	"I stick fast in the mire of the depth: and there is no sure standing. I am come into the depth of the sea: and a tempest hath overwhelmed me.\n"
	"I have laboured crying, my jaws are made hoarse: my eyes have failed, whilst I hope in my God.\n"
	"They are multiplied above the hairs of my head, that hate me without cause. Mine enemies are made strong, that have persecuted me unjustly: then did I pay the things that I took not.\n"
	"O God thou knowest my foolishness: and mine offences are not hid from thee.\n"
	"Let them not be ashamed upon me, which expected thee, o Lord, Lord of hosts. Let them not be confounded upon me that seek thee, o God of Israel.\n"
	"Because for thee have I sustained reproach, confusion hath covered my face.\n"
	"I am become a foreigner to my brethren, and a stranger to the sons of my mother.\n"
	"Because the zeal of thy house hath eaten me: and the reproaches of them that reproached thee, fell upon me.\n"
	"And I covered my soul in fasting: and it was made a reproach to me.\n"
	"And I put hair cloth my garment, & I became a parable to them.\n"
	"They spake against me that sat in the gate; and they sung against me that drank wine.\n"
	"But I, my prayer to thee, o Lord: a time of thy good pleasure, o God. In the multitude of thy mercy hear me, in the truth of thy salvation:\n"
	"Deliver me out of the mire, that I stick not fast: deliver me from them that hate me, and from the depths of waters.\n"
	"Let not the tempest of water drown me, nor the depth swallow me: neither let the pit shut his mouth upon me.\n"
	"Hear me, o Lord, because thy mercy is benign: according to the multitude of thy commiserations have respect to me.\n"
	"And turn not away thy face from thy servant: because I am in tribulation, hear me speedily.\n"
	"Attend to my soul, and deliver it: because of mine enemies deliver me.\n"
	"Thou knowest my reproach & my confusion, & my shame.\n"
	"In thy sight are all they that afflict me, my heart hath looked for reproach and misery. And I expected some body that would be sorry together with me, and there was none: and that would comfort me, and I found not.\n"
	"And they gave gall for my meat: & in my thirst they gave me vinegar to drink.\n"
	"Let their table be made a snare before them, & for retributions, and for a scandal.\n"
	"Let their eyes be darkened that they see not: and make their back crooked always.\n"
	"Pour out thy wrath upon them: and let the fury of thy wrath overtake them.\n"
	"Let their habitation be made desert: and in their tabernacles let there be none to dwell.\n"
	"Because whom thou hast strucken, they have persecuted: and upon the sorrow of my wounds they have added.\n"
	"Add thou iniquity upon their iniquity: and let them not enter into thy justice.\n"
	"Let them be put out of the book of the living: and with the just let them not be written.\n"
	"I am poor and sorrowful: thy salvation, o God, hath received me.\n"
	"I will praise the name of God with canticle: and will magnify him in praise.\n"
	"And it shall please God more than a young calf: that bringeth forth horns and hoofs.\n"
	"Let the poor see and rejoice: seek ye God, and your soul shall live.\n"
	"Because our Lord hath heard the poor: and he hath not despised his prisoners.\n"
	"Let the heavens and earth praise him, the sea, and all the creeping beasts in them.\n"
	"Because God will save Sion: and the cities of Juda shall be built up. And they shall inhabit there, & by inheritance, they shall get it.\n"
	"And the seed of his servants shall possess it, and they that love his name shall dwell in it.";