const char* chap584 = "A Psalm for David, of the sons of Jonadab, and the former captives. In thee o Lord I have hoped, let me not be confounded for ever:\n"
	"in thy justice deliver me, and receive me. Incline thine ear to me and save me.\n"
	"Be unto me for a God protector, and for a fenced place: that thou mayst save me: Because thou art my firmament, and my refuge.\n"
	"My God deliver me out of the hand of the sinner, and out of the hand of him that doth against the law, and of the unjust.\n"
	"Because thou art my patience, o Lord; o Lord my hope from my youth.\n"
	"Upon thee have I been confirmed from the womb: from my mother's belly thou art my protector. In thee is my singing always:\n"
	"I was made to many as a wonder: & thou art a strong helper.\n"
	"Let my mouth be filled with praise, that I may sing thy glory: all the day thy greatness.\n"
	"Reject me not in the time of old age: when my strength shall fail, forsake me not.\n"
	"Because mine enemies have said to me: and they that watched my soul consulted together.\n"
	"saying: God hath forsaken him, pursue, and take him: because there is none to deliver.\n"
	"O God be not far from me: my God have respect to mine aid.\n"
	"Let them be confounded & fail that detract from my soul: let them be covered with confusion and shame, that seek evils to me.\n"
	"But I will always hope: and will add upon all thy praise.\n"
	"My mouth shall shew forth thy justice: all the day thy salvation. Because I have not known learning, I will enter into the powers of our Lord:\n"
	"Lord I will be mindful of thy justice only.\n"
	"O God thou hast taught me from my youth: and until now I will pronounce thy marvelous works.\n"
	"And unto ancient age, and old age: o God, forsake me not? Until I shew forth thy arm to all the generation, that is to come. Thy might,\n"
	"and thy justice, o God, even to the highest, great marvels, which thou hast done: O God who may be like to thee?\n"
	"How great tribulations hast thou shewed me, many and evil: and turning thou hast quickened me: and from the depths of the earth thou hast brought me back again.\n"
	"Thou hast multiplied thy magnificence: and being turned thou hast comforted me.\n"
	"For I also will confess to thee in the instruments of Psalm thy truth: O God, I will sing to thee on the harp, holy one of Israel.\n"
	"My lips shall rejoice when I shall sing to thee; and my soul which thou hast redeemed.\n"
	"Yea and my tongue all the day shall meditate thy justice: when they shall be confounded and ashamed that seek evils to me.";