const char* chap587 = "Understanding to Asaph. Why hast thou, o God, repelled for ever: is thy fury wrath upon the sheep of thy pasture?\n"
	"Be mindful of thy congregation, which thou hast possessed from the beginning. Thou hast redeemed the rod of thine inheritance: mount Sion, in which thou hast dwelt.\n"
	"Lift up thy hands upon their prides for ever: how great things hath the enemy done malignantly in the holy place?\n"
	"And they that hate thee have gloried: in the midst of thy solemnity. They have set their signs, for signs:\n"
	"and have not known, as in the issue on high. As in a wood of trees they have with axes\n"
	"cut out the gates thereof together: in hatchet and chip-axe they have cast it down.\n"
	"They have burnt thy sanctuary with fire: they have polluted the tabernacle of thy name in the earth.\n"
	"Their kindred together have said in their heart: Let us make all the festival days of God to cease from the earth.\n"
	"Our signs we have not seen, there is now no Prophet: and he will know us no more.\n"
	"How long, o God, shall the enemy upbraid: the adversary provoke thy name for ever?\n"
	"Why doest thou turn away thy hand, and thy right hand, out of the midst of thy bosom for ever?\n"
	"But God our King before the worlds: he hath wrought salvation in the midst of the earth.\n"
	"Thou in thy strength hast confirmed the sea: thou hast crushed the head of Dragons in the waters.\n"
	"Thou hast broken the heads of the dragon: thou hast given him for meat to the peoples of the Aethiopians.\n"
	"Thou hast broken up fountains, and torrents, thou hast dried the rivers of Ethan.\n"
	"The day is thine, and the night is thine: thou hast made the morning and the sun.\n"
	"Thou hast made all the coasts of the earth: the summer and the spring thou hast formed them.\n"
	"Be mindful of this, the enemy hath upbraided our Lord: and a foolish people hath provoked thy name.\n"
	"Deliver not to beasts the souls that confess to thee: and the souls of the poor forget not for ever.\n"
	"Have respect unto thy testament: because they that are obscure of the earth, are filled with houses of iniquities.\n"
	"Let not the humble be turned away being confounded: the poor and needy shall praise thy name.\n"
	"Arise God, judge thy cause: be mindful of those thy reproaches, that are from the foolish man all the day.\n"
	"Forget not the voices of thine enemies: the pride of them that hate thee, hath ascended always.";