const char* chap59 = "And our Lord said to Moyses: Go into Pharao, and speak to him: This saith our Lord, the God of the Hebrews: dismiss my people to sacrifice unto me.\n"
	"And if thou refuse, and holdest them,\n"
	"behold my hand shall be upon thy fields: and upon thy horses, and asses, and camels, and oxen, and sheep, a very sore pestilence.\n"
	"And our Lord will make a marvel between the possessions of Israel and the possessions of the Aegyptians, that nothing at all perish of those things that pertain to the children of Israel.\n"
	"And our Lord hath appointed a time, saying: Tomorrow will our Lord do this thing in the land.\n"
	"Our Lord therefore did this thing the next day: and all the beasts of the Aegyptians died, but of the beasts of the children of Israel nothing at all perished.\n"
	"And Pharao sent to see: neither was there any thing dead of that which Israel possessed. And Pharao's heart was hardened, & he did not dismiss the people.\n"
	"And our Lord said to Moyses and Aaron: Take your hands full of ashes out of the chimney, & let Moyses sprinkle it into the air before Pharao.\n"
	"And be there dust upon all the Land of Aegypt: for there shall be in men, and beasts boyles, and swelling bladders in the whole land of Aegypt.\n"
	"And they took ashes out of the chimney, and stood before Pharao, and Moyses sprinkled it into the air: and there were made boyles of swelling bladders in men and beasts.\n"
	"Neither could the enchanters stand before Moyses for boyles that were upon them, and in all the Land of Aegypt.\n"
	"And our Lord did indurate Pharao's heart, and he heard them not, as our Lord spake to Moyses.\n"
	"And our Lord said to Moyses: In the morning arise, and stand before Pharao, and thou shalt say to him: This saith the Lord, the God of the Hebrews: Dismiss my people to sacrifice unto me.\n"
	"Because this time I will send all my plagues upon thy heart, and upon thy servants, and upon thy people: that thou mayest know there is not the like to me in all the earth.\n"
	"For now stretching forth my hand I will strike thee, and thy people with pestilence, and thou shalt perish from the earth.\n"
	"And therefore have I set thee, that in thee I may shew my might, & my name may be told in all the earth.\n"
	"Dost thou yet hold back my people, and wilt thou not dismiss them?\n"
	"Behold I will rain tomorrow this very hour hail exceeding much: such as was not in Aegypt from the day that it was founded, until this present time.\n"
	"Send therefore now presently, and gather together thy cattle, and all things that thou hast in the field: for men and beasts, and all things that shall be found abroad, and not gathered together out of the fields, and the hail fall upon them, shall die.\n"
	"He that feared the word of our Lord of Pharao's servants, made his servants to fly, and his beasts into houses:\n"
	"But he that neglected the word of our Lord, let alone his servants, and his beasts in the fields.\n"
	"And our Lord said to Moyses: Stretch forth thy hand towards heaven, that there may be hail in the whole Land of Aegypt upon men, and upon beasts, and upon every herb of the field in the Land of Aegypt.\n"
	"And Moyses stretched forth his rod toward heaven, and our Lord gave thunders, and hail, and running lightnings on the land: and our Lord rained hail upon the Land of Aegypt.\n"
	"And the hail and fire mixed together did drive: and it was of so great bigness as never before appeared in the whole Land of Aegypt since that nation was made.\n"
	"And the hail smote in all the Land of Aegypt all things that were in the fields, from man even unto beast: and every herb of the field did the hail strike, and every tree of the country it did break.\n"
	"Only in the Land of Gessen, where the children of Israel were, the hail fell not.\n"
	"And Pharao sent, and called Moyses and Aaron, saying to them: I have sinned now also, the Lord is just: I and my people, impious.\n"
	"Pray ye the Lord that the thunders may cease, and the hail: that I may dismiss you, and ye tarry not here any longer.\n"
	"Moyses said: When I shall be gone forth out of the city, I will stretch forth my hands to our Lord, and the thunders shall cease, and the hail shall not be: that thou mayest know that the earth is our Lord's:\n"
	"but I know that neither thou, nor thy servants do yet fear the Lord God.\n"
	"The flax therefore, and the barley were hurt, because the barley came up green, & the flax now was bolled:\n"
	"but the wheat, and other winter corn were not hurt, because they were lateward.\n"
	"And Moyses going forth from Pharao out of the city, stretched forth his hands to our Lord: and the thunders and hail ceased, neither did there drop rain any more upon the earth.\n"
	"And Pharao seeing that the rain and the hail and thunders were ceased, he increased his sin:\n"
	"and his heart was aggravated, and the heart of his servants, & indurate exceedingly: neither did he dismiss the children of Israel, as our Lord had commanded by the hand of Moyses.";