const char* chap590 = "Unto the end, for Idithun, a psalm to Asaph.\n"
	"With my voice I have cried to our Lord: with my voice to God and he attended to me.\n"
	"In the day of my tribulation I sought God, with my hands in the night before him: and I was not deceived. My soul refused to be comforted,\n"
	"I was mindful of God and was delighted, and was exercised: and my spirit fainted.\n"
	"Mine eyes prevented the watches: I was troubled & spake not.\n"
	"I thought upon old days: and the eternal years I had in mind.\n"
	"And I meditated in the night with my heart, and I was exercised, and I swept my spirit.\n"
	"Why, will God reject for ever: or will he not add to be better pleased as yet?\n"
	"Or will he cut off his mercy for ever, from generation unto generation?\n"
	"Or will God forget to have mercy? Or will he in his wrath keep in his mercies?\n"
	"And I said: Now have I begun; this is the change of the right hand of the Highest.\n"
	"I have been mindful of the works of our Lord: because I will be mindful from the beginning of thy marvelous works.\n"
	"And I will meditate in all thy works: and in thy inventions I will be exercised.\n"
	"O God in the holy is thy way: what god is great as our God?\n"
	"thou art the God that doest marvelous things. Thou hast made thy power known among peoples:\n"
	"thou hast with thine arm redeemed thy people, the children of Jacob, and Joseph.\n"
	"The waters saw thee, o God, the waters saw thee: and they were afraid, and the depths were troubled.\n"
	"A multitude of the sounding of waters: the clouds gave a voice. For indeed arrows do pass:\n"
	"the voice of thy thunder in a wheel. Thy lightnings shined to the round world: the earth was moved and troubled.\n"
	"Thy way in the sea, and thy paths in many waters: and thy steps shall not be known.\n"
	"Thou hast conducted thy people as sheep: in the hand of Moyses and Aaron.";