const char* chap591 = "Understanding to Asaph. My people attend ye to my law: incline your ear unto the words of my mouth.\n"
	"I will open my mouth in parables: I will speak propositions from the beginning.\n"
	"How great things have we heard and have known them, and our fathers have told us.\n"
	"They were not hid from their children, in another generation. Telling the praises of our Lord, and his powers, and his marvelous works which he hath done.\n"
	"And he raised up a testimony in Jacob: and made a law in Israel. How great things he commanded our fathers, to make the same known to their children:\n"
	"that another generation may know. The children that shall be born, and shall rise up, and shall tell their children.\n"
	"That they may put their hope in God, and may not forget the works of God: and may seek after his commandments.\n"
	"That they become not as their fathers: a perverse generation and exasperating. A generation, that hath not directed their heart, their spirit hath not been faithful toward God.\n"
	"The children of Ephrem bending, and shooting with bow: were turned in the day of battle.\n"
	"They kept not the testament of God: and in his law they would not walk.\n"
	"And they forgat his benefits, and his marvelous works, which he shewed them.\n"
	"Before their fathers he did marvelous things in the land of Aegypt, in the field of Tanis.\n"
	"He divided the sea & brought them through: and he made the waters to stand as in a bottle.\n"
	"And he conducted them in a cloud by day: and all the night by light of fire.\n"
	"He struck the rock in the desert: and gave them water to drink as in a great depth.\n"
	"And he brought forth water out of the rock: and made waters run down as rivers.\n"
	"And they added as yet to sin unto him: they provoked the Highest to wrath in the place without water.\n"
	"And they tempted God in their hearts: so that they asked meats for their lives.\n"
	"And they spake evil of God, they said: Can God prepare a table in the desert?\n"
	"Because he struck the rock and waters ran, & torrents flowed: Can he also give bread, or prepare a table for his people?\n"
	"Therefore our Lord heard, and made delay: and fire was kindled in Jacob, and wrath ascended upon Israel.\n"
	"Because they believed not in God, nor hoped in his salvation.\n"
	"And he commanded the clouds from above, and opened the gates of heaven.\n"
	"And he rained them Manna to eat, and bread of heaven he gave to them.\n"
	"Bread of Angels did man eat: he sent them victuals in aboundance.\n"
	"He transported the South-wind from heaven: and in his power he brought in the South-west-wind.\n"
	"And he rained upon them flesh as dust: and as the sand of the sea feathered fowls.\n"
	"And they fell in the midst of their camp: about their tabernacles.\n"
	"And they did eat and were filled exceedingly, and their desire he brought to them:\n"
	"They were not defrauded of their desire. As yet their meats were in their mouth:\n"
	"And the wrath of God ascended upon them. And he killed their fat ones, and the chosen of Israel he hindered.\n"
	"In all these things they sinned as yet: and they believed not in his marvelous works.\n"
	"And their days failed in vanity: and their years in haste.\n"
	"When he slew them, they sought him: and they returned, and early they came to him.\n"
	"And they remembered that God is their helper: and the high God is their redeemer.\n"
	"And they loved him with their mouth, and with their tongue they did lie to him.\n"
	"But their heart was not right with him: neither were they counted faithful in his testament.\n"
	"But he is merciful, and will be propitious to their sins: and he will not destroy them. And he abounded to turn away his wrath: and he kindled not all his wrath.\n"
	"And he remembered that they are flesh: spirit going, and not returning.\n"
	"How often have they exasperated him in the desert: provoked him to wrath in the place without water.\n"
	"And they returned, and tempted God: and the holy one of Israel they exasperated.\n"
	"They did not remember his hand: in the day that he redeemed them from the hand of the afflicter.\n"
	"As he put his signs in Aegypt, and his wonders in the field of Tanis.\n"
	"And he turned their rivers into blood, & their showers that they might not drink.\n"
	"He sent upon them a swarm of flies, and it eat them: and the frog, and it destroyed them.\n"
	"And he gave their fruits to the blast, and their labours to the locust.\n"
	"And he killed their vineyards with hail: and their mulberry trees with hoar-frost.\n"
	"And he delivered their beast to hail: and their possession to fire.\n"
	"He sent upon them the wrath of his indignation: indignation, & wrath, and tribulation: immissions by evil angels.\n"
	"He made a way to the path of his wrath, he spared not their lives from death: and their cattle he shut up in death.\n"
	"And he struck all the first-born in the land of Aegypt: the first fruits of all their labours in the tabernacles of Cham.\n"
	"And he took away his people as sheep: and led them as a flock in the desert.\n"
	"And he brought them forth in hope, and they feared not: and the sea covered their enemies.\n"
	"And he brought them into the mount of his sanctification, the mount, which his right hand purchased. And he cast out the gentiles from their face: and by lot he divided the land of them in a cord of distribution:\n"
	"And he made the tribes of Israel to dwell in their tabernacles.\n"
	"And they tempted, and exasperated God the highest, and they kept not his testimonies.\n"
	"And they turned away themselves, & kept not the covenant: even as their fathers, they were turned as a crooked bow.\n"
	"They incensed him to wrath in their hills: and in their gravens they provoked him to emulation.\n"
	"God heard, and contemned: and he brought Israel to nothing exceedingly\n"
	"And he rejected the tabernacle of Silo, his tabernacle, where he dwelt among men.\n"
	"And he delivered their force into captivity: and their beauty into the hands of the enemy.\n"
	"And he shut up his people in the sword: and he despised his inheritance.\n"
	"Fire devoured their young men: and their virgins were not lamented.\n"
	"Their Priests fell by the sword: and their widows were not wept for.\n"
	"And our Lord was raised up as one that sleepeth: as a mighty man having surfeited of wine.\n"
	"And he struck his enemies on the hinder parts: an everlasting reproach he gave to them.\n"
	"And he rejected the tabernacle of Joseph: and the tribe of Ephraim he chose not.\n"
	"But he chose the tribe of Juda, mount Sion which he loved.\n"
	"And he built his sanctuary as of unicorns in the land, which he hath founded for ever.\n"
	"And he chose David his servant, and took him from the flocks of sheep: from after the ewes with young he took him.\n"
	"To feed Jacob his servant, and Israel his inheritance.\n"
	"And he fed them in the innocency of his heart: and in the understandings of his hands he conducted them.";