const char* chap594 = "Unto the end, for wine presses, a Psalm to Asaph himself.\n"
	"Rejoice to God, our helper: make Jubilation to the God of Jacob.\n"
	"Take ye Psalm, and give timbrel: pleasant Psalter with the harp.\n"
	"Sound ye with trumpet in the new moon, in the notable day of your solemnity.\n"
	"Because it is a precept in Israel, and judgment to the God of Jacob.\n"
	"He put it for a testimony in Joseph, when he came out of the Land of Aegypt: he heard a tongue which he knew not.\n"
	"He turned away his back from burdens: his hands served in baskets.\n"
	"In tribulation thou didst invocate me, and I heard thee: I heard thee in the secret of the tempest: I proved thee at the water of contradiction.\n"
	"Hear, o my people, and I will contest thee: Israel if thou wilt hear me.\n"
	"There shall be no new god in thee, neither shalt thou adore a strange god.\n"
	"For I am the Lord thy God, which brought thee out of the land of Aegypt: dilate thy mouth and I will fill it.\n"
	"And my People heard not my voice: and Israel attended not to me.\n"
	"And I let them alone, according to the desires of their heart, they shall go in their own inventions.\n"
	"If my people had heard me, if Israel had walked in my ways:\n"
	"I had for nothing perhaps humbled their enemies: and had laid my hand upon those that afflict them.\n"
	"The enemies of our Lord have lied to him: and their time shall be for ever.\n"
	"And he fed them of the fat of corn: and out of the rock with honey he filled them.";