const char* chap599 = "A prayer to David himself. Incline thine ear, o Lord, & hear me: because I am needy and poor.\n"
	"Keep my soul, because I am holy: save thy servant my God, that hopeth in thee.\n"
	"Have mercy on me, o Lord, because I have cried to thee all the day:\n"
	"make joyful the soul of thy servant, because to thee, o Lord, have I lifted up my soul.\n"
	"Because thou, o Lord, art sweet, and mild: and of much mercy to all that invocate thee.\n"
	"Receive, o Lord, my prayer with thine ears: and attend to the voice of my petition.\n"
	"In the day of my tribulation I have called to thee: because thou hast heard me.\n"
	"There is not the like to thee amongst gods, o Lord: and there is not according to thy works.\n"
	"All nations whatsoever thou hast made, shall come, and shall adore before thee, o Lord: and they shall glorify thy name.\n"
	"Because thou art great and doing marvelous things: thou only art God.\n"
	"Conduct me, o Lord, in thy way, and I will walk in thy truth: let my heart rejoice that it may fear thy name.\n"
	"I will confess to thee, o Lord my God, with all my heart, and will glorify thy name for ever.\n"
	"Because thy mercy is great upon me: & thou hast delivered my soul out of the lower hell.\n"
	"O God the wicked are risen up upon me, and the synagogue of the mighty have sought my soul: and they have not set thee in their sight.\n"
	"And thou, o Lord, the God of compassion and merciful, patient, and of much mercy, and true.\n"
	"Have respect to me and have mercy on me, give thine empire to thy servant: and save the son of thy handmaid.\n"
	"Make with me a sign unto God, that they may see which hate me, and may be confounded: because thou o Lord hast holpen me.";