const char* chap60 = "And our Lord said to Moyses: Go in to Pharao: for I have indurate his heart, and the heart of his servants: that I may work these my signs in him,\n"
	"and thou mayst tell in the ears of thy son, and of thy nephews, how often I have broken the Aegyptians, & wrought my signs in them: and you may know that I am the Lord.\n"
	"Moyses therefore and Aaron went in to Pharao, and said to him: Thus saith the Lord the God of the Hebrews: Till when wilt thou not be subject to me? Dismiss my people, to sacrifice unto me.\n"
	"But if thou resist, and wilt not dismiss them: behold I will bring in tomorrow the locust into thy coasts:\n"
	"which may cover the face of the earth, that nothing thereof appear, but that which the hail hath left may be eaten: for it shall gnaw all trees that spring in the fields.\n"
	"And they shall fill thy houses, and the houses of thy servants, and of all the Aegyptians': such a number as thy fathers have not seen, nor grand-fathers, since they arose upon the earth, until this present day. And he turned himself away, and went forth from Pharao.\n"
	"And Pharao's servants said to him: How long shall we endure this scandal? Dismiss the men to sacrifice to the Lord their God. Dost thou not see that Aegypt is undone?\n"
	"And they called back Moyses & Aaron unto Pharao: who said to them: Go, sacrifice to the Lord your God: who are they that shall go?\n"
	"Moyses said: With our young and old we will go, with our sons and daughters, with our sheep and herds: for it is the solemnity of the Lord our God.\n"
	"And Pharao answered: So be the Lord with you, as I shall dismiss you, and your little ones: who doubteth but that you intend very wickedly?\n"
	"It shall not so be: but go ye men only, and sacrifice to the Lord: for this yourselves also desired. And immediately they were cast out from Pharao's sight.\n"
	"And our Lord said to Moyses: Stretch forth thy hand upon the Land of Aegypt unto the locust, that it come upon it, and devour every herb that remained after the hail.\n"
	"And Moyses stretched forth his rod upon the Land of Aegypt: and our Lord brought in a burning wind all that day & night: and when it was morning, the burning wind raised the locusts:\n"
	"which came up over the whole Land of Aegypt: and sat in all the coasts of the Aegyptians innumerable, the like as had not been before that time, nor shall be afterward.\n"
	"And they covered the whole face of the earth, wasting all things. Therefore the grass of the earth was devoured, and what fruits soever on the trees, which the hail had left: there was also nothing at all left that was green in the trees, and in the herbs of the earth, in all Aegypt.\n"
	"For the which cause Pharao in haste called Moyses and Aaron, and said to them: I have sinned against the Lord your God, and against you.\n"
	"But now forgive me my sin this time also, and pray to the Lord your God, that he take away from me this death.\n"
	"And Moyses going forth from Pharao's sight, prayed to our Lord:\n"
	"who made a very vehement wind to blow from the west, and taking the locusts it threw them into the Red sea: there remained not so much as one in all the coasts of Aegypt.\n"
	"And our Lord did indurate Pharao's heart, neither did he dismiss the children of Israel.\n"
	"And our Lord said to Moyses: Stretch forth thy hand toward heaven: and be there darkness upon the Land of Aegypt so thick, that it be palpable.\n"
	"And Moyses stretched forth his hand toward heaven: and there was made horrible darkness in the whole Land of Aegypt three days.\n"
	"No man saw his brother, nor moved himself out of the place where he was: but wheresoever the children of Israel dwelt, there was light.\n"
	"And Pharao called Moyses and Aaron, and said to them: Go sacrifice to the Lord: let your sheep only and herds remain, let your little ones go with you.\n"
	"Moyses said: Hosts also & holocausts thou shalt give to us, which we may offer to the Lord our God.\n"
	"All the flocks shall go with us: there shall not a hoof remain of them; the which are necessary unto the service of the Lord our God: especially whereas we know not what must be offered till we come to the very place.\n"
	"And our Lord did indurate Pharao's heart, and he would not dismiss them.\n"
	"And Pharao said to Moyses: Get thee from me, and beware thou see not my face any more: in what day soever thou shalt come in my sight, thou shalt die.\n"
	"Moyses answered: So shall it be as thou hast spoken, I will not see thy face any more.";