const char* chap615 = "The prayer of the poor, when he shall be anxious, and shall make his petition before our Lord.\n"
	"Lord hear my prayer: and let my cry come to thee.\n"
	"Turn not away thy face from me: in what day soever I am in tribulation, incline thine ear to me. In what day soever I shall invocate thee, hear me speedily.\n"
	"Because my days have vanished as smoke: and my bones are withered as a dry burnt firebrand.\n"
	"I am strucken as grass, and my heart is withered: because I have forgotten to eat my bread.\n"
	"For the voice of my groaning, my bone hath cleaved to my flesh.\n"
	"I am become like a pelican of the wilderness: I am become as a night crow in the house.\n"
	"I have watched, and am become as a sparrow solitary in the house-top.\n"
	"All the day did mine enemies upbraid me: and they that praised me sware against me.\n"
	"Because I did eat ashes as bread, & mingled my drink with weeping.\n"
	"At the face of thy wrath and indignation: because lifting me up thou hast thrown me down.\n"
	"My days have declined as a shadow: and I am withered as grass.\n"
	"But thou o Lord endurest for ever: and thy memorial in generation and generation.\n"
	"Thou rising up shalt have mercy on Sion: because it is time to have mercy on it, because the time cometh.\n"
	"Because the stones thereof have pleased thy servants: and they shall have pity on the earth thereof.\n"
	"And the Gentiles shall fear thy name o Lord, and all the kings of the earth thy glory.\n"
	"Because our Lord hath built Sion: and he shall be seen in his glory.\n"
	"He hath had respect to the prayer of the humble: and he hath not despised their petition.\n"
	"Let these things be written unto another generation: and the people that shall be created shall praise our Lord.\n"
	"Because he hath looked forth from his high holy place: our Lord from heaven hath looked upon the earth.\n"
	"That he might hear the groanings of the fettered: that he might loose the children of them that are slain:\n"
	"That they may shew forth the name of our Lord in Sion: and his praise Jerusalem.\n"
	"In the assembling of the people together in one, and kings to serve our Lord.\n"
	"He answered him in the way of his strength: Shew me the fewness of my days.\n"
	"Call me not back in the half of my days: thy years are unto generation and generation.\n"
	"In the beginning, o Lord, thou didst found the earth: and the heavens are the works of thy hands.\n"
	"They shall perish, but thou art permanent: and they shall all wax old as a garment. And as a vesture thou shalt change them, and they shall be changed:\n"
	"but thou art the self-same, and thy years shall not fail.\n"
	"The children of thy servants shall inhabit: and their seed shall be directed for ever.";