const char* chap619 = "Alleluia. Confess ye to our Lord because he is good: because his mercy is for ever.\n"
	"Who shalt speak the powers of our Lord, shall make all his praises to be heard?\n"
	"Blessed are they, that keep judgment, & do justice at all time.\n"
	"Remember us, o Lord in the good pleasure of thy people: visit us in thy salvation:\n"
	"To see in the goodness of thine elect, to rejoice in the joy of thy nation: that thou mayst be praised with thine inheritance.\n"
	"We have sinned with our fathers: we have dealt unjustly, we have done iniquity.\n"
	"Our fathers in Aegypt did not understand thy marvelous works: they were not mindful of the multitude of thy mercy. And they provoked thee to wrath going up unto the sea, the Red sea.\n"
	"And he saved them for his name sake; that he might make his power known.\n"
	"And he rebuked the Red sea, and it was made dry: and he led them in the depths as in a desert.\n"
	"And he saved them from the hand of them that hated them: and he redeemed them out of the hand of the enemy.\n"
	"And water overwhelmed those that afflicted them: there did not one of them remain.\n"
	"And they believed his words: and they sang his praises.\n"
	"They had quickly done, they forgot his works: and they expected not his counsel.\n"
	"And they coveted concupiscence in the desert: and tempted God in the place without water.\n"
	"He gave them their petition: and sent saturity into their souls.\n"
	"And they provoked Moyses in the camp: Aaron the holy of our Lord.\n"
	"The earth was opened, and swallowed Dathan, and overwhelmed the congregation of Abiron.\n"
	"And a fire flamed up in their synagogue: the flame burnt the sinners.\n"
	"And they made a calf in Horeb: and they adored the sculptile.\n"
	"And they changed their glory into the similitude of a calf that eateth grass.\n"
	"They forgat God, which saved them, which did great things in Aegypt,\n"
	"marvelous things in the land of Cham, terrible things in the Red sea.\n"
	"And he said to destroy them: if Moyses his elect had not stood in the way before him. To turn away his wrath that he should not destroy them:\n"
	"and they esteemed for naught the land that was to be desired. They did not believe his word.\n"
	"and they murmured in their tabernacles: they heard not the voice of our Lord.\n"
	"And he lifted up his hand over them: to overthrow them in the desert:\n"
	"And to cast down their seed among the Nations: & to disperse them in the countries.\n"
	"And they were professed to Beelphegor: and they did eat the sacrifices of the dead.\n"
	"And they provoked him in their inventions: & ruin was multiplied on them.\n"
	"And Phinees stood, and pacified: and the slaughter ceased.\n"
	"And it was reputed to him unto justice, in generation and generation even for ever.\n"
	"And they provoked him at the waters of contradiction: and Moyses was vexed for them:\n"
	"because they exasperated his spirit. And he plainly affirmed in his lips:\n"
	"they destroyed not the nations, of which our Lord spake to them.\n"
	"And they were mingled among the nations, and learned their works:\n"
	"and they served their sculptiles: and it became a scandal to them.\n"
	"And they immolated their sons, and their daughters to devils.\n"
	"And they shed innocent blood: the blood of their sons and of their daughters, which they sacrificed to the sculptiles of Chanaan. And the land was infected with blood,\n"
	"& was contaminated in their works: and they did fornicate in their inventions.\n"
	"And our Lord was wrath with fury upon his people: and he abhorred his inheritance.\n"
	"And he delivered them into the hands of the nations: and they that hated them had the dominion of them.\n"
	"And their enemies afflicted them, and they were humbled under their hands:\n"
	"he did often deliver them. But they exasperated him in their counsel: and they were humbled in their iniquities.\n"
	"And he saw when they were afflicted: and he heard their prayer.\n"
	"And he was mindful of his testament: and it repented him according to the multitude of his mercy.\n"
	"And he gave them into mercies in the sight of all, that had taken them.\n"
	"Save us, o Lord our God: and gather us out of the Nations. That we may confess to thy holy name: & may glory in thy praise.\n"
	"Blessed be our Lord the God of Israel from everlasting unto everlasting: and all the people shall say: Be it, be it.";