const char* chap621 = "A canticle of Psalm, to David himself.\n"
	"My heart is ready, o God, my heart is ready: I will chant and will sing in my glory.\n"
	"Arise my glory, arise psalter and harp: I will arise early.\n"
	"I will confess to thee in peoples, o Lord: and I will sing to thee in the Nations.\n"
	"Because thy mercy is great above the heavens: & thy truth even to the clouds.\n"
	"Be exalted above the heavens o God, and thy glory over all the earth:\n"
	"that thy beloved may be delivered. Save with thy right hand, and hear me:\n"
	"God spake in his holy: I will rejoice, and will divide Sichem, and I will measure the vale of tabernacles.\n"
	"Galaad is mine, and Manasses is mine: and Ephraim the protection of my head. Juda is my king:\n"
	"Moab the pot of my hope. Upon Idumea I will extend my shoe: the strangers are made my friends.\n"
	"Who will conduct me into a fenced city? Who will conduct me into Idumea?\n"
	"Wilt not thou, o God, which hast repelled us, and wilt not thou go forth, o God, in our hosts?\n"
	"Give us help out of tribulation: because man's salvation is vain.\n"
	"In God we shall do strength: and he will bring our enemies to nothing.";