const char* chap622 = "Unto the end, a Psalm of David.\n"
	"O God conceal not my praise: because the mouth of the sinner, and the mouth of the deceitful man is open upon me.\n"
	"They have spoken against me with deceitful tongue, and with words of hatred they have compassed me: and they have impugned me without cause.\n"
	"For that they should love me, they backbited me: but I prayed.\n"
	"And they set against me evil things for good: and hatred for my love.\n"
	"Appoint a sinner over him: and let the devil stand on his right hand.\n"
	"When he is judged, let him come forth condemned: and let his prayer be turned into sin.\n"
	"Let his days be made few: and let another take his bishoprick.\n"
	"Let his children be made orphans: and his wife a widow.\n"
	"Let his children be transported wandering, and let them beg: and let them be cast out of their habitations.\n"
	"Let the usurer search all his substance: and let strangers spoil his labours.\n"
	"Let there be none to help him: neither let there be any to have pity on his pupils.\n"
	"Let his children come to destruction: in one generation let his name be clean put out.\n"
	"Let the iniquity of his fathers return to memory in the sight of our Lord: and let not the sin of his mother be blotted out.\n"
	"Let them be before our Lord always, and let the memory of them perish out of the earth:\n"
	"For that he remembered not to do mercy.\n"
	"And he persecuted the poor, and needy man, and the compunct in heart to kill him.\n"
	"And he loved cursing, and it shall come to him: and he would not blessing, and it shall be far from him. And he put on cursing as a garment, and it entered as water into his inner parts, and as oil in his bones.\n"
	"Be it to him as a garment, wherewith he is covered: and as a girdle, wherewith he is always girded.\n"
	"This is the work of them that detract from me before our Lord: and that speak evils against my soul.\n"
	"And thou Lord, Lord, do with me for thy name's sake: because thy mercy is sweet. Deliver me\n"
	"because I am needy and poor: and my heart is troubled within me.\n"
	"As a shadow when it declineth, am I taken away: and I am shaken as locusts.\n"
	"My knees are weakened with fasting: and my flesh is changed by reason of oil.\n"
	"And I am made a reproach to them: they saw me, and wagged their heads.\n"
	"Help me, o Lord my God: save me according to thy mercy.\n"
	"And let them know that this is thy hand: & thou, o Lord, hast done it.\n"
	"They will curse, and thou shalt bless: let them that rise up against me be confounded: but thy servant shall rejoice.\n"
	"Let them that detract from me, be clothed with shame: and let them be covered with their confusion, as with a double patched cloak.\n"
	"I will confess to our Lord exceedingly with my mouth: and in the midst of many I will praise him.\n"
	"Because he hath stood on the right hand of the poor, that he might save my soul from the persecutors.";