const char* chap63 = "And our Lord spake to Moyses, saying:\n"
	"Sanctify unto me every first-born that openeth the matrice in the children of Israel, as well of men as of beasts; for they are all mine.\n"
	"And Moyses said to the people: Remember this day in the which you went forth out of Aegypt, & out of the house of servitude, because with a strong hand hath our Lord brought you forth out of this place; that you eat not leavened bread.\n"
	"This day you go forth in the month of new corn.\n"
	"And when our Lord shall have brought thee into the Land of Chananeite and Hetheite & Amorrheite & Heveite & Jebuseite, which he sware to thy fathers that he would give thee, a land that floweth with milk and honey, thou shalt celebrate this manner of sacred rites in this month.\n"
	"Seven days shalt thou eat azymes: and in the seventh day shall be the solemnity of our Lord.\n"
	"Azymes shall you eat seven days: there shall not be seen any leavened thing with thee, nor in all thy coasts.\n"
	"And thou shalt tell thy son in that day, saying: This is that which our Lord did to me when I came forth out of Aegypt.\n"
	"And it shall be as a sign in thy hand, and as a monument before thine eyes: and that the law of our Lord be always in the mouth, for in a strong hand our Lord hath brought thee out of Aegypt.\n"
	"Thou shalt keep this observation at the set time from days to days.\n"
	"And when our Lord shall have brought thee into the Land of the Chananeite, as he sware to thee and thy fathers, and shall give it thee,\n"
	"thou shalt separate all that openeth the matrice unto our Lord, and all that is brought forth in thy cattle: whatsoever thou shalt have of male sex thou shalt consecrate to our Lord.\n"
	"The first-born of an ass thou shall change for a sheep: and if thou do not redeem it, thou shalt kill it. And every first-born of men among thy children, thou shalt redeem with a price.\n"
	"And when thy son shall ask thee tomorrow saying: What is this? Thou shalt answer him: With a strong hand did our Lord bring us forth out of the land of Aegypt, out of the house of servitude.\n"
	"For when Pharao's heart was indurate, and would not dismiss us, our Lord slew every first-born in the Land of Aegypt, from the first-born of man to the first-born of beasts: therefore I sacrifice to our Lord all that openeth the matrice of the male sex, and all the first-born of my sons I do redeem.\n"
	"It shall be therefore as a sign in thy hand, and as a thing hanged before thine eyes, for a remembrance: because our Lord by a strong hand hath brought us forth out of Aegypt.\n"
	"Therefore when Pharao had sent forth the people, our Lord led them not by the way of the Philisthiims' country which is near: thinking lest perhaps it would repent them, if they should see wars arise against them, and would return into Aegypt.\n"
	"But he led them about by the way of the desert, which is besides the Red sea: and the children of Israel went up out of the Land of Aegypt armed.\n"
	"Moyses also took Joseph's bones with him: because he had adjured the children of Israel, saying: God shall visit you, carry out my bones from hence with you.\n"
	"And marching from Socoth they camped in Etham in the utmost coasts of the wilderness.\n"
	"And our Lord went before them to shew the way by day in a pillar of a cloud, and by night in a pillar of fire: that he might be the guide of their journey both times.\n"
	"There never failed the pillar of the cloud by day, nor the pillar of fire by night, before the people.";