const char* chap631 = "Alleluia. Confess ye to our Lord because he is good: because his mercy is for ever.\n"
	"Let Israel now say that he is good: that his mercy is for ever.\n"
	"Let the house of Aaron now say: that his mercy is for ever.\n"
	"Let them now say which fear our Lord: that his mercy is for ever.\n"
	"From tribulation I invocated our Lord: and our Lord heard me in largeness.\n"
	"Our Lord is my helper: I will not fear what man can do to me.\n"
	"Our Lord is my helper: and I will look over mine enemies.\n"
	"It is good to hope in our Lord, rather than to hope in man.\n"
	"It is good to hope in our Lord, rather than to hope in Princes.\n"
	"All nations have compassed me: and in the name of our Lord am I revenged on them.\n"
	"Compassing they have compassed me: and in the name of our Lord I was revenged on them.\n"
	"They compassed me as bees, and were inflamed as fire in thorns: and in the name of our Lord I was revenged on them.\n"
	"Being thrust^ I was overturned to fall: and our Lord received me.\n"
	"Our Lord is my strength, and my praise: and he is made my salvation.\n"
	"The voice of exultation, and of salvation in the tabernacles of the just.\n"
	"The right hand of our Lord hath wrought strength: the right hand of our Lord hath exalted me, the right hand of our Lord hath wrought strength.\n"
	"I shall not die, but shall live: and I will tell the works of our Lord.\n"
	"Our Lord chastising hath chastised me: and to death he hath not delivered me.\n"
	"Open ye the gates of justice to me, being entered into them I will confess to our Lord:\n"
	"this is the gate of our Lord, the just shall enter into it.\n"
	"I will confess to thee because thou hast heard me: and art become my salvation.\n"
	"The stone, which the builders rejected: the same is made into the head of the corner.\n"
	"This was done by our Lord: and it is marvelous in our eyes.\n"
	"This is the day, which our Lord made: let us rejoice, and be glad therein.\n"
	"O Lord save me, o Lord give good success: Blessed be he that cometh in the name of our Lord.\n"
	"We have blessed you of the house of our Lord:\n"
	"our Lord is God, and he hath given light to us. Appoint a solemn day with thick boughs, even to the horn of the altar.\n"
	"Thou art my God, and I will confess to thee: thou art my God, and I will exalt thee. I will confess to thee because thou hast heard me: and art become my salvation.\n"
	"Confess ye to our Lord because he is good: because his mercy is for ever.";