const char* chap653 = "Unto the end, a Psalm of David.\n"
	"Deliver me, o Lord, from the evil man: from the unjust man rescue me.\n"
	"Which have devised iniquity in their heart: all the day they did appoint battles. They have whet their tongues as that of a serpent:\n"
	"the venom of asps is under their lips.\n"
	"Keep me, o Lord, from the hand of the sinner: and from unjust men deliver me.\n"
	"Who have devised to supplant my steps: the proud have hid a snare for me: And they have stretched out ropes for a snare: they have laid a stumbling block for me near the way.\n"
	"I said to our Lord: Thou art my God: hear, o Lord, the voice of my petition.\n"
	"O Lord, Lord the strength of my salvation: thou hast overshadowed my head in the day of battle.\n"
	"Yield me not, o Lord, from my desire to the sinner: they have devised against me, forsake me not, lest they perhaps be proud.\n"
	"The head of their compass: the labour of their lips shall cover them.\n"
	"Coals shall fall upon them, thou shalt cast them down into fire: in miseries they shall not stand up.\n"
	"A man full of tongue shall not be directed in the earth: evils shall take the unjust man into destruction.\n"
	"I have known that our Lord will do the judgment of the needy: and the revenge of the poor.\n"
	"But as for the just, they shall confess to thy name: and the righteous shall dwell with thy countenance.";