const char* chap654 = "A Psalm of David. Lord I have cried to thee, hear me: attend to my voice when I shall cry to thee.\n"
	"Let my prayer be directed as incense in thy sight: the elevation of my hands as evening sacrifice.\n"
	"Set o Lord a watch to my mouth: and a door round about to my lips.\n"
	"Decline not my heart into words of malice, to make excuses in sins. With men that work iniquity: and I will not communicate with the chief of them.\n"
	"The just shall rebuke me in mercy, and shall reprehend me: but let not the oil of a sinner fat my head. Because yet also my prayer is in their good pleasures:\n"
	"their judges are swallowed up joined to the rock. They shall hear my words because they have prevailed:\n"
	"as the grossness of the earth is broken out upon the earth. Our bones are dissipated near to hell:\n"
	"for to thee, o Lord, Lord are mine eyes; in thee have I hoped, take not away my soul.\n"
	"Keep me from the snare, which they have set for me: and from the scandals of them that work iniquity.\n"
	"Sinners shall fall in his net: I am alone until I pass.";