const char* chap659 = "Alleluia, of Aggaeus and Zacharie.\n"
	"My soul praise thou our Lord, I will praise our Lord in my life: I will sing to my God as long as I shall be. Put not confidence in Princes:\n"
	"in the sons of men: in whom there is no salvation.\n"
	"His spirit shall go forth, and he shall return into his earth: in that day all their cogitations shall perish.\n"
	"Blessed is he, whose helper is the God of Jacob, his hope in our Lord his God:\n"
	"who made heaven and earth, the sea, and all things that are in them.\n"
	"Which keepeth truth for ever, doth judgment for them that suffer wrong: giveth food to the hungry. Our Lord looseth the fettered:\n"
	"our Lord illuminateth the blind. Our Lord lifteth up the bruised, our Lord loveth the just.\n"
	"Our Lord keepeth strangers, the pupil and widow he will receive: and the ways of sinners he will destroy.\n"
	"Our Lord will reign for ever^ thy God, o Sion in generation & generation.";