const char* chap66 = "And they set forward from Elim, and all the multitude of the children of Israel came into the desert Sin, which is between Elim and Sinai: the fifteenth day of the second month, after they came forth out of the Land of Aegypt.\n"
	"And all the assembly of the children of Israel murmured against Moyses & Aaron in the wilderness.\n"
	"And the children of Israel said to them: Would to God we had died by the hand of our Lord in the Land of Aegypt, when we sat over the flesh pots, and did eat bread our fill: why have you brought us into this desert, that you might kill all the multitude with famine?\n"
	"And our Lord said to Moyses: Behold I will rain you bread from heaven: let the people go forth, and gather that sufficeth for every day: that I may prove them whether they will walk in my law, or not.\n"
	"But the sixth day let them provide for to bring in: and let it be double to that they were wont to gather every day.\n"
	"And Moyses and Aaron said to all the children of Israel: At even you shall know that our Lord hath brought you forth out of the land of Aegypt;\n"
	"and in the morning you shall see the glory of our Lord: for he hath heard your murmuring against our Lord. But as for us, what are we, that you mutter against us?\n"
	"And Moyses said: At even our Lord will give you flesh to eat, and in the morning bread your fill: for he hath heard your murmurings, which you have murmured against him, for what are we? Neither is your murmuring against us, but against our Lord.\n"
	"Moyses also said to Aaron: Say to the whole assembly of the children of Israel: Approach you before our Lord: for he hath heard your murmuring.\n"
	"And when Aaron spake to all the assembly of the children of Israel, they looked toward the wilderness: and behold the glory of our Lord appeared in a cloud.\n"
	"And our Lord spake to Moyses, saying:\n"
	"I have heard the murmurings of the children of Israel, say to them: At even you shall eat flesh, and in the morning you shall have your fill of bread: and you shall know that I am the Lord your God.\n"
	"Therefore it came to pass at even, & the quail rose, and covered the camp: in the morning also a dew lay round about the camp.\n"
	"And when it had covered the face of the earth, it appeared in the wilderness small, and as it were beaten with a pestle like unto the hoar frost on the ground.\n"
	"Which when the children of Israel had seen, they said one to other: Man-hu! Which signifieth: What is this! For they knew not what it was. To whom Moyses said: This is the bread, which our Lord hath given you to eat.\n"
	"This is the word, that our Lord hath commanded: Let every one gather of it so much as sufficeth to eat: a gomor every man, according to the number of your souls that dwell in a tent so shall you take up.\n"
	"And the children of Israel did so: and they gathered, one more, another less.\n"
	"And they measured by the measure of a gomor: neither he that gathered more, had above: nor he that provided less, found under: but every one gathered according to that which they were able to eat.\n"
	"And Moyses said to them: Let no man leave thereof till the morning.\n"
	"Who heard him not, but certain of them left until the morning, and it began to be full of worms, and it putrefied. And Moyses was angry against them.\n"
	"And every one of them gathered in the morning so much as might suffice to eat: and after the sun waxed hot, it melted.\n"
	"But in the sixth day they gathered double portions, that is, two gomors every man: and all the Princes of the multitude came, and told Moyses.\n"
	"Who said to them: This is it which our Lord hath spoken: The Sabbath's rest is sanctified unto our Lord tomorrow. Whatsoever is to be wrought, do it: and the meats that are to be made ready, make them ready: and whatsoever shall remain, lay it up until the morning.\n"
	"And they did so as Moyses had commanded, and it putrefied not, neither was there worm found in it.\n"
	"And Moyses said: Eat it today, because it is the Sabbath of our Lord: today it shall not be found in the field.\n"
	"Gather it six days: but in the seventh day is the Sabbath of our Lord, therefore it shall not be found.\n"
	"And the seventh day came: and some of the people going forth to gather, found not.\n"
	"And our Lord said to Moyses: How long will you not keep my commandments, and my law?\n"
	"See that our Lord hath given you a Sabbath, and for this cause on the sixth day he giveth you double portions: let each man tarry with himself, and let none go forth out of his place the seventh day.\n"
	"And the people kept the Sabbath on the seventh day.\n"
	"And the house of Israel called the name thereof Manna: which was as it were coriander seed white, and the taste thereof like to flour with honey.\n"
	"And Moyses said: This is the word, which our Lord hath commanded: Fill a gomor of it, and let it be kept unto the generations to come hereafter; that they may know the bread, wherewith I fed you in the wilderness, when you were brought forth out of the Land of Aegypt.\n"
	"And Moyses said to Aaron: Take one vessel, and put Manna into it, so much as a gomor can hold: and lay it up before our Lord to keep unto your generations:\n"
	"as our Lord commanded Moyses. And Aaron put it in the tabernacle to be reserved.\n"
	"And the children of Israel did eat Manna forty years, till they came into the habitable land: with this meat were they fed, until they touched the borders of the land of Chanaan.\n"
	"And a gomor is the tenth part an ephi.";