const char* chap660 = "Alleluia. Praise ye our Lord because Psalm is good: to our God let there be pleasant and comely praise.\n"
	"Our Lord building up Jerusalem: will gather together the dispersions of Israel.\n"
	"Who healeth the contrite of heart: and bindeth up their sores.\n"
	"Who numbereth the multitude of stars: & giveth names to them all.\n"
	"Great is our Lord, and great is his strength: and of his wisdom there is no number.\n"
	"Our Lord receiving the meek: & humbling sinners even to the ground.\n"
	"Sing ye to our Lord in confession: sing ye to our God on harp.\n"
	"Who covereth the heaven with clouds: and prepareth rain for the earth. Who bringeth forth grass in the mountains: and herb for the service of men.\n"
	"Who giveth to beasts their food: and to the young ravens that call upon him.\n"
	"He shall not have pleasure in the strength of an horse: nor in the legs of a man shall he be well pleased.\n"
	"Our Lord is well pleased toward them that fear him: and in them that hope upon his mercy.";