const char* chap67 = "Therefore all the multitude of the children of Israel setting forward from the desert Sin, by their mansions, according to the word of our Lord, camped in Raphidim, where there was no water for the people to drink.\n"
	"Who chiding against Moyses, said: Give us water, that we may drink. To whom Moyses answered: Why chide you against me? Wherefore do you tempt our Lord?\n"
	"The people therefore was thirsty there for lack of water, & murmured against Moyses, saying: Why didst thou make us go forth out of Aegypt to kill us, and our children, & our beasts with thirst:\n"
	"And Moyses cried to our Lord, saying: What shall I do to this people? Yet a little while, and they will stone me.\n"
	"And our Lord said to Moyses: Go before the people, and take with thee of the ancients of Israel: and the rod wherewith thou didst strike the river, take in thy hand, and go.\n"
	"Behold I will stand there before thee, upon the rock Horeb: and thou shalt strike the rock, & water shall go out thereof, that the people may drink. Moyses did so before the ancients of Israel:\n"
	"and he called the name of that place, Temptation, because of the chiding of the children of Israel, and for that they tempted our Lord, saying: Is the Lord among us or not?\n"
	"And Amalec came, and fought against Israel in Raphidim.\n"
	"And Moyses said to Josue: Choose out men, and go forth & fight against Amalec: tomorrow I will stand in the top of the hill having the rod of God in my hand.\n"
	"Josue did as Moyses had spoken, and he fought against Amalec: but Moyses and Aaron and Hur went up upon the top of the Hill.\n"
	"And when Moyses lifted up his hands, Israel overcame: but if he did let them down a little, Amalec overcame.\n"
	"And the hands of Moyses were heavy: therefore they took a stone, and put under him, whereupon he sat: and Aaron and Hur stayed up his hands on both sides. And it came to pass that his hands were not weary until sun set.\n"
	"And Josue put Amalec to flight, & his people by the edge of the sword.\n"
	"And our Lord said to Moyses: Write this for a monument in a book, & deliver it to the ears of Josue: for I will destroy the memory of Amalec from under heaven.\n"
	"And Moyses builded an Altar, and called the name thereof, Our Lord my exaltation, saying:\n"
	"Because the hand of our Lord's throne, and the war of our Lord shall be against Amalec, from generation unto generation.";