const char* chap676 = "He that loveth discipline, loveth knowledge: but he that hateth reprehensions is unwise.\n"
	"He that is good, shall draw grace from our Lord: but he that trusteth in his own cogitations, doth impiously.\n"
	"Man shall not be strengthened by impiety: and the root of the just shall not be moved.\n"
	"A diligent woman is a crown to her husband: and putrefaction in his bones, she that doth things worthy of confusion.\n"
	"The cogitations of the just are judgments: & the counsels of the impious are fraudulent.\n"
	"The words of the impious lie in wait for blood: the mouth of the just shall deliver them.\n"
	"Turn the impious, and they shall not be: but the house of the just shall be permanent.\n"
	"A man shall be known by his doctrine: but he that is vain and foolish, shall lie open to contempt.\n"
	"Better is the poor and sufficient to himself, than he that is glorious and wanteth bread.\n"
	"The just knoweth the lives of his beasts: but the bowels of the impious are cruel.\n"
	"He that tilleth his land, shall be filled with breads: but he that pursueth idleness is a very fool. He that is delighted in much quaffing of wine, leaveth contumely in his munitions.\n"
	"The desire of the impious is the muniment of the most wicked: but the root of the just shall prosper.\n"
	"For the sins of the lips' ruin approacheth to the evil man: but the just escapeth out of distress.\n"
	"Of the fruit of his own mouth shall every man be replenished with good things, and according to the works of his hands it shall be repayed him.\n"
	"The way of a fool is right in his eyes: but he that is wise heareth counsels.\n"
	"A fool by & by sheweth his anger: but he that dissembleth injuries is wise.\n"
	"He that speaketh that which he knoweth, is an utterer of justice: but he that lieth, is a fraudulent witness.\n"
	"There is that promiseth, and is pricked as it were with the sword of conscience: but the tongue of the wise is health.\n"
	"The lips of truth shall be stable for ever: but he that is an hasty witness, frameth a tongue of lying.\n"
	"Guile is in the heart of them that think evil things: but joy followeth them that give counsels of peace.\n"
	"It shall not make the just sorry what soever shall fall to him: but the impious shall be replenished with evil.\n"
	"Lying lips are an abomination to our Lord: but they that do faithfully please him.\n"
	"A circumspect man concealeth knowledge: and the heart of the unwise provoketh folly.\n"
	"The hand of the strong shall rule, but that which is slothful, shall serve under tributes.\n"
	"Pensiveness in the heart of a man shall humble him, & with a good word he shall be made glad.\n"
	"He that neglecteth damage for a friend, is just: but the way of the impious shall deceive them.\n"
	"The fraudulent man shall not find gain: and the substance of a man shall be the price of gold.\n"
	"In the path of justice, life: but the by-way leadeth to death.";