const char* chap677 = "A wise son is the doctrine of the father: but he that is a scorner, heareth not when he is rebuked.\n"
	"Of the fruit of his own mouth man shall be filled with good things: but the soul of the prevaricators is wicked.\n"
	"He that keepeth his mouth, keepeth his soul: but he that is unadvised to speak shall feel evils.\n"
	"The sluggard will and will not: but the soul of them that work, shall be made fat.\n"
	"The just shall detest a lying word: but the impious confoundeth, and shall be confounded.\n"
	"Justice keepeth the way of the innocent: but impiety supplanteth the sinner.\n"
	"There is one as it were with riches whereas he hath nothing: and there is as it were poor, whereas he is in much riches.\n"
	"The redemption of a man's life, his riches: but he that is poor, beareth not reprehension.\n"
	"The light of the just maketh glad: but the candle of the impious shall be extinguished.\n"
	"Among the proud there are always brawls: but they that do all things with counsel, are ruled by wisdom.\n"
	"Substance hastened shall be diminished: but that which by little and little is gathered with the hand, shall be multiplied.\n"
	"Hope that is deferred afflicteth the soul: a tree of life the desire of ckoning.\n"
	"Who so detracteth from any thing, he bindeth himself for the time to come: but he that feareth the precept, shall converse in peace. Guileful souls err in sins: the just are merciful & have pity.\n"
	"The law of a wise man a fountain of life, that he may decline from the ruin of death.\n"
	"Good doctrine shall give grace: in the way of contemners a whirlpool.\n"
	"The subtle man doth all things with counsel: but he that is a fool openeth folly.\n"
	"The messenger of the impious shall fall into evil: but a faithful legate, is health.\n"
	"Poverty, and ignominy, to him that forsaketh discipline: but he that yieldeth to him that rebuketh, shall be glorified.\n"
	"Desire if it be accomplished, delighteth the soul: fools detest them that fly evil things.\n"
	"He that walketh with the wise, shall be wise: a friend of fools shall be made like.\n"
	"Evil pursueth sinners, and to the just good things shall be repayed.\n"
	"The good man leaveth heirs, sons, and nephews: and the substance of the sinner is kept for the just.\n"
	"Much meat in the tilled grounds of the fathers: and to others they are gathered without judgment.\n"
	"He that spareth the rod, hateth his child: but he that loveth him doth instantly nurture him.\n"
	"The just eateth and filleth his soul: but the belly of the impious unsatiable.";