const char* chap678 = "A wise woman buildeth her house: the unwise will with her hands destroy that also which is built.\n"
	"He that walketh in the right way, & feareth God, is despised of him, that goeth an infamous way.\n"
	"In the mouth of a fool the rod of pride: but the lips of the wise keep them.\n"
	"Where oxen are not, the stall is empty: but where much corn is, there is the ox's strength manifest.\n"
	"A faithful witness will not lie: but a deceitful witness uttereth a lie.\n"
	"A scorner seeketh wisdom and findeth it not: the doctrine of the prudent is easy.\n"
	"Go against a foolish man, and he knoweth not the lips of prudence.\n"
	"The wisdom of a discreet man is to understand his way: and the imprudence of fools erreth.\n"
	"A fool will laugh at sin, & among the just grace shall abide.\n"
	"The heart that knoweth the bitterness of his soul, in his joy shall not the stranger be mingled.\n"
	"The house of the impious shall be rased: the tabernacles of the just shall spring.\n"
	"There is a way, which seemeth to a man just: but the later ends thereof lead to death.\n"
	"Laughter shall be mingled with sorrow, and mourning occupieth the later ends of joy.\n"
	"A fool shall be replenished with his ways, and the good man shall be above him.\n"
	"The innocent believeth every word: the discreet man considereth his steps.\n"
	"A wise man feareth and declineth from evil: the fool leapeth over and is confident.\n"
	"The impatient man shall work folly: and the subtle man is odious.\n"
	"The childish man shall possess folly, and the prudent shall expect knowledge.\n"
	"The evil shall lie down before the good, and the impious before the gates of the just.\n"
	"The poor shall be odious even to his neighbour: but the friends of the rich be many.\n"
	"He that despiseth his neighbour, sinneth: but he that hath pity on the poor, shall be blessed.\n"
	"They err that work evil: mercy and truth prepare good things.\n"
	"In every work there shall be aboundance: but where many words are, there is oftentimes poverty.\n"
	"The crown of the wise, their riches: the folly of fools, imprudence.\n"
	"A faithful witness delivereth souls: and the dissembler uttereth lies.\n"
	"In the fear of our Lord is confidence of strength, and to his children there shall be hope.\n"
	"The fear of our Lord a fountain of life, that he may decline from the ruin of death.\n"
	"In the multitude of people the dignity of the king: and in fewness of people the ignominy of the Prince.\n"
	"He that is patient, is governed with much wisdom: but he that is impatient, exalteth his folly.\n"
	"Health of heart, the life of the flesh: envy, the putrefaction of the bones.\n"
	"He that doth calumniate the needy, upbraideth his maker: but he honoureth him, that hath pity on the poor.\n"
	"The impious shall be expelled in his malice: but the just hopeth in his death.\n"
	"In the heart of the prudent resteth wisdom, & it shall instruct all the unlearned.\n"
	"Justice advanceth a nation: but sin maketh peoples miserable.\n"
	"A servant that understandeth is acceptable to the king: he that is unprofitable shall sustain his anger.";