const char* chap679 = "A soft answer breaketh anger: and a hard word raiseth up fury.\n"
	"The tongue of the wise adorneth knowledge: the mouth of fools boileth forth folly.\n"
	"In every place the eyes of our Lord behold the good and the evil.\n"
	"A peaceable tongue is a tree of life: but that which is immoderate, shall break the spirit.\n"
	"A fool scorneth the discipline of his father: but he that regardeth reprehensions, shall become more prudent. In abundant justice there is greater force: but the cogitations of the impious shall be rooted out.\n"
	"The house of the just is very much strength: and in the fruits of the impious is perturbation.\n"
	"The lips of the wise shall sow knowledge: the heart of fools shall be unlike.\n"
	"The victims of the impious are abominable to our Lord: the vows of the just are acceptable.\n"
	"The way of the impious is abomination to our Lord: he that followeth justice is beloved of him.\n"
	"The doctrine is evil of them that forsake the way of life: he that hateth reprehensions shall die.\n"
	"Hell and perdition are before our Lord: how much more the hearts of the children of men?\n"
	"The pestilent man loveth not him that rebuketh him: nor goeth to the wise.\n"
	"A glad heart cheereth the face: in pensiveness of mind the spirit is cast down.\n"
	"The heart of the wise seeketh doctrine: and the mouth of fools is fed with unskillfulness.\n"
	"All the days of the poor are evil: a secure mind is as it were a continual feast.\n"
	"Better is a little with the fear of our Lord, than great treasures and unsatiable.\n"
	"It is better to be called to herbs with charity: than to a fatted calf with hatred.\n"
	"An angry man stirreth brawls: he that is patient appeaseth those that are raised.\n"
	"The way of the slothful is as an hedge of thorns: the way of the just is without offence.\n"
	"A wise son maketh the father joyful: and the foolish man despiseth his mother.\n"
	"Folly is joy to a fool: and the wise man directeth his steps.\n"
	"Cogitations are dissipated where there is no counsel: but where many counsellers are, they are confirmed.\n"
	"A man rejoiceth in the sentence of his mouth: and a word in due time is best.\n"
	"The path of life above the learned, that he may decline from the lowest hell.\n"
	"Our Lord will destroy the house of the proud: and will make sure the borders of the widow.\n"
	"Evil cogitations are an abomination to our Lord: and pure speech most beautiful shall be confirmed of him.\n"
	"He that pursueth avarice disturbeth his house: but he that hateth gifts shall live. By mercy and faith sins are purged: and by the fear of our Lord every one declineth from evil.\n"
	"The mind of the just meditateth obedience: the mouth of the impious redoundeth with evils.\n"
	"Our Lord is far from the impious: and he will hear the prayers of the just.\n"
	"The light of the eyes rejoiceth the soul: a good name fatteth the bones.\n"
	"The ear that heareth the reprehensions of life, shall abide in the midst of the wise.\n"
	"He that rejecteth discipline, despiseth his soul: but he that yieldeth to reprehensions, is a possessor of the heart.\n"
	"The fear of our Lord, the discipline of wisdom: and humility goeth before glory.";