const char* chap680 = "It pertaineth to man to prepare the heart: and to our Lord to govern the tongue.\n"
	"All the ways of man are open to his eyes: our Lord is the weigher of spirits.\n"
	"Reveal thy works to our Lord: and thy cogitations shall be directed.\n"
	"Our Lord hath wrought all things for himself: the impious also to the evil day.\n"
	"Every arrogant man is an abomination to our Lord: although hand shall be to hand he is not innocent. The beginning of a good way, is to do justice: and it is more acceptable with God, than to immolate hosts.\n"
	"By mercy and truth iniquity is redeemed: and in the fear of our Lord evil is avoided.\n"
	"When the ways of man shall please our Lord, he will convert also his enemies to peace.\n"
	"Better is a little with justice, than much fruit with iniquity.\n"
	"The heart of man disposeth his way: but it pertaineth to our Lord to direct his progress.\n"
	"Divination is in the lips of the king, his mouth shall not err in judgment.\n"
	"Weight and balance are judgments of our Lord: and his work all the stones of the bag.\n"
	"They are abominable to the king that do impiously: because the throne is established by justice.\n"
	"The will of kings are just lips: he that speaketh right things shall be beloved.\n"
	"The king's indignation, messengers of death: and the wise man will pacify it.\n"
	"In the cheerfulness of the king's countenance is life: and his clemency is as the later shower.\n"
	"Possess wisdom, because it is better than gold: and get prudence, because it is more precious than silver.\n"
	"The path of the just avoideth evils: the keeper of his soul keepeth his way.\n"
	"Pride goeth before destruction, and before ruin the spirit shall be exalted.\n"
	"It is better to be humbled with the meek, than to divide spoils with the proud.\n"
	"The learned in word shall find good things: and he that hopeth in our Lord, is blessed.\n"
	"He that is wise in heart, shall be called prudent: and he that is sweet in speech shall find greater things.\n"
	"A fountain of life the learning of him that possesseth it: the doctrine of fools foolishness.\n"
	"The heart of the wise shall instruct his mouth: and shall add grace to his lips.\n"
	"Well set words are a honey comb: sweetness of the soul the health of the bones.\n"
	"There is a way that seemeth to a man right: and the later ends thereof lead to death.\n"
	"The soul of him that laboureth doth labour to himself, because his mouth hath compelled him.\n"
	"The impious man diggeth evil, and in his lips fire burneth.\n"
	"A perverse man raiseth contentions: and one full of words separateth Princes.\n"
	"An unjust man allureth his friend: and leadeth him by a way not good.\n"
	"He that with astonished eyes thinketh wicked things, biting his lips bringeth evil to pass.\n"
	"A crown of dignity old age, which shall be found in the ways of justice.\n"
	"Better is the patient than a strong man: and he that ruleth his mind, than the overthrower of cities.\n"
	"Lots are cast into the bosom, but they are ordered of our Lord.";