const char* chap685 = "As divisions of waters, so the heart of the king is in the hand of our Lord: whither soever he will, he shall incline it.\n"
	"Every way of a man seemeth to himself right: but our Lord weigheth the hearts.\n"
	"To do mercy and judgment, doth more please our Lord than victims.\n"
	"Exaltation of the eyes is the dilation of the heart: the lamp of the impious^ sin.\n"
	"The cogitations of the strong are always in aboundance: but every sluggard is always in poverty.\n"
	"He that gathereth treasures with a lying tongue is vain and witless, and shall stumble at the snares of death.\n"
	"The robberies of the impious shall draw them down, because they would not do judgment.\n"
	"The perverse way of a man is strange: but he that is clean, his work is right.\n"
	"It is better to sit in a corner of the house top, than with a brawling woman, and in a common house.\n"
	"The soul of the impious desireth evil, he will not have pity on his neighbour.\n"
	"The pestilent man being punished, the little one will be wiser: and if he follow the wiseman, he will take knowledge.\n"
	"The just deviseth concerning the house of the impious, that he may draw the impious from evil.\n"
	"He that stoppeth his ear at the cry of the poor, himself also shall cry and shall not be heard.\n"
	"A gift hid quencheth angers: and a gift in the bosom the greatest indignation.\n"
	"It is a joy to the just to do judgment: and dread to them that work iniquity.\n"
	"A man, that shall err from the way of doctrine, shall abide in the assembly of giants.\n"
	"He that loveth good cheer, shall be in poverty: he that loveth wine, and fat things, shall not be rich.\n"
	"The impious shall be given for the just: and the unjust for the righteous.\n"
	"It is better to dwell in a desert land, than with a brawling and angry woman.\n"
	"Treasure to be desired, and oil in the habitation of the just: and the unwise man shall dissipate it.\n"
	"He that followeth justice and mercy, shall find life, justice, and glory.\n"
	"The wise hath scaled the city of the strong, and hath destroyed the confidence thereof.\n"
	"He that keepeth his mouth, and his tongue, keepeth his soul from distresses.\n"
	"The proud and arrogant is called unlearned, which in anger worketh pride.\n"
	"Desires kill the slothful: for his hands would not work any thing:\n"
	"all the day he longeth and desireth: but he that is just, will give, and will not cease.\n"
	"The hosts of the impious abominable, because they are offered of wickedness.\n"
	"A lying witness shall perish: an obedient man shall speak victory.\n"
	"The impious man malapertly hardeneth his countenance: but he that is righteous, correcteth his way.\n"
	"There is no wisdom, there is no prudence, there is no counsel against our Lord.\n"
	"The horse is prepared to the day of battle: but our Lord giveth salvation.";