const char* chap69 = "In the third month of the departure of Israel out of the Land of Aegypt, this day they came into the wilderness of Sinai.\n"
	"For departing out of Raphidim, and coming to the desert of Sinai, they camped in the same place, & there Israel pitched their tents over against the mountain.\n"
	"And Moyses went up to God: and our Lord called him from the mountain, and said: This shalt thou say to the house of Jacob, and shalt tell the children of Israel:\n"
	"Yourselves have seen what I have done to the Aegyptians, how I have carried you upon the wings of eagles, and have taken you unto me.\n"
	"If therefore you will hear my voice, and keep my covenant, you shall be my peculiar of all peoples: for all the earth is mine.\n"
	"And you shall be unto me a Priestly Kingdom, and a holy nation: these are the words that thou shalt speak to the children of Israel.\n"
	"Moyses came: and calling together the nations of the people, he declared all the words which our Lord had commanded him.\n"
	"And all the people answered together. All things that our Lord hath spoken, we will do. And when Moyses had reported the people's words to our Lord,\n"
	"our Lord said to him: Now presently will I come to thee in the darkness of a cloud, that the people may hear me speaking to thee, and may believe thee for ever. Moyses therefore told the people's words to our Lord.\n"
	"Who said to him: Go to the people, and sanctify them today, and tomorrow, and let them wash their garments.\n"
	"And let them be ready against the third day: for in the third day the Lord will descend in the sight of all the people upon the mount Sinai.\n"
	"And thou shalt appoint certain limits to the people in circuit, and shalt say to them: Beware ye ascend not into the mount, & that you touch not the ends thereof: every one that toucheth the mount, dying shall die.\n"
	"Hand shall not touch him, but he shall be stoned to death, or shall be shot through with arrows: whether it be beast, or man, it shall not live. When the trumpet shall begin to sound, then let them ascend into the mount.\n"
	"And Moyses came down from the mount to the people, and sanctified them. And when they had washed their garments,\n"
	"he said to them: Be ready against the third day, and come not near your wives.\n"
	"And now the third day was come, and the morning appeared: and behold thunders began to be heard, and lightnings to flash, and a very thick cloud to cover the mount, & the noise of the trumpet sounded exceedingly: and the people, that was in the camp, feared.\n"
	"And when Moyses had brought them forth to meet with God from the place of the camp, they stood at the bottom of the mount.\n"
	"And all the mount Sinai smoked: for because our Lord was descended upon it in fire, and the smoke arose from it as out of a furnace: and all the mount was terrible.\n"
	"And the sound of the trumpet grew louder by little and little, and was drawn out a length: Moyses spake, and God answered him.\n"
	"And our Lord descended upon the mount Sinai in the very top of the mount, and he called Moyses into the top thereof. Whither when he was ascended,\n"
	"he said unto him: Go down, and charge the people, lest perhaps they will pass their limits to see the Lord, and a very great multitude of them perish.\n"
	"The Priests also that come to the Lord, let them be sanctified, lest he strike them.\n"
	"And Moyses said to our Lord: The common people cannot ascend into the mount Sinai: for thou didst charge, and command, saying: Put limits about the mount, and sanctify it.\n"
	"To whom our Lord said: Go, get thee down, and thou shalt come up, and Aaron with thee: but the Priests and the people let them not pass the limits nor ascend to the Lord, lest perhaps he kill them.\n"
	"And Moyses went down to the people, and told them all.";