const char* chap692 = "The impious flyeth, no man pursuing: but the just confident as a lion, shall be without terror.\n"
	"For the sins of the land the Princes thereof shall be many: & for the wisdom of a man, & the knowledge of those things that are said, the life of the Prince shall be longer.\n"
	"A poor man calumniating the poor, is like a vehement shower, whereby famine is gotten.\n"
	"They that forsake the law, praise the impious: they that keep it, are set on fire against him.\n"
	"Evil men think not on judgment: but they that seek after our Lord, mark all things.\n"
	"Better is a poor man walking in his simplicity, than the rich in crooked ways.\n"
	"He that keepeth the law is a wise son, but he that feedeth gluttons, shameth his father.\n"
	"He that heapeth together riches by usuries and ocker, gathereth them for him that is liberal to the poor.\n"
	"He that turneth away his ears from hearing the law, his prayer shall be execrable.\n"
	"He that deceiveth the just in a wicked way, shall fall into his destruction: and the simple shall possess his goods.\n"
	"The rich man seemeth to himself wise: but the poor man being prudent shall search him.\n"
	"In the exultation of the just there is much glory: when the impious reign^ ruins of men.\n"
	"He that hideth his wicked deeds, shall not be directed: but he that shall confess, and shall forsake them, shall obtain mercy.\n"
	"Blessed is the man that is always fearful: but he that is of an obstinate mind, shall fall into evil.\n"
	"A roaring lion, and hungry bear, an impious Prince over the poor people.\n"
	"A Prince lacking prudence, shall oppress many by calumny: but he that hateth avarice, his days shall be made long.\n"
	"A man that doth calumniate the blood of a soul, if he shall fly into a lake, no man abideth.\n"
	"He that walketh simply shall be saved: he that goeth perverse ways, shall fall once.\n"
	"He that tilleth his ground, shall be filled with breads: but he that pursueth idleness, shall be replenished with poverty.\n"
	"A faithful man shall be much praised: but he that hasteneth to be rich, shall not be innocent.\n"
	"He that knoweth a person in judgement, doth not well: this man even for a morsel of bread forsaketh the truth.\n"
	"A man that hasteneth to be rich, and envieth others, is ignorant that poverty shall come upon him.\n"
	"He that rebuketh a man, shall afterward find favour with him, more than he that by flatteries of tongue deceiveth.\n"
	"He that pilfereth any thing from his father, and from his mother: & saith this is no sin, is the partaker of a mankiller.\n"
	"He that exalteth and dilateth himself, raiseth brawls: but he that trusteth in our Lord, shall be healed.\n"
	"He that hath confidence in his own heart, is a fool: but who so walketh wisely shall be saved.\n"
	"He that giveth to the poor, shall not lack: he that despiseth him that asketh shall sustain penury.\n"
	"When the impious shall rise, men shall be hid: when they shall perish, the just shall be multiplied.";