const char* chap693 = "The man that with stiff neck contemneth him that rebuketh, sudden destruction shall come upon him: and health shall not follow him.\n"
	"In the multiplication of just men, the common people shall rejoice: when the impious shall take princedom, the people shall mourn.\n"
	"A man that loveth wisdom, maketh his father glad: but he that maintaineth harlots, shall destroy his substance.\n"
	"A just king setteth up the land, a covetous man shall destroy it.\n"
	"A man that with fair and feigned words speaketh to his friend, spreadeth a net to his steps.\n"
	"A snare shall entangle the wicked man sinning: and the just shall praise and rejoice.\n"
	"The just knoweth the cause of the poor: the impious is ignorant of knowledge.\n"
	"Pestilent men dissipate a city: but the wise turn away fury.\n"
	"A wise man, if he contend with a fool, whether he be angry, or whether he laugh, shall not find rest.\n"
	"Men of blood hate the simple: but just men seek his soul.\n"
	"A fool uttereth all his spirit: a wiseman deferreth and reserveth till afterward.\n"
	"A Prince that gladly heareth words of lying, hath all his servants impious.\n"
	"The poor man and the creditor have met one another: our Lord is illuminator of both.\n"
	"The king that judgeth the poor in truth, his throne shall be replenished for ever.\n"
	"Rod and rebuke giveth wisdom: but the child that is left to his own will, confoundeth his mother.\n"
	"In the multiplication of the impious, wickedness shall be multiplied, and the just shall see the ruins of them.\n"
	"Nurture thy son, and he shall refresh thee, and shall give delights to thy soul.\n"
	"When prophecy shall fail, the people shall be dissipated: but he that keepeth the Law, is blessed.\n"
	"A servant cannot be taught by words: because he understandeth that which thou sayst, and contemneth to answer.\n"
	"Hast thou seen a man swift to speak? Folly is rather to be hoped, than his amendment.\n"
	"He that nourished his servant delicately from his childhood, afterward shall feel him stubborn.\n"
	"An angry man provoketh brawls: and he that is easy to indignation, shall be more prone to sin.\n"
	"Humiliation followeth the proud: and glory shall receive the humble of spirit.\n"
	"He that is partaker with a thief, hateth his own soul: he heareth one adjuring, and telleth not.\n"
	"He that feareth man, shall soon fall: he that trusteth in our Lord shall be lifted up.\n"
	"Many seek after the face of the Prince: & the judgement of every one cometh forth from our Lord.\n"
	"The just abhor an impious man: & the impious abhor them that are in the right way. The son that keepeth the word, shall be out of perdition.";