const char* chap694 = "The words of the Gatherer the son of Vomiter. The vision, that the man spake, with whom God is, and who being strengthened by God abiding with him, said:\n"
	"I am most foolish of men, & the wisdom of men is not with me.\n"
	"I have not learned wisdom, and have not known the science of saints.\n"
	"Who hath ascended into heaven and descended? Who hath contained the spirit in his hands? Who hath bound the waters together as in a garment? Who hath raised up all the borders of the earth? What is his name, and what is the name of his son, if thou know?\n"
	"Every word of God tried by fire, is a buckler to them that hope in him:\n"
	"Add not any thing to his words, and so thou be reproved and found a liar.\n"
	"Two things I have asked thee, deny them not to me before I die.\n"
	"Vanity, and lying words make far from me. Beggary, and riches give me not: give only things necessary for my sustenance:\n"
	"lest perhaps being filled I be allured to deny, and may say: Who is the Lord? Or being compelled by poverty I may steal, and forswear the name of my God.\n"
	"Accuse not a servant to his master, lest perhaps he curse thee, and thou fall.\n"
	"There is a generation that curseth their father, and that blesseth not their mother.\n"
	"A generation, that seemeth to it-self clean, & yet is not washed from their filthiness.\n"
	"A generation, whose eyes are lofty, and the eye-lids thereof set up on high.\n"
	"A generation, that for teeth hath swords, and chaweth with their grinding teeth, that they may eat the needy out of the earth, and the poor from among men.\n"
	"The horseleech hath two daughters that say: Bring, bring. Three things are unsatiable, the fourth never saith it sufficeth.\n"
	"Hell, and the mouth of the matrice, & the earth which is not satisfied with water: but the fire never saith it sufficeth.\n"
	"The eye that scorneth his father, & that despiseth the travail of his mother in bearing him, let the ravens of the torrents pick it out, and the young of the eagle eat it.\n"
	"Three things are hard to me, and of the fourth I am utterly ignorant.\n"
	"The way of an eagle in the air, the way of a serpent upon a rock, the way of a ship in the midst of the sea, and the way of a man in youth.\n"
	"Such is also the way of an adulterous woman, which eateth, and wiping her mouth saith: I have done no evil.\n"
	"By three things the earth is moved, and the fourth it cannot sustain.\n"
	"By a servant when he shall reign: by a fool when he shall be filled with meat:\n"
	"by an odious woman when she shall be taken in matrimony: & by a bond-woman when she shall be heir to her mistress.\n"
	"There are four the least things of the earth, and they are wiser than the wise.\n"
	"The ants, a weak people, which prepareth in the harvest meat for themselves:\n"
	"The leveret, a people not strong, which placeth his bed in the rock:\n"
	"The locust hath no king, and they go out all by their troops:\n"
	"The stellion stayeth on his hands, & tarrieth in king's houses.\n"
	"There are three things which go well, and the fourth that goeth happily.\n"
	"The lion, the strongest of beasts shall fear at the meeting of none:\n"
	"the cock girded about the loins, and the ram: also the king, against whom none can resist.\n"
	"There is that hath appeared a fool after that he was lifted up on high: for if he had understood, he would have laid his hand upon his mouth.\n"
	"And he that strongly presseth the paps to wring out milk, straineth out butter, and he that violently cleanseth his nose, wringeth out blood: & he that provoketh angers, bringeth forth discords.";