const char* chap697 = "I said therefore in my heart: I will go, & flow in delights, and enjoy good things. And I saw that this also was vanity.\n"
	"Laughter I have reputed error: and to joy I have said: Why art thou deceived in vain?\n"
	"I have thought in my heart to withdraw my flesh from wine, that I might transfer my mind to wisdom, and might avoid folly, till I might see what should be profitable for the children of men: what is needful to be done under the sun, in the number of the days of their life.\n"
	"I have magnified my works, I have built me houses, & planted vineyards,\n"
	"I have made gardens, and orchards, and set them with trees of all kinds,\n"
	"and I have made me ponds of waters, to water the wood of springing trees,\n"
	"I have possessed men-servants and women-servants, and have had a great family: herds also, and great flocks of sheep, above all that were before me in Jerusalem:\n"
	"I have heaped together to myself silver, and gold, and the substance of kings, and provinces: I made me singing men, & singing women, and the delights of the children of men: cups, and goblets to serve to pour out wines:\n"
	"and I surpassed in riches all that were before me in Jerusalem: wisdom also hath persevered with me.\n"
	"And all things that mine eyes desired, I have not denied to them: neither have I stayed my heart, but that it enjoyed all pleasure, & delighted it-self in these things, which I had prepared: and this I esteemed my portion, if I did use my labour.\n"
	"And when I had turned myself to all the works which my hands had done, & to the labours wherein I had sweat in vain, I saw in all things vanity, and affliction of mind, & nothing to be permanent under the sun.\n"
	"I passed further to contemplate wisdom, and errors, and folly (what is man, quoth I, that he can follow the King his Maker?)\n"
	"and I saw that wisdom so much excelled folly, as light differeth from darkness.\n"
	"The eyes of a wiseman are in his head: the fool walketh in darkness: and I have learned that there was one death of both.\n"
	"And I said in my heart: if the fall of the fool & mine shall be one, what doth it profit me, that I have bestowed greater labour for wisdom? And speaking with my mind, I perceived that this also was vanity.\n"
	"For there shall be no memory of the wise in like manner as of the fool for ever, and the times to come shall cover all things together with oblivion: the learned dieth in like manner as the unlearned.\n"
	"And therefore I have been weary of my life, seeing all things under the sun to be evil, and all things vanity and affliction of spirit.\n"
	"Again, I detested all mine industry, wherewith I have laboured under the sun most studiously, being like to have an heir after me:\n"
	"whom I know not, whether he will be a wiseman or a fool, and he shall rule in my labours, wherewith I have sweat and have been careful: and is there any thing so vain?\n"
	"Wherefore I ceased, and my heart hath renounced to labour any more under the sun.\n"
	"For whereas one laboureth in wisdom, and doctrine, and carefulness, he leaveth the things gotten to an idle man: and this therefore is vanity, and great evil.\n"
	"For what profit shall be to a man of all his labour, and affliction of spirit, wherewith he is vexed under the sun?\n"
	"All his days are full of sorrows and miseries, neither by night doth he rest in mind: and is not this vanity?\n"
	"Is it not better to eat and drink, and shew unto his soul good things of his labours? & this is of the hand of God.\n"
	"Who shall so devour, and flow with delights as I?\n"
	"To a man good in his sight, God hath given wisdom, and knowledge, and joy: but to the sinner he hath given affliction, and superfluous care, to add, and to gather together, and deliver it to him that hath pleased God: but this also is vanity, & vain carefulness of the mind.";