const char* chap699 = "I turned myself to other things, and I saw the oppressions, that are done under the sun, and the tears of the innocents, and no comforter: & that they cannot resist their violence, being destitute of all men's help.\n"
	"And I praised rather the dead, than the living:\n"
	"and happier than both have I judged him that is not yet born, nor hath seen the evils that are done under the sun.\n"
	"Again I have contemplated all the labours of men, and their industries I have perceived to lie open to the envy of their neighbour: and in this therefore there is vanity, and superfluous care.\n"
	"A fool foldeth his hands together, and eateth his own flesh, saying:\n"
	"Better is an handful with rest, than both hands full with labour and affliction of mind.\n"
	"Considering I found also another vanity under the sun:\n"
	"There is one, and he hath not a second, not a son, not a brother, and yet he ceaseth not to labour, neither are his eyes satisfied with riches, neither doth he recount, saying: For whom do I labour, and defraud my soul of good things? In this also is vanity, and very ill affliction.\n"
	"It is better therefore that two be together, than one: for they have profit of their society:\n"
	"if one fall, he shall be stayed up of the other. Woe to him that is alone: because when he falleth, he hath none to lift him up.\n"
	"And if two sleep together, they shall warm each other: one how shall he be warmed?\n"
	"And if a man prevail against one, two resist him: a triple cord is hardly broken.\n"
	"Better is a child that is poor and wise, than a king old and foolish, that knoweth not to foresee for hereafter.\n"
	"Because out of the prison and chains sometime there cometh one forth to a Kingdom: and another born in his Kingdom, is consumed with poverty.\n"
	"I saw all men alive, that walk under the sun, with the second youngman, which shall rise up for him.\n"
	"The number of the people, of all that have been before him is infinite: and they that shall be afterward, shall not rejoice in him. But this also is vanity, and affliction of spirit.\n"
	"Take heed to keep thy foot, when thou enterest into the house of God, and approach thou to hear. For much better is obedience, than the victims of fools, who know not what evil they do.";