const char* chap70 = "And our Lord spake all these words.\n"
	"I am the Lord thy God, which brought thee forth out of the Land of Aegypt, out of the house of servitude.\n"
	"Thou shalt not have strange gods before me.\n"
	"Thou shalt not make to thee a graven thing, nor any similitude that is in heaven above, & that is in the earth beneath, neither of those things that are in the waters under the earth.\n"
	"Thou shalt not adore them, nor serve them: I am the Lord thy God mighty, jealous, visiting the iniquity of the fathers upon the children, upon the third and fourth generation of them that hate me:\n"
	"and doing mercy upon thousands to them that love me, and keep my precepts.\n"
	"Thou shalt not take the name of the Lord thy God in vain. For the Lord will not hold him innocent that shall take the name of the Lord his God vainly.\n"
	"Remember that thou sanctify the Sabbath day.\n"
	"Six days shalt thou work, and shalt do all thy works.\n"
	"But on the seventh day is the sabbath of the Lord thy God: thou shalt do no work in it, thou and thy son, and thy daughter, thy man servant, and thy woman servant, thy beast, and the stranger that is within thy gates.\n"
	"For six days the Lord made heaven and earth, and the sea, and all things that are in them, and rested in the seventh day, therefore the Lord blessed the sabbath day, and sanctified it.\n"
	"Honour thy father and thy mother, that thou mayst be long lived upon the earth, which the Lord thy God will give thee.\n"
	"Thou shalt not murder.\n"
	"Thou shalt not commit adultery.\n"
	"Thou shalt not steal.\n"
	"Thou shalt not speak against thy neighbour false testimony.\n"
	"Thou shalt not covet thy neighbour's house: neither shalt thou desire his wife, nor servant, nor handmaid, nor ox, nor ass, nor any thing that is his.\n"
	"And all the people saw the voices, and the flames, and the sound of the trumpet, and the mount smoking: and being frightened and strucken with fear they stood a far off,\n"
	"saying to Moyses: Speak thou to us, and we will hear: let not our Lord Speak to us, lest perhaps we die.\n"
	"And Moyses said to the people: Fear not: for God came to prove you, and that his terror might be in you, and you should not sin.\n"
	"And the people stood a far off. But Moyses went unto the dark cloud wherein God was.\n"
	"Our Lord said moreover to Moyses: This shalt thou say to the children of Israel: You have seen that from heaven I have spoken to you.\n"
	"You shall not make gods of silver, nor gods of gold shall you make to you.\n"
	"An altar of earth you shall make to me, and you shall offer upon it your holocausts and pacifics, your sheep and oxen in every place where the memory of my name shall be: I will come to thee, and will bless thee.\n"
	"And if thou make an Altar of stone unto me, thou shalt not build it of hewed stones: for if thou lift up thy knife over it, it shall be polluted.\n"
	"Thou shalt not go up by grises unto mine Altar, lest thy turpitude be discovered.";