const char* chap703 = "The wisdom of a man shineth in his countenance, and the most mighty will change his face.\n"
	"I observe the mouth of the king, and the precepts of the oath of God.\n"
	"Hasten not to depart from his face, nor continue thou in an evil work: because all that he pleaseth he will do,\n"
	"and his word is full of power: neither can any man say to him. Why dost thou so:\n"
	"He that keepeth the precept, shall find no evil. The heart of a wiseman understandeth time and answer.\n"
	"There is a time for all business, and opportunity, and much affliction of man:\n"
	"because he is ignorant of things past, and things to come he can know by no messenger.\n"
	"It is not in man's power to prohibit the spirit, neither hath he power in the day of death, neither is he suffered to rest when war is at hand, neither shall impiety save the impious.\n"
	"All these things I have considered, and gave my heart on all the works that are done under the sun. Sometime man ruleth over man to his own hurt.\n"
	"I saw the impious buried: who also when they yet lived, were in holy place, and were praised in the city as men of just works. But this also is vanity.\n"
	"Because sentence is not speedily pronounced against the evil, the children of men commit evils without any fear.\n"
	"But yet a sinner by this that he doth evil an hundred times, & by patience is borne withal, I know that it shall be good to them that fear God, which dread his face.\n"
	"Let there be no good to the impious, neither let his days be prolonged, but as a shadow let them pass, that fear not the face of our Lord.\n"
	"There is also another vanity, which is done upon the earth. There are just men, to whom evils happen, as though they had done the works of the impious: and there are impious men, which are so secure, as though they had the deeds of the just. But this also I judge most vain.\n"
	"I therefore have praised mirth, that there was no good thing for a man under the sun, but that he should eat, and drink, and be glad: and this only he should take away with him of his labour in the days of his life, which God hath given him under the sun.\n"
	"And I have set my heart to know wisdom, and to understand the distraction that is in the earth: There is a man that days and nights taketh no sleep with his eyes.\n"
	"And I understood that man can find no reason of all those works of God, that are done under the sun: and the more he shall labour to seek. So much the less he can find: yea if the wiseman shall say that he knoweth, he is not able to find it.";