const char* chap704 = "All these things have I discoursed in my heart, that I might curiously understand them: there are just men and wise: and their works are in the hand of God: and yet man knoweth not whether he be worthy of love or hatred:\n"
	"but all things are reserved uncertain for the time to come, because all things do equally chance to the just and impious, to the good and the evil, to the clean and unclean, to him that immolateth victims, and him that contemneth sacrifices. As the good, so also is the sinner: as the perjured, so he also that sweareth truth.\n"
	"This is a very evil thing among all which are done under the sun, that the same things chance to all men. Whereby also the hearts of the children of men are filled with malice, and with contempt in their life, and after that they shall be brought down to hell.\n"
	"There is no man that may live always, and that can have confidence of this thing: better is a dog living than a lion dead.\n"
	"For the living know that they shall die, but the dead know nothing more, neither have they reward any more: because the memory of them is forgotten.\n"
	"Love also and hatred, and envies have perished together, neither have they part in this world, and in the work that is done under the sun.\n"
	"Go therefore and eat thy bread in joy, & drink thy wine with gladness: because thy works please God.\n"
	"At all time let thy garments be white, and let not oil fall from off thy head.\n"
	"Enjoy life, with thy wife whom thou lovest, all the days of the life of thy instability, which are given to thee under the sun, all the time of thy vanity: for this is the portion in life, and in thy labour, wherewith thou labourest under the sun.\n"
	"Whatsoever thy hand is able to do, work it instantly: for neither work, nor reason, nor wisdom, nor knowledge shall be in hell, whither thou dost hasten.\n"
	"I turned me to another thing, and I saw under the sun, that neither running is of the swift, nor war of the strong, nor bread of the wise, nor riches of the learned, nor grace of the artificers: but time and chance in all.\n"
	"Man knoweth not his own end: but as fishes are taken with the hook, and as birds are caught with the snare, so men are taken in the evil time, when it shall suddenly come upon them.\n"
	"This wisdom also I have seen under the sun and have proved it to be very great:\n"
	"A little city, and few men in it: there came against it a great king, and compassed it, and builded forts round about, and the siege was perfited.\n"
	"And there was found in it a man poor and wise, and he delivered the city by his wisdom, and no man afterward remembered that poorman.\n"
	"And I said, that wisdom is better than strength: how then was the wisdom of the poorman contemned, & his words were not heard?\n"
	"The words of the wise are heard in silence, more than the cry of a Prince among fools.\n"
	"Better is wisdom, than weapons of war: and he that shall offend in one point, shall lose many good things.";