const char* chap705 = "Flies dying mar the sweetness of ointment. Wisdom and glory is more precious, than a little and temporal folly.\n"
	"The heart of a wiseman is in his right hand, and the heart of a fool is in his left hand.\n"
	"Yea and the fool walking in the way, whereas himself is unwise, esteemeth all men fools.\n"
	"If the spirit of him that hath power, ascend upon thee, leave not thy place: because carefulness will make the greatest sins to cease.\n"
	"There is an evil that I have seen under the sun, as it were by error proceeding from the face of the Prince:\n"
	"a fool set in high dignity, and the rich to sit beneath.\n"
	"I have seen servants upon horses: and Princes walking on the ground as servants.\n"
	"He that diggeth a pit, shall fall into it: and he that breaketh the hedge, a serpent shall bite him.\n"
	"He that removeth stones, shall be afflicted in them: and he that cutteth trees, shall be wounded of them.\n"
	"If the iron shall be blunt, and that not as before, but shall be made blunt, it shall be sharpened by great labour: and after industry shall wisdom follow.\n"
	"If a serpent bite in silence, nothing less than it hath he, that detracteth secretly.\n"
	"The words of the mouth of a wiseman grace: and the lips of the unwise shall throw him down headlong.\n"
	"The beginning of his words is folly, and the later end of his mouth is most wicked error.\n"
	"A fool multiplieth words. A man is ignorant what hath been before him: and what shall be after him, who can tell him?\n"
	"The labour of fools shall afflict them, that know not to go into the city.\n"
	"Woe to thee o land, whose king is a child, and whose Princes eat in the morning.\n"
	"Blessed is the land whose king is noble, & whose Princes eat in their time, to refection, and not to riotousness.\n"
	"In slothfulness the roof of the house shall go to ruin, & in the infirmity of the hands the house shall drop through.\n"
	"They make bread for laughter, and wine, that living they may make merry: and to money all things obey.\n"
	"In thy cogitation detract not from the king, and in the secret of thy chamber curse not the richman: because even the birds of the air will carry thy voice, and he that hath wings will declare the sentence.";