const char* chap708 = "Let him kiss me with the kiss of his mouth: because thy breasts are better than wine.\n"
	"smelling fragrantly of the best ointments. Oil poured out is thy name: therefore have young maids loved thee.\n"
	"Draw me: we will run after thee in the odour of thine ointments. The king hath brought me into his cellars: we will rejoice & be glad in thee, mindful of thy breasts above wine: the righteous love thee.\n"
	"I am black but beautiful, o ye daughters of Jerusalem, as the tabernacles of Cedar, as the skins of Salomon.\n"
	"Do not consider me that I am brown, because the sun hath altered my colour: the sons of my mother have fought against me, they have made me a keeper in the vineyards: my vineyard I have not kept.\n"
	"Shew me o thou, whom my soul loveth, where thou feedest, where thou liest in the midday, lest I begin to wander after the flocks of thy companions.\n"
	"If thou know not thyself, o most fairest among women, go forth, and follow after the steps of the flocks, and feed thy kids beside the tabernacles of the pastors.\n"
	"To my company of horsemen, in the chariots of Pharao, have I likened thee, o my love.\n"
	"Thy cheeks are beautiful as the turtle-doves, thy neck as jewels.\n"
	"We will make thee chains of gold, enamelled with silver.\n"
	"Whilst the king was at his repose, my spikenard gave the odour thereof.\n"
	"A bundle of myrrh my beloved is to me, he shall abide between my breasts.\n"
	"A cluster of cypress my love is to me, in the vineyards of Engaddi.\n"
	"Behold thou art fair, o my love, behold thou art fair, thine eyes are as of doves'.\n"
	"Behold thou art fair my beloved, & comely: our little bed is flourishing.\n"
	"The beams of our houses are of cedar, our rafters of cypress trees.";