const char* chap712 = "Let my beloved come into his garden, and eat the fruit of his apple-trees. I am come into my garden o my sister^ spouse, I have reaped my myrrh, with mine aromatical spices: I have eaten the honey-comb with mine honey, I have drunk my wine with my milk: eat o friends, and drink, and be inebriated my dearest.\n"
	"I sleep, and my heart watcheth: the voice of my beloved knocking: Open to me my sister, my love, my dove, mine immaculate: because my head is full of dew, and my locks of the drops of the nights.\n"
	"I have spoiled myself of my robe, how shall I be clothed with it? I have washed my feet, how shall I defile them?\n"
	"My beloved put his hand through the hole, and my belly trembled at his touch.\n"
	"I arose, that I might open to my beloved: my hands have distilled myrrh, and my fingers are full of most approved myrrh.\n"
	"I opened the bolt of my door to my beloved: but he had turned aside, and was passed. My soul melted, as he spake: I sought, and found him not: I called, and he did not answer me.\n"
	"The keepers that go about the city found me: they struck me, and wounded me: the keepers of the walls took away my cloak.\n"
	"I adjure you o daughters of Jerusalem, if you shall find my beloved, that you tell him that I languish with love.\n"
	"What manner of one is thy beloved of the beloved, o most beautiful of women? What manner of one is thy beloved of the beloved, that thou hast so adjured us?\n"
	"My beloved is white and ruddy, chosen of thousands.\n"
	"His head is as the best gold: his hairs as the branches of palm-trees, black as a raven.\n"
	"His eyes as doves upon the little rivers of waters, which are washed with milk, and sit beside the most full streams.\n"
	"His cheeks are as little beds of aromatical spices set of the pigmentaries. His lips are as lilies distilling principal myrrh.\n"
	"His hands wrought round of gold, full of hyacinths. His belly of ivory, distinguished with sapphires.\n"
	"His thighs as pillars of marble, that are upon feet of gold. His form as of Libanus, elect as the cedars.\n"
	"His throat most sweet, and he whole to be desired: such an one is my beloved, and he is my friend, o daughters of Jerusalem.\n"
	"Whither is thy beloved gone o most beautiful of women? Whither is thy beloved turned aside? And we will seek him with thee.";