const char* chap714 = "What shalt thou see in the Sulamitess but the companies of camps? How beautiful are thy passes in shoes, o prince's daughter! The joints of thy thighs are as jewels, that are made by the hand of the artificer.\n"
	"Thy navel as a round bowl, never wanting cups. Thy belly as an heap of wheat, compassed about with lilies.\n"
	"Thy two breasts, as two fawns the twins of a roe.\n"
	"Thy neck as a tower of ivory. Thine eyes as the fish-pools in Hesebon, which are in the gate of the daughter of the multitude. Thy nose as the tower of Libanus, that looketh against Damascus.\n"
	"Thy head as Carmelus: and the hairs of thy head as a king's purple tied to conduit pipes.\n"
	"How beautiful art thou, and how comely my dearest, in delights!\n"
	"Thy stature is like to a palm-tree, & thy breasts to clusters of grapes.\n"
	"I said: I will go up into the palm-tree, and will take hold of the fruits thereof: and thy breasts shall be as the clusters of a vineyard: and the odour of thy mouth as it were of apples.\n"
	"Thy throat as the best wine, worthy for my beloved to drink, & for his lips and his teeth to ruminate.\n"
	"I to my beloved, and his turning is toward me.\n"
	"Come my beloved, let us go forth into the field, let us abide in the villages.\n"
	"Let us rise early to the vineyards, let us see if the vineyard flourish, if the flowers be ready to bring forth fruits, if the pomegranates flourish: there will I give thee my breasts.\n"
	"The Mandragoraes have given a smell. In our gates all fruits: the new and the old, my beloved, I have kept for thee.";