const char* chap716 = "Love justice, you that judge the earth. Think of our Lord in goodness, and in simplicity of heart seek him:\n"
	"because he is found of them that tempt him not: and he appeareth to them that have faith in him.\n"
	"For perverse cogitations separate from God: and proved power chasteneth the unwise:\n"
	"because wisdom will not enter into a malicious soul, nor dwell in a body subject to sins.\n"
	"For the Holy Ghost of discipline will fly from him that feigneth, and will withdraw himself from the cogitations that are without understanding, and he shall be chastened of iniquity ensuing.\n"
	"For the spirit of wisdom is gentle, and will not deliver the curser from his lips: because God is witness of his reins, and he is a true searcher of his heart, and an hearer of his tongue.\n"
	"Because the Spirit of our Lord hath replenished the whole world: and that which containeth all things, hath the knowledge of voice.\n"
	"For this cause he that speaketh unjust things, cannot be hid, neither shall the chastising judgement pass him.\n"
	"For in the cogitations of the impious there shall be examination: and the hearing of his works shall come to God, to the chastising of his iniquities.\n"
	"Because the ear of jealousy heareth all things, and the tumult of murmurings shall not be hid.\n"
	"Keep yourselves therefore from murmuring, which profiteth nothing, and refrain your tongue from detraction, because an obscure speech shall not pass in vain: and the mouth that lieth, killeth the soul.\n"
	"Zeal not death in the error of your life, neither procure ye perdition by the works of your hands.\n"
	"Because God made not death, neither doth he rejoice in the perdition of the living.\n"
	"For he created all things to be: and he made the nations of the earth to health: and there is no medicine of destruction in them, nor Kingdom of hell in the earth.\n"
	"For justice is perpetual and immortal.\n"
	"But the impious with hands & words have provoked it: and esteeming it a friend, have fallen to decay, and have made covenants with it: because they are worthy to be of the part thereof.";