const char* chap717 = "For they have said thinking with themselves not well: Little, and with tediousness is the time of our life: and in the end of a man there is no recovery, and there is none known that hath returned from hell:\n"
	"because of nothing were we born, and after this we shall be as if we had not been: because the breath is a smoke in our nostrils: & speech a spark to move our heart.\n"
	"Which being extinguished, our body shall be ashes, and the spirit shall be poured abroad as soft air, and our life shall pass as the trace of a cloud, and shall be dissolved as a mist, which is driven away by the beams of the sun, and oppressed with the heat thereof:\n"
	"and our name in time shall be forgotten, and no man shall have remembrance of our works.\n"
	"For our time is the passing of a shadow, and there is no return of our end: because it is sealed, and no man returneth.\n"
	"Come therefore, and let us enjoy the good things that are, and let us quickly use the creature as in youth.\n"
	"Let us fill ourselves with precious wine, and ointments: and let not the flower of the time pass us.\n"
	"Let us crown ourselves with roses, before they wither: let there be no meadow, which our riot shall not pass through.\n"
	"Let none of us be exempted from our riotousness: every-where let us leave signs of joy: because this is our portion, and this our lot.\n"
	"Let us oppress the poor just man, and not spare the widow, nor reverence the old man's grey head of long time.\n"
	"But let our strength be the law of justice: for that which is weak, is found unprofitable.\n"
	"Let us therefore circumvent the just, because he is unprofitable to us, and he is contrary to our works, and reproachfully objecteth unto us the sins of the law, and defameth in us the sins of our discipline.\n"
	"He boasteth that he hath the knowledge of God, and nameth himself the son of God.\n"
	"He is made unto us to the defaming of our cogitations.\n"
	"He is grievous unto us even to behold, because his life is unlike to others, & his ways are changed.\n"
	"We are esteemed of him as triflers, and he abstaineth from our ways as from uncleanness, and he preferreth the later ends of the just, and glorieth that he hath God for his father.\n"
	"Let us see therefore if his words be true, and let us prove what things shall come to him, and we shall know what shall be his later end.\n"
	"For if he be the true son of God, he will defend him, & will deliver him from the hands of the adversaries.\n"
	"By contumely and torment let us examine him, that we may know his reverence, and prove his patience.\n"
	"To a most shameful death let us condemn him: for there shall be respect had unto him by his words.\n"
	"These things have they thought, and have erred: for their malice hath blinded them.\n"
	"And they have not known the sacraments of God, nor hoped for the reward of justice, nor esteemed the honour of holy souls.\n"
	"For God created man incorruptible, and to the image of his own likeness he made him.\n"
	"But by the envy of the devil, death entered into the world:\n"
	"and they follow him that are of his part.";