const char* chap718 = "But the souls of the just are in the hand of God, and the torment of death shall not touch them.\n"
	"They seemed in the eyes of the unwise to die: and their decease was counted affliction:\n"
	"and that which with us is the way, is destruction: but they are in peace.\n"
	"And though before men they suffered torments, their hope is full of immortality.\n"
	"Vexed in few things, in many they shall be well disposed of: because God hath tempted them, and hath found them worthy of himself.\n"
	"As gold in the furnace he hath proved them, and as an host of holocaust he hath received them, & in time there shall be respect of them.\n"
	"The just shall shine, and as sparks in a place of reeds they shall run abroad.\n"
	"They shall judge nations, & have dominion over peoples, and their Lord shall reign for ever.\n"
	"They that trust in him, shall understand truth: & the faithful in love shall rest in him: because rest and peace is to his elect.\n"
	"But the impious according to the things which they have thought, shall have correption: which have neglected the just, & have revolted from our Lord.\n"
	"For he that rejecteth wisdom and discipline, is unhappy: and their hope is vain, and labours without fruit, & their works unprofitable.\n"
	"Their wives are senseless, and their children most wicked.\n"
	"Cursed is their creature: because happy is the barren woman: and the undefiled, which hath not known bed in sin, she shall have fruit in visitation of holy souls:\n"
	"and the eunuch that hath not wrought iniquity with his hands, nor thought most wicked things against God: for the chosen gift of faith shall be given to him, and a most acceptable lot in the temple of God.\n"
	"For of good labour there is glorious fruit, and the root of wisdom which falleth not.\n"
	"But the children of adulterers shall be in consummation, and the seed of the unlawful bed shall be destroyed.\n"
	"And if certes they be of long life, they shall be reputed for nothing, & their last old-age shall be without honour.\n"
	"And if they die quickly they shall have no hope, nor speech of comfort in the day of acknowledging.\n"
	"For of a wicked nation the ends are cruel.";