const char* chap719 = "How beautiful is the chaste generation with glory! For the memory thereof is immortal: because it is known both with God and with men.\n"
	"When it is present, they imitate it, and they desire it when it hath withdrawn it-self, and it triumpheth crowned for ever, winning the reward of undefiled conflicts.\n"
	"But the multitude of the impious that hath many children, shall not be profitable, and bastard plants shall not take deep root, nor lay sure foundation.\n"
	"And if in the boughs for a time they shall spring being weakly set, they shall be moved of the wind, and by the vehemency of the winds they shall be rooted out.\n"
	"For the unperfect boughs shall be broken, and their fruits shall be unprofitable, and sour to eat, and meet for nothing.\n"
	"For the children that be born of wicked sleeps, are witnesses of wickedness against the parents in their examination.\n"
	"But the just if he be prevented with death, shall be in a place of refreshing.\n"
	"For venerable old age is not that of long time, nor accounted by the number of years: but the understanding of a man are grey hairs:\n"
	"and an immaculate life is old age.\n"
	"Pleasing God he is made beloved, and living among sinners he was translated.\n"
	"He was taken away lest malice should change his understanding, or lest any guile might deceive his soul.\n"
	"For the bewitching of vanity obscureth good things, and the inconstancy of concupiscence perverteth the understanding that is without malice.\n"
	"Being consummate in short space he fulfilled much time:\n"
	"for his soul pleased God: for this cause he hastened to bring him out of the midst of iniquities: but the peoples that are seeing, and not understanding, nor putting such things in their hearts:\n"
	"that the grace of God, and mercy is toward his saints, and respect toward his elect.\n"
	"But the just dead condemneth the impious alive, and youth soon ended, the long life of the unjust.\n"
	"For they shall see the end of the wise, and shall not understand what God hath thought of him, and why our Lord hath fenced him.\n"
	"For they shall see and shall contemn him: but our Lord shall laugh them to scorn,\n"
	"and they shall fall after this without honour, and in contumely among the dead for ever: because he shall break them puffed up without voice, and shall remove them from the foundations, and they shall be made desolate unto the highest degree: and shall be mourning, and the memory of them shall perish.\n"
	"They shall come fearful in cogitation of their sins, and their iniquities on the contrary shall convince them.";