const char* chap720 = "Then shall the just stand in great constancy against those that have afflicted them, and taken away their labours.\n"
	"They seeing shall be troubled with horrible fear, and shall marvel at the suddenness of unexpected salvation,\n"
	"saying within themselves, repenting, and sighing for anguish of spirit: These are they, whom we had sometime in derision, and in a parable of reproach.\n"
	"We senseless esteemed their life madness, and their end without honour.\n"
	"Behold how they are counted among the children of God, and their lot is among the saints.\n"
	"We therefore have erred from the way of truth, and the light of justice hath not shined to us, and the sun of understanding rose not to us.\n"
	"We are wearied in the way of iniquity and perdition, and have walked hard ways, but the way of our Lord we have not known.\n"
	"What hath pride profited us? Or what commodity hath the vaunting of riches brought to us?\n"
	"All those things are passed away as a shadow, and as a messenger running before,\n"
	"and as a ship, that passeth through the surging waters: whereof, when it is past, the trace cannot be found nor the path of that ship's keel in the waves:\n"
	"or as a bird, that flyeth through in the air, of which there is no token can be found of her passage, but only a sound of the wings beating the light wind: and by vehemence of going cutting the air, moving the wings she is flown through, and afterward there is no sign found of her way:\n"
	"or as when an arrow is shot forth to a set mark, the divided air is forthwith closed in it-self again, so that the passage thereof is not known:\n"
	"so we also being born forthwith ceased to be: and of virtue certes have been able to shew no sign: but in our naughtiness we are consumed.\n"
	"Such things said they in hell, which sinned:\n"
	"because the hope of the impious is as dust, which is taken away with the wind: and as a thin froth, which is dispersed by the storm: and as smoke that is scattered abroad by the wind: and as the memory of a guest of one day that passeth.\n"
	"But the just shall live for ever, and their reward is with our Lord, and cogitation of them with the Highest.\n"
	"Therefore shall they receive a Kingdom of honour, & a crown of beauty at the hand of our Lord: because with his right hand he will cover them, and within his holy arm he will defend them.\n"
	"And his zeal will take armour, and he will arm the creature to the revenge of the enemies.\n"
	"He will put on justice for a breast-plate, & will take sincere judgement for an helmet:\n"
	"he will take equity for an invincible shield:\n"
	"and he will sharpen fierce wrath for a spear, & the round world shall fight with him against the senseless.\n"
	"The shots of lightnings shall go directly, & as it were from a bow of the clouds well bent they shall be cast forth, and shall light on a certain place.\n"
	"And from rocked wrath shall thick hail-stones be cast, the water of the sea shall rage against them, and the rivers shall run together roughly.\n"
	"A spirit of power shall stand against them, and as a hurlwind shall divide them: and their iniquity shall bring all the land to a desert, and naughtiness shall overthrow the seats of the mighty.";