const char* chap722 = "I also certes am a mortal man, like to all, and of the earthly kindred of him that was made first, and in the womb of my mother was I fashioned flesh,\n"
	"the time of ten months was I brought together in blood, of the seed of man, and the delectation of sleep concurring.\n"
	"And I being born received the common air, and fell upon the earth that is made alike, and the first voice like to all men did I put forth weeping.\n"
	"I was nourished in swaddling cloths, and great cares.\n"
	"For none of the kings had other beginning of nativity.\n"
	"There is one entrance therefore into life to all men, and like departure.\n"
	"For this cause I wished, and understanding was given me: and I invocated, and the spirit of wisdom came upon me:\n"
	"and I preferred her before Kingdoms and thrones, and riches I counted to be nothing in comparison of her.\n"
	"Neither did I compare the precious stone to her: because all gold in comparison of her, is a little sand, and silver in the sight of her shall be esteemed as clay.\n"
	"Above health and beauty did I love her, and purposed to have her for light: because her light cannot be extinguished.\n"
	"And all good things came to me together with her, and very much honesty by her hands,\n"
	"and I rejoiced in all: because this wisdom went before me, and I was ignorant that she is the mother of all these.\n"
	"Which I learned without fiction, and do communicate without envy, and her honesty I hid not.\n"
	"For she is an infinite treasure to men: which who so have, are made partakers of the friendship of God commended for the gifts of discipline.\n"
	"And to me God hath given to speak according to my mind, and to presume things worthy of those, that are given me: because he is the guide of wisdom, and the Creator of the wise:\n"
	"For in his hand are both we, & our words, and wisdom, and the knowledge & discipline of works.\n"
	"For he gave me the true knowledge of those things which are: that I may know the disposition of the round world, and the virtues of the elements,\n"
	"the beginning, & end, & midst of times, the permutations of changeable seasons, and consummations of times,\n"
	"the courses of the year, and dispositions of the stars,\n"
	"the natures of beasts, and furies of wild beasts, the force of winds, and the cogitations of men, the differences of plants, and virtues of roots,\n"
	"& whatsoever are hid things and not foreseen, I have learned: for wisdom the worker of all taught me.\n"
	"For in her is the spirit of understanding, holy, only, manifold, subtile, eloquent, moveable, undefiled, sure, sweet, loving, good, sharp, who nothing hindereth well-doing,\n"
	"gentle, benign, stable, certain, secure, having all power, foreseeing all things, and that containeth all spirits: intelligible, clean, subtile.\n"
	"For wisdom is more moveable than all moveable things: and reacheth every-where because of her cleanness.\n"
	"For she is a vapour of the power of God, & a certain sincere emanation of the glory of God omnipotent: and therefore no defiled thing cometh unto her.\n"
	"For she is the brightness of eternal light, & the unspotted glass of God's majesty, and the image of his goodness.\n"
	"And whereas she is one, she can do all things: and permanent in herself she reneweth all things, and by nations transporteth herself into holy souls, she maketh the friends of God, and Prophets.\n"
	"For God loveth none, but him that dwelleth with wisdom.\n"
	"For she is more beautiful than the sun, and above all disposition of the stars, being compared to light she is found the first.\n"
	"For night succeedeth to it, but malice overcometh not wisdom.";