const char* chap723 = "She reacheth therefore from end unto end mightily, and disposeth all things sweetly.\n"
	"Her have I loved, and have sought her out from my youth, and have sought to take her for my spouse, and I was made a lover of her beauty.\n"
	"She glorifieth her nobility, having consociation with God: yea and the Lord of all hath loved her.\n"
	"For she is the mistress of the discipline of God, & the chooser of his works.\n"
	"And if riches be desired in life, what is richer than wisdom, which worketh all things?\n"
	"And if understanding do work: who is the worker of those things that are, more than she?\n"
	"And if a man love justice: her labours have great virtues: for she teacheth sobriety, and prudence, and justice, and strength, than the which nothing is more profitable in life to men.\n"
	"And if a man desire multitude of knowledge, she knoweth things past, & conjectureth of things to come: she knoweth the subtilties of words, and the solutions of arguments: she knoweth signs and wonders before they be done, and the events of times and ages.\n"
	"I purposed therefore to bring her to me to live together: knowing that she will communicate unto me of good things, and will be a comfort of my cogitation & tediousness.\n"
	"I shall have for her sake glory with the multitudes and honour with the ancient being young:\n"
	"and I shall be found sharp in judgement, and in the sight of the mighty I shall be marvelous, and the faces of Princes will marvel at me.\n"
	"Holding my peace they shall expect me, and whilst I speak many words, they shall lay their hands on their mouth.\n"
	"Moreover by her I shall have immortality: and I shall leave an eternal memory to them, that shall be after me.\n"
	"I shall dispose peoples, and nations shall be subject to me.\n"
	"Horrible kings hearing shall fear me: in the multitude I shall seem good, and in battle strong.\n"
	"Entering into my house, I shall rest with her: for her conversation hath no bitterness, nor her company tediousness, but joy and gladness.\n"
	"Thinking these things with myself, and recording in my heart, that immortality is in the kindred of wisdom,\n"
	"and good delectation in her friendship, and in the works of her hands honesty without defect, and wisdom in the disputation of her talk, and glory in the communication of her words: I went about seeking, that I might take her to me.\n"
	"And I was a witty child, and had gotten a good soul.\n"
	"And whereas I was more good, I came to a body undefiled.\n"
	"And as I knew that I could not otherwise be continent, unless God gave it, this very thing also was wisdom, to know whose this gift was: I went to our Lord, and besought him, and said from my whole heart:";