const char* chap726 = "She directed their works in the hands of a holy Prophet.\n"
	"They made a journey through the deserts, that were not inhabited: and in desert places they pitched cottages.\n"
	"They stood against the adversaries, and revenged themselves of the enemies.\n"
	"They thirsted, and invocated thee, and water was given them out of a most high rock, and quenching of their thirst out of the hard stone.\n"
	"For by the things whereby their enemies suffered punishment, for defect of their drink, and therein, when the children of Israel abounded, they did rejoice:\n"
	"by these things, when others lacked the same, it went well with them.\n"
	"For in stead of the fountain of an everlasting river, thou gavest man's blood to the unjust.\n"
	"Who when they were diminished in the destruction of the murdered infants, thou gavest them aboundant water unlooked for:\n"
	"shewing by the thirst, that then was, how thou didst exalt thine, & didst kill their adversaries.\n"
	"For when they were tempted, and indeed with mercy taking discipline, they knew how the impious being judged with wrath did suffer torments.\n"
	"These certes admonishing as a father thou didst prove: but them examining as a hard king thou didst condemn.\n"
	"For the absent and the present were tormented alike.\n"
	"For double tediousness had taken them, and sighing with the memory of good things past.\n"
	"For when they understood by their punishment that it went well with them, they remembered our Lord, marveling at the end of the event.\n"
	"For whom before they derided, being cast forth in that wicked laying out to perish, him they marveled at in the end of the event: not thirsting in like manner to the just.\n"
	"But for senseless cogitations of their iniquities, for that some erring did worship dumb serpents and superfluous beasts, thou didst send upon them a multitude of dumb beasts for revenge:\n"
	"that they might know that by what things a man sinneth, by the same also he is tormented.\n"
	"For thine omnipotent hand, which made the world of invisible matter, was not unable to send upon them a multitude of bears, or fierce lions,\n"
	"or unknown beasts full of anger of a new kind; or breathing the vapour of fires, or casting forth the savour of smoke, or shooting horrible sparks from their eyes:\n"
	"of which not only their hurt was able to destroy them, but also their sight to kill them for fear.\n"
	"Yea and without these with one spirit they might have been slain suffering persecution of their own facts, and dispersed by the spirit of thy power: but thou hast disposed all things in measure, and number, and weight.\n"
	"For, to be of great force rested always in thee only: & who shall resist the power of thine arm?\n"
	"Because as the least weight of the balance, so is the round world before thee, and as a drop of the dew before day, that falleth upon the earth.\n"
	"But thou hast mercy on all, because thou canst do all things, and dissemblest the sins of men for repentance.\n"
	"For thou lovest all things that are, and hatest nothing of those which thou hast made: for thou didst not ordain or make any thing hating it.\n"
	"And how could any thing continue, unless thou wouldest? Or be preserved which was not called of thee?\n"
	"But thou sparest all: because they are thine o Lord, which lovest souls.";