const char* chap731 = "For these things, and by the like to these, they have worthily suffered torments, and were destroyed by a multitude of beasts.\n"
	"For the which torments thou didst well dispose of thy people, to whom thou gavest the desire of their delectation, a new taste, preparing them the quail for meat:\n"
	"that they indeed coveting meat, because of those things which were shewed and sent them, might be turned away even from necessary concupiscence. But they in short time being made needy, tasted a new meat.\n"
	"For it behoved that without excuse destruction should come upon them exercising tyranny: but to these only to shew how their enemies were destroyed.\n"
	"For when the cruel wrath of beasts came upon them, they were destroyed with the bitings of perverse serpents.\n"
	"Howbeit thy wrath endured not for ever, but for chastisement they were troubled a short time, having a sign of salvation for the remembrance of the commandment of thy law.\n"
	"For he that turned to it, was not healed by that which he saw, but by thee the Saviour of all:\n"
	"and in this thou didst shew to our enemies, that thou art he which deliverest from all evil.\n"
	"For the bitings of locusts and flies killed them, and their was found no remedy for their life: because they were worthy to be destroyed by such things.\n"
	"But neither the teeth of venomous dragons overcame thy children: for thy mercy coming healed them.\n"
	"For in memory of thy words they were examined, & were quickly saved, lest falling into deep oblivion they might not use thy help.\n"
	"For neither herb, nor plaster healed them, but thy word, o Lord, which healeth all things.\n"
	"For it is thou, o Lord, that hast power of life and death, and bringest down to the gates of death, and fetchest again:\n"
	"but man certes killeth by malice, and when the spirit is gone forth, it shall not return, neither shall he call back the soul that is received:\n"
	"but it is unpossible to escape thy hand.\n"
	"For the impious denying to know thee, have been scourged by the strength of thine arm, suffering persecution by strange waters, and hail, and rain, and consumed by fire.\n"
	"For that which was marvelous in water, which extinguisheth all things, fire more prevailed: for the world is revenger of the just.\n"
	"For a certain time, the fire was mitigated, that the beasts which were sent to the impious might not be burnt, but that they seeing might know that by God's judgment they suffer punishment.\n"
	"And at a certain time the fire above his power burnt in water on every side, that it might destroy the nation of a wicked land.\n"
	"For the which things thou didst nourish thy people with the meat of Angels, and bread prepared thou gavest them from heaven without labour, having in it all delectation, and the sweetness of all taste.\n"
	"For thy substance did shew thy sweetness which thou hast toward thy children, and serving every man's will, it was turned to that, that every man would.\n"
	"Yea snow and ice sustained the force of fire, and melted not: that they might know that fire burning in hail, and lightning in rain destroyed the fruits of the enemies.\n"
	"And this again, that the just might be nourished, it forgat also his own strength.\n"
	"For the creature serving thee the Creator, is fierce into torment against the unjust: and is made more gentle to do good for them, that trust in thee.\n"
	"For this cause even then being transformed into all things, they served thy grace the nurse of all, at their will that desired thee:\n"
	"that thy children might know, whom thou lovedst o Lord, that not the fruits of nativity do feed men, but thy word preserveth them, that believe in thee.\n"
	"For that which could not be destroyed by fire, forthwith being heated with a little beam of the sun did melt:\n"
	"that it might be known to all men, that we ought to prevent the sun to bless thee, and at the rising of light to adore thee.\n"
	"For the faith of the ungrateful shall melt as winter ice, & shall perish as unprofitable water.";