const char* chap732 = "For thy judgements, o Lord, are great, & thy words inexplicable, for this cause the souls lacking discipline have erred.\n"
	"For whilst the wicked are persuaded that they can rule over the holy nation: fettered with the bands of darkness and long night, shut up under roofs, they have lien fugitives from the everlasting providence.\n"
	"And whilst they think that they lie hid in obscure sins, they were dispersed by the dark covert of oblivion, being horribly afraid and disturbed with exceeding admiration.\n"
	"For neither did the den that contained them, keep them without fear: because the sound coming down troubled them, and sorrowful visions appearing to them, put them in fear.\n"
	"And no force certes of the fire could give them light, neither could the clear flames of the stars lighten that horrible night.\n"
	"But there appeared to them sudden fire full of fear: and being strucken with the fear of that face, which was not seen, they esteemed the things that were seen to be worse.\n"
	"and there were added derisions of the magical art, and contumelious rebuke of the glory of their wisdom.\n"
	"For they which promised that they would expel fears and perturbations from the languishing soul, these with derision languished full of fear.\n"
	"For although none of the monsters disturbed them: being moved with the passing by of beasts, and hissing of serpents, they perished trembling: and denying that they saw the air which by no means any man could avoid.\n"
	"For whereas wickedness is fearful, it giveth testimony of condemnation: for a troubled conscience doth always presume cruel things.\n"
	"For fear is nothing else but a betraying of the aids of cogitation.\n"
	"And whilst inwardly there is less expectation, the greater doth he count the ignorance of that cause which maketh the torment.\n"
	"But they that during the night indeed impotent, and coming upon them from the lowest and highest hell, slept the same sleep,\n"
	"were sometime molested with the fear of monsters, sometime failed by passing away of the soul: for sudden fear and unlooked for came upon them.\n"
	"Moreover if any of them had fallen down, he was kept shut up in prison without iron.\n"
	"For if one were a husbandman, or if a shepherd, or worker of the labours in the field were suddenly taken, he sustained necessity inevitable.\n"
	"For with one chain of darkness they were all tied together. Whether it were the hissing wind, or among the thick boughs of trees the sweet sound of birds, or the force of water running downward exceedingly,\n"
	"or the mighty sound of rocks tumbled headlong, or the running of playing beasts, that were not seen, or the mighty noise of roaring beasts, or an Echo resounding from the highest mountains: they made them swoon for fear.\n"
	"For all the world was illuminated with a clear light, & none was hindered in their works.\n"
	"But over them only was laid an heavy night, the image of darkness, which was to come upon them. They therefore were unto themselves more heavy than the darkness.";