const char* chap735 = "All wisdom is of our Lord God, & hath been always with him, & is before all time.\n"
	"The sand of the sea, & the drops of rain, & the days of the world, who hath numbered? The height of heaven, and breadth of the earth, & profundity of the depth, who hath measured?\n"
	"The wisdom of God that goeth before all things, who hath searched out?\n"
	"Wisdom was created before all things, & the understanding of prudence from everlasting.\n"
	"A fountain of wisdom the word of God on high, and the entrance thereof everlasting commandments.\n"
	"The root of wisdom to whom hath it been revealed, & the subtilties thereof who hath known?\n"
	"The discipline of wisdom to whom hath it been revealed and made manifest, and the multiplication of her entrance who hath understood.\n"
	"There is one most high Creator omnipotent, and mighty King, and to be feared exceedingly, sitting upon his throne & the God of dominion.\n"
	"He created her in the Holy Ghost, and hath seen, and numbered, and measured her.\n"
	"And he hath poured her out upon all his works, and upon all flesh according to his gift, and hath given her to them that fear him.\n"
	"The fear of our Lord is glory, and gloriation, and joy, and a crown of exultation.\n"
	"The fear of our Lord shall delight the heart, and shall give joy, and gladness, and length of days.\n"
	"With him that feareth our Lord it shall be well in the later end, and in the day of his death he shall be blessed.\n"
	"The love of God is honourable wisdom.\n"
	"But they to whom she shall appear in vision, they love her in the vision, and in the agnizing of her great works.\n"
	"The fear of our Lord is the beginning of wisdom, and was created with the faithful in the womb, and goeth with the elect women, and is known with the just & faithful.\n"
	"The fear of our Lord is religiosity of knowledge.\n"
	"Religiosity shall keep and justify the heart, shall give joy and gladness.\n"
	"With him that feareth our Lord it shall be well, and in the days of his consummation he shall be blessed.\n"
	"The fullness of wisdom is to fear God, and fullness is of the fruits thereof.\n"
	"All her house she shall fill with her generations, and the store-houses with her treasures.\n"
	"A crown of wisdom, the fear of our Lord, replenishing peace, and the fruit of salvation:\n"
	"and hath seen, and numbered her: but both are the gifts of God.\n"
	"Wisdom shall distribute knowledge, and understanding of prudence: and exalteth the glory of them that hold it.\n"
	"The root of wisdom is to fear our Lord: for the boughs thereof are of long time.\n"
	"in the treasures of wisdom is understanding, & religiosity of knowledge: but to sinners wisdom is abomination.\n"
	"The fear of our Lord expelleth sin:\n"
	"for he that is without fear, cannot be justified: for the anger of his animosity, is his subversion.\n"
	"Until a time the patient shall sustain, and after shall be rewarded of joyfulness.\n"
	"A good understanding will hide his words until a time, and the lips of many shall shew forth his understanding.\n"
	"In the treasures of wisdom is signification of discipline:\n"
	"But the worship of God is abomination to a sinner.\n"
	"Son, coveting wisdom, keep justice, & God will give her to thee.\n"
	"For the fear of our Lord is wisdom and discipline: and that which well pleaseth him,\n"
	"is faith, and meekness, and he will fill his treasures.\n"
	"Be not incredulous to the fear of our Lord: and come not to him with a double heart.\n"
	"Be not an hypocrite in the sight of men, and be not scandalized in thy lips.\n"
	"Attend to them, lest perhaps thou fall, and bring dishonour to thy soul,\n"
	"and God reveal thy secret, and in the midst of the synagogue cast thee down:\n"
	"because thou camest to our Lord wickedly, & thy heart is full of guile and deceit.";