const char* chap736 = "Son, coming to the service of God, stand in justice, and in fear, & prepare thy soul to tentation.\n"
	"Repress thy heart, & sustain: incline thine ear, & receive the words of understanding, and make no haste in the time of obduction.\n"
	"Sustain the sustentations of God: be joined to God, and sustain, that thy life may increase in the later end.\n"
	"All that shall be applied to thee, receive: and in sorrow sustain, and in thy humiliation have patience:\n"
	"for gold and silver are tried in the fire, but acceptable men in the furnace of humiliation.\n"
	"Believe God, and he will recover thee: and direct thy way, and hope in him. Keep his fear, and grow old therein.\n"
	"Ye that fear our Lord, expect his mercy: & decline not from him, lest ye fall.\n"
	"Ye that fear our Lord, believe him, & your reward shall not be void.\n"
	"Ye that fear our Lord^ hope in him: and mercy shall come to you for your delectation.\n"
	"Ye that fear our Lord, love him, & your hearts shall be illuminated.\n"
	"Children behold the nations of men: and know ye that none hath hoped in our Lord, and hath been confounded.\n"
	"For who hath continued in his commandment, and hath been forsaken? Or who hath invocated him, and he despised him?\n"
	"Because God is pitiful and merciful, and will forgive sins in the day of tribulation: and he is protector to all that seek him in truth.\n"
	"Woe to them of a double heart, & to wicked lips, and to the hands that do evil, and to the sinner that goeth on the earth two ways.\n"
	"Woe to them that be dissolute of heart, which believe not God: and therefore they shall not be protected of him.\n"
	"Woe be to them, that have lost patience, and that have forsaken the right ways, and have declined into perverse ways.\n"
	"And what will they do, when our Lord shall begin to look on them?\n"
	"They that fear our Lord, will not be incredulous to his word: and they that love him, will keep his way.\n"
	"They that fear our Lord, will seek after the things that are well pleasing to him: and they that love him, shall be filled with his law.\n"
	"They that fear our Lord, will prepare their hearts, and in his sight will sanctify their souls.\n"
	"They that fear our Lord, keep his commandments, and will have patience even until his visitation,\n"
	"saying: If we do not penance, we shall fall into the hands of our Lord, and not into the hands of men.\n"
	"For according to his greatness, so also his mercy is with him.";