const char* chap74 = "To Moyses also he said: Go up to the Lord, thou, and Aaron, Nadab and Abiu, and seventy Ancients of Israel, and you shall adore a far off.\n"
	"And Moyses only shall ascend to the Lord, and they shall not approach: neither shall the people ascend with him.\n"
	"Moyses therefore came and told the people all the words of our Lord, & the judgments: and all the people answered with one voice: All the words of our Lord, which he hath spoken, we will do.\n"
	"And Moyses wrote all the words of our Lord: and rising in the morning he builded an Altar at the foot of the mount, & twelve titles according to the twelve tribes of Israel.\n"
	"And he sent young men of the children of Israel, & they offered holocausts, & sacrificed pacific victims to our Lord, calves.\n"
	"Moyses therefore took the half part of the blood, and put it into bowls: and the residue he poured upon the Altar.\n"
	"And taking the volume of the covenant, he read^ the people hearing it: Who said, All things that our Lord hath spoken, we will do, and we will be obedient.\n"
	"And he took the blood, and sprinkled it upon the people, and said: This is the blood of the Covenant which our Lord hath made with you upon all these words.\n"
	"And there went up Moyses and Aaron, Nadab and Abiu, and seventy of the Ancients of Israel:\n"
	"and they saw the God of Israel: and under his feet as it were a work of sapphire stone, and as the heaven, when it is clear.\n"
	"Neither did he set his hand upon those of the children of Israel, that retired far off, and they saw God, and did eat, and drink.\n"
	"And our Lord said to Moyses: Come up to me into the mount, and be there: and I will give thee tables of stone, and the law, and the commandments which I have written: that thou mayst teach them.\n"
	"Moyses rose up, and his Minister Josue: and Moyses ascending into the mount of God,\n"
	"said to the Ancients: Expect here till we return to you, you have Aaron and Hur with you: If any question shall rise, you shall refer it to them.\n"
	"And when Moyses was ascended, a cloud covered the mount,\n"
	"and the glory of our Lord dwelt upon Sinai, covering it with a cloud six days, and the seventh day he called him out of the midst of the darkness.\n"
	"And the form of the glory of our Lord, was as it were fire burning upon the top of the mount, in the sight of the children of Israel.\n"
	"And Moyses entering into the midst of the cloud, ascended into the mount: and he was there forty days and forty nights.";