const char* chap745 = "The wisdom of the humble shall exalt his head, & shall make him sit in the midst of great men.\n"
	"Praise not a man in his beauty, neither despise a man by his look.\n"
	"The bee is small among fowls, and her fruit hath the beginning of sweetness.\n"
	"In apparel do not glory at any time, nor be extolled in the day of thine honour, because the works of the Highest only be marvelous, and his works are glorious, and secret, and not seen.\n"
	"Many tyrants have sit in the throne, and he whom no man would think hath worn the crown.\n"
	"Many mighty men have been greatly oppressed, and the glorious have been delivered into the hands of others.\n"
	"Before thou inquire, blame no man: and when thou hast inquired, chasten justly.\n"
	"Before thou hear, answer not a word, and in the midst of ancients add not to speak.\n"
	"Strive not for that thing, which doth not molest thee: and consist not in the judgement of sinners.\n"
	"Son let not thy doings be in many things: and if thou be rich, thou shalt not be free from sin: for if thou pursue, thou shalt not attain: and if thou run before, thou shalt not escape.\n"
	"There is one that laboureth, and hasteneth, and is a sorrowful impious man, and so much the more he shall not abound.\n"
	"There is a lither man that wanteth recovery, more failing in strength, and abounding in poverty:\n"
	"and the eye of God hath respected him in good, and hath erected him from his low estate, and hath exalted his head: and many have marveled at him, and have honoured God.\n"
	"Good things and evil, life and death, poverty and honesty are of God.\n"
	"Wisdom and discipline, and the knowledge of the law are with God. Love, and the ways of good things are with him.\n"
	"Error & darkness are created with sinners: and they that rejoice in evils, wax old in evil.\n"
	"The gift of God is permanent to the just, and his prospering shall have success for ever.\n"
	"There is that is enriched by doing sparingly, and this is the portion of his reward,\n"
	"in that he saith: I have found me rest, and now I will eat of my goods alone:\n"
	"and he knoweth not that time passeth, & death approacheth, and he must leave all to others, and shall die.\n"
	"Stand in thy covenant, and commune therein, and grow old in the work of thy commandments.\n"
	"Abide not in the works of sinners. But trust in God, and tarry in thy place.\n"
	"For it is easy in the eyes of God suddenly to enrich the poor man.\n"
	"The blessing of God hasteneth to the reward of the just, and in a swift hour his prospering fructifieth.\n"
	"Say not: What need I, and what good shall I have by this?\n"
	"Say not: I am sufficient for myself: and what shall I be made worse by this?\n"
	"In the day of good things be not unmindful of evils: and in the day of evils be not unmindful of good things:\n"
	"because it is easy before God in the day of death to reward every one according to his ways.\n"
	"The malice of an hour maketh oblivion of great voluptuousness, and in the end of a man in the disclosing of his works.\n"
	"Before death praise no man, because a man is known in his children.\n"
	"Bring not every man into thine house: for there be many trains of the deceitful man.\n"
	"For as the stomachs belch of stinking breaths, and as the partridge is brought in to the cage, and as the doe into the snare: so also the heart of the proud, and as a watch-man that seeth the fall of his neighbour.\n"
	"For turning good things into evil he lieth in wait, and on the elect he will lay a blot.\n"
	"For of one spark fire is increased, and of a deceitful man blood is increased: and a sinful man lieth in wait for blood.\n"
	"Take heed of thyself of the pestiferous person, for he forgeth evils: lest perhaps he bring upon thee derision for ever.\n"
	"Admit a stranger to thee, and he shall overthrow thee in an hurlwind, & shall make thee an alien from thine own.";