const char* chap751 = "God created man of the earth, and after his own image he made him.\n"
	"And again he turned him into it, and conformable to himself clothed him with strength.\n"
	"He gave him a number of days and time, and gave him power of those things that are upon the earth.\n"
	"He put his fear over all flesh, and he had dominion of beasts and fowls.\n"
	"He created of him an helper like to himself: he gave them counsel, and tongue, and eyes, & ears, and heart to devise: and he filled them with the discipline of understanding.\n"
	"He created in them the knowledge of the spirit, he filled their heart with understanding, and evil and good he shewed them.\n"
	"He set his eye upon their hearts to shew them the great things of his works:\n"
	"that they might praise the name of sanctification: & glory in his marvelous works, that they might declare the glorious things of his works.\n"
	"He added discipline unto them, and made them inherit the law of life.\n"
	"He made an everlasting testament with them, & he shewed them justice and his judgements.\n"
	"And their eye saw the glorious things of his honour, & their ears heard the honour of his voice, and he said to them: Beware of every unjust thing.\n"
	"And he gave them commandment every one concerning his neighbour.\n"
	"Their ways are before him always, they are not hid from his eyes.\n"
	"Over every nation he appointed a ruler.\n"
	"And Israel was made the manifest portion of God.\n"
	"And all their works as the sun in the sight of God: and his eyes without intermission looking on their ways.\n"
	"The testaments were not hid by their iniquities and all their iniquities are in the sight of God.\n"
	"The alms of a man is as a seal with him, and shall preserve the grace of a man as the apple of the eye:\n"
	"And afterward he shall arise, and shall render them reward, to every one upon their head, and shall turn into the inner parts of the earth.\n"
	"But to the penitent he hath given the way of justice, and he hath confirmed them that fail to sustain, and hath appointed to them the lot of truth.\n"
	"Turn to our Lord, and forsake thy sins:\n"
	"pray before the face of our Lord, and diminish offences.\n"
	"Return to our Lord, & turn away from thine injustice, and hate exceedingly abomination:\n"
	"and know the justices and judgments of God, and stand in the lot of thy purpose, and of prayer of the most high God.\n"
	"Go into the parts of the holy world, with the living, and them that give praise to God.\n"
	"Tarry not in the error of the impious, before death confess. From the death as nothing, confession perisheth.\n"
	"Thou shalt confess living, alive and in health thou shalt confess, and shalt praise God, and shalt glory in his mercies.\n"
	"How great is the mercy of our Lord, and his propitiation to them that turn to him?\n"
	"For all things cannot be in men, because the son of man is not immortal, and they have delighted in the vanity of malice.\n"
	"What is brighter than the sun? & it shall fail. Or what more wicked than that which flesh and blood hath invented? And this shall be reproved.\n"
	"He beholdeth the power of the height of heaven: and all men be earth and ashes.";