const char* chap753 = "A workman that is a drunkard shall not be rich: and he that contemneth small things, shall fall by little and little.\n"
	"Wine and women make wisemen to apostatate, and shall reprove the prudent:\n"
	"and he that joineth himself to harlots, shall be naught. Rottenness and worms shall inherit him, and he shall be lifted up for a greater example, and his life shall be taken out of the number.\n"
	"He that giveth credit quickly, is light of heart, and shall be lessened: and he shall moreover be counted one that sinneth against his own soul.\n"
	"He that rejoiceth in iniquity, shall be reprehended, and he that hateth chastisement shall be diminished of life: and he that hateth babbling, extinguisheth malice.\n"
	"He that sinneth against his own soul, shall repent: and he that is delighted in naughtiness, shall be reprehended.\n"
	"Iterate not a wicked and hard word, and thou shalt not be lessened.\n"
	"To friend and foe tell not thy mind: and if thou have sin disclose it not.\n"
	"For he will hear thee, and will watch thee, and as it were defending the sin he will hate thee, and so will he be present with thee always.\n"
	"Hast thou heard a word against thy neighbour? Let it die together in thee, trusting that it will not burst thee.\n"
	"At the presence of a word the fool travaileth, as the groaning of the childbirth of an infant.\n"
	"An arrow stickt in the thigh of flesh: so is a word in the heart of a fool.\n"
	"Rebuke a friend, lest perhaps he hath not understood, and say: I did it not: or if he did it, that he do it not again.\n"
	"Rebuke thy neighbour, lest perhaps he said it not: and if he said it, lest perhaps he iterate it.\n"
	"Rebuke thy friend: for there is often a fault committed.\n"
	"And believe not every word. There is that offendeth with the tongue, but not from his heart.\n"
	"For who is there that hath not offended in his tongue? Rebuke thy neighbour before thou threaten.\n"
	"And give place to the fear of the Highest: because the fear of God is all wisdom, and to fear God is in it, & the disposition of the law is in all wisdom.\n"
	"And the discipline of wickedness is not wisdom: and the cogitation of sinners is not prudence.\n"
	"There is wickedness, and in it execration: and there is a fool that hath less wisdom.\n"
	"Better is a man that hath less wisdom and lacketh understanding, in fear, than he that aboundeth in understanding and transgresseth the law of the Highest.\n"
	"There is an assured subtility, & the same wicked.\n"
	"And there is that uttereth an exact word telling the truth. There is that wickedly humbleth himself, and his inner parts be full of deceit:\n"
	"and there is a just man that submitteth himself overmuch of great humility: and there is a just one that boweth his face, and feigneth himself not to see that which is unknown:\n"
	"and if he be forbidden to sin for imbecility of power, if he shall find a time to do evil, he will do evil.\n"
	"A man is known by the sight, and a wiseman is known by the shew of his face.\n"
	"The clothing of the body, and the laughing of the teeth, and the going of the man tell of him.\n"
	"There is a lying chastisement in the anger of a contumelious person: and there is a judgement, that is not allowed to be good: and there is that holdeth his peace, and he is wise.";