const char* chap756 = "The sluggard is stoned with a dirty stone, & all men will speak of his disgrace.\n"
	"The sluggard is stoned with the dung of oxen: and every one that shall touch him, will shake his hands.\n"
	"The confusion of the father is of a son without discipline: and the daughter shall be made of less account.\n"
	"A wise daughter is an inheritance to her husband: for she that confoundeth, is made a contumely to her father.\n"
	"She that is bold shameth father and husband, and shall not be inferior to the impious: but of them both she shall be dishonoured.\n"
	"Music in mourning is a tale out of time: scourges and doctrine are at all time wisdom.\n"
	"He that teacheth a fool, is as he that glueth together a pot-sherd.\n"
	"He that telleth a word to him that heareth not, is as he that raiseth up a man sleeping out of an heavy sleep.\n"
	"He speaketh with him that sleepeth, which uttereth wisdom to a fool: and in the end of the narration he saith: Who is this?\n"
	"Weep upon the dead, for his light hath failed: and weep upon a fool, for he faileth in understanding.\n"
	"Weep a little upon the dead, because he is at rest.\n"
	"For the wicked life of the very wicked, above the death of a fool.\n"
	"The mourning of the dead is seven days: but of a fool and of the impious, all the days of their life.\n"
	"Speak not much with a fool, and go not with the unwise.\n"
	"Keep thyself from him, that thou have no molestation, and thou shalt not be defiled with his sin.\n"
	"Turn aside from him, and thou shalt find rest, and shall not be wearied with his folly.\n"
	"What shall be heavier than lead? And what other name hath it but fool?\n"
	"It is easier to bear sand and salt, and a mass of iron, than an unwise man, and a fool, and impious.\n"
	"A frame of wood bound together in the foundation of a building, shall not be dissolved: so also the heart confirmed in the cogitation of counsel.\n"
	"The cogitation of the wise at all time, yea by fear shall not be depraved.\n"
	"As stakes in high places, and plasterings laid without cost, shall not abide against the face of the wind:\n"
	"so also a fearful heart in the cogitation of a fool shall not resist against the violence of fear.\n"
	"As a trembling heart in the cogitation of a fool, all time will not fear, so also he that continueth always in the precepts of God.\n"
	"He that pricketh the eye, bringeth forth tears: and he that pricketh the heart, bringeth forth feeling.\n"
	"He that casteth a stone at fowls, and shall throw them down: so he that speaketh reproachfully to his friend, dissolveth friendship.\n"
	"Although thou drawest a sword at a friend, despair not: for there is returning to a friend.\n"
	"If thou open a sad mouth, fear not: for there is agreement: except taunt, and reproach, and pride, and revealing of secret, and a treacherous wound: in all these things a friend will fly away.\n"
	"Possess fidelity with a friend in his poverty, that in his goods also thou mayst rejoice.\n"
	"In the time of his tribulation continue faithful to him, that in his inheritance also thou mayst be heir with him.\n"
	"Before the fire the vapour of the chimney, and the smoke of the fire riseth on high: so also before blood evil words, and contumelies, & threats.\n"
	"I will not be ashamed to salute a friend, from his face I will not hide myself: and if there chance evils to me by him, I will bear it.\n"
	"Every one that shall hear, will beware of him.\n"
	"Who will give a guard to my mouth, and a sure seal upon my lips, that I fall not by them, and my tongue destroy me?";