const char* chap757 = "O Lord father, and dominatour of my life, leave me not in their counsel: nor suffer me to fall in them.\n"
	"Who layeth on stripes in my cogitation, and in my heart the doctrine of wisdom, and in their ignorances they spare me not, and their offences appear not,\n"
	"and my ignorances increase not, and my offences be multiplied, and my sins abound, and I fall in the sight of mine adversaries, & mine enemy rejoice?\n"
	"O Lord father, and God of my life, leave me not in their cogitation.\n"
	"Haughtiness of mine eyes give me not, and all desire turn away from me.\n"
	"Take from me the concupiscences of the belly, and let not the concupiscences of copulation take hold of me, and give me not over to a shameless and foolish mind.\n"
	"O children hear the doctrine of the mouth: and he that will keep it, shall not perish by his lips, nor be scandalized in most wicked works.\n"
	"A sinner is taught in his vanity, and the proud and the evil speaker shall be scandalized in them.\n"
	"Let not thy mouth be accustomed to swearing: for there be many falls in it.\n"
	"But let not the naming of God be usual in thy mouth, and meddle not with the names of Saints, because thou shalt not scape free from them.\n"
	"For as a servant daily examined, lacketh not the mark thereof: so every one that sweareth, and nameth, shall not be wholly purged from sin.\n"
	"A man that sweareth much shall be filled with iniquity, and plague shall not depart from his house.\n"
	"And if he frustrate it, his sin shall be upon him: and if he dissemble, he offendeth double:\n"
	"and if he swear in vain, he shall not be justified: for his house shall be filled with retribution.\n"
	"There is another contrary speech, also to death, be it not found in the inheritance of Jacob.\n"
	"For of the merciful all those things shall be taken away, and they will not wallow in sins.\n"
	"Let not thy mouth be accustomed to unuttered speech: for there is in it a word of sin.\n"
	"Remember thy father and thy mother, for thou sittest in the midst of great men:\n"
	"lest perhaps God forget thee in their sight, & being besotted with thy daily custom, thou suffer reproach, & hadst better not have been born, and curse the day of thy nativity.\n"
	"A man accustomed to the words of reproach, will not be instructed in all his days.\n"
	"Two sorts abound in sins, and the third bringeth wrath and perdition.\n"
	"An hot soul as a burning fire will not be quenched, till it swallow somewhat.\n"
	"and a wicked man in the mouth of his flesh will not cease till he kindle a fire.\n"
	"To a man that is a fornicator all bread is sweet, he will not be weary transgressing unto the end.\n"
	"Every man that passeth beyond his own bed, contemning against his own soul, and saying: Who seeth me?\n"
	"Darkness compasseth me, and the walls cover me, and no man beholdeth me: whom do I fear? The Highest will not be mindful of my sins.\n"
	"And he understandeth not that his eye seeth all things, for that such fear of man expelleth from him the fear of God, & the eyes of men fearing him:\n"
	"and he knoweth not that the eyes of our Lord are much more brighter than the sun, beholding round about all the ways of man, and the bottom of the depth, and the hearts of men, looking into the hidden parts.\n"
	"For all things were known unto our Lord God, before they were created: so also after it is perfected he beholdeth all things.\n"
	"Revenge shall be taken on this man in the streets of the city, and as an horse-colt he shall be chased: and where he expected not, he shall be apprehended.\n"
	"And he shall be in dishonour with all men, for that he understood not the fear of our Lord.\n"
	"So every woman also that forsaketh her husband, & getteth inheritance by marriage of another.\n"
	"For first she hath been unfaithful in the law of the Highest: and secondly she hath sinned against her husband: thirdly she hath fornicated in adultery, and hath gotten her children of another man.\n"
	"This woman shall be brought into the Church, and upon her children there shall be examination.\n"
	"Her children shall not take root, & her boughs shall not yield fruit.\n"
	"She shall leave her memory to be cursed, and her dishonour shall not be wiped out.\n"
	"And they that are left shall know, that nothing is better than the fear of God: and nothing sweeter, than to have regard to the commandments of our Lord.\n"
	"It is great glory to follow our Lord: for length of days shall be taken of him.";