const char* chap758 = "Wisdom shall praise her soul, & shall be honoured in God, and shall glory in the midst of her people,\n"
	"and shall open her mouth in the churches of the Highest and shall glory in the sight of his power,\n"
	"and in the midst of her people she shall be exalted, and in the holy assembly she shall be admired,\n"
	"and in the multitude of the elect she shall have praise, and among the blessed she shall be blessed, saying:\n"
	"I came forth from the mouth of the Highest, the first begotten before all creatures.\n"
	"I made that in the heavens, there should rise light that faileth not, and as a cloud I covered all the earth.\n"
	"I dwelt in the highest places, and my throne is in the pillar of a cloud.\n"
	"I alone have gone round about the compass of heaven, and have penetrated into the bottom of the depth, and have walked in the waves of the sea,\n"
	"and stood in all the earth: and in all people.\n"
	"and in every nation I have had the primacy:\n"
	"and I have by strength trodden down the hearts of all the excellent, and the base; and in all these things I sought rest, & I shall abide in the inheritance of our Lord.\n"
	"Then the creator of all commanded, and said to me: & he that created me, rested in my tabernacle,\n"
	"and he said to me: Inhabit in Jacob, and inherit in Israel, and take root in mine elect.\n"
	"From the beginning and before the worlds was I created, and unto the world to come I shall not cease, and in the holy habitation I have ministered before him.\n"
	"And so in Sion was I established, and in the sanctified city likewise I rested, and my power was in Jerusalem\n"
	"And I took root in an honourable people, and in the portion of my God his inheritance, and my abiding is in the full assembly of saints.\n"
	"I am exalted as a cedar in Libanus, and as a cypress tree in mount Sion.\n"
	"As a palm tree in Cades am I exalted, and as a rose plant in Jericho:\n"
	"As a fair olive tree in the fields, and as a plane tree by the water in the streets am I exalted.\n"
	"I gave an odour as cinnamon, & aromatical balm: as chosen myrrh have I given the sweetness of odour:\n"
	"and as storax, and galbanum, and onyx, and aloes, and as Libanus not cut, have I perfumed mine habitation, and mine odour is a balm not mingled.\n"
	"I have spread out my boughs as the terebinth, and my boughs are of honour & grace.\n"
	"I as a vine have fructified sweetness of odour: and my flowers are fruit of honour and honesty.\n"
	"I am the mother of beautiful love, and of fear, and of knowledge, and of holy hope.\n"
	"In me is all grace of way and truth, in me all hope of life and virtue.\n"
	"Pass to me all ye that desire me, and be filled of my generations.\n"
	"For my spirit is sweet above honey, and mine inheritance above honey and the honey comb.\n"
	"My memory is unto generations of worlds.\n"
	"They that eat me, shall yet hunger: and they that drink me, shall yet thirst.\n"
	"He that heareth me, shall not be confounded: and they that work in me, shall not sin.\n"
	"They that explicate me, shall have life everlasting.\n"
	"All these things are the book of life, and the testament of the Highest, & the knowledge of truth.\n"
	"Moyses commanded a law in the precepts of justices, and an inheritance to the house of Jacob, and the promises to Israel.\n"
	"He appointed to David his servant for to raise up a king of him most strong, and sitting in the throne of honour for ever.\n"
	"Who filleth wisdom as Phison, and as Tigris in the days of new fruits.\n"
	"Who replenisheth understanding as Euphrates, who multiplieth it as Jordan in the time of harvest.\n"
	"Who sendeth discipline as the light, and assisting as Gehon in the day of vintage.\n"
	"Who first hath perfect knowledge of it, & a weaker shall not search it out.\n"
	"For her cogitation shall abound above the sea, and her counsels above the great depth.\n"
	"I wisdom have poured out rivers.\n"
	"I as a sluse of a mighty water out of the river, I as the river Dioryx, & as a water conduit I came out of paradise.\n"
	"I said: I will water my garden of plants, and will inebriate the fruit of my meadow.\n"
	"And behold my sluse was made aboundant, and my river came near to a sea.\n"
	"Because I illuminated doctrine to all as the morning light, & I will declare it far.\n"
	"I will penetrate all the inferior parts of the earth, and will behold all that sleep, and will illuminate all that hope in our Lord.\n"
	"I will yet pour out doctrine as prophecy, and will leave it to them that seek wisdom, and will not cease unto their progenies even to the holy age.\n"
	"See ye that I have not laboured for myself only, but for all that seek out the truth.";