const char* chap759 = "In three things my spirit is pleased, which are approved before God, and men:\n"
	"The concord of brethren, and the love of neighbours, and man and wife well agreeing together.\n"
	"Three sorts my soul hateth, and I am greatly grieved at their life:\n"
	"A poor man proud: & a rich man a liar: an old man a fool, and doting.\n"
	"The things that thou hast not gathered in thy youth, how shalt thou find them in thy old age?\n"
	"How beautiful is judgement for a gray head, and for ancients to know counsel!\n"
	"How beautiful is wisdom for the aged, & understanding glorious, and counsel!\n"
	"Much cunning is the crown of old men, and the fear of God is their glory.\n"
	"Nine things not to be imagined of the heart have I magnified, and the tenth I will tell unto men with my tongue:\n"
	"A man that hath joy in his children; living and seeing the subversion of his enemies.\n"
	"Blessed is he that dwelleth with a wise woman; & that hath not offended with his tongue; and that hath not served such as are unworthy of him.\n"
	"Blessed is he that findeth a true friend; and that declareth justice to an ear that heareth.\n"
	"How great is he, that findeth wisdom and knowledge; but he is not above him that feareth our Lord.\n"
	"The fear of God hath set it-self above all things:\n"
	"blessed is the man, to whom is given to have the fear of God: he that holdeth it, to whom shall he be resembled?\n"
	"The fear of God is the beginning of his love: and the beginning of faith is to be fast joined unto it.\n"
	"The heaviness of the heart is all plague: & all malice, the wickedness of a woman.\n"
	"And he will see all plague, and not the plague of the heart:\n"
	"& all wickedness, & not the wickedness of a woman:\n"
	"and all obduction and not the obduction of them that hate him:\n"
	"and all revenge, and not the revenge of the enemies.\n"
	"There is no head worse than the head of a serpent:\n"
	"and there is no anger above the anger of a woman. It shall be more pleasant to abide with a lion and dragon, than to dwell with a wicked woman.\n"
	"The wickedness of a woman changeth her face: and darkeneth her countenance as a bear: and will shew it as a sack. In the midst of her neighbours,\n"
	"her husband groaned, and hearing he sighed a little.\n"
	"All malice is short to the malice of a woman, the lot of sinners fall upon her.\n"
	"As the going up a gravelly way in the feet of the aged, so a woman full of tongue to a quiet man.\n"
	"Look not upon a woman's beauty, and desire not a woman for beauty.\n"
	"A woman's anger, and impudency, and confusion is great.\n"
	"A woman if she have superiority, is contrary to her husband.\n"
	"An humbled heart, and heavy countenance, and plague of heart, is a wicked woman.\n"
	"Feeble hands, and disjointed knees, a woman that doth not make her husband happy.\n"
	"From woman came the beginning of sin, and by her we do all die.\n"
	"Give not issue to thy water, no not a little: nor to a wicked woman leave to go forth.\n"
	"If she walk not at thine hand, she will confound thee in the sight of thine enemies.\n"
	"Cut her off from thy flesh, lest she always abuse thee.";