const char* chap76 = "And the tabernacle thou shalt make thus: Ten curtains shalt thou make of twisted silk, and hyacinth, and purple, and scarlet twice dyed, varied with embroidered work.\n"
	"The length of one curtain shall have twenty eight cubits: the breadth shall be of four cubits. All the curtains shall be of one measure.\n"
	"Five curtains shall be joined one to another, & the other five shall hang together with the connection.\n"
	"Loops of hyacinth thou shalt make in the sides & tops of the curtains, that they may be coupled one to another.\n"
	"Fifty loops shall every curtain have on both sides, so set on, that one loop may be against another loop, and one may be fitted to the other.\n"
	"Thou shalt make also fifty circles of gold wherewith the veils of the curtains are to be joined, that it may be made one tabernacle.\n"
	"Thou shalt make also eleven curtains of hair, to cover the top of the tabernacle.\n"
	"The length of one hair curtain shall have thirty cubits: and the breadth, four: the measure of all the curtains shall be equal.\n"
	"Of the which, five thou shalt join apart, and the six thou shalt couple one to another, so that the sixth curtain in the front of the roof thou shalt double.\n"
	"Thou shalt make also fifty loops in the edge of one curtain, that it may be joined with the other: and fifty loops in the edge of the other curtains that it may be coupled with his fellow.\n"
	"Thou shalt make also fifty buckles of brass, wherewith the loops may be joined, that of all there may be made one covering.\n"
	"And that which shall remain in the curtains, that are prepared for the roof, to wit, one curtain that is overplus, with the half thereof thou shalt cover the backside of the tabernacle.\n"
	"And there shall hang down a cubit on the one side, and another on the other side, which is the overplus in the length of the curtains, fencing both sides of the tabernacle.\n"
	"Thou shalt make also another cover to the roof^ of the ram's skins dyed red: & over that again another cover of janthine skins.\n"
	"Thou shalt make also the boards of the tabernacle standing upright of the wood setim,\n"
	"of the which let every one have ten cubits in length, and in breadth one and a half a-piece.\n"
	"In the sides of the board, shall be made two mortises, whereby one board may be joined to another board: and after this manner shall all the boards be prepared.\n"
	"Of the which twenty shall be in the south side that tendeth southward.\n"
	"For the which thou shalt cast forty feet of silver, that there may two feet be put under every board at the two corners.\n"
	"In the second side also of the tabernacle that looketh to the North, there shall be twenty boards,\n"
	"having forty feet of silver, two feet shall be put under every board.\n"
	"But on the west quarter of the tabernacle thou shalt make six boards,\n"
	"and again other two which shall be erected in the corners at the back of the tabernacle.\n"
	"And they shall be joined together from beneath unto the top, & one jointure shall hold them all. The like jointure shall be kept for the two boards also that are to be put in the corners.\n"
	"And they shall be in all eight boards, their silver feet sixteen, two feet accounted for every board.\n"
	"Thou shalt make also five bars of the wood setim, to hold together the boards on the one side of the tabernacle,\n"
	"and five others on the other side, & as many at the west side:\n"
	"which shall be put along by the midst of the boards from one end to the other.\n"
	"The boards also themselves thou shalt plate with gold, & shalt cast rings of gold to be set upon them, through which the bars may hold together the boardwork: the which thou shalt cover with plates of gold.\n"
	"And thou shalt erect the tabernacle according to the pattern that was shewed thee in the Mount.\n"
	"Thou shalt make also a veil of hyacinth, and purple, and scarlet twice dyed, and twisted silk, wrought with embroidered work & goodly variety:\n"
	"which thou shalt hang before four pillars of the wood setim, the which themselves also shall be plated with gold, & shall have four heads of gold, but feet of silver.\n"
	"And the veil shall be hanged on with rings, within the which thou shalt put the ark of testimony, with the which also the Sanctuary, and the Sanctuaries of the Sanctuary, shall be divided.\n"
	"Thou shalt set also the Propitiatory upon the ark of testimony in the Sancta sanctorum:\n"
	"and the table without the veil: and over-against the table the candlestick in the south side of the tabernacle: for the table shall stand in the north side.\n"
	"Thou shalt make also a hanging in the entering of the tabernacle of hyacinth, and purple, and scarlet twice dyed, and twisted silk with embroidered work.\n"
	"And five pillars of the wood setim thou shalt plate with gold, before the which the hanging shall be drawn: whose heads shall be of gold, and feet of brass.";