const char* chap763 = "He that lendeth to his neighbour, doth mercy: and he that prevaileth with hand, keepeth the commandments.\n"
	"Lend to thy neighbour in the time of his necessity, and again repay thy neighbour in his time.\n"
	"Confirm thy word, and do faithfully with him: & thou shalt find at all time, that which is necessary for thee.\n"
	"Many have esteemed a thing lent as a thing found, and have given molestation to them that did help them.\n"
	"Till they receive, they kiss the hands of the lender, and in promises they humble their voice:\n"
	"and in the time of repaying they will ask a time, and will speak words of tediousness and murmurings, and will make the time an excuse:\n"
	"and if he be able to pay, he will resist, he will pay scarce half of the whole, and will account it as a thing found:\n"
	"but if not, he will defraud him of his money, and possess him an enemy without cause:\n"
	"and will repay him reproaches and curses, and for honour and benefit will repay him contumely.\n"
	"Many have not lent, not because of wickedness, but they were afraid to be defrauded without cause.\n"
	"But yet upon the humble be stronger of mind, & for alms defer him not.\n"
	"Because of the commandment receive the poor: and because of his poverty, send him not away empty.\n"
	"Lose money for thy brother and thy friend: and hide it not under a stone unto perdition.\n"
	"Put thy treasure in the precepts of the Highest, & it shall profit thee more than gold.\n"
	"Shut up alms in the heart of the poor, and the same shall obtain for thee against all evil.\n"
	"The alms a man giveth is as a purse with him: it will conserve his grace as the ball of the eye.\n"
	"And furthermore will raise up and render reward to every one upon their heads.\n"
	"Above the shield of the mighty, & above the spear, it shall fight against thine enemy.\n"
	"A good man becometh surety for his neighbour: and he that hath lost shame, will leave him to himself.\n"
	"Forget not the kindness of a surety: for he hath given his life for thee.\n"
	"The sinner and unclean person flyeth from his surety.\n"
	"A sinner counteth the goods of his surety to himself: and unthankful in mind, will forsake him that delivered him.\n"
	"A man is surety for his neighbour: and when he hath lost shame, he shall be forsaken of him.\n"
	"Naughty suretyship hath undone many that were in good case, and hath tossed them as a wave of the sea.\n"
	"Whurling round about, it hath made mighty men to remove, and they have wandered in strange nations.\n"
	"A sinner that transgresseth the commandment of our Lord, shall fall into naughty suretyship: and he that endeavoureth to do many things, shall fall into judgement.\n"
	"Recover thy neighbour according to thy power, and take heed to thyself that thou fall not.\n"
	"The beginning of man's life water & bread, and garment, and house covering his turpitude.\n"
	"Better is the poor man's fare under a roof of boards, than sumptuous cheer in a strange place without a house.\n"
	"Let the least thing please thee in stead of a great, and thou shalt not hear the reproach of peregrination.\n"
	"It is a naughty life to change lodging from house to house: and where he shall lodge, he shall not deal boldly, nor open his mouth.\n"
	"He shall lodge, and feed, and make the unthankful drink, and beside these things he shall hear bitter words.\n"
	"Pass thou stranger & furnish the table, & with the things thou hast in thy hand, feed the rest.\n"
	"Depart from the presence of the honour of my friends: for the necessity of my house my brother is to be lodged with me.\n"
	"These things be grievous to a man that hath understanding: rebuke for the house, and the reproach of the lender.";