const char* chap764 = "He that loveth his son, doth accustom him to stripes, that he may rejoice in his later end, and not grope after the doors of his neighbours.\n"
	"He that teacheth his son, shall be praised in him, & in the midst of them of his household he shall glory in him.\n"
	"He that teacheth his son, doth cast the enemy into emulation, and in the midst of his friends he shall glory in him.\n"
	"His father is dead, & he is as it were not dead: for he hath left behind him the like to himself.\n"
	"In his life he saw and rejoiced in him: in his death he was not made sorry, neither was he confounded before the enemies.\n"
	"For he left a defender of his house against the enemies, & one that should render thank to his friends.\n"
	"For the souls of his sons he will bind up his wounds, & at every voice his bowels shall be troubled.\n"
	"An untamed horse becometh stubborn, and a dissolute child will become heady.\n"
	"Pamper thy son, and he will make thee afraid: play with him, and he will make thee sorrowful.\n"
	"Laugh not with him, lest thou be sorry, and at the last thy teeth shall be on edge.\n"
	"Give him not power in his youth, and contemn not his cogitations.\n"
	"Curb his neck in youth, and knock his sides whilst he is a child, lest perhaps he be hardened, and believe thee not, and he shall be sorrow of mind to thee.\n"
	"Teach thy son, and work in him, that thou offend not in his dishonesty.\n"
	"Better is a poor man whole and strong of force, than a rich man weak and scourged with misery.\n"
	"The health of the soul in holiness of justice, is better than all gold and silver: and a sound body, than infinite revenues.\n"
	"There is no riches above the riches of the health of the body: and there is no delight above the joy of the heart.\n"
	"Better is death than a bitter life: and everlasting rest, than continual sickness.\n"
	"Good things hid in a mouth that is shut, are as messes of meats set about a grave.\n"
	"What shall sacrifice profit an idol? For neither shall he eat, nor smell:\n"
	"so he that is chased away of our Lord, beareth the rewards of iniquity:\n"
	"seeing with his eyes, & groaning, as an eunuch embracing a virgin and sighing.\n"
	"Give not heaviness to thy soul, & afflict not thyself in thy counsel.\n"
	"Joyfulness of the heart, this is the life of a man, and a treasure without defect of holiness: and the joy of a man is long life.\n"
	"Have mercy on thine own soul, pleasing God, and refrain: and comfort thy heart in his holiness: and expel sorrow far from thee.\n"
	"For sorrow hath killed many, and there is no profit in it.\n"
	"Envy and anger diminish the days, and thought will bring old age before the time.\n"
	"A magnifical heart is good in banquets: for his banquets are made diligently.";