const char* chap766 = "Have they made thee Ruler? Be not extolled: be among them as one of them.\n"
	"Have care of them, and so sit thou still, and all thy care being dispatched, repose.\n"
	"That thou mayst rejoice for their sakes, & receive a crown as an ornament of grace, and obtain the dignity of the contribution.\n"
	"Speak thou that art elder: for it becometh thee,\n"
	"the first word to him that loveth with knowledge, & hinder not music.\n"
	"Where there is no hearing, pour not out speech, and extol not thyself out of time in thy wisdom.\n"
	"A little pearl of the carbuncle in an ornament of gold, and the comparison of musicians in a banquet of wine.\n"
	"As a signet of the emerald is in the working of gold: so the melody of music is joyful and moderate wine.\n"
	"Hear holding thy peace, & for thy reverence good grace shall come to thee.\n"
	"Young man speak in thine own cause scarcely.\n"
	"If thou be asked twice, let thine answer have an head.\n"
	"In many things be as it were ignorant, and hear holding thy peace and withal asking.\n"
	"In the midst of great men presume not: & where ancients are, speak not much.\n"
	"before hail there shall go lightning: & grace shall go before shamefastness, & for thy reverence good grace shall come to thee.\n"
	"And at the hour of rising slack not thyself: but run before first into thy house, and there withdraw thyself, and there play,\n"
	"and do thy conceits, and not in sins and proud word.\n"
	"And above all these things bless our Lord that made thee, & that doth replenish thee with all his goods.\n"
	"He that feareth our Lord, shall receive his doctrine: and they that will watch after him, shall find blessing.\n"
	"He that seeketh the law shall be replenished with it: and he that doth deceitfully, shall be scandalized by it.\n"
	"They that fear our Lord, shall find just judgement, and shall kindle justices as light.\n"
	"A sinful man will fly reprehension, and according to his will, will find excuse.\n"
	"A man of counsel will not destroy understanding, an alien and proud man will not dread fear:\n"
	"Yea after he hath done with fear without counsel, he shall be controlled even by his own pursuits.\n"
	"Son do nothing without counsel, and after the fact thou shalt not repent.\n"
	"Go not in the way of ruin, and thou shalt not stumble at stones: commit not thyself to a laborious way, lest thou set a scandal to thy soul.\n"
	"And beware of thy children, and take heed of them of thy household.\n"
	"In all thy work believe thy soul by faith: for this is the keeping of the commandments.\n"
	"He that believeth God attendeth to the commandments: and he that trusteth in him, shall not be lessened.";