const char* chap767 = "To him that feareth our Lord evils shall not happen, but in tentation God will keep him, and deliver him from evils.\n"
	"A wise man hateth not the commandments and justices, and he shall not be shaken as a ship in a storm.\n"
	"A man of understanding believeth the law of God, and the law is sure to him.\n"
	"He that repeateth an interrogation, shall better prepare his answer, and so shall be heard, and shall keep discipline.\n"
	"The heart of a fool is a wheel of a cart: & his cogitation as a turning axletree.\n"
	"A stallion horse neigheth under every one that sitteth upon him, so a friend that is a scorner.\n"
	"Why doth one day excel another, and one light another, and one year another year of the sun?\n"
	"By the knowledge of our Lord they were separated, the sun being made, and keeping the precept.\n"
	"And he changed times, and the festival days thereof, and in the same they celebrated the festival days at an hour.\n"
	"Of them God exalted and magnified, and of them he put into the number of days. And all men are of the ground, and of the earth, from whence Adam was created.\n"
	"In the multitude of the discipline of our Lord he separated them, and changed their ways.\n"
	"Of them he blessed, and exalted: and of them he sanctified, and applied to himself: and of them he cursed and humbled, and converted them from their separation.\n"
	"As potter's clay is in his hand, to fashion and dispose it.\n"
	"All his ways according to his disposition: so man in the hand of him, and he will render to him according to his judgement.\n"
	"Against evil is good, and against death life: so also against a just man a sinner. And so look upon all the works of the Highest. Two against two, and one against one.\n"
	"And I awaked last, and as he that gathereth berries after the grape gatherers.\n"
	"In the blessing of God I also have hoped: and as he that gathereth grapes, have I filled the wine press.\n"
	"See that I have not laboured for myself only, but for all that seek out discipline.\n"
	"Hear me ye great men, and all peoples, and ye rulers of the Church harken with your ears.\n"
	"To son and wife, brother and friend, give not power over thee in thy life: and give not thy possession to another: lest perhaps thou repent thee, and thou entreat for them.\n"
	"Whilst thou art yet alive and takest breath, all flesh shall not change thee.\n"
	"For it is better that thy children ask of thee, than that thou look toward the hands of thy children.\n"
	"In all thy works be exquisite.\n"
	"Give no stain to thy glory. In the day of the consummation of the days of thy life, and in the time of thy decease distribute thine inheritance.\n"
	"Fodder, and wand, and burden for an ass: bread, and discipline, and work for a servant.\n"
	"He worketh in discipline, and seeketh to rest: release him his hands, and he seeketh liberty.\n"
	"The yoke and the rein bend a stiff neck, and continual works do bow a servant.\n"
	"For a malicious servant torment & fetters, send him into work, that he be not idle.\n"
	"For idleness hath taught much naughtiness.\n"
	"Set him to work: for so it becometh him. And if he be not obedient, bow him with fetters, and exceed not over all flesh: but without judgement do no grievous thing.\n"
	"If thou have a faithful servant, let him be unto thee as thy soul: as a brother so entreat him: because in the blood of thy soul thou hast gotten him.\n"
	"If thou hurt him unjustly, he will run away:\n"
	"if rising up he depart, thou knowest not whom to ask, and what way to seek him.";