const char* chap770 = "Have mercy upon us o God of all, and respect us, and shew us the light of thy mercies:\n"
	"and send in thy fear upon the nations, that have not sought after thee, that they may know that there is no God but thou, and that they may shew forth thy glorious things.\n"
	"Lift up thy hand over the strange Nations, that they may see thy might.\n"
	"For as in their sight thou art sanctified in us, so in our sight thou shalt be magnified in them,\n"
	"that they may know thee, as we also have known, that there is no God beside thee o Lord.\n"
	"Renew signs, and change marvels.\n"
	"Glorify thy hand, and thy right arm.\n"
	"Raise up fury, and pour out wrath.\n"
	"Take away the adversary, and afflict the enemy.\n"
	"Hasten the time, and remember the end, that they may declare thy marvels.\n"
	"Let him that is saved be devoured in the wrath of flame: and let them that evil entreat thy people, find perdition.\n"
	"Break the head of Princes of the enemies, that say: There is none other beside us.\n"
	"Gather together all the tribes of Jacob: and let them know that there is no God but thou, that they may declare thy great works: & thou shalt inherit them as from the beginning.\n"
	"Have mercy on thy people, upon which thy name is invocated: and upon Israel, whom thou hast made equal to thy first begotten.\n"
	"Have mercy on the city of thy sanctification Jerusalem, the city of thy rest.\n"
	"Replenish Sion with thy words that cannot be uttered, & thy people with thy glory.\n"
	"Give the testimony to them that are thy creatures from the beginning, and raise up the prophecies, which the former prophets spake in thy name.\n"
	"Give reward to them that patiently expect thee, that thy prophets may be found faithful: and hear the prayers of thy servants,\n"
	"according to Aaron's benediction of thy people, and direct us into the way of justice, and let all know that inhabit the earth, that thou art God the beholder of the worlds.\n"
	"The belly will eat all meat, and one meat is better than another meat.\n"
	"The jaws taste venison, & the wise heart lying words,\n"
	"A perverse heart will give sorrow, and a cunning man will resist it.\n"
	"Some woman will receive every man: and one daughter is better than another daughter.\n"
	"The beauty of a woman cheereth the face of her husband, and increaseth the desire above all man's concupiscence.\n"
	"If there be a tongue of curing, there is also a mitigating and of mercy: her husband is not according to the sons of men.\n"
	"He that possesseth a good woman beginneth riches: she is an help like unto him, & a pillar as rest.\n"
	"Where there is no hedge, the possession shall be spoiled: and where there is no wife, he mourneth wanting.\n"
	"Who doth credit him that hath no nest, and turning aside wheresoever it waxeth dark, as a robber girded, leaping from city to city.";