const char* chap772 = "Honour the physician for necessity: for the Highest hath created him.\n"
	"For all medicine is of God, & it shall receive gift of the king.\n"
	"The knowledge of the physician shall exalt his head, and in the sight of great men he shall be praised.\n"
	"The Highest hath created medicines of the earth, and a wise man will not abhor them.\n"
	"Was not bitter water made sweet by wood?\n"
	"The virtue of the things is come to the knowledge of men, and the Highest hath given knowledge to men, for to be honoured in his marvelous things.\n"
	"Curing with these things he shall mitigate pain, and the apothecary shall make confections of sweetness, and shall make ointments of health, and his works shall not be consummated.\n"
	"For the peace of God is upon the face of the earth.\n"
	"Son in thine infirmity contemn not thyself, but pray our Lord, and he will cure thee.\n"
	"Turn away from sin, and direct thy hands, and from all offence cleanse thy heart.\n"
	"Give sweetness and a memorial of fine flour, and make a fat oblation, and give place to the physician.\n"
	"For our Lord created him: and let him not depart from thee, because his works be necessary.\n"
	"For there is a time when thou mayst fall into their hands:\n"
	"and they shall beseech our Lord, that he direct their rest, and healing; for their conversation.\n"
	"He that sinneth in his sight, that made him, shall fall into the hands of the physician.\n"
	"Son, upon the dead shed tears, and begin to weep as having suffered doleful things, and according to judgement cover his body, and neglect not his burial.\n"
	"But for detraction bear bitterly the mourning of him one day, and be comforted for the heaviness,\n"
	"and make mourning according to his desert one day, or two, because of detraction.\n"
	"For by heaviness death hasteneth, and it covereth the strength, and sorrow of the heart boweth the neck.\n"
	"In abstraction sorrow is permanent: and the substance of the poor is according to his heart.\n"
	"Give not thine heart into heaviness, but expel it from thee: and remember the latter ends,\n"
	"and forget not: for neither is there return, and him thou shalt profit nothing, and thou shalt hurt thyself.\n"
	"Be mindful of my judgement: for thine also must be so: to me yesterday, and to thee today.\n"
	"In the repose of the dead make the memory of him to rest, and comfort him in the departing of his spirit.\n"
	"The wisdom of a scribe in the time of vacancy: and he that is less in action, shall receive wisdom.\n"
	"With what wisdom shall he be replenished, that holdeth the plough, and glorieth in the goad, driveth oxen with the prickle, and converseth in their works, and his talk is in the breed of bulls?\n"
	"He will give his heart to turn up furrows, and his watching in the feeding of kine.\n"
	"So every craftsman and workmaster that passeth the night as the day, that maketh graven seals, and his continual diligence varieth the picture: he will give his heart to the similitude of the picture, and his watching will perfect the work.\n"
	"So the ironsmith sitting by the anvil and considering the work of iron. The vapour of the fire will parch his flesh, and he striveth in the heat of the furnace:\n"
	"The noise of the hammer reneweth his ear, and his eye is against the similitude of the vessel.\n"
	"He will give his heart to the finishing of the works, and his watching will polish to perfection.\n"
	"So the potter sitting at his work, turning the wheel with his feet, who is always set in carefulness for his works, and all his working is in number:\n"
	"With his arm he will fashion the clay, and before his feet he will bend his strength:\n"
	"He will give his heart to finish the varnishing thereof, and his watching will make clean the furnace.\n"
	"All these have hoped in their hands, and every one is wise in his own art.\n"
	"Without these a city is not built.\n"
	"And they shall not inhabit, nor walk therein, and they shall not leap high into the congregation.\n"
	"Upon the judge's seat they shall not sit, and the ordinance of judgement they shall not understand, neither shall they declare discipline and judgement, and in parables they shall not be found:\n"
	"but they shall confirm the creature of the world, and their prayer shall be in the work of their art, applying their soul, & searching in the law of the Highest.";