const char* chap776 = "Repeat not the word which thou hast heard, neither reveal thou of a secret word, & thou shalt indeed be without confusion, and shalt find grace in the sight of all men: be not ashamed for all these things, and accept not person thereby to sin.\n"
	"Of the law of the Highest, and his testament, and of judgement to justify the impious,\n"
	"of the word of companions and wayfaring men, and of the giving of the inheritance of friends,\n"
	"of the equality of balance and weights, of the getting of many things and few,\n"
	"of the corruption of buying, and of merchants, and of much discipline of thy children, and to make bloody the side of a wicked servant.\n"
	"Over a naughty woman a seal is good.\n"
	"Where there are many hands, shut up, and what soever thou shalt deliver, number, and weigh it: and write every thing given and received.\n"
	"Of the discipline of the unwise and foolish, and of ancients, that are judged of young men: and thou shalt be well instructed in all things, and approved in the sight of all the living.\n"
	"A daughter is the secret watch of the father, and the care of her taketh away sleep, lest perhaps in her youth she become past age, & abiding with an husband she become odious:\n"
	"lest at any time she be corrupted in her virginity, and in her father's house she be found with child: lest perhaps abiding with her husband she transgress, or at the least become barren.\n"
	"Over a dissolute daughter keep sure watch: lest at any time she make thee come into reproach with thine enemies, because of detraction in the city, and the objection of the people, and she confound thee in the multitude of the people.\n"
	"Look not on every body for beauty sake: & among women tarry not.\n"
	"For out of garments cometh forth the moth, and from a woman the iniquity of a man.\n"
	"For better is the iniquity of a man, than a woman doing a good turn, and a woman shaming unto reproach.\n"
	"I therefore will be mindful of the works of our Lord, and I will shew forth which I have seen. By the words of our Lord are his works.\n"
	"The sun illuminating hath looked throughout all, and full of the glory of our Lord is his work.\n"
	"Hath not our Lord made the saints to declare all his marvelous things, which our Lord the omnipotent confirmed to be established in his glory?\n"
	"He hath searched out the depth, and the heart of men: & in their subtility he hath considered.\n"
	"For our Lord hath known all knowledge, and hath beheld the sign of age, declaring what things are past, and what are to come, revealing the tokens of secret things.\n"
	"No cogitation escapeth him, and no word hideth itself from him.\n"
	"The glorious works of his wisdom he hath beautified: who is before the world & world without end, neither is there added,\n"
	"nor diminished, and he needeth not any man's counsel.\n"
	"How are all his works to be desired, and which is as it were a spark to consider!\n"
	"All these live, and remain for ever, and in all necessity all things obey him.\n"
	"All things double, one against one, and he hath made nothing to want.\n"
	"He hath confirmed the good things of every one. And who shall be filled seeing his glory?";