const char* chap778 = "Let us praise glorious men, and our fathers in their generation.\n"
	"Much glory hath our Lord made by his magnificence from the beginning of the world.\n"
	"Ruling in their dominions, men great for force, and endued with their wisdom, declaring in the prophets the dignity of prophets,\n"
	"and ruling in the people that was present, and by the virtue of wisdom most holy words to the peoples.\n"
	"In their skill seeking out musical melodies, & uttering songs of scriptures.\n"
	"Rich men in force studying beautifulness: living at peace in their houses.\n"
	"All these in the generations of their nation have obtained glory, and in their days are praised.\n"
	"They that were born of them have left a name to tell their praises:\n"
	"and there are some of whom there is no memory: they are perished, as they that never were; & are born, as not born at all, & their children with them.\n"
	"But they are men of mercy, whose godly deeds have not failed:\n"
	"good things continue with their seed,\n"
	"their nephews are an holy inheritance, and their seed hath stood in the testaments:\n"
	"and their children because of them abide for ever: their seed and their glory shall not be forsaken.\n"
	"Their bodies are buried in peace, and their name liveth unto generation and generation.\n"
	"Let peoples tell their wisdom, and the Church declare their praise.\n"
	"Henoch pleased God, and was translated into paradise, that he may give repentance to the nations.\n"
	"Noe was found perfect, just, and in the time of wrath he was made a reconciliation.\n"
	"Therefore was there a remnant left to the earth, when the flood was made.\n"
	"The testaments of the world were made with him, that all flesh should no more be destroyed with the flood.\n"
	"Abraham the great father of the multitude of the nations, and there was not found the like to him in glory, who kept the law of the Highest, and was in covenant with him.\n"
	"In his flesh he made the covenant to stand, and in tentation he was found faithful.\n"
	"Therefore by an oath he gave him glory in his nation, that he should increase as an heap of earth,\n"
	"and that he would exalt his seed as the stars, and they should inherit from sea to sea, and from the river to the ends of the earth.\n"
	"And he did in like manner in Isaac for Abraham his father.\n"
	"Our Lord gave him the blessing of all nations, and confirmed his covenant upon the head of Jacob.\n"
	"He knew him in his blessings, and gave him an inheritance, & divided him his portion in twelve tribes.\n"
	"And he preserved unto him men of mercy, and found grace in the eyes of all flesh.";