const char* chap780 = "Strong in battle was Jesus the son of Nave, successor of Moyses among the prophets, who was great according to his name,\n"
	"most great in the salvation of God's elect, to overthrow the enemies rising up, that he might get the inheritance of Israel.\n"
	"What glory obtained he in lifting up his hands, and casting swords against the cities?\n"
	"Who before him did so resist? For our Lord himself brought the enemies.\n"
	"Whether was not the sun hindered in his anger, and one day was made as two?\n"
	"He invocated the mighty sovereign in assaulting of the enemies on every side, and the great and holy God heard him in hail-stones of exceeding great force.\n"
	"He made violent assault against the nation of his enemies, and in the going down he destroyed the adversaries,\n"
	"that the nations might know his might, that it is not easy to fight against God. And he followed at the back of the mighty.\n"
	"And in the days of Moyses did mercy, and Caleb the son of Jephone, did stand against the enemy, and stayed the nation from sins, and appeased the murmuring of malice.\n"
	"And they two being appointed, were delivered out of danger from among the number of six hundred thousand foot men, to bring them into their inheritance, into the land that yieldeth milk and honey.\n"
	"And our Lord gave strength to Caleb himself, and his strength continued even until old age, so that he went up into the high place of the land, & his seed obtained inheritance.\n"
	"That all the children of Israel might see, that it is good to obey the holy God.\n"
	"And all the judges by their name, whose heart was not corrupted: which were not turned away from our Lord,\n"
	"that their memory might be blessed, and their bones spring out of their place,\n"
	"and their name continue for ever, the glory of the holy men remaining unto their children.\n"
	"The beloved of our Lord his God^ Samuel the prophet of our Lord, renewed the empire, and anointed princes in his nation.\n"
	"By the law of our Lord he judged the congregation, and the God of Jacob saw, and in his fidelity was proved a prophet.\n"
	"And he was known faithful in his words, because he saw the God of light:\n"
	"and invocated our Lord Omnipotent, in assaulting the enemies besetting him on every side, in the oblation of an immaculate lamb.\n"
	"And our Lord thundered from heaven, and in great sound he made his voice heard,\n"
	"and he discomfited the Princes of the Tyrians, and all the dukes of the Philisthiims:\n"
	"and before the time of the end of his life, and the world, he gave testimony before our Lord, and his Christ, money and what soever besides unto the very shoes he took not of all flesh, and no man accused him.\n"
	"And after this he slept, and he notified to the king, and shewed him the end of his life, and he exalted his voice out of the earth in prophecy, to take clean away the impiety of the nation.";