const char* chap790 = "I will sing to my beloved the canticle of my cousin concerning his vineyard. A vineyard was made to my beloved in horn, the son of oil.\n"
	"And he hedged it, and chose stones out of it, and planted it elect, and built a tower in the midst thereof, and set up a press therein: and looked that it should yield grapes, and it yielded wild grapes.\n"
	"Now therefore ye inhabitants of Jerusalem, and men of Juda, judge between me and my vineyard.\n"
	"What is there that I ought to do more to my vineyard, and have not done to it? Whether that I looked, it should yield grapes, and it hath yielded wild grapes?\n"
	"And now I will shew you what I will do to my vineyard. I will take away the hedge thereof, and it shall be into spoil: I will throw down the wall thereof, and it shall be to be trodden upon.\n"
	"And I will lay it waste: it shall not be pruned, and it shall not be digged: and briers and thorns shall overgrow it: and I will command the clouds that they rain no shower upon it.\n"
	"For the vineyard of the Lord of hosts, is the house of Israel: and the man of Juda, his delectable bud: & I looked that it should do judgement, and behold iniquity: and justice, and behold clamour.\n"
	"Woe to you that join house to house, and lay field to field, even to the end of the place: why shall you alone dwell in the midst of the earth?\n"
	"These things are in my ears, saith the Lord of hosts: unless many great and fair houses become desolate, without an inhabiter.\n"
	"For ten acres of the vineyards shall yield one little flagon, and thirty bushels of seed shall yield three bushels.\n"
	"Woe to you that rise up early to follow drunkenness, & to drink even until evening, that you may be inflamed with wine.\n"
	"Harp, and viol, & timbrel, and shalm, & wine in your feasts: and the work of our Lord you regard not, nor consider the works of his hands.\n"
	"Therefore is my people led away captive, because they had not knowledge, and their nobles died with famine, and the multitude thereof dried away with thirst.\n"
	"Therefore hath hell dilated his soul, and opened his mouth without any limit: and their strong ones, and their people, and their high and glorious ones shall descend into it.\n"
	"And man shall be bowed, and man shall be humbled, and the eyes of the lofty shall be brought low.\n"
	"And the Lord of hosts shall be exalted in judgement, and the holy God shall be sanctified in justice.\n"
	"And the lambs shall feed according to their order, and strangers shall eat the deserts turned into fruitfulness.\n"
	"Woe to you that draw iniquity in cords of vanity, & sin as the link of a wain.\n"
	"Which say: let him make haste, & let his work come quickly, that we may see it: & let the counsel of the holy one of Israel come, and we shall know it.\n"
	"Woe unto you that call evil good; & good evil: putting darkness light, and light darkness: putting bitter for sweet, & sweet for bitter.\n"
	"Woe to you that are wise in your own eyes, and prudent before yourselves.\n"
	"Woe to you that are mighty to drink wine, & stout men in drunkenness.\n"
	"Which justify the impious for gifts, and take away the justice of the just from them.\n"
	"For this, even as the tongue of fire devoureth stubble, and the heat of the flame burneth it up: so shall their root be as ashes, and their bud shall rise up as dust, for they have cast away the law of the Lord of hosts, and have blasphemed the word of the holy one of Israel.\n"
	"Therefore is the fury of our Lord wrath against his people, and he hath stretched out his hand upon them, & strucken them: and the mountains were troubled, and their carcasses were made as dung in the midst of the streets. In all these things his fury is not turned away, but yet is his hand stretched forth.\n"
	"And he shall lift up a sign in the nations a far, and shall whistle to him of the ends of the earth: and behold he shall come in haste speedily.\n"
	"There is none that fainteth, nor that laboureth in him, he will not slumber, nor sleep, neither shall the girdle of his reins be loosed, neither shall the latchet of his shoe be broken.\n"
	"His arrows sharp, and all his bows bent. The hoofs of his horses as the flint, & his wheels as the violence of a tempest.\n"
	"His roaring as a lion's, he shall roar as lions' whelps: and he will gnash, and hold the prey, and clasp it, and there shall be none to pluck it away.\n"
	"And it shall sound upon him in that day, as the sound of the sea: we shall look toward the earth, and behold darkness of tribulation, and the light is darkened in the mist thereof.";