const char* chap791 = "In the year that king Ozias died, I saw our Lord sitting upon an high throne and elevated: and those things that were under him filled the temple.\n"
	"Seraphims stood upon the same: six wings to one, and six wings to the other: with two they covered his face, and with two they covered his feet, and with two they flew.\n"
	"And they cried one to another, and said: Holy, holy, holy, the Lord God of hosts, all the earth is full of his glory.\n"
	"And the lintels of the doors were moved at the voice of him that cried, & the house was filled with smoke.\n"
	"And I said: Woe is me because I have held my peace, because I am a man of polluted lips, and I dwell in the midst of a people that hath polluted lips, and the King the Lord of hosts I have seen with mine eyes.\n"
	"And one of the Seraphims flew to me, & in his hand an hot coal, which he had taken with tongs from the altar.\n"
	"And he touched my mouth, and said: Behold this hath touched thy lips, and thine iniquity shall be taken away, & thy sin shall be cleansed.\n"
	"And I heard the voice of our Lord saying: Whom shall I send? And who shall go for us? And I said: Lo I am here, send me.\n"
	"And he said: Go, and thou shalt say to this people: Hear ye that hear, and understand not: and see the vision, & know it not.\n"
	"Blind the heart of this people, and make their ears heavy, and shut their eyes: lest perhaps they may see with their eyes, and hear with their ears, and understand with their heart, and be converted and I heal them.\n"
	"And I said: How long Lord? And he said: Until the cities be made desolate without inhabiter, and the houses without man, and the land shall be left desert.\n"
	"And our Lord shall make men go far off, and he shall be multiplied that was left in the midst of the earth.\n"
	"And yet there shall be tithing in it, and she shall be converted, and shall be to the shew as a terebinth, and as an oak, that spreadeth his boughs: that which shall stand in it, shall be an holy seed.";