const char* chap794 = "At the first time was the land of Zabulon alleviated, and the land of Nephthali: and at the last was aggravated the way of the sea beyond Jordan of Galilee of the Gentiles.\n"
	"The people that walked in darkness, hath seen great light: to them that dwelt in the country of the shadow of death, light is risen.\n"
	"Thou hast multiplied the nation, & not magnified the joy. They shall rejoice before thee, as they that rejoice in harvest, as conquerors rejoice after a prey is taken, when they divide the spoils.\n"
	"For the yoke of their burden, and the rod of their shoulder, and the sceptre of their exactor thou hast overcome, as in the day of Madian.\n"
	"Because all violent taking of prey with tumult, and garment mingled with blood, shall be to be burnt, and food for the fire.\n"
	"For A LITTLE CHILD IS BORN TO US, and a son is given to us, and his principality is made upon his shoulder: and his name shall be called, Marvelous, Counseller, God, Strong, Father of the world to come, the Prince of peace:\n"
	"His empire shall be multiplied, and there shall be no end of peace: he shall sit upon the throne of David, and upon his kingdom: that he may confirm it, and strengthen it in judgement and justice, from this time & for ever: the zeal of the Lord of hosts shall do this.\n"
	"Our Lord hath sent a word into Jacob, and it is fallen in Israel.\n"
	"And all the people of Ephraim shall know, & the inhabitants of Samaria, saying in pride & greatness of heart:\n"
	"Bricks are fallen, but we will build with square stones: they have cut down sycamores, but we will change them into cedars.\n"
	"And our Lord shall lift up the enemies of Rasin over him, and shall turn his enemies into tumult.\n"
	"Syria from the East, and the Philisthims from the West: and they shall devour Israel with full mouth. In all these things his fury is not turned away, but his hand is yet stretched forth.\n"
	"And the people is not returned to him, who hath strucken them, and have not sought after the Lord of hosts.\n"
	"And our Lord shall destroy from Israel the head & the tail, the perverter and restrainer in one day.\n"
	"The aged and honourable, he is the head, & the prophet that teacheth a lie, he is the tail.\n"
	"And they that call this people blessed, seducing them: and that are called blessed, shall be thrown headlong.\n"
	"For this cause our Lord shall not rejoice upon their young men: and on their pupils and widows he shall not have mercy: because every one is an hypocrite & wicked, and every mouth hath spoken folly. In all these things his fury is not turned away, but his hand is yet stretched forth.\n"
	"For impiety is kindled as a fire, it shall devour brier & thorn: & it shall be kindled in the thicket of the forest, and it shall be wrapped up together in the pride of smoke.\n"
	"In the wrath of the Lord of hosts the earth is troubled, and the people shall be food for the fire: man shall not spare his brother.\n"
	"And he shall decline to the right hand, and shall be hungry: and shall eat on the left hand, and shall not be filled: every one shall eat the flesh of his arm: Manasses Ephraim, and Ephraim Manasses, they together against Juda.\n"
	"In all these things his fury is not turned away, but his hand is yet stretched forth.";