const char* chap798 = "The burden of Babylon, which Isaie the son of Amos saw.\n"
	"Upon the dark mountain lift up a sign, exalt the voice, lift up the hand, & let the dukes enter the gates.\n"
	"I have commanded my sanctified, and have called my strong ones in my wrath, them that rejoice in my glory.\n"
	"The voice of a multitude in the mountains, as it were of many peoples, a voice of the sound of kings, nations gathered together: The Lord of hosts hath commanded the host of battle.\n"
	"Coming from a country far off, from the end of heaven: our Lord, & the instruments of his fury, to destroy the whole land.\n"
	"Howl ye, because the day of our Lord is near: it shall come as destruction from our Lord.\n"
	"For this cause shall all hands be dissolved, and every heart of man shall melt;\n"
	"and be broken. Gripings and pains shall hold them, they shall be in pain as she that travaileth. Every one shall be astonied at his neighbour, their countenances as faces burnt.\n"
	"Behold the day of our Lord shall come, cruel, & full of indignation, & of wrath, & fury to bring the land to a wilderness, and to destroy the sinners thereof out of it.\n"
	"Because the stars of heaven, and their brightness shall not display their light: the sun is darkened in his rising, and the moon shall not shine in her light.\n"
	"And I will visit over the evils of the world, and against the impious their iniquity, and I will make the pride of infidels to cease, & will humble the arrogancy of the strong.\n"
	"A man shall be more precious than gold, & man than pure fine gold.\n"
	"For this I shall trouble heaven: and the earth shall be moved out of her place, for the indignation of the Lord of hosts, & for the day of the wrath of his fury.\n"
	"And it shall be as a young doe flying, & as a sheep: & there shall be none to gather them together: every man shall turn to his own people, and every one shall fly to his own land.\n"
	"Every one that shall be found, shall be slain: and every one that shall come to aid, shall fall by the sword.\n"
	"Their infants shall be dashed in pieces before their eyes: their houses shall be spoiled, and their wives shall be ravished.\n"
	"Behold I will raise upon them the Medes, which shall not seek silver, nor desire gold.\n"
	"But with arrows they shall kill the little ones, and shall have no pity upon the sucklings of the womb, and upon the children their eye shall not spare.\n"
	"And that Babylon glorious in kingdoms, noble in the pride of the Chaldees, shall be even as our Lord subverted Sodom and Gomorrha.\n"
	"It shall not be inhabited for ever, & it shall not be founded unto generation & generation: neither shall the Arabian pitch his tents there, nor shepherds rest there.\n"
	"But beasts shall rest there, and their houses shall be filled with dragons, and ostriches shall dwell there, and Satyrs shall dance there:\n"
	"And the Syrach owls shall answer there in the houses thereof, and mermaids in the temples of pleasure.";