const char* chap799 = "It is near that the time thereof shall come, and the days thereof shall not be prolonged. For our Lord will have mercy on Jacob, and will yet choose out of Israel, and will make them rest upon their own ground: the stranger shall be joined to them, & shall stick to the house of Jacob.\n"
	"And peoples shall hold them, and bring them into their place, and the house of Israel shall possess them upon the land of our Lord for servants and handmaids: and they shall lead captive those that had taken them, & shall subdue their exactors.\n"
	"And it shall be in that day, when God shall give thee rest from thy labour, and from thy vexation, and from the sore servitude, which thou didst serve before.\n"
	"Thou shalt take this parable against the king of Babylon, and shalt say: How hath the exactor ceased, the tribute rested:\n"
	"Our Lord hath broken the staff of the impious, the rod of the rulers,\n"
	"that did beat peoples in indignation with uncurable wound, subduing nations in fury, persecuting cruelly.\n"
	"All earth is quiet and still, is glad & hath rejoiced.\n"
	"The fir trees also have rejoiced over thee, and the cedars of Libanus: since thou hast slept, there hath none come up to hew us.\n"
	"Hell beneath is troubled to meet thy coming, it hath raised up the giants for thee. All the princes of the earth are risen up from their thrones, all the princes of nations.\n"
	"All shall answer, and say to thee: Thou also art wounded even as we, made like unto us.\n"
	"Thy pride is drawn down to hell, thy carcass is fallen: under thee shall the moth be strawed, and worms shall be thy covering.\n"
	"How art thou fallen from heaven Lucifer, which didst rise in the morning? Art thou fallen to the earth, that didst wound nations?\n"
	"Which didst say in thy heart: I will ascend into heaven, above the stars of God will I exalt my throne, I will sit in the mount of the testament, in the sides of the North.\n"
	"I will ascend above the height of the clouds, I will be like to the Highest.\n"
	"But yet thou shalt be drawn down to hell, into the depth of the lake.\n"
	"They that shall see thee, shall turn toward thee, & behold thee: Is this the man that troubled the earth, that shaked kingdoms,\n"
	"that made the world a desert, & destroyed the cities thereof, opened not the prison to his prisoners?\n"
	"All the kings of the nations every one have slept in glory, each man in his own house.\n"
	"But thou art cast forth out of thy sepulchre, as an unprofitable branch polluted, and wrapped up with them that were slain by the sword, and are gone down to the foundations of the lake, as a rotten carcass.\n"
	"Thou shalt not keep company with them, neither in burial, for thou hast destroyed thy land, thou hast slain thy people: the seed of the wicked shall not be named for ever.\n"
	"Prepare his children to slaughter in the iniquity of their fathers: they shall not rise up, nor inherit the land, nor fill the world with cities.\n"
	"And I will rise over them, saith the Lord of hosts: & I will destroy the name of Babylon, and the remains, and bud, and progeny: saith our Lord.\n"
	"And I will make it the possession of the hedgehog, & matrices of waters, & I will sweep it with besom wearing it, saith the Lord of hosts.\n"
	"The Lord of hosts hath sworn, saying: If it shall not be, as I have thought: and so fall out, as I have in mind consulted:\n"
	"That I destroy the Assyrian in my land, and in my mountains tread upon him: and his yoke shall be taken away from them, and his burden taken off from their shoulder.\n"
	"This is the counsel, that I have devised upon all the earth, and this is the hand stretched forth upon all nations.\n"
	"For the Lord of hosts hath decreed, and who can weaken it? And his hand is stretched out: and who shall turn it away?\n"
	"In the year, that king Achaz died, was this burden made.\n"
	"Rejoice not thou whole Philistaea, that the rod of thy striker is broken in pieces: for from the root of the serpent shall issue forth a cockatrice, and his seed swallowing the bird.\n"
	"And the first born of the poor shall be fed, & the poor shall rest confidently: and I will make thy root to perish in famine, & will kill thy remnant.\n"
	"Howl thou gate, cry out o city: all Philisthaea is thrown down: for a smoke shall come from the North, and there is none that shall escape his troop.\n"
	"And what shall be answered to the messengers of nations? That our Lord hath founded Sion, and the poor of his people shall hope in him.";