const char* chap80 = "Thou shalt make also an Altar to burn incense, of the wood setim,\n"
	"having a cubit of length, and another of breadth, that is, four square, and two cubits in height. The horns shall proceed out of the same.\n"
	"And thou shalt plate it with the purest gold, as well the grate thereof, as the walls round about, and the horns. And thou shalt make to it a crown of gold round about,\n"
	"and two golden rings under the crown on either side, that the bars may be put into them, and the Altar may be carried.\n"
	"The bars also themselves thou shalt make of the wood setim, and shalt plate them with gold.\n"
	"And thou shalt set the Altar against the veil, that hangeth before the ark of the testimony before the propitiatory wherewith the testimony is covered, where I will speak to thee.\n"
	"And Aaron shall burn incense upon it, sweetly fragrant, in the morning. When he shall dress the lamps, he shall burn it:\n"
	"and when he shall place them at even, he shall burn incense everlasting before the Lord through your generations.\n"
	"You shall not offer upon it incense of another composition, nor oblation, and victim, neither shall you offer libaments.\n"
	"And Aaron shall pray upon the horns thereof once a year, with the blood of that which was offered for sin, & shall pacify upon it in your generations. It shall be most Holy to the Lord.\n"
	"And our Lord spake to Moyses, saying:\n"
	"When thou shalt take the sum of the children of Israel according to their number, every one of them shall give a price for their souls to the Lord, & there shall be no scourge among them, when they shall be reckoned.\n"
	"And this shall every one give that passeth to the naming, half a sicle according to the measure of the temple. A sicle hath twenty oboles. The half part of a sicle shall be offered to the Lord.\n"
	"He that is accounted in the number, for twenty years and upward, shall give price.\n"
	"The rich man shall not add to half a sicle, & the poor man shall diminish nothing.\n"
	"And the money being received, which was contributed of the children of Israel, thou shalt deliver unto the uses of the tabernacle of testimony, that it may be a monument of them before the Lord, & he may be propitious to their souls.\n"
	"And our Lord spake to Moyses, saying:\n"
	"Thou shalt make also a laver with his foot of brass, to wash in: and thou shalt set it between the tabernacle of the testimony and the Altar. And water being put into it,\n"
	"Aaron and his sons shall wash therein their hands and feet,\n"
	"when they are going into the tabernacle of testimony, and when they are to come unto the Altar, to offer on it incense to the Lord,\n"
	"lest perhaps they die. It shall be an everlasting law to him, and to his seed by succession.\n"
	"And our Lord spake to Moyses,\n"
	"saying: Take spices, of principal and chosen myrrh five hundred sicles, and of cinnamon half so much, that is, two hundred fifty sicles, of calamus in like manner two hundred fifty,\n"
	"and of cassia five hundred sicles after the weight of the Sanctuary, of oil of olives the measure hin:\n"
	"and thou shalt make the holy oil of unction, an ointment compounded by the art of an unguentary,\n"
	"and thereof thou shalt anoint the tabernacle of testimony, and the ark of the testament,\n"
	"and the table with the vessel thereof, the candlestick, and the furniture thereof, the Altars of incense,\n"
	"and of holocaust, and all the furniture that pertaineth to the service of them.\n"
	"And thou shalt sanctify all, and they shall be most Holy: he that shall touch them, shall be sanctified.\n"
	"Thou shalt anoint Aaron and his sons, and shalt sanctify them, that they may do the function of priesthood unto me.\n"
	"To the children of Israel also thou shalt say: This oil of unction shall be holy unto me through your generations.\n"
	"The flesh of man shall not be anointed therewith, and you shall make none other after the composition of it, because it is sanctified, and shall be holy unto you.\n"
	"What man soever shall compound such, and shall give thereof to a stranger, shall be abandoned out of his people.\n"
	"And our Lord said to Moyses: Take unto thee spices, stacte, and onycha, galbanum of sweet savour, and the clearest frankincense, all shall be of equal weight:\n"
	"and thou shalt make incense compounded by the work of an unguentary, exactly tempered, and pure, and most worthy of sanctification.\n"
	"And when thou hast beaten all into very small powder, thou shalt set of it before the tabernacle of testimony, in the place where I will appear to thee. Most Holy shall the incense be unto you.\n"
	"Such confection you shall not make unto your own uses, because it is holy to the Lord.\n"
	"What man soever shall make the like, to enjoy the smell thereof, shall perish out of his people.";