const char* chap801 = "Send forth o Lord the lamb the dominatour of the earth, from the Rock of the desert, to the mount of the daughter of Sion.\n"
	"And he shall be as a bird flying, and the young flying out of the nest, so shall the daughters of Moab be in the passage of Arnon.\n"
	"Take counsel, gather a council: set thy shadow in the midday as it were night: hide them that fly, and them that wander bewray not.\n"
	"My fugitives shall dwell with thee: Moab be thou their covert from the face of the destroyer: for the dust is ended, the wretch is come to naught: he hath failed, that trod down the earth.\n"
	"And a throne shall be prepared in mercy, and there shall sit upon it, in truth in the tabernacle of David, he that judgeth & seeketh judgement, and quickly rendereth that which is just.\n"
	"We have heard the pride of Moab, he is proud exceedingly: his pride and his arrogancy, and his indignation is more than his strength.\n"
	"Therefore shall Moab howl: to Moab, all shall howl: to them that rejoice upon the walls of baked brick, tell ye their plagues.\n"
	"Because the suburbs of Hesebon are desolate, and the vineyard of Sabama the lords of the Nations have cut off: the branches thereof have reached to Jazer: they wandered in the desert, the branches thereof are left, they passed over the sea.\n"
	"For this I will lament in the weeping of Jazer the vineyard of Sabama: I will inebriate thee with my tear o Hesebon, and Eleale: because the voice of the treaders is rusht in upon thy vintage, and upon thy harvest.\n"
	"And gladness and joy shall be taken away from Carmelus, and it shall not rejoice nor make jubilation in vineyards. He shall not tread wine in the press that was wont to tread: the voice of the treaders I have taken away.\n"
	"For this my belly shall sound as an harp to Moab, & my bowels to the wall of baked brick.\n"
	"And it shall be: when it shall appear that Moab hath laboured for his excelses, he shall go into his sanctuaries to pray, & shall not prevail.\n"
	"This is the word, that our Lord spake to Moab from that time:\n"
	"and now our Lord hath spoken saying: In three years, as the years of an hired servant, the glory of Moab shall be taken away upon all the multitude of people, and it shall be left little & small, not much.";