const char* chap810 = "O Lord thou art my God. I will exalt thee, and confess to thy name: because thou hast done marvelous things, the old cogitations faithful, Amen.\n"
	"Because thou hast brought the city into a heap, the strong city into ruin, the house of strangers: that it be no city, & that it be not built for ever.\n"
	"For this shall strong people praise thee, the city of strong nations shall fear thee.\n"
	"Because thou art become a strength to the poor, a strength to the needy in his tribulation: an hope against the whirlwind, a shadow against the heat. For the spirit of the strong is as a whirlwind beating against a wall.\n"
	"As heat in thirst, shalt thou humble the tumult of strangers: and as with heat under a burning cloud thou shalt make the branch of the strong to wither.\n"
	"And the Lord of hosts shall make to all peoples in this mount, a feast of fat things, a feast of vintage, of fat things full of marrow, of vintage purified from the dregs.\n"
	"And he shall in this mount throw down headlong the face of the bond, tied together upon all peoples, and the web that he hath begun upon all nations.\n"
	"He shall cast death down headlong for ever: and our Lord God shall take away tear from all face, and the reproach of his people he shall take away out of the whole earth: because our Lord hath spoken it.\n"
	"And he shall say in that day: Lo this is our God, we have expected him, and he will save us: this is our Lord, we have patiently waited for him, we shall rejoice and be joyful in his salvation.\n"
	"Because the hand of our Lord shall rest in this mount: and Moab shall be threshed under him, as straw is broken with the wain.\n"
	"And he shall stretch forth his hands under him, as he that swimmeth stretcheth forth to swim: and he shall humble his glory with dashing of his hands.\n"
	"And the munitions of thy high walls shall fall, and be humbled, & shall be plucked down to the ground even to the dust.";