const char* chap813 = "Woe to the crown of pride, to the drunkards of Ephraim, and to the flower falling down from the glory of his exultation, which were in the top of the most fat valley, erring by wine.\n"
	"Behold our Lord is valiant and strong, as the violence of hail: a whirlwind breaking, the violence of many waters overflowing, & sent forth upon a large ground.\n"
	"The crown of pride of the drunkards of Ephraim shall be trodden under feet.\n"
	"And the flower of the glory of his exultation, which is upon the top of the valley of fat ones, shall be falling as a timely fruit before the ripeness of autumn: which when he that seeth it shall behold, as soon as he taketh it in his hand, he will devour it.\n"
	"In that day the Lord of hosts shall be a crown of glory, and a garland of exultation to the residue of his people:\n"
	"and a spirit of judgement to him that sitteth in judgement, and strength to them that return out of battle to the gate.\n"
	"But these also have been ignorant, because of wine, and by drunkenness have erred: the priest and the prophet have been ignorant because of drunkenness, they are swallowed up with wine, they have erred in drunkenness, they have not known him that seeth, they have been ignorant of judgement.\n"
	"For all tables were filled with vomiting and filth, so that there was no more place.\n"
	"Whom shall he teach knowledge? And whom shall he make to understand the thing heard? Them that are weaned from the milk, that are plucked away from the breasts.\n"
	"For command recommand, command recommand; expect reexpect, expect reexpect; a little there, a little there.\n"
	"For in the speech of lip, & in another tongue he will speak to his people.\n"
	"To whom he said: This is my rest, refresh the weary, and this is my refreshing: & they would not hear.\n"
	"And the word of our Lord shall be to them, command recommand, command, recommand; expect reexpect, expect, reexpect, a little there, a little there: that they may go, and fall backward, and be destroyed, and snared, and taken.\n"
	"For this cause hear the word of our Lord ye scornful men, which rule over my people that is in Jerusalem.\n"
	"For you have said: We have strucken a league with death, & with hell we have made a covenant. The scourge overflowing when it shall pass, shall not come upon us: because we have made lying our hope, & with lying we are protected.\n"
	"Therefore thus saith our Lord God: Behold I will send in the foundations of Sion a stone, an approved stone, a corner stone, precious, founded in the foundation. He that believeth, let him not make haste.\n"
	"And I will put judgement in weight, and justice in measure: and hail shall overthrow the hope of lying: and waters shall overflow the protection.\n"
	"And your league with death shall be abolished, & your covenant with hell shall not stand: when the scourge overflowing shall pass, you shall be trodden down of it.\n"
	"Whensoever it shall pass through, it shall take you away: because in the morning early it shall pass through in the day and in the night, and vexation alone shall give understanding in the hearing.\n"
	"For the bed is straitened, so that one must fall out, & a short mantle cannot cover both.\n"
	"For our Lord shall stand as in the mount of divisions: as in the valley, which is in Gabaon, shall he be angry: that he may do his work, his strange work: that he may work, his work is strange from him.\n"
	"And now mock not, lest perhaps your bonds be tied strait. For I have heard of our Lord the God of hosts consummation and abridgment upon all the earth.\n"
	"Harken with your ears, and hear my voice, attend, & hear my speech.\n"
	"Will the ploughman plow all the day to sow, will he cut & harrow his ground?\n"
	"Will he not when he hath made even the face thereof, sprinkle cummin, and place the wheat by order, and the barley, and millet, and vetch, in their bounds?\n"
	"And his God will instruct him in judgement: he will teach him.\n"
	"For gith shall not be threshed with instruments that have teeth, neither shall the wain wheel turn about upon cummin: but gith shall be beaten out with a rod, and cummin with a staff.\n"
	"But bread corn shall be broken small: but the thresher shall not thresh it for ever, neither shall the wain wheel vex it, nor break it with the teeth thereof.\n"
	"And this is come forth from our Lord the God of hosts, that he might make his counsel marvelous, and magnify justice.";