const char* chap815 = "Woe unto renegade children, saith our Lord, that you would take counsel, and not of me: and would begin a web, and not by my spirit, that you might add sin upon sin:\n"
	"which walk to go down into Aegypt, and have not asked my mouth, hoping for help in the strength of Pharao, and having confidence in the shadow of Aegypt.\n"
	"And the strength of Pharao shall be a confusion to you, and the confidence in the shadow of Aegypt an ignominy.\n"
	"For thy Princes were in Tanis, & thy messengers came even to Hanes.\n"
	"All were confounded upon the people, that could not profit them: they were no help, nor to any profit, but to confusion & to reproach.\n"
	"The burden of the beasts of the South. In a land of tribulation & distress, the lioness, & the lion of them, the viper & the flying basiliscus carrying their riches upon the shoulders of beasts, & their treasures upon the bunch of camels, to a people that cannot be able to profit them.\n"
	"For Aegypt shall help in vain, and to no purpose: therefore have I cried upon this: It is pride only, cease.\n"
	"Now therefore going in write to her upon box, and draw it diligently in a book, and it shall be in the latter day for a testimony for ever.\n"
	"For it is a people provoking to wrath, & lying children, children that will not hear the law of God.\n"
	"Which say to the seers: See not: & to them that behold: Behold us not those things that are right: Speak unto us pleasant things, see errors unto us.\n"
	"Take from me the way, turn away the path from me, let the holy one of Israel cease from our face.\n"
	"Therefore thus saith the holy one of Israel: For that you have rejected this word, and have hoped in calumny and tumult, and have leaned thereupon:\n"
	"therefore shall this iniquity be unto you as a breach that falleth, and is found lacking in an high wall, because suddenly, whilst it is not hoped, shall come the destruction thereof.\n"
	"And it shall be broken small, as the potter's vessel is broken with mighty breaking: and there shall not a shred be found of the fragments thereof, wherein a little fire may be carried from the burning, or a little water be drawn out of the pit.\n"
	"Because thus saith our Lord the God of Israel: If you return and be quiet, you shall be saved: in silence and in hope shall your strength be. And you would not:\n"
	"and you have said: No, but we will fly to horses: therefore shall you fly. And we will mount upon swift ones: therefore shall they be swifter, that shall persecute you.\n"
	"A thousand men at the face of the terror of one, and at the face of the terror of five shall you fly, till you be left as the mast of a ship in the top of a mountain, and as a sign upon a little hill.\n"
	"Therefore our Lord expecteth that he may have mercy on you: and therefore shall he be exalted sparing you: because our Lord is the God of judgement: blessed are all they that expect him.\n"
	"For the people of Sion shall dwell in Jerusalem: weeping thou shalt not weep, pitying he will pity thee: at the voice of thy cry as soon as he shall hear, he will answer thee.\n"
	"And our Lord will give you strait bread, & short water: and will not make thy doctor to fly away from thee any more: and thine eyes shall see thy master.\n"
	"And thine ears shall hear the word of him, that behind thy back admonisheth thee: This is the way, walk in it: and decline ye not neither to the right hand, nor to the left.\n"
	"And thou shalt contaminate the plates of the sculptiles of thy silver, & the garment of the molten of thy gold, and shalt scatter them as the uncleanness of a menstruous woman. Thou shalt say to it: Get thee hence.\n"
	"And rain shall be given to thy seed, wheresoever thou shalt sow in the land: and the bread of the corn of the land shall be most plentiful, and fat. The lamb in that day shall feed at large in thy possession:\n"
	"and thine oxen, as the ass colts, that till the ground, shall eat mingled provender as it was fanned in the floor.\n"
	"And there shall be upon every high mountain, and upon every little hill elevated, rivers of running waters in the day of the killing of many when the towers shall fall.\n"
	"And the light of the moon shall be as the light of the sun, and the light of the sun shall be sevenfold, as the light of seven days, in the day when our Lord shall bind up the wound of his people, and shall heal the stroke of their wound.\n"
	"Behold the name of our Lord cometh from far, his burning fury, and heavy to bear: his lips are filled with indignation, and his tongue as a devouring fire.\n"
	"His spirit as a torrent overflowing even to the midst of the neck, to destroy the nations to nothing, and the bridle of error, that was in the jaws of peoples.\n"
	"There shall be a song unto you as the night of a sanctified solemnity, and joy of heart as he that goeth with a shalm, to enter into the mount of our Lord to the strong one of Israel.\n"
	"And our Lord shall make the glory of his voice to be heard, and shall shew the terror of his arm, in threatening of fury, and flame of devouring fire: he shall dash to pieces in whirlwind, and in hail stone.\n"
	"For at the voice of our Lord shall Assur fear being strucken with the rod.\n"
	"And the passage of the rod shall never cease, which our Lord shall make to rest upon him in timbrels and harps, and in principal battles he shall overthrow them.\n"
	"For Topheth is prepared since yesterday, prepared of the king, deep, and wide. The nourishments thereof, fire and much wood: the breath of our Lord as a torrent of brimstone kindling it.";