const char* chap819 = "Come near ye Gentiles, and hear, and ye peoples attend: let the earth hear, & the fullness thereof, the round world, and every spring thereof.\n"
	"Because the indignation of our Lord is upon all Gentiles, and fury upon all their hosts: he hath killed them, & given them into slaughter.\n"
	"Their slain shall be cast forth, and out of their carcasses shall rise a stink: the mountains shall melt with their blood.\n"
	"And all the host of the heavens shall melt away, and the heavens shall be folded together as a book: and all their hosts shall fall away as the leaf falleth from the vine, & from the fig tree.\n"
	"Because my sword is inebriated in heaven: behold it shall descend upon Idumaea, and upon the peoples of my slaughter to judgement.\n"
	"The sword of our Lord is filled with blood, it is fatted of the blood of lambs and buckgoats, of the blood of rams full of marrow: for the victim of our Lord is in Bosra, & a great slaughter in the land of Edom.\n"
	"And the unicorns shall come down with them, & the bulls with the mighty: their land shall be drunk with blood, & their ground with the fatness of fat ones.\n"
	"Because it is the day of the revenge of our Lord, the year of retributions of the judgement of Sion.\n"
	"And the torrents thereof shall be turned into pitch, and the ground thereof into brimstone: and the land thereof shall be into burning pitch.\n"
	"Night and day it shall not be quenched, the smoke thereof shall go up for ever: from generation unto generation it shall be desolate, there shall none pass by it world without end.\n"
	"The onocrotalus, and hedgehog shall possess it: & the ibis, and the raven shall dwell in it: & a measure shall be stretched out upon it, to bring it to nothing, and a plum line unto desolation.\n"
	"The nobles thereof shall not be there: they shall call rather upon the king, and all the princes thereof shall be as nothing.\n"
	"And thorns and nettles shall grow up in the houses thereof, & the thistles in the munitions thereof: and it shall be the couch of dragons, and the pasture of ostriches.\n"
	"And spirits shall meet the onocentaurus, and the satyr shall cry one to the other, there hath the lamia lien, and found herself rest.\n"
	"There hath the hedgehog had an hole, and brought up whelps, and digged round about, and cherished them in the shadow thereof: thither are the kites gathered together, one to another.\n"
	"Search ye diligently in the book of our Lord, and read: one of them hath not wanted, one hath not sought for the other, because that which proceedeth out of my mouth, he hath commanded, and his spirit the same hath gathered them.\n"
	"And he hath cast them a lot, and his hand hath divided it unto them by measure: they shall possess it for ever, in generation and generation they shall dwell therein.";