const char* chap82 = "And the people seeing that Moyses made tarriance ere he came down from the mount, being assembled against Aaron, they said: Arise, make us gods, that may go before us: for what hath chanced to this Moyses the man that brought us out of the Land of Aegypt, we know not.\n"
	"And Aaron said to them: Take the golden earlets from the ears of your wives, and sons, and daughters, & bring them to me.\n"
	"And the people did that he had commanded, bringing the earlets to Aaron.\n"
	"Which when he had received, he formed them by founder's work, and made of them a molten calf. And they said: These are thy gods Israel, that have brought thee out of the land of Aegypt.\n"
	"Which when Aaron had seen, he builded an altar before it, and by a crier's voice proclaimed saying: Tomorrow is the solemnity of the Lord.\n"
	"And rising in the morning, they offered holocausts, and pacific hosts, and the people sat down to eat, and to drink, and they rose up to play.\n"
	"And our Lord spake to Moyses, saying: Go, get thee down: thy people, which thou hast brought out of the Land of Aegypt, hath sinned.\n"
	"They have quickly revolted from the way that thou didst shew them: and they have made to themselves a molten calf, and have adored, and immolating hosts unto it, have said: These are thy gods Israel, that have brought thee out of the Land of Aegypt.\n"
	"And again our Lord said to Moyses: I see that this people is stiff-necked:\n"
	"suffer me, that my fury may be angry against them, & that I may destroy them, and I will make thee into a great nation.\n"
	"But Moyses besought the Lord his God, saying: Why Lord, is thy fury angry against thy people, whom thou hast brought forth of the Land of Aegypt, in great power, and in a strong hand?\n"
	"Let not the Aegyptians say I beseech thee: He hath craftily brought them forth, that he might kill them in the mountains, and destroy them from the earth: let thine anger cease, and be pacified upon the wickedness of thy people.\n"
	"Remember Abraham, Isaac, and Israel thy servants, to whom thou swarest by thine own self, saying: I will multiply your seed as the stars of heaven: and this whole land, whereof I have spoken, I will give to your seed, & you shall possess it always.\n"
	"And our Lord was pacified from doing the evil which he had spoken against his people.\n"
	"And Moyses returned from the mount, carrying the two tables of testimony in his hand, written on both sides,\n"
	"and made by the work of God: the writing also of God was graven in the tables.\n"
	"And Josue hearing the tumult of the people crying out, said to Moyses: The noise of battail is heard in the camp.\n"
	"Who answered: It is not the cry of men encouraging of fight, nor the shout of men compelling to fly: but I do hear the voice of singers.\n"
	"And when he approached to the camp, he saw the calf, and the dances: and being very wrath, he threw the tables out of his hand, and brake them at the foot of the mount.\n"
	"And catching the calf which they had made, he burnt it, & beat it into powder, which he strawed into water, and gave thereof drink to the children of Israel.\n"
	"And he said to Aaron: What hath this people done to thee, that thou shouldest bring upon them an heinous sin?\n"
	"To whom he answered: Let not my Lord be offended for thou knowest this people, that it is prone to evil:\n"
	"they said to me: Make us gods, that may go before us: for unto this same Moyses, that brought us forth out of the Land of Aegypt, we know not what is chanced.\n"
	"To whom I said: Which of you hath gold? They took, & brought to me: & I cast it into the fire, and this calf came forth.\n"
	"Moyses therefore seeing the people that they were made naked (for Aaron had spoiled them for the ignominy of filth, & had set them naked among their enemies).\n"
	"& standing in the gate of the camp, he said: If any man be our Lord's, let him join to me, And there gathered unto him all the sons of Levi:\n"
	"to whom he said: This saith the Lord God of Israel: Put every man his sword upon his thigh: go, and return from gate to gate through the midst of the camp, and every man kill his brother, and friend, and neighbour.\n"
	"And the sons of Levi did according to the saying of Moyses, and there were slain in that day about three and twenty thousand men.\n"
	"And Moyses said: You have consecrated your hands this day to our Lord, every man in his son & in his brother, that blessing may be given to you.\n"
	"And when the next day was come, Moyses spake to the people: You have sinned a very great sin: I will go up to our Lord, if by any means I may be able to entreat him for your sinful fact.\n"
	"And returning to our Lord, he said: I beseech thee, this people hath sinned a heinous sin, and they have made to themselves gods of gold; either forgive them this trespass,\n"
	"or if thou do not, strike me out of the book that thou hast written.\n"
	"To whom our Lord answered: He that hath sinned to me, him will I strike out of my book:\n"
	"but go thou, and lead this people wither I have told thee: mine Angel shall go before thee. And I in the day of revenge will visit this sin also of theirs.\n"
	"Our Lord therefore smote the people for the fault concerning the calf, which Aaron had made.";