const char* chap820 = "The desert and the land without passage shall be glad, and the wilderness shall rejoice, & shall flourish as the lily.\n"
	"Springing it shall spring, & shall rejoice joyful and praising: the glory of Libanus is given to it, the beauty of Carmel, & Saron, they shall see the glory of our Lord, and the beauty of our God.\n"
	"Encourage ye the loose hands, and strengthen the weak knees.\n"
	"Say to the faint hearted: Take courage, and fear not: behold your God shall bring revenge of retribution: God himself will come and will save you.\n"
	"Then shall the eyes of the blind be opened, and the ears of the deaf shall be open.\n"
	"Then shall the lame leap as an hart, and the tongue of the dumb shall be opened: because waters are cut out in the desert, and torrents in the wilderness.\n"
	"And that which was dry land, shall be as a pool, and the thirsty ground as fountains of waters. In the dens wherein dragons dwelt before, shall spring up the greenness of reed and bulrush.\n"
	"And a path and a way shall be there, and it shall be called the holy way: the polluted shall not pass by it, and this shall be unto you a direct way, so that fools cannot err by it.\n"
	"The lion shall not be there, and the naughty beast shall not go up by it, nor be found there: and they shall walk that shall be delivered.\n"
	"And the redeemed of our Lord shall be converted, and shall come into Sion with praise, and everlasting joy shall be upon their head: they shall obtain joy and gladness, and sorrow and mourning shall fly away.";