const char* chap823 = "In those days Ezechias was sick even to death: and Isaie the son of Amos the Prophet, went in unto him, and said to him: Thus saith our Lord: Take order with thy house, for thou shalt die, and shalt not live.\n"
	"And Ezechias turned his face to the wall, & prayed to our Lord,\n"
	"and said: I beseech thee Lord, remember I pray thee how I have walked before thee in truth, and in a perfect heart, and have done that which is good in thine eyes. And Ezechias wept with great weeping.\n"
	"And the word of our Lord was made to Isaie, saying:\n"
	"Go, & tell Ezechias: Thus saith our Lord the God of David thy father: I have heard thy prayer, and seen thy tears: Lo I will add upon thy days fifteen years:\n"
	"and out of the hand of the king of the Assyrians will I deliver thee, and this city, & will protect it.\n"
	"And this shall be a sign to thee from our Lord that our Lord will do this word, which he hath spoken:\n"
	"Behold I will make the shadow of the lines return, by the which it is now gone down in the dial of Achaz in the sun, back-ward ten lines. And the sun returned ten lines by the degrees whereby it was gone down.\n"
	"The scripture of Ezechias the king of Juda, when he had been sick, & was recovered of his infirmity.\n"
	"I have said: In the midst of my days^ shall I go to the gates of hell. I have sought the residue of my years.\n"
	"I have said: I shall not see our Lord God in the land of the living. I shall behold man no more, and the inhabiter of rest.\n"
	"My generation is taken away; and is wrapped together from me, as the tent of shepherds: My life is cut off, as by a weaver; whilst I yet began he cut me off: from morning until night thou wilt make an end of me.\n"
	"I hoped until morning, as a lion so hath he broken all my bones: From morning until evening thou wilt make an end of me.\n"
	"As a young swallow so will I cry. I will meditate as a dove: Mine eyes are weakened, looking on high: Lord I suffer violence, answer for me.\n"
	"What shall I say, or what shall he answer me, whereas himself hath done it?\n"
	"I will recount to thee all my years in the bitterness of my soul. Lord if man's life be such, and the life of my spirit in such things, thou shalt chasten me, and shalt quicken me.\n"
	"Behold in peace is my bitterness most bitter: But thou hast delivered my soul that it should not perish, thou hast cast all my sins behind thy back.\n"
	"Because hell shall not confess to thee, neither shall death praise thee: they that go down into the lake, shall not expect thy truth.\n"
	"The living the living he shall confess to thee, as I also this day: the father shall make thy truth known to the children.\n"
	"O Lord save me, and we shall sing our Psalms, all the days of our life in the house of our Lord.\n"
	"And Isaie commanded that they should take a lump of figs, & plaster it upon the wound, and he should be healed.\n"
	"And Ezechias said: What shall be the sign that I shall go up into the house of our Lord?";