const char* chap83 = "And our Lord spake to Moyses, saying: Go, get thee up from this place, thou and thy people which thou hast brought out of the Land of Aegypt, into the land whereof I sware to Abraham, Isaac, and Jacob, saying: To thy seed I will give it:\n"
	"and I will send an Angel thy precursor, that I may cast out the Chananeite, and Amorrheite, and Hetheite, and Pherezeite, and Heveite, and Jebuseite,\n"
	"and thou mayest enter into the land that floweth with milk and honey: for I will not go up with thee, because thou art a stiff-necked people: lest perhaps I destroy thee in the way.\n"
	"And the people hearing this very ill saying, mourned: and no man put on his ornaments after the custom.\n"
	"And our Lord said to Moyses: Speak to the children of Israel: Thou art a stiff-necked people, once I shall go up in the midst of thee, and shall destroy thee. Now presently lay away thy ornaments, that I may know what to do unto thee.\n"
	"Therefore the children of Israel laid away their ornaments from mount Horeb.\n"
	"Moyses also taking the tabernacle, pitched it without the camp a far off, and called the name thereof, The Tabernacle of covenant. And all the people, that had any question, went forth to the Tabernacle of covenant, without the camp.\n"
	"And when Moyses went forth to the tabernacle, all the people rose up, and every one stood in the door of his pavilion, and they beheld the back of Moyses, till he entered into the tabernacle.\n"
	"And when he was entered into the Tabernacle of covenant, the pillar of the cloud came down, and stood at the door, & he spake with Moyses,\n"
	"all they beholding that the pillar of the cloud stood at the door of the Tabernacle. And they stood, & adored at the doors of their tabernacles.\n"
	"And our Lord spake unto Moyses face to face, as a man is wont to speak to his friend. And when he returned into the camp, his minister Josue the son of Nun, a young man, departed not from the Tabernacle.\n"
	"And Moyses said to our Lord: Thou commandest me to lead forth this people, & doest not shew me whom thou wilt send with me, especially whereas thou hast said: I know thee by name, and thou hast found grace in my sight.\n"
	"If therefore I have found grace in thy sight, shew me thy face, that I may know thee, and may find grace before thine eyes, look upon thy people this nation.\n"
	"And our Lord said: My face shall go before thee, & I will give thee rest.\n"
	"And Moyses said: If thyself doest not go before, bring us not out of this place.\n"
	"For whereby shall we be able to know I and thy people, that we have found grace in thy sight, unless thou walk with us that we may be glorified of all peoples, that dwell upon the earth?\n"
	"And our Lord said to Moyses: This word also, which thou hast spoken, will I do: for thou hast found grace before me, and thyself I have known by name.\n"
	"Who said: Shew me thy glory.\n"
	"He answered: I will shew thee all good, and will call in the name of the Lord before thee: and I will have mercy on whom I will, and I will be merciful to whom it shall please me.\n"
	"And again he said: Thou canst not see my face: for man shall not see me, & live.\n"
	"And again: Behold, quoth he, there is a place with me, and thou shalt stand upon the rock.\n"
	"And when my glory shall pass, I will set thee in a hole of the rock, & protect thee with my right hand, until I pass:\n"
	"and I will take away my hand, and thou shalt see my back-parts: but my face thou canst not see,";