const char* chap830 = "Thus saith the Lord to my christ Cyrus, whose right hand I have taken to subdue the Gentiles before his face, and to turn the backs of kings, and to open the doors before him, and the gates shall not be shut.\n"
	"I will go before thee, and will humble the glorious of the earth: I will break the brazen gates, and will burst the iron bars.\n"
	"And I will give thee hidden treasures, and mysteries of secrets: that thou mayst know that I am the Lord, which call thy name, the God of Israel.\n"
	"For my servant Jacob, and Israel mine elect, and I have called thee by thy name: I have resembled thee, and thou hast not known me.\n"
	"I^ the Lord, & there is none else: beside me there is no God: I girded thee, and thou hast not known me:\n"
	"that they which are from the rising of the sun, and which are from the west may know, that there is none beside me, I^ the Lord, and there is none other,\n"
	"that form light, and create darkness, make peace, and create evil: I^ the Lord that do all these things.\n"
	"Drop dew ye heavens from above, and let the clouds rain the just: be the earth opened, & bud forth a saviour: & let justice spring up withal: I^ the Lord have created him.\n"
	"Woe to him that gainsayeth his maker, a sherd of the earthen pots: shall the clay say to him that fashioneth it: What makest thou, & thy work is without hands?\n"
	"Woe to him that saith to his father: Why doest thou beget? And to the woman: Why doest thou travail?\n"
	"Thus saith our Lord the holy one of Israel, the maker thereof: Ask me things to come: concerning my children & the work of my hands command you me.\n"
	"I made the earth: & man upon the same I have created: my hands stretched forth the heavens, and I have commanded all their host.\n"
	"I have raised him up to justice, & will direct all his ways: he shall build my city, & dismiss my captivity: not for price, nor for gifts, saith our Lord the God of hosts.\n"
	"Thus saith our Lord: The labour of Aegypt, and the merchandise of Aethiopia, and of Sabaim the high men shall pass to thee, & shall be thine: they shall walk after thee, they shall go bound with manacles: & they shall adore thee, & shall beseech thee: Only in thee is God, and there is no God beside thee.\n"
	"Verily thou art God hidden, the God of Israel a saviour.\n"
	"They are all confounded, and ashamed: the forgers of errors are gone together into confusion.\n"
	"Israel is saved in our Lord with eternal salvation: you shall not be confounded, and you shall not be ashamed for ever and ever.\n"
	"Because thus saith our Lord that created the heavens, the very God that formed the earth, and made it, the very maker thereof: he did not create it in vain: to be inhabited he formed it. I^ the Lord, and there is none other.\n"
	"I have not spoken in secret, in a dark place of the earth: I have not said to the seed of Jacob: Seek me in vain. I^ the Lord that speak justice, that declare right things.\n"
	"Gather ye together, and come, and approach together ye that are saved of the Gentiles: they have been ignorant that lift up the wood of their graven work, and ask of a god that saveth not.\n"
	"Declare ye, and come, and consult together: who hath made this to be heard from the beginning, from that time foretold this? Have not I^ the Lord, and there is no God besides but I? A just God, and that saveth^ there is none beside me.\n"
	"Be converted to me, and you shall be saved all ye ends of the earth: because I am God, and there is none other.\n"
	"I have sworn by myself, the word of justice shall proceed out of my mouth, and shall not return, because every knee shall be bowed to me, and every tongue shall swear.\n"
	"Therefore in our Lord, shall he say, are my justices and empire: they shall come to him, and all that resist him, shall be confounded.\n"
	"In our Lord shall all the seed of Israel be justified and praised.";