const char* chap836 = "Hear me ye that follow that which is just, and that seek our Lord: attend to the rock whence you are hewn out, & to the cave of the lake from the which you are cut out.\n"
	"Attend to Abraham your father, and to Sara that bare you: because I called him alone, and blessed him, & multiplied him.\n"
	"Our Lord therefore will comfort Sion, and will comfort all the ruins thereof: and he will make her desert as delicacies, and her wilderness as the garden of our Lord. Joy and gladness shall be found in it, giving of thanks, and voice of praise.\n"
	"Attend unto me, o my people, and my tribe hear ye me: because a law shall proceed from me, and my judgement shall rest to be a light of the peoples.\n"
	"My just one is nigh at hand, my saviour is gone forth, and mine arms shall judge peoples: the islands shall expect me, & shall patiently wait for mine arm.\n"
	"Lift up your eyes into heaven, and look down to the earth beneath: because the heavens shall melt as smoke, and the earth shall be worn away as a garment, and like to these things shall the inhabitants thereof perish: but my salvation shall be for ever, and my justice shall not fail.\n"
	"Hear me ye that know that which is just, my people which have my law in their heart: fear ye not the reproach of men, and be not afraid of their blasphemies.\n"
	"For as a garment so shall the worm eat them: and as wool, so shall the moth devour them, but my salvation shall be for ever, and my justice unto generations of generations.\n"
	"Arise, arise, put on strength o arm of our Lord: arise as in the old days, in the generations of worlds. Hast not thou strucken the proud, & wounded the dragon?\n"
	"Hast not thou dried the sea, the water of the vehement, which madest the depth of the sea a way, that the delivered might pass.\n"
	"And now they that are redeemed of our Lord shall return, and shall come into Sion praying, and joy everlasting upon their heads, they shall possess joy and gladness, sorrow and mourning shall fly away.\n"
	"I, even I myself will comfort you: who art thou that thou shouldest be afraid of a mortal man, and of the son of man, which as grass so shall wither?\n"
	"And thou hast forgotten our Lord thy maker, which stretched out the heavens, and founded the earth: and thou hast been afraid continually all the day at the face of his fury, which afflicted thee, and had prepared to destroy: where is now the fury of the affliction?\n"
	"He shall quickly come going to open, and he shall not kill unto utter destruction, neither shall his bread fail.\n"
	"But I am the Lord thy God which trouble the sea, and the waves thereof do swell, the Lord of hosts is my name.\n"
	"I have put my words in thy mouth, and in the shadow of my hand I have protected thee, that thou mightest plant the heavens, and found the earth, & mightest say to Sion: Thou art my people.\n"
	"Be lifted up, be lifted up, arise Jerusalem, which hast drunken of the hand of our Lord the cup of his wrath: even to the bottom of the cup of drowsiness hast thou drunk, even to the dregs.\n"
	"There is none that can uphold her of all the children that she hath born: and there is none that taketh her by the hand of all the children, that she hath brought up.\n"
	"There are two things which have happened to thee: who shall be sorry for thee? Spoil, and destruction, and famine, and the sword, who shall comfort thee?\n"
	"Thy children are thrown forth, they have slept in the head of all ways, as the oryx that is snared: full of the indignation of our Lord, of the rebuke of thy God.\n"
	"Therefore hear this poor little one, and drunken not of wine.\n"
	"Thus saith thy dominatour our Lord, and thy God, who hath fought for his people: Behold I have taken out of thy hand the cup of drowsiness, the bottom of the cup of mine indignation, thou shalt not add to drink it any more.\n"
	"And I will put it in their hand, that have humbled thee, and have said to thy soul: Bow down, that we may pass over: and thou hast laid thy body as the ground, and as a way to them that pass over?";