const char* chap837 = "Arise, arise, put on thy strength o Sion, put on the garments of thy glory o Jerusalem the city of the holy one: because the uncircumcised, and unclean shall add no more to pass by thee.\n"
	"Be shaken out of the dust, arise, sit up Jerusalem: loose the bonds of thy neck, o captive daughter of Sion.\n"
	"Because thus saith our Lord: You were sold for nought, and without silver you shall be redeemed.\n"
	"Because thus saith our Lord God: My people went down into Aegypt at the beginning to be a sojourner there: and Assur without any cause did oppress them.\n"
	"And now what have I here? Saith our Lord: because my people is taken away for nought. Their rulers do unjustly, saith our Lord, and continually all the day my name is blasphemed.\n"
	"For this cause shall my people know my name in that day: because I myself that spake, lo am present.\n"
	"How beautiful upon the mountains are the feet of him that evangelizeth & preacheth peace: of him that telleth good, preaching health, that saith to Sion: Thy God shall reign.\n"
	"The voice of thy watchmen, they have lifted up their voice, they shall praise together: because eye to eye they shall see when our Lord shall convert Sion.\n"
	"Rejoice, & praise together ye deserts of Jerusalem: because our Lord hath comforted his people: he hath redeemed Jerusalem.\n"
	"Our Lord hath prepared his holy arm in the sight of all the Gentiles: and all the ends of the earth shall see the salvation of our God.\n"
	"Depart, depart, go ye out from thence, touch not a polluted thing: go out of the midst of her, be cleansed ye that carry the vessels of our Lord.\n"
	"Because you shall not go out in tumult, neither with flight shall you make haste: for our Lord will go before you, and the God of Israel will gather you together.\n"
	"Behold my servant shall understand, he shall be exalted, and shall be lifted up, and shall be exceeding high.\n"
	"As many have been astonished upon thee, so shall his look among men be inglorious, and his form among the sons of men.\n"
	"He shall sprinkle many nations, kings shall shut their mouth upon him: because they to whom it was not told of him, have seen: and they that heard not have beheld.";