const char* chap842 = "The just perisheth, and there is none that considereth in his heart, & men of mercy are gathered away, because there is none that understandeth; for at the face of malice, is the just gathered away.\n"
	"Let peace come, let him rest in his bed that hath walked in his direction.\n"
	"But come you hither ye children of the witch, the seed of the adulterer, and of the harlot.\n"
	"Upon whom have you jested? Upon whom have you opened your mouth awide, and thrust out the tongue? Are not you wicked children, a lying seed?\n"
	"Which take comfort in the gods under every thick green tree, immolating your little ones in the torrents, under the high rocks?\n"
	"In the parts of the torrent is thy part, this is thy lot: and thou hast poured out libament to them, thou hast offered sacrifice, shall I not take indignation of these things?\n"
	"Upon an high and lofty mountain thou hast laid thy bed, and hast gone up thither to immolate hosts.\n"
	"And behind the door, and behind the post thou hast set thy memorial: because thou hast discovered thyself near me, and hast received an adulterer, thou hast enlarged thy bed, and made a covenant with them: thou hast loved their couch with open hand.\n"
	"And thou hast adorned thyself with royal ointment, and hast multiplied the gay paintings. Thou didst send thy legates far off, & wast humbled even to hell.\n"
	"In the multitude of thy way thou hast laboured; thou saidst not: I will rest: thou hast found life of thine own hand, therefore thou hast not asked.\n"
	"For whom, with careful reverence, hast thou feared, whereas thou hast lied, & hast not been mindful of me, nor thought on me in thy heart? Because I am holding my peace, and as it were not seeing, and thou hast forgotten me.\n"
	"I will declare thy justice, and thy works shall not profit thee.\n"
	"When thou shalt cry, let thy gathered together deliver thee, and the wind shall take them all away, a soft blast shall bear them away: But he that hath confidence in me, shall inherit the land, & shall possess my holy mount.\n"
	"And I will say: Make a way, give passage, turn out of the path, take away stumbling blocks out of the way of my people.\n"
	"Because thus saith the High & Eminent, that inhabiteth eternity: and his name is holy, dwelling in the high, and holy place, and with a contrite & humble spirit: that he may revive the spirit of the humble, and revive the heart of the contrite.\n"
	"For I will not contend for ever, neither will I be wrath unto the end: because the spirit shall proceed from my face, and breathings I will make.\n"
	"For the iniquity of his avarice I was angry, and have strucken him: I have hid my face from thee, and have taken indignation: and he hath gone wandering in the way of his own heart.\n"
	"I saw his ways, and have healed him, and reduced him, and have restored consolations unto him, and to them that mourn for him.\n"
	"I have created the fruit of the lips peace, peace to him that is far off, & that is near, saith our Lord, and I have healed him.\n"
	"But the impious are as it were the raging sea, which cannot be quiet, and the waves thereof overflow unto conculcation and mire.\n"
	"There is no peace to the impious, saith our Lord God.";