const char* chap844 = "Behold the hand of our Lord is not abridged that he cannot save, neither is his ear made heavy that it cannot hear.\n"
	"But your iniquities have divided between you and your God, and your sins have hid his face from you that he would not hear.\n"
	"For your hands are polluted with blood and your fingers with iniquity: your lips have spoken lie, and your tongue speaketh iniquity.\n"
	"There is none that doth invocate justice, neither is there any that judgeth truly: but they trust in things of nothing, and speak vanities: they have conceived labour, and brought forth iniquity.\n"
	"They have broken the eggs of asps, & have woven the spider's webs: he that shall eat of their eggs, shall die: and that which is nourished, shall be hatched into a cockatrice.\n"
	"Their webs shall not be for clothing, neither shall they be covered with their works: their works are unprofitable works, and the work of iniquity is in their hands.\n"
	"Their feet run to evil, & hasten to shed innocent blood: their cogitations are unprofitable cogitations: waste & destruction are in their ways.\n"
	"They have not known the way of peace, and there is no judgement in their steps: their paths are become crooked to them: every one that treadeth in them, knoweth not peace.\n"
	"For this cause is judgement far from us, & justice shall not apprehend us. We expected light, and behold darkness: brightness, & we have walked in darkness.\n"
	"We have groped as blind men for the wall, and as without eyes have feeled: we have stumbled at noon day as in darkness, in dark places as the dead.\n"
	"We all shall roar as bears, and as mourning doves we shall lament. We have expected judgement, and there is none: salvation, and it is far from us.\n"
	"For our iniquities are multiplied before thee and our sins have answered to us: because our wicked doings are with us, & our iniquities we have known,\n"
	"to sin and lie against our Lord: and we were turned away so that we went not after our God, that we spake calumny and transgression: we conceived, and spake from the heart words of lying.\n"
	"And judgement was turned backward, and justice stood far off: because truth hath fallen down in the street, and equity could not enter in.\n"
	"And truth grew into oblivion: and he that departed from evil, lay open to the prey: and our Lord saw, and it appeared evil in his eyes, because there is no judgement.\n"
	"And he saw that there is not a man: & he was astonished, because there is none to oppose himself: and his own arm saved to himself, and his justice it-self confirmed him.\n"
	"He is clothed with justice as with a breastplate, and is an helmet of salvation on his head: he is clothed with garments of revenge, and is covered as with a mantle of zeal.\n"
	"As unto revenge as it were unto retribution of indignation to his adversaries, and recompense to his enemies: he will repay the like to the islands.\n"
	"And they of the West shall fear the name of our Lord: and they of the rising of the sun, his glory: when he shall come as a violent stream, which the spirit of our Lord driveth:\n"
	"and there shall come a redeemer to Sion, and to them, that return from iniquity in Jacob, saith our Lord.\n"
	"This is my covenant with them, saith our Lord: My spirit that is in thee, and my words that I have put in thy mouth, shall not depart out of thy mouth, and out of the mouth of thy seed, & out of the mouth of thy seed's seed, saith our Lord, from this present and for ever.";