const char* chap848 = "Who is this that cometh from Edom, with dyed garments from Bosra, this beautiful one in his robe, going in the multitude of his strength? I that speak justice, and am a defender to save.\n"
	"Why then is thy clothing red, and thy garments as theirs that tread in the wine-press?\n"
	"I have trodden the press alone, and of the Gentiles there is not a man with me: I have trodden them in my fury, and have trodden them down in my wrath: & their blood is sprinkled upon my garments, & I have stained all my raiment.\n"
	"For the day of revenge is in my heart, the year of my redemption is come.\n"
	"I looked about, & there was no helper: I sought, and there was none to aid: and mine arm hath saved, and mine indignation it-self hath holpen me.\n"
	"And I have trodden down the peoples in my fury, and have inebriated them in mine indignation, and have drawn their strength down to the ground.\n"
	"I will remember the mercies of our Lord, the praise of our Lord for all things, that our Lord hath rendered to us, and for the multitude of the good things to the house of Israel, which he hath given them according to his indulgence, and according to the multitude of his mercies.\n"
	"And he said: But yet is my people, children that deny not: and he is become their saviour.\n"
	"In all their tribulation he was not troubled, and the Angel of his face saved them: in his love, and in his indulgence he redeemed them, and bare them, and lifted them up all the days of the world.\n"
	"But they provoked to wrath, and afflicted the spirit of his holy one: and he was turned to be their enemy, and he conquered them.\n"
	"And he remembered the days of the world of Moyses, and of his people: Where is he that brought them out of the sea, with the Pastors of his flock? Where is he that put in the midst of him the spirit of his holy one?\n"
	"He that brought out Moyses to the right hand by the arm of his majesty: that divided the waters before them, that he might make to himself an everlasting name.\n"
	"He that brought them out through the depths, as an horse in the desert that stumbled not.\n"
	"As the beast that goeth down in the plain field, the spirit of our Lord was their conductor: so didst thou bring thy people that thou mightest make thee a name of glory.\n"
	"Attend from heaven, and look from thy holy habitation, & of thy glory: where is thy zeal, and thy strength, the multitude of thy bowels, and of thy mercies? They have held back themselves toward me.\n"
	"For thou art our father, and Abraham hath not known us, and Israel hath been ignorant of us: thou, o Lord, art our father, our Redeemer, from the beginning is thy name.\n"
	"Why hast thou made us err, o Lord, from thy ways: hast thou hardened our heart, that we feared not thee? Return for thy servants, the tribes of thine inheritance.\n"
	"As nothing have they possessed thy holy people: our enemies have trodden down thy sanctification.\n"
	"We are become as in the beginning, when thou didst not rule over us, neither was thy name invocated upon us.";