const char* chap851 = "Thus saith our Lord: Heaven is my seat, and the earth my foot stool: what is this house that you will build to me? And what is this place of my rest?\n"
	"My hand hath made all these things, & all these things have been done, saith our Lord. But to whom shall I have respect, but to the poor little one, & the contrite of spirit, and him that trembleth at my words?\n"
	"He that immolateth an oxe, is as he that should slay a man: he that killeth a sheep in sacrifice, as he that should brain a dog: he that offereth oblation, as he that should offer swine's blood: he that remembereth frankincense, as he that should bless an idol. All these things have they chosen in their ways, and in their abominations their soul is delighted.\n"
	"Wherefore I also will choose their delusions: and the things that they feared, I will bring to them: because I called, and there was none that would answer: I have spoken, and they heard not: & they have done evil in mine eyes, and have chosen the things that I would not.\n"
	"Hear the word of our Lord, ye that tremble at his word: your brethren that hate you, and reject you for my name sake, have said: Let the Lord be glorified, & we shall see in your joy: but they shall be confounded.\n"
	"A voice of people from the city, a voice from the temple, the voice of our Lord repaying retribution to his enemies.\n"
	"Before she travailed, she brought forth, before her time came to be delivered, she brought forth a man child.\n"
	"Who ever heard such a thing? & who hath seen the like to this? Why, shall the earth travail in one day? Or shall a nation be brought forth together, because Sion hath travailed, & brought forth her children?\n"
	"Shall not I that make others to bring forth children, myself bring forth, saith the Lord? Shall I, that give generation to others, be barren, saith the Lord thy God?\n"
	"Rejoice with Jerusalem, & be joyful in her all ye that love her: be glad with her in gladness all ye, that mourn upon her,\n"
	"that you may suck, & be filled of the breast of her consolation: that you may milk, & flow with delights in all manner of her glory.\n"
	"Because thus saith our Lord: Behold I will decline upon her as it were a flood of peace, and as a torrent overflowing the glory of the Gentiles, which you shall suck: at the breasts, you shall be carried, & upon the knees they shall speak you fair.\n"
	"As if the mother would speak one fair, so will I comfort you, & in Jerusalem you shall be comforted.\n"
	"You shall see, & your heart shall rejoice, and your bones shall spring as an herb, and the hand of our Lord shall be known to his servants, & he shall be wrath with his enemies.\n"
	"Because lo our Lord will come in fire, & his chariots as a whirlwind, to render his fury in indignation, & his rebuking in flame of fire:\n"
	"because our Lord shall judge in fire, & in his sword to all flesh, and the slain of our Lord shall be multiplied,\n"
	"they that were sanctified, & thought themselves clean in the gardens behind the gate within, they that did eat swine's flesh, and abomination, and the mouse: they shall be confounded, saith our Lord.\n"
	"But I know their works, and their cogitations: I come that I may gather together, with all nations and tongues: and they shall come and shall see my glory.\n"
	"And I will put a sign in them, and I will send of them, that shall be saved, to the Gentiles into the sea, into Afrike, & Lydia, them that hold the arrow: into Italy, and Greece; to the islands far off, to them that have not heard of me, and have not seen my glory. And they shall shew forth my glory to the Gentiles:\n"
	"and they shall bring all your brethren of all nations a gift to our Lord, upon horses, and in chariots, & in horse-litters, & on mules, and in coaches, to my holy mountain Jerusalem, saith our Lord, as if the children of Israel should bring in a gift in a clean vessel into the house of our Lord.\n"
	"And I will take of them to be Priests, & Levites, saith our Lord.\n"
	"Because as new heavens, and a new earth, which I make to stand before me, saith our Lord: so shall your seed stand, and your name.\n"
	"And there shall be month after month, and sabbath after sabbath: all flesh shall come to adore before my face, saith our Lord.\n"
	"And they shall go out, and see the carcasses of the men, that have transgressed against me: their worm shall not die, and their fire shall not be quenched: and they shall be even unto satiety of sight to all flesh.";