const char* chap853 = "And the word of our Lord was made to me, saying:\n"
	"Go, and cry in the ears of Jerusalem, saying: Thus saith our Lord: I have remembered thee, pitying thy youth, and the charity of thy despousing, when thou didst follow me in the desert, in a land that is not sown.\n"
	"Israel is holy to our Lord, the first fruits of his fruits: all they that do devour it do sin: evil shall come upon them, saith our Lord.\n"
	"Hear ye the word of our Lord, o house of Jacob, and all ye kindreds of the house of Israel:\n"
	"thus saith our Lord: What iniquity have your fathers found in me, that they have made themselves far from me, and have walked after vanity, and are become vain?\n"
	"And they have not said: Where is our Lord, that made us come up out of the land of Aegypt, that led us through the desert, through a land inhabitable and without way, through a land of thirst, & the image of death, through a land, wherein no man walked, nor any man dwelt?\n"
	"And I brought you into the land of Carmel, that you might eat the fruit thereof, and the best things thereof: and being entered in, you have contaminated my land, & made mine inheritance an abomination.\n"
	"The Priests have not said: Where is our Lord? And they that held the law knew me not: and the Pastors have transgressed against me, and the Prophets have prophesied in Baal, and have followed idols.\n"
	"Therefore will I yet contend in judgement with you, saith our Lord, and I will plead with your children.\n"
	"Pass ye to the isles of Cethim, and see: and send into Cedar, and consider earnestly, & see if there hath the like thing been done.\n"
	"If a nation hath changed their gods, & surely they are not gods: but my people hath changed their glory into an idol.\n"
	"Be astonished, o heavens, upon this, and o gates thereof be ye desolate exceedingly, saith our Lord.\n"
	"For two evils hath my people done, Me they have forsaken the fountain of living water, & have digged to themselves cisterns: broken cisterns, that are not able to hold waters.\n"
	"Why, is Israel a bondman, or a servant born in the house? Why then is he become a prey?\n"
	"The lions have roared upon him, & have given their voice, they have made his land a wilderness: his cities are burnt up, & there is none to dwell in them.\n"
	"The children also of Memphis and Taphnes have deflowered thee, even to the crown of the head.\n"
	"Is not this done to thee, because thou didst forsake the Lord thy God at that time, when he led thee by the way?\n"
	"And now what wilt thou in the way of Aegypt, to drink the troubled water? And what hast thou to do with the way of the Assyrians, to drink the waters of the river?\n"
	"Thy malice shall reprove thee, and thine apostasy shall rebuke thee. Know thou, & see that it is an evil & a bitter thing for thee, to have left the Lord thy God, & that my fear is not with thee, saith our Lord the God of hosts.\n"
	"From the beginning thou hast broken my yoke, thou hast burst my bonds, & thou saidst: I will not serve. For on every little high hill, & under every green thick tree thou wast laid down as an harlot.\n"
	"But I planted thee an elect vineyard, all true seed: how then art thou turned unto me into that which is depraved, o strange vineyard?\n"
	"If thou shalt wash thyself with nitre, and multiply to thyself the herb borith, thou art spotted in thine iniquity before me, saith our Lord God.\n"
	"How sayst thou: I am not polluted, I have not walked after Baalim? See thy ways in the valley, know what thou hast done: a swift courser that rideth his ways.\n"
	"The wild Ass accustomed to the wilderness in the desire of his soul, hath drawn the wind of his love: none shall turn her away: all that seek her shall not fail: in her monthly flowers they shall find her.\n"
	"Stay thy foot from nakedness, and thy throat from thirst. And thou saidst: I have despaired, no, I will not do it: for I have loved strangers, and I will walk after them.\n"
	"As the thief is confounded when he is taken, so is the house of Israel confounded, they and their kings, the princes and priests, and their prophets,\n"
	"saying to wood: Thou art my father: and to stone: Thou hast begotten me: they have turned the back to me, & not the face: and in the time of their affliction they will say: Arise, and deliver us.\n"
	"Where are the gods, whom thou hast made to thee? Let them arise and deliver thee in the time of thine affliction: for according to the number of thy cities were thy gods, o Juda.\n"
	"What will you contend with me in judgement? You have all forsaken me, saith our Lord.\n"
	"In vain have I strucken your children, they have not received discipline: your sword hath devoured your Prophets, as a wasting lion is your generation.\n"
	"See ye the word of our Lord: why, am I become a wilderness to Israel, or a lateward springing land? Why then hath my people said: We have revolted, we will no more come to thee?\n"
	"Will a Virgin forget her ornament, or a bride the stomacher of her breast? But my people hath forgotten me innumerable days.\n"
	"Why dost thou endeavour to shew thy way good to seek love, which moreover also hast taught thy malices to be thy ways.\n"
	"And in thy wings is found the blood of the souls of the poor and innocents? Not in ditches have I found them, but in all places, which before I have mentioned.\n"
	"And thou hast said: I am without sin and innocent: and therefore let thy fury be turned away from me. Behold, I will contend with thee in judgement, because thou hast said: I have not sinned.\n"
	"How vile art thou become exceedingly, iterating thy ways! And thou shalt be confounded of Aegypt, as thou art confounded of Assur.\n"
	"For from hence also thou shalt go, & thy hands shall be upon thy head: because the Lord hath destroyed thy confidence, and thou shalt have nothing prosperous therein.";