const char* chap855 = "If thou wilt return, o Israel, saith our Lord, return to me: if thou wilt take away thy stumbling blocks from my face, thou shalt not be moved.\n"
	"And thou shalt swear: Our Lord liveth, in truth, & in judgement, and in justice: and the Gentiles shall bless him, & shall praise him.\n"
	"For thus saith our Lord to the man of Juda, and to Jerusalem: Make unto you new fallow ground, & sow not upon thorns:\n"
	"be circumcised to our Lord, and take away the prepuces of your hearts, ye men of Juda, and inhabitants of Jerusalem: lest perhaps mine indignation go forth as fire, and be kindled, & there be none that can quench it: because of the malice of your cogitations.\n"
	"Declare ye in Juda, and make it heard in Jerusalem: speak, and sound with the trumpet in the land: cry strongly, and say: Assemble yourselves, & let us enter into the fenced cities,\n"
	"lift up the sign in Sion. Take courage, stand not, because I do bring evil from the North, & great destruction.\n"
	"The Lion is come up out of his den, and the robber of the Gentiles hath lifted up himself: he is come forth out of his place, that he may make thy land as a wilderness: thy cities shall be wasted, remaining without an inhabiter.\n"
	"For this gird yourselves with cloths of hair, mourn and howl: because the wrath of the fury of our Lord is not turned away from us.\n"
	"And it shall be in that day, saith our Lord: The heart of the king shall perish, & the heart of the Princes: and the Priests shall be astonished, and the Prophets shall be amazed.\n"
	"And I said: Alas, alas, alas, o Lord God, hast thou then deceived this people & Jerusalem, saying: You shall have peace: and behold the sword hath come even to the soul?\n"
	"At that time it shall be said to this people, & to Jerusalem: A burning wind in the ways, that are in the desert of the way of the daughter of my people, not to fan and to purge.\n"
	"A full spirit from these shall come to me: and now I will speak my judgement with them.\n"
	"Behold he shall come in a cloud, and his chariots as a tempest: his horses are swifter than eagles: woe unto us, because we are destroyed\n"
	"Wash thy heart from malice, o Jerusalem, that thou mayst be saved: how long shall hurtful cogitations abide in thee?\n"
	"For a voice of one declaring from Dan, and notifying the idol from mount Ephraim.\n"
	"Say ye to the Gentiles: lo it is heard in Jerusalem, that there come keepers from a far country, and sound their voice upon the cities of Juda.\n"
	"They are set upon her round about, as the keepers of fields: because she hath provoked me to wrath, saith our Lord.\n"
	"Thy ways and thy cogitations have done these things to thee: this thy malice, because it is bitter, because it hath touched thy heart.\n"
	"My belly, my belly asketh, the senses of my heart are troubled in me, I will not hold my peace, because my soul hath heard the voice of the trumpet, the cry of battle.\n"
	"Destruction is called upon destruction, and all the earth is wasted: my tents are wasted quickly, suddenly my skins.\n"
	"How long shall I see one that flyeth away, shall I hear the voice of the trumpet?\n"
	"Because my foolish people have not known me: they are unwise children, and without wit: they are wise to do evils, but to do well they have not known.\n"
	"I beheld the earth, and lo it was void, and a thing of nothing: and the heavens, & there was no light in them.\n"
	"I saw the mountains, and lo they were moved: and all the little hills were troubled.\n"
	"I beheld, and there was not a man: and every fowl of the air was departed.\n"
	"I looked, and behold Carmel made desert: and all the cities thereof were destroyed at the face of our Lord, and at the face of the wrath of his fury.\n"
	"For thus saith our Lord: All the land shall be desolate, but yet I will not make a consummation.\n"
	"The earth shall mourn, and the heavens shall lament from above: because I have spoken, I have purposed, and it hath not repented me, neither am I turned away from it.\n"
	"At the voice of the horseman, and the archer, all the city is fled: they have entered into high places, and have climbed the rocks: all the cities are forsaken, and there dwelleth not a man in them.\n"
	"But thou being wasted, what wilt thou do? When thou shalt clothe thyself in scarlet, when thou shalt be adorned with golden jewels, and shalt paint thine eyes with stibic stone, thou shalt be trimmed in vain: thy lovers have contemned thee, they will seek thy life.\n"
	"For I have heard the voice as of a travailing woman, anguishes as of a woman in labour of child. The voice of the daughter of Sion, amongst them that die, and stretch forth their hands: woe is me, because my soul hath fainted for them that are slain.";