const char* chap859 = "At that time, saith our Lord, they will cast out the bones of the kings of Juda, and the bones of the Princes thereof, and the bones of Priests, and the bones of the Prophets, and the bones of them that inhabit Jerusalem, out of their sepulchres.\n"
	"And they shall spread them abroad in the sun, and the moon, and all the host of heaven, which they have loved, and which they have served, & after which they have walked, and which they have sought, and adored: they shall not be gathered, and they shall not be buried: they shall be as a dunghill upon the face of the earth.\n"
	"And they shall choose rather death than life, all that shall be remaining of this wicked kindred in all places, which are left, to the which I have cast them out, saith the Lord of hosts.\n"
	"And thou shalt say to them: Thus saith our Lord: Shall not he that falleth rise again? And he that is turned away, shall he not turn again?\n"
	"Why then is this people in Jerusalem turned away with a contentious revolting? They have apprehended lying, and would not return.\n"
	"I attended, and harkened: no man speaketh that which is good, there is none that doth penance for his sin, saying: What have I done? They are all turned to their own course, as an horse going with violence to battle.\n"
	"The kite in the heaven hath known her time: the turtle, and the swallow, and the stork have observed the time of their coming: but my people have not known the judgement of the Lord.\n"
	"How say you: We are wise, and the law of our Lord is with us? In very deed the lying pen of the Scribes hath wrought lying.\n"
	"The wise are confounded, they are terrified and taken: for they have cast away the word of our Lord, and there is no wisdom in them.\n"
	"Therefore will I give their women to strangers, their fields to inheritors: because from the least even to the greatest all follow avarice: from the Prophet even to the Priest all make lies.\n"
	"And they healed the destruction of the daughter of my people to ignominy, saying: Peace, peace, when there was not peace.\n"
	"They are confounded, because they have done abomination: yea rather they are not confounded with confusion, and they have not known how to blush: therefore shall they fall among them that fall, in the time of their visitation they shall fall, saith our Lord.\n"
	"Gathering I will gather them together, saith our Lord, there is no grape in the vines, and there are no figs on the figtree, the leaf is fallen down: and I have given them the things that are passed.\n"
	"Why do we sit? Come together and let us enter into the fenced city, and let us be silent there: because the Lord our God hath made us to be silent, and hath given us water of gall for drink: for we have sinned to our Lord.\n"
	"We expected peace and there was no good: a time of medicine and behold fear.\n"
	"From Dan was the snoring noise of his horses heard, with the voice of the neighings of his fighting horses all the land was moved: and they came and devoured the land, and the fullness thereof: the city & the inhabitants thereof.\n"
	"For behold I will send you serpents basilisks, for which there is no enchantment: and they shall bite you, saith our Lord.\n"
	"My sorrow is above sorrow, my heart mourning within me.\n"
	"Behold the voice of the daughter of my people from a far country: Is not our Lord in Sion: or is not her king in her? Why then have they provoked me to wrath in their sculptiles, & in strange vanities?\n"
	"The harvest is past, summer is ended: and we are not saved.\n"
	"For the affliction of the daughter of my people I am afflicted, and made sorrowful, astonishment hath taken me.\n"
	"Is there no rosin in Galaad? Or is there no physician there? Why then is not the wound of the daughter of my people closed?";