const char* chap860 = "Who will give water to my head, and to mine eyes a fountain of tears? And I will weep day and night for the slain of the daughter of my people.\n"
	"Who will give me in the wilderness an inn of wayfaring men, and I will forsake my people, and depart from them? Because they are all adulterers, an assembly of transgressors.\n"
	"And they have bent their tongue, as a bow of lying and not of truth: they have taken courage in the land, because they have proceeded from evil to evil, and me they have not known, saith our Lord.\n"
	"Let every man take heed to himself of his neighbour, and in every brother of his, let him not have affiance: because every brother supplanting will supplant, and every friend will walk deceitfully.\n"
	"And man shall scorn his brother, and they will not speak truth: for they have taught their tongue to speak lies: they have laboured to do unjustly.\n"
	"Thine inhabitation is in the midst of deceit: in deceit they have refused to know me, saith our Lord.\n"
	"Therefore thus saith the Lord of hosts: Behold I will melt, and will try them: for what else shall I do at the face of the daughter of my people?\n"
	"There tongue is a wandering arrow, it hath spoken guile: in his mouth he hath spoken peace with his friend, and secretly he layeth wait for him.\n"
	"Shall I not visit upon these things, saith our Lord? Or upon such a nation shall not my soul be revenged?\n"
	"Upon the mountains I will take up weeping and lamentation, & upon the beautiful places of the desert, mourning: because they are burnt, for that there is not a man that passeth through: and they have not heard the voice of the owner: from the fowl of the air unto the beasts they are gone away & departed.\n"
	"And I will make Jerusalem to be heaps of sand, and dens of dragons: and I will give the cities of Juda into desolation, because there is not an inhabiter.\n"
	"Who is a wise man, that can understand this, & to whom the word of the mouth of our Lord may be made, that he may declare this, why the earth hath perished, and is burnt as a desert, because there is none that passeth through?\n"
	"And our Lord said: Because they have forsaken my law, which I gave them, and have not heard my voice, & have not walked in it.\n"
	"And they have gone after the perversity of their own heart, and after Baalim, which they learned of their fathers.\n"
	"Therefore thus saith the Lord of hosts the God of Israel: Behold I will feed this people with wormwood, and give them water of gall to drink.\n"
	"And I will disperse them in the Nations, which they & their fathers have not known: & I will send the sword after them, till they be consumed.\n"
	"Thus saith the Lord of hosts the God of Israel: Consider & call ye lamenting women, & let them come: & send to them that are wise, and let them make haste:\n"
	"let them hasten & take up a lamentation upon us: let our eyes shed tears, & our eye-lids run down with waters.\n"
	"Because a voice of lamentation is heard from Sion: How are we wasted and confounded exceedingly? Because we have left the land, because our tabernacles are cast down.\n"
	"Hear therefore ye women the word of our Lord: and let your ears take the word of his mouth: and teach your daughters lamentation: & every one her neighbour^ mourning:\n"
	"because death is come up through our windows, it is entered into our houses, to destroy the children from without, the young men out of the streets.\n"
	"Speak: Thus saith our Lord: and the carcass of man shall fall as dung upon the face of the country, and as a grass behind the back of the mower, and there is none to gather it.\n"
	"Thus saith our Lord: Let not the wiseman glory in his wisdom, & let not the strong man glory in his strength, & let not the rich man glory in his riches:\n"
	"but he that glorieth, let him glory in this, to understand & know me, because I am the Lord that do mercy and judgement, & justice in the earth: for these things please me, saith our Lord\n"
	"Behold, the days come, saith our Lord; & I will visit upon every one that hath the prepuce circumcised.\n"
	"upon Aegypt, and upon Juda, & upon Edom, and upon the children of Ammon, & upon Moab, & upon all that have their hair polled, dwelling in the desert: because all nations have the prepuce, but all the house of Israel are uncircumcised in the heart.";