const char* chap861 = "Hear ye the word, which our Lord hath spoken concerning you, o house of Israel.\n"
	"Thus saith our Lord: According to the ways of the Gentiles learn not: and of the signs of heaven, which the heathen fear, be not afraid:\n"
	"Because the laws of the people are vain: because the work of the hand of the artificer hath cut a tree out of the forest with an axe:\n"
	"with silver & gold he hath decked it: with nails and hammers he hath compacted it, that it fall not asunder.\n"
	"They are framed after the similitude of a palm tree, & shall not speak: being carried they shall be removed, because they are not able to go. Therefore fear them not, because they can neither do ill nor well.\n"
	"There is not the like unto thee o Lord: thou art great, and great is thy name in strength.\n"
	"Who shall not fear thee o King of Nations? For thine is the glory: among all the wise of the Gentiles, & in all their kingdoms there is none like unto thee.\n"
	"They shall be proved altogether unwise & foolish: the doctrine of their vanity is wood.\n"
	"Silver wrapped up is brought from Tharsis, and gold from Ophaz: the work of the artificer, & the hands of the coppersmith: hyacinth and purple are their clothing: all these things are the work of artificers.\n"
	"But our Lord is the true God: he is the living God, and the King everlasting: at his indignation the earth shall be moved: and the Gentiles shall not sustain his threatening.\n"
	"Thus then you shall say to them: The gods that made not heaven and earth, let them perish from off the earth, and from these places, that are under heaven.\n"
	"He that maketh the earth in his strength, prepareth the world in his wisdom, & with his prudence stretcheth out the heavens.\n"
	"At his voice he giveth a multitude of waters in the heaven, & lifteth up the clouds from the ends of the earth: he maketh lightnings into rain, & bringeth forth the wind out of his treasures.\n"
	"Every man is become a fool for knowledge, every crafts-man is confounded in the sculptile: because it is false that he hath melted, and there is no spirit in them.\n"
	"They are vain things, and a work worthy to be laughed at: in the time of their visitation they shall perish.\n"
	"The portion of Jacob is not like to these: for it is he that formed all things: and Israel is the rod of his inheritance: the Lord of hosts is his name.\n"
	"Gather thy confusion out of the land, thou that dwellest in besiege.\n"
	"Because thus saith our Lord: Behold I will cast forth far off the inhabitants of the land at this time: & I will afflict them, so that they may not be found.\n"
	"Woe is me for my destruction, my plague is very sore. But I said. Truly this is mine infirmity, and I will bear it.\n"
	"My tabernacle is wasted, all my cords are broken in sunder: my children are gone out from me, and are not: there is none to stretch out my tent any more, & to set up my curtains.\n"
	"Because the Pastors have done foolishly, & have not sought our Lord: therefore have they not understood, and all their flock is dispersed.\n"
	"Lo the voice of a bruit cometh, a great commotion from the land of the North: to make the cities of Juda a desert, and an habitation of dragons.\n"
	"I know Lord, that man's way is not his own: neither is it in a man to walk, and to direct his steps.\n"
	"Correct me o Lord, but yet in judgement: and not in thy fury, lest perhaps thou bring me to nothing.\n"
	"Pour out thine indignation upon the Gentiles, that have not known thee, and upon the Provinces, that have not invocated thy name: because they have eaten Jacob, and devoured him, and consumed him, and have dissipated his glory.";