const char* chap862 = "The word that was made from our Lord to Jeremy, saying:\n"
	"Hear ye the words of this covenant, and speak to the men of Juda, and to the inhabitants of Jerusalem,\n"
	"and thou shalt say to them: Thus saith our Lord the God of Israel: Cursed is the man that shall not hear the words of this covenant,\n"
	"which I commanded your fathers in the day, that I brought them out of the Land of Aegypt, out of the iron furnace, saying: Hear ye my voice, and do all things, that I command you: and you shall be my people, and I will be your God.\n"
	"That I may raise up the oath, which I sware to your fathers, that I would give them a land flowing with milk and honey, as is this day. And I answered, and said: Amen Lord.\n"
	"And our Lord said to me: Cry aloud all these words in the cities of Juda, and without Jerusalem, saying: Hear ye the words of this covenant, and do them:\n"
	"because contesting I did contest your fathers in the day, that I brought them out of the Land of Aegypt even to this day: arising early I contested, and said: Hear ye my voice:\n"
	"and they heard not, nor inclined their ear: but went every one in the perversity of his own wicked heart: and I brought upon them all the words of this covenant, which I commanded them to do, and they did not.\n"
	"And our Lord said to me: Conspiracy is found in the men of Juda, and in the inhabitants of the men of Jerusalem.\n"
	"They are returned to the former iniquities of their fathers, which would not hear my words: and these therefore have gone after strange gods, to serve them: the house of Israel, and the house of Juda hath made void my covenant, which I made with their fathers.\n"
	"For which thing thus saith our Lord: Behold I will bring in evils upon them, out of which they shall not be able to go forth: and they shall cry to me, and I will not hear them.\n"
	"And the cities of Juda, and the inhabitants of Jerusalem shall go, and cry to the gods, unto whom they sacrificed, and they shall not save them in the time of their affliction.\n"
	"For according to the number of thy cities were thy gods o Juda: and according to the number of the ways of Jerusalem thou didst set altars of confusion, altars to sacrifice to Baalim.\n"
	"Thou therefore pray not for this people, and take not to thee praise and prayer for them: because I will not hear in the time of their cry unto me, in the time of their affliction.\n"
	"What is it, that my beloved hath in my house done much wickedness? Shall the holy flesh take away from thee thy malices: in which thou hast boasted?\n"
	"The Lord hath called thy name, a plentiful olive tree, fair, fruitful, beautiful: at the voice of a word, a great fire flamed up in it, and the shrubs thereof are burnt.\n"
	"And the Lord of hosts that planted thee, hath spoken evil upon thee: for the evils of the house of Israel, and of the house of Juda, which they have done to themselves, to provoke me, in offering to Baalim.\n"
	"But thou Lord hast shewed me, and I have known: thou hast shewed me their studies.\n"
	"And I as a mild lamb, that is carried to a victim: and I knew not that they devised counsels against me, saying: Let us cast wood on his bread, & rase him out of the land of the living, and let his name be mentioned no more.\n"
	"But thou o Lord of Sabaoth, which judgest justly, & provest the reins & the hearts, let me see thy revenge of them: for to thee I have revealed my cause.\n"
	"Therefore thus saith the Lord to the men of Anathoth, which seek thy life, and say: Thou shalt not prophesy in the name of our Lord, and thou shalt not die in our hands.\n"
	"Therefore thus saith the Lord of hosts: Behold I will visit upon them: their young men shall die by the sword, their sons and their daughters shall die in famine.\n"
	"And there shall be no remains of them: for I will bring in evil upon the men of Anathoth, the year of their visitation.";