const char* chap864 = "Thus saith our Lord to me: Go, and get thee a girdle of linen, and thou shalt put it about thy loins, and shalt not put it into water.\n"
	"And I got a girdle according to the word of our Lord, and put it about my loins.\n"
	"And the word of our Lord was made to me the second time, saying:\n"
	"Take the girdle, which thou hast gotten, which is about thy loins, and rising go to Euphrates, and hide it there in an hole of the rock.\n"
	"And I went, and hid it in Euphrates, as our Lord had commanded me.\n"
	"And it came to pass after many days, our Lord said to me: Arise, go to Euphrates: and take from thence the girdle, which I commanded thee that thou shouldst hide it there.\n"
	"And I went to Euphrates, and digged, and took the girdle out of the place, where I had hid it: and behold the girdle was rotten, so that it was fit for no use.\n"
	"And the word of our Lord was made to me, saying:\n"
	"Thus saith our Lord: so will I make the pride of Juda, and the great pride of Jerusalem.\n"
	"This most wicked people, which will not hear my words, and walk in the perversity of their heart: & have gone after strange gods to serve them, and to adore them: and they shall be as this girdle, which is fit for no use.\n"
	"For as the girdle cleaveth to the loins of a man, so have I fast joined to me all the house of Israel, and all the house of Juda, saith our Lord: that they might be my people, and name, and praise, and glory: & they heard not.\n"
	"Thou shalt say therefore unto them this word: Thus saith our Lord the God of Israel: Every bottle shall be filled with wine. And they shall say to thee: Why, are we ignorant that every bottle shall be filled with wine?\n"
	"And thou shalt say to them: Thus saith our Lord: Behold I will fill all the inhabitants of this land, & the kings that of the stock of David sit upon his throne, & the Priests, & the Prophets, & all the inhabitants of Jerusalem, with drunkenness.\n"
	"And I will disperse them every man from his brother, and the fathers and sons together, saith our Lord: I will not spare, and I will not yield: neither will I have mercy not to destroy them.\n"
	"Hear ye, and give ear. Be not elevated, because our Lord hath spoken.\n"
	"Give ye glory to our Lord your God, before it wax dark, and before your feet stumble at the dark mountains: you shall look for light, and he will turn it into the shadow of death, & into darkness.\n"
	"But if you will not hear this, in secret my soul shall weep because of the pride: weeping it shall weep, and mine eye shall drop tears, because the flock of our Lord is taken.\n"
	"Say to the king, and to her that ruleth: Be humbled, sit down: because the crown of your glory is come down from your head.\n"
	"The cities of the South are shut, and there is none that may open them: all Juda is transported with a perfect transmigration.\n"
	"Lift up your eyes and see, you that come from the North, where is the flock that is given thee, thy noble cattle?\n"
	"What wilt thou say when he shall visit thee? For thou hast taught them against thee, and instructed them against thine own head: shall not sorrows apprehend thee, as a woman in travail?\n"
	"And if thou shalt say in thy heart: why are these things come unto me? For the multitude of thine iniquity, thy more shamely parts are discovered: the soles of thy feet are polluted.\n"
	"If the Aethiopian can change his skin, or the leopard his spots: you also can do well, when you have learned evil.\n"
	"And I will scatter them as stubble, which is violently taken with the wind in the desert.\n"
	"This is thy lot, and portion of thy measure from me, saith our Lord, because thou hast forgotten me, and hast trusted in lying.\n"
	"Wherefore I have also made bare thy thighs against thy face, and thine ignominy hath appeared,\n"
	"thine adulteries, and thy neighing, the wickedness of thy fornication: upon the little hills in the field I have seen thine abominations. Woe to thee Jerusalem, thou wilt not be made clean after me: how long yet?";