const char* chap874 = "Woe to the Pastors, that destroy and tear the flock of my pasture, saith our Lord.\n"
	"Therefore thus saith our Lord the God of Israel to the Pastors, that feed my people: You have scattered my flock, and cast them out, & have not visited them: Behold I will visit upon you the malice of your studies, saith our Lord.\n"
	"And I will gather together the remnant of my flock out of all lands, into which I shall have cast them out: and I will make them return to their fields, and they shall increase and be multiplied.\n"
	"And I will raise up Pastors over them, and they shall feed them: they shall fear no more, and they shall not dread: and none shall be to seek of the number, saith our Lord.\n"
	"Behold the days come, saith our Lord: and I will raise up to David a just branch: and he shall reign a king, and shall be wise: and he shall do judgement and justice in the earth.\n"
	"In those days shall Juda be saved, and Israel shall dwell confidently: and this is the name that they shall call him: The Lord our just one.\n"
	"For this cause behold the days come, saith our Lord, and they shall say no more: Our Lord liveth, that brought forth the children of Israel out of the Land of Aegypt:\n"
	"but: Our Lord liveth, that hath brought forth, and brought hither the seed of the house of Israel from the Land of the North, and out of all the lands, to which I had cast them out: and they shall dwell in their own land.\n"
	"To the Prophets: My heart is broken in the midst of me, all my bones have trembled: I am become as a drunken man, and as a man wet with wine, at the presence of our Lord, and at the presence of his holy words.\n"
	"Because the land is replenished with adulterers, because the land hath mourned by reason of malediction, the fields of the desert are withered: and their course is become evil, and their strength unlike.\n"
	"For the Prophet and the Priest are polluted: and in my house I have found their evil, saith our Lord.\n"
	"Therefore their way shall be as slipper ground in the dark: for they shall be driven forth, and fall therein: for I will bring evils upon them, the year of their visitation, saith our Lord.\n"
	"And in the Prophets of Samaria I have seen foolishness: They Prophesied in Baal, and deceived my people Israel.\n"
	"And in the Prophets of Jerusalem I saw the similitude of adulterers, and the way of lying: and they strengthened the hands of the most wicked, that no man would return from his malice: they are all become unto me as Sodoma, and the inhabitants thereof as Gomorrha.\n"
	"Therefore thus saith the Lord of hosts to the Prophets: Behold I will feed them with wormwood, and will give them gall to drink, for from the Prophets of Jerusalem is pollution gone forth upon all the land.\n"
	"Thus saith the Lord of hosts: Hear not the words of the Prophets, that prophesy unto you, and deceive you: they speak the vision of their own heart, not from the mouth of the Lord.\n"
	"They say to them that blaspheme me: Our Lord hath spoken: Peace shall be to you, and to every one that walketh in the perversity of his own heart, they have said: There shall no evil come upon you.\n"
	"For who hath been present in the counsel of our Lord, and hath seen and heard his word? Who hath considered his word, & heard it?\n"
	"Behold the whirlwind of the Lord's indignation shall come forth, and a tempest breaking out: it shall come upon the head of the impious.\n"
	"The fury of the Lord shall not return till he do it, and until he accomplish the cogitation of his heart: in the later days you shall understand his counsel.\n"
	"I sent not the Prophets, and they ran: I spake not to them, and they Prophesied.\n"
	"If they had stood in my counsel, and made my words known to my people, I had verily turned them from their evil way, and from their most wicked cogitations.\n"
	"Am I God near hand thinkest thou, saith our Lord? And not God far off?\n"
	"Shall a man be hid in secrets: and shall not I see him, saith our Lord? Why, do not I fill heaven and earth, saith our Lord?\n"
	"I have heard what the Prophets have said, prophesying in my name lies, and saying: I have dreamed, I have dreamed.\n"
	"How long is this in the heart of the Prophets prophesying lies, and prophesying the seductions of their own heart?\n"
	"Who will make my people to forget my name through their dreams, which every one telleth to his neighbour: as their fathers forgot my name for Baal.\n"
	"The prophet that hath a dream, let him tell the dream: & he that hath my word, let him speak my word truly: what hath the chaff to do with the wheat, saith our Lord?\n"
	"Why, are not my words as fire, saith our Lord: and as a hammer breaking a rock?\n"
	"Therefore behold I to the Prophets, saith our Lord: which steal my words every one from his neighbour.\n"
	"Behold I to the Prophets, saith our Lord: which take their tongues, & say: Our Lord saith it.\n"
	"Behold, I to the Prophets dreaming lies, saith our Lord: which have told those things, & have seduced my people in their lying, & in their miracles: When I had not sent them, nor commanded them, who have not profited this people, saith our Lord.\n"
	"If therefore this people, or the Prophet, or the Priest shall ask thee, saying: What is the burden of our Lord? Thou shalt say to them: We are the burden. for I will cast you forth, saith our Lord.\n"
	"And the Prophet, and the Priest, and the people that saith: The burden of our Lord will I visit upon that man, and upon his house.\n"
	"Thus shall you say every one to his brother, & neighbour: What hath our Lord answered? And what hath our Lord spoken?\n"
	"And the burden of our Lord shall no more be mentioned: because every man's burden shall be his own word: & you have perverted the words of the living God, the Lord of hosts our God.\n"
	"Thus shalt thou say to the Prophet: What hath our Lord answered thee? And what hath our Lord spoken?\n"
	"But if thou shalt say the burden of our Lord: for this, thus saith our Lord: Because you have said this word: The burden of our Lord: and I have sent to you, saying: Say not: The burden of our Lord:\n"
	"Therefore behold I will take you away carrying you, and will forsake you, and the city which I have given to you, and to your fathers, from before my face.\n"
	"And I will give you into everlasting reproach, and into eternal ignominy, which shall never be put away by oblivion.";