const char* chap876 = "The word that was made to Jeremy concerning all the people of Juda in the fourth year of Joakim the son of Josias king of Juda (the same is the first year of Nabuchodonosor king of Babylon.)\n"
	"Which Jeremy the Prophet spake to all the people of Juda, and to all the inhabitants of Jerusalem, saying:\n"
	"From the thirteenth year of Josias, the son of Amon king of Juda until this day; this is the three and twentieth year, the word of our Lord was made to me, and I have spoken to you rising in the night and speaking, and you have not heard.\n"
	"And our Lord hath sent all his servants the Prophets, rising early, and sending, and you have not heard, nor inclined your ears to hear\n"
	"when he said: Return ye every one from his evil way, and from your most wicked cogitations: and you shall dwell in the land, which our Lord hath given you, and your fathers from everlasting and for evermore.\n"
	"And go ye not after strange gods to serve them, and adore them: nor provoke me to wrath in the works of your hands, and I will not afflict you.\n"
	"And you have not heard me, saith our Lord, so that you provoked me to anger in the works of your hands, to your evil.\n"
	"Therefore thus saith the Lord of hosts: For that you have not heard my words:\n"
	"behold I will send, & take all the kindreds of the North, saith our Lord, & Nabuchodonosor the king of Babylon my servant: & I will bring them upon this land, & upon the inhabitants thereof, & upon all the nations that are round about it: and I will kill them & make them into astonishment & hissing, and into everlasting desolations.\n"
	"And I will destroy out of them the voice of joy, and the voice of gladness, the voice of the bridegroom, and the voice of the bride, the noise of the mill, and the light of the lamp.\n"
	"And all this land shall be in desolation, and into astonishment: and all these nations shall serve the king of Babylon seventy years.\n"
	"And when the seventy years shall be expired, I will visit upon the king of Babylon, & upon the nation, saith our Lord, their iniquity, and upon the land of Chaldees: and I will make it into everlasting desolations.\n"
	"And I will bring upon that land all my words that I have spoken against it, all that is written in this Book, whatsoever Jeremy hath prophesied against all nations:\n"
	"because they have served them, whereas they were many nations, and great kings: and I will repay them according to their works, and according to the deeds of their hands.\n"
	"Because thus saith the Lord of hosts the God of Israel: Take the cup of wine of this fury at my hand: & thou shalt drink thereof to all nations, unto the which I shall send thee.\n"
	"And they shall drink, & be troubled, and be mad at the face of the sword, which I shall send among them.\n"
	"And I took the cup at the hand of our Lord, and I drank to all the nations, to which our Lord sent me:\n"
	"to Jerusalem, and the cities of Juda, and to the kings thereof, and Princes thereof: that I would give them into desolation, and into astonishment, and into hissing, and into malediction, as is this day.\n"
	"To Pharao the king of Aegypt, and to his servants, and his Princes, and all his people,\n"
	"and to all generally: to all the kings of the land of Ausitis, and to all the kings of the land of the Philisthiims, and of Ascalon, and of Gaza, & of Accaron, & to the remnant of Azotus,\n"
	"& of Idumea, and of Moab, and to the children of Ammon.\n"
	"And to all the kings of Tyre, and to all the kings of Sidon: and to the kings of the land of the isles, who are beyond the Sea.\n"
	"And to Dedan, and Thema, and Buz, and to all that have their hair polled.\n"
	"And to all the kings of Arabia, and to all the kings of the West, that dwell in the desert.\n"
	"And to all the kings of Zambri, and to all the kings of Elam, and to all the kings of the Medes:\n"
	"also to all the kings of the North from near and from a far off: to every one against his brother: and to all the kingdoms of the earth, which are upon the face thereof: and the king of Sesac shall drink after them.\n"
	"And thou shalt say to them: Thus saith the Lord of hosts the God of Israel: Drink ye, and be drunken, and vomit: and fall, and rise not, at the face of the sword, which I shall send among you.\n"
	"And when they shall not take the cup of thy hand to drink, thou shalt say to them: Thus saith the Lord of hosts: Drinking you shall drink:\n"
	"because lo in the city, wherein my name is invocated, will I begin to afflict, and shall you be as innocent and scape free? You shall not scape free: for I call the sword upon all the inhabitants of the earth, saith the Lord of hosts.\n"
	"And thou shalt prophesy unto them all these words, and shalt say to them: Our Lord from on high shall roar, and from his holy habitation shall give his voice: roaring he shall roar upon his beauty: the cry as it were of them that tread grapes shall be sung against all the inhabitants of the earth.\n"
	"The sound is come even to the ends of the earth: because there is judgement to our Lord with the Nations: he entereth judgement with all flesh, the impious I have delivered to the sword, saith our Lord.\n"
	"Thus saith the Lord of hosts: Behold, affliction shall go forth from nation to nation: and a great whirlwind shall go forth from the ends of the earth.\n"
	"And the slain of our Lord shall be in that day from the one end of the earth even to the other end thereof: they shall not be mourned & they shall not be gathered up, nor buried: as a dunghill shall they lie upon the face of the earth.\n"
	"Howl ye pastors, and cry: and sprinkle yourselves with ashes ye leaders of the flock: because your days are accomplished to be slain: and your dissipations, and you shall fall as precious vessels.\n"
	"And flight shall fail from the Pastors, and salvation from the principals of the flock.\n"
	"A voice of the cry of the Pastors, and an howling of the Principals of the flock: because our Lord hath wasted their pastures.\n"
	"And the fields of peace have been silent at the presence of the wrath of the fury of our Lord.\n"
	"He hath as a lion forsaken his covert, because their land is made into desolation at the presence of the wrath of the dove, and at the presence of the wrath of the fury of our Lord.";