const char* chap877 = "In the beginning of the kingdom of Joakim the son of Josias king of Juda came this word from our Lord, saying:\n"
	"Thus saith our Lord: Stand in the court of the house of our Lord, and thou shalt speak to all the cities of Juda, out of the which they come, to adore in the house of our Lord, all the words which I have commanded thee to speak unto them: withdraw not a word,\n"
	"If perhaps they will hear and be converted every one from his evil way: and it may repent me of the evil that I think to do to them for the malice of their studies.\n"
	"And thou shalt say to them: Thus saith our Lord: If you will not hear me to walk in my law, which I have given you,\n"
	"that you hear the words of my servants the Prophets, which I sent to you in the night rising, and directing, and you heard not:\n"
	"I will give this house as Silo, and this city I will give into malediction to all the nations of the earth.\n"
	"And the Priests, and Prophets, and all the people heard Jeremy speaking these words in the house of our Lord.\n"
	"And when Jeremy had ended speaking all things that our Lord had commanded him, to speak unto all the people: the Priests, and Prophets, and all the people apprehended him, saying: Let him die the death.\n"
	"Why hath he prophesied in the name of our Lord, saying: This house shall be as Silo: and this city shall be made desolate, for that there is no inhabitant? And all the people was gathered together against Jeremy in the house of our Lord.\n"
	"And the Princes of Juda heard these words: & they went up from the king's house into the house of our Lord, & sat in the entry of the new gate of the house of our Lord.\n"
	"And the Priests and the Prophets spake to the Princes, and to all the people, saying: The judgement of death is to this man: because he hath prophesied against this city, as you have heard with your ears.\n"
	"And Jeremy spake to all the Princes, & to all the people, saying: Our Lord sent me, that I should prophesy to this house, and to this city all the words that you have heard.\n"
	"Now therefore make your ways good, and your studies, and hear the voice of our Lord your God: and our Lord will repent him of the evil, that he hath spoken against you.\n"
	"But I lo am in your hands: do unto me that which is good, and right in your eyes:\n"
	"Howbeit know ye and understand, that if you kill me, you shall betray innocent blood against yourselves, and against this city, & the inhabitants thereof. For in truth our Lord sent me to you, that I should speak all these words in your ears.\n"
	"And the Princes, and all the people said to the Priests, and to the Prophets: There is no judgement of death to this man: because he hath spoken to us in the name of the Lord our God.\n"
	"Men therefore of the ancients of the land rose up, & they spake to all the assembly of the people, saying:\n"
	"Michaeas the Morasthi was a Prophet in the days of Ezechias the king of Juda, and he spake to all the people Juda, saying: Thus saith the Lord of hosts: Sion shall be plowed as a field, and Jerusalem shall be as an heap of stones: and the mount of the house as the high places of woods.\n"
	"Did Ezechias the king of Juda, and all Juda, condemn him to death? Did they not fear our Lord, and beseech the face of our Lord: and it repented our Lord of the evil, that he had spoken against them? Therefore we do great evil against ourselves.\n"
	"There was also a man prophesying in the name of our Lord, Urias the son of Semei of Cariathiarim: and he prophesied against this city, & against this land, according to all the words of Jeremy.\n"
	"And king Joakim, and all his mighties, and his Princes heard these words: & the king sought to kill him. And Urias heard, and was afraid, & fled & went into Aegypt.\n"
	"And king Joakim sent men into Aegypt, Elnathan the son of Achobor, and men with him into Aegypt.\n"
	"And they brought Urias out of Aegypt: and brought him to king Joakim, & he struck him with the sword: and he cast forth his carcass in the sepulchres of the base vulgar people.\n"
	"Therefore the hand of Ahicam the son of Saphan was with Jeremy, that he should not be delivered into the hands of the people, and they kill him.";