const char* chap880 = "And these are the words of the book, which Jeremy the Prophet sent from Jerusalem to the remnant of the Ancients of the transmigration, and to the Priests, and to the Prophets, and to all the people, which Nabuchodonosor had transported from Jerusalem into Babylon:\n"
	"after that Jechonias the king was gone forth, and the queen, and the Eunuchs, and the Princes of Juda, and of Jerusalem, and the craftsman, and the incloser out of Jerusalem:\n"
	"by the hand of Elasa the son of Saphan, and Gamarias the son of Helcias, whom Sedecias the king of Juda sent to Nabuchodonosor king of Babylon into Babylon, saying:\n"
	"Thus saith the Lord of hosts the God of Israel to all the transmigration, which I have transported from Jerusalem into Babylon:\n"
	"Build ye houses, and inhabit them: and plant orchards, and eat the fruit of them.\n"
	"Take wives, and beget sons and daughters: & give wives to your sons, & give your daughters to husbands, and let them bear sons and daughters: and be ye multiplied there, and be not few in number.\n"
	"And seek the peace of the city, to which I have transported you: and pray for it to our Lord: because in the peace thereof there shall be peace to you.\n"
	"For thus saith the Lord of hosts the God of Israel: Let not your Prophets, that are in the midst of you, and your diviners seduce you: and attend not to your dreams, which you dream:\n"
	"because they do falsely prophesy to you in my name: and I sent them not, saith our Lord.\n"
	"Because thus saith our Lord: When the seventy years shall begin to be expired in Babylon, I will visit you: and I will raise up upon you my good word, to bring you again to this place.\n"
	"For I know the cogitations, that I intend upon you, saith our Lord, cogitations of peace, and not of affliction, to give you an end and patience.\n"
	"And you shall invocate me, and go: and you shall pray me, and I will hear you.\n"
	"You shall seek me, and shall find: when you shall seek me with all your heart.\n"
	"And I will be found of you, saith our Lord: and I will bring back your captivity, & I will gather you out of all nations, & from all places to the which I have expelled you, saith our Lord: and I will make you to return from the place, to the which I have transported you.\n"
	"Because you have said: Our Lord hath raised up Prophets to us in Babylon:\n"
	"for thus saith our Lord to the king, that sitteth upon the throne of David, and to all the people the inhabiter of this city, to your brethren, that are not gone forth with you into the transmigration.\n"
	"Thus saith the Lord of hosts: Behold I will send upon them the sword, and famine, and the pestilence: and I will make them as naughty figs, that cannot be eaten, because they are very naught.\n"
	"And I will persecute them with the sword, and with famine, and with pestilence: and I will give them into vexation to all the kingdoms of the earth: into malediction, & into astonishment, and into hissing, and into reproach to all the Nations, to which I have cast them out:\n"
	"because they have not heard my words, saith our Lord: which I sent to them by my servants the Prophets in the night rising, and sending: and you heard not, saith our Lord.\n"
	"You therefore hear the word of our Lord all ye the transmigration, which I have sent out from Jerusalem into Babylon.\n"
	"Thus saith the Lord of hosts the God of Israel to Achab the son of Colias, and to Sedecias the son of Maasias, which prophesy unto you in my name falsely: Behold I will deliver them into the hands of Nabuchodonosor the king of Babylon: & he shall strike them in your eyes.\n"
	"And of them a malediction shall be taken up by all the transmigration of Juda, that is in Babylon, saying: Our Lord make thee as Sedecias, & as Achab, whom the king of Babylon fried in the fire:\n"
	"for that they have done folly in Israel, and committed adultery with their friends' wives, and have spoken the word in my name falsely, which I commanded them not: I am the judge and the witness, saith our Lord.\n"
	"And to Semeias the Nehelamite thou shalt say:\n"
	"Thus saith the Lord of hosts, the God of Israel: For that thou hast sent in thy name books to all the people, that is in Jerusalem, and to Sophonias the son of Maasias, the Priest, & to all the Priests, saying:\n"
	"Our Lord hath made thee Priest for Joiada the Priest, that thou shouldest be ruler in the house of our Lord, upon every man raving and prophesying, to put him into the stocks, and into prison.\n"
	"And now why hast thou not rebuked Jeremy the Anathothite, which prophesieth unto you?\n"
	"Because upon this he hath sent into Babylon to us, saying: It is long: build ye houses, and inhabit them: and plant gardens, and eat the fruits of them.\n"
	"Sophonias therefore the Priest read this Book in the ears of Jeremy the Prophet.\n"
	"And the word of our Lord was made to Jeremy, saying:\n"
	"Send to all the transmigration, saying: Thus saith the Lord to Semeias the Nehelamite: Because Semeias hath prophesied to you, and I sent him not: and hath made you to trust in a lie:\n"
	"Therefore thus saith our Lord: Behold I will visit upon Semeias the Nehelamite, and upon his seed: there shall not be unto him a man sitting in the midst of this people, & he shall not see the good, that I will do to my people, saith our Lord: because he hath spoken prevarication against our Lord.";