const char* chap888 = "And king Sedecias the son of Josias reigned for Jechonias the son of Joakim: whom Nabuchodonosor the king of Babylon made king in the Land of Juda.\n"
	"And he obeyed not, he and his servants, and the people of the land the words of our Lord, that he spake in the hand of Jeremy the Prophet.\n"
	"And king Sedecias sent Juchal the son of Selemias, and Sophonias the son of Maasias Priest to Jeremy the Prophet, saying: Pray the Lord our God for us.\n"
	"And Jeremy walked freely in the midst of the people: for they had not cast him into ward in prison. Therefore the army of Pharao came out of Aegypt: and the Chaldees that besieged Jerusalem, hearing such tidings, retired from Jerusalem.\n"
	"And the word of our Lord was made to Jeremy the Prophet, saying:\n"
	"Thus saith our Lord the God of Israel: Thus shall you say to the king of Juda, which sent you to demand of me: Behold the army of Pharao, which is come forth to help you, shall return into his land into Aegypt.\n"
	"And the Chaldees shall return, and make war against this city, and take it, and burn it with fire.\n"
	"Thus saith our Lord: Deceive not your souls, saying: The Chaldees going shall go away, & retire from us, because they shall not go away.\n"
	"But if you shall strike all the host of the Chaldees, that fight against you, and there be left of them some wounded: every one shall rise up out of his tent, and shall burn this city with fire.\n"
	"Therefore when the army of the Chaldees was retired from Jerusalem, because of Pharao's army,\n"
	"Jeremy went out of Jerusalem to go into the land of Benjamin, and to divide possession there in the sight of the citizens.\n"
	"And when he was come to the gate of Benjamin, there was there the keeper of the gate by course, one named Jerias, the son of Selemias, the son of Hananias: and he apprehended Jeremy the Prophet, saying: Thou flyest to the Chaldees.\n"
	"And Jeremy answered: It is not so, I fly not to the Chaldees. And he heard him not: but took Jeremy, and brought him to the Princes.\n"
	"For which thing the Princes being angry against Jeremy, they beat him, and cast him into the prison that was in the house of Jonathan the scribe: for he was chief over the prison.\n"
	"Jeremy therefore went into the house of the lake, and into the dungeon: and Jeremy sat there many days.\n"
	"But Sedecias the king sending took him: and demanded of him in his house secretly, and said: Thinkest thou the word is from our Lord? And Jeremy said: It is. And he said: Thou shalt be delivered into the hands of the king of Babylon.\n"
	"And Jeremy said to king Sedecias, what have I sinned against thee, and thy servants, and thy people, that thou hast cast me into the prison house?\n"
	"Where are your Prophets that did prophesy to you, and said: The king of Babylon shall not come upon you & upon this land?\n"
	"Now therefore hear I beseech thee my lord king: let my petition be available in thy sight: and send me not back into the house of Jonathan the scribe, lest I die there.\n"
	"King Sedecias therefore commanded that Jeremy should be committed in the entry of the prison: and there should be given him a piece of bread every day, beside broth, till all the bread were spent out of the city: and Jeremy remained in the entry of the prison.";