const char* chap890 = "In the ninth year of Sedecias the king of Juda, the tenth month, came Nabuchodonosor king of Babylon, & all his army to Jerusalem, and they besieged it.\n"
	"And in the eleventh year of Sedecias, the fourth month, the fifth of the month the city was opened.\n"
	"And all the Princes of the king of Babylon went in, & sat in the middle gate: Neregal, Sereser, Semegarnabu, Sarsachim, Rabsares, Neregel, Serezer, Rebmag, & all the rest of the Princes of the king of Babylon.\n"
	"And when Sedecias the king of Juda, & all the men of war had seen them, they fled: & they went forth in the night out of the city by the way of the king's garden, and by the gate, that was between the two walls, & they went out to the way of the desert.\n"
	"But the host of the Chaldees pursued them: and they took Sedecias in the field of the desert of Jericho, and being taken they brought him to Nabuchodonosor king of Babylon into Reblatha, which is in the Land of Emath: and he spake unto him judgements.\n"
	"And the king of Babylon killed the sons of Sedecias in Reblatha, before his eyes: and the king of Babylon killed all the nobles of Juda.\n"
	"The eyes also of Sedecias he plucked out: and bound him with fetters, to be led into Babylon.\n"
	"The king's house also, and the house of the common people the Chaldees burnt with fire, and they overthrew the wall of Jerusalem.\n"
	"And the remnant of the people, that remained in the city, and the fugitives that were fled to him, and the rest of the people that remained, Nabuzardan the Prince of the soldiers transported into Babylon.\n"
	"And the poor people, that had nothing at all, Nabuzardan the master of the soldiers let alone in the land of Juda, and he gave them vineyards, and cisterns in that day.\n"
	"But Nabuchodonosor the king of Babylon had commanded Nabuzardan the Prince of the soldiers concerning Jeremy, saying:\n"
	"Take him, and set thine eyes upon him, and do him no evil: but as he will^ so do to him.\n"
	"Nabuzardan therefore the Prince of the warfare sent; and Nabusezban also, and Rabsares, and Neregel, & Sereser, and Rebmag, and all the nobles of the king of Babylon,\n"
	"sent, & took Jeremy out of the entry of the prison, and delivered him to Godolias the son of Ahicam the son of Saphan, that he might enter into the house, and dwell among the people.\n"
	"But to Jeremy the word of our Lord was made, when he was shut up in the entry of the prison, saying: Go, and tell Abdemelech the Aethiopian, saying:\n"
	"Thus saith the Lord of hosts the God of Israel: Behold I will bring my words upon this city unto evil, and not unto good: and they shall be in thy sight in that day:\n"
	"And I will deliver thee in that day, saith our Lord: and thou shalt not be delivered into the hands of the men, whom thou fearest:\n"
	"but delivering I will deliver thee, and thou shalt not fall by the sword: but thy life shall be to thee unto salvation, because thou hast had confidence in me, saith our Lord.";