const char* chap906 = "The man that see my poverty in the rod of his indignation.\n"
	"He hath led me, and brought me into darkness and not into light.\n"
	"Only against me he hath turned and hath converted his hand all the day.\n"
	"He hath made my skin old and my flesh, he hath broken my bones.\n"
	"He hath built round about me, and he hath compassed me with gall and labour.\n"
	"In dark places he hath placed me as the everlasting dead.\n"
	"He hath built round about against me, that I go not forth: he hath aggravated my fetters.\n"
	"Yea and when I shall cry, and ask, he hath excluded my prayer.\n"
	"He hath shut up my ways with square stones, he hath subverted my paths.\n"
	"He is become unto me a bear lying in wait: a lion in secret places.\n"
	"He hath subverted my paths, and hath broken me, he hath made me desolate.\n"
	"He hath bent his bow, and set me as a mark for the arrow.\n"
	"He hath shot in my reins the daughters of his quiver.\n"
	"I am made a derision to all my people, their song all the day.\n"
	"He hath replenished me with bitterness, he hath inebriated me with wormwood.\n"
	"And he hath broken my teeth by number, he hath fed me with ashes.\n"
	"And my soul is repelled from peace, I have forgotten good things.\n"
	"And I said: Mine end is perished, and mine hope from our Lord.\n"
	"Remember my poverty, and transgression, the wormwood, and the gall.\n"
	"Remembering I will be mindful, and my soul shall languish in me.\n"
	"Recording this thing in my heart, therefore will I hope.\n"
	"The mercies of our Lord that we are not consumed: because his commiserations have not failed.\n"
	"New in the morning, great is thy fidelity.\n"
	"Our Lord is my portion, said my soul: therefore will I expect him.\n"
	"Our Lord is good to them that hope in him, to the soul that seeketh him.\n"
	"It is good to wait with silence for the salvation of God.\n"
	"It is good for a man, when he beareth the yoke from his youth.\n"
	"He shall sit solitary, and hold his peace: because he hath lifted himself above himself.\n"
	"He shall put his mouth in the dust, if perhaps there be hope.\n"
	"He shall give the cheek to him that striketh him, he shall be filled with reproaches.\n"
	"Because our Lord will not reject for ever.\n"
	"Because if he hath rejected, he will also have mercy, according to the multitude of his mercies.\n"
	"For he hath not humbled from his heart, and cast off the children of men.\n"
	"To stamp under his feet all the prisoners of the earth.\n"
	"To avert the judgement of a man before the face of the Highest\n"
	"To pervert a man in his judgement, our Lord hath not known.\n"
	"Who is this, that hath commanded it to be done, our Lord not commanding it?\n"
	"Out of the mouth of the Highest, there shall not proceed neither evil things, nor good.\n"
	"What hath the living man murmured, man for his sins?\n"
	"Let us search our ways, & seek, and return to our Lord.\n"
	"Let us lift up our hearts with our hands to our Lord into the heavens.\n"
	"We have done wickedly, and provoked to wrath: therefore thou art inexorable.\n"
	"Thou hast covered in fury, and hast strucken us: thou hast killed, and not spared.\n"
	"Thou hast set a cloud before thee, that prayer may not pass.\n"
	"Thou hast made me to be rooted out, and abject in the midst of the peoples.\n"
	"All the enemies have opened their mouth upon us.\n"
	"Prophecy is made unto us, fear, and snare, and destruction.\n"
	"Mine eye hath shed streams of waters, in the destruction of the daughter of my people.\n"
	"Mine eye is afflicted, neither hath it been quiet, because there was no rest:\n"
	"Till our Lord regarded and looked from the heavens.\n"
	"Mine eye hath spoiled my soul for all the daughters of my city.\n"
	"Mine enemies in hunting have caught me as a bird, without cause.\n"
	"My life is fallen into the lake, and they have laid a stone upon me.\n"
	"The waters have flowed over my head: I said: I am undone.\n"
	"I have invocated thy name o Lord from the lowest lake.\n"
	"Thou hast heard my voice: turn not away thine ear from my sobbings, and cries.\n"
	"Thou didst approach in the day, when I invocated thee: thou hast said: Fear not.\n"
	"Thou hast judged o Lord the cause of my soul, redeemer of my life.\n"
	"Thou hast seen o Lord their iniquity against me: judge my judgement.\n"
	"Thou hast seen all their fury, all their cogitations against me.\n"
	"Thou hast heard their reproach o Lord, all their cogitations against me.\n"
	"The lips of them that rise up against me; and their cogitations against me all the day.\n"
	"See their sitting down, and their rising up, I am their psalm.\n"
	"Thou shalt render them a recompense o Lord, according to the works of their hands.\n"
	"Thou shalt give them a shield of heart thy labour.\n"
	"Thou shalt persecute in fury, and shalt destroy them from under the heavens o Lord.";