const char* chap91 = "And our Lord called Moyses, and spake to him out of the tabernacle of testimony, saying:\n"
	"Speak to the children of Israel, & thou shalt say to them: The man of you, that shall offer an host to our Lord, of beasts, that is of oxen & sheep, offering victims,\n"
	"if his oblation be an holocaust, and of the herd, he shall offer a male, without spot, at the door of the tabernacle of testimony, to propitiate our Lord unto him:\n"
	"and he shall put his hands upon the head of the host, and it shall be acceptable, and profitable to his expiation.\n"
	"And he shall immolate the calf before our Lord, and the children of Aaron the Priests shall offer the blood thereof, pouring it in the circuit of the altar, which is before the door of the tabernacle.\n"
	"And the skin of the host being plucked off, the joints they shall cut into pieces,\n"
	"and shall put fire underneath in the altar, having before laid a pile of wood in order:\n"
	"and the joints that are cut out, laying in order thereupon, to wit, the head, & all things that cleave to the liver,\n"
	"the entrails and feet being washed with water, and the Priest shall burn them upon the altar for an holocaust, and sweet savour to our Lord.\n"
	"And if the oblation be of flocks, an holocaust of sheep or of goats, a lamb of a year old without spot shall he offer:\n"
	"and he shall immolate it at the side of the altar that looketh to the North, before our Lord: but the blood thereof the sons of Aaron shall pour upon the Altar round about:\n"
	"And they shall divide the joints, the head, and all that cleave to the liver: and shall lay them upon the wood, under which the fire is to be put:\n"
	"but the entrails & the feet they shall wash with water. And the whole the Priest shall offer and burn upon the altar for an holocaust, and most sweet savour to our Lord.\n"
	"But if the oblation of holocaust to our Lord be of birds, of turtles and young pigeons,\n"
	"the Priest shall offer it at the altar: and writhing the head to the neck, and breaking the place of the wound, he shall make the blood to run down upon the brim of the altar:\n"
	"but the crop of the throat, and the feathers he shall cast night to the altar at the east side, in the place where the ashes are wont to be poured out,\n"
	"& he shall break the pinions thereof, and shall not cut nor divide it with a knife, and shall burn it upon the altar, putting fire under the wood. It is an holocaust and oblation of most sweet savour to our Lord.";