const char* chap911 = "AND now o Lord omnipotent, God of Israel, the soul in distresses, & the pensive spirit cryeth to thee:\n"
	"hear Lord, and have mercy, because thou art a merciful God, & have mercy upon us: because we have sinned before thee.\n"
	"Because thou sittest for ever, and shall we perish everlastingly?\n"
	"O Lord omnipotent, God of Israel, hear now the prayer of the dead of Israel, and of their children, that have sinned before thee, and have not heard the voice of the Lord their God, and evils have stuck fast to us.\n"
	"Remember not the iniquities of our fathers, but remember thy hand, and thy name in this time:\n"
	"because thou art the Lord our God, and we will praise thee o Lord:\n"
	"because for this end thou hast given thy fear in our hearts, and that we may invocate thy name, and may praise thee in our captivity, because we are converted from the iniquity of our fathers, which have sinned before thee.\n"
	"And behold we are in our captivity, this day, whereby thou hast dispersed us into reproach, and into malediction, and into sin, according to all the iniquities of our fathers, which have revolted from thee o Lord our God.\n"
	"Hear Israel the commandments of life: harken with your ears, that you may know prudence.\n"
	"What is the matter Israel that thou art in the land of the enemies?\n"
	"Thou art waxen old in a strange land, thou art defiled with the dead: thou art reputed with them that go down into hell.\n"
	"Thou hast forsaken the fountain of wisdom:\n"
	"for if thou hadst walked in the way of God, thou hadst verily dwelt in peace everlasting.\n"
	"Learn where wisdom is, where strength is, where understanding is: that thou mayst know withal where is the long continuance of life and living, where the light of the eyes, and peace is.\n"
	"Who hath found the place thereof? and who hath entered into the treasures thereof?\n"
	"Where are the princes of the Gentiles, and they that rule over the beasts, that are upon the earth?\n"
	"that play with the birds of the heaven,\n"
	"that treasure up silver, and gold, wherein men have confidence, and is there no end of their getting? which fashion silver & are careful, neither is there invention of their works?\n"
	"They are destroyed, and are gone down to hell, and others are risen up in their place.\n"
	"Young men saw the light, and dwelt upon the earth: but the way of discipline they knew not,\n"
	"neither understood they the paths thereof, neither have their children received it, it is made far from their face.\n"
	"It hath not been heard in the Land of Chanaan, neither hath it been seen in Theman.\n"
	"The children of Agar also, that seek out the prudence, that is of the earth, merchants of Merrhe, and of Theman, and fablers, and searchers of prudence and understanding: but the way of wisdom they have not known, neither have they remembered the paths thereof.\n"
	"O Israel how great is the house of God, and how great is the place of his possession!\n"
	"It is great, and hath no end: high and unmeasurable.\n"
	"There were the giants those renowned, that were from the beginning, of big stature, expert in war?\n"
	"These did not our Lord choose, neither found they the way of discipline: therefore did they perish.\n"
	"And because they had not wisdom, they perished through their folly.\n"
	"Who hath ascended into heaven, and taken her, and brought her down from the clouds?\n"
	"Who hath passed over the sea, and found her, and brought her above chosen gold?\n"
	"There is none that can know her ways, nor that can search out her paths:\n"
	"but he that knoweth all things, knoweth her, & hath found her out by his prudence: he hath prepared the earth in time everlasting, and replenished it with cattle, and fourfooted beasts:\n"
	"he that sendeth forth light, and it goeth: and hath called it, and it obeyeth him with trembling.\n"
	"And the stars have given light in their watches, and rejoiced:\n"
	"they were called, and they said: here we are: and they have shined to him with cheerfulness, that made them.\n"
	"This is our God, and there shall none other be esteemed against him.\n"
	"He found out all the way of discipline, and delivered it to Jacob his servant, and to Israel his beloved.\n"
	"After these things he was seen upon the earth, and was conversant with men.";