const char* chap912 = "THIS is the book of the commandments of God, and the law, that is for ever: all that hold it, shall come to life: but they that have forsaken it, into death.\n"
	"Return Jacob, and take hold of it, walk by the way to the brightness of it, against the light thereof.\n"
	"Deliver not thy glory to another, & dignity to a strange nation.\n"
	"We are blessed o Israel: because the things that please God, are manifest to us.\n"
	"Be of good comfort o people of God, memorable Israel:\n"
	"you are sold to the Gentiles, not into perdition: but for that in anger you provoked God to wrath, you are delivered to the adversaries.\n"
	"For you have exasperated him, that made you, the eternal God, immolating to devils, and not to God.\n"
	"For you have forgotten God, who hath nourished you, and your nurse Jerusalem you have made sorrowful.\n"
	"For she saw the wrath coming from God to you, and she said: Hear ye confines of Sion, for God hath brought me great mourning:\n"
	"For I have seen the captivity of my people, and of my sons, and daughters, which the everlasting hath brought upon them.\n"
	"For I nourished them with joyfulness: but I have left them with weeping and mourning.\n"
	"Let no man rejoice over me a widow, and desolate: I am forsaken of many for the sins of my children, because they have declined from the law of God.\n"
	"And his justices they have not known, nor walked by the ways of God's commandments, neither have they entered by the paths of his truth and justice.\n"
	"Let the borderers of Sion come, and remember the captivity of my sons & daughters, which the everlasting hath brought upon them.\n"
	"For he hath brought upon them a nation from afar, a wicked nation, and of another tongue:\n"
	"which have not reverenced the ancient, nor pitied the children, & have led away the beloved of the widow, and made the sole woman desolate of children.\n"
	"But as for me what can I help you?\n"
	"For he that hath brought the evils upon you, he will deliver you out of the hands of your enemies.\n"
	"walk children, walk: for I am left alone.\n"
	"I have put off the stole of peace, and I have put upon me the sackcloth of prayer, and I will cry to the Highest in my days.\n"
	"Be of good comfort my children, cry to our Lord, and he will deliver you out of the hand of the princes your enemies.\n"
	"For I have hoped in the everlasting for your salvation: & joy is come to me from the holy one upon the mercy, which shall come to you from our everlasting saviour.\n"
	"For I sent you forth with mourning and weeping: but our Lord will bring you back to me with joy and gladness for ever.\n"
	"For as the neighbours of Sion have seen your captivity from God: so shall they see also with celerity your salvation from God, which shall come upon you with great honour, and everlasting brightness.\n"
	"Children patiently sustain the wrath, which is come upon you: for thine enemy hath persecuted thee, but thou shalt quickly see his destruction: and thou shalt get up upon his neck.\n"
	"My delicate ones have walked rough ways, for they are led as a flock taken violently of the enemies.\n"
	"Be of good comfort children, and cry out to our Lord: for there shall be remembrance of you with him, that hath led you away.\n"
	"For as your mind hath been to stray from God: ten times so much shall you returning again seek him.\n"
	"For he that hath brought the evils upon you, he again will bring unto you everlasting joy with your salvation.\n"
	"Be of good comfort Jerusalem: for he exhorteth thee, that named thee.\n"
	"The wicked afflicters shall perish, that have vexed thee: & they that have rejoiced in thy ruin, shall be punished.\n"
	"The cities which thy children have served, shall be punished: and she that received thy children.\n"
	"For as she hath rejoiced in thy ruin, and been glad at thy fall: so shall she be made sorrowful in her own desolation.\n"
	"And the rejoicing of her multitude shall be cut off, & her gladness shall be turned to mourning.\n"
	"For fire shall come upon her from the everlasting in long during days, and she shall be inhabited of devils a great time.\n"
	"Look about o Jerusalem toward the East, and see the joy that cometh to thee from God.\n"
	"For behold thy children come, whom thou hast let go dispersed, they come gathered together from the East even to the West, in the word of the holy one rejoicing to the honor of God.";