const char* chap914 = "For the sins that you have sinned before God, you shall be led away captive into Babylon by Nabuchodonosor the king of Babylon.\n"
	"Being entered therefore into Babylon, you shall be there many years, and long times even unto seven generations: and after this I will bring you forth from thence with peace.\n"
	"But now you shall see in Babylon gods of gold, and of silver, and of stone, and of wood to be carried upon shoulders, shewing fear to the Gentiles.\n"
	"Beware therefore lest you also be like to the doing of strangers, and you be afraid, and fear take you in them.\n"
	"Seeing therefore the multitude adoring behind, and before, say you in your hearts: Thou oughtest to be adored o Lord.\n"
	"For mine Angel is with you: and myself will ask account of your souls.\n"
	"For their tongue polished by the craftsman, themselves also laid over with gold, and silver are false things, and they cannot speak.\n"
	"And as to a virgin that loveth ornaments: so taking gold their gods are forged.\n"
	"Their gods certes have golden crowns upon their heads: whereof the priests secretly convey away from them gold, and silver, and bestow it on themselves.\n"
	"Yea and they give thereof to strumpets, and they deck whores: and again when they receive it of the harlots, they deck their gods.\n"
	"But these are not delivered from the rust, and the moth.\n"
	"And these being covered with a purple garment, they wipe their face for the dust of the house, which is very much among them.\n"
	"And he hath a sceptre as a man, as a judge of the country, that killeth him not that offendeth against him.\n"
	"He hath also in his hand a sword, and an axe, but himself he delivereth not from the sword, and from robbers, whereby be it known to you that they are not gods.\n"
	"Therefore fear them not. For as a man's vessel being broken is made unprofitable: such also are their gods:\n"
	"they being placed in the house, their eyes are full of dust by the feet of them that go in.\n"
	"And as upon one, that hath offended the king, the gates be shut round about, or as the dead brought to the grave, so do the priests guard the doors with shuttings, and locks, lest they be spoiled of thieves.\n"
	"They light candles to them, and that many, of the which they can see none: but they are as beams in the house.\n"
	"And they say that the serpents which are of the earth, gnaw out their hearts, whiles they eat them and their garment, and they feel not.\n"
	"Their faces are black with the smoke, that is made in the house.\n"
	"The owls, and the swallows fly upon their body, and upon their head, and the birds also, the cats in like manner.\n"
	"Whereby you may know that they are not gods. Therefore fear them not.\n"
	"The gold also which they have, is for beauty, unless a man wipe off the rust, they shall not shine: for neither when they were molten, did they feel.\n"
	"With all price are they bought, whereas there is no breath in them.\n"
	"As being without feet they are carried upon shoulders, shewing their baseness to men. Be they confounded also that worship them.\n"
	"Therefore if they fall to the ground, they rise not up of themselves, nor if a man set him upright, shall he stand by himself, but as to dead men their gifts shall be set before them.\n"
	"Their priests sell their sacrifices, and abuse them: likewise also their wives plucking from them, impart nothing, neither to the sick, nor to the beggar.\n"
	"Of their sacrifices women in childbed, and in flowers do touch: knowing therefore by these things that they are not gods, fear them not.\n"
	"For whence are they called gods? Because women offer to the gods of silver, and gold, and wood.\n"
	"And priests sit in their houses, having their garments rent, and their heads, & beard shaven, whose heads be bare.\n"
	"And they were crying before their gods, as at the supper of the dead.\n"
	"The priests take away their garments, and they clothe their wives & their children.\n"
	"Neither if they suffer any evil, nor if any good of any man, are they able to recompence it: neither can they make a king, nor take him away:\n"
	"In like manner they can neither give riches, nor requite evil. If a man vow a vow unto them, and perform it not; neither this do they require.\n"
	"They deliver not a man from death, nor save the weak from the mightier.\n"
	"The blind man they restore not to his sight: they shall not deliver a man out of necessity.\n"
	"They shall not pity the widow, nor do good to the fatherless.\n"
	"Like unto the stones of the mountain are their gods, of wood, and of stone, and of gold, and of silver. & they that worship them, shall be confounded:\n"
	"How then is it to be supposed, or to be said, that they are gods?\n"
	"Moreover the Chaldees themselves not honoring them: who when they hear that the dumb cannot speak, they offer it to Bel, requesting of him, that it may speak.\n"
	"As though they could feel that have no motion: and they when they shall understand, will leave them: for their gods themselves have no sense.\n"
	"And women compassed with cords, sit in the ways, burning the bones of olives.\n"
	"And when one of them being drawn of some passenger shall lie with him, she upbraideth her neighbour, that she is not counted worthy, as herself, neither is her cord broken.\n"
	"But all things that are done about them are false, how is it then to be thought, or to be said, that they be gods?\n"
	"And they are made by craftsmen, & by goldsmiths. They shall be nothing else, but that which the priests will have them to be.\n"
	"For the artificers themselves, that make them, are of no long time. Why, can those things then that are made by them, be gods?\n"
	"But they have left forged things & reproach, to them that shall come after.\n"
	"For when battle cometh upon them, and evils: the priests devise with themselves, where they may hide themselves with them.\n"
	"How then may they be thought, that they are gods, which neither deliver themselves from battle, nor save themselves from evils?\n"
	"For seeing they be of wood, & laid over with gold, and with silver, it shall be known afterwards that they are false things, of all the Gentiles, and kings: Which are manifest that they are no gods, but the works of men's hands, and no work of God is with them.\n"
	"Whence then is it known, that they are not gods, but the works of men's hands, & no work of God is in them?\n"
	"A king to the country they raise not up, neither shall they give rain to men.\n"
	"Judgement also they shall not discern, neither shall they deliver countries from injury: because they can do nothing, as crows between the heaven and the earth.\n"
	"For when fire shall fall into the house of the wooden, and silver, and golden gods, their priests indeed shall flee, and be delivered: but themselves as beams shall be burnt in the midst.\n"
	"And king and battle they shall not resist. How is it then to be supposed, or to be received that they are gods?\n"
	"Not from thieves, nor from robbers shall the gods of wood, and of stone, and laid over with gold, and with silver deliver themselves, stronger than which are the wicked men.\n"
	"The gold, and silver, and the garment wherewith they are covered, they shall take from them, and shall depart, neither shall they help themselves.\n"
	"Therefore it is better to be a king shewing his strength: or a profitable vessel in the house, wherein he will glory that possesseth it: or a door in the house, which keepeth the things that are therein, than false gods.\n"
	"The sun certes, and the moon, and the stars whereas they are bright, and sent forth for profitable uses, obey.\n"
	"Likewise also the lightning, when it shall appear is perspicuous: and the wind also bloweth the self same in every country.\n"
	"And the clouds, which when God shall command to walk throughout the whole world, they do that which is commanded them.\n"
	"The fire also being sent from above to consume mountains, and woods, doeth that which is commanded it. But these neither in shapes, nor in virtues are like to one of them.\n"
	"Wherefore neither is it to be thought, nor to be said, that they be gods: whereas they can neither judge judgment, nor do any thing for men.\n"
	"Knowing therefore that they are not gods, then fear them not.\n"
	"For neither shall they curse kings, nor bless them.\n"
	"Signs also in the heaven to the Gentiles they shew not, neither shall they shine as the sun, nor give light as the moon.\n"
	"Beasts are better than they, which can fly under the roof, and profit themselves.\n"
	"By no means therefore is it manifest unto us, that they are gods: for which cause fear them not.\n"
	"For as in a garden of cucumbers a scarecrow keepeth nothing, so are their gods of wood, and of silver, and laid over with gold.\n"
	"After the same sort also in a garden the white thorn, upon the which every bird sitteth. In like manner also their gods of wood, and laid over with gold, and with silver, are like to a dead body cast forth in the dark.\n"
	"By the purple also and the murex colour laid upon them, which fadeth, you shall know that they are not gods. At the last also they are consumed, and shall be a reproach in the country.\n"
	"Better is therefore the just man, that hath not idols: for he shall be far from reproaches.";