const char* chap925 = "And the spirit lifted me up, and brought me into the east gate of the house of our Lord, which looketh to the rising of the sun: and behold in the entry of the gate five and twenty men: and I saw in the midst of them Jezonias the son of Azur, & Pheltias the son of Banaias, the Princes of the people.\n"
	"And he said to me: Son of man, these are the men that conceive iniquity, and devise most wicked counsel in this city,\n"
	"saying: Were not houses builded of late? This is the cauldron, & we the flesh.\n"
	"Therefore prophesy of them, prophesy thou son of man.\n"
	"And the spirit of our Lord fell upon me, & said to me: Speak: Thus saith our Lord: So have you spoken, o house of Israel, & the cogitations of your heart I know.\n"
	"Very many have you killed in this city, and you have filled the ways thereof with the slain.\n"
	"Therefore thus saith our Lord God: Your slain, whom you have laid in the midst thereof, these are the flesh, and this is the cauldron: and I will bring you out of the midst thereof.\n"
	"The sword you have feared, and the sword I will bring upon you, saith our Lord God.\n"
	"And I will cast you out of the midst thereof, & I will give you into the hand of the enemies, & will do judgements in you.\n"
	"You shall fall by the sword: in the borders of Israel will I judge you, and you shall know that I am the Lord.\n"
	"This shall not be as a cauldron to you, and you shall not be as flesh in the midst thereof, in the borders of Israel I will judge you.\n"
	"And you shall know that I am the Lord: because you have not walked in my precepts, and have not done my judgements, but you have done according to the judgements of nations, that are round about you.\n"
	"And it came to pass, when I prophesied, Pheltias the son of Banaias died: and I fell upon my face, crying with a loud voice: and said: Alas, alas, alas, o Lord God: makest thou a consummation of the remnant of Israel?\n"
	"And the word of our Lord was made to me, saying:\n"
	"Son of man thy brethren, thy brethren, thy kinsmen, and all the house of Israel, all to whom the inhabitants of Jerusalem have said: Depart ye far from our Lord, the land is given to us in possession.\n"
	"Therefore thus saith our Lord God: Because I have made them far off in the Gentiles, and because I have dispersed them in the lands: I will be a little sanctification to them in the lands, to which they are come.\n"
	"Therefore speak: Thus saith our Lord God: I will gather you out of the peoples, and unite you out of the lands, wherein you are dispersed, and I will give you the ground of Israel.\n"
	"And they shall go in thither, and shall take away all the offences, and all the abominations thereof out of it.\n"
	"And I will give them one heart, and will give a new spirit in their bowels: and I will take away the stony heart out of their flesh, and will give them a fleshy heart:\n"
	"that they may walk in my precepts, and keep my judgements, and do them: and they may be my people, and I may be their God.\n"
	"Whose heart walketh after their offences and abominations, their way will I lay on their head, saith our Lord God.\n"
	"And the Cherubs lifted up their wings, and the wheels with them: and the glory of the God of Israel was over them.\n"
	"And the glory of our Lord ascended from the midst of the city, and stood over the mount, that is on the east side of the city.\n"
	"And the spirit lifted me up, and brought me into Chaldee to the transmigration, in a vision in the spirit of God: and the vision which I had seen was taken up from me.\n"
	"And I spake to the transmigration all the words of our Lord, which he had shewed me.";