const char* chap927 = "And the word of our Lord was made to me, saying:\n"
	"Son of man prophesy to the Prophets of Israel, that prophesy: and thou shalt say to them, that prophesy of their own heart: Hear ye the word of our Lord:\n"
	"Thus saith our Lord God: Woe to the foolish Prophets, which follow their own spirit, and see nothing.\n"
	"As foxes in the deserts, were thy Prophets o Israel.\n"
	"You have not ascended against, nor opposed a wall for the house of Israel, that you might stand in battle in the day of our Lord.\n"
	"They see vain things, and they divine lies, saying: Our Lord saith: whereas our Lord sent them not: and they persevered to confirm the word.\n"
	"Why^ have you not seen vain vision, and spoken lying divination? And you say: Our Lord saith; whereas I have not spoken.\n"
	"Therefore thus saith our Lord God: Because you have spoken vain things, and have seen lies: therefore behold I to you, saith our Lord God.\n"
	"And my hand shall be upon the Prophets, that see vain things, and divine a lie: in the counsel of my people they shall not be, & in the scripture of the house of Israel they shall not be written, neither shall they enter into the land of Israel: and you shall know that I am the Lord God.\n"
	"For that they have deceived my people, saying: Peace, and there is not peace: and he builded the wall, and they daubed it with mortar without straw.\n"
	"Say to them that daub without tempering, that it shall fall: for there shall be a shower overflowing, and I will give very great stones falling violently from above, and the wind of a storm dissipating.\n"
	"For indeed behold the wall is fallen: shall it not be said to you: Where is the daubing, that you daubed?\n"
	"Therefore thus saith our Lord God: And I will make the spirit of tempests to break forth in mine indignation, and there shall be an overflowing showering in my fury: & great stones in my wrath unto consumption.\n"
	"And I will destroy the wall, that you have daubed without tempering: & I will make it even with the ground, and the foundation thereof shall be revealed: and it shall fall, and shall be consumed in the midst thereof: and you shall know that I am the Lord.\n"
	"And I will accomplish mine indignation in the wall, and in them, that daub it without tempering, and I will say to you: The wall is not, and they are not that daub it.\n"
	"The Prophets of Israel, which prophesy to Jerusalem, & see vision of peace for it: and there is not peace, saith our Lord God.\n"
	"And thou son of man, put thy face against the daughters of thy people, which prophesy of their own heart: and do thou prophesy upon them,\n"
	"and say: Thus saith our Lord God: woe to them that sow cushions under every cubit of the hand: and make pillows under the head of every age to catch souls: and when they caught the souls of my people, they did vivificate their souls.\n"
	"And they violated me to my people, for a handful of barley, and a cantel of a bread, that they might kill the souls, which die not, and vivificate the souls which live not, lying to my people, that believeth lies.\n"
	"For this cause thus saith our Lord God: Behold I to your cushions, wherewith you catch flying souls: and I will break them from your arms: and I will let go the souls that you take, the souls to fly\n"
	"And I will break your pillows, & will deliver my people out of your hand, neither shall they be any more in your hands to be a prey: and you shall know that I am the Lord.\n"
	"For that you have made the heart of the just to mourn lyingly, whom I made not sorrowful: and have strengthened the hands of the impious, that he might not return from his evil way, and live.\n"
	"Therefore you shall not see vain things, and divinations you shall divine no more, and I will deliver my people out of your hand: and you shall know that I am the Lord.";