const char* chap930 = "And the word of our Lord was made to me saying:\n"
	"Son of man make known to Jerusalem her abominations:\n"
	"and thou shalt say: Thus saith our Lord God to Jerusalem: Thy root, and thy generation of the land of Chanaan, thy father an Amorrheite, & thy mother a Cetheite.\n"
	"And when thou wast born, in the day of thy birth thy navel was not cut, and thou wast not washed with water to health, nor salted with salt, nor swaddled in clouts.\n"
	"No eye had mercy on thee to do unto thee one of these things, having pity on thee: but thou wast thrown forth upon the face of the earth in the abjection of thy soul, in the day that thou wast born.\n"
	"And passing by thee I saw thee to be trodden down in thy blood: and I said to thee when thou wast in thy blood: Live. I said to thee, I say: In thy blood live.\n"
	"Multiplied as the spring of the field have I made thee: and thou wast multiplied, & made great, and thou wentest in, and camest to the ornaments of women: thy breasts swelled, and thy hair budded: and thou was naked, and full of confusion.\n"
	"And I passed by thee, and saw thee: and behold thy time, the time of lovers: and I spread my garment over thee, and covered thy ignominy. And I sware to thee, and I entered a covenant with thee, saith our Lord God: and thou wast made mine.\n"
	"And I washed thee with water, and made clean thy blood from off thee: and I anointed thee with oil.\n"
	"And I clothed thee with diverse colours, and shod thee with hyacinth: and I girded thee with silk, and clothed thee with fine garments.\n"
	"And I adorned thee with ornament, and gave bracelets on thy hands, and a chain about thy neck.\n"
	"And I gave a jewel upon thy face, and rings to thine ears, and a crown of beauty on thy head.\n"
	"And thou was adorned with gold, and silver, and wast clothed with silk, and embroidered work, and many colours: thou hast eaten flours, and honey, and oil, and wast made very beautiful exceedingly: and didst prosper to a kingdom.\n"
	"And thy name went forth into the Gentiles, because of thy beauty: because thou wast perfect in my beauty, which I had put upon thee, saith our Lord God.\n"
	"And having confidence in thy beauty thou hast fornicated in thy name: & thou hast laid forth thy fornication to every passenger to be made his.\n"
	"And taking off thy garments thou madest thee idols embroidered on each side: & thou didst fornicate upon them, as hath not been done, nor shall not hereafter.\n"
	"And thou tookest the vessels of thy beauty, of my gold, and my silver, which I gave thee: and thou madest thee images of men, and hast fornicated in them.\n"
	"And thou tookest thy garments of many colours, and coveredst them: and mine oil, and mine incense thou didst put before them.\n"
	"And my bread, which I gave thee, the flour, and oil, and honey, wherewith I have nourished thee, thou didst set in their sight for an odour of sweetness, and it was done saith our Lord God.\n"
	"And thou hast taken thy sons, & thy daughters, which thou didst beget to me: and hast immolated the same unto them to devour. Why, is thy fornication small?\n"
	"Thou hast immolated my sons, & hast given them, consecrating them to the idols.\n"
	"And after all thine abominations, & fornications, thou wast not mindful of the days of thy youth, when thou wast naked, & full of confusion, trodden down in thy blood.\n"
	"And it chanced after all thy malice (woe, woe to thee, saith our Lord God)\n"
	"thou didst also build thee a stews, & madest thee a brothel house in all streets.\n"
	"At every head of the way hast thou built a sign of thy prostitution: & hast made thy beauty abominable: & hast divided thy feet to every one that passeth by, and hast multiplied thy fornications.\n"
	"And thou hast fornicated with the children of Aegypt thy neighbours of great flesh, & hast multiplied thy fornication to provoke me.\n"
	"Behold I will stretch out my hand upon thee, & will take away thy justification: & I will give thee into the souls of the daughters of Palestine that hate thee, that are ashamed of thy wicked way.\n"
	"And thou hast committed fornication with the sons of the Assyrians, because neither as yet wast thou filled: & after thou didst fornicate, neither so wast thou satiated.\n"
	"And thou didst multiply thy fornication in the Land of Chanaan with the Chaldees: & neither so wast thou satiated.\n"
	"Wherein shall I cleanse thy heart, saith our Lord God: whereas thou doest all these the works of a woman that is a whore, & malapert?\n"
	"Because thou hast built thy brothel house in the head of every way, & thy excelse thou hast made in every street, neither becamest thou as an harlot that by disdain augmenteth the price,\n"
	"but as a woman adulteress, that over her husband bringeth in strangers.\n"
	"To all harlots are rewards given: but thou hast given rewards to all thy lovers, & thou didst give them gifts to come unto thee on every side, to fornicate with thee.\n"
	"And in thee it was done contrary to the custom of women in thy fornications, and after thee there shall be no fornication: for in that thou gavest rewards, and didst not take rewards, it hath been done contrary in thee.\n"
	"Therefore hear, o harlot, the word of our Lord.\n"
	"Thus saith our Lord God: Because thy brass is poured out, & thine ignominy is revealed in thy fornications upon thy lovers, and upon the idols of thine abominations in the blood of thy children, whom thou gavest them:\n"
	"Behold I will gather together all thy lovers, with whom thou hast taken pleasure, & all whom thou hast loved, with all, whom thou didst hate: and I will gather them together upon thee on every side, and will discover thine ignominy before them, and they shall see all thy turpitude.\n"
	"And I will judge thee by the judgements of adulteresses, and them that shed blood: and I will give thee into blood of fury and zeal.\n"
	"And I will give thee into their hands, and they shall destroy thy brothel-house, and throw down thy stews: and they shall turn thee naked out of thy garments, and shall take away the vessels of thy beauty: and shall leave thee naked, and full of ignominy.\n"
	"And they shall bring upon thee a multitude, and they shall stone thee with stones, and shall murder thee with their swords.\n"
	"And they shall burn thy houses with fire, and shall do judgements in thee in the eyes of very many women: and thou shalt cease to fornicate, and shalt give rewards no more.\n"
	"And mine indignation shall rest in thee: and my zeal shall be taken away from thee, and I will cease, and be angry no more.\n"
	"For that thou hast not remembered the days of thy youth, and hast provoked me in all these: wherefore I also have given thy ways on thy head, saith our Lord God, & I have not done according to thy wicked deeds in all thine abominations.\n"
	"Behold every one, that speaketh a common proverb, shall take up that against thee, saying: As the mother, so also her daughter.\n"
	"Thou art the daughter of thy mother, which did cast off her husband, & her children: & thou art sister of thy sisters, which did cast off their husbands, and their children: your mother was a Cetheite, and your father an Amorrheite.\n"
	"And thy elder sister, Samaria, she & her daughters, that dwell on thy left hand, & thy sister younger than thou, which dwelleth on thy right hand, Sodom, & her daughters.\n"
	"But neither in their ways has thou walked, nor according to their wicked deeds hast thou done a very little less: thou hast done almost more wicked things than they in all thy ways.\n"
	"Live I, saith our Lord God, that Sodom thy sister herself hath not done, and her daughters, as thou hast done, and thy daughters.\n"
	"Lo this was the iniquity of Sodom thy sister, pride, fullness of bread, and aboundance, and the idleness of her, and of her daughters: and they raught not the hand to the needy, and the poor.\n"
	"And they were elevated, and did abominations before me: & I took them away as thou hast seen.\n"
	"And Samaria sinned not the half of thy sins: but thou hast passed them with thy wicked deeds, & hast justified thy sisters in all thine abominations, which thou hast wrought.\n"
	"Thou also therefore carry thy confusion, which hast passed thy sisters with thy sins, doing more wickedly than they: for they are justified above thee: thou also therefore be confounded, and bear thine ignominy, which hast justified thy sisters.\n"
	"And I will convert restoring them by the conversion of Sodom with her daughters, and by the conversion of Samaria, and her daughters: and I will convert thy reversion in the midst of them,\n"
	"that thou mayst carry thine ignominy, and mayst be confounded in all things, that thou hast done, comforting them.\n"
	"And thy sister Sodom, and her daughters shall return to their antiquity: and Samaria, and her daughters shall return to their antiquity: and thou, and thy daughters shall return to your antiquity.\n"
	"And Sodom thy sister was not heard in thy mouth, in the day of thy pride,\n"
	"before that thy malice was revealed: as at this time for reproach of the daughters of Syria, & of all the daughters of Palesthine in the circuit of thee, which compass thee round about.\n"
	"Thy wickedness, & thine ignominy thou hast carried, saith our Lord God.\n"
	"Because thus saith our Lord God: And I will do to thee, as thou hast despised the oath, to make the covenant frustrate:\n"
	"and I will remember my covenant with thee in the days of thy youth: and I will raise unto thee an everlasting covenant.\n"
	"And thou shalt remember thy ways, & shalt be confounded: when thou shalt receive thy sisters elder than thee with thy younger: and I will give them to thee for daughters, but not by thy covenant.\n"
	"And I will raise up my covenant with thee: and thou shalt know that I am the Lord,\n"
	"that thou mayst remember, and be confounded, and mayst no more open thy mouth because of thy confusion, when I shall be pacified toward thee in all that thou hast done, saith our Lord God.";