const char* chap934 = "And it came to pass in the seventh year, in the fifth, the tenth of the month: there came men of the ancients of Israel to ask our Lord, and they sat before me.\n"
	"And the word of our Lord was made to me, saying:\n"
	"Son of man, speak to the ancients of Israel, and thou shalt say to them: Thus saith our Lord God: Why, are you come to ask me? Live I, that I will not answer you, saith our Lord God.\n"
	"Doest thou judge them, doest thou judge o son of man? Shew to them the abominations of their fathers.\n"
	"And thou shalt say to them: Thus saith our Lord God: In the day that I chose Israel, and lifted up my hand for the stock of the house of Jacob: and appeared to them in the Land of Aegypt, & lifted up my hand for them, saying: I^ the Lord your God:\n"
	"in that day I lifted up my hand for them, that I might bring them out of the Land of Aegypt, into a Land which I had provided for them, flowing with milk & honey, which is excellent among all lands.\n"
	"And I said to them: Let every man cast away the scandals of his eyes, & in the idols of Aegypt be ye not polluted: I^ the Lord your God.\n"
	"And they provoked me, & would not hear me: every one did not cast away the abominations of his eyes, neither did they leave the idols of Aegypt: and I said I would pour out mine indignation upon them, and fill my wrath in them, in the midst of the Land of Aegypt.\n"
	"And I did for my name sake, that it might not be violated before the Gentiles, in the midst of whom they were, & among whom I appeared to them to bring them out of the Land of Aegypt.\n"
	"I cast them out therefore of the Land of Aegypt, and brought them forth into the desert.\n"
	"And I gave them my precepts, and I shewed to them my judgements, which a man doing, shall live in them.\n"
	"Moreover also my sabbaths I gave to them, to be a sign between me and them: & that they might know that I am the Lord sanctifying them.\n"
	"And the houses of Israel provoked me in the desert; they walked not in my precepts, and my judgements they rejected, which a man doing shall live in them: & my sabbaths they violated exceedingly. I said therefore I would pour out my fury upon them in the desert, and would consume them.\n"
	"And I did for my name sake, lest it should be violated before the Gentiles, from which I cast them out, in their sight.\n"
	"I therefore lifted up my hand upon them in the desert, not to bring them into the Land, which I gave them flowing with milk and honey, the chief of all lands.\n"
	"Because they rejected my judgements, and walked not in my precepts, and violated my sabbaths: for their heart went after idols.\n"
	"And mine eye was merciful on them, that I killed them not: neither did I consume them in the desert.\n"
	"But I said to their children in the wilderness: In the precepts of your fathers^ walk not, neither keep ye their judgments, nor be polluted in their idols:\n"
	"I^ the Lord your God: walk ye in my precepts, and keep my judgements, and do them.\n"
	"And sanctify ye my sabbaths, that they may be a sign between me and you: and ye may know that I am the Lord your God.\n"
	"And the children exasperated me, in my precepts they walked not: and my judgements they kept not, to do them: which when a man shall do, he shall live in them: and they violated my sabbaths: and I threatened to pour out my fury upon them, and to fill my wrath in them in the desert.\n"
	"But I turned away my hand, & did for my name's sake, that it might not be violated before the Gentiles, out of which I did cast them forth in their eyes.\n"
	"Again I lifted up my hand upon them in the wilderness, that I might disperse them into nations, and scatter them into lands:\n"
	"for that they had not done my judgements, and had rejected my precepts, and had violated my sabbaths, and their eyes had been after the idols of their fathers.\n"
	"Therefore I also gave them precepts not good, & judgements, in which they shall not live.\n"
	"And I polluted them in their gifts, when they offered all that opened the matrice, for their offences: and they shall know that I am the Lord.\n"
	"Wherefore speak to the house of Israel, o son of man: and thou shalt say to them: Thus saith our Lord God: Yet also in this did your fathers blaspheme me, when contemning they had despised me:\n"
	"and I had brought them into the Land, upon which I lifted up my hand to give it them: they saw every high hill, & every woody tree, and there they immolated their victims: and there they gave the irritation of their oblation, and there they put the odour of their sweetness, and offered their libations.\n"
	"And I said to them: What is the excelse, unto which you go? & the name thereof was called Excelse even to this day.\n"
	"Therefore say to the house of Israel: Thus saith our Lord God: Surely in the way of your fathers you are polluted, and after their scandals you do fornicate.\n"
	"And in the oblation of your gifts, when you make your children pass through the fire, you are polluted in all your idols unto this day: and shall I answer you, o house of Israel? Live I, saith our Lord God, that I will not answer you.\n"
	"Neither shall the cogitation of your mind come to pass, saying: We will be as the Gentiles, and as the kindreds of the earth, that we may worship wood, and stones.\n"
	"Live I, saith our Lord God, that in a strong hand, & in a stretched out arm, & in fury poured forth will I reign over you.\n"
	"And I will bring you out of the peoples, and I will gather you out of the lands, in which you are dispersed, in a strong hand, & in a stretched out arm, & in fury poured forth will I reign over you.\n"
	"And I will bring you into the desert of peoples, and will be judged there with you face to face.\n"
	"As I contended in judgement against your fathers in the desert of the Land of Aegypt: so will I judge you, saith our Lord God.\n"
	"And I will subdue you to my sceptre, & will bring you into the bands of covenant.\n"
	"And I will choose out of you the transgressors, and impious, & will bring them out of the land of their sojourning, and into the land of Israel they shall not enter: and you shall know that I am the Lord.\n"
	"And you o house of Israel, Thus saith our Lord God: Walk you every one after your idols, & serve them. But and if in this also you hear me not, and shall pollute my holy name any more in your gifts, & in your idols:\n"
	"in my holy mount, in the high mount of Israel, saith our Lord God, there shall all the house of Israel serve me; all I say in the land, wherein they shall please me, & there will I require your first fruits, and the beginning of your tithes in all your sanctifications.\n"
	"I will receive you for an odour of sweetness, when I shall have brought you out of the peoples, & shall have gathered you out of the lands, into which you are dispersed, & I will be sanctified in you in the eyes of the nations.\n"
	"And you shall know that I am the Lord, when I shall have brought you into the land of Israel, into the land for which I lifted up my hand to give it to your fathers.\n"
	"And there you shall remember your ways, and all your wicked deeds, in which you were polluted: & you shall mislike yourselves in your own sight, in all your malices, which you have done.\n"
	"And you shall know that I am the Lord, when I shall have done you good for my name sake, and not according to your evil ways, nor according to your most wicked deeds, o house of Israel, saith our Lord God.\n"
	"And the word of our Lord was made to me, saying:\n"
	"Son of man, set thy face against the way of the south, and drop toward the southern wind, & prophesy to the forest of the southern field.\n"
	"And thou shalt say to the southern forest: Hear the word of our Lord: Thus saith our Lord God: Behold I will kindle a fire in thee, and will burn in thee every green tree, and every dry tree: the flame of the fire shall not be quenched: and every face shall be burned in it, from the South even to the North.\n"
	"And all flesh shall see, that I^ the Lord kindled it, neither shall it be quenched.\n"
	"And I said: A a a, o Lord God: they say of me: Doth not this man speak by parables?";