const char* chap935 = "And the word of our Lord was made to me, saying:\n"
	"Son of man set thy face to Jerusalem, and drop to the sanctuaries, and prophesy against the ground of Israel:\n"
	"And thou shalt say to the land of Israel: Thus saith our Lord God: Behold I to thee, and I will draw forth my sword out of his scabbard, and will kill in thee the just, and the impious.\n"
	"And for that I have killed in thee the just, and the impious, therefore shall my sword go forth out of his scabbard to all flesh, from the South even to the North.\n"
	"That all flesh may know that I^ the Lord have drawn my sword out of his scabbard not to be revoked.\n"
	"And thou son of man, mourn in contrition of the loins, and in bitterness mourn before them.\n"
	"And when they shall say to thee: Why mournest thou? Thou shalt say: For the bruit: because it cometh, and every heart shall melt, & all hands shall be dissolved, and every spirit shall be weakened, and waters shall run by all knees: behold it cometh, and it shall be done, saith our Lord God.\n"
	"And the word of our Lord was made to me, saying:\n"
	"Son of man prophesy, and thou shalt say: Thus saith our Lord God: Speak: The sword, the sword is sharpened, and furbished.\n"
	"To kill victims it is sharpened, to glitter it is furbished: thou that movest the sceptre of my son, hast cut down every tree.\n"
	"And I gave it to be made smooth, that it may be held with the hand: this is a sharpened sword, and this is furbished, that it may be in the hand of the slayer.\n"
	"Cry, and howl, o son of man, because this same is made in my people, in all the captains of Israel, that fled: they are delivered to the sword with my people, therefore strike upon the thigh,\n"
	"Because it is proved: and that, when it shall overthrow the sceptre, it shall not be, saith our Lord God.\n"
	"Thou therefore o son of man prophesy, and strike hand against hand, and let the sword be doubled, & let the sword of the slain be tripled: this is the sword of great slaughter, that maketh them to be astonished,\n"
	"and to pine in heart, & multiplieth ruins. In all their gates have I given the trouble of the sword sharp and furbished to glitter, addressed to slaughter.\n"
	"Be thou sharpened, go to the right hand, or to the left, whithersoever the appetite of thy face is.\n"
	"Yea and I will clap hand to hand, and will fill mine indignation: I^ the Lord have spoken.\n"
	"And the word of our Lord was made to me, saying:\n"
	"And thou son of man, put thee two ways, that the sword of the king of Babylon may come: both shall come forth out of one land: and he shall take conjecture with the hand, in the head of the way of the city shall he choose it.\n"
	"Thou shalt make way that the sword may come to Rabbath of the children of Ammon, and to Juda into Jerusalem most fenced.\n"
	"For the king of Babylon stood in the high way, in the head of two ways, seeking divination, shuffling arrows: he asked the idols, and took counsel of entrails.\n"
	"On his right hand was made divination upon Jerusalem, to set engines to open the mouth in slaughter, to elevate the voice in howling, to set engines against the gates, to cast up a rampier, to build munitions.\n"
	"And he shall be as it were consulting the oracle in vain in their eyes, and imitating the rest of sabbaths: but he shall remember the iniquity to take it.\n"
	"Therefore thus saith our Lord God: For that you have remembered your iniquity, and have revealed your prevarications, and your sins have appeared in all your cogitations: for that, I say, that you remembered, you shall be taken by hand.\n"
	"But thou profane, impious prince of Israel, whose day prefixed cometh in the time of iniquity:\n"
	"Thus saith our Lord God: Take away the mitre, take off the crown: is not this it, that extolled the humble, and humbled the high?\n"
	"Iniquity, iniquity, iniquity will I put it, and this was not done, till he came to whom judgement belongeth, and I will deliver it to him.\n"
	"And thou son of man prophesy, and say: Thus saith our Lord God to the children of Ammon, and to their reproach, and thou shalt say: Sword, sword draw out thyself to kill, furbish thyself to slay, and to glitter.\n"
	"When vain things were seen for thee, and lies were divined: that thou mightest be given upon the necks of the wounded impious, whose day prefixed cometh in the time of iniquity.\n"
	"Return to thy scabbard, in the place wherein thou wast created, in the land of thy nativity I will judge thee,\n"
	"and will pour out upon thee mine indignation: in the fire of my fury will I blow upon thee, and will give thee into the hands of men unwise, and framing destruction.\n"
	"Thou shalt be food for the fire, thy blood shall be in the midst of the land, thou shalt be forgotten: because I^ the Lord have spoken.";