const char* chap936 = "And the word of our Lord was made to me, saying:\n"
	"And thou son of man doest thou not judge, doest thou not judge the city of blood?\n"
	"And thou shall shew her all her abominations, & shalt say: Thus saith our Lord God: The city shedding blood in the midst of it, that her time may come: & that hath made idols against herself, that she might be polluted.\n"
	"In thy blood, which is shed by thee, thou hast offended: and in thine idols, which thou hast made, thou art polluted: and thou hast made thy days to approach, and hast brought the time of thy years: therefore have I given thee a reproach to the Gentiles, and a mockery to all lands.\n"
	"Those that are near, and that are far from thee, shall triumph over thee: thou filthy one, noble, great in destruction.\n"
	"Behold the princes of Israel, every one in his arm, have been in thee, to shed blood.\n"
	"Father and mother they have abused with contumelies in thee, the stranger they have calumniated in the midst of thee, the pupil and widow they have made sorrowful in thee.\n"
	"My sanctuaries you have despised, and my sabbaths you have polluted.\n"
	"Detracting men have been in thee to shed blood, and upon the mountains they have eaten in thee, they have wrought wickedness in the midst of thee.\n"
	"The father's shame they have discovered in thee, the uncleanness of the menstruous woman they have humbled in thee.\n"
	"And every one hath wrought abomination upon his neighbour's wife, and the father in law hath polluted his daughter in law wickedly, the brother hath oppressed his sister the daughter of his father in thee.\n"
	"They have taken gifts in thee to shed blood: thou hast taken usury and overplus, and didst calumniate thy neighbours covetously: and thou hast forgotten me, saith our Lord God.\n"
	"Behold, I have wrung my hands upon thy covetousness, which thou hast done, & upon the blood that hath been shed in the midst of thee.\n"
	"Why, shall thy heart abide, or shall thy hands prevail in the days, which I shall make to thee? I^ the Lord have spoken, and will do it.\n"
	"And I will disperse thee into nations, & will scatter thee into lands, and will make thy uncleanness to fail from thee.\n"
	"And I will possess thee in the sight of the Gentiles, and thou shalt know that I am the Lord.\n"
	"And the word of our Lord was made to me, saying:\n"
	"Son of man, the house of Israel is turned into dross to me: all these are become brass, and tin, and iron, and lead, and dross of silver, in the midst of the furnace.\n"
	"Therefore thus saith our Lord God: Because you are all turned into dross, therefore behold I will gather you together in the midst of Jerusalem,\n"
	"with the gathering of silver, and brass, and tin, & iron, and lead, in the midst of a furnace: that I may kindle a fire in it to melt it: so will I gather you together in my fury, and in my wrath, and will rest: and I will melt you.\n"
	"And I will gather you together, and will set you on fire, in the fire of my fury, and you shall be melted in the midst thereof.\n"
	"As silver is melted in the midst of the furnace, so shall you be in the midst thereof: & you shall know that I am the Lord, when I have poured out mine indignation upon you.\n"
	"And the word of our Lord was made to me, saying:\n"
	"Son of man, say to it: Thou art an unclean land, and not rained upon in the day of fury.\n"
	"A conspiracy of Prophets in the midst thereof: as a lion roaring, and ravening the prey, have they devoured souls, they have taken the riches and the price, her widows they have multiplied in the midst thereof.\n"
	"Her Priests have contemned my law, and have polluted my sanctuaries: between a holy thing and profane they have put no difference: and between the polluted and the clean they understood not: and from my sabbaths they have turned away their eyes, and I was defiled in the midst of them.\n"
	"Her princes in the midst of her, as wolves ravening the prey to shed blood, and to destroy souls, and to pursue gains covetously.\n"
	"And her Prophets daubed them without tempering, seeing vain things, & divining lies to them, saying: Thus saith our Lord God: whereas our Lord hath not spoken.\n"
	"The people of the land they oppressed by calumny, and took away violently: the needy and poor they afflicted, and the stranger they oppressed by calumny without judgement.\n"
	"And I sought of them a man that might interpose an hedge, and stand opposite against me for the land, that I might not destroy it: and I found not.\n"
	"And I poured out mine indignation upon them, in the fire of my wrath I consumed them: I have rendered their way upon their head, saith our Lord God.";