const char* chap937 = "And the word of our Lord was made to me, saying:\n"
	"Son of man, there were two women daughters of one mother.\n"
	"And they fornicated in Aegypt, in their youth they fornicated: there were their breasts pressed, and the paps of their virginity were broken.\n"
	"And their names Oolla the elder, and Ooliba her younger sister: and I had them, & they bare sons, and daughters. Moreover their names, Samaria Oolla, and Jerusalem Ooliba.\n"
	"Oolla therefore fornicated over me, and was mad upon her lovers, upon the Assyrians approaching,\n"
	"clothed with hyacinth, the princes, and the magistrates, all the young men of concupiscences, all the horsemen, the riders of horses.\n"
	"And she gave her fornications upon them all the chosen children of the Assyrians: and in all, on whom she was mad, in their uncleanness she was polluted.\n"
	"Moreover also her fornications, which she had made in Aegypt she left not: for they also slept with her in her youth, and they brake the breasts of her virginity, and poured out their fornication upon her.\n"
	"Therefore have I delivered her into the hands of her lovers, into the hands of the children of Assur, upon whose lust she was mad.\n"
	"They discovered her ignominy, took her sons and daughters, and her they killed with the sword: and they were made notorious women, and they did judgements in her.\n"
	"Which when her sister Ooliba had seen, she was mad with lust more than she: and she gave impudently her fornication above the fornication of her sister\n"
	"to the children of the Assyrians, to the princes, and magistrates coming to her clothed with party clothing, to the horsemen that were carried on horses, and to young men all of goodly beauty.\n"
	"And I saw that she was polluted, both one way.\n"
	"And she increased her fornication: and when she had seen men painted in a wall, the images of the Chaldees expressed in colours,\n"
	"and girded with girdles about their reins, and dyed turbans on their heads, the form of all the dukes, the similitude of the children of Babylon, and of the land of the Chaldees, wherein they were born,\n"
	"she was mad upon them with the concupiscence of her eyes, & she sent messengers to them into Chaldee.\n"
	"And when the children of Babylon were come to her unto the bed of paps, they polluted her with their fornications, and she was polluted of them, and her soul was filled of them.\n"
	"She revealed also her fornications, & discovered her ignominy: & my soul departed from her, as my soul departed from her sister.\n"
	"For she hath multiplied her fornications, remembering the days of her youth, in which she fornicated in the land of Aegypt.\n"
	"And she was mad for lust upon the lying with them, whose flesh is as the flesh of asses: and as the flux of horses, their flux.\n"
	"And thou hast visited the wickedness of thy youth when thy breasts were pressed in Aegypt, & the paps of thy virginity broken.\n"
	"Therefore Ooliba, thus saith our Lord God: Behold I will raise up all thy lovers against thee, of whom thy soul is filled: & I will gather them together against thee round about,\n"
	"the children of Babylon, & all the Chaldees, the nobles, & the tyrants, & princes, all the children of the Assyrians, the young men of goodly beauty, all the captains, & magistrates, the princes of princes, & the renowned riders of horses.\n"
	"And they shall come upon thee well appointed with chariot, & wheel, a multitude of peoples: with brigantine, and buckler, and helmet they shall be armed against thee on every side: and I will give judgement before them, and they shall judge thee by their judgements.\n"
	"And I will put my zeal in thee, which they exercise with thee in fury: thy nose and thine ears they shall cut off: & the things that remain shall fall by the sword: they shall take thy sons, and thy daughters, and thy very last thing shall be devoured with fire.\n"
	"And they shall strip thee of thy garments, and shall take away the vessels of thy glory.\n"
	"And I will make thy wickedness to cease out of thee, and thy fornication out of the Land of Aegypt: neither shalt thou lift up thine eyes to them, & Aegypt thou shalt remember no more.\n"
	"Because thus saith our Lord God: Behold I will deliver thee into the hands of them, whom thou hatest, into their hands, of whom thy soul is filled.\n"
	"And they shall deal with thee in hatred, and they shall take away all thy labours, & shall let thee go naked, and full of ignominy, and the ignominy of thy fornications shall be revealed, thy wicked deed, and thy fornications.\n"
	"They have done these things to thee, because thou hast fornicated after the Nations, among which thou wast polluted in their idols.\n"
	"Thou hast walked in the way of thy sister, and I will give her cup in thy hand.\n"
	"Thus saith our Lord God: The cup of thy sister thou shalt drink deep, and wide: thou shalt be into derision & into scorn, which is most capable.\n"
	"With drunkenness and sorrow thou shall be replenished: with the cup of pensiveness, and sadness, with the cup of thy sister Samaria.\n"
	"And thou shalt drink it, and shalt drink it up even to the dregs, and the fragments thereof thou shalt devour, thou shalt rent thy breasts: because I have spoken, saith our Lord God:\n"
	"Therefore thus saith our Lord God: Because thou hast forgotten me, and hast cast me off behind thy body, thou also bear thy wickedness, and thy fornications.\n"
	"And our Lord spake to me, saying: Son of man, doest thou judge Oolla, and Ooliba, and shewest thou them their wicked deeds?\n"
	"because they have committed adultery, and blood is in their hands, and with their idols they have fornicated: moreover also their children, whom they begat for me, they have offered unto them to be devoured.\n"
	"Yea and they have done this to me. They polluted my sanctuary in that day, & profaned my sabbaths.\n"
	"And when they immolated their children to their idols, and went into my sanctuary in that day to pollute it: these things also they did in the midst of my house.\n"
	"They sent to men coming from far, to whom they had sent a messenger: therefore lo they came: to whom thou didst wash thyself, and didst anoint thine eyes about with stibic stone, and wast adorned with women's ornaments.\n"
	"Thou satest in a very fair bed, and a table was decked before thee: mine incense, and mine ointment thou didst set upon it.\n"
	"And the voice of a multitude rejoicing was on it: and on the men, that were brought of the multitude of men, and came from the desert, they did put bracelets on their hands, and beautiful crowns on their heads.\n"
	"And I said to her, that was worn in adulteries: Now will this woman also fornicate in her fornication.\n"
	"And they went to her as to an harlot woman: so went they unto Oolla, and Ooliba wicked women.\n"
	"They therefore are just men: these shall judge them with the judgement of adulteresses, and with the judgement of blood-shedders: because they are adulteresses, and blood is in their hands.\n"
	"For thus saith our Lord God: Bring a multitude to them, and deliver them into tumult, and into spoil:\n"
	"and let them be stoned with the stones of peoples, and let them be thrust through with their swords: they shall kill their sons, and daughters, and their houses they shall burn with fire.\n"
	"And I will take away the wickedness out of the land, and all women shall learn, not to do according to the wickedness of them.\n"
	"And they shall give your wickedness upon you, and the sins of your idols you shall carry: and you shall know that I am the Lord God.";