const char* chap939 = "And the word of our Lord was made to me, saying:\n"
	"Son of man, set thy face against the children of Ammon, & thou shalt prophesy of them.\n"
	"And thou shalt say to the children of Ammon: Hear ye the word of our Lord God: Thus saith our Lord God: For that thou hast said: Ha, ha, upon my sanctuary, because it is polluted: and upon the Land of Israel, because it is made desolate: and upon the house of Juda, because they are led into captivity:\n"
	"Therefore will I deliver thee to the children of the east for an inheritance, and they shall place their sheepcotes in thee, and shall set their tents in thee: they shall eat thy fruits: and they shall drink thy milk.\n"
	"And I will give Rabbath to be an habitation of camels, and the children of Ammon to be a lying place for beasts: and you shall know that I am the Lord.\n"
	"Because thus saith our Lord God: For that thou hast clapped with the hand, and strucken with the foot, and hast been glad with all thy affection upon the land of Israel:\n"
	"therefore behold I will stretch forth my hand upon thee, and will deliver thee into the spoil of the Gentiles, and will kill thee out of the peoples, and destroy thee out of the lands, and break thee: and thou shalt know that I am the Lord.\n"
	"Thus saith our Lord God: For that Moab, and Seir have said: Behold as all the Gentiles, so is the house of Juda:\n"
	"therefore behold I will open the shoulder of Moab of his cities, of his cities I say, and of his borders the noble cities of the land Bethiesimoth, and Beelmeon, and Cariathaim,\n"
	"to the children of the East with the children of Ammon, & I will give it for an inheritance: that there may be memory no more of the children of Ammon among the Gentiles.\n"
	"And in Moab I will do judgements: and they shall know that I am the Lord.\n"
	"Thus saith our Lord God: For that Idumea hath made revenge to revenge herself of the children of Juda, and hath sinned offending, & hath sought revenge of them,\n"
	"therefore thus saith our Lord God: I will stretch forth my hand upon Idumea, and will take away out of it man, and beast, and will make it desert from the South: and they that are in Dedan, shall fall by the sword.\n"
	"And I will give my revenge upon Idumea by the hand of my people Israel: and they shall do in Edom according to my wrath, and my fury: and they shall know my vengeance, saith our Lord God.\n"
	"Thus saith our Lord God: For that the Palesthines have made revenge, and have revenged themselves with all their mind, killing, and accomplishing old enmities:\n"
	"therefore thus saith our Lord God: Behold I will stretch forth my hand upon the Palesthines, and will kill the killers, and will destroy the remnant of the sea coast,\n"
	"and I will make in them great revengements arguing in fury: and they shall know that I am the Lord, when I shall have given my vengeance upon them.";