const char* chap943 = "In the tenth year, the tenth month, the eleventh day of the month, the word of our Lord was made to me, saying:\n"
	"Son of man, set thy face against Pharao the king of Aegypt: and thou shalt prophesy of him, & of all Aegypt.\n"
	"Speak, and thou shalt say: Thus saith our Lord God: Behold I to thee Pharao king of Aegypt, thou great dragon, which liest in the midst of thy rivers, & sayest: The river is mine, & I made it myself.\n"
	"And I will put a bridle in thy jaws: and I will fasten the fishes of thy rivers to thy scales: and I will draw thee out of the midst of the rivers, and all thy fishes shall stick to thy scales.\n"
	"And I will cast thee forth into the desert, and all the fishes of thy river: thou shalt fall upon the face of the earth, thou shalt not be collected, nor gathered together: to the beasts of the earth, and to the fowls of the heaven have I given thee to be devoured.\n"
	"And all the inhabitants of Aegypt shall know that I am the Lord: for that thou hast been a staff of reed to the house of Israel.\n"
	"When they took thee with the hand, & thou wast broken, and didst rent all their shoulder: and they leaning upon thee, thou was broken, and didst dissolve all their reins.\n"
	"Therefore thus saith our Lord God: Behold I will bring upon thee the sword: and will kill out of thee man, & beast.\n"
	"And the Land of Aegypt shall be into a desert, and into a wilderness: & they shall know that I am the Lord: for that thou hast said: The river is mine, & I made it.\n"
	"Therefore behold I to thee, and to thy rivers: and I will give the Land of Aegypt into desolations, destroyed with the sword, from the tower of Syene, even to the borders of Aethiopia.\n"
	"The foot of men shall not pass through it, neither shall the foot of beast go in it: & it shall not be inhabited forty years.\n"
	"And I will make the Land of Aegypt desert in the midst of desert lands, & the cities thereof in the midst of cities overthrown, and they shall be desolate forty years: & I will disperse the Aegyptians into nations, and will scatter them into the lands.\n"
	"Because thus saith our Lord God: After the end of forty years I will gather Aegypt out of the peoples in which they had been dispersed.\n"
	"And I will bring back the captivity of Aegypt, & will place them in the land of Phatures, in the land of their nativity, and they shall be there as a low kingdom:\n"
	"among other kingdoms it shall be lowest, and it shall no more be elevated over the nations, and I will diminish them that they rule not over the Gentiles.\n"
	"And they shall no more be to the house of Israel in confidence, teaching iniquity, that they may fly, and follow them: and they shall know that I am the Lord God.\n"
	"And it came to pass in the seven and twentieth year, in the first, in the first of the month: the word of our Lord was made to me, saying:\n"
	"Son of man, Nabuchodonosor the king of Babylon hath made his army to serve with great service against Tyre: every head made bald, and every shoulder hath the hair plucked off: and there hath been no reward rendered him, nor his army concerning Tyre, for the service that he served me against it.\n"
	"Therefore thus saith our Lord God: Behold I will give Nabuchodonosor the king of Babylon in the land of Aegypt: & he shall take the multitude thereof, and take the booties thereof for a prey, and rifle the spoils thereof: & it shall be a reward for his army,\n"
	"and for the work, that he served me against it: I have given him the land of Aegypt, for that they have laboured for me, saith our Lord God.\n"
	"In that day there shall a horn spring to the house of Israel, & I will give thee an open mouth in the midst of them: and they shall know that I am the Lord.";