const char* chap948 = "And the word of our Lord was made to me saying:\n"
	"Son of man prophesy of the Pastors of Israel: prophesy, and thou shalt say to the Pastors: Thus saith our Lord God: Woe to the Pastors of Israel, which fed themselves: are not the flocks fed of the Pastors?\n"
	"You did eat the milk, & were covered with the wool, & that which was fat ye killed: but my flock you fed not.\n"
	"That which was weak, you strengthened not: and that which was sick, you healed not: that which was broken, you bound not up: and that which was cast away, you brought not again: and that which was lost, you sought not: but with austerity you did rule over them, and with might.\n"
	"And my sheep were dispersed, because there was no Pastor: & they came to be devoured of all the beasts of the field, and were dispersed.\n"
	"My flocks have wandered in all mountains, and in every high hill: and upon all the face of the earth were my flocks dispersed, and there was none that sought them, there was none, I say, that sought them.\n"
	"Therefore ye shepherds hear the word of our Lord:\n"
	"Live I, saith our Lord God: that for as much as my flocks have been made a spoil: & my sheep to be devoured of all the beasts of the field, because there was no Pastor (for my Pastors did not seek my flock, but the Pastors fed themselves, & my flocks they fed not:)\n"
	"therefore ye Pastors hear the word of our Lord:\n"
	"Thus saith our Lord God: Behold I myself upon the shepherds, I will require my flock of their hand, and I will make them cease, that they feed my flock no more, & that the Pastors feed no more themselves: and I will deliver my flock out of their mouth, and it shall no more be meat for them.\n"
	"Because thus saith our Lord God: Behold I myself will seek my sheep, and will visit them.\n"
	"As the Pastor visiteth his flock in the day when he shall be in the midst of his sheep which were scattered: so will I visit my sheep, and will deliver them out of all places, wherein they had been dispersed in the day of the cloud and of darkness.\n"
	"And I will bring them out of the peoples, and will gather them out of the lands, and will bring them into their own land: and I will feed them in the mountains of Israel, in the rivers, and in all the seats of the land.\n"
	"In the most plentiful pastures will I feed them, & in the high mountains of Israel shall be their pastures: there shall they rest on the green grass, and in fat pastures they shall be fed upon the mountains of Israel.\n"
	"I will feed my sheep, & I will make them lie, saith our Lord God.\n"
	"That which was lost, I will seek: & that which was cast away, I will bring again: & that which was broken I will bind up: & that which was weak, I will strengthen: & that which was fat & strong, I will keep: & will feed them in judgement.\n"
	"And you my flocks, thus saith our Lord God: Behold I judge between beast & beast, of rams, & of buck goats.\n"
	"Was it not enough for you to feed upon good pastures? You have besides also trodden down with your feet the residue of your pastures: and when you drank most pure water, the rest you troubled with your feet.\n"
	"And my sheep were fed with those things, which were trodden with your feet: and what your feet had troubled, that did they drink.\n"
	"Therefore thus saith our Lord God to you: Behold, I myself do judge between the fat beast & the lean.\n"
	"For that you with sides & shoulders did thrust, and with your horns struck all the weak beasts, till they were dispersed abroad:\n"
	"I will save my flock, & it shall be no more into spoil, & I will judge between beast and beast.\n"
	"AND I WILL RAISE UP OVER THEM ONE PASTOR: who shall feed them, my servant David: he shall feed them, & he shall be their Pastor.\n"
	"And I^ the Lord will be their God: & my servant David the Prince in the midst of them: I^ the Lord have spoken.\n"
	"And I will make a covenant of peace with them, and will make the most cruel beasts to cease out of the land: & they that dwell in the desert, shall sleep secure in the forests.\n"
	"And I will put them round about my hill a blessing: and I will bring down the showers in his time, there shall be rains of blessing.\n"
	"And the tree of the field shall give his fruit, and the earth shall give her spring, and they shall be in their land without fear: and they shall know that I am the Lord, when I shall have broken the chains of their yoke, and shall have delivered them out of the hand of those that rule over them.\n"
	"And they shall be no more for a spoil in the Gentiles, neither shall the beasts of the earth devour them: but they shall dwell confidently without any terror.\n"
	"And I will raise up unto them a bud of name: and they shall be no more diminished for famine in the land, neither shall they bear any more the reproach of the Gentiles.\n"
	"And they shall know that I^ the Lord their God with them, and they my people the house of Israel: saith our Lord God.\n"
	"And you my flocks, the flocks of my pasture are men: and I^ the Lord your God, saith our Lord God.";