const char* chap949 = "And the word of our Lord was made to me, saying:\n"
	"Son of man set thy face against mount Seir, and thou shalt Prophesy of it, and shalt say to it:\n"
	"Thus saith our Lord God: Behold I to thee mount Seir, and I will stretch forth my hand upon thee, & will make thee desolate and desert.\n"
	"Thy cities I will destroy, & thou shalt be desert: & thou shalt know that I am the Lord.\n"
	"For that thou hast been an everlasting enemy, and hast shut up the children of Israel into the hands of the sword in the time of their affliction, in the time of extreme iniquity.\n"
	"Therefore live I, saith our Lord God, that I will deliver thee unto blood, & blood shall persecute thee: & whereas thou hast hated blood, blood shall persecute thee.\n"
	"And I will make mount Seir desolate & desert: & I will take from it the comer & goer.\n"
	"And I will fill his mountains with his slain: in thy hills, and in thy valleys, & in the torrents shall the slain with the sword fall.\n"
	"Into everlasting desolations will I deliver thee, & thy cities shall not be inhabited: & thou shalt know that I am the Lord God.\n"
	"For that thou hast said: The two nations, & the two lands shall be mine, & I will possess them by inheritance: whereas our Lord was there.\n"
	"Therefore live I, saith our Lord God, that I will do according to thy wrath, and according to thy zeal, which thou hast used hating them: & I will be made known by them, when I shall have judged thee.\n"
	"And thou shalt know that I^ the Lord have heard all thy reproaches, that thou hast spoken of the mountains of Israel, saying: They are desert, they are given unto us to devour.\n"
	"And you rose up upon me with your mouth, and have derogated your words against me: I heard it.\n"
	"Thus saith our Lord God: All the earth rejoicing, I will bring thee into a wilderness.\n"
	"As thou hast rejoiced upon the inheritance of the house of Israel, because it was dissipated, so will I do to thee: Thou shalt be dissipated mount Seir, & all Idumea: and they shall know that I am the Lord.";