const char* chap952 = "And the word of our Lord was made to me, saying:\n"
	"Son of man, set thy face against Gog, and the Land of Magog, the Prince of the head of Mosoch, and Thubal: and prophesy of him and thou shalt say to him: Thus saith our Lord God: Behold I to thee Gog Prince of the head of Mosoch and Thubal.\n"
	"And I will turn thee about, and will put a bit in thy jaws: and will bring forth thee, and all thine army, the horses and horsemen clothed with brigantines,\n"
	"a great multitude, of them that take spear and buckler and sword.\n"
	"The Persians, Aethiopians, and Libyans with them, all with shields & helmets.\n"
	"Gomer, and all her troops, the houses of Thogorma the sides of the North, and all his strength, and many peoples with them.\n"
	"Prepare and make ready thyself, and all thy multitude, that is gathered to thee in heaps: and be thou as a precept to them.\n"
	"After many days thou shalt be visited: in the later end of years thou shalt come to the land, that is returned from the sword, and is gathered together out of many peoples, to the mountains of Israel, that were desert continually: this same is brought forth out of the peoples, and they shall all dwell in it confidently.\n"
	"And going up as a tempest thou shalt come, & as it were a cloud that thou mayst cover the land, thou & thy troops, & many peoples with thee.\n"
	"Thus saith our Lord God: In that day shall words ascend upon thy heart, and thou shalt think a most wicked thought.\n"
	"And shalt say: I will go up to the land without wall: I will come to them that rest, & dwell securely: all these dwell without wall, there are no bars nor gates to them:\n"
	"That thou mayst take the spoils, & invade the prey, that thou mayst lay thy hand upon them, that had been desert, & afterward restored, & upon the people that is gathered together out of the Gentiles, which hath begun to possess, & to be inhabitant of the navel of the earth.\n"
	"Saba, & Dedan, and the merchants of Tharsis, & all the lions thereof shall say to thee: What comest thou to take spoils? Behold thou hast gathered thy multitude to take the prey, that thou mayst take silver, and gold, and mayst take away stuff & substance, and spoil infinite booties.\n"
	"Therefore prophesy thou son of man, and thou shalt say to Gog: Thus saith our Lord God: Why shalt thou not know in that day, when my people of Israel shall dwell confidently?\n"
	"And thou shalt come out of thy place from the sides of the North, thou & many peoples with thee, all riders of horses, a great company, and a vehement army.\n"
	"And thou shalt ascend upon my people of Israel as a cloud, that thou cover the earth. In the later days shalt thou be, and I will bring thee upon my land: that the Gentiles may know me, when I shall be sanctified in thee before their eyes, o Gog.\n"
	"Thus saith our Lord God: Thou then art he, of whom I spake in the days of old, in the hand of my servants the Prophets of Israel, which prophesied in the days of those times, that I would bring in thee upon them.\n"
	"And it shall be in that day, in the day of the coming of Gog upon the land of Israel, saith our Lord God, mine indignation shall ascend in my fury.\n"
	"And in my zeal, and in the fire of my wrath I have spoken. That in that day shall be a great commotion upon the land of Israel:\n"
	"and at my presence shall the fishes of the sea be moved, and the fowls of heaven, and the beasts of the field, and every creeping thing, that moveth upon the ground, and all men that are upon the face of the earth: & the mountains shall be overthrown, & the hedges shall fall, and every wall shall fall on the ground.\n"
	"And I will call in against him in all my mountains the sword, saith our Lord God: every man's sword shall be directed against his brother.\n"
	"And I will judge him with pestilence, & blood, & vehement shower, & mighty great stones: fire, and brimstone will I rain upon him, and upon his army, and upon the many peoples that are with him.\n"
	"And I will be magnified, and I will be sanctified: and I will be known in the eyes of many nations: and they shall know that I am the Lord.";