const char* chap953 = "But thou son of man, prophesy against Gog, & thou shalt say: Thus saith our Lord God: Behold I upon thee Gog, the Prince of the head of Mosoch and Thubal.\n"
	"And I will turn thee about, & will reduce thee, and will make thee ascend from the sides of the North: & will bring thee upon the mountains of Israel.\n"
	"And I will strike thy bow in thy left hand, & thine arrows I will cast down out of thy right hand.\n"
	"Upon the mountains of Israel shalt thou fall, and all thy troops, and thy peoples that are with thee: to the wild beasts, to the birds, and to every fowl, and to the beasts of the earth have I given thee to be devoured.\n"
	"Thou shalt fall upon the face of the field: because I have spoken, saith our Lord God.\n"
	"And I will send in fire upon Magog, and on them that dwell in the islands confidently: and they shall know that I am the Lord.\n"
	"And my holy name will I make known in the midst of my people Israel, and I will pollute my holy name no more: and the Gentiles shall know that I am the Lord the holy one of Israel.\n"
	"Behold it cometh, and it is done, saith our Lord God: this is the day, whereof I have spoken.\n"
	"And the inhabitants shall go forth of the cities of Israel, and shall set on fire and burn weapons, buckler, and spears, bow and arrows, and hand-staves, and poleaxes: and they shall burn them with fire seven years.\n"
	"And they shall not carry trees out of the countries, nor cut down out of the forests: because they shall burn the weapons with fire, & shall make prey of them, to whom they had been a prey, & they shall spoil their spoilers, saith our Lord God.\n"
	"And it shall be in that day: I will give Gog a renowned place for a sepulchre in Israel: the valley of wayfaring men on the East of the sea, which shall make them that pass by to be astonished: & they shall there burn Gog, and all his multitude, and it shall be called the valley of the multitude of Gog.\n"
	"And the house of Israel shall bury them, that they may cleanse the land seven months.\n"
	"And all the people of the land shall bury him, and it shall be unto them a renowned day, wherein I was glorified, saith our Lord God.\n"
	"And they shall appoint men continually going about the land, to bury & to seek them, that were remaining upon the face of the earth, that they may cleanse it: and after seven months they shall begin to seek.\n"
	"And they that travel through the land shall go about: and when they shall see the bone of man, they shall set up a sign beside it, till the buriers bury it in the valley of the multitude of Gog.\n"
	"And the name of the city Amona, and they shall cleanse the land.\n"
	"Thou therefore o son of man, saith our Lord God, say to every fowl, and to all birds, and to all the beasts of the field: Come together, make haste, run together on every side to my victim, which I immolate for you, the great victim upon the mountains of Israel: that you may eat the flesh, and drink the blood.\n"
	"The flesh of the strong shall you eat, and the blood of the princes of the earth shall you drink: of rams, of lambs, and of buckgoats, and bulls, and of fed wares, and of all fat things.\n"
	"And you shall eat the fat your fill, and shall drink blood till you be drunk of the victim, which I shall immolate for you.\n"
	"And you shall be filled upon my table of horse, and strong horsemen, and of all the men of war, saith our Lord God.\n"
	"and I will put my glory in the Gentiles: and all nations shall see my judgement, that I have done, and my hand, that I have put upon them.\n"
	"And the house of Israel shall know that I am the Lord their God from that day and so forward.\n"
	"And the Gentiles shall know that the house of Israel was taken in their iniquity, for that they forsook me, and I hid my face from them: and delivered them into the hands of the enemies, and they fell all by the sword.\n"
	"According to their uncleanness and wickedness have I done to them, and have hid my face from them.\n"
	"Therefore thus saith our Lord God: Now will I bring back the captivity of Jacob, and will have mercy on all the house of Israel: and I will take on me zeal for my holy name.\n"
	"And they shall bear their confusion, and all the prevarication wherewith they prevaricated against me, when they shall dwell in their land confidently fearing no man:\n"
	"and I shall have brought them back out of the peoples, & shall have gathered them together out of the lands of their enemies, and shall be sanctified in them, in the eyes of many nations.\n"
	"And they shall know that I am the Lord their God, for that I transported them into the nations, and have gathered them together upon their own land, & have not left any of them there.\n"
	"And I will hide my face no more from them, because I have poured out my spirit upon all the house of Israel, saith our Lord God.";