const char* chap954 = "In the five & twentieth year of our transmigration, in the beginning of the year, the tenth of the month, the fourteenth year, after the city was strucken: in this self-same day the hand of our Lord was made upon me, & he brought me thither.\n"
	"In the visions of God he brought me into the Land of Israel, & left me upon a mountain exceeding high: upon which there was as it were the building of a city bending toward the south.\n"
	"And he brought me in thither: and behold a man, whose form was as the form of brass, and a linen cord in his hand, and a reed of measure in his hand: & he stood in the gate.\n"
	"And the same man spake to me: Son of man, see with thine eyes, and hear with thine ears, & set thy heart on all things, which I will shew thee: for thou art brought hither that they may be shewed to thee: declare all things that thou seest, to the house of Israel.\n"
	"And behold a wall on the outside round about the house, & in the man's hand a reed of measure of six cubits & a palm: & he measured the breadth of the building with one reed, the height also with one reed.\n"
	"And he came to the gate, that looked to the way of the east, & he ascended by the steps thereof: & he measured the threshold of the gate with one reed the breadth, that is, one threshold with one reed in breadth:\n"
	"and a chamber with one reed in length, and one reed in breadth: and between the chambers five cubits:\n"
	"and the threshold of the gate by entry of the gate within, with one reed.\n"
	"And he measured the entry of the gate of eight cubits, and the front thereof of two cubits: and the entry of the gate was within.\n"
	"Moreover the chambers of the gate to the way of the East, three on this side, and three on that side: one measure of the three, and one measure of the fronts, on both parts.\n"
	"And he measured the breadth of the threshold of the gate ten cubits: and the length of the gate of thirteen cubits:\n"
	"and the border before the chambers of one cubit: and one cubit the end on both sides, and the chambers were of six cubits, on this side and that side.\n"
	"And he measured the gate from the roof of the chamber, even to the roof thereof, the breadth of five and twenty cubits: door against door.\n"
	"And he made fronts by sixty cubits: & to the front the court of the gate on every side round about.\n"
	"And before the face of the gate, which raught even to the face of the entry of the inner gate, fifty cubits.\n"
	"And oblique windows in the chambers, and in their fronts, which were within the gate on every side round about: & in like manner there were also in the entries windows round about within, and before the fronts the picture of palm trees graven.\n"
	"And he brought me out of the utter court, & behold cells, and the pavement paved with stone in the court round about: thirty cells in the compass of the pavement.\n"
	"And the pavement in the front of the gates according to the length of the gates was beneath.\n"
	"And he measured the breadth from the face of the lower gate even to the front of the inner court without, an hundred cubits to the East, and to the North.\n"
	"The gate also that looked to the way of the North of the utter court, he measured as well in length as in breadth.\n"
	"And the chambers thereof three on this side, & three on that side: and the front thereof, and the entry thereof according to the measure of the former gate, of fifty cubits the length thereof, and the breadth of five and twenty cubits.\n"
	"And the windows thereof, & the entry, and the gravings according to the measure of the gate, that looked to the East, and the ascent thereof was of seven steps, and an entry before it.\n"
	"And the gate of the inner court against the gate of the North, and the East gate: and he measured from gate even to gate an hundred cubits.\n"
	"And he brought me out to the way of the South, and behold the gate, that looked to the South: and he measured the front thereof, and the entry thereof according to the former measures.\n"
	"And the windows thereof, and the entries round about, as the other windows: of fifty cubits in length, and in breadth of five and twenty cubits.\n"
	"And on seven steps was the ascent to it: and an entry before the doors thereof: and there were graven palm trees, one on this side, and another on that side in the front thereof.\n"
	"And the gate of the inner court in the way of the South: and he measured from gate even to gate in the way of the South, an hundred cubits.\n"
	"And he brought me into the inner court to the South gate: and he measured the gate according to the former measures.\n"
	"The chamber thereof, and the front thereof, and the entry thereof with the same measures: and the windows thereof, and entry thereof round about fifty cubits of length, and of breadth five and twenty cubits.\n"
	"And the entry round about in length of five and twenty cubits, & in breadth of five cubits.\n"
	"And the entry thereof to the utter court, & the palm-trees thereof in the front: & there were eight steps, on which the ascent was through it.\n"
	"And he brought me in into the inner court by the way of the east: & he measured the gate according to the former measures.\n"
	"The chamber thereof, and the front thereof, and the entry thereof as before: and the windows thereof, and the entries thereof round about, in length of fifty cubits, & in breadth of five and twenty cubits.\n"
	"And the entry thereof, that is, of the utter court: & the graven palm-trees in the front thereof on this side and on that side: and on eight steps the ascent thereof.\n"
	"And he brought me into the gate, that looked to the North: & he measured according to the former measures.\n"
	"The chamber thereof, and the front thereof, and the entry thereof, and the windows thereof round about, in length of fifty cubits, and breadth of five and twenty cubits.\n"
	"And the entry thereof looked to the utter court: and the graving of palm-trees in the front thereof on this side & on that side: and upon eight steps the ascent thereof.\n"
	"And at every chamber a door in the forefronts of the gates: there they washed the holocaust.\n"
	"And in the entry of the gate, two tables on this side, and two tables on that side: that there might be immolated upon them holocaust, & for sin, and for offence.\n"
	"And on the utter side, which goeth up to the door of the gate, that goeth on toward the North, two tables: and at the other side before the entry of the gate, two tables.\n"
	"Four tables on this side, and four tables on that side: at the sides of the gate were eight tables, whereupon they did immolate.\n"
	"And the four tables for holocaust, were made of square stones: in length of one cubit and an half, and in breadth of one cubit and an half, and in height of one cubit: upon which they shall put the vessels, wherein is immolated the holocaust, and the victim.\n"
	"And the brims of them of one palm, bowed back within round about: and upon the tables, the flesh of the oblation.\n"
	"And without the inner gate the cells of the singing men in the inner court, which was on the side of the gate that looketh to the North: and the faces of them against the way of the South, one at the side of the East gate, which looked to the way of the North.\n"
	"And he said to me: This is the chamber, which looketh to the way of the South, it shall be for the Priests, that watch in the wards of the temple.\n"
	"Moreover the chamber that looketh to the way of the North shall be for the Priests, that watch upon the ministry of the altar. These are the children of Sadoc, which of the children of Levi approach to our Lord to minister unto him.\n"
	"And he measured the court in length of an hundred cubits, and in breadth of an hundred cubits square: and the altar before the face of the temple.\n"
	"And he brought me into the entry of the temple: and he measured five cubits on this side, and five cubits on that side: and the breadth of the gate of three cubits on this side, and of three cubits on that side.\n"
	"And the length of the entry of twenty cubits: and the breadth of eleven cubits, and by eight steps was the ascent to it. And there were pillars in the fronts: one on this side, and another on that side.";