const char* chap958 = "And he turned me to the way of the utter sanctuary, which looked toward the East: and it was shut.\n"
	"And our Lord said to me: This gate shall be shut: it shall not be opened, and man shall not pass through it: Because our Lord the God of Israel is entered in through it, and it shall be shut\n"
	"for the Prince. The Prince himself shall sit in it, to eat bread before our Lord: by the way of the gate of the entry shall he enter in, and by the way thereof he shall go out.\n"
	"And he brought me by the way of the North gate in the sight of the house: and I saw, & behold the glory of our Lord filled the house of our Lord: and I fell on my face.\n"
	"And our Lord said to me: Son of man set thy heart, and see with thine eyes, and hear with thine ears all things, that I speak to thee concerning all the ceremonies of the house of our Lord, and concerning all the laws thereof: & thou shalt set thy heart in the ways of the temple, by all the goings out of the sanctuary.\n"
	"And thou shalt say to the house of Israel that exasperateth me: Thus saith our Lord God: Let all your wicked deeds suffice you o house of Israel:\n"
	"because you bring in strange children uncircumcised in heart, & uncircumcised in flesh, to be in my sanctuary, & to pollute my house, & you offer my breads, the fat, and the blood: & you dissolve my covenant in all your wicked abominations.\n"
	"And you have not kept the precepts of my sanctuary: & you have set keepers of my observances in my sanctuary to your own selves.\n"
	"Thus saith our Lord God: Every stranger uncircumcised in heart, & uncircumcised in flesh, shall not enter into my sanctuary, every strange child that is in the midst of the children of Israel.\n"
	"Yea and the Levites that have revolted far from me in the error of the children of Israel, & have erred from me after their idols, and have borne their iniquity:\n"
	"they shall be officers in my sanctuary, and porters of the gates of the house, and ministers of the house: they shall kill the holocausts, and the victims of the people: & they shall stand in their sight, to serve them.\n"
	"For that they have served them in the sight of their idols, and were made to the house of Israel a scandal of iniquity: therefore have I lifted up mine hand upon them, saith our Lord God, & they shall bear their iniquity:\n"
	"and they shall not approach to me, to do the function of priesthood unto me, neither shall they approach to all my sanctuary by Sancta Sanctorum: but they shall bear their confusion, and their wicked abominations which they have done.\n"
	"And I will make them porters of the house, in all the ministry thereof, and in all things that shall be done therein.\n"
	"But the Priests, and Levites, the sons of Sadoc, which kept the ceremonies of my sanctuary, when the children of Israel erred from me, they shall approach to me, to minister unto me: & they shall stand in my sight, to offer me the fat, and the blood, saith our Lord God.\n"
	"They shall enter into my sanctuary, and they shall approach to my table, to minister unto me, and to keep my ceremonies.\n"
	"And when they shall enter into the gates of the inner court, they shall be clothed with linen garments: neither shall any woollen thing come upon them, when they minister in the gates of the inner court & within.\n"
	"There shall be linen mitres on their heads, & there shall be linen breeches on their loins, & they shall not be girded in sweat.\n"
	"And when they shall go out to the utter court unto the people, they shall put off from them their vestments, wherein they had ministered, and shall lay them up in the vestry of the sanctuary, & they shall clothe themselves with other garments: and they shall not sanctify the people in their vestures.\n"
	"And they shall not shave their head, nor nourish their hair: but polling they shall poll their heads.\n"
	"And no Priest shall drink wine when he is to enter into the inner court.\n"
	"And widow, and her that is divorced they shall not take for wives, but virgins of the seed of the house of Israel: but a widow also which hath been the widow of a Priest, they shall take.\n"
	"And they shall teach my people what is between a holy thing and polluted, & between clean and unclean they shall shew to them.\n"
	"And when there shall be a controversy, they shall stand in my judgements, & shall judge: my laws, and my precepts in all my solemnities shall they keep, and my sabbaths they shall sanctify.\n"
	"And to a dead man they shall not enter in, lest they be polluted, but to father and mother, and son and daughter, & brother & sister, which hath not had another husband: in which they shall be contaminated.\n"
	"And after that he is cleansed, seven days shall be numbered to him.\n"
	"And in the day of his entering into the sanctuary to the inner court to minister unto me in the sanctuary, he shall offer for his sin, saith our Lord God.\n"
	"And there shall not be inheritance to them, I am their inheritance: and possession you shall not give them in Israel, for I am their possession.\n"
	"The victim both for sin and for offence they shall eat: and every vowed thing in Israel shall be theirs.\n"
	"And the first fruits of all the first born, and all the libaments of all things that are offered, shall be the priest's: and the first fruits of your meats you shall give to the priest, that he may lay up a blessing for thy house.\n"
	"All carrion, and thing taken by a beast of birds, and of cattle the Priests shall not eat.";