const char* chap967 = "BALTASSAR the king made a great feast to his nobles a thousand: and every one drank according to his age.\n"
	"He commanded therefore now being drunk that the vessels of gold & silver, should be brought, which Nabuchodonosor his father had carried away out of the temple, that was in Jerusalem, that the king, and his Nobles might drink in them, and his wives, and concubines.\n"
	"Then were the golden and silver vessels brought, which he had carried away out of the temple, that was in Jerusalem: and the king and his nobles drank in them, his wives and concubines.\n"
	"They drank wine, and praised their gods of gold, and of silver, of brass, of iron, and of wood, and of stone.\n"
	"In the very same hour there appeared fingers, as it were of the hand of a man, writing over against the candlestick in the utter part of the wall of the king's palace: and the king beheld the joints of the hand that wrote.\n"
	"Then was the king's face changed, and his cogitations troubled him: and the junctures of his reins were loosed, and his knees were strucken one against the other.\n"
	"The king therefore cried out mightily that they should bring in the magicians, Chaldees, and soothsayers. And the king speaking said to the wisemen of Babylon: Whosoever shall read this writing, and shall make the interpretation thereof manifest unto me, shall be clothed with purple, and shall have a golden chain on his neck, & shall be the third in my kingdom.\n"
	"Then all the king's wisemen going in could not neither read the writing, nor declare the interpretation to the king.\n"
	"Wherewith king Baltassar was much troubled, and his countenance was changed: yea and his nobles were troubled.\n"
	"And the queen for the thing that had happened to the king, and his nobles, entered into the house of the feast: and speaking she said: King for ever live: let not thy cogitations trouble thee, neither let thy face be changed.\n"
	"There is a man in thy kingdom, that hath the spirit of the holy gods in him: and in the days of thy father knowledge and wisdom were found in him: for king Nabuchodonosor also thy father appointed him prince of the magicians, enchanters, Chaldees and soothsayers, thy father, I say o king:\n"
	"Because more ample spirit, and prudence, and understanding, & interpretation of dreams, and shewing of secrets, and solution of things bound were found in him, that is, in Daniel: to whom the king gave the name Baltassar. Now therefore let Daniel be called, and he will tell the interpretation.\n"
	"Daniel therefore was brought in before the king. To whom the king speaking, said: Art thou Daniel of the children of the captivity of Juda, whom my father the king brought out of Jewry?\n"
	"I have heard of thee, that thou hast the spirit of the gods, and more ample knowledge, and understanding, and wisdom are found in thee.\n"
	"And now there have come into my sight the wise magicians, that they might read this writing, and might shew me the interpretation thereof: and they could not declare me the sense of this word.\n"
	"Moreover I have heard of thee, that thou canst interpret obscure things, and resolve things bound: if therefore thou be able to read the writing, & to shew me the interpretation thereof, thou shalt be clothed with purple, and shalt have a chain of gold about thy neck, & shalt be the third prince in my kingdom.\n"
	"To which things Daniel answering, said before the king: Thy rewards be they unto thee, and the gifts of thy house give to another: but the writing will I read thee, o king, and the interpretation thereof will I shew to thee.\n"
	"O king, God the most high gave to Nabuchodonosor thy father kingdom and magnificence, glory and honour.\n"
	"And for the magnificence, which he gave to him, all peoples, tribes, and tongues trembled, and feared him: whom he would he killed: and whom he would, he struck: and whom he would he exalted: and whom he would, he humbled.\n"
	"But when his heart was elevated, and his spirit obstinately set to pride, he was deposed from the throne of his kingdom, and his glory was taken away.\n"
	"And he was cast out from the sons of men, yea and his heart was set with the beasts, and with the wild asses was his habitation: grass also he did eat as an ox, and with the dew of heaven his body was imbrued: till he knew that the Highest had power in the kingdom of men, and whomsoever it shall please him he will raise up over it.\n"
	"Thou also his son Baltassar, hast not humbled thy heart, whereas thou knowest all these things:\n"
	"but against the dominator of heaven thou wast elevated: and the vessels of his house have been brought before thee: and thou, and thy nobles, and thy wives, and thy concubines have drunk wine in them: the gods also of silver, and of gold, and of brass, of iron, and of wood, and of stone that see not, nor hear, nor feel, thou hast praised: moreover the God, that hath thy breath in his hand, and all thy ways, thou hast not glorified.\n"
	"Therefore from him is the joint of the hand sent, which hath written this that is drawn.\n"
	"And this is the writing which is ordered: MANE, THECEL, PHARES.\n"
	"And this the interpretation of the word. MANE: God hath numbered thy kingdom, and hath finished it.\n"
	"THECEL: thou art weighed in the balance, and art found having less.\n"
	"PHARES: thy kingdom is divided, and is given to the Medes, and Persians.\n"
	"Then the king commanding Daniel was clothed with purple, and a chain of gold was put about his neck: & it was proclaimed of him that he had power the third in the kingdom.\n"
	"The same night was Baltassar the king of Chaldee slain.\n"
	"And Darius the Mede succeeded into the kingdom, being three score and two years old.";