const char* chap97 = "This also is the law of an host for an offence, the most Holy:\n"
	"therefore where the holocaust is immolated, the victim also for an offence shall be slain: the blood thereof shall be poured round about the altar.\n"
	"They shall offer thereof the rump and the fat that covereth the entrails:\n"
	"the two little kidneys, and the fat that is beside the guts, and the caul of the liver with the two little kidneys.\n"
	"And the Priest shall burn them upon the altar: it is the burnt sacrifice of our Lord for an offence.\n"
	"Every male of the Priests stock, in a holy place shall eat this flesh, because it is most Holy.\n"
	"As the host for sin is offered, so also that for an offence: the law of both hosts shall be one: to the Priest that offereth it, it shall pertain.\n"
	"The Priest that offereth the victim of holocaust, shall have the skin thereof.\n"
	"And every sacrifice of flour, that is baked in the one, & whatsoever is prepared upon the gridiron, or in the frying pan, it shall be that Priest's by whom it is offered.\n"
	"Whether they be tempered with oil, or dry, to all the sons of Aaron equal measure shall be divided to ever one.\n"
	"This is the law of the host of pacifics that is offered to our Lord.\n"
	"If the oblation be for thanks-giving, they shall offer loaves without leaven tempered with oil, and wafers unleavened laid over with oil, and fried flour, and manchets tempered with the mingling of oil:\n"
	"Loaves also leavened with the host of thanks, which is offered for pacifics:\n"
	"whereof one for first fruits shall be offered to our Lord, and shall be the Priest's that shall pour out the blood of the host.\n"
	"the flesh whereof shall be eaten the same day, neither shall any of it remain until morning.\n"
	"If any man by vow, or of his own accord offer an host, it shall in like manner be eaten the same day: but if ought remain until the morrow, it is lawful to eat it:\n"
	"but whatsoever the third day shall find, fire shall consume it.\n"
	"If any man eat of the flesh of the victim of pacifics the third day, the oblation shall be of none effect, neither shall it profit the offerer: yea rather whatsoever soul shall defile itself with such meat, shall be guilty of prevarication.\n"
	"The flesh that hath touched any unclean thing, shall not be eaten, but shall be burnt with fire: he that is clean, shall eat thereof.\n"
	"A soul being polluted that eateth of the flesh of the host of pacifics, which is offered to our Lord, shall perish from his people.\n"
	"And that which hath touched the uncleanness of man, or of beast, or of any thing that can pollute, & eateth of such kind of flesh, shall perish from his people.\n"
	"And our Lord spake to Moyses, saying:\n"
	"Speak to the children of Israel: The fat of a sheep, and of an oxe, and of a goat you shall not eat.\n"
	"The fat of the carcass of carrion, & of the beast that was caught of another beast, you shall have for diverse uses.\n"
	"If any man eat the fat that should be offered for the burnt sacrifice of our Lord, he shall perish out of his people.\n"
	"The blood also of whatsoever beast you shall not take in meat, as well of birds as of cattle.\n"
	"Every soul that eateth blood, shall perish out of his people.\n"
	"And our Lord spake to Moyses, saying:\n"
	"Speak to the children of Israel, saying: He that offereth a victim of pacifics to our Lord, let him offer therewith a sacrifice also, that is, the libaments thereof.\n"
	"He shall hold in his hands the fat of the host, and the breast: & when he hath offered and consecrated both to our Lord, he shall deliver them to the Priest,\n"
	"who shall burn the fat upon the altar, but the breast shall be Aaron's, and his sons'.\n"
	"The right shoulder also of the pacific hosts shall fall for first fruits of the Priest.\n"
	"He of the sons of Aaron, that offereth the blood, and the fat, himself shall have the right shoulder also for his portion.\n"
	"For the breast of elevation and the shoulder of separation I have taken of the children of Israel, from their pacific hosts, and have given them to Aaron the Priest, and to his sons, by a law for ever, of all the people of Israel.\n"
	"This is the anointing of Aaron and his sons, in the ceremonies of our Lord, in the day when Moyses offered them, that they might do the function of priesthood,\n"
	"and the things that our Lord commanded to be given them of the children of Israel, by a perpetual religion in their generations.\n"
	"This is the law of holocaust, and of the sacrifice of sin, and for an offence, and for consecration, and the victims of pacifics:\n"
	"Which our Lord appointed to Moyses in mount Sinai when he commanded the children of Israel, that they should offer their oblations to our Lord in the desert of Sinai.";