const char* chap970 = "IN the third year of the reign of Baltassar the king, a vision appeared to me.\n"
	"I^ Daniel saw in my vision, after that which I had seen in the beginning, when I was in Susis the castle, which is in the province of Aelam: and I saw in the vision, that I was over the gate Ulai.\n"
	"& I lifted up mine eyes, and saw: and behold one ram stood before the marish, having high horns, & one higher than another & growing under.\n"
	"Afterward I saw the ram pushing with the horns against the West, & against the North, and against the South: and all beasts could not resist him, nor be delivered out of his hand: and he did according to his will, & was magnified.\n"
	"And I understood: and behold a buckgoat came from the West upon the face of the whole earth, & he touched not the ground. Moreover the buckgoat had a notable horn between his eyes:\n"
	"And he came even to that ram with the horns, which I had seen standing before the gate, & he ran towards him in the violence of his strength.\n"
	"And when he had approached near the ram, he was wood against him, and struck the ram: and he brake his two horns, and the ram could not resist him: and when he had cast him on the ground, he trod him, and no man could deliver the ram out of his hand.\n"
	"And the buckgoat became exceeding great: and when he was grown, the great horn was broken, and there rose up four horns under it by the four winds of heaven.\n"
	"And out of one of them came forth one little horn: and it was made great against the South, and against the East, and against the strength.\n"
	"And it was magnified even unto the strength of heaven: and it threw down of the strength, and of the stars, and trod them.\n"
	"And it was magnified even unto the prince of the strength: and from him it took the continual sacrifice, and threw down the place of his sanctification.\n"
	"And strength was given against the continual sacrifice because of sins: and truth shall be thrown prostrate on the ground, and he shall do, and shall prosper.\n"
	"And I heard one of the saints speaking, & one saint said to another, I know not to whom that spake: How long the vision, and the continual sacrifice, and the sin of the desolation that is made: and the sanctuary, and the strength shall be conculcate?\n"
	"And he said to him: Unto the evening & morning, two thousand three hundred: & the sanctuary shall be cleansed.\n"
	"And it came to pass when I^ Daniel saw the vision, and sought the understanding: behold there stood in my sight as it were the form of a man.\n"
	"And I heard the voice of a man between the banks of Ulai: and he cried, and said: Gabriel make this man understand the vision.\n"
	"And he came and stood near where I stood: and when he was come, trembling I fell on my face, & he said to me: Understand son of man, that in the time of the end the vision shall be accomplished.\n"
	"And when he spake to me I fell flat on the ground: and he touched me, and set me up in my standing,\n"
	"and said to me: I will shew thee what things are to come in the last of the malediction: because the time hath his end.\n"
	"The ram, which thou sawest have horns, is the king of the Medes and Persians.\n"
	"Moreover the buckgoat, is the king of the Graecians, and the great horn, that was between his eyes, the same is the first king.\n"
	"But whereas that being broken, there rose up four for it: four kings shall rise up of his nation, but not in his strength.\n"
	"And after their reign, when iniquities shall be increased, there shall arise a king impudent of face, and understanding propositions.\n"
	"And his strength shall be made strong, but not in his own strength: and more than can be believed, shall he waste all things, and shall prosper, and do. And he shall kill the strong, and the people of the saints\n"
	"according to his will, and craft shall be directed in his hand: and he shall magnify his heart, and in the abundance of all things he shall murder very many: & against the prince of princes shall he arise, & without hand he shall be destroyed.\n"
	"& the vision of the evening and the morning, which hath been said, is true: thou therefore seal the vision, because it shall be after many days.\n"
	"And I^ Daniel languished, and was sick for certain days: and when I was risen up, I did the king's works, and was astonished at the vision, and there was none that could interpret it.";