const char* chap973 = "AND I from the first year of Darius the Mede stood that he might be strengthened, and made strong.\n"
	"And now I will declare the truth unto thee. Behold three kings as yet shall stand in Persia, and the fourth shall be enriched with exceeding riches above all: & when he is grown mighty in his riches, he shall raise up all against the kingdom of Greece.\n"
	"But there shall rise a strong king, and shall rule with much power: and he shall do what shall please him.\n"
	"And when he shall stand, his kingdom shall be broken, and it shall be divided into the four winds of heaven: but not unto his posterity, nor according to his mightiness wherewith he ruled. For his kingdom shall be rent even unto foreigners, beside these.\n"
	"And the king of the South shall be made strong, & there shall of his princes prevail above him, and he shall rule in dominion: for his dominion shall be much.\n"
	"And after the end of years they shall be confederated: and the daughter of the king of the South shall come to the king of the North to make amity, and shall not obtain the strength of the arm, neither shall his seed stand: and she shall be delivered, and they that brought her, her youngmen and they that strengthened her in the times.\n"
	"And there shall stand of the bud of her roots a plant: and he shall come with an army, and shall enter the province of the king of the North: and he shall abuse them, and shall obtain.\n"
	"Moreover also their gods, and sculptiles, the precious vessels also of gold, and silver, he shall carry away captive into Aegypt: he shall prevail against the king of the North.\n"
	"And the king of the South shall enter into the kingdom, and shall return to his own land.\n"
	"And his sons shall be provoked, and they shall gather a multitude of very many hosts: and he shall come hastening, and overflowing: and he shall return and be stirred up, and he shall join battle with his force.\n"
	"And the king of the South being provoked shall go forth, and shall fight against the king of the North, & shall prepare an exceeding great multitude, and a multitude shall be given into his hands.\n"
	"And he shall take a multitude, and his heart shall be exalted, and he shall overthrow many thousands: but he shall not prevail.\n"
	"For the king of the North shall return, and shall prepare a multitude much greater than before: & in the end of times, & years, he shall come hastening with a great host, and riches exceeding much.\n"
	"And in those times many shall rise up against the king of the South, the children also of the prevaricators of thy people shall be extolled to fulfill the vision, and they shall fall.\n"
	"And the king of the North shall come, and shall cast up a mount, and shall take the best fenced cities: & the arms of the South shall not sustain, and his chosen shall rise up to resist, & there shall be no strength.\n"
	"And he shall do coming upon him according to his pleasure, and there shall be none to stand against his face: and he shall stand in a noble land, & it shall be consumed in his hand.\n"
	"And he shall set his face to come to possess all his kingdom, & he shall do right things with him: and he shall give unto him a daughter of women, to overthrow it: and she shall not stand neither shall she be his.\n"
	"And he shall turn his face to the islands, & shall take many: and he shall make the prince of his reproach to cease, and his reproach shall be returned upon him.\n"
	"And he shall turn his face to the empire of his own land, and he shall stumble, and fall, & shall not be found.\n"
	"And there shall stand in his place one most vile, & unworthy of kingly honour: & in few days he shall be destroyed, not in fury nor in battle.\n"
	"And there shall stand in his place one despised, and kingly honour shall not be given him: and he shall come secretly, and shall obtain the kingdom by fraud.\n"
	"And the arms of him that fighteth shall be expugned from before his face, and shall be broken: moreover also the prince of the league.\n"
	"And after the amities, he shall work deceit with him: and he shall go up, and shall overcome with few people.\n"
	"And he shall enter abundant and plentiful cities: & he shall do things that his fathers never did, & his father's fathers: their robberies, and prey, & riches he shall dissipate, and shall devise devices against the best fenced: and this until a time.\n"
	"And his strength & his heart shall be stirred up against the king of the South in a great army: and the king of the South shall be provoked to battle with many aids, and exceeding strong: & they shall not stand because they shall take counsels against him.\n"
	"And they that eat bread with him, shall destroy him, and his army shall be oppressed: & there shall fall slain very many.\n"
	"The heart also of the two kings shall be to evil, and at one table they shall speak lies, and they shall not prosper: because as yet the end unto another time.\n"
	"And he shall return into his land with much riches: and his heart against the holy testament, and he shall prosper and shall return into his own land.\n"
	"At the time appointed he shall return, and he shall come to the South, and the later end shall not be like to the former.\n"
	"And there shall come upon him galleys, and the Romans, and he shall be strucken, and shall return, and shall fret against the testament of the sanctuary, and he shall speed: and shall return, and shall devise against them, that have forsaken the testament of the sanctuary.\n"
	"And of him shall stand arms, and shall pollute the sanctuary of strength, and shall take away the continual sacrifice: and they shall give abomination into desolation.\n"
	"And the impious against the testament shall dissemble fraudulently: but the people that knoweth their God, shall obtain, and shall do.\n"
	"And the learned in the people shall teach very many: and they shall fall by sword, and by flame, and by captivity, and by spoil of days.\n"
	"And when they are fallen, they shall be relieved with a little aid: and very many shall be joined to them feignedly.\n"
	"And of the learned there shall fall, that they may be tried, and may be chosen, and made white even to the time prefixed: because yet there shall be another time.\n"
	"And the king shall do according to his will, and shall be elevated, & magnified against every god: and against the God of gods he shall speak magnifical things, & shall be directed, till the wrath be accomplished: for the determination is made.\n"
	"And the God of his fathers he shall not account of: and he shall be in the concupiscences of women, neither shall he care for any of the gods: because he shall rise up against all things.\n"
	"But god Maozim he shall worship in his place: and the god whom his fathers knew not, he shall worship with gold, and silver, and precious stone, and precious things.\n"
	"And he shall do it to fence Maozim with a strange god, whom he acknowledged, and he shall multiply glory, and shall give them power in many, and shall divide the land gratis.\n"
	"And in the time prefixed shall the king of the South make battle against him, & as a tempest shall the king of the North come against him in chariots, and in horsemen, and in a great navy, and he shall enter the lands, and shall destroy, and pass through.\n"
	"And he shall enter into the glorious land, and many shall fall: but these only shall be saved out of his hand, Edom, and Moab, and the beginning of the children of Ammon.\n"
	"And he shall lay his hand upon the lands: and the Land of Aegypt shall not escape.\n"
	"And he shall rule over the treasures of gold, and of silver, and in all the precious things of Aegypt: through Libya also, and Aethiopia he shall pass.\n"
	"And a bruit shall trouble him from the East, and from the North: and he shall come in a great multitude to destroy and kill very many.\n"
	"And he shall pitch his tabernacle Apadno between the seas, upon a mount glorious and holy: and he shall come even to the top thereof, and no man shall help him.";