const char* chap975 = "AND there was a man dwelling in Babylon, and his name Joakim:\n"
	"& he took a wife named Susanna, the daughter of Helcias exceeding fair, and fearing God.\n"
	"For her parents being just, instructed their daughter according to the law of Moyses.\n"
	"And Joakim was very rich, and he had an orchard near unto his house: and to him the Jews resorted together, because he was the more honorable of all.\n"
	"And there were two ancients appointed judges in that year, of whom our Lord spake: That iniquities came out of Babylon from the senior judges, that seemed to rule the people.\n"
	"These frequented the house of Joakim, and all that had judgements came to them.\n"
	"And when the people returned at noon, Susanna went in, and walked in her husband's orchard.\n"
	"and the ancients saw her daily going in, and walking: and they were inflamed to the concupiscence of her:\n"
	"and they subverted their sense, and declined their eyes that they would not see heaven, nor remember just judgements.\n"
	"They were both therefore wounded with the love of her, neither did they shew their grief one to the other:\n"
	"for they were ashamed to shew one another their concupiscence, being desirous to lie with her:\n"
	"and they watched every day carefully to see her. And one said to the other:\n"
	"Let us go home, because it is the hour of dinner. And going forth they departed one from another.\n"
	"And when they were returned, they came into one place: and asking of each other the cause, they confessed their concupiscence: and then in commune they appointed a time, when they might find her alone.\n"
	"And it came to pass, when they observed a fit day, she went in on a time as yesterday and the day before, with two maids only, & would be washed in the orchard: for it was an hot season.\n"
	"And there was none there, but the two ancients hid, & beholding her.\n"
	"She therefore said to the maids: Fetch me oil, and washing balls, and shut the doors of the orchard, that I may be washed.\n"
	"And they did as she had commanded: and they shut the doors of the orchard, and went out by a back door to fetch the thing that she had commanded; and they knew not that the ancients were hid within.\n"
	"But when the maids were gone forth, the two ancients arose, and ran to her, and said:\n"
	"Lo the doors of the orchard be shut, and no body seeth us, and we are in the concupiscence of thee: wherefore consent to us, and lie with us.\n"
	"and if thou wilt not, we will give testimony against thee, that there was a young man with thee, and for this cause thou didst send out thy maids from thee.\n"
	"Susanna sighed, and said: Perplexities are to me on every side: for if I shall do this, it is death to me: and if I do it not, I shall not escape your hands.\n"
	"But it is better for me without the act to fall into your hands, than to sin in the sight of our Lord.\n"
	"And Susanna cried out with a loud voice: but the ancients also cried out against her.\n"
	"And one ran to the door of the orchard, and opened it.\n"
	"when the servants therefore of the house had heard the cry in the orchard, they rushed in by the back door, to see what it was.\n"
	"And after the ancients spake, the servants were ashamed exceedingly: because never had there been such a word said of Susanna. And the morrow came.\n"
	"And when the people was come to Joakim her husband, the two ancients also came full of unjust cogitation against Susanna, to put her to death.\n"
	"And they said before the people: Send to Susanna daughter of Helcias the wife of Joakim. And forthwith they sent.\n"
	"And she came with her parents, and children, and all her kin.\n"
	"Moreover Susanna was exceeding delicate, and beautiful of face.\n"
	"But those wicked men commanded that she should be uncovered (for she was covered) that so at least they might be satisfied with her beauty.\n"
	"Her friends therefore wept, & all that had known her.\n"
	"But the two ancients rising up in the midst of the people, laid their hands upon her head.\n"
	"Who weeping looked up to heaven, for her heart had confidence in our Lord.\n"
	"And the ancients said: When we walked alone in the orchard, this woman came in with two maids, and shut the doors of the orchard: and she sent away the maids from her.\n"
	"And a young man that was hid came to her, and lay with her.\n"
	"But we being in a corner of the orchard, seeing the iniquity, ran to them, and saw them lie together.\n"
	"And him indeed we could not take, because he was stronger than we, and opening the doors he lept out:\n"
	"but her when we apprehended, we asked what youngman it was, and she would not tell us, of this thing we are witnesses.\n"
	"The multitude believed them as the ancients and the judges of the people, and they condemned her to death.\n"
	"But Susanna cried out with a loud voice, and said: Eternal God, which art the knower of hidden things before they come to pass,\n"
	"thou knowest that they have borne false witness against me: and lo I die, whereas I have done none of these things, which these men have maliciously forged against me.\n"
	"And our Lord heard her voice.\n"
	"and when she was led to death, our Lord raised up the holy spirit of a young boy, whose name was Daniel:\n"
	"and he cried out with a loud voice: I am clean from the blood of this woman.\n"
	"And all the people turning to him, said: What is this word, that thou hast spoken?\n"
	"Who when he stood in the midst of them, said: So foolish ye children of Israel, not judging, nor discerning that which is the truth, have you condemned the daughter of Israel?\n"
	"Return ye to judgement, because they have spoken false testimony against her.\n"
	"The people therefore returned with speed, and the ancients said to him: Come, and sit in the midst of us, and tell us: because God hath given thee the honour of old age.\n"
	"And Daniel said to the people: Separate them far one from another, and I will discover them.\n"
	"When they were therefore divided one from the other, he called one of them, and said to him: O thou inveterated of evil days, now are thy sins come, which thou didst commit before:\n"
	"judging unjust judgements, oppressing innocents, and dismissing offenders, our Lord saying: The innocent and the just thou shalt not kill.\n"
	"Now then if thou sawest her, tell under what tree thou sawest them talking together. Who said: Under a schine tree.\n"
	"And Daniel said: Well hast thou lied against thine own head: for behold the Angel of God taking the sentence of him, shall cut thee in the midst.\n"
	"And removing him away, he commanded that the other should come, and he said to him: Seed of Chanaan, and not of Juda, beauty hath deceived thee, and concupiscence hath subverted thy heart:\n"
	"so did you to the daughters of Israel, and they fearing spake to you: but the daughter of Juda did not abide your iniquity.\n"
	"Now therefore tell me, under what tree thou tookest them speaking one to another. Who said: Under a prine tree.\n"
	"And Daniel said to him: Well hast thou also lied against thine own head: for the Angel of our Lord tarrieth, having a sword, that he may cut thee in the midst, and kill you.\n"
	"Therefore all the assembly cried out with a loud voice, and they blessed God, which saveth them that hope in him.\n"
	"And they rose up against the two elders (for Daniel had convinced them by their own mouth to have given false testimony) and they did to them as they had dealt naughtily against their neighbour,\n"
	"to do according to the law of Moyses: & they killed them, and innocent blood was saved in that day.\n"
	"But Helcias, and his wife praised God, for their daughter Susanna, with Joakim her husband, and all her kin, because there was no unhonest thing found in her.\n"
	"And Daniel became great in the sight of the people from that day, & thence forward.\n"
	"And king Astyages was laid to his fathers, & Cyrus the Persian received his kingdom.";