const char* chap976 = "AND Daniel was the king's guest, and honoured above all his friends.\n"
	"There was also an idol among the Babylonians named Bel: and there were bestowed on him every day of flour twelve arctabaes, and forty sheep, and of wine six great pots.\n"
	"The king also did worship him, and went every day to adore him: But Daniel adored his God. & the king said to him: Why dost thou not adore Bel.\n"
	"Who answering, said to him: Because I worship not idols made with hand, but the living God, that created heaven, and earth, and hath power over all flesh.\n"
	"And the king said to him: Doeth not Bel seem unto thee to be a living God? Seest thou not how much he eateth and drinketh every day?\n"
	"And Daniel smiling said: Be not deceived o king: For this same is within of clay, and without of brass, neither hath he eaten at any time.\n"
	"And the king being wrath called his priests, & said to them: Unless you tell me, who it is that eateth these expenses, you shall die.\n"
	"But if you shew, that Bel eateth these things Daniel shall die, because he hath blasphemed against Bel. And Daniel said to the king: Be it done according to thy word.\n"
	"And the priests of Bel were seventy, beside their wives, and little ones, & children. And the king came with Daniel into the temple of Bel.\n"
	"And the priests of Bel said: Behold we go forth: & thou o king set the meats, & mingle the wine, & shut the door, & seal it with thy ring:\n"
	"and when thou shalt come in the morning, unless thou find all eaten of Bel, dying we will die, or Daniel that hath lied against us.\n"
	"And they contemned, because they had made under the table a secret entrance, & by it they came in always, and devoured those things.\n"
	"It came to pass therefore after they were gone out, the king set the meats before Bel: & Daniel commanded his servants, and they brought ashes, and he sifted them over all the temple before the king: and going forth they shut the door, and sealing it with the king's ring, they departed.\n"
	"But the priests went in by night, according to their custom, and their wives, and their children: and they did eat, and drink all.\n"
	"And the king arose in the first break of day, and Daniel with him.\n"
	"And the king said: Are the seals safe, Daniel? Who answered: Safe o king.\n"
	"And forthwith when he had opened the door, the king looking on the table, cried out with a loud voice: Great art thou o Bel, and there is not any deceit with thee.\n"
	"And Daniel laughed: and he held the king that he should not go in: and he said: Behold the pavement, mark whose steps these are.\n"
	"And the king said: I see the steps of men, & women, and of infants. And the king was angry.\n"
	"Then apprehended he the priests, & their wives, & their children: and they shewed him secret little doors by which they came in, & consumed the things that were on the table.\n"
	"The king therefore slew them, & he delivered Bel into the power of Daniel: who overthrew him, & his temple.\n"
	"And there was a great dragon in that place, & the Babylonians worshipped him.\n"
	"And the king said to Daniel: Lo now thou canst not say, that this same is not a living god: adore him therefore.\n"
	"And Daniel said: The Lord my God I do adore: because he is the living God:\n"
	"but thou o king give me licence, and I will kill the dragon without sword and club. And the king said: I give thee licence.\n"
	"Daniel therefore took pitch, and fat, and hairs, and sod them together: & he made lumps, and gave into the dragon's mouth, & the dragon burst in sunder. And he said: Lo whom you worshipped.\n"
	"Which when the Babylonians had heard, they were wrath exceedingly: and being gathered together against the king, they said: The king is become a Jew. Bel he hath destroyed, the dragon he hath killed, & he hath slain the priests.\n"
	"And they said when they were come to the king: Deliver us Daniel, otherwise we will kill thee, & thy house.\n"
	"The king therefore saw that they pressed upon him vehemently: and compelled by necessity he delivered Daniel to them.\n"
	"Who cast him into the lake of lions, and he was there six days.\n"
	"Moreover in the lake were seven lions, & there were given to them two bodies every day, & two sheep: and they were not given unto them, that they might devour Daniel.\n"
	"And there was Habacuc a prophet in Jewry, & he had boiled broth, & had broken bread in a bowl: and he went into the field, to carry it to the reapers.\n"
	"And the Angel of our Lord said to Habacuc: Carry the dinner which thou hast, into Babylon to Daniel, who is in the lake of lions.\n"
	"And Habacuc said: Lord, Babylon I have not seen, and the lake I know not.\n"
	"And the Angel of our Lord took him by the top of his head, and carried him by the hair of his head, & put him into Babylon over the lake in the force of his spirit.\n"
	"And Habacuc cried, saying: Daniel, take the dinner that God hath sent to thee.\n"
	"And Daniel said: Thou hast remembered me o God, and hast not forsaken them that love thee.\n"
	"And Daniel rising up did eat. Moreover the Angel of our Lord restored Habacuc forthwith in his place.\n"
	"The king therefore came the seventh day to lament Daniel: and he came to the lake, and looked in, and behold Daniel sitting in the midst of the lions.\n"
	"And the king cried out with a loud voice, saying: Great art thou o Lord the God of Daniel. And he drew him out of the lake of lions.\n"
	"But those that had been the cause of his perdition, he cast into the lake, and they were devoured in a moment before him.\n"
	"Then the king said: Let all inhabitants in the whole earth fear the God of Daniel: because he is the Saviour, doing signs, & marvels in the earth: who hath delivered Daniel out of the lions' den.";