const char* chap978 = "Say ye to your brethren: My people: and to your sister, She that hath obtained mercy.\n"
	"Judge your mother, judge ye: because she not my wife, and I not her husband. Let her take away fornications from her face, and her adulteries from the midst of her breasts.\n"
	"Lest perhaps I strip her naked, and set her according to the day of her nativity: and I will lay her as a wilderness, and will set her as a land unpassable, and will kill her with drought.\n"
	"And I will not have mercy on her children: because they are the children of fornications:\n"
	"because their mother hath fornicated, she is confounded that conceived them: because she said: I will go after my lovers, that give me my breads, & my waters, my wool, and my flax, mine oil, & my drink.\n"
	"For this behold I will hedge thy way with thorns, and I will hedge it with a wall, & she shall not find her paths.\n"
	"And she shall follow her lovers, and shall not overtake them: and she shall seek them, and shall not find, and she shall say: I will go, and will return to my former husband: because it was well with me then, more than now.\n"
	"And she did not know that I gave her corn, and wine, and oil, and multiplied silver unto her, & gold, which they have made to Baal.\n"
	"Therefore will I return, and will take my corn in his time, and my wine in his time, and I will deliver my wool, and my flax, which covered her ignominy.\n"
	"And now I will reveal her folly in the eyes of her lovers: and there shall not a man deliver her out of my hand:\n"
	"and I will make all her joy to cease, her solemnity, her new-moon, her sabbath, & all her festival times.\n"
	"And I will destroy her vine, and her figtree, of which she said: These are my rewards, which my lovers have given me: and I will lay her as a forest, & the beast of the field shall eat her.\n"
	"And I will visit upon her the days of Baalim, to whom she burnt incense, and was adorned with her earlet, and with her tablet, & went after her lovers, & forgot me, saith our Lord.\n"
	"For this, lo I will allure her, and will lead her into the wilderness: and I will speak to her heart.\n"
	"And I will give her dressers of vines out of the same place, and the vale of Achor to open hope: and she shall sing there according to the days of her youth, and according to the days of her ascending out of the Land of Aegypt.\n"
	"And it shall be in that day, saith our Lord: She shall call me: My husband, and she shall call me no more, Baalim.\n"
	"And I will take away the names of Baalim out of her mouth, and she shall no more remember their name.\n"
	"And I will make with them a league in that day, with the beast of the field, and with the fowl of the heaven, and with that, which creepeth on the earth: and bow, and sword, and battle I will destroy out of the earth: and will make them sleep confidently.\n"
	"And I will despouse thee to me for ever: and I will despouse thee to me in justice, and judgement, and in mercy, and in commiserations.\n"
	"And I will despouse thee to me in faith: and thou shalt know that I am the Lord.\n"
	"And it shall be in that day: I will hear, saith our Lord, I will hear the heavens, and they shall hear the earth.\n"
	"And the earth shall hear wheat, and wine, and oil: and these shall hear Jezrahel.\n"
	"And I will sow her unto me into the earth, and I will have mercy on her, that was without mercy.\n"
	"And I will say to Not my people: My people art thou: and it shall say: Thou art my God.";