const char* chap98 = "And Our Lord spake to Moyses, saying:\n"
	"Take Aaron with his sons, their vestments, and the oil of unction, a calf for sin, two Rams, a basket with azymes,\n"
	"and thou shalt gather all the assembly to the door of the tabernacle.\n"
	"And Moyses did as our Lord had commanded. And all the multitude being gathered before the door of the tabernacle,\n"
	"he said: This is the word, that our Lord hath commanded to be done.\n"
	"And immediately he offered Aaron & his sons: and when he had washed them,\n"
	"he revested the high-Priest with the strait linen garment, girding him with a bawdrike, & revesting him with the tunic of hyacinth, and over it he put the Ephod,\n"
	"which he straitening with the girdle, fitted it to the Rationale, wherein was Doctrine and Verity.\n"
	"with the mitre also he covered his head: and upon it, against the forehead, he put the plate of gold consecrated in sanctification, as our Lord had commanded him.\n"
	"He took also the oil of unction, wherewith he anointed the tabernacle, with all the furniture thereof.\n"
	"And sanctifying them, and having sprinkled the altar seven times, he anointed it, and all the vessels thereof, and the laver with the foot thereof he sanctified with the oil.\n"
	"The which pouring upon Aaron's head, he anointed, & consecrated him:\n"
	"his sons also after he had offered them, he revested with linen tunics and girded them with bawdrikes, and put mitres on them, as our Lord had commanded.\n"
	"He offered also the calf for sin: and when Aaron and his sons had put their hands upon the head thereof,\n"
	"he did immolate it: drawing the blood, & dipping his finger, touched the horns of the altar round about. Which being expiated, and sanctified, he poured the rest of the blood at the bottom thereof.\n"
	"But the fat that was upon the entrails, and the caul of the liver, & the two little kidneys, with their little tallow he burnt upon the altar:\n"
	"the calf with the skin, and the flesh, and the dung, he burnt without the camp, as our Lord had commanded.\n"
	"He offered also a ram for an holocaust: upon the head whereof when Aaron and his sons had put their hands,\n"
	"he did immolate it, and poured the blood thereof in the circuit of the altar.\n"
	"And cutting the ram itself into pieces, the head thereof, and the joints, and the fat he burnt with fire,\n"
	"having first washed the entrails, & the feet, & the whole ram together he burnt upon the altar, because it was an holocaust of most sweet odour to our Lord, as he had commanded him.\n"
	"He offered also the second ram, for the consecration of Priests: and Aaron and his sons did put their hands upon the head thereof:\n"
	"which when Moyses had immolated, taking of the blood thereof, he touched the tip of Aaron's right ear, and the thumb of his right hand, in like manner also of his foot.\n"
	"He offered also the sons of Aaron: and when of the blood of the ram, being immolated, he had touched the tip of the right ear of every one, and the thumbs of the right hand and foot, the rest he poured on the altar, round about:\n"
	"but the fat, and the rump, and all the fat that covereth the entrails, and the caul of the liver, and the two kidneys with their fat, and with the right shoulder, he separated.\n"
	"And taking out of the basket of azymes, which was before our Lord, a loaf without leaven, and a manchet tempered with oil, and a wafer, he put them upon the fat, and the right shoulder,\n"
	"delivering all to Aaron, and to his sons, Who having lifted them up before our Lord,\n"
	"he took them again of their hands, and burnt them upon the altar of holocaust, because it was the oblation of consecration, for a sweet odour, of the sacrifice to our Lord.\n"
	"And he took of the ram of consecration, the breast for his portion, elevating it before our Lord, as our Lord had commanded him.\n"
	"And taking the ointment, and the blood that was upon the altar, he sprinkled it upon Aaron, and his vestments, & upon his sons and their vestments.\n"
	"And when he had sanctified them in their vestments, he commanded them, saying: Boil the flesh before the door of the tabernacle, and there eat it. Eat ye also the loaves of consecration, that are laid in the basket, as our Lord commanded me, saying: Aaron and his sons shall eat them:\n"
	"and whatsoever shall be left of the flesh, and the loaves, fire shall consume.\n"
	"Out of the door also of the tabernacle you shall not go forth seven days, until the day wherein the time of your consecration shall be expired, for in seven days the consecration is finished:\n"
	"as at this present it hath been done, that the rite of the sacrifice might be accomplished.\n"
	"Day & night shall you tarry in the tabernacle observing the watches of our Lord, lest you die: for so it hath been commanded me.\n"
	"And Aaron, and his sons did all things which our Lord spake by the hand of Moyses.";