const char* chap99 = "And when the eighth day was come, Moyses called Aaron and his sons, and the ancients of Israel, and said to Aaron.\n"
	"Take of the herd a calf for sin, and a ram for an holocaust, both without spot, and offer them before our Lord.\n"
	"And to the children of Israel thou shalt speak: Take ye a buck goat for sin, and a calf, and a lamb, of a year old, & without spot for an holocaust,\n"
	"an ox and a ram for pacifics: and immolate them before our Lord, offering in the sacrifice of every one flour tempered with oil; for today our Lord will appear to you.\n"
	"They took therefore all things that Moyses had commanded before the door of the tabernacle: where when all the multitude stood,\n"
	"Moyses said: This is the word, which our Lord hath commanded: do it, and his glory will appear to you.\n"
	"And he said to Aaron: Approach to the altar, & immolate for thy sin: offer the holocaust, and pray for thyself and for the people, and when thou hast slain the people's host, pray for them, as our Lord hath commanded.\n"
	"And forthwith Aaron approaching to the altar, immolated the calf for his sin:\n"
	"the blood whereof his sons brought to him: wherein dipping his finger, he touched the horns of the altar, and poured the rest at the foot thereof.\n"
	"And the fat, and the little kidneys, and the caul of the liver, which are for sin, he burnt upon the altar, as our Lord had commanded Moyses:\n"
	"but the flesh and skin thereof he burnt with fire without the camp.\n"
	"He immolated also the victim of holocaust: and his sons brought him the blood thereof, which he poured in the circuit of the altar.\n"
	"The host also it-self being cut into pieces, they brought with the head and every member. All which he burnt with fire upon the altar,\n"
	"having first washed the entrails and the feet with water.\n"
	"And offering for the sin of the people, he slew the buck goat: and expiating the altar:\n"
	"he made the holocaust,\n"
	"adding in the sacrifice the libaments, which are offered withal, and burning them upon the altar, beside the ceremonies of the morning holocaust.\n"
	"He immolated also the ox, and the ram, the pacific hosts of the people: and his sons brought him the blood, which he poured upon the altar round about.\n"
	"The fat also of the ox, and the rump of the ram, and the two little kidneys with their fat, and the caul of the liver,\n"
	"they put upon the breasts, & after the fat was burnt upon the altar,\n"
	"their breasts, & the right shoulders, Aaron did separate, elevating them before our Lord, as Moyses had commanded.\n"
	"And stretching forth his hand to the people, he blessed them. And so the hosts for sin, and the holocausts, and the pacifics being finished, he descended.\n"
	"And Moyses and Aaron going into the tabernacle of testimony, & afterward coming forth, blessed the people. And the glory of our Lord appeared to all the multitude:\n"
	"& behold a fire coming forth from our Lord, devoured the holocaust, and the fat that was upon the altar: Which thing, when the multitude had seen, they praised our Lord, falling on their faces.";