const char* chap993 = "Because lo in those days, and in that time when I shall convert the captivity of Juda, & Jerusalem,\n"
	"I will gather together all Nations, and will lead them into the valley of Josaphat: and I will plead with them there upon my people, and mine inheritance Israel, whom they have dispersed in the nations, and have divided my land.\n"
	"And upon my people they have cast lot: & boy they have given to be a strumpet, and wench they have sold for wine, that they might drink.\n"
	"But what is to me and to you o Tyre, and Sidon, and all the border of the Palesthines? What, will you render me revenge, and if you do revenge against me, I will soon render you quickly recompense upon your head.\n"
	"For my silver, and my gold you have taken: and my desirable things, and most beautiful you have carried into your temples.\n"
	"And the children of Jerusalem you have sold to the children of the Greeks, that you might make them far off from their coasts.\n"
	"Behold I will raise them up out of the place, wherein you have sold them: and I will turn your retribution upon your own head.\n"
	"And I will sell your sons and your daughters into the hands of the children of Juda, and they shall sell them to the Sabaeans, a nation far off, because our Lord hath spoken.\n"
	"Proclaim ye this in the Gentiles: sanctify battle, raise up the strong: let them come, let all the men of war come up.\n"
	"Cut your ploughs into swords, and your spades into spears. Let the weak say: That I am strong.\n"
	"Break out, and come all ye nations from round about, and be gathered together: there will our Lord make all thy strong ones to be slain.\n"
	"Let them arise, & let the Gentiles ascend into the valley of Josaphat: because there I will sit, to judge all nations round about.\n"
	"Put in the sithes, because the harvest is ripe: come, and descend, because the press is full, the presses run over: because their malice is multiplied.\n"
	"Peoples^ peoples in the valley of concision, because the day of our Lord is nigh in the valley of concision.\n"
	"The sun and the moon are darkened, & the stars have withdrawn their shining.\n"
	"And our Lord will roar out of Sion, and out of Jerusalem he will give his voice: and the heavens, and the earth shall be moved, and our Lord the hope of his people, and the strength of the children of Israel.\n"
	"And you shall know that I am the Lord your God dwelling in Sion my holy mount: and Jerusalem shall be holy, and strangers shall pass through it no more.\n"
	"And it shall be in that day: the mountains shall distill sweetness, and the hills shall flow with milk: and through all the rivers of Juda shall run waters: and a fountain shall issue out of the house of the Lord, and shall water the torrent of thorns.\n"
	"Aegypt shall be into desolation, & Idumea into a desert of perdition, for that they have done unjustly against the children of Juda, and have shed innocent blood in their land.\n"
	"And Jewry shall be inhabited for ever, and Jerusalem unto generation and generation.\n"
	"And I will cleanse their blood, which I had not cleansed: and the Lord will dwell in Sion.";